use crate::{
    game::{
        Game,
        board::{Board, Position},
        lines::LINES,
    },
    player::PlayerColor,
};
use std::{
    fs::File,
    io::{self, Write as _},
    sync::LazyLock,
};

pub const STENCIL_SIZE: usize = 6;

pub const COEFFS_FILE: &str = match STENCIL_SIZE {
    6 => "./coeffs/incdec6.rs",
    7 => "./coeffs/omnisearch7.rs",
    _ => unreachable!(),
};
pub static INITIAL_COEFFS: LazyLock<Coeffs> = LazyLock::new(|| match STENCIL_SIZE {
    // include! needs a literal, so we can't give it COEFFS_FILE
    6 => include!("../../coeffs/incdec6.rs"),
    7 => include!("../../coeffs/omnisearch7.rs"),
    _ => unreachable!(),
});

// TODO: compute dynamically
pub const UNIQUE_STENCIL_INDICES: usize = match STENCIL_SIZE {
    6 => 182,
    7 => 560,
    _ => unreachable!(),
};

// Generated by scripts/unique_coeffs.py
// TODO: test indices are correctly symmetrized
// TODO: benchmark const vs static
pub static STENCIL_INDICES: [usize; UNIQUE_STENCIL_INDICES] = [
    1, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 82, 83, 84, 85, 86, 88, 89, 91, 92, 93, 94,
    95, 96, 97, 98, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 112, 113, 115, 116, 118, 119,
    120, 121, 122, 123, 124, 125, 127, 128, 129, 130, 131, 133, 134, 136, 137, 139, 140, 142, 143,
    145, 146, 148, 149, 151, 152, 154, 155, 156, 157, 158, 160, 161, 244, 247, 248, 250, 251, 253,
    254, 256, 257, 259, 260, 262, 263, 265, 266, 268, 269, 274, 275, 277, 278, 280, 281, 283, 284,
    286, 287, 289, 292, 293, 295, 296, 301, 302, 304, 305, 310, 311, 313, 314, 316, 319, 320, 322,
    323, 328, 329, 331, 337, 338, 340, 341, 346, 347, 349, 350, 356, 358, 364, 365, 367, 368, 373,
    374, 376, 383, 385, 392, 394, 400, 401, 403, 412, 419, 421, 428, 430, 446, 448, 457, 484,
];
pub static STENCIL_INDICES_SYM: [usize; UNIQUE_STENCIL_INDICES] = [
    243, 81, 324, 567, 27, 270, 513, 108, 351, 594, 189, 432, 675, 252, 495, 90, 333, 576, 171,
    414, 657, 36, 279, 522, 117, 360, 603, 198, 441, 684, 306, 549, 144, 387, 630, 225, 468, 711,
    246, 489, 84, 327, 570, 408, 651, 273, 516, 111, 354, 597, 192, 435, 678, 300, 543, 138, 381,
    624, 219, 462, 705, 255, 498, 336, 579, 417, 660, 282, 525, 120, 363, 606, 201, 444, 687, 309,
    552, 147, 390, 633, 471, 714, 264, 507, 345, 588, 426, 669, 291, 534, 372, 615, 453, 696, 318,
    561, 156, 399, 642, 480, 723, 244, 325, 568, 406, 649, 271, 514, 352, 595, 433, 676, 298, 541,
    379, 622, 460, 703, 334, 577, 415, 658, 280, 523, 361, 604, 442, 685, 307, 388, 631, 469, 712,
    343, 586, 424, 667, 370, 613, 451, 694, 316, 397, 640, 478, 721, 328, 571, 409, 355, 598, 436,
    679, 382, 625, 463, 706, 580, 418, 364, 607, 445, 688, 391, 634, 472, 589, 427, 616, 454, 400,
    643, 481, 412, 601, 439, 628, 466, 610, 448, 475, 484,
];
pub static STENCIL_INDICES_OPP: [usize; UNIQUE_STENCIL_INDICES] = [
    2, 6, 8, 7, 18, 20, 19, 24, 26, 25, 21, 23, 22, 56, 55, 60, 62, 61, 57, 59, 58, 72, 74, 73, 78,
    80, 79, 75, 77, 76, 65, 64, 69, 71, 70, 66, 68, 67, 164, 163, 168, 170, 169, 167, 166, 182,
    181, 186, 188, 187, 183, 185, 184, 173, 172, 177, 179, 178, 174, 176, 175, 218, 217, 224, 223,
    221, 220, 236, 235, 240, 242, 241, 237, 239, 238, 227, 226, 231, 233, 232, 230, 229, 191, 190,
    197, 196, 194, 193, 209, 208, 215, 214, 212, 211, 200, 199, 204, 206, 205, 203, 202, 488, 494,
    493, 491, 490, 506, 505, 512, 511, 509, 508, 497, 496, 503, 502, 500, 499, 548, 547, 545, 544,
    560, 559, 566, 565, 563, 562, 551, 557, 556, 554, 553, 521, 520, 518, 517, 539, 538, 536, 535,
    524, 530, 529, 527, 526, 656, 655, 653, 674, 673, 671, 670, 665, 664, 662, 661, 709, 707, 728,
    727, 725, 724, 719, 718, 716, 682, 680, 700, 698, 692, 691, 689, 572, 592, 590, 583, 581, 646,
    644, 635, 608,
];
pub static STENCIL_INDICES_SYM_OPP: [usize; UNIQUE_STENCIL_INDICES] = [
    486, 162, 648, 405, 54, 540, 297, 216, 702, 459, 135, 621, 378, 504, 261, 180, 666, 423, 99,
    585, 342, 72, 558, 315, 234, 720, 477, 153, 639, 396, 531, 288, 207, 693, 450, 126, 612, 369,
    492, 249, 168, 654, 411, 573, 330, 546, 303, 222, 708, 465, 141, 627, 384, 519, 276, 195, 681,
    438, 114, 600, 357, 510, 267, 672, 429, 591, 348, 564, 321, 240, 726, 483, 159, 645, 402, 537,
    294, 213, 699, 456, 618, 375, 501, 258, 663, 420, 582, 339, 555, 312, 717, 474, 636, 393, 528,
    285, 204, 690, 447, 609, 366, 488, 650, 407, 569, 326, 542, 299, 704, 461, 623, 380, 515, 272,
    677, 434, 596, 353, 668, 425, 587, 344, 560, 317, 722, 479, 641, 398, 533, 695, 452, 614, 371,
    659, 416, 578, 335, 713, 470, 632, 389, 524, 686, 443, 605, 362, 656, 413, 575, 710, 467, 629,
    386, 683, 440, 602, 359, 431, 593, 728, 485, 647, 404, 701, 458, 620, 422, 584, 476, 638, 692,
    449, 611, 572, 464, 626, 437, 599, 482, 644, 617, 608,
];

pub const N_STENCIL_COEFFS: usize = 3usize.pow(STENCIL_SIZE as u32);
pub const N_COEFFS: usize = N_STENCIL_COEFFS + 9;
pub type Coeffs = Box<[i64]>;

static STENCIL_INDEX_MAPPING: [usize; 1 << (2 * STENCIL_SIZE)] = {
    let mut res = [usize::MAX; 1 << (2 * STENCIL_SIZE)];
    let mut base4 = 0;
    while base4 < res.len() {
        let mut n = base4;
        let mut base3 = 0;
        let mut is_valid = true;
        while n > 0 {
            let bits = n & 0b11;
            if bits == 0 {
                is_valid = false;
                break;
            }
            base3 = 3 * base3 + bits - 1;
            n >>= 2;
        }
        if is_valid {
            res[base4] = base3;
        }
        base4 += 1;
    }
    res
};

pub fn coeffistic(game: &Game, coeffs: Option<&Coeffs>) -> i64 {
    let mut h = 0;
    let mut black_capture_threats = 0;
    let mut white_capture_threats = 0;
    let coeffs = coeffs.unwrap();

    for line in LINES {
        h += evaluate_patterns(
            &game.board,
            line,
            coeffs,
            &mut black_capture_threats,
            &mut white_capture_threats,
        );
    }

    h += capture_heuristic(coeffs, game.black_captures as i64, black_capture_threats);
    h -= capture_heuristic(coeffs, game.white_captures as i64, white_capture_threats);

    h
}

const fn capture_heuristic(coeffs: &Coeffs, c: i64, t: i64) -> i64 {
    let i = N_STENCIL_COEFFS;
    let h_captures = coeffs[i] * c * c * c + coeffs[i + 1] * c * c + coeffs[i + 2] * c;
    let h_threats = coeffs[i + 3] * t * t * t + coeffs[i + 4] * t * t + coeffs[i + 5] * t;
    let cross_terms = c * t * (coeffs[i + 6] + coeffs[i + 7] * c + coeffs[i + 8] * t);
    h_captures + h_threats + cross_terms
}

fn evaluate_patterns(
    board: &Board,
    line: &[Position],
    coeffs: &Coeffs,
    black_capture_threats: &mut i64,
    white_capture_threats: &mut i64,
) -> i64 {
    const MASK: usize = (1 << (STENCIL_SIZE * 2 - 2)) - 1;

    let mut stencil = 0;
    let mut h = 0;

    for (i, &(x, y)) in line.iter().enumerate() {
        let player_color = board[y][x];
        let new_bits = match player_color {
            None => 0b01,
            Some(PlayerColor::Black) => 0b10,
            Some(PlayerColor::White) => 0b11,
        };
        stencil = ((stencil & MASK) << 2) | new_bits;

        match stencil & 255 {
            0b_11_10_10_01 | 0b_01_10_10_11 => *white_capture_threats += 1,
            0b_10_11_11_01 | 0b_01_11_11_10 => *black_capture_threats += 1,
            _ => {}
        }

        if i >= STENCIL_SIZE - 1 {
            h += coeffs[STENCIL_INDEX_MAPPING[stencil]];
        }
    }

    h
}

pub fn write_coeffs(coeffs: &[i64]) -> io::Result<()> {
    const CAPACITY: usize = match STENCIL_SIZE {
        6 => 1 << 15,
        7 => 1 << 17,
        _ => unreachable!(),
    };

    let mut buf = io::BufWriter::with_capacity(CAPACITY, Vec::new());
    writeln!(buf, "vec![")?;

    for i in 0..N_STENCIL_COEFFS {
        let c = coeffs[i];
        // TODO: check correct direction (might be symmetric)
        let pat: String =
            (0..STENCIL_SIZE).map(|j| ['.', 'b', 'w'][i / 3usize.pow(j as u32) % 3]).collect();
        let num = format!("{c},");
        writeln!(buf, "    {num:7}// {pat}")?;
    }

    for (i, poly_coeff) in
        ["ccc", "cc", "c", "ttt", "tt", "t", "ct", "cct", "ctt"].iter().enumerate()
    {
        let c = coeffs[N_STENCIL_COEFFS + i];
        let num = format!("{c},");
        writeln!(buf, "    {num:7}// {poly_coeff}")?;
    }

    writeln!(buf, "].into_boxed_slice()")?;

    let mut file = File::create(COEFFS_FILE)?;
    file.write_all(buf.buffer())
}
