[package]
name = "gomoku"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = { version = "0.19.0", default-features = false }
nannou_egui = { version = "0.19.0", default-features = false }
once_cell = "1.19.0"
rand = "0.8.5"

[profile.dev]
debug = false # set to true when crashes occur
