vec![
    0,     // .......
    5,     // b......
    -5,    // w......
    -33,   // .b.....
    49,    // bb.....
    52,    // wb.....
    33,    // .w.....
    -52,   // bw.....
    -49,   // ww.....
    57,    // ..b....
    40,    // b.b....
    20,    // w.b....
    -139,  // .bb....
    155,   // bbb....
    -162,  // wbb....
    -61,   // .wb....
    -78,   // bwb....
    52,    // wwb....
    -57,   // ..w....
    -20,   // b.w....
    -40,   // w.w....
    61,    // .bw....
    -52,   // bbw....
    78,    // wbw....
    139,   // .ww....
    162,   // bww....
    -155,  // www....
    -31,   // ...b...
    -56,   // b..b...
    -83,   // w..b...
    32,    // .b.b...
    110,   // bb.b...
    -73,   // wb.b...
    -40,   // .w.b...
    -166,  // bw.b...
    -200,  // ww.b...
    -29,   // ..bb...
    -37,   // b.bb...
    -39,   // w.bb...
    40,    // .bbb...
    337,   // bbbb...
    -62,   // wbbb...
    -69,   // .wbb...
    -14,   // bwbb...
    117,   // wwbb...
    53,    // ..wb...
    13,    // b.wb...
    42,    // w.wb...
    -19,   // .bwb...
    -32,   // bbwb...
    -20,   // wbwb...
    -11,   // .wwb...
    -21,   // bwwb...
    121,   // wwwb...
    31,    // ...w...
    83,    // b..w...
    56,    // w..w...
    40,    // .b.w...
    200,   // bb.w...
    166,   // wb.w...
    -32,   // .w.w...
    73,    // bw.w...
    -110,  // ww.w...
    -53,   // ..bw...
    -42,   // b.bw...
    -13,   // w.bw...
    11,    // .bbw...
    -121,  // bbbw...
    21,    // wbbw...
    19,    // .wbw...
    20,    // bwbw...
    32,    // wwbw...
    29,    // ..ww...
    39,    // b.ww...
    37,    // w.ww...
    69,    // .bww...
    -117,  // bbww...
    14,    // wbww...
    -40,   // .www...
    62,    // bwww...
    -337,  // wwww...
    57,    // ....b..
    19,    // b...b..
    64,    // w...b..
    -97,   // .b..b..
    164,   // bb..b..
    -9,    // wb..b..
    -43,   // .w..b..
    6,     // bw..b..
    -48,   // ww..b..
    -54,   // ..b.b..
    55,    // b.b.b..
    -12,   // w.b.b..
    99,    // .bb.b..
    132,   // bbb.b..
    84,    // wbb.b..
    64,    // .wb.b..
    -148,  // bwb.b..
    30,    // wwb.b..
    0,     // ..w.b..
    -1,    // b.w.b..
    -74,   // w.w.b..
    120,   // .bw.b..
    55,    // bbw.b..
    -43,   // wbw.b..
    169,   // .ww.b..
    5,     // bww.b..
    24,    // www.b..
    -29,   // ...bb..
    90,    // b..bb..
    -6,    // w..bb..
    -176,  // .b.bb..
    91,    // bb.bb..
    139,   // wb.bb..
    -92,   // .w.bb..
    -134,  // bw.bb..
    59,    // ww.bb..
    72,    // ..bbb..
    140,   // b.bbb..
    -55,   // w.bbb..
    299,   // .bbbb..
    -43,   // bbbbb..
    -16,   // wbbbb..
    -219,  // .wbbb..
    -97,   // bwbbb..
    -7,    // wwbbb..
    74,    // ..wbb..
    -170,  // b.wbb..
    -162,  // w.wbb..
    -178,  // .bwbb..
    91,    // bbwbb..
    102,   // wbwbb..
    -48,   // .wwbb..
    78,    // bwwbb..
    -59,   // wwwbb..
    -53,   // ...wb..
    3,     // b..wb..
    -56,   // w..wb..
    -16,   // .b.wb..
    -54,   // bb.wb..
    -23,   // wb.wb..
    -10,   // .w.wb..
    139,   // bw.wb..
    -127,  // ww.wb..
    52,    // ..bwb..
    64,    // b.bwb..
    -51,   // w.bwb..
    -22,   // .bbwb..
    -128,  // bbbwb..
    -9,    // wbbwb..
    -85,   // .wbwb..
    22,    // bwbwb..
    -73,   // wwbwb..
    -74,   // ..wwb..
    -49,   // b.wwb..
    61,    // w.wwb..
    76,    // .bwwb..
    134,   // bbwwb..
    12,    // wbwwb..
    -162,  // .wwwb..
    -56,   // bwwwb..
    -10,   // wwwwb..
    -57,   // ....w..
    -64,   // b...w..
    -19,   // w...w..
    43,    // .b..w..
    48,    // bb..w..
    -6,    // wb..w..
    97,    // .w..w..
    9,     // bw..w..
    -164,  // ww..w..
    0,     // ..b.w..
    74,    // b.b.w..
    1,     // w.b.w..
    -169,  // .bb.w..
    -24,   // bbb.w..
    -5,    // wbb.w..
    -120,  // .wb.w..
    43,    // bwb.w..
    -55,   // wwb.w..
    54,    // ..w.w..
    12,    // b.w.w..
    -55,   // w.w.w..
    -64,   // .bw.w..
    -30,   // bbw.w..
    148,   // wbw.w..
    -99,   // .ww.w..
    -84,   // bww.w..
    -132,  // www.w..
    53,    // ...bw..
    56,    // b..bw..
    -3,    // w..bw..
    10,    // .b.bw..
    127,   // bb.bw..
    -139,  // wb.bw..
    16,    // .w.bw..
    23,    // bw.bw..
    54,    // ww.bw..
    74,    // ..bbw..
    -61,   // b.bbw..
    49,    // w.bbw..
    162,   // .bbbw..
    10,    // bbbbw..
    56,    // wbbbw..
    -76,   // .wbbw..
    -12,   // bwbbw..
    -134,  // wwbbw..
    -52,   // ..wbw..
    51,    // b.wbw..
    -64,   // w.wbw..
    85,    // .bwbw..
    73,    // bbwbw..
    -22,   // wbwbw..
    22,    // .wwbw..
    9,     // bwwbw..
    128,   // wwwbw..
    29,    // ...ww..
    6,     // b..ww..
    -90,   // w..ww..
    92,    // .b.ww..
    -59,   // bb.ww..
    134,   // wb.ww..
    176,   // .w.ww..
    -139,  // bw.ww..
    -91,   // ww.ww..
    -74,   // ..bww..
    162,   // b.bww..
    170,   // w.bww..
    48,    // .bbww..
    59,    // bbbww..
    -78,   // wbbww..
    178,   // .wbww..
    -102,  // bwbww..
    -91,   // wwbww..
    -72,   // ..www..
    55,    // b.www..
    -140,  // w.www..
    219,   // .bwww..
    7,     // bbwww..
    97,    // wbwww..
    -299,  // .wwww..
    16,    // bwwww..
    43,    // wwwww..
    -33,   // .....b.
    -177,  // b....b.
    86,    // w....b.
    20,    // .b...b.
    -83,   // bb...b.
    37,    // wb...b.
    0,     // .w...b.
    -39,   // bw...b.
    36,    // ww...b.
    -97,   // ..b..b.
    1,     // b.b..b.
    -1,    // w.b..b.
    30,    // .bb..b.
    22,    // bbb..b.
    70,    // wbb..b.
    -32,   // .wb..b.
    -140,  // bwb..b.
    -70,   // wwb..b.
    43,    // ..w..b.
    22,    // b.w..b.
    26,    // w.w..b.
    14,    // .bw..b.
    27,    // bbw..b.
    68,    // wbw..b.
    16,    // .ww..b.
    37,    // bww..b.
    54,    // www..b.
    32,    // ...b.b.
    -48,   // b..b.b.
    -142,  // w..b.b.
    -36,   // .b.b.b.
    2,     // bb.b.b.
    -81,   // wb.b.b.
    -64,   // .w.b.b.
    33,    // bw.b.b.
    -81,   // ww.b.b.
    -176,  // ..bb.b.
    57,    // b.bb.b.
    37,    // w.bb.b.
    106,   // .bbb.b.
    47,    // bbbb.b.
    175,   // wbbb.b.
    21,    // .wbb.b.
    -37,   // bwbb.b.
    -105,  // wwbb.b.
    10,    // ..wb.b.
    14,    // b.wb.b.
    23,    // w.wb.b.
    -19,   // .bwb.b.
    -12,   // bbwb.b.
    -74,   // wbwb.b.
    60,    // .wwb.b.
    -85,   // bwwb.b.
    -62,   // wwwb.b.
    40,    // ...w.b.
    12,    // b..w.b.
    89,    // w..w.b.
    58,    // .b.w.b.
    29,    // bb.w.b.
    -118,  // wb.w.b.
    64,    // .w.w.b.
    84,    // bw.w.b.
    57,    // ww.w.b.
    -16,   // ..bw.b.
    -39,   // b.bw.b.
    -62,   // w.bw.b.
    20,    // .bbw.b.
    19,    // bbbw.b.
    2,     // wbbw.b.
    83,    // .wbw.b.
    -217,  // bwbw.b.
    -153,  // wwbw.b.
    92,    // ..ww.b.
    -15,   // b.ww.b.
    -29,   // w.ww.b.
    38,    // .bww.b.
    -58,   // bbww.b.
    -67,   // wbww.b.
    -7,    // .www.b.
    58,    // bwww.b.
    -195,  // wwww.b.
    -139,  // ....bb.
    -161,  // b...bb.
    -43,   // w...bb.
    30,    // .b..bb.
    64,    // bb..bb.
    10,    // wb..bb.
    -16,   // .w..bb.
    -28,   // bw..bb.
    -81,   // ww..bb.
    99,    // ..b.bb.
    114,   // b.b.bb.
    37,    // w.b.bb.
    212,   // .bb.bb.
    -69,   // bbb.bb.
    75,    // wbb.bb.
    107,   // .wb.bb.
    82,    // bwb.bb.
    -2,    // wwb.bb.
    -169,  // ..w.bb.
    -187,  // b.w.bb.
    48,    // w.w.bb.
    -24,   // .bw.bb.
    -25,   // bbw.bb.
    13,    // wbw.bb.
    0,     // .ww.bb.
    76,    // bww.bb.
    -20,   // www.bb.
    40,    // ...bbb.
    -65,   // b..bbb.
    -14,   // w..bbb.
    106,   // .b.bbb.
    -105,  // bb.bbb.
    -91,   // wb.bbb.
    7,     // .w.bbb.
    -185,  // bw.bbb.
    -45,   // ww.bbb.
    299,   // ..bbbb.
    46,    // b.bbbb.
    97,    // w.bbbb.
    68,    // .bbbbb.
    112,   // bbbbbb.
    -109,  // wbbbbb.
    36,    // .wbbbb.
    118,   // bwbbbb.
    -18,   // wwbbbb.
    162,   // ..wbbb.
    -35,   // b.wbbb.
    41,    // w.wbbb.
    -1,    // .bwbbb.
    -102,  // bbwbbb.
    -224,  // wbwbbb.
    34,    // .wwbbb.
    -29,   // bwwbbb.
    110,   // wwwbbb.
    11,    // ...wbb.
    57,    // b..wbb.
    -91,   // w..wbb.
    20,    // .b.wbb.
    -59,   // bb.wbb.
    -70,   // wb.wbb.
    -60,   // .w.wbb.
    40,    // bw.wbb.
    23,    // ww.wbb.
    -22,   // ..bwbb.
    103,   // b.bwbb.
    -6,    // w.bwbb.
    99,    // .bbwbb.
    231,   // bbbwbb.
    37,    // wbbwbb.
    -56,   // .wbwbb.
    -144,  // bwbwbb.
    -38,   // wwbwbb.
    48,    // ..wwbb.
    11,    // b.wwbb.
    -54,   // w.wwbb.
    34,    // .bwwbb.
    7,     // bbwwbb.
    152,   // wbwwbb.
    -34,   // .wwwbb.
    -17,   // bwwwbb.
    -31,   // wwwwbb.
    61,    // ....wb.
    -105,  // b...wb.
    37,    // w...wb.
    14,    // .b..wb.
    -70,   // bb..wb.
    11,    // wb..wb.
    32,    // .w..wb.
    62,    // bw..wb.
    3,     // ww..wb.
    120,   // ..b.wb.
    -114,  // b.b.wb.
    -92,   // w.b.wb.
    -24,   // .bb.wb.
    -170,  // bbb.wb.
    -228,  // wbb.wb.
    0,     // .wb.wb.
    10,    // bwb.wb.
    77,    // wwb.wb.
    -64,   // ..w.wb.
    -9,    // b.w.wb.
    -19,   // w.w.wb.
    64,    // .bw.wb.
    -41,   // bbw.wb.
    -69,   // wbw.wb.
    -107,  // .ww.wb.
    62,    // bww.wb.
    156,   // www.wb.
    -19,   // ...bwb.
    -66,   // b..bwb.
    -84,   // w..bwb.
    -19,   // .b.bwb.
    24,    // bb.bwb.
    -3,    // wb.bwb.
    -83,   // .w.bwb.
    64,    // bw.bwb.
    -174,  // ww.bwb.
    -178,  // ..bbwb.
    8,     // b.bbwb.
    74,    // w.bbwb.
    -1,    // .bbbwb.
    76,    // bbbbwb.
    -138,  // wbbbwb.
    71,    // .wbbwb.
    -53,   // bwbbwb.
    -6,    // wwbbwb.
    85,    // ..wbwb.
    76,    // b.wbwb.
    94,    // w.wbwb.
    26,    // .bwbwb.
    145,   // bbwbwb.
    -160,  // wbwbwb.
    56,    // .wwbwb.
    52,    // bwwbwb.
    -116,  // wwwbwb.
    69,    // ...wwb.
    -52,   // b..wwb.
    -67,   // w..wwb.
    38,    // .b.wwb.
    70,    // bb.wwb.
    53,    // wb.wwb.
    -21,   // .w.wwb.
    135,   // bw.wwb.
    129,   // ww.wwb.
    76,    // ..bwwb.
    111,   // b.bwwb.
    5,     // w.bwwb.
    34,    // .bbwwb.
    1,     // bbbwwb.
    -6,    // wbbwwb.
    -71,   // .wbwwb.
    -68,   // bwbwwb.
    -15,   // wwbwwb.
    219,   // ..wwwb.
    28,    // b.wwwb.
    -120,  // w.wwwb.
    -40,   // .bwwwb.
    66,    // bbwwwb.
    57,    // wbwwwb.
    -36,   // .wwwwb.
    60,    // bwwwwb.
    46,    // wwwwwb.
    33,    // .....w.
    -86,   // b....w.
    177,   // w....w.
    0,     // .b...w.
    -36,   // bb...w.
    39,    // wb...w.
    -20,   // .w...w.
    -37,   // bw...w.
    83,    // ww...w.
    -43,   // ..b..w.
    -26,   // b.b..w.
    -22,   // w.b..w.
    -16,   // .bb..w.
    -54,   // bbb..w.
    -37,   // wbb..w.
    -14,   // .wb..w.
    -68,   // bwb..w.
    -27,   // wwb..w.
    97,    // ..w..w.
    1,     // b.w..w.
    -1,    // w.w..w.
    32,    // .bw..w.
    70,    // bbw..w.
    140,   // wbw..w.
    -30,   // .ww..w.
    -70,   // bww..w.
    -22,   // www..w.
    -40,   // ...b.w.
    -89,   // b..b.w.
    -12,   // w..b.w.
    -64,   // .b.b.w.
    -57,   // bb.b.w.
    -84,   // wb.b.w.
    -58,   // .w.b.w.
    118,   // bw.b.w.
    -29,   // ww.b.w.
    -92,   // ..bb.w.
    29,    // b.bb.w.
    15,    // w.bb.w.
    7,     // .bbb.w.
    195,   // bbbb.w.
    -58,   // wbbb.w.
    -38,   // .wbb.w.
    67,    // bwbb.w.
    58,    // wwbb.w.
    16,    // ..wb.w.
    62,    // b.wb.w.
    39,    // w.wb.w.
    -83,   // .bwb.w.
    153,   // bbwb.w.
    217,   // wbwb.w.
    -20,   // .wwb.w.
    -2,    // bwwb.w.
    -19,   // wwwb.w.
    -32,   // ...w.w.
    142,   // b..w.w.
    48,    // w..w.w.
    64,    // .b.w.w.
    81,    // bb.w.w.
    -33,   // wb.w.w.
    36,    // .w.w.w.
    81,    // bw.w.w.
    -2,    // ww.w.w.
    -10,   // ..bw.w.
    -23,   // b.bw.w.
    -14,   // w.bw.w.
    -60,   // .bbw.w.
    62,    // bbbw.w.
    85,    // wbbw.w.
    19,    // .wbw.w.
    74,    // bwbw.w.
    12,    // wwbw.w.
    176,   // ..ww.w.
    -37,   // b.ww.w.
    -57,   // w.ww.w.
    -21,   // .bww.w.
    105,   // bbww.w.
    37,    // wbww.w.
    -106,  // .www.w.
    -175,  // bwww.w.
    -47,   // wwww.w.
    -61,   // ....bw.
    -37,   // b...bw.
    105,   // w...bw.
    -32,   // .b..bw.
    -3,    // bb..bw.
    -62,   // wb..bw.
    -14,   // .w..bw.
    -11,   // bw..bw.
    70,    // ww..bw.
    64,    // ..b.bw.
    19,    // b.b.bw.
    9,     // w.b.bw.
    107,   // .bb.bw.
    -156,  // bbb.bw.
    -62,   // wbb.bw.
    -64,   // .wb.bw.
    69,    // bwb.bw.
    41,    // wwb.bw.
    -120,  // ..w.bw.
    92,    // b.w.bw.
    114,   // w.w.bw.
    0,     // .bw.bw.
    -77,   // bbw.bw.
    -10,   // wbw.bw.
    24,    // .ww.bw.
    228,   // bww.bw.
    170,   // www.bw.
    -69,   // ...bbw.
    67,    // b..bbw.
    52,    // w..bbw.
    21,    // .b.bbw.
    -129,  // bb.bbw.
    -135,  // wb.bbw.
    -38,   // .w.bbw.
    -53,   // bw.bbw.
    -70,   // ww.bbw.
    -219,  // ..bbbw.
    120,   // b.bbbw.
    -28,   // w.bbbw.
    36,    // .bbbbw.
    -46,   // bbbbbw.
    -60,   // wbbbbw.
    40,    // .wbbbw.
    -57,   // bwbbbw.
    -66,   // wwbbbw.
    -76,   // ..wbbw.
    -5,    // b.wbbw.
    -111,  // w.wbbw.
    71,    // .bwbbw.
    15,    // bbwbbw.
    68,    // wbwbbw.
    -34,   // .wwbbw.
    6,     // bwwbbw.
    -1,    // wwwbbw.
    19,    // ...wbw.
    84,    // b..wbw.
    66,    // w..wbw.
    83,    // .b.wbw.
    174,   // bb.wbw.
    -64,   // wb.wbw.
    19,    // .w.wbw.
    3,     // bw.wbw.
    -24,   // ww.wbw.
    -85,   // ..bwbw.
    -94,   // b.bwbw.
    -76,   // w.bwbw.
    -56,   // .bbwbw.
    116,   // bbbwbw.
    -52,   // wbbwbw.
    -26,   // .wbwbw.
    160,   // bwbwbw.
    -145,  // wwbwbw.
    178,   // ..wwbw.
    -74,   // b.wwbw.
    -8,    // w.wwbw.
    -71,   // .bwwbw.
    6,     // bbwwbw.
    53,    // wbwwbw.
    1,     // .wwwbw.
    138,   // bwwwbw.
    -76,   // wwwwbw.
    139,   // ....ww.
    43,    // b...ww.
    161,   // w...ww.
    16,    // .b..ww.
    81,    // bb..ww.
    28,    // wb..ww.
    -30,   // .w..ww.
    -10,   // bw..ww.
    -64,   // ww..ww.
    169,   // ..b.ww.
    -48,   // b.b.ww.
    187,   // w.b.ww.
    0,     // .bb.ww.
    20,    // bbb.ww.
    -76,   // wbb.ww.
    24,    // .wb.ww.
    -13,   // bwb.ww.
    25,    // wwb.ww.
    -99,   // ..w.ww.
    -37,   // b.w.ww.
    -114,  // w.w.ww.
    -107,  // .bw.ww.
    2,     // bbw.ww.
    -82,   // wbw.ww.
    -212,  // .ww.ww.
    -75,   // bww.ww.
    69,    // www.ww.
    -11,   // ...bww.
    91,    // b..bww.
    -57,   // w..bww.
    60,    // .b.bww.
    -23,   // bb.bww.
    -40,   // wb.bww.
    -20,   // .w.bww.
    70,    // bw.bww.
    59,    // ww.bww.
    -48,   // ..bbww.
    54,    // b.bbww.
    -11,   // w.bbww.
    34,    // .bbbww.
    31,    // bbbbww.
    17,    // wbbbww.
    -34,   // .wbbww.
    -152,  // bwbbww.
    -7,    // wwbbww.
    22,    // ..wbww.
    6,     // b.wbww.
    -103,  // w.wbww.
    56,    // .bwbww.
    38,    // bbwbww.
    144,   // wbwbww.
    -99,   // .wwbww.
    -37,   // bwwbww.
    -231,  // wwwbww.
    -40,   // ...www.
    14,    // b..www.
    65,    // w..www.
    -7,    // .b.www.
    45,    // bb.www.
    185,   // wb.www.
    -106,  // .w.www.
    91,    // bw.www.
    105,   // ww.www.
    -162,  // ..bwww.
    -41,   // b.bwww.
    35,    // w.bwww.
    -34,   // .bbwww.
    -110,  // bbbwww.
    29,    // wbbwww.
    1,     // .wbwww.
    224,   // bwbwww.
    102,   // wwbwww.
    -299,  // ..wwww.
    -97,   // b.wwww.
    -46,   // w.wwww.
    -36,   // .bwwww.
    18,    // bbwwww.
    -118,  // wbwwww.
    -68,   // .wwwww.
    109,   // bwwwww.
    -112,  // wwwwww.
    5,     // ......b
    -29,   // b.....b
    0,     // w.....b
    -177,  // .b....b
    -18,   // bb....b
    53,    // wb....b
    -86,   // .w....b
    17,    // bw....b
    -152,  // ww....b
    19,    // ..b...b
    67,    // b.b...b
    108,   // w.b...b
    -161,  // .bb...b
    -26,   // bbb...b
    -63,   // wbb...b
    -37,   // .wb...b
    -90,   // bwb...b
    68,    // wwb...b
    -64,   // ..w...b
    -158,  // b.w...b
    -13,   // w.w...b
    -105,  // .bw...b
    73,    // bbw...b
    -42,   // wbw...b
    43,    // .ww...b
    -43,   // bww...b
    -58,   // www...b
    -56,   // ...b..b
    68,    // b..b..b
    -140,  // w..b..b
    -48,   // .b.b..b
    -19,   // bb.b..b
    75,    // wb.b..b
    -89,   // .w.b..b
    -42,   // bw.b..b
    166,   // ww.b..b
    90,    // ..bb..b
    59,    // b.bb..b
    84,    // w.bb..b
    -65,   // .bbb..b
    0,     // bbbb..b
    -64,   // wbbb..b
    67,    // .wbb..b
    -7,    // bwbb..b
    -66,   // wwbb..b
    56,    // ..wb..b
    54,    // b.wb..b
    -65,   // w.wb..b
    -66,   // .bwb..b
    -30,   // bbwb..b
    20,    // wbwb..b
    91,    // .wwb..b
    99,    // bwwb..b
    -106,  // wwwb..b
    83,    // ...w..b
    -11,   // b..w..b
    140,   // w..w..b
    12,    // .b.w..b
    -61,   // bb.w..b
    124,   // wb.w..b
    142,   // .w.w..b
    -87,   // bw.w..b
    -49,   // ww.w..b
    3,     // ..bw..b
    -39,   // b.bw..b
    -82,   // w.bw..b
    57,    // .bbw..b
    71,    // bbbw..b
    -31,   // wbbw..b
    84,    // .wbw..b
    95,    // bwbw..b
    15,    // wwbw..b
    6,     // ..ww..b
    52,    // b.ww..b
    -171,  // w.ww..b
    -52,   // .bww..b
    -80,   // bbww..b
    -69,   // wbww..b
    14,    // .www..b
    -24,   // bwww..b
    -88,   // wwww..b
    40,    // ....b.b
    67,    // b...b.b
    13,    // w...b.b
    1,     // .b..b.b
    64,    // bb..b.b
    -44,   // wb..b.b
    -26,   // .w..b.b
    -116,  // bw..b.b
    53,    // ww..b.b
    55,    // ..b.b.b
    -98,   // b.b.b.b
    42,    // w.b.b.b
    114,   // .bb.b.b
    -83,   // bbb.b.b
    -136,  // wbb.b.b
    19,    // .wb.b.b
    33,    // bwb.b.b
    126,   // wwb.b.b
    74,    // ..w.b.b
    35,    // b.w.b.b
    0,     // w.w.b.b
    -114,  // .bw.b.b
    -17,   // bbw.b.b
    -44,   // wbw.b.b
    -48,   // .ww.b.b
    0,     // bww.b.b
    55,    // www.b.b
    -37,   // ...bb.b
    59,    // b..bb.b
    171,   // w..bb.b
    57,    // .b.bb.b
    -92,   // bb.bb.b
    65,    // wb.bb.b
    29,    // .w.bb.b
    24,    // bw.bb.b
    93,    // ww.bb.b
    140,   // ..bbb.b
    -129,  // b.bbb.b
    -57,   // w.bbb.b
    46,    // .bbbb.b
    15,    // bbbbb.b
    11,    // wbbbb.b
    120,   // .wbbb.b
    -91,   // bwbbb.b
    -16,   // wwbbb.b
    -61,   // ..wbb.b
    6,     // b.wbb.b
    59,    // w.wbb.b
    8,     // .bwbb.b
    113,   // bbwbb.b
    10,    // wbwbb.b
    54,    // .wwbb.b
    -7,    // bwwbb.b
    -11,   // wwwbb.b
    -42,   // ...wb.b
    -39,   // b..wb.b
    65,    // w..wb.b
    -39,   // .b.wb.b
    -15,   // bb.wb.b
    -24,   // wb.wb.b
    -23,   // .w.wb.b
    -73,   // bw.wb.b
    103,   // ww.wb.b
    64,    // ..bwb.b
    -4,    // b.bwb.b
    85,    // w.bwb.b
    103,   // .bbwb.b
    10,    // bbbwb.b
    -80,   // wbbwb.b
    -94,   // .wbwb.b
    -125,  // bwbwb.b
    50,    // wwbwb.b
    162,   // ..wwb.b
    65,    // b.wwb.b
    -59,   // w.wwb.b
    111,   // .bwwb.b
    -17,   // bbwwb.b
    163,   // wbwwb.b
    -41,   // .wwwb.b
    -47,   // bwwwb.b
    -7,    // wwwwb.b
    -20,   // ....w.b
    -158,  // b...w.b
    -108,  // w...w.b
    22,    // .b..w.b
    -106,  // bb..w.b
    -28,   // wb..w.b
    1,     // .w..w.b
    -60,   // bw..w.b
    46,    // ww..w.b
    -1,    // ..b.w.b
    35,    // b.b.w.b
    0,     // w.b.w.b
    -187,  // .bb.w.b
    -69,   // bbb.w.b
    41,    // wbb.w.b
    92,    // .wb.w.b
    -87,   // bwb.w.b
    -35,   // wwb.w.b
    12,    // ..w.w.b
    141,   // b.w.w.b
    -42,   // w.w.w.b
    -9,    // .bw.w.b
    90,    // bbw.w.b
    63,    // wbw.w.b
    -37,   // .ww.w.b
    -22,   // bww.w.b
    -64,   // www.w.b
    13,    // ...bw.b
    54,    // b..bw.b
    82,    // w..bw.b
    14,    // .b.bw.b
    61,    // bb.bw.b
    -76,   // wb.bw.b
    62,    // .w.bw.b
    -37,   // bw.bw.b
    96,    // ww.bw.b
    -170,  // ..bbw.b
    6,     // b.bbw.b
    -85,   // w.bbw.b
    -35,   // .bbbw.b
    -80,   // bbbbw.b
    -30,   // wbbbw.b
    -5,    // .wbbw.b
    1,     // bwbbw.b
    -81,   // wwbbw.b
    51,    // ..wbw.b
    -92,   // b.wbw.b
    -85,   // w.wbw.b
    76,    // .bwbw.b
    35,    // bbwbw.b
    -30,   // wbwbw.b
    6,     // .wwbw.b
    -108,  // bwwbw.b
    -52,   // wwwbw.b
    39,    // ...ww.b
    52,    // b..ww.b
    -84,   // w..ww.b
    -15,   // .b.ww.b
    -49,   // bb.ww.b
    -173,  // wb.ww.b
    -37,   // .w.ww.b
    -43,   // bw.ww.b
    113,   // ww.ww.b
    -49,   // ..bww.b
    65,    // b.bww.b
    85,    // w.bww.b
    11,    // .bbww.b
    -58,   // bbbww.b
    45,    // wbbww.b
    -74,   // .wbww.b
    12,    // bwbww.b
    32,    // wwbww.b
    55,    // ..www.b
    94,    // b.www.b
    57,    // w.www.b
    28,    // .bwww.b
    -203,  // bbwww.b
    -153,  // wbwww.b
    -97,   // .wwww.b
    31,    // bwwww.b
    1,     // wwwww.b
    49,    // .....bb
    -18,   // b....bb
    152,   // w....bb
    -83,   // .b...bb
    -111,  // bb...bb
    53,    // wb...bb
    -36,   // .w...bb
    16,    // bw...bb
    0,     // ww...bb
    164,   // ..b..bb
    64,    // b.b..bb
    -46,   // w.b..bb
    64,    // .bb..bb
    132,   // bbb..bb
    169,   // wbb..bb
    -3,    // .wb..bb
    -65,   // bwb..bb
    -52,   // wwb..bb
    48,    // ..w..bb
    -106,  // b.w..bb
    -53,   // w.w..bb
    -70,   // .bw..bb
    7,     // bbw..bb
    127,   // wbw..bb
    81,    // .ww..bb
    -9,    // bww..bb
    44,    // www..bb
    110,   // ...b.bb
    -19,   // b..b.bb
    49,    // w..b.bb
    2,     // .b.b.bb
    70,    // bb.b.bb
    42,    // wb.b.bb
    -57,   // .w.b.bb
    52,    // bw.b.bb
    39,    // ww.b.bb
    91,    // ..bb.bb
    -92,   // b.bb.bb
    -113,  // w.bb.bb
    -105,  // .bbb.bb
    -51,   // bbbb.bb
    -2,    // wbbb.bb
    -129,  // .wbb.bb
    -14,   // bwbb.bb
    -49,   // wwbb.bb
    127,   // ..wb.bb
    61,    // b.wb.bb
    -103,  // w.wb.bb
    24,    // .bwb.bb
    101,   // bbwb.bb
    73,    // wbwb.bb
    -23,   // .wwb.bb
    68,    // bwwb.bb
    -6,    // wwwb.bb
    200,   // ...w.bb
    -61,   // b..w.bb
    -166,  // w..w.bb
    29,    // .b.w.bb
    -18,   // bb.w.bb
    -28,   // wb.w.bb
    81,    // .w.w.bb
    38,    // bw.w.bb
    -39,   // ww.w.bb
    -54,   // ..bw.bb
    -15,   // b.bw.bb
    -96,   // w.bw.bb
    -59,   // .bbw.bb
    44,    // bbbw.bb
    19,    // wbbw.bb
    174,   // .wbw.bb
    35,    // bwbw.bb
    -58,   // wwbw.bb
    -59,   // ..ww.bb
    -49,   // b.ww.bb
    -93,   // w.ww.bb
    70,    // .bww.bb
    13,    // bbww.bb
    28,    // wbww.bb
    45,    // .www.bb
    97,    // bwww.bb
    -120,  // wwww.bb
    155,   // ....bbb
    -26,   // b...bbb
    58,    // w...bbb
    22,    // .b..bbb
    132,   // bb..bbb
    -43,   // wb..bbb
    -54,   // .w..bbb
    83,    // bw..bbb
    -44,   // ww..bbb
    132,   // ..b.bbb
    -83,   // b.b.bbb
    64,    // w.b.bbb
    -69,   // .bb.bbb
    -12,   // bbb.bbb
    47,    // wbb.bbb
    -156,  // .wb.bbb
    22,    // bwb.bbb
    -117,  // wwb.bbb
    -24,   // ..w.bbb
    -69,   // b.w.bbb
    -55,   // w.w.bbb
    -170,  // .bw.bbb
    -5,    // bbw.bbb
    -67,   // wbw.bbb
    20,    // .ww.bbb
    -62,   // bww.bbb
    0,     // www.bbb
    337,   // ...bbbb
    0,     // b..bbbb
    88,    // w..bbbb
    47,    // .b.bbbb
    -51,   // bb.bbbb
    -64,   // wb.bbbb
    195,   // .w.bbbb
    -68,   // bw.bbbb
    120,   // ww.bbbb
    -43,   // ..bbbbb
    15,    // b.bbbbb
    -1,    // w.bbbbb
    112,   // .bbbbbb
    55,    // bbbbbbb
    79,    // wbbbbbb
    -46,   // .wbbbbb
    -30,   // bwbbbbb
    -3,    // wwbbbbb
    10,    // ..wbbbb
    -80,   // b.wbbbb
    7,     // w.wbbbb
    76,    // .bwbbbb
    108,   // bbwbbbb
    33,    // wbwbbbb
    31,    // .wwbbbb
    18,    // bwwbbbb
    -101,  // wwwbbbb
    -121,  // ...wbbb
    71,    // b..wbbb
    106,   // w..wbbb
    19,    // .b.wbbb
    44,    // bb.wbbb
    -23,   // wb.wbbb
    62,    // .w.wbbb
    92,    // bw.wbbb
    6,     // ww.wbbb
    -128,  // ..bwbbb
    10,    // b.bwbbb
    52,    // w.bwbbb
    231,   // .bbwbbb
    -19,   // bbbwbbb
    70,    // wbbwbbb
    116,   // .wbwbbb
    -21,   // bwbwbbb
    92,    // wwbwbbb
    59,    // ..wwbbb
    -58,   // b.wwbbb
    11,    // w.wwbbb
    1,     // .bwwbbb
    14,    // bbwwbbb
    5,     // wbwwbbb
    -110,  // .wwwbbb
    8,     // bwwwbbb
    101,   // wwwwbbb
    -52,   // ....wbb
    73,    // b...wbb
    -68,   // w...wbb
    27,    // .b..wbb
    7,     // bb..wbb
    -58,   // wb..wbb
    70,    // .w..wbb
    -7,    // bw..wbb
    52,    // ww..wbb
    55,    // ..b.wbb
    -17,   // b.b.wbb
    35,    // w.b.wbb
    -25,   // .bb.wbb
    -5,    // bbb.wbb
    56,    // wbb.wbb
    -77,   // .wb.wbb
    32,    // bwb.wbb
    0,     // wwb.wbb
    -30,   // ..w.wbb
    90,    // b.w.wbb
    -126,  // w.w.wbb
    -41,   // .bw.wbb
    91,    // bbw.wbb
    29,    // wbw.wbb
    2,     // .ww.wbb
    -67,   // bww.wbb
    117,   // www.wbb
    -32,   // ...bwbb
    -30,   // b..bwbb
    -15,   // w..bwbb
    -12,   // .b.bwbb
    101,   // bb.bwbb
    -56,   // wb.bwbb
    153,   // .w.bwbb
    14,    // bw.bwbb
    58,    // ww.bwbb
    91,    // ..bbwbb
    113,   // b.bbwbb
    -32,   // w.bbwbb
    -102,  // .bbbwbb
    108,   // bbbbwbb
    -23,   // wbbbwbb
    15,    // .wbbwbb
    -122,  // bwbbwbb
    128,   // wwbbwbb
    73,    // ..wbwbb
    35,    // b.wbwbb
    -50,   // w.wbwbb
    145,   // .bwbwbb
    78,    // bbwbwbb
    -20,   // wbwbwbb
    38,    // .wwbwbb
    57,    // bwwbwbb
    -92,   // wwwbwbb
    -117,  // ...wwbb
    -80,   // b..wwbb
    66,    // w..wwbb
    -58,   // .b.wwbb
    13,    // bb.wwbb
    176,   // wb.wwbb
    105,   // .w.wwbb
    -127,  // bw.wwbb
    49,    // ww.wwbb
    134,   // ..bwwbb
    -17,   // b.bwwbb
    81,    // w.bwwbb
    7,     // .bbwwbb
    14,    // bbbwwbb
    -111,  // wbbwwbb
    6,     // .wbwwbb
    -88,   // bwbwwbb
    -128,  // wwbwwbb
    7,     // ..wwwbb
    -203,  // b.wwwbb
    16,    // w.wwwbb
    66,    // .bwwwbb
    -64,   // bbwwwbb
    40,    // wbwwwbb
    18,    // .wwwwbb
    11,    // bwwwwbb
    3,     // wwwwwbb
    -52,   // .....wb
    17,    // b....wb
    -53,   // w....wb
    -39,   // .b...wb
    16,    // bb...wb
    0,     // wb...wb
    -37,   // .w...wb
    22,    // bw...wb
    -53,   // ww...wb
    6,     // ..b..wb
    -116,  // b.b..wb
    28,    // w.b..wb
    -28,   // .bb..wb
    83,    // bbb..wb
    40,    // wbb..wb
    -11,   // .wb..wb
    106,   // bwb..wb
    58,    // wwb..wb
    9,     // ..w..wb
    -60,   // b.w..wb
    44,    // w.w..wb
    62,    // .bw..wb
    -7,    // bbw..wb
    -176,  // wbw..wb
    -10,   // .ww..wb
    -96,   // bww..wb
    43,    // www..wb
    -166,  // ...b.wb
    -42,   // b..b.wb
    -124,  // w..b.wb
    33,    // .b.b.wb
    52,    // bb.b.wb
    15,    // wb.b.wb
    118,   // .w.b.wb
    -144,  // bw.b.wb
    28,    // ww.b.wb
    -134,  // ..bb.wb
    24,    // b.bb.wb
    173,   // w.bb.wb
    -185,  // .bbb.wb
    -68,   // bbbb.wb
    -13,   // wbbb.wb
    -53,   // .wbb.wb
    5,     // bwbb.wb
    -176,  // wwbb.wb
    23,    // ..wb.wb
    -37,   // b.wb.wb
    24,    // w.wb.wb
    64,    // .bwb.wb
    14,    // bbwb.wb
    -50,   // wbwb.wb
    70,    // .wwb.wb
    -60,   // bwwb.wb
    23,    // wwwb.wb
    73,    // ...w.wb
    -87,   // b..w.wb
    -75,   // w..w.wb
    84,    // .b.w.wb
    38,    // bb.w.wb
    -15,   // wb.w.wb
    81,    // .w.w.wb
    -58,   // bw.w.wb
    -42,   // ww.w.wb
    139,   // ..bw.wb
    -73,   // b.bw.wb
    76,    // w.bw.wb
    40,    // .bbw.wb
    92,    // bbbw.wb
    -172,  // wbbw.wb
    3,     // .wbw.wb
    -63,   // bwbw.wb
    56,    // wwbw.wb
    -139,  // ..ww.wb
    -43,   // b.ww.wb
    -65,   // w.ww.wb
    135,   // .bww.wb
    -127,  // bbww.wb
    -6,    // wbww.wb
    91,    // .www.wb
    -114,  // bwww.wb
    64,    // wwww.wb
    -78,   // ....bwb
    -90,   // b...bwb
    42,    // w...bwb
    -140,  // .b..bwb
    -65,   // bb..bwb
    176,   // wb..bwb
    -68,   // .w..bwb
    106,   // bw..bwb
    -127,  // ww..bwb
    -148,  // ..b.bwb
    33,    // b.b.bwb
    -63,   // w.b.bwb
    82,    // .bb.bwb
    22,    // bbb.bwb
    91,    // wbb.bwb
    69,    // .wb.bwb
    51,    // bwb.bwb
    -29,   // wwb.bwb
    43,    // ..w.bwb
    -87,   // b.w.bwb
    44,    // w.w.bwb
    10,    // .bw.bwb
    32,    // bbw.bwb
    0,     // wbw.bwb
    -13,   // .ww.bwb
    -171,  // bww.bwb
    67,    // www.bwb
    -14,   // ...bbwb
    -7,    // b..bbwb
    69,    // w..bbwb
    -37,   // .b.bbwb
    -14,   // bb.bbwb
    6,     // wb.bbwb
    67,    // .w.bbwb
    5,     // bw.bbwb
    -28,   // ww.bbwb
    -97,   // ..bbbwb
    -91,   // b.bbbwb
    153,   // w.bbbwb
    118,   // .bbbbwb
    -30,   // bbbbbwb
    2,     // wbbbbwb
    -57,   // .wbbbwb
    20,    // bwbbbwb
    -40,   // wwbbbwb
    -12,   // ..wbbwb
    1,     // b.wbbwb
    -163,  // w.wbbwb
    -53,   // .bwbbwb
    -122,  // bbwbbwb
    70,    // wbwbbwb
    -152,  // .wwbbwb
    149,   // bwwbbwb
    -5,    // wwwbbwb
    20,    // ...wbwb
    95,    // b..wbwb
    -20,   // w..wbwb
    -217,  // .b.wbwb
    35,    // bb.wbwb
    50,    // wb.wbwb
    74,    // .w.wbwb
    -63,   // bw.wbwb
    -73,   // ww.wbwb
    22,    // ..bwbwb
    -125,  // b.bwbwb
    30,    // w.bwbwb
    -144,  // .bbwbwb
    -21,   // bbbwbwb
    171,   // wbbwbwb
    160,   // .wbwbwb
    86,    // bwbwbwb
    20,    // wwbwbwb
    -102,  // ..wwbwb
    12,    // b.wwbwb
    -10,   // w.wwbwb
    -68,   // .bwwbwb
    -88,   // bbwwbwb
    -70,   // wbwwbwb
    224,   // .wwwbwb
    -125,  // bwwwbwb
    -33,   // wwwwbwb
    162,   // ....wwb
    -43,   // b...wwb
    63,    // w...wwb
    37,    // .b..wwb
    -9,    // bb..wwb
    -40,   // wb..wwb
    -70,   // .w..wwb
    -96,   // bw..wwb
    -169,  // ww..wwb
    5,     // ..b.wwb
    0,     // b.b.wwb
    -41,   // w.b.wwb
    76,    // .bb.wwb
    -62,   // bbb.wwb
    0,     // wbb.wwb
    228,   // .wb.wwb
    -171,  // bwb.wwb
    -56,   // wwb.wwb
    -84,   // ..w.wwb
    -22,   // b.w.wwb
    136,   // w.w.wwb
    62,    // .bw.wwb
    -67,   // bbw.wwb
    -91,   // wbw.wwb
    -75,   // .ww.wwb
    51,    // bww.wwb
    -47,   // www.wwb
    -21,   // ...bwwb
    99,    // b..bwwb
    31,    // w..bwwb
    -85,   // .b.bwwb
    68,    // bb.bwwb
    172,   // wb.bwwb
    -2,    // .w.bwwb
    -60,   // bw.bwwb
    -19,   // ww.bwwb
    78,    // ..bbwwb
    -7,    // b.bbwwb
    -45,   // w.bbwwb
    -29,   // .bbbwwb
    18,    // bbbbwwb
    147,   // wbbbwwb
    6,     // .wbbwwb
    149,   // bwbbwwb
    111,   // wwbbwwb
    9,     // ..wbwwb
    -108,  // b.wbwwb
    80,    // w.wbwwb
    52,    // .bwbwwb
    57,    // bbwbwwb
    -171,  // wbwbwwb
    -37,   // .wwbwwb
    4,     // bwwbwwb
    -70,   // wwwbwwb
    62,    // ...wwwb
    -24,   // b..wwwb
    64,    // w..wwwb
    58,    // .b.wwwb
    97,    // bb.wwwb
    13,    // wb.wwwb
    -175,  // .w.wwwb
    -114,  // bw.wwwb
    2,     // ww.wwwb
    -56,   // ..bwwwb
    -47,   // b.bwwwb
    30,    // w.bwwwb
    -17,   // .bbwwwb
    8,     // bbbwwwb
    -147,  // wbbwwwb
    138,   // .wbwwwb
    -125,  // bwbwwwb
    23,    // wwbwwwb
    16,    // ..wwwwb
    31,    // b.wwwwb
    -11,   // w.wwwwb
    60,    // .bwwwwb
    11,    // bbwwwwb
    -2,    // wbwwwwb
    109,   // .wwwwwb
    -69,   // bwwwwwb
    -79,   // wwwwwwb
    -5,    // ......w
    0,     // b.....w
    29,    // w.....w
    86,    // .b....w
    152,   // bb....w
    -17,   // wb....w
    177,   // .w....w
    -53,   // bw....w
    18,    // ww....w
    64,    // ..b...w
    13,    // b.b...w
    158,   // w.b...w
    -43,   // .bb...w
    58,    // bbb...w
    43,    // wbb...w
    105,   // .wb...w
    42,    // bwb...w
    -73,   // wwb...w
    -19,   // ..w...w
    -108,  // b.w...w
    -67,   // w.w...w
    37,    // .bw...w
    -68,   // bbw...w
    90,    // wbw...w
    161,   // .ww...w
    63,    // bww...w
    26,    // www...w
    -83,   // ...b..w
    -140,  // b..b..w
    11,    // w..b..w
    -142,  // .b.b..w
    49,    // bb.b..w
    87,    // wb.b..w
    -12,   // .w.b..w
    -124,  // bw.b..w
    61,    // ww.b..w
    -6,    // ..bb..w
    171,   // b.bb..w
    -52,   // w.bb..w
    -14,   // .bbb..w
    88,    // bbbb..w
    24,    // wbbb..w
    52,    // .wbb..w
    69,    // bwbb..w
    80,    // wwbb..w
    -3,    // ..wb..w
    82,    // b.wb..w
    39,    // w.wb..w
    -84,   // .bwb..w
    -15,   // bbwb..w
    -95,   // wbwb..w
    -57,   // .wwb..w
    31,    // bwwb..w
    -71,   // wwwb..w
    56,    // ...w..w
    140,   // b..w..w
    -68,   // w..w..w
    89,    // .b.w..w
    -166,  // bb.w..w
    42,    // wb.w..w
    48,    // .w.w..w
    -75,   // bw.w..w
    19,    // ww.w..w
    -56,   // ..bw..w
    65,    // b.bw..w
    -54,   // w.bw..w
    -91,   // .bbw..w
    106,   // bbbw..w
    -99,   // wbbw..w
    66,    // .wbw..w
    -20,   // bwbw..w
    30,    // wwbw..w
    -90,   // ..ww..w
    -84,   // b.ww..w
    -59,   // w.ww..w
    -67,   // .bww..w
    66,    // bbww..w
    7,     // wbww..w
    65,    // .www..w
    64,    // bwww..w
    0,     // wwww..w
    20,    // ....b.w
    108,   // b...b.w
    158,   // w...b.w
    -1,    // .b..b.w
    -46,   // bb..b.w
    60,    // wb..b.w
    -22,   // .w..b.w
    28,    // bw..b.w
    106,   // ww..b.w
    -12,   // ..b.b.w
    42,    // b.b.b.w
    -141,  // w.b.b.w
    37,    // .bb.b.w
    64,    // bbb.b.w
    22,    // wbb.b.w
    9,     // .wb.b.w
    -63,   // bwb.b.w
    -90,   // wwb.b.w
    1,     // ..w.b.w
    0,     // b.w.b.w
    -35,   // w.w.b.w
    -92,   // .bw.b.w
    35,    // bbw.b.w
    87,    // wbw.b.w
    187,   // .ww.b.w
    -41,   // bww.b.w
    69,    // www.b.w
    -39,   // ...bb.w
    84,    // b..bb.w
    -52,   // w..bb.w
    37,    // .b.bb.w
    -113,  // bb.bb.w
    43,    // wb.bb.w
    15,    // .w.bb.w
    173,   // bw.bb.w
    49,    // ww.bb.w
    -55,   // ..bbb.w
    -57,   // b.bbb.w
    -94,   // w.bbb.w
    97,    // .bbbb.w
    -1,    // bbbbb.w
    -31,   // wbbbb.w
    -28,   // .wbbb.w
    153,   // bwbbb.w
    203,   // wwbbb.w
    49,    // ..wbb.w
    -85,   // b.wbb.w
    -65,   // w.wbb.w
    74,    // .bwbb.w
    -32,   // bbwbb.w
    -12,   // wbwbb.w
    -11,   // .wwbb.w
    -45,   // bwwbb.w
    58,    // wwwbb.w
    -13,   // ...wb.w
    -82,   // b..wb.w
    -54,   // w..wb.w
    -62,   // .b.wb.w
    -96,   // bb.wb.w
    37,    // wb.wb.w
    -14,   // .w.wb.w
    76,    // bw.wb.w
    -61,   // ww.wb.w
    -51,   // ..bwb.w
    85,    // b.bwb.w
    92,    // w.bwb.w
    -6,    // .bbwb.w
    52,    // bbbwb.w
    108,   // wbbwb.w
    -76,   // .wbwb.w
    30,    // bwbwb.w
    -35,   // wwbwb.w
    170,   // ..wwb.w
    85,    // b.wwb.w
    -6,    // w.wwb.w
    5,     // .bwwb.w
    81,    // bbwwb.w
    -1,    // wbwwb.w
    35,    // .wwwb.w
    30,    // bwwwb.w
    80,    // wwwwb.w
    -40,   // ....w.w
    -13,   // b...w.w
    -67,   // w...w.w
    26,    // .b..w.w
    -53,   // bb..w.w
    116,   // wb..w.w
    -1,    // .w..w.w
    44,    // bw..w.w
    -64,   // ww..w.w
    -74,   // ..b.w.w
    0,     // b.b.w.w
    -35,   // w.b.w.w
    48,    // .bb.w.w
    -55,   // bbb.w.w
    0,     // wbb.w.w
    114,   // .wb.w.w
    44,    // bwb.w.w
    17,    // wwb.w.w
    -55,   // ..w.w.w
    -42,   // b.w.w.w
    98,    // w.w.w.w
    -19,   // .bw.w.w
    -126,  // bbw.w.w
    -33,   // wbw.w.w
    -114,  // .ww.w.w
    136,   // bww.w.w
    83,    // www.w.w
    42,    // ...bw.w
    -65,   // b..bw.w
    39,    // w..bw.w
    23,    // .b.bw.w
    -103,  // bb.bw.w
    73,    // wb.bw.w
    39,    // .w.bw.w
    24,    // bw.bw.w
    15,    // ww.bw.w
    -162,  // ..bbw.w
    59,    // b.bbw.w
    -65,   // w.bbw.w
    41,    // .bbbw.w
    7,     // bbbbw.w
    47,    // wbbbw.w
    -111,  // .wbbw.w
    -163,  // bwbbw.w
    17,    // wwbbw.w
    -64,   // ..wbw.w
    -85,   // b.wbw.w
    4,     // w.wbw.w
    94,    // .bwbw.w
    -50,   // bbwbw.w
    125,   // wbwbw.w
    -103,  // .wwbw.w
    80,    // bwwbw.w
    -10,   // wwwbw.w
    37,    // ...ww.w
    -171,  // b..ww.w
    -59,   // w..ww.w
    -29,   // .b.ww.w
    -93,   // bb.ww.w
    -24,   // wb.ww.w
    -57,   // .w.ww.w
    -65,   // bw.ww.w
    92,    // ww.ww.w
    61,    // ..bww.w
    -59,   // b.bww.w
    -6,    // w.bww.w
    -54,   // .bbww.w
    11,    // bbbww.w
    7,     // wbbww.w
    -8,    // .wbww.w
    -10,   // bwbww.w
    -113,  // wwbww.w
    -140,  // ..www.w
    57,    // b.www.w
    129,   // w.www.w
    -120,  // .bwww.w
    16,    // bbwww.w
    91,    // wbwww.w
    -46,   // .wwww.w
    -11,   // bwwww.w
    -15,   // wwwww.w
    52,    // .....bw
    53,    // b....bw
    -17,   // w....bw
    37,    // .b...bw
    53,    // bb...bw
    -22,   // wb...bw
    39,    // .w...bw
    0,     // bw...bw
    -16,   // ww...bw
    -9,    // ..b..bw
    -44,   // b.b..bw
    60,    // w.b..bw
    10,    // .bb..bw
    -43,   // bbb..bw
    96,    // wbb..bw
    -62,   // .wb..bw
    176,   // bwb..bw
    7,     // wwb..bw
    -6,    // ..w..bw
    -28,   // b.w..bw
    116,   // w.w..bw
    11,    // .bw..bw
    -58,   // bbw..bw
    -106,  // wbw..bw
    28,    // .ww..bw
    -40,   // bww..bw
    -83,   // www..bw
    -73,   // ...b.bw
    75,    // b..b.bw
    87,    // w..b.bw
    -81,   // .b.b.bw
    42,    // bb.b.bw
    58,    // wb.b.bw
    -84,   // .w.b.bw
    15,    // bw.b.bw
    -38,   // ww.b.bw
    139,   // ..bb.bw
    65,    // b.bb.bw
    43,    // w.bb.bw
    -91,   // .bbb.bw
    -64,   // bbbb.bw
    114,   // wbbb.bw
    -135,  // .wbb.bw
    6,     // bwbb.bw
    127,   // wwbb.bw
    -139,  // ..wb.bw
    -76,   // b.wb.bw
    73,    // w.wb.bw
    -3,    // .bwb.bw
    -56,   // bbwb.bw
    63,    // wbwb.bw
    -40,   // .wwb.bw
    172,   // bwwb.bw
    -92,   // wwwb.bw
    166,   // ...w.bw
    124,   // b..w.bw
    42,    // w..w.bw
    -118,  // .b.w.bw
    -28,   // bb.w.bw
    144,   // wb.w.bw
    -33,   // .w.w.bw
    -15,   // bw.w.bw
    -52,   // ww.w.bw
    -23,   // ..bw.bw
    -24,   // b.bw.bw
    37,    // w.bw.bw
    -70,   // .bbw.bw
    -23,   // bbbw.bw
    60,    // wbbw.bw
    -64,   // .wbw.bw
    50,    // bwbw.bw
    -14,   // wwbw.bw
    134,   // ..ww.bw
    -173,  // b.ww.bw
    -24,   // w.ww.bw
    53,    // .bww.bw
    176,   // bbww.bw
    -5,    // wbww.bw
    185,   // .www.bw
    13,    // bwww.bw
    68,    // wwww.bw
    -162,  // ....bbw
    -63,   // b...bbw
    43,    // w...bbw
    70,    // .b..bbw
    169,   // bb..bbw
    96,    // wb..bbw
    -37,   // .w..bbw
    40,    // bw..bbw
    9,     // ww..bbw
    84,    // ..b.bbw
    -136,  // b.b.bbw
    22,    // w.b.bbw
    75,    // .bb.bbw
    47,    // bbb.bbw
    -51,   // wbb.bbw
    -62,   // .wb.bbw
    91,    // bwb.bbw
    67,    // wwb.bbw
    -5,    // ..w.bbw
    41,    // b.w.bbw
    0,     // w.w.bbw
    -228,  // .bw.bbw
    56,    // bbw.bbw
    171,   // wbw.bbw
    -76,   // .ww.bbw
    0,     // bww.bbw
    62,    // www.bbw
    -62,   // ...bbbw
    -64,   // b..bbbw
    24,    // w..bbbw
    175,   // .b.bbbw
    -2,    // bb.bbbw
    114,   // wb.bbbw
    -58,   // .w.bbbw
    -13,   // bw.bbbw
    -97,   // ww.bbbw
    -16,   // ..bbbbw
    11,    // b.bbbbw
    -31,   // w.bbbbw
    -109,  // .bbbbbw
    79,    // bbbbbbw
    69,    // wbbbbbw
    -60,   // .wbbbbw
    2,     // bwbbbbw
    -11,   // wwbbbbw
    56,    // ..wbbbw
    -30,   // b.wbbbw
    47,    // w.wbbbw
    -138,  // .bwbbbw
    -23,   // bbwbbbw
    125,   // wbwbbbw
    17,    // .wwbbbw
    147,   // bwwbbbw
    -8,    // wwwbbbw
    21,    // ...wbbw
    -31,   // b..wbbw
    -99,   // w..wbbw
    2,     // .b.wbbw
    19,    // bb.wbbw
    60,    // wb.wbbw
    85,    // .w.wbbw
    -172,  // bw.wbbw
    -68,   // ww.wbbw
    -9,    // ..bwbbw
    -80,   // b.bwbbw
    108,   // w.bwbbw
    37,    // .bbwbbw
    70,    // bbbwbbw
    -4,    // wbbwbbw
    -52,   // .wbwbbw
    171,   // bwbwbbw
    -57,   // wwbwbbw
    -78,   // ..wwbbw
    45,    // b.wwbbw
    7,     // w.wwbbw
    -6,    // .bwwbbw
    -111,  // bbwwbbw
    -149,  // wbwwbbw
    29,    // .wwwbbw
    -147,  // bwwwbbw
    -18,   // wwwwbbw
    78,    // ....wbw
    -42,   // b...wbw
    90,    // w...wbw
    68,    // .b..wbw
    127,   // bb..wbw
    -106,  // wb..wbw
    140,   // .w..wbw
    -176,  // bw..wbw
    65,    // ww..wbw
    -43,   // ..b.wbw
    -44,   // b.b.wbw
    87,    // w.b.wbw
    13,    // .bb.wbw
    -67,   // bbb.wbw
    171,   // wbb.wbw
    -10,   // .wb.wbw
    0,     // bwb.wbw
    -32,   // wwb.wbw
    148,   // ..w.wbw
    63,    // b.w.wbw
    -33,   // w.w.wbw
    -69,   // .bw.wbw
    29,    // bbw.wbw
    -51,   // wbw.wbw
    -82,   // .ww.wbw
    -91,   // bww.wbw
    -22,   // www.wbw
    -20,   // ...bwbw
    20,    // b..bwbw
    -95,   // w..bwbw
    -74,   // .b.bwbw
    73,    // bb.bwbw
    63,    // wb.bwbw
    217,   // .w.bwbw
    -50,   // bw.bwbw
    -35,   // ww.bwbw
    102,   // ..bbwbw
    10,    // b.bbwbw
    -12,   // w.bbwbw
    -224,  // .bbbwbw
    33,    // bbbbwbw
    125,   // wbbbwbw
    68,    // .wbbwbw
    70,    // bwbbwbw
    88,    // wwbbwbw
    -22,   // ..wbwbw
    -30,   // b.wbwbw
    125,   // w.wbwbw
    -160,  // .bwbwbw
    -20,   // bbwbwbw
    -86,   // wbwbwbw
    144,   // .wwbwbw
    -171,  // bwwbwbw
    21,    // wwwbwbw
    14,    // ...wwbw
    -69,   // b..wwbw
    7,     // w..wwbw
    -67,   // .b.wwbw
    28,    // bb.wwbw
    -5,    // wb.wwbw
    37,    // .w.wwbw
    -6,    // bw.wwbw
    14,    // ww.wwbw
    12,    // ..bwwbw
    163,   // b.bwwbw
    -1,    // w.bwwbw
    152,   // .bbwwbw
    5,     // bbbwwbw
    -149,  // wbbwwbw
    53,    // .wbwwbw
    -70,   // bwbwwbw
    122,   // wwbwwbw
    97,    // ..wwwbw
    -153,  // b.wwwbw
    91,    // w.wwwbw
    57,    // .bwwwbw
    40,    // bbwwwbw
    -20,   // wbwwwbw
    -118,  // .wwwwbw
    -2,    // bwwwwbw
    30,    // wwwwwbw
    -49,   // .....ww
    -152,  // b....ww
    18,    // w....ww
    36,    // .b...ww
    0,     // bb...ww
    -16,   // wb...ww
    83,    // .w...ww
    -53,   // bw...ww
    111,   // ww...ww
    -48,   // ..b..ww
    53,    // b.b..ww
    106,   // w.b..ww
    -81,   // .bb..ww
    -44,   // bbb..ww
    9,     // wbb..ww
    70,    // .wb..ww
    -127,  // bwb..ww
    -7,    // wwb..ww
    -164,  // ..w..ww
    46,    // b.w..ww
    -64,   // w.w..ww
    3,     // .bw..ww
    52,    // bbw..ww
    65,    // wbw..ww
    -64,   // .ww..ww
    -169,  // bww..ww
    -132,  // www..ww
    -200,  // ...b.ww
    166,   // b..b.ww
    61,    // w..b.ww
    -81,   // .b.b.ww
    39,    // bb.b.ww
    -38,   // wb.b.ww
    -29,   // .w.b.ww
    28,    // bw.b.ww
    18,    // ww.b.ww
    59,    // ..bb.ww
    93,    // b.bb.ww
    49,    // w.bb.ww
    -45,   // .bbb.ww
    120,   // bbbb.ww
    -97,   // wbbb.ww
    -70,   // .wbb.ww
    -28,   // bwbb.ww
    -13,   // wwbb.ww
    54,    // ..wb.ww
    96,    // b.wb.ww
    15,    // w.wb.ww
    -174,  // .bwb.ww
    58,    // bbwb.ww
    -35,   // wbwb.ww
    59,    // .wwb.ww
    -19,   // bwwb.ww
    -44,   // wwwb.ww
    -110,  // ...w.ww
    -49,   // b..w.ww
    19,    // w..w.ww
    57,    // .b.w.ww
    -39,   // bb.w.ww
    -52,   // wb.w.ww
    -2,    // .w.w.ww
    -42,   // bw.w.ww
    -70,   // ww.w.ww
    -127,  // ..bw.ww
    103,   // b.bw.ww
    -61,   // w.bw.ww
    23,    // .bbw.ww
    6,     // bbbw.ww
    -68,   // wbbw.ww
    -24,   // .wbw.ww
    -73,   // bwbw.ww
    -101,  // wwbw.ww
    -91,   // ..ww.ww
    113,   // b.ww.ww
    92,    // w.ww.ww
    129,   // .bww.ww
    49,    // bbww.ww
    14,    // wbww.ww
    105,   // .www.ww
    2,     // bwww.ww
    51,    // wwww.ww
    52,    // ....bww
    68,    // b...bww
    -73,   // w...bww
    -70,   // .b..bww
    -52,   // bb..bww
    7,     // wb..bww
    -27,   // .w..bww
    58,    // bw..bww
    -7,    // ww..bww
    30,    // ..b.bww
    126,   // b.b.bww
    -90,   // w.b.bww
    -2,    // .bb.bww
    -117,  // bbb.bww
    67,    // wbb.bww
    41,    // .wb.bww
    -29,   // bwb.bww
    -91,   // wwb.bww
    -55,   // ..w.bww
    -35,   // b.w.bww
    17,    // w.w.bww
    77,    // .bw.bww
    0,     // bbw.bww
    -32,   // wbw.bww
    25,    // .ww.bww
    -56,   // bww.bww
    5,     // www.bww
    117,   // ...bbww
    -66,   // b..bbww
    80,    // w..bbww
    -105,  // .b.bbww
    -49,   // bb.bbww
    127,   // wb.bbww
    58,    // .w.bbww
    -176,  // bw.bbww
    -13,   // ww.bbww
    -7,    // ..bbbww
    -16,   // b.bbbww
    203,   // w.bbbww
    -18,   // .bbbbww
    -3,    // bbbbbww
    -11,   // wbbbbww
    -66,   // .wbbbww
    -40,   // bwbbbww
    64,    // wwbbbww
    -134,  // ..wbbww
    -81,   // b.wbbww
    17,    // w.wbbww
    -6,    // .bwbbww
    128,   // bbwbbww
    88,    // wbwbbww
    -7,    // .wwbbww
    111,   // bwwbbww
    -14,   // wwwbbww
    32,    // ...wbww
    15,    // b..wbww
    30,    // w..wbww
    -153,  // .b.wbww
    -58,   // bb.wbww
    -14,   // wb.wbww
    12,    // .w.wbww
    56,    // bw.wbww
    -101,  // ww.wbww
    -73,   // ..bwbww
    50,    // b.bwbww
    -35,   // w.bwbww
    -38,   // .bbwbww
    92,    // bbbwbww
    -57,   // wbbwbww
    -145,  // .wbwbww
    20,    // bwbwbww
    -78,   // wwbwbww
    -91,   // ..wwbww
    32,    // b.wwbww
    -113,  // w.wwbww
    -15,   // .bwwbww
    -128,  // bbwwbww
    122,   // wbwwbww
    102,   // .wwwbww
    23,    // bwwwbww
    -108,  // wwwwbww
    -155,  // ....www
    -58,   // b...www
    26,    // w...www
    54,    // .b..www
    44,    // bb..www
    -83,   // wb..www
    -22,   // .w..www
    43,    // bw..www
    -132,  // ww..www
    24,    // ..b.www
    55,    // b.b.www
    69,    // w.b.www
    -20,   // .bb.www
    0,     // bbb.www
    62,    // wbb.www
    170,   // .wb.www
    67,    // bwb.www
    5,     // wwb.www
    -132,  // ..w.www
    -64,   // b.w.www
    83,    // w.w.www
    156,   // .bw.www
    117,   // bbw.www
    -22,   // wbw.www
    69,    // .ww.www
    -47,   // bww.www
    12,    // www.www
    121,   // ...bwww
    -106,  // b..bwww
    -71,   // w..bwww
    -62,   // .b.bwww
    -6,    // bb.bwww
    -92,   // wb.bwww
    -19,   // .w.bwww
    23,    // bw.bwww
    -44,   // ww.bwww
    -59,   // ..bbwww
    -11,   // b.bbwww
    58,    // w.bbwww
    110,   // .bbbwww
    -101,  // bbbbwww
    -8,    // wbbbwww
    -1,    // .wbbwww
    -5,    // bwbbwww
    -14,   // wwbbwww
    128,   // ..wbwww
    -52,   // b.wbwww
    -10,   // w.wbwww
    -116,  // .bwbwww
    -92,   // bbwbwww
    21,    // wbwbwww
    -231,  // .wwbwww
    -70,   // bwwbwww
    19,    // wwwbwww
    -337,  // ...wwww
    -88,   // b..wwww
    0,     // w..wwww
    -195,  // .b.wwww
    -120,  // bb.wwww
    68,    // wb.wwww
    -47,   // .w.wwww
    64,    // bw.wwww
    51,    // ww.wwww
    -10,   // ..bwwww
    -7,    // b.bwwww
    80,    // w.bwwww
    -31,   // .bbwwww
    101,   // bbbwwww
    -18,   // wbbwwww
    -76,   // .wbwwww
    -33,   // bwbwwww
    -108,  // wwbwwww
    43,    // ..wwwww
    1,     // b.wwwww
    -15,   // w.wwwww
    46,    // .bwwwww
    3,     // bbwwwww
    30,    // wbwwwww
    -112,  // .wwwwww
    -79,   // bwwwwww
    -55,   // wwwwwww
    32,    // ccc
    -7,    // cc
    26,    // c
    373,   // ttt
    30,    // tt
    76,    // t
    -5,    // ct
    -8,    // cct
    49,    // ctt
].into_boxed_slice()
