vec![
    0,     // .......
    26,    // b......
    -26,   // w......
    -52,   // .b.....
    100,   // bb.....
    -20,   // wb.....
    52,    // .w.....
    20,    // bw.....
    -100,  // ww.....
    13,    // ..b....
    47,    // b.b....
    18,    // w.b....
    -114,  // .bb....
    181,   // bbb....
    -163,  // wbb....
    -107,  // .wb....
    -32,   // bwb....
    88,    // wwb....
    -13,   // ..w....
    -18,   // b.w....
    -47,   // w.w....
    107,   // .bw....
    -88,   // bbw....
    32,    // wbw....
    114,   // .ww....
    163,   // bww....
    -181,  // www....
    -52,   // ...b...
    -80,   // b..b...
    -88,   // w..b...
    4,     // .b.b...
    164,   // bb.b...
    -49,   // wb.b...
    28,    // .w.b...
    -142,  // bw.b...
    -185,  // ww.b...
    -30,   // ..bb...
    15,    // b.bb...
    -18,   // w.bb...
    35,    // .bbb...
    447,   // bbbb...
    -76,   // wbbb...
    -82,   // .wbb...
    -78,   // bwbb...
    107,   // wwbb...
    105,   // ..wb...
    41,    // b.wb...
    44,    // w.wb...
    -62,   // .bwb...
    -95,   // bbwb...
    -14,   // wbwb...
    -16,   // .wwb...
    -118,  // bwwb...
    80,    // wwwb...
    52,    // ...w...
    88,    // b..w...
    80,    // w..w...
    -28,   // .b.w...
    185,   // bb.w...
    142,   // wb.w...
    -4,    // .w.w...
    49,    // bw.w...
    -164,  // ww.w...
    -105,  // ..bw...
    -44,   // b.bw...
    -41,   // w.bw...
    16,    // .bbw...
    -80,   // bbbw...
    118,   // wbbw...
    62,    // .wbw...
    14,    // bwbw...
    95,    // wwbw...
    30,    // ..ww...
    18,    // b.ww...
    -15,   // w.ww...
    82,    // .bww...
    -107,  // bbww...
    78,    // wbww...
    -35,   // .www...
    76,    // bwww...
    -447,  // wwww...
    13,    // ....b..
    29,    // b...b..
    66,    // w...b..
    -36,   // .b..b..
    136,   // bb..b..
    -27,   // wb..b..
    9,     // .w..b..
    37,    // bw..b..
    -57,   // ww..b..
    -31,   // ..b.b..
    45,    // b.b.b..
    14,    // w.b.b..
    56,    // .bb.b..
    176,   // bbb.b..
    100,   // wbb.b..
    94,    // .wb.b..
    -147,  // bwb.b..
    74,    // wwb.b..
    0,     // ..w.b..
    -12,   // b.w.b..
    -71,   // w.w.b..
    113,   // .bw.b..
    51,    // bbw.b..
    -33,   // wbw.b..
    115,   // .ww.b..
    20,    // bww.b..
    -60,   // www.b..
    -30,   // ...bb..
    102,   // b..bb..
    -23,   // w..bb..
    -149,  // .b.bb..
    83,    // bb.bb..
    111,   // wb.bb..
    -56,   // .w.bb..
    -129,  // bw.bb..
    80,    // ww.bb..
    34,    // ..bbb..
    153,   // b.bbb..
    -54,   // w.bbb..
    359,   // .bbbb..
    -7,    // bbbbb..
    15,    // wbbbb..
    -254,  // .wbbb..
    -79,   // bwbbb..
    77,    // wwbbb..
    93,    // ..wbb..
    -177,  // b.wbb..
    -136,  // w.wbb..
    -176,  // .bwbb..
    106,   // bbwbb..
    114,   // wbwbb..
    -49,   // .wwbb..
    87,    // bwwbb..
    -73,   // wwwbb..
    -105,  // ...wb..
    -21,   // b..wb..
    -13,   // w..wb..
    -11,   // .b.wb..
    -54,   // bb.wb..
    -16,   // wb.wb..
    -25,   // .w.wb..
    150,   // bw.wb..
    -121,  // ww.wb..
    98,    // ..bwb..
    22,    // b.bwb..
    3,     // w.bwb..
    -49,   // .bbwb..
    -154,  // bbbwb..
    -48,   // wbbwb..
    -80,   // .wbwb..
    35,    // bwbwb..
    -92,   // wwbwb..
    -93,   // ..wwb..
    -51,   // b.wwb..
    34,    // w.wwb..
    81,    // .bwwb..
    108,   // bbwwb..
    58,    // wbwwb..
    -136,  // .wwwb..
    -22,   // bwwwb..
    -48,   // wwwwb..
    -13,   // ....w..
    -66,   // b...w..
    -29,   // w...w..
    -9,    // .b..w..
    57,    // bb..w..
    -37,   // wb..w..
    36,    // .w..w..
    27,    // bw..w..
    -136,  // ww..w..
    0,     // ..b.w..
    71,    // b.b.w..
    12,    // w.b.w..
    -115,  // .bb.w..
    60,    // bbb.w..
    -20,   // wbb.w..
    -113,  // .wb.w..
    33,    // bwb.w..
    -51,   // wwb.w..
    31,    // ..w.w..
    -14,   // b.w.w..
    -45,   // w.w.w..
    -94,   // .bw.w..
    -74,   // bbw.w..
    147,   // wbw.w..
    -56,   // .ww.w..
    -100,  // bww.w..
    -176,  // www.w..
    105,   // ...bw..
    13,    // b..bw..
    21,    // w..bw..
    25,    // .b.bw..
    121,   // bb.bw..
    -150,  // wb.bw..
    11,    // .w.bw..
    16,    // bw.bw..
    54,    // ww.bw..
    93,    // ..bbw..
    -34,   // b.bbw..
    51,    // w.bbw..
    136,   // .bbbw..
    48,    // bbbbw..
    22,    // wbbbw..
    -81,   // .wbbw..
    -58,   // bwbbw..
    -108,  // wwbbw..
    -98,   // ..wbw..
    -3,    // b.wbw..
    -22,   // w.wbw..
    80,    // .bwbw..
    92,    // bbwbw..
    -35,   // wbwbw..
    49,    // .wwbw..
    48,    // bwwbw..
    154,   // wwwbw..
    30,    // ...ww..
    23,    // b..ww..
    -102,  // w..ww..
    56,    // .b.ww..
    -80,   // bb.ww..
    129,   // wb.ww..
    149,   // .w.ww..
    -111,  // bw.ww..
    -83,   // ww.ww..
    -93,   // ..bww..
    136,   // b.bww..
    177,   // w.bww..
    49,    // .bbww..
    73,    // bbbww..
    -87,   // wbbww..
    176,   // .wbww..
    -114,  // bwbww..
    -106,  // wwbww..
    -34,   // ..www..
    54,    // b.www..
    -153,  // w.www..
    254,   // .bwww..
    -77,   // bbwww..
    79,    // wbwww..
    -359,  // .wwww..
    -15,   // bwwww..
    7,     // wwwww..
    -52,   // .....b.
    -178,  // b....b.
    108,   // w....b.
    4,     // .b...b.
    -132,  // bb...b.
    -1,    // wb...b.
    0,     // .w...b.
    -61,   // bw...b.
    35,    // ww...b.
    -36,   // ..b..b.
    67,    // b.b..b.
    -32,   // w.b..b.
    20,    // .bb..b.
    33,    // bbb..b.
    100,   // wbb..b.
    2,     // .wb..b.
    -192,  // bwb..b.
    -78,   // wwb..b.
    -9,    // ..w..b.
    12,    // b.w..b.
    -23,   // w.w..b.
    57,    // .bw..b.
    34,    // bbw..b.
    76,    // wbw..b.
    62,    // .ww..b.
    30,    // bww..b.
    80,    // www..b.
    4,     // ...b.b.
    -72,   // b..b.b.
    -149,  // w..b.b.
    -26,   // .b.b.b.
    -19,   // bb.b.b.
    -113,  // wb.b.b.
    -72,   // .w.b.b.
    146,   // bw.b.b.
    -42,   // ww.b.b.
    -149,  // ..bb.b.
    112,   // b.bb.b.
    66,    // w.bb.b.
    136,   // .bbb.b.
    60,    // bbbb.b.
    221,   // wbbb.b.
    -13,   // .wbb.b.
    -21,   // bwbb.b.
    -75,   // wwbb.b.
    25,    // ..wb.b.
    -22,   // b.wb.b.
    -61,   // w.wb.b.
    -16,   // .bwb.b.
    -20,   // bbwb.b.
    -75,   // wbwb.b.
    18,    // .wwb.b.
    -150,  // bwwb.b.
    -146,  // wwwb.b.
    -28,   // ...w.b.
    3,     // b..w.b.
    73,    // w..w.b.
    20,    // .b.w.b.
    12,    // bb.w.b.
    -132,  // wb.w.b.
    72,    // .w.w.b.
    101,   // bw.w.b.
    13,    // ww.w.b.
    -11,   // ..bw.b.
    -61,   // b.bw.b.
    -30,   // w.bw.b.
    45,    // .bbw.b.
    34,    // bbbw.b.
    81,    // wbbw.b.
    49,    // .wbw.b.
    -211,  // bwbw.b.
    -218,  // wwbw.b.
    56,    // ..ww.b.
    -23,   // b.ww.b.
    -62,   // w.ww.b.
    79,    // .bww.b.
    -72,   // bbww.b.
    -45,   // wbww.b.
    -40,   // .www.b.
    76,    // bwww.b.
    -225,  // wwww.b.
    -114,  // ....bb.
    -148,  // b...bb.
    -1,    // w...bb.
    20,    // .b..bb.
    54,    // bb..bb.
    5,     // wb..bb.
    -62,   // .w..bb.
    8,     // bw..bb.
    -98,   // ww..bb.
    56,    // ..b.bb.
    67,    // b.b.bb.
    64,    // w.b.bb.
    197,   // .bb.bb.
    -79,   // bbb.bb.
    94,    // wbb.bb.
    101,   // .wb.bb.
    46,    // bwb.bb.
    53,    // wwb.bb.
    -115,  // ..w.bb.
    -177,  // b.w.bb.
    47,    // w.w.bb.
    15,    // .bw.bb.
    -5,    // bbw.bb.
    29,    // wbw.bb.
    0,     // .ww.bb.
    76,    // bww.bb.
    -48,   // www.bb.
    35,    // ...bbb.
    -33,   // b..bbb.
    -24,   // w..bbb.
    136,   // .b.bbb.
    -150,  // bb.bbb.
    -87,   // wb.bbb.
    40,    // .w.bbb.
    -149,  // bw.bbb.
    -30,   // ww.bbb.
    359,   // ..bbbb.
    30,    // b.bbbb.
    127,   // w.bbbb.
    57,    // .bbbbb.
    179,   // bbbbbb.
    -162,  // wbbbbb.
    76,    // .wbbbb.
    109,   // bwbbbb.
    -46,   // wwbbbb.
    136,   // ..wbbb.
    -58,   // b.wbbb.
    42,    // w.wbbb.
    -53,   // .bwbbb.
    -111,  // bbwbbb.
    -226,  // wbwbbb.
    -31,   // .wwbbb.
    -96,   // bwwbbb.
    112,   // wwwbbb.
    16,    // ...wbb.
    66,    // b..wbb.
    -55,   // w..wbb.
    45,    // .b.wbb.
    -22,   // bb.wbb.
    -16,   // wb.wbb.
    -18,   // .w.wbb.
    22,    // bw.wbb.
    14,    // ww.wbb.
    -49,   // ..bwbb.
    66,    // b.bwbb.
    -21,   // w.bwbb.
    73,    // .bbwbb.
    226,   // bbbwbb.
    115,   // wbbwbb.
    -4,    // .wbwbb.
    -192,  // bwbwbb.
    -74,   // wwbwbb.
    49,    // ..wwbb.
    35,    // b.wwbb.
    13,    // w.wwbb.
    92,    // .bwwbb.
    -34,   // bbwwbb.
    129,   // wbwwbb.
    31,    // .wwwbb.
    -48,   // bwwwbb.
    -33,   // wwwwbb.
    107,   // ....wb.
    -186,  // b...wb.
    65,    // w...wb.
    57,    // .b..wb.
    -67,   // bb..wb.
    -18,   // wb..wb.
    -2,    // .w..wb.
    38,    // bw..wb.
    58,    // ww..wb.
    113,   // ..b.wb.
    -153,  // b.b.wb.
    -118,  // w.b.wb.
    15,    // .bb.wb.
    -180,  // bbb.wb.
    -240,  // wbb.wb.
    0,     // .wb.wb.
    5,     // bwb.wb.
    71,    // wwb.wb.
    -94,   // ..w.wb.
    32,    // b.w.wb.
    -44,   // w.w.wb.
    40,    // .bw.wb.
    2,     // bbw.wb.
    -59,   // wbw.wb.
    -101,  // .ww.wb.
    94,    // bww.wb.
    204,   // www.wb.
    -62,   // ...bwb.
    -58,   // b..bwb.
    -77,   // w..bwb.
    -16,   // .b.bwb.
    -44,   // bb.bwb.
    -22,   // wb.bwb.
    -49,   // .w.bwb.
    65,    // bw.bwb.
    -183,  // ww.bwb.
    -176,  // ..bbwb.
    -33,   // b.bbwb.
    33,    // w.bbwb.
    -53,   // .bbbwb.
    41,    // bbbbwb.
    -77,   // wbbbwb.
    81,    // .wbbwb.
    -43,   // bwbbwb.
    -58,   // wwbbwb.
    80,    // ..wbwb.
    98,    // b.wbwb.
    107,   // w.wbwb.
    -5,    // .bwbwb.
    113,   // bbwbwb.
    -158,  // wbwbwb.
    4,     // .wwbwb.
    24,    // bwwbwb.
    -71,   // wwwbwb.
    82,    // ...wwb.
    -123,  // b..wwb.
    4,     // w..wwb.
    79,    // .b.wwb.
    34,    // bb.wwb.
    124,   // wb.wwb.
    13,    // .w.wwb.
    109,   // bw.wwb.
    128,   // ww.wwb.
    81,    // ..bwwb.
    98,    // b.bwwb.
    50,    // w.bwwb.
    92,    // .bbwwb.
    3,     // bbbwwb.
    -13,   // wbbwwb.
    -81,   // .wbwwb.
    -78,   // bwbwwb.
    6,     // wwbwwb.
    254,   // ..wwwb.
    32,    // b.wwwb.
    -176,  // w.wwwb.
    -8,    // .bwwwb.
    95,    // bbwwwb.
    127,   // wbwwwb.
    -76,   // .wwwwb.
    124,   // bwwwwb.
    8,     // wwwwwb.
    52,    // .....w.
    -108,  // b....w.
    178,   // w....w.
    0,     // .b...w.
    -35,   // bb...w.
    61,    // wb...w.
    -4,    // .w...w.
    1,     // bw...w.
    132,   // ww...w.
    9,     // ..b..w.
    23,    // b.b..w.
    -12,   // w.b..w.
    -62,   // .bb..w.
    -80,   // bbb..w.
    -30,   // wbb..w.
    -57,   // .wb..w.
    -76,   // bwb..w.
    -34,   // wwb..w.
    36,    // ..w..w.
    32,    // b.w..w.
    -67,   // w.w..w.
    -2,    // .bw..w.
    78,    // bbw..w.
    192,   // wbw..w.
    -20,   // .ww..w.
    -100,  // bww..w.
    -33,   // www..w.
    28,    // ...b.w.
    -73,   // b..b.w.
    -3,    // w..b.w.
    -72,   // .b.b.w.
    -13,   // bb.b.w.
    -101,  // wb.b.w.
    -20,   // .w.b.w.
    132,   // bw.b.w.
    -12,   // ww.b.w.
    -56,   // ..bb.w.
    62,    // b.bb.w.
    23,    // w.bb.w.
    40,    // .bbb.w.
    225,   // bbbb.w.
    -76,   // wbbb.w.
    -79,   // .wbb.w.
    45,    // bwbb.w.
    72,    // wwbb.w.
    11,    // ..wb.w.
    30,    // b.wb.w.
    61,    // w.wb.w.
    -49,   // .bwb.w.
    218,   // bbwb.w.
    211,   // wbwb.w.
    -45,   // .wwb.w.
    -81,   // bwwb.w.
    -34,   // wwwb.w.
    -4,    // ...w.w.
    149,   // b..w.w.
    72,    // w..w.w.
    72,    // .b.w.w.
    42,    // bb.w.w.
    -146,  // wb.w.w.
    26,    // .w.w.w.
    113,   // bw.w.w.
    19,    // ww.w.w.
    -25,   // ..bw.w.
    61,    // b.bw.w.
    22,    // w.bw.w.
    -18,   // .bbw.w.
    146,   // bbbw.w.
    150,   // wbbw.w.
    16,    // .wbw.w.
    75,    // bwbw.w.
    20,    // wwbw.w.
    149,   // ..ww.w.
    -66,   // b.ww.w.
    -112,  // w.ww.w.
    13,    // .bww.w.
    75,    // bbww.w.
    21,    // wbww.w.
    -136,  // .www.w.
    -221,  // bwww.w.
    -60,   // wwww.w.
    -107,  // ....bw.
    -65,   // b...bw.
    186,   // w...bw.
    2,     // .b..bw.
    -58,   // bb..bw.
    -38,   // wb..bw.
    -57,   // .w..bw.
    18,    // bw..bw.
    67,    // ww..bw.
    94,    // ..b.bw.
    44,    // b.b.bw.
    -32,   // w.b.bw.
    101,   // .bb.bw.
    -204,  // bbb.bw.
    -94,   // wbb.bw.
    -40,   // .wb.bw.
    59,    // bwb.bw.
    -2,    // wwb.bw.
    -113,  // ..w.bw.
    118,   // b.w.bw.
    153,   // w.w.bw.
    0,     // .bw.bw.
    -71,   // bbw.bw.
    -5,    // wbw.bw.
    -15,   // .ww.bw.
    240,   // bww.bw.
    180,   // www.bw.
    -82,   // ...bbw.
    -4,    // b..bbw.
    123,   // w..bbw.
    -13,   // .b.bbw.
    -128,  // bb.bbw.
    -109,  // wb.bbw.
    -79,   // .w.bbw.
    -124,  // bw.bbw.
    -34,   // ww.bbw.
    -254,  // ..bbbw.
    176,   // b.bbbw.
    -32,   // w.bbbw.
    76,    // .bbbbw.
    -8,    // bbbbbw.
    -124,  // wbbbbw.
    8,     // .wbbbw.
    -127,  // bwbbbw.
    -95,   // wwbbbw.
    -81,   // ..wbbw.
    -50,   // b.wbbw.
    -98,   // w.wbbw.
    81,    // .bwbbw.
    -6,    // bbwbbw.
    78,    // wbwbbw.
    -92,   // .wwbbw.
    13,    // bwwbbw.
    -3,    // wwwbbw.
    62,    // ...wbw.
    77,    // b..wbw.
    58,    // w..wbw.
    49,    // .b.wbw.
    183,   // bb.wbw.
    -65,   // wb.wbw.
    16,    // .w.wbw.
    22,    // bw.wbw.
    44,    // ww.wbw.
    -80,   // ..bwbw.
    -107,  // b.bwbw.
    -98,   // w.bwbw.
    -4,    // .bbwbw.
    71,    // bbbwbw.
    -24,   // wbbwbw.
    5,     // .wbwbw.
    158,   // bwbwbw.
    -113,  // wwbwbw.
    176,   // ..wwbw.
    -33,   // b.wwbw.
    33,    // w.wwbw.
    -81,   // .bwwbw.
    58,    // bbwwbw.
    43,    // wbwwbw.
    53,    // .wwwbw.
    77,    // bwwwbw.
    -41,   // wwwwbw.
    114,   // ....ww.
    1,     // b...ww.
    148,   // w...ww.
    62,    // .b..ww.
    98,    // bb..ww.
    -8,    // wb..ww.
    -20,   // .w..ww.
    -5,    // bw..ww.
    -54,   // ww..ww.
    115,   // ..b.ww.
    -47,   // b.b.ww.
    177,   // w.b.ww.
    0,     // .bb.ww.
    48,    // bbb.ww.
    -76,   // wbb.ww.
    -15,   // .wb.ww.
    -29,   // bwb.ww.
    5,     // wwb.ww.
    -56,   // ..w.ww.
    -64,   // b.w.ww.
    -67,   // w.w.ww.
    -101,  // .bw.ww.
    -53,   // bbw.ww.
    -46,   // wbw.ww.
    -197,  // .ww.ww.
    -94,   // bww.ww.
    79,    // www.ww.
    -16,   // ...bww.
    55,    // b..bww.
    -66,   // w..bww.
    18,    // .b.bww.
    -14,   // bb.bww.
    -22,   // wb.bww.
    -45,   // .w.bww.
    16,    // bw.bww.
    22,    // ww.bww.
    -49,   // ..bbww.
    -13,   // b.bbww.
    -35,   // w.bbww.
    -31,   // .bbbww.
    33,    // bbbbww.
    48,    // wbbbww.
    -92,   // .wbbww.
    -129,  // bwbbww.
    34,    // wwbbww.
    49,    // ..wbww.
    21,    // b.wbww.
    -66,   // w.wbww.
    4,     // .bwbww.
    74,    // bbwbww.
    192,   // wbwbww.
    -73,   // .wwbww.
    -115,  // bwwbww.
    -226,  // wwwbww.
    -35,   // ...www.
    24,    // b..www.
    33,    // w..www.
    -40,   // .b.www.
    30,    // bb.www.
    149,   // wb.www.
    -136,  // .w.www.
    87,    // bw.www.
    150,   // ww.www.
    -136,  // ..bwww.
    -42,   // b.bwww.
    58,    // w.bwww.
    31,    // .bbwww.
    -112,  // bbbwww.
    96,    // wbbwww.
    53,    // .wbwww.
    226,   // bwbwww.
    111,   // wwbwww.
    -359,  // ..wwww.
    -127,  // b.wwww.
    -30,   // w.wwww.
    -76,   // .bwwww.
    46,    // bbwwww.
    -109,  // wbwwww.
    -57,   // .wwwww.
    162,   // bwwwww.
    -179,  // wwwwww.
    26,    // ......b
    -54,   // b.....b
    0,     // w.....b
    -178,  // .b....b
    -46,   // bb....b
    78,    // wb....b
    -108,  // .w....b
    -6,    // bw....b
    -172,  // ww....b
    29,    // ..b...b
    19,    // b.b...b
    159,   // w.b...b
    -148,  // .bb...b
    -31,   // bbb...b
    -40,   // wbb...b
    -65,   // .wb...b
    -91,   // bwb...b
    45,    // wwb...b
    -66,   // ..w...b
    -266,  // b.w...b
    18,    // w.w...b
    -186,  // .bw...b
    60,    // bbw...b
    -81,   // wbw...b
    1,     // .ww...b
    -44,   // bww...b
    -80,   // www...b
    -80,   // ...b..b
    100,   // b..b..b
    -153,  // w..b..b
    -72,   // .b.b..b
    -98,   // bb.b..b
    111,   // wb.b..b
    -73,   // .w.b..b
    -21,   // bw.b..b
    146,   // ww.b..b
    102,   // ..bb..b
    64,    // b.bb..b
    134,   // w.bb..b
    -33,   // .bbb..b
    -51,   // bbbb..b
    -100,  // wbbb..b
    -4,    // .wbb..b
    9,     // bwbb..b
    -107,  // wwbb..b
    13,    // ..wb..b
    -4,    // b.wb..b
    -151,  // w.wb..b
    -58,   // .bwb..b
    -3,    // bbwb..b
    55,    // wbwb..b
    55,    // .wwb..b
    120,   // bwwb..b
    -67,   // wwwb..b
    88,    // ...w..b
    12,    // b..w..b
    153,   // w..w..b
    3,     // .b.w..b
    -36,   // bb.w..b
    94,    // wb.w..b
    149,   // .w.w..b
    -118,  // bw.w..b
    11,    // ww.w..b
    -21,   // ..bw..b
    -76,   // b.bw..b
    -45,   // w.bw..b
    66,    // .bbw..b
    42,    // bbbw..b
    -9,    // wbbw..b
    77,    // .wbw..b
    116,   // bwbw..b
    2,     // wwbw..b
    23,    // ..ww..b
    -9,    // b.ww..b
    -132,  // w.ww..b
    -123,  // .bww..b
    -62,   // bbww..b
    -86,   // wbww..b
    24,    // .www..b
    0,     // bwww..b
    -94,   // wwww..b
    47,    // ....b.b
    19,    // b...b.b
    -18,   // w...b.b
    67,    // .b..b.b
    20,    // bb..b.b
    -56,   // wb..b.b
    23,    // .w..b.b
    -86,   // bw..b.b
    33,    // ww..b.b
    45,    // ..b.b.b
    -106,  // b.b.b.b
    49,    // w.b.b.b
    67,    // .bb.b.b
    -17,   // bbb.b.b
    -147,  // wbb.b.b
    44,    // .wb.b.b
    58,    // bwb.b.b
    198,   // wwb.b.b
    71,    // ..w.b.b
    -55,   // b.w.b.b
    0,     // w.w.b.b
    -153,  // .bw.b.b
    -9,    // bbw.b.b
    -16,   // wbw.b.b
    -47,   // .ww.b.b
    19,    // bww.b.b
    53,    // www.b.b
    15,    // ...bb.b
    64,    // b..bb.b
    132,   // w..bb.b
    112,   // .b.bb.b
    -110,  // bb.bb.b
    162,   // wb.bb.b
    62,    // .w.bb.b
    -24,   // bw.bb.b
    135,   // ww.bb.b
    153,   // ..bbb.b
    -138,  // b.bbb.b
    -83,   // w.bbb.b
    30,    // .bbbb.b
    60,    // bbbbb.b
    -35,   // wbbbb.b
    176,   // .wbbb.b
    -70,   // bwbbb.b
    -39,   // wwbbb.b
    -34,   // ..wbb.b
    26,    // b.wbb.b
    48,    // w.wbb.b
    -33,   // .bwbb.b
    95,    // bbwbb.b
    36,    // wbwbb.b
    -13,   // .wwbb.b
    -2,    // bwwbb.b
    60,    // wwwbb.b
    -44,   // ...wb.b
    -76,   // b..wb.b
    151,   // w..wb.b
    -61,   // .b.wb.b
    -35,   // bb.wb.b
    -36,   // wb.wb.b
    61,    // .w.wb.b
    -91,   // bw.wb.b
    100,   // ww.wb.b
    22,    // ..bwb.b
    -19,   // b.bwb.b
    157,   // w.bwb.b
    66,    // .bbwb.b
    -39,   // bbbwb.b
    -63,   // wbbwb.b
    -107,  // .wbwb.b
    -121,  // bwbwb.b
    74,    // wwbwb.b
    136,   // ..wwb.b
    82,    // b.wwb.b
    -48,   // w.wwb.b
    98,    // .bwwb.b
    29,    // bbwwb.b
    164,   // wbwwb.b
    -42,   // .wwwb.b
    -31,   // bwwwb.b
    -29,   // wwwwb.b
    -18,   // ....w.b
    -266,  // b...w.b
    -159,  // w...w.b
    12,    // .b..w.b
    -147,  // bb..w.b
    -2,    // wb..w.b
    32,    // .w..w.b
    -27,   // bw..w.b
    56,    // ww..w.b
    -12,   // ..b.w.b
    -55,   // b.b.w.b
    0,     // w.b.w.b
    -177,  // .bb.w.b
    -84,   // bbb.w.b
    45,    // wbb.w.b
    118,   // .wb.w.b
    -74,   // bwb.w.b
    -43,   // wwb.w.b
    -14,   // ..w.w.b
    86,    // b.w.w.b
    -49,   // w.w.w.b
    32,    // .bw.w.b
    89,    // bbw.w.b
    34,    // wbw.w.b
    -64,   // .ww.w.b
    -48,   // bww.w.b
    -72,   // www.w.b
    41,    // ...bw.b
    -4,    // b..bw.b
    45,    // w..bw.b
    -22,   // .b.bw.b
    2,     // bb.bw.b
    -112,  // wb.bw.b
    30,    // .w.bw.b
    -29,   // bw.bw.b
    127,   // ww.bw.b
    -177,  // ..bbw.b
    26,    // b.bbw.b
    -36,   // w.bbw.b
    -58,   // .bbbw.b
    -183,  // bbbbw.b
    -65,   // wbbbw.b
    -50,   // .wbbw.b
    45,    // bwbbw.b
    -64,   // wwbbw.b
    -3,    // ..wbw.b
    -124,  // b.wbw.b
    -157,  // w.wbw.b
    98,    // .bwbw.b
    -23,   // bbwbw.b
    1,     // wbwbw.b
    21,    // .wwbw.b
    -103,  // bwwbw.b
    -85,   // wwwbw.b
    18,    // ...ww.b
    -9,    // b..ww.b
    -134,  // w..ww.b
    -23,   // .b.ww.b
    -76,   // bb.ww.b
    -163,  // wb.ww.b
    -66,   // .w.ww.b
    -56,   // bw.ww.b
    106,   // ww.ww.b
    -51,   // ..bww.b
    82,    // b.bww.b
    36,    // w.bww.b
    35,    // .bbww.b
    -58,   // bbbww.b
    69,    // wbbww.b
    -33,   // .wbww.b
    35,    // bwbww.b
    68,    // wwbww.b
    54,    // ..www.b
    148,   // b.www.b
    83,    // w.www.b
    32,    // .bwww.b
    -221,  // bbwww.b
    -244,  // wbwww.b
    -127,  // .wwww.b
    35,    // bwwww.b
    20,    // wwwww.b
    100,   // .....bb
    -46,   // b....bb
    172,   // w....bb
    -132,  // .b...bb
    -134,  // bb...bb
    32,    // wb...bb
    -35,   // .w...bb
    -7,    // bw...bb
    0,     // ww...bb
    136,   // ..b..bb
    20,    // b.b..bb
    -56,   // w.b..bb
    54,    // .bb..bb
    111,   // bbb..bb
    197,   // wbb..bb
    -58,   // .wb..bb
    -87,   // bwb..bb
    -23,   // wwb..bb
    57,    // ..w..bb
    -147,  // b.w..bb
    -33,   // w.w..bb
    -67,   // .bw..bb
    -14,   // bbw..bb
    106,   // wbw..bb
    98,    // .ww..bb
    -10,   // bww..bb
    78,    // www..bb
    164,   // ...b.bb
    -98,   // b..b.bb
    -11,   // w..b.bb
    -19,   // .b.b.bb
    110,   // bb.b.bb
    13,    // wb.b.bb
    -13,   // .w.b.bb
    67,    // bw.b.bb
    42,    // ww.b.bb
    83,    // ..bb.bb
    -110,  // b.bb.bb
    -106,  // w.bb.bb
    -150,  // .bbb.bb
    -78,   // bbbb.bb
    -17,   // wbbb.bb
    -128,  // .wbb.bb
    56,    // bwbb.bb
    -81,   // wwbb.bb
    121,   // ..wb.bb
    2,     // b.wb.bb
    -100,  // w.wb.bb
    -44,   // .bwb.bb
    105,   // bbwb.bb
    35,    // wbwb.bb
    -14,   // .wwb.bb
    88,    // bwwb.bb
    -22,   // wwwb.bb
    185,   // ...w.bb
    -36,   // b..w.bb
    -146,  // w..w.bb
    12,    // .b.w.bb
    21,    // bb.w.bb
    -60,   // wb.w.bb
    42,    // .w.w.bb
    9,     // bw.w.bb
    -42,   // ww.w.bb
    -54,   // ..bw.bb
    -35,   // b.bw.bb
    -127,  // w.bw.bb
    -22,   // .bbw.bb
    51,    // bbbw.bb
    35,    // wbbw.bb
    183,   // .wbw.bb
    42,    // bwbw.bb
    -49,   // wwbw.bb
    -80,   // ..ww.bb
    -76,   // b.ww.bb
    -135,  // w.ww.bb
    34,    // .bww.bb
    -8,    // bbww.bb
    -32,   // wbww.bb
    30,    // .www.bb
    158,   // bwww.bb
    -135,  // wwww.bb
    181,   // ....bbb
    -31,   // b...bbb
    80,    // w...bbb
    33,    // .b..bbb
    111,   // bb..bbb
    -103,  // wb..bbb
    -80,   // .w..bbb
    18,    // bw..bbb
    -78,   // ww..bbb
    176,   // ..b.bbb
    -17,   // b.b.bbb
    72,    // w.b.bbb
    -79,   // .bb.bbb
    -20,   // bbb.bbb
    108,   // wbb.bbb
    -204,  // .wb.bbb
    19,    // bwb.bbb
    -139,  // wwb.bbb
    60,    // ..w.bbb
    -84,   // b.w.bbb
    -53,   // w.w.bbb
    -180,  // .bw.bbb
    0,     // bbw.bbb
    -102,  // wbw.bbb
    48,    // .ww.bbb
    -28,   // bww.bbb
    0,     // www.bbb
    447,   // ...bbbb
    -51,   // b..bbbb
    94,    // w..bbbb
    60,    // .b.bbbb
    -78,   // bb.bbbb
    -3,    // wb.bbbb
    225,   // .w.bbbb
    -45,   // bw.bbbb
    135,   // ww.bbbb
    -7,    // ..bbbbb
    60,    // b.bbbbb
    -20,   // w.bbbbb
    179,   // .bbbbbb
    5,     // bbbbbbb
    90,    // wbbbbbb
    -8,    // .wbbbbb
    -25,   // bwbbbbb
    5,     // wwbbbbb
    48,    // ..wbbbb
    -183,  // b.wbbbb
    29,    // w.wbbbb
    41,    // .bwbbbb
    50,    // bbwbbbb
    40,    // wbwbbbb
    33,    // .wwbbbb
    39,    // bwwbbbb
    -67,   // wwwbbbb
    -80,   // ...wbbb
    42,    // b..wbbb
    67,    // w..wbbb
    34,    // .b.wbbb
    51,    // bb.wbbb
    -12,   // wb.wbbb
    146,   // .w.wbbb
    77,    // bw.wbbb
    22,    // ww.wbbb
    -154,  // ..bwbbb
    -39,   // b.bwbbb
    85,    // w.bwbbb
    226,   // .bbwbbb
    -11,   // bbbwbbb
    116,   // wbbwbbb
    71,    // .wbwbbb
    -54,   // bwbwbbb
    64,    // wwbwbbb
    73,    // ..wwbbb
    -58,   // b.wwbbb
    -60,   // w.wwbbb
    3,     // .bwwbbb
    3,     // bbwwbbb
    9,     // wbwwbbb
    -112,  // .wwwbbb
    69,    // bwwwbbb
    67,    // wwwwbbb
    -88,   // ....wbb
    60,    // b...wbb
    -45,   // w...wbb
    34,    // .b..wbb
    -14,   // bb..wbb
    -87,   // wb..wbb
    78,    // .w..wbb
    -23,   // bw..wbb
    23,    // ww..wbb
    51,    // ..b.wbb
    -9,    // b.b.wbb
    43,    // w.b.wbb
    -5,    // .bb.wbb
    0,     // bbb.wbb
    84,    // wbb.wbb
    -71,   // .wb.wbb
    6,     // bwb.wbb
    0,     // wwb.wbb
    -74,   // ..w.wbb
    89,    // b.w.wbb
    -198,  // w.w.wbb
    2,     // .bw.wbb
    151,   // bbw.wbb
    27,    // wbw.wbb
    -53,   // .ww.wbb
    -98,   // bww.wbb
    139,   // www.wbb
    -95,   // ...bwbb
    -3,    // b..bwbb
    -2,    // w..bwbb
    -20,   // .b.bwbb
    105,   // bb.bwbb
    12,    // wb.bwbb
    218,   // .w.bwbb
    19,    // bw.bwbb
    49,    // ww.bwbb
    106,   // ..bbwbb
    95,    // b.bbwbb
    -68,   // w.bbwbb
    -111,  // .bbbwbb
    50,    // bbbbwbb
    -22,   // wbbbwbb
    -6,    // .wbbwbb
    -122,  // bwbbwbb
    173,   // wwbbwbb
    92,    // ..wbwbb
    -23,   // b.wbwbb
    -74,   // w.wbwbb
    113,   // .bwbwbb
    121,   // bbwbwbb
    37,    // wbwbwbb
    74,    // .wwbwbb
    13,    // bwwbwbb
    -64,   // wwwbwbb
    -107,  // ...wwbb
    -62,   // b..wwbb
    107,   // w..wwbb
    -72,   // .b.wwbb
    -8,    // bb.wwbb
    198,   // wb.wwbb
    75,    // .w.wwbb
    -115,  // bw.wwbb
    81,    // ww.wwbb
    108,   // ..bwwbb
    29,    // b.bwwbb
    64,    // w.bwwbb
    -34,   // .bbwwbb
    3,     // bbbwwbb
    -46,   // wbbwwbb
    58,    // .wbwwbb
    -94,   // bwbwwbb
    -173,  // wwbwwbb
    -77,   // ..wwwbb
    -221,  // b.wwwbb
    39,    // w.wwwbb
    95,    // .bwwwbb
    -69,   // bbwwwbb
    24,    // wbwwwbb
    46,    // .wwwwbb
    39,    // bwwwwbb
    -5,    // wwwwwbb
    20,    // .....wb
    -6,    // b....wb
    -78,   // w....wb
    -61,   // .b...wb
    -7,    // bb...wb
    0,     // wb...wb
    1,     // .w...wb
    14,    // bw...wb
    -32,   // ww...wb
    37,    // ..b..wb
    -86,   // b.b..wb
    2,     // w.b..wb
    8,     // .bb..wb
    18,    // bbb..wb
    34,    // wbb..wb
    18,    // .wb..wb
    136,   // bwb..wb
    87,    // wwb..wb
    27,    // ..w..wb
    -27,   // b.w..wb
    56,    // w.w..wb
    38,    // .bw..wb
    -23,   // bbw..wb
    -267,  // wbw..wb
    -5,    // .ww..wb
    -68,   // bww..wb
    103,   // www..wb
    -142,  // ...b.wb
    -21,   // b..b.wb
    -94,   // w..b.wb
    146,   // .b.b.wb
    67,    // bb.b.wb
    37,    // wb.b.wb
    132,   // .w.b.wb
    -174,  // bw.b.wb
    60,    // ww.b.wb
    -129,  // ..bb.wb
    -24,   // b.bb.wb
    163,   // w.bb.wb
    -149,  // .bbb.wb
    -45,   // bbbb.wb
    27,    // wbbb.wb
    -124,  // .wbb.wb
    -54,   // bwbb.wb
    -198,  // wwbb.wb
    16,    // ..wb.wb
    -29,   // b.wb.wb
    36,    // w.wb.wb
    65,    // .bwb.wb
    19,    // bbwb.wb
    -45,   // wbwb.wb
    16,    // .wwb.wb
    -45,   // bwwb.wb
    12,    // wwwb.wb
    49,    // ...w.wb
    -118,  // b..w.wb
    -111,  // w..w.wb
    101,   // .b.w.wb
    9,     // bb.w.wb
    -37,   // wb.w.wb
    113,   // .w.w.wb
    -51,   // bw.w.wb
    -13,   // ww.w.wb
    150,   // ..bw.wb
    -91,   // b.bw.wb
    112,   // w.bw.wb
    22,    // .bbw.wb
    77,    // bbbw.wb
    -198,  // wbbw.wb
    22,    // .wbw.wb
    -79,   // bwbw.wb
    -12,   // wwbw.wb
    -111,  // ..ww.wb
    -56,   // b.ww.wb
    -162,  // w.ww.wb
    109,   // .bww.wb
    -115,  // bbww.wb
    -67,   // wbww.wb
    87,    // .www.wb
    -124,  // bwww.wb
    3,     // wwww.wb
    -32,   // ....bwb
    -91,   // b...bwb
    81,    // w...bwb
    -192,  // .b..bwb
    -87,   // bb..bwb
    267,   // wb..bwb
    -76,   // .w..bwb
    136,   // bw..bwb
    -106,  // ww..bwb
    -147,  // ..b.bwb
    58,    // b.b.bwb
    -34,   // w.b.bwb
    46,    // .bb.bwb
    19,    // bbb.bwb
    27,    // wbb.bwb
    59,    // .wb.bwb
    58,    // bwb.bwb
    -27,   // wwb.bwb
    33,    // ..w.bwb
    -74,   // b.w.bwb
    16,    // w.w.bwb
    5,     // .bw.bwb
    6,     // bbw.bwb
    0,     // wbw.bwb
    -29,   // .ww.bwb
    -153,  // bww.bwb
    102,   // www.bwb
    -78,   // ...bbwb
    9,     // b..bbwb
    86,    // w..bbwb
    -21,   // .b.bbwb
    56,    // bb.bbwb
    67,    // wb.bbwb
    45,    // .w.bbwb
    -54,   // bw.bbwb
    32,    // ww.bbwb
    -79,   // ..bbbwb
    -70,   // b.bbbwb
    244,   // w.bbbwb
    109,   // .bbbbwb
    -25,   // bbbbbwb
    50,    // wbbbbwb
    -127,  // .wbbbwb
    1,     // bwbbbwb
    -24,   // wwbbbwb
    -58,   // ..wbbwb
    45,    // b.wbbwb
    -164,  // w.wbbwb
    -43,   // .bwbbwb
    -122,  // bbwbbwb
    51,    // wbwbbwb
    -129,  // .wwbbwb
    201,   // bwwbbwb
    -9,    // wwwbbwb
    14,    // ...wbwb
    116,   // b..wbwb
    -55,   // w..wbwb
    -211,  // .b.wbwb
    42,    // bb.wbwb
    45,    // wb.wbwb
    75,    // .w.wbwb
    -79,   // bw.wbwb
    -35,   // ww.wbwb
    35,    // ..bwbwb
    -121,  // b.bwbwb
    -1,    // w.bwbwb
    -192,  // .bbwbwb
    -54,   // bbbwbwb
    46,    // wbbwbwb
    158,   // .wbwbwb
    61,    // bwbwbwb
    -37,   // wwbwbwb
    -114,  // ..wwbwb
    35,    // b.wwbwb
    -36,   // w.wwbwb
    -78,   // .bwwbwb
    -94,   // bbwwbwb
    -51,   // wbwwbwb
    226,   // .wwwbwb
    -61,   // bwwwbwb
    -40,   // wwwwbwb
    163,   // ....wwb
    -44,   // b...wwb
    40,    // w...wwb
    30,    // .b..wwb
    -10,   // bb..wwb
    -34,   // wb..wwb
    -100,  // .w..wwb
    -68,   // bw..wwb
    -197,  // ww..wwb
    20,    // ..b.wwb
    19,    // b.b.wwb
    -45,   // w.b.wwb
    76,    // .bb.wwb
    -28,   // bbb.wwb
    0,     // wbb.wwb
    240,   // .wb.wwb
    -153,  // bwb.wwb
    -84,   // wwb.wwb
    -100,  // ..w.wwb
    -48,   // b.w.wwb
    147,   // w.w.wwb
    94,    // .bw.wwb
    -98,   // bbw.wwb
    -27,   // wbw.wwb
    -94,   // .ww.wwb
    57,    // bww.wwb
    -108,  // www.wwb
    -118,  // ...bwwb
    120,   // b..bwwb
    9,     // w..bwwb
    -150,  // .b.bwwb
    88,    // bb.bwwb
    198,   // wb.bwwb
    -81,   // .w.bwwb
    -45,   // bw.bwwb
    -35,   // ww.bwwb
    87,    // ..bbwwb
    -2,    // b.bbwwb
    -69,   // w.bbwwb
    -96,   // .bbbwwb
    39,    // bbbbwwb
    184,   // wbbbwwb
    13,    // .wbbwwb
    201,   // bwbbwwb
    46,    // wwbbwwb
    48,    // ..wbwwb
    -103,  // b.wbwwb
    63,    // w.wbwwb
    24,    // .bwbwwb
    13,    // bbwbwwb
    -46,   // wbwbwwb
    -115,  // .wwbwwb
    -19,   // bwwbwwb
    -116,  // wwwbwwb
    76,    // ...wwwb
    0,     // b..wwwb
    100,   // w..wwwb
    76,    // .b.wwwb
    158,   // bb.wwwb
    -27,   // wb.wwwb
    -221,  // .w.wwwb
    -124,  // bw.wwwb
    17,    // ww.wwwb
    -22,   // ..bwwwb
    -31,   // b.bwwwb
    65,    // w.bwwwb
    -48,   // .bbwwwb
    69,    // bbbwwwb
    -184,  // wbbwwwb
    77,    // .wbwwwb
    -61,   // bwbwwwb
    22,    // wwbwwwb
    -15,   // ..wwwwb
    35,    // b.wwwwb
    35,    // w.wwwwb
    124,   // .bwwwwb
    39,    // bbwwwwb
    -50,   // wbwwwwb
    162,   // .wwwwwb
    -112,  // bwwwwwb
    -90,   // wwwwwwb
    -26,   // ......w
    0,     // b.....w
    54,    // w.....w
    108,   // .b....w
    172,   // bb....w
    6,     // wb....w
    178,   // .w....w
    -78,   // bw....w
    46,    // ww....w
    66,    // ..b...w
    -18,   // b.b...w
    266,   // w.b...w
    -1,    // .bb...w
    80,    // bbb...w
    44,    // wbb...w
    186,   // .wb...w
    81,    // bwb...w
    -60,   // wwb...w
    -29,   // ..w...w
    -159,  // b.w...w
    -19,   // w.w...w
    65,    // .bw...w
    -45,   // bbw...w
    91,    // wbw...w
    148,   // .ww...w
    40,    // bww...w
    31,    // www...w
    -88,   // ...b..w
    -153,  // b..b..w
    -12,   // w..b..w
    -149,  // .b.b..w
    -11,   // bb.b..w
    118,   // wb.b..w
    -3,    // .w.b..w
    -94,   // bw.b..w
    36,    // ww.b..w
    -23,   // ..bb..w
    132,   // b.bb..w
    9,     // w.bb..w
    -24,   // .bbb..w
    94,    // bbbb..w
    0,     // wbbb..w
    123,   // .wbb..w
    86,    // bwbb..w
    62,    // wwbb..w
    21,    // ..wb..w
    45,    // b.wb..w
    76,    // w.wb..w
    -77,   // .bwb..w
    -2,    // bbwb..w
    -116,  // wbwb..w
    -66,   // .wwb..w
    9,     // bwwb..w
    -42,   // wwwb..w
    80,    // ...w..w
    153,   // b..w..w
    -100,  // w..w..w
    73,    // .b.w..w
    -146,  // bb.w..w
    21,    // wb.w..w
    72,    // .w.w..w
    -111,  // bw.w..w
    98,    // ww.w..w
    -13,   // ..bw..w
    151,   // b.bw..w
    4,     // w.bw..w
    -55,   // .bbw..w
    67,    // bbbw..w
    -120,  // wbbw..w
    58,    // .wbw..w
    -55,   // bwbw..w
    3,     // wwbw..w
    -102,  // ..ww..w
    -134,  // b.ww..w
    -64,   // w.ww..w
    4,     // .bww..w
    107,   // bbww..w
    -9,    // wbww..w
    33,    // .www..w
    100,   // bwww..w
    51,    // wwww..w
    18,    // ....b.w
    159,   // b...b.w
    266,   // w...b.w
    -32,   // .b..b.w
    -56,   // bb..b.w
    27,    // wb..b.w
    -12,   // .w..b.w
    2,     // bw..b.w
    147,   // ww..b.w
    14,    // ..b.b.w
    49,    // b.b.b.w
    -86,   // w.b.b.w
    64,    // .bb.b.w
    72,    // bbb.b.w
    48,    // wbb.b.w
    -32,   // .wb.b.w
    -34,   // bwb.b.w
    -89,   // wwb.b.w
    12,    // ..w.b.w
    0,     // b.w.b.w
    55,    // w.w.b.w
    -118,  // .bw.b.w
    43,    // bbw.b.w
    74,    // wbw.b.w
    177,   // .ww.b.w
    -45,   // bww.b.w
    84,    // www.b.w
    -18,   // ...bb.w
    134,   // b..bb.w
    9,     // w..bb.w
    66,    // .b.bb.w
    -106,  // bb.bb.w
    56,    // wb.bb.w
    23,    // .w.bb.w
    163,   // bw.bb.w
    76,    // ww.bb.w
    -54,   // ..bbb.w
    -83,   // b.bbb.w
    -148,  // w.bbb.w
    127,   // .bbbb.w
    -20,   // bbbbb.w
    -35,   // wbbbb.w
    -32,   // .wbbb.w
    244,   // bwbbb.w
    221,   // wwbbb.w
    51,    // ..wbb.w
    -36,   // b.wbb.w
    -82,   // w.wbb.w
    33,    // .bwbb.w
    -68,   // bbwbb.w
    -35,   // wbwbb.w
    -35,   // .wwbb.w
    -69,   // bwwbb.w
    58,    // wwwbb.w
    -41,   // ...wb.w
    -45,   // b..wb.w
    4,     // w..wb.w
    -30,   // .b.wb.w
    -127,  // bb.wb.w
    29,    // wb.wb.w
    22,    // .w.wb.w
    112,   // bw.wb.w
    -2,    // ww.wb.w
    3,     // ..bwb.w
    157,   // b.bwb.w
    124,   // w.bwb.w
    -21,   // .bbwb.w
    85,    // bbbwb.w
    103,   // wbbwb.w
    -98,   // .wbwb.w
    -1,    // bwbwb.w
    23,    // wwbwb.w
    177,   // ..wwb.w
    36,    // b.wwb.w
    -26,   // w.wwb.w
    50,    // .bwwb.w
    64,    // bbwwb.w
    -45,   // wbwwb.w
    58,    // .wwwb.w
    65,    // bwwwb.w
    183,   // wwwwb.w
    -47,   // ....w.w
    18,    // b...w.w
    -19,   // w...w.w
    -23,   // .b..w.w
    -33,   // bb..w.w
    86,    // wb..w.w
    -67,   // .w..w.w
    56,    // bw..w.w
    -20,   // ww..w.w
    -71,   // ..b.w.w
    0,     // b.b.w.w
    55,    // w.b.w.w
    47,    // .bb.w.w
    -53,   // bbb.w.w
    -19,   // wbb.w.w
    153,   // .wb.w.w
    16,    // bwb.w.w
    9,     // wwb.w.w
    -45,   // ..w.w.w
    -49,   // b.w.w.w
    106,   // w.w.w.w
    -44,   // .bw.w.w
    -198,  // bbw.w.w
    -58,   // wbw.w.w
    -67,   // .ww.w.w
    147,   // bww.w.w
    17,    // www.w.w
    44,    // ...bw.w
    -151,  // b..bw.w
    76,    // w..bw.w
    -61,   // .b.bw.w
    -100,  // bb.bw.w
    91,    // wb.bw.w
    61,    // .w.bw.w
    36,    // bw.bw.w
    35,    // ww.bw.w
    -136,  // ..bbw.w
    48,    // b.bbw.w
    -82,   // w.bbw.w
    42,    // .bbbw.w
    29,    // bbbbw.w
    31,    // wbbbw.w
    -98,   // .wbbw.w
    -164,  // bwbbw.w
    -29,   // wwbbw.w
    -22,   // ..wbw.w
    -157,  // b.wbw.w
    19,    // w.wbw.w
    107,   // .bwbw.w
    -74,   // bbwbw.w
    121,   // wbwbw.w
    -66,   // .wwbw.w
    63,    // bwwbw.w
    39,    // wwwbw.w
    -15,   // ...ww.w
    -132,  // b..ww.w
    -64,   // w..ww.w
    -62,   // .b.ww.w
    -135,  // bb.ww.w
    24,    // wb.ww.w
    -112,  // .w.ww.w
    -162,  // bw.ww.w
    110,   // ww.ww.w
    34,    // ..bww.w
    -48,   // b.bww.w
    -26,   // w.bww.w
    13,    // .bbww.w
    -60,   // bbbww.w
    2,     // wbbww.w
    33,    // .wbww.w
    -36,   // bwbww.w
    -95,   // wwbww.w
    -153,  // ..www.w
    83,    // b.www.w
    138,   // w.www.w
    -176,  // .bwww.w
    39,    // bbwww.w
    70,    // wbwww.w
    -30,   // .wwww.w
    35,    // bwwww.w
    -60,   // wwwww.w
    -20,   // .....bw
    78,    // b....bw
    6,     // w....bw
    -1,    // .b...bw
    32,    // bb...bw
    -14,   // wb...bw
    61,    // .w...bw
    0,     // bw...bw
    7,     // ww...bw
    -27,   // ..b..bw
    -56,   // b.b..bw
    27,    // w.b..bw
    5,     // .bb..bw
    -103,  // bbb..bw
    68,    // wbb..bw
    -38,   // .wb..bw
    267,   // bwb..bw
    23,    // wwb..bw
    -37,   // ..w..bw
    -2,    // b.w..bw
    86,    // w.w..bw
    -18,   // .bw..bw
    -87,   // bbw..bw
    -136,  // wbw..bw
    -8,    // .ww..bw
    -34,   // bww..bw
    -18,   // www..bw
    -49,   // ...b.bw
    111,   // b..b.bw
    118,   // w..b.bw
    -113,  // .b.b.bw
    13,    // bb.b.bw
    51,    // wb.b.bw
    -101,  // .w.b.bw
    37,    // bw.b.bw
    -9,    // ww.b.bw
    111,   // ..bb.bw
    162,   // b.bb.bw
    56,    // w.bb.bw
    -87,   // .bbb.bw
    -3,    // bbbb.bw
    124,   // wbbb.bw
    -109,  // .wbb.bw
    67,    // bwbb.bw
    115,   // wwbb.bw
    -150,  // ..wb.bw
    -112,  // b.wb.bw
    91,    // w.wb.bw
    -22,   // .bwb.bw
    12,    // bbwb.bw
    79,    // wbwb.bw
    -22,   // .wwb.bw
    198,   // bwwb.bw
    -77,   // wwwb.bw
    142,   // ...w.bw
    94,    // b..w.bw
    21,    // w..w.bw
    -132,  // .b.w.bw
    -60,   // bb.w.bw
    174,   // wb.w.bw
    -146,  // .w.w.bw
    -37,   // bw.w.bw
    -67,   // ww.w.bw
    -16,   // ..bw.bw
    -36,   // b.bw.bw
    29,    // w.bw.bw
    -16,   // .bbw.bw
    -12,   // bbbw.bw
    45,    // wbbw.bw
    -65,   // .wbw.bw
    45,    // bwbw.bw
    -19,   // wwbw.bw
    129,   // ..ww.bw
    -163,  // b.ww.bw
    24,    // w.ww.bw
    124,   // .bww.bw
    198,   // bbww.bw
    54,    // wbww.bw
    149,   // .www.bw
    -27,   // bwww.bw
    45,    // wwww.bw
    -163,  // ....bbw
    -40,   // b...bbw
    44,    // w...bbw
    100,   // .b..bbw
    197,   // bb..bbw
    68,    // wb..bbw
    -30,   // .w..bbw
    34,    // bw..bbw
    10,    // ww..bbw
    100,   // ..b.bbw
    -147,  // b.b.bbw
    48,    // w.b.bbw
    94,    // .bb.bbw
    108,   // bbb.bbw
    -57,   // wbb.bbw
    -94,   // .wb.bbw
    27,    // bwb.bbw
    98,    // wwb.bbw
    -20,   // ..w.bbw
    45,    // b.w.bbw
    -19,   // w.w.bbw
    -240,  // .bw.bbw
    84,    // bbw.bbw
    153,   // wbw.bbw
    -76,   // .ww.bbw
    0,     // bww.bbw
    28,    // www.bbw
    -76,   // ...bbbw
    -100,  // b..bbbw
    0,     // w..bbbw
    221,   // .b.bbbw
    -17,   // bb.bbbw
    124,   // wb.bbbw
    -76,   // .w.bbbw
    27,    // bw.bbbw
    -158,  // ww.bbbw
    15,    // ..bbbbw
    -35,   // b.bbbbw
    -35,   // w.bbbbw
    -162,  // .bbbbbw
    90,    // bbbbbbw
    112,   // wbbbbbw
    -124,  // .wbbbbw
    50,    // bwbbbbw
    -39,   // wwbbbbw
    22,    // ..wbbbw
    -65,   // b.wbbbw
    31,    // w.wbbbw
    -77,   // .bwbbbw
    -22,   // bbwbbbw
    61,    // wbwbbbw
    48,    // .wwbbbw
    184,   // bwwbbbw
    -69,   // wwwbbbw
    118,   // ...wbbw
    -9,    // b..wbbw
    -120,  // w..wbbw
    81,    // .b.wbbw
    35,    // bb.wbbw
    45,    // wb.wbbw
    150,   // .w.wbbw
    -198,  // bw.wbbw
    -88,   // ww.wbbw
    -48,   // ..bwbbw
    -63,   // b.bwbbw
    103,   // w.bwbbw
    115,   // .bbwbbw
    116,   // bbbwbbw
    19,    // wbbwbbw
    -24,   // .wbwbbw
    46,    // bwbwbbw
    -13,   // wwbwbbw
    -87,   // ..wwbbw
    69,    // b.wwbbw
    2,     // w.wwbbw
    -13,   // .bwwbbw
    -46,   // bbwwbbw
    -201,  // wbwwbbw
    96,    // .wwwbbw
    -184,  // bwwwbbw
    -39,   // wwwwbbw
    32,    // ....wbw
    -81,   // b...wbw
    91,    // w...wbw
    76,    // .b..wbw
    106,   // bb..wbw
    -136,  // wb..wbw
    192,   // .w..wbw
    -267,  // bw..wbw
    87,    // ww..wbw
    -33,   // ..b.wbw
    -16,   // b.b.wbw
    74,    // w.b.wbw
    29,    // .bb.wbw
    -102,  // bbb.wbw
    153,   // wbb.wbw
    -5,    // .wb.wbw
    0,     // bwb.wbw
    -6,    // wwb.wbw
    147,   // ..w.wbw
    34,    // b.w.wbw
    -58,   // w.w.wbw
    -59,   // .bw.wbw
    27,    // bbw.wbw
    -58,   // wbw.wbw
    -46,   // .ww.wbw
    -27,   // bww.wbw
    -19,   // www.wbw
    -14,   // ...bwbw
    55,    // b..bwbw
    -116,  // w..bwbw
    -75,   // .b.bwbw
    35,    // bb.bwbw
    79,    // wb.bwbw
    211,   // .w.bwbw
    -45,   // bw.bwbw
    -42,   // ww.bwbw
    114,   // ..bbwbw
    36,    // b.bbwbw
    -35,   // w.bbwbw
    -226,  // .bbbwbw
    40,    // bbbbwbw
    61,    // wbbbwbw
    78,    // .wbbwbw
    51,    // bwbbwbw
    94,    // wwbbwbw
    -35,   // ..wbwbw
    1,     // b.wbwbw
    121,   // w.wbwbw
    -158,  // .bwbwbw
    37,    // bbwbwbw
    -61,   // wbwbwbw
    192,   // .wwbwbw
    -46,   // bwwbwbw
    54,    // wwwbwbw
    78,    // ...wwbw
    -86,   // b..wwbw
    -9,    // w..wwbw
    -45,   // .b.wwbw
    -32,   // bb.wwbw
    54,    // wb.wwbw
    21,    // .w.wwbw
    -67,   // bw.wwbw
    -56,   // ww.wwbw
    58,    // ..bwwbw
    164,   // b.bwwbw
    -45,   // w.bwwbw
    129,   // .bbwwbw
    9,     // bbbwwbw
    -201,  // wbbwwbw
    43,    // .wbwwbw
    -51,   // bwbwwbw
    122,   // wwbwwbw
    79,    // ..wwwbw
    -244,  // b.wwwbw
    70,    // w.wwwbw
    127,   // .bwwwbw
    24,    // bbwwwbw
    -1,    // wbwwwbw
    -109,  // .wwwwbw
    -50,   // bwwwwbw
    25,    // wwwwwbw
    -100,  // .....ww
    -172,  // b....ww
    46,    // w....ww
    35,    // .b...ww
    0,     // bb...ww
    7,     // wb...ww
    132,   // .w...ww
    -32,   // bw...ww
    134,   // ww...ww
    -57,   // ..b..ww
    33,    // b.b..ww
    147,   // w.b..ww
    -98,   // .bb..ww
    -78,   // bbb..ww
    10,    // wbb..ww
    67,    // .wb..ww
    -106,  // bwb..ww
    14,    // wwb..ww
    -136,  // ..w..ww
    56,    // b.w..ww
    -20,   // w.w..ww
    58,    // .bw..ww
    23,    // bbw..ww
    87,    // wbw..ww
    -54,   // .ww..ww
    -197,  // bww..ww
    -111,  // www..ww
    -185,  // ...b.ww
    146,   // b..b.ww
    36,    // w..b.ww
    -42,   // .b.b.ww
    42,    // bb.b.ww
    -9,    // wb.b.ww
    -12,   // .w.b.ww
    60,    // bw.b.ww
    -21,   // ww.b.ww
    80,    // ..bb.ww
    135,   // b.bb.ww
    76,    // w.bb.ww
    -30,   // .bbb.ww
    135,   // bbbb.ww
    -158,  // wbbb.ww
    -34,   // .wbb.ww
    32,    // bwbb.ww
    8,     // wwbb.ww
    54,    // ..wb.ww
    127,   // b.wb.ww
    35,    // w.wb.ww
    -183,  // .bwb.ww
    49,    // bbwb.ww
    -42,   // wbwb.ww
    22,    // .wwb.ww
    -35,   // bwwb.ww
    -51,   // wwwb.ww
    -164,  // ...w.ww
    11,    // b..w.ww
    98,    // w..w.ww
    13,    // .b.w.ww
    -42,   // bb.w.ww
    -67,   // wb.w.ww
    19,    // .w.w.ww
    -13,   // bw.w.ww
    -110,  // ww.w.ww
    -121,  // ..bw.ww
    100,   // b.bw.ww
    -2,    // w.bw.ww
    14,    // .bbw.ww
    22,    // bbbw.ww
    -88,   // wbbw.ww
    44,    // .wbw.ww
    -35,   // bwbw.ww
    -105,  // wwbw.ww
    -83,   // ..ww.ww
    106,   // b.ww.ww
    110,   // w.ww.ww
    128,   // .bww.ww
    81,    // bbww.ww
    -56,   // wbww.ww
    150,   // .www.ww
    17,    // bwww.ww
    78,    // wwww.ww
    88,    // ....bww
    45,    // b...bww
    -60,   // w...bww
    -78,   // .b..bww
    -23,   // bb..bww
    23,    // wb..bww
    -34,   // .w..bww
    87,    // bw..bww
    14,    // ww..bww
    74,    // ..b.bww
    198,   // b.b.bww
    -89,   // w.b.bww
    53,    // .bb.bww
    -139,  // bbb.bww
    98,    // wbb.bww
    -2,    // .wb.bww
    -27,   // bwb.bww
    -151,  // wwb.bww
    -51,   // ..w.bww
    -43,   // b.w.bww
    9,     // w.w.bww
    71,    // .bw.bww
    0,     // bbw.bww
    -6,    // wbw.bww
    5,     // .ww.bww
    -84,   // bww.bww
    0,     // www.bww
    107,   // ...bbww
    -107,  // b..bbww
    62,    // w..bbww
    -75,   // .b.bbww
    -81,   // bb.bbww
    115,   // wb.bbww
    72,    // .w.bbww
    -198,  // bw.bbww
    8,     // ww.bbww
    77,    // ..bbbww
    -39,   // b.bbbww
    221,   // w.bbbww
    -46,   // .bbbbww
    5,     // bbbbbww
    -39,   // wbbbbww
    -95,   // .wbbbww
    -24,   // bwbbbww
    69,    // wwbbbww
    -108,  // ..wbbww
    -64,   // b.wbbww
    -29,   // w.wbbww
    -58,   // .bwbbww
    173,   // bbwbbww
    94,    // wbwbbww
    34,    // .wwbbww
    46,    // bwwbbww
    -3,    // wwwbbww
    95,    // ...wbww
    2,     // b..wbww
    3,     // w..wbww
    -218,  // .b.wbww
    -49,   // bb.wbww
    -19,   // wb.wbww
    20,    // .w.wbww
    -12,   // bw.wbww
    -105,  // ww.wbww
    -92,   // ..bwbww
    74,    // b.bwbww
    23,    // w.bwbww
    -74,   // .bbwbww
    64,    // bbbwbww
    -13,   // wbbwbww
    -113,  // .wbwbww
    -37,   // bwbwbww
    -121,  // wwbwbww
    -106,  // ..wwbww
    68,    // b.wwbww
    -95,   // w.wwbww
    6,     // .bwwbww
    -173,  // bbwwbww
    122,   // wbwwbww
    111,   // .wwwbww
    22,    // bwwwbww
    -50,   // wwwwbww
    -181,  // ....www
    -80,   // b...www
    31,    // w...www
    80,    // .b..www
    78,    // bb..www
    -18,   // wb..www
    -33,   // .w..www
    103,   // bw..www
    -111,  // ww..www
    -60,   // ..b.www
    53,    // b.b.www
    84,    // w.b.www
    -48,   // .bb.www
    0,     // bbb.www
    28,    // wbb.www
    180,   // .wb.www
    102,   // bwb.www
    0,     // wwb.www
    -176,  // ..w.www
    -72,   // b.w.www
    17,    // w.w.www
    204,   // .bw.www
    139,   // bbw.www
    -19,   // wbw.www
    79,    // .ww.www
    -108,  // bww.www
    20,    // www.www
    80,    // ...bwww
    -67,   // b..bwww
    -42,   // w..bwww
    -146,  // .b.bwww
    -22,   // bb.bwww
    -77,   // wb.bwww
    -34,   // .w.bwww
    12,    // bw.bwww
    -51,   // ww.bwww
    -73,   // ..bbwww
    60,    // b.bbwww
    58,    // w.bbwww
    112,   // .bbbwww
    -67,   // bbbbwww
    -69,   // wbbbwww
    -3,    // .wbbwww
    -9,    // bwbbwww
    -3,    // wwbbwww
    154,   // ..wbwww
    -85,   // b.wbwww
    39,    // w.wbwww
    -71,   // .bwbwww
    -64,   // bbwbwww
    54,    // wbwbwww
    -226,  // .wwbwww
    -116,  // bwwbwww
    11,    // wwwbwww
    -447,  // ...wwww
    -94,   // b..wwww
    51,    // w..wwww
    -225,  // .b.wwww
    -135,  // bb.wwww
    45,    // wb.wwww
    -60,   // .w.wwww
    3,     // bw.wwww
    78,    // ww.wwww
    -48,   // ..bwwww
    -29,   // b.bwwww
    183,   // w.bwwww
    -33,   // .bbwwww
    67,    // bbbwwww
    -39,   // wbbwwww
    -41,   // .wbwwww
    -40,   // bwbwwww
    -50,   // wwbwwww
    7,     // ..wwwww
    20,    // b.wwwww
    -60,   // w.wwwww
    8,     // .bwwwww
    -5,    // bbwwwww
    25,    // wbwwwww
    -179,  // .wwwwww
    -90,   // bwwwwww
    -5,    // wwwwwww
    70,    // ccc
    101,   // cc
    37,    // c
    3,     // ttt
    94,    // tt
    122,   // t
    58,    // ct
    62,    // cct
    119,   // ctt
].into_boxed_slice()
