vec![
    0,     // .......
    19,    // b......
    -19,   // w......
    -18,   // .b.....
    28,    // bb.....
    -11,   // wb.....
    18,    // .w.....
    11,    // bw.....
    -28,   // ww.....
    21,    // ..b....
    86,    // b.b....
    -23,   // w.b....
    16,    // .bb....
    85,    // bbb....
    -100,  // wbb....
    -18,   // .wb....
    53,    // bwb....
    69,    // wwb....
    -21,   // ..w....
    23,    // b.w....
    -86,   // w.w....
    18,    // .bw....
    -69,   // bbw....
    -53,   // wbw....
    -16,   // .ww....
    100,   // bww....
    -85,   // www....
    -15,   // ...b...
    -7,    // b..b...
    -7,    // w..b...
    1,     // .b.b...
    119,   // bb.b...
    -82,   // wb.b...
    -4,    // .w.b...
    -18,   // bw.b...
    -41,   // ww.b...
    -7,    // ..bb...
    99,    // b.bb...
    -30,   // w.bb...
    191,   // .bbb...
    718,   // bbbb...
    -101,  // wbbb...
    42,    // .wbb...
    -20,   // bwbb...
    -5,    // wwbb...
    -7,    // ..wb...
    67,    // b.wb...
    -91,   // w.wb...
    -44,   // .bwb...
    -85,   // bbwb...
    -14,   // wbwb...
    -14,   // .wwb...
    22,    // bwwb...
    -116,  // wwwb...
    15,    // ...w...
    7,     // b..w...
    7,     // w..w...
    4,     // .b.w...
    41,    // bb.w...
    18,    // wb.w...
    -1,    // .w.w...
    82,    // bw.w...
    -119,  // ww.w...
    7,     // ..bw...
    91,    // b.bw...
    -67,   // w.bw...
    14,    // .bbw...
    116,   // bbbw...
    -22,   // wbbw...
    44,    // .wbw...
    14,    // bwbw...
    85,    // wwbw...
    7,     // ..ww...
    30,    // b.ww...
    -99,   // w.ww...
    -42,   // .bww...
    5,     // bbww...
    20,    // wbww...
    -191,  // .www...
    101,   // bwww...
    -718,  // wwww...
    21,    // ....b..
    29,    // b...b..
    -86,   // w...b..
    25,    // .b..b..
    -58,   // bb..b..
    20,    // wb..b..
    -11,   // .w..b..
    -60,   // bw..b..
    26,    // ww..b..
    -6,    // ..b.b..
    -34,   // b.b.b..
    -26,   // w.b.b..
    -5,    // .bb.b..
    189,   // bbb.b..
    -189,  // wbb.b..
    -24,   // .wb.b..
    -87,   // bwb.b..
    -49,   // wwb.b..
    0,     // ..w.b..
    -26,   // b.w.b..
    -79,   // w.w.b..
    -26,   // .bw.b..
    -34,   // bbw.b..
    -69,   // wbw.b..
    -1,    // .ww.b..
    -49,   // bww.b..
    -37,   // www.b..
    -7,    // ...bb..
    40,    // b..bb..
    -35,   // w..bb..
    15,    // .b.bb..
    37,    // bb.bb..
    -11,   // wb.bb..
    -75,   // .w.bb..
    -8,    // bw.bb..
    -49,   // ww.bb..
    19,    // ..bbb..
    118,   // b.bbb..
    -6,    // w.bbb..
    286,   // .bbbb..
    82,    // bbbbb..
    11,    // wbbbb..
    -57,   // .wbbb..
    -53,   // bwbbb..
    21,    // wwbbb..
    -96,   // ..wbb..
    -49,   // b.wbb..
    -29,   // w.wbb..
    -57,   // .bwbb..
    -8,    // bbwbb..
    84,    // wbwbb..
    67,    // .wwbb..
    -114,  // bwwbb..
    -99,   // wwwbb..
    7,     // ...wb..
    102,   // b..wb..
    47,    // w..wb..
    20,    // .b.wb..
    -35,   // bb.wb..
    13,    // wb.wb..
    2,     // .w.wb..
    35,    // bw.wb..
    27,    // ww.wb..
    6,     // ..bwb..
    7,     // b.bwb..
    -2,    // w.bwb..
    -43,   // .bbwb..
    -157,  // bbbwb..
    10,    // wbbwb..
    -1,    // .wbwb..
    -67,   // bwbwb..
    32,    // wwbwb..
    96,    // ..wwb..
    62,    // b.wwb..
    69,    // w.wwb..
    87,    // .bwwb..
    -14,   // bbwwb..
    -16,   // wbwwb..
    -104,  // .wwwb..
    30,    // bwwwb..
    -102,  // wwwwb..
    -21,   // ....w..
    86,    // b...w..
    -29,   // w...w..
    11,    // .b..w..
    -26,   // bb..w..
    60,    // wb..w..
    -25,   // .w..w..
    -20,   // bw..w..
    58,    // ww..w..
    0,     // ..b.w..
    79,    // b.b.w..
    26,    // w.b.w..
    1,     // .bb.w..
    37,    // bbb.w..
    49,    // wbb.w..
    26,    // .wb.w..
    69,    // bwb.w..
    34,    // wwb.w..
    6,     // ..w.w..
    26,    // b.w.w..
    34,    // w.w.w..
    24,    // .bw.w..
    49,    // bbw.w..
    87,    // wbw.w..
    5,     // .ww.w..
    189,   // bww.w..
    -189,  // www.w..
    -7,    // ...bw..
    -47,   // b..bw..
    -102,  // w..bw..
    -2,    // .b.bw..
    -27,   // bb.bw..
    -35,   // wb.bw..
    -20,   // .w.bw..
    -13,   // bw.bw..
    35,    // ww.bw..
    -96,   // ..bbw..
    -69,   // b.bbw..
    -62,   // w.bbw..
    104,   // .bbbw..
    102,   // bbbbw..
    -30,   // wbbbw..
    -87,   // .wbbw..
    16,    // bwbbw..
    14,    // wwbbw..
    -6,    // ..wbw..
    2,     // b.wbw..
    -7,    // w.wbw..
    1,     // .bwbw..
    -32,   // bbwbw..
    67,    // wbwbw..
    43,    // .wwbw..
    -10,   // bwwbw..
    157,   // wwwbw..
    7,     // ...ww..
    35,    // b..ww..
    -40,   // w..ww..
    75,    // .b.ww..
    49,    // bb.ww..
    8,     // wb.ww..
    -15,   // .w.ww..
    11,    // bw.ww..
    -37,   // ww.ww..
    96,    // ..bww..
    29,    // b.bww..
    49,    // w.bww..
    -67,   // .bbww..
    99,    // bbbww..
    114,   // wbbww..
    57,    // .wbww..
    -84,   // bwbww..
    8,     // wwbww..
    -19,   // ..www..
    6,     // b.www..
    -118,  // w.www..
    57,    // .bwww..
    -21,   // bbwww..
    53,    // wbwww..
    -286,  // .wwww..
    -11,   // bwwww..
    -82,   // wwwww..
    -18,   // .....b.
    -30,   // b....b.
    -69,   // w....b.
    -28,   // .b...b.
    -46,   // bb...b.
    29,    // wb...b.
    0,     // .w...b.
    -66,   // bw...b.
    27,    // ww...b.
    25,    // ..b..b.
    42,    // b.b..b.
    -72,   // w.b..b.
    43,    // .bb..b.
    22,    // bbb..b.
    87,    // wbb..b.
    17,    // .wb..b.
    -64,   // bwb..b.
    37,    // wwb..b.
    11,    // ..w..b.
    -14,   // b.w..b.
    -35,   // w.w..b.
    20,    // .bw..b.
    -25,   // bbw..b.
    -29,   // wbw..b.
    -14,   // .ww..b.
    17,    // bww..b.
    -95,   // www..b.
    1,     // ...b.b.
    -42,   // b..b.b.
    -20,   // w..b.b.
    -16,   // .b.b.b.
    -80,   // bb.b.b.
    8,     // wb.b.b.
    -23,   // .w.b.b.
    -4,    // bw.b.b.
    -14,   // ww.b.b.
    15,    // ..bb.b.
    31,    // b.bb.b.
    118,   // w.bb.b.
    76,    // .bbb.b.
    -91,   // bbbb.b.
    90,    // wbbb.b.
    -19,   // .wbb.b.
    -53,   // bwbb.b.
    0,     // wwbb.b.
    -2,    // ..wb.b.
    -19,   // b.wb.b.
    -27,   // w.wb.b.
    37,    // .bwb.b.
    44,    // bbwb.b.
    24,    // wbwb.b.
    96,    // .wwb.b.
    -70,   // bwwb.b.
    52,    // wwwb.b.
    4,     // ...w.b.
    -76,   // b..w.b.
    -12,   // w..w.b.
    34,    // .b.w.b.
    -40,   // bb.w.b.
    -76,   // wb.w.b.
    23,    // .w.w.b.
    109,   // bw.w.b.
    -149,  // ww.w.b.
    20,    // ..bw.b.
    48,    // b.bw.b.
    38,    // w.bw.b.
    -6,    // .bbw.b.
    -109,  // bbbw.b.
    -92,   // wbbw.b.
    50,    // .wbw.b.
    3,     // bwbw.b.
    54,    // wwbw.b.
    75,    // ..ww.b.
    -2,    // b.ww.b.
    36,    // w.ww.b.
    49,    // .bww.b.
    -1,    // bbww.b.
    169,   // wbww.b.
    -105,  // .www.b.
    40,    // bwww.b.
    -264,  // wwww.b.
    16,    // ....bb.
    -1,    // b...bb.
    23,    // w...bb.
    43,    // .b..bb.
    10,    // bb..bb.
    2,     // wb..bb.
    14,    // .w..bb.
    -20,   // bw..bb.
    -93,   // ww..bb.
    -5,    // ..b.bb.
    24,    // b.b.bb.
    15,    // w.b.bb.
    44,    // .bb.bb.
    -20,   // bbb.bb.
    -4,    // wbb.bb.
    -103,  // .wb.bb.
    32,    // bwb.bb.
    -26,   // wwb.bb.
    1,     // ..w.bb.
    -4,    // b.w.bb.
    56,    // w.w.bb.
    -101,  // .bw.bb.
    51,    // bbw.bb.
    -128,  // wbw.bb.
    0,     // .ww.bb.
    102,   // bww.bb.
    -97,   // www.bb.
    191,   // ...bbb.
    -57,   // b..bbb.
    90,    // w..bbb.
    76,    // .b.bbb.
    18,    // bb.bbb.
    55,    // wb.bbb.
    105,   // .w.bbb.
    64,    // bw.bbb.
    -13,   // ww.bbb.
    286,   // ..bbbb.
    138,   // b.bbbb.
    82,    // w.bbbb.
    -77,   // .bbbbb.
    -70,   // bbbbbb.
    16,    // wbbbbb.
    51,    // .wbbbb.
    -77,   // bwbbbb.
    7,     // wwbbbb.
    104,   // ..wbbb.
    19,    // b.wbbb.
    -75,   // w.wbbb.
    69,    // .bwbbb.
    -109,  // bbwbbb.
    79,    // wbwbbb.
    27,    // .wwbbb.
    22,    // bwwbbb.
    -44,   // wwwbbb.
    14,    // ...wbb.
    64,    // b..wbb.
    38,    // w..wbb.
    -6,    // .b.wbb.
    77,    // bb.wbb.
    3,     // wb.wbb.
    -96,   // .w.wbb.
    -26,   // bw.wbb.
    -41,   // ww.wbb.
    -43,   // ..bwbb.
    -88,   // b.bwbb.
    -113,  // w.bwbb.
    -44,   // .bbwbb.
    -69,   // bbbwbb.
    -85,   // wbbwbb.
    42,    // .wbwbb.
    -48,   // bwbwbb.
    124,   // wwbwbb.
    -67,   // ..wwbb.
    -22,   // b.wwbb.
    -21,   // w.wwbb.
    -46,   // .bwwbb.
    -56,   // bbwwbb.
    -49,   // wbwwbb.
    -27,   // .wwwbb.
    105,   // bwwwbb.
    57,    // wwwwbb.
    18,    // ....wb.
    20,    // b...wb.
    94,    // w...wb.
    20,    // .b..wb.
    -18,   // bb..wb.
    -94,   // wb..wb.
    -17,   // .w..wb.
    -90,   // bw..wb.
    -139,  // ww..wb.
    -26,   // ..b.wb.
    -51,   // b.b.wb.
    -25,   // w.b.wb.
    -101,  // .bb.wb.
    -15,   // bbb.wb.
    -64,   // wbb.wb.
    0,     // .wb.wb.
    52,    // bwb.wb.
    -2,    // wwb.wb.
    24,    // ..w.wb.
    -32,   // b.w.wb.
    123,   // w.w.wb.
    56,    // .bw.wb.
    -15,   // bbw.wb.
    -3,    // wbw.wb.
    103,   // .ww.wb.
    -44,   // bww.wb.
    13,    // www.wb.
    -44,   // ...bwb.
    36,    // b..bwb.
    68,    // w..bwb.
    37,    // .b.bwb.
    -17,   // bb.bwb.
    -37,   // wb.bwb.
    -50,   // .w.bwb.
    -24,   // bw.bwb.
    -21,   // ww.bwb.
    -57,   // ..bbwb.
    -58,   // b.bbwb.
    -21,   // w.bbwb.
    69,    // .bbbwb.
    -131,  // bbbbwb.
    -11,   // wbbbwb.
    22,    // .wbbwb.
    -111,  // bwbbwb.
    71,    // wwbbwb.
    1,     // ..wbwb.
    -39,   // b.wbwb.
    30,    // w.wbwb.
    -10,   // .bwbwb.
    5,     // bbwbwb.
    -64,   // wbwbwb.
    -42,   // .wwbwb.
    104,   // bwwbwb.
    43,    // wwwbwb.
    -42,   // ...wwb.
    33,    // b..wwb.
    9,     // w..wwb.
    49,    // .b.wwb.
    -27,   // bb.wwb.
    41,    // wb.wwb.
    19,    // .w.wwb.
    74,    // bw.wwb.
    -102,  // ww.wwb.
    87,    // ..bwwb.
    -80,   // b.bwwb.
    -20,   // w.bwwb.
    -46,   // .bbwwb.
    13,    // bbbwwb.
    -83,   // wbbwwb.
    -22,   // .wbwwb.
    -111,  // bwbwwb.
    -24,   // wwbwwb.
    57,    // ..wwwb.
    142,   // b.wwwb.
    -240,  // w.wwwb.
    -28,   // .bwwwb.
    100,   // bbwwwb.
    -18,   // wbwwwb.
    -51,   // .wwwwb.
    265,   // bwwwwb.
    -302,  // wwwwwb.
    18,    // .....w.
    69,    // b....w.
    30,    // w....w.
    0,     // .b...w.
    -27,   // bb...w.
    66,    // wb...w.
    28,    // .w...w.
    -29,   // bw...w.
    46,    // ww...w.
    -11,   // ..b..w.
    35,    // b.b..w.
    14,    // w.b..w.
    14,    // .bb..w.
    95,    // bbb..w.
    -17,   // wbb..w.
    -20,   // .wb..w.
    29,    // bwb..w.
    25,    // wwb..w.
    -25,   // ..w..w.
    72,    // b.w..w.
    -42,   // w.w..w.
    -17,   // .bw..w.
    -37,   // bbw..w.
    64,    // wbw..w.
    -43,   // .ww..w.
    -87,   // bww..w.
    -22,   // www..w.
    -4,    // ...b.w.
    12,    // b..b.w.
    76,    // w..b.w.
    -23,   // .b.b.w.
    149,   // bb.b.w.
    -109,  // wb.b.w.
    -34,   // .w.b.w.
    76,    // bw.b.w.
    40,    // ww.b.w.
    -75,   // ..bb.w.
    -36,   // b.bb.w.
    2,     // w.bb.w.
    105,   // .bbb.w.
    264,   // bbbb.w.
    -40,   // wbbb.w.
    -49,   // .wbb.w.
    -169,  // bwbb.w.
    1,     // wwbb.w.
    -20,   // ..wb.w.
    -38,   // b.wb.w.
    -48,   // w.wb.w.
    -50,   // .bwb.w.
    -54,   // bbwb.w.
    -3,    // wbwb.w.
    6,     // .wwb.w.
    92,    // bwwb.w.
    109,   // wwwb.w.
    -1,    // ...w.w.
    20,    // b..w.w.
    42,    // w..w.w.
    23,    // .b.w.w.
    14,    // bb.w.w.
    4,     // wb.w.w.
    16,    // .w.w.w.
    -8,    // bw.w.w.
    80,    // ww.w.w.
    2,     // ..bw.w.
    27,    // b.bw.w.
    19,    // w.bw.w.
    -96,   // .bbw.w.
    -52,   // bbbw.w.
    70,    // wbbw.w.
    -37,   // .wbw.w.
    -24,   // bwbw.w.
    -44,   // wwbw.w.
    -15,   // ..ww.w.
    -118,  // b.ww.w.
    -31,   // w.ww.w.
    19,    // .bww.w.
    0,     // bbww.w.
    53,    // wbww.w.
    -76,   // .www.w.
    -90,   // bwww.w.
    91,    // wwww.w.
    -18,   // ....bw.
    -94,   // b...bw.
    -20,   // w...bw.
    17,    // .b..bw.
    139,   // bb..bw.
    90,    // wb..bw.
    -20,   // .w..bw.
    94,    // bw..bw.
    18,    // ww..bw.
    -24,   // ..b.bw.
    -123,  // b.b.bw.
    32,    // w.b.bw.
    -103,  // .bb.bw.
    -13,   // bbb.bw.
    44,    // wbb.bw.
    -56,   // .wb.bw.
    3,     // bwb.bw.
    15,    // wwb.bw.
    26,    // ..w.bw.
    25,    // b.w.bw.
    51,    // w.w.bw.
    0,     // .bw.bw.
    2,     // bbw.bw.
    -52,   // wbw.bw.
    101,   // .ww.bw.
    64,    // bww.bw.
    15,    // www.bw.
    42,    // ...bbw.
    -9,    // b..bbw.
    -33,   // w..bbw.
    -19,   // .b.bbw.
    102,   // bb.bbw.
    -74,   // wb.bbw.
    -49,   // .w.bbw.
    -41,   // bw.bbw.
    27,    // ww.bbw.
    -57,   // ..bbbw.
    240,   // b.bbbw.
    -142,  // w.bbbw.
    51,    // .bbbbw.
    302,   // bbbbbw.
    -265,  // wbbbbw.
    28,    // .wbbbw.
    18,    // bwbbbw.
    -100,  // wwbbbw.
    -87,   // ..wbbw.
    20,    // b.wbbw.
    80,    // w.wbbw.
    22,    // .bwbbw.
    24,    // bbwbbw.
    111,   // wbwbbw.
    46,    // .wwbbw.
    83,    // bwwbbw.
    -13,   // wwwbbw.
    44,    // ...wbw.
    -68,   // b..wbw.
    -36,   // w..wbw.
    50,    // .b.wbw.
    21,    // bb.wbw.
    24,    // wb.wbw.
    -37,   // .w.wbw.
    37,    // bw.wbw.
    17,    // ww.wbw.
    -1,    // ..bwbw.
    -30,   // b.bwbw.
    39,    // w.bwbw.
    42,    // .bbwbw.
    -43,   // bbbwbw.
    -104,  // wbbwbw.
    10,    // .wbwbw.
    64,    // bwbwbw.
    -5,    // wwbwbw.
    57,    // ..wwbw.
    21,    // b.wwbw.
    58,    // w.wwbw.
    -22,   // .bwwbw.
    -71,   // bbwwbw.
    111,   // wbwwbw.
    -69,   // .wwwbw.
    11,    // bwwwbw.
    131,   // wwwwbw.
    -16,   // ....ww.
    -23,   // b...ww.
    1,     // w...ww.
    -14,   // .b..ww.
    93,    // bb..ww.
    20,    // wb..ww.
    -43,   // .w..ww.
    -2,    // bw..ww.
    -10,   // ww..ww.
    -1,    // ..b.ww.
    -56,   // b.b.ww.
    4,     // w.b.ww.
    0,     // .bb.ww.
    97,    // bbb.ww.
    -102,  // wbb.ww.
    101,   // .wb.ww.
    128,   // bwb.ww.
    -51,   // wwb.ww.
    5,     // ..w.ww.
    -15,   // b.w.ww.
    -24,   // w.w.ww.
    103,   // .bw.ww.
    26,    // bbw.ww.
    -32,   // wbw.ww.
    -44,   // .ww.ww.
    4,     // bww.ww.
    20,    // www.ww.
    -14,   // ...bww.
    -38,   // b..bww.
    -64,   // w..bww.
    96,    // .b.bww.
    41,    // bb.bww.
    26,    // wb.bww.
    6,     // .w.bww.
    -3,    // bw.bww.
    -77,   // ww.bww.
    67,    // ..bbww.
    21,    // b.bbww.
    22,    // w.bbww.
    27,    // .bbbww.
    -57,   // bbbbww.
    -105,  // wbbbww.
    46,    // .wbbww.
    49,    // bwbbww.
    56,    // wwbbww.
    43,    // ..wbww.
    113,   // b.wbww.
    88,    // w.wbww.
    -42,   // .bwbww.
    -124,  // bbwbww.
    48,    // wbwbww.
    44,    // .wwbww.
    85,    // bwwbww.
    69,    // wwwbww.
    -191,  // ...www.
    -90,   // b..www.
    57,    // w..www.
    -105,  // .b.www.
    13,    // bb.www.
    -64,   // wb.www.
    -76,   // .w.www.
    -55,   // bw.www.
    -18,   // ww.www.
    -104,  // ..bwww.
    75,    // b.bwww.
    -19,   // w.bwww.
    -27,   // .bbwww.
    44,    // bbbwww.
    -22,   // wbbwww.
    -69,   // .wbwww.
    -79,   // bwbwww.
    109,   // wwbwww.
    -286,  // ..wwww.
    -82,   // b.wwww.
    -138,  // w.wwww.
    -51,   // .bwwww.
    -7,    // bbwwww.
    77,    // wbwwww.
    77,    // .wwwww.
    -16,   // bwwwww.
    70,    // wwwwww.
    19,    // ......b
    34,    // b.....b
    0,     // w.....b
    -30,   // .b....b
    -15,   // bb....b
    10,    // wb....b
    69,    // .w....b
    0,     // bw....b
    -45,   // ww....b
    29,    // ..b...b
    5,     // b.b...b
    -79,   // w.b...b
    -1,    // .bb...b
    -89,   // bbb...b
    -122,  // wbb...b
    -94,   // .wb...b
    7,     // bwb...b
    10,    // wwb...b
    86,    // ..w...b
    -5,    // b.w...b
    87,    // w.w...b
    20,    // .bw...b
    -40,   // bbw...b
    -45,   // wbw...b
    -23,   // .ww...b
    -38,   // bww...b
    -91,   // www...b
    -7,    // ...b..b
    -38,   // b..b..b
    32,    // w..b..b
    -42,   // .b.b..b
    -39,   // bb.b..b
    -99,   // wb.b..b
    12,    // .w.b..b
    1,     // bw.b..b
    110,   // ww.b..b
    40,    // ..bb..b
    -27,   // b.bb..b
    -12,   // w.bb..b
    -57,   // .bbb..b
    12,    // bbbb..b
    -97,   // wbbb..b
    -9,    // .wbb..b
    111,   // bwbb..b
    -52,   // wwbb..b
    -47,   // ..wb..b
    -60,   // b.wb..b
    2,     // w.wb..b
    36,    // .bwb..b
    -83,   // bbwb..b
    -67,   // wbwb..b
    -38,   // .wwb..b
    -79,   // bwwb..b
    37,    // wwwb..b
    7,     // ...w..b
    -10,   // b..w..b
    -32,   // w..w..b
    -76,   // .b.w..b
    60,    // bb.w..b
    -26,   // wb.w..b
    20,    // .w.w..b
    -63,   // bw.w..b
    79,    // ww.w..b
    102,   // ..bw..b
    63,    // b.bw..b
    20,    // w.bw..b
    64,    // .bbw..b
    71,    // bbbw..b
    -64,   // wbbw..b
    -68,   // .wbw..b
    -29,   // bwbw..b
    -12,   // wwbw..b
    35,    // ..ww..b
    -6,    // b.ww..b
    38,    // w.ww..b
    33,    // .bww..b
    -53,   // bbww..b
    115,   // wbww..b
    -90,   // .www..b
    -29,   // bwww..b
    -67,   // wwww..b
    86,    // ....b.b
    5,     // b...b.b
    -87,   // w...b.b
    42,    // .b..b.b
    -94,   // bb..b.b
    125,   // wb..b.b
    35,    // .w..b.b
    19,    // bw..b.b
    29,    // ww..b.b
    -34,   // ..b.b.b
    25,    // b.b.b.b
    72,    // w.b.b.b
    24,    // .bb.b.b
    32,    // bbb.b.b
    20,    // wbb.b.b
    -123,  // .wb.b.b
    4,     // bwb.b.b
    -24,   // wwb.b.b
    79,    // ..w.b.b
    13,    // b.w.b.b
    0,     // w.w.b.b
    -51,   // .bw.b.b
    35,    // bbw.b.b
    30,    // wbw.b.b
    -56,   // .ww.b.b
    221,   // bww.b.b
    30,    // www.b.b
    99,    // ...bb.b
    -27,   // b..bb.b
    -38,   // w..bb.b
    31,    // .b.bb.b
    -30,   // bb.bb.b
    -69,   // wb.bb.b
    -36,   // .w.bb.b
    -21,   // bw.bb.b
    3,     // ww.bb.b
    118,   // ..bbb.b
    51,    // b.bbb.b
    -42,   // w.bbb.b
    138,   // .bbbb.b
    -88,   // bbbbb.b
    -24,   // wbbbb.b
    240,   // .wbbb.b
    -79,   // bwbbb.b
    6,     // wwbbb.b
    -69,   // ..wbb.b
    14,    // b.wbb.b
    84,    // w.wbb.b
    -58,   // .bwbb.b
    -46,   // bbwbb.b
    42,    // wbwbb.b
    21,    // .wwbb.b
    -55,   // bwwbb.b
    73,    // wwwbb.b
    91,    // ...wb.b
    63,    // b..wb.b
    -2,    // w..wb.b
    48,    // .b.wb.b
    -3,    // bb.wb.b
    -2,    // wb.wb.b
    27,    // .w.wb.b
    33,    // bw.wb.b
    27,    // ww.wb.b
    7,     // ..bwb.b
    24,    // b.bwb.b
    -7,    // w.bwb.b
    -88,   // .bbwb.b
    -58,   // bbbwb.b
    20,    // wbbwb.b
    -30,   // .wbwb.b
    28,    // bwbwb.b
    103,   // wwbwb.b
    29,    // ..wwb.b
    -22,   // b.wwb.b
    -84,   // w.wwb.b
    -80,   // .bwwb.b
    -66,   // bbwwb.b
    29,    // wbwwb.b
    75,    // .wwwb.b
    -34,   // bwwwb.b
    11,    // wwwwb.b
    23,    // ....w.b
    -5,    // b...w.b
    79,    // w...w.b
    -14,   // .b..w.b
    -15,   // bb..w.b
    130,   // wb..w.b
    72,    // .w..w.b
    53,    // bw..w.b
    -35,   // ww..w.b
    -26,   // ..b.w.b
    13,    // b.b.w.b
    0,     // w.b.w.b
    -4,    // .bb.w.b
    -33,   // bbb.w.b
    -42,   // wbb.w.b
    25,    // .wb.w.b
    31,    // bwb.w.b
    -28,   // wwb.w.b
    26,    // ..w.w.b
    63,    // b.w.w.b
    -72,   // w.w.w.b
    -32,   // .bw.w.b
    -112,  // bbw.w.b
    48,    // wbw.w.b
    -15,   // .ww.w.b
    49,    // bww.w.b
    -2,    // www.w.b
    67,    // ...bw.b
    -60,   // b..bw.b
    -20,   // w..bw.b
    -19,   // .b.bw.b
    74,    // bb.bw.b
    -31,   // wb.bw.b
    -38,   // .w.bw.b
    45,    // bw.bw.b
    -35,   // ww.bw.b
    -49,   // ..bbw.b
    14,    // b.bbw.b
    39,    // w.bbw.b
    19,    // .bbbw.b
    98,    // bbbbw.b
    -30,   // wbbbw.b
    20,    // .wbbw.b
    100,   // bwbbw.b
    -5,    // wwbbw.b
    2,     // ..wbw.b
    -69,   // b.wbw.b
    7,     // w.wbw.b
    -39,   // .bwbw.b
    -6,    // bbwbw.b
    -47,   // wbwbw.b
    113,   // .wwbw.b
    80,    // bwwbw.b
    -44,   // wwwbw.b
    30,    // ...ww.b
    -6,    // b..ww.b
    12,    // w..ww.b
    -2,    // .b.ww.b
    -17,   // bb.ww.b
    76,    // wb.ww.b
    -118,  // .w.ww.b
    -33,   // bw.ww.b
    2,     // ww.ww.b
    62,    // ..bww.b
    -22,   // b.bww.b
    -39,   // w.bww.b
    -22,   // .bbww.b
    119,   // bbbww.b
    60,    // wbbww.b
    21,    // .wbww.b
    66,    // bwbww.b
    -47,   // wwbww.b
    6,     // ..www.b
    -43,   // b.www.b
    42,    // w.www.b
    142,   // .bwww.b
    -45,   // bbwww.b
    -8,    // wbwww.b
    -82,   // .wwww.b
    -1,    // bwwww.b
    -18,   // wwwww.b
    28,    // .....bb
    -15,   // b....bb
    45,    // w....bb
    -46,   // .b...bb
    12,    // bb...bb
    -57,   // wb...bb
    -27,   // .w...bb
    -27,   // bw...bb
    0,     // ww...bb
    -58,   // ..b..bb
    -94,   // b.b..bb
    35,    // w.b..bb
    10,    // .bb..bb
    132,   // bbb..bb
    -59,   // wbb..bb
    139,   // .wb..bb
    -59,   // bwb..bb
    31,    // wwb..bb
    -26,   // ..w..bb
    -15,   // b.w..bb
    -29,   // w.w..bb
    -18,   // .bw..bb
    -24,   // bbw..bb
    -9,    // wbw..bb
    93,    // .ww..bb
    -25,   // bww..bb
    -30,   // www..bb
    119,   // ...b.bb
    -39,   // b..b.bb
    -79,   // w..b.bb
    -80,   // .b.b.bb
    11,    // bb.b.bb
    84,    // wb.b.bb
    149,   // .w.b.bb
    -72,   // bw.b.bb
    39,    // ww.b.bb
    37,    // ..bb.bb
    -30,   // b.bb.bb
    -2,    // w.bb.bb
    18,    // .bbb.bb
    -38,   // bbbb.bb
    -4,    // wbbb.bb
    102,   // .wbb.bb
    42,    // bwbb.bb
    -120,  // wwbb.bb
    -27,   // ..wb.bb
    74,    // b.wb.bb
    -27,   // w.wb.bb
    -17,   // .bwb.bb
    -20,   // bbwb.bb
    -41,   // wbwb.bb
    41,    // .wwb.bb
    58,    // bwwb.bb
    53,    // wwwb.bb
    41,    // ...w.bb
    60,    // b..w.bb
    -110,  // w..w.bb
    -40,   // .b.w.bb
    72,    // bb.w.bb
    52,    // wb.w.bb
    14,    // .w.w.bb
    91,    // bw.w.bb
    -39,   // ww.w.bb
    -35,   // ..bw.bb
    -3,    // b.bw.bb
    35,    // w.bw.bb
    77,    // .bbw.bb
    52,    // bbbw.bb
    93,    // wbbw.bb
    21,    // .wbw.bb
    177,   // bwbw.bb
    61,    // wwbw.bb
    49,    // ..ww.bb
    -17,   // b.ww.bb
    -3,    // w.ww.bb
    -27,   // .bww.bb
    -28,   // bbww.bb
    27,    // wbww.bb
    13,    // .www.bb
    6,     // bwww.bb
    -32,   // wwww.bb
    85,    // ....bbb
    -89,   // b...bbb
    91,    // w...bbb
    22,    // .b..bbb
    132,   // bb..bbb
    -16,   // wb..bbb
    95,    // .w..bbb
    5,     // bw..bbb
    30,    // ww..bbb
    189,   // ..b.bbb
    32,    // b.b.bbb
    2,     // w.b.bbb
    -20,   // .bb.bbb
    33,    // bbb.bbb
    13,    // wbb.bbb
    -13,   // .wb.bbb
    -71,   // bwb.bbb
    -81,   // wwb.bbb
    37,    // ..w.bbb
    -33,   // b.w.bbb
    -30,   // w.w.bbb
    -15,   // .bw.bbb
    61,    // bbw.bbb
    -67,   // wbw.bbb
    97,    // .ww.bbb
    -32,   // bww.bbb
    0,     // www.bbb
    718,   // ...bbbb
    12,    // b..bbbb
    67,    // w..bbbb
    -91,   // .b.bbbb
    -38,   // bb.bbbb
    64,    // wb.bbbb
    264,   // .w.bbbb
    109,   // bw.bbbb
    32,    // ww.bbbb
    82,    // ..bbbbb
    -88,   // b.bbbbb
    18,    // w.bbbbb
    -70,   // .bbbbbb
    -34,   // bbbbbbb
    -21,   // wbbbbbb
    302,   // .wbbbbb
    -13,   // bwbbbbb
    121,   // wwbbbbb
    102,   // ..wbbbb
    98,    // b.wbbbb
    -11,   // w.wbbbb
    -131,  // .bwbbbb
    -40,   // bbwbbbb
    52,    // wbwbbbb
    -57,   // .wwbbbb
    7,     // bwwbbbb
    -101,  // wwwbbbb
    116,   // ...wbbb
    71,    // b..wbbb
    -37,   // w..wbbb
    -109,  // .b.wbbb
    52,    // bb.wbbb
    -46,   // wb.wbbb
    -52,   // .w.wbbb
    31,    // bw.wbbb
    -53,   // ww.wbbb
    -157,  // ..bwbbb
    -58,   // b.bwbbb
    44,    // w.bwbbb
    -69,   // .bbwbbb
    -13,   // bbbwbbb
    -183,  // wbbwbbb
    -43,   // .wbwbbb
    54,    // bwbwbbb
    -17,   // wwbwbbb
    99,    // ..wwbbb
    119,   // b.wwbbb
    -73,   // w.wwbbb
    13,    // .bwwbbb
    73,    // bbwwbbb
    -98,   // wbwwbbb
    44,    // .wwwbbb
    9,     // bwwwbbb
    101,   // wwwwbbb
    -69,   // ....wbb
    -40,   // b...wbb
    -10,   // w...wbb
    -25,   // .b..wbb
    -24,   // bb..wbb
    -31,   // wb..wbb
    -37,   // .w..wbb
    51,    // bw..wbb
    -31,   // ww..wbb
    -34,   // ..b.wbb
    35,    // b.b.wbb
    28,    // w.b.wbb
    51,    // .bb.wbb
    61,    // bbb.wbb
    -5,    // wbb.wbb
    2,     // .wb.wbb
    27,    // bwb.wbb
    0,     // wwb.wbb
    49,    // ..w.wbb
    -112,  // b.w.wbb
    24,    // w.w.wbb
    -15,   // .bw.wbb
    -66,   // bbw.wbb
    -59,   // wbw.wbb
    26,    // .ww.wbb
    14,    // bww.wbb
    81,    // www.wbb
    -85,   // ...bwbb
    -83,   // b..bwbb
    12,    // w..bwbb
    44,    // .b.bwbb
    -20,   // bb.bwbb
    80,    // wb.bwbb
    -54,   // .w.bwbb
    -55,   // bw.bwbb
    -61,   // ww.bwbb
    -8,    // ..bbwbb
    -46,   // b.bbwbb
    47,    // w.bbwbb
    -109,  // .bbbwbb
    -40,   // bbbbwbb
    -18,   // wbbbwbb
    24,    // .wbbwbb
    -22,   // bwbbwbb
    34,    // wwbbwbb
    -32,   // ..wbwbb
    -6,    // b.wbwbb
    -103,  // w.wbwbb
    5,     // .bwbwbb
    45,    // bbwbwbb
    126,   // wbwbwbb
    -124,  // .wwbwbb
    13,    // bwwbwbb
    17,    // wwwbwbb
    5,     // ...wwbb
    -53,   // b..wwbb
    52,    // w..wwbb
    -1,    // .b.wwbb
    -28,   // bb.wwbb
    -15,   // wb.wwbb
    0,     // .w.wwbb
    100,   // bw.wwbb
    120,   // ww.wwbb
    -14,   // ..bwwbb
    -66,   // b.bwwbb
    5,     // w.bwwbb
    -56,   // .bbwwbb
    73,    // bbbwwbb
    16,    // wbbwwbb
    -71,   // .wbwwbb
    -37,   // bwbwwbb
    -34,   // wwbwwbb
    -21,   // ..wwwbb
    -45,   // b.wwwbb
    -6,    // w.wwwbb
    100,   // .bwwwbb
    -3,    // bbwwwbb
    21,    // wbwwwbb
    -7,    // .wwwwbb
    -4,    // bwwwwbb
    -121,  // wwwwwbb
    11,    // .....wb
    0,     // b....wb
    -10,   // w....wb
    -66,   // .b...wb
    -27,   // bb...wb
    0,     // wb...wb
    -29,   // .w...wb
    -151,  // bw...wb
    57,    // ww...wb
    -60,   // ..b..wb
    19,    // b.b..wb
    -130,  // w.b..wb
    -20,   // .bb..wb
    5,     // bbb..wb
    31,    // wbb..wb
    94,    // .wb..wb
    -94,   // bwb..wb
    31,    // wwb..wb
    -20,   // ..w..wb
    53,    // b.w..wb
    -125,  // w.w..wb
    -90,   // .bw..wb
    51,    // bbw..wb
    8,     // wbw..wb
    -2,    // .ww..wb
    -57,   // bww..wb
    16,    // www..wb
    -18,   // ...b.wb
    1,     // b..b.wb
    26,    // w..b.wb
    -4,    // .b.b.wb
    -72,   // bb.b.wb
    -55,   // wb.b.wb
    76,    // .w.b.wb
    42,    // bw.b.wb
    -52,   // ww.b.wb
    -8,    // ..bb.wb
    -21,   // b.bb.wb
    -76,   // w.bb.wb
    64,    // .bbb.wb
    109,   // bbbb.wb
    -34,   // wbbb.wb
    -41,   // .wbb.wb
    -44,   // bwbb.wb
    15,    // wwbb.wb
    -13,   // ..wb.wb
    45,    // b.wb.wb
    2,     // w.wb.wb
    -24,   // .bwb.wb
    -55,   // bbwb.wb
    -6,    // wbwb.wb
    -3,    // .wwb.wb
    69,    // bwwb.wb
    46,    // wwwb.wb
    82,    // ...w.wb
    -63,   // b..w.wb
    99,    // w..w.wb
    109,   // .b.w.wb
    91,    // bb.w.wb
    55,    // wb.w.wb
    -8,    // .w.w.wb
    28,    // bw.w.wb
    -84,   // ww.w.wb
    35,    // ..bw.wb
    33,    // b.bw.wb
    31,    // w.bw.wb
    -26,   // .bbw.wb
    31,    // bbbw.wb
    -23,   // wbbw.wb
    37,    // .wbw.wb
    35,    // bwbw.wb
    -80,   // wwbw.wb
    11,    // ..ww.wb
    -33,   // b.ww.wb
    69,    // w.ww.wb
    74,    // .bww.wb
    100,   // bbww.wb
    81,    // wbww.wb
    -55,   // .www.wb
    -49,   // bwww.wb
    -64,   // wwww.wb
    53,    // ....bwb
    7,     // b...bwb
    45,    // w...bwb
    -64,   // .b..bwb
    -59,   // bb..bwb
    -8,    // wb..bwb
    29,    // .w..bwb
    -94,   // bw..bwb
    9,     // ww..bwb
    -87,   // ..b.bwb
    4,     // b.b.bwb
    -48,   // w.b.bwb
    32,    // .bb.bwb
    -71,   // bbb.bwb
    -43,   // wbb.bwb
    3,     // .wb.bwb
    28,    // bwb.bwb
    59,    // wwb.bwb
    69,    // ..w.bwb
    31,    // b.w.bwb
    -30,   // w.w.bwb
    52,    // .bw.bwb
    27,    // bbw.bwb
    0,     // wbw.bwb
    128,   // .ww.bwb
    97,    // bww.bwb
    67,    // www.bwb
    -20,   // ...bbwb
    111,   // b..bbwb
    -115,  // w..bbwb
    -53,   // .b.bbwb
    42,    // bb.bbwb
    -81,   // wb.bbwb
    -169,  // .w.bbwb
    -44,   // bw.bbwb
    -27,   // ww.bbwb
    -53,   // ..bbbwb
    -79,   // b.bbbwb
    8,     // w.bbbwb
    -77,   // .bbbbwb
    -13,   // bbbbbwb
    -119,  // wbbbbwb
    18,    // .wbbbwb
    64,    // bwbbbwb
    -21,   // wwbbbwb
    16,    // ..wbbwb
    100,   // b.wbbwb
    -29,   // w.wbbwb
    -111,  // .bwbbwb
    -22,   // bbwbbwb
    63,    // wbwbbwb
    49,    // .wwbbwb
    7,     // bwwbbwb
    98,    // wwwbbwb
    14,    // ...wbwb
    -29,   // b..wbwb
    67,    // w..wbwb
    3,     // .b.wbwb
    177,   // bb.wbwb
    6,     // wb.wbwb
    -24,   // .w.wbwb
    35,    // bw.wbwb
    41,    // ww.wbwb
    -67,   // ..bwbwb
    28,    // b.bwbwb
    47,    // w.bwbwb
    -48,   // .bbwbwb
    54,    // bbbwbwb
    -44,   // wbbwbwb
    64,    // .wbwbwb
    -67,   // bwbwbwb
    -126,  // wwbwbwb
    -84,   // ..wwbwb
    66,    // b.wwbwb
    -42,   // w.wwbwb
    -111,  // .bwwbwb
    -37,   // bbwwbwb
    -63,   // wbwwbwb
    -79,   // .wwwbwb
    -113,  // bwwwbwb
    -52,   // wwwwbwb
    100,   // ....wwb
    -38,   // b...wwb
    122,   // w...wwb
    17,    // .b..wwb
    -25,   // bb..wwb
    -31,   // wb..wwb
    -87,   // .w..wwb
    -57,   // bw..wwb
    59,    // ww..wwb
    -49,   // ..b.wwb
    221,   // b.b.wwb
    42,    // w.b.wwb
    102,   // .bb.wwb
    -32,   // bbb.wwb
    0,     // wbb.wwb
    64,    // .wb.wwb
    97,    // bwb.wwb
    5,     // wwb.wwb
    189,   // ..w.wwb
    49,    // b.w.wwb
    -20,   // w.w.wwb
    -44,   // .bw.wwb
    14,    // bbw.wwb
    43,    // wbw.wwb
    4,     // .ww.wwb
    -8,    // bww.wwb
    -13,   // www.wwb
    22,    // ...bwwb
    -79,   // b..bwwb
    64,    // w..bwwb
    -70,   // .b.bwwb
    58,    // bb.bwwb
    23,    // wb.bwwb
    92,    // .w.bwwb
    69,    // bw.bwwb
    -93,   // ww.bwwb
    -114,  // ..bbwwb
    -55,   // b.bbwwb
    -60,   // w.bbwwb
    22,    // .bbbwwb
    7,     // bbbbwwb
    18,    // wbbbwwb
    83,    // .wbbwwb
    7,     // bwbbwwb
    -16,   // wwbbwwb
    -10,   // ..wbwwb
    80,    // b.wbwwb
    -20,   // w.wbwwb
    104,   // .bwbwwb
    13,    // bbwbwwb
    44,    // wbwbwwb
    85,    // .wwbwwb
    -25,   // bwwbwwb
    183,   // wwwbwwb
    101,   // ...wwwb
    -29,   // b..wwwb
    97,    // w..wwwb
    40,    // .b.wwwb
    6,     // bb.wwwb
    34,    // wb.wwwb
    -90,   // .w.wwwb
    -49,   // bw.wwwb
    4,     // ww.wwwb
    30,    // ..bwwwb
    -34,   // b.bwwwb
    30,    // w.bwwwb
    105,   // .bbwwwb
    9,     // bbbwwwb
    -18,   // wbbwwwb
    11,    // .wbwwwb
    -113,  // bwbwwwb
    18,    // wwbwwwb
    -11,   // ..wwwwb
    -1,    // b.wwwwb
    24,    // w.wwwwb
    265,   // .bwwwwb
    -4,    // bbwwwwb
    119,   // wbwwwwb
    -16,   // .wwwwwb
    82,    // bwwwwwb
    21,    // wwwwwwb
    -19,   // ......w
    0,     // b.....w
    -34,   // w.....w
    -69,   // .b....w
    45,    // bb....w
    0,     // wb....w
    30,    // .w....w
    -10,   // bw....w
    15,    // ww....w
    -86,   // ..b...w
    -87,   // b.b...w
    5,     // w.b...w
    23,    // .bb...w
    91,    // bbb...w
    38,    // wbb...w
    -20,   // .wb...w
    45,    // bwb...w
    40,    // wwb...w
    -29,   // ..w...w
    79,    // b.w...w
    -5,    // w.w...w
    94,    // .bw...w
    -10,   // bbw...w
    -7,    // wbw...w
    1,     // .ww...w
    122,   // bww...w
    89,    // www...w
    -7,    // ...b..w
    32,    // b..b..w
    10,    // w..b..w
    -20,   // .b.b..w
    -79,   // bb.b..w
    63,    // wb.b..w
    76,    // .w.b..w
    26,    // bw.b..w
    -60,   // ww.b..w
    -35,   // ..bb..w
    -38,   // b.bb..w
    6,     // w.bb..w
    90,    // .bbb..w
    67,    // bbbb..w
    29,    // wbbb..w
    -33,   // .wbb..w
    -115,  // bwbb..w
    53,    // wwbb..w
    -102,  // ..wb..w
    -20,   // b.wb..w
    -63,   // w.wb..w
    68,    // .bwb..w
    12,    // bbwb..w
    29,    // wbwb..w
    -64,   // .wwb..w
    64,    // bwwb..w
    -71,   // wwwb..w
    7,     // ...w..w
    -32,   // b..w..w
    38,    // w..w..w
    -12,   // .b.w..w
    -110,  // bb.w..w
    -1,    // wb.w..w
    42,    // .w.w..w
    99,    // bw.w..w
    39,    // ww.w..w
    47,    // ..bw..w
    -2,    // b.bw..w
    60,    // w.bw..w
    38,    // .bbw..w
    -37,   // bbbw..w
    79,    // wbbw..w
    -36,   // .wbw..w
    67,    // bwbw..w
    83,    // wwbw..w
    -40,   // ..ww..w
    12,    // b.ww..w
    27,    // w.ww..w
    9,     // .bww..w
    52,    // bbww..w
    -111,  // wbww..w
    57,    // .www..w
    97,    // bwww..w
    -12,   // wwww..w
    -23,   // ....b.w
    -79,   // b...b.w
    5,     // w...b.w
    -72,   // .b..b.w
    35,    // bb..b.w
    -53,   // wb..b.w
    14,    // .w..b.w
    -130,  // bw..b.w
    15,    // ww..b.w
    -26,   // ..b.b.w
    72,    // b.b.b.w
    -63,   // w.b.b.w
    15,    // .bb.b.w
    2,     // bbb.b.w
    -49,   // wbb.b.w
    32,    // .wb.b.w
    -48,   // bwb.b.w
    112,   // wwb.b.w
    26,    // ..w.b.w
    0,     // b.w.b.w
    -13,   // w.w.b.w
    -25,   // .bw.b.w
    28,    // bbw.b.w
    -31,   // wbw.b.w
    4,     // .ww.b.w
    42,    // bww.b.w
    33,    // www.b.w
    -30,   // ...bb.w
    -12,   // b..bb.w
    6,     // w..bb.w
    118,   // .b.bb.w
    -2,    // bb.bb.w
    33,    // wb.bb.w
    2,     // .w.bb.w
    -76,   // bw.bb.w
    17,    // ww.bb.w
    -6,    // ..bbb.w
    -42,   // b.bbb.w
    43,    // w.bbb.w
    82,    // .bbbb.w
    18,    // bbbbb.w
    1,     // wbbbb.w
    -142,  // .wbbb.w
    8,     // bwbbb.w
    45,    // wwbbb.w
    -62,   // ..wbb.w
    39,    // b.wbb.w
    22,    // w.wbb.w
    -21,   // .bwbb.w
    47,    // bbwbb.w
    -66,   // wbwbb.w
    22,    // .wwbb.w
    -60,   // bwwbb.w
    -119,  // wwwbb.w
    -67,   // ...wb.w
    20,    // b..wb.w
    60,    // w..wb.w
    38,    // .b.wb.w
    35,    // bb.wb.w
    -45,   // wb.wb.w
    19,    // .w.wb.w
    31,    // bw.wb.w
    -74,   // ww.wb.w
    -2,    // ..bwb.w
    -7,    // b.bwb.w
    69,    // w.bwb.w
    -113,  // .bbwb.w
    44,    // bbbwb.w
    -80,   // wbbwb.w
    39,    // .wbwb.w
    47,    // bwbwb.w
    6,     // wwbwb.w
    49,    // ..wwb.w
    -39,   // b.wwb.w
    -14,   // w.wwb.w
    -20,   // .bwwb.w
    5,     // bbwwb.w
    -100,  // wbwwb.w
    -19,   // .wwwb.w
    30,    // bwwwb.w
    -98,   // wwwwb.w
    -86,   // ....w.w
    87,    // b...w.w
    -5,    // w...w.w
    -35,   // .b..w.w
    -29,   // bb..w.w
    -19,   // wb..w.w
    -42,   // .w..w.w
    -125,  // bw..w.w
    94,    // ww..w.w
    -79,   // ..b.w.w
    0,     // b.b.w.w
    -13,   // w.b.w.w
    56,    // .bb.w.w
    -30,   // bbb.w.w
    -221,  // wbb.w.w
    51,    // .wb.w.w
    -30,   // bwb.w.w
    -35,   // wwb.w.w
    34,    // ..w.w.w
    -72,   // b.w.w.w
    -25,   // w.w.w.w
    123,   // .bw.w.w
    24,    // bbw.w.w
    -4,    // wbw.w.w
    -24,   // .ww.w.w
    -20,   // bww.w.w
    -32,   // www.w.w
    -91,   // ...bw.w
    2,     // b..bw.w
    -63,   // w..bw.w
    -27,   // .b.bw.w
    -27,   // bb.bw.w
    -33,   // wb.bw.w
    -48,   // .w.bw.w
    2,     // bw.bw.w
    3,     // ww.bw.w
    -29,   // ..bbw.w
    84,    // b.bbw.w
    22,    // w.bbw.w
    -75,   // .bbbw.w
    -11,   // bbbbw.w
    34,    // wbbbw.w
    80,    // .wbbw.w
    -29,   // bwbbw.w
    66,    // wwbbw.w
    -7,    // ..wbw.w
    7,     // b.wbw.w
    -24,   // w.wbw.w
    30,    // .bwbw.w
    -103,  // bbwbw.w
    -28,   // wbwbw.w
    88,    // .wwbw.w
    -20,   // bwwbw.w
    58,    // wwwbw.w
    -99,   // ...ww.w
    38,    // b..ww.w
    27,    // w..ww.w
    36,    // .b.ww.w
    -3,    // bb.ww.w
    21,    // wb.ww.w
    -31,   // .w.ww.w
    69,    // bw.ww.w
    30,    // ww.ww.w
    69,    // ..bww.w
    -84,   // b.bww.w
    -14,   // w.bww.w
    -21,   // .bbww.w
    -73,   // bbbww.w
    55,    // wbbww.w
    58,    // .wbww.w
    -42,   // bwbww.w
    46,    // wwbww.w
    -118,  // ..www.w
    42,    // b.www.w
    -51,   // w.www.w
    -240,  // .bwww.w
    -6,    // bbwww.w
    79,    // wbwww.w
    -138,  // .wwww.w
    24,    // bwwww.w
    88,    // wwwww.w
    -11,   // .....bw
    10,    // b....bw
    0,     // w....bw
    29,    // .b...bw
    -57,   // bb...bw
    151,   // wb...bw
    66,    // .w...bw
    0,     // bw...bw
    27,    // ww...bw
    20,    // ..b..bw
    125,   // b.b..bw
    -53,   // w.b..bw
    2,     // .bb..bw
    -16,   // bbb..bw
    57,    // wbb..bw
    90,    // .wb..bw
    -8,    // bwb..bw
    -51,   // wwb..bw
    60,    // ..w..bw
    130,   // b.w..bw
    -19,   // w.w..bw
    -94,   // .bw..bw
    -31,   // bbw..bw
    94,    // wbw..bw
    20,    // .ww..bw
    -31,   // bww..bw
    -5,    // www..bw
    -82,   // ...b.bw
    -99,   // b..b.bw
    63,    // w..b.bw
    8,     // .b.b.bw
    84,    // bb.b.bw
    -28,   // wb.b.bw
    -109,  // .w.b.bw
    -55,   // bw.b.bw
    -91,   // ww.b.bw
    -11,   // ..bb.bw
    -69,   // b.bb.bw
    33,    // w.bb.bw
    55,    // .bbb.bw
    64,    // bbbb.bw
    49,    // wbbb.bw
    -74,   // .wbb.bw
    -81,   // bwbb.bw
    -100,  // wwbb.bw
    -35,   // ..wb.bw
    -31,   // b.wb.bw
    -33,   // w.wb.bw
    -37,   // .bwb.bw
    80,    // bbwb.bw
    -35,   // wbwb.bw
    26,    // .wwb.bw
    23,    // bwwb.bw
    -31,   // wwwb.bw
    18,    // ...w.bw
    -26,   // b..w.bw
    -1,    // w..w.bw
    -76,   // .b.w.bw
    52,    // bb.w.bw
    -42,   // wb.w.bw
    4,     // .w.w.bw
    55,    // bw.w.bw
    72,    // ww.w.bw
    13,    // ..bw.bw
    -2,    // b.bw.bw
    -45,   // w.bw.bw
    3,     // .bbw.bw
    -46,   // bbbw.bw
    -69,   // wbbw.bw
    24,    // .wbw.bw
    6,     // bwbw.bw
    55,    // wwbw.bw
    8,     // ..ww.bw
    76,    // b.ww.bw
    21,    // w.ww.bw
    41,    // .bww.bw
    -15,   // bbww.bw
    44,    // wbww.bw
    -64,   // .www.bw
    34,    // bwww.bw
    -109,  // wwww.bw
    -100,  // ....bbw
    -122,  // b...bbw
    38,    // w...bbw
    87,    // .b..bbw
    -59,   // bb..bbw
    57,    // wb..bbw
    -17,   // .w..bbw
    31,    // bw..bbw
    25,    // ww..bbw
    -189,  // ..b.bbw
    20,    // b.b.bbw
    -49,   // w.b.bbw
    -4,    // .bb.bbw
    13,    // bbb.bbw
    8,     // wbb.bbw
    44,    // .wb.bbw
    -43,   // bwb.bbw
    -14,   // wwb.bbw
    49,    // ..w.bbw
    -42,   // b.w.bbw
    -221,  // w.w.bbw
    -64,   // .bw.bbw
    -5,    // bbw.bbw
    -97,   // wbw.bbw
    -102,  // .ww.bbw
    0,     // bww.bbw
    32,    // www.bbw
    -101,  // ...bbbw
    -97,   // b..bbbw
    29,    // w..bbbw
    90,    // .b.bbbw
    -4,    // bb.bbbw
    49,    // wb.bbbw
    -40,   // .w.bbbw
    -34,   // bw.bbbw
    -6,    // ww.bbbw
    11,    // ..bbbbw
    -24,   // b.bbbbw
    1,     // w.bbbbw
    16,    // .bbbbbw
    -21,   // bbbbbbw
    -82,   // wbbbbbw
    -265,  // .wbbbbw
    -119,  // bwbbbbw
    4,     // wwbbbbw
    -30,   // ..wbbbw
    -30,   // b.wbbbw
    34,    // w.wbbbw
    -11,   // .bwbbbw
    -18,   // bbwbbbw
    113,   // wbwbbbw
    -105,  // .wwbbbw
    18,    // bwwbbbw
    -9,    // wwwbbbw
    -22,   // ...wbbw
    -64,   // b..wbbw
    79,    // w..wbbw
    -92,   // .b.wbbw
    93,    // bb.wbbw
    -69,   // wb.wbbw
    70,    // .w.wbbw
    -23,   // bw.wbbw
    -58,   // ww.wbbw
    10,    // ..bwbbw
    20,    // b.bwbbw
    -80,   // w.bwbbw
    -85,   // .bbwbbw
    -183,  // bbbwbbw
    25,    // wbbwbbw
    -104,  // .wbwbbw
    -44,   // bwbwbbw
    -13,   // wwbwbbw
    114,   // ..wwbbw
    60,    // b.wwbbw
    55,    // w.wwbbw
    -83,   // .bwwbbw
    16,    // bbwwbbw
    -7,    // wbwwbbw
    -22,   // .wwwbbw
    -18,   // bwwwbbw
    -7,    // wwwwbbw
    -53,   // ....wbw
    -45,   // b...wbw
    -7,    // w...wbw
    -29,   // .b..wbw
    -9,    // bb..wbw
    94,    // wb..wbw
    64,    // .w..wbw
    8,     // bw..wbw
    59,    // ww..wbw
    -69,   // ..b.wbw
    30,    // b.b.wbw
    -31,   // w.b.wbw
    -128,  // .bb.wbw
    -67,   // bbb.wbw
    -97,   // wbb.wbw
    -52,   // .wb.wbw
    0,     // bwb.wbw
    -27,   // wwb.wbw
    87,    // ..w.wbw
    48,    // b.w.wbw
    -4,    // w.w.wbw
    -3,    // .bw.wbw
    -59,   // bbw.wbw
    -28,   // wbw.wbw
    -32,   // .ww.wbw
    43,    // bww.wbw
    71,    // www.wbw
    -14,   // ...bwbw
    -67,   // b..bwbw
    29,    // w..bwbw
    24,    // .b.bwbw
    -41,   // bb.bwbw
    -35,   // wb.bwbw
    -3,    // .w.bwbw
    -6,    // bw.bwbw
    -177,  // ww.bwbw
    84,    // ..bbwbw
    42,    // b.bbwbw
    -66,   // w.bbwbw
    79,    // .bbbwbw
    52,    // bbbbwbw
    113,   // wbbbwbw
    111,   // .wbbwbw
    63,    // bwbbwbw
    37,    // wwbbwbw
    67,    // ..wbwbw
    -47,   // b.wbwbw
    -28,   // w.wbwbw
    -64,   // .bwbwbw
    126,   // bbwbwbw
    67,    // wbwbwbw
    48,    // .wwbwbw
    44,    // bwwbwbw
    -54,   // wwwbwbw
    20,    // ...wwbw
    115,   // b..wwbw
    -111,  // w..wwbw
    169,   // .b.wwbw
    27,    // bb.wwbw
    44,    // wb.wwbw
    53,    // .w.wwbw
    81,    // bw.wwbw
    -42,   // ww.wwbw
    -16,   // ..bwwbw
    29,    // b.bwwbw
    -100,  // w.bwwbw
    -49,   // .bbwwbw
    -98,   // bbbwwbw
    -7,    // wbbwwbw
    111,   // .wbwwbw
    -63,   // bwbwwbw
    22,    // wwbwwbw
    53,    // ..wwwbw
    -8,    // b.wwwbw
    79,    // w.wwwbw
    -18,   // .bwwwbw
    21,    // bbwwwbw
    -64,   // wbwwwbw
    77,    // .wwwwbw
    119,   // bwwwwbw
    13,    // wwwwwbw
    -28,   // .....ww
    -45,   // b....ww
    15,    // w....ww
    27,    // .b...ww
    0,     // bb...ww
    27,    // wb...ww
    46,    // .w...ww
    57,    // bw...ww
    -12,   // ww...ww
    26,    // ..b..ww
    29,    // b.b..ww
    15,    // w.b..ww
    -93,   // .bb..ww
    30,    // bbb..ww
    25,    // wbb..ww
    18,    // .wb..ww
    9,     // bwb..ww
    24,    // wwb..ww
    58,    // ..w..ww
    -35,   // b.w..ww
    94,    // w.w..ww
    -139,  // .bw..ww
    -31,   // bbw..ww
    59,    // wbw..ww
    -10,   // .ww..ww
    59,    // bww..ww
    -132,  // www..ww
    -41,   // ...b.ww
    110,   // b..b.ww
    -60,   // w..b.ww
    -14,   // .b.b.ww
    39,    // bb.b.ww
    -91,   // wb.b.ww
    40,    // .w.b.ww
    -52,   // bw.b.ww
    -72,   // ww.b.ww
    -49,   // ..bb.ww
    3,     // b.bb.ww
    17,    // w.bb.ww
    -13,   // .bbb.ww
    32,    // bbbb.ww
    -6,    // wbbb.ww
    27,    // .wbb.ww
    -27,   // bwbb.ww
    28,    // wwbb.ww
    35,    // ..wb.ww
    -35,   // b.wb.ww
    3,     // w.wb.ww
    -21,   // .bwb.ww
    -61,   // bbwb.ww
    -177,  // wbwb.ww
    -77,   // .wwb.ww
    -93,   // bwwb.ww
    -52,   // wwwb.ww
    -119,  // ...w.ww
    79,    // b..w.ww
    39,    // w..w.ww
    -149,  // .b.w.ww
    -39,   // bb.w.ww
    72,    // wb.w.ww
    80,    // .w.w.ww
    -84,   // bw.w.ww
    -11,   // ww.w.ww
    27,    // ..bw.ww
    27,    // b.bw.ww
    -74,   // w.bw.ww
    -41,   // .bbw.ww
    -53,   // bbbw.ww
    -58,   // wbbw.ww
    17,    // .wbw.ww
    41,    // bwbw.ww
    20,    // wwbw.ww
    -37,   // ..ww.ww
    2,     // b.ww.ww
    30,    // w.ww.ww
    -102,  // .bww.ww
    120,   // bbww.ww
    -42,   // wbww.ww
    -18,   // .www.ww
    4,     // bwww.ww
    38,    // wwww.ww
    69,    // ....bww
    10,    // b...bww
    40,    // w...bww
    37,    // .b..bww
    31,    // bb..bww
    -51,   // wb..bww
    25,    // .w..bww
    31,    // bw..bww
    24,    // ww..bww
    -49,   // ..b.bww
    -24,   // b.b.bww
    112,   // w.b.bww
    -26,   // .bb.bww
    -81,   // bbb.bww
    -14,   // wbb.bww
    15,    // .wb.bww
    59,    // bwb.bww
    66,    // wwb.bww
    34,    // ..w.bww
    -28,   // b.w.bww
    -35,   // w.w.bww
    -2,    // .bw.bww
    0,     // bbw.bww
    -27,   // wbw.bww
    -51,   // .ww.bww
    5,     // bww.bww
    -61,   // www.bww
    -5,    // ...bbww
    -52,   // b..bbww
    53,    // w..bbww
    0,     // .b.bbww
    -120,  // bb.bbww
    -100,  // wb.bbww
    1,     // .w.bbww
    15,    // bw.bbww
    28,    // ww.bbww
    21,    // ..bbbww
    6,     // b.bbbww
    45,    // w.bbbww
    7,     // .bbbbww
    121,   // bbbbbww
    4,     // wbbbbww
    -100,  // .wbbbww
    -21,   // bwbbbww
    3,     // wwbbbww
    14,    // ..wbbww
    -5,    // b.wbbww
    66,    // w.wbbww
    71,    // .bwbbww
    34,    // bbwbbww
    37,    // wbwbbww
    56,    // .wwbbww
    -16,   // bwwbbww
    -73,   // wwwbbww
    85,    // ...wbww
    -12,   // b..wbww
    83,    // w..wbww
    54,    // .b.wbww
    61,    // bb.wbww
    55,    // wb.wbww
    -44,   // .w.wbww
    -80,   // bw.wbww
    20,    // ww.wbww
    32,    // ..bwbww
    103,   // b.bwbww
    6,     // w.bwbww
    124,   // .bbwbww
    -17,   // bbbwbww
    -13,   // wbbwbww
    -5,    // .wbwbww
    -126,  // bwbwbww
    -45,   // wwbwbww
    8,     // ..wwbww
    -47,   // b.wwbww
    46,    // w.wwbww
    -24,   // .bwwbww
    -34,   // bbwwbww
    22,    // wbwwbww
    109,   // .wwwbww
    18,    // bwwwbww
    40,    // wwwwbww
    -85,   // ....www
    -91,   // b...www
    89,    // w...www
    -95,   // .b..www
    -30,   // bb..www
    -5,    // wb..www
    -22,   // .w..www
    16,    // bw..www
    -132,  // ww..www
    -37,   // ..b.www
    30,    // b.b.www
    33,    // w.b.www
    -97,   // .bb.www
    0,     // bbb.www
    32,    // wbb.www
    15,    // .wb.www
    67,    // bwb.www
    -61,   // wwb.www
    -189,  // ..w.www
    -2,    // b.w.www
    -32,   // w.w.www
    13,    // .bw.www
    81,    // bbw.www
    71,    // wbw.www
    20,    // .ww.www
    -13,   // bww.www
    -33,   // www.www
    -116,  // ...bwww
    37,    // b..bwww
    -71,   // w..bwww
    52,    // .b.bwww
    53,    // bb.bwww
    -31,   // wb.bwww
    109,   // .w.bwww
    46,    // bw.bwww
    -52,   // ww.bwww
    -99,   // ..bbwww
    73,    // b.bbwww
    -119,  // w.bbwww
    -44,   // .bbbwww
    -101,  // bbbbwww
    -9,    // wbbbwww
    -13,   // .wbbwww
    98,    // bwbbwww
    -73,   // wwbbwww
    157,   // ..wbwww
    -44,   // b.wbwww
    58,    // w.wbwww
    43,    // .bwbwww
    17,    // bbwbwww
    -54,   // wbwbwww
    69,    // .wwbwww
    183,   // bwwbwww
    13,    // wwwbwww
    -718,  // ...wwww
    -67,   // b..wwww
    -12,   // w..wwww
    -264,  // .b.wwww
    -32,   // bb.wwww
    -109,  // wb.wwww
    91,    // .w.wwww
    -64,   // bw.wwww
    38,    // ww.wwww
    -102,  // ..bwwww
    11,    // b.bwwww
    -98,   // w.bwwww
    57,    // .bbwwww
    101,   // bbbwwww
    -7,    // wbbwwww
    131,   // .wbwwww
    -52,   // bwbwwww
    40,    // wwbwwww
    -82,   // ..wwwww
    -18,   // b.wwwww
    88,    // w.wwwww
    -302,  // .bwwwww
    -121,  // bbwwwww
    13,    // wbwwwww
    70,    // .wwwwww
    21,    // bwwwwww
    34,    // wwwwwww
    0,     // captures=0 threats=0
    55,    // captures=0 threats=1
    115,   // captures=0 threats=2
    178,   // captures=0 threats=3
    180,   // captures=0 threats=4
    69,    // captures=0 additional threats
    72,    // captures=1 threats=0
    123,   // captures=1 threats=1
    212,   // captures=1 threats=2
    437,   // captures=1 threats=3
    554,   // captures=1 threats=4
    7,     // captures=1 additional threats
    96,    // captures=2 threats=0
    281,   // captures=2 threats=1
    373,   // captures=2 threats=2
    699,   // captures=2 threats=3
    856,   // captures=2 threats=4
    141,   // captures=2 additional threats
    148,   // captures=3 threats=0
    452,   // captures=3 threats=1
    627,   // captures=3 threats=2
    774,   // captures=3 threats=3
    907,   // captures=3 threats=4
    189,   // captures=3 additional threats
    156,   // captures=4 threats=0
    474,   // captures=4 threats=1
    758,   // captures=4 threats=2
    979,   // captures=4 threats=3
    1157,  // captures=4 threats=4
    351,   // captures=4 additional threats
].into_boxed_slice()
