vec![
    0,     // ......
    -2,    // b.....
    2,     // w.....
    -4,    // .b....
    -10,   // bb....
    18,    // wb....
    4,     // .w....
    -18,   // bw....
    10,    // ww....
    -7,    // ..b...
    -14,   // b.b...
    14,    // w.b...
    -16,   // .bb...
    34,    // bbb...
    -24,   // wbb...
    -22,   // .wb...
    -25,   // bwb...
    -10,   // wwb...
    7,     // ..w...
    -14,   // b.w...
    14,    // w.w...
    22,    // .bw...
    10,    // bbw...
    25,    // wbw...
    16,    // .ww...
    24,    // bww...
    -34,   // www...
    -7,    // ...b..
    3,     // b..b..
    2,     // w..b..
    -12,   // .b.b..
    4,     // bb.b..
    3,     // wb.b..
    -31,   // .w.b..
    -31,   // bw.b..
    -3,    // ww.b..
    -8,    // ..bb..
    21,    // b.bb..
    6,     // w.bb..
    29,    // .bbb..
    24,    // bbbb..
    -26,   // wbbb..
    9,     // .wbb..
    -9,    // bwbb..
    6,     // wwbb..
    0,     // ..wb..
    -7,    // b.wb..
    -18,   // w.wb..
    -7,    // .bwb..
    -6,    // bbwb..
    37,    // wbwb..
    -22,   // .wwb..
    11,    // bwwb..
    33,    // wwwb..
    7,     // ...w..
    -2,    // b..w..
    -3,    // w..w..
    31,    // .b.w..
    3,     // bb.w..
    31,    // wb.w..
    12,    // .w.w..
    -3,    // bw.w..
    -4,    // ww.w..
    0,     // ..bw..
    18,    // b.bw..
    7,     // w.bw..
    22,    // .bbw..
    -33,   // bbbw..
    -11,   // wbbw..
    7,     // .wbw..
    -37,   // bwbw..
    6,     // wwbw..
    8,     // ..ww..
    -6,    // b.ww..
    -21,   // w.ww..
    -9,    // .bww..
    -6,    // bbww..
    9,     // wbww..
    -29,   // .www..
    26,    // bwww..
    -24,   // wwww..
    -4,    // ....b.
    -4,    // b...b.
    27,    // w...b.
    -24,   // .b..b.
    -11,   // bb..b.
    12,    // wb..b.
    0,     // .w..b.
    -5,    // bw..b.
    27,    // ww..b.
    -12,   // ..b.b.
    -29,   // b.b.b.
    29,    // w.b.b.
    19,    // .bb.b.
    38,    // bbb.b.
    14,    // wbb.b.
    -22,   // .wb.b.
    7,     // bwb.b.
    10,    // wwb.b.
    31,    // ..w.b.
    -17,   // b.w.b.
    -18,   // w.w.b.
    11,    // .bw.b.
    -6,    // bbw.b.
    14,    // wbw.b.
    29,    // .ww.b.
    18,    // bww.b.
    -10,   // www.b.
    -16,   // ...bb.
    -1,    // b..bb.
    0,     // w..bb.
    19,    // .b.bb.
    30,    // bb.bb.
    7,     // wb.bb.
    -29,   // .w.bb.
    0,     // bw.bb.
    2,     // ww.bb.
    29,    // ..bbb.
    28,    // b.bbb.
    -10,   // w.bbb.
    70,    // .bbbb.
    7,     // bbbbb.
    -9,    // wbbbb.
    16,    // .wbbb.
    -4,    // bwbbb.
    15,    // wwbbb.
    22,    // ..wbb.
    -7,    // b.wbb.
    -2,    // w.wbb.
    0,     // .bwbb.
    13,    // bbwbb.
    0,     // wbwbb.
    0,     // .wwbb.
    -21,   // bwwbb.
    -22,   // wwwbb.
    22,    // ...wb.
    4,     // b..wb.
    9,     // w..wb.
    11,    // .b.wb.
    -27,   // bb.wb.
    14,    // wb.wb.
    22,    // .w.wb.
    -7,    // bw.wb.
    4,     // ww.wb.
    -7,    // ..bwb.
    13,    // b.bwb.
    0,     // w.bwb.
    0,     // .bbwb.
    -26,   // bbbwb.
    -26,   // wbbwb.
    0,     // .wbwb.
    14,    // bwbwb.
    -13,   // wwbwb.
    -9,    // ..wwb.
    15,    // b.wwb.
    20,    // w.wwb.
    -22,   // .bwwb.
    20,    // bbwwb.
    22,    // wbwwb.
    -16,   // .wwwb.
    -7,    // bwwwb.
    -5,    // wwwwb.
    4,     // ....w.
    -27,   // b...w.
    4,     // w...w.
    0,     // .b..w.
    -27,   // bb..w.
    5,     // wb..w.
    24,    // .w..w.
    -12,   // bw..w.
    11,    // ww..w.
    -31,   // ..b.w.
    18,    // b.b.w.
    17,    // w.b.w.
    -29,   // .bb.w.
    10,    // bbb.w.
    -18,   // wbb.w.
    -11,   // .wb.w.
    -14,   // bwb.w.
    6,     // wwb.w.
    12,    // ..w.w.
    -29,   // b.w.w.
    29,    // w.w.w.
    22,    // .bw.w.
    -10,   // bbw.w.
    -7,    // wbw.w.
    -19,   // .ww.w.
    -14,   // bww.w.
    -38,   // www.w.
    -22,   // ...bw.
    -9,    // b..bw.
    -4,    // w..bw.
    -22,   // .b.bw.
    -4,    // bb.bw.
    7,     // wb.bw.
    -11,   // .w.bw.
    -14,   // bw.bw.
    27,    // ww.bw.
    9,     // ..bbw.
    -20,   // b.bbw.
    -15,   // w.bbw.
    16,    // .bbbw.
    5,     // bbbbw.
    7,     // wbbbw.
    22,    // .wbbw.
    -22,   // bwbbw.
    -20,   // wwbbw.
    7,     // ..wbw.
    0,     // b.wbw.
    -13,   // w.wbw.
    0,     // .bwbw.
    13,    // bbwbw.
    -14,   // wbwbw.
    0,     // .wwbw.
    26,    // bwwbw.
    26,    // wwwbw.
    16,    // ...ww.
    0,     // b..ww.
    1,     // w..ww.
    29,    // .b.ww.
    -2,    // bb.ww.
    0,     // wb.ww.
    -19,   // .w.ww.
    -7,    // bw.ww.
    -30,   // ww.ww.
    -22,   // ..bww.
    2,     // b.bww.
    7,     // w.bww.
    0,     // .bbww.
    22,    // bbbww.
    21,    // wbbww.
    0,     // .wbww.
    0,     // bwbww.
    -13,   // wwbww.
    -29,   // ..www.
    10,    // b.www.
    -28,   // w.www.
    -16,   // .bwww.
    -15,   // bbwww.
    4,     // wbwww.
    -70,   // .wwww.
    9,     // bwwww.
    -7,    // wwwww.
    -2,    // .....b
    -29,   // b....b
    0,     // w....b
    -4,    // .b...b
    -38,   // bb...b
    -8,    // wb...b
    -27,   // .w...b
    -14,   // bw...b
    44,    // ww...b
    3,     // ..b..b
    -30,   // b.b..b
    10,    // w.b..b
    -1,    // .bb..b
    15,    // bbb..b
    -31,   // wbb..b
    -9,    // .wb..b
    2,     // bwb..b
    26,    // wwb..b
    -2,    // ..w..b
    -4,    // b.w..b
    -19,   // w.w..b
    4,     // .bw..b
    2,     // bbw..b
    -11,   // wbw..b
    0,     // .ww..b
    19,    // bww..b
    -19,   // www..b
    -14,   // ...b.b
    -30,   // b..b.b
    19,    // w..b.b
    -29,   // .b.b.b
    6,     // bb.b.b
    31,    // wb.b.b
    18,    // .w.b.b
    -11,   // bw.b.b
    -3,    // ww.b.b
    21,    // ..bb.b
    -14,   // b.bb.b
    21,    // w.bb.b
    28,    // .bbb.b
    35,    // bbbb.b
    2,     // wbbb.b
    -20,   // .wbb.b
    1,     // bwbb.b
    16,    // wwbb.b
    18,    // ..wb.b
    -15,   // b.wb.b
    0,     // w.wb.b
    13,    // .bwb.b
    -13,   // bbwb.b
    8,     // wbwb.b
    2,     // .wwb.b
    15,    // bwwb.b
    -39,   // wwwb.b
    -14,   // ...w.b
    -4,    // b..w.b
    -10,   // w..w.b
    -17,   // .b.w.b
    -11,   // bb.w.b
    7,     // wb.w.b
    -29,   // .w.w.b
    -27,   // bw.w.b
    -15,   // ww.w.b
    -7,    // ..bw.b
    -15,   // b.bw.b
    0,     // w.bw.b
    -7,    // .bbw.b
    -10,   // bbbw.b
    -12,   // wbbw.b
    0,     // .wbw.b
    4,     // bwbw.b
    -3,    // wwbw.b
    -6,    // ..ww.b
    -2,    // b.ww.b
    -21,   // w.ww.b
    15,    // .bww.b
    -15,   // bbww.b
    18,    // wbww.b
    10,    // .www.b
    10,    // bwww.b
    -10,   // wwww.b
    -10,   // ....bb
    -38,   // b...bb
    -44,   // w...bb
    -11,   // .b..bb
    23,    // bb..bb
    41,    // wb..bb
    -27,   // .w..bb
    -35,   // bw..bb
    0,     // ww..bb
    4,     // ..b.bb
    6,     // b.b.bb
    15,    // w.b.bb
    30,    // .bb.bb
    8,     // bbb.bb
    -9,    // wbb.bb
    -4,    // .wb.bb
    -8,    // bwb.bb
    7,     // wwb.bb
    3,     // ..w.bb
    -11,   // b.w.bb
    3,     // w.w.bb
    -27,   // .bw.bb
    -6,    // bbw.bb
    -20,   // wbw.bb
    -2,    // .ww.bb
    -5,    // bww.bb
    -17,   // www.bb
    34,    // ...bbb
    15,    // b..bbb
    19,    // w..bbb
    38,    // .b.bbb
    8,     // bb.bbb
    -51,   // wb.bbb
    10,    // .w.bbb
    -28,   // bw.bbb
    17,    // ww.bbb
    24,    // ..bbbb
    35,    // b.bbbb
    10,    // w.bbbb
    7,     // .bbbbb
    7,     // bbbbbb
    2,     // wbbbbb
    5,     // .wbbbb
    4,     // bwbbbb
    3,     // wwbbbb
    -33,   // ..wbbb
    -10,   // b.wbbb
    39,    // w.wbbb
    -26,   // .bwbbb
    16,    // bbwbbb
    14,    // wbwbbb
    22,    // .wwbbb
    1,     // bwwbbb
    0,     // wwwbbb
    10,    // ...wbb
    2,     // b..wbb
    -26,   // w..wbb
    -6,    // .b.wbb
    -6,    // bb.wbb
    13,    // wb.wbb
    -10,   // .w.wbb
    19,    // bw.wbb
    -7,    // ww.wbb
    -6,    // ..bwbb
    -13,   // b.bwbb
    3,     // w.bwbb
    13,    // .bbwbb
    16,    // bbbwbb
    -19,   // wbbwbb
    13,    // .wbwbb
    2,     // bwbwbb
    0,     // wwbwbb
    -6,    // ..wwbb
    -15,   // b.wwbb
    -16,   // w.wwbb
    20,    // .bwwbb
    -18,   // bbwwbb
    20,    // wbwwbb
    -15,   // .wwwbb
    12,    // bwwwbb
    -3,    // wwwwbb
    -18,   // ....wb
    -14,   // b...wb
    8,     // w...wb
    -5,    // .b..wb
    -35,   // bb..wb
    0,     // wb..wb
    -12,   // .w..wb
    -14,   // bw..wb
    -41,   // ww..wb
    -31,   // ..b.wb
    -11,   // b.b.wb
    -7,    // w.b.wb
    0,     // .bb.wb
    -28,   // bbb.wb
    6,     // wbb.wb
    -14,   // .wb.wb
    4,     // bwb.wb
    -13,   // wwb.wb
    -3,    // ..w.wb
    -27,   // b.w.wb
    -31,   // w.w.wb
    -7,    // .bw.wb
    19,    // bbw.wb
    1,     // wbw.wb
    -7,    // .ww.wb
    -18,   // bww.wb
    51,    // www.wb
    -25,   // ...bwb
    2,     // b..bwb
    11,    // w..bwb
    7,     // .b.bwb
    -8,    // bb.bwb
    -1,    // wb.bwb
    -14,   // .w.bwb
    4,     // bw.bwb
    20,    // ww.bwb
    -9,    // ..bbwb
    1,     // b.bbwb
    -18,   // w.bbwb
    -4,    // .bbbwb
    4,     // bbbbwb
    2,     // wbbbwb
    -22,   // .wbbwb
    -69,   // bwbbwb
    -20,   // wwbbwb
    -37,   // ..wbwb
    4,     // b.wbwb
    -8,    // w.wbwb
    14,    // .bwbwb
    2,     // bbwbwb
    0,     // wbwbwb
    0,     // .wwbwb
    24,    // bwwbwb
    -14,   // wwwbwb
    24,    // ...wwb
    19,    // b..wwb
    31,    // w..wwb
    18,    // .b.wwb
    -5,    // bb.wwb
    -6,    // wb.wwb
    -14,   // .w.wwb
    -18,   // bw.wwb
    9,     // ww.wwb
    11,    // ..bwwb
    15,    // b.bwwb
    12,    // w.bwwb
    -21,   // .bbwwb
    1,     // bbbwwb
    0,     // wbbwwb
    26,    // .wbwwb
    24,    // bwbwwb
    19,    // wwbwwb
    26,    // ..wwwb
    10,    // b.wwwb
    -2,    // w.wwwb
    -7,    // .bwwwb
    12,    // bbwwwb
    -2,    // wbwwwb
    9,     // .wwwwb
    -3,    // bwwwwb
    -2,    // wwwwwb
    2,     // .....w
    0,     // b....w
    29,    // w....w
    27,    // .b...w
    -44,   // bb...w
    14,    // wb...w
    4,     // .w...w
    8,     // bw...w
    38,    // ww...w
    2,     // ..b..w
    19,    // b.b..w
    4,     // w.b..w
    0,     // .bb..w
    19,    // bbb..w
    -19,   // wbb..w
    -4,    // .wb..w
    11,    // bwb..w
    -2,    // wwb..w
    -3,    // ..w..w
    -10,   // b.w..w
    30,    // w.w..w
    9,     // .bw..w
    -26,   // bbw..w
    -2,    // wbw..w
    1,     // .ww..w
    31,    // bww..w
    -15,   // www..w
    14,    // ...b.w
    10,    // b..b.w
    4,     // w..b.w
    29,    // .b.b.w
    15,    // bb.b.w
    27,    // wb.b.w
    17,    // .w.b.w
    -7,    // bw.b.w
    11,    // ww.b.w
    6,     // ..bb.w
    21,    // b.bb.w
    2,     // w.bb.w
    -10,   // .bbb.w
    10,    // bbbb.w
    -10,   // wbbb.w
    -15,   // .wbb.w
    -18,   // bwbb.w
    15,    // wwbb.w
    7,     // ..wb.w
    0,     // b.wb.w
    15,    // w.wb.w
    0,     // .bwb.w
    3,     // bbwb.w
    -4,    // wbwb.w
    7,     // .wwb.w
    12,    // bwwb.w
    10,    // wwwb.w
    14,    // ...w.w
    -19,   // b..w.w
    30,    // w..w.w
    -18,   // .b.w.w
    3,     // bb.w.w
    11,    // wb.w.w
    29,    // .w.w.w
    -31,   // bw.w.w
    -6,    // ww.w.w
    -18,   // ..bw.w
    0,     // b.bw.w
    15,    // w.bw.w
    -2,    // .bbw.w
    39,    // bbbw.w
    -15,   // wbbw.w
    -13,   // .wbw.w
    -8,    // bwbw.w
    13,    // wwbw.w
    -21,   // ..ww.w
    -21,   // b.ww.w
    14,    // w.ww.w
    20,    // .bww.w
    -16,   // bbww.w
    -1,    // wbww.w
    -28,   // .www.w
    -2,    // bwww.w
    -35,   // wwww.w
    18,    // ....bw
    -8,    // b...bw
    14,    // w...bw
    12,    // .b..bw
    41,    // bb..bw
    14,    // wb..bw
    5,     // .w..bw
    0,     // bw..bw
    35,    // ww..bw
    3,     // ..b.bw
    31,    // b.b.bw
    27,    // w.b.bw
    7,     // .bb.bw
    -51,   // bbb.bw
    18,    // wbb.bw
    7,     // .wb.bw
    -1,    // bwb.bw
    -19,   // wwb.bw
    31,    // ..w.bw
    7,     // b.w.bw
    11,    // w.w.bw
    14,    // .bw.bw
    13,    // bbw.bw
    -4,    // wbw.bw
    0,     // .ww.bw
    -6,    // bww.bw
    28,    // www.bw
    -24,   // ...bbw
    -31,   // b..bbw
    -19,   // w..bbw
    14,    // .b.bbw
    -9,    // bb.bbw
    18,    // wb.bbw
    -18,   // .w.bbw
    6,     // bw.bbw
    5,     // ww.bbw
    -26,   // ..bbbw
    2,     // b.bbbw
    -10,   // w.bbbw
    -9,    // .bbbbw
    2,     // bbbbbw
    3,     // wbbbbw
    7,     // .wbbbw
    2,     // bwbbbw
    -12,   // wwbbbw
    -11,   // ..wbbw
    -12,   // b.wbbw
    -15,   // w.wbbw
    -26,   // .bwbbw
    -19,   // bbwbbw
    -24,   // wbwbbw
    21,    // .wwbbw
    0,     // bwwbbw
    -1,    // wwwbbw
    25,    // ...wbw
    -11,   // b..wbw
    -2,    // w..wbw
    14,    // .b.wbw
    -20,   // bb.wbw
    -4,    // wb.wbw
    -7,    // .w.wbw
    1,     // bw.wbw
    8,     // ww.wbw
    37,    // ..bwbw
    8,     // b.bwbw
    -4,    // w.bwbw
    0,     // .bbwbw
    14,    // bbbwbw
    -24,   // wbbwbw
    -14,   // .wbwbw
    0,     // bwbwbw
    -2,    // wwbwbw
    9,     // ..wwbw
    18,    // b.wwbw
    -1,    // w.wwbw
    22,    // .bwwbw
    20,    // bbwwbw
    69,    // wbwwbw
    4,     // .wwwbw
    -2,    // bwwwbw
    -4,    // wwwwbw
    10,    // ....ww
    44,    // b...ww
    38,    // w...ww
    27,    // .b..ww
    0,     // bb..ww
    35,    // wb..ww
    11,    // .w..ww
    -41,   // bw..ww
    -23,   // ww..ww
    -3,    // ..b.ww
    -3,    // b.b.ww
    11,    // w.b.ww
    2,     // .bb.ww
    17,    // bbb.ww
    5,     // wbb.ww
    27,    // .wb.ww
    20,    // bwb.ww
    6,     // wwb.ww
    -4,    // ..w.ww
    -15,   // b.w.ww
    -6,    // w.w.ww
    4,     // .bw.ww
    -7,    // bbw.ww
    8,     // wbw.ww
    -30,   // .ww.ww
    9,     // bww.ww
    -8,    // www.ww
    -10,   // ...bww
    26,    // b..bww
    -2,    // w..bww
    10,    // .b.bww
    7,     // bb.bww
    -19,   // wb.bww
    6,     // .w.bww
    -13,   // bw.bww
    6,     // ww.bww
    6,     // ..bbww
    16,    // b.bbww
    15,    // w.bbww
    15,    // .bbbww
    3,     // bbbbww
    -12,   // wbbbww
    -20,   // .wbbww
    -20,   // bwbbww
    18,    // wwbbww
    6,     // ..wbww
    -3,    // b.wbww
    13,    // w.wbww
    -13,   // .bwbww
    0,     // bbwbww
    -2,    // wbwbww
    -13,   // .wwbww
    19,    // bwwbww
    -16,   // wwwbww
    -34,   // ...www
    -19,   // b..www
    -15,   // w..www
    -10,   // .b.www
    -17,   // bb.www
    28,    // wb.www
    -38,   // .w.www
    51,    // bw.www
    -8,    // ww.www
    33,    // ..bwww
    -39,   // b.bwww
    10,    // w.bwww
    -22,   // .bbwww
    0,     // bbbwww
    -1,    // wbbwww
    26,    // .wbwww
    -14,   // bwbwww
    -16,   // wwbwww
    -24,   // ..wwww
    -10,   // b.wwww
    -35,   // w.wwww
    -5,    // .bwwww
    -3,    // bbwwww
    -4,    // wbwwww
    -7,    // .wwwww
    -2,    // bwwwww
    -7,    // wwwwww
    -8,    // ccc
    -13,   // cc
    0,     // c
    16,    // ttt
    -6,    // tt
    34,    // t
    -5,    // ct
    -32,   // cct
    -36,   // ctt
].into_boxed_slice()
