vec![
    0,     // .......
    5,     // b......
    -5,    // w......
    -1,    // .b.....
    21,    // bb.....
    3,     // wb.....
    1,     // .w.....
    -3,    // bw.....
    -21,   // ww.....
    11,    // ..b....
    27,    // b.b....
    -15,   // w.b....
    17,    // .bb....
    105,   // bbb....
    2,     // wbb....
    -32,   // .wb....
    -13,   // bwb....
    -8,    // wwb....
    -11,   // ..w....
    15,    // b.w....
    -27,   // w.w....
    32,    // .bw....
    8,     // bbw....
    13,    // wbw....
    -17,   // .ww....
    -2,    // bww....
    -105,  // www....
    -15,   // ...b...
    6,     // b..b...
    10,    // w..b...
    3,     // .b.b...
    18,    // bb.b...
    -29,   // wb.b...
    -3,    // .w.b...
    10,    // bw.b...
    -40,   // ww.b...
    -21,   // ..bb...
    -6,    // b.bb...
    -36,   // w.bb...
    45,    // .bbb...
    188,   // bbbb...
    -66,   // wbbb...
    -19,   // .wbb...
    -16,   // bwbb...
    38,    // wwbb...
    18,    // ..wb...
    44,    // b.wb...
    13,    // w.wb...
    9,     // .bwb...
    -55,   // bbwb...
    17,    // wbwb...
    38,    // .wwb...
    -33,   // bwwb...
    -5,    // wwwb...
    15,    // ...w...
    -10,   // b..w...
    -6,    // w..w...
    3,     // .b.w...
    40,    // bb.w...
    -10,   // wb.w...
    -3,    // .w.w...
    29,    // bw.w...
    -18,   // ww.w...
    -18,   // ..bw...
    -13,   // b.bw...
    -44,   // w.bw...
    -38,   // .bbw...
    5,     // bbbw...
    33,    // wbbw...
    -9,    // .wbw...
    -17,   // bwbw...
    55,    // wwbw...
    21,    // ..ww...
    36,    // b.ww...
    6,     // w.ww...
    19,    // .bww...
    -38,   // bbww...
    16,    // wbww...
    -45,   // .www...
    66,    // bwww...
    -188,  // wwww...
    11,    // ....b..
    9,     // b...b..
    18,    // w...b..
    -7,    // .b..b..
    2,     // bb..b..
    -20,   // wb..b..
    3,     // .w..b..
    -26,   // bw..b..
    -40,   // ww..b..
    9,     // ..b.b..
    -12,   // b.b.b..
    -11,   // w.b.b..
    9,     // .bb.b..
    45,    // bbb.b..
    42,    // wbb.b..
    -4,    // .wb.b..
    -8,    // bwb.b..
    1,     // wwb.b..
    0,     // ..w.b..
    42,    // b.w.b..
    -17,   // w.w.b..
    -5,    // .bw.b..
    -8,    // bbw.b..
    -8,    // wbw.b..
    20,    // .ww.b..
    11,    // bww.b..
    -56,   // www.b..
    -21,   // ...bb..
    0,     // b..bb..
    -10,   // w..bb..
    92,    // .b.bb..
    39,    // bb.bb..
    -40,   // wb.bb..
    5,     // .w.bb..
    9,     // bw.bb..
    -1,    // ww.bb..
    -2,    // ..bbb..
    53,    // b.bbb..
    -48,   // w.bbb..
    147,   // .bbbb..
    42,    // bbbbb..
    51,    // wbbbb..
    -51,   // .wbbb..
    1,     // bwbbb..
    -4,    // wwbbb..
    -7,    // ..wbb..
    -14,   // b.wbb..
    1,     // w.wbb..
    1,     // .bwbb..
    -12,   // bbwbb..
    -27,   // wbwbb..
    -13,   // .wwbb..
    -28,   // bwwbb..
    -21,   // wwwbb..
    -18,   // ...wb..
    -22,   // b..wb..
    -19,   // w..wb..
    -11,   // .b.wb..
    -8,    // bb.wb..
    -2,    // wb.wb..
    -9,    // .w.wb..
    -2,    // bw.wb..
    -7,    // ww.wb..
    19,    // ..bwb..
    -19,   // b.bwb..
    -6,    // w.bwb..
    -28,   // .bbwb..
    -27,   // bbbwb..
    65,    // wbbwb..
    -16,   // .wbwb..
    9,     // bwbwb..
    -9,    // wwbwb..
    7,     // ..wwb..
    -25,   // b.wwb..
    7,     // w.wwb..
    9,     // .bwwb..
    22,    // bbwwb..
    60,    // wbwwb..
    0,     // .wwwb..
    29,    // bwwwb..
    -36,   // wwwwb..
    -11,   // ....w..
    -18,   // b...w..
    -9,    // w...w..
    -3,    // .b..w..
    40,    // bb..w..
    26,    // wb..w..
    7,     // .w..w..
    20,    // bw..w..
    -2,    // ww..w..
    0,     // ..b.w..
    17,    // b.b.w..
    -42,   // w.b.w..
    -20,   // .bb.w..
    56,    // bbb.w..
    -11,   // wbb.w..
    5,     // .wb.w..
    8,     // bwb.w..
    8,     // wwb.w..
    -9,    // ..w.w..
    11,    // b.w.w..
    12,    // w.w.w..
    4,     // .bw.w..
    -1,    // bbw.w..
    8,     // wbw.w..
    -9,    // .ww.w..
    -42,   // bww.w..
    -45,   // www.w..
    18,    // ...bw..
    19,    // b..bw..
    22,    // w..bw..
    9,     // .b.bw..
    7,     // bb.bw..
    2,     // wb.bw..
    11,    // .w.bw..
    2,     // bw.bw..
    8,     // ww.bw..
    -7,    // ..bbw..
    -7,    // b.bbw..
    25,    // w.bbw..
    0,     // .bbbw..
    36,    // bbbbw..
    -29,   // wbbbw..
    -9,    // .wbbw..
    -60,   // bwbbw..
    -22,   // wwbbw..
    -19,   // ..wbw..
    6,     // b.wbw..
    19,    // w.wbw..
    16,    // .bwbw..
    9,     // bbwbw..
    -9,    // wbwbw..
    28,    // .wwbw..
    -65,   // bwwbw..
    27,    // wwwbw..
    21,    // ...ww..
    10,    // b..ww..
    0,     // w..ww..
    -5,    // .b.ww..
    1,     // bb.ww..
    -9,    // wb.ww..
    -92,   // .w.ww..
    40,    // bw.ww..
    -39,   // ww.ww..
    7,     // ..bww..
    -1,    // b.bww..
    14,    // w.bww..
    13,    // .bbww..
    21,    // bbbww..
    28,    // wbbww..
    -1,    // .wbww..
    27,    // bwbww..
    12,    // wwbww..
    2,     // ..www..
    48,    // b.www..
    -53,   // w.www..
    51,    // .bwww..
    4,     // bbwww..
    -1,    // wbwww..
    -147,  // .wwww..
    -51,   // bwwww..
    -42,   // wwwww..
    -1,    // .....b.
    -12,   // b....b.
    -55,   // w....b.
    17,    // .b...b.
    47,    // bb...b.
    6,     // wb...b.
    0,     // .w...b.
    1,     // bw...b.
    6,     // ww...b.
    -7,    // ..b..b.
    12,    // b.b..b.
    7,     // w.b..b.
    28,    // .bb..b.
    6,     // bbb..b.
    49,    // wbb..b.
    -9,    // .wb..b.
    -14,   // bwb..b.
    51,    // wwb..b.
    -3,    // ..w..b.
    -24,   // b.w..b.
    18,    // w.w..b.
    -13,   // .bw..b.
    -18,   // bbw..b.
    -46,   // wbw..b.
    33,    // .ww..b.
    -40,   // bww..b.
    -65,   // www..b.
    3,     // ...b.b.
    -10,   // b..b.b.
    50,    // w..b.b.
    17,    // .b.b.b.
    7,     // bb.b.b.
    -6,    // wb.b.b.
    -13,   // .w.b.b.
    -59,   // bw.b.b.
    -32,   // ww.b.b.
    92,    // ..bb.b.
    -24,   // b.bb.b.
    29,    // w.bb.b.
    18,    // .bbb.b.
    10,    // bbbb.b.
    57,    // wbbb.b.
    9,     // .wbb.b.
    22,    // bwbb.b.
    -45,   // wwbb.b.
    9,     // ..wb.b.
    -3,    // b.wb.b.
    -12,   // w.wb.b.
    10,    // .bwb.b.
    12,    // bbwb.b.
    -3,    // wbwb.b.
    34,    // .wwb.b.
    4,     // bwwb.b.
    -19,   // wwwb.b.
    3,     // ...w.b.
    14,    // b..w.b.
    -9,    // w..w.b.
    -50,   // .b.w.b.
    27,    // bb.w.b.
    0,     // wb.w.b.
    13,    // .w.w.b.
    -1,    // bw.w.b.
    -18,   // ww.w.b.
    -11,   // ..bw.b.
    1,     // b.bw.b.
    -7,    // w.bw.b.
    -27,   // .bbw.b.
    13,    // bbbw.b.
    -1,    // wbbw.b.
    -13,   // .wbw.b.
    1,     // bwbw.b.
    7,     // wwbw.b.
    -5,    // ..ww.b.
    -12,   // b.ww.b.
    -19,   // w.ww.b.
    -26,   // .bww.b.
    -44,   // bbww.b.
    29,    // wbww.b.
    -29,   // .www.b.
    37,    // bwww.b.
    -31,   // wwww.b.
    17,    // ....bb.
    -8,    // b...bb.
    -11,   // w...bb.
    28,    // .b..bb.
    13,    // bb..bb.
    36,    // wb..bb.
    -33,   // .w..bb.
    13,    // bw..bb.
    -25,   // ww..bb.
    9,     // ..b.bb.
    1,     // b.b.bb.
    22,    // w.b.bb.
    4,     // .bb.bb.
    17,    // bbb.bb.
    47,    // wbb.bb.
    -5,    // .wb.bb.
    9,     // bwb.bb.
    7,     // wwb.bb.
    -20,   // ..w.bb.
    -7,    // b.w.bb.
    -55,   // w.w.bb.
    -15,   // .bw.bb.
    14,    // bbw.bb.
    1,     // wbw.bb.
    0,     // .ww.bb.
    -8,    // bww.bb.
    -42,   // www.bb.
    45,    // ...bbb.
    -15,   // b..bbb.
    14,    // w..bbb.
    18,    // .b.bbb.
    -3,    // bb.bbb.
    38,    // wb.bbb.
    29,    // .w.bbb.
    25,    // bw.bbb.
    -6,    // ww.bbb.
    147,   // ..bbbb.
    30,    // b.bbbb.
    17,    // w.bbbb.
    13,    // .bbbbb.
    -4,    // bbbbbb.
    35,    // wbbbbb.
    54,    // .wbbbb.
    22,    // bwbbbb.
    11,    // wwbbbb.
    0,     // ..wbbb.
    -1,    // b.wbbb.
    -22,   // w.wbbb.
    3,     // .bwbbb.
    -35,   // bbwbbb.
    -35,   // wbwbbb.
    -16,   // .wwbbb.
    -14,   // bwwbbb.
    -8,    // wwwbbb.
    -38,   // ...wbb.
    6,     // b..wbb.
    10,    // w..wbb.
    -27,   // .b.wbb.
    27,    // bb.wbb.
    -17,   // wb.wbb.
    -34,   // .w.wbb.
    -32,   // bw.wbb.
    -18,   // ww.wbb.
    -28,   // ..bwbb.
    5,     // b.bwbb.
    -44,   // w.bwbb.
    17,    // .bbwbb.
    -29,   // bbbwbb.
    -23,   // wbbwbb.
    3,     // .wbwbb.
    -2,    // bwbwbb.
    54,    // wwbwbb.
    13,    // ..wwbb.
    -34,   // b.wwbb.
    12,    // w.wwbb.
    -21,   // .bwwbb.
    -31,   // bbwwbb.
    12,    // wbwwbb.
    16,    // .wwwbb.
    -5,    // bwwwbb.
    15,    // wwwwbb.
    32,    // ....wb.
    22,    // b...wb.
    -10,   // w...wb.
    -13,   // .b..wb.
    -12,   // bb..wb.
    -26,   // wb..wb.
    9,     // .w..wb.
    -17,   // bw..wb.
    12,    // ww..wb.
    -5,    // ..b.wb.
    -13,   // b.b.wb.
    -30,   // w.b.wb.
    -15,   // .bb.wb.
    24,    // bbb.wb.
    -36,   // wbb.wb.
    0,     // .wb.wb.
    -35,   // bwb.wb.
    6,     // wwb.wb.
    4,     // ..w.wb.
    43,    // b.w.wb.
    33,    // w.w.wb.
    3,     // .bw.wb.
    14,    // bbw.wb.
    -15,   // wbw.wb.
    5,     // .ww.wb.
    7,     // bww.wb.
    -49,   // www.wb.
    9,     // ...bwb.
    -7,    // b..bwb.
    1,     // w..bwb.
    10,    // .b.bwb.
    8,     // bb.bwb.
    14,    // wb.bwb.
    13,    // .w.bwb.
    19,    // bw.bwb.
    -23,   // ww.bwb.
    1,     // ..bbwb.
    -29,   // b.bbwb.
    16,    // w.bbwb.
    3,     // .bbbwb.
    -10,   // bbbbwb.
    7,     // wbbbwb.
    -5,    // .wbbwb.
    -8,    // bwbbwb.
    33,    // wwbbwb.
    16,    // ..wbwb.
    20,    // b.wbwb.
    -2,    // w.wbwb.
    -24,   // .bwbwb.
    42,    // bbwbwb.
    24,    // wbwbwb.
    -3,    // .wwbwb.
    25,    // bwwbwb.
    -37,   // wwwbwb.
    19,    // ...wwb.
    -39,   // b..wwb.
    25,    // w..wwb.
    -26,   // .b.wwb.
    -6,    // bb.wwb.
    -3,    // wb.wwb.
    -9,    // .w.wwb.
    -13,   // bw.wwb.
    -7,    // ww.wwb.
    9,     // ..bwwb.
    9,     // b.bwwb.
    -8,    // w.bwwb.
    -21,   // .bbwwb.
    -25,   // bbbwwb.
    -23,   // wbbwwb.
    5,     // .wbwwb.
    -12,   // bwbwwb.
    1,     // wwbwwb.
    51,    // ..wwwb.
    46,    // b.wwwb.
    -39,   // w.wwwb.
    -39,   // .bwwwb.
    -3,    // bbwwwb.
    20,    // wbwwwb.
    -54,   // .wwwwb.
    104,   // bwwwwb.
    -2,    // wwwwwb.
    1,     // .....w.
    55,    // b....w.
    12,    // w....w.
    0,     // .b...w.
    -6,    // bb...w.
    -1,    // wb...w.
    -17,   // .w...w.
    -6,    // bw...w.
    -47,   // ww...w.
    3,     // ..b..w.
    -18,   // b.b..w.
    24,    // w.b..w.
    -33,   // .bb..w.
    65,    // bbb..w.
    40,    // wbb..w.
    13,    // .wb..w.
    46,    // bwb..w.
    18,    // wwb..w.
    7,     // ..w..w.
    -7,    // b.w..w.
    -12,   // w.w..w.
    9,     // .bw..w.
    -51,   // bbw..w.
    14,    // wbw..w.
    -28,   // .ww..w.
    -49,   // bww..w.
    -6,    // www..w.
    -3,    // ...b.w.
    9,     // b..b.w.
    -14,   // w..b.w.
    -13,   // .b.b.w.
    18,    // bb.b.w.
    1,     // wb.b.w.
    50,    // .w.b.w.
    0,     // bw.b.w.
    -27,   // ww.b.w.
    5,     // ..bb.w.
    19,    // b.bb.w.
    12,    // w.bb.w.
    29,    // .bbb.w.
    31,    // bbbb.w.
    -37,   // wbbb.w.
    26,    // .wbb.w.
    -29,   // bwbb.w.
    44,    // wwbb.w.
    11,    // ..wb.w.
    7,     // b.wb.w.
    -1,    // w.wb.w.
    13,    // .bwb.w.
    -7,    // bbwb.w.
    -1,    // wbwb.w.
    27,    // .wwb.w.
    1,     // bwwb.w.
    -13,   // wwwb.w.
    -3,    // ...w.w.
    -50,   // b..w.w.
    10,    // w..w.w.
    13,    // .b.w.w.
    32,    // bb.w.w.
    59,    // wb.w.w.
    -17,   // .w.w.w.
    6,     // bw.w.w.
    -7,    // ww.w.w.
    -9,    // ..bw.w.
    12,    // b.bw.w.
    3,     // w.bw.w.
    -34,   // .bbw.w.
    19,    // bbbw.w.
    -4,    // wbbw.w.
    -10,   // .wbw.w.
    3,     // bwbw.w.
    -12,   // wwbw.w.
    -92,   // ..ww.w.
    -29,   // b.ww.w.
    24,    // w.ww.w.
    -9,    // .bww.w.
    45,    // bbww.w.
    -22,   // wbww.w.
    -18,   // .www.w.
    -57,   // bwww.w.
    -10,   // wwww.w.
    -32,   // ....bw.
    10,    // b...bw.
    -22,   // w...bw.
    -9,    // .b..bw.
    -12,   // bb..bw.
    17,    // wb..bw.
    13,    // .w..bw.
    26,    // bw..bw.
    12,    // ww..bw.
    -4,    // ..b.bw.
    -33,   // b.b.bw.
    -43,   // w.b.bw.
    -5,    // .bb.bw.
    49,    // bbb.bw.
    -7,    // wbb.bw.
    -3,    // .wb.bw.
    15,    // bwb.bw.
    -14,   // wwb.bw.
    5,     // ..w.bw.
    30,    // b.w.bw.
    13,    // w.w.bw.
    0,     // .bw.bw.
    -6,    // bbw.bw.
    35,    // wbw.bw.
    15,    // .ww.bw.
    36,    // bww.bw.
    -24,   // www.bw.
    -19,   // ...bbw.
    -25,   // b..bbw.
    39,    // w..bbw.
    9,     // .b.bbw.
    7,     // bb.bbw.
    13,    // wb.bbw.
    26,    // .w.bbw.
    3,     // bw.bbw.
    6,     // ww.bbw.
    -51,   // ..bbbw.
    39,    // b.bbbw.
    -46,   // w.bbbw.
    54,    // .bbbbw.
    2,     // bbbbbw.
    -104,  // wbbbbw.
    39,    // .wbbbw.
    -20,   // bwbbbw.
    3,     // wwbbbw.
    -9,    // ..wbbw.
    8,     // b.wbbw.
    -9,    // w.wbbw.
    -5,    // .bwbbw.
    -1,    // bbwbbw.
    12,    // wbwbbw.
    21,    // .wwbbw.
    23,    // bwwbbw.
    25,    // wwwbbw.
    -9,    // ...wbw.
    -1,    // b..wbw.
    7,     // w..wbw.
    -13,   // .b.wbw.
    23,    // bb.wbw.
    -19,   // wb.wbw.
    -10,   // .w.wbw.
    -14,   // bw.wbw.
    -8,    // ww.wbw.
    -16,   // ..bwbw.
    2,     // b.bwbw.
    -20,   // w.bwbw.
    3,     // .bbwbw.
    37,    // bbbwbw.
    -25,   // wbbwbw.
    24,    // .wbwbw.
    -24,   // bwbwbw.
    -42,   // wwbwbw.
    -1,    // ..wwbw.
    -16,   // b.wwbw.
    29,    // w.wwbw.
    5,     // .bwwbw.
    -33,   // bbwwbw.
    8,     // wbwwbw.
    -3,    // .wwwbw.
    -7,    // bwwwbw.
    10,    // wwwwbw.
    -17,   // ....ww.
    11,    // b...ww.
    8,     // w...ww.
    33,    // .b..ww.
    25,    // bb..ww.
    -13,   // wb..ww.
    -28,   // .w..ww.
    -36,   // bw..ww.
    -13,   // ww..ww.
    20,    // ..b.ww.
    55,    // b.b.ww.
    7,     // w.b.ww.
    0,     // .bb.ww.
    42,    // bbb.ww.
    8,     // wbb.ww.
    15,    // .wb.ww.
    -1,    // bwb.ww.
    -14,   // wwb.ww.
    -9,    // ..w.ww.
    -22,   // b.w.ww.
    -1,    // w.w.ww.
    5,     // .bw.ww.
    -7,    // bbw.ww.
    -9,    // wbw.ww.
    -4,    // .ww.ww.
    -47,   // bww.ww.
    -17,   // www.ww.
    38,    // ...bww.
    -10,   // b..bww.
    -6,    // w..bww.
    34,    // .b.bww.
    18,    // bb.bww.
    32,    // wb.bww.
    27,    // .w.bww.
    17,    // bw.bww.
    -27,   // ww.bww.
    -13,   // ..bbww.
    -12,   // b.bbww.
    34,    // w.bbww.
    -16,   // .bbbww.
    -15,   // bbbbww.
    5,     // wbbbww.
    21,    // .wbbww.
    -12,   // bwbbww.
    31,    // wwbbww.
    28,    // ..wbww.
    44,    // b.wbww.
    -5,    // w.wbww.
    -3,    // .bwbww.
    -54,   // bbwbww.
    2,     // wbwbww.
    -17,   // .wwbww.
    23,    // bwwbww.
    29,    // wwwbww.
    -45,   // ...www.
    -14,   // b..www.
    15,    // w..www.
    -29,   // .b.www.
    6,     // bb.www.
    -25,   // wb.www.
    -18,   // .w.www.
    -38,   // bw.www.
    3,     // ww.www.
    0,     // ..bwww.
    22,    // b.bwww.
    1,     // w.bwww.
    16,    // .bbwww.
    8,     // bbbwww.
    14,    // wbbwww.
    -3,    // .wbwww.
    35,    // bwbwww.
    35,    // wwbwww.
    -147,  // ..wwww.
    -17,   // b.wwww.
    -30,   // w.wwww.
    -54,   // .bwwww.
    -11,   // bbwwww.
    -22,   // wbwwww.
    -13,   // .wwwww.
    -35,   // bwwwww.
    4,     // wwwwww.
    5,     // ......b
    17,    // b.....b
    0,     // w.....b
    -12,   // .b....b
    40,    // bb....b
    9,     // wb....b
    55,    // .w....b
    7,     // bw....b
    -7,    // ww....b
    9,     // ..b...b
    7,     // b.b...b
    -23,   // w.b...b
    -8,    // .bb...b
    -49,   // bbb...b
    -32,   // wbb...b
    10,    // .wb...b
    -47,   // bwb...b
    -35,   // wwb...b
    -18,   // ..w...b
    -25,   // b.w...b
    -14,   // w.w...b
    22,    // .bw...b
    -12,   // bbw...b
    -13,   // wbw...b
    11,    // .ww...b
    0,     // bww...b
    34,    // www...b
    6,     // ...b..b
    18,    // b..b..b
    11,    // w..b..b
    -10,   // .b.b..b
    18,    // bb.b..b
    21,    // wb.b..b
    9,     // .w.b..b
    -45,   // bw.b..b
    -5,    // ww.b..b
    0,     // ..bb..b
    17,    // b.bb..b
    -32,   // w.bb..b
    -15,   // .bbb..b
    27,    // bbbb..b
    -4,    // wbbb..b
    -25,   // .wbb..b
    -29,   // bwbb..b
    -6,    // wwbb..b
    19,    // ..wb..b
    38,    // b.wb..b
    -15,   // w.wb..b
    -7,    // .bwb..b
    3,     // bbwb..b
    -33,   // wbwb..b
    -10,   // .wwb..b
    -9,    // bwwb..b
    5,     // wwwb..b
    -10,   // ...w..b
    -39,   // b..w..b
    -11,   // w..w..b
    14,    // .b.w..b
    37,    // bb.w..b
    4,     // wb.w..b
    -50,   // .w.w..b
    -12,   // bw.w..b
    -33,   // ww.w..b
    -22,   // ..bw..b
    -1,    // b.bw..b
    -32,   // w.bw..b
    6,     // .bbw..b
    -3,    // bbbw..b
    -41,   // wbbw..b
    -1,    // .wbw..b
    -45,   // bwbw..b
    1,     // wwbw..b
    10,    // ..ww..b
    7,     // b.ww..b
    -4,    // w.ww..b
    -39,   // .bww..b
    36,    // bbww..b
    19,    // wbww..b
    -14,   // .www..b
    -2,    // bwww..b
    -38,   // wwww..b
    27,    // ....b.b
    7,     // b...b.b
    14,    // w...b.b
    12,    // .b..b.b
    -37,   // bb..b.b
    -8,    // wb..b.b
    -18,   // .w..b.b
    44,    // bw..b.b
    -37,   // ww..b.b
    -12,   // ..b.b.b
    -12,   // b.b.b.b
    13,    // w.b.b.b
    1,     // .bb.b.b
    -6,    // bbb.b.b
    -1,    // wbb.b.b
    -33,   // .wb.b.b
    17,    // bwb.b.b
    44,    // wwb.b.b
    17,    // ..w.b.b
    -24,   // b.w.b.b
    0,     // w.w.b.b
    -13,   // .bw.b.b
    15,    // bbw.b.b
    -10,   // wbw.b.b
    55,    // .ww.b.b
    1,     // bww.b.b
    -22,   // www.b.b
    -6,    // ...bb.b
    17,    // b..bb.b
    4,     // w..bb.b
    -24,   // .b.bb.b
    -6,    // bb.bb.b
    -9,    // wb.bb.b
    19,    // .w.bb.b
    15,    // bw.bb.b
    -31,   // ww.bb.b
    53,    // ..bbb.b
    31,    // b.bbb.b
    34,    // w.bbb.b
    30,    // .bbbb.b
    1,     // bbbbb.b
    -27,   // wbbbb.b
    39,    // .wbbb.b
    21,    // bwbbb.b
    -19,   // wwbbb.b
    -7,    // ..wbb.b
    25,    // b.wbb.b
    11,    // w.wbb.b
    -29,   // .bwbb.b
    32,    // bbwbb.b
    -4,    // wbwbb.b
    -12,   // .wwbb.b
    -1,    // bwwbb.b
    -26,   // wwwbb.b
    -13,   // ...wb.b
    -1,    // b..wb.b
    15,    // w..wb.b
    1,     // .b.wb.b
    1,     // bb.wb.b
    -10,   // wb.wb.b
    12,    // .w.wb.b
    28,    // bw.wb.b
    48,    // ww.wb.b
    -19,   // ..bwb.b
    11,    // b.bwb.b
    -46,   // w.bwb.b
    5,     // .bbwb.b
    -15,   // bbbwb.b
    19,    // wbbwb.b
    2,     // .wbwb.b
    -22,   // bwbwb.b
    19,    // wwbwb.b
    -1,    // ..wwb.b
    5,     // b.wwb.b
    -11,   // w.wwb.b
    9,     // .bwwb.b
    -17,   // bbwwb.b
    -26,   // wbwwb.b
    22,    // .wwwb.b
    -16,   // bwwwb.b
    -11,   // wwwwb.b
    15,    // ....w.b
    -25,   // b...w.b
    23,    // w...w.b
    -24,   // .b..w.b
    47,    // bb..w.b
    11,    // wb..w.b
    -7,    // .w..w.b
    0,     // bw..w.b
    -7,    // ww..w.b
    42,    // ..b.w.b
    -24,   // b.b.w.b
    0,     // w.b.w.b
    -7,    // .bb.w.b
    29,    // bbb.w.b
    20,    // wbb.w.b
    30,    // .wb.w.b
    41,    // bwb.w.b
    -49,   // wwb.w.b
    11,    // ..w.w.b
    -42,   // b.w.w.b
    -13,   // w.w.w.b
    43,    // .bw.w.b
    18,    // bbw.w.b
    -17,   // wbw.w.b
    -22,   // .ww.w.b
    6,     // bww.w.b
    0,     // www.w.b
    44,    // ...bw.b
    38,    // b..bw.b
    32,    // w..bw.b
    -3,    // .b.bw.b
    -5,    // bb.bw.b
    25,    // wb.bw.b
    7,     // .w.bw.b
    35,    // bw.bw.b
    28,    // ww.bw.b
    -14,   // ..bbw.b
    25,    // b.bbw.b
    -40,   // w.bbw.b
    -1,    // .bbbw.b
    -49,   // bbbbw.b
    -9,    // wbbbw.b
    8,     // .wbbw.b
    -9,    // bwbbw.b
    -4,    // wwbbw.b
    6,     // ..wbw.b
    -24,   // b.wbw.b
    46,    // w.wbw.b
    20,    // .bwbw.b
    39,    // bbwbw.b
    -16,   // wbwbw.b
    44,    // .wwbw.b
    -8,    // bwwbw.b
    27,    // wwwbw.b
    36,    // ...ww.b
    7,     // b..ww.b
    32,    // w..ww.b
    -12,   // .b.ww.b
    -1,    // bb.ww.b
    -7,    // wb.ww.b
    -29,   // .w.ww.b
    -18,   // bw.ww.b
    -6,    // ww.ww.b
    -25,   // ..bww.b
    5,     // b.bww.b
    40,    // w.bww.b
    -34,   // .bbww.b
    -2,    // bbbww.b
    8,     // wbbww.b
    -16,   // .wbww.b
    18,    // bwbww.b
    -16,   // wwbww.b
    48,    // ..www.b
    23,    // b.www.b
    -34,   // w.www.b
    46,    // .bwww.b
    23,    // bbwww.b
    -12,   // wbwww.b
    -17,   // .wwww.b
    8,     // bwwww.b
    -13,   // wwwww.b
    21,    // .....bb
    40,    // b....bb
    7,     // w....bb
    47,    // .b...bb
    -26,   // bb...bb
    23,    // wb...bb
    -6,    // .w...bb
    -9,    // bw...bb
    0,     // ww...bb
    2,     // ..b..bb
    -37,   // b.b..bb
    7,     // w.b..bb
    13,    // .bb..bb
    65,    // bbb..bb
    -38,   // wbb..bb
    -12,   // .wb..bb
    -23,   // bwb..bb
    -5,    // wwb..bb
    40,    // ..w..bb
    47,    // b.w..bb
    37,    // w.w..bb
    -12,   // .bw..bb
    32,    // bbw..bb
    3,     // wbw..bb
    25,    // .ww..bb
    10,    // bww..bb
    0,     // www..bb
    18,    // ...b.bb
    18,    // b..b.bb
    33,    // w..b.bb
    7,     // .b.b.bb
    -15,   // bb.b.bb
    -19,   // wb.b.bb
    18,    // .w.b.bb
    -7,    // bw.b.bb
    1,     // ww.b.bb
    39,    // ..bb.bb
    -6,    // b.bb.bb
    6,     // w.bb.bb
    -3,    // .bbb.bb
    2,     // bbbb.bb
    8,     // wbbb.bb
    7,     // .wbb.bb
    33,    // bwbb.bb
    36,    // wwbb.bb
    7,     // ..wb.bb
    -5,    // b.wb.bb
    -48,   // w.wb.bb
    8,     // .bwb.bb
    66,    // bbwb.bb
    -25,   // wbwb.bb
    18,    // .wwb.bb
    -14,   // bwwb.bb
    37,    // wwwb.bb
    40,    // ...w.bb
    37,    // b..w.bb
    5,     // w..w.bb
    27,    // .b.w.bb
    46,    // bb.w.bb
    -19,   // wb.w.bb
    32,    // .w.w.bb
    -36,   // bw.w.bb
    -1,    // ww.w.bb
    -8,    // ..bw.bb
    1,     // b.bw.bb
    -28,   // w.bw.bb
    27,    // .bbw.bb
    -40,   // bbbw.bb
    10,    // wbbw.bb
    23,    // .wbw.bb
    25,    // bwbw.bb
    16,    // wwbw.bb
    1,     // ..ww.bb
    -1,    // b.ww.bb
    31,    // w.ww.bb
    -6,    // .bww.bb
    6,     // bbww.bb
    43,    // wbww.bb
    6,     // .www.bb
    -6,    // bwww.bb
    5,     // wwww.bb
    105,   // ....bbb
    -49,   // b...bbb
    -34,   // w...bbb
    6,     // .b..bbb
    65,    // bb..bbb
    25,    // wb..bbb
    65,    // .w..bbb
    18,    // bw..bbb
    0,     // ww..bbb
    45,    // ..b.bbb
    -6,    // b.b.bbb
    0,     // w.b.bbb
    17,    // .bb.bbb
    21,    // bbb.bbb
    14,    // wbb.bbb
    49,    // .wb.bbb
    -35,   // bwb.bbb
    -1,    // wwb.bbb
    56,    // ..w.bbb
    29,    // b.w.bbb
    22,    // w.w.bbb
    24,    // .bw.bbb
    -13,   // bbw.bbb
    -21,   // wbw.bbb
    42,    // .ww.bbb
    -4,    // bww.bbb
    0,     // www.bbb
    188,   // ...bbbb
    27,    // b..bbbb
    38,    // w..bbbb
    10,    // .b.bbbb
    2,     // bb.bbbb
    -34,   // wb.bbbb
    31,    // .w.bbbb
    -17,   // bw.bbbb
    -5,    // ww.bbbb
    42,    // ..bbbbb
    1,     // b.bbbbb
    13,    // w.bbbbb
    -4,    // .bbbbbb
    20,    // bbbbbbb
    -16,   // wbbbbbb
    2,     // .wbbbbb
    -16,   // bwbbbbb
    -15,   // wwbbbbb
    36,    // ..wbbbb
    -49,   // b.wbbbb
    11,    // w.wbbbb
    -10,   // .bwbbbb
    5,     // bbwbbbb
    -18,   // wbwbbbb
    -15,   // .wwbbbb
    -12,   // bwwbbbb
    1,     // wwwbbbb
    5,     // ...wbbb
    -3,    // b..wbbb
    -5,    // w..wbbb
    13,    // .b.wbbb
    -40,   // bb.wbbb
    2,     // wb.wbbb
    19,    // .w.wbbb
    -49,   // bw.wbbb
    -37,   // ww.wbbb
    -27,   // ..bwbbb
    -15,   // b.bwbbb
    -27,   // w.bwbbb
    -29,   // .bbwbbb
    -8,    // bbbwbbb
    -23,   // wbbwbbb
    37,    // .wbwbbb
    -21,   // bwbwbbb
    11,    // wwbwbbb
    21,    // ..wwbbb
    -2,    // b.wwbbb
    26,    // w.wwbbb
    -25,   // .bwwbbb
    -10,   // bbwwbbb
    2,     // wbwwbbb
    8,     // .wwwbbb
    -26,   // bwwwbbb
    -1,    // wwwwbbb
    8,     // ....wbb
    -12,   // b...wbb
    35,    // w...wbb
    -18,   // .b..wbb
    32,    // bb..wbb
    -33,   // wb..wbb
    -51,   // .w..wbb
    15,    // bw..wbb
    5,     // ww..wbb
    -8,    // ..b.wbb
    15,    // b.b.wbb
    49,    // w.b.wbb
    14,    // .bb.wbb
    -13,   // bbb.wbb
    17,    // wbb.wbb
    -6,    // .wb.wbb
    -21,   // bwb.wbb
    0,     // wwb.wbb
    -1,    // ..w.wbb
    18,    // b.w.wbb
    -44,   // w.w.wbb
    14,    // .bw.wbb
    37,    // bbw.wbb
    -1,    // wbw.wbb
    -7,    // .ww.wbb
    -3,    // bww.wbb
    1,     // www.wbb
    -55,   // ...bwbb
    3,     // b..bwbb
    -1,    // w..bwbb
    12,    // .b.bwbb
    66,    // bb.bwbb
    17,    // wb.bwbb
    -7,    // .w.bwbb
    -50,   // bw.bwbb
    -16,   // ww.bwbb
    -12,   // ..bbwbb
    32,    // b.bbwbb
    16,    // w.bbwbb
    -35,   // .bbbwbb
    5,     // bbbbwbb
    -16,   // wbbbwbb
    -1,    // .wbbwbb
    -25,   // bwbbwbb
    55,    // wwbbwbb
    9,     // ..wbwbb
    39,    // b.wbwbb
    -19,   // w.wbwbb
    42,    // .bwbwbb
    6,     // bbwbwbb
    18,    // wbwbwbb
    -54,   // .wwbwbb
    -19,   // bwwbwbb
    -11,   // wwwbwbb
    -38,   // ...wwbb
    36,    // b..wwbb
    6,     // w..wwbb
    -44,   // .b.wwbb
    6,     // bb.wwbb
    2,     // wb.wwbb
    45,    // .w.wwbb
    59,    // bw.wwbb
    -36,   // ww.wwbb
    22,    // ..bwwbb
    -17,   // b.bwwbb
    4,     // w.bwwbb
    -31,   // .bbwwbb
    -10,   // bbbwwbb
    -45,   // wbbwwbb
    -33,   // .wbwwbb
    -27,   // bwbwwbb
    -55,   // wwbwwbb
    4,     // ..wwwbb
    23,    // b.wwwbb
    19,    // w.wwwbb
    -3,    // .bwwwbb
    -14,   // bbwwwbb
    11,    // wbwwwbb
    -11,   // .wwwwbb
    1,     // bwwwwbb
    15,    // wwwwwbb
    -3,    // .....wb
    7,     // b....wb
    -9,    // w....wb
    1,     // .b...wb
    -9,    // bb...wb
    0,     // wb...wb
    -6,    // .w...wb
    52,    // bw...wb
    -23,   // ww...wb
    -26,   // ..b..wb
    44,    // b.b..wb
    -11,   // w.b..wb
    13,    // .bb..wb
    18,    // bbb..wb
    -3,    // wbb..wb
    26,    // .wb..wb
    -14,   // bwb..wb
    33,    // wwb..wb
    20,    // ..w..wb
    0,     // b.w..wb
    8,     // w.w..wb
    -17,   // .bw..wb
    15,    // bbw..wb
    -26,   // wbw..wb
    -36,   // .ww..wb
    41,    // bww..wb
    -25,   // www..wb
    10,    // ...b.wb
    -45,   // b..b.wb
    -4,    // w..b.wb
    -59,   // .b.b.wb
    -7,    // bb.b.wb
    20,    // wb.b.wb
    0,     // .w.b.wb
    -12,   // bw.b.wb
    19,    // ww.b.wb
    9,     // ..bb.wb
    15,    // b.bb.wb
    7,     // w.bb.wb
    25,    // .bbb.wb
    -17,   // bbbb.wb
    11,    // wbbb.wb
    3,     // .wbb.wb
    -10,   // bwbb.wb
    -2,    // wwbb.wb
    2,     // ..wb.wb
    35,    // b.wb.wb
    10,    // w.wb.wb
    19,    // .bwb.wb
    -50,   // bbwb.wb
    -13,   // wbwb.wb
    17,    // .wwb.wb
    -50,   // bwwb.wb
    -2,    // wwwb.wb
    29,    // ...w.wb
    -12,   // b..w.wb
    -21,   // w..w.wb
    -1,    // .b.w.wb
    -36,   // bb.w.wb
    -20,   // wb.w.wb
    6,     // .w.w.wb
    9,     // bw.w.wb
    19,    // ww.w.wb
    -2,    // ..bw.wb
    28,    // b.bw.wb
    -25,   // w.bw.wb
    -32,   // .bbw.wb
    -49,   // bbbw.wb
    -21,   // wbbw.wb
    -14,   // .wbw.wb
    -39,   // bwbw.wb
    -17,   // wwbw.wb
    40,    // ..ww.wb
    -18,   // b.ww.wb
    9,     // w.ww.wb
    -13,   // .bww.wb
    59,    // bbww.wb
    19,    // wbww.wb
    -38,   // .www.wb
    12,    // bwww.wb
    34,    // wwww.wb
    -13,   // ....bwb
    -47,   // b...bwb
    13,    // w...bwb
    -14,   // .b..bwb
    -23,   // bb..bwb
    26,    // wb..bwb
    46,    // .w..bwb
    -14,   // bw..bwb
    -3,    // ww..bwb
    -8,    // ..b.bwb
    17,    // b.b.bwb
    17,    // w.b.bwb
    9,     // .bb.bwb
    -35,   // bbb.bwb
    13,    // wbb.bwb
    15,    // .wb.bwb
    -21,   // bwb.bwb
    1,     // wwb.bwb
    8,     // ..w.bwb
    41,    // b.w.bwb
    10,    // w.w.bwb
    -35,   // .bw.bwb
    -21,   // bbw.bwb
    0,     // wbw.bwb
    -1,    // .ww.bwb
    -18,   // bww.bwb
    21,    // www.bwb
    -16,   // ...bbwb
    -29,   // b..bbwb
    -19,   // w..bbwb
    22,    // .b.bbwb
    33,    // bb.bbwb
    -19,   // wb.bbwb
    -29,   // .w.bbwb
    -10,   // bw.bbwb
    -43,   // ww.bbwb
    1,     // ..bbbwb
    21,    // b.bbbwb
    12,    // w.bbbwb
    22,    // .bbbbwb
    -16,   // bbbbbwb
    34,    // wbbbbwb
    -20,   // .wbbbwb
    -34,   // bwbbbwb
    -11,   // wwbbbwb
    -60,   // ..wbbwb
    -9,    // b.wbbwb
    26,    // w.wbbwb
    -8,    // .bwbbwb
    -25,   // bbwbbwb
    -17,   // wbwbbwb
    -12,   // .wwbbwb
    38,    // bwwbbwb
    -2,    // wwwbbwb
    -17,   // ...wbwb
    -45,   // b..wbwb
    33,    // w..wbwb
    1,     // .b.wbwb
    25,    // bb.wbwb
    13,    // wb.wbwb
    3,     // .w.wbwb
    -39,   // bw.wbwb
    25,    // ww.wbwb
    9,     // ..bwbwb
    -22,   // b.bwbwb
    16,    // w.bwbwb
    -2,    // .bbwbwb
    -21,   // bbbwbwb
    -26,   // wbbwbwb
    -24,   // .wbwbwb
    2,     // bwbwbwb
    -18,   // wwbwbwb
    27,    // ..wwbwb
    18,    // b.wwbwb
    4,     // w.wwbwb
    -12,   // .bwwbwb
    -27,   // bbwwbwb
    17,    // wbwwbwb
    35,    // .wwwbwb
    29,    // bwwwbwb
    18,    // wwwwbwb
    -2,    // ....wwb
    0,     // b...wwb
    32,    // w...wwb
    -40,   // .b..wwb
    10,    // bb..wwb
    3,     // wb..wwb
    -49,   // .w..wwb
    41,    // bw..wwb
    38,    // ww..wwb
    11,    // ..b.wwb
    1,     // b.b.wwb
    -20,   // w.b.wwb
    -8,    // .bb.wwb
    -4,    // bbb.wwb
    0,     // wbb.wwb
    36,    // .wb.wwb
    -18,   // bwb.wwb
    -17,   // wwb.wwb
    -42,   // ..w.wwb
    6,     // b.w.wwb
    1,     // w.w.wwb
    7,     // .bw.wwb
    -3,    // bbw.wwb
    -13,   // wbw.wwb
    -47,   // .ww.wwb
    -37,   // bww.wwb
    -14,   // www.wwb
    -33,   // ...bwwb
    -9,    // b..bwwb
    41,    // w..bwwb
    4,     // .b.bwwb
    -14,   // bb.bwwb
    21,    // wb.bwwb
    1,     // .w.bwwb
    -50,   // bw.bwwb
    -10,   // ww.bwwb
    -28,   // ..bbwwb
    -1,    // b.bbwwb
    -8,    // w.bbwwb
    -14,   // .bbbwwb
    -12,   // bbbbwwb
    -11,   // wbbbwwb
    23,    // .wbbwwb
    38,    // bwbbwwb
    45,    // wwbbwwb
    -65,   // ..wbwwb
    -8,    // b.wbwwb
    -19,   // w.wbwwb
    25,    // .bwbwwb
    -19,   // bbwbwwb
    26,    // wbwbwwb
    23,    // .wwbwwb
    39,    // bwwbwwb
    23,    // wwwbwwb
    66,    // ...wwwb
    -2,    // b..wwwb
    4,     // w..wwwb
    37,    // .b.wwwb
    -6,    // bb.wwwb
    -11,   // wb.wwwb
    -57,   // .w.wwwb
    12,    // bw.wwwb
    -8,    // ww.wwwb
    29,    // ..bwwwb
    -16,   // b.bwwwb
    9,     // w.bwwwb
    -5,    // .bbwwwb
    -26,   // bbbwwwb
    11,    // wbbwwwb
    -7,    // .wbwwwb
    29,    // bwbwwwb
    16,    // wwbwwwb
    -51,   // ..wwwwb
    8,     // b.wwwwb
    27,    // w.wwwwb
    104,   // .bwwwwb
    1,     // bbwwwwb
    -34,   // wbwwwwb
    -35,   // .wwwwwb
    25,    // bwwwwwb
    16,    // wwwwwwb
    -5,    // ......w
    0,     // b.....w
    -17,   // w.....w
    -55,   // .b....w
    7,     // bb....w
    -7,    // wb....w
    12,    // .w....w
    -9,    // bw....w
    -40,   // ww....w
    18,    // ..b...w
    14,    // b.b...w
    25,    // w.b...w
    -11,   // .bb...w
    -34,   // bbb...w
    0,     // wbb...w
    -22,   // .wb...w
    13,    // bwb...w
    12,    // wwb...w
    -9,    // ..w...w
    23,    // b.w...w
    -7,    // w.w...w
    -10,   // .bw...w
    35,    // bbw...w
    47,    // wbw...w
    8,     // .ww...w
    32,    // bww...w
    49,    // www...w
    10,    // ...b..w
    11,    // b..b..w
    39,    // w..b..w
    50,    // .b.b..w
    33,    // bb.b..w
    12,    // wb.b..w
    -14,   // .w.b..w
    -4,    // bw.b..w
    -37,   // ww.b..w
    -10,   // ..bb..w
    4,     // b.bb..w
    -7,    // w.bb..w
    14,    // .bbb..w
    38,    // bbbb..w
    2,     // wbbb..w
    39,    // .wbb..w
    -19,   // bwbb..w
    -36,   // wwbb..w
    22,    // ..wb..w
    32,    // b.wb..w
    1,     // w.wb..w
    1,     // .bwb..w
    -1,    // bbwb..w
    45,    // wbwb..w
    -6,    // .wwb..w
    41,    // bwwb..w
    3,     // wwwb..w
    -6,    // ...w..w
    -11,   // b..w..w
    -18,   // w..w..w
    -9,    // .b.w..w
    5,     // bb.w..w
    45,    // wb.w..w
    10,    // .w.w..w
    -21,   // bw.w..w
    -18,   // ww.w..w
    -19,   // ..bw..w
    15,    // b.bw..w
    -38,   // w.bw..w
    10,    // .bbw..w
    -5,    // bbbw..w
    9,     // wbbw..w
    7,     // .wbw..w
    33,    // bwbw..w
    -3,    // wwbw..w
    0,     // ..ww..w
    32,    // b.ww..w
    -17,   // w.ww..w
    25,    // .bww..w
    6,     // bbww..w
    29,    // wbww..w
    15,    // .www..w
    4,     // bwww..w
    -27,   // wwww..w
    -15,   // ....b.w
    -23,   // b...b.w
    25,    // w...b.w
    7,     // .b..b.w
    7,     // bb..b.w
    0,     // wb..b.w
    24,    // .w..b.w
    -11,   // bw..b.w
    -47,   // ww..b.w
    -11,   // ..b.b.w
    13,    // b.b.b.w
    42,    // w.b.b.w
    22,    // .bb.b.w
    0,     // bbb.b.w
    -6,    // wbb.b.w
    -43,   // .wb.b.w
    17,    // bwb.b.w
    -18,   // wwb.b.w
    -42,   // ..w.b.w
    0,     // b.w.b.w
    24,    // w.w.b.w
    -30,   // .bw.b.w
    49,    // bbw.b.w
    -41,   // wbw.b.w
    7,     // .ww.b.w
    -20,   // bww.b.w
    -29,   // www.b.w
    -36,   // ...bb.w
    -32,   // b..bb.w
    -7,    // w..bb.w
    29,    // .b.bb.w
    6,     // bb.bb.w
    18,    // wb.bb.w
    12,    // .w.bb.w
    7,     // bw.bb.w
    1,     // ww.bb.w
    -48,   // ..bbb.w
    34,    // b.bbb.w
    -23,   // w.bbb.w
    17,    // .bbbb.w
    13,    // bbbbb.w
    -8,    // wbbbb.w
    -46,   // .wbbb.w
    12,    // bwbbb.w
    -23,   // wwbbb.w
    25,    // ..wbb.w
    -40,   // b.wbb.w
    -5,    // w.wbb.w
    16,    // .bwbb.w
    16,    // bbwbb.w
    -18,   // wbwbb.w
    34,    // .wwbb.w
    -8,    // bwwbb.w
    2,     // wwwbb.w
    -44,   // ...wb.w
    -32,   // b..wb.w
    -38,   // w..wb.w
    -7,    // .b.wb.w
    -28,   // bb.wb.w
    -35,   // wb.wb.w
    3,     // .w.wb.w
    -25,   // bw.wb.w
    5,     // ww.wb.w
    -6,    // ..bwb.w
    -46,   // b.bwb.w
    24,    // w.bwb.w
    -44,   // .bbwb.w
    -27,   // bbbwb.w
    8,     // wbbwb.w
    -20,   // .wbwb.w
    16,    // bwbwb.w
    -39,   // wwbwb.w
    14,    // ..wwb.w
    40,    // b.wwb.w
    -25,   // w.wwb.w
    -8,    // .bwwb.w
    4,     // bbwwb.w
    9,     // wbwwb.w
    1,     // .wwwb.w
    9,     // bwwwb.w
    49,    // wwwwb.w
    -27,   // ....w.w
    -14,   // b...w.w
    -7,    // w...w.w
    18,    // .b..w.w
    37,    // bb..w.w
    -44,   // wb..w.w
    -12,   // .w..w.w
    8,     // bw..w.w
    37,    // ww..w.w
    -17,   // ..b.w.w
    0,     // b.b.w.w
    24,    // w.b.w.w
    -55,   // .bb.w.w
    22,    // bbb.w.w
    -1,    // wbb.w.w
    13,    // .wb.w.w
    10,    // bwb.w.w
    -15,   // wwb.w.w
    12,    // ..w.w.w
    -13,   // b.w.w.w
    12,    // w.w.w.w
    33,    // .bw.w.w
    -44,   // bbw.w.w
    -17,   // wbw.w.w
    -1,    // .ww.w.w
    1,     // bww.w.w
    6,     // www.w.w
    13,    // ...bw.w
    -15,   // b..bw.w
    1,     // w..bw.w
    -12,   // .b.bw.w
    -48,   // bb.bw.w
    -28,   // wb.bw.w
    -1,    // .w.bw.w
    10,    // bw.bw.w
    -1,    // ww.bw.w
    1,     // ..bbw.w
    11,    // b.bbw.w
    -5,    // w.bbw.w
    -22,   // .bbbw.w
    11,    // bbbbw.w
    16,    // wbbbw.w
    -9,    // .wbbw.w
    26,    // bwbbw.w
    17,    // wwbbw.w
    19,    // ..wbw.w
    46,    // b.wbw.w
    -11,   // w.wbw.w
    -2,    // .bwbw.w
    -19,   // bbwbw.w
    22,    // wbwbw.w
    -5,    // .wwbw.w
    -19,   // bwwbw.w
    15,    // wwwbw.w
    6,     // ...ww.w
    -4,    // b..ww.w
    -17,   // w..ww.w
    -19,   // .b.ww.w
    31,    // bb.ww.w
    -15,   // wb.ww.w
    24,    // .w.ww.w
    9,     // bw.ww.w
    6,     // ww.ww.w
    7,     // ..bww.w
    -11,   // b.bww.w
    -25,   // w.bww.w
    12,    // .bbww.w
    26,    // bbbww.w
    1,     // wbbww.w
    29,    // .wbww.w
    4,     // bwbww.w
    -32,   // wwbww.w
    -53,   // ..www.w
    -34,   // b.www.w
    -31,   // w.www.w
    -39,   // .bwww.w
    19,    // bbwww.w
    -21,   // wbwww.w
    -30,   // .wwww.w
    27,    // bwwww.w
    -1,    // wwwww.w
    3,     // .....bw
    9,     // b....bw
    -7,    // w....bw
    6,     // .b...bw
    23,    // bb...bw
    -52,   // wb...bw
    -1,    // .w...bw
    0,     // bw...bw
    9,     // ww...bw
    -20,   // ..b..bw
    -8,    // b.b..bw
    0,     // w.b..bw
    36,    // .bb..bw
    25,    // bbb..bw
    -41,   // wbb..bw
    17,    // .wb..bw
    26,    // bwb..bw
    -15,   // wwb..bw
    26,    // ..w..bw
    11,    // b.w..bw
    -44,   // w.w..bw
    -26,   // .bw..bw
    -33,   // bbw..bw
    14,    // wbw..bw
    -13,   // .ww..bw
    3,     // bww..bw
    -18,   // www..bw
    -29,   // ...b.bw
    21,    // b..b.bw
    12,    // w..b.bw
    -6,    // .b.b.bw
    -19,   // bb.b.bw
    -9,    // wb.b.bw
    1,     // .w.b.bw
    20,    // bw.b.bw
    36,    // ww.b.bw
    -40,   // ..bb.bw
    -9,    // b.bb.bw
    18,    // w.bb.bw
    38,    // .bbb.bw
    -34,   // bbbb.bw
    -12,   // wbbb.bw
    13,    // .wbb.bw
    -19,   // bwbb.bw
    -59,   // wwbb.bw
    2,     // ..wb.bw
    25,    // b.wb.bw
    -28,   // w.wb.bw
    14,    // .bwb.bw
    17,    // bbwb.bw
    39,    // wbwb.bw
    32,    // .wwb.bw
    21,    // bwwb.bw
    49,    // wwwb.bw
    -10,   // ...w.bw
    4,     // b..w.bw
    45,    // w..w.bw
    0,     // .b.w.bw
    -19,   // bb.w.bw
    12,    // wb.w.bw
    59,    // .w.w.bw
    -20,   // bw.w.bw
    7,     // ww.w.bw
    -2,    // ..bw.bw
    -10,   // b.bw.bw
    -35,   // w.bw.bw
    -17,   // .bbw.bw
    2,     // bbbw.bw
    50,    // wbbw.bw
    -19,   // .wbw.bw
    13,    // bwbw.bw
    50,    // wwbw.bw
    -9,    // ..ww.bw
    -7,    // b.ww.bw
    -15,   // w.ww.bw
    -3,    // .bww.bw
    2,     // bbww.bw
    10,    // wbww.bw
    -25,   // .www.bw
    -11,   // bwww.bw
    17,    // wwww.bw
    2,     // ....bbw
    -32,   // b...bbw
    0,     // w...bbw
    49,    // .b..bbw
    -38,   // bb..bbw
    -41,   // wb..bbw
    40,    // .w..bbw
    -3,    // bw..bbw
    -10,   // ww..bbw
    42,    // ..b.bbw
    -1,    // b.b.bbw
    -6,    // w.b.bbw
    47,    // .bb.bbw
    14,    // bbb.bbw
    37,    // wbb.bbw
    -7,    // .wb.bbw
    13,    // bwb.bbw
    3,     // wwb.bbw
    -11,   // ..w.bbw
    20,    // b.w.bbw
    -1,    // w.w.bbw
    -36,   // .bw.bbw
    17,    // bbw.bbw
    18,    // wbw.bbw
    8,     // .ww.bbw
    0,     // bww.bbw
    4,     // www.bbw
    -66,   // ...bbbw
    -4,    // b..bbbw
    2,     // w..bbbw
    57,    // .b.bbbw
    8,     // bb.bbbw
    -12,   // wb.bbbw
    -37,   // .w.bbbw
    11,    // bw.bbbw
    6,     // ww.bbbw
    51,    // ..bbbbw
    -27,   // b.bbbbw
    -8,    // w.bbbbw
    35,    // .bbbbbw
    -16,   // bbbbbbw
    -25,   // wbbbbbw
    -104,  // .wbbbbw
    34,    // bwbbbbw
    -1,    // wwbbbbw
    -29,   // ..wbbbw
    -9,    // b.wbbbw
    16,    // w.wbbbw
    7,     // .bwbbbw
    -16,   // bbwbbbw
    -29,   // wbwbbbw
    5,     // .wwbbbw
    -11,   // bwwbbbw
    26,    // wwwbbbw
    33,    // ...wbbw
    -41,   // b..wbbw
    9,     // w..wbbw
    -1,    // .b.wbbw
    10,    // bb.wbbw
    50,    // wb.wbbw
    -4,    // .w.wbbw
    -21,   // bw.wbbw
    14,    // ww.wbbw
    65,    // ..bwbbw
    19,    // b.bwbbw
    8,     // w.bwbbw
    -23,   // .bbwbbw
    -23,   // bbbwbbw
    -39,   // wbbwbbw
    -25,   // .wbwbbw
    -26,   // bwbwbbw
    19,    // wwbwbbw
    28,    // ..wwbbw
    8,     // b.wwbbw
    1,     // w.wwbbw
    -23,   // .bwwbbw
    -45,   // bbwwbbw
    -38,   // wbwwbbw
    14,    // .wwwbbw
    11,    // bwwwbbw
    12,    // wwwwbbw
    13,    // ....wbw
    -13,   // b...wbw
    47,    // w...wbw
    -46,   // .b..wbw
    3,     // bb..wbw
    14,    // wb..wbw
    14,    // .w..wbw
    -26,   // bw..wbw
    23,    // ww..wbw
    -8,    // ..b.wbw
    -10,   // b.b.wbw
    -41,   // w.b.wbw
    1,     // .bb.wbw
    -21,   // bbb.wbw
    18,    // wbb.wbw
    35,    // .wb.wbw
    0,     // bwb.wbw
    21,    // wwb.wbw
    8,     // ..w.wbw
    -17,   // b.w.wbw
    -17,   // w.w.wbw
    -15,   // .bw.wbw
    -1,    // bbw.wbw
    21,    // wbw.wbw
    -9,    // .ww.wbw
    -13,   // bww.wbw
    35,    // www.wbw
    17,    // ...bwbw
    -33,   // b..bwbw
    45,    // w..bwbw
    -3,    // .b.bwbw
    -25,   // bb.bwbw
    39,    // wb.bwbw
    -1,    // .w.bwbw
    -13,   // bw.bwbw
    -25,   // ww.bwbw
    -27,   // ..bbwbw
    -4,    // b.bbwbw
    -18,   // w.bbwbw
    -35,   // .bbbwbw
    -18,   // bbbbwbw
    -29,   // wbbbwbw
    12,    // .wbbwbw
    -17,   // bwbbwbw
    27,    // wwbbwbw
    -9,    // ..wbwbw
    -16,   // b.wbwbw
    22,    // w.wbwbw
    24,    // .bwbwbw
    18,    // bbwbwbw
    -2,    // wbwbwbw
    2,     // .wwbwbw
    26,    // bwwbwbw
    21,    // wwwbwbw
    16,    // ...wwbw
    19,    // b..wwbw
    29,    // w..wwbw
    29,    // .b.wwbw
    43,    // bb.wwbw
    10,    // wb.wwbw
    -22,   // .w.wwbw
    19,    // bw.wwbw
    -33,   // ww.wwbw
    60,    // ..bwwbw
    -26,   // b.bwwbw
    9,     // w.bwwbw
    12,    // .bbwwbw
    2,     // bbbwwbw
    -38,   // wbbwwbw
    8,     // .wbwwbw
    17,    // bwbwwbw
    25,    // wwbwwbw
    -1,    // ..wwwbw
    -12,   // b.wwwbw
    -21,   // w.wwwbw
    20,    // .bwwwbw
    11,    // bbwwwbw
    34,    // wbwwwbw
    -22,   // .wwwwbw
    -34,   // bwwwwbw
    16,    // wwwwwbw
    -21,   // .....ww
    -7,    // b....ww
    -40,   // w....ww
    6,     // .b...ww
    0,     // bb...ww
    9,     // wb...ww
    -47,   // .w...ww
    -23,   // bw...ww
    26,    // ww...ww
    -40,   // ..b..ww
    -37,   // b.b..ww
    -47,   // w.b..ww
    -25,   // .bb..ww
    0,     // bbb..ww
    -10,   // wbb..ww
    12,    // .wb..ww
    -3,    // bwb..ww
    -32,   // wwb..ww
    -2,    // ..w..ww
    -7,    // b.w..ww
    37,    // w.w..ww
    12,    // .bw..ww
    5,     // bbw..ww
    23,    // wbw..ww
    -13,   // .ww..ww
    38,    // bww..ww
    -65,   // www..ww
    -40,   // ...b.ww
    -5,    // b..b.ww
    -37,   // w..b.ww
    -32,   // .b.b.ww
    1,     // bb.b.ww
    36,    // wb.b.ww
    -27,   // .w.b.ww
    19,    // bw.b.ww
    -46,   // ww.b.ww
    -1,    // ..bb.ww
    -31,   // b.bb.ww
    1,     // w.bb.ww
    -6,    // .bbb.ww
    -5,    // bbbb.ww
    6,     // wbbb.ww
    6,     // .wbb.ww
    -43,   // bwbb.ww
    -6,    // wwbb.ww
    8,     // ..wb.ww
    28,    // b.wb.ww
    -1,    // w.wb.ww
    -23,   // .bwb.ww
    -16,   // bbwb.ww
    -25,   // wbwb.ww
    -27,   // .wwb.ww
    -10,   // bwwb.ww
    40,    // wwwb.ww
    -18,   // ...w.ww
    -33,   // b..w.ww
    -18,   // w..w.ww
    -18,   // .b.w.ww
    -1,    // bb.w.ww
    7,     // wb.w.ww
    -7,    // .w.w.ww
    19,    // bw.w.ww
    15,    // ww.w.ww
    -7,    // ..bw.ww
    48,    // b.bw.ww
    5,     // w.bw.ww
    -18,   // .bbw.ww
    -37,   // bbbw.ww
    14,    // wbbw.ww
    -8,    // .wbw.ww
    25,    // bwbw.ww
    -66,   // wwbw.ww
    -39,   // ..ww.ww
    -6,    // b.ww.ww
    6,     // w.ww.ww
    -7,    // .bww.ww
    -36,   // bbww.ww
    -33,   // wbww.ww
    3,     // .www.ww
    -8,    // bwww.ww
    -2,    // wwww.ww
    -8,    // ....bww
    -35,   // b...bww
    12,    // w...bww
    51,    // .b..bww
    -5,    // bb..bww
    -15,   // wb..bww
    18,    // .w..bww
    33,    // bw..bww
    -32,   // ww..bww
    1,     // ..b.bww
    44,    // b.b.bww
    -18,   // w.b.bww
    7,     // .bb.bww
    -1,    // bbb.bww
    3,     // wbb.bww
    -14,   // .wb.bww
    1,     // bwb.bww
    -37,   // wwb.bww
    8,     // ..w.bww
    -49,   // b.w.bww
    -15,   // w.w.bww
    6,     // .bw.bww
    0,     // bbw.bww
    21,    // wbw.bww
    -14,   // .ww.bww
    -17,   // bww.bww
    13,    // www.bww
    38,    // ...bbww
    -6,    // b..bbww
    -36,   // w..bbww
    -45,   // .b.bbww
    36,    // bb.bbww
    -59,   // wb.bbww
    44,    // .w.bbww
    -2,    // bw.bbww
    -6,    // ww.bbww
    -4,    // ..bbbww
    -19,   // b.bbbww
    -23,   // w.bbbww
    11,    // .bbbbww
    -15,   // bbbbbww
    -1,    // wbbbbww
    3,     // .wbbbww
    -11,   // bwbbbww
    14,    // wwbbbww
    -22,   // ..wbbww
    -4,    // b.wbbww
    17,    // w.wbbww
    33,    // .bwbbww
    55,    // bbwbbww
    27,    // wbwbbww
    31,    // .wwbbww
    45,    // bwwbbww
    10,    // wwwbbww
    55,    // ...wbww
    1,     // b..wbww
    -3,    // w..wbww
    7,     // .b.wbww
    16,    // bb.wbww
    50,    // wb.wbww
    -12,   // .w.wbww
    -17,   // bw.wbww
    -66,   // ww.wbww
    -9,    // ..bwbww
    19,    // b.bwbww
    -39,   // w.bwbww
    54,    // .bbwbww
    11,    // bbbwbww
    19,    // wbbwbww
    -42,   // .wbwbww
    -18,   // bwbwbww
    -6,    // wwbwbww
    12,    // ..wwbww
    -16,   // b.wwbww
    -32,   // w.wwbww
    1,     // .bwwbww
    -55,   // bbwwbww
    25,    // wbwwbww
    35,    // .wwwbww
    16,    // bwwwbww
    -5,    // wwwwbww
    -105,  // ....www
    34,    // b...www
    49,    // w...www
    -65,   // .b..www
    0,     // bb..www
    -18,   // wb..www
    -6,    // .w..www
    -25,   // bw..www
    -65,   // ww..www
    -56,   // ..b.www
    -22,   // b.b.www
    -29,   // w.b.www
    -42,   // .bb.www
    0,     // bbb.www
    4,     // wbb.www
    -24,   // .wb.www
    21,    // bwb.www
    13,    // wwb.www
    -45,   // ..w.www
    0,     // b.w.www
    6,     // w.w.www
    -49,   // .bw.www
    1,     // bbw.www
    35,    // wbw.www
    -17,   // .ww.www
    -14,   // bww.www
    -21,   // www.www
    -5,    // ...bwww
    5,     // b..bwww
    3,     // w..bwww
    -19,   // .b.bwww
    37,    // bb.bwww
    49,    // wb.bwww
    -13,   // .w.bwww
    -2,    // bw.bwww
    40,    // ww.bwww
    -21,   // ..bbwww
    -26,   // b.bbwww
    2,     // w.bbwww
    -8,    // .bbbwww
    1,     // bbbbwww
    26,    // wbbbwww
    25,    // .wbbwww
    -2,    // bwbbwww
    10,    // wwbbwww
    27,    // ..wbwww
    27,    // b.wbwww
    15,    // w.wbwww
    -37,   // .bwbwww
    -11,   // bbwbwww
    21,    // wbwbwww
    29,    // .wwbwww
    23,    // bwwbwww
    8,     // wwwbwww
    -188,  // ...wwww
    -38,   // b..wwww
    -27,   // w..wwww
    -31,   // .b.wwww
    5,     // bb.wwww
    17,    // wb.wwww
    -10,   // .w.wwww
    34,    // bw.wwww
    -2,    // ww.wwww
    -36,   // ..bwwww
    -11,   // b.bwwww
    49,    // w.bwwww
    15,    // .bbwwww
    -1,    // bbbwwww
    12,    // wbbwwww
    10,    // .wbwwww
    18,    // bwbwwww
    -5,    // wwbwwww
    -42,   // ..wwwww
    -13,   // b.wwwww
    -1,    // w.wwwww
    -2,    // .bwwwww
    15,    // bbwwwww
    16,    // wbwwwww
    4,     // .wwwwww
    16,    // bwwwwww
    -20,   // wwwwwww
    0,     // captures=0 threats=0
    63,    // captures=0 threats=1
    77,    // captures=0 threats=2
    144,   // captures=0 threats=3
    161,   // captures=0 threats=4
    2,     // captures=0 additional threats
    6,     // captures=1 threats=0
    87,    // captures=1 threats=1
    132,   // captures=1 threats=2
    310,   // captures=1 threats=3
    317,   // captures=1 threats=4
    166,   // captures=1 additional threats
    71,    // captures=2 threats=0
    96,    // captures=2 threats=1
    136,   // captures=2 threats=2
    312,   // captures=2 threats=3
    324,   // captures=2 threats=4
    115,   // captures=2 additional threats
    105,   // captures=3 threats=0
    188,   // captures=3 threats=1
    215,   // captures=3 threats=2
    347,   // captures=3 threats=3
    572,   // captures=3 threats=4
    104,   // captures=3 additional threats
    208,   // captures=4 threats=0
    234,   // captures=4 threats=1
    336,   // captures=4 threats=2
    615,   // captures=4 threats=3
    723,   // captures=4 threats=4
    83,    // captures=4 additional threats
].into_boxed_slice()
