vec![
    0,     // .......
    4,     // b......
    -4,    // w......
    7,     // .b.....
    28,    // bb.....
    -10,   // wb.....
    -7,    // .w.....
    10,    // bw.....
    -28,   // ww.....
    4,     // ..b....
    19,    // b.b....
    -13,   // w.b....
    5,     // .bb....
    68,    // bbb....
    -35,   // wbb....
    -12,   // .wb....
    -14,   // bwb....
    -20,   // wwb....
    -4,    // ..w....
    13,    // b.w....
    -19,   // w.w....
    12,    // .bw....
    20,    // bbw....
    14,    // wbw....
    -5,    // .ww....
    35,    // bww....
    -68,   // www....
    -15,   // ...b...
    -5,    // b..b...
    12,    // w..b...
    -8,    // .b.b...
    -11,   // bb.b...
    -29,   // wb.b...
    2,     // .w.b...
    -16,   // bw.b...
    -14,   // ww.b...
    -22,   // ..bb...
    20,    // b.bb...
    -23,   // w.bb...
    28,    // .bbb...
    125,   // bbbb...
    -41,   // wbbb...
    -27,   // .wbb...
    6,     // bwbb...
    26,    // wwbb...
    5,     // ..wb...
    18,    // b.wb...
    6,     // w.wb...
    26,    // .bwb...
    -3,    // bbwb...
    4,     // wbwb...
    18,    // .wwb...
    3,     // bwwb...
    14,    // wwwb...
    15,    // ...w...
    -12,   // b..w...
    5,     // w..w...
    -2,    // .b.w...
    14,    // bb.w...
    16,    // wb.w...
    8,     // .w.w...
    29,    // bw.w...
    11,    // ww.w...
    -5,    // ..bw...
    -6,    // b.bw...
    -18,   // w.bw...
    -18,   // .bbw...
    -14,   // bbbw...
    -3,    // wbbw...
    -26,   // .wbw...
    -4,    // bwbw...
    3,     // wwbw...
    22,    // ..ww...
    23,    // b.ww...
    -20,   // w.ww...
    27,    // .bww...
    -26,   // bbww...
    -6,    // wbww...
    -28,   // .www...
    41,    // bwww...
    -125,  // wwww...
    4,     // ....b..
    -6,    // b...b..
    8,     // w...b..
    9,     // .b..b..
    -13,   // bb..b..
    -17,   // wb..b..
    -1,    // .w..b..
    -22,   // bw..b..
    -15,   // ww..b..
    3,     // ..b.b..
    -34,   // b.b.b..
    8,     // w.b.b..
    12,    // .bb.b..
    13,    // bbb.b..
    3,     // wbb.b..
    14,    // .wb.b..
    6,     // bwb.b..
    11,    // wwb.b..
    0,     // ..w.b..
    -13,   // b.w.b..
    4,     // w.w.b..
    17,    // .bw.b..
    -12,   // bbw.b..
    7,     // wbw.b..
    7,     // .ww.b..
    -3,    // bww.b..
    -5,    // www.b..
    -22,   // ...bb..
    -7,    // b..bb..
    -9,    // w..bb..
    50,    // .b.bb..
    11,    // bb.bb..
    -7,    // wb.bb..
    9,     // .w.bb..
    6,     // bw.bb..
    18,    // ww.bb..
    -4,    // ..bbb..
    26,    // b.bbb..
    -34,   // w.bbb..
    98,    // .bbbb..
    21,    // bbbbb..
    30,    // wbbbb..
    -49,   // .wbbb..
    -21,   // bwbbb..
    2,     // wwbbb..
    -16,   // ..wbb..
    -9,    // b.wbb..
    6,     // w.wbb..
    -19,   // .bwbb..
    -21,   // bbwbb..
    -23,   // wbwbb..
    -27,   // .wwbb..
    -7,    // bwwbb..
    -15,   // wwwbb..
    -5,    // ...wb..
    -20,   // b..wb..
    -13,   // w..wb..
    -17,   // .b.wb..
    -2,    // bb.wb..
    32,    // wb.wb..
    -16,   // .w.wb..
    -17,   // bw.wb..
    -3,    // ww.wb..
    1,     // ..bwb..
    2,     // b.bwb..
    -24,   // w.bwb..
    -3,    // .bbwb..
    -25,   // bbbwb..
    38,    // wbbwb..
    -32,   // .wbwb..
    13,    // bwbwb..
    -17,   // wwbwb..
    16,    // ..wwb..
    -5,    // b.wwb..
    16,    // w.wwb..
    14,    // .bwwb..
    9,     // bbwwb..
    42,    // wbwwb..
    23,    // .wwwb..
    8,     // bwwwb..
    -30,   // wwwwb..
    -4,    // ....w..
    -8,    // b...w..
    6,     // w...w..
    1,     // .b..w..
    15,    // bb..w..
    22,    // wb..w..
    -9,    // .w..w..
    17,    // bw..w..
    13,    // ww..w..
    0,     // ..b.w..
    -4,    // b.b.w..
    13,    // w.b.w..
    -7,    // .bb.w..
    5,     // bbb.w..
    3,     // wbb.w..
    -17,   // .wb.w..
    -7,    // bwb.w..
    12,    // wwb.w..
    -3,    // ..w.w..
    -8,    // b.w.w..
    34,    // w.w.w..
    -14,   // .bw.w..
    -11,   // bbw.w..
    -6,    // wbw.w..
    -12,   // .ww.w..
    -3,    // bww.w..
    -13,   // www.w..
    5,     // ...bw..
    13,    // b..bw..
    20,    // w..bw..
    16,    // .b.bw..
    3,     // bb.bw..
    17,    // wb.bw..
    17,    // .w.bw..
    -32,   // bw.bw..
    2,     // ww.bw..
    -16,   // ..bbw..
    -16,   // b.bbw..
    5,     // w.bbw..
    -23,   // .bbbw..
    30,    // bbbbw..
    -8,    // wbbbw..
    -14,   // .wbbw..
    -42,   // bwbbw..
    -9,    // wwbbw..
    -1,    // ..wbw..
    24,    // b.wbw..
    -2,    // w.wbw..
    32,    // .bwbw..
    17,    // bbwbw..
    -13,   // wbwbw..
    3,     // .wwbw..
    -38,   // bwwbw..
    25,    // wwwbw..
    22,    // ...ww..
    9,     // b..ww..
    7,     // w..ww..
    -9,    // .b.ww..
    -18,   // bb.ww..
    -6,    // wb.ww..
    -50,   // .w.ww..
    7,     // bw.ww..
    -11,   // ww.ww..
    16,    // ..bww..
    -6,    // b.bww..
    9,     // w.bww..
    27,    // .bbww..
    15,    // bbbww..
    7,     // wbbww..
    19,    // .wbww..
    23,    // bwbww..
    21,    // wwbww..
    4,     // ..www..
    34,    // b.www..
    -26,   // w.www..
    49,    // .bwww..
    -2,    // bbwww..
    21,    // wbwww..
    -98,   // .wwww..
    -30,   // bwwww..
    -21,   // wwwww..
    7,     // .....b.
    -12,   // b....b.
    -41,   // w....b.
    13,    // .b...b.
    32,    // bb...b.
    6,     // wb...b.
    0,     // .w...b.
    20,    // bw...b.
    9,     // ww...b.
    9,     // ..b..b.
    13,    // b.b..b.
    9,     // w.b..b.
    -4,    // .bb..b.
    -3,    // bbb..b.
    43,    // wbb..b.
    -9,    // .wb..b.
    12,    // bwb..b.
    27,    // wwb..b.
    1,     // ..w..b.
    -42,   // b.w..b.
    13,    // w.w..b.
    9,     // .bw..b.
    -29,   // bbw..b.
    -40,   // wbw..b.
    45,    // .ww..b.
    -54,   // bww..b.
    -35,   // www..b.
    -8,    // ...b.b.
    -11,   // b..b.b.
    44,    // w..b.b.
    17,    // .b.b.b.
    3,     // bb.b.b.
    -7,    // wb.b.b.
    0,     // .w.b.b.
    -53,   // bw.b.b.
    -25,   // ww.b.b.
    50,    // ..bb.b.
    -24,   // b.bb.b.
    14,    // w.bb.b.
    -8,    // .bbb.b.
    30,    // bbbb.b.
    35,    // wbbb.b.
    -4,    // .wbb.b.
    18,    // bwbb.b.
    -37,   // wwbb.b.
    16,    // ..wb.b.
    4,     // b.wb.b.
    -2,    // w.wb.b.
    12,    // .bwb.b.
    -3,    // bbwb.b.
    3,     // wbwb.b.
    15,    // .wwb.b.
    6,     // bwwb.b.
    -16,   // wwwb.b.
    -2,    // ...w.b.
    5,     // b..w.b.
    -22,   // w..w.b.
    -28,   // .b.w.b.
    -4,    // bb.w.b.
    0,     // wb.w.b.
    0,     // .w.w.b.
    7,     // bw.w.b.
    2,     // ww.w.b.
    -17,   // ..bw.b.
    -3,    // b.bw.b.
    -8,    // w.bw.b.
    -17,   // .bbw.b.
    -2,    // bbbw.b.
    -26,   // wbbw.b.
    -13,   // .wbw.b.
    -19,   // bwbw.b.
    26,    // wwbw.b.
    -9,    // ..ww.b.
    -3,    // b.ww.b.
    -9,    // w.ww.b.
    3,     // .bww.b.
    -31,   // bbww.b.
    46,    // wbww.b.
    -28,   // .www.b.
    -9,    // bwww.b.
    -7,    // wwww.b.
    5,     // ....bb.
    -18,   // b...bb.
    8,     // w...bb.
    -4,    // .b..bb.
    3,     // bb..bb.
    22,    // wb..bb.
    -45,   // .w..bb.
    14,    // bw..bb.
    7,     // ww..bb.
    12,    // ..b.bb.
    3,     // b.b.bb.
    -9,    // w.b.bb.
    7,     // .bb.bb.
    -10,   // bbb.bb.
    24,    // wbb.bb.
    8,     // .wb.bb.
    -3,    // bwb.bb.
    -14,   // wwb.bb.
    -7,    // ..w.bb.
    -2,    // b.w.bb.
    -35,   // w.w.bb.
    -1,    // .bw.bb.
    1,     // bbw.bb.
    -12,   // wbw.bb.
    0,     // .ww.bb.
    10,    // bww.bb.
    -37,   // www.bb.
    28,    // ...bbb.
    -10,   // b..bbb.
    8,     // w..bbb.
    -8,    // .b.bbb.
    -1,    // bb.bbb.
    31,    // wb.bbb.
    28,    // .w.bbb.
    21,    // bw.bbb.
    -14,   // ww.bbb.
    98,    // ..bbbb.
    21,    // b.bbbb.
    0,     // w.bbbb.
    11,    // .bbbbb.
    13,    // bbbbbb.
    20,    // wbbbbb.
    37,    // .wbbbb.
    31,    // bwbbbb.
    28,    // wwbbbb.
    -23,   // ..wbbb.
    13,    // b.wbbb.
    -15,   // w.wbbb.
    -18,   // .bwbbb.
    -19,   // bbwbbb.
    -13,   // wbwbbb.
    17,    // .wwbbb.
    -27,   // bwwbbb.
    0,     // wwwbbb.
    -18,   // ...wbb.
    25,    // b..wbb.
    28,    // w..wbb.
    -17,   // .b.wbb.
    20,    // bb.wbb.
    -19,   // wb.wbb.
    -15,   // .w.wbb.
    -32,   // bw.wbb.
    -6,    // ww.wbb.
    -3,    // ..bwbb.
    16,    // b.bwbb.
    -28,   // w.bwbb.
    9,     // .bbwbb.
    -25,   // bbbwbb.
    -12,   // wbbwbb.
    11,    // .wbwbb.
    -9,    // bwbwbb.
    14,    // wwbwbb.
    27,    // ..wwbb.
    1,     // b.wwbb.
    14,    // w.wwbb.
    -21,   // .bwwbb.
    -25,   // bbwwbb.
    9,     // wbwwbb.
    -17,   // .wwwbb.
    -16,   // bwwwbb.
    -4,    // wwwwbb.
    12,    // ....wb.
    27,    // b...wb.
    -20,   // w...wb.
    9,     // .b..wb.
    -14,   // bb..wb.
    -43,   // wb..wb.
    9,     // .w..wb.
    -25,   // bw..wb.
    -14,   // ww..wb.
    17,    // ..b.wb.
    -29,   // b.b.wb.
    -17,   // w.b.wb.
    -1,    // .bb.wb.
    -8,    // bbb.wb.
    -3,    // wbb.wb.
    0,     // .wb.wb.
    -9,    // bwb.wb.
    23,    // wwb.wb.
    -14,   // ..w.wb.
    45,    // b.w.wb.
    32,    // w.w.wb.
    2,     // .bw.wb.
    18,    // bbw.wb.
    -27,   // wbw.wb.
    -8,    // .ww.wb.
    17,    // bww.wb.
    -31,   // www.wb.
    26,    // ...bwb.
    -4,    // b..bwb.
    -5,    // w..bwb.
    12,    // .b.bwb.
    0,     // bb.bwb.
    36,    // wb.bwb.
    13,    // .w.bwb.
    13,    // bw.bwb.
    -15,   // ww.bwb.
    -19,   // ..bbwb.
    -33,   // b.bbwb.
    21,    // w.bbwb.
    -18,   // .bbbwb.
    8,     // bbbbwb.
    15,    // wbbbwb.
    -18,   // .wbbwb.
    -1,    // bwbbwb.
    28,    // wwbbwb.
    32,    // ..wbwb.
    -1,    // b.wbwb.
    -9,    // w.wbwb.
    -28,   // .bwbwb.
    31,    // bbwbwb.
    16,    // wbwbwb.
    -11,   // .wwbwb.
    23,    // bwwbwb.
    -41,   // wwwbwb.
    27,    // ...wwb.
    -5,    // b..wwb.
    6,     // w..wwb.
    3,     // .b.wwb.
    -15,   // bb.wwb.
    -15,   // wb.wwb.
    4,     // .w.wwb.
    -17,   // bw.wwb.
    0,     // ww.wwb.
    14,    // ..bwwb.
    21,    // b.bwwb.
    -14,   // w.bwwb.
    -21,   // .bbwwb.
    -18,   // bbbwwb.
    -26,   // wbbwwb.
    18,    // .wbwwb.
    14,    // bwbwwb.
    27,    // wwbwwb.
    49,    // ..wwwb.
    36,    // b.wwwb.
    -24,   // w.wwwb.
    -28,   // .bwwwb.
    9,     // bbwwwb.
    14,    // wbwwwb.
    -37,   // .wwwwb.
    68,    // bwwwwb.
    -7,    // wwwwwb.
    -7,    // .....w.
    41,    // b....w.
    12,    // w....w.
    0,     // .b...w.
    -9,    // bb...w.
    -20,   // wb...w.
    -13,   // .w...w.
    -6,    // bw...w.
    -32,   // ww...w.
    -1,    // ..b..w.
    -13,   // b.b..w.
    42,    // w.b..w.
    -45,   // .bb..w.
    35,    // bbb..w.
    54,    // wbb..w.
    -9,    // .wb..w.
    40,    // bwb..w.
    29,    // wwb..w.
    -9,    // ..w..w.
    -9,    // b.w..w.
    -13,   // w.w..w.
    9,     // .bw..w.
    -27,   // bbw..w.
    -12,   // wbw..w.
    4,     // .ww..w.
    -43,   // bww..w.
    3,     // www..w.
    2,     // ...b.w.
    22,    // b..b.w.
    -5,    // w..b.w.
    0,     // .b.b.w.
    -2,    // bb.b.w.
    -7,    // wb.b.w.
    28,    // .w.b.w.
    0,     // bw.b.w.
    4,     // ww.b.w.
    9,     // ..bb.w.
    9,     // b.bb.w.
    3,     // w.bb.w.
    28,    // .bbb.w.
    7,     // bbbb.w.
    9,     // wbbb.w.
    -3,    // .wbb.w.
    -46,   // bwbb.w.
    31,    // wwbb.w.
    17,    // ..wb.w.
    8,     // b.wb.w.
    3,     // w.wb.w.
    13,    // .bwb.w.
    -26,   // bbwb.w.
    19,    // wbwb.w.
    17,    // .wwb.w.
    26,    // bwwb.w.
    2,     // wwwb.w.
    8,     // ...w.w.
    -44,   // b..w.w.
    11,    // w..w.w.
    0,     // .b.w.w.
    25,    // bb.w.w.
    53,    // wb.w.w.
    -17,   // .w.w.w.
    7,     // bw.w.w.
    -3,    // ww.w.w.
    -16,   // ..bw.w.
    2,     // b.bw.w.
    -4,    // w.bw.w.
    -15,   // .bbw.w.
    16,    // bbbw.w.
    -6,    // wbbw.w.
    -12,   // .wbw.w.
    -3,    // bwbw.w.
    3,     // wwbw.w.
    -50,   // ..ww.w.
    -14,   // b.ww.w.
    24,    // w.ww.w.
    4,     // .bww.w.
    37,    // bbww.w.
    -18,   // wbww.w.
    8,     // .www.w.
    -35,   // bwww.w.
    -30,   // wwww.w.
    -12,   // ....bw.
    20,    // b...bw.
    -27,   // w...bw.
    -9,    // .b..bw.
    14,    // bb..bw.
    25,    // wb..bw.
    -9,    // .w..bw.
    43,    // bw..bw.
    14,    // ww..bw.
    14,    // ..b.bw.
    -32,   // b.b.bw.
    -45,   // w.b.bw.
    8,     // .bb.bw.
    31,    // bbb.bw.
    -17,   // wbb.bw.
    -2,    // .wb.bw.
    27,    // bwb.bw.
    -18,   // wwb.bw.
    -17,   // ..w.bw.
    17,    // b.w.bw.
    29,    // w.w.bw.
    0,     // .bw.bw.
    -23,   // bbw.bw.
    9,     // wbw.bw.
    1,     // .ww.bw.
    3,     // bww.bw.
    8,     // www.bw.
    -27,   // ...bbw.
    -6,    // b..bbw.
    5,     // w..bbw.
    -4,    // .b.bbw.
    0,     // bb.bbw.
    17,    // wb.bbw.
    -3,    // .w.bbw.
    15,    // bw.bbw.
    15,    // ww.bbw.
    -49,   // ..bbbw.
    24,    // b.bbbw.
    -36,   // w.bbbw.
    37,    // .bbbbw.
    7,     // bbbbbw.
    -68,   // wbbbbw.
    28,    // .wbbbw.
    -14,   // bwbbbw.
    -9,    // wwbbbw.
    -14,   // ..wbbw.
    14,    // b.wbbw.
    -21,   // w.wbbw.
    -18,   // .bwbbw.
    -27,   // bbwbbw.
    -14,   // wbwbbw.
    21,    // .wwbbw.
    26,    // bwwbbw.
    18,    // wwwbbw.
    -26,   // ...wbw.
    5,     // b..wbw.
    4,     // w..wbw.
    -13,   // .b.wbw.
    15,    // bb.wbw.
    -13,   // wb.wbw.
    -12,   // .w.wbw.
    -36,   // bw.wbw.
    0,     // ww.wbw.
    -32,   // ..bwbw.
    9,     // b.bwbw.
    1,     // w.bwbw.
    11,    // .bbwbw.
    41,    // bbbwbw.
    -23,   // wbbwbw.
    28,    // .wbwbw.
    -16,   // bwbwbw.
    -31,   // wwbwbw.
    19,    // ..wwbw.
    -21,   // b.wwbw.
    33,    // w.wwbw.
    18,    // .bwwbw.
    -28,   // bbwwbw.
    1,     // wbwwbw.
    18,    // .wwwbw.
    -15,   // bwwwbw.
    -8,    // wwwwbw.
    -5,    // ....ww.
    -8,    // b...ww.
    18,    // w...ww.
    45,    // .b..ww.
    -7,    // bb..ww.
    -14,   // wb..ww.
    4,     // .w..ww.
    -22,   // bw..ww.
    -3,    // ww..ww.
    7,     // ..b.ww.
    35,    // b.b.ww.
    2,     // w.b.ww.
    0,     // .bb.ww.
    37,    // bbb.ww.
    -10,   // wbb.ww.
    1,     // .wb.ww.
    12,    // bwb.ww.
    -1,    // wwb.ww.
    -12,   // ..w.ww.
    9,     // b.w.ww.
    -3,    // w.w.ww.
    -8,    // .bw.ww.
    14,    // bbw.ww.
    3,     // wbw.ww.
    -7,    // .ww.ww.
    -24,   // bww.ww.
    10,    // www.ww.
    18,    // ...bww.
    -28,   // b..bww.
    -25,   // w..bww.
    15,    // .b.bww.
    6,     // bb.bww.
    32,    // wb.bww.
    17,    // .w.bww.
    19,    // bw.bww.
    -20,   // ww.bww.
    -27,   // ..bbww.
    -14,   // b.bbww.
    -1,    // w.bbww.
    17,    // .bbbww.
    4,     // bbbbww.
    16,    // wbbbww.
    21,    // .wbbww.
    -9,    // bwbbww.
    25,    // wwbbww.
    3,     // ..wbww.
    28,    // b.wbww.
    -16,   // w.wbww.
    -11,   // .bwbww.
    -14,   // bbwbww.
    9,     // wbwbww.
    -9,    // .wwbww.
    12,    // bwwbww.
    25,    // wwwbww.
    -28,   // ...www.
    -8,    // b..www.
    10,    // w..www.
    -28,   // .b.www.
    14,    // bb.www.
    -21,   // wb.www.
    8,     // .w.www.
    -31,   // bw.www.
    1,     // ww.www.
    23,    // ..bwww.
    15,    // b.bwww.
    -13,   // w.bwww.
    -17,   // .bbwww.
    0,     // bbbwww.
    27,    // wbbwww.
    18,    // .wbwww.
    13,    // bwbwww.
    19,    // wwbwww.
    -98,   // ..wwww.
    0,     // b.wwww.
    -21,   // w.wwww.
    -37,   // .bwwww.
    -28,   // bbwwww.
    -31,   // wbwwww.
    -11,   // .wwwww.
    -20,   // bwwwww.
    -13,   // wwwwww.
    4,     // ......b
    -9,    // b.....b
    0,     // w.....b
    -12,   // .b....b
    17,    // bb....b
    16,    // wb....b
    41,    // .w....b
    -13,   // bw....b
    13,    // ww....b
    -6,    // ..b...b
    -8,    // b.b...b
    -5,    // w.b...b
    -18,   // .bb...b
    -37,   // bbb...b
    -16,   // wbb...b
    20,    // .wb...b
    -44,   // bwb...b
    -20,   // wwb...b
    -8,    // ..w...b
    -32,   // b.w...b
    1,     // w.w...b
    27,    // .bw...b
    -15,   // bbw...b
    -21,   // wbw...b
    -8,    // .ww...b
    -15,   // bww...b
    19,    // www...b
    -5,    // ...b..b
    -4,    // b..b..b
    18,    // w..b..b
    -11,   // .b.b..b
    2,     // bb.b..b
    26,    // wb.b..b
    22,    // .w.b..b
    -12,   // bw.b..b
    -1,    // ww.b..b
    -7,    // ..bb..b
    14,    // b.bb..b
    -25,   // w.bb..b
    -10,   // .bbb..b
    12,    // bbbb..b
    23,    // wbbb..b
    -6,    // .wbb..b
    -7,    // bwbb..b
    4,     // wwbb..b
    13,    // ..wb..b
    21,    // b.wb..b
    -11,   // w.wb..b
    -4,    // .bwb..b
    19,    // bbwb..b
    -2,    // wbwb..b
    -28,   // .wwb..b
    1,     // bwwb..b
    -14,   // wwwb..b
    -12,   // ...w..b
    -3,    // b..w..b
    -18,   // w..w..b
    5,     // .b.w..b
    10,    // bb.w..b
    -14,   // wb.w..b
    -44,   // .w.w..b
    -16,   // bw.w..b
    -34,   // ww.w..b
    -20,   // ..bw..b
    20,    // b.bw..b
    -7,    // w.bw..b
    25,    // .bbw..b
    -4,    // bbbw..b
    -21,   // wbbw..b
    5,     // .wbw..b
    -18,   // bwbw..b
    10,    // wwbw..b
    9,     // ..ww..b
    26,    // b.ww..b
    -40,   // w.ww..b
    -5,    // .bww..b
    -10,   // bbww..b
    14,    // wbww..b
    -8,    // .www..b
    8,     // bwww..b
    4,     // wwww..b
    19,    // ....b.b
    -8,    // b...b.b
    -1,    // w...b.b
    13,    // .b..b.b
    -23,   // bb..b.b
    -30,   // wb..b.b
    -13,   // .w..b.b
    52,    // bw..b.b
    -32,   // ww..b.b
    -34,   // ..b.b.b
    -27,   // b.b.b.b
    -9,    // w.b.b.b
    3,     // .bb.b.b
    -12,   // bbb.b.b
    -4,    // wbb.b.b
    -32,   // .wb.b.b
    0,     // bwb.b.b
    12,    // wwb.b.b
    -4,    // ..w.b.b
    -9,    // b.w.b.b
    0,     // w.w.b.b
    -29,   // .bw.b.b
    -7,    // bbw.b.b
    10,    // wbw.b.b
    35,    // .ww.b.b
    0,     // bww.b.b
    -14,   // www.b.b
    20,    // ...bb.b
    14,    // b..bb.b
    40,    // w..bb.b
    -24,   // .b.bb.b
    21,    // bb.bb.b
    -13,   // wb.bb.b
    9,     // .w.bb.b
    38,    // bw.bb.b
    2,     // ww.bb.b
    26,    // ..bbb.b
    32,    // b.bbb.b
    28,    // w.bbb.b
    21,    // .bbbb.b
    8,     // bbbbb.b
    -28,   // wbbbb.b
    24,    // .wbbb.b
    8,     // bwbbb.b
    -16,   // wwbbb.b
    -16,   // ..wbb.b
    23,    // b.wbb.b
    10,    // w.wbb.b
    -33,   // .bwbb.b
    18,    // bbwbb.b
    1,     // wbwbb.b
    -14,   // .wwbb.b
    -12,   // bwwbb.b
    -32,   // wwwbb.b
    -6,    // ...wb.b
    20,    // b..wb.b
    11,    // w..wb.b
    -3,    // .b.wb.b
    18,    // bb.wb.b
    -19,   // wb.wb.b
    2,     // .w.wb.b
    15,    // bw.wb.b
    40,    // ww.wb.b
    2,     // ..bwb.b
    17,    // b.bwb.b
    -26,   // w.bwb.b
    16,    // .bbwb.b
    -1,    // bbbwb.b
    -1,    // wbbwb.b
    9,     // .wbwb.b
    -9,    // bwbwb.b
    -6,    // wwbwb.b
    -6,    // ..wwb.b
    18,    // b.wwb.b
    -10,   // w.wwb.b
    21,    // .bwwb.b
    -24,   // bbwwb.b
    1,     // wbwwb.b
    15,    // .wwwb.b
    4,     // bwwwb.b
    12,    // wwwwb.b
    13,    // ....w.b
    -32,   // b...w.b
    5,     // w...w.b
    -42,   // .b..w.b
    24,    // bb..w.b
    8,     // wb..w.b
    -9,    // .w..w.b
    7,     // bw..w.b
    -5,    // ww..w.b
    -13,   // ..b.w.b
    -9,    // b.b.w.b
    0,     // w.b.w.b
    -2,    // .bb.w.b
    24,    // bbb.w.b
    -12,   // wbb.w.b
    17,    // .wb.w.b
    26,    // bwb.w.b
    -20,   // wwb.w.b
    -8,    // ..w.w.b
    -52,   // b.w.w.b
    9,     // w.w.w.b
    45,    // .bw.w.b
    20,    // bbw.w.b
    -3,    // wbw.w.b
    9,     // .ww.w.b
    -17,   // bww.w.b
    -1,    // www.w.b
    18,    // ...bw.b
    21,    // b..bw.b
    7,     // w..bw.b
    4,     // .b.bw.b
    5,     // bb.bw.b
    -6,    // wb.bw.b
    8,     // .w.bw.b
    46,    // bw.bw.b
    -4,    // ww.bw.b
    -9,    // ..bbw.b
    23,    // b.bbw.b
    -4,    // w.bbw.b
    13,    // .bbbw.b
    -16,   // bbbbw.b
    -3,    // wbbbw.b
    14,    // .wbbw.b
    12,    // bwbbw.b
    -17,   // wwbbw.b
    24,    // ..wbw.b
    -26,   // b.wbw.b
    26,    // w.wbw.b
    -1,    // .bwbw.b
    15,    // bbwbw.b
    3,     // wbwbw.b
    28,    // .wwbw.b
    0,     // bwwbw.b
    14,    // wwwbw.b
    23,    // ...ww.b
    26,    // b..ww.b
    25,    // w..ww.b
    -3,    // .b.ww.b
    6,     // bb.ww.b
    -11,   // wb.ww.b
    -14,   // .w.ww.b
    -26,   // bw.ww.b
    -33,   // ww.ww.b
    -5,    // ..bww.b
    18,    // b.bww.b
    4,     // w.bww.b
    1,     // .bbww.b
    -3,    // bbbww.b
    13,    // wbbww.b
    -21,   // .wbww.b
    -18,   // bwbww.b
    -26,   // wwbww.b
    34,    // ..www.b
    4,     // b.www.b
    -28,   // w.www.b
    36,    // .bwww.b
    16,    // bbwww.b
    -8,    // wbwww.b
    0,     // .wwww.b
    -9,    // bwwww.b
    -11,   // wwwww.b
    28,    // .....bb
    17,    // b....bb
    -13,   // w....bb
    32,    // .b...bb
    -25,   // bb...bb
    27,    // wb...bb
    -9,    // .w...bb
    -5,    // bw...bb
    0,     // ww...bb
    -13,   // ..b..bb
    -23,   // b.b..bb
    5,     // w.b..bb
    3,     // .bb..bb
    62,    // bbb..bb
    -19,   // wbb..bb
    14,    // .wb..bb
    -24,   // bwb..bb
    8,     // wwb..bb
    15,    // ..w..bb
    24,    // b.w..bb
    32,    // w.w..bb
    -14,   // .bw..bb
    6,     // bbw..bb
    16,    // wbw..bb
    -7,    // .ww..bb
    17,    // bww..bb
    3,     // www..bb
    -11,   // ...b.bb
    2,     // b..b.bb
    34,    // w..b.bb
    3,     // .b.b.bb
    -31,   // bb.b.bb
    -22,   // wb.b.bb
    -2,    // .w.b.bb
    0,     // bw.b.bb
    4,     // ww.b.bb
    11,    // ..bb.bb
    21,    // b.bb.bb
    33,    // w.bb.bb
    -1,    // .bbb.bb
    11,    // bbbb.bb
    6,     // wbbb.bb
    0,     // .wbb.bb
    8,     // bwbb.bb
    6,     // wwbb.bb
    3,     // ..wb.bb
    5,     // b.wb.bb
    -40,   // w.wb.bb
    0,     // .bwb.bb
    44,    // bbwb.bb
    -24,   // wbwb.bb
    6,     // .wwb.bb
    4,     // bwwb.bb
    21,    // wwwb.bb
    14,    // ...w.bb
    10,    // b..w.bb
    1,     // w..w.bb
    -4,    // .b.w.bb
    28,    // bb.w.bb
    1,     // wb.w.bb
    25,    // .w.w.bb
    -25,   // bw.w.bb
    -4,    // ww.w.bb
    -2,    // ..bw.bb
    18,    // b.bw.bb
    4,     // w.bw.bb
    20,    // .bbw.bb
    -29,   // bbbw.bb
    2,     // wbbw.bb
    15,    // .wbw.bb
    29,    // bwbw.bb
    -2,    // wwbw.bb
    -18,   // ..ww.bb
    6,     // b.ww.bb
    -2,    // w.ww.bb
    -15,   // .bww.bb
    8,     // bbww.bb
    11,    // wbww.bb
    14,    // .www.bb
    4,     // bwww.bb
    1,     // wwww.bb
    68,    // ....bbb
    -37,   // b...bbb
    -19,   // w...bbb
    -3,    // .b..bbb
    62,    // bb..bbb
    3,     // wb..bbb
    35,    // .w..bbb
    5,     // bw..bbb
    -3,    // ww..bbb
    13,    // ..b.bbb
    -12,   // b.b.bbb
    1,     // w.b.bbb
    -10,   // .bb.bbb
    41,    // bbb.bbb
    3,     // wbb.bbb
    31,    // .wb.bbb
    -13,   // bwb.bbb
    27,    // wwb.bbb
    5,     // ..w.bbb
    24,    // b.w.bbb
    14,    // w.w.bbb
    -8,    // .bw.bbb
    8,     // bbw.bbb
    -16,   // wbw.bbb
    37,    // .ww.bbb
    -17,   // bww.bbb
    0,     // www.bbb
    125,   // ...bbbb
    12,    // b..bbbb
    -4,    // w..bbbb
    30,    // .b.bbbb
    11,    // bb.bbbb
    -35,   // wb.bbbb
    7,     // .w.bbbb
    9,     // bw.bbbb
    -1,    // ww.bbbb
    21,    // ..bbbbb
    8,     // b.bbbbb
    11,    // w.bbbbb
    13,    // .bbbbbb
    59,    // bbbbbbb
    27,    // wbbbbbb
    7,     // .wbbbbb
    -2,    // bwbbbbb
    -1,    // wwbbbbb
    30,    // ..wbbbb
    -16,   // b.wbbbb
    -12,   // w.wbbbb
    8,     // .bwbbbb
    25,    // bbwbbbb
    -25,   // wbwbbbb
    4,     // .wwbbbb
    4,     // bwwbbbb
    1,     // wwwbbbb
    -14,   // ...wbbb
    -4,    // b..wbbb
    14,    // w..wbbb
    -2,    // .b.wbbb
    -29,   // bb.wbbb
    -12,   // wb.wbbb
    16,    // .w.wbbb
    -12,   // bw.wbbb
    -21,   // ww.wbbb
    -25,   // ..bwbbb
    -1,    // b.bwbbb
    -14,   // w.bwbbb
    -25,   // .bbwbbb
    -18,   // bbbwbbb
    10,    // wbbwbbb
    41,    // .wbwbbb
    -30,   // bwbwbbb
    7,     // wwbwbbb
    15,    // ..wwbbb
    -3,    // b.wwbbb
    32,    // w.wwbbb
    -18,   // .bwwbbb
    -25,   // bbwwbbb
    9,     // wbwwbbb
    0,     // .wwwbbb
    7,     // bwwwbbb
    -1,    // wwwwbbb
    20,    // ....wbb
    -15,   // b...wbb
    20,    // w...wbb
    -29,   // .b..wbb
    6,     // bb..wbb
    2,     // wb..wbb
    -27,   // .w..wbb
    -22,   // bw..wbb
    -8,    // ww..wbb
    -12,   // ..b.wbb
    -7,    // b.b.wbb
    20,    // w.b.wbb
    1,     // .bb.wbb
    8,     // bbb.wbb
    26,    // wbb.wbb
    -23,   // .wb.wbb
    0,     // bwb.wbb
    0,     // wwb.wbb
    -11,   // ..w.wbb
    20,    // b.w.wbb
    -12,   // w.w.wbb
    18,    // .bw.wbb
    24,    // bbw.wbb
    1,     // wbw.wbb
    14,    // .ww.wbb
    -1,    // bww.wbb
    -27,   // www.wbb
    -3,    // ...bwbb
    19,    // b..bwbb
    -10,   // w..bwbb
    -3,    // .b.bwbb
    44,    // bb.bwbb
    -4,    // wb.bwbb
    -26,   // .w.bwbb
    -33,   // bw.bwbb
    2,     // ww.bwbb
    -21,   // ..bbwbb
    18,    // b.bbwbb
    26,    // w.bbwbb
    -19,   // .bbbwbb
    25,    // bbbbwbb
    -34,   // wbbbwbb
    -27,   // .wbbwbb
    -8,    // bwbbwbb
    31,    // wwbbwbb
    17,    // ..wbwbb
    15,    // b.wbwbb
    6,     // w.wbwbb
    31,    // .bwbwbb
    -19,   // bbwbwbb
    -8,    // wbwbwbb
    -14,   // .wwbwbb
    -10,   // bwwbwbb
    -7,    // wwwbwbb
    -26,   // ...wwbb
    -10,   // b..wwbb
    -4,    // w..wwbb
    -31,   // .b.wwbb
    8,     // bb.wwbb
    6,     // wb.wwbb
    37,    // .w.wwbb
    55,    // bw.wwbb
    -6,    // ww.wwbb
    9,     // ..bwwbb
    -24,   // b.bwwbb
    17,    // w.bwwbb
    -25,   // .bbwwbb
    -25,   // bbbwwbb
    -3,    // wbbwwbb
    -28,   // .wbwwbb
    -3,    // bwbwwbb
    -31,   // wwbwwbb
    -2,    // ..wwwbb
    16,    // b.wwwbb
    16,    // w.wwwbb
    9,     // .bwwwbb
    -3,    // bbwwwbb
    -6,    // wbwwwbb
    -28,   // .wwwwbb
    -3,    // bwwwwbb
    1,     // wwwwwbb
    10,    // .....wb
    -13,   // b....wb
    -16,   // w....wb
    20,    // .b...wb
    -5,    // bb...wb
    0,     // wb...wb
    -6,    // .w...wb
    7,     // bw...wb
    -27,   // ww...wb
    -22,   // ..b..wb
    52,    // b.b..wb
    -8,    // w.b..wb
    14,    // .bb..wb
    5,     // bbb..wb
    -6,    // wbb..wb
    43,    // .wb..wb
    -5,    // bwb..wb
    -2,    // wwb..wb
    17,    // ..w..wb
    7,     // b.w..wb
    30,    // w.w..wb
    -25,   // .bw..wb
    -22,   // bbw..wb
    -39,   // wbw..wb
    -22,   // .ww..wb
    18,    // bww..wb
    -3,    // www..wb
    -16,   // ...b.wb
    -12,   // b..b.wb
    14,    // w..b.wb
    -53,   // .b.b.wb
    0,     // bb.b.wb
    -5,    // wb.b.wb
    0,     // .w.b.wb
    -8,    // bw.b.wb
    -1,    // ww.b.wb
    6,     // ..bb.wb
    38,    // b.bb.wb
    11,    // w.bb.wb
    21,    // .bbb.wb
    9,     // bbbb.wb
    2,     // wbbb.wb
    15,    // .wbb.wb
    -1,    // bwbb.wb
    -6,    // wwbb.wb
    -32,   // ..wb.wb
    46,    // b.wb.wb
    19,    // w.wb.wb
    13,    // .bwb.wb
    -33,   // bbwb.wb
    -2,    // wbwb.wb
    19,    // .wwb.wb
    -23,   // bwwb.wb
    12,    // wwwb.wb
    29,    // ...w.wb
    -16,   // b..w.wb
    -26,   // w..w.wb
    7,     // .b.w.wb
    -25,   // bb.w.wb
    5,     // wb.w.wb
    7,     // .w.w.wb
    13,    // bw.w.wb
    22,    // ww.w.wb
    -17,   // ..bw.wb
    15,    // b.bw.wb
    6,     // w.bw.wb
    -32,   // .bbw.wb
    -12,   // bbbw.wb
    -6,    // wbbw.wb
    -36,   // .wbw.wb
    -5,    // bwbw.wb
    4,     // wwbw.wb
    7,     // ..ww.wb
    -26,   // b.ww.wb
    13,    // w.ww.wb
    -17,   // .bww.wb
    55,    // bbww.wb
    2,     // wbww.wb
    -31,   // .www.wb
    -14,   // bwww.wb
    35,    // wwww.wb
    -14,   // ....bwb
    -44,   // b...bwb
    21,    // w...bwb
    12,    // .b..bwb
    -24,   // bb..bwb
    39,    // wb..bwb
    40,    // .w..bwb
    -5,    // bw..bwb
    -16,   // ww..bwb
    6,     // ..b.bwb
    0,     // b.b.bwb
    3,     // w.b.bwb
    -3,    // .bb.bwb
    -13,   // bbb.bwb
    -15,   // wbb.bwb
    27,    // .wb.bwb
    -12,   // bwb.bwb
    -1,    // wwb.bwb
    -7,    // ..w.bwb
    26,    // b.w.bwb
    -10,   // w.w.bwb
    -9,    // .bw.bwb
    0,     // bbw.bwb
    0,     // wbw.bwb
    12,    // .ww.bwb
    -4,    // bww.bwb
    16,    // www.bwb
    6,     // ...bbwb
    -7,    // b..bbwb
    -14,   // w..bbwb
    18,    // .b.bbwb
    8,     // bb.bbwb
    -2,    // wb.bbwb
    -46,   // .w.bbwb
    -1,    // bw.bbwb
    -11,   // ww.bbwb
    -21,   // ..bbbwb
    8,     // b.bbbwb
    8,     // w.bbbwb
    31,    // .bbbbwb
    -2,    // bbbbbwb
    20,    // wbbbbwb
    -14,   // .wbbbwb
    -26,   // bwbbbwb
    6,     // wwbbbwb
    -42,   // ..wbbwb
    12,    // b.wbbwb
    -1,    // w.wbbwb
    -1,    // .bwbbwb
    -8,    // bbwbbwb
    -8,    // wbwbbwb
    -9,    // .wwbbwb
    9,     // bwwbbwb
    -9,    // wwwbbwb
    -4,    // ...wbwb
    -18,   // b..wbwb
    2,     // w..wbwb
    -19,   // .b.wbwb
    29,    // bb.wbwb
    2,     // wb.wbwb
    -3,    // .w.wbwb
    -5,    // bw.wbwb
    24,    // ww.wbwb
    13,    // ..bwbwb
    -9,    // b.bwbwb
    -3,    // w.bwbwb
    -9,    // .bbwbwb
    -30,   // bbbwbwb
    -5,    // wbbwbwb
    -16,   // .wbwbwb
    9,     // bwbwbwb
    8,     // wwbwbwb
    23,    // ..wwbwb
    -18,   // b.wwbwb
    -1,    // w.wwbwb
    14,    // .bwwbwb
    -3,    // bbwwbwb
    8,     // wbwwbwb
    13,    // .wwwbwb
    28,    // bwwwbwb
    25,    // wwwwbwb
    35,    // ....wwb
    -15,   // b...wwb
    16,    // w...wwb
    -54,   // .b..wwb
    17,    // bb..wwb
    6,     // wb..wwb
    -43,   // .w..wwb
    18,    // bw..wwb
    19,    // ww..wwb
    -3,    // ..b.wwb
    0,     // b.b.wwb
    12,    // w.b.wwb
    10,    // .bb.wwb
    -17,   // bbb.wwb
    0,     // wbb.wwb
    3,     // .wb.wwb
    -4,    // bwb.wwb
    -26,   // wwb.wwb
    -3,    // ..w.wwb
    -17,   // b.w.wwb
    4,     // w.w.wwb
    17,    // .bw.wwb
    -1,    // bbw.wwb
    15,    // wbw.wwb
    -24,   // .ww.wwb
    -28,   // bww.wwb
    -3,    // www.wwb
    3,     // ...bwwb
    1,     // b..bwwb
    21,    // w..bwwb
    6,     // .b.bwwb
    4,     // bb.bwwb
    6,     // wb.bwwb
    26,    // .w.bwwb
    -23,   // bw.bwwb
    -2,    // ww.bwwb
    -7,    // ..bbwwb
    -12,   // b.bbwwb
    -13,   // w.bbwwb
    -27,   // .bbbwwb
    4,     // bbbbwwb
    7,     // wbbbwwb
    26,    // .wbbwwb
    9,     // bwbbwwb
    3,     // wwbbwwb
    -38,   // ..wbwwb
    0,     // b.wbwwb
    1,     // w.wbwwb
    23,    // .bwbwwb
    -10,   // bbwbwwb
    5,     // wbwbwwb
    12,    // .wwbwwb
    41,    // bwwbwwb
    -10,   // wwwbwwb
    41,    // ...wwwb
    8,     // b..wwwb
    -23,   // w..wwwb
    -9,    // .b.wwwb
    4,     // bb.wwwb
    -2,    // wb.wwwb
    -35,   // .w.wwwb
    -14,   // bw.wwwb
    -6,    // ww.wwwb
    8,     // ..bwwwb
    4,     // b.bwwwb
    3,     // w.bwwwb
    -16,   // .bbwwwb
    7,     // bbbwwwb
    -7,    // wbbwwwb
    -15,   // .wbwwwb
    28,    // bwbwwwb
    34,    // wwbwwwb
    -30,   // ..wwwwb
    -9,    // b.wwwwb
    28,    // w.wwwwb
    68,    // .bwwwwb
    -3,    // bbwwwwb
    -20,   // wbwwwwb
    -20,   // .wwwwwb
    26,    // bwwwwwb
    -27,   // wwwwwwb
    -4,    // ......w
    0,     // b.....w
    9,     // w.....w
    -41,   // .b....w
    -13,   // bb....w
    13,    // wb....w
    12,    // .w....w
    -16,   // bw....w
    -17,   // ww....w
    8,     // ..b...w
    -1,    // b.b...w
    32,    // w.b...w
    8,     // .bb...w
    -19,   // bbb...w
    15,    // wbb...w
    -27,   // .wb...w
    21,    // bwb...w
    15,    // wwb...w
    6,     // ..w...w
    5,     // b.w...w
    8,     // w.w...w
    -20,   // .bw...w
    20,    // bbw...w
    44,    // wbw...w
    18,    // .ww...w
    16,    // bww...w
    37,    // www...w
    12,    // ...b..w
    18,    // b..b..w
    3,     // w..b..w
    44,    // .b.b..w
    34,    // bb.b..w
    16,    // wb.b..w
    -5,    // .w.b..w
    14,    // bw.b..w
    -10,   // ww.b..w
    -9,    // ..bb..w
    40,    // b.bb..w
    -26,   // w.bb..w
    8,     // .bbb..w
    -4,    // bbbb..w
    -8,    // wbbb..w
    5,     // .wbb..w
    -14,   // bwbb..w
    10,    // wwbb..w
    20,    // ..wb..w
    7,     // b.wb..w
    -20,   // w.wb..w
    -5,    // .bwb..w
    -10,   // bbwb..w
    18,    // wbwb..w
    -25,   // .wwb..w
    21,    // bwwb..w
    4,     // wwwb..w
    5,     // ...w..w
    -18,   // b..w..w
    4,     // w..w..w
    -22,   // .b.w..w
    1,     // bb.w..w
    12,    // wb.w..w
    11,    // .w.w..w
    -26,   // bw.w..w
    -2,    // ww.w..w
    -13,   // ..bw..w
    11,    // b.bw..w
    -21,   // w.bw..w
    28,    // .bbw..w
    14,    // bbbw..w
    -1,    // wbbw..w
    4,     // .wbw..w
    2,     // bwbw..w
    -19,   // wwbw..w
    7,     // ..ww..w
    25,    // b.ww..w
    -14,   // w.ww..w
    6,     // .bww..w
    -4,    // bbww..w
    7,     // wbww..w
    10,    // .www..w
    -23,   // bwww..w
    -12,   // wwww..w
    -13,   // ....b.w
    -5,    // b...b.w
    32,    // w...b.w
    9,     // .b..b.w
    5,     // bb..b.w
    -7,    // wb..b.w
    42,    // .w..b.w
    -8,    // bw..b.w
    -24,   // ww..b.w
    8,     // ..b.b.w
    -9,    // b.b.b.w
    52,    // w.b.b.w
    -9,    // .bb.b.w
    1,     // bbb.b.w
    17,    // wbb.b.w
    -45,   // .wb.b.w
    3,     // bwb.b.w
    -20,   // wwb.b.w
    13,    // ..w.b.w
    0,     // b.w.b.w
    9,     // w.w.b.w
    -17,   // .bw.b.w
    20,    // bbw.b.w
    -26,   // wbw.b.w
    2,     // .ww.b.w
    12,    // bww.b.w
    -24,   // www.b.w
    -23,   // ...bb.w
    -25,   // b..bb.w
    -26,   // w..bb.w
    14,    // .b.bb.w
    33,    // bb.bb.w
    26,    // wb.bb.w
    3,     // .w.bb.w
    11,    // bw.bb.w
    -6,    // ww.bb.w
    -34,   // ..bbb.w
    28,    // b.bbb.w
    -4,    // w.bbb.w
    0,     // .bbbb.w
    11,    // bbbbb.w
    9,     // wbbbb.w
    -36,   // .wbbb.w
    8,     // bwbbb.w
    -16,   // wwbbb.w
    5,     // ..wbb.w
    -4,    // b.wbb.w
    -18,   // w.wbb.w
    21,    // .bwbb.w
    26,    // bbwbb.w
    18,    // wbwbb.w
    -1,    // .wwbb.w
    -13,   // bwwbb.w
    3,     // wwwbb.w
    -18,   // ...wb.w
    -7,    // b..wb.w
    -21,   // w..wb.w
    -8,    // .b.wb.w
    4,     // bb.wb.w
    -46,   // wb.wb.w
    -4,    // .w.wb.w
    6,     // bw.wb.w
    -5,    // ww.wb.w
    -24,   // ..bwb.w
    -26,   // b.bwb.w
    26,    // w.bwb.w
    -28,   // .bbwb.w
    -14,   // bbbwb.w
    0,     // wbbwb.w
    1,     // .wbwb.w
    -3,    // bwbwb.w
    -15,   // wwbwb.w
    9,     // ..wwb.w
    4,     // b.wwb.w
    -23,   // w.wwb.w
    -14,   // .bwwb.w
    17,    // bbwwb.w
    -12,   // wbwwb.w
    -13,   // .wwwb.w
    3,     // bwwwb.w
    16,    // wwwwb.w
    -19,   // ....w.w
    1,     // b...w.w
    8,     // w...w.w
    13,    // .b..w.w
    32,    // bb..w.w
    -52,   // wb..w.w
    -13,   // .w..w.w
    30,    // bw..w.w
    23,    // ww..w.w
    4,     // ..b.w.w
    0,     // b.b.w.w
    9,     // w.b.w.w
    -35,   // .bb.w.w
    14,    // bbb.w.w
    0,     // wbb.w.w
    29,    // .wb.w.w
    -10,   // bwb.w.w
    7,     // wwb.w.w
    34,    // ..w.w.w
    9,     // b.w.w.w
    27,    // w.w.w.w
    32,    // .bw.w.w
    -12,   // bbw.w.w
    0,     // wbw.w.w
    -3,    // .ww.w.w
    4,     // bww.w.w
    12,    // www.w.w
    6,     // ...bw.w
    -11,   // b..bw.w
    -20,   // w..bw.w
    -2,    // .b.bw.w
    -40,   // bb.bw.w
    -15,   // wb.bw.w
    3,     // .w.bw.w
    19,    // bw.bw.w
    -18,   // ww.bw.w
    6,     // ..bbw.w
    10,    // b.bbw.w
    -18,   // w.bbw.w
    -15,   // .bbbw.w
    -12,   // bbbbw.w
    -4,    // wbbbw.w
    -21,   // .wbbw.w
    -1,    // bwbbw.w
    24,    // wwbbw.w
    -2,    // ..wbw.w
    26,    // b.wbw.w
    -17,   // w.wbw.w
    -9,    // .bwbw.w
    6,     // bbwbw.w
    9,     // wbwbw.w
    -16,   // .wwbw.w
    1,     // bwwbw.w
    1,     // wwwbw.w
    -20,   // ...ww.w
    -40,   // b..ww.w
    -14,   // w..ww.w
    -9,    // .b.ww.w
    -2,    // bb.ww.w
    -38,   // wb.ww.w
    24,    // .w.ww.w
    13,    // bw.ww.w
    -21,   // ww.ww.w
    16,    // ..bww.w
    -10,   // b.bww.w
    -23,   // w.bww.w
    14,    // .bbww.w
    32,    // bbbww.w
    12,    // wbbww.w
    33,    // .wbww.w
    -1,    // bwbww.w
    -18,   // wwbww.w
    -26,   // ..www.w
    -28,   // b.www.w
    -32,   // w.www.w
    -24,   // .bwww.w
    16,    // bbwww.w
    -8,    // wbwww.w
    -21,   // .wwww.w
    28,    // bwwww.w
    -8,    // wwwww.w
    -10,   // .....bw
    16,    // b....bw
    13,    // w....bw
    6,     // .b...bw
    27,    // bb...bw
    -7,    // wb...bw
    -20,   // .w...bw
    0,     // bw...bw
    5,     // ww...bw
    -17,   // ..b..bw
    -30,   // b.b..bw
    -7,    // w.b..bw
    22,    // .bb..bw
    3,     // bbb..bw
    -18,   // wbb..bw
    25,    // .wb..bw
    39,    // bwb..bw
    22,    // wwb..bw
    22,    // ..w..bw
    8,     // b.w..bw
    -52,   // w.w..bw
    -43,   // .bw..bw
    2,     // bbw..bw
    5,     // wbw..bw
    -14,   // .ww..bw
    6,     // bww..bw
    -5,    // www..bw
    -29,   // ...b.bw
    26,    // b..b.bw
    16,    // w..b.bw
    -7,    // .b.b.bw
    -22,   // bb.b.bw
    -13,   // wb.b.bw
    -7,    // .w.b.bw
    -5,    // bw.b.bw
    25,    // ww.b.bw
    -7,    // ..bb.bw
    -13,   // b.bb.bw
    26,    // w.bb.bw
    31,    // .bbb.bw
    -35,   // bbbb.bw
    14,    // wbbb.bw
    17,    // .wbb.bw
    -2,    // bwbb.bw
    -55,   // wwbb.bw
    17,    // ..wb.bw
    -6,    // b.wb.bw
    -15,   // w.wb.bw
    36,    // .bwb.bw
    -4,    // bbwb.bw
    5,     // wbwb.bw
    32,    // .wwb.bw
    6,     // bwwb.bw
    12,    // wwwb.bw
    16,    // ...w.bw
    -14,   // b..w.bw
    12,    // w..w.bw
    0,     // .b.w.bw
    1,     // bb.w.bw
    8,     // wb.w.bw
    53,    // .w.w.bw
    5,     // bw.w.bw
    0,     // ww.w.bw
    32,    // ..bw.bw
    -19,   // b.bw.bw
    -46,   // w.bw.bw
    -19,   // .bbw.bw
    -12,   // bbbw.bw
    23,    // wbbw.bw
    -13,   // .wbw.bw
    2,     // bwbw.bw
    33,    // wwbw.bw
    -6,    // ..ww.bw
    -11,   // b.ww.bw
    -38,   // w.ww.bw
    -15,   // .bww.bw
    6,     // bbww.bw
    1,     // wbww.bw
    -21,   // .www.bw
    -2,    // bwww.bw
    -9,    // wwww.bw
    -35,   // ....bbw
    -16,   // b...bbw
    15,    // w...bbw
    43,    // .b..bbw
    -19,   // bb..bbw
    -18,   // wb..bbw
    54,    // .w..bbw
    -6,    // bw..bbw
    -17,   // ww..bbw
    3,     // ..b.bbw
    -4,    // b.b.bbw
    17,    // w.b.bbw
    24,    // .bb.bbw
    3,     // bbb.bbw
    28,    // wbb.bbw
    -17,   // .wb.bbw
    -15,   // bwb.bbw
    1,     // wwb.bbw
    3,     // ..w.bbw
    -12,   // b.w.bbw
    0,     // w.w.bbw
    -3,    // .bw.bbw
    26,    // bbw.bbw
    4,     // wbw.bbw
    -10,   // .ww.bbw
    0,     // bww.bbw
    17,    // www.bbw
    -41,   // ...bbbw
    23,    // b..bbbw
    -8,    // w..bbbw
    35,    // .b.bbbw
    6,     // bb.bbbw
    14,    // wb.bbbw
    9,     // .w.bbbw
    2,     // bw.bbbw
    -4,    // ww.bbbw
    30,    // ..bbbbw
    -28,   // b.bbbbw
    9,     // w.bbbbw
    20,    // .bbbbbw
    27,    // bbbbbbw
    -26,   // wbbbbbw
    -68,   // .wbbbbw
    20,    // bwbbbbw
    3,     // wwbbbbw
    -8,    // ..wbbbw
    -3,    // b.wbbbw
    -4,    // w.wbbbw
    15,    // .bwbbbw
    -34,   // bbwbbbw
    -28,   // wbwbbbw
    16,    // .wwbbbw
    7,     // bwwbbbw
    -7,    // wwwbbbw
    -3,    // ...wbbw
    -21,   // b..wbbw
    -1,    // w..wbbw
    -26,   // .b.wbbw
    2,     // bb.wbbw
    23,    // wb.wbbw
    -6,    // .w.wbbw
    -6,    // bw.wbbw
    -4,    // ww.wbbw
    38,    // ..bwbbw
    -1,    // b.bwbbw
    0,     // w.bwbbw
    -12,   // .bbwbbw
    10,    // bbbwbbw
    -41,   // wbbwbbw
    -23,   // .wbwbbw
    -5,    // bwbwbbw
    10,    // wwbwbbw
    7,     // ..wwbbw
    13,    // b.wwbbw
    12,    // w.wwbbw
    -26,   // .bwwbbw
    -3,    // bbwwbbw
    -9,    // wbwwbbw
    27,    // .wwwbbw
    -7,    // bwwwbbw
    -4,    // wwwwbbw
    14,    // ....wbw
    -21,   // b...wbw
    44,    // w...wbw
    -40,   // .b..wbw
    16,    // bb..wbw
    5,     // wb..wbw
    -12,   // .w..wbw
    -39,   // bw..wbw
    24,    // ww..wbw
    7,     // ..b.wbw
    10,    // b.b.wbw
    -26,   // w.b.wbw
    -12,   // .bb.wbw
    -16,   // bbb.wbw
    4,     // wbb.wbw
    9,     // .wb.wbw
    0,     // bwb.wbw
    0,     // wwb.wbw
    -6,    // ..w.wbw
    -3,    // b.w.wbw
    0,     // w.w.wbw
    -27,   // .bw.wbw
    1,     // bbw.wbw
    12,    // wbw.wbw
    3,     // .ww.wbw
    15,    // bww.wbw
    13,    // www.wbw
    4,     // ...bwbw
    -2,    // b..bwbw
    18,    // w..bwbw
    3,     // .b.bwbw
    -24,   // bb.bwbw
    5,     // wb.bwbw
    19,    // .w.bwbw
    -2,    // bw.bwbw
    -29,   // ww.bwbw
    -23,   // ..bbwbw
    1,     // b.bbwbw
    18,    // w.bbwbw
    -13,   // .bbbwbw
    -25,   // bbbbwbw
    -28,   // wbbbwbw
    -14,   // .wbbwbw
    -8,    // bwbbwbw
    3,     // wwbbwbw
    -13,   // ..wbwbw
    3,     // b.wbwbw
    9,     // w.wbwbw
    16,    // .bwbwbw
    -8,    // bbwbwbw
    -9,    // wbwbwbw
    9,     // .wwbwbw
    5,     // bwwbwbw
    30,    // wwwbwbw
    -6,    // ...wwbw
    14,    // b..wwbw
    7,     // w..wwbw
    46,    // .b.wwbw
    11,    // bb.wwbw
    1,     // wb.wwbw
    -18,   // .w.wwbw
    2,     // bw.wwbw
    -8,    // ww.wwbw
    42,    // ..bwwbw
    1,     // b.bwwbw
    -12,   // w.bwwbw
    9,     // .bbwwbw
    9,     // bbbwwbw
    -9,    // wbbwwbw
    1,     // .wbwwbw
    8,     // bwbwwbw
    8,     // wwbwwbw
    21,    // ..wwwbw
    -8,    // b.wwwbw
    -8,    // w.wwwbw
    14,    // .bwwwbw
    -6,    // bbwwwbw
    26,    // wbwwwbw
    -31,   // .wwwwbw
    -20,   // bwwwwbw
    2,     // wwwwwbw
    -28,   // .....ww
    13,    // b....ww
    -17,   // w....ww
    9,     // .b...ww
    0,     // bb...ww
    5,     // wb...ww
    -32,   // .w...ww
    -27,   // bw...ww
    25,    // ww...ww
    -15,   // ..b..ww
    -32,   // b.b..ww
    -24,   // w.b..ww
    7,     // .bb..ww
    -3,    // bbb..ww
    -17,   // wbb..ww
    14,    // .wb..ww
    -16,   // bwb..ww
    -6,    // wwb..ww
    13,    // ..w..ww
    -5,    // b.w..ww
    23,    // w.w..ww
    -14,   // .bw..ww
    -8,    // bbw..ww
    24,    // wbw..ww
    -3,    // .ww..ww
    19,    // bww..ww
    -62,   // www..ww
    -14,   // ...b.ww
    -1,    // b..b.ww
    -10,   // w..b.ww
    -25,   // .b.b.ww
    4,     // bb.b.ww
    25,    // wb.b.ww
    4,     // .w.b.ww
    -1,    // bw.b.ww
    -28,   // ww.b.ww
    18,    // ..bb.ww
    2,     // b.bb.ww
    -6,    // w.bb.ww
    -14,   // .bbb.ww
    -1,    // bbbb.ww
    -4,    // wbbb.ww
    15,    // .wbb.ww
    -11,   // bwbb.ww
    -8,    // wwbb.ww
    2,     // ..wb.ww
    -4,    // b.wb.ww
    -18,   // w.wb.ww
    -15,   // .bwb.ww
    2,     // bbwb.ww
    -29,   // wbwb.ww
    -20,   // .wwb.ww
    -2,    // bwwb.ww
    29,    // wwwb.ww
    11,    // ...w.ww
    -34,   // b..w.ww
    -2,    // w..w.ww
    2,     // .b.w.ww
    -4,    // bb.w.ww
    0,     // wb.w.ww
    -3,    // .w.w.ww
    22,    // bw.w.ww
    31,    // ww.w.ww
    -3,    // ..bw.ww
    40,    // b.bw.ww
    -5,    // w.bw.ww
    -6,    // .bbw.ww
    -21,   // bbbw.ww
    -4,    // wbbw.ww
    0,     // .wbw.ww
    24,    // bwbw.ww
    -44,   // wwbw.ww
    -11,   // ..ww.ww
    -33,   // b.ww.ww
    -21,   // w.ww.ww
    0,     // .bww.ww
    -6,    // bbww.ww
    -8,    // wbww.ww
    1,     // .www.ww
    -6,    // bwww.ww
    -11,   // wwww.ww
    -20,   // ....bww
    -20,   // b...bww
    15,    // w...bww
    27,    // .b..bww
    8,     // bb..bww
    22,    // wb..bww
    29,    // .w..bww
    -2,    // bw..bww
    -6,    // ww..bww
    11,    // ..b.bww
    12,    // b.b.bww
    -20,   // w.b.bww
    -14,   // .bb.bww
    27,    // bbb.bww
    1,     // wbb.bww
    -18,   // .wb.bww
    -1,    // bwb.bww
    -24,   // wwb.bww
    12,    // ..w.bww
    -20,   // b.w.bww
    7,     // w.w.bww
    23,    // .bw.bww
    0,     // bbw.bww
    0,     // wbw.bww
    -1,    // .ww.bww
    -26,   // bww.bww
    -8,    // www.bww
    26,    // ...bbww
    4,     // b..bbww
    10,    // w..bbww
    -37,   // .b.bbww
    6,     // bb.bbww
    -55,   // wb.bbww
    31,    // .w.bbww
    -6,    // bw.bbww
    -8,    // ww.bbww
    2,     // ..bbbww
    -16,   // b.bbbww
    -16,   // w.bbbww
    28,    // .bbbbww
    -1,    // bbbbbww
    3,     // wbbbbww
    -9,    // .wbbbww
    6,     // bwbbbww
    3,     // wwbbbww
    -9,    // ..wbbww
    -17,   // b.wbbww
    24,    // w.wbbww
    28,    // .bwbbww
    31,    // bbwbbww
    3,     // wbwbbww
    25,    // .wwbbww
    3,     // bwwbbww
    25,    // wwwbbww
    3,     // ...wbww
    10,    // b..wbww
    -19,   // w..wbww
    26,    // .b.wbww
    -2,    // bb.wbww
    33,    // wb.wbww
    3,     // .w.wbww
    4,     // bw.wbww
    -44,   // ww.wbww
    -17,   // ..bwbww
    -6,    // b.bwbww
    -15,   // w.bwbww
    14,    // .bbwbww
    7,     // bbbwbww
    10,    // wbbwbww
    -31,   // .wbwbww
    8,     // bwbwbww
    19,    // wwbwbww
    21,    // ..wwbww
    -26,   // b.wwbww
    -18,   // w.wwbww
    27,    // .bwwbww
    -31,   // bbwwbww
    8,     // wbwwbww
    19,    // .wwwbww
    34,    // bwwwbww
    -25,   // wwwwbww
    -68,   // ....www
    19,    // b...www
    37,    // w...www
    -35,   // .b..www
    3,     // bb..www
    -5,    // wb..www
    3,     // .w..www
    -3,    // bw..www
    -62,   // ww..www
    -5,    // ..b.www
    -14,   // b.b.www
    -24,   // w.b.www
    -37,   // .bb.www
    0,     // bbb.www
    17,    // wbb.www
    8,     // .wb.www
    16,    // bwb.www
    -8,    // wwb.www
    -13,   // ..w.www
    -1,    // b.w.www
    12,    // w.w.www
    -31,   // .bw.www
    -27,   // bbw.www
    13,    // wbw.www
    10,    // .ww.www
    -3,    // bww.www
    -41,   // www.www
    14,    // ...bwww
    -14,   // b..bwww
    4,     // w..bwww
    -16,   // .b.bwww
    21,    // bb.bwww
    12,    // wb.bwww
    2,     // .w.bwww
    12,    // bw.bwww
    29,    // ww.bwww
    -15,   // ..bbwww
    -32,   // b.bbwww
    3,     // w.bbwww
    0,     // .bbbwww
    1,     // bbbbwww
    -7,    // wbbbwww
    18,    // .wbbwww
    -9,    // bwbbwww
    25,    // wwbbwww
    25,    // ..wbwww
    14,    // b.wbwww
    1,     // w.wbwww
    -41,   // .bwbwww
    -7,    // bbwbwww
    30,    // wbwbwww
    25,    // .wwbwww
    -10,   // bwwbwww
    18,    // wwwbwww
    -125,  // ...wwww
    4,     // b..wwww
    -12,   // w..wwww
    -7,    // .b.wwww
    1,     // bb.wwww
    -9,    // wb.wwww
    -30,   // .w.wwww
    35,    // bw.wwww
    -11,   // ww.wwww
    -30,   // ..bwwww
    12,    // b.bwwww
    16,    // w.bwwww
    -4,    // .bbwwww
    -1,    // bbbwwww
    -4,    // wbbwwww
    -8,    // .wbwwww
    25,    // bwbwwww
    -25,   // wwbwwww
    -21,   // ..wwwww
    -11,   // b.wwwww
    -8,    // w.wwwww
    -7,    // .bwwwww
    1,     // bbwwwww
    2,     // wbwwwww
    -13,   // .wwwwww
    -27,   // bwwwwww
    -59,   // wwwwwww
    0,     // captures=0 threats=0
    15,    // captures=0 threats=1
    44,    // captures=0 threats=2
    51,    // captures=0 threats=3
    65,    // captures=0 threats=4
    6,     // captures=0 additional threats
    6,     // captures=1 threats=0
    40,    // captures=1 threats=1
    51,    // captures=1 threats=2
    73,    // captures=1 threats=3
    85,    // captures=1 threats=4
    39,    // captures=1 additional threats
    9,     // captures=2 threats=0
    45,    // captures=2 threats=1
    71,    // captures=2 threats=2
    77,    // captures=2 threats=3
    86,    // captures=2 threats=4
    21,    // captures=2 additional threats
    28,    // captures=3 threats=0
    79,    // captures=3 threats=1
    84,    // captures=3 threats=2
    87,    // captures=3 threats=3
    98,    // captures=3 threats=4
    42,    // captures=3 additional threats
    51,    // captures=4 threats=0
    81,    // captures=4 threats=1
    92,    // captures=4 threats=2
    94,    // captures=4 threats=3
    104,   // captures=4 threats=4
    4,     // captures=4 additional threats
].into_boxed_slice()
