vec![
    0,     // .......
    16,    // b......
    -16,   // w......
    -3,    // .b.....
    44,    // bb.....
    -16,   // wb.....
    3,     // .w.....
    16,    // bw.....
    -44,   // ww.....
    18,    // ..b....
    73,    // b.b....
    -18,   // w.b....
    16,    // .bb....
    71,    // bbb....
    -109,  // wbb....
    -32,   // .wb....
    50,    // bwb....
    72,    // wwb....
    -18,   // ..w....
    18,    // b.w....
    -73,   // w.w....
    32,    // .bw....
    -72,   // bbw....
    -50,   // wbw....
    -16,   // .ww....
    109,   // bww....
    -71,   // www....
    -25,   // ...b...
    -16,   // b..b...
    -13,   // w..b...
    9,     // .b.b...
    122,   // bb.b...
    -64,   // wb.b...
    17,    // .w.b...
    -18,   // bw.b...
    -48,   // ww.b...
    -8,    // ..bb...
    94,    // b.bb...
    -23,   // w.bb...
    208,   // .bbb...
    642,   // bbbb...
    -91,   // wbbb...
    48,    // .wbb...
    -15,   // bwbb...
    9,     // wwbb...
    2,     // ..wb...
    64,    // b.wb...
    -75,   // w.wb...
    -34,   // .bwb...
    -86,   // bbwb...
    -4,    // wbwb...
    -9,    // .wwb...
    37,    // bwwb...
    -113,  // wwwb...
    25,    // ...w...
    13,    // b..w...
    16,    // w..w...
    -17,   // .b.w...
    48,    // bb.w...
    18,    // wb.w...
    -9,    // .w.w...
    64,    // bw.w...
    -122,  // ww.w...
    -2,    // ..bw...
    75,    // b.bw...
    -64,   // w.bw...
    9,     // .bbw...
    113,   // bbbw...
    -37,   // wbbw...
    34,    // .wbw...
    4,     // bwbw...
    86,    // wwbw...
    8,     // ..ww...
    23,    // b.ww...
    -94,   // w.ww...
    -48,   // .bww...
    -9,    // bbww...
    15,    // wbww...
    -208,  // .www...
    91,    // bwww...
    -642,  // wwww...
    18,    // ....b..
    37,    // b...b..
    -81,   // w...b..
    30,    // .b..b..
    -41,   // bb..b..
    17,    // wb..b..
    -1,    // .w..b..
    -56,   // bw..b..
    26,    // ww..b..
    -12,   // ..b.b..
    -20,   // b.b.b..
    -26,   // w.b.b..
    -22,   // .bb.b..
    184,   // bbb.b..
    -130,  // wbb.b..
    -19,   // .wb.b..
    -69,   // bwb.b..
    -34,   // wwb.b..
    0,     // ..w.b..
    -15,   // b.w.b..
    -66,   // w.w.b..
    -23,   // .bw.b..
    -56,   // bbw.b..
    -67,   // wbw.b..
    20,    // .ww.b..
    -39,   // bww.b..
    -42,   // www.b..
    -8,    // ...bb..
    27,    // b..bb..
    -31,   // w..bb..
    20,    // .b.bb..
    47,    // bb.bb..
    1,     // wb.bb..
    -53,   // .w.bb..
    2,     // bw.bb..
    -47,   // ww.bb..
    23,    // ..bbb..
    101,   // b.bbb..
    -11,   // w.bbb..
    306,   // .bbbb..
    79,    // bbbbb..
    13,    // wbbbb..
    -59,   // .wbbb..
    -48,   // bwbbb..
    3,     // wwbbb..
    -89,   // ..wbb..
    -54,   // b.wbb..
    -30,   // w.wbb..
    -43,   // .bwbb..
    -10,   // bbwbb..
    73,    // wbwbb..
    59,    // .wwbb..
    -109,  // bwwbb..
    -95,   // wwwbb..
    -2,    // ...wb..
    101,   // b..wb..
    58,    // w..wb..
    6,     // .b.wb..
    -32,   // bb.wb..
    7,     // wb.wb..
    19,    // .w.wb..
    40,    // bw.wb..
    20,    // ww.wb..
    10,    // ..bwb..
    10,    // b.bwb..
    -12,   // w.bwb..
    -55,   // .bbwb..
    -147,  // bbbwb..
    6,     // wbbwb..
    1,     // .wbwb..
    -35,   // bwbwb..
    14,    // wwbwb..
    89,    // ..wwb..
    62,    // b.wwb..
    79,    // w.wwb..
    99,    // .bwwb..
    -9,    // bbwwb..
    -5,    // wbwwb..
    -95,   // .wwwb..
    37,    // bwwwb..
    -119,  // wwwwb..
    -18,   // ....w..
    81,    // b...w..
    -37,   // w...w..
    1,     // .b..w..
    -26,   // bb..w..
    56,    // wb..w..
    -30,   // .w..w..
    -17,   // bw..w..
    41,    // ww..w..
    0,     // ..b.w..
    66,    // b.b.w..
    15,    // w.b.w..
    -20,   // .bb.w..
    42,    // bbb.w..
    39,    // wbb.w..
    23,    // .wb.w..
    67,    // bwb.w..
    56,    // wwb.w..
    12,    // ..w.w..
    26,    // b.w.w..
    20,    // w.w.w..
    19,    // .bw.w..
    34,    // bbw.w..
    69,    // wbw.w..
    22,    // .ww.w..
    130,   // bww.w..
    -184,  // www.w..
    2,     // ...bw..
    -58,   // b..bw..
    -101,  // w..bw..
    -19,   // .b.bw..
    -20,   // bb.bw..
    -40,   // wb.bw..
    -6,    // .w.bw..
    -7,    // bw.bw..
    32,    // ww.bw..
    -89,   // ..bbw..
    -79,   // b.bbw..
    -62,   // w.bbw..
    95,    // .bbbw..
    119,   // bbbbw..
    -37,   // wbbbw..
    -99,   // .wbbw..
    5,     // bwbbw..
    9,     // wwbbw..
    -10,   // ..wbw..
    12,    // b.wbw..
    -10,   // w.wbw..
    -1,    // .bwbw..
    -14,   // bbwbw..
    35,    // wbwbw..
    55,    // .wwbw..
    -6,    // bwwbw..
    147,   // wwwbw..
    8,     // ...ww..
    31,    // b..ww..
    -27,   // w..ww..
    53,    // .b.ww..
    47,    // bb.ww..
    -2,    // wb.ww..
    -20,   // .w.ww..
    -1,    // bw.ww..
    -47,   // ww.ww..
    89,    // ..bww..
    30,    // b.bww..
    54,    // w.bww..
    -59,   // .bbww..
    95,    // bbbww..
    109,   // wbbww..
    43,    // .wbww..
    -73,   // bwbww..
    10,    // wwbww..
    -23,   // ..www..
    11,    // b.www..
    -101,  // w.www..
    59,    // .bwww..
    -3,    // bbwww..
    48,    // wbwww..
    -306,  // .wwww..
    -13,   // bwwww..
    -79,   // wwwww..
    -3,    // .....b.
    -33,   // b....b.
    -79,   // w....b.
    -41,   // .b...b.
    -39,   // bb...b.
    23,    // wb...b.
    0,     // .w...b.
    -58,   // bw...b.
    9,     // ww...b.
    30,    // ..b..b.
    56,    // b.b..b.
    -59,   // w.b..b.
    52,    // .bb..b.
    16,    // bbb..b.
    106,   // wbb..b.
    21,    // .wb..b.
    -68,   // bwb..b.
    32,    // wwb..b.
    1,     // ..w..b.
    -20,   // b.w..b.
    -33,   // w.w..b.
    25,    // .bw..b.
    -21,   // bbw..b.
    -31,   // wbw..b.
    -26,   // .ww..b.
    24,    // bww..b.
    -87,   // www..b.
    9,     // ...b.b.
    -37,   // b..b.b.
    -32,   // w..b.b.
    6,     // .b.b.b.
    -90,   // bb.b.b.
    4,     // wb.b.b.
    -26,   // .w.b.b.
    0,     // bw.b.b.
    -28,   // ww.b.b.
    20,    // ..bb.b.
    11,    // b.bb.b.
    118,   // w.bb.b.
    62,    // .bbb.b.
    -70,   // bbbb.b.
    98,    // wbbb.b.
    -28,   // .wbb.b.
    -51,   // bwbb.b.
    -2,    // wwbb.b.
    -19,   // ..wb.b.
    -11,   // b.wb.b.
    -44,   // w.wb.b.
    32,    // .bwb.b.
    36,    // bbwb.b.
    21,    // wbwb.b.
    75,    // .wwb.b.
    -73,   // bwwb.b.
    41,    // wwwb.b.
    -17,   // ...w.b.
    -76,   // b..w.b.
    4,     // w..w.b.
    29,    // .b.w.b.
    -32,   // bb.w.b.
    -89,   // wb.w.b.
    26,    // .w.w.b.
    116,   // bw.w.b.
    -132,  // ww.w.b.
    6,     // ..bw.b.
    57,    // b.bw.b.
    52,    // w.bw.b.
    5,     // .bbw.b.
    -110,  // bbbw.b.
    -96,   // wbbw.b.
    32,    // .wbw.b.
    -3,    // bwbw.b.
    54,    // wwbw.b.
    53,    // ..ww.b.
    -3,    // b.ww.b.
    29,    // w.ww.b.
    54,    // .bww.b.
    -7,    // bbww.b.
    142,   // wbww.b.
    -91,   // .www.b.
    41,    // bwww.b.
    -259,  // wwww.b.
    16,    // ....bb.
    -8,    // b...bb.
    24,    // w...bb.
    52,    // .b..bb.
    15,    // bb..bb.
    1,     // wb..bb.
    26,    // .w..bb.
    -18,   // bw..bb.
    -95,   // ww..bb.
    -22,   // ..b.bb.
    27,    // b.b.bb.
    5,     // w.b.bb.
    37,    // .bb.bb.
    -19,   // bbb.bb.
    -11,   // wbb.bb.
    -98,   // .wb.bb.
    11,    // bwb.bb.
    -16,   // wwb.bb.
    -20,   // ..w.bb.
    4,     // b.w.bb.
    41,    // w.w.bb.
    -90,   // .bw.bb.
    45,    // bbw.bb.
    -128,  // wbw.bb.
    0,     // .ww.bb.
    84,    // bww.bb.
    -105,  // www.bb.
    208,   // ...bbb.
    -46,   // b..bbb.
    98,    // w..bbb.
    62,    // .b.bbb.
    20,    // bb.bbb.
    55,    // wb.bbb.
    91,    // .w.bbb.
    66,    // bw.bbb.
    -1,    // ww.bbb.
    306,   // ..bbbb.
    120,   // b.bbbb.
    85,    // w.bbbb.
    -57,   // .bbbbb.
    -78,   // bbbbbb.
    1,     // wbbbbb.
    56,    // .wbbbb.
    -62,   // bwbbbb.
    -2,    // wwbbbb.
    95,    // ..wbbb.
    11,    // b.wbbb.
    -80,   // w.wbbb.
    73,    // .bwbbb.
    -111,  // bbwbbb.
    89,    // wbwbbb.
    33,    // .wwbbb.
    7,     // bwwbbb.
    -39,   // wwwbbb.
    9,     // ...wbb.
    58,    // b..wbb.
    37,    // w..wbb.
    5,     // .b.wbb.
    82,    // bb.wbb.
    5,     // wb.wbb.
    -75,   // .w.wbb.
    -20,   // bw.wbb.
    -34,   // ww.wbb.
    -55,   // ..bwbb.
    -85,   // b.bwbb.
    -93,   // w.bwbb.
    -56,   // .bbwbb.
    -68,   // bbbwbb.
    -84,   // wbbwbb.
    34,    // .wbwbb.
    -55,   // bwbwbb.
    128,   // wwbwbb.
    -59,   // ..wwbb.
    -3,    // b.wwbb.
    -30,   // w.wwbb.
    -42,   // .bwwbb.
    -60,   // bbwwbb.
    -36,   // wbwwbb.
    -33,   // .wwwbb.
    98,    // bwwwbb.
    52,    // wwwwbb.
    32,    // ....wb.
    6,     // b...wb.
    86,    // w...wb.
    25,    // .b..wb.
    -9,    // bb..wb.
    -94,   // wb..wb.
    -21,   // .w..wb.
    -103,  // bw..wb.
    -111,  // ww..wb.
    -23,   // ..b.wb.
    -51,   // b.b.wb.
    -28,   // w.b.wb.
    -90,   // .bb.wb.
    -11,   // bbb.wb.
    -48,   // wbb.wb.
    0,     // .wb.wb.
    45,    // bwb.wb.
    15,    // wwb.wb.
    19,    // ..w.wb.
    -36,   // b.w.wb.
    95,    // w.w.wb.
    67,    // .bw.wb.
    -24,   // bbw.wb.
    1,     // wbw.wb.
    98,    // .ww.wb.
    -57,   // bww.wb.
    8,     // www.wb.
    -34,   // ...bwb.
    32,    // b..bwb.
    68,    // w..bwb.
    32,    // .b.bwb.
    -32,   // bb.bwb.
    -40,   // wb.bwb.
    -32,   // .w.bwb.
    -20,   // bw.bwb.
    -36,   // ww.bwb.
    -43,   // ..bbwb.
    -39,   // b.bbwb.
    -18,   // w.bbwb.
    73,    // .bbbwb.
    -112,  // bbbbwb.
    -19,   // wbbbwb.
    14,    // .wbbwb.
    -107,  // bwbbwb.
    70,    // wwbbwb.
    -1,    // ..wbwb.
    -37,   // b.wbwb.
    1,     // w.wbwb.
    -12,   // .bwbwb.
    -4,    // bbwbwb.
    -59,   // wbwbwb.
    -34,   // .wwbwb.
    102,   // bwwbwb.
    29,    // wwwbwb.
    -48,   // ...wwb.
    26,    // b..wwb.
    11,    // w..wwb.
    54,    // .b.wwb.
    -32,   // bb.wwb.
    31,    // wb.wwb.
    28,    // .w.wwb.
    82,    // bw.wwb.
    -94,   // ww.wwb.
    99,    // ..bwwb.
    -69,   // b.bwwb.
    -31,   // w.bwwb.
    -42,   // .bbwwb.
    -4,    // bbbwwb.
    -90,   // wbbwwb.
    -14,   // .wbwwb.
    -117,  // bwbwwb.
    -21,   // wwbwwb.
    59,    // ..wwwb.
    144,   // b.wwwb.
    -206,  // w.wwwb.
    -19,   // .bwwwb.
    81,    // bbwwwb.
    -1,    // wbwwwb.
    -56,   // .wwwwb.
    223,   // bwwwwb.
    -293,  // wwwwwb.
    3,     // .....w.
    79,    // b....w.
    33,    // w....w.
    0,     // .b...w.
    -9,    // bb...w.
    58,    // wb...w.
    41,    // .w...w.
    -23,   // bw...w.
    39,    // ww...w.
    -1,    // ..b..w.
    33,    // b.b..w.
    20,    // w.b..w.
    26,    // .bb..w.
    87,    // bbb..w.
    -24,   // wbb..w.
    -25,   // .wb..w.
    31,    // bwb..w.
    21,    // wwb..w.
    -30,   // ..w..w.
    59,    // b.w..w.
    -56,   // w.w..w.
    -21,   // .bw..w.
    -32,   // bbw..w.
    68,    // wbw..w.
    -52,   // .ww..w.
    -106,  // bww..w.
    -16,   // www..w.
    17,    // ...b.w.
    -4,    // b..b.w.
    76,    // w..b.w.
    -26,   // .b.b.w.
    132,   // bb.b.w.
    -116,  // wb.b.w.
    -29,   // .w.b.w.
    89,    // bw.b.w.
    32,    // ww.b.w.
    -53,   // ..bb.w.
    -29,   // b.bb.w.
    3,     // w.bb.w.
    91,    // .bbb.w.
    259,   // bbbb.w.
    -41,   // wbbb.w.
    -54,   // .wbb.w.
    -142,  // bwbb.w.
    7,     // wwbb.w.
    -6,    // ..wb.w.
    -52,   // b.wb.w.
    -57,   // w.wb.w.
    -32,   // .bwb.w.
    -54,   // bbwb.w.
    3,     // wbwb.w.
    -5,    // .wwb.w.
    96,    // bwwb.w.
    110,   // wwwb.w.
    -9,    // ...w.w.
    32,    // b..w.w.
    37,    // w..w.w.
    26,    // .b.w.w.
    28,    // bb.w.w.
    0,     // wb.w.w.
    -6,    // .w.w.w.
    -4,    // bw.w.w.
    90,    // ww.w.w.
    19,    // ..bw.w.
    44,    // b.bw.w.
    11,    // w.bw.w.
    -75,   // .bbw.w.
    -41,   // bbbw.w.
    73,    // wbbw.w.
    -32,   // .wbw.w.
    -21,   // bwbw.w.
    -36,   // wwbw.w.
    -20,   // ..ww.w.
    -118,  // b.ww.w.
    -11,   // w.ww.w.
    28,    // .bww.w.
    2,     // bbww.w.
    51,    // wbww.w.
    -62,   // .www.w.
    -98,   // bwww.w.
    70,    // wwww.w.
    -32,   // ....bw.
    -86,   // b...bw.
    -6,    // w...bw.
    21,    // .b..bw.
    111,   // bb..bw.
    103,   // wb..bw.
    -25,   // .w..bw.
    94,    // bw..bw.
    9,     // ww..bw.
    -19,   // ..b.bw.
    -95,   // b.b.bw.
    36,    // w.b.bw.
    -98,   // .bb.bw.
    -8,    // bbb.bw.
    57,    // wbb.bw.
    -67,   // .wb.bw.
    -1,    // bwb.bw.
    24,    // wwb.bw.
    23,    // ..w.bw.
    28,    // b.w.bw.
    51,    // w.w.bw.
    0,     // .bw.bw.
    -15,   // bbw.bw.
    -45,   // wbw.bw.
    90,    // .ww.bw.
    48,    // bww.bw.
    11,    // www.bw.
    48,    // ...bbw.
    -11,   // b..bbw.
    -26,   // w..bbw.
    -28,   // .b.bbw.
    94,    // bb.bbw.
    -82,   // wb.bbw.
    -54,   // .w.bbw.
    -31,   // bw.bbw.
    32,    // ww.bbw.
    -59,   // ..bbbw.
    206,   // b.bbbw.
    -144,  // w.bbbw.
    56,    // .bbbbw.
    293,   // bbbbbw.
    -223,  // wbbbbw.
    19,    // .wbbbw.
    1,     // bwbbbw.
    -81,   // wwbbbw.
    -99,   // ..wbbw.
    31,    // b.wbbw.
    69,    // w.wbbw.
    14,    // .bwbbw.
    21,    // bbwbbw.
    117,   // wbwbbw.
    42,    // .wwbbw.
    90,    // bwwbbw.
    4,     // wwwbbw.
    34,    // ...wbw.
    -68,   // b..wbw.
    -32,   // w..wbw.
    32,    // .b.wbw.
    36,    // bb.wbw.
    20,    // wb.wbw.
    -32,   // .w.wbw.
    40,    // bw.wbw.
    32,    // ww.wbw.
    1,     // ..bwbw.
    -1,    // b.bwbw.
    37,    // w.bwbw.
    34,    // .bbwbw.
    -29,   // bbbwbw.
    -102,  // wbbwbw.
    12,    // .wbwbw.
    59,    // bwbwbw.
    4,     // wwbwbw.
    43,    // ..wwbw.
    18,    // b.wwbw.
    39,    // w.wwbw.
    -14,   // .bwwbw.
    -70,   // bbwwbw.
    107,   // wbwwbw.
    -73,   // .wwwbw.
    19,    // bwwwbw.
    112,   // wwwwbw.
    -16,   // ....ww.
    -24,   // b...ww.
    8,     // w...ww.
    -26,   // .b..ww.
    95,    // bb..ww.
    18,    // wb..ww.
    -52,   // .w..ww.
    -1,    // bw..ww.
    -15,   // ww..ww.
    20,    // ..b.ww.
    -41,   // b.b.ww.
    -4,    // w.b.ww.
    0,     // .bb.ww.
    105,   // bbb.ww.
    -84,   // wbb.ww.
    90,    // .wb.ww.
    128,   // bwb.ww.
    -45,   // wwb.ww.
    22,    // ..w.ww.
    -5,    // b.w.ww.
    -27,   // w.w.ww.
    98,    // .bw.ww.
    16,    // bbw.ww.
    -11,   // wbw.ww.
    -37,   // .ww.ww.
    11,    // bww.ww.
    19,    // www.ww.
    -9,    // ...bww.
    -37,   // b..bww.
    -58,   // w..bww.
    75,    // .b.bww.
    34,    // bb.bww.
    20,    // wb.bww.
    -5,    // .w.bww.
    -5,    // bw.bww.
    -82,   // ww.bww.
    59,    // ..bbww.
    30,    // b.bbww.
    3,     // w.bbww.
    33,    // .bbbww.
    -52,   // bbbbww.
    -98,   // wbbbww.
    42,    // .wbbww.
    36,    // bwbbww.
    60,    // wwbbww.
    55,    // ..wbww.
    93,    // b.wbww.
    85,    // w.wbww.
    -34,   // .bwbww.
    -128,  // bbwbww.
    55,    // wbwbww.
    56,    // .wwbww.
    84,    // bwwbww.
    68,    // wwwbww.
    -208,  // ...www.
    -98,   // b..www.
    46,    // w..www.
    -91,   // .b.www.
    1,     // bb.www.
    -66,   // wb.www.
    -62,   // .w.www.
    -55,   // bw.www.
    -20,   // ww.www.
    -95,   // ..bwww.
    80,    // b.bwww.
    -11,   // w.bwww.
    -33,   // .bbwww.
    39,    // bbbwww.
    -7,    // wbbwww.
    -73,   // .wbwww.
    -89,   // bwbwww.
    111,   // wwbwww.
    -306,  // ..wwww.
    -85,   // b.wwww.
    -120,  // w.wwww.
    -56,   // .bwwww.
    2,     // bbwwww.
    62,    // wbwwww.
    57,    // .wwwww.
    -1,    // bwwwww.
    78,    // wwwwww.
    16,    // ......b
    20,    // b.....b
    0,     // w.....b
    -33,   // .b....b
    -30,   // bb....b
    9,     // wb....b
    79,    // .w....b
    6,     // bw....b
    -34,   // ww....b
    37,    // ..b...b
    4,     // b.b...b
    -92,   // w.b...b
    -8,    // .bb...b
    -101,  // bbb...b
    -115,  // wbb...b
    -86,   // .wb...b
    20,    // bwb...b
    10,    // wwb...b
    81,    // ..w...b
    0,     // b.w...b
    79,    // w.w...b
    6,     // .bw...b
    -54,   // bbw...b
    -32,   // wbw...b
    -24,   // .ww...b
    -28,   // bww...b
    -102,  // www...b
    -16,   // ...b..b
    -55,   // b..b..b
    27,    // w..b..b
    -37,   // .b.b..b
    -44,   // bb.b..b
    -97,   // wb.b..b
    -4,    // .w.b..b
    -13,   // bw.b..b
    98,    // ww.b..b
    27,    // ..bb..b
    -38,   // b.bb..b
    -21,   // w.bb..b
    -46,   // .bbb..b
    6,     // bbbb..b
    -106,  // wbbb..b
    -11,   // .wbb..b
    100,   // bwbb..b
    -67,   // wwbb..b
    -58,   // ..wb..b
    -57,   // b.wb..b
    14,    // w.wb..b
    32,    // .bwb..b
    -91,   // bbwb..b
    -75,   // wbwb..b
    -37,   // .wwb..b
    -78,   // bwwb..b
    32,    // wwwb..b
    13,    // ...w..b
    -14,   // b..w..b
    -27,   // w..w..b
    -76,   // .b.w..b
    64,    // bb.w..b
    -26,   // wb.w..b
    32,    // .w.w..b
    -71,   // bw.w..b
    85,    // ww.w..b
    101,   // ..bw..b
    67,    // b.bw..b
    23,    // w.bw..b
    58,    // .bbw..b
    68,    // bbbw..b
    -55,   // wbbw..b
    -68,   // .wbw..b
    -35,   // bwbw..b
    -7,    // wwbw..b
    31,    // ..ww..b
    -4,    // b.ww..b
    50,    // w.ww..b
    26,    // .bww..b
    -61,   // bbww..b
    96,    // wbww..b
    -98,   // .www..b
    -24,   // bwww..b
    -84,   // wwww..b
    73,    // ....b.b
    4,     // b...b.b
    -79,   // w...b.b
    56,    // .b..b.b
    -86,   // bb..b.b
    145,   // wb..b.b
    33,    // .w..b.b
    32,    // bw..b.b
    32,    // ww..b.b
    -20,   // ..b.b.b
    40,    // b.b.b.b
    82,    // w.b.b.b
    27,    // .bb.b.b
    36,    // bbb.b.b
    20,    // wbb.b.b
    -95,   // .wb.b.b
    12,    // bwb.b.b
    -18,   // wwb.b.b
    66,    // ..w.b.b
    16,    // b.w.b.b
    0,     // w.w.b.b
    -51,   // .bw.b.b
    41,    // bbw.b.b
    28,    // wbw.b.b
    -41,   // .ww.b.b
    161,   // bww.b.b
    23,    // www.b.b
    94,    // ...bb.b
    -38,   // b..bb.b
    -50,   // w..bb.b
    11,    // .b.bb.b
    -31,   // bb.bb.b
    -72,   // wb.bb.b
    -29,   // .w.bb.b
    -24,   // bw.bb.b
    -2,    // ww.bb.b
    101,   // ..bbb.b
    49,    // b.bbb.b
    -36,   // w.bbb.b
    120,   // .bbbb.b
    -79,   // bbbbb.b
    -34,   // wbbbb.b
    206,   // .wbbb.b
    -80,   // bwbbb.b
    10,    // wwbbb.b
    -79,   // ..wbb.b
    3,     // b.wbb.b
    95,    // w.wbb.b
    -39,   // .bwbb.b
    -64,   // bbwbb.b
    17,    // wbwbb.b
    30,    // .wwbb.b
    -66,   // bwwbb.b
    80,    // wwwbb.b
    75,    // ...wb.b
    67,    // b..wb.b
    -14,   // w..wb.b
    57,    // .b.wb.b
    -6,    // bb.wb.b
    0,     // wb.wb.b
    44,    // .w.wb.b
    32,    // bw.wb.b
    37,    // ww.wb.b
    10,    // ..bwb.b
    30,    // b.bwb.b
    -2,    // w.bwb.b
    -85,   // .bbwb.b
    -53,   // bbbwb.b
    4,     // wbbwb.b
    -1,    // .wbwb.b
    28,    // bwbwb.b
    109,   // wwbwb.b
    30,    // ..wwb.b
    -18,   // b.wwb.b
    -95,   // w.wwb.b
    -69,   // .bwwb.b
    -48,   // bbwwb.b
    44,    // wbwwb.b
    80,    // .wwwb.b
    -29,   // bwwwb.b
    15,    // wwwwb.b
    18,    // ....w.b
    0,     // b...w.b
    92,    // w...w.b
    -20,   // .b..w.b
    -20,   // bb..w.b
    131,   // wb..w.b
    59,    // .w..w.b
    83,    // bw..w.b
    -22,   // ww..w.b
    -15,   // ..b.w.b
    16,    // b.b.w.b
    0,     // w.b.w.b
    4,     // .bb.w.b
    -30,   // bbb.w.b
    -45,   // wbb.w.b
    28,    // .wb.w.b
    41,    // bwb.w.b
    -10,   // wwb.w.b
    26,    // ..w.w.b
    64,    // b.w.w.b
    -82,   // w.w.w.b
    -36,   // .bw.w.b
    -101,  // bbw.w.b
    57,    // wbw.w.b
    -5,    // .ww.w.b
    40,    // bww.w.b
    -12,   // www.w.b
    64,    // ...bw.b
    -57,   // b..bw.b
    -23,   // w..bw.b
    -11,   // .b.bw.b
    63,    // bb.bw.b
    -18,   // wb.bw.b
    -52,   // .w.bw.b
    32,    // bw.bw.b
    -36,   // ww.bw.b
    -54,   // ..bbw.b
    3,     // b.bbw.b
    29,    // w.bbw.b
    11,    // .bbbw.b
    96,    // bbbbw.b
    -24,   // wbbbw.b
    31,    // .wbbw.b
    100,   // bwbbw.b
    -3,    // wwbbw.b
    12,    // ..wbw.b
    -50,   // b.wbw.b
    2,     // w.wbw.b
    -37,   // .bwbw.b
    0,     // bbwbw.b
    -39,   // wbwbw.b
    93,    // .wwbw.b
    67,    // bwwbw.b
    -46,   // wwwbw.b
    23,    // ...ww.b
    -4,    // b..ww.b
    21,    // w..ww.b
    -3,    // .b.ww.b
    2,     // bb.ww.b
    86,    // wb.ww.b
    -118,  // .w.ww.b
    -20,   // bw.ww.b
    5,     // ww.ww.b
    62,    // ..bww.b
    -18,   // b.bww.b
    -29,   // w.bww.b
    -3,    // .bbww.b
    106,   // bbbww.b
    40,    // wbbww.b
    18,    // .wbww.b
    74,    // bwbww.b
    -64,   // wwbww.b
    11,    // ..www.b
    -54,   // b.www.b
    36,    // w.www.b
    144,   // .bwww.b
    -58,   // bbwww.b
    0,     // wbwww.b
    -85,   // .wwww.b
    -4,    // bwwww.b
    -18,   // wwwww.b
    44,    // .....bb
    -30,   // b....bb
    34,    // w....bb
    -39,   // .b...bb
    14,    // bb...bb
    -50,   // wb...bb
    -9,    // .w...bb
    -27,   // bw...bb
    0,     // ww...bb
    -41,   // ..b..bb
    -86,   // b.b..bb
    22,    // w.b..bb
    15,    // .bb..bb
    146,   // bbb..bb
    -48,   // wbb..bb
    111,   // .wb..bb
    -56,   // bwb..bb
    29,    // wwb..bb
    -26,   // ..w..bb
    -20,   // b.w..bb
    -32,   // w.w..bb
    -9,    // .bw..bb
    -8,    // bbw..bb
    -15,   // wbw..bb
    95,    // .ww..bb
    -22,   // bww..bb
    -46,   // www..bb
    122,   // ...b.bb
    -44,   // b..b.bb
    -85,   // w..b.bb
    -90,   // .b.b.bb
    16,    // bb.b.bb
    79,    // wb.b.bb
    132,   // .w.b.bb
    -63,   // bw.b.bb
    35,    // ww.b.bb
    47,    // ..bb.bb
    -31,   // b.bb.bb
    -5,    // w.bb.bb
    20,    // .bbb.bb
    -35,   // bbbb.bb
    -6,    // wbbb.bb
    94,    // .wbb.bb
    31,    // bwbb.bb
    -122,  // wwbb.bb
    -20,   // ..wb.bb
    63,    // b.wb.bb
    -37,   // w.wb.bb
    -32,   // .bwb.bb
    -14,   // bbwb.bb
    -51,   // wbwb.bb
    34,    // .wwb.bb
    56,    // bwwb.bb
    43,    // wwwb.bb
    48,    // ...w.bb
    64,    // b..w.bb
    -98,   // w..w.bb
    -32,   // .b.w.bb
    72,    // bb.w.bb
    34,    // wb.w.bb
    28,    // .w.w.bb
    68,    // bw.w.bb
    -35,   // ww.w.bb
    -32,   // ..bw.bb
    -6,    // b.bw.bb
    36,    // w.bw.bb
    82,    // .bbw.bb
    65,    // bbbw.bb
    97,    // wbbw.bb
    36,    // .wbw.bb
    180,   // bwbw.bb
    58,    // wwbw.bb
    47,    // ..ww.bb
    2,     // b.ww.bb
    2,     // w.ww.bb
    -32,   // .bww.bb
    -23,   // bbww.bb
    36,    // wbww.bb
    1,     // .www.bb
    12,    // bwww.bb
    -42,   // wwww.bb
    71,    // ....bbb
    -101,  // b...bbb
    102,   // w...bbb
    16,    // .b..bbb
    146,   // bb..bbb
    -21,   // wb..bbb
    87,    // .w..bbb
    9,     // bw..bbb
    46,    // ww..bbb
    184,   // ..b.bbb
    36,    // b.b.bbb
    12,    // w.b.bbb
    -19,   // .bb.bbb
    27,    // bbb.bbb
    -18,   // wbb.bbb
    -8,    // .wb.bbb
    -62,   // bwb.bbb
    -85,   // wwb.bbb
    42,    // ..w.bbb
    -30,   // b.w.bbb
    -23,   // w.w.bbb
    -11,   // .bw.bbb
    73,    // bbw.bbb
    -62,   // wbw.bbb
    105,   // .ww.bbb
    -11,   // bww.bbb
    0,     // www.bbb
    642,   // ...bbbb
    6,     // b..bbbb
    84,    // w..bbbb
    -70,   // .b.bbbb
    -35,   // bb.bbbb
    70,    // wb.bbbb
    259,   // .w.bbbb
    102,   // bw.bbbb
    42,    // ww.bbbb
    79,    // ..bbbbb
    -79,   // b.bbbbb
    18,    // w.bbbbb
    -78,   // .bbbbbb
    -46,   // bbbbbbb
    -9,    // wbbbbbb
    293,   // .wbbbbb
    -17,   // bwbbbbb
    131,   // wwbbbbb
    119,   // ..wbbbb
    96,    // b.wbbbb
    -15,   // w.wbbbb
    -112,  // .bwbbbb
    -26,   // bbwbbbb
    80,    // wbwbbbb
    -52,   // .wwbbbb
    6,     // bwwbbbb
    -97,   // wwwbbbb
    113,   // ...wbbb
    68,    // b..wbbb
    -32,   // w..wbbb
    -110,  // .b.wbbb
    65,    // bb.wbbb
    -45,   // wb.wbbb
    -41,   // .w.wbbb
    39,    // bw.wbbb
    -43,   // ww.wbbb
    -147,  // ..bwbbb
    -53,   // b.bwbbb
    46,    // w.bwbbb
    -68,   // .bbwbbb
    -4,    // bbbwbbb
    -182,  // wbbwbbb
    -29,   // .wbwbbb
    35,    // bwbwbbb
    -25,   // wwbwbbb
    95,    // ..wwbbb
    106,   // b.wwbbb
    -80,   // w.wwbbb
    -4,    // .bwwbbb
    59,    // bbwwbbb
    -96,   // wbwwbbb
    39,    // .wwwbbb
    23,    // bwwwbbb
    97,    // wwwwbbb
    -72,   // ....wbb
    -54,   // b...wbb
    -10,   // w...wbb
    -21,   // .b..wbb
    -8,    // bb..wbb
    -8,    // wb..wbb
    -32,   // .w..wbb
    46,    // bw..wbb
    -29,   // ww..wbb
    -56,   // ..b.wbb
    41,    // b.b.wbb
    10,    // w.b.wbb
    45,    // .bb.wbb
    73,    // bbb.wbb
    7,     // wbb.wbb
    -15,   // .wb.wbb
    18,    // bwb.wbb
    0,     // wwb.wbb
    34,    // ..w.wbb
    -101,  // b.w.wbb
    18,    // w.w.wbb
    -24,   // .bw.wbb
    -70,   // bbw.wbb
    -74,   // wbw.wbb
    16,    // .ww.wbb
    -2,    // bww.wbb
    85,    // www.wbb
    -86,   // ...bwbb
    -91,   // b..bwbb
    7,     // w..bwbb
    36,    // .b.bwbb
    -14,   // bb.bwbb
    71,    // wb.bwbb
    -54,   // .w.bwbb
    -21,   // bw.bwbb
    -58,   // ww.bwbb
    -10,   // ..bbwbb
    -64,   // b.bbwbb
    64,    // w.bbwbb
    -111,  // .bbbwbb
    -26,   // bbbbwbb
    -17,   // wbbbwbb
    21,    // .wbbwbb
    1,     // bwbbwbb
    47,    // wwbbwbb
    -14,   // ..wbwbb
    0,     // b.wbwbb
    -109,  // w.wbwbb
    -4,    // .bwbwbb
    43,    // bbwbwbb
    126,   // wbwbwbb
    -128,  // .wwbwbb
    26,    // bwwbwbb
    25,    // wwwbwbb
    -9,    // ...wwbb
    -61,   // b..wwbb
    67,    // w..wwbb
    -7,    // .b.wwbb
    -23,   // bb.wwbb
    -10,   // wb.wwbb
    2,     // .w.wwbb
    98,    // bw.wwbb
    122,   // ww.wwbb
    -9,    // ..bwwbb
    -48,   // b.bwwbb
    3,     // w.bwwbb
    -60,   // .bbwwbb
    59,    // bbbwwbb
    9,     // wbbwwbb
    -70,   // .wbwwbb
    -26,   // bwbwwbb
    -47,   // wwbwwbb
    -3,    // ..wwwbb
    -58,   // b.wwwbb
    -10,   // w.wwwbb
    81,    // .bwwwbb
    -2,    // bbwwwbb
    5,     // wbwwwbb
    2,     // .wwwwbb
    -11,   // bwwwwbb
    -131,  // wwwwwbb
    16,    // .....wb
    6,     // b....wb
    -9,    // w....wb
    -58,   // .b...wb
    -27,   // bb...wb
    0,     // wb...wb
    -23,   // .w...wb
    -154,  // bw...wb
    50,    // ww...wb
    -56,   // ..b..wb
    32,    // b.b..wb
    -131,  // w.b..wb
    -18,   // .bb..wb
    9,     // bbb..wb
    23,    // wbb..wb
    94,    // .wb..wb
    -81,   // bwb..wb
    8,     // wwb..wb
    -17,   // ..w..wb
    83,    // b.w..wb
    -145,  // w.w..wb
    -103,  // .bw..wb
    46,    // bbw..wb
    -1,    // wbw..wb
    -1,    // .ww..wb
    -50,   // bww..wb
    21,    // www..wb
    -18,   // ...b.wb
    -13,   // b..b.wb
    26,    // w..b.wb
    0,     // .b.b.wb
    -63,   // bb.b.wb
    -52,   // wb.b.wb
    89,    // .w.b.wb
    36,    // bw.b.wb
    -34,   // ww.b.wb
    2,     // ..bb.wb
    -24,   // b.bb.wb
    -86,   // w.bb.wb
    66,    // .bbb.wb
    102,   // bbbb.wb
    -17,   // wbbb.wb
    -31,   // .wbb.wb
    -46,   // bwbb.wb
    10,    // wwbb.wb
    -7,    // ..wb.wb
    32,    // b.wb.wb
    0,     // w.wb.wb
    -20,   // .bwb.wb
    -21,   // bbwb.wb
    -17,   // wbwb.wb
    -5,    // .wwb.wb
    73,    // bwwb.wb
    45,    // wwwb.wb
    64,    // ...w.wb
    -71,   // b..w.wb
    97,    // w..w.wb
    116,   // .b.w.wb
    68,    // bb.w.wb
    52,    // wb.w.wb
    -4,    // .w.w.wb
    20,    // bw.w.wb
    -79,   // ww.w.wb
    40,    // ..bw.wb
    32,    // b.bw.wb
    18,    // w.bw.wb
    -20,   // .bbw.wb
    39,    // bbbw.wb
    -36,   // wbbw.wb
    40,    // .wbw.wb
    45,    // bwbw.wb
    -71,   // wwbw.wb
    -1,    // ..ww.wb
    -20,   // b.ww.wb
    72,    // w.ww.wb
    82,    // .bww.wb
    98,    // bbww.wb
    81,    // wbww.wb
    -55,   // .www.wb
    -58,   // bwww.wb
    -70,   // wwww.wb
    50,    // ....bwb
    20,    // b...bwb
    32,    // w...bwb
    -68,   // .b..bwb
    -56,   // bb..bwb
    1,     // wb..bwb
    31,    // .w..bwb
    -81,   // bw..bwb
    15,    // ww..bwb
    -69,   // ..b.bwb
    12,    // b.b.bwb
    -57,   // w.b.bwb
    11,    // .bb.bwb
    -62,   // bbb.bwb
    -28,   // wbb.bwb
    -1,    // .wb.bwb
    21,    // bwb.bwb
    74,    // wwb.bwb
    67,    // ..w.bwb
    41,    // b.w.bwb
    -28,   // w.w.bwb
    45,    // .bw.bwb
    18,    // bbw.bwb
    0,     // wbw.bwb
    128,   // .ww.bwb
    95,    // bww.bwb
    62,    // www.bwb
    -15,   // ...bbwb
    100,   // b..bbwb
    -96,   // w..bbwb
    -51,   // .b.bbwb
    31,    // bb.bbwb
    -81,   // wb.bbwb
    -142,  // .w.bbwb
    -46,   // bw.bbwb
    -36,   // ww.bbwb
    -48,   // ..bbbwb
    -80,   // b.bbbwb
    0,     // w.bbbwb
    -62,   // .bbbbwb
    -17,   // bbbbbwb
    -108,  // wbbbbwb
    1,     // .wbbbwb
    58,    // bwbbbwb
    -5,    // wwbbbwb
    5,     // ..wbbwb
    100,   // b.wbbwb
    -44,   // w.wbbwb
    -107,  // .bwbbwb
    1,     // bbwbbwb
    78,    // wbwbbwb
    36,    // .wwbbwb
    12,    // bwwbbwb
    96,    // wwwbbwb
    4,     // ...wbwb
    -35,   // b..wbwb
    75,    // w..wbwb
    -3,    // .b.wbwb
    180,   // bb.wbwb
    17,    // wb.wbwb
    -21,   // .w.wbwb
    45,    // bw.wbwb
    51,    // ww.wbwb
    -35,   // ..bwbwb
    28,    // b.bwbwb
    39,    // w.bwbwb
    -55,   // .bbwbwb
    35,    // bbbwbwb
    -46,   // wbbwbwb
    59,    // .wbwbwb
    -58,   // bwbwbwb
    -126,  // wwbwbwb
    -73,   // ..wwbwb
    74,    // b.wwbwb
    -17,   // w.wwbwb
    -117,  // .bwwbwb
    -26,   // bbwwbwb
    -78,   // wbwwbwb
    -89,   // .wwwbwb
    -97,   // bwwwbwb
    -80,   // wwwwbwb
    109,   // ....wwb
    -28,   // b...wwb
    115,   // w...wwb
    24,    // .b..wwb
    -22,   // bb..wwb
    -23,   // wb..wwb
    -106,  // .w..wwb
    -50,   // bw..wwb
    48,    // ww..wwb
    -39,   // ..b.wwb
    161,   // b.b.wwb
    45,    // w.b.wwb
    84,    // .bb.wwb
    -11,   // bbb.wwb
    0,     // wbb.wwb
    48,    // .wb.wwb
    95,    // bwb.wwb
    -7,    // wwb.wwb
    130,   // ..w.wwb
    40,    // b.w.wwb
    -20,   // w.w.wwb
    -57,   // .bw.wwb
    -2,    // bbw.wwb
    28,    // wbw.wwb
    11,    // .ww.wwb
    -11,   // bww.wwb
    18,    // www.wwb
    37,    // ...bwwb
    -78,   // b..bwwb
    55,    // w..bwwb
    -73,   // .b.bwwb
    56,    // bb.bwwb
    36,    // wb.bwwb
    96,    // .w.bwwb
    73,    // bw.bwwb
    -97,   // ww.bwwb
    -109,  // ..bbwwb
    -66,   // b.bbwwb
    -40,   // w.bbwwb
    7,     // .bbbwwb
    6,     // bbbbwwb
    26,    // wbbbwwb
    90,    // .wbbwwb
    12,    // bwbbwwb
    -9,    // wwbbwwb
    -6,    // ..wbwwb
    67,    // b.wbwwb
    -4,    // w.wbwwb
    102,   // .bwbwwb
    26,    // bbwbwwb
    46,    // wbwbwwb
    84,    // .wwbwwb
    -11,   // bwwbwwb
    182,   // wwwbwwb
    91,    // ...wwwb
    -24,   // b..wwwb
    106,   // w..wwwb
    41,    // .b.wwwb
    12,    // bb.wwwb
    17,    // wb.wwwb
    -98,   // .w.wwwb
    -58,   // bw.wwwb
    6,     // ww.wwwb
    37,    // ..bwwwb
    -29,   // b.bwwwb
    24,    // w.bwwwb
    98,    // .bbwwwb
    23,    // bbbwwwb
    -26,   // wbbwwwb
    19,    // .wbwwwb
    -97,   // bwbwwwb
    17,    // wwbwwwb
    -13,   // ..wwwwb
    -4,    // b.wwwwb
    34,    // w.wwwwb
    223,   // .bwwwwb
    -11,   // bbwwwwb
    108,   // wbwwwwb
    -1,    // .wwwwwb
    70,    // bwwwwwb
    9,     // wwwwwwb
    -16,   // ......w
    0,     // b.....w
    -20,   // w.....w
    -79,   // .b....w
    34,    // bb....w
    -6,    // wb....w
    33,    // .w....w
    -9,    // bw....w
    30,    // ww....w
    -81,   // ..b...w
    -79,   // b.b...w
    0,     // w.b...w
    24,    // .bb...w
    102,   // bbb...w
    28,    // wbb...w
    -6,    // .wb...w
    32,    // bwb...w
    54,    // wwb...w
    -37,   // ..w...w
    92,    // b.w...w
    -4,    // w.w...w
    86,    // .bw...w
    -10,   // bbw...w
    -20,   // wbw...w
    8,     // .ww...w
    115,   // bww...w
    101,   // www...w
    -13,   // ...b..w
    27,    // b..b..w
    14,    // w..b..w
    -32,   // .b.b..w
    -85,   // bb.b..w
    71,    // wb.b..w
    76,    // .w.b..w
    26,    // bw.b..w
    -64,   // ww.b..w
    -31,   // ..bb..w
    -50,   // b.bb..w
    4,     // w.bb..w
    98,    // .bbb..w
    84,    // bbbb..w
    24,    // wbbb..w
    -26,   // .wbb..w
    -96,   // bwbb..w
    61,    // wwbb..w
    -101,  // ..wb..w
    -23,   // b.wb..w
    -67,   // w.wb..w
    68,    // .bwb..w
    7,     // bbwb..w
    35,    // wbwb..w
    -58,   // .wwb..w
    55,    // bwwb..w
    -68,   // wwwb..w
    16,    // ...w..w
    -27,   // b..w..w
    55,    // w..w..w
    4,     // .b.w..w
    -98,   // bb.w..w
    13,    // wb.w..w
    37,    // .w.w..w
    97,    // bw.w..w
    44,    // ww.w..w
    58,    // ..bw..w
    -14,   // b.bw..w
    57,    // w.bw..w
    37,    // .bbw..w
    -32,   // bbbw..w
    78,    // wbbw..w
    -32,   // .wbw..w
    75,    // bwbw..w
    91,    // wwbw..w
    -27,   // ..ww..w
    21,    // b.ww..w
    38,    // w.ww..w
    11,    // .bww..w
    67,    // bbww..w
    -100,  // wbww..w
    46,    // .www..w
    106,   // bwww..w
    -6,    // wwww..w
    -18,   // ....b.w
    -92,   // b...b.w
    0,     // w...b.w
    -59,   // .b..b.w
    22,    // bb..b.w
    -83,   // wb..b.w
    20,    // .w..b.w
    -131,  // bw..b.w
    20,    // ww..b.w
    -26,   // ..b.b.w
    82,    // b.b.b.w
    -64,   // w.b.b.w
    5,     // .bb.b.w
    12,    // bbb.b.w
    -40,   // wbb.b.w
    36,    // .wb.b.w
    -57,   // bwb.b.w
    101,   // wwb.b.w
    15,    // ..w.b.w
    0,     // b.w.b.w
    -16,   // w.w.b.w
    -28,   // .bw.b.w
    10,    // bbw.b.w
    -41,   // wbw.b.w
    -4,    // .ww.b.w
    45,    // bww.b.w
    30,    // www.b.w
    -23,   // ...bb.w
    -21,   // b..bb.w
    4,     // w..bb.w
    118,   // .b.bb.w
    -5,    // bb.bb.w
    20,    // wb.bb.w
    3,     // .w.bb.w
    -86,   // bw.bb.w
    -2,    // ww.bb.w
    -11,   // ..bbb.w
    -36,   // b.bbb.w
    54,    // w.bbb.w
    85,    // .bbbb.w
    18,    // bbbbb.w
    4,     // wbbbb.w
    -144,  // .wbbb.w
    0,     // bwbbb.w
    58,    // wwbbb.w
    -62,   // ..wbb.w
    29,    // b.wbb.w
    18,    // w.wbb.w
    -18,   // .bwbb.w
    64,    // bbwbb.w
    -74,   // wbwbb.w
    3,     // .wwbb.w
    -40,   // bwwbb.w
    -106,  // wwwbb.w
    -64,   // ...wb.w
    23,    // b..wb.w
    57,    // w..wb.w
    52,    // .b.wb.w
    36,    // bb.wb.w
    -32,   // wb.wb.w
    11,    // .w.wb.w
    18,    // bw.wb.w
    -63,   // ww.wb.w
    -12,   // ..bwb.w
    -2,    // b.bwb.w
    50,    // w.bwb.w
    -93,   // .bbwb.w
    46,    // bbbwb.w
    -67,   // wbbwb.w
    37,    // .wbwb.w
    39,    // bwbwb.w
    0,     // wwbwb.w
    54,    // ..wwb.w
    -29,   // b.wwb.w
    -3,    // w.wwb.w
    -31,   // .bwwb.w
    3,     // bbwwb.w
    -100,  // wbwwb.w
    -11,   // .wwwb.w
    24,    // bwwwb.w
    -96,   // wwwwb.w
    -73,   // ....w.w
    79,    // b...w.w
    -4,    // w...w.w
    -33,   // .b..w.w
    -32,   // bb..w.w
    -32,   // wb..w.w
    -56,   // .w..w.w
    -145,  // bw..w.w
    86,    // ww..w.w
    -66,   // ..b.w.w
    0,     // b.b.w.w
    -16,   // w.b.w.w
    41,    // .bb.w.w
    -23,   // bbb.w.w
    -161,  // wbb.w.w
    51,    // .wb.w.w
    -28,   // bwb.w.w
    -41,   // wwb.w.w
    20,    // ..w.w.w
    -82,   // b.w.w.w
    -40,   // w.w.w.w
    95,    // .bw.w.w
    18,    // bbw.w.w
    -12,   // wbw.w.w
    -27,   // .ww.w.w
    -20,   // bww.w.w
    -36,   // www.w.w
    -75,   // ...bw.w
    14,    // b..bw.w
    -67,   // w..bw.w
    -44,   // .b.bw.w
    -37,   // bb.bw.w
    -32,   // wb.bw.w
    -57,   // .w.bw.w
    0,     // bw.bw.w
    6,     // ww.bw.w
    -30,   // ..bbw.w
    95,    // b.bbw.w
    18,    // w.bbw.w
    -80,   // .bbbw.w
    -15,   // bbbbw.w
    29,    // wbbbw.w
    69,    // .wbbw.w
    -44,   // bwbbw.w
    48,    // wwbbw.w
    -10,   // ..wbw.w
    2,     // b.wbw.w
    -30,   // w.wbw.w
    1,     // .bwbw.w
    -109,  // bbwbw.w
    -28,   // wbwbw.w
    85,    // .wwbw.w
    -4,    // bwwbw.w
    53,    // wwwbw.w
    -94,   // ...ww.w
    50,    // b..ww.w
    38,    // w..ww.w
    29,    // .b.ww.w
    2,     // bb.ww.w
    24,    // wb.ww.w
    -11,   // .w.ww.w
    72,    // bw.ww.w
    31,    // ww.ww.w
    79,    // ..bww.w
    -95,   // b.bww.w
    -3,    // w.bww.w
    -30,   // .bbww.w
    -80,   // bbbww.w
    66,    // wbbww.w
    39,    // .wbww.w
    -17,   // bwbww.w
    64,    // wwbww.w
    -101,  // ..www.w
    36,    // b.www.w
    -49,   // w.www.w
    -206,  // .bwww.w
    -10,   // bbwww.w
    80,    // wbwww.w
    -120,  // .wwww.w
    34,    // bwwww.w
    79,    // wwwww.w
    -16,   // .....bw
    9,     // b....bw
    -6,    // w....bw
    23,    // .b...bw
    -50,   // bb...bw
    154,   // wb...bw
    58,    // .w...bw
    0,     // bw...bw
    27,    // ww...bw
    17,    // ..b..bw
    145,   // b.b..bw
    -83,   // w.b..bw
    1,     // .bb..bw
    -21,   // bbb..bw
    50,    // wbb..bw
    103,   // .wb..bw
    1,     // bwb..bw
    -46,   // wwb..bw
    56,    // ..w..bw
    131,   // b.w..bw
    -32,   // w.w..bw
    -94,   // .bw..bw
    -8,    // bbw..bw
    81,    // wbw..bw
    18,    // .ww..bw
    -23,   // bww..bw
    -9,    // www..bw
    -64,   // ...b.bw
    -97,   // b..b.bw
    71,    // w..b.bw
    4,     // .b.b.bw
    79,    // bb.b.bw
    -20,   // wb.b.bw
    -116,  // .w.b.bw
    -52,   // bw.b.bw
    -68,   // ww.b.bw
    1,     // ..bb.bw
    -72,   // b.bb.bw
    20,    // w.bb.bw
    55,    // .bbb.bw
    70,    // bbbb.bw
    58,    // wbbb.bw
    -82,   // .wbb.bw
    -81,   // bwbb.bw
    -98,   // wwbb.bw
    -40,   // ..wb.bw
    -18,   // b.wb.bw
    -32,   // w.wb.bw
    -40,   // .bwb.bw
    71,    // bbwb.bw
    -45,   // wbwb.bw
    20,    // .wwb.bw
    36,    // bwwb.bw
    -39,   // wwwb.bw
    18,    // ...w.bw
    -26,   // b..w.bw
    13,    // w..w.bw
    -89,   // .b.w.bw
    34,    // bb.w.bw
    -36,   // wb.w.bw
    0,     // .w.w.bw
    52,    // bw.w.bw
    63,    // ww.w.bw
    7,     // ..bw.bw
    0,     // b.bw.bw
    -32,   // w.bw.bw
    5,     // .bbw.bw
    -45,   // bbbw.bw
    -73,   // wbbw.bw
    20,    // .wbw.bw
    17,    // bwbw.bw
    21,    // wwbw.bw
    -2,    // ..ww.bw
    86,    // b.ww.bw
    24,    // w.ww.bw
    31,    // .bww.bw
    -10,   // bbww.bw
    46,    // wbww.bw
    -66,   // .www.bw
    17,    // bwww.bw
    -102,  // wwww.bw
    -109,  // ....bbw
    -115,  // b...bbw
    28,    // w...bbw
    106,   // .b..bbw
    -48,   // bb..bbw
    50,    // wb..bbw
    -24,   // .w..bbw
    23,    // bw..bbw
    22,    // ww..bbw
    -130,  // ..b.bbw
    20,    // b.b.bbw
    -40,   // w.b.bbw
    -11,   // .bb.bbw
    -18,   // bbb.bbw
    11,    // wbb.bbw
    57,    // .wb.bbw
    -28,   // bwb.bbw
    2,     // wwb.bbw
    39,    // ..w.bbw
    -45,   // b.w.bbw
    -161,  // w.w.bbw
    -48,   // .bw.bbw
    7,     // bbw.bbw
    -95,   // wbw.bbw
    -84,   // .ww.bbw
    0,     // bww.bbw
    11,    // www.bbw
    -91,   // ...bbbw
    -106,  // b..bbbw
    24,    // w..bbbw
    98,    // .b.bbbw
    -6,    // bb.bbbw
    58,    // wb.bbbw
    -41,   // .w.bbbw
    -17,   // bw.bbbw
    -12,   // ww.bbbw
    13,    // ..bbbbw
    -34,   // b.bbbbw
    4,     // w.bbbbw
    1,     // .bbbbbw
    -9,    // bbbbbbw
    -70,   // wbbbbbw
    -223,  // .wbbbbw
    -108,  // bwbbbbw
    11,    // wwbbbbw
    -37,   // ..wbbbw
    -24,   // b.wbbbw
    29,    // w.wbbbw
    -19,   // .bwbbbw
    -17,   // bbwbbbw
    97,    // wbwbbbw
    -98,   // .wwbbbw
    26,    // bwwbbbw
    -23,   // wwwbbbw
    -37,   // ...wbbw
    -55,   // b..wbbw
    78,    // w..wbbw
    -96,   // .b.wbbw
    97,    // bb.wbbw
    -73,   // wb.wbbw
    73,    // .w.wbbw
    -36,   // bw.wbbw
    -56,   // ww.wbbw
    6,     // ..bwbbw
    4,     // b.bwbbw
    -67,   // w.bwbbw
    -84,   // .bbwbbw
    -182,  // bbbwbbw
    11,    // wbbwbbw
    -102,  // .wbwbbw
    -46,   // bwbwbbw
    -26,   // wwbwbbw
    109,   // ..wwbbw
    40,    // b.wwbbw
    66,    // w.wwbbw
    -90,   // .bwwbbw
    9,     // bbwwbbw
    -12,   // wbwwbbw
    -7,    // .wwwbbw
    -26,   // bwwwbbw
    -6,    // wwwwbbw
    -50,   // ....wbw
    -32,   // b...wbw
    -20,   // w...wbw
    -31,   // .b..wbw
    -15,   // bb..wbw
    81,    // wb..wbw
    68,    // .w..wbw
    -1,    // bw..wbw
    56,    // ww..wbw
    -67,   // ..b.wbw
    28,    // b.b.wbw
    -41,   // w.b.wbw
    -128,  // .bb.wbw
    -62,   // bbb.wbw
    -95,   // wbb.wbw
    -45,   // .wb.wbw
    0,     // bwb.wbw
    -18,   // wwb.wbw
    69,    // ..w.wbw
    57,    // b.w.wbw
    -12,   // w.w.wbw
    1,     // .bw.wbw
    -74,   // bbw.wbw
    -21,   // wbw.wbw
    -11,   // .ww.wbw
    28,    // bww.wbw
    62,    // www.wbw
    -4,    // ...bwbw
    -75,   // b..bwbw
    35,    // w..bwbw
    21,    // .b.bwbw
    -51,   // bb.bwbw
    -45,   // wb.bwbw
    3,     // .w.bwbw
    -17,   // bw.bwbw
    -180,  // ww.bwbw
    73,    // ..bbwbw
    17,    // b.bbwbw
    -74,   // w.bbwbw
    89,    // .bbbwbw
    80,    // bbbbwbw
    97,    // wbbbwbw
    117,   // .wbbwbw
    78,    // bwbbwbw
    26,    // wwbbwbw
    35,    // ..wbwbw
    -39,   // b.wbwbw
    -28,   // w.wbwbw
    -59,   // .bwbwbw
    126,   // bbwbwbw
    58,    // wbwbwbw
    55,    // .wwbwbw
    46,    // bwwbwbw
    -35,   // wwwbwbw
    15,    // ...wwbw
    96,    // b..wwbw
    -100,  // w..wwbw
    142,   // .b.wwbw
    36,    // bb.wwbw
    46,    // wb.wwbw
    51,    // .w.wwbw
    81,    // bw.wwbw
    -31,   // ww.wwbw
    -5,    // ..bwwbw
    44,    // b.bwwbw
    -100,  // w.bwwbw
    -36,   // .bbwwbw
    -96,   // bbbwwbw
    -12,   // wbbwwbw
    107,   // .wbwwbw
    -78,   // bwbwwbw
    -1,    // wwbwwbw
    48,    // ..wwwbw
    0,     // b.wwwbw
    80,    // w.wwwbw
    -1,    // .bwwwbw
    5,     // bbwwwbw
    -58,   // wbwwwbw
    62,    // .wwwwbw
    108,   // bwwwwbw
    17,    // wwwwwbw
    -44,   // .....ww
    -34,   // b....ww
    30,    // w....ww
    9,     // .b...ww
    0,     // bb...ww
    27,    // wb...ww
    39,    // .w...ww
    50,    // bw...ww
    -14,   // ww...ww
    26,    // ..b..ww
    32,    // b.b..ww
    20,    // w.b..ww
    -95,   // .bb..ww
    46,    // bbb..ww
    22,    // wbb..ww
    9,     // .wb..ww
    15,    // bwb..ww
    8,     // wwb..ww
    41,    // ..w..ww
    -22,   // b.w..ww
    86,    // w.w..ww
    -111,  // .bw..ww
    -29,   // bbw..ww
    56,    // wbw..ww
    -15,   // .ww..ww
    48,    // bww..ww
    -146,  // www..ww
    -48,   // ...b.ww
    98,    // b..b.ww
    -64,   // w..b.ww
    -28,   // .b.b.ww
    35,    // bb.b.ww
    -68,   // wb.b.ww
    32,    // .w.b.ww
    -34,   // bw.b.ww
    -72,   // ww.b.ww
    -47,   // ..bb.ww
    -2,    // b.bb.ww
    -2,    // w.bb.ww
    -1,    // .bbb.ww
    42,    // bbbb.ww
    -12,   // wbbb.ww
    32,    // .wbb.ww
    -36,   // bwbb.ww
    23,    // wwbb.ww
    32,    // ..wb.ww
    -36,   // b.wb.ww
    6,     // w.wb.ww
    -36,   // .bwb.ww
    -58,   // bbwb.ww
    -180,  // wbwb.ww
    -82,   // .wwb.ww
    -97,   // bwwb.ww
    -65,   // wwwb.ww
    -122,  // ...w.ww
    85,    // b..w.ww
    44,    // w..w.ww
    -132,  // .b.w.ww
    -35,   // bb.w.ww
    63,    // wb.w.ww
    90,    // .w.w.ww
    -79,   // bw.w.ww
    -16,   // ww.w.ww
    20,    // ..bw.ww
    37,    // b.bw.ww
    -63,   // w.bw.ww
    -34,   // .bbw.ww
    -43,   // bbbw.ww
    -56,   // wbbw.ww
    32,    // .wbw.ww
    51,    // bwbw.ww
    14,    // wwbw.ww
    -47,   // ..ww.ww
    5,     // b.ww.ww
    31,    // w.ww.ww
    -94,   // .bww.ww
    122,   // bbww.ww
    -31,   // wbww.ww
    -20,   // .www.ww
    6,     // bwww.ww
    35,    // wwww.ww
    72,    // ....bww
    10,    // b...bww
    54,    // w...bww
    32,    // .b..bww
    29,    // bb..bww
    -46,   // wb..bww
    21,    // .w..bww
    8,     // bw..bww
    8,     // ww..bww
    -34,   // ..b.bww
    -18,   // b.b.bww
    101,   // w.b.bww
    -16,   // .bb.bww
    -85,   // bbb.bww
    2,     // wbb.bww
    24,    // .wb.bww
    74,    // bwb.bww
    70,    // wwb.bww
    56,    // ..w.bww
    -10,   // b.w.bww
    -41,   // w.w.bww
    15,    // .bw.bww
    0,     // bbw.bww
    -18,   // wbw.bww
    -45,   // .ww.bww
    -7,    // bww.bww
    -73,   // www.bww
    9,     // ...bbww
    -67,   // b..bbww
    61,    // w..bbww
    -2,    // .b.bbww
    -122,  // bb.bbww
    -98,   // wb.bbww
    7,     // .w.bbww
    10,    // bw.bbww
    23,    // ww.bbww
    3,     // ..bbbww
    10,    // b.bbbww
    58,    // w.bbbww
    -2,    // .bbbbww
    131,   // bbbbbww
    11,    // wbbbbww
    -81,   // .wbbbww
    -5,    // bwbbbww
    2,     // wwbbbww
    9,     // ..wbbww
    -3,    // b.wbbww
    48,    // w.wbbww
    70,    // .bwbbww
    47,    // bbwbbww
    26,    // wbwbbww
    60,    // .wwbbww
    -9,    // bwwbbww
    -59,   // wwwbbww
    86,    // ...wbww
    -7,    // b..wbww
    91,    // w..wbww
    54,    // .b.wbww
    58,    // bb.wbww
    21,    // wb.wbww
    -36,   // .w.wbww
    -71,   // bw.wbww
    14,    // ww.wbww
    14,    // ..bwbww
    109,   // b.bwbww
    0,     // w.bwbww
    128,   // .bbwbww
    -25,   // bbbwbww
    -26,   // wbbwbww
    4,     // .wbwbww
    -126,  // bwbwbww
    -43,   // wwbwbww
    10,    // ..wwbww
    -64,   // b.wwbww
    64,    // w.wwbww
    -21,   // .bwwbww
    -47,   // bbwwbww
    -1,    // wbwwbww
    111,   // .wwwbww
    17,    // bwwwbww
    26,    // wwwwbww
    -71,   // ....www
    -102,  // b...www
    101,   // w...www
    -87,   // .b..www
    -46,   // bb..www
    -9,    // wb..www
    -16,   // .w..www
    21,    // bw..www
    -146,  // ww..www
    -42,   // ..b.www
    23,    // b.b.www
    30,    // w.b.www
    -105,  // .bb.www
    0,     // bbb.www
    11,    // wbb.www
    11,    // .wb.www
    62,    // bwb.www
    -73,   // wwb.www
    -184,  // ..w.www
    -12,   // b.w.www
    -36,   // w.w.www
    8,     // .bw.www
    85,    // bbw.www
    62,    // wbw.www
    19,    // .ww.www
    18,    // bww.www
    -27,   // www.www
    -113,  // ...bwww
    32,    // b..bwww
    -68,   // w..bwww
    41,    // .b.bwww
    43,    // bb.bwww
    -39,   // wb.bwww
    110,   // .w.bwww
    45,    // bw.bwww
    -65,   // ww.bwww
    -95,   // ..bbwww
    80,    // b.bbwww
    -106,  // w.bbwww
    -39,   // .bbbwww
    -97,   // bbbbwww
    -23,   // wbbbwww
    4,     // .wbbwww
    96,    // bwbbwww
    -59,   // wwbbwww
    147,   // ..wbwww
    -46,   // b.wbwww
    53,    // w.wbwww
    29,    // .bwbwww
    25,    // bbwbwww
    -35,   // wbwbwww
    68,    // .wwbwww
    182,   // bwwbwww
    4,     // wwwbwww
    -642,  // ...wwww
    -84,   // b..wwww
    -6,    // w..wwww
    -259,  // .b.wwww
    -42,   // bb.wwww
    -102,  // wb.wwww
    70,    // .w.wwww
    -70,   // bw.wwww
    35,    // ww.wwww
    -119,  // ..bwwww
    15,    // b.bwwww
    -96,   // w.bwwww
    52,    // .bbwwww
    97,    // bbbwwww
    -6,    // wbbwwww
    112,   // .wbwwww
    -80,   // bwbwwww
    26,    // wwbwwww
    -79,   // ..wwwww
    -18,   // b.wwwww
    79,    // w.wwwww
    -293,  // .bwwwww
    -131,  // bbwwwww
    17,    // wbwwwww
    78,    // .wwwwww
    9,     // bwwwwww
    46,    // wwwwwww
    0,     // captures=0 threats=0
    55,    // captures=0 threats=1
    110,   // captures=0 threats=2
    151,   // captures=0 threats=3
    182,   // captures=0 threats=4
    51,    // captures=0 additional threats
    80,    // captures=1 threats=0
    136,   // captures=1 threats=1
    210,   // captures=1 threats=2
    451,   // captures=1 threats=3
    514,   // captures=1 threats=4
    14,    // captures=1 additional threats
    119,   // captures=2 threats=0
    267,   // captures=2 threats=1
    373,   // captures=2 threats=2
    549,   // captures=2 threats=3
    784,   // captures=2 threats=4
    136,   // captures=2 additional threats
    153,   // captures=3 threats=0
    433,   // captures=3 threats=1
    640,   // captures=3 threats=2
    774,   // captures=3 threats=3
    801,   // captures=3 threats=4
    195,   // captures=3 additional threats
    156,   // captures=4 threats=0
    443,   // captures=4 threats=1
    734,   // captures=4 threats=2
    936,   // captures=4 threats=3
    1035,  // captures=4 threats=4
    304,   // captures=4 additional threats
].into_boxed_slice()
