vec![
    0,     // .......
    -8,    // b......
    8,     // w......
    14,    // .b.....
    22,    // bb.....
    -39,   // wb.....
    -14,   // .w.....
    39,    // bw.....
    -22,   // ww.....
    -14,   // ..b....
    -16,   // b.b....
    -41,   // w.b....
    -26,   // .bb....
    93,    // bbb....
    -1,    // wbb....
    -33,   // .wb....
    -35,   // bwb....
    -13,   // wwb....
    14,    // ..w....
    41,    // b.w....
    16,    // w.w....
    33,    // .bw....
    13,    // bbw....
    35,    // wbw....
    26,    // .ww....
    1,     // bww....
    -93,   // www....
    -43,   // ...b...
    2,     // b..b...
    -23,   // w..b...
    -8,    // .b.b...
    41,    // bb.b...
    -54,   // wb.b...
    47,    // .w.b...
    36,    // bw.b...
    -56,   // ww.b...
    -14,   // ..bb...
    48,    // b.bb...
    24,    // w.bb...
    58,    // .bbb...
    263,   // bbbb...
    -85,   // wbbb...
    -50,   // .wbb...
    97,    // bwbb...
    75,    // wwbb...
    71,    // ..wb...
    0,     // b.wb...
    72,    // w.wb...
    57,    // .bwb...
    -2,    // bbwb...
    62,    // wbwb...
    -34,   // .wwb...
    20,    // bwwb...
    66,    // wwwb...
    43,    // ...w...
    23,    // b..w...
    -2,    // w..w...
    -47,   // .b.w...
    56,    // bb.w...
    -36,   // wb.w...
    8,     // .w.w...
    54,    // bw.w...
    -41,   // ww.w...
    -71,   // ..bw...
    -72,   // b.bw...
    0,     // w.bw...
    34,    // .bbw...
    -66,   // bbbw...
    -20,   // wbbw...
    -57,   // .wbw...
    -62,   // bwbw...
    2,     // wwbw...
    14,    // ..ww...
    -24,   // b.ww...
    -48,   // w.ww...
    50,    // .bww...
    -75,   // bbww...
    -97,   // wbww...
    -58,   // .www...
    85,    // bwww...
    -263,  // wwww...
    -14,   // ....b..
    -11,   // b...b..
    10,    // w...b..
    -37,   // .b..b..
    105,   // bb..b..
    -17,   // wb..b..
    -74,   // .w..b..
    47,    // bw..b..
    -58,   // ww..b..
    10,    // ..b.b..
    3,     // b.b.b..
    -38,   // w.b.b..
    53,    // .bb.b..
    207,   // bbb.b..
    33,    // wbb.b..
    -2,    // .wb.b..
    22,    // bwb.b..
    21,    // wwb.b..
    0,     // ..w.b..
    21,    // b.w.b..
    -32,   // w.w.b..
    -31,   // .bw.b..
    -19,   // bbw.b..
    -50,   // wbw.b..
    74,    // .ww.b..
    -71,   // bww.b..
    20,    // www.b..
    -14,   // ...bb..
    -27,   // b..bb..
    -128,  // w..bb..
    50,    // .b.bb..
    16,    // bb.bb..
    -91,   // wb.bb..
    -60,   // .w.bb..
    -52,   // bw.bb..
    68,    // ww.bb..
    38,    // ..bbb..
    49,    // b.bbb..
    8,     // w.bbb..
    212,   // .bbbb..
    -10,   // bbbbb..
    68,    // wbbbb..
    -19,   // .wbbb..
    -70,   // bwbbb..
    -19,   // wwbbb..
    13,    // ..wbb..
    -37,   // b.wbb..
    13,    // w.wbb..
    -46,   // .bwbb..
    -46,   // bbwbb..
    -44,   // wbwbb..
    -20,   // .wwbb..
    -19,   // bwwbb..
    -18,   // wwwbb..
    -71,   // ...wb..
    -19,   // b..wb..
    -46,   // w..wb..
    -12,   // .b.wb..
    -17,   // bb.wb..
    -40,   // wb.wb..
    -60,   // .w.wb..
    62,    // bw.wb..
    18,    // ww.wb..
    -23,   // ..bwb..
    -5,    // b.bwb..
    -41,   // w.bwb..
    -8,    // .bbwb..
    -62,   // bbbwb..
    6,     // wbbwb..
    10,    // .wbwb..
    2,     // bwbwb..
    88,    // wwbwb..
    -13,   // ..wwb..
    -4,    // b.wwb..
    -36,   // w.wwb..
    34,    // .bwwb..
    17,    // bbwwb..
    11,    // wbwwb..
    -7,    // .wwwb..
    5,     // bwwwb..
    -33,   // wwwwb..
    14,    // ....w..
    -10,   // b...w..
    11,    // w...w..
    74,    // .b..w..
    58,    // bb..w..
    -47,   // wb..w..
    37,    // .w..w..
    17,    // bw..w..
    -105,  // ww..w..
    0,     // ..b.w..
    32,    // b.b.w..
    -21,   // w.b.w..
    -74,   // .bb.w..
    -20,   // bbb.w..
    71,    // wbb.w..
    31,    // .wb.w..
    50,    // bwb.w..
    19,    // wwb.w..
    -10,   // ..w.w..
    38,    // b.w.w..
    -3,    // w.w.w..
    2,     // .bw.w..
    -21,   // bbw.w..
    -22,   // wbw.w..
    -53,   // .ww.w..
    -33,   // bww.w..
    -207,  // www.w..
    71,    // ...bw..
    46,    // b..bw..
    19,    // w..bw..
    60,    // .b.bw..
    -18,   // bb.bw..
    -62,   // wb.bw..
    12,    // .w.bw..
    40,    // bw.bw..
    17,    // ww.bw..
    13,    // ..bbw..
    36,    // b.bbw..
    4,     // w.bbw..
    7,     // .bbbw..
    33,    // bbbbw..
    -5,    // wbbbw..
    -34,   // .wbbw..
    -11,   // bwbbw..
    -17,   // wwbbw..
    23,    // ..wbw..
    41,    // b.wbw..
    5,     // w.wbw..
    -10,   // .bwbw..
    -88,   // bbwbw..
    -2,    // wbwbw..
    8,     // .wwbw..
    -6,    // bwwbw..
    62,    // wwwbw..
    14,    // ...ww..
    128,   // b..ww..
    27,    // w..ww..
    60,    // .b.ww..
    -68,   // bb.ww..
    52,    // wb.ww..
    -50,   // .w.ww..
    91,    // bw.ww..
    -16,   // ww.ww..
    -13,   // ..bww..
    -13,   // b.bww..
    37,    // w.bww..
    20,    // .bbww..
    18,    // bbbww..
    19,    // wbbww..
    46,    // .wbww..
    44,    // bwbww..
    46,    // wwbww..
    -38,   // ..www..
    -8,    // b.www..
    -49,   // w.www..
    19,    // .bwww..
    19,    // bbwww..
    70,    // wbwww..
    -212,  // .wwww..
    -68,   // bwwww..
    10,    // wwwww..
    14,    // .....b.
    -18,   // b....b.
    -22,   // w....b.
    20,    // .b...b.
    8,     // bb...b.
    11,    // wb...b.
    0,     // .w...b.
    7,     // bw...b.
    -6,    // ww...b.
    -37,   // ..b..b.
    3,     // b.b..b.
    7,     // w.b..b.
    -39,   // .bb..b.
    -20,   // bbb..b.
    69,    // wbb..b.
    -68,   // .wb..b.
    3,     // bwb..b.
    14,    // wwb..b.
    74,    // ..w..b.
    -41,   // b.w..b.
    -1,    // w.w..b.
    -71,   // .bw..b.
    -30,   // bbw..b.
    38,    // wbw..b.
    -39,   // .ww..b.
    -17,   // bww..b.
    -10,   // www..b.
    -8,    // ...b.b.
    18,    // b..b.b.
    67,    // w..b.b.
    8,     // .b.b.b.
    -13,   // bb.b.b.
    -11,   // wb.b.b.
    21,    // .w.b.b.
    21,    // bw.b.b.
    -10,   // ww.b.b.
    50,    // ..bb.b.
    40,    // b.bb.b.
    25,    // w.bb.b.
    89,    // .bbb.b.
    -27,   // bbbb.b.
    89,    // wbbb.b.
    -90,   // .wbb.b.
    93,    // bwbb.b.
    -35,   // wwbb.b.
    60,    // ..wb.b.
    -57,   // b.wb.b.
    -10,   // w.wb.b.
    -38,   // .bwb.b.
    60,    // bbwb.b.
    -2,    // wbwb.b.
    -31,   // .wwb.b.
    -11,   // bwwb.b.
    2,     // wwwb.b.
    -47,   // ...w.b.
    -21,   // b..w.b.
    -8,    // w..w.b.
    -52,   // .b.w.b.
    -65,   // bb.w.b.
    37,    // wb.w.b.
    -21,   // .w.w.b.
    -34,   // bw.w.b.
    -42,   // ww.w.b.
    -12,   // ..bw.b.
    8,     // b.bw.b.
    -82,   // w.bw.b.
    2,     // .bbw.b.
    -40,   // bbbw.b.
    -7,    // wbbw.b.
    -50,   // .wbw.b.
    -37,   // bwbw.b.
    -71,   // wwbw.b.
    60,    // ..ww.b.
    -26,   // b.ww.b.
    50,    // w.ww.b.
    -77,   // .bww.b.
    -38,   // bbww.b.
    -6,    // wbww.b.
    -36,   // .www.b.
    18,    // bwww.b.
    -95,   // wwww.b.
    -26,   // ....bb.
    -3,    // b...bb.
    82,    // w...bb.
    -39,   // .b..bb.
    49,    // bb..bb.
    8,     // wb..bb.
    39,    // .w..bb.
    -10,   // bw..bb.
    0,     // ww..bb.
    53,    // ..b.bb.
    46,    // b.b.bb.
    -35,   // w.b.bb.
    -18,   // .bb.bb.
    -55,   // bbb.bb.
    82,    // wbb.bb.
    45,    // .wb.bb.
    -76,   // bwb.bb.
    -4,    // wwb.bb.
    -74,   // ..w.bb.
    52,    // b.w.bb.
    -21,   // w.w.bb.
    4,     // .bw.bb.
    5,     // bbw.bb.
    -128,  // wbw.bb.
    0,     // .ww.bb.
    -17,   // bww.bb.
    -12,   // www.bb.
    58,    // ...bbb.
    61,    // b..bbb.
    -1,    // w..bbb.
    89,    // .b.bbb.
    -4,    // bb.bbb.
    25,    // wb.bbb.
    36,    // .w.bbb.
    7,     // bw.bbb.
    -43,   // ww.bbb.
    212,   // ..bbbb.
    34,    // b.bbbb.
    50,    // w.bbbb.
    -61,   // .bbbbb.
    34,    // bbbbbb.
    -55,   // wbbbbb.
    35,    // .wbbbb.
    -45,   // bwbbbb.
    82,    // wwbbbb.
    7,     // ..wbbb.
    27,    // b.wbbb.
    23,    // w.wbbb.
    21,    // .bwbbb.
    -4,    // bbwbbb.
    42,    // wbwbbb.
    -9,    // .wwbbb.
    12,    // bwwbbb.
    16,    // wwwbbb.
    34,    // ...wbb.
    74,    // b..wbb.
    55,    // w..wbb.
    2,     // .b.wbb.
    -8,    // bb.wbb.
    3,     // wb.wbb.
    31,    // .w.wbb.
    12,    // bw.wbb.
    -28,   // ww.wbb.
    -8,    // ..bwbb.
    26,    // b.bwbb.
    19,    // w.bwbb.
    81,    // .bbwbb.
    8,     // bbbwbb.
    -12,   // wbbwbb.
    -54,   // .wbwbb.
    29,    // bwbwbb.
    7,     // wwbwbb.
    20,    // ..wwbb.
    -3,    // b.wwbb.
    21,    // w.wwbb.
    54,    // .bwwbb.
    34,    // bbwwbb.
    28,    // wbwwbb.
    9,     // .wwwbb.
    -52,   // bwwwbb.
    -46,   // wwwwbb.
    33,    // ....wb.
    -34,   // b...wb.
    41,    // w...wb.
    -71,   // .b..wb.
    64,    // bb..wb.
    -1,    // wb..wb.
    68,    // .w..wb.
    0,     // bw..wb.
    -65,   // ww..wb.
    -31,   // ..b.wb.
    -96,   // b.b.wb.
    -65,   // w.b.wb.
    4,     // .bb.wb.
    20,    // bbb.wb.
    18,    // wbb.wb.
    0,     // .wb.wb.
    -62,   // bwb.wb.
    58,    // wwb.wb.
    2,     // ..w.wb.
    -17,   // b.w.wb.
    41,    // w.w.wb.
    -64,   // .bw.wb.
    70,    // bbw.wb.
    -65,   // wbw.wb.
    -45,   // .ww.wb.
    87,    // bww.wb.
    43,    // www.wb.
    57,    // ...bwb.
    -15,   // b..bwb.
    83,    // w..bwb.
    -38,   // .b.bwb.
    -38,   // bb.bwb.
    -4,    // wb.bwb.
    50,    // .w.bwb.
    6,     // bw.bwb.
    43,    // ww.bwb.
    -46,   // ..bbwb.
    -33,   // b.bbwb.
    -13,   // w.bbwb.
    21,    // .bbbwb.
    13,    // bbbbwb.
    41,    // wbbbwb.
    -89,   // .wbbwb.
    -22,   // bwbbwb.
    -44,   // wwbbwb.
    -10,   // ..wbwb.
    32,    // b.wbwb.
    -6,    // w.wbwb.
    -84,   // .bwbwb.
    11,    // bbwbwb.
    13,    // wbwbwb.
    54,    // .wwbwb.
    -91,   // bwwbwb.
    -116,  // wwwbwb.
    50,    // ...wwb.
    -18,   // b..wwb.
    14,    // w..wwb.
    -77,   // .b.wwb.
    -38,   // bb.wwb.
    -5,    // wb.wwb.
    90,    // .w.wwb.
    -12,   // bw.wwb.
    -44,   // ww.wwb.
    34,    // ..bwwb.
    8,     // b.bwwb.
    2,     // w.bwwb.
    54,    // .bbwwb.
    35,    // bbbwwb.
    -6,    // wbbwwb.
    89,    // .wbwwb.
    66,    // bwbwwb.
    -6,    // wwbwwb.
    19,    // ..wwwb.
    -52,   // b.wwwb.
    -58,   // w.wwwb.
    -29,   // .bwwwb.
    5,     // bbwwwb.
    39,    // wbwwwb.
    -35,   // .wwwwb.
    146,   // bwwwwb.
    49,    // wwwwwb.
    -14,   // .....w.
    22,    // b....w.
    18,    // w....w.
    0,     // .b...w.
    6,     // bb...w.
    -7,    // wb...w.
    -20,   // .w...w.
    -11,   // bw...w.
    -8,    // ww...w.
    -74,   // ..b..w.
    1,     // b.b..w.
    41,    // w.b..w.
    39,    // .bb..w.
    10,    // bbb..w.
    17,    // wbb..w.
    71,    // .wb..w.
    -38,   // bwb..w.
    30,    // wwb..w.
    37,    // ..w..w.
    -7,    // b.w..w.
    -3,    // w.w..w.
    68,    // .bw..w.
    -14,   // bbw..w.
    -3,    // wbw..w.
    39,    // .ww..w.
    -69,   // bww..w.
    20,    // www..w.
    47,    // ...b.w.
    8,     // b..b.w.
    21,    // w..b.w.
    21,    // .b.b.w.
    42,    // bb.b.w.
    34,    // wb.b.w.
    52,    // .w.b.w.
    -37,   // bw.b.w.
    65,    // ww.b.w.
    -60,   // ..bb.w.
    -50,   // b.bb.w.
    26,    // w.bb.w.
    36,    // .bbb.w.
    95,    // bbbb.w.
    -18,   // wbbb.w.
    77,    // .wbb.w.
    6,     // bwbb.w.
    38,    // wwbb.w.
    12,    // ..wb.w.
    82,    // b.wb.w.
    -8,    // w.wb.w.
    50,    // .bwb.w.
    71,    // bbwb.w.
    37,    // wbwb.w.
    -2,    // .wwb.w.
    7,     // bwwb.w.
    40,    // wwwb.w.
    8,     // ...w.w.
    -67,   // b..w.w.
    -18,   // w..w.w.
    -21,   // .b.w.w.
    10,    // bb.w.w.
    -21,   // wb.w.w.
    -8,    // .w.w.w.
    11,    // bw.w.w.
    13,    // ww.w.w.
    -60,   // ..bw.w.
    10,    // b.bw.w.
    57,    // w.bw.w.
    31,    // .bbw.w.
    -2,    // bbbw.w.
    11,    // wbbw.w.
    38,    // .wbw.w.
    2,     // bwbw.w.
    -60,   // wwbw.w.
    -50,   // ..ww.w.
    -25,   // b.ww.w.
    -40,   // w.ww.w.
    90,    // .bww.w.
    35,    // bbww.w.
    -93,   // wbww.w.
    -89,   // .www.w.
    -89,   // bwww.w.
    27,    // wwww.w.
    -33,   // ....bw.
    -41,   // b...bw.
    34,    // w...bw.
    -68,   // .b..bw.
    65,    // bb..bw.
    0,     // wb..bw.
    71,    // .w..bw.
    1,     // bw..bw.
    -64,   // ww..bw.
    -2,    // ..b.bw.
    -41,   // b.b.bw.
    17,    // w.b.bw.
    45,    // .bb.bw.
    -43,   // bbb.bw.
    -87,   // wbb.bw.
    64,    // .wb.bw.
    65,    // bwb.bw.
    -70,   // wwb.bw.
    31,    // ..w.bw.
    65,    // b.w.bw.
    96,    // w.w.bw.
    0,     // .bw.bw.
    -58,   // bbw.bw.
    62,    // wbw.bw.
    -4,    // .ww.bw.
    -18,   // bww.bw.
    -20,   // www.bw.
    -50,   // ...bbw.
    -14,   // b..bbw.
    18,    // w..bbw.
    -90,   // .b.bbw.
    44,    // bb.bbw.
    12,    // wb.bbw.
    77,    // .w.bbw.
    5,     // bw.bbw.
    38,    // ww.bbw.
    -19,   // ..bbbw.
    58,    // b.bbbw.
    52,    // w.bbbw.
    35,    // .bbbbw.
    -49,   // bbbbbw.
    -146,  // wbbbbw.
    29,    // .wbbbw.
    -39,   // bwbbbw.
    -5,    // wwbbbw.
    -34,   // ..wbbw.
    -2,    // b.wbbw.
    -8,    // w.wbbw.
    -89,   // .bwbbw.
    6,     // bbwbbw.
    -66,   // wbwbbw.
    -54,   // .wwbbw.
    6,     // bwwbbw.
    -35,   // wwwbbw.
    -57,   // ...wbw.
    -83,   // b..wbw.
    15,    // w..wbw.
    -50,   // .b.wbw.
    -43,   // bb.wbw.
    -6,    // wb.wbw.
    38,    // .w.wbw.
    4,     // bw.wbw.
    38,    // ww.wbw.
    10,    // ..bwbw.
    6,     // b.bwbw.
    -32,   // w.bwbw.
    -54,   // .bbwbw.
    116,   // bbbwbw.
    91,    // wbbwbw.
    84,    // .wbwbw.
    -13,   // bwbwbw.
    -11,   // wwbwbw.
    46,    // ..wwbw.
    13,    // b.wwbw.
    33,    // w.wwbw.
    89,    // .bwwbw.
    44,    // bbwwbw.
    22,    // wbwwbw.
    -21,   // .wwwbw.
    -41,   // bwwwbw.
    -13,   // wwwwbw.
    26,    // ....ww.
    -82,   // b...ww.
    3,     // w...ww.
    -39,   // .b..ww.
    0,     // bb..ww.
    10,    // wb..ww.
    39,    // .w..ww.
    -8,    // bw..ww.
    -49,   // ww..ww.
    74,    // ..b.ww.
    21,    // b.b.ww.
    -52,   // w.b.ww.
    0,     // .bb.ww.
    12,    // bbb.ww.
    17,    // wbb.ww.
    -4,    // .wb.ww.
    128,   // bwb.ww.
    -5,    // wwb.ww.
    -53,   // ..w.ww.
    35,    // b.w.ww.
    -46,   // w.w.ww.
    -45,   // .bw.ww.
    4,     // bbw.ww.
    76,    // wbw.ww.
    18,    // .ww.ww.
    -82,   // bww.ww.
    55,    // www.ww.
    -34,   // ...bww.
    -55,   // b..bww.
    -74,   // w..bww.
    -31,   // .b.bww.
    28,    // bb.bww.
    -12,   // wb.bww.
    -2,    // .w.bww.
    -3,    // bw.bww.
    8,     // ww.bww.
    -20,   // ..bbww.
    -21,   // b.bbww.
    3,     // w.bbww.
    -9,    // .bbbww.
    46,    // bbbbww.
    52,    // wbbbww.
    -54,   // .wbbww.
    -28,   // bwbbww.
    -34,   // wwbbww.
    8,     // ..wbww.
    -19,   // b.wbww.
    -26,   // w.wbww.
    54,    // .bwbww.
    -7,    // bbwbww.
    -29,   // wbwbww.
    -81,   // .wwbww.
    12,    // bwwbww.
    -8,    // wwwbww.
    -58,   // ...www.
    1,     // b..www.
    -61,   // w..www.
    -36,   // .b.www.
    43,    // bb.www.
    -7,    // wb.www.
    -89,   // .w.www.
    -25,   // bw.www.
    4,     // ww.www.
    -7,    // ..bwww.
    -23,   // b.bwww.
    -27,   // w.bwww.
    9,     // .bbwww.
    -16,   // bbbwww.
    -12,   // wbbwww.
    -21,   // .wbwww.
    -42,   // bwbwww.
    4,     // wwbwww.
    -212,  // ..wwww.
    -50,   // b.wwww.
    -34,   // w.wwww.
    -35,   // .bwwww.
    -82,   // bbwwww.
    45,    // wbwwww.
    61,    // .wwwww.
    55,    // bwwwww.
    -34,   // wwwwww.
    -8,    // ......b
    17,    // b.....b
    0,     // w.....b
    -18,   // .b....b
    10,    // bb....b
    -53,   // wb....b
    22,    // .w....b
    70,    // bw....b
    38,    // ww....b
    -11,   // ..b...b
    -97,   // b.b...b
    6,     // w.b...b
    -3,    // .bb...b
    -66,   // bbb...b
    138,   // wbb...b
    -41,   // .wb...b
    -5,    // bwb...b
    25,    // wwb...b
    -10,   // ..w...b
    84,    // b.w...b
    19,    // w.w...b
    -34,   // .bw...b
    -51,   // bbw...b
    21,    // wbw...b
    -82,   // .ww...b
    73,    // bww...b
    -13,   // www...b
    2,     // ...b..b
    -26,   // b..b..b
    -89,   // w..b..b
    18,    // .b.b..b
    -62,   // bb.b..b
    -55,   // wb.b..b
    8,     // .w.b..b
    87,    // bw.b..b
    -30,   // ww.b..b
    -27,   // ..bb..b
    99,    // b.bb..b
    53,    // w.bb..b
    61,    // .bbb..b
    -15,   // bbbb..b
    26,    // wbbb..b
    -14,   // .wbb..b
    -63,   // bwbb..b
    -99,   // wwbb..b
    46,    // ..wb..b
    -13,   // b.wb..b
    -94,   // w.wb..b
    -15,   // .bwb..b
    4,     // bbwb..b
    2,     // wbwb..b
    -55,   // .wwb..b
    40,    // bwwb..b
    76,    // wwwb..b
    23,    // ...w..b
    -51,   // b..w..b
    89,    // w..w..b
    -21,   // .b.w..b
    -24,   // bb.w..b
    -28,   // wb.w..b
    -67,   // .w.w..b
    35,    // bw.w..b
    24,    // ww.w..b
    -19,   // ..bw..b
    48,    // b.bw..b
    -21,   // w.bw..b
    74,    // .bbw..b
    -38,   // bbbw..b
    18,    // wbbw..b
    -83,   // .wbw..b
    -1,    // bwbw..b
    41,    // wwbw..b
    128,   // ..ww..b
    -134,  // b.ww..b
    114,   // w.ww..b
    -18,   // .bww..b
    -38,   // bbww..b
    -24,   // wbww..b
    1,     // .www..b
    -24,   // bwww..b
    -1,    // wwww..b
    -16,   // ....b.b
    -97,   // b...b.b
    -19,   // w...b.b
    3,     // .b..b.b
    24,    // bb..b.b
    -73,   // wb..b.b
    1,     // .w..b.b
    1,     // bw..b.b
    -33,   // ww..b.b
    3,     // ..b.b.b
    31,    // b.b.b.b
    -36,   // w.b.b.b
    46,    // .bb.b.b
    -17,   // bbb.b.b
    -32,   // wbb.b.b
    -41,   // .wb.b.b
    15,    // bwb.b.b
    -23,   // wwb.b.b
    32,    // ..w.b.b
    10,    // b.w.b.b
    0,     // w.w.b.b
    -96,   // .bw.b.b
    -8,    // bbw.b.b
    19,    // wbw.b.b
    21,    // .ww.b.b
    95,    // bww.b.b
    33,    // www.b.b
    48,    // ...bb.b
    99,    // b..bb.b
    -114,  // w..bb.b
    40,    // .b.bb.b
    -168,  // bb.bb.b
    -22,   // wb.bb.b
    -50,   // .w.bb.b
    4,     // bw.bb.b
    -75,   // ww.bb.b
    49,    // ..bbb.b
    -3,    // b.bbb.b
    31,    // w.bbb.b
    34,    // .bbbb.b
    108,   // bbbbb.b
    40,    // wbbbb.b
    58,    // .wbbb.b
    33,    // bwbbb.b
    28,    // wwbbb.b
    36,    // ..wbb.b
    -33,   // b.wbb.b
    -8,    // w.wbb.b
    -33,   // .bwbb.b
    -68,   // bbwbb.b
    -68,   // wbwbb.b
    -21,   // .wwbb.b
    11,    // bwwbb.b
    57,    // wwwbb.b
    -72,   // ...wb.b
    48,    // b..wb.b
    94,    // w..wb.b
    8,     // .b.wb.b
    24,    // bb.wb.b
    -69,   // wb.wb.b
    10,    // .w.wb.b
    -52,   // bw.wb.b
    82,    // ww.wb.b
    -5,    // ..bwb.b
    0,     // b.bwb.b
    -28,   // w.bwb.b
    26,    // .bbwb.b
    -99,   // bbbwb.b
    39,    // wbbwb.b
    6,     // .wbwb.b
    26,    // bwbwb.b
    27,    // wwbwb.b
    -13,   // ..wwb.b
    -50,   // b.wwb.b
    8,     // w.wwb.b
    8,     // .bwwb.b
    1,     // bbwwb.b
    83,    // wbwwb.b
    -23,   // .wwwb.b
    12,    // bwwwb.b
    -75,   // wwwwb.b
    41,    // ....w.b
    84,    // b...w.b
    -6,    // w...w.b
    -41,   // .b..w.b
    -40,   // bb..w.b
    -35,   // wb..w.b
    -7,    // .w..w.b
    -7,    // bw..w.b
    -38,   // ww..w.b
    21,    // ..b.w.b
    10,    // b.b.w.b
    0,     // w.b.w.b
    52,    // .bb.w.b
    -51,   // bbb.w.b
    29,    // wbb.w.b
    65,    // .wb.w.b
    0,     // bwb.w.b
    -34,   // wwb.w.b
    38,    // ..w.w.b
    -16,   // b.w.w.b
    36,    // w.w.w.b
    -17,   // .bw.w.b
    -31,   // bbw.w.b
    -12,   // wbw.w.b
    35,    // .ww.w.b
    47,    // bww.w.b
    26,    // www.w.b
    0,     // ...bw.b
    -13,   // b..bw.b
    21,    // w..bw.b
    -57,   // .b.bw.b
    -47,   // bb.bw.b
    70,    // wb.bw.b
    82,    // .w.bw.b
    36,    // bw.bw.b
    25,    // ww.bw.b
    -37,   // ..bbw.b
    -33,   // b.bbw.b
    -57,   // w.bbw.b
    27,    // .bbbw.b
    0,     // bbbbw.b
    -3,    // wbbbw.b
    -2,    // .wbbw.b
    -92,   // bwbbw.b
    26,    // wwbbw.b
    41,    // ..wbw.b
    14,    // b.wbw.b
    28,    // w.wbw.b
    32,    // .bwbw.b
    13,    // bbwbw.b
    -74,   // wbwbw.b
    -19,   // .wwbw.b
    50,    // bwwbw.b
    26,    // wwwbw.b
    -24,   // ...ww.b
    -134,  // b..ww.b
    -53,   // w..ww.b
    -26,   // .b.ww.b
    -15,   // bb.ww.b
    -7,    // wb.ww.b
    -25,   // .w.ww.b
    -29,   // bw.ww.b
    -51,   // ww.ww.b
    -4,    // ..bww.b
    -50,   // b.bww.b
    57,    // w.bww.b
    -3,    // .bbww.b
    8,     // bbbww.b
    -20,   // wbbww.b
    13,    // .wbww.b
    -7,    // bwbww.b
    -80,   // wwbww.b
    -8,    // ..www.b
    20,    // b.www.b
    -31,   // w.www.b
    -52,   // .bwww.b
    -30,   // bbwww.b
    1,     // wbwww.b
    -50,   // .wwww.b
    -93,   // bwwww.b
    -51,   // wwwww.b
    22,    // .....bb
    10,    // b....bb
    -38,   // w....bb
    8,     // .b...bb
    7,     // bb...bb
    75,    // wb...bb
    6,     // .w...bb
    55,    // bw...bb
    0,     // ww...bb
    105,   // ..b..bb
    24,    // b.b..bb
    38,    // w.b..bb
    49,    // .bb..bb
    -27,   // bbb..bb
    66,    // wbb..bb
    65,    // .wb..bb
    -144,  // bwb..bb
    -20,   // wwb..bb
    58,    // ..w..bb
    -40,   // b.w..bb
    33,    // w.w..bb
    64,    // .bw..bb
    9,     // bbw..bb
    30,    // wbw..bb
    0,     // .ww..bb
    88,    // bww..bb
    -8,    // www..bb
    41,    // ...b.bb
    -62,   // b..b.bb
    -24,   // w..b.bb
    -13,   // .b.b.bb
    -49,   // bb.b.bb
    -38,   // wb.b.bb
    42,    // .w.b.bb
    -2,    // bw.b.bb
    -85,   // ww.b.bb
    16,    // ..bb.bb
    -168,  // b.bb.bb
    51,    // w.bb.bb
    -4,    // .bbb.bb
    -14,   // bbbb.bb
    -14,   // wbbb.bb
    44,    // .wbb.bb
    -34,   // bwbb.bb
    11,    // wwbb.bb
    -18,   // ..wb.bb
    -47,   // b.wb.bb
    -82,   // w.wb.bb
    -38,   // .bwb.bb
    70,    // bbwb.bb
    -44,   // wbwb.bb
    28,    // .wwb.bb
    76,    // bwwb.bb
    -53,   // wwwb.bb
    56,    // ...w.bb
    -24,   // b..w.bb
    30,    // w..w.bb
    -65,   // .b.w.bb
    6,     // bb.w.bb
    2,     // wb.w.bb
    10,    // .w.w.bb
    -26,   // bw.w.bb
    85,    // ww.w.bb
    -17,   // ..bw.bb
    24,    // b.bw.bb
    -25,   // w.bw.bb
    -8,    // .bbw.bb
    -23,   // bbbw.bb
    -30,   // wbbw.bb
    -43,   // .wbw.bb
    -22,   // bwbw.bb
    11,    // wwbw.bb
    -68,   // ..ww.bb
    -15,   // b.ww.bb
    75,    // w.ww.bb
    -38,   // .bww.bb
    -18,   // bbww.bb
    -50,   // wbww.bb
    43,    // .www.bb
    8,     // bwww.bb
    25,    // wwww.bb
    93,    // ....bbb
    -66,   // b...bbb
    13,    // w...bbb
    -20,   // .b..bbb
    -27,   // bb..bbb
    -10,   // wb..bbb
    10,    // .w..bbb
    -25,   // bw..bbb
    8,     // ww..bbb
    207,   // ..b.bbb
    -17,   // b.b.bbb
    -26,   // w.b.bbb
    -55,   // .bb.bbb
    -40,   // bbb.bbb
    -62,   // wbb.bbb
    -43,   // .wb.bbb
    58,    // bwb.bbb
    3,     // wwb.bbb
    -20,   // ..w.bbb
    -51,   // b.w.bbb
    -33,   // w.w.bbb
    20,    // .bw.bbb
    13,    // bbw.bbb
    -40,   // wbw.bbb
    12,    // .ww.bbb
    -12,   // bww.bbb
    0,     // www.bbb
    263,   // ...bbbb
    -15,   // b..bbbb
    1,     // w..bbbb
    -27,   // .b.bbbb
    -14,   // bb.bbbb
    -29,   // wb.bbbb
    95,    // .w.bbbb
    -8,    // bw.bbbb
    -25,   // ww.bbbb
    -10,   // ..bbbbb
    108,   // b.bbbbb
    51,    // w.bbbbb
    34,    // .bbbbbb
    -72,   // bbbbbbb
    39,    // wbbbbbb
    -49,   // .wbbbbb
    64,    // bwbbbbb
    -49,   // wwbbbbb
    33,    // ..wbbbb
    0,     // b.wbbbb
    75,    // w.wbbbb
    13,    // .bwbbbb
    -101,  // bbwbbbb
    -9,    // wbwbbbb
    46,    // .wwbbbb
    67,    // bwwbbbb
    45,    // wwwbbbb
    -66,   // ...wbbb
    -38,   // b..wbbb
    -76,   // w..wbbb
    -40,   // .b.wbbb
    -23,   // bb.wbbb
    13,    // wb.wbbb
    -2,    // .w.wbbb
    -58,   // bw.wbbb
    53,    // ww.wbbb
    -62,   // ..bwbbb
    -99,   // b.bwbbb
    -26,   // w.bwbbb
    8,     // .bbwbbb
    -43,   // bbbwbbb
    -2,    // wbbwbbb
    116,   // .wbwbbb
    -13,   // bwbwbbb
    -56,   // wwbwbbb
    18,    // ..wwbbb
    8,     // b.wwbbb
    -57,   // w.wwbbb
    35,    // .bwwbbb
    5,     // bbwwbbb
    6,     // wbwwbbb
    -16,   // .wwwbbb
    45,    // bwwwbbb
    -45,   // wwwwbbb
    13,    // ....wbb
    -51,   // b...wbb
    -25,   // w...wbb
    -30,   // .b..wbb
    9,     // bb..wbb
    25,    // wb..wbb
    -14,   // .w..wbb
    68,    // bw..wbb
    20,    // ww..wbb
    -19,   // ..b.wbb
    -8,    // b.b.wbb
    34,    // w.b.wbb
    5,     // .bb.wbb
    13,    // bbb.wbb
    29,    // wbb.wbb
    -58,   // .wb.wbb
    31,    // bwb.wbb
    0,     // wwb.wbb
    -21,   // ..w.wbb
    -31,   // b.w.wbb
    23,    // w.w.wbb
    70,    // .bw.wbb
    16,    // bbw.wbb
    52,    // wbw.wbb
    4,     // .ww.wbb
    -22,   // bww.wbb
    -3,    // www.wbb
    -2,    // ...bwbb
    4,     // b..bwbb
    -41,   // w..bwbb
    60,    // .b.bwbb
    70,    // bb.bwbb
    5,     // wb.bwbb
    71,    // .w.bwbb
    -99,   // bw.bwbb
    -11,   // ww.bwbb
    -46,   // ..bbwbb
    -68,   // b.bbwbb
    80,    // w.bbwbb
    -4,    // .bbbwbb
    -101,  // bbbbwbb
    38,    // wbbbwbb
    6,     // .wbbwbb
    0,     // bwbbwbb
    85,    // wwbbwbb
    -88,   // ..wbwbb
    13,    // b.wbwbb
    -27,   // w.wbwbb
    11,    // .bwbwbb
    -60,   // bbwbwbb
    17,    // wbwbwbb
    -7,    // .wwbwbb
    43,    // bwwbwbb
    56,    // wwwbwbb
    -75,   // ...wwbb
    -38,   // b..wwbb
    99,    // w..wwbb
    -38,   // .b.wwbb
    -18,   // bb.wwbb
    73,    // wb.wwbb
    35,    // .w.wwbb
    -70,   // bw.wwbb
    -11,   // ww.wwbb
    17,    // ..bwwbb
    1,     // b.bwwbb
    -26,   // w.bwwbb
    34,    // .bbwwbb
    5,     // bbbwwbb
    -56,   // wbbwwbb
    44,    // .wbwwbb
    -20,   // bwbwwbb
    -85,   // wwbwwbb
    19,    // ..wwwbb
    -30,   // b.wwwbb
    -28,   // w.wwwbb
    5,     // .bwwwbb
    29,    // bbwwwbb
    0,     // wbwwwbb
    -82,   // .wwwwbb
    11,    // bwwwwbb
    49,    // wwwwwbb
    39,    // .....wb
    70,    // b....wb
    53,    // w....wb
    7,     // .b...wb
    55,    // bb...wb
    0,     // wb...wb
    -11,   // .w...wb
    83,    // bw...wb
    -75,   // ww...wb
    47,    // ..b..wb
    1,     // b.b..wb
    35,    // w.b..wb
    -10,   // .bb..wb
    -25,   // bbb..wb
    7,     // wbb..wb
    1,     // .wb..wb
    -18,   // bwb..wb
    -25,   // wwb..wb
    17,    // ..w..wb
    -7,    // b.w..wb
    73,    // w.w..wb
    0,     // .bw..wb
    68,    // bbw..wb
    -44,   // wbw..wb
    -8,    // .ww..wb
    9,     // bww..wb
    10,    // www..wb
    36,    // ...b.wb
    87,    // b..b.wb
    28,    // w..b.wb
    21,    // .b.b.wb
    -2,    // bb.b.wb
    -32,   // wb.b.wb
    -37,   // .w.b.wb
    -55,   // bw.b.wb
    -2,    // ww.b.wb
    -52,   // ..bb.wb
    4,     // b.bb.wb
    7,     // w.bb.wb
    7,     // .bbb.wb
    -8,    // bbbb.wb
    96,    // wbbb.wb
    5,     // .wbb.wb
    -48,   // bwbb.wb
    -73,   // wwbb.wb
    40,    // ..wb.wb
    36,    // b.wb.wb
    69,    // w.wb.wb
    6,     // .bwb.wb
    -99,   // bbwb.wb
    13,    // wbwb.wb
    -3,    // .wwb.wb
    -22,   // bwwb.wb
    -13,   // wwwb.wb
    54,    // ...w.wb
    35,    // b..w.wb
    55,    // w..w.wb
    -34,   // .b.w.wb
    -26,   // bb.w.wb
    32,    // wb.w.wb
    11,    // .w.w.wb
    -1,    // bw.w.wb
    38,    // ww.w.wb
    62,    // ..bw.wb
    -52,   // b.bw.wb
    -70,   // w.bw.wb
    12,    // .bbw.wb
    -58,   // bbbw.wb
    -69,   // wbbw.wb
    4,     // .wbw.wb
    -93,   // bwbw.wb
    -5,    // wwbw.wb
    91,    // ..ww.wb
    -29,   // b.ww.wb
    22,    // w.ww.wb
    -12,   // .bww.wb
    -70,   // bbww.wb
    -38,   // wbww.wb
    -25,   // .www.wb
    -75,   // bwww.wb
    29,    // wwww.wb
    -35,   // ....bwb
    -5,    // b...bwb
    -21,   // w...bwb
    3,     // .b..bwb
    -144,  // bb..bwb
    44,    // wb..bwb
    -38,   // .w..bwb
    -18,   // bw..bwb
    -30,   // ww..bwb
    22,    // ..b.bwb
    15,    // b.b.bwb
    12,    // w.b.bwb
    -76,   // .bb.bwb
    58,    // bbb.bwb
    19,    // wbb.bwb
    65,    // .wb.bwb
    -8,    // bwb.bwb
    -52,   // wwb.bwb
    50,    // ..w.bwb
    0,     // b.w.bwb
    -19,   // w.w.bwb
    -62,   // .bw.bwb
    31,    // bbw.bwb
    0,     // wbw.bwb
    128,   // .ww.bwb
    43,    // bww.bwb
    40,    // www.bwb
    97,    // ...bbwb
    -63,   // b..bbwb
    24,    // w..bbwb
    93,    // .b.bbwb
    -34,   // bb.bbwb
    38,    // wb.bbwb
    6,     // .w.bbwb
    -48,   // bw.bbwb
    50,    // ww.bbwb
    -70,   // ..bbbwb
    33,    // b.bbbwb
    -1,    // w.bbbwb
    -45,   // .bbbbwb
    64,    // bbbbbwb
    -44,   // wbbbbwb
    -39,   // .wbbbwb
    1,     // bwbbbwb
    0,     // wwbbbwb
    -11,   // ..wbbwb
    -92,   // b.wbbwb
    -83,   // w.wbbwb
    -22,   // .bwbbwb
    0,     // bbwbbwb
    3,     // wbwbbwb
    -28,   // .wwbbwb
    -20,   // bwwbbwb
    -6,    // wwwbbwb
    -62,   // ...wbwb
    -1,    // b..wbwb
    -2,    // w..wbwb
    -37,   // .b.wbwb
    -22,   // bb.wbwb
    -13,   // wb.wbwb
    2,     // .w.wbwb
    -93,   // bw.wbwb
    44,    // ww.wbwb
    2,     // ..bwbwb
    26,    // b.bwbwb
    74,    // w.bwbwb
    29,    // .bbwbwb
    -13,   // bbbwbwb
    -51,   // wbbwbwb
    -13,   // .wbwbwb
    -9,    // bwbwbwb
    -17,   // wwbwbwb
    44,    // ..wwbwb
    -7,    // b.wwbwb
    68,    // w.wwbwb
    66,    // .bwwbwb
    -20,   // bbwwbwb
    -3,    // wbwwbwb
    -42,   // .wwwbwb
    -20,   // bwwwbwb
    9,     // wwwwbwb
    1,     // ....wwb
    73,    // b...wwb
    -138,  // w...wwb
    -17,   // .b..wwb
    88,    // bb..wwb
    -7,    // wb..wwb
    -69,   // .w..wwb
    9,     // bw..wwb
    -66,   // ww..wwb
    -71,   // ..b.wwb
    95,    // b.b.wwb
    -29,   // w.b.wwb
    -17,   // .bb.wwb
    -12,   // bbb.wwb
    0,     // wbb.wwb
    -18,   // .wb.wwb
    43,    // bwb.wwb
    -29,   // wwb.wwb
    -33,   // ..w.wwb
    47,    // b.w.wwb
    32,    // w.w.wwb
    87,    // .bw.wwb
    -22,   // bbw.wwb
    -19,   // wbw.wwb
    -82,   // .ww.wwb
    -45,   // bww.wwb
    62,    // www.wwb
    20,    // ...bwwb
    40,    // b..bwwb
    -18,   // w..bwwb
    -11,   // .b.bwwb
    76,    // bb.bwwb
    69,    // wb.bwwb
    7,     // .w.bwwb
    -22,   // bw.bwwb
    30,    // ww.bwwb
    -19,   // ..bbwwb
    11,    // b.bbwwb
    20,    // w.bbwwb
    12,    // .bbbwwb
    67,    // bbbbwwb
    52,    // wbbbwwb
    6,     // .wbbwwb
    -20,   // bwbbwwb
    56,    // wwbbwwb
    -6,    // ..wbwwb
    50,    // b.wbwwb
    -39,   // w.wbwwb
    -91,   // .bwbwwb
    43,    // bbwbwwb
    51,    // wbwbwwb
    12,    // .wwbwwb
    -88,   // bwwbwwb
    2,     // wwwbwwb
    85,    // ...wwwb
    -24,   // b..wwwb
    -26,   // w..wwwb
    18,    // .b.wwwb
    8,     // bb.wwwb
    -96,   // wb.wwwb
    -89,   // .w.wwwb
    -75,   // bw.wwwb
    14,    // ww.wwwb
    5,     // ..bwwwb
    12,    // b.bwwwb
    3,     // w.bwwwb
    -52,   // .bbwwwb
    45,    // bbbwwwb
    -52,   // wbbwwwb
    -41,   // .wbwwwb
    -20,   // bwbwwwb
    -38,   // wwbwwwb
    -68,   // ..wwwwb
    -93,   // b.wwwwb
    -40,   // w.wwwwb
    146,   // .bwwwwb
    11,    // bbwwwwb
    44,    // wbwwwwb
    55,    // .wwwwwb
    56,    // bwwwwwb
    -39,   // wwwwwwb
    8,     // ......w
    0,     // b.....w
    -17,   // w.....w
    -22,   // .b....w
    -38,   // bb....w
    -70,   // wb....w
    18,    // .w....w
    53,    // bw....w
    -10,   // ww....w
    10,    // ..b...w
    -19,   // b.b...w
    -84,   // w.b...w
    82,    // .bb...w
    13,    // bbb...w
    -73,   // wbb...w
    34,    // .wb...w
    -21,   // bwb...w
    51,    // wwb...w
    11,    // ..w...w
    -6,    // b.w...w
    97,    // w.w...w
    41,    // .bw...w
    -25,   // bbw...w
    5,     // wbw...w
    3,     // .ww...w
    -138,  // bww...w
    66,    // www...w
    -23,   // ...b..w
    -89,   // b..b..w
    51,    // w..b..w
    67,    // .b.b..w
    -24,   // bb.b..w
    -35,   // wb.b..w
    21,    // .w.b..w
    28,    // bw.b..w
    24,    // ww.b..w
    -128,  // ..bb..w
    -114,  // b.bb..w
    134,   // w.bb..w
    -1,    // .bbb..w
    1,     // bbbb..w
    24,    // wbbb..w
    18,    // .wbb..w
    24,    // bwbb..w
    38,    // wwbb..w
    19,    // ..wb..w
    21,    // b.wb..w
    -48,   // w.wb..w
    83,    // .bwb..w
    -41,   // bbwb..w
    1,     // wbwb..w
    -74,   // .wwb..w
    -18,   // bwwb..w
    38,    // wwwb..w
    -2,    // ...w..w
    89,    // b..w..w
    26,    // w..w..w
    -8,    // .b.w..w
    30,    // bb.w..w
    -87,   // wb.w..w
    -18,   // .w.w..w
    55,    // bw.w..w
    62,    // ww.w..w
    -46,   // ..bw..w
    94,    // b.bw..w
    13,    // w.bw..w
    55,    // .bbw..w
    -76,   // bbbw..w
    -40,   // wbbw..w
    15,    // .wbw..w
    -2,    // bwbw..w
    -4,    // wwbw..w
    27,    // ..ww..w
    -53,   // b.ww..w
    -99,   // w.ww..w
    14,    // .bww..w
    99,    // bbww..w
    63,    // wbww..w
    -61,   // .www..w
    -26,   // bwww..w
    15,    // wwww..w
    -41,   // ....b.w
    6,     // b...b.w
    -84,   // w...b.w
    7,     // .b..b.w
    38,    // bb..b.w
    7,     // wb..b.w
    41,    // .w..b.w
    35,    // bw..b.w
    40,    // ww..b.w
    -38,   // ..b.b.w
    -36,   // b.b.b.w
    16,    // w.b.b.w
    -35,   // .bb.b.w
    -26,   // bbb.b.w
    -47,   // wbb.b.w
    17,    // .wb.b.w
    12,    // bwb.b.w
    31,    // wwb.b.w
    -21,   // ..w.b.w
    0,     // b.w.b.w
    -10,   // w.w.b.w
    -65,   // .bw.b.w
    34,    // bbw.b.w
    0,     // wbw.b.w
    -52,   // .ww.b.w
    -29,   // bww.b.w
    51,    // www.b.w
    24,    // ...bb.w
    53,    // b..bb.w
    134,   // w..bb.w
    25,    // .b.bb.w
    51,    // bb.bb.w
    29,    // wb.bb.w
    26,    // .w.bb.w
    7,     // bw.bb.w
    15,    // ww.bb.w
    8,     // ..bbb.w
    31,    // b.bbb.w
    -20,   // w.bbb.w
    50,    // .bbbb.w
    51,    // bbbbb.w
    93,    // wbbbb.w
    52,    // .wbbb.w
    -1,    // bwbbb.w
    30,    // wwbbb.w
    4,     // ..wbb.w
    -57,   // b.wbb.w
    50,    // w.wbb.w
    -13,   // .bwbb.w
    80,    // bbwbb.w
    7,     // wbwbb.w
    3,     // .wwbb.w
    20,    // bwwbb.w
    -8,    // wwwbb.w
    0,     // ...wb.w
    -21,   // b..wb.w
    13,    // w..wb.w
    -82,   // .b.wb.w
    -25,   // bb.wb.w
    -36,   // wb.wb.w
    57,    // .w.wb.w
    -70,   // bw.wb.w
    47,    // ww.wb.w
    -41,   // ..bwb.w
    -28,   // b.bwb.w
    -14,   // w.bwb.w
    19,    // .bbwb.w
    -26,   // bbbwb.w
    -50,   // wbbwb.w
    -32,   // .wbwb.w
    74,    // bwbwb.w
    -13,   // wwbwb.w
    37,    // ..wwb.w
    57,    // b.wwb.w
    33,    // w.wwb.w
    2,     // .bwwb.w
    -26,   // bbwwb.w
    92,    // wbwwb.w
    -27,   // .wwwb.w
    3,     // bwwwb.w
    0,     // wwwwb.w
    16,    // ....w.w
    19,    // b...w.w
    97,    // w...w.w
    -1,    // .b..w.w
    33,    // bb..w.w
    -1,    // wb..w.w
    -3,    // .w..w.w
    73,    // bw..w.w
    -24,   // ww..w.w
    -32,   // ..b.w.w
    0,     // b.b.w.w
    -10,   // w.b.w.w
    -21,   // .bb.w.w
    -33,   // bbb.w.w
    -95,   // wbb.w.w
    96,    // .wb.w.w
    -19,   // bwb.w.w
    8,     // wwb.w.w
    -3,    // ..w.w.w
    36,    // b.w.w.w
    -31,   // w.w.w.w
    41,    // .bw.w.w
    23,    // bbw.w.w
    -15,   // wbw.w.w
    -46,   // .ww.w.w
    32,    // bww.w.w
    17,    // www.w.w
    72,    // ...bw.w
    -94,   // b..bw.w
    -48,   // w..bw.w
    -10,   // .b.bw.w
    -82,   // bb.bw.w
    52,    // wb.bw.w
    -8,    // .w.bw.w
    69,    // bw.bw.w
    -24,   // ww.bw.w
    13,    // ..bbw.w
    -8,    // b.bbw.w
    50,    // w.bbw.w
    23,    // .bbbw.w
    75,    // bbbbw.w
    -12,   // wbbbw.w
    -8,    // .wbbw.w
    -83,   // bwbbw.w
    -1,    // wwbbw.w
    5,     // ..wbw.w
    28,    // b.wbw.w
    0,     // w.wbw.w
    -6,    // .bwbw.w
    -27,   // bbwbw.w
    -26,   // wbwbw.w
    -26,   // .wwbw.w
    -39,   // bwwbw.w
    99,    // wwwbw.w
    -48,   // ...ww.w
    114,   // b..ww.w
    -99,   // w..ww.w
    50,    // .b.ww.w
    75,    // bb.ww.w
    -4,    // wb.ww.w
    -40,   // .w.ww.w
    22,    // bw.ww.w
    168,   // ww.ww.w
    -36,   // ..bww.w
    8,     // b.bww.w
    33,    // w.bww.w
    21,    // .bbww.w
    -57,   // bbbww.w
    -11,   // wbbww.w
    33,    // .wbww.w
    68,    // bwbww.w
    68,    // wwbww.w
    -49,   // ..www.w
    -31,   // b.www.w
    3,     // w.www.w
    -58,   // .bwww.w
    -28,   // bbwww.w
    -33,   // wbwww.w
    -34,   // .wwww.w
    -40,   // bwwww.w
    -108,  // wwwww.w
    -39,   // .....bw
    -53,   // b....bw
    -70,   // w....bw
    11,    // .b...bw
    75,    // bb...bw
    -83,   // wb...bw
    -7,    // .w...bw
    0,     // bw...bw
    -55,   // ww...bw
    -17,   // ..b..bw
    -73,   // b.b..bw
    7,     // w.b..bw
    8,     // .bb..bw
    -10,   // bbb..bw
    -9,    // wbb..bw
    0,     // .wb..bw
    44,    // bwb..bw
    -68,   // wwb..bw
    -47,   // ..w..bw
    -35,   // b.w..bw
    -1,    // w.w..bw
    -1,    // .bw..bw
    25,    // bbw..bw
    18,    // wbw..bw
    10,    // .ww..bw
    -7,    // bww..bw
    25,    // www..bw
    -54,   // ...b.bw
    -55,   // b..b.bw
    -35,   // w..b.bw
    -11,   // .b.b.bw
    -38,   // bb.b.bw
    1,     // wb.b.bw
    34,    // .w.b.bw
    -32,   // bw.b.bw
    26,    // ww.b.bw
    -91,   // ..bb.bw
    -22,   // b.bb.bw
    29,    // w.bb.bw
    25,    // .bbb.bw
    -29,   // bbbb.bw
    75,    // wbbb.bw
    12,    // .wbb.bw
    38,    // bwbb.bw
    70,    // wwbb.bw
    -62,   // ..wb.bw
    70,    // b.wb.bw
    52,    // w.wb.bw
    -4,    // .bwb.bw
    5,     // bbwb.bw
    93,    // wbwb.bw
    -12,   // .wwb.bw
    69,    // bwwb.bw
    58,    // wwwb.bw
    -36,   // ...w.bw
    -28,   // b..w.bw
    -87,   // w..w.bw
    37,    // .b.w.bw
    2,     // bb.w.bw
    55,    // wb.w.bw
    -21,   // .w.w.bw
    32,    // bw.w.bw
    2,     // ww.w.bw
    -40,   // ..bw.bw
    -69,   // b.bw.bw
    -36,   // w.bw.bw
    3,     // .bbw.bw
    13,    // bbbw.bw
    22,    // wbbw.bw
    -6,    // .wbw.bw
    -13,   // bwbw.bw
    99,    // wwbw.bw
    52,    // ..ww.bw
    -7,    // b.ww.bw
    -4,    // w.ww.bw
    -5,    // .bww.bw
    73,    // bbww.bw
    48,    // wbww.bw
    -7,    // .www.bw
    -96,   // bwww.bw
    8,     // wwww.bw
    -1,    // ....bbw
    138,   // b...bbw
    -73,   // w...bbw
    69,    // .b..bbw
    66,    // bb..bbw
    -9,    // wb..bbw
    17,    // .w..bbw
    7,     // bw..bbw
    -88,   // ww..bbw
    33,    // ..b.bbw
    -32,   // b.b.bbw
    -47,   // w.b.bbw
    82,    // .bb.bbw
    -62,   // bbb.bbw
    45,    // wbb.bbw
    -87,   // .wb.bbw
    19,    // bwb.bbw
    22,    // wwb.bbw
    71,    // ..w.bbw
    29,    // b.w.bbw
    -95,   // w.w.bbw
    18,    // .bw.bbw
    29,    // bbw.bbw
    -43,   // wbw.bbw
    17,    // .ww.bbw
    0,     // bww.bbw
    12,    // www.bbw
    -85,   // ...bbbw
    26,    // b..bbbw
    24,    // w..bbbw
    89,    // .b.bbbw
    -14,   // bb.bbbw
    75,    // wb.bbbw
    -18,   // .w.bbbw
    96,    // bw.bbbw
    -8,    // ww.bbbw
    68,    // ..bbbbw
    40,    // b.bbbbw
    93,    // w.bbbbw
    -55,   // .bbbbbw
    39,    // bbbbbbw
    -56,   // wbbbbbw
    -146,  // .wbbbbw
    -44,   // bwbbbbw
    -11,   // wwbbbbw
    -5,    // ..wbbbw
    -3,    // b.wbbbw
    -12,   // w.wbbbw
    41,    // .bwbbbw
    38,    // bbwbbbw
    20,    // wbwbbbw
    52,    // .wwbbbw
    52,    // bwwbbbw
    -45,   // wwwbbbw
    -20,   // ...wbbw
    18,    // b..wbbw
    -40,   // w..wbbw
    -7,    // .b.wbbw
    -30,   // bb.wbbw
    22,    // wb.wbbw
    11,    // .w.wbbw
    -69,   // bw.wbbw
    -76,   // ww.wbbw
    6,     // ..bwbbw
    39,    // b.bwbbw
    -50,   // w.bwbbw
    -12,   // .bbwbbw
    -2,    // bbbwbbw
    88,    // wbbwbbw
    91,    // .wbwbbw
    -51,   // bwbwbbw
    -43,   // wwbwbbw
    19,    // ..wwbbw
    -20,   // b.wwbbw
    -11,   // w.wwbbw
    -6,    // .bwwbbw
    -56,   // bbwwbbw
    20,    // wbwwbbw
    -12,   // .wwwbbw
    -52,   // bwwwbbw
    -67,   // wwwwbbw
    35,    // ....wbw
    21,    // b...wbw
    5,     // w...wbw
    38,    // .b..wbw
    30,    // bb..wbw
    18,    // wb..wbw
    -3,    // .w..wbw
    -44,   // bw..wbw
    144,   // ww..wbw
    -50,   // ..b.wbw
    19,    // b.b.wbw
    0,     // w.b.wbw
    -128,  // .bb.wbw
    -40,   // bbb.wbw
    -43,   // wbb.wbw
    62,    // .wb.wbw
    0,     // bwb.wbw
    -31,   // wwb.wbw
    -22,   // ..w.wbw
    -12,   // b.w.wbw
    -15,   // w.w.wbw
    -65,   // .bw.wbw
    52,    // bbw.wbw
    8,     // wbw.wbw
    76,    // .ww.wbw
    -19,   // bww.wbw
    -58,   // www.wbw
    62,    // ...bwbw
    2,     // b..bwbw
    1,     // w..bwbw
    -2,    // .b.bwbw
    -44,   // bb.bwbw
    93,    // wb.bwbw
    37,    // .w.bwbw
    13,    // bw.bwbw
    22,    // ww.bwbw
    -44,   // ..bbwbw
    -68,   // b.bbwbw
    7,     // w.bbwbw
    42,    // .bbbwbw
    -9,    // bbbbwbw
    20,    // wbbbwbw
    -66,   // .wbbwbw
    3,     // bwbbwbw
    20,    // wwbbwbw
    -2,    // ..wbwbw
    -74,   // b.wbwbw
    -26,   // w.wbwbw
    13,    // .bwbwbw
    17,    // bbwbwbw
    9,     // wbwbwbw
    -29,   // .wwbwbw
    51,    // bwwbwbw
    13,    // wwwbwbw
    -97,   // ...wwbw
    -24,   // b..wwbw
    63,    // w..wwbw
    -6,    // .b.wwbw
    -50,   // bb.wwbw
    48,    // wb.wwbw
    -93,   // .w.wwbw
    -38,   // bw.wwbw
    34,    // ww.wwbw
    11,    // ..bwwbw
    83,    // b.bwwbw
    92,    // w.bwwbw
    28,    // .bbwwbw
    6,     // bbbwwbw
    20,    // wbbwwbw
    22,    // .wbwwbw
    -3,    // bwbwwbw
    0,     // wwbwwbw
    70,    // ..wwwbw
    1,     // b.wwwbw
    -33,   // w.wwwbw
    39,    // .bwwwbw
    0,     // bbwwwbw
    -1,    // wbwwwbw
    45,    // .wwwwbw
    44,    // bwwwwbw
    -64,   // wwwwwbw
    -22,   // .....ww
    38,    // b....ww
    -10,   // w....ww
    -6,    // .b...ww
    0,     // bb...ww
    -55,   // wb...ww
    -8,    // .w...ww
    -75,   // bw...ww
    -7,    // ww...ww
    -58,   // ..b..ww
    -33,   // b.b..ww
    40,    // w.b..ww
    0,     // .bb..ww
    8,     // bbb..ww
    -88,   // wbb..ww
    -64,   // .wb..ww
    -30,   // bwb..ww
    -9,    // wwb..ww
    -105,  // ..w..ww
    -38,   // b.w..ww
    -24,   // w.w..ww
    -65,   // .bw..ww
    20,    // bbw..ww
    144,   // wbw..ww
    -49,   // .ww..ww
    -66,   // bww..ww
    27,    // www..ww
    -56,   // ...b.ww
    -30,   // b..b.ww
    24,    // w..b.ww
    -10,   // .b.b.ww
    -85,   // bb.b.ww
    26,    // wb.b.ww
    65,    // .w.b.ww
    -2,    // bw.b.ww
    -6,    // ww.b.ww
    68,    // ..bb.ww
    -75,   // b.bb.ww
    15,    // w.bb.ww
    -43,   // .bbb.ww
    -25,   // bbbb.ww
    -8,    // wbbb.ww
    38,    // .wbb.ww
    50,    // bwbb.ww
    18,    // wwbb.ww
    17,    // ..wb.ww
    25,    // b.wb.ww
    -24,   // w.wb.ww
    43,    // .bwb.ww
    -11,   // bbwb.ww
    22,    // wbwb.ww
    8,     // .wwb.ww
    30,    // bwwb.ww
    23,    // wwwb.ww
    -41,   // ...w.ww
    24,    // b..w.ww
    62,    // w..w.ww
    -42,   // .b.w.ww
    85,    // bb.w.ww
    2,     // wb.w.ww
    13,    // .w.w.ww
    38,    // bw.w.ww
    49,    // ww.w.ww
    18,    // ..bw.ww
    82,    // b.bw.ww
    47,    // w.bw.ww
    -28,   // .bbw.ww
    53,    // bbbw.ww
    -76,   // wbbw.ww
    38,    // .wbw.ww
    44,    // bwbw.ww
    -70,   // wwbw.ww
    -16,   // ..ww.ww
    -51,   // b.ww.ww
    168,   // w.ww.ww
    -44,   // .bww.ww
    -11,   // bbww.ww
    34,    // wbww.ww
    4,     // .www.ww
    14,    // bwww.ww
    14,    // wwww.ww
    -13,   // ....bww
    25,    // b...bww
    51,    // w...bww
    14,    // .b..bww
    -20,   // bb..bww
    -68,   // wb..bww
    30,    // .w..bww
    -25,   // bw..bww
    -9,    // ww..bww
    21,    // ..b.bww
    -23,   // b.b.bww
    31,    // w.b.bww
    -4,    // .bb.bww
    3,     // bbb.bww
    22,    // wbb.bww
    -70,   // .wb.bww
    -52,   // bwb.bww
    -16,   // wwb.bww
    19,    // ..w.bww
    -34,   // b.w.bww
    8,     // w.w.bww
    58,    // .bw.bww
    0,     // bbw.bww
    -31,   // wbw.bww
    -5,    // .ww.bww
    -29,   // bww.bww
    -13,   // www.bww
    75,    // ...bbww
    -99,   // b..bbww
    38,    // w..bbww
    -35,   // .b.bbww
    11,    // bb.bbww
    70,    // wb.bbww
    38,    // .w.bbww
    -73,   // bw.bbww
    18,    // ww.bbww
    -19,   // ..bbbww
    28,    // b.bbbww
    30,    // w.bbbww
    82,    // .bbbbww
    -49,   // bbbbbww
    -11,   // wbbbbww
    -5,    // .wbbbww
    0,     // bwbbbww
    -29,   // wwbbbww
    -17,   // ..wbbww
    26,    // b.wbbww
    -1,    // w.wbbww
    -44,   // .bwbbww
    85,    // bbwbbww
    20,    // wbwbbww
    -34,   // .wwbbww
    56,    // bwwbbww
    -5,    // wwwbbww
    2,     // ...wbww
    41,    // b..wbww
    -4,    // w..wbww
    -71,   // .b.wbww
    11,    // bb.wbww
    99,    // wb.wbww
    -60,   // .w.wbww
    -5,    // bw.wbww
    -70,   // ww.wbww
    88,    // ..bwbww
    27,    // b.bwbww
    -13,   // w.bwbww
    7,     // .bbwbww
    -56,   // bbbwbww
    -43,   // wbbwbww
    -11,   // .wbwbww
    -17,   // bwbwbww
    60,    // wwbwbww
    46,    // ..wwbww
    -80,   // b.wwbww
    68,    // w.wwbww
    -6,    // .bwwbww
    -85,   // bbwwbww
    0,     // wbwwbww
    4,     // .wwwbww
    -38,   // bwwwbww
    101,   // wwwwbww
    -93,   // ....www
    -13,   // b...www
    66,    // w...www
    -10,   // .b..www
    -8,    // bb..www
    25,    // wb..www
    20,    // .w..www
    10,    // bw..www
    27,    // ww..www
    20,    // ..b.www
    33,    // b.b.www
    51,    // w.b.www
    -12,   // .bb.www
    0,     // bbb.www
    12,    // wbb.www
    -20,   // .wb.www
    40,    // bwb.www
    -13,   // wwb.www
    -207,  // ..w.www
    26,    // b.w.www
    17,    // w.w.www
    43,    // .bw.www
    -3,    // bbw.www
    -58,   // wbw.www
    55,    // .ww.www
    62,    // bww.www
    40,    // www.www
    66,    // ...bwww
    76,    // b..bwww
    38,    // w..bwww
    2,     // .b.bwww
    -53,   // bb.bwww
    58,    // wb.bwww
    40,    // .w.bwww
    -13,   // bw.bwww
    23,    // ww.bwww
    -18,   // ..bbwww
    57,    // b.bbwww
    -8,    // w.bbwww
    16,    // .bbbwww
    45,    // bbbbwww
    -45,   // wbbbwww
    -35,   // .wbbwww
    -6,    // bwbbwww
    -5,    // wwbbwww
    62,    // ..wbwww
    26,    // b.wbwww
    99,    // w.wbwww
    -116,  // .bwbwww
    56,    // bbwbwww
    13,    // wbwbwww
    -8,    // .wwbwww
    2,     // bwwbwww
    43,    // wwwbwww
    -263,  // ...wwww
    -1,    // b..wwww
    15,    // w..wwww
    -95,   // .b.wwww
    25,    // bb.wwww
    8,     // wb.wwww
    27,    // .w.wwww
    29,    // bw.wwww
    14,    // ww.wwww
    -33,   // ..bwwww
    -75,   // b.bwwww
    0,     // w.bwwww
    -46,   // .bbwwww
    -45,   // bbbwwww
    -67,   // wbbwwww
    -13,   // .wbwwww
    9,     // bwbwwww
    101,   // wwbwwww
    10,    // ..wwwww
    -51,   // b.wwwww
    -108,  // w.wwwww
    49,    // .bwwwww
    49,    // bbwwwww
    -64,   // wbwwwww
    -34,   // .wwwwww
    -39,   // bwwwwww
    72,    // wwwwwww
    -31,   // ccc
    2,     // cc
    -48,   // c
    -18,   // ttt
    133,   // tt
    72,    // t
    -57,   // ct
    98,    // cct
    21,    // ctt
].into_boxed_slice()
