vec![
    0,     // .......
    7,     // b......
    -7,    // w......
    7,     // .b.....
    15,    // bb.....
    -9,    // wb.....
    -7,    // .w.....
    9,     // bw.....
    -15,   // ww.....
    0,     // ..b....
    66,    // b.b....
    -41,   // w.b....
    41,    // .bb....
    166,   // bbb....
    -90,   // wbb....
    -20,   // .wb....
    41,    // bwb....
    46,    // wwb....
    0,     // ..w....
    41,    // b.w....
    -66,   // w.w....
    20,    // .bw....
    -46,   // bbw....
    -41,   // wbw....
    -41,   // .ww....
    90,    // bww....
    -166,  // www....
    -9,    // ...b...
    -1,    // b..b...
    -5,    // w..b...
    -6,    // .b.b...
    150,   // bb.b...
    -42,   // wb.b...
    13,    // .w.b...
    34,    // bw.b...
    -23,   // ww.b...
    -22,   // ..bb...
    66,    // b.bb...
    38,    // w.bb...
    59,    // .bbb...
    313,   // bbbb...
    -101,  // wbbb...
    51,    // .wbb...
    1,     // bwbb...
    22,    // wwbb...
    7,     // ..wb...
    79,    // b.wb...
    -53,   // w.wb...
    -16,   // .bwb...
    -52,   // bbwb...
    -15,   // wbwb...
    7,     // .wwb...
    14,    // bwwb...
    -55,   // wwwb...
    9,     // ...w...
    5,     // b..w...
    1,     // w..w...
    -13,   // .b.w...
    23,    // bb.w...
    -34,   // wb.w...
    6,     // .w.w...
    42,    // bw.w...
    -150,  // ww.w...
    -7,    // ..bw...
    53,    // b.bw...
    -79,   // w.bw...
    -7,    // .bbw...
    55,    // bbbw...
    -14,   // wbbw...
    16,    // .wbw...
    15,    // bwbw...
    52,    // wwbw...
    22,    // ..ww...
    -38,   // b.ww...
    -66,   // w.ww...
    -51,   // .bww...
    -22,   // bbww...
    -1,    // wbww...
    -59,   // .www...
    101,   // bwww...
    -313,  // wwww...
    0,     // ....b..
    19,    // b...b..
    -29,   // w...b..
    10,    // .b..b..
    24,    // bb..b..
    33,    // wb..b..
    -11,   // .w..b..
    7,     // bw..b..
    37,    // ww..b..
    -12,   // ..b.b..
    27,    // b.b.b..
    -35,   // w.b.b..
    -77,   // .bb.b..
    141,   // bbb.b..
    -64,   // wbb.b..
    -6,    // .wb.b..
    -51,   // bwb.b..
    -12,   // wwb.b..
    0,     // ..w.b..
    33,    // b.w.b..
    -36,   // w.w.b..
    -24,   // .bw.b..
    -25,   // bbw.b..
    -32,   // wbw.b..
    35,    // .ww.b..
    11,    // bww.b..
    -78,   // www.b..
    -22,   // ...bb..
    -41,   // b..bb..
    14,    // w..bb..
    -8,    // .b.bb..
    36,    // bb.bb..
    8,     // wb.bb..
    -67,   // .w.bb..
    7,     // bw.bb..
    -26,   // ww.bb..
    26,    // ..bbb..
    103,   // b.bbb..
    -19,   // w.bbb..
    277,   // .bbbb..
    45,    // bbbbb..
    49,    // wbbbb..
    -27,   // .wbbb..
    -45,   // bwbbb..
    -48,   // wwbbb..
    -66,   // ..wbb..
    -22,   // b.wbb..
    -45,   // w.wbb..
    -16,   // .bwbb..
    -28,   // bbwbb..
    43,    // wbwbb..
    22,    // .wwbb..
    -126,  // bwwbb..
    -74,   // wwwbb..
    -7,    // ...wb..
    74,    // b..wb..
    30,    // w..wb..
    -28,   // .b.wb..
    -65,   // bb.wb..
    -8,    // wb.wb..
    48,    // .w.wb..
    8,     // bw.wb..
    9,     // ww.wb..
    -3,    // ..bwb..
    31,    // b.bwb..
    -3,    // w.bwb..
    9,     // .bbwb..
    -144,  // bbbwb..
    73,    // wbbwb..
    17,    // .wbwb..
    -9,    // bwbwb..
    -30,   // wwbwb..
    66,    // ..wwb..
    32,    // b.wwb..
    113,   // w.wwb..
    -5,    // .bwwb..
    51,    // bbwwb..
    -19,   // wbwwb..
    -88,   // .wwwb..
    -5,    // bwwwb..
    -48,   // wwwwb..
    0,     // ....w..
    29,    // b...w..
    -19,   // w...w..
    11,    // .b..w..
    -37,   // bb..w..
    -7,    // wb..w..
    -10,   // .w..w..
    -33,   // bw..w..
    -24,   // ww..w..
    0,     // ..b.w..
    36,    // b.b.w..
    -33,   // w.b.w..
    -35,   // .bb.w..
    78,    // bbb.w..
    -11,   // wbb.w..
    24,    // .wb.w..
    32,    // bwb.w..
    25,    // wwb.w..
    12,    // ..w.w..
    35,    // b.w.w..
    -27,   // w.w.w..
    6,     // .bw.w..
    12,    // bbw.w..
    51,    // wbw.w..
    77,    // .ww.w..
    64,    // bww.w..
    -141,  // www.w..
    7,     // ...bw..
    -30,   // b..bw..
    -74,   // w..bw..
    -48,   // .b.bw..
    -9,    // bb.bw..
    -8,    // wb.bw..
    28,    // .w.bw..
    8,     // bw.bw..
    65,    // ww.bw..
    -66,   // ..bbw..
    -113,  // b.bbw..
    -32,   // w.bbw..
    88,    // .bbbw..
    48,    // bbbbw..
    5,     // wbbbw..
    5,     // .wbbw..
    19,    // bwbbw..
    -51,   // wwbbw..
    3,     // ..wbw..
    3,     // b.wbw..
    -31,   // w.wbw..
    -17,   // .bwbw..
    30,    // bbwbw..
    9,     // wbwbw..
    -9,    // .wwbw..
    -73,   // bwwbw..
    144,   // wwwbw..
    22,    // ...ww..
    -14,   // b..ww..
    41,    // w..ww..
    67,    // .b.ww..
    26,    // bb.ww..
    -7,    // wb.ww..
    8,     // .w.ww..
    -8,    // bw.ww..
    -36,   // ww.ww..
    66,    // ..bww..
    45,    // b.bww..
    22,    // w.bww..
    -22,   // .bbww..
    74,    // bbbww..
    126,   // wbbww..
    16,    // .wbww..
    -43,   // bwbww..
    28,    // wwbww..
    -26,   // ..www..
    19,    // b.www..
    -103,  // w.www..
    27,    // .bwww..
    48,    // bbwww..
    45,    // wbwww..
    -277,  // .wwww..
    -49,   // bwwww..
    -45,   // wwwww..
    7,     // .....b.
    -9,    // b....b.
    -62,   // w....b.
    -12,   // .b...b.
    2,     // bb...b.
    -3,    // wb...b.
    0,     // .w...b.
    5,     // bw...b.
    -15,   // ww...b.
    10,    // ..b..b.
    26,    // b.b..b.
    -32,   // w.b..b.
    35,    // .bb..b.
    11,    // bbb..b.
    115,   // wbb..b.
    -12,   // .wb..b.
    -21,   // bwb..b.
    54,    // wwb..b.
    11,    // ..w..b.
    -21,   // b.w..b.
    -19,   // w.w..b.
    -19,   // .bw..b.
    -7,    // bbw..b.
    -41,   // wbw..b.
    -35,   // .ww..b.
    2,     // bww..b.
    -50,   // www..b.
    -6,    // ...b.b.
    -67,   // b..b.b.
    -32,   // w..b.b.
    -9,    // .b.b.b.
    -50,   // bb.b.b.
    -8,    // wb.b.b.
    -35,   // .w.b.b.
    0,     // bw.b.b.
    -18,   // ww.b.b.
    -8,    // ..bb.b.
    -26,   // b.bb.b.
    97,    // w.bb.b.
    60,    // .bbb.b.
    -73,   // bbbb.b.
    117,   // wbbb.b.
    1,     // .wbb.b.
    -2,    // bwbb.b.
    -27,   // wwbb.b.
    -48,   // ..wb.b.
    -55,   // b.wb.b.
    -53,   // w.wb.b.
    24,    // .bwb.b.
    28,    // bbwb.b.
    17,    // wbwb.b.
    20,    // .wwb.b.
    36,    // bwwb.b.
    73,    // wwwb.b.
    -13,   // ...w.b.
    -21,   // b..w.b.
    -28,   // w..w.b.
    -9,    // .b.w.b.
    -44,   // bb.w.b.
    -35,   // wb.w.b.
    35,    // .w.w.b.
    71,    // bw.w.b.
    -118,  // ww.w.b.
    -28,   // ..bw.b.
    28,    // b.bw.b.
    25,    // w.bw.b.
    39,    // .bbw.b.
    -81,   // bbbw.b.
    -78,   // wbbw.b.
    29,    // .wbw.b.
    30,    // bwbw.b.
    17,    // wwbw.b.
    67,    // ..ww.b.
    -9,    // b.ww.b.
    -60,   // w.ww.b.
    44,    // .bww.b.
    -6,    // bbww.b.
    102,   // wbww.b.
    0,     // .www.b.
    44,    // bwww.b.
    -265,  // wwww.b.
    41,    // ....bb.
    -24,   // b...bb.
    29,    // w...bb.
    35,    // .b..bb.
    11,    // bb..bb.
    -26,   // wb..bb.
    35,    // .w..bb.
    18,    // bw..bb.
    -85,   // ww..bb.
    -77,   // ..b.bb.
    -15,   // b.b.bb.
    21,    // w.b.bb.
    26,    // .bb.bb.
    16,    // bbb.bb.
    -47,   // wbb.bb.
    -64,   // .wb.bb.
    -32,   // bwb.bb.
    -38,   // wwb.bb.
    -35,   // ..w.bb.
    -53,   // b.w.bb.
    14,    // w.w.bb.
    -17,   // .bw.bb.
    -4,    // bbw.bb.
    -79,   // wbw.bb.
    0,     // .ww.bb.
    57,    // bww.bb.
    -55,   // www.bb.
    59,    // ...bbb.
    30,    // b..bbb.
    -28,   // w..bbb.
    60,    // .b.bbb.
    -34,   // bb.bbb.
    103,   // wb.bbb.
    0,     // .w.bbb.
    96,    // bw.bbb.
    6,     // ww.bbb.
    277,   // ..bbbb.
    48,    // b.bbbb.
    77,    // w.bbbb.
    -55,   // .bbbbb.
    -13,   // bbbbbb.
    -39,   // wbbbbb.
    101,   // .wbbbb.
    -15,   // bwbbbb.
    -36,   // wwbbbb.
    88,    // ..wbbb.
    -1,    // b.wbbb.
    -15,   // w.wbbb.
    65,    // .bwbbb.
    -105,  // bbwbbb.
    49,    // wbwbbb.
    -3,    // .wwbbb.
    48,    // bwwbbb.
    -16,   // wwwbbb.
    -7,    // ...wbb.
    14,    // b..wbb.
    -12,   // w..wbb.
    39,    // .b.wbb.
    53,    // bb.wbb.
    48,    // wb.wbb.
    -20,   // .w.wbb.
    -34,   // bw.wbb.
    -70,   // ww.wbb.
    9,     // ..bwbb.
    -120,  // b.bwbb.
    -34,   // w.bwbb.
    30,    // .bbwbb.
    -21,   // bbbwbb.
    -65,   // wbbwbb.
    30,    // .wbwbb.
    -58,   // bwbwbb.
    119,   // wwbwbb.
    -22,   // ..wwbb.
    -40,   // b.wwbb.
    20,    // w.wwbb.
    4,     // .bwwbb.
    -103,  // bbwwbb.
    2,     // wbwwbb.
    3,     // .wwwbb.
    55,    // bwwwbb.
    -14,   // wwwwbb.
    20,    // ....wb.
    -14,   // b...wb.
    23,    // w...wb.
    -19,   // .b..wb.
    42,    // bb..wb.
    -74,   // wb..wb.
    12,    // .w..wb.
    -19,   // bw..wb.
    -37,   // ww..wb.
    -24,   // ..b.wb.
    -34,   // b.b.wb.
    17,    // w.b.wb.
    -17,   // .bb.wb.
    35,    // bbb.wb.
    29,    // wbb.wb.
    0,     // .wb.wb.
    -1,    // bwb.wb.
    2,     // wwb.wb.
    6,     // ..w.wb.
    -1,    // b.w.wb.
    71,    // w.w.wb.
    50,    // .bw.wb.
    4,     // bbw.wb.
    -2,    // wbw.wb.
    64,    // .ww.wb.
    -76,   // bww.wb.
    -4,    // www.wb.
    -16,   // ...bwb.
    44,    // b..bwb.
    55,    // w..bwb.
    24,    // .b.bwb.
    33,    // bb.bwb.
    -70,   // wb.bwb.
    -29,   // .w.bwb.
    -35,   // bw.bwb.
    -19,   // ww.bwb.
    -16,   // ..bbwb.
    -13,   // b.bbwb.
    -28,   // w.bbwb.
    65,    // .bbbwb.
    -77,   // bbbbwb.
    -14,   // wbbbwb.
    9,     // .wbbwb.
    -47,   // bwbbwb.
    82,    // wwbbwb.
    -17,   // ..wbwb.
    -40,   // b.wbwb.
    9,     // w.wbwb.
    33,    // .bwbwb.
    7,     // bbwbwb.
    -25,   // wbwbwb.
    -30,   // .wwbwb.
    114,   // bwwbwb.
    -2,    // wwwbwb.
    -51,   // ...wwb.
    -13,   // b..wwb.
    23,    // w..wwb.
    44,    // .b.wwb.
    -69,   // bb.wwb.
    -19,   // wb.wwb.
    -1,    // .w.wwb.
    32,    // bw.wwb.
    -70,   // ww.wwb.
    -5,    // ..bwwb.
    -42,   // b.bwwb.
    -40,   // w.bwwb.
    4,     // .bbwwb.
    -21,   // bbbwwb.
    -78,   // wbbwwb.
    -9,    // .wbwwb.
    -54,   // bwbwwb.
    -13,   // wwbwwb.
    27,    // ..wwwb.
    106,   // b.wwwb.
    -130,  // w.wwwb.
    2,     // .bwwwb.
    29,    // bbwwwb.
    -71,   // wbwwwb.
    -101,  // .wwwwb.
    115,   // bwwwwb.
    -108,  // wwwwwb.
    -7,    // .....w.
    62,    // b....w.
    9,     // w....w.
    0,     // .b...w.
    15,    // bb...w.
    -5,    // wb...w.
    12,    // .w...w.
    3,     // bw...w.
    -2,    // ww...w.
    -11,   // ..b..w.
    19,    // b.b..w.
    21,    // w.b..w.
    35,    // .bb..w.
    50,    // bbb..w.
    -2,    // wbb..w.
    19,    // .wb..w.
    41,    // bwb..w.
    7,     // wwb..w.
    -10,   // ..w..w.
    32,    // b.w..w.
    -26,   // w.w..w.
    12,    // .bw..w.
    -54,   // bbw..w.
    21,    // wbw..w.
    -35,   // .ww..w.
    -115,  // bww..w.
    -11,   // www..w.
    13,    // ...b.w.
    28,    // b..b.w.
    21,    // w..b.w.
    -35,   // .b.b.w.
    118,   // bb.b.w.
    -71,   // wb.b.w.
    9,     // .w.b.w.
    35,    // bw.b.w.
    44,    // ww.b.w.
    -67,   // ..bb.w.
    60,    // b.bb.w.
    9,     // w.bb.w.
    0,     // .bbb.w.
    265,   // bbbb.w.
    -44,   // wbbb.w.
    -44,   // .wbb.w.
    -102,  // bwbb.w.
    6,     // wwbb.w.
    28,    // ..wb.w.
    -25,   // b.wb.w.
    -28,   // w.wb.w.
    -29,   // .bwb.w.
    -17,   // bbwb.w.
    -30,   // wbwb.w.
    -39,   // .wwb.w.
    78,    // bwwb.w.
    81,    // wwwb.w.
    6,     // ...w.w.
    32,    // b..w.w.
    67,    // w..w.w.
    35,    // .b.w.w.
    18,    // bb.w.w.
    0,     // wb.w.w.
    9,     // .w.w.w.
    8,     // bw.w.w.
    50,    // ww.w.w.
    48,    // ..bw.w.
    53,    // b.bw.w.
    55,    // w.bw.w.
    -20,   // .bbw.w.
    -73,   // bbbw.w.
    -36,   // wbbw.w.
    -24,   // .wbw.w.
    -17,   // bwbw.w.
    -28,   // wwbw.w.
    8,     // ..ww.w.
    -97,   // b.ww.w.
    26,    // w.ww.w.
    -1,    // .bww.w.
    27,    // bbww.w.
    2,     // wbww.w.
    -60,   // .www.w.
    -117,  // bwww.w.
    73,    // wwww.w.
    -20,   // ....bw.
    -23,   // b...bw.
    14,    // w...bw.
    -12,   // .b..bw.
    37,    // bb..bw.
    19,    // wb..bw.
    19,    // .w..bw.
    74,    // bw..bw.
    -42,   // ww..bw.
    -6,    // ..b.bw.
    -71,   // b.b.bw.
    1,     // w.b.bw.
    -64,   // .bb.bw.
    4,     // bbb.bw.
    76,    // wbb.bw.
    -50,   // .wb.bw.
    2,     // bwb.bw.
    -4,    // wwb.bw.
    24,    // ..w.bw.
    -17,   // b.w.bw.
    34,    // w.w.bw.
    0,     // .bw.bw.
    -2,    // bbw.bw.
    1,     // wbw.bw.
    17,    // .ww.bw.
    -29,   // bww.bw.
    -35,   // www.bw.
    51,    // ...bbw.
    -23,   // b..bbw.
    13,    // w..bbw.
    1,     // .b.bbw.
    70,    // bb.bbw.
    -32,   // wb.bbw.
    -44,   // .w.bbw.
    19,    // bw.bbw.
    69,    // ww.bbw.
    -27,   // ..bbbw.
    130,   // b.bbbw.
    -106,  // w.bbbw.
    101,   // .bbbbw.
    108,   // bbbbbw.
    -115,  // wbbbbw.
    -2,    // .wbbbw.
    71,    // bwbbbw.
    -29,   // wwbbbw.
    5,     // ..wbbw.
    40,    // b.wbbw.
    42,    // w.wbbw.
    9,     // .bwbbw.
    13,    // bbwbbw.
    54,    // wbwbbw.
    -4,    // .wwbbw.
    78,    // bwwbbw.
    21,    // wwwbbw.
    16,    // ...wbw.
    -55,   // b..wbw.
    -44,   // w..wbw.
    29,    // .b.wbw.
    19,    // bb.wbw.
    35,    // wb.wbw.
    -24,   // .w.wbw.
    70,    // bw.wbw.
    -33,   // ww.wbw.
    17,    // ..bwbw.
    -9,    // b.bwbw.
    40,    // w.bwbw.
    30,    // .bbwbw.
    2,     // bbbwbw.
    -114,  // wbbwbw.
    -33,   // .wbwbw.
    25,    // bwbwbw.
    -7,    // wwbwbw.
    16,    // ..wwbw.
    28,    // b.wwbw.
    13,    // w.wwbw.
    -9,    // .bwwbw.
    -82,   // bbwwbw.
    47,    // wbwwbw.
    -65,   // .wwwbw.
    14,    // bwwwbw.
    77,    // wwwwbw.
    -41,   // ....ww.
    -29,   // b...ww.
    24,    // w...ww.
    -35,   // .b..ww.
    85,    // bb..ww.
    -18,   // wb..ww.
    -35,   // .w..ww.
    26,    // bw..ww.
    -11,   // ww..ww.
    35,    // ..b.ww.
    -14,   // b.b.ww.
    53,    // w.b.ww.
    0,     // .bb.ww.
    55,    // bbb.ww.
    -57,   // wbb.ww.
    17,    // .wb.ww.
    79,    // bwb.ww.
    4,     // wwb.ww.
    77,    // ..w.ww.
    -21,   // b.w.ww.
    15,    // w.w.ww.
    64,    // .bw.ww.
    38,    // bbw.ww.
    32,    // wbw.ww.
    -26,   // .ww.ww.
    47,    // bww.ww.
    -16,   // www.ww.
    7,     // ...bww.
    12,    // b..bww.
    -14,   // w..bww.
    20,    // .b.bww.
    70,    // bb.bww.
    34,    // wb.bww.
    -39,   // .w.bww.
    -48,   // bw.bww.
    -53,   // ww.bww.
    22,    // ..bbww.
    -20,   // b.bbww.
    40,    // w.bbww.
    -3,    // .bbbww.
    14,    // bbbbww.
    -55,   // wbbbww.
    -4,    // .wbbww.
    -2,    // bwbbww.
    103,   // wwbbww.
    -9,    // ..wbww.
    34,    // b.wbww.
    120,   // w.wbww.
    -30,   // .bwbww.
    -119,  // bbwbww.
    58,    // wbwbww.
    -30,   // .wwbww.
    65,    // bwwbww.
    21,    // wwwbww.
    -59,   // ...www.
    28,    // b..www.
    -30,   // w..www.
    0,     // .b.www.
    -6,    // bb.www.
    -96,   // wb.www.
    -60,   // .w.www.
    -103,  // bw.www.
    34,    // ww.www.
    -88,   // ..bwww.
    15,    // b.bwww.
    1,     // w.bwww.
    3,     // .bbwww.
    16,    // bbbwww.
    -48,   // wbbwww.
    -65,   // .wbwww.
    -49,   // bwbwww.
    105,   // wwbwww.
    -277,  // ..wwww.
    -77,   // b.wwww.
    -48,   // w.wwww.
    -101,  // .bwwww.
    36,    // bbwwww.
    15,    // wbwwww.
    55,    // .wwwww.
    39,    // bwwwww.
    13,    // wwwwww.
    7,     // ......b
    -49,   // b.....b
    0,     // w.....b
    -9,    // .b....b
    -22,   // bb....b
    11,    // wb....b
    62,    // .w....b
    56,    // bw....b
    20,    // ww....b
    19,    // ..b...b
    64,    // b.b...b
    -29,   // w.b...b
    -24,   // .bb...b
    -27,   // bbb...b
    -73,   // wbb...b
    -23,   // .wb...b
    -9,    // bwb...b
    6,     // wwb...b
    29,    // ..w...b
    8,     // b.w...b
    56,    // w.w...b
    -14,   // .bw...b
    6,     // bbw...b
    -7,    // wbw...b
    -29,   // .ww...b
    -47,   // bww...b
    -54,   // www...b
    -1,    // ...b..b
    2,     // b..b..b
    58,    // w..b..b
    -67,   // .b.b..b
    30,    // bb.b..b
    -56,   // wb.b..b
    28,    // .w.b..b
    -51,   // bw.b..b
    117,   // ww.b..b
    -41,   // ..bb..b
    -66,   // b.bb..b
    38,    // w.bb..b
    30,    // .bbb..b
    21,    // bbbb..b
    -100,  // wbbb..b
    -23,   // .wbb..b
    137,   // bwbb..b
    -66,   // wwbb..b
    -30,   // ..wb..b
    -1,    // b.wb..b
    10,    // w.wb..b
    44,    // .bwb..b
    -45,   // bbwb..b
    -38,   // wbwb..b
    12,    // .wwb..b
    -13,   // bwwb..b
    9,     // wwwb..b
    5,     // ...w..b
    -56,   // b..w..b
    -58,   // w..w..b
    -21,   // .b.w..b
    0,     // bb.w..b
    -63,   // wb.w..b
    32,    // .w.w..b
    -50,   // bw.w..b
    25,    // ww.w..b
    74,    // ..bw..b
    21,    // b.bw..b
    34,    // w.bw..b
    14,    // .bbw..b
    50,    // bbbw..b
    -19,   // wbbw..b
    -55,   // .wbw..b
    -73,   // bwbw..b
    -4,    // wwbw..b
    -14,   // ..ww..b
    -45,   // b.ww..b
    49,    // w.ww..b
    -13,   // .bww..b
    -42,   // bbww..b
    33,    // wbww..b
    28,    // .www..b
    19,    // bwww..b
    -73,   // wwww..b
    66,    // ....b.b
    64,    // b...b.b
    -56,   // w...b.b
    26,    // .b..b.b
    -77,   // bb..b.b
    91,    // wb..b.b
    19,    // .w..b.b
    49,    // bw..b.b
    1,     // ww..b.b
    27,    // ..b.b.b
    20,    // b.b.b.b
    63,    // w.b.b.b
    -15,   // .bb.b.b
    46,    // bbb.b.b
    3,     // wbb.b.b
    -71,   // .wb.b.b
    -46,   // bwb.b.b
    -58,   // wwb.b.b
    36,    // ..w.b.b
    24,    // b.w.b.b
    0,     // w.w.b.b
    -34,   // .bw.b.b
    17,    // bbw.b.b
    13,    // wbw.b.b
    -14,   // .ww.b.b
    66,    // bww.b.b
    -21,   // www.b.b
    66,    // ...bb.b
    -66,   // b..bb.b
    -49,   // w..bb.b
    -26,   // .b.bb.b
    -50,   // bb.bb.b
    -71,   // wb.bb.b
    60,    // .w.bb.b
    29,    // bw.bb.b
    -54,   // ww.bb.b
    103,   // ..bbb.b
    56,    // b.bbb.b
    -41,   // w.bbb.b
    48,    // .bbbb.b
    -57,   // bbbbb.b
    15,    // wbbbb.b
    130,   // .wbbb.b
    -36,   // bwbbb.b
    14,    // wwbbb.b
    -113,  // ..wbb.b
    6,     // b.wbb.b
    87,    // w.wbb.b
    -13,   // .bwbb.b
    -17,   // bbwbb.b
    21,    // wbwbb.b
    -20,   // .wwbb.b
    -80,   // bwwbb.b
    89,    // wwwbb.b
    53,    // ...wb.b
    21,    // b..wb.b
    -10,   // w..wb.b
    28,    // .b.wb.b
    28,    // bb.wb.b
    49,    // wb.wb.b
    53,    // .w.wb.b
    -22,   // bw.wb.b
    44,    // ww.wb.b
    31,    // ..bwb.b
    33,    // b.bwb.b
    7,     // w.bwb.b
    -120,  // .bbwb.b
    -50,   // bbbwb.b
    -55,   // wbbwb.b
    -9,    // .wbwb.b
    38,    // bwbwb.b
    74,    // wwbwb.b
    45,    // ..wwb.b
    20,    // b.wwb.b
    -87,   // w.wwb.b
    -42,   // .bwwb.b
    -8,    // bbwwb.b
    19,    // wbwwb.b
    15,    // .wwwb.b
    21,    // bwwwb.b
    18,    // wwwwb.b
    41,    // ....w.b
    8,     // b...w.b
    29,    // w...w.b
    -21,   // .b..w.b
    12,    // bb..w.b
    108,   // wb..w.b
    32,    // .w..w.b
    14,    // bw..w.b
    -42,   // ww..w.b
    33,    // ..b.w.b
    24,    // b.b.w.b
    0,     // w.b.w.b
    -53,   // .bb.w.b
    28,    // bbb.w.b
    79,    // wbb.w.b
    -17,   // .wb.w.b
    72,    // bwb.w.b
    -3,    // wwb.w.b
    35,    // ..w.w.b
    46,    // b.w.w.b
    -63,   // w.w.w.b
    -1,    // .bw.w.b
    -5,    // bbw.w.b
    71,    // wbw.w.b
    -21,   // .ww.w.b
    12,    // bww.w.b
    17,    // www.w.b
    79,    // ...bw.b
    -1,    // b..bw.b
    -34,   // w..bw.b
    -55,   // .b.bw.b
    4,     // bb.bw.b
    15,    // wb.bw.b
    -25,   // .w.bw.b
    53,    // bw.bw.b
    6,     // ww.bw.b
    -22,   // ..bbw.b
    6,     // b.bbw.b
    -12,   // w.bbw.b
    -1,    // .bbbw.b
    61,    // bbbbw.b
    -1,    // wbbbw.b
    40,    // .wbbw.b
    17,    // bwbbw.b
    -55,   // wwbbw.b
    3,     // ..wbw.b
    -37,   // b.wbw.b
    -7,    // w.wbw.b
    -40,   // .bwbw.b
    11,    // bbwbw.b
    -65,   // wbwbw.b
    34,    // .wwbw.b
    37,    // bwwbw.b
    -88,   // wwwbw.b
    -38,   // ...ww.b
    -45,   // b..ww.b
    -38,   // w..ww.b
    -9,    // .b.ww.b
    -24,   // bb.ww.b
    56,    // wb.ww.b
    -97,   // .w.ww.b
    17,    // bw.ww.b
    -27,   // ww.ww.b
    32,    // ..bww.b
    20,    // b.bww.b
    12,    // w.bww.b
    -40,   // .bbww.b
    66,    // bbbww.b
    66,    // wbbww.b
    28,    // .wbww.b
    29,    // bwbww.b
    -57,   // wwbww.b
    19,    // ..www.b
    -73,   // b.www.b
    41,    // w.www.b
    106,   // .bwww.b
    5,     // bbwww.b
    28,    // wbwww.b
    -77,   // .wwww.b
    -6,    // bwwww.b
    -46,   // wwwww.b
    15,    // .....bb
    -22,   // b....bb
    -20,   // w....bb
    2,     // .b...bb
    -19,   // bb...bb
    -34,   // wb...bb
    15,    // .w...bb
    17,    // bw...bb
    0,     // ww...bb
    24,    // ..b..bb
    -77,   // b.b..bb
    42,    // w.b..bb
    11,    // .bb..bb
    60,    // bbb..bb
    -12,   // wbb..bb
    37,    // .wb..bb
    -86,   // bwb..bb
    16,    // wwb..bb
    -37,   // ..w..bb
    12,    // b.w..bb
    -1,    // w.w..bb
    42,    // .bw..bb
    20,    // bbw..bb
    11,    // wbw..bb
    85,    // .ww..bb
    14,    // bww..bb
    20,    // www..bb
    150,   // ...b.bb
    30,    // b..b.bb
    -25,   // w..b.bb
    -50,   // .b.b.bb
    25,    // bb.b.bb
    52,    // wb.b.bb
    118,   // .w.b.bb
    -43,   // bw.b.bb
    -5,    // ww.b.bb
    36,    // ..bb.bb
    -50,   // b.bb.bb
    27,    // w.bb.bb
    -34,   // .bbb.bb
    -54,   // bbbb.bb
    6,     // wbbb.bb
    70,    // .wbb.bb
    -14,   // bwbb.bb
    -86,   // wwbb.bb
    -9,    // ..wb.bb
    4,     // b.wb.bb
    -44,   // w.wb.bb
    33,    // .bwb.bb
    25,    // bbwb.bb
    1,     // wbwb.bb
    70,    // .wwb.bb
    1,     // bwwb.bb
    28,    // wwwb.bb
    23,    // ...w.bb
    0,     // b..w.bb
    -117,  // w..w.bb
    -44,   // .b.w.bb
    85,    // bb.w.bb
    10,    // wb.w.bb
    18,    // .w.w.bb
    29,    // bw.w.bb
    5,     // ww.w.bb
    -65,   // ..bw.bb
    28,    // b.bw.bb
    -6,    // w.bw.bb
    53,    // .bbw.bb
    64,    // bbbw.bb
    42,    // wbbw.bb
    19,    // .wbw.bb
    59,    // bwbw.bb
    123,   // wwbw.bb
    26,    // ..ww.bb
    -24,   // b.ww.bb
    54,    // w.ww.bb
    -69,   // .bww.bb
    -51,   // bbww.bb
    -21,   // wbww.bb
    -6,    // .www.bb
    -2,    // bwww.bb
    -47,   // wwww.bb
    166,   // ....bbb
    -27,   // b...bbb
    54,    // w...bbb
    11,    // .b..bbb
    60,    // bb..bbb
    41,    // wb..bbb
    50,    // .w..bbb
    -7,    // bw..bbb
    -20,   // ww..bbb
    141,   // ..b.bbb
    46,    // b.b.bbb
    -17,   // w.b.bbb
    16,    // .bb.bbb
    39,    // bbb.bbb
    17,    // wbb.bbb
    4,     // .wb.bbb
    -43,   // bwb.bbb
    -61,   // wwb.bbb
    78,    // ..w.bbb
    28,    // b.w.bbb
    21,    // w.w.bbb
    35,    // .bw.bbb
    61,    // bbw.bbb
    -54,   // wbw.bbb
    55,    // .ww.bbb
    -27,   // bww.bbb
    0,     // www.bbb
    313,   // ...bbbb
    21,    // b..bbbb
    73,    // w..bbbb
    -73,   // .b.bbbb
    -54,   // bb.bbbb
    51,    // wb.bbbb
    265,   // .w.bbbb
    71,    // bw.bbbb
    47,    // ww.bbbb
    45,    // ..bbbbb
    -57,   // b.bbbbb
    46,    // w.bbbbb
    -13,   // .bbbbbb
    -38,   // bbbbbbb
    -26,   // wbbbbbb
    108,   // .wbbbbb
    -17,   // bwbbbbb
    68,    // wwbbbbb
    48,    // ..wbbbb
    61,    // b.wbbbb
    -18,   // w.wbbbb
    -77,   // .bwbbbb
    -23,   // bbwbbbb
    65,    // wbwbbbb
    14,    // .wwbbbb
    -20,   // bwwbbbb
    -90,   // wwwbbbb
    55,    // ...wbbb
    50,    // b..wbbb
    -9,    // w..wbbb
    -81,   // .b.wbbb
    64,    // bb.wbbb
    29,    // wb.wbbb
    -73,   // .w.wbbb
    20,    // bw.wbbb
    -28,   // ww.wbbb
    -144,  // ..bwbbb
    -50,   // b.bwbbb
    88,    // w.bwbbb
    -21,   // .bbwbbb
    49,    // bbbwbbb
    -165,  // wbbwbbb
    2,     // .wbwbbb
    17,    // bwbwbbb
    -14,   // wwbwbbb
    74,    // ..wwbbb
    66,    // b.wwbbb
    -89,   // w.wwbbb
    -21,   // .bwwbbb
    21,    // bbwwbbb
    -44,   // wbwwbbb
    16,    // .wwwbbb
    33,    // bwwwbbb
    90,    // wwwwbbb
    -46,   // ....wbb
    6,     // b...wbb
    -6,    // w...wbb
    -7,    // .b..wbb
    20,    // bb..wbb
    37,    // wb..wbb
    -54,   // .w..wbb
    55,    // bw..wbb
    -16,   // ww..wbb
    -25,   // ..b.wbb
    17,    // b.b.wbb
    3,     // w.b.wbb
    -4,    // .bb.wbb
    61,    // bbb.wbb
    -10,   // wbb.wbb
    -2,    // .wb.wbb
    30,    // bwb.wbb
    0,     // wwb.wbb
    12,    // ..w.wbb
    -5,    // b.w.wbb
    58,    // w.w.wbb
    4,     // .bw.wbb
    -100,  // bbw.wbb
    -67,   // wbw.wbb
    38,    // .ww.wbb
    -9,    // bww.wbb
    61,    // www.wbb
    -52,   // ...bwbb
    -45,   // b..bwbb
    4,     // w..bwbb
    28,    // .b.bwbb
    25,    // bb.bwbb
    17,    // wb.bwbb
    -17,   // .w.bwbb
    -56,   // bw.bwbb
    -123,  // ww.bwbb
    -28,   // ..bbwbb
    -17,   // b.bbwbb
    57,    // w.bbwbb
    -105,  // .bbbwbb
    -23,   // bbbbwbb
    15,    // wbbbwbb
    13,    // .wbbwbb
    18,    // bwbbwbb
    60,    // wwbbwbb
    30,    // ..wbwbb
    11,    // b.wbwbb
    -74,   // w.wbwbb
    7,     // .bwbwbb
    -34,   // bbwbwbb
    132,   // wbwbwbb
    -119,  // .wwbwbb
    -4,    // bwwbwbb
    14,    // wwwbwbb
    -22,   // ...wwbb
    -42,   // b..wwbb
    66,    // w..wwbb
    -6,    // .b.wwbb
    -51,   // bb.wwbb
    -2,    // wb.wwbb
    27,    // .w.wwbb
    85,    // bw.wwbb
    86,    // ww.wwbb
    51,    // ..bwwbb
    -8,    // b.bwwbb
    55,    // w.bwwbb
    -103,  // .bbwwbb
    21,    // bbbwwbb
    25,    // wbbwwbb
    -82,   // .wbwwbb
    -17,   // bwbwwbb
    -60,   // wwbwwbb
    48,    // ..wwwbb
    5,     // b.wwwbb
    -14,   // w.wwwbb
    29,    // .bwwwbb
    2,     // bbwwwbb
    -20,   // wbwwwbb
    36,    // .wwwwbb
    -19,   // bwwwwbb
    -68,   // wwwwwbb
    9,     // .....wb
    56,    // b....wb
    -11,   // w....wb
    5,     // .b...wb
    17,    // bb...wb
    0,     // wb...wb
    3,     // .w...wb
    -104,  // bw...wb
    34,    // ww...wb
    7,     // ..b..wb
    49,    // b.b..wb
    -108,  // w.b..wb
    18,    // .bb..wb
    -7,    // bbb..wb
    -62,   // wbb..wb
    74,    // .wb..wb
    -42,   // bwb..wb
    -37,   // wwb..wb
    -33,   // ..w..wb
    14,    // b.w..wb
    -91,   // w.w..wb
    -19,   // .bw..wb
    55,    // bbw..wb
    28,    // wbw..wb
    26,    // .ww..wb
    -43,   // bww..wb
    -41,   // www..wb
    34,    // ...b.wb
    -51,   // b..b.wb
    63,    // w..b.wb
    0,     // .b.b.wb
    -43,   // bb.b.wb
    15,    // wb.b.wb
    35,    // .w.b.wb
    -81,   // bw.b.wb
    -10,   // ww.b.wb
    7,     // ..bb.wb
    29,    // b.bb.wb
    -56,   // w.bb.wb
    96,    // .bbb.wb
    71,    // bbbb.wb
    -11,   // wbbb.wb
    19,    // .wbb.wb
    -37,   // bwbb.wb
    2,     // wwbb.wb
    8,     // ..wb.wb
    53,    // b.wb.wb
    -49,   // w.wb.wb
    -35,   // .bwb.wb
    -56,   // bbwb.wb
    -48,   // wbwb.wb
    -48,   // .wwb.wb
    129,   // bwwb.wb
    -29,   // wwwb.wb
    42,    // ...w.wb
    -50,   // b..w.wb
    56,    // w..w.wb
    71,    // .b.w.wb
    29,    // bb.w.wb
    -15,   // wb.w.wb
    8,     // .w.w.wb
    -3,    // bw.w.wb
    -52,   // ww.w.wb
    8,     // ..bw.wb
    -22,   // b.bw.wb
    -15,   // w.bw.wb
    -34,   // .bbw.wb
    20,    // bbbw.wb
    -27,   // wbbw.wb
    70,    // .wbw.wb
    31,    // bwbw.wb
    -17,   // wwbw.wb
    -8,    // ..ww.wb
    17,    // b.ww.wb
    71,    // w.ww.wb
    32,    // .bww.wb
    85,    // bbww.wb
    41,    // wbww.wb
    -103,  // .www.wb
    -68,   // bwww.wb
    -51,   // wwww.wb
    41,    // ....bwb
    -9,    // b...bwb
    7,     // w...bwb
    -21,   // .b..bwb
    -86,   // bb..bwb
    -28,   // wb..bwb
    41,    // .w..bwb
    -42,   // bw..bwb
    -11,   // ww..bwb
    -51,   // ..b.bwb
    -46,   // b.b.bwb
    -71,   // w.b.bwb
    -32,   // .bb.bwb
    -43,   // bbb.bwb
    32,    // wbb.bwb
    2,     // .wb.bwb
    -1,    // bwb.bwb
    67,    // wwb.bwb
    32,    // ..w.bwb
    72,    // b.w.bwb
    -13,   // w.w.bwb
    -1,    // .bw.bwb
    30,    // bbw.bwb
    0,     // wbw.bwb
    79,    // .ww.bwb
    47,    // bww.bwb
    54,    // www.bwb
    1,     // ...bbwb
    137,   // b..bbwb
    -33,   // w..bbwb
    -2,    // .b.bbwb
    -14,   // bb.bbwb
    -41,   // wb.bbwb
    -102,  // .w.bbwb
    -37,   // bw.bbwb
    21,    // ww.bbwb
    -45,   // ..bbbwb
    -36,   // b.bbbwb
    -28,   // w.bbbwb
    -15,   // .bbbbwb
    -17,   // bbbbbwb
    -101,  // wbbbbwb
    71,    // .wbbbwb
    57,    // bwbbbwb
    20,    // wwbbbwb
    19,    // ..wbbwb
    17,    // b.wbbwb
    -19,   // w.wbbwb
    -47,   // .bwbbwb
    18,    // bbwbbwb
    95,    // wbwbbwb
    -2,    // .wwbbwb
    -2,    // bwwbbwb
    44,    // wwwbbwb
    15,    // ...wbwb
    -73,   // b..wbwb
    38,    // w..wbwb
    30,    // .b.wbwb
    59,    // bb.wbwb
    48,    // wb.wbwb
    -17,   // .w.wbwb
    31,    // bw.wbwb
    -1,    // ww.wbwb
    -9,    // ..bwbwb
    38,    // b.bwbwb
    65,    // w.bwbwb
    -58,   // .bbwbwb
    17,    // bbbwbwb
    -7,    // wbbwbwb
    25,    // .wbwbwb
    -65,   // bwbwbwb
    -132,  // wwbwbwb
    -43,   // ..wwbwb
    29,    // b.wwbwb
    -21,   // w.wwbwb
    -54,   // .bwwbwb
    -17,   // bbwwbwb
    -95,   // wbwwbwb
    -49,   // .wwwbwb
    -3,    // bwwwbwb
    -65,   // wwwwbwb
    90,    // ....wwb
    -47,   // b...wwb
    73,    // w...wwb
    2,     // .b..wwb
    14,    // bb..wwb
    62,    // wb..wwb
    -115,  // .w..wwb
    -43,   // bw..wwb
    12,    // ww..wwb
    11,    // ..b.wwb
    66,    // b.b.wwb
    -79,   // w.b.wwb
    57,    // .bb.wwb
    -27,   // bbb.wwb
    0,     // wbb.wwb
    -29,   // .wb.wwb
    47,    // bwb.wwb
    10,    // wwb.wwb
    64,    // ..w.wwb
    12,    // b.w.wwb
    -3,    // w.w.wwb
    -76,   // .bw.wwb
    -9,    // bbw.wwb
    -32,   // wbw.wwb
    47,    // .ww.wwb
    -56,   // bww.wwb
    -17,   // www.wwb
    14,    // ...bwwb
    -13,   // b..bwwb
    19,    // w..bwwb
    36,    // .b.bwwb
    1,     // bb.bwwb
    27,    // wb.bwwb
    78,    // .w.bwwb
    129,   // bw.bwwb
    -42,   // ww.bwwb
    -126,  // ..bbwwb
    -80,   // b.bbwwb
    -66,   // w.bbwwb
    48,    // .bbbwwb
    -20,   // bbbbwwb
    14,    // wbbbwwb
    78,    // .wbbwwb
    -2,    // bwbbwwb
    -25,   // wwbbwwb
    -73,   // ..wbwwb
    37,    // b.wbwwb
    55,    // w.wbwwb
    114,   // .bwbwwb
    -4,    // bbwbwwb
    7,     // wbwbwwb
    65,    // .wwbwwb
    9,     // bwwbwwb
    165,   // wwwbwwb
    101,   // ...wwwb
    19,    // b..wwwb
    100,   // w..wwwb
    44,    // .b.wwwb
    -2,    // bb.wwwb
    11,    // wb.wwwb
    -117,  // .w.wwwb
    -68,   // bw.wwwb
    -6,    // ww.wwwb
    -5,    // ..bwwwb
    21,    // b.bwwwb
    1,     // w.bwwwb
    55,    // .bbwwwb
    33,    // bbbwwwb
    -14,   // wbbwwwb
    14,    // .wbwwwb
    -3,    // bwbwwwb
    -15,   // wwbwwwb
    -49,   // ..wwwwb
    -6,    // b.wwwwb
    -15,   // w.wwwwb
    115,   // .bwwwwb
    -19,   // bbwwwwb
    101,   // wbwwwwb
    39,    // .wwwwwb
    30,    // bwwwwwb
    26,    // wwwwwwb
    -7,    // ......w
    0,     // b.....w
    49,    // w.....w
    -62,   // .b....w
    -20,   // bb....w
    -56,   // wb....w
    9,     // .w....w
    -11,   // bw....w
    22,    // ww....w
    -29,   // ..b...w
    -56,   // b.b...w
    -8,    // w.b...w
    29,    // .bb...w
    54,    // bbb...w
    47,    // wbb...w
    14,    // .wb...w
    7,     // bwb...w
    -6,    // wwb...w
    -19,   // ..w...w
    29,    // b.w...w
    -64,   // w.w...w
    23,    // .bw...w
    -6,    // bbw...w
    9,     // wbw...w
    24,    // .ww...w
    73,    // bww...w
    27,    // www...w
    -5,    // ...b..w
    58,    // b..b..w
    56,    // w..b..w
    -32,   // .b.b..w
    -25,   // bb.b..w
    50,    // wb.b..w
    21,    // .w.b..w
    63,    // bw.b..w
    0,     // ww.b..w
    14,    // ..bb..w
    -49,   // b.bb..w
    45,    // w.bb..w
    -28,   // .bbb..w
    73,    // bbbb..w
    -19,   // wbbb..w
    13,    // .wbb..w
    -33,   // bwbb..w
    42,    // wwbb..w
    -74,   // ..wb..w
    -34,   // b.wb..w
    -21,   // w.wb..w
    55,    // .bwb..w
    4,     // bbwb..w
    73,    // wbwb..w
    -14,   // .wwb..w
    19,    // bwwb..w
    -50,   // wwwb..w
    1,     // ...w..w
    -58,   // b..w..w
    -2,    // w..w..w
    -28,   // .b.w..w
    -117,  // bb.w..w
    51,    // wb.w..w
    67,    // .w.w..w
    56,    // bw.w..w
    -30,   // ww.w..w
    30,    // ..bw..w
    -10,   // b.bw..w
    1,     // w.bw..w
    -12,   // .bbw..w
    -9,    // bbbw..w
    13,    // wbbw..w
    -44,   // .wbw..w
    38,    // bwbw..w
    45,    // wwbw..w
    41,    // ..ww..w
    -38,   // b.ww..w
    66,    // w.ww..w
    23,    // .bww..w
    66,    // bbww..w
    -137,  // wbww..w
    -30,   // .www..w
    100,   // bwww..w
    -21,   // wwww..w
    -41,   // ....b.w
    -29,   // b...b.w
    -8,    // w...b.w
    -32,   // .b..b.w
    42,    // bb..b.w
    -14,   // wb..b.w
    21,    // .w..b.w
    -108,  // bw..b.w
    -12,   // ww..b.w
    -35,   // ..b.b.w
    63,    // b.b.b.w
    -46,   // w.b.b.w
    21,    // .bb.b.w
    -17,   // bbb.b.w
    -12,   // wbb.b.w
    1,     // .wb.b.w
    -71,   // bwb.b.w
    5,     // wwb.b.w
    -33,   // ..w.b.w
    0,     // b.w.b.w
    -24,   // w.w.b.w
    17,    // .bw.b.w
    3,     // bbw.b.w
    -72,   // wbw.b.w
    53,    // .ww.b.w
    -79,   // bww.b.w
    -28,   // www.b.w
    38,    // ...bb.w
    38,    // b..bb.w
    45,    // w..bb.w
    97,    // .b.bb.w
    27,    // bb.bb.w
    -17,   // wb.bb.w
    9,     // .w.bb.w
    -56,   // bw.bb.w
    24,    // ww.bb.w
    -19,   // ..bbb.w
    -41,   // b.bbb.w
    73,    // w.bbb.w
    77,    // .bbbb.w
    46,    // bbbbb.w
    6,     // wbbbb.w
    -106,  // .wbbb.w
    -28,   // bwbbb.w
    -5,    // wwbbb.w
    -32,   // ..wbb.w
    -12,   // b.wbb.w
    -20,   // w.wbb.w
    -28,   // .bwbb.w
    57,    // bbwbb.w
    -29,   // wbwbb.w
    40,    // .wwbb.w
    -66,   // bwwbb.w
    -66,   // wwwbb.w
    -79,   // ...wb.w
    34,    // b..wb.w
    1,     // w..wb.w
    25,    // .b.wb.w
    -6,    // bb.wb.w
    -53,   // wb.wb.w
    55,    // .w.wb.w
    -15,   // bw.wb.w
    -4,    // ww.wb.w
    -3,    // ..bwb.w
    7,     // b.bwb.w
    37,    // w.bwb.w
    -34,   // .bbwb.w
    88,    // bbbwb.w
    -37,   // wbbwb.w
    40,    // .wbwb.w
    65,    // bwbwb.w
    -11,   // wwbwb.w
    22,    // ..wwb.w
    12,    // b.wwb.w
    -6,    // w.wwb.w
    -40,   // .bwwb.w
    55,    // bbwwb.w
    -17,   // wbwwb.w
    1,     // .wwwb.w
    1,     // bwwwb.w
    -61,   // wwwwb.w
    -66,   // ....w.w
    56,    // b...w.w
    -64,   // w...w.w
    -19,   // .b..w.w
    -1,    // bb..w.w
    -49,   // wb..w.w
    -26,   // .w..w.w
    -91,   // bw..w.w
    77,    // ww..w.w
    -36,   // ..b.w.w
    0,     // b.b.w.w
    -24,   // w.b.w.w
    14,    // .bb.w.w
    21,    // bbb.w.w
    -66,   // wbb.w.w
    34,    // .wb.w.w
    -13,   // bwb.w.w
    -17,   // wwb.w.w
    -27,   // ..w.w.w
    -63,   // b.w.w.w
    -20,   // w.w.w.w
    71,    // .bw.w.w
    58,    // bbw.w.w
    46,    // wbw.w.w
    15,    // .ww.w.w
    -3,    // bww.w.w
    -46,   // www.w.w
    -53,   // ...bw.w
    10,    // b..bw.w
    -21,   // w..bw.w
    -53,   // .b.bw.w
    -44,   // bb.bw.w
    22,    // wb.bw.w
    -28,   // .w.bw.w
    -49,   // bw.bw.w
    -28,   // ww.bw.w
    -45,   // ..bbw.w
    87,    // b.bbw.w
    -20,   // w.bbw.w
    -15,   // .bbbw.w
    -18,   // bbbbw.w
    -21,   // wbbbw.w
    42,    // .wbbw.w
    -19,   // bwbbw.w
    8,     // wwbbw.w
    -31,   // ..wbw.w
    -7,    // b.wbw.w
    -33,   // w.wbw.w
    9,     // .bwbw.w
    -74,   // bbwbw.w
    -38,   // wbwbw.w
    120,   // .wwbw.w
    55,    // bwwbw.w
    50,    // wwwbw.w
    -66,   // ...ww.w
    49,    // b..ww.w
    66,    // w..ww.w
    -60,   // .b.ww.w
    54,    // bb.ww.w
    -29,   // wb.ww.w
    26,    // .w.ww.w
    71,    // bw.ww.w
    50,    // ww.ww.w
    113,   // ..bww.w
    -87,   // b.bww.w
    -6,    // w.bww.w
    20,    // .bbww.w
    -89,   // bbbww.w
    80,    // wbbww.w
    13,    // .wbww.w
    -21,   // bwbww.w
    17,    // wwbww.w
    -103,  // ..www.w
    41,    // b.www.w
    -56,   // w.www.w
    -130,  // .bwww.w
    -14,   // bbwww.w
    36,    // wbwww.w
    -48,   // .wwww.w
    -15,   // bwwww.w
    57,    // wwwww.w
    -9,    // .....bw
    11,    // b....bw
    -56,   // w....bw
    -3,    // .b...bw
    -34,   // bb...bw
    104,   // wb...bw
    -5,    // .w...bw
    0,     // bw...bw
    -17,   // ww...bw
    33,    // ..b..bw
    91,    // b.b..bw
    -14,   // w.b..bw
    -26,   // .bb..bw
    41,    // bbb..bw
    43,    // wbb..bw
    19,    // .wb..bw
    -28,   // bwb..bw
    -55,   // wwb..bw
    -7,    // ..w..bw
    108,   // b.w..bw
    -49,   // w.w..bw
    -74,   // .bw..bw
    37,    // bbw..bw
    42,    // wbw..bw
    -18,   // .ww..bw
    62,    // bww..bw
    7,     // www..bw
    -42,   // ...b.bw
    -56,   // b..b.bw
    50,    // w..b.bw
    -8,    // .b.b.bw
    52,    // bb.b.bw
    3,     // wb.b.bw
    -71,   // .w.b.bw
    15,    // bw.b.bw
    -29,   // ww.b.bw
    8,     // ..bb.bw
    -71,   // b.bb.bw
    -17,   // w.bb.bw
    103,   // .bbb.bw
    51,    // bbbb.bw
    68,    // wbbb.bw
    -32,   // .wbb.bw
    -41,   // bwbb.bw
    -85,   // wwbb.bw
    -8,    // ..wb.bw
    15,    // b.wb.bw
    22,    // w.wb.bw
    -70,   // .bwb.bw
    17,    // bbwb.bw
    -31,   // wbwb.bw
    34,    // .wwb.bw
    27,    // bwwb.bw
    -20,   // wwwb.bw
    -34,   // ...w.bw
    -63,   // b..w.bw
    51,    // w..w.bw
    -35,   // .b.w.bw
    10,    // bb.w.bw
    81,    // wb.w.bw
    0,     // .w.w.bw
    -15,   // bw.w.bw
    43,    // ww.w.bw
    -8,    // ..bw.bw
    49,    // b.bw.bw
    -53,   // w.bw.bw
    48,    // .bbw.bw
    29,    // bbbw.bw
    -129,  // wbbw.bw
    35,    // .wbw.bw
    48,    // bwbw.bw
    56,    // wwbw.bw
    -7,    // ..ww.bw
    56,    // b.ww.bw
    -29,   // w.ww.bw
    -19,   // .bww.bw
    -2,    // bbww.bw
    37,    // wbww.bw
    -96,   // .www.bw
    11,    // bwww.bw
    -71,   // wwww.bw
    -90,   // ....bbw
    -73,   // b...bbw
    47,    // w...bbw
    115,   // .b..bbw
    -12,   // bb..bbw
    43,    // wb..bbw
    -2,    // .w..bbw
    -62,   // bw..bbw
    -14,   // ww..bbw
    -64,   // ..b.bbw
    3,     // b.b.bbw
    -12,   // w.b.bbw
    -47,   // .bb.bbw
    17,    // bbb.bbw
    56,    // wbb.bbw
    76,    // .wb.bbw
    32,    // bwb.bbw
    9,     // wwb.bbw
    -11,   // ..w.bbw
    79,    // b.w.bbw
    -66,   // w.w.bbw
    29,    // .bw.bbw
    -10,   // bbw.bbw
    -47,   // wbw.bbw
    -57,   // .ww.bbw
    0,     // bww.bbw
    27,    // www.bbw
    -101,  // ...bbbw
    -100,  // b..bbbw
    -19,   // w..bbbw
    117,   // .b.bbbw
    6,     // bb.bbbw
    68,    // wb.bbbw
    -44,   // .w.bbbw
    -11,   // bw.bbbw
    2,     // ww.bbbw
    49,    // ..bbbbw
    15,    // b.bbbbw
    6,     // w.bbbbw
    -39,   // .bbbbbw
    -26,   // bbbbbbw
    -30,   // wbbbbbw
    -115,  // .wbbbbw
    -101,  // bwbbbbw
    19,    // wwbbbbw
    5,     // ..wbbbw
    -1,    // b.wbbbw
    -21,   // w.wbbbw
    -14,   // .bwbbbw
    15,    // bbwbbbw
    3,     // wbwbbbw
    -55,   // .wwbbbw
    14,    // bwwbbbw
    -33,   // wwwbbbw
    -14,   // ...wbbw
    -19,   // b..wbbw
    13,    // w..wbbw
    -78,   // .b.wbbw
    42,    // bb.wbbw
    -129,  // wb.wbbw
    -36,   // .w.wbbw
    -27,   // bw.wbbw
    -1,    // ww.wbbw
    73,    // ..bwbbw
    -55,   // b.bwbbw
    -37,   // w.bwbbw
    -65,   // .bbwbbw
    -165,  // bbbwbbw
    -9,    // wbbwbbw
    -114,  // .wbwbbw
    -7,    // bwbwbbw
    4,     // wwbwbbw
    126,   // ..wwbbw
    66,    // b.wwbbw
    80,    // w.wwbbw
    -78,   // .bwwbbw
    25,    // bbwwbbw
    2,     // wbwwbbw
    -48,   // .wwwbbw
    -14,   // bwwwbbw
    20,    // wwwwbbw
    -41,   // ....wbw
    -7,    // b...wbw
    9,     // w...wbw
    -41,   // .b..wbw
    11,    // bb..wbw
    42,    // wb..wbw
    21,    // .w..wbw
    28,    // bw..wbw
    86,    // ww..wbw
    -32,   // ..b.wbw
    13,    // b.b.wbw
    -72,   // w.b.wbw
    -79,   // .bb.wbw
    -54,   // bbb.wbw
    -47,   // wbb.wbw
    1,     // .wb.wbw
    0,     // bwb.wbw
    -30,   // wwb.wbw
    51,    // ..w.wbw
    71,    // b.w.wbw
    46,    // w.w.wbw
    -2,    // .bw.wbw
    -67,   // bbw.wbw
    1,     // wbw.wbw
    32,    // .ww.wbw
    -32,   // bww.wbw
    43,    // www.wbw
    -15,   // ...bwbw
    -38,   // b..bwbw
    73,    // w..bwbw
    17,    // .b.bwbw
    1,     // bb.bwbw
    -31,   // wb.bwbw
    -30,   // .w.bwbw
    -48,   // bw.bwbw
    -59,   // ww.bwbw
    43,    // ..bbwbw
    21,    // b.bbwbw
    -29,   // w.bbwbw
    49,    // .bbbwbw
    65,    // bbbbwbw
    3,     // wbbbwbw
    54,    // .wbbwbw
    95,    // bwbbwbw
    17,    // wwbbwbw
    9,     // ..wbwbw
    -65,   // b.wbwbw
    -38,   // w.wbwbw
    -25,   // .bwbwbw
    132,   // bbwbwbw
    65,    // wbwbwbw
    58,    // .wwbwbw
    7,     // bwwbwbw
    -17,   // wwwbwbw
    -1,    // ...wwbw
    33,    // b..wwbw
    -137,  // w..wwbw
    102,   // .b.wwbw
    -21,   // bb.wwbw
    37,    // wb.wwbw
    2,     // .w.wwbw
    41,    // bw.wwbw
    14,    // ww.wwbw
    -19,   // ..bwwbw
    19,    // b.bwwbw
    -17,   // w.bwwbw
    2,     // .bbwwbw
    -44,   // bbbwwbw
    2,     // wbbwwbw
    47,    // .wbwwbw
    -95,   // bwbwwbw
    -18,   // wwbwwbw
    45,    // ..wwwbw
    28,    // b.wwwbw
    36,    // w.wwwbw
    -71,   // .bwwwbw
    -20,   // bbwwwbw
    -57,   // wbwwwbw
    15,    // .wwwwbw
    101,   // bwwwwbw
    17,    // wwwwwbw
    -15,   // .....ww
    20,    // b....ww
    22,    // w....ww
    -15,   // .b...ww
    0,     // bb...ww
    -17,   // wb...ww
    -2,    // .w...ww
    34,    // bw...ww
    19,    // ww...ww
    37,    // ..b..ww
    1,     // b.b..ww
    -12,   // w.b..ww
    -85,   // .bb..ww
    -20,   // bbb..ww
    -14,   // wbb..ww
    -42,   // .wb..ww
    -11,   // bwb..ww
    -20,   // wwb..ww
    -24,   // ..w..ww
    -42,   // b.w..ww
    77,    // w.w..ww
    -37,   // .bw..ww
    -16,   // bbw..ww
    86,    // wbw..ww
    -11,   // .ww..ww
    12,    // bww..ww
    -60,   // www..ww
    -23,   // ...b.ww
    117,   // b..b.ww
    0,     // w..b.ww
    -18,   // .b.b.ww
    -5,    // bb.b.ww
    -29,   // wb.b.ww
    44,    // .w.b.ww
    -10,   // bw.b.ww
    -85,   // ww.b.ww
    -26,   // ..bb.ww
    -54,   // b.bb.ww
    24,    // w.bb.ww
    6,     // .bbb.ww
    47,    // bbbb.ww
    2,     // wbbb.ww
    69,    // .wbb.ww
    21,    // bwbb.ww
    51,    // wwbb.ww
    65,    // ..wb.ww
    6,     // b.wb.ww
    -28,   // w.wb.ww
    -19,   // .bwb.ww
    -123,  // bbwb.ww
    -59,   // wbwb.ww
    -53,   // .wwb.ww
    -42,   // bwwb.ww
    -64,   // wwwb.ww
    -150,  // ...w.ww
    25,    // b..w.ww
    -30,   // w..w.ww
    -118,  // .b.w.ww
    5,     // bb.w.ww
    43,    // wb.w.ww
    50,    // .w.w.ww
    -52,   // bw.w.ww
    -25,   // ww.w.ww
    9,     // ..bw.ww
    44,    // b.bw.ww
    -4,    // w.bw.ww
    -70,   // .bbw.ww
    -28,   // bbbw.ww
    -1,    // wbbw.ww
    -33,   // .wbw.ww
    -1,    // bwbw.ww
    -25,   // wwbw.ww
    -36,   // ..ww.ww
    -27,   // b.ww.ww
    50,    // w.ww.ww
    -70,   // .bww.ww
    86,    // bbww.ww
    14,    // wbww.ww
    34,    // .www.ww
    -6,    // bwww.ww
    54,    // wwww.ww
    46,    // ....bww
    6,     // b...bww
    -6,    // w...bww
    54,    // .b..bww
    16,    // bb..bww
    -55,   // wb..bww
    7,     // .w..bww
    -37,   // bw..bww
    -20,   // ww..bww
    -12,   // ..b.bww
    -58,   // b.b.bww
    5,     // w.b.bww
    -38,   // .bb.bww
    -61,   // bbb.bww
    9,     // wbb.bww
    -4,    // .wb.bww
    67,    // bwb.bww
    100,   // wwb.bww
    25,    // ..w.bww
    -3,    // b.w.bww
    -17,   // w.w.bww
    2,     // .bw.bww
    0,     // bbw.bww
    -30,   // wbw.bww
    4,     // .ww.bww
    10,    // bww.bww
    -61,   // www.bww
    22,    // ...bbww
    -66,   // b..bbww
    42,    // w..bbww
    -27,   // .b.bbww
    -86,   // bb.bbww
    -85,   // wb.bbww
    6,     // .w.bbww
    2,     // bw.bbww
    51,    // ww.bbww
    -48,   // ..bbbww
    14,    // b.bbbww
    -5,    // w.bbbww
    -36,   // .bbbbww
    68,    // bbbbbww
    19,    // wbbbbww
    -29,   // .wbbbww
    20,    // bwbbbww
    -2,    // wwbbbww
    -51,   // ..wbbww
    -55,   // b.wbbww
    8,     // w.wbbww
    82,    // .bwbbww
    60,    // bbwbbww
    17,    // wbwbbww
    103,   // .wwbbww
    -25,   // bwwbbww
    -21,   // wwwbbww
    52,    // ...wbww
    -4,    // b..wbww
    45,    // w..wbww
    17,    // .b.wbww
    123,   // bb.wbww
    56,    // wb.wbww
    -28,   // .w.wbww
    -17,   // bw.wbww
    -25,   // ww.wbww
    -30,   // ..bwbww
    74,    // b.bwbww
    -11,   // w.bwbww
    119,   // .bbwbww
    -14,   // bbbwbww
    4,     // wbbwbww
    -7,    // .wbwbww
    -132,  // bwbwbww
    34,    // wwbwbww
    28,    // ..wwbww
    -57,   // b.wwbww
    17,    // w.wwbww
    -13,   // .bwwbww
    -60,   // bbwwbww
    -18,   // wbwwbww
    105,   // .wwwbww
    -15,   // bwwwbww
    23,    // wwwwbww
    -166,  // ....www
    -54,   // b...www
    27,    // w...www
    -50,   // .b..www
    20,    // bb..www
    7,     // wb..www
    -11,   // .w..www
    -41,   // bw..www
    -60,   // ww..www
    -78,   // ..b.www
    -21,   // b.b.www
    -28,   // w.b.www
    -55,   // .bb.www
    0,     // bbb.www
    27,    // wbb.www
    -35,   // .wb.www
    54,    // bwb.www
    -61,   // wwb.www
    -141,  // ..w.www
    17,    // b.w.www
    -46,   // w.w.www
    -4,    // .bw.www
    61,    // bbw.www
    43,    // wbw.www
    -16,   // .ww.www
    -17,   // bww.www
    -39,   // www.www
    -55,   // ...bwww
    9,     // b..bwww
    -50,   // w..bwww
    73,    // .b.bwww
    28,    // bb.bwww
    -20,   // wb.bwww
    81,    // .w.bwww
    -29,   // bw.bwww
    -64,   // ww.bwww
    -74,   // ..bbwww
    89,    // b.bbwww
    -66,   // w.bbwww
    -16,   // .bbbwww
    -90,   // bbbbwww
    -33,   // wbbbwww
    21,    // .wbbwww
    44,    // bwbbwww
    -21,   // wwbbwww
    144,   // ..wbwww
    -88,   // b.wbwww
    50,    // w.wbwww
    -2,    // .bwbwww
    14,    // bbwbwww
    -17,   // wbwbwww
    21,    // .wwbwww
    165,   // bwwbwww
    -49,   // wwwbwww
    -313,  // ...wwww
    -73,   // b..wwww
    -21,   // w..wwww
    -265,  // .b.wwww
    -47,   // bb.wwww
    -71,   // wb.wwww
    73,    // .w.wwww
    -51,   // bw.wwww
    54,    // ww.wwww
    -48,   // ..bwwww
    18,    // b.bwwww
    -61,   // w.bwwww
    -14,   // .bbwwww
    90,    // bbbwwww
    20,    // wbbwwww
    77,    // .wbwwww
    -65,   // bwbwwww
    23,    // wwbwwww
    -45,   // ..wwwww
    -46,   // b.wwwww
    57,    // w.wwwww
    -108,  // .bwwwww
    -68,   // bbwwwww
    17,    // wbwwwww
    13,    // .wwwwww
    26,    // bwwwwww
    38,    // wwwwwww
    0,     // captures=0 threats=0
    61,    // captures=0 threats=1
    67,    // captures=0 threats=2
    68,    // captures=0 threats=3
    71,    // captures=0 threats=4
    135,   // captures=0 additional threats
    58,    // captures=1 threats=0
    162,   // captures=1 threats=1
    191,   // captures=1 threats=2
    200,   // captures=1 threats=3
    210,   // captures=1 threats=4
    6,     // captures=1 additional threats
    63,    // captures=2 threats=0
    171,   // captures=2 threats=1
    202,   // captures=2 threats=2
    208,   // captures=2 threats=3
    223,   // captures=2 threats=4
    66,    // captures=2 additional threats
    63,    // captures=3 threats=0
    294,   // captures=3 threats=1
    642,   // captures=3 threats=2
    812,   // captures=3 threats=3
    833,   // captures=3 threats=4
    117,   // captures=3 additional threats
    290,   // captures=4 threats=0
    1458,  // captures=4 threats=1
    1555,  // captures=4 threats=2
    1719,  // captures=4 threats=3
    1751,  // captures=4 threats=4
    34,    // captures=4 additional threats
].into_boxed_slice()
