vec![
    0,     // .......
    0,     // b......
    0,     // w......
    2,     // .b.....
    47,    // bb.....
    1,     // wb.....
    -2,    // .w.....
    -1,    // bw.....
    -47,   // ww.....
    7,     // ..b....
    40,    // b.b....
    -6,    // w.b....
    -41,   // .bb....
    93,    // bbb....
    -20,   // wbb....
    9,     // .wb....
    -13,   // bwb....
    31,    // wwb....
    -7,    // ..w....
    6,     // b.w....
    -40,   // w.w....
    -9,    // .bw....
    -31,   // bbw....
    13,    // wbw....
    41,    // .ww....
    20,    // bww....
    -93,   // www....
    -18,   // ...b...
    -7,    // b..b...
    -13,   // w..b...
    -13,   // .b.b...
    104,   // bb.b...
    -40,   // wb.b...
    -32,   // .w.b...
    -43,   // bw.b...
    -37,   // ww.b...
    -12,   // ..bb...
    -13,   // b.bb...
    18,    // w.bb...
    -3,    // .bbb...
    141,   // bbbb...
    -33,   // wbbb...
    -3,    // .wbb...
    30,    // bwbb...
    -1,    // wwbb...
    10,    // ..wb...
    -20,   // b.wb...
    -30,   // w.wb...
    47,    // .bwb...
    19,    // bbwb...
    -16,   // wbwb...
    19,    // .wwb...
    64,    // bwwb...
    2,     // wwwb...
    18,    // ...w...
    13,    // b..w...
    7,     // w..w...
    32,    // .b.w...
    37,    // bb.w...
    43,    // wb.w...
    13,    // .w.w...
    40,    // bw.w...
    -104,  // ww.w...
    -10,   // ..bw...
    30,    // b.bw...
    20,    // w.bw...
    -19,   // .bbw...
    -2,    // bbbw...
    -64,   // wbbw...
    -47,   // .wbw...
    16,    // bwbw...
    -19,   // wwbw...
    12,    // ..ww...
    -18,   // b.ww...
    13,    // w.ww...
    3,     // .bww...
    1,     // bbww...
    -30,   // wbww...
    3,     // .www...
    33,    // bwww...
    -141,  // wwww...
    7,     // ....b..
    8,     // b...b..
    -29,   // w...b..
    -19,   // .b..b..
    7,     // bb..b..
    -22,   // wb..b..
    -29,   // .w..b..
    -42,   // bw..b..
    24,    // ww..b..
    -40,   // ..b.b..
    11,    // b.b.b..
    -18,   // w.b.b..
    26,    // .bb.b..
    37,    // bbb.b..
    -51,   // wbb.b..
    -8,    // .wb.b..
    -46,   // bwb.b..
    -30,   // wwb.b..
    0,     // ..w.b..
    16,    // b.w.b..
    31,    // w.w.b..
    -19,   // .bw.b..
    2,     // bbw.b..
    8,     // wbw.b..
    29,    // .ww.b..
    48,    // bww.b..
    -50,   // www.b..
    -12,   // ...bb..
    -26,   // b..bb..
    58,    // w..bb..
    -3,    // .b.bb..
    4,     // bb.bb..
    0,     // wb.bb..
    13,    // .w.bb..
    34,    // bw.bb..
    -39,   // ww.bb..
    6,     // ..bbb..
    44,    // b.bbb..
    26,    // w.bbb..
    102,   // .bbbb..
    -10,   // bbbbb..
    21,    // wbbbb..
    -35,   // .wbbb..
    -22,   // bwbbb..
    -1,    // wwbbb..
    -22,   // ..wbb..
    31,    // b.wbb..
    12,    // w.wbb..
    -19,   // .bwbb..
    72,    // bbwbb..
    3,     // wbwbb..
    21,    // .wwbb..
    -14,   // bwwbb..
    30,    // wwwbb..
    -10,   // ...wb..
    -31,   // b..wb..
    -36,   // w..wb..
    3,     // .b.wb..
    12,    // bb.wb..
    -6,    // wb.wb..
    -23,   // .w.wb..
    23,    // bw.wb..
    21,    // ww.wb..
    -59,   // ..bwb..
    48,    // b.bwb..
    10,    // w.bwb..
    -8,    // .bbwb..
    -26,   // bbbwb..
    -3,    // wbbwb..
    33,    // .wbwb..
    44,    // bwbwb..
    60,    // wwbwb..
    22,    // ..wwb..
    -12,   // b.wwb..
    1,     // w.wwb..
    -6,    // .bwwb..
    11,    // bbwwb..
    -15,   // wbwwb..
    21,    // .wwwb..
    2,     // bwwwb..
    -29,   // wwwwb..
    -7,    // ....w..
    29,    // b...w..
    -8,    // w...w..
    29,    // .b..w..
    -24,   // bb..w..
    42,    // wb..w..
    19,    // .w..w..
    22,    // bw..w..
    -7,    // ww..w..
    0,     // ..b.w..
    -31,   // b.b.w..
    -16,   // w.b.w..
    -29,   // .bb.w..
    50,    // bbb.w..
    -48,   // wbb.w..
    19,    // .wb.w..
    -8,    // bwb.w..
    -2,    // wwb.w..
    40,    // ..w.w..
    18,    // b.w.w..
    -11,   // w.w.w..
    8,     // .bw.w..
    30,    // bbw.w..
    46,    // wbw.w..
    -26,   // .ww.w..
    51,    // bww.w..
    -37,   // www.w..
    10,    // ...bw..
    36,    // b..bw..
    31,    // w..bw..
    23,    // .b.bw..
    -21,   // bb.bw..
    -23,   // wb.bw..
    -3,    // .w.bw..
    6,     // bw.bw..
    -12,   // ww.bw..
    -22,   // ..bbw..
    -1,    // b.bbw..
    12,    // w.bbw..
    -21,   // .bbbw..
    29,    // bbbbw..
    -2,    // wbbbw..
    6,     // .wbbw..
    15,    // bwbbw..
    -11,   // wwbbw..
    59,    // ..wbw..
    -10,   // b.wbw..
    -48,   // w.wbw..
    -33,   // .bwbw..
    -60,   // bbwbw..
    -44,   // wbwbw..
    8,     // .wwbw..
    3,     // bwwbw..
    26,    // wwwbw..
    12,    // ...ww..
    -58,   // b..ww..
    26,    // w..ww..
    -13,   // .b.ww..
    39,    // bb.ww..
    -34,   // wb.ww..
    3,     // .w.ww..
    0,     // bw.ww..
    -4,    // ww.ww..
    22,    // ..bww..
    -12,   // b.bww..
    -31,   // w.bww..
    -21,   // .bbww..
    -30,   // bbbww..
    14,    // wbbww..
    19,    // .wbww..
    -3,    // bwbww..
    -72,   // wwbww..
    -6,    // ..www..
    -26,   // b.www..
    -44,   // w.www..
    35,    // .bwww..
    1,     // bbwww..
    22,    // wbwww..
    -102,  // .wwww..
    -21,   // bwwww..
    10,    // wwwww..
    2,     // .....b.
    -19,   // b....b.
    16,    // w....b.
    -4,    // .b...b.
    -15,   // bb...b.
    8,     // wb...b.
    0,     // .w...b.
    15,    // bw...b.
    -49,   // ww...b.
    -19,   // ..b..b.
    29,    // b.b..b.
    -3,    // w.b..b.
    -43,   // .bb..b.
    7,     // bbb..b.
    -18,   // wbb..b.
    16,    // .wb..b.
    31,    // bwb..b.
    -24,   // wwb..b.
    29,    // ..w..b.
    7,     // b.w..b.
    -11,   // w.w..b.
    16,    // .bw..b.
    -3,    // bbw..b.
    40,    // wbw..b.
    32,    // .ww..b.
    -4,    // bww..b.
    1,     // www..b.
    -13,   // ...b.b.
    9,     // b..b.b.
    -8,    // w..b.b.
    2,     // .b.b.b.
    -52,   // bb.b.b.
    -41,   // wb.b.b.
    2,     // .w.b.b.
    2,     // bw.b.b.
    -5,    // ww.b.b.
    -3,    // ..bb.b.
    -11,   // b.bb.b.
    14,    // w.bb.b.
    56,    // .bbb.b.
    48,    // bbbb.b.
    47,    // wbbb.b.
    -7,    // .wbb.b.
    0,     // bwbb.b.
    -10,   // wwbb.b.
    23,    // ..wb.b.
    -20,   // b.wb.b.
    -18,   // w.wb.b.
    10,    // .bwb.b.
    -25,   // bbwb.b.
    3,     // wbwb.b.
    13,    // .wwb.b.
    -37,   // bwwb.b.
    7,     // wwwb.b.
    32,    // ...w.b.
    -30,   // b..w.b.
    -24,   // w..w.b.
    -1,    // .b.w.b.
    -13,   // bb.w.b.
    -11,   // wb.w.b.
    -2,    // .w.w.b.
    -18,   // bw.w.b.
    -20,   // ww.w.b.
    3,     // ..bw.b.
    -20,   // b.bw.b.
    28,    // w.bw.b.
    47,    // .bbw.b.
    21,    // bbbw.b.
    45,    // wbbw.b.
    16,    // .wbw.b.
    51,    // bwbw.b.
    6,     // wwbw.b.
    -13,   // ..ww.b.
    -12,   // b.ww.b.
    -33,   // w.ww.b.
    -17,   // .bww.b.
    6,     // bbww.b.
    4,     // wbww.b.
    16,    // .www.b.
    -30,   // bwww.b.
    -14,   // wwww.b.
    -41,   // ....bb.
    -26,   // b...bb.
    22,    // w...bb.
    -43,   // .b..bb.
    14,    // bb..bb.
    8,     // wb..bb.
    -32,   // .w..bb.
    -44,   // bw..bb.
    -10,   // ww..bb.
    26,    // ..b.bb.
    17,    // b.b.bb.
    51,    // w.b.bb.
    39,    // .bb.bb.
    3,     // bbb.bb.
    -10,   // wbb.bb.
    -10,   // .wb.bb.
    26,    // bwb.bb.
    -30,   // wwb.bb.
    -29,   // ..w.bb.
    -38,   // b.w.bb.
    17,    // w.w.bb.
    -9,    // .bw.bb.
    17,    // bbw.bb.
    -9,    // wbw.bb.
    0,     // .ww.bb.
    -5,    // bww.bb.
    -3,    // www.bb.
    -3,    // ...bbb.
    38,    // b..bbb.
    -45,   // w..bbb.
    56,    // .b.bbb.
    43,    // bb.bbb.
    -36,   // wb.bbb.
    -16,   // .w.bbb.
    -13,   // bw.bbb.
    3,     // ww.bbb.
    102,   // ..bbbb.
    -49,   // b.bbbb.
    68,    // w.bbbb.
    6,     // .bbbbb.
    -10,   // bbbbbb.
    14,    // wbbbbb.
    72,    // .wbbbb.
    8,     // bwbbbb.
    5,     // wwbbbb.
    -21,   // ..wbbb.
    -37,   // b.wbbb.
    15,    // w.wbbb.
    2,     // .bwbbb.
    10,    // bbwbbb.
    54,    // wbwbbb.
    -18,   // .wwbbb.
    26,    // bwwbbb.
    33,    // wwwbbb.
    -19,   // ...wbb.
    -73,   // b..wbb.
    -17,   // w..wbb.
    47,    // .b.wbb.
    -17,   // bb.wbb.
    -20,   // wb.wbb.
    -13,   // .w.wbb.
    -44,   // bw.wbb.
    -36,   // ww.wbb.
    -8,    // ..bwbb.
    -69,   // b.bwbb.
    -14,   // w.bwbb.
    65,    // .bbwbb.
    -80,   // bbbwbb.
    -7,    // wbbwbb.
    5,     // .wbwbb.
    -27,   // bwbwbb.
    13,    // wwbwbb.
    -21,   // ..wwbb.
    -5,    // b.wwbb.
    -54,   // w.wwbb.
    12,    // .bwwbb.
    18,    // bbwwbb.
    -7,    // wbwwbb.
    18,    // .wwwbb.
    24,    // bwwwbb.
    -73,   // wwwwbb.
    -9,    // ....wb.
    -30,   // b...wb.
    -39,   // w...wb.
    16,    // .b..wb.
    -9,    // bb..wb.
    -2,    // wb..wb.
    -16,   // .w..wb.
    7,     // bw..wb.
    20,    // ww..wb.
    -19,   // ..b.wb.
    20,    // b.b.wb.
    -6,    // w.b.wb.
    -9,    // .bb.wb.
    -47,   // bbb.wb.
    -2,    // wbb.wb.
    0,     // .wb.wb.
    -25,   // bwb.wb.
    -20,   // wwb.wb.
    8,     // ..w.wb.
    33,    // b.w.wb.
    32,    // w.w.wb.
    26,    // .bw.wb.
    5,     // bbw.wb.
    50,    // wbw.wb.
    10,    // .ww.wb.
    -52,   // bww.wb.
    15,    // www.wb.
    47,    // ...bwb.
    63,    // b..bwb.
    -5,    // w..bwb.
    10,    // .b.bwb.
    -6,    // bb.bwb.
    19,    // wb.bwb.
    -16,   // .w.bwb.
    -16,   // bw.bwb.
    42,    // ww.bwb.
    -19,   // ..bbwb.
    -35,   // b.bbwb.
    -23,   // w.bbwb.
    2,     // .bbbwb.
    1,     // bbbbwb.
    -5,    // wbbbwb.
    -11,   // .wbbwb.
    -7,    // bwbbwb.
    11,    // wwbbwb.
    -33,   // ..wbwb.
    21,    // b.wbwb.
    -5,    // w.wbwb.
    11,    // .bwbwb.
    -28,   // bbwbwb.
    -24,   // wbwbwb.
    -5,    // .wwbwb.
    -25,   // bwwbwb.
    -42,   // wwwbwb.
    3,     // ...wwb.
    -13,   // b..wwb.
    20,    // w..wwb.
    -17,   // .b.wwb.
    30,    // bb.wwb.
    66,    // wb.wwb.
    7,     // .w.wwb.
    37,    // bw.wwb.
    22,    // ww.wwb.
    -6,    // ..bwwb.
    62,    // b.bwwb.
    -32,   // w.bwwb.
    12,    // .bbwwb.
    10,    // bbbwwb.
    -5,    // wbbwwb.
    11,    // .wbwwb.
    -37,   // bwbwwb.
    30,    // wwbwwb.
    35,    // ..wwwb.
    -11,   // b.wwwb.
    -15,   // w.wwwb.
    -21,   // .bwwwb.
    -24,   // bbwwwb.
    1,     // wbwwwb.
    -72,   // .wwwwb.
    2,     // bwwwwb.
    -2,    // wwwwwb.
    -2,    // .....w.
    -16,   // b....w.
    19,    // w....w.
    0,     // .b...w.
    49,    // bb...w.
    -15,   // wb...w.
    4,     // .w...w.
    -8,    // bw...w.
    15,    // ww...w.
    -29,   // ..b..w.
    11,    // b.b..w.
    -7,    // w.b..w.
    -32,   // .bb..w.
    -1,    // bbb..w.
    4,     // wbb..w.
    -16,   // .wb..w.
    -40,   // bwb..w.
    3,     // wwb..w.
    19,    // ..w..w.
    3,     // b.w..w.
    -29,   // w.w..w.
    -16,   // .bw..w.
    24,    // bbw..w.
    -31,   // wbw..w.
    43,    // .ww..w.
    18,    // bww..w.
    -7,    // www..w.
    -32,   // ...b.w.
    24,    // b..b.w.
    30,    // w..b.w.
    2,     // .b.b.w.
    20,    // bb.b.w.
    18,    // wb.b.w.
    1,     // .w.b.w.
    11,    // bw.b.w.
    13,    // ww.b.w.
    13,    // ..bb.w.
    33,    // b.bb.w.
    12,    // w.bb.w.
    -16,   // .bbb.w.
    14,    // bbbb.w.
    30,    // wbbb.w.
    17,    // .wbb.w.
    -4,    // bwbb.w.
    -6,    // wwbb.w.
    -3,    // ..wb.w.
    -28,   // b.wb.w.
    20,    // w.wb.w.
    -16,   // .bwb.w.
    -6,    // bbwb.w.
    -51,   // wbwb.w.
    -47,   // .wwb.w.
    -45,   // bwwb.w.
    -21,   // wwwb.w.
    13,    // ...w.w.
    8,     // b..w.w.
    -9,    // w..w.w.
    -2,    // .b.w.w.
    5,     // bb.w.w.
    -2,    // wb.w.w.
    -2,    // .w.w.w.
    41,    // bw.w.w.
    52,    // ww.w.w.
    -23,   // ..bw.w.
    18,    // b.bw.w.
    20,    // w.bw.w.
    -13,   // .bbw.w.
    -7,    // bbbw.w.
    37,    // wbbw.w.
    -10,   // .wbw.w.
    -3,    // bwbw.w.
    25,    // wwbw.w.
    3,     // ..ww.w.
    -14,   // b.ww.w.
    11,    // w.ww.w.
    7,     // .bww.w.
    10,    // bbww.w.
    0,     // wbww.w.
    -56,   // .www.w.
    -47,   // bwww.w.
    -48,   // wwww.w.
    9,     // ....bw.
    39,    // b...bw.
    30,    // w...bw.
    16,    // .b..bw.
    -20,   // bb..bw.
    -7,    // wb..bw.
    -16,   // .w..bw.
    2,     // bw..bw.
    9,     // ww..bw.
    -8,    // ..b.bw.
    -32,   // b.b.bw.
    -33,   // w.b.bw.
    -10,   // .bb.bw.
    -15,   // bbb.bw.
    52,    // wbb.bw.
    -26,   // .wb.bw.
    -50,   // bwb.bw.
    -5,    // wwb.bw.
    19,    // ..w.bw.
    6,     // b.w.bw.
    -20,   // w.w.bw.
    0,     // .bw.bw.
    20,    // bbw.bw.
    25,    // wbw.bw.
    9,     // .ww.bw.
    2,     // bww.bw.
    47,    // www.bw.
    -3,    // ...bbw.
    -20,   // b..bbw.
    13,    // w..bbw.
    -7,    // .b.bbw.
    -22,   // bb.bbw.
    -37,   // wb.bbw.
    17,    // .w.bbw.
    -66,   // bw.bbw.
    -30,   // ww.bbw.
    -35,   // ..bbbw.
    15,    // b.bbbw.
    11,    // w.bbbw.
    72,    // .bbbbw.
    2,     // bbbbbw.
    -2,    // wbbbbw.
    21,    // .wbbbw.
    -1,    // bwbbbw.
    24,    // wwbbbw.
    6,     // ..wbbw.
    32,    // b.wbbw.
    -62,   // w.wbbw.
    -11,   // .bwbbw.
    -30,   // bbwbbw.
    37,    // wbwbbw.
    -12,   // .wwbbw.
    5,     // bwwbbw.
    -10,   // wwwbbw.
    -47,   // ...wbw.
    5,     // b..wbw.
    -63,   // w..wbw.
    16,    // .b.wbw.
    -42,   // bb.wbw.
    16,    // wb.wbw.
    -10,   // .w.wbw.
    -19,   // bw.wbw.
    6,     // ww.wbw.
    33,    // ..bwbw.
    5,     // b.bwbw.
    -21,   // w.bwbw.
    5,     // .bbwbw.
    42,    // bbbwbw.
    25,    // wbbwbw.
    -11,   // .wbwbw.
    24,    // bwbwbw.
    28,    // wwbwbw.
    19,    // ..wwbw.
    23,    // b.wwbw.
    35,    // w.wwbw.
    11,    // .bwwbw.
    -11,   // bbwwbw.
    7,     // wbwwbw.
    -2,    // .wwwbw.
    5,     // bwwwbw.
    -1,    // wwwwbw.
    41,    // ....ww.
    -22,   // b...ww.
    26,    // w...ww.
    32,    // .b..ww.
    10,    // bb..ww.
    44,    // wb..ww.
    43,    // .w..ww.
    -8,    // bw..ww.
    -14,   // ww..ww.
    29,    // ..b.ww.
    -17,   // b.b.ww.
    38,    // w.b.ww.
    0,     // .bb.ww.
    3,     // bbb.ww.
    5,     // wbb.ww.
    9,     // .wb.ww.
    9,     // bwb.ww.
    -17,   // wwb.ww.
    -26,   // ..w.ww.
    -51,   // b.w.ww.
    -17,   // w.w.ww.
    10,    // .bw.ww.
    30,    // bbw.ww.
    -26,   // wbw.ww.
    -39,   // .ww.ww.
    10,    // bww.ww.
    -3,    // www.ww.
    19,    // ...bww.
    17,    // b..bww.
    73,    // w..bww.
    13,    // .b.bww.
    36,    // bb.bww.
    44,    // wb.bww.
    -47,   // .w.bww.
    20,    // bw.bww.
    17,    // ww.bww.
    21,    // ..bbww.
    54,    // b.bbww.
    5,     // w.bbww.
    -18,   // .bbbww.
    73,    // bbbbww.
    -24,   // wbbbww.
    -12,   // .wbbww.
    7,     // bwbbww.
    -18,   // wwbbww.
    8,     // ..wbww.
    14,    // b.wbww.
    69,    // w.wbww.
    -5,    // .bwbww.
    -13,   // bbwbww.
    27,    // wbwbww.
    -65,   // .wwbww.
    7,     // bwwbww.
    80,    // wwwbww.
    3,     // ...www.
    45,    // b..www.
    -38,   // w..www.
    16,    // .b.www.
    -3,    // bb.www.
    13,    // wb.www.
    -56,   // .w.www.
    36,    // bw.www.
    -43,   // ww.www.
    21,    // ..bwww.
    -15,   // b.bwww.
    37,    // w.bwww.
    18,    // .bbwww.
    -33,   // bbbwww.
    -26,   // wbbwww.
    -2,    // .wbwww.
    -54,   // bwbwww.
    -10,   // wwbwww.
    -102,  // ..wwww.
    -68,   // b.wwww.
    49,    // w.wwww.
    -72,   // .bwwww.
    -5,    // bbwwww.
    -8,    // wbwwww.
    -6,    // .wwwww.
    -14,   // bwwwww.
    10,    // wwwwww.
    0,     // ......b
    -61,   // b.....b
    0,     // w.....b
    -19,   // .b....b
    38,    // bb....b
    54,    // wb....b
    -16,   // .w....b
    -23,   // bw....b
    -5,    // ww....b
    8,     // ..b...b
    -56,   // b.b...b
    -19,   // w.b...b
    -26,   // .bb...b
    18,    // bbb...b
    -30,   // wbb...b
    39,    // .wb...b
    7,     // bwb...b
    34,    // wwb...b
    29,    // ..w...b
    -18,   // b.w...b
    -33,   // w.w...b
    -30,   // .bw...b
    -13,   // bbw...b
    -18,   // wbw...b
    -22,   // .ww...b
    -22,   // bww...b
    1,     // www...b
    -7,    // ...b..b
    5,     // b..b..b
    -49,   // w..b..b
    9,     // .b.b..b
    -28,   // bb.b..b
    -59,   // wb.b..b
    24,    // .w.b..b
    0,     // bw.b..b
    4,     // ww.b..b
    -26,   // ..bb..b
    -31,   // b.bb..b
    -16,   // w.bb..b
    38,    // .bbb..b
    15,    // bbbb..b
    60,    // wbbb..b
    -20,   // .wbb..b
    0,     // bwbb..b
    -42,   // wwbb..b
    36,    // ..wb..b
    24,    // b.wb..b
    -16,   // w.wb..b
    63,    // .bwb..b
    26,    // bbwb..b
    -15,   // wbwb..b
    17,    // .wwb..b
    26,    // bwwb..b
    -55,   // wwwb..b
    13,    // ...w..b
    11,    // b..w..b
    49,    // w..w..b
    -30,   // .b.w..b
    32,    // bb.w..b
    -32,   // wb.w..b
    8,     // .w.w..b
    -9,    // bw.w..b
    18,    // ww.w..b
    -31,   // ..bw..b
    34,    // b.bw..b
    28,    // w.bw..b
    -73,   // .bbw..b
    -60,   // bbbw..b
    39,    // wbbw..b
    5,     // .wbw..b
    -24,   // bwbw..b
    -5,    // wwbw..b
    -58,   // ..ww..b
    -29,   // b.ww..b
    -62,   // w.ww..b
    -13,   // .bww..b
    -50,   // bbww..b
    8,     // wbww..b
    45,    // .www..b
    -19,   // bwww..b
    11,    // wwww..b
    40,    // ....b.b
    -56,   // b...b.b
    33,    // w...b.b
    29,    // .b..b.b
    5,     // bb..b.b
    33,    // wb..b.b
    11,    // .w..b.b
    -44,   // bw..b.b
    -1,    // ww..b.b
    11,    // ..b.b.b
    -23,   // b.b.b.b
    16,    // w.b.b.b
    17,    // .bb.b.b
    19,    // bbb.b.b
    62,    // wbb.b.b
    -32,   // .wb.b.b
    -48,   // bwb.b.b
    -34,   // wwb.b.b
    -31,   // ..w.b.b
    -14,   // b.w.b.b
    0,     // w.w.b.b
    20,    // .bw.b.b
    22,    // bbw.b.b
    27,    // wbw.b.b
    -17,   // .ww.b.b
    38,    // bww.b.b
    -33,   // www.b.b
    -13,   // ...bb.b
    -31,   // b..bb.b
    62,    // w..bb.b
    -11,   // .b.bb.b
    16,    // bb.bb.b
    50,    // wb.bb.b
    33,    // .w.bb.b
    40,    // bw.bb.b
    21,    // ww.bb.b
    44,    // ..bbb.b
    16,    // b.bbb.b
    32,    // w.bbb.b
    -49,   // .bbbb.b
    34,    // bbbbb.b
    -5,    // wbbbb.b
    15,    // .wbbb.b
    -19,   // bwbbb.b
    14,    // wwbbb.b
    -1,    // ..wbb.b
    -3,    // b.wbb.b
    -40,   // w.wbb.b
    -35,   // .bwbb.b
    -39,   // bbwbb.b
    -18,   // wbwbb.b
    54,    // .wwbb.b
    1,     // bwwbb.b
    34,    // wwwbb.b
    30,    // ...wb.b
    34,    // b..wb.b
    16,    // w..wb.b
    -20,   // .b.wb.b
    -19,   // bb.wb.b
    -14,   // wb.wb.b
    18,    // .w.wb.b
    26,    // bw.wb.b
    1,     // ww.wb.b
    48,    // ..bwb.b
    -5,    // b.bwb.b
    28,    // w.bwb.b
    -69,   // .bbwb.b
    25,    // bbbwb.b
    -13,   // wbbwb.b
    5,     // .wbwb.b
    7,     // bwbwb.b
    13,    // wwbwb.b
    -12,   // ..wwb.b
    1,     // b.wwb.b
    40,    // w.wwb.b
    62,    // .bwwb.b
    20,    // bbwwb.b
    24,    // wbwwb.b
    -15,   // .wwwb.b
    22,    // bwwwb.b
    -14,   // wwwwb.b
    6,     // ....w.b
    -18,   // b...w.b
    19,    // w...w.b
    7,     // .b..w.b
    -23,   // bb..w.b
    35,    // wb..w.b
    3,     // .w..w.b
    17,    // bw..w.b
    4,     // ww..w.b
    16,    // ..b.w.b
    -14,   // b.b.w.b
    0,     // w.b.w.b
    -38,   // .bb.w.b
    25,    // bbb.w.b
    30,    // wbb.w.b
    6,     // .wb.w.b
    -40,   // bwb.w.b
    -53,   // wwb.w.b
    18,    // ..w.w.b
    7,     // b.w.w.b
    -16,   // w.w.w.b
    33,    // .bw.w.b
    58,    // bbw.w.b
    7,     // wbw.w.b
    -51,   // .ww.w.b
    5,     // bww.w.b
    30,    // www.w.b
    -20,   // ...bw.b
    24,    // b..bw.b
    -28,   // w..bw.b
    -20,   // .b.bw.b
    49,    // bb.bw.b
    23,    // wb.bw.b
    -28,   // .w.bw.b
    -1,    // bw.bw.b
    0,     // ww.bw.b
    31,    // ..bbw.b
    -3,    // b.bbw.b
    -32,   // w.bbw.b
    -37,   // .bbbw.b
    57,    // bbbbw.b
    -8,    // wbbbw.b
    32,    // .wbbw.b
    32,    // bwbbw.b
    82,    // wwbbw.b
    -10,   // ..wbw.b
    -19,   // b.wbw.b
    -28,   // w.wbw.b
    21,    // .bwbw.b
    -47,   // bbwbw.b
    43,    // wbwbw.b
    14,    // .wwbw.b
    -15,   // bwwbw.b
    44,    // wwwbw.b
    -18,   // ...ww.b
    -29,   // b..ww.b
    16,    // w..ww.b
    -12,   // .b.ww.b
    27,    // bb.ww.b
    31,    // wb.ww.b
    -14,   // .w.ww.b
    -2,    // bw.ww.b
    -17,   // ww.ww.b
    -12,   // ..bww.b
    1,     // b.bww.b
    32,    // w.bww.b
    -5,    // .bbww.b
    -58,   // bbbww.b
    -47,   // wbbww.b
    23,    // .wbww.b
    -9,    // bwbww.b
    -32,   // wwbww.b
    -26,   // ..www.b
    -12,   // b.www.b
    -32,   // w.www.b
    -11,   // .bwww.b
    38,    // bbwww.b
    34,    // wbwww.b
    -68,   // .wwww.b
    -8,    // bwwww.b
    25,    // wwwww.b
    47,    // .....bb
    38,    // b....bb
    5,     // w....bb
    -15,   // .b...bb
    -22,   // bb...bb
    -14,   // wb...bb
    49,    // .w...bb
    40,    // bw...bb
    0,     // ww...bb
    7,     // ..b..bb
    5,     // b.b..bb
    -4,    // w.b..bb
    14,    // .bb..bb
    -22,   // bbb..bb
    20,    // wbb..bb
    -20,   // .wb..bb
    46,    // bwb..bb
    61,    // wwb..bb
    -24,   // ..w..bb
    -23,   // b.w..bb
    1,     // w.w..bb
    -9,    // .bw..bb
    21,    // bbw..bb
    -23,   // wbw..bb
    10,    // .ww..bb
    -7,    // bww..bb
    -21,   // www..bb
    104,   // ...b.bb
    -28,   // b..b.bb
    -18,   // w..b.bb
    -52,   // .b.b.bb
    16,    // bb.b.bb
    25,    // wb.b.bb
    20,    // .w.b.bb
    48,    // bw.b.bb
    62,    // ww.b.bb
    4,     // ..bb.bb
    16,    // b.bb.bb
    17,    // w.bb.bb
    43,    // .bbb.bb
    -23,   // bbbb.bb
    -8,    // wbbb.bb
    -22,   // .wbb.bb
    -25,   // bwbb.bb
    6,     // wwbb.bb
    -21,   // ..wb.bb
    49,    // b.wb.bb
    -1,    // w.wb.bb
    -6,    // .bwb.bb
    -4,    // bbwb.bb
    45,    // wbwb.bb
    36,    // .wwb.bb
    23,    // bwwb.bb
    25,    // wwwb.bb
    37,    // ...w.bb
    32,    // b..w.bb
    -4,    // w..w.bb
    -13,   // .b.w.bb
    -19,   // bb.w.bb
    -39,   // wb.w.bb
    5,     // .w.w.bb
    -27,   // bw.w.bb
    -62,   // ww.w.bb
    12,    // ..bw.bb
    -19,   // b.bw.bb
    0,     // w.bw.bb
    -17,   // .bbw.bb
    -11,   // bbbw.bb
    -48,   // wbbw.bb
    -42,   // .wbw.bb
    -17,   // bwbw.bb
    -9,    // wwbw.bb
    39,    // ..ww.bb
    27,    // b.ww.bb
    -21,   // w.ww.bb
    30,    // .bww.bb
    16,    // bbww.bb
    -2,    // wbww.bb
    -3,    // .www.bb
    3,     // bwww.bb
    54,    // wwww.bb
    93,    // ....bbb
    18,    // b...bbb
    -1,    // w...bbb
    7,     // .b..bbb
    -22,   // bb..bbb
    -6,    // wb..bbb
    -1,    // .w..bbb
    -1,    // bw..bbb
    21,    // ww..bbb
    37,    // ..b.bbb
    19,    // b.b.bbb
    -30,   // w.b.bbb
    3,     // .bb.bbb
    44,    // bbb.bbb
    -4,    // wbb.bbb
    -15,   // .wb.bbb
    8,     // bwb.bbb
    -2,    // wwb.bbb
    50,    // ..w.bbb
    25,    // b.w.bbb
    33,    // w.w.bbb
    -47,   // .bw.bbb
    19,    // bbw.bbb
    -33,   // wbw.bbb
    3,     // .ww.bbb
    -4,    // bww.bbb
    0,     // www.bbb
    141,   // ...bbbb
    15,    // b..bbbb
    -11,   // w..bbbb
    48,    // .b.bbbb
    -23,   // bb.bbbb
    13,    // wb.bbbb
    14,    // .w.bbbb
    8,     // bw.bbbb
    -54,   // ww.bbbb
    -10,   // ..bbbbb
    34,    // b.bbbbb
    -25,   // w.bbbbb
    -10,   // .bbbbbb
    -51,   // bbbbbbb
    -29,   // wbbbbbb
    2,     // .wbbbbb
    -7,    // bwbbbbb
    32,    // wwbbbbb
    29,    // ..wbbbb
    57,    // b.wbbbb
    14,    // w.wbbbb
    1,     // .bwbbbb
    37,    // bbwbbbb
    36,    // wbwbbbb
    73,    // .wwbbbb
    2,     // bwwbbbb
    -5,    // wwwbbbb
    -2,    // ...wbbb
    -60,   // b..wbbb
    55,    // w..wbbb
    21,    // .b.wbbb
    -11,   // bb.wbbb
    3,     // wb.wbbb
    -7,    // .w.wbbb
    0,     // bw.wbbb
    -25,   // ww.wbbb
    -26,   // ..bwbbb
    25,    // b.bwbbb
    -44,   // w.bwbbb
    -80,   // .bbwbbb
    39,    // bbbwbbb
    1,     // wbbwbbb
    42,    // .wbwbbb
    9,     // bwbwbbb
    7,     // wwbwbbb
    -30,   // ..wwbbb
    -58,   // b.wwbbb
    -34,   // w.wwbbb
    10,    // .bwwbbb
    54,    // bbwwbbb
    65,    // wbwwbbb
    -33,   // .wwwbbb
    -38,   // bwwwbbb
    5,     // wwwwbbb
    -31,   // ....wbb
    -13,   // b...wbb
    -34,   // w...wbb
    -3,    // .b..wbb
    21,    // bb..wbb
    15,    // wb..wbb
    24,    // .w..wbb
    -10,   // bw..wbb
    -61,   // ww..wbb
    2,     // ..b.wbb
    22,    // b.b.wbb
    53,    // w.b.wbb
    17,    // .bb.wbb
    19,    // bbb.wbb
    -1,    // wbb.wbb
    20,    // .wb.wbb
    6,     // bwb.wbb
    0,     // wwb.wbb
    30,    // ..w.wbb
    58,    // b.w.wbb
    34,    // w.w.wbb
    5,     // .bw.wbb
    -32,   // bbw.wbb
    43,    // wbw.wbb
    30,    // .ww.wbb
    8,     // bww.wbb
    2,     // www.wbb
    19,    // ...bwbb
    26,    // b..bwbb
    5,     // w..bwbb
    -25,   // .b.bwbb
    -4,    // bb.bwbb
    22,    // wb.bwbb
    -6,    // .w.bwbb
    4,     // bw.bwbb
    9,     // ww.bwbb
    72,    // ..bbwbb
    -39,   // b.bbwbb
    32,    // w.bbwbb
    10,    // .bbbwbb
    37,    // bbbbwbb
    14,    // wbbbwbb
    -30,   // .wbbwbb
    -5,    // bwbbwbb
    31,    // wwbbwbb
    -60,   // ..wbwbb
    -47,   // b.wbwbb
    -13,   // w.wbwbb
    -28,   // .bwbwbb
    15,    // bbwbwbb
    27,    // wbwbwbb
    -13,   // .wwbwbb
    -11,   // bwwbwbb
    -7,    // wwwbwbb
    1,     // ...wwbb
    -50,   // b..wwbb
    42,    // w..wwbb
    6,     // .b.wwbb
    16,    // bb.wwbb
    -2,    // wb.wwbb
    10,    // .w.wwbb
    -8,    // bw.wwbb
    -6,    // ww.wwbb
    11,    // ..bwwbb
    20,    // b.bwwbb
    -82,   // w.bwwbb
    18,    // .bbwwbb
    54,    // bbbwwbb
    10,    // wbbwwbb
    -11,   // .wbwwbb
    -23,   // bwbwwbb
    -31,   // wwbwwbb
    1,     // ..wwwbb
    38,    // b.wwwbb
    -14,   // w.wwwbb
    -24,   // .bwwwbb
    -17,   // bbwwwbb
    -30,   // wbwwwbb
    -5,    // .wwwwbb
    -7,    // bwwwwbb
    -32,   // wwwwwbb
    -1,    // .....wb
    -23,   // b....wb
    -54,   // w....wb
    15,    // .b...wb
    40,    // bb...wb
    0,     // wb...wb
    -8,    // .w...wb
    -47,   // bw...wb
    14,    // ww...wb
    -42,   // ..b..wb
    -44,   // b.b..wb
    -35,   // w.b..wb
    -44,   // .bb..wb
    -1,    // bbb..wb
    -34,   // wbb..wb
    2,     // .wb..wb
    -9,    // bwb..wb
    -15,   // wwb..wb
    22,    // ..w..wb
    17,    // b.w..wb
    -33,   // w.w..wb
    7,     // .bw..wb
    -10,   // bbw..wb
    -25,   // wbw..wb
    -8,    // .ww..wb
    -35,   // bww..wb
    6,     // www..wb
    -43,   // ...b.wb
    0,     // b..b.wb
    32,    // w..b.wb
    2,     // .b.b.wb
    48,    // bb.b.wb
    51,    // wb.b.wb
    11,    // .w.b.wb
    -24,   // bw.b.wb
    39,    // ww.b.wb
    34,    // ..bb.wb
    40,    // b.bb.wb
    -31,   // w.bb.wb
    -13,   // .bbb.wb
    8,     // bbbb.wb
    -7,    // wbbb.wb
    -66,   // .wbb.wb
    18,    // bwbb.wb
    2,     // wwbb.wb
    6,     // ..wb.wb
    -1,    // b.wb.wb
    14,    // w.wb.wb
    -16,   // .bwb.wb
    4,     // bbwb.wb
    4,     // wbwb.wb
    20,    // .wwb.wb
    35,    // bwwb.wb
    -3,    // wwwb.wb
    40,    // ...w.wb
    -9,    // b..w.wb
    59,    // w..w.wb
    -18,   // .b.w.wb
    -27,   // bb.w.wb
    -51,   // wb.w.wb
    41,    // .w.w.wb
    36,    // bw.w.wb
    -25,   // ww.w.wb
    23,    // ..bw.wb
    26,    // b.bw.wb
    -23,   // w.bw.wb
    -44,   // .bbw.wb
    0,     // bbbw.wb
    58,    // wbbw.wb
    -19,   // .wbw.wb
    -13,   // bwbw.wb
    -22,   // wwbw.wb
    0,     // ..ww.wb
    -2,    // b.ww.wb
    -50,   // w.ww.wb
    37,    // .bww.wb
    -8,    // bbww.wb
    -6,    // wbww.wb
    36,    // .www.wb
    18,    // bwww.wb
    -13,   // wwww.wb
    -13,   // ....bwb
    7,     // b...bwb
    18,    // w...bwb
    31,    // .b..bwb
    46,    // bb..bwb
    25,    // wb..bwb
    -40,   // .w..bwb
    -9,    // bw..bwb
    23,    // ww..bwb
    -46,   // ..b.bwb
    -48,   // b.b.bwb
    -7,    // w.b.bwb
    26,    // .bb.bwb
    8,     // bbb.bwb
    -7,    // wbb.bwb
    -50,   // .wb.bwb
    22,    // bwb.bwb
    -43,   // wwb.bwb
    -8,    // ..w.bwb
    -40,   // b.w.bwb
    -27,   // w.w.bwb
    -25,   // .bw.bwb
    6,     // bbw.bwb
    0,     // wbw.bwb
    9,     // .ww.bwb
    36,    // bww.bwb
    33,    // www.bwb
    30,    // ...bbwb
    0,     // b..bbwb
    -8,    // w..bbwb
    0,     // .b.bbwb
    -25,   // bb.bbwb
    6,     // wb.bbwb
    -4,    // .w.bbwb
    18,    // bw.bbwb
    2,     // ww.bbwb
    -22,   // ..bbbwb
    -19,   // b.bbbwb
    -34,   // w.bbbwb
    8,     // .bbbbwb
    -7,    // bbbbbwb
    -1,    // wbbbbwb
    -1,    // .wbbbwb
    3,     // bwbbbwb
    30,    // wwbbbwb
    15,    // ..wbbwb
    32,    // b.wbbwb
    -24,   // w.wbbwb
    -7,    // .bwbbwb
    -5,    // bbwbbwb
    2,     // wbwbbwb
    7,     // .wwbbwb
    3,     // bwwbbwb
    -65,   // wwwbbwb
    16,    // ...wbwb
    -24,   // b..wbwb
    15,    // w..wbwb
    51,    // .b.wbwb
    -17,   // bb.wbwb
    -4,    // wb.wbwb
    -3,    // .w.wbwb
    -13,   // bw.wbwb
    -45,   // ww.wbwb
    44,    // ..bwbwb
    7,     // b.bwbwb
    -43,   // w.bwbwb
    -27,   // .bbwbwb
    9,     // bbbwbwb
    5,     // wbbwbwb
    24,    // .wbwbwb
    -79,   // bwbwbwb
    -27,   // wwbwbwb
    -3,    // ..wwbwb
    -9,    // b.wwbwb
    18,    // w.wwbwb
    -37,   // .bwwbwb
    -23,   // bbwwbwb
    -2,    // wbwwbwb
    -54,   // .wwwbwb
    13,    // bwwwbwb
    -36,   // wwwwbwb
    20,    // ....wwb
    -22,   // b...wwb
    30,    // w...wwb
    -4,    // .b..wwb
    -7,    // bb..wwb
    34,    // wb..wwb
    18,    // .w..wwb
    -35,   // bw..wwb
    -20,   // ww..wwb
    48,    // ..b.wwb
    38,    // b.b.wwb
    -30,   // w.b.wwb
    -5,    // .bb.wwb
    -4,    // bbb.wwb
    0,     // wbb.wwb
    2,     // .wb.wwb
    36,    // bwb.wwb
    1,     // wwb.wwb
    51,    // ..w.wwb
    5,     // b.w.wwb
    -62,   // w.w.wwb
    -52,   // .bw.wwb
    8,     // bbw.wwb
    7,     // wbw.wwb
    10,    // .ww.wwb
    41,    // bww.wwb
    4,     // www.wwb
    64,    // ...bwwb
    26,    // b..bwwb
    -39,   // w..bwwb
    -37,   // .b.bwwb
    23,    // bb.bwwb
    -58,   // wb.bwwb
    -45,   // .w.bwwb
    35,    // bw.bwwb
    48,    // ww.bwwb
    -14,   // ..bbwwb
    1,     // b.bbwwb
    47,    // w.bbwwb
    26,    // .bbbwwb
    2,     // bbbbwwb
    12,    // wbbbwwb
    5,     // .wbbwwb
    3,     // bwbbwwb
    -10,   // wwbbwwb
    3,     // ..wbwwb
    -15,   // b.wbwwb
    13,    // w.wbwwb
    -25,   // .bwbwwb
    -11,   // bbwbwwb
    -5,    // wbwbwwb
    7,     // .wwbwwb
    15,    // bwwbwwb
    -1,    // wwwbwwb
    33,    // ...wwwb
    -19,   // b..wwwb
    -60,   // w..wwwb
    -30,   // .b.wwwb
    3,     // bb.wwwb
    7,     // wb.wwwb
    -47,   // .w.wwwb
    18,    // bw.wwwb
    8,     // ww.wwwb
    2,     // ..bwwwb
    22,    // b.bwwwb
    8,     // w.bwwwb
    24,    // .bbwwwb
    -38,   // bbbwwwb
    -12,   // wbbwwwb
    5,     // .wbwwwb
    13,    // bwbwwwb
    -14,   // wwbwwwb
    -21,   // ..wwwwb
    -8,    // b.wwwwb
    5,     // w.wwwwb
    2,     // .bwwwwb
    -7,    // bbwwwwb
    1,     // wbwwwwb
    -14,   // .wwwwwb
    -51,   // bwwwwwb
    29,    // wwwwwwb
    0,     // ......w
    0,     // b.....w
    61,    // w.....w
    16,    // .b....w
    5,     // bb....w
    23,    // wb....w
    19,    // .w....w
    -54,   // bw....w
    -38,   // ww....w
    -29,   // ..b...w
    33,    // b.b...w
    18,    // w.b...w
    22,    // .bb...w
    -1,    // bbb...w
    22,    // wbb...w
    30,    // .wb...w
    18,    // bwb...w
    13,    // wwb...w
    -8,    // ..w...w
    19,    // b.w...w
    56,    // w.w...w
    -39,   // .bw...w
    -34,   // bbw...w
    -7,    // wbw...w
    26,    // .ww...w
    30,    // bww...w
    -18,   // www...w
    -13,   // ...b..w
    -49,   // b..b..w
    -11,   // w..b..w
    -8,    // .b.b..w
    -18,   // bb.b..w
    9,     // wb.b..w
    30,    // .w.b..w
    32,    // bw.b..w
    -32,   // ww.b..w
    58,    // ..bb..w
    62,    // b.bb..w
    29,    // w.bb..w
    -45,   // .bbb..w
    -11,   // bbbb..w
    19,    // wbbb..w
    13,    // .wbb..w
    -8,    // bwbb..w
    50,    // wwbb..w
    31,    // ..wb..w
    -28,   // b.wb..w
    -34,   // w.wb..w
    -5,    // .bwb..w
    5,     // bbwb..w
    24,    // wbwb..w
    73,    // .wwb..w
    -39,   // bwwb..w
    60,    // wwwb..w
    7,     // ...w..w
    49,    // b..w..w
    -5,    // w..w..w
    -24,   // .b.w..w
    -4,    // bb.w..w
    0,     // wb.w..w
    -9,    // .w.w..w
    59,    // bw.w..w
    28,    // ww.w..w
    -36,   // ..bw..w
    16,    // b.bw..w
    -24,   // w.bw..w
    -17,   // .bbw..w
    55,    // bbbw..w
    -26,   // wbbw..w
    -63,   // .wbw..w
    15,    // bwbw..w
    -26,   // wwbw..w
    26,    // ..ww..w
    16,    // b.ww..w
    31,    // w.ww..w
    20,    // .bww..w
    42,    // bbww..w
    0,     // wbww..w
    -38,   // .www..w
    -60,   // bwww..w
    -15,   // wwww..w
    -6,    // ....b.w
    -19,   // b...b.w
    18,    // w...b.w
    -3,    // .b..b.w
    -4,    // bb..b.w
    -17,   // wb..b.w
    -7,    // .w..b.w
    -35,   // bw..b.w
    23,    // ww..b.w
    -18,   // ..b.b.w
    16,    // b.b.b.w
    -7,    // w.b.b.w
    51,    // .bb.b.w
    -30,   // bbb.b.w
    -5,    // wbb.b.w
    -33,   // .wb.b.w
    -7,    // bwb.b.w
    -58,   // wwb.b.w
    -16,   // ..w.b.w
    0,     // b.w.b.w
    14,    // w.w.b.w
    -6,    // .bw.b.w
    53,    // bbw.b.w
    40,    // wbw.b.w
    38,    // .ww.b.w
    -30,   // bww.b.w
    -25,   // www.b.w
    18,    // ...bb.w
    -16,   // b..bb.w
    29,    // w..bb.w
    14,    // .b.bb.w
    17,    // bb.bb.w
    2,     // wb.bb.w
    12,    // .w.bb.w
    -31,   // bw.bb.w
    -27,   // ww.bb.w
    26,    // ..bbb.w
    32,    // b.bbb.w
    12,    // w.bbb.w
    68,    // .bbbb.w
    -25,   // bbbbb.w
    8,     // wbbbb.w
    11,    // .wbbb.w
    -34,   // bwbbb.w
    -38,   // wwbbb.w
    12,    // ..wbb.w
    -32,   // b.wbb.w
    -1,    // w.wbb.w
    -23,   // .bwbb.w
    32,    // bbwbb.w
    9,     // wbwbb.w
    5,     // .wwbb.w
    47,    // bwwbb.w
    58,    // wwwbb.w
    20,    // ...wb.w
    28,    // b..wb.w
    -24,   // w..wb.w
    28,    // .b.wb.w
    0,     // bb.wb.w
    1,     // wb.wb.w
    20,    // .w.wb.w
    -23,   // bw.wb.w
    -49,   // ww.wb.w
    10,    // ..bwb.w
    28,    // b.bwb.w
    19,    // w.bwb.w
    -14,   // .bbwb.w
    -44,   // bbbwb.w
    15,    // wbbwb.w
    -21,   // .wbwb.w
    -43,   // bwbwb.w
    47,    // wwbwb.w
    -31,   // ..wwb.w
    32,    // b.wwb.w
    3,     // w.wwb.w
    -32,   // .bwwb.w
    -82,   // bbwwb.w
    -32,   // wbwwb.w
    37,    // .wwwb.w
    8,     // bwwwb.w
    -57,   // wwwwb.w
    -40,   // ....w.w
    -33,   // b...w.w
    56,    // w...w.w
    -11,   // .b..w.w
    1,     // bb..w.w
    44,    // wb..w.w
    -29,   // .w..w.w
    -33,   // bw..w.w
    -5,    // ww..w.w
    31,    // ..b.w.w
    0,     // b.b.w.w
    14,    // w.b.w.w
    17,    // .bb.w.w
    33,    // bbb.w.w
    -38,   // wbb.w.w
    -20,   // .wb.w.w
    -27,   // bwb.w.w
    -22,   // wwb.w.w
    -11,   // ..w.w.w
    -16,   // b.w.w.w
    23,    // w.w.w.w
    32,    // .bw.w.w
    34,    // bbw.w.w
    48,    // wbw.w.w
    -17,   // .ww.w.w
    -62,   // bww.w.w
    -19,   // www.w.w
    -30,   // ...bw.w
    -16,   // b..bw.w
    -34,   // w..bw.w
    -18,   // .b.bw.w
    -1,    // bb.bw.w
    -26,   // wb.bw.w
    20,    // .w.bw.w
    14,    // bw.bw.w
    19,    // ww.bw.w
    12,    // ..bbw.w
    -40,   // b.bbw.w
    -1,    // w.bbw.w
    15,    // .bbbw.w
    14,    // bbbbw.w
    -22,   // wbbbw.w
    -62,   // .wbbw.w
    -24,   // bwbbw.w
    -20,   // wwbbw.w
    -48,   // ..wbw.w
    -28,   // b.wbw.w
    5,     // w.wbw.w
    -5,    // .bwbw.w
    -13,   // bbwbw.w
    -7,    // wbwbw.w
    69,    // .wwbw.w
    13,    // bwwbw.w
    -25,   // wwwbw.w
    13,    // ...ww.w
    -62,   // b..ww.w
    31,    // w..ww.w
    -33,   // .b.ww.w
    -21,   // bb.ww.w
    -40,   // wb.ww.w
    11,    // .w.ww.w
    -50,   // bw.ww.w
    -16,   // ww.ww.w
    1,     // ..bww.w
    40,    // b.bww.w
    3,     // w.bww.w
    -54,   // .bbww.w
    -34,   // bbbww.w
    -1,    // wbbww.w
    35,    // .wbww.w
    18,    // bwbww.w
    39,    // wwbww.w
    -44,   // ..www.w
    -32,   // b.www.w
    -16,   // w.www.w
    -15,   // .bwww.w
    -14,   // bbwww.w
    19,    // wbwww.w
    49,    // .wwww.w
    5,     // bwwww.w
    -34,   // wwwww.w
    1,     // .....bw
    54,    // b....bw
    23,    // w....bw
    8,     // .b...bw
    -14,   // bb...bw
    47,    // wb...bw
    -15,   // .w...bw
    0,     // bw...bw
    -40,   // ww...bw
    -22,   // ..b..bw
    33,    // b.b..bw
    -17,   // w.b..bw
    8,     // .bb..bw
    -6,    // bbb..bw
    35,    // wbb..bw
    -7,    // .wb..bw
    25,    // bwb..bw
    10,    // wwb..bw
    42,    // ..w..bw
    35,    // b.w..bw
    44,    // w.w..bw
    -2,    // .bw..bw
    15,    // bbw..bw
    9,     // wbw..bw
    44,    // .ww..bw
    34,    // bww..bw
    1,     // www..bw
    -40,   // ...b.bw
    -59,   // b..b.bw
    9,     // w..b.bw
    -41,   // .b.b.bw
    25,    // bb.b.bw
    -36,   // wb.b.bw
    18,    // .w.b.bw
    51,    // bw.b.bw
    27,    // ww.b.bw
    0,     // ..bb.bw
    50,    // b.bb.bw
    2,     // w.bb.bw
    -36,   // .bbb.bw
    13,    // bbbb.bw
    -18,   // wbbb.bw
    -37,   // .wbb.bw
    6,     // bwbb.bw
    8,     // wwbb.bw
    -23,   // ..wb.bw
    23,    // b.wb.bw
    -26,   // w.wb.bw
    19,    // .bwb.bw
    22,    // bbwb.bw
    13,    // wbwb.bw
    44,    // .wwb.bw
    -58,   // bwwb.bw
    0,     // wwwb.bw
    43,    // ...w.bw
    -32,   // b..w.bw
    0,     // w..w.bw
    -11,   // .b.w.bw
    -39,   // bb.w.bw
    24,    // wb.w.bw
    -2,    // .w.w.bw
    -51,   // bw.w.bw
    -48,   // ww.w.bw
    -6,    // ..bw.bw
    -14,   // b.bw.bw
    1,     // w.bw.bw
    -20,   // .bbw.bw
    3,     // bbbw.bw
    -35,   // wbbw.bw
    16,    // .wbw.bw
    -4,    // bwbw.bw
    -4,    // wwbw.bw
    -34,   // ..ww.bw
    31,    // b.ww.bw
    -40,   // w.ww.bw
    66,    // .bww.bw
    -2,    // bbww.bw
    -18,   // wbww.bw
    13,    // .www.bw
    7,     // bwww.bw
    -8,    // wwww.bw
    -20,   // ....bbw
    -30,   // b...bbw
    22,    // w...bbw
    -18,   // .b..bbw
    20,    // bb..bbw
    35,    // wb..bbw
    4,     // .w..bbw
    -34,   // bw..bbw
    7,     // ww..bbw
    -51,   // ..b.bbw
    62,    // b.b.bbw
    -5,    // w.b.bbw
    -10,   // .bb.bbw
    -4,    // bbb.bbw
    -41,   // wbb.bbw
    52,    // .wb.bbw
    -7,    // bwb.bbw
    -8,    // wwb.bbw
    -48,   // ..w.bbw
    30,    // b.w.bbw
    -38,   // w.w.bbw
    -2,    // .bw.bbw
    -1,    // bbw.bbw
    -36,   // wbw.bbw
    5,     // .ww.bbw
    0,     // bww.bbw
    4,     // www.bbw
    -33,   // ...bbbw
    60,    // b..bbbw
    19,    // w..bbbw
    47,    // .b.bbbw
    -8,    // bb.bbbw
    -18,   // wb.bbbw
    30,    // .w.bbbw
    -7,    // bw.bbbw
    -3,    // ww.bbbw
    21,    // ..bbbbw
    -5,    // b.bbbbw
    8,     // w.bbbbw
    14,    // .bbbbbw
    -29,   // bbbbbbw
    51,    // wbbbbbw
    -2,    // .wbbbbw
    -1,    // bwbbbbw
    7,     // wwbbbbw
    -2,    // ..wbbbw
    -8,    // b.wbbbw
    -22,   // w.wbbbw
    -5,    // .bwbbbw
    14,    // bbwbbbw
    -13,   // wbwbbbw
    -24,   // .wwbbbw
    12,    // bwwbbbw
    38,    // wwwbbbw
    -64,   // ...wbbw
    39,    // b..wbbw
    -26,   // w..wbbw
    45,    // .b.wbbw
    -48,   // bb.wbbw
    -35,   // wb.wbbw
    37,    // .w.wbbw
    58,    // bw.wbbw
    -23,   // ww.wbbw
    -3,    // ..bwbbw
    -13,   // b.bwbbw
    15,    // w.bwbbw
    -7,    // .bbwbbw
    1,     // bbbwbbw
    -15,   // wbbwbbw
    25,    // .wbwbbw
    5,     // bwbwbbw
    11,    // wwbwbbw
    14,    // ..wwbbw
    -47,   // b.wwbbw
    -1,    // w.wwbbw
    -5,    // .bwwbbw
    10,    // bbwwbbw
    -3,    // wbwwbbw
    -26,   // .wwwbbw
    -12,   // bwwwbbw
    -2,    // wwwwbbw
    13,    // ....wbw
    -18,   // b...wbw
    -7,    // w...wbw
    40,    // .b..wbw
    -23,   // bb..wbw
    9,     // wb..wbw
    -31,   // .w..wbw
    -25,   // bw..wbw
    -46,   // ww..wbw
    8,     // ..b.wbw
    27,    // b.b.wbw
    40,    // w.b.wbw
    -9,    // .bb.wbw
    -33,   // bbb.wbw
    -36,   // wbb.wbw
    25,    // .wb.wbw
    0,     // bwb.wbw
    -6,    // wwb.wbw
    46,    // ..w.wbw
    7,     // b.w.wbw
    48,    // w.w.wbw
    50,    // .bw.wbw
    43,    // bbw.wbw
    -22,   // wbw.wbw
    -26,   // .ww.wbw
    7,     // bww.wbw
    -8,    // www.wbw
    -16,   // ...bwbw
    -15,   // b..bwbw
    24,    // w..bwbw
    3,     // .b.bwbw
    45,    // bb.bwbw
    13,    // wb.bwbw
    -51,   // .w.bwbw
    4,     // bw.bwbw
    17,    // ww.bwbw
    3,     // ..bbwbw
    -18,   // b.bbwbw
    9,     // w.bbwbw
    54,    // .bbbwbw
    36,    // bbbbwbw
    -13,   // wbbbwbw
    37,    // .wbbwbw
    2,     // bwbbwbw
    23,    // wwbbwbw
    -44,   // ..wbwbw
    43,    // b.wbwbw
    -7,    // w.wbwbw
    -24,   // .bwbwbw
    27,    // bbwbwbw
    79,    // wbwbwbw
    27,    // .wwbwbw
    -5,    // bwwbwbw
    -9,    // wwwbwbw
    -30,   // ...wwbw
    8,     // b..wwbw
    0,     // w..wwbw
    4,     // .b.wwbw
    -2,    // bb.wwbw
    -18,   // wb.wwbw
    0,     // .w.wwbw
    -6,    // bw.wwbw
    25,    // ww.wwbw
    -15,   // ..bwwbw
    24,    // b.bwwbw
    -32,   // w.bwwbw
    -7,    // .bbwwbw
    65,    // bbbwwbw
    -3,    // wbbwwbw
    7,     // .wbwwbw
    -2,    // bwbwwbw
    5,     // wwbwwbw
    22,    // ..wwwbw
    34,    // b.wwwbw
    19,    // w.wwwbw
    1,     // .bwwwbw
    -30,   // bbwwwbw
    -3,    // wbwwwbw
    -8,    // .wwwwbw
    1,     // bwwwwbw
    7,     // wwwwwbw
    -47,   // .....ww
    -5,    // b....ww
    -38,   // w....ww
    -49,   // .b...ww
    0,     // bb...ww
    -40,   // wb...ww
    15,    // .w...ww
    14,    // bw...ww
    22,    // ww...ww
    24,    // ..b..ww
    -1,    // b.b..ww
    23,    // w.b..ww
    -10,   // .bb..ww
    21,    // bbb..ww
    7,     // wbb..ww
    9,     // .wb..ww
    23,    // bwb..ww
    -21,   // wwb..ww
    -7,    // ..w..ww
    4,     // b.w..ww
    -5,    // w.w..ww
    20,    // .bw..ww
    -61,   // bbw..ww
    -46,   // wbw..ww
    -14,   // .ww..ww
    -20,   // bww..ww
    22,    // www..ww
    -37,   // ...b.ww
    4,     // b..b.ww
    -32,   // w..b.ww
    -5,    // .b.b.ww
    62,    // bb.b.ww
    27,    // wb.b.ww
    13,    // .w.b.ww
    39,    // bw.b.ww
    19,    // ww.b.ww
    -39,   // ..bb.ww
    21,    // b.bb.ww
    -27,   // w.bb.ww
    3,     // .bbb.ww
    -54,   // bbbb.ww
    -3,    // wbbb.ww
    -30,   // .wbb.ww
    2,     // bwbb.ww
    -16,   // wwbb.ww
    -12,   // ..wb.ww
    0,     // b.wb.ww
    19,    // w.wb.ww
    42,    // .bwb.ww
    9,     // bbwb.ww
    17,    // wbwb.ww
    17,    // .wwb.ww
    48,    // bwwb.ww
    11,    // wwwb.ww
    -104,  // ...w.ww
    18,    // b..w.ww
    28,    // w..w.ww
    -20,   // .b.w.ww
    -62,   // bb.w.ww
    -48,   // wb.w.ww
    52,    // .w.w.ww
    -25,   // bw.w.ww
    -16,   // ww.w.ww
    21,    // ..bw.ww
    1,     // b.bw.ww
    -49,   // w.bw.ww
    -36,   // .bbw.ww
    -25,   // bbbw.ww
    -23,   // wbbw.ww
    6,     // .wbw.ww
    -45,   // bwbw.ww
    4,     // wwbw.ww
    -4,    // ..ww.ww
    -17,   // b.ww.ww
    -16,   // w.ww.ww
    22,    // .bww.ww
    -6,    // bbww.ww
    25,    // wbww.ww
    -43,   // .www.ww
    8,     // bwww.ww
    23,    // wwww.ww
    31,    // ....bww
    34,    // b...bww
    13,    // w...bww
    -24,   // .b..bww
    61,    // bb..bww
    10,    // wb..bww
    3,     // .w..bww
    -15,   // bw..bww
    -21,   // ww..bww
    -30,   // ..b.bww
    -34,   // b.b.bww
    -58,   // w.b.bww
    -30,   // .bb.bww
    -2,    // bbb.bww
    -8,    // wbb.bww
    -5,    // .wb.bww
    -43,   // bwb.bww
    32,    // wwb.bww
    -2,    // ..w.bww
    -53,   // b.w.bww
    -22,   // w.w.bww
    -20,   // .bw.bww
    0,     // bbw.bww
    -6,    // wbw.bww
    -17,   // .ww.bww
    1,     // bww.bww
    -19,   // www.bww
    -1,    // ...bbww
    -42,   // b..bbww
    50,    // w..bbww
    -10,   // .b.bbww
    6,     // bb.bbww
    8,     // wb.bbww
    -6,    // .w.bbww
    2,     // bw.bbww
    -16,   // ww.bbww
    -1,    // ..bbbww
    14,    // b.bbbww
    -38,   // w.bbbww
    5,     // .bbbbww
    32,    // bbbbbww
    7,     // wbbbbww
    24,    // .wbbbww
    30,    // bwbbbww
    17,    // wwbbbww
    -11,   // ..wbbww
    82,    // b.wbbww
    -20,   // w.wbbww
    11,    // .bwbbww
    31,    // bbwbbww
    23,    // wbwbbww
    -18,   // .wwbbww
    -10,   // bwwbbww
    -54,   // wwwbbww
    -19,   // ...wbww
    -5,    // b..wbww
    -26,   // w..wbww
    6,     // .b.wbww
    -9,    // bb.wbww
    -4,    // wb.wbww
    25,    // .w.wbww
    -22,   // bw.wbww
    4,     // ww.wbww
    60,    // ..bwbww
    13,    // b.bwbww
    47,    // w.bwbww
    13,    // .bbwbww
    7,     // bbbwbww
    11,    // wbbwbww
    28,    // .wbwbww
    -27,   // bwbwbww
    -15,   // wwbwbww
    -72,   // ..wwbww
    -32,   // b.wwbww
    39,    // w.wwbww
    30,    // .bwwbww
    -31,   // bbwwbww
    5,     // wbwwbww
    -10,   // .wwwbww
    -14,   // bwwwbww
    -37,   // wwwwbww
    -93,   // ....www
    1,     // b...www
    -18,   // w...www
    1,     // .b..www
    -21,   // bb..www
    1,     // wb..www
    -7,    // .w..www
    6,     // bw..www
    22,    // ww..www
    -50,   // ..b.www
    -33,   // b.b.www
    -25,   // w.b.www
    -3,    // .bb.www
    0,     // bbb.www
    4,     // wbb.www
    47,    // .wb.www
    33,    // bwb.www
    -19,   // wwb.www
    -37,   // ..w.www
    30,    // b.w.www
    -19,   // w.w.www
    15,    // .bw.www
    2,     // bbw.www
    -8,    // wbw.www
    -3,    // .ww.www
    4,     // bww.www
    -44,   // www.www
    2,     // ...bwww
    -55,   // b..bwww
    60,    // w..bwww
    7,     // .b.bwww
    25,    // bb.bwww
    0,     // wb.bwww
    -21,   // .w.bwww
    -3,    // bw.bwww
    11,    // ww.bwww
    30,    // ..bbwww
    34,    // b.bbwww
    58,    // w.bbwww
    33,    // .bbbwww
    -5,    // bbbbwww
    38,    // wbbbwww
    -10,   // .wbbwww
    -65,   // bwbbwww
    -54,   // wwbbwww
    26,    // ..wbwww
    44,    // b.wbwww
    -25,   // w.wbwww
    -42,   // .bwbwww
    -7,    // bbwbwww
    -9,    // wbwbwww
    80,    // .wwbwww
    -1,    // bwwbwww
    -39,   // wwwbwww
    -141,  // ...wwww
    11,    // b..wwww
    -15,   // w..wwww
    -14,   // .b.wwww
    54,    // bb.wwww
    -8,    // wb.wwww
    -48,   // .w.wwww
    -13,   // bw.wwww
    23,    // ww.wwww
    -29,   // ..bwwww
    -14,   // b.bwwww
    -57,   // w.bwwww
    -73,   // .bbwwww
    5,     // bbbwwww
    -2,    // wbbwwww
    -1,    // .wbwwww
    -36,   // bwbwwww
    -37,   // wwbwwww
    10,    // ..wwwww
    25,    // b.wwwww
    -34,   // w.wwwww
    -2,    // .bwwwww
    -32,   // bbwwwww
    7,     // wbwwwww
    10,    // .wwwwww
    29,    // bwwwwww
    51,    // wwwwwww
    37,    // ccc
    35,    // cc
    9,     // c
    -5,    // ttt
    16,    // tt
    58,    // t
    32,    // ct
    31,    // cct
    8,     // ctt
].into_boxed_slice()
