vec![
    0,     // .......
    2,     // b......
    -2,    // w......
    8,     // .b.....
    22,    // bb.....
    4,     // wb.....
    -8,    // .w.....
    -4,    // bw.....
    -22,   // ww.....
    2,     // ..b....
    19,    // b.b....
    -4,    // w.b....
    12,    // .bb....
    88,    // bbb....
    -25,   // wbb....
    -18,   // .wb....
    -14,   // bwb....
    -18,   // wwb....
    -2,    // ..w....
    4,     // b.w....
    -19,   // w.w....
    18,    // .bw....
    18,    // bbw....
    14,    // wbw....
    -12,   // .ww....
    25,    // bww....
    -88,   // www....
    -2,    // ...b...
    8,     // b..b...
    16,    // w..b...
    0,     // .b.b...
    -2,    // bb.b...
    -29,   // wb.b...
    -5,    // .w.b...
    -16,   // bw.b...
    -34,   // ww.b...
    -15,   // ..bb...
    12,    // b.bb...
    -23,   // w.bb...
    36,    // .bbb...
    135,   // bbbb...
    -46,   // wbbb...
    -20,   // .wbb...
    1,     // bwbb...
    17,    // wwbb...
    4,     // ..wb...
    23,    // b.wb...
    10,    // w.wb...
    21,    // .bwb...
    -25,   // bbwb...
    -1,    // wbwb...
    24,    // .wwb...
    0,     // bwwb...
    10,    // wwwb...
    2,     // ...w...
    -16,   // b..w...
    -8,    // w..w...
    5,     // .b.w...
    34,    // bb.w...
    16,    // wb.w...
    0,     // .w.w...
    29,    // bw.w...
    2,     // ww.w...
    -4,    // ..bw...
    -10,   // b.bw...
    -23,   // w.bw...
    -24,   // .bbw...
    -10,   // bbbw...
    0,     // wbbw...
    -21,   // .wbw...
    1,     // bwbw...
    25,    // wwbw...
    15,    // ..ww...
    23,    // b.ww...
    -12,   // w.ww...
    20,    // .bww...
    -17,   // bbww...
    -1,    // wbww...
    -36,   // .www...
    46,    // bwww...
    -135,  // wwww...
    2,     // ....b..
    -5,    // b...b..
    5,     // w...b..
    -6,    // .b..b..
    -19,   // bb..b..
    -13,   // wb..b..
    -7,    // .w..b..
    -23,   // bw..b..
    -24,   // ww..b..
    3,     // ..b.b..
    -22,   // b.b.b..
    0,     // w.b.b..
    9,     // .bb.b..
    25,    // bbb.b..
    3,     // wbb.b..
    19,    // .wb.b..
    -10,   // bwb.b..
    12,    // wwb.b..
    0,     // ..w.b..
    -12,   // b.w.b..
    -2,    // w.w.b..
    12,    // .bw.b..
    -7,    // bbw.b..
    8,     // wbw.b..
    19,    // .ww.b..
    -5,    // bww.b..
    -21,   // www.b..
    -15,   // ...bb..
    -5,    // b..bb..
    0,     // w..bb..
    60,    // .b.bb..
    16,    // bb.bb..
    -20,   // wb.bb..
    4,     // .w.bb..
    1,     // bw.bb..
    19,    // ww.bb..
    -4,    // ..bbb..
    31,    // b.bbb..
    -33,   // w.bbb..
    107,   // .bbbb..
    26,    // bbbbb..
    39,    // wbbbb..
    -49,   // .wbbb..
    -22,   // bwbbb..
    2,     // wwbbb..
    -13,   // ..wbb..
    -20,   // b.wbb..
    6,     // w.wbb..
    -8,    // .bwbb..
    -31,   // bbwbb..
    -24,   // wbwbb..
    -32,   // .wwbb..
    -6,    // bwwbb..
    -28,   // wwwbb..
    -4,    // ...wb..
    -21,   // b..wb..
    -12,   // w..wb..
    -20,   // .b.wb..
    -5,    // bb.wb..
    37,    // wb.wb..
    -5,    // .w.wb..
    -8,    // bw.wb..
    0,     // ww.wb..
    5,     // ..bwb..
    -3,    // b.bwb..
    -18,   // w.bwb..
    -3,    // .bbwb..
    -10,   // bbbwb..
    28,    // wbbwb..
    -31,   // .wbwb..
    8,     // bwbwb..
    -5,    // wwbwb..
    13,    // ..wwb..
    -5,    // b.wwb..
    9,     // w.wwb..
    12,    // .bwwb..
    5,     // bbwwb..
    47,    // wbwwb..
    25,    // .wwwb..
    16,    // bwwwb..
    -30,   // wwwwb..
    -2,    // ....w..
    -5,    // b...w..
    5,     // w...w..
    7,     // .b..w..
    24,    // bb..w..
    23,    // wb..w..
    6,     // .w..w..
    13,    // bw..w..
    19,    // ww..w..
    0,     // ..b.w..
    2,     // b.b.w..
    12,    // w.b.w..
    -19,   // .bb.w..
    21,    // bbb.w..
    5,     // wbb.w..
    -12,   // .wb.w..
    -8,    // bwb.w..
    7,     // wwb.w..
    -3,    // ..w.w..
    0,     // b.w.w..
    22,    // w.w.w..
    -19,   // .bw.w..
    -12,   // bbw.w..
    10,    // wbw.w..
    -9,    // .ww.w..
    -3,    // bww.w..
    -25,   // www.w..
    4,     // ...bw..
    12,    // b..bw..
    21,    // w..bw..
    5,     // .b.bw..
    0,     // bb.bw..
    8,     // wb.bw..
    20,    // .w.bw..
    -37,   // bw.bw..
    5,     // ww.bw..
    -13,   // ..bbw..
    -9,    // b.bbw..
    5,     // w.bbw..
    -25,   // .bbbw..
    30,    // bbbbw..
    -16,   // wbbbw..
    -12,   // .wbbw..
    -47,   // bwbbw..
    -5,    // wwbbw..
    -5,    // ..wbw..
    18,    // b.wbw..
    3,     // w.wbw..
    31,    // .bwbw..
    5,     // bbwbw..
    -8,    // wbwbw..
    3,     // .wwbw..
    -28,   // bwwbw..
    10,    // wwwbw..
    15,    // ...ww..
    0,     // b..ww..
    5,     // w..ww..
    -4,    // .b.ww..
    -19,   // bb.ww..
    -1,    // wb.ww..
    -60,   // .w.ww..
    20,    // bw.ww..
    -16,   // ww.ww..
    13,    // ..bww..
    -6,    // b.bww..
    20,    // w.bww..
    32,    // .bbww..
    28,    // bbbww..
    6,     // wbbww..
    8,     // .wbww..
    24,    // bwbww..
    31,    // wwbww..
    4,     // ..www..
    33,    // b.www..
    -31,   // w.www..
    49,    // .bwww..
    -2,    // bbwww..
    22,    // wbwww..
    -107,  // .wwww..
    -39,   // bwwww..
    -26,   // wwwww..
    8,     // .....b.
    -15,   // b....b.
    -35,   // w....b.
    15,    // .b...b.
    37,    // bb...b.
    15,    // wb...b.
    0,     // .w...b.
    17,    // bw...b.
    19,    // ww...b.
    -6,    // ..b..b.
    11,    // b.b..b.
    4,     // w.b..b.
    9,     // .bb..b.
    -14,   // bbb..b.
    53,    // wbb..b.
    -15,   // .wb..b.
    3,     // bwb..b.
    32,    // wwb..b.
    7,     // ..w..b.
    -43,   // b.w..b.
    9,     // w.w..b.
    13,    // .bw..b.
    -27,   // bbw..b.
    -34,   // wbw..b.
    41,    // .ww..b.
    -43,   // bww..b.
    -41,   // www..b.
    0,     // ...b.b.
    -14,   // b..b.b.
    43,    // w..b.b.
    21,    // .b.b.b.
    3,     // bb.b.b.
    -6,    // wb.b.b.
    -4,    // .w.b.b.
    -55,   // bw.b.b.
    -19,   // ww.b.b.
    60,    // ..bb.b.
    -42,   // b.bb.b.
    16,    // w.bb.b.
    10,    // .bbb.b.
    26,    // bbbb.b.
    50,    // wbbb.b.
    3,     // .wbb.b.
    19,    // bwbb.b.
    -44,   // wwbb.b.
    5,     // ..wb.b.
    -3,    // b.wb.b.
    5,     // w.wb.b.
    14,    // .bwb.b.
    6,     // bbwb.b.
    3,     // wbwb.b.
    12,    // .wwb.b.
    -6,    // bwwb.b.
    -30,   // wwwb.b.
    5,     // ...w.b.
    16,    // b..w.b.
    -9,    // w..w.b.
    -33,   // .b.w.b.
    18,    // bb.w.b.
    1,     // wb.w.b.
    4,     // .w.w.b.
    6,     // bw.w.b.
    -15,   // ww.w.b.
    -20,   // ..bw.b.
    3,     // b.bw.b.
    -5,    // w.bw.b.
    -15,   // .bbw.b.
    -5,    // bbbw.b.
    -5,    // wbbw.b.
    -22,   // .wbw.b.
    -8,    // bwbw.b.
    28,    // wwbw.b.
    -4,    // ..ww.b.
    6,     // b.ww.b.
    -6,    // w.ww.b.
    -9,    // .bww.b.
    -36,   // bbww.b.
    36,    // wbww.b.
    -26,   // .www.b.
    -3,    // bwww.b.
    -22,   // wwww.b.
    12,    // ....bb.
    -18,   // b...bb.
    7,     // w...bb.
    9,     // .b..bb.
    11,    // bb..bb.
    22,    // wb..bb.
    -41,   // .w..bb.
    13,    // bw..bb.
    -7,    // ww..bb.
    9,     // ..b.bb.
    11,    // b.b.bb.
    0,     // w.b.bb.
    9,     // .bb.bb.
    -15,   // bbb.bb.
    31,    // wbb.bb.
    14,    // .wb.bb.
    6,     // bwb.bb.
    -6,    // wwb.bb.
    -19,   // ..w.bb.
    5,     // b.w.bb.
    -42,   // w.w.bb.
    4,     // .bw.bb.
    -2,    // bbw.bb.
    -7,    // wbw.bb.
    0,     // .ww.bb.
    -3,    // bww.bb.
    -47,   // www.bb.
    36,    // ...bbb.
    -15,   // b..bbb.
    14,    // w..bbb.
    10,    // .b.bbb.
    11,    // bb.bbb.
    29,    // wb.bbb.
    26,    // .w.bbb.
    33,    // bw.bbb.
    -12,   // ww.bbb.
    107,   // ..bbbb.
    29,    // b.bbbb.
    0,     // w.bbbb.
    13,    // .bbbbb.
    12,    // bbbbbb.
    9,     // wbbbbb.
    51,    // .wbbbb.
    14,    // bwbbbb.
    20,    // wwbbbb.
    -25,   // ..wbbb.
    5,     // b.wbbb.
    -11,   // w.wbbb.
    -13,   // .bwbbb.
    -25,   // bbwbbb.
    -28,   // wbwbbb.
    0,     // .wwbbb.
    -31,   // bwwbbb.
    10,    // wwwbbb.
    -24,   // ...wbb.
    18,    // b..wbb.
    16,    // w..wbb.
    -15,   // .b.wbb.
    28,    // bb.wbb.
    -11,   // wb.wbb.
    -12,   // .w.wbb.
    -34,   // bw.wbb.
    -10,   // ww.wbb.
    -3,    // ..bwbb.
    7,     // b.bwbb.
    -38,   // w.bwbb.
    13,    // .bbwbb.
    -30,   // bbbwbb.
    -14,   // wbbwbb.
    -3,    // .wbwbb.
    -10,   // bwbwbb.
    31,    // wwbwbb.
    32,    // ..wwbb.
    -13,   // b.wwbb.
    2,     // w.wwbb.
    -30,   // .bwwbb.
    -16,   // bbwwbb.
    23,    // wbwwbb.
    0,     // .wwwbb.
    -9,    // bwwwbb.
    8,     // wwwwbb.
    18,    // ....wb.
    27,    // b...wb.
    -19,   // w...wb.
    13,    // .b..wb.
    -18,   // bb..wb.
    -30,   // wb..wb.
    15,    // .w..wb.
    -21,   // bw..wb.
    -3,    // ww..wb.
    12,    // ..b.wb.
    -30,   // b.b.wb.
    -11,   // w.b.wb.
    4,     // .bb.wb.
    -4,    // bbb.wb.
    -13,   // wbb.wb.
    0,     // .wb.wb.
    -14,   // bwb.wb.
    16,    // wwb.wb.
    -19,   // ..w.wb.
    44,    // b.w.wb.
    38,    // w.w.wb.
    6,     // .bw.wb.
    15,    // bbw.wb.
    -26,   // wbw.wb.
    -14,   // .ww.wb.
    18,    // bww.wb.
    -34,   // www.wb.
    21,    // ...bwb.
    -5,    // b..bwb.
    -10,   // w..bwb.
    14,    // .b.bwb.
    -11,   // bb.bwb.
    30,    // wb.bwb.
    22,    // .w.bwb.
    12,    // bw.bwb.
    -19,   // ww.bwb.
    -8,    // ..bbwb.
    -36,   // b.bbwb.
    20,    // w.bbwb.
    -13,   // .bbbwb.
    -1,    // bbbbwb.
    8,     // wbbbwb.
    -22,   // .wbbwb.
    -3,    // bwbbwb.
    33,    // wwbbwb.
    31,    // ..wbwb.
    7,     // b.wbwb.
    -7,    // w.wbwb.
    -21,   // .bwbwb.
    38,    // bbwbwb.
    21,    // wbwbwb.
    3,     // .wwbwb.
    40,    // bwwbwb.
    -43,   // wwwbwb.
    20,    // ...wwb.
    -8,    // b..wwb.
    21,    // w..wwb.
    -9,    // .b.wwb.
    -22,   // bb.wwb.
    -16,   // wb.wwb.
    -3,    // .w.wwb.
    -12,   // bw.wwb.
    -3,    // ww.wwb.
    12,    // ..bwwb.
    17,    // b.bwwb.
    -23,   // w.bwwb.
    -30,   // .bbwwb.
    -12,   // bbbwwb.
    -20,   // wbbwwb.
    22,    // .wbwwb.
    -5,    // bwbwwb.
    22,    // wwbwwb.
    49,    // ..wwwb.
    44,    // b.wwwb.
    -20,   // w.wwwb.
    -27,   // .bwwwb.
    5,     // bbwwwb.
    3,     // wbwwwb.
    -51,   // .wwwwb.
    67,    // bwwwwb.
    -3,    // wwwwwb.
    -8,    // .....w.
    35,    // b....w.
    15,    // w....w.
    0,     // .b...w.
    -19,   // bb...w.
    -17,   // wb...w.
    -15,   // .w...w.
    -15,   // bw...w.
    -37,   // ww...w.
    -7,    // ..b..w.
    -9,    // b.b..w.
    43,    // w.b..w.
    -41,   // .bb..w.
    41,    // bbb..w.
    43,    // wbb..w.
    -13,   // .wb..w.
    34,    // bwb..w.
    27,    // wwb..w.
    6,     // ..w..w.
    -4,    // b.w..w.
    -11,   // w.w..w.
    15,    // .bw..w.
    -32,   // bbw..w.
    -3,    // wbw..w.
    -9,    // .ww..w.
    -53,   // bww..w.
    14,    // www..w.
    -5,    // ...b.w.
    9,     // b..b.w.
    -16,   // w..b.w.
    -4,    // .b.b.w.
    15,    // bb.b.w.
    -6,    // wb.b.w.
    33,    // .w.b.w.
    -1,    // bw.b.w.
    -18,   // ww.b.w.
    4,     // ..bb.w.
    6,     // b.bb.w.
    -6,    // w.bb.w.
    26,    // .bbb.w.
    22,    // bbbb.w.
    3,     // wbbb.w.
    9,     // .wbb.w.
    -36,   // bwbb.w.
    36,    // wwbb.w.
    20,    // ..wb.w.
    5,     // b.wb.w.
    -3,    // w.wb.w.
    22,    // .bwb.w.
    -28,   // bbwb.w.
    8,     // wbwb.w.
    15,    // .wwb.w.
    5,     // bwwb.w.
    5,     // wwwb.w.
    0,     // ...w.w.
    -43,   // b..w.w.
    14,    // w..w.w.
    4,     // .b.w.w.
    19,    // bb.w.w.
    55,    // wb.w.w.
    -21,   // .w.w.w.
    6,     // bw.w.w.
    -3,    // ww.w.w.
    -5,    // ..bw.w.
    -5,    // b.bw.w.
    3,     // w.bw.w.
    -12,   // .bbw.w.
    30,    // bbbw.w.
    6,     // wbbw.w.
    -14,   // .wbw.w.
    -3,    // bwbw.w.
    -6,    // wwbw.w.
    -60,   // ..ww.w.
    -16,   // b.ww.w.
    42,    // w.ww.w.
    -3,    // .bww.w.
    44,    // bbww.w.
    -19,   // wbww.w.
    -10,   // .www.w.
    -50,   // bwww.w.
    -26,   // wwww.w.
    -18,   // ....bw.
    19,    // b...bw.
    -27,   // w...bw.
    -15,   // .b..bw.
    3,     // bb..bw.
    21,    // wb..bw.
    -13,   // .w..bw.
    30,    // bw..bw.
    18,    // ww..bw.
    19,    // ..b.bw.
    -38,   // b.b.bw.
    -44,   // w.b.bw.
    14,    // .bb.bw.
    34,    // bbb.bw.
    -18,   // wbb.bw.
    -6,    // .wb.bw.
    26,    // bwb.bw.
    -15,   // wwb.bw.
    -12,   // ..w.bw.
    11,    // b.w.bw.
    30,    // w.w.bw.
    0,     // .bw.bw.
    -16,   // bbw.bw.
    14,    // wbw.bw.
    -4,    // .ww.bw.
    13,    // bww.bw.
    4,     // www.bw.
    -20,   // ...bbw.
    -21,   // b..bbw.
    8,     // w..bbw.
    3,     // .b.bbw.
    3,     // bb.bbw.
    12,    // wb.bbw.
    9,     // .w.bbw.
    16,    // bw.bbw.
    22,    // ww.bbw.
    -49,   // ..bbbw.
    20,    // b.bbbw.
    -44,   // w.bbbw.
    51,    // .bbbbw.
    3,     // bbbbbw.
    -67,   // wbbbbw.
    27,    // .wbbbw.
    -3,    // bwbbbw.
    -5,    // wwbbbw.
    -12,   // ..wbbw.
    23,    // b.wbbw.
    -17,   // w.wbbw.
    -22,   // .bwbbw.
    -22,   // bbwbbw.
    5,     // wbwbbw.
    30,    // .wwbbw.
    20,    // bwwbbw.
    12,    // wwwbbw.
    -21,   // ...wbw.
    10,    // b..wbw.
    5,     // w..wbw.
    -22,   // .b.wbw.
    19,    // bb.wbw.
    -12,   // wb.wbw.
    -14,   // .w.wbw.
    -30,   // bw.wbw.
    11,    // ww.wbw.
    -31,   // ..bwbw.
    7,     // b.bwbw.
    -7,    // w.bwbw.
    -3,    // .bbwbw.
    43,    // bbbwbw.
    -40,   // wbbwbw.
    21,    // .wbwbw.
    -21,   // bwbwbw.
    -38,   // wwbwbw.
    8,     // ..wwbw.
    -20,   // b.wwbw.
    36,    // w.wwbw.
    22,    // .bwwbw.
    -33,   // bbwwbw.
    3,     // wbwwbw.
    13,    // .wwwbw.
    -8,    // bwwwbw.
    1,     // wwwwbw.
    -12,   // ....ww.
    -7,    // b...ww.
    18,    // w...ww.
    41,    // .b..ww.
    7,     // bb..ww.
    -13,   // wb..ww.
    -9,    // .w..ww.
    -22,   // bw..ww.
    -11,   // ww..ww.
    19,    // ..b.ww.
    42,    // b.b.ww.
    -5,    // w.b.ww.
    0,     // .bb.ww.
    47,    // bbb.ww.
    3,     // wbb.ww.
    -4,    // .wb.ww.
    7,     // bwb.ww.
    2,     // wwb.ww.
    -9,    // ..w.ww.
    0,     // b.w.ww.
    -11,   // w.w.ww.
    -14,   // .bw.ww.
    6,     // bbw.ww.
    -6,    // wbw.ww.
    -9,    // .ww.ww.
    -31,   // bww.ww.
    15,    // www.ww.
    24,    // ...bww.
    -16,   // b..bww.
    -18,   // w..bww.
    12,    // .b.bww.
    10,    // bb.bww.
    34,    // wb.bww.
    15,    // .w.bww.
    11,    // bw.bww.
    -28,   // ww.bww.
    -32,   // ..bbww.
    -2,    // b.bbww.
    13,    // w.bbww.
    0,     // .bbbww.
    -8,    // bbbbww.
    9,     // wbbbww.
    30,    // .wbbww.
    -23,   // bwbbww.
    16,    // wwbbww.
    3,     // ..wbww.
    38,    // b.wbww.
    -7,    // w.wbww.
    3,     // .bwbww.
    -31,   // bbwbww.
    10,    // wbwbww.
    -13,   // .wwbww.
    14,    // bwwbww.
    30,    // wwwbww.
    -36,   // ...www.
    -14,   // b..www.
    15,    // w..www.
    -26,   // .b.www.
    12,    // bb.www.
    -33,   // wb.www.
    -10,   // .w.www.
    -29,   // bw.www.
    -11,   // ww.www.
    25,    // ..bwww.
    11,    // b.bwww.
    -5,    // w.bwww.
    0,     // .bbwww.
    -10,   // bbbwww.
    31,    // wbbwww.
    13,    // .wbwww.
    28,    // bwbwww.
    25,    // wwbwww.
    -107,  // ..wwww.
    0,     // b.wwww.
    -29,   // w.wwww.
    -51,   // .bwwww.
    -20,   // bbwwww.
    -14,   // wbwwww.
    -13,   // .wwwww.
    -9,    // bwwwww.
    -12,   // wwwwww.
    2,     // ......b
    -3,    // b.....b
    0,     // w.....b
    -15,   // .b....b
    15,    // bb....b
    11,    // wb....b
    35,    // .w....b
    -6,    // bw....b
    6,     // ww....b
    -5,    // ..b...b
    -13,   // b.b...b
    -3,    // w.b...b
    -18,   // .bb...b
    -40,   // bbb...b
    -29,   // wbb...b
    19,    // .wb...b
    -44,   // bwb...b
    -21,   // wwb...b
    -5,    // ..w...b
    -30,   // b.w...b
    4,     // w.w...b
    27,    // .bw...b
    -22,   // bbw...b
    -13,   // wbw...b
    -7,    // .ww...b
    -6,    // bww...b
    20,    // www...b
    8,     // ...b..b
    4,     // b..b..b
    3,     // w..b..b
    -14,   // .b.b..b
    6,     // bb.b..b
    24,    // wb.b..b
    9,     // .w.b..b
    -17,   // bw.b..b
    -5,    // ww.b..b
    -5,    // ..bb..b
    -1,    // b.bb..b
    -34,   // w.bb..b
    -15,   // .bbb..b
    14,    // bbbb..b
    14,    // wbbb..b
    -21,   // .wbb..b
    -22,   // bwbb..b
    2,     // wwbb..b
    12,    // ..wb..b
    33,    // b.wb..b
    -17,   // w.wb..b
    -5,    // .bwb..b
    31,    // bbwb..b
    -9,    // wbwb..b
    -16,   // .wwb..b
    5,     // bwwb..b
    -10,   // wwwb..b
    -16,   // ...w..b
    -12,   // b..w..b
    -3,    // w..w..b
    16,    // .b.w..b
    1,     // bb.w..b
    -26,   // wb.w..b
    -43,   // .w.w..b
    -22,   // bw.w..b
    -32,   // ww.w..b
    -21,   // ..bw..b
    4,     // b.bw..b
    -20,   // w.bw..b
    18,    // .bbw..b
    1,     // bbbw..b
    -28,   // wbbw..b
    10,    // .wbw..b
    -39,   // bwbw..b
    11,    // wwbw..b
    0,     // ..ww..b
    34,    // b.ww..b
    -36,   // w.ww..b
    -8,    // .bww..b
    7,     // bbww..b
    31,    // wbww..b
    -14,   // .www..b
    -4,    // bwww..b
    -5,    // wwww..b
    19,    // ....b.b
    -13,   // b...b.b
    -4,    // w...b.b
    11,    // .b..b.b
    -20,   // bb..b.b
    -14,   // wb..b.b
    -9,    // .w..b.b
    50,    // bw..b.b
    -41,   // ww..b.b
    -22,   // ..b.b.b
    -13,   // b.b.b.b
    8,     // w.b.b.b
    11,    // .bb.b.b
    -19,   // bbb.b.b
    -8,    // wbb.b.b
    -38,   // .wb.b.b
    15,    // bwb.b.b
    40,    // wwb.b.b
    2,     // ..w.b.b
    -19,   // b.w.b.b
    0,     // w.w.b.b
    -30,   // .bw.b.b
    9,     // bbw.b.b
    -12,   // wbw.b.b
    42,    // .ww.b.b
    0,     // bww.b.b
    -18,   // www.b.b
    12,    // ...bb.b
    -1,    // b..bb.b
    36,    // w..bb.b
    -42,   // .b.bb.b
    18,    // bb.bb.b
    -19,   // wb.bb.b
    6,     // .w.bb.b
    34,    // bw.bb.b
    -4,    // ww.bb.b
    31,    // ..bbb.b
    35,    // b.bbb.b
    35,    // w.bbb.b
    29,    // .bbbb.b
    8,     // bbbbb.b
    -25,   // wbbbb.b
    20,    // .wbbb.b
    12,    // bwbbb.b
    -15,   // wwbbb.b
    -9,    // ..wbb.b
    23,    // b.wbb.b
    14,    // w.wbb.b
    -36,   // .bwbb.b
    26,    // bbwbb.b
    7,     // wbwbb.b
    -2,    // .wwbb.b
    1,     // bwwbb.b
    -24,   // wwwbb.b
    -10,   // ...wb.b
    4,     // b..wb.b
    17,    // w..wb.b
    3,     // .b.wb.b
    8,     // bb.wb.b
    -15,   // wb.wb.b
    -5,    // .w.wb.b
    29,    // bw.wb.b
    50,    // ww.wb.b
    -3,    // ..bwb.b
    20,    // b.bwb.b
    -35,   // w.bwb.b
    7,     // .bbwb.b
    -12,   // bbbwb.b
    -4,    // wbbwb.b
    7,     // .wbwb.b
    -18,   // bwbwb.b
    -7,    // wwbwb.b
    -6,    // ..wwb.b
    18,    // b.wwb.b
    -14,   // w.wwb.b
    17,    // .bwwb.b
    -32,   // bbwwb.b
    -10,   // wbwwb.b
    11,    // .wwwb.b
    7,     // bwwwb.b
    25,    // wwwwb.b
    4,     // ....w.b
    -30,   // b...w.b
    3,     // w...w.b
    -43,   // .b..w.b
    23,    // bb..w.b
    25,    // wb..w.b
    -4,    // .w..w.b
    12,    // bw..w.b
    -1,    // ww..w.b
    -12,   // ..b.w.b
    -19,   // b.b.w.b
    0,     // w.b.w.b
    5,     // .bb.w.b
    23,    // bbb.w.b
    -1,    // wbb.w.b
    11,    // .wb.w.b
    18,    // bwb.w.b
    -21,   // wwb.w.b
    0,     // ..w.w.b
    -47,   // b.w.w.b
    -8,    // w.w.w.b
    44,    // .bw.w.b
    10,    // bbw.w.b
    -7,    // wbw.w.b
    0,     // .ww.w.b
    -8,    // bww.w.b
    -5,    // www.w.b
    23,    // ...bw.b
    33,    // b..bw.b
    20,    // w..bw.b
    -3,    // .b.bw.b
    -3,    // bb.bw.b
    0,     // wb.bw.b
    5,     // .w.bw.b
    33,    // bw.bw.b
    8,     // ww.bw.b
    -20,   // ..bbw.b
    23,    // b.bbw.b
    -28,   // w.bbw.b
    5,     // .bbbw.b
    -30,   // bbbbw.b
    -11,   // wbbbw.b
    23,    // .wbbw.b
    12,    // bwbbw.b
    -8,    // wwbbw.b
    18,    // ..wbw.b
    -24,   // b.wbw.b
    35,    // w.wbw.b
    7,     // .bwbw.b
    8,     // bbwbw.b
    -4,    // wbwbw.b
    38,    // .wwbw.b
    -4,    // bwwbw.b
    13,    // wwwbw.b
    23,    // ...ww.b
    34,    // b..ww.b
    34,    // w..ww.b
    6,     // .b.ww.b
    6,     // bb.ww.b
    7,     // wb.ww.b
    -16,   // .w.ww.b
    -29,   // bw.ww.b
    -18,   // ww.ww.b
    -5,    // ..bww.b
    18,    // b.bww.b
    28,    // w.bww.b
    -13,   // .bbww.b
    -6,    // bbbww.b
    6,     // wbbww.b
    -20,   // .wbww.b
    -13,   // bwbww.b
    -35,   // wwbww.b
    33,    // ..www.b
    4,     // b.www.b
    -35,   // w.www.b
    44,    // .bwww.b
    17,    // bbwww.b
    -6,    // wbwww.b
    0,     // .wwww.b
    -12,   // bwwww.b
    -8,    // wwwww.b
    22,    // .....bb
    15,    // b....bb
    -6,    // w....bb
    37,    // .b...bb
    -25,   // bb...bb
    32,    // wb...bb
    -19,   // .w...bb
    -11,   // bw...bb
    0,     // ww...bb
    -19,   // ..b..bb
    -20,   // b.b..bb
    1,     // w.b..bb
    11,    // .bb..bb
    70,    // bbb..bb
    -24,   // wbb..bb
    3,     // .wb..bb
    -21,   // bwb..bb
    5,     // wwb..bb
    24,    // ..w..bb
    23,    // b.w..bb
    41,    // w.w..bb
    -18,   // .bw..bb
    12,    // bbw..bb
    10,    // wbw..bb
    7,     // .ww..bb
    12,    // bww..bb
    -1,    // www..bb
    -2,    // ...b.bb
    6,     // b..b.bb
    32,    // w..b.bb
    3,     // .b.b.bb
    -16,   // bb.b.bb
    -15,   // wb.b.bb
    15,    // .w.b.bb
    14,    // bw.b.bb
    0,     // ww.b.bb
    16,    // ..bb.bb
    18,    // b.bb.bb
    18,    // w.bb.bb
    11,    // .bbb.bb
    11,    // bbbb.bb
    5,     // wbbb.bb
    3,     // .wbb.bb
    16,    // bwbb.bb
    16,    // wwbb.bb
    0,     // ..wb.bb
    -3,    // b.wb.bb
    -50,   // w.wb.bb
    -11,   // .bwb.bb
    43,    // bbwb.bb
    -38,   // wbwb.bb
    10,    // .wwb.bb
    8,     // bwwb.bb
    20,    // wwwb.bb
    34,    // ...w.bb
    1,     // b..w.bb
    5,     // w..w.bb
    18,    // .b.w.bb
    22,    // bb.w.bb
    1,     // wb.w.bb
    19,    // .w.w.bb
    -33,   // bw.w.bb
    0,     // ww.w.bb
    -5,    // ..bw.bb
    8,     // b.bw.bb
    -8,    // w.bw.bb
    28,    // .bbw.bb
    -35,   // bbbw.bb
    8,     // wbbw.bb
    19,    // .wbw.bb
    19,    // bwbw.bb
    -2,    // wwbw.bb
    -19,   // ..ww.bb
    6,     // b.ww.bb
    4,     // w.ww.bb
    -22,   // .bww.bb
    13,    // bbww.bb
    17,    // wbww.bb
    12,    // .www.bb
    12,    // bwww.bb
    10,    // wwww.bb
    88,    // ....bbb
    -40,   // b...bbb
    -20,   // w...bbb
    -14,   // .b..bbb
    70,    // bb..bbb
    4,     // wb..bbb
    41,    // .w..bbb
    14,    // bw..bbb
    1,     // ww..bbb
    25,    // ..b.bbb
    -19,   // b.b.bbb
    5,     // w.b.bbb
    -15,   // .bb.bbb
    55,    // bbb.bbb
    4,     // wbb.bbb
    34,    // .wb.bbb
    -7,    // bwb.bbb
    20,    // wwb.bbb
    21,    // ..w.bbb
    23,    // b.w.bbb
    18,    // w.w.bbb
    -4,    // .bw.bbb
    -6,    // bbw.bbb
    -14,   // wbw.bbb
    47,    // .ww.bbb
    -15,   // bww.bbb
    0,     // www.bbb
    135,   // ...bbbb
    14,    // b..bbbb
    5,     // w..bbbb
    26,    // .b.bbbb
    11,    // bb.bbbb
    -44,   // wb.bbbb
    22,    // .w.bbbb
    -6,    // bw.bbbb
    -10,   // ww.bbbb
    26,    // ..bbbbb
    8,     // b.bbbbb
    8,     // w.bbbbb
    12,    // .bbbbbb
    45,    // bbbbbbb
    5,     // wbbbbbb
    3,     // .wbbbbb
    -18,   // bwbbbbb
    -4,    // wwbbbbb
    30,    // ..wbbbb
    -30,   // b.wbbbb
    -25,   // w.wbbbb
    -1,    // .bwbbbb
    24,    // bbwbbbb
    -21,   // wbwbbbb
    -8,    // .wwbbbb
    -12,   // bwwbbbb
    -9,    // wwwbbbb
    -10,   // ...wbbb
    1,     // b..wbbb
    10,    // w..wbbb
    -5,    // .b.wbbb
    -35,   // bb.wbbb
    -26,   // wb.wbbb
    30,    // .w.wbbb
    -17,   // bw.wbbb
    -20,   // ww.wbbb
    -10,   // ..bwbbb
    -12,   // b.bwbbb
    -13,   // w.bwbbb
    -30,   // .bbwbbb
    -10,   // bbbwbbb
    -2,    // wbbwbbb
    43,    // .wbwbbb
    -23,   // bwbwbbb
    -1,    // wwbwbbb
    28,    // ..wwbbb
    -6,    // b.wwbbb
    24,    // w.wwbbb
    -12,   // .bwwbbb
    -23,   // bbwwbbb
    6,     // wbwwbbb
    -10,   // .wwwbbb
    -12,   // bwwwbbb
    9,     // wwwwbbb
    18,    // ....wbb
    -22,   // b...wbb
    21,    // w...wbb
    -27,   // .b..wbb
    12,    // bb..wbb
    1,     // wb..wbb
    -32,   // .w..wbb
    -15,   // bw..wbb
    -5,    // ww..wbb
    -7,    // ..b.wbb
    9,     // b.b.wbb
    21,    // w.b.wbb
    -2,    // .bb.wbb
    -6,    // bbb.wbb
    33,    // wbb.wbb
    -16,   // .wb.wbb
    -13,   // bwb.wbb
    0,     // wwb.wbb
    -12,   // ..w.wbb
    10,    // b.w.wbb
    -40,   // w.w.wbb
    15,    // .bw.wbb
    29,    // bbw.wbb
    0,     // wbw.wbb
    6,     // .ww.wbb
    -6,    // bww.wbb
    -20,   // www.wbb
    -25,   // ...bwbb
    31,    // b..bwbb
    -11,   // w..bwbb
    6,     // .b.bwbb
    43,    // bb.bwbb
    -18,   // wb.bwbb
    -28,   // .w.bwbb
    -41,   // bw.bwbb
    2,     // ww.bwbb
    -31,   // ..bbwbb
    26,    // b.bbwbb
    35,    // w.bbwbb
    -25,   // .bbbwbb
    24,    // bbbbwbb
    -45,   // wbbbwbb
    -22,   // .wbbwbb
    -15,   // bwbbwbb
    36,    // wwbbwbb
    5,     // ..wbwbb
    8,     // b.wbwbb
    7,     // w.wbwbb
    38,    // .bwbwbb
    -17,   // bbwbwbb
    -7,    // wbwbwbb
    -31,   // .wwbwbb
    1,     // bwwbwbb
    1,     // wwwbwbb
    -17,   // ...wwbb
    7,     // b..wwbb
    -2,    // w..wwbb
    -36,   // .b.wwbb
    13,    // bb.wwbb
    3,     // wb.wwbb
    44,    // .w.wwbb
    50,    // bw.wwbb
    -16,   // ww.wwbb
    5,     // ..bwwbb
    -32,   // b.bwwbb
    8,     // w.bwwbb
    -16,   // .bbwwbb
    -23,   // bbbwwbb
    -14,   // wbbwwbb
    -33,   // .wbwwbb
    3,     // bwbwwbb
    -36,   // wwbwwbb
    -2,    // ..wwwbb
    17,    // b.wwwbb
    15,    // w.wwwbb
    5,     // .bwwwbb
    -8,    // bbwwwbb
    -1,    // wbwwwbb
    -20,   // .wwwwbb
    1,     // bwwwwbb
    4,     // wwwwwbb
    -4,    // .....wb
    -6,    // b....wb
    -11,   // w....wb
    17,    // .b...wb
    -11,   // bb...wb
    0,     // wb...wb
    -15,   // .w...wb
    17,    // bw...wb
    -32,   // ww...wb
    -23,   // ..b..wb
    50,    // b.b..wb
    -25,   // w.b..wb
    13,    // .bb..wb
    14,    // bbb..wb
    10,    // wbb..wb
    30,    // .wb..wb
    -15,   // bwb..wb
    -1,    // wwb..wb
    13,    // ..w..wb
    12,    // b.w..wb
    14,    // w.w..wb
    -21,   // .bw..wb
    -15,   // bbw..wb
    -50,   // wbw..wb
    -22,   // .ww..wb
    16,    // bww..wb
    -4,    // www..wb
    -16,   // ...b.wb
    -17,   // b..b.wb
    26,    // w..b.wb
    -55,   // .b.b.wb
    14,    // bb.b.wb
    3,     // wb.b.wb
    -1,    // .w.b.wb
    -11,   // bw.b.wb
    -1,    // ww.b.wb
    1,     // ..bb.wb
    34,    // b.bb.wb
    -7,    // w.bb.wb
    33,    // .bbb.wb
    -6,    // bbbb.wb
    2,     // wbbb.wb
    16,    // .wbb.wb
    -4,    // bwbb.wb
    -3,    // wwbb.wb
    -37,   // ..wb.wb
    33,    // b.wb.wb
    15,    // w.wb.wb
    12,    // .bwb.wb
    -41,   // bbwb.wb
    -12,   // wbwb.wb
    11,    // .wwb.wb
    -21,   // bwwb.wb
    26,    // wwwb.wb
    29,    // ...w.wb
    -22,   // b..w.wb
    -24,   // w..w.wb
    6,     // .b.w.wb
    -33,   // bb.w.wb
    -3,    // wb.w.wb
    6,     // .w.w.wb
    14,    // bw.w.wb
    15,    // ww.w.wb
    -8,    // ..bw.wb
    29,    // b.bw.wb
    0,     // w.bw.wb
    -34,   // .bbw.wb
    -17,   // bbbw.wb
    -6,    // wbbw.wb
    -30,   // .wbw.wb
    -14,   // bwbw.wb
    18,    // wwbw.wb
    20,    // ..ww.wb
    -29,   // b.ww.wb
    19,    // w.ww.wb
    -12,   // .bww.wb
    50,    // bbww.wb
    14,    // wbww.wb
    -29,   // .www.wb
    -19,   // bwww.wb
    44,    // wwww.wb
    -14,   // ....bwb
    -44,   // b...bwb
    13,    // w...bwb
    3,     // .b..bwb
    -21,   // bb..bwb
    50,    // wb..bwb
    34,    // .w..bwb
    -15,   // bw..bwb
    -10,   // ww..bwb
    -10,   // ..b.bwb
    15,    // b.b.bwb
    7,     // w.b.bwb
    6,     // .bb.bwb
    -7,    // bbb.bwb
    -19,   // wbb.bwb
    26,    // .wb.bwb
    -19,   // bwb.bwb
    0,     // wwb.bwb
    -8,    // ..w.bwb
    18,    // b.w.bwb
    12,    // w.w.bwb
    -14,   // .bw.bwb
    -13,   // bbw.bwb
    0,     // wbw.bwb
    7,     // .ww.bwb
    -12,   // bww.bwb
    14,    // www.bwb
    1,     // ...bbwb
    -22,   // b..bbwb
    -31,   // w..bbwb
    19,    // .b.bbwb
    16,    // bb.bbwb
    -14,   // wb.bbwb
    -36,   // .w.bbwb
    -4,    // bw.bbwb
    -17,   // ww.bbwb
    -22,   // ..bbbwb
    12,    // b.bbbwb
    6,     // w.bbbwb
    14,    // .bbbbwb
    -18,   // bbbbbwb
    26,    // wbbbbwb
    -3,    // .wbbbwb
    -29,   // bwbbbwb
    1,     // wwbbbwb
    -47,   // ..wbbwb
    12,    // b.wbbwb
    10,    // w.wbbwb
    -3,    // .bwbbwb
    -15,   // bbwbbwb
    -14,   // wbwbbwb
    -23,   // .wwbbwb
    6,     // bwwbbwb
    -6,    // wwwbbwb
    1,     // ...wbwb
    -39,   // b..wbwb
    9,     // w..wbwb
    -8,    // .b.wbwb
    19,    // bb.wbwb
    12,    // wb.wbwb
    -3,    // .w.wbwb
    -14,   // bw.wbwb
    38,    // ww.wbwb
    8,     // ..bwbwb
    -18,   // b.bwbwb
    4,     // w.bwbwb
    -10,   // .bbwbwb
    -23,   // bbbwbwb
    -14,   // wbbwbwb
    -21,   // .wbwbwb
    10,    // bwbwbwb
    7,     // wwbwbwb
    24,    // ..wwbwb
    -13,   // b.wwbwb
    -7,    // w.wwbwb
    -5,    // .bwwbwb
    3,     // bbwwbwb
    14,    // wbwwbwb
    28,    // .wwwbwb
    23,    // bwwwbwb
    21,    // wwwwbwb
    25,    // ....wwb
    -6,    // b...wwb
    29,    // w...wwb
    -43,   // .b..wwb
    12,    // bb..wwb
    -10,   // wb..wwb
    -53,   // .w..wwb
    16,    // bw..wwb
    24,    // ww..wwb
    -5,    // ..b.wwb
    0,     // b.b.wwb
    1,     // w.b.wwb
    -3,    // .bb.wwb
    -15,   // bbb.wwb
    0,     // wbb.wwb
    13,    // .wb.wwb
    -12,   // bwb.wwb
    -33,   // wwb.wwb
    -3,    // ..w.wwb
    -8,    // b.w.wwb
    8,     // w.w.wwb
    18,    // .bw.wwb
    -6,    // bbw.wwb
    19,    // wbw.wwb
    -31,   // .ww.wwb
    -32,   // bww.wwb
    -4,    // www.wwb
    0,     // ...bwwb
    5,     // b..bwwb
    28,    // w..bwwb
    -6,    // .b.bwwb
    8,     // bb.bwwb
    6,     // wb.bwwb
    5,     // .w.bwwb
    -21,   // bw.bwwb
    -8,    // ww.bwwb
    -6,    // ..bbwwb
    1,     // b.bbwwb
    -6,    // w.bbwwb
    -31,   // .bbbwwb
    -12,   // bbbbwwb
    13,    // wbbbwwb
    20,    // .wbbwwb
    6,     // bwbbwwb
    14,    // wwbbwwb
    -28,   // ..wbwwb
    -4,    // b.wbwwb
    4,     // w.wbwwb
    40,    // .bwbwwb
    1,     // bbwbwwb
    14,    // wbwbwwb
    14,    // .wwbwwb
    29,    // bwwbwwb
    2,     // wwwbwwb
    46,    // ...wwwb
    -4,    // b..wwwb
    -14,   // w..wwwb
    -3,    // .b.wwwb
    12,    // bb.wwwb
    -2,    // wb.wwwb
    -50,   // .w.wwwb
    -19,   // bw.wwwb
    -5,    // ww.wwwb
    16,    // ..bwwwb
    7,     // b.bwwwb
    11,    // w.bwwwb
    -9,    // .bbwwwb
    -12,   // bbbwwwb
    -13,   // wbbwwwb
    -8,    // .wbwwwb
    23,    // bwbwwwb
    45,    // wwbwwwb
    -39,   // ..wwwwb
    -12,   // b.wwwwb
    25,    // w.wwwwb
    67,    // .bwwwwb
    1,     // bbwwwwb
    -26,   // wbwwwwb
    -9,    // .wwwwwb
    19,    // bwwwwwb
    -5,    // wwwwwwb
    -2,    // ......w
    0,     // b.....w
    3,     // w.....w
    -35,   // .b....w
    -6,    // bb....w
    6,     // wb....w
    15,    // .w....w
    -11,   // bw....w
    -15,   // ww....w
    5,     // ..b...w
    -4,    // b.b...w
    30,    // w.b...w
    7,     // .bb...w
    -20,   // bbb...w
    6,     // wbb...w
    -27,   // .wb...w
    13,    // bwb...w
    22,    // wwb...w
    5,     // ..w...w
    3,     // b.w...w
    13,    // w.w...w
    -19,   // .bw...w
    21,    // bbw...w
    44,    // wbw...w
    18,    // .ww...w
    29,    // bww...w
    40,    // www...w
    16,    // ...b..w
    3,     // b..b..w
    12,    // w..b..w
    43,    // .b.b..w
    32,    // bb.b..w
    22,    // wb.b..w
    -16,   // .w.b..w
    26,    // bw.b..w
    -1,    // ww.b..w
    0,     // ..bb..w
    36,    // b.bb..w
    -34,   // w.bb..w
    14,    // .bbb..w
    5,     // bbbb..w
    4,     // wbbb..w
    8,     // .wbb..w
    -31,   // bwbb..w
    -7,    // wwbb..w
    21,    // ..wb..w
    20,    // b.wb..w
    -4,    // w.wb..w
    -10,   // .bwb..w
    -11,   // bbwb..w
    39,    // wbwb..w
    -18,   // .wwb..w
    28,    // bwwb..w
    -1,    // wwwb..w
    -8,    // ...w..w
    -3,    // b..w..w
    -4,    // w..w..w
    -9,    // .b.w..w
    5,     // bb.w..w
    17,    // wb.w..w
    14,    // .w.w..w
    -24,   // bw.w..w
    -6,    // ww.w..w
    -12,   // ..bw..w
    17,    // b.bw..w
    -33,   // w.bw..w
    16,    // .bbw..w
    10,    // bbbw..w
    -5,    // wbbw..w
    5,     // .wbw..w
    9,     // bwbw..w
    -31,   // wwbw..w
    5,     // ..ww..w
    34,    // b.ww..w
    1,     // w.ww..w
    21,    // .bww..w
    -2,    // bbww..w
    22,    // wbww..w
    15,    // .www..w
    -14,   // bwww..w
    -14,   // wwww..w
    -4,    // ....b.w
    -3,    // b...b.w
    30,    // w...b.w
    4,     // .b..b.w
    1,     // bb..b.w
    -12,   // wb..b.w
    43,    // .w..b.w
    -25,   // bw..b.w
    -23,   // ww..b.w
    0,     // ..b.b.w
    8,     // b.b.b.w
    47,    // w.b.b.w
    0,     // .bb.b.w
    5,     // bbb.b.w
    8,     // wbb.b.w
    -44,   // .wb.b.w
    7,     // bwb.b.w
    -10,   // wwb.b.w
    12,    // ..w.b.w
    0,     // b.w.b.w
    19,    // w.w.b.w
    -11,   // .bw.b.w
    21,    // bbw.b.w
    -18,   // wbw.b.w
    -5,    // .ww.b.w
    1,     // bww.b.w
    -23,   // www.b.w
    -23,   // ...bb.w
    -34,   // b..bb.w
    -34,   // w..bb.w
    16,    // .b.bb.w
    18,    // bb.bb.w
    29,    // wb.bb.w
    -6,    // .w.bb.w
    -7,    // bw.bb.w
    -6,    // ww.bb.w
    -33,   // ..bbb.w
    35,    // b.bbb.w
    -4,    // w.bbb.w
    0,     // .bbbb.w
    8,     // bbbbb.w
    12,    // wbbbb.w
    -44,   // .wbbb.w
    6,     // bwbbb.w
    -17,   // wwbbb.w
    5,     // ..wbb.w
    -28,   // b.wbb.w
    -18,   // w.wbb.w
    20,    // .bwbb.w
    35,    // bbwbb.w
    13,    // wbwbb.w
    13,    // .wwbb.w
    -6,    // bwwbb.w
    6,     // wwwbb.w
    -23,   // ...wb.w
    -20,   // b..wb.w
    -33,   // w..wb.w
    -5,    // .b.wb.w
    -8,    // bb.wb.w
    -33,   // wb.wb.w
    3,     // .w.wb.w
    0,     // bw.wb.w
    3,     // ww.wb.w
    -18,   // ..bwb.w
    -35,   // b.bwb.w
    24,    // w.bwb.w
    -38,   // .bbwb.w
    -13,   // bbbwb.w
    4,     // wbbwb.w
    -7,    // .wbwb.w
    4,     // bwbwb.w
    -8,    // wwbwb.w
    20,    // ..wwb.w
    28,    // b.wwb.w
    -23,   // w.wwb.w
    -23,   // .bwwb.w
    8,     // bbwwb.w
    -12,   // wbwwb.w
    -5,    // .wwwb.w
    11,    // bwwwb.w
    30,    // wwwwb.w
    -19,   // ....w.w
    4,     // b...w.w
    13,    // w...w.w
    9,     // .b..w.w
    41,    // bb..w.w
    -50,   // wb..w.w
    -11,   // .w..w.w
    14,    // bw..w.w
    20,    // ww..w.w
    -2,    // ..b.w.w
    0,     // b.b.w.w
    19,    // w.b.w.w
    -42,   // .bb.w.w
    18,    // bbb.w.w
    0,     // wbb.w.w
    30,    // .wb.w.w
    12,    // bwb.w.w
    -9,    // wwb.w.w
    22,    // ..w.w.w
    -8,    // b.w.w.w
    13,    // w.w.w.w
    38,    // .bw.w.w
    -40,   // bbw.w.w
    -15,   // wbw.w.w
    -11,   // .ww.w.w
    8,     // bww.w.w
    19,    // www.w.w
    10,    // ...bw.w
    -17,   // b..bw.w
    -4,    // w..bw.w
    5,     // .b.bw.w
    -50,   // bb.bw.w
    -29,   // wb.bw.w
    -3,    // .w.bw.w
    15,    // bw.bw.w
    -8,    // ww.bw.w
    6,     // ..bbw.w
    14,    // b.bbw.w
    -18,   // w.bbw.w
    -11,   // .bbbw.w
    -25,   // bbbbw.w
    -7,    // wbbbw.w
    -17,   // .wbbw.w
    10,    // bwbbw.w
    32,    // wwbbw.w
    3,     // ..wbw.w
    35,    // b.wbw.w
    -20,   // w.wbw.w
    -7,    // .bwbw.w
    7,     // bbwbw.w
    18,    // wbwbw.w
    -7,    // .wwbw.w
    4,     // bwwbw.w
    12,    // wwwbw.w
    -12,   // ...ww.w
    -36,   // b..ww.w
    1,     // w..ww.w
    -6,    // .b.ww.w
    4,     // bb.ww.w
    -34,   // wb.ww.w
    42,    // .w.ww.w
    19,    // bw.ww.w
    -18,   // ww.ww.w
    9,     // ..bww.w
    -14,   // b.bww.w
    -23,   // w.bww.w
    2,     // .bbww.w
    24,    // bbbww.w
    -1,    // wbbww.w
    36,    // .wbww.w
    -7,    // bwbww.w
    -26,   // wwbww.w
    -31,   // ..www.w
    -35,   // b.www.w
    -35,   // w.www.w
    -20,   // .bwww.w
    15,    // bbwww.w
    -12,   // wbwww.w
    -29,   // .wwww.w
    25,    // bwwww.w
    -8,    // wwwww.w
    4,     // .....bw
    11,    // b....bw
    6,     // w....bw
    15,    // .b...bw
    32,    // bb...bw
    -17,   // wb...bw
    -17,   // .w...bw
    0,     // bw...bw
    11,    // ww...bw
    -13,   // ..b..bw
    -14,   // b.b..bw
    -12,   // w.b..bw
    22,    // .bb..bw
    4,     // bbb..bw
    -16,   // wbb..bw
    21,    // .wb..bw
    50,    // bwb..bw
    15,    // wwb..bw
    23,    // ..w..bw
    25,    // b.w..bw
    -50,   // w.w..bw
    -30,   // .bw..bw
    1,     // bbw..bw
    15,    // wbw..bw
    -13,   // .ww..bw
    -10,   // bww..bw
    -14,   // www..bw
    -29,   // ...b.bw
    24,    // b..b.bw
    22,    // w..b.bw
    -6,    // .b.b.bw
    -15,   // bb.b.bw
    -14,   // wb.b.bw
    -6,    // .w.b.bw
    3,     // bw.b.bw
    33,    // ww.b.bw
    -20,   // ..bb.bw
    -19,   // b.bb.bw
    29,    // w.bb.bw
    29,    // .bbb.bw
    -44,   // bbbb.bw
    19,    // wbbb.bw
    12,    // .wbb.bw
    -14,   // bwbb.bw
    -50,   // wwbb.bw
    8,     // ..wb.bw
    0,     // b.wb.bw
    -29,   // w.wb.bw
    30,    // .bwb.bw
    -18,   // bbwb.bw
    14,    // wbwb.bw
    34,    // .wwb.bw
    6,     // bwwb.bw
    17,    // wwwb.bw
    16,    // ...w.bw
    -26,   // b..w.bw
    17,    // w..w.bw
    1,     // .b.w.bw
    1,     // bb.w.bw
    11,    // wb.w.bw
    55,    // .w.w.bw
    -3,    // bw.w.bw
    -14,   // ww.w.bw
    37,    // ..bw.bw
    -15,   // b.bw.bw
    -33,   // w.bw.bw
    -11,   // .bbw.bw
    -26,   // bbbw.bw
    21,    // wbbw.bw
    -12,   // .wbw.bw
    12,    // bwbw.bw
    41,    // wwbw.bw
    -1,    // ..ww.bw
    7,     // b.ww.bw
    -34,   // w.ww.bw
    -16,   // .bww.bw
    3,     // bbww.bw
    4,     // wbww.bw
    -33,   // .www.bw
    -2,    // bwww.bw
    6,     // wwww.bw
    -25,   // ....bbw
    -29,   // b...bbw
    6,     // w...bbw
    53,    // .b..bbw
    -24,   // bb..bbw
    -16,   // wb..bbw
    43,    // .w..bbw
    10,    // bw..bbw
    -12,   // ww..bbw
    3,     // ..b.bbw
    -8,    // b.b.bbw
    8,     // w.b.bbw
    31,    // .bb.bbw
    4,     // bbb.bbw
    32,    // wbb.bbw
    -18,   // .wb.bbw
    -19,   // bwb.bbw
    6,     // wwb.bbw
    5,     // ..w.bbw
    -1,    // b.w.bbw
    0,     // w.w.bbw
    -13,   // .bw.bbw
    33,    // bbw.bbw
    12,    // wbw.bbw
    3,     // .ww.bbw
    0,     // bww.bbw
    15,    // www.bbw
    -46,   // ...bbbw
    14,    // b..bbbw
    4,     // w..bbbw
    50,    // .b.bbbw
    5,     // bb.bbbw
    19,    // wb.bbbw
    3,     // .w.bbbw
    2,     // bw.bbbw
    -12,   // ww.bbbw
    39,    // ..bbbbw
    -25,   // b.bbbbw
    12,    // w.bbbbw
    9,     // .bbbbbw
    5,     // bbbbbbw
    -19,   // wbbbbbw
    -67,   // .wbbbbw
    26,    // bwbbbbw
    -1,    // wwbbbbw
    -16,   // ..wbbbw
    -11,   // b.wbbbw
    -7,    // w.wbbbw
    8,     // .bwbbbw
    -45,   // bbwbbbw
    -23,   // wbwbbbw
    9,     // .wwbbbw
    13,    // bwwbbbw
    12,    // wwwbbbw
    0,     // ...wbbw
    -28,   // b..wbbw
    -5,    // w..wbbw
    -5,    // .b.wbbw
    8,     // bb.wbbw
    21,    // wb.wbbw
    6,     // .w.wbbw
    -6,    // bw.wbbw
    -8,    // ww.wbbw
    28,    // ..bwbbw
    -4,    // b.bwbbw
    4,     // w.bwbbw
    -14,   // .bbwbbw
    -2,    // bbbwbbw
    -29,   // wbbwbbw
    -40,   // .wbwbbw
    -14,   // bwbwbbw
    -1,    // wwbwbbw
    6,     // ..wwbbw
    6,     // b.wwbbw
    -1,    // w.wwbbw
    -20,   // .bwwbbw
    -14,   // bbwwbbw
    -6,    // wbwwbbw
    31,    // .wwwbbw
    -13,   // bwwwbbw
    12,    // wwwwbbw
    14,    // ....wbw
    -13,   // b...wbw
    44,    // w...wbw
    -34,   // .b..wbw
    10,    // bb..wbw
    15,    // wb..wbw
    -3,    // .w..wbw
    -50,   // bw..wbw
    21,    // ww..wbw
    8,     // ..b.wbw
    -12,   // b.b.wbw
    -18,   // w.b.wbw
    -7,    // .bb.wbw
    -14,   // bbb.wbw
    12,    // wbb.wbw
    14,    // .wb.wbw
    0,     // bwb.wbw
    13,    // wwb.wbw
    10,    // ..w.wbw
    -7,    // b.w.wbw
    -15,   // w.w.wbw
    -26,   // .bw.wbw
    0,     // bbw.wbw
    19,    // wbw.wbw
    -6,    // .ww.wbw
    19,    // bww.wbw
    7,     // www.wbw
    -1,    // ...bwbw
    -9,    // b..bwbw
    39,    // w..bwbw
    3,     // .b.bwbw
    -38,   // bb.bwbw
    14,    // wb.bwbw
    8,     // .w.bwbw
    -12,   // bw.bwbw
    -19,   // ww.bwbw
    -24,   // ..bbwbw
    7,     // b.bbwbw
    13,    // w.bbwbw
    -28,   // .bbbwbw
    -21,   // bbbbwbw
    -23,   // wbbbwbw
    5,     // .wbbwbw
    -14,   // bwbbwbw
    -3,    // wwbbwbw
    -8,    // ..wbwbw
    -4,    // b.wbwbw
    18,    // w.wbwbw
    21,    // .bwbwbw
    -7,    // bbwbwbw
    -10,   // wbwbwbw
    10,    // .wwbwbw
    14,    // bwwbwbw
    23,    // wwwbwbw
    -1,    // ...wwbw
    31,    // b..wwbw
    22,    // w..wwbw
    36,    // .b.wwbw
    17,    // bb.wwbw
    4,     // wb.wwbw
    -19,   // .w.wwbw
    14,    // bw.wwbw
    -16,   // ww.wwbw
    47,    // ..bwwbw
    -10,   // b.bwwbw
    -12,   // w.bwwbw
    23,    // .bbwwbw
    6,     // bbbwwbw
    -6,    // wbbwwbw
    3,     // .wbwwbw
    14,    // bwbwwbw
    15,    // wwbwwbw
    22,    // ..wwwbw
    -6,    // b.wwwbw
    -12,   // w.wwwbw
    3,     // .bwwwbw
    -1,    // bbwwwbw
    29,    // wbwwwbw
    -14,   // .wwwwbw
    -26,   // bwwwwbw
    18,    // wwwwwbw
    -22,   // .....ww
    6,     // b....ww
    -15,   // w....ww
    19,    // .b...ww
    0,     // bb...ww
    11,    // wb...ww
    -37,   // .w...ww
    -32,   // bw...ww
    25,    // ww...ww
    -24,   // ..b..ww
    -41,   // b.b..ww
    -23,   // w.b..ww
    -7,    // .bb..ww
    1,     // bbb..ww
    -12,   // wbb..ww
    18,    // .wb..ww
    -10,   // bwb..ww
    -12,   // wwb..ww
    19,    // ..w..ww
    -1,    // b.w..ww
    20,    // w.w..ww
    -3,    // .bw..ww
    -5,    // bbw..ww
    21,    // wbw..ww
    -11,   // .ww..ww
    24,    // bww..ww
    -70,   // www..ww
    -34,   // ...b.ww
    -5,    // b..b.ww
    -1,    // w..b.ww
    -19,   // .b.b.ww
    0,     // bb.b.ww
    33,    // wb.b.ww
    -18,   // .w.b.ww
    -1,    // bw.b.ww
    -22,   // ww.b.ww
    19,    // ..bb.ww
    -4,    // b.bb.ww
    -6,    // w.bb.ww
    -12,   // .bbb.ww
    -10,   // bbbb.ww
    -12,   // wbbb.ww
    22,    // .wbb.ww
    -17,   // bwbb.ww
    -13,   // wwbb.ww
    5,     // ..wb.ww
    8,     // b.wb.ww
    -8,    // w.wb.ww
    -19,   // .bwb.ww
    2,     // bbwb.ww
    -19,   // wbwb.ww
    -28,   // .wwb.ww
    -8,    // bwwb.ww
    35,    // wwwb.ww
    2,     // ...w.ww
    -32,   // b..w.ww
    -6,    // w..w.ww
    -15,   // .b.w.ww
    0,     // bb.w.ww
    -14,   // wb.w.ww
    -3,    // .w.w.ww
    15,    // bw.w.ww
    16,    // ww.w.ww
    0,     // ..bw.ww
    50,    // b.bw.ww
    3,     // w.bw.ww
    -10,   // .bbw.ww
    -20,   // bbbw.ww
    -8,    // wbbw.ww
    11,    // .wbw.ww
    38,    // bwbw.ww
    -43,   // wwbw.ww
    -16,   // ..ww.ww
    -18,   // b.ww.ww
    -18,   // w.ww.ww
    -3,    // .bww.ww
    -16,   // bbww.ww
    -16,   // wbww.ww
    -11,   // .www.ww
    -5,    // bwww.ww
    -11,   // wwww.ww
    -18,   // ....bww
    -21,   // b...bww
    22,    // w...bww
    32,    // .b..bww
    5,     // bb..bww
    15,    // wb..bww
    27,    // .w..bww
    -1,    // bw..bww
    -12,   // ww..bww
    12,    // ..b.bww
    40,    // b.b.bww
    -10,   // w.b.bww
    -6,    // .bb.bww
    20,    // bbb.bww
    6,     // wbb.bww
    -15,   // .wb.bww
    0,     // bwb.bww
    -29,   // wwb.bww
    7,     // ..w.bww
    -21,   // b.w.bww
    -9,    // w.w.bww
    16,    // .bw.bww
    0,     // bbw.bww
    13,    // wbw.bww
    2,     // .ww.bww
    -33,   // bww.bww
    6,     // www.bww
    17,    // ...bbww
    2,     // b..bbww
    -7,    // w..bbww
    -44,   // .b.bbww
    16,    // bb.bbww
    -50,   // wb.bbww
    36,    // .w.bbww
    -3,    // bw.bbww
    -13,   // ww.bbww
    2,     // ..bbbww
    -15,   // b.bbbww
    -17,   // w.bbbww
    20,    // .bbbbww
    -4,    // bbbbbww
    -1,    // wbbbbww
    -5,    // .wbbbww
    1,     // bwbbbww
    8,     // wwbbbww
    -5,    // ..wbbww
    -8,    // b.wbbww
    32,    // w.wbbww
    33,    // .bwbbww
    36,    // bbwbbww
    -3,    // wbwbbww
    16,    // .wwbbww
    14,    // bwwbbww
    23,    // wwwbbww
    25,    // ...wbww
    11,    // b..wbww
    -31,   // w..wbww
    28,    // .b.wbww
    -2,    // bb.wbww
    41,    // wb.wbww
    -6,    // .w.wbww
    18,    // bw.wbww
    -43,   // ww.wbww
    -5,    // ..bwbww
    -7,    // b.bwbww
    -8,    // w.bwbww
    31,    // .bbwbww
    -1,    // bbbwbww
    -1,    // wbbwbww
    -38,   // .wbwbww
    7,     // bwbwbww
    17,    // wwbwbww
    31,    // ..wwbww
    -35,   // b.wwbww
    -26,   // w.wwbww
    22,    // .bwwbww
    -36,   // bbwwbww
    15,    // wbwwbww
    25,    // .wwwbww
    45,    // bwwwbww
    -24,   // wwwwbww
    -88,   // ....www
    20,    // b...www
    40,    // w...www
    -41,   // .b..www
    -1,    // bb..www
    -14,   // wb..www
    14,    // .w..www
    -4,    // bw..www
    -70,   // ww..www
    -21,   // ..b.www
    -18,   // b.b.www
    -23,   // w.b.www
    -47,   // .bb.www
    0,     // bbb.www
    15,    // wbb.www
    4,     // .wb.www
    14,    // bwb.www
    6,     // wwb.www
    -25,   // ..w.www
    -5,    // b.w.www
    19,    // w.w.www
    -34,   // .bw.www
    -20,   // bbw.www
    7,     // wbw.www
    15,    // .ww.www
    -4,    // bww.www
    -55,   // www.www
    10,    // ...bwww
    -10,   // b..bwww
    -1,    // w..bwww
    -30,   // .b.bwww
    20,    // bb.bwww
    17,    // wb.bwww
    5,     // .w.bwww
    26,    // bw.bwww
    35,    // ww.bwww
    -28,   // ..bbwww
    -24,   // b.bbwww
    6,     // w.bbwww
    10,    // .bbbwww
    -9,    // bbbbwww
    12,    // wbbbwww
    12,    // .wbbwww
    -6,    // bwbbwww
    23,    // wwbbwww
    10,    // ..wbwww
    13,    // b.wbwww
    12,    // w.wbwww
    -43,   // .bwbwww
    1,     // bbwbwww
    23,    // wbwbwww
    30,    // .wwbwww
    2,     // bwwbwww
    10,    // wwwbwww
    -135,  // ...wwww
    -5,    // b..wwww
    -14,   // w..wwww
    -22,   // .b.wwww
    10,    // bb.wwww
    6,     // wb.wwww
    -26,   // .w.wwww
    44,    // bw.wwww
    -11,   // ww.wwww
    -30,   // ..bwwww
    25,    // b.bwwww
    30,    // w.bwwww
    8,     // .bbwwww
    9,     // bbbwwww
    12,    // wbbwwww
    1,     // .wbwwww
    21,    // bwbwwww
    -24,   // wwbwwww
    -26,   // ..wwwww
    -8,    // b.wwwww
    -8,    // w.wwwww
    -3,    // .bwwwww
    4,     // bbwwwww
    18,    // wbwwwww
    -12,   // .wwwwww
    -5,    // bwwwwww
    -45,   // wwwwwww
    0,     // captures=0 threats=0
    7,     // captures=0 threats=1
    38,    // captures=0 threats=2
    42,    // captures=0 threats=3
    64,    // captures=0 threats=4
    7,     // captures=0 additional threats
    6,     // captures=1 threats=0
    42,    // captures=1 threats=1
    43,    // captures=1 threats=2
    79,    // captures=1 threats=3
    82,    // captures=1 threats=4
    39,    // captures=1 additional threats
    13,    // captures=2 threats=0
    53,    // captures=2 threats=1
    80,    // captures=2 threats=2
    97,    // captures=2 threats=3
    98,    // captures=2 threats=4
    29,    // captures=2 additional threats
    30,    // captures=3 threats=0
    70,    // captures=3 threats=1
    83,    // captures=3 threats=2
    98,    // captures=3 threats=3
    98,    // captures=3 threats=4
    41,    // captures=3 additional threats
    50,    // captures=4 threats=0
    100,   // captures=4 threats=1
    100,   // captures=4 threats=2
    100,   // captures=4 threats=3
    120,   // captures=4 threats=4
    16,    // captures=4 additional threats
].into_boxed_slice()
