vec![
    0,     // .......
    13,    // b......
    -13,   // w......
    -5,    // .b.....
    8,     // bb.....
    13,    // wb.....
    5,     // .w.....
    -13,   // bw.....
    -8,    // ww.....
    -11,   // ..b....
    -23,   // b.b....
    -11,   // w.b....
    -20,   // .bb....
    86,    // bbb....
    -38,   // wbb....
    -21,   // .wb....
    -17,   // bwb....
    39,    // wwb....
    11,    // ..w....
    11,    // b.w....
    23,    // w.w....
    21,    // .bw....
    -39,   // bbw....
    17,    // wbw....
    20,    // .ww....
    38,    // bww....
    -86,   // www....
    4,     // ...b...
    -1,    // b..b...
    -26,   // w..b...
    12,    // .b.b...
    38,    // bb.b...
    20,    // wb.b...
    -13,   // .w.b...
    -16,   // bw.b...
    -9,    // ww.b...
    -10,   // ..bb...
    52,    // b.bb...
    16,    // w.bb...
    20,    // .bbb...
    65,    // bbbb...
    -24,   // wbbb...
    10,    // .wbb...
    -10,   // bwbb...
    0,     // wwbb...
    17,    // ..wb...
    -18,   // b.wb...
    38,    // w.wb...
    -25,   // .bwb...
    -18,   // bbwb...
    -2,    // wbwb...
    -21,   // .wwb...
    11,    // bwwb...
    -3,    // wwwb...
    -4,    // ...w...
    26,    // b..w...
    1,     // w..w...
    13,    // .b.w...
    9,     // bb.w...
    16,    // wb.w...
    -12,   // .w.w...
    -20,   // bw.w...
    -38,   // ww.w...
    -17,   // ..bw...
    -38,   // b.bw...
    18,    // w.bw...
    21,    // .bbw...
    3,     // bbbw...
    -11,   // wbbw...
    25,    // .wbw...
    2,     // bwbw...
    18,    // wwbw...
    10,    // ..ww...
    -16,   // b.ww...
    -52,   // w.ww...
    -10,   // .bww...
    0,     // bbww...
    10,    // wbww...
    -20,   // .www...
    24,    // bwww...
    -65,   // wwww...
    -11,   // ....b..
    -17,   // b...b..
    18,    // w...b..
    -33,   // .b..b..
    -8,    // bb..b..
    3,     // wb..b..
    -16,   // .w..b..
    8,     // bw..b..
    -7,    // ww..b..
    -37,   // ..b.b..
    -33,   // b.b.b..
    -16,   // w.b.b..
    12,    // .bb.b..
    26,    // bbb.b..
    29,    // wbb.b..
    1,     // .wb.b..
    -3,    // bwb.b..
    22,    // wwb.b..
    0,     // ..w.b..
    -35,   // b.w.b..
    6,     // w.w.b..
    -12,   // .bw.b..
    -54,   // bbw.b..
    -6,    // wbw.b..
    2,     // .ww.b..
    -9,    // bww.b..
    22,    // www.b..
    -10,   // ...bb..
    -20,   // b..bb..
    -4,    // w..bb..
    42,    // .b.bb..
    8,     // bb.bb..
    -2,    // wb.bb..
    14,    // .w.bb..
    -27,   // bw.bb..
    -23,   // ww.bb..
    -11,   // ..bbb..
    -7,    // b.bbb..
    16,    // w.bbb..
    42,    // .bbbb..
    27,    // bbbbb..
    38,    // wbbbb..
    -19,   // .wbbb..
    -20,   // bwbbb..
    0,     // wwbbb..
    1,     // ..wbb..
    -1,    // b.wbb..
    -9,    // w.wbb..
    -13,   // .bwbb..
    36,    // bbwbb..
    17,    // wbwbb..
    -8,    // .wwbb..
    -22,   // bwwbb..
    41,    // wwwbb..
    -17,   // ...wb..
    18,    // b..wb..
    -1,    // w..wb..
    -21,   // .b.wb..
    -32,   // bb.wb..
    50,    // wb.wb..
    -1,    // .w.wb..
    3,     // bw.wb..
    16,    // ww.wb..
    20,    // ..bwb..
    17,    // b.bwb..
    25,    // w.bwb..
    -4,    // .bbwb..
    26,    // bbbwb..
    -3,    // wbbwb..
    11,    // .wbwb..
    20,    // bwbwb..
    6,     // wwbwb..
    -1,    // ..wwb..
    19,    // b.wwb..
    -15,   // w.wwb..
    -5,    // .bwwb..
    9,     // bbwwb..
    -15,   // wbwwb..
    -6,    // .wwwb..
    -27,   // bwwwb..
    10,    // wwwwb..
    11,    // ....w..
    -18,   // b...w..
    17,    // w...w..
    16,    // .b..w..
    7,     // bb..w..
    -8,    // wb..w..
    33,    // .w..w..
    -3,    // bw..w..
    8,     // ww..w..
    0,     // ..b.w..
    -6,    // b.b.w..
    35,    // w.b.w..
    -2,    // .bb.w..
    -22,   // bbb.w..
    9,     // wbb.w..
    12,    // .wb.w..
    6,     // bwb.w..
    54,    // wwb.w..
    37,    // ..w.w..
    16,    // b.w.w..
    33,    // w.w.w..
    -1,    // .bw.w..
    -22,   // bbw.w..
    3,     // wbw.w..
    -12,   // .ww.w..
    -29,   // bww.w..
    -26,   // www.w..
    17,    // ...bw..
    1,     // b..bw..
    -18,   // w..bw..
    1,     // .b.bw..
    -16,   // bb.bw..
    -3,    // wb.bw..
    21,    // .w.bw..
    -50,   // bw.bw..
    32,    // ww.bw..
    1,     // ..bbw..
    15,    // b.bbw..
    -19,   // w.bbw..
    6,     // .bbbw..
    -10,   // bbbbw..
    27,    // wbbbw..
    5,     // .wbbw..
    15,    // bwbbw..
    -9,    // wwbbw..
    -20,   // ..wbw..
    -25,   // b.wbw..
    -17,   // w.wbw..
    -11,   // .bwbw..
    -6,    // bbwbw..
    -20,   // wbwbw..
    4,     // .wwbw..
    3,     // bwwbw..
    -26,   // wwwbw..
    10,    // ...ww..
    4,     // b..ww..
    20,    // w..ww..
    -14,   // .b.ww..
    23,    // bb.ww..
    27,    // wb.ww..
    -42,   // .w.ww..
    2,     // bw.ww..
    -8,    // ww.ww..
    -1,    // ..bww..
    9,     // b.bww..
    1,     // w.bww..
    8,     // .bbww..
    -41,   // bbbww..
    22,    // wbbww..
    13,    // .wbww..
    -17,   // bwbww..
    -36,   // wwbww..
    11,    // ..www..
    -16,   // b.www..
    7,     // w.www..
    19,    // .bwww..
    0,     // bbwww..
    20,    // wbwww..
    -42,   // .wwww..
    -38,   // bwwww..
    -27,   // wwwww..
    -5,    // .....b.
    -23,   // b....b.
    -27,   // w....b.
    12,    // .b...b.
    17,    // bb...b.
    15,    // wb...b.
    0,     // .w...b.
    -14,   // bw...b.
    -23,   // ww...b.
    -33,   // ..b..b.
    14,    // b.b..b.
    -3,    // w.b..b.
    13,    // .bb..b.
    -2,    // bbb..b.
    10,    // wbb..b.
    -48,   // .wb..b.
    16,    // bwb..b.
    -13,   // wwb..b.
    16,    // ..w..b.
    4,     // b.w..b.
    -29,   // w.w..b.
    -12,   // .bw..b.
    7,     // bbw..b.
    -27,   // wbw..b.
    10,    // .ww..b.
    25,    // bww..b.
    6,     // www..b.
    12,    // ...b.b.
    -31,   // b..b.b.
    -2,    // w..b.b.
    -8,    // .b.b.b.
    -1,    // bb.b.b.
    -19,   // wb.b.b.
    37,    // .w.b.b.
    -4,    // bw.b.b.
    10,    // ww.b.b.
    42,    // ..bb.b.
    31,    // b.bb.b.
    -15,   // w.bb.b.
    12,    // .bbb.b.
    -5,    // bbbb.b.
    -10,   // wbbb.b.
    -21,   // .wbb.b.
    -7,    // bwbb.b.
    -13,   // wwbb.b.
    1,     // ..wb.b.
    -4,    // b.wb.b.
    19,    // w.wb.b.
    -40,   // .bwb.b.
    -13,   // bbwb.b.
    -6,    // wbwb.b.
    -1,    // .wwb.b.
    15,    // bwwb.b.
    -14,   // wwwb.b.
    13,    // ...w.b.
    16,    // b..w.b.
    1,     // w..w.b.
    2,     // .b.w.b.
    -13,   // bb.w.b.
    10,    // wb.w.b.
    -37,   // .w.w.b.
    -37,   // bw.w.b.
    -15,   // ww.w.b.
    -21,   // ..bw.b.
    -10,   // b.bw.b.
    6,     // w.bw.b.
    9,     // .bbw.b.
    -19,   // bbbw.b.
    -14,   // wbbw.b.
    -11,   // .wbw.b.
    6,     // bwbw.b.
    4,     // wwbw.b.
    -14,   // ..ww.b.
    -11,   // b.ww.b.
    -6,    // w.ww.b.
    12,    // .bww.b.
    49,    // bbww.b.
    5,     // wbww.b.
    -55,   // .www.b.
    10,    // bwww.b.
    6,     // wwww.b.
    -20,   // ....bb.
    18,    // b...bb.
    -29,   // w...bb.
    13,    // .b..bb.
    -13,   // bb..bb.
    -8,    // wb..bb.
    -10,   // .w..bb.
    16,    // bw..bb.
    -40,   // ww..bb.
    12,    // ..b.bb.
    -3,    // b.b.bb.
    -5,    // w.b.bb.
    -38,   // .bb.bb.
    5,     // bbb.bb.
    -1,    // wbb.bb.
    -4,    // .wb.bb.
    -24,   // bwb.bb.
    -3,    // wwb.bb.
    -2,    // ..w.bb.
    10,    // b.w.bb.
    -23,   // w.w.bb.
    -14,   // .bw.bb.
    30,    // bbw.bb.
    -18,   // wbw.bb.
    0,     // .ww.bb.
    -22,   // bww.bb.
    -2,    // www.bb.
    20,    // ...bbb.
    20,    // b..bbb.
    -27,   // w..bbb.
    12,    // .b.bbb.
    8,     // bb.bbb.
    15,    // wb.bbb.
    55,    // .w.bbb.
    9,     // bw.bbb.
    30,    // ww.bbb.
    42,    // ..bbbb.
    -17,   // b.bbbb.
    18,    // w.bbbb.
    30,    // .bbbbb.
    35,    // bbbbbb.
    16,    // wbbbbb.
    16,    // .wbbbb.
    -46,   // bwbbbb.
    -24,   // wwbbbb.
    6,     // ..wbbb.
    -23,   // b.wbbb.
    39,    // w.wbbb.
    10,    // .bwbbb.
    6,     // bbwbbb.
    -18,   // wbwbbb.
    16,    // .wwbbb.
    -29,   // bwwbbb.
    -25,   // wwwbbb.
    21,    // ...wbb.
    19,    // b..wbb.
    -19,   // w..wbb.
    9,     // .b.wbb.
    2,     // bb.wbb.
    9,     // wb.wbb.
    1,     // .w.wbb.
    12,    // bw.wbb.
    29,    // ww.wbb.
    -4,    // ..bwbb.
    5,     // b.bwbb.
    5,     // w.bwbb.
    -21,   // .bbwbb.
    11,    // bbbwbb.
    -20,   // wbbwbb.
    32,    // .wbwbb.
    10,    // bwbwbb.
    -6,    // wwbwbb.
    8,     // ..wwbb.
    10,    // b.wwbb.
    22,    // w.wwbb.
    -39,   // .bwwbb.
    4,     // bbwwbb.
    8,     // wbwwbb.
    -16,   // .wwwbb.
    -13,   // bwwwbb.
    -30,   // wwwwbb.
    21,    // ....wb.
    27,    // b...wb.
    -16,   // w...wb.
    -12,   // .b..wb.
    13,    // bb..wb.
    -5,    // wb..wb.
    48,    // .w..wb.
    34,    // bw..wb.
    -3,    // ww..wb.
    -12,   // ..b.wb.
    -1,    // b.b.wb.
    9,     // w.b.wb.
    -14,   // .bb.wb.
    40,    // bbb.wb.
    4,     // wbb.wb.
    0,     // .wb.wb.
    6,     // bwb.wb.
    8,     // wwb.wb.
    -1,    // ..w.wb.
    7,     // b.w.wb.
    9,     // w.w.wb.
    18,    // .bw.wb.
    -4,    // bbw.wb.
    -3,    // wbw.wb.
    4,     // .ww.wb.
    -20,   // bww.wb.
    -37,   // www.wb.
    -25,   // ...bwb.
    -1,    // b..bwb.
    33,    // w..bwb.
    -40,   // .b.bwb.
    -28,   // bb.bwb.
    26,    // wb.bwb.
    11,    // .w.bwb.
    -28,   // bw.bwb.
    -8,    // ww.bwb.
    -13,   // ..bbwb.
    22,    // b.bbwb.
    -10,   // w.bbwb.
    10,    // .bbbwb.
    -9,    // bbbbwb.
    -4,    // wbbbwb.
    -7,    // .wbbwb.
    8,     // bwbbwb.
    -23,   // wwbbwb.
    -11,   // ..wbwb.
    1,     // b.wbwb.
    25,    // w.wbwb.
    33,    // .bwbwb.
    -28,   // bbwbwb.
    30,    // wbwbwb.
    -32,   // .wwbwb.
    27,    // bwwbwb.
    23,    // wwwbwb.
    -10,   // ...wwb.
    40,    // b..wwb.
    12,    // w..wwb.
    12,    // .b.wwb.
    17,    // bb.wwb.
    -4,    // wb.wwb.
    21,    // .w.wwb.
    -15,   // bw.wwb.
    -1,    // ww.wwb.
    -5,    // ..bwwb.
    37,    // b.bwwb.
    24,    // w.bwwb.
    -39,   // .bbwwb.
    21,    // bbbwwb.
    9,     // wbbwwb.
    7,     // .wbwwb.
    14,    // bwbwwb.
    -3,    // wwbwwb.
    19,    // ..wwwb.
    -26,   // b.wwwb.
    6,     // w.wwwb.
    29,    // .bwwwb.
    -35,   // bbwwwb.
    1,     // wbwwwb.
    -16,   // .wwwwb.
    -30,   // bwwwwb.
    16,    // wwwwwb.
    5,     // .....w.
    27,    // b....w.
    23,    // w....w.
    0,     // .b...w.
    23,    // bb...w.
    14,    // wb...w.
    -12,   // .w...w.
    -15,   // bw...w.
    -17,   // ww...w.
    -16,   // ..b..w.
    29,    // b.b..w.
    -4,    // w.b..w.
    -10,   // .bb..w.
    -6,    // bbb..w.
    -25,   // wbb..w.
    12,    // .wb..w.
    27,    // bwb..w.
    -7,    // wwb..w.
    33,    // ..w..w.
    3,     // b.w..w.
    -14,   // w.w..w.
    48,    // .bw..w.
    13,    // bbw..w.
    -16,   // wbw..w.
    -13,   // .ww..w.
    -10,   // bww..w.
    2,     // www..w.
    -13,   // ...b.w.
    -1,    // b..b.w.
    -16,   // w..b.w.
    37,    // .b.b.w.
    15,    // bb.b.w.
    37,    // wb.b.w.
    -2,    // .w.b.w.
    -10,   // bw.b.w.
    13,    // ww.b.w.
    14,    // ..bb.w.
    6,     // b.bb.w.
    11,    // w.bb.w.
    55,    // .bbb.w.
    -6,    // bbbb.w.
    -10,   // wbbb.w.
    -12,   // .wbb.w.
    -5,    // bwbb.w.
    -49,   // wwbb.w.
    21,    // ..wb.w.
    -6,    // b.wb.w.
    10,    // w.wb.w.
    11,    // .bwb.w.
    -4,    // bbwb.w.
    -6,    // wbwb.w.
    -9,    // .wwb.w.
    14,    // bwwb.w.
    19,    // wwwb.w.
    -12,   // ...w.w.
    2,     // b..w.w.
    31,    // w..w.w.
    -37,   // .b.w.w.
    -10,   // bb.w.w.
    4,     // wb.w.w.
    8,     // .w.w.w.
    19,    // bw.w.w.
    1,     // ww.w.w.
    -1,    // ..bw.w.
    -19,   // b.bw.w.
    4,     // w.bw.w.
    1,     // .bbw.w.
    14,    // bbbw.w.
    -15,   // wbbw.w.
    40,    // .wbw.w.
    6,     // bwbw.w.
    13,    // wwbw.w.
    -42,   // ..ww.w.
    15,    // b.ww.w.
    -31,   // w.ww.w.
    21,    // .bww.w.
    13,    // bbww.w.
    7,     // wbww.w.
    -12,   // .www.w.
    10,    // bwww.w.
    5,     // wwww.w.
    -21,   // ....bw.
    16,    // b...bw.
    -27,   // w...bw.
    -48,   // .b..bw.
    3,     // bb..bw.
    -34,   // wb..bw.
    12,    // .w..bw.
    5,     // bw..bw.
    -13,   // ww..bw.
    1,     // ..b.bw.
    -9,    // b.b.bw.
    -7,    // w.b.bw.
    -4,    // .bb.bw.
    37,    // bbb.bw.
    20,    // wbb.bw.
    -18,   // .wb.bw.
    3,     // bwb.bw.
    4,     // wwb.bw.
    12,    // ..w.bw.
    -9,    // b.w.bw.
    1,     // w.w.bw.
    0,     // .bw.bw.
    -8,    // bbw.bw.
    -6,    // wbw.bw.
    14,    // .ww.bw.
    -4,    // bww.bw.
    -40,   // www.bw.
    10,    // ...bbw.
    -12,   // b..bbw.
    -40,   // w..bbw.
    -21,   // .b.bbw.
    1,     // bb.bbw.
    15,    // wb.bbw.
    -12,   // .w.bbw.
    4,     // bw.bbw.
    -17,   // ww.bbw.
    -19,   // ..bbbw.
    -6,    // b.bbbw.
    26,    // w.bbbw.
    16,    // .bbbbw.
    -16,   // bbbbbw.
    30,    // wbbbbw.
    -29,   // .wbbbw.
    -1,    // bwbbbw.
    35,    // wwbbbw.
    5,     // ..wbbw.
    -24,   // b.wbbw.
    -37,   // w.wbbw.
    -7,    // .bwbbw.
    3,     // bbwbbw.
    -14,   // wbwbbw.
    39,    // .wwbbw.
    -9,    // bwwbbw.
    -21,   // wwwbbw.
    25,    // ...wbw.
    -33,   // b..wbw.
    1,     // w..wbw.
    -11,   // .b.wbw.
    8,     // bb.wbw.
    28,    // wb.wbw.
    40,    // .w.wbw.
    -26,   // bw.wbw.
    28,    // ww.wbw.
    11,    // ..bwbw.
    -25,   // b.bwbw.
    -1,    // w.bwbw.
    32,    // .bbwbw.
    -23,   // bbbwbw.
    -27,   // wbbwbw.
    -33,   // .wbwbw.
    -30,   // bwbwbw.
    28,    // wwbwbw.
    13,    // ..wwbw.
    10,    // b.wwbw.
    -22,   // w.wwbw.
    7,     // .bwwbw.
    23,    // bbwwbw.
    -8,    // wbwwbw.
    -10,   // .wwwbw.
    4,     // bwwwbw.
    9,     // wwwwbw.
    20,    // ....ww.
    29,    // b...ww.
    -18,   // w...ww.
    10,    // .b..ww.
    40,    // bb..ww.
    -16,   // wb..ww.
    -13,   // .w..ww.
    8,     // bw..ww.
    13,    // ww..ww.
    2,     // ..b.ww.
    23,    // b.b.ww.
    -10,   // w.b.ww.
    0,     // .bb.ww.
    2,     // bbb.ww.
    22,    // wbb.ww.
    14,    // .wb.ww.
    18,    // bwb.ww.
    -30,   // wwb.ww.
    -12,   // ..w.ww.
    5,     // b.w.ww.
    3,     // w.w.ww.
    4,     // .bw.ww.
    3,     // bbw.ww.
    24,    // wbw.ww.
    38,    // .ww.ww.
    1,     // bww.ww.
    -5,    // www.ww.
    -21,   // ...bww.
    19,    // b..bww.
    -19,   // w..bww.
    -1,    // .b.bww.
    -29,   // bb.bww.
    -12,   // wb.bww.
    -9,    // .w.bww.
    -9,    // bw.bww.
    -2,    // ww.bww.
    -8,    // ..bbww.
    -22,   // b.bbww.
    -10,   // w.bbww.
    16,    // .bbbww.
    30,    // bbbbww.
    13,    // wbbbww.
    39,    // .wbbww.
    -8,    // bwbbww.
    -4,    // wwbbww.
    4,     // ..wbww.
    -5,    // b.wbww.
    -5,    // w.wbww.
    -32,   // .bwbww.
    6,     // bbwbww.
    -10,   // wbwbww.
    21,    // .wwbww.
    20,    // bwwbww.
    -11,   // wwwbww.
    -20,   // ...www.
    27,    // b..www.
    -20,   // w..www.
    -55,   // .b.www.
    -30,   // bb.www.
    -9,    // wb.www.
    -12,   // .w.www.
    -15,   // bw.www.
    -8,    // ww.www.
    -6,    // ..bwww.
    -39,   // b.bwww.
    23,    // w.bwww.
    -16,   // .bbwww.
    25,    // bbbwww.
    29,    // wbbwww.
    -10,   // .wbwww.
    18,    // bwbwww.
    -6,    // wwbwww.
    -42,   // ..wwww.
    -18,   // b.wwww.
    17,    // w.wwww.
    -16,   // .bwwww.
    24,    // bbwwww.
    46,    // wbwwww.
    -30,   // .wwwww.
    -16,   // bwwwww.
    -35,   // wwwwww.
    13,    // ......b
    10,    // b.....b
    0,     // w.....b
    -23,   // .b....b
    32,    // bb....b
    10,    // wb....b
    27,    // .w....b
    28,    // bw....b
    -27,   // ww....b
    -17,   // ..b...b
    -20,   // b.b...b
    9,     // w.b...b
    18,    // .bb...b
    -17,   // bbb...b
    -18,   // wbb...b
    16,    // .wb...b
    44,    // bwb...b
    -14,   // wwb...b
    -18,   // ..w...b
    -7,    // b.w...b
    5,     // w.w...b
    27,    // .bw...b
    4,     // bbw...b
    2,     // wbw...b
    29,    // .ww...b
    -23,   // bww...b
    -30,   // www...b
    -1,    // ...b..b
    34,    // b..b..b
    35,    // w..b..b
    -31,   // .b.b..b
    -33,   // bb.b..b
    8,     // wb.b..b
    -1,    // .w.b..b
    21,    // bw.b..b
    25,    // ww.b..b
    -20,   // ..bb..b
    -15,   // b.bb..b
    -21,   // w.bb..b
    20,    // .bbb..b
    -24,   // bbbb..b
    14,    // wbbb..b
    -12,   // .wbb..b
    -8,    // bwbb..b
    10,    // wwbb..b
    1,     // ..wb..b
    6,     // b.wb..b
    6,     // w.wb..b
    -1,    // .bwb..b
    -10,   // bbwb..b
    -36,   // wbwb..b
    19,    // .wwb..b
    0,     // bwwb..b
    -23,   // wwwb..b
    26,    // ...w..b
    -7,    // b..w..b
    -35,   // w..w..b
    16,    // .b.w..b
    -34,   // bb.w..b
    11,    // wb.w..b
    2,     // .w.w..b
    18,    // bw.w..b
    23,    // ww.w..b
    18,    // ..bw..b
    8,     // b.bw..b
    -7,    // w.bw..b
    19,    // .bbw..b
    8,     // bbbw..b
    1,     // wbbw..b
    -33,   // .wbw..b
    -7,    // bwbw..b
    -23,   // wwbw..b
    4,     // ..ww..b
    -19,   // b.ww..b
    34,    // w.ww..b
    40,    // .bww..b
    22,    // bbww..b
    41,    // wbww..b
    27,    // .www..b
    20,    // bwww..b
    29,    // wwww..b
    -23,   // ....b.b
    -20,   // b...b.b
    -5,    // w...b.b
    14,    // .b..b.b
    4,     // bb..b.b
    -25,   // wb..b.b
    29,    // .w..b.b
    6,     // bw..b.b
    -23,   // ww..b.b
    -33,   // ..b.b.b
    27,    // b.b.b.b
    2,     // w.b.b.b
    -3,    // .bb.b.b
    8,     // bbb.b.b
    10,    // wbb.b.b
    -9,    // .wb.b.b
    24,    // bwb.b.b
    -11,   // wwb.b.b
    -6,    // ..w.b.b
    46,    // b.w.b.b
    0,     // w.w.b.b
    -1,    // .bw.b.b
    -10,   // bbw.b.b
    -6,    // wbw.b.b
    23,    // .ww.b.b
    -24,   // bww.b.b
    32,    // www.b.b
    52,    // ...bb.b
    -15,   // b..bb.b
    -34,   // w..bb.b
    31,    // .b.bb.b
    -4,    // bb.bb.b
    21,    // wb.bb.b
    6,     // .w.bb.b
    -16,   // bw.bb.b
    -16,   // ww.bb.b
    -7,    // ..bbb.b
    13,    // b.bbb.b
    15,    // w.bbb.b
    -17,   // .bbbb.b
    16,    // bbbbb.b
    0,     // wbbbb.b
    -6,    // .wbbb.b
    -2,    // bwbbb.b
    24,    // wwbbb.b
    15,    // ..wbb.b
    7,     // b.wbb.b
    8,     // w.wbb.b
    22,    // .bwbb.b
    17,    // bbwbb.b
    42,    // wbwbb.b
    -22,   // .wwbb.b
    -36,   // bwwbb.b
    -19,   // wwwbb.b
    -38,   // ...wb.b
    8,     // b..wb.b
    -6,    // w..wb.b
    -10,   // .b.wb.b
    -4,    // bb.wb.b
    -8,    // wb.wb.b
    -19,   // .w.wb.b
    -12,   // bw.wb.b
    21,    // ww.wb.b
    17,    // ..bwb.b
    0,     // b.bwb.b
    7,     // w.bwb.b
    5,     // .bbwb.b
    6,     // bbbwb.b
    16,    // wbbwb.b
    -25,   // .wbwb.b
    -4,    // bwbwb.b
    -34,   // wwbwb.b
    9,     // ..wwb.b
    10,    // b.wwb.b
    -8,    // w.wwb.b
    37,    // .bwwb.b
    13,    // bbwwb.b
    41,    // wbwwb.b
    -39,   // .wwwb.b
    15,    // bwwwb.b
    -5,    // wwwwb.b
    11,    // ....w.b
    -7,    // b...w.b
    -9,    // w...w.b
    4,     // .b..w.b
    -3,    // bb..w.b
    26,    // wb..w.b
    3,     // .w..w.b
    10,    // bw..w.b
    32,    // ww..w.b
    -35,   // ..b.w.b
    46,    // b.b.w.b
    0,     // w.b.w.b
    10,    // .bb.w.b
    48,    // bbb.w.b
    -34,   // wbb.w.b
    -9,    // .wb.w.b
    -15,   // bwb.w.b
    26,    // wwb.w.b
    16,    // ..w.w.b
    -11,   // b.w.w.b
    -2,    // w.w.w.b
    7,     // .bw.w.b
    -6,    // bbw.w.b
    31,    // wbw.w.b
    5,     // .ww.w.b
    -13,   // bww.w.b
    -21,   // www.w.b
    -18,   // ...bw.b
    6,     // b..bw.b
    7,     // w..bw.b
    -4,    // .b.bw.b
    -34,   // bb.bw.b
    -16,   // wb.bw.b
    -6,    // .w.bw.b
    -7,    // bw.bw.b
    -9,    // ww.bw.b
    -1,    // ..bbw.b
    7,     // b.bbw.b
    -2,    // w.bbw.b
    -23,   // .bbbw.b
    -5,    // bbbbw.b
    -12,   // wbbbw.b
    -24,   // .wbbw.b
    7,     // bwbbw.b
    -11,   // wwbbw.b
    -25,   // ..wbw.b
    24,    // b.wbw.b
    -7,    // w.wbw.b
    1,     // .bwbw.b
    29,    // bbwbw.b
    21,    // wbwbw.b
    -5,    // .wwbw.b
    6,     // bwwbw.b
    -19,   // wwwbw.b
    -16,   // ...ww.b
    -19,   // b..ww.b
    21,    // w..ww.b
    -11,   // .b.ww.b
    8,     // bb.ww.b
    9,     // wb.ww.b
    15,    // .w.ww.b
    1,     // bw.ww.b
    -10,   // ww.ww.b
    19,    // ..bww.b
    10,    // b.bww.b
    2,     // w.bww.b
    10,    // .bbww.b
    -5,    // bbbww.b
    -23,   // wbbww.b
    10,    // .wbww.b
    27,    // bwbww.b
    49,    // wwbww.b
    -16,   // ..www.b
    3,     // b.www.b
    -15,   // w.www.b
    -26,   // .bwww.b
    3,     // bbwww.b
    -7,    // wbwww.b
    -18,   // .wwww.b
    61,    // bwwww.b
    -2,    // wwwww.b
    8,     // .....bb
    32,    // b....bb
    27,    // w....bb
    17,    // .b...bb
    9,     // bb...bb
    -23,   // wb...bb
    23,    // .w...bb
    37,    // bw...bb
    0,     // ww...bb
    -8,    // ..b..bb
    4,     // b.b..bb
    -32,   // w.b..bb
    -13,   // .bb..bb
    -5,    // bbb..bb
    -2,    // wbb..bb
    3,     // .wb..bb
    -7,    // bwb..bb
    35,    // wwb..bb
    7,     // ..w..bb
    -3,    // b.w..bb
    23,    // w.w..bb
    13,    // .bw..bb
    3,     // bbw..bb
    38,    // wbw..bb
    40,    // .ww..bb
    16,    // bww..bb
    -7,    // www..bb
    38,    // ...b.bb
    -33,   // b..b.bb
    -23,   // w..b.bb
    -1,    // .b.b.bb
    -2,    // bb.b.bb
    -5,    // wb.b.bb
    15,    // .w.b.bb
    0,     // bw.b.bb
    7,     // ww.b.bb
    8,     // ..bb.bb
    -4,    // b.bb.bb
    10,    // w.bb.bb
    8,     // .bbb.bb
    12,    // bbbb.bb
    -22,   // wbbb.bb
    1,     // .wbb.bb
    -26,   // bwbb.bb
    -20,   // wwbb.bb
    -16,   // ..wb.bb
    -34,   // b.wb.bb
    -21,   // w.wb.bb
    -28,   // .bwb.bb
    32,    // bbwb.bb
    -12,   // wbwb.bb
    -29,   // .wwb.bb
    8,     // bwwb.bb
    17,    // wwwb.bb
    9,     // ...w.bb
    -34,   // b..w.bb
    -25,   // w..w.bb
    -13,   // .b.w.bb
    37,    // bb.w.bb
    -30,   // wb.w.bb
    -10,   // .w.w.bb
    35,    // bw.w.bb
    -7,    // ww.w.bb
    -32,   // ..bw.bb
    -4,    // b.bw.bb
    9,     // w.bw.bb
    2,     // .bbw.bb
    7,     // bbbw.bb
    -18,   // wbbw.bb
    8,     // .wbw.bb
    1,     // bwbw.bb
    -45,   // wwbw.bb
    23,    // ..ww.bb
    8,     // b.ww.bb
    16,    // w.ww.bb
    17,    // .bww.bb
    24,    // bbww.bb
    19,    // wbww.bb
    -30,   // .www.bb
    41,    // bwww.bb
    -1,    // wwww.bb
    86,    // ....bbb
    -17,   // b...bbb
    30,    // w...bbb
    -2,    // .b..bbb
    -5,    // bb..bbb
    11,    // wb..bbb
    -6,    // .w..bbb
    -14,   // bw..bbb
    7,     // ww..bbb
    26,    // ..b.bbb
    8,     // b.b.bbb
    21,    // w.b.bbb
    5,     // .bb.bbb
    -11,   // bbb.bbb
    -6,    // wbb.bbb
    37,    // .wb.bbb
    3,     // bwb.bbb
    29,    // wwb.bbb
    -22,   // ..w.bbb
    48,    // b.w.bbb
    -32,   // w.w.bbb
    40,    // .bw.bbb
    -17,   // bbw.bbb
    5,     // wbw.bbb
    2,     // .ww.bbb
    -5,    // bww.bbb
    0,     // www.bbb
    65,    // ...bbbb
    -24,   // b..bbbb
    -29,   // w..bbbb
    -5,    // .b.bbbb
    12,    // bb.bbbb
    -20,   // wb.bbbb
    -6,    // .w.bbbb
    17,    // bw.bbbb
    1,     // ww.bbbb
    27,    // ..bbbbb
    16,    // b.bbbbb
    2,     // w.bbbbb
    35,    // .bbbbbb
    16,    // bbbbbbb
    -17,   // wbbbbbb
    -16,   // .wbbbbb
    6,     // bwbbbbb
    -26,   // wwbbbbb
    -10,   // ..wbbbb
    -5,    // b.wbbbb
    5,     // w.wbbbb
    -9,    // .bwbbbb
    12,    // bbwbbbb
    17,    // wbwbbbb
    30,    // .wwbbbb
    -14,   // bwwbbbb
    -33,   // wwwbbbb
    3,     // ...wbbb
    8,     // b..wbbb
    23,    // w..wbbb
    -19,   // .b.wbbb
    7,     // bb.wbbb
    5,     // wb.wbbb
    14,    // .w.wbbb
    9,     // bw.wbbb
    -17,   // ww.wbbb
    26,    // ..bwbbb
    6,     // b.bwbbb
    19,    // w.bwbbb
    11,    // .bbwbbb
    13,    // bbbwbbb
    -5,    // wbbwbbb
    -23,   // .wbwbbb
    -14,   // bwbwbbb
    11,    // wwbwbbb
    -41,   // ..wwbbb
    -5,    // b.wwbbb
    19,    // w.wwbbb
    21,    // .bwwbbb
    -4,    // bbwwbbb
    -2,    // wbwwbbb
    25,    // .wwwbbb
    41,    // bwwwbbb
    33,    // wwwwbbb
    -39,   // ....wbb
    4,     // b...wbb
    14,    // w...wbb
    7,     // .b..wbb
    3,     // bb..wbb
    -4,    // wb..wbb
    13,    // .w..wbb
    43,    // bw..wbb
    -35,   // ww..wbb
    -54,   // ..b.wbb
    -10,   // b.b.wbb
    -26,   // w.b.wbb
    30,    // .bb.wbb
    -17,   // bbb.wbb
    3,     // wbb.wbb
    -8,    // .wb.wbb
    -3,    // bwb.wbb
    0,     // wwb.wbb
    -22,   // ..w.wbb
    -6,    // b.w.wbb
    11,    // w.w.wbb
    -4,    // .bw.wbb
    -7,    // bbw.wbb
    31,    // wbw.wbb
    3,     // .ww.wbb
    -34,   // bww.wbb
    -29,   // www.wbb
    -18,   // ...bwbb
    -10,   // b..bwbb
    23,    // w..bwbb
    -13,   // .b.bwbb
    32,    // bb.bwbb
    17,    // wb.bwbb
    -4,    // .w.bwbb
    -9,    // bw.bwbb
    45,    // ww.bwbb
    36,    // ..bbwbb
    17,    // b.bbwbb
    -49,   // w.bbwbb
    6,     // .bbbwbb
    12,    // bbbbwbb
    -4,    // wbbbwbb
    3,     // .wbbwbb
    18,    // bwbbwbb
    3,     // wwbbwbb
    -6,    // ..wbwbb
    29,    // b.wbwbb
    34,    // w.wbwbb
    -28,   // .bwbwbb
    -31,   // bbwbwbb
    -14,   // wbwbwbb
    6,     // .wwbwbb
    -34,   // bwwbwbb
    -11,   // wwwbwbb
    0,     // ...wwbb
    22,    // b..wwbb
    -10,   // w..wwbb
    49,    // .b.wwbb
    24,    // bb.wwbb
    13,    // wb.wwbb
    13,    // .w.wwbb
    -7,    // bw.wwbb
    20,    // ww.wwbb
    9,     // ..bwwbb
    13,    // b.bwwbb
    11,    // w.bwwbb
    4,     // .bbwwbb
    -4,    // bbbwwbb
    15,    // wbbwwbb
    23,    // .wbwwbb
    -27,   // bwbwwbb
    -3,    // wwbwwbb
    0,     // ..wwwbb
    3,     // b.wwwbb
    -24,   // w.wwwbb
    -35,   // .bwwwbb
    12,    // bbwwwbb
    2,     // wbwwwbb
    24,    // .wwwwbb
    -14,   // bwwwwbb
    26,    // wwwwwbb
    -13,   // .....wb
    28,    // b....wb
    -10,   // w....wb
    -14,   // .b...wb
    37,    // bb...wb
    0,     // wb...wb
    -15,   // .w...wb
    6,     // bw...wb
    23,    // ww...wb
    8,     // ..b..wb
    6,     // b.b..wb
    -26,   // w.b..wb
    16,    // .bb..wb
    -14,   // bbb..wb
    32,    // wbb..wb
    5,     // .wb..wb
    -10,   // bwb..wb
    4,     // wwb..wb
    -3,    // ..w..wb
    10,    // b.w..wb
    25,    // w.w..wb
    34,    // .bw..wb
    43,    // bbw..wb
    -1,    // wbw..wb
    8,     // .ww..wb
    -18,   // bww..wb
    -11,   // www..wb
    -16,   // ...b.wb
    21,    // b..b.wb
    -11,   // w..b.wb
    -4,    // .b.b.wb
    0,     // bb.b.wb
    16,    // wb.b.wb
    -10,   // .w.b.wb
    9,     // bw.b.wb
    30,    // ww.b.wb
    -27,   // ..bb.wb
    -16,   // b.bb.wb
    -9,    // w.bb.wb
    9,     // .bbb.wb
    17,    // bbbb.wb
    5,     // wbbb.wb
    4,     // .wbb.wb
    -12,   // bwbb.wb
    -13,   // wwbb.wb
    -50,   // ..wb.wb
    -7,    // b.wb.wb
    8,     // w.wb.wb
    -28,   // .bwb.wb
    -9,    // bbwb.wb
    20,    // wbwb.wb
    -9,    // .wwb.wb
    43,    // bwwb.wb
    -5,    // wwwb.wb
    -20,   // ...w.wb
    18,    // b..w.wb
    -8,    // w..w.wb
    -37,   // .b.w.wb
    35,    // bb.w.wb
    -16,   // wb.w.wb
    19,    // .w.w.wb
    -3,    // bw.w.wb
    5,     // ww.w.wb
    3,     // ..bw.wb
    -12,   // b.bw.wb
    16,    // w.bw.wb
    12,    // .bbw.wb
    9,     // bbbw.wb
    -14,   // wbbw.wb
    -26,   // .wbw.wb
    20,    // bwbw.wb
    -17,   // wwbw.wb
    2,     // ..ww.wb
    1,     // b.ww.wb
    -21,   // w.ww.wb
    -15,   // .bww.wb
    -7,    // bbww.wb
    -27,   // wbww.wb
    -15,   // .www.wb
    -32,   // bwww.wb
    20,    // wwww.wb
    -17,   // ....bwb
    44,    // b...bwb
    -2,    // w...bwb
    16,    // .b..bwb
    -7,    // bb..bwb
    1,     // wb..bwb
    27,    // .w..bwb
    -10,   // bw..bwb
    -38,   // ww..bwb
    -3,    // ..b.bwb
    24,    // b.b.bwb
    -31,   // w.b.bwb
    -24,   // .bb.bwb
    3,     // bbb.bwb
    -28,   // wbb.bwb
    3,     // .wb.bwb
    -47,   // bwb.bwb
    -31,   // wwb.bwb
    6,     // ..w.bwb
    -15,   // b.w.bwb
    6,     // w.w.bwb
    6,     // .bw.bwb
    -3,    // bbw.bwb
    0,     // wbw.bwb
    18,    // .ww.bwb
    -30,   // bww.bwb
    -5,    // www.bwb
    -10,   // ...bbwb
    -8,    // b..bbwb
    -41,   // w..bbwb
    -7,    // .b.bbwb
    -26,   // bb.bbwb
    27,    // wb.bbwb
    -5,    // .w.bbwb
    -12,   // bw.bbwb
    -19,   // ww.bbwb
    -20,   // ..bbbwb
    -2,    // b.bbbwb
    7,     // w.bbbwb
    -46,   // .bbbbwb
    6,     // bbbbbwb
    28,    // wbbbbwb
    -1,    // .wbbbwb
    16,    // bwbbbwb
    -2,    // wwbbbwb
    15,    // ..wbbwb
    7,     // b.wbbwb
    -41,   // w.wbbwb
    8,     // .bwbbwb
    18,    // bbwbbwb
    -22,   // wbwbbwb
    -8,    // .wwbbwb
    -35,   // bwwbbwb
    2,     // wwwbbwb
    2,     // ...wbwb
    -7,    // b..wbwb
    36,    // w..wbwb
    6,     // .b.wbwb
    1,     // bb.wbwb
    -20,   // wb.wbwb
    6,     // .w.wbwb
    20,    // bw.wbwb
    12,    // ww.wbwb
    20,    // ..bwbwb
    -4,    // b.bwbwb
    -21,   // w.bwbwb
    10,    // .bbwbwb
    -14,   // bbbwbwb
    -7,    // wbbwbwb
    -30,   // .wbwbwb
    -23,   // bwbwbwb
    14,    // wwbwbwb
    -17,   // ..wwbwb
    27,    // b.wwbwb
    -42,   // w.wwbwb
    14,    // .bwwbwb
    -27,   // bbwwbwb
    22,    // wbwwbwb
    18,    // .wwwbwb
    -8,    // bwwwbwb
    -17,   // wwwwbwb
    38,    // ....wwb
    -23,   // b...wwb
    18,    // w...wwb
    25,    // .b..wwb
    16,    // bb..wwb
    -32,   // wb..wwb
    -10,   // .w..wwb
    -18,   // bw..wwb
    2,     // ww..wwb
    -9,    // ..b.wwb
    -24,   // b.b.wwb
    34,    // w.b.wwb
    -22,   // .bb.wwb
    -5,    // bbb.wwb
    0,     // wbb.wwb
    -4,    // .wb.wwb
    -30,   // bwb.wwb
    -3,    // wwb.wwb
    -29,   // ..w.wwb
    -13,   // b.w.wwb
    -10,   // w.w.wwb
    -20,   // .bw.wwb
    -34,   // bbw.wwb
    28,    // wbw.wwb
    1,     // .ww.wwb
    -6,    // bww.wwb
    6,     // www.wwb
    11,    // ...bwwb
    0,     // b..bwwb
    -1,    // w..bwwb
    15,    // .b.bwwb
    8,     // bb.bwwb
    14,    // wb.bwwb
    14,    // .w.bwwb
    43,    // bw.bwwb
    18,    // ww.bwwb
    -22,   // ..bbwwb
    -36,   // b.bbwwb
    23,    // w.bbwwb
    -29,   // .bbbwwb
    -14,   // bbbbwwb
    15,    // wbbbwwb
    -9,    // .wbbwwb
    -35,   // bwbbwwb
    -15,   // wwbbwwb
    3,     // ..wbwwb
    6,     // b.wbwwb
    -16,   // w.wbwwb
    27,    // .bwbwwb
    -34,   // bbwbwwb
    7,     // wbwbwwb
    20,    // .wwbwwb
    -10,   // bwwbwwb
    5,     // wwwbwwb
    24,    // ...wwwb
    20,    // b..wwwb
    -14,   // w..wwwb
    10,    // .b.wwwb
    41,    // bb.wwwb
    -5,    // wb.wwwb
    10,    // .w.wwwb
    -32,   // bw.wwwb
    22,    // ww.wwwb
    -27,   // ..bwwwb
    15,    // b.bwwwb
    12,    // w.bwwwb
    -13,   // .bbwwwb
    41,    // bbbwwwb
    -15,   // wbbwwwb
    4,     // .wbwwwb
    -8,    // bwbwwwb
    4,     // wwbwwwb
    -38,   // ..wwwwb
    61,    // b.wwwwb
    0,     // w.wwwwb
    -30,   // .bwwwwb
    -14,   // bbwwwwb
    -28,   // wbwwwwb
    -16,   // .wwwwwb
    27,    // bwwwwwb
    17,    // wwwwwwb
    -13,   // ......w
    0,     // b.....w
    -10,   // w.....w
    -27,   // .b....w
    27,    // bb....w
    -28,   // wb....w
    23,    // .w....w
    -10,   // bw....w
    -32,   // ww....w
    18,    // ..b...w
    -5,    // b.b...w
    7,     // w.b...w
    -29,   // .bb...w
    30,    // bbb...w
    23,    // wbb...w
    -27,   // .wb...w
    -2,    // bwb...w
    -4,    // wwb...w
    17,    // ..w...w
    -9,    // b.w...w
    20,    // w.w...w
    -16,   // .bw...w
    14,    // bbw...w
    -44,   // wbw...w
    -18,   // .ww...w
    18,    // bww...w
    17,    // www...w
    -26,   // ...b..w
    35,    // b..b..w
    7,     // w..b..w
    -2,    // .b.b..w
    -23,   // bb.b..w
    -18,   // wb.b..w
    -16,   // .w.b..w
    -11,   // bw.b..w
    34,    // ww.b..w
    -4,    // ..bb..w
    -34,   // b.bb..w
    19,    // w.bb..w
    -27,   // .bbb..w
    -29,   // bbbb..w
    -20,   // wbbb..w
    -40,   // .wbb..w
    -41,   // bwbb..w
    -22,   // wwbb..w
    -18,   // ..wb..w
    7,     // b.wb..w
    -8,    // w.wb..w
    33,    // .bwb..w
    23,    // bbwb..w
    7,     // wbwb..w
    -19,   // .wwb..w
    -1,    // bwwb..w
    -8,    // wwwb..w
    1,     // ...w..w
    -35,   // b..w..w
    -34,   // w..w..w
    1,     // .b.w..w
    -25,   // bb.w..w
    -21,   // wb.w..w
    31,    // .w.w..w
    -8,    // bw.w..w
    33,    // ww.w..w
    -1,    // ..bw..w
    -6,    // b.bw..w
    -6,    // w.bw..w
    -19,   // .bbw..w
    23,    // bbbw..w
    0,     // wbbw..w
    1,     // .wbw..w
    36,    // bwbw..w
    10,    // wwbw..w
    20,    // ..ww..w
    21,    // b.ww..w
    15,    // w.ww..w
    12,    // .bww..w
    -10,   // bbww..w
    8,     // wbww..w
    -20,   // .www..w
    -14,   // bwww..w
    24,    // wwww..w
    -11,   // ....b.w
    9,     // b...b.w
    7,     // w...b.w
    -3,    // .b..b.w
    -32,   // bb..b.w
    -10,   // wb..b.w
    -4,    // .w..b.w
    -26,   // bw..b.w
    3,     // ww..b.w
    -16,   // ..b.b.w
    2,     // b.b.b.w
    11,    // w.b.b.w
    -5,    // .bb.b.w
    21,    // bbb.b.w
    13,    // wbb.b.w
    -7,    // .wb.b.w
    -31,   // bwb.b.w
    6,     // wwb.b.w
    35,    // ..w.b.w
    0,     // b.w.b.w
    -46,   // w.w.b.w
    9,     // .bw.b.w
    -26,   // bbw.b.w
    15,    // wbw.b.w
    -10,   // .ww.b.w
    34,    // bww.b.w
    -48,   // www.b.w
    16,    // ...bb.w
    -21,   // b..bb.w
    19,    // w..bb.w
    -15,   // .b.bb.w
    10,    // bb.bb.w
    -1,    // wb.bb.w
    11,    // .w.bb.w
    -9,    // bw.bb.w
    -8,    // ww.bb.w
    16,    // ..bbb.w
    15,    // b.bbb.w
    -3,    // w.bbb.w
    18,    // .bbbb.w
    2,     // bbbbb.w
    -61,   // wbbbb.w
    26,    // .wbbb.w
    7,     // bwbbb.w
    -3,    // wwbbb.w
    -19,   // ..wbb.w
    -2,    // b.wbb.w
    -10,   // w.wbb.w
    -10,   // .bwbb.w
    -49,   // bbwbb.w
    -27,   // wbwbb.w
    -10,   // .wwbb.w
    23,    // bwwbb.w
    5,     // wwwbb.w
    18,    // ...wb.w
    -7,    // b..wb.w
    -6,    // w..wb.w
    6,     // .b.wb.w
    9,     // bb.wb.w
    7,     // wb.wb.w
    4,     // .w.wb.w
    16,    // bw.wb.w
    34,    // ww.wb.w
    25,    // ..bwb.w
    7,     // b.bwb.w
    -24,   // w.bwb.w
    5,     // .bbwb.w
    19,    // bbbwb.w
    -6,    // wbbwb.w
    -1,    // .wbwb.w
    -21,   // bwbwb.w
    -29,   // wwbwb.w
    1,     // ..wwb.w
    2,     // b.wwb.w
    -7,    // w.wwb.w
    24,    // .bwwb.w
    11,    // bbwwb.w
    -7,    // wbwwb.w
    23,    // .wwwb.w
    12,    // bwwwb.w
    5,     // wwwwb.w
    23,    // ....w.w
    5,     // b...w.w
    20,    // w...w.w
    -29,   // .b..w.w
    23,    // bb..w.w
    -6,    // wb..w.w
    -14,   // .w..w.w
    25,    // bw..w.w
    -4,    // ww..w.w
    6,     // ..b.w.w
    0,     // b.b.w.w
    -46,   // w.b.w.w
    -23,   // .bb.w.w
    -32,   // bbb.w.w
    24,    // wbb.w.w
    1,     // .wb.w.w
    6,     // bwb.w.w
    10,    // wwb.w.w
    33,    // ..w.w.w
    -2,    // b.w.w.w
    -27,   // w.w.w.w
    9,     // .bw.w.w
    11,    // bbw.w.w
    -24,   // wbw.w.w
    3,     // .ww.w.w
    -10,   // bww.w.w
    -8,    // www.w.w
    38,    // ...bw.w
    6,     // b..bw.w
    -8,    // w..bw.w
    19,    // .b.bw.w
    -21,   // bb.bw.w
    12,    // wb.bw.w
    10,    // .w.bw.w
    8,     // bw.bw.w
    4,     // ww.bw.w
    -9,    // ..bbw.w
    8,     // b.bbw.w
    -10,   // w.bbw.w
    39,    // .bbbw.w
    5,     // bbbbw.w
    -15,   // wbbbw.w
    -37,   // .wbbw.w
    -41,   // bwbbw.w
    -13,   // wwbbw.w
    -17,   // ..wbw.w
    -7,    // b.wbw.w
    0,     // w.wbw.w
    25,    // .bwbw.w
    34,    // bbwbw.w
    4,     // wbwbw.w
    -5,    // .wwbw.w
    -16,   // bwwbw.w
    -6,    // wwwbw.w
    -52,   // ...ww.w
    34,    // b..ww.w
    15,    // w..ww.w
    -6,    // .b.ww.w
    16,    // bb.ww.w
    16,    // wb.ww.w
    -31,   // .w.ww.w
    -21,   // bw.ww.w
    4,     // ww.ww.w
    -15,   // ..bww.w
    -8,    // b.bww.w
    -7,    // w.bww.w
    22,    // .bbww.w
    19,    // bbbww.w
    36,    // wbbww.w
    -22,   // .wbww.w
    -42,   // bwbww.w
    -17,   // wwbww.w
    7,     // ..www.w
    -15,   // b.www.w
    -13,   // w.www.w
    6,     // .bwww.w
    -24,   // bbwww.w
    2,     // wbwww.w
    17,    // .wwww.w
    0,     // bwwww.w
    -16,   // wwwww.w
    13,    // .....bw
    10,    // b....bw
    -28,   // w....bw
    15,    // .b...bw
    -23,   // bb...bw
    -6,    // wb...bw
    14,    // .w...bw
    0,     // bw...bw
    -37,   // ww...bw
    3,     // ..b..bw
    -25,   // b.b..bw
    -10,   // w.b..bw
    -8,    // .bb..bw
    11,    // bbb..bw
    18,    // wbb..bw
    -34,   // .wb..bw
    1,     // bwb..bw
    -43,   // wwb..bw
    -8,    // ..w..bw
    26,    // b.w..bw
    -6,    // w.w..bw
    -5,    // .bw..bw
    -4,    // bbw..bw
    10,    // wbw..bw
    -16,   // .ww..bw
    -32,   // bww..bw
    14,    // www..bw
    20,    // ...b.bw
    8,     // b..b.bw
    -18,   // w..b.bw
    -19,   // .b.b.bw
    -5,    // bb.b.bw
    3,     // wb.b.bw
    37,    // .w.b.bw
    16,    // bw.b.bw
    -35,   // ww.b.bw
    -2,    // ..bb.bw
    21,    // b.bb.bw
    -1,    // w.bb.bw
    15,    // .bbb.bw
    -20,   // bbbb.bw
    32,    // wbbb.bw
    15,    // .wbb.bw
    27,    // bwbb.bw
    7,     // wwbb.bw
    -3,    // ..wb.bw
    -16,   // b.wb.bw
    12,    // w.wb.bw
    26,    // .bwb.bw
    17,    // bbwb.bw
    -20,   // wbwb.bw
    -12,   // .wwb.bw
    14,    // bwwb.bw
    -9,    // wwwb.bw
    16,    // ...w.bw
    11,    // b..w.bw
    -21,   // w..w.bw
    10,    // .b.w.bw
    -30,   // bb.w.bw
    -9,    // wb.w.bw
    4,     // .w.w.bw
    -16,   // bw.w.bw
    0,     // ww.w.bw
    50,    // ..bw.bw
    -8,    // b.bw.bw
    7,     // w.bw.bw
    9,     // .bbw.bw
    5,     // bbbw.bw
    -43,   // wbbw.bw
    28,    // .wbw.bw
    -20,   // bwbw.bw
    9,     // wwbw.bw
    27,    // ..ww.bw
    9,     // b.ww.bw
    16,    // w.ww.bw
    -4,    // .bww.bw
    13,    // bbww.bw
    12,    // wbww.bw
    -9,    // .www.bw
    -5,    // bwww.bw
    -17,   // wwww.bw
    -38,   // ....bbw
    -18,   // b...bbw
    23,    // w...bbw
    10,    // .b..bbw
    -2,    // bb..bbw
    18,    // wb..bbw
    -25,   // .w..bbw
    32,    // bw..bbw
    -16,   // ww..bbw
    29,    // ..b.bbw
    10,    // b.b.bbw
    13,    // w.b.bbw
    -1,    // .bb.bbw
    -6,    // bbb.bbw
    6,     // wbb.bbw
    20,    // .wb.bbw
    -28,   // bwb.bbw
    34,    // wwb.bbw
    9,     // ..w.bbw
    -34,   // b.w.bbw
    24,    // w.w.bbw
    4,     // .bw.bbw
    3,     // bbw.bbw
    30,    // wbw.bbw
    22,    // .ww.bbw
    0,     // bww.bbw
    5,     // www.bbw
    -24,   // ...bbbw
    14,    // b..bbbw
    -20,   // w..bbbw
    -10,   // .b.bbbw
    -22,   // bb.bbbw
    32,    // wb.bbbw
    -10,   // .w.bbbw
    5,     // bw.bbbw
    -41,   // ww.bbbw
    38,    // ..bbbbw
    0,     // b.bbbbw
    -61,   // w.bbbbw
    16,    // .bbbbbw
    -17,   // bbbbbbw
    -27,   // wbbbbbw
    30,    // .wbbbbw
    28,    // bwbbbbw
    14,    // wwbbbbw
    27,    // ..wbbbw
    -12,   // b.wbbbw
    -15,   // w.wbbbw
    -4,    // .bwbbbw
    -4,    // bbwbbbw
    8,     // wbwbbbw
    13,    // .wwbbbw
    15,    // bwwbbbw
    -41,   // wwwbbbw
    -11,   // ...wbbw
    1,     // b..wbbw
    0,     // w..wbbw
    -14,   // .b.wbbw
    -18,   // bb.wbbw
    -43,   // wb.wbbw
    -15,   // .w.wbbw
    -14,   // bw.wbbw
    -8,    // ww.wbbw
    -3,    // ..bwbbw
    16,    // b.bwbbw
    -6,    // w.bwbbw
    -20,   // .bbwbbw
    -5,    // bbbwbbw
    10,    // wbbwbbw
    -27,   // .wbwbbw
    -7,    // bwbwbbw
    34,    // wwbwbbw
    22,    // ..wwbbw
    -23,   // b.wwbbw
    36,    // w.wwbbw
    9,     // .bwwbbw
    15,    // bbwwbbw
    35,    // wbwwbbw
    29,    // .wwwbbw
    -15,   // bwwwbbw
    14,    // wwwwbbw
    17,    // ....wbw
    2,     // b...wbw
    -44,   // w...wbw
    -27,   // .b..wbw
    38,    // bb..wbw
    10,    // wb..wbw
    -16,   // .w..wbw
    -1,    // bw..wbw
    7,     // ww..wbw
    -6,    // ..b.wbw
    -6,    // b.b.wbw
    15,    // w.b.wbw
    -18,   // .bb.wbw
    5,     // bbb.wbw
    30,    // wbb.wbw
    -6,    // .wb.wbw
    0,     // bwb.wbw
    3,     // wwb.wbw
    3,     // ..w.wbw
    31,    // b.w.wbw
    -24,   // w.w.wbw
    -3,    // .bw.wbw
    31,    // bbw.wbw
    47,    // wbw.wbw
    24,    // .ww.wbw
    28,    // bww.wbw
    -3,    // www.wbw
    -2,    // ...bwbw
    -36,   // b..bwbw
    7,     // w..bwbw
    -6,    // .b.bwbw
    -12,   // bb.bwbw
    -20,   // wb.bwbw
    -6,    // .w.bwbw
    20,    // bw.bwbw
    -1,    // ww.bwbw
    17,    // ..bbwbw
    42,    // b.bbwbw
    -27,   // w.bbwbw
    -18,   // .bbbwbw
    17,    // bbbbwbw
    8,     // wbbbwbw
    -14,   // .wbbwbw
    -22,   // bwbbwbw
    27,    // wwbbwbw
    -20,   // ..wbwbw
    21,    // b.wbwbw
    4,     // w.wbwbw
    30,    // .bwbwbw
    -14,   // bbwbwbw
    23,    // wbwbwbw
    -10,   // .wwbwbw
    7,     // bwwbwbw
    14,    // wwwbwbw
    10,    // ...wwbw
    41,    // b..wwbw
    8,     // w..wwbw
    5,     // .b.wwbw
    19,    // bb.wwbw
    12,    // wb.wwbw
    7,     // .w.wwbw
    -27,   // bw.wwbw
    26,    // ww.wwbw
    -15,   // ..bwwbw
    41,    // b.bwwbw
    -7,    // w.bwwbw
    8,     // .bbwwbw
    -2,    // bbbwwbw
    35,    // wbbwwbw
    -8,    // .wbwwbw
    22,    // bwbwwbw
    -18,   // wwbwwbw
    20,    // ..wwwbw
    -7,    // b.wwwbw
    2,     // w.wwwbw
    1,     // .bwwwbw
    2,     // bbwwwbw
    -16,   // wbwwwbw
    46,    // .wwwwbw
    -28,   // bwwwwbw
    -6,    // wwwwwbw
    -8,    // .....ww
    -27,   // b....ww
    -32,   // w....ww
    -23,   // .b...ww
    0,     // bb...ww
    -37,   // wb...ww
    -17,   // .w...ww
    23,    // bw...ww
    -9,    // ww...ww
    -7,    // ..b..ww
    -23,   // b.b..ww
    3,     // w.b..ww
    -40,   // .bb..ww
    7,     // bbb..ww
    -16,   // wbb..ww
    -13,   // .wb..ww
    -38,   // bwb..ww
    -3,    // wwb..ww
    8,     // ..w..ww
    32,    // b.w..ww
    -4,    // w.w..ww
    -3,    // .bw..ww
    -35,   // bbw..ww
    7,     // wbw..ww
    13,    // .ww..ww
    2,     // bww..ww
    5,     // www..ww
    -9,    // ...b.ww
    25,    // b..b.ww
    34,    // w..b.ww
    10,    // .b.b.ww
    7,     // bb.b.ww
    -35,   // wb.b.ww
    13,    // .w.b.ww
    30,    // bw.b.ww
    -37,   // ww.b.ww
    -23,   // ..bb.ww
    -16,   // b.bb.ww
    -8,    // w.bb.ww
    30,    // .bbb.ww
    1,     // bbbb.ww
    -41,   // wbbb.ww
    -17,   // .wbb.ww
    -19,   // bwbb.ww
    -24,   // wwbb.ww
    32,    // ..wb.ww
    -9,    // b.wb.ww
    4,     // w.wb.ww
    -8,    // .bwb.ww
    45,    // bbwb.ww
    -1,    // wbwb.ww
    -2,    // .wwb.ww
    18,    // bwwb.ww
    -7,    // wwwb.ww
    -38,   // ...w.ww
    23,    // b..w.ww
    33,    // w..w.ww
    -15,   // .b.w.ww
    -7,    // bb.w.ww
    0,     // wb.w.ww
    1,     // .w.w.ww
    5,     // bw.w.ww
    2,     // ww.w.ww
    16,    // ..bw.ww
    21,    // b.bw.ww
    34,    // w.bw.ww
    29,    // .bbw.ww
    -17,   // bbbw.ww
    -8,    // wbbw.ww
    28,    // .wbw.ww
    12,    // bwbw.ww
    -32,   // wwbw.ww
    -8,    // ..ww.ww
    -10,   // b.ww.ww
    4,     // w.ww.ww
    -1,    // .bww.ww
    20,    // bbww.ww
    26,    // wbww.ww
    -8,    // .www.ww
    22,    // bwww.ww
    -12,   // wwww.ww
    39,    // ....bww
    -14,   // b...bww
    -4,    // w...bww
    -13,   // .b..bww
    35,    // bb..bww
    -43,   // wb..bww
    -7,    // .w..bww
    4,     // bw..bww
    -3,    // ww..bww
    22,    // ..b.bww
    -11,   // b.b.bww
    6,     // w.b.bww
    -3,    // .bb.bww
    29,    // bbb.bww
    34,    // wbb.bww
    4,     // .wb.bww
    -31,   // bwb.bww
    7,     // wwb.bww
    54,    // ..w.bww
    26,    // b.w.bww
    10,    // w.w.bww
    8,     // .bw.bww
    0,     // bbw.bww
    3,     // wbw.bww
    -30,   // .ww.bww
    -3,    // bww.bww
    17,    // www.bww
    0,     // ...bbww
    10,    // b..bbww
    -22,   // w..bbww
    -13,   // .b.bbww
    -20,   // bb.bbww
    7,     // wb.bbww
    -49,   // .w.bbww
    -13,   // bw.bbww
    -24,   // ww.bbww
    0,     // ..bbbww
    24,    // b.bbbww
    -3,    // w.bbbww
    -24,   // .bbbbww
    -26,   // bbbbbww
    14,    // wbbbbww
    35,    // .wbbbww
    -2,    // bwbbbww
    -12,   // wwbbbww
    -9,    // ..wbbww
    -11,   // b.wbbww
    -13,   // w.wbbww
    -23,   // .bwbbww
    3,     // bbwbbww
    27,    // wbwbbww
    -4,    // .wwbbww
    -15,   // bwwbbww
    4,     // wwwbbww
    18,    // ...wbww
    -23,   // b..wbww
    10,    // w..wbww
    4,     // .b.wbww
    -45,   // bb.wbww
    9,     // wb.wbww
    13,    // .w.wbww
    -17,   // bw.wbww
    -32,   // ww.wbww
    6,     // ..bwbww
    -34,   // b.bwbww
    -29,   // w.bwbww
    -6,    // .bbwbww
    11,    // bbbwbww
    34,    // wbbwbww
    28,    // .wbwbww
    14,    // bwbwbww
    31,    // wwbwbww
    -36,   // ..wwbww
    49,    // b.wwbww
    -17,   // w.wwbww
    -3,    // .bwwbww
    -3,    // bbwwbww
    -18,   // wbwwbww
    -6,    // .wwwbww
    4,     // bwwwbww
    -12,   // wwwwbww
    -86,   // ....www
    -30,   // b...www
    17,    // w...www
    6,     // .b..www
    -7,    // bb..www
    14,    // wb..www
    2,     // .w..www
    -11,   // bw..www
    5,     // ww..www
    22,    // ..b.www
    32,    // b.b.www
    -48,   // w.b.www
    -2,    // .bb.www
    0,     // bbb.www
    5,     // wbb.www
    -40,   // .wb.www
    -5,    // bwb.www
    17,    // wwb.www
    -26,   // ..w.www
    -21,   // b.w.www
    -8,    // w.w.www
    -37,   // .bw.www
    -29,   // bbw.www
    -3,    // wbw.www
    -5,    // .ww.www
    6,     // bww.www
    11,    // www.www
    -3,    // ...bwww
    -23,   // b..bwww
    -8,    // w..bwww
    -14,   // .b.bwww
    17,    // bb.bwww
    -9,    // wb.bwww
    19,    // .w.bwww
    -5,    // bw.bwww
    -7,    // ww.bwww
    41,    // ..bbwww
    -19,   // b.bbwww
    5,     // w.bbwww
    -25,   // .bbbwww
    -33,   // bbbbwww
    -41,   // wbbbwww
    -21,   // .wbbwww
    2,     // bwbbwww
    4,     // wwbbwww
    -26,   // ..wbwww
    -19,   // b.wbwww
    -6,    // w.wbwww
    23,    // .bwbwww
    -11,   // bbwbwww
    14,    // wbwbwww
    -11,   // .wwbwww
    5,     // bwwbwww
    -13,   // wwwbwww
    -65,   // ...wwww
    29,    // b..wwww
    24,    // w..wwww
    6,     // .b.wwww
    -1,    // bb.wwww
    -17,   // wb.wwww
    5,     // .w.wwww
    20,    // bw.wwww
    -12,   // ww.wwww
    10,    // ..bwwww
    -5,    // b.bwwww
    5,     // w.bwwww
    -30,   // .bbwwww
    33,    // bbbwwww
    14,    // wbbwwww
    9,     // .wbwwww
    -17,   // bwbwwww
    -12,   // wwbwwww
    -27,   // ..wwwww
    -2,    // b.wwwww
    -16,   // w.wwwww
    16,    // .bwwwww
    26,    // bbwwwww
    -6,    // wbwwwww
    -35,   // .wwwwww
    17,    // bwwwwww
    -16,   // wwwwwww
    -8,    // ccc
    -19,   // cc
    2,     // c
    0,     // ttt
    15,    // tt
    -3,    // t
    -36,   // ct
    13,    // cct
    -14,   // ctt
].into_boxed_slice()
