vec![
    0,     // .......
    5,     // b......
    -5,    // w......
    -4,    // .b.....
    16,    // bb.....
    3,     // wb.....
    4,     // .w.....
    -3,    // bw.....
    -16,   // ww.....
    14,    // ..b....
    21,    // b.b....
    -12,   // w.b....
    17,    // .bb....
    93,    // bbb....
    3,     // wbb....
    -30,   // .wb....
    -12,   // bwb....
    -2,    // wwb....
    -14,   // ..w....
    12,    // b.w....
    -21,   // w.w....
    30,    // .bw....
    2,     // bbw....
    12,    // wbw....
    -17,   // .ww....
    -3,    // bww....
    -93,   // www....
    -14,   // ...b...
    -3,    // b..b...
    9,     // w..b...
    2,     // .b.b...
    21,    // bb.b...
    -21,   // wb.b...
    3,     // .w.b...
    13,    // bw.b...
    -51,   // ww.b...
    -14,   // ..bb...
    0,     // b.bb...
    -38,   // w.bb...
    39,    // .bbb...
    185,   // bbbb...
    -66,   // wbbb...
    -26,   // .wbb...
    -14,   // bwbb...
    45,    // wwbb...
    14,    // ..wb...
    35,    // b.wb...
    8,     // w.wb...
    9,     // .bwb...
    -58,   // bbwb...
    8,     // wbwb...
    35,    // .wwb...
    -21,   // bwwb...
    -5,    // wwwb...
    14,    // ...w...
    -9,    // b..w...
    3,     // w..w...
    -3,    // .b.w...
    51,    // bb.w...
    -13,   // wb.w...
    -2,    // .w.w...
    21,    // bw.w...
    -21,   // ww.w...
    -14,   // ..bw...
    -8,    // b.bw...
    -35,   // w.bw...
    -35,   // .bbw...
    5,     // bbbw...
    21,    // wbbw...
    -9,    // .wbw...
    -8,    // bwbw...
    58,    // wwbw...
    14,    // ..ww...
    38,    // b.ww...
    0,     // w.ww...
    26,    // .bww...
    -45,   // bbww...
    14,    // wbww...
    -39,   // .www...
    66,    // bwww...
    -185,  // wwww...
    14,    // ....b..
    0,     // b...b..
    18,    // w...b..
    -2,    // .b..b..
    -7,    // bb..b..
    -24,   // wb..b..
    3,     // .w..b..
    -20,   // bw..b..
    -44,   // ww..b..
    5,     // ..b.b..
    -9,    // b.b.b..
    -9,    // w.b.b..
    15,    // .bb.b..
    41,    // bbb.b..
    42,    // wbb.b..
    2,     // .wb.b..
    -6,    // bwb.b..
    1,     // wwb.b..
    0,     // ..w.b..
    41,    // b.w.b..
    -19,   // w.w.b..
    -5,    // .bw.b..
    -2,    // bbw.b..
    -6,    // wbw.b..
    18,    // .ww.b..
    2,     // bww.b..
    -51,   // www.b..
    -14,   // ...bb..
    -1,    // b..bb..
    -3,    // w..bb..
    90,    // .b.bb..
    30,    // bb.bb..
    -41,   // wb.bb..
    4,     // .w.bb..
    10,    // bw.bb..
    4,     // ww.bb..
    0,     // ..bbb..
    55,    // b.bbb..
    -41,   // w.bbb..
    136,   // .bbbb..
    43,    // bbbbb..
    57,    // wbbbb..
    -62,   // .wbbb..
    -2,    // bwbbb..
    -7,    // wwbbb..
    -9,    // ..wbb..
    -13,   // b.wbb..
    3,     // w.wbb..
    3,     // .bwbb..
    -16,   // bbwbb..
    -25,   // wbwbb..
    -20,   // .wwbb..
    -23,   // bwwbb..
    -18,   // wwwbb..
    -14,   // ...wb..
    -21,   // b..wb..
    -12,   // w..wb..
    -10,   // .b.wb..
    -8,    // bb.wb..
    -1,    // wb.wb..
    -13,   // .w.wb..
    0,     // bw.wb..
    -9,    // ww.wb..
    10,    // ..bwb..
    -21,   // b.bwb..
    -8,    // w.bwb..
    -25,   // .bbwb..
    -24,   // bbbwb..
    63,    // wbbwb..
    -15,   // .wbwb..
    15,    // bwbwb..
    -15,   // wwbwb..
    9,     // ..wwb..
    -19,   // b.wwb..
    4,     // w.wwb..
    9,     // .bwwb..
    22,    // bbwwb..
    47,    // wbwwb..
    4,     // .wwwb..
    26,    // bwwwb..
    -35,   // wwwwb..
    -14,   // ....w..
    -18,   // b...w..
    0,     // w...w..
    -3,    // .b..w..
    44,    // bb..w..
    20,    // wb..w..
    2,     // .w..w..
    24,    // bw..w..
    7,     // ww..w..
    0,     // ..b.w..
    19,    // b.b.w..
    -41,   // w.b.w..
    -18,   // .bb.w..
    51,    // bbb.w..
    -2,    // wbb.w..
    5,     // .wb.w..
    6,     // bwb.w..
    2,     // wwb.w..
    -5,    // ..w.w..
    9,     // b.w.w..
    9,     // w.w.w..
    -2,    // .bw.w..
    -1,    // bbw.w..
    6,     // wbw.w..
    -15,   // .ww.w..
    -42,   // bww.w..
    -41,   // www.w..
    14,    // ...bw..
    12,    // b..bw..
    21,    // w..bw..
    13,    // .b.bw..
    9,     // bb.bw..
    0,     // wb.bw..
    10,    // .w.bw..
    1,     // bw.bw..
    8,     // ww.bw..
    -9,    // ..bbw..
    -4,    // b.bbw..
    19,    // w.bbw..
    -4,    // .bbbw..
    35,    // bbbbw..
    -26,   // wbbbw..
    -9,    // .wbbw..
    -47,   // bwbbw..
    -22,   // wwbbw..
    -10,   // ..wbw..
    8,     // b.wbw..
    21,    // w.wbw..
    15,    // .bwbw..
    15,    // bbwbw..
    -15,   // wbwbw..
    25,    // .wwbw..
    -63,   // bwwbw..
    24,    // wwwbw..
    14,    // ...ww..
    3,     // b..ww..
    1,     // w..ww..
    -4,    // .b.ww..
    -4,    // bb.ww..
    -10,   // wb.ww..
    -90,   // .w.ww..
    41,    // bw.ww..
    -30,   // ww.ww..
    9,     // ..bww..
    -3,    // b.bww..
    13,    // w.bww..
    20,    // .bbww..
    18,    // bbbww..
    23,    // wbbww..
    -3,    // .wbww..
    25,    // bwbww..
    16,    // wwbww..
    0,     // ..www..
    41,    // b.www..
    -55,   // w.www..
    62,    // .bwww..
    7,     // bbwww..
    2,     // wbwww..
    -136,  // .wwww..
    -57,   // bwwww..
    -43,   // wwwww..
    -4,    // .....b.
    -9,    // b....b.
    -59,   // w....b.
    17,    // .b...b.
    53,    // bb...b.
    13,    // wb...b.
    0,     // .w...b.
    -2,    // bw...b.
    4,     // ww...b.
    -2,    // ..b..b.
    10,    // b.b..b.
    4,     // w.b..b.
    27,    // .bb..b.
    7,     // bbb..b.
    46,    // wbb..b.
    -3,    // .wb..b.
    -7,    // bwb..b.
    43,    // wwb..b.
    -3,    // ..w..b.
    -26,   // b.w..b.
    17,    // w.w..b.
    -18,   // .bw..b.
    -21,   // bbw..b.
    -48,   // wbw..b.
    28,    // .ww..b.
    -41,   // bww..b.
    -65,   // www..b.
    2,     // ...b.b.
    -13,   // b..b.b.
    49,    // w..b.b.
    21,    // .b.b.b.
    8,     // bb.b.b.
    -7,    // wb.b.b.
    -8,    // .w.b.b.
    -68,   // bw.b.b.
    -31,   // ww.b.b.
    90,    // ..bb.b.
    -29,   // b.bb.b.
    15,    // w.bb.b.
    16,    // .bbb.b.
    4,     // bbbb.b.
    59,    // wbbb.b.
    9,     // .wbb.b.
    29,    // bwbb.b.
    -39,   // wwbb.b.
    13,    // ..wb.b.
    -4,    // b.wb.b.
    -10,   // w.wb.b.
    7,     // .bwb.b.
    10,    // bbwb.b.
    0,     // wbwb.b.
    35,    // .wwb.b.
    0,     // bwwb.b.
    -20,   // wwwb.b.
    -3,    // ...w.b.
    13,    // b..w.b.
    -20,   // w..w.b.
    -47,   // .b.w.b.
    26,    // bb.w.b.
    1,     // wb.w.b.
    8,     // .w.w.b.
    1,     // bw.w.b.
    -7,    // ww.w.b.
    -10,   // ..bw.b.
    -4,    // b.bw.b.
    -5,    // w.bw.b.
    -20,   // .bbw.b.
    2,     // bbbw.b.
    0,     // wbbw.b.
    -19,   // .wbw.b.
    7,     // bwbw.b.
    9,     // wwbw.b.
    -4,    // ..ww.b.
    -4,    // b.ww.b.
    -19,   // w.ww.b.
    -20,   // .bww.b.
    -37,   // bbww.b.
    27,    // wbww.b.
    -28,   // .www.b.
    32,    // bwww.b.
    -25,   // wwww.b.
    17,    // ....bb.
    -7,    // b...bb.
    -3,    // w...bb.
    27,    // .b..bb.
    4,     // bb..bb.
    34,    // wb..bb.
    -28,   // .w..bb.
    18,    // bw..bb.
    -23,   // ww..bb.
    15,    // ..b.bb.
    -1,    // b.b.bb.
    22,    // w.b.bb.
    5,     // .bb.bb.
    11,    // bbb.bb.
    50,    // wbb.bb.
    4,     // .wb.bb.
    15,    // bwb.bb.
    8,     // wwb.bb.
    -18,   // ..w.bb.
    -5,    // b.w.bb.
    -62,   // w.w.bb.
    0,     // .bw.bb.
    13,    // bbw.bb.
    -3,    // wbw.bb.
    0,     // .ww.bb.
    -8,    // bww.bb.
    -46,   // www.bb.
    39,    // ...bbb.
    -13,   // b..bbb.
    16,    // w..bbb.
    16,    // .b.bbb.
    0,     // bb.bbb.
    39,    // wb.bbb.
    28,    // .w.bbb.
    20,    // bw.bbb.
    -10,   // ww.bbb.
    136,   // ..bbbb.
    27,    // b.bbbb.
    16,    // w.bbbb.
    13,    // .bbbbb.
    -2,    // bbbbbb.
    36,    // wbbbbb.
    53,    // .wbbbb.
    27,    // bwbbbb.
    13,    // wwbbbb.
    -4,    // ..wbbb.
    -1,    // b.wbbb.
    -19,   // w.wbbb.
    6,     // .bwbbb.
    -33,   // bbwbbb.
    -35,   // wbwbbb.
    -16,   // .wwbbb.
    -17,   // bwwbbb.
    -5,    // wwwbbb.
    -35,   // ...wbb.
    6,     // b..wbb.
    10,    // w..wbb.
    -20,   // .b.wbb.
    24,    // bb.wbb.
    -23,   // wb.wbb.
    -35,   // .w.wbb.
    -23,   // bw.wbb.
    -22,   // ww.wbb.
    -25,   // ..bwbb.
    4,     // b.bwbb.
    -39,   // w.bwbb.
    12,    // .bbwbb.
    -24,   // bbbwbb.
    -21,   // wbbwbb.
    8,     // .wbwbb.
    -4,    // bwbwbb.
    51,    // wwbwbb.
    20,    // ..wwbb.
    -35,   // b.wwbb.
    14,    // w.wwbb.
    -22,   // .bwwbb.
    -38,   // bbwwbb.
    22,    // wbwwbb.
    16,    // .wwwbb.
    -3,    // bwwwbb.
    15,    // wwwwbb.
    30,    // ....wb.
    25,    // b...wb.
    -10,   // w...wb.
    -18,   // .b..wb.
    -19,   // bb..wb.
    -27,   // wb..wb.
    3,     // .w..wb.
    -14,   // bw..wb.
    6,     // ww..wb.
    -5,    // ..b.wb.
    -19,   // b.b.wb.
    -31,   // w.b.wb.
    0,     // .bb.wb.
    18,    // bbb.wb.
    -35,   // wbb.wb.
    0,     // .wb.wb.
    -34,   // bwb.wb.
    8,     // wwb.wb.
    -2,    // ..w.wb.
    46,    // b.w.wb.
    38,    // w.w.wb.
    4,     // .bw.wb.
    10,    // bbw.wb.
    -20,   // wbw.wb.
    -4,    // .ww.wb.
    0,     // bww.wb.
    -47,   // www.wb.
    9,     // ...bwb.
    -11,   // b..bwb.
    -1,    // w..bwb.
    7,     // .b.bwb.
    3,     // bb.bwb.
    6,     // wb.bwb.
    19,    // .w.bwb.
    21,    // bw.bwb.
    -19,   // ww.bwb.
    3,     // ..bbwb.
    -31,   // b.bbwb.
    18,    // w.bbwb.
    6,     // .bbbwb.
    -9,    // bbbbwb.
    14,    // wbbbwb.
    -18,   // .wbbwb.
    -14,   // bwbbwb.
    23,    // wwbbwb.
    15,    // ..wbwb.
    26,    // b.wbwb.
    -1,    // w.wbwb.
    -28,   // .bwbwb.
    45,    // bbwbwb.
    15,    // wbwbwb.
    -8,    // .wwbwb.
    25,    // bwwbwb.
    -54,   // wwwbwb.
    26,    // ...wwb.
    -30,   // b..wwb.
    20,    // w..wwb.
    -20,   // .b.wwb.
    -12,   // bb.wwb.
    2,     // wb.wwb.
    -9,    // .w.wwb.
    -13,   // bw.wwb.
    -5,    // ww.wwb.
    9,     // ..bwwb.
    8,     // b.bwwb.
    -11,   // w.bwwb.
    -22,   // .bbwwb.
    -21,   // bbbwwb.
    -20,   // wbbwwb.
    18,    // .wbwwb.
    -9,    // bwbwwb.
    7,     // wwbwwb.
    62,    // ..wwwb.
    43,    // b.wwwb.
    -41,   // w.wwwb.
    -41,   // .bwwwb.
    5,     // bbwwwb.
    15,    // wbwwwb.
    -53,   // .wwwwb.
    102,   // bwwwwb.
    -1,    // wwwwwb.
    4,     // .....w.
    59,    // b....w.
    9,     // w....w.
    0,     // .b...w.
    -4,    // bb...w.
    2,     // wb...w.
    -17,   // .w...w.
    -13,   // bw...w.
    -53,   // ww...w.
    3,     // ..b..w.
    -17,   // b.b..w.
    26,    // w.b..w.
    -28,   // .bb..w.
    65,    // bbb..w.
    41,    // wbb..w.
    18,    // .wb..w.
    48,    // bwb..w.
    21,    // wwb..w.
    2,     // ..w..w.
    -4,    // b.w..w.
    -10,   // w.w..w.
    3,     // .bw..w.
    -43,   // bbw..w.
    7,     // wbw..w.
    -27,   // .ww..w.
    -46,   // bww..w.
    -7,    // www..w.
    3,     // ...b.w.
    20,    // b..b.w.
    -13,   // w..b.w.
    -8,    // .b.b.w.
    7,     // bb.b.w.
    -1,    // wb.b.w.
    47,    // .w.b.w.
    -1,    // bw.b.w.
    -26,   // ww.b.w.
    4,     // ..bb.w.
    19,    // b.bb.w.
    4,     // w.bb.w.
    28,    // .bbb.w.
    25,    // bbbb.w.
    -32,   // wbbb.w.
    20,    // .wbb.w.
    -27,   // bwbb.w.
    37,    // wwbb.w.
    10,    // ..wb.w.
    5,     // b.wb.w.
    4,     // w.wb.w.
    19,    // .bwb.w.
    -9,    // bbwb.w.
    -7,    // wbwb.w.
    20,    // .wwb.w.
    0,     // bwwb.w.
    -2,    // wwwb.w.
    -2,    // ...w.w.
    -49,   // b..w.w.
    13,    // w..w.w.
    8,     // .b.w.w.
    31,    // bb.w.w.
    68,    // wb.w.w.
    -21,   // .w.w.w.
    7,     // bw.w.w.
    -8,    // ww.w.w.
    -13,   // ..bw.w.
    10,    // b.bw.w.
    4,     // w.bw.w.
    -35,   // .bbw.w.
    20,    // bbbw.w.
    0,     // wbbw.w.
    -7,    // .wbw.w.
    0,     // bwbw.w.
    -10,   // wwbw.w.
    -90,   // ..ww.w.
    -15,   // b.ww.w.
    29,    // w.ww.w.
    -9,    // .bww.w.
    39,    // bbww.w.
    -29,   // wbww.w.
    -16,   // .www.w.
    -59,   // bwww.w.
    -4,    // wwww.w.
    -30,   // ....bw.
    10,    // b...bw.
    -25,   // w...bw.
    -3,    // .b..bw.
    -6,    // bb..bw.
    14,    // wb..bw.
    18,    // .w..bw.
    27,    // bw..bw.
    19,    // ww..bw.
    2,     // ..b.bw.
    -38,   // b.b.bw.
    -46,   // w.b.bw.
    4,     // .bb.bw.
    47,    // bbb.bw.
    0,     // wbb.bw.
    -4,    // .wb.bw.
    20,    // bwb.bw.
    -10,   // wwb.bw.
    5,     // ..w.bw.
    31,    // b.w.bw.
    19,    // w.w.bw.
    0,     // .bw.bw.
    -8,    // bbw.bw.
    34,    // wbw.bw.
    0,     // .ww.bw.
    35,    // bww.bw.
    -18,   // www.bw.
    -26,   // ...bbw.
    -20,   // b..bbw.
    30,    // w..bbw.
    9,     // .b.bbw.
    5,     // bb.bbw.
    13,    // wb.bbw.
    20,    // .w.bbw.
    -2,    // bw.bbw.
    12,    // ww.bbw.
    -62,   // ..bbbw.
    41,    // b.bbbw.
    -43,   // w.bbbw.
    53,    // .bbbbw.
    1,     // bbbbbw.
    -102,  // wbbbbw.
    41,    // .wbbbw.
    -15,   // bwbbbw.
    -5,    // wwbbbw.
    -9,    // ..wbbw.
    11,    // b.wbbw.
    -8,    // w.wbbw.
    -18,   // .bwbbw.
    -7,    // bbwbbw.
    9,     // wbwbbw.
    22,    // .wwbbw.
    20,    // bwwbbw.
    21,    // wwwbbw.
    -9,    // ...wbw.
    1,     // b..wbw.
    11,    // w..wbw.
    -19,   // .b.wbw.
    19,    // bb.wbw.
    -21,   // wb.wbw.
    -7,    // .w.wbw.
    -6,    // bw.wbw.
    -3,    // ww.wbw.
    -15,   // ..bwbw.
    1,     // b.bwbw.
    -26,   // w.bwbw.
    8,     // .bbwbw.
    54,    // bbbwbw.
    -25,   // wbbwbw.
    28,    // .wbwbw.
    -15,   // bwbwbw.
    -45,   // wwbwbw.
    -3,    // ..wwbw.
    -18,   // b.wwbw.
    31,    // w.wwbw.
    18,    // .bwwbw.
    -23,   // bbwwbw.
    14,    // wbwwbw.
    -6,    // .wwwbw.
    -14,   // bwwwbw.
    9,     // wwwwbw.
    -17,   // ....ww.
    3,     // b...ww.
    7,     // w...ww.
    28,    // .b..ww.
    23,    // bb..ww.
    -18,   // wb..ww.
    -27,   // .w..ww.
    -34,   // bw..ww.
    -4,    // ww..ww.
    18,    // ..b.ww.
    62,    // b.b.ww.
    5,     // w.b.ww.
    0,     // .bb.ww.
    46,    // bbb.ww.
    8,     // wbb.ww.
    0,     // .wb.ww.
    3,     // bwb.ww.
    -13,   // wwb.ww.
    -15,   // ..w.ww.
    -22,   // b.w.ww.
    1,     // w.w.ww.
    -4,    // .bw.ww.
    -8,    // bbw.ww.
    -15,   // wbw.ww.
    -5,    // .ww.ww.
    -50,   // bww.ww.
    -11,   // www.ww.
    35,    // ...bww.
    -10,   // b..bww.
    -6,    // w..bww.
    35,    // .b.bww.
    22,    // bb.bww.
    23,    // wb.bww.
    20,    // .w.bww.
    23,    // bw.bww.
    -24,   // ww.bww.
    -20,   // ..bbww.
    -14,   // b.bbww.
    35,    // w.bbww.
    -16,   // .bbbww.
    -15,   // bbbbww.
    3,     // wbbbww.
    22,    // .wbbww.
    -22,   // bwbbww.
    38,    // wwbbww.
    25,    // ..wbww.
    39,    // b.wbww.
    -4,    // w.wbww.
    -8,    // .bwbww.
    -51,   // bbwbww.
    4,     // wbwbww.
    -12,   // .wwbww.
    21,    // bwwbww.
    24,    // wwwbww.
    -39,   // ...www.
    -16,   // b..www.
    13,    // w..www.
    -28,   // .b.www.
    10,    // bb.www.
    -20,   // wb.www.
    -16,   // .w.www.
    -39,   // bw.www.
    0,     // ww.www.
    4,     // ..bwww.
    19,    // b.bwww.
    1,     // w.bwww.
    16,    // .bbwww.
    5,     // bbbwww.
    17,    // wbbwww.
    -6,    // .wbwww.
    35,    // bwbwww.
    33,    // wwbwww.
    -136,  // ..wwww.
    -16,   // b.wwww.
    -27,   // w.wwww.
    -53,   // .bwwww.
    -13,   // bbwwww.
    -27,   // wbwwww.
    -13,   // .wwwww.
    -36,   // bwwwww.
    2,     // wwwwww.
    5,     // ......b
    18,    // b.....b
    0,     // w.....b
    -9,    // .b....b
    37,    // bb....b
    6,     // wb....b
    59,    // .w....b
    8,     // bw....b
    -6,    // ww....b
    0,     // ..b...b
    4,     // b.b...b
    -20,   // w.b...b
    -7,    // .bb...b
    -56,   // bbb...b
    -29,   // wbb...b
    10,    // .wb...b
    -38,   // bwb...b
    -32,   // wwb...b
    -18,   // ..w...b
    -31,   // b.w...b
    -15,   // w.w...b
    25,    // .bw...b
    -10,   // bbw...b
    -12,   // wbw...b
    3,     // .ww...b
    -1,    // bww...b
    26,    // www...b
    -3,    // ...b..b
    13,    // b..b..b
    17,    // w..b..b
    -13,   // .b.b..b
    17,    // bb.b..b
    13,    // wb.b..b
    20,    // .w.b..b
    -38,   // bw.b..b
    -2,    // ww.b..b
    -1,    // ..bb..b
    17,    // b.bb..b
    -28,   // w.bb..b
    -13,   // .bbb..b
    31,    // bbbb..b
    -1,    // wbbb..b
    -20,   // .wbb..b
    -27,   // bwbb..b
    -12,   // wwbb..b
    12,    // ..wb..b
    28,    // b.wb..b
    -5,    // w.wb..b
    -11,   // .bwb..b
    11,    // bbwb..b
    -30,   // wbwb..b
    -10,   // .wwb..b
    -6,    // bwwb..b
    7,     // wwwb..b
    -9,    // ...w..b
    -36,   // b..w..b
    -17,   // w..w..b
    13,    // .b.w..b
    36,    // bb.w..b
    -5,    // wb.w..b
    -49,   // .w.w..b
    -11,   // bw.w..b
    -30,   // ww.w..b
    -21,   // ..bw..b
    1,     // b.bw..b
    -28,   // w.bw..b
    6,     // .bbw..b
    -5,    // bbbw..b
    -39,   // wbbw..b
    1,     // .wbw..b
    -43,   // bwbw..b
    5,     // wwbw..b
    3,     // ..ww..b
    10,    // b.ww..b
    -1,    // w.ww..b
    -30,   // .bww..b
    34,    // bbww..b
    17,    // wbww..b
    -16,   // .www..b
    -6,    // bwww..b
    -39,   // wwww..b
    21,    // ....b.b
    4,     // b...b.b
    15,    // w...b.b
    10,    // .b..b.b
    -45,   // bb..b.b
    -8,    // wb..b.b
    -17,   // .w..b.b
    48,    // bw..b.b
    -29,   // ww..b.b
    -9,    // ..b.b.b
    -19,   // b.b.b.b
    13,    // w.b.b.b
    -1,    // .bb.b.b
    -14,   // bbb.b.b
    1,     // wbb.b.b
    -38,   // .wb.b.b
    18,    // bwb.b.b
    46,    // wwb.b.b
    19,    // ..w.b.b
    -16,   // b.w.b.b
    0,     // w.w.b.b
    -19,   // .bw.b.b
    15,    // bbw.b.b
    -8,    // wbw.b.b
    62,    // .ww.b.b
    -5,    // bww.b.b
    -15,   // www.b.b
    0,     // ...bb.b
    17,    // b..bb.b
    1,     // w..bb.b
    -29,   // .b.bb.b
    -3,    // bb.bb.b
    -8,    // wb.bb.b
    19,    // .w.bb.b
    17,    // bw.bb.b
    -27,   // ww.bb.b
    55,    // ..bbb.b
    32,    // b.bbb.b
    32,    // w.bbb.b
    27,    // .bbbb.b
    -7,    // bbbbb.b
    -20,   // wbbbb.b
    41,    // .wbbb.b
    17,    // bwbbb.b
    -28,   // wwbbb.b
    -4,    // ..wbb.b
    31,    // b.wbb.b
    4,     // w.wbb.b
    -31,   // .bwbb.b
    33,    // bbwbb.b
    -3,    // wbwbb.b
    -14,   // .wwbb.b
    2,     // bwwbb.b
    -27,   // wwwbb.b
    -8,    // ...wb.b
    1,     // b..wb.b
    5,     // w..wb.b
    -4,    // .b.wb.b
    -4,    // bb.wb.b
    -14,   // wb.wb.b
    10,    // .w.wb.b
    34,    // bw.wb.b
    46,    // ww.wb.b
    -21,   // ..bwb.b
    5,     // b.bwb.b
    -47,   // w.bwb.b
    4,     // .bbwb.b
    -17,   // bbbwb.b
    16,    // wbbwb.b
    1,     // .wbwb.b
    -16,   // bwbwb.b
    10,    // wwbwb.b
    -3,    // ..wwb.b
    3,     // b.wwb.b
    -4,    // w.wwb.b
    8,     // .bwwb.b
    -19,   // bbwwb.b
    -27,   // wbwwb.b
    19,    // .wwwb.b
    -21,   // bwwwb.b
    -7,    // wwwwb.b
    12,    // ....w.b
    -31,   // b...w.b
    20,    // w...w.b
    -26,   // .b..w.b
    46,    // bb..w.b
    10,    // wb..w.b
    -4,    // .w..w.b
    5,     // bw..w.b
    -9,    // ww..w.b
    41,    // ..b.w.b
    -16,   // b.b.w.b
    0,     // w.b.w.b
    -5,    // .bb.w.b
    37,    // bbb.w.b
    20,    // wbb.w.b
    31,    // .wb.w.b
    39,    // bwb.w.b
    -42,   // wwb.w.b
    9,     // ..w.w.b
    -49,   // b.w.w.b
    -13,   // w.w.w.b
    46,    // .bw.w.b
    14,    // bbw.w.b
    -11,   // wbw.w.b
    -22,   // .ww.w.b
    4,     // bww.w.b
    -1,    // www.w.b
    35,    // ...bw.b
    28,    // b..bw.b
    28,    // w..bw.b
    -4,    // .b.bw.b
    -3,    // bb.bw.b
    23,    // wb.bw.b
    5,     // .w.bw.b
    29,    // bw.bw.b
    22,    // ww.bw.b
    -13,   // ..bbw.b
    31,    // b.bbw.b
    -38,   // w.bbw.b
    -1,    // .bbbw.b
    -42,   // bbbbw.b
    -11,   // wbbbw.b
    11,    // .wbbw.b
    -5,    // bwbbw.b
    0,     // wwbbw.b
    8,     // ..wbw.b
    -13,   // b.wbw.b
    47,    // w.wbw.b
    26,    // .bwbw.b
    35,    // bbwbw.b
    -13,   // wbwbw.b
    39,    // .wwbw.b
    -11,   // bwwbw.b
    29,    // wwwbw.b
    38,    // ...ww.b
    10,    // b..ww.b
    28,    // w..ww.b
    -4,    // .b.ww.b
    -8,    // bb.ww.b
    0,     // wb.ww.b
    -15,   // .w.ww.b
    -14,   // bw.ww.b
    -10,   // ww.ww.b
    -19,   // ..bww.b
    3,     // b.bww.b
    38,    // w.bww.b
    -35,   // .bbww.b
    -1,    // bbbww.b
    8,     // wbbww.b
    -18,   // .wbww.b
    17,    // bwbww.b
    -16,   // wwbww.b
    41,    // ..www.b
    24,    // b.www.b
    -32,   // w.www.b
    43,    // .bwww.b
    23,    // bbwww.b
    -15,   // wbwww.b
    -16,   // .wwww.b
    7,     // bwwww.b
    -19,   // wwwww.b
    16,    // .....bb
    37,    // b....bb
    6,     // w....bb
    53,    // .b...bb
    -20,   // bb...bb
    27,    // wb...bb
    -4,    // .w...bb
    -11,   // bw...bb
    0,     // ww...bb
    -7,    // ..b..bb
    -45,   // b.b..bb
    9,     // w.b..bb
    4,     // .bb..bb
    63,    // bbb..bb
    -33,   // wbb..bb
    -6,    // .wb..bb
    -17,   // bwb..bb
    -15,   // wwb..bb
    44,    // ..w..bb
    46,    // b.w..bb
    29,    // w.w..bb
    -19,   // .bw..bb
    28,    // bbw..bb
    15,    // wbw..bb
    23,    // .ww..bb
    23,    // bww..bb
    -8,    // www..bb
    21,    // ...b.bb
    17,    // b..b.bb
    30,    // w..b.bb
    8,     // .b.b.bb
    -19,   // bb.b.bb
    -22,   // wb.b.bb
    7,     // .w.b.bb
    -5,    // bw.b.bb
    1,     // ww.b.bb
    30,    // ..bb.bb
    -3,    // b.bb.bb
    10,    // w.bb.bb
    0,     // .bbb.bb
    7,     // bbbb.bb
    8,     // wbbb.bb
    5,     // .wbb.bb
    26,    // bwbb.bb
    34,    // wwbb.bb
    9,     // ..wb.bb
    -3,    // b.wb.bb
    -46,   // w.wb.bb
    3,     // .bwb.bb
    66,    // bbwb.bb
    -36,   // wbwb.bb
    22,    // .wwb.bb
    -10,   // bwwb.bb
    33,    // wwwb.bb
    51,    // ...w.bb
    36,    // b..w.bb
    2,     // w..w.bb
    26,    // .b.w.bb
    44,    // bb.w.bb
    -19,   // wb.w.bb
    31,    // .w.w.bb
    -40,   // bw.w.bb
    -1,    // ww.w.bb
    -8,    // ..bw.bb
    -4,    // b.bw.bb
    -22,   // w.bw.bb
    24,    // .bbw.bb
    -37,   // bbbw.bb
    11,    // wbbw.bb
    19,    // .wbw.bb
    24,    // bwbw.bb
    14,    // wwbw.bb
    -4,    // ..ww.bb
    -8,    // b.ww.bb
    27,    // w.ww.bb
    -12,   // .bww.bb
    11,    // bbww.bb
    34,    // wbww.bb
    10,    // .www.bb
    -7,    // bwww.bb
    2,     // wwww.bb
    93,    // ....bbb
    -56,   // b...bbb
    -26,   // w...bbb
    7,     // .b..bbb
    63,    // bb..bbb
    21,    // wb..bbb
    65,    // .w..bbb
    20,    // bw..bbb
    8,     // ww..bbb
    41,    // ..b.bbb
    -14,   // b.b.bbb
    1,     // w.b.bbb
    11,    // .bb.bbb
    19,    // bbb.bbb
    13,    // wbb.bbb
    47,    // .wb.bbb
    -32,   // bwb.bbb
    2,     // wwb.bbb
    51,    // ..w.bbb
    37,    // b.w.bbb
    15,    // w.w.bbb
    18,    // .bw.bbb
    -13,   // bbw.bbb
    -27,   // wbw.bbb
    46,    // .ww.bbb
    -7,    // bww.bbb
    0,     // www.bbb
    185,   // ...bbbb
    31,    // b..bbbb
    39,    // w..bbbb
    4,     // .b.bbbb
    7,     // bb.bbbb
    -41,   // wb.bbbb
    25,    // .w.bbbb
    -16,   // bw.bbbb
    -2,    // ww.bbbb
    43,    // ..bbbbb
    -7,    // b.bbbbb
    19,    // w.bbbbb
    -2,    // .bbbbbb
    26,    // bbbbbbb
    -15,   // wbbbbbb
    1,     // .wbbbbb
    -14,   // bwbbbbb
    -12,   // wwbbbbb
    35,    // ..wbbbb
    -42,   // b.wbbbb
    7,     // w.wbbbb
    -9,    // .bwbbbb
    6,     // bbwbbbb
    -23,   // wbwbbbb
    -15,   // .wwbbbb
    -6,    // bwwbbbb
    12,    // wwwbbbb
    5,     // ...wbbb
    -5,    // b..wbbb
    -7,    // w..wbbb
    2,     // .b.wbbb
    -37,   // bb.wbbb
    -2,    // wb.wbbb
    20,    // .w.wbbb
    -45,   // bw.wbbb
    -33,   // ww.wbbb
    -24,   // ..bwbbb
    -17,   // b.bwbbb
    -29,   // w.bwbbb
    -24,   // .bbwbbb
    -15,   // bbbwbbb
    -19,   // wbbwbbb
    54,    // .wbwbbb
    -23,   // bwbwbbb
    12,    // wwbwbbb
    18,    // ..wwbbb
    -1,    // b.wwbbb
    27,    // w.wwbbb
    -21,   // .bwwbbb
    -13,   // bbwwbbb
    -7,    // wbwwbbb
    5,     // .wwwbbb
    -30,   // bwwwbbb
    -12,   // wwwwbbb
    2,     // ....wbb
    -10,   // b...wbb
    32,    // w...wbb
    -21,   // .b..wbb
    28,    // bb..wbb
    -29,   // wb..wbb
    -43,   // .w..wbb
    10,    // bw..wbb
    15,    // ww..wbb
    -2,    // ..b.wbb
    15,    // b.b.wbb
    42,    // w.b.wbb
    13,    // .bb.wbb
    -13,   // bbb.wbb
    18,    // wbb.wbb
    -8,    // .wb.wbb
    -18,   // bwb.wbb
    0,     // wwb.wbb
    -1,    // ..w.wbb
    14,    // b.w.wbb
    -46,   // w.w.wbb
    10,    // .bw.wbb
    41,    // bbw.wbb
    3,     // wbw.wbb
    -8,    // .ww.wbb
    -3,    // bww.wbb
    -2,    // www.wbb
    -58,   // ...bwbb
    11,    // b..bwbb
    -5,    // w..bwbb
    10,    // .b.bwbb
    66,    // bb.bwbb
    14,    // wb.bwbb
    -9,    // .w.bwbb
    -55,   // bw.bwbb
    -14,   // ww.bwbb
    -16,   // ..bbwbb
    33,    // b.bbwbb
    16,    // w.bbwbb
    -33,   // .bbbwbb
    6,     // bbbbwbb
    -13,   // wbbbwbb
    -7,    // .wbbwbb
    -21,   // bwbbwbb
    57,    // wwbbwbb
    15,    // ..wbwbb
    35,    // b.wbwbb
    -10,   // w.wbwbb
    45,    // .bwbwbb
    -3,    // bbwbwbb
    8,     // wbwbwbb
    -51,   // .wwbwbb
    -21,   // bwwbwbb
    -12,   // wwwbwbb
    -45,   // ...wwbb
    34,    // b..wwbb
    12,    // w..wwbb
    -37,   // .b.wwbb
    11,    // bb.wwbb
    -1,    // wb.wwbb
    39,    // .w.wwbb
    54,    // bw.wwbb
    -34,   // ww.wwbb
    22,    // ..bwwbb
    -19,   // b.bwwbb
    0,     // w.bwwbb
    -38,   // .bbwwbb
    -13,   // bbbwwbb
    -42,   // wbbwwbb
    -23,   // .wbwwbb
    -27,   // bwbwwbb
    -57,   // wwbwwbb
    7,     // ..wwwbb
    23,    // b.wwwbb
    28,    // w.wwwbb
    5,     // .bwwwbb
    -7,    // bbwwwbb
    8,     // wbwwwbb
    -13,   // .wwwwbb
    3,     // bwwwwbb
    12,    // wwwwwbb
    -3,    // .....wb
    8,     // b....wb
    -6,    // w....wb
    -2,    // .b...wb
    -11,   // bb...wb
    0,     // wb...wb
    -13,   // .w...wb
    49,    // bw...wb
    -27,   // ww...wb
    -20,   // ..b..wb
    48,    // b.b..wb
    -10,   // w.b..wb
    18,    // .bb..wb
    20,    // bbb..wb
    -6,    // wbb..wb
    27,    // .wb..wb
    -9,    // bwb..wb
    29,    // wwb..wb
    24,    // ..w..wb
    5,     // b.w..wb
    8,     // w.w..wb
    -14,   // .bw..wb
    10,    // bbw..wb
    -35,   // wbw..wb
    -34,   // .ww..wb
    39,    // bww..wb
    -21,   // www..wb
    13,    // ...b.wb
    -38,   // b..b.wb
    5,     // w..b.wb
    -68,   // .b.b.wb
    -5,    // bb.b.wb
    19,    // wb.b.wb
    -1,    // .w.b.wb
    -8,    // bw.b.wb
    19,    // ww.b.wb
    10,    // ..bb.wb
    17,    // b.bb.wb
    0,     // w.bb.wb
    20,    // .bbb.wb
    -16,   // bbbb.wb
    4,     // wbbb.wb
    -2,    // .wbb.wb
    -9,    // bwbb.wb
    1,     // wwbb.wb
    1,     // ..wb.wb
    29,    // b.wb.wb
    14,    // w.wb.wb
    21,    // .bwb.wb
    -55,   // bbwb.wb
    -9,    // wbwb.wb
    23,    // .wwb.wb
    -52,   // bwwb.wb
    2,     // wwwb.wb
    21,    // ...w.wb
    -11,   // b..w.wb
    -13,   // w..w.wb
    1,     // .b.w.wb
    -40,   // bb.w.wb
    -19,   // wb.w.wb
    7,     // .w.w.wb
    0,     // bw.w.wb
    22,    // ww.w.wb
    0,     // ..bw.wb
    34,    // b.bw.wb
    -23,   // w.bw.wb
    -23,   // .bbw.wb
    -45,   // bbbw.wb
    -14,   // wbbw.wb
    -6,    // .wbw.wb
    -38,   // bwbw.wb
    -14,   // wwbw.wb
    41,    // ..ww.wb
    -14,   // b.ww.wb
    8,     // w.ww.wb
    -13,   // .bww.wb
    54,    // bbww.wb
    23,    // wbww.wb
    -39,   // .www.wb
    15,    // bwww.wb
    41,    // wwww.wb
    -12,   // ....bwb
    -38,   // b...bwb
    12,    // w...bwb
    -7,    // .b..bwb
    -17,   // bb..bwb
    35,    // wb..bwb
    48,    // .w..bwb
    -9,    // bw..bwb
    -15,   // ww..bwb
    -6,    // ..b.bwb
    18,    // b.b.bwb
    11,    // w.b.bwb
    15,    // .bb.bwb
    -32,   // bbb.bwb
    6,     // wbb.bwb
    20,    // .wb.bwb
    -21,   // bwb.bwb
    -3,    // wwb.bwb
    6,     // ..w.bwb
    39,    // b.w.bwb
    8,     // w.w.bwb
    -34,   // .bw.bwb
    -18,   // bbw.bwb
    0,     // wbw.bwb
    3,     // .ww.bwb
    -20,   // bww.bwb
    27,    // www.bwb
    -14,   // ...bbwb
    -27,   // b..bbwb
    -17,   // w..bbwb
    29,    // .b.bbwb
    26,    // bb.bbwb
    -23,   // wb.bbwb
    -27,   // .w.bbwb
    -9,    // bw.bbwb
    -34,   // ww.bbwb
    -2,    // ..bbbwb
    17,    // b.bbbwb
    15,    // w.bbbwb
    27,    // .bbbbwb
    -14,   // bbbbbwb
    31,    // wbbbbwb
    -15,   // .wbbbwb
    -32,   // bwbbbwb
    -8,    // wwbbbwb
    -47,   // ..wbbwb
    -5,    // b.wbbwb
    27,    // w.wbbwb
    -14,   // .bwbbwb
    -21,   // bbwbbwb
    -18,   // wbwbbwb
    -22,   // .wwbbwb
    40,    // bwwbbwb
    7,     // wwwbbwb
    -8,    // ...wbwb
    -43,   // b..wbwb
    30,    // w..wbwb
    7,     // .b.wbwb
    24,    // bb.wbwb
    9,     // wb.wbwb
    0,     // .w.wbwb
    -38,   // bw.wbwb
    36,    // ww.wbwb
    15,    // ..bwbwb
    -16,   // b.bwbwb
    13,    // w.bwbwb
    -4,    // .bbwbwb
    -23,   // bbbwbwb
    -27,   // wbbwbwb
    -15,   // .wbwbwb
    6,     // bwbwbwb
    -8,    // wwbwbwb
    25,    // ..wwbwb
    17,    // b.wwbwb
    3,     // w.wwbwb
    -9,    // .bwwbwb
    -27,   // bbwwbwb
    18,    // wbwwbwb
    35,    // .wwwbwb
    33,    // bwwwbwb
    23,    // wwwwbwb
    -3,    // ....wwb
    -1,    // b...wwb
    29,    // w...wwb
    -41,   // .b..wwb
    23,    // bb..wwb
    6,     // wb..wwb
    -46,   // .w..wwb
    39,    // bw..wwb
    33,    // ww..wwb
    2,     // ..b.wwb
    -5,    // b.b.wwb
    -20,   // w.b.wwb
    -8,    // .bb.wwb
    -7,    // bbb.wwb
    0,     // wbb.wwb
    35,    // .wb.wwb
    -20,   // bwb.wwb
    -18,   // wwb.wwb
    -42,   // ..w.wwb
    4,     // b.w.wwb
    -1,    // w.w.wwb
    0,     // .bw.wwb
    -3,    // bbw.wwb
    -6,    // wbw.wwb
    -50,   // .ww.wwb
    -42,   // bww.wwb
    -13,   // www.wwb
    -21,   // ...bwwb
    -6,    // b..bwwb
    39,    // w..bwwb
    0,     // .b.bwwb
    -10,   // bb.bwwb
    14,    // wb.bwwb
    0,     // .w.bwwb
    -52,   // bw.bwwb
    -11,   // ww.bwwb
    -23,   // ..bbwwb
    2,     // b.bbwwb
    -8,    // w.bbwwb
    -17,   // .bbbwwb
    -6,    // bbbbwwb
    -13,   // wbbbwwb
    20,    // .wbbwwb
    40,    // bwbbwwb
    42,    // wwbbwwb
    -63,   // ..wbwwb
    -11,   // b.wbwwb
    -16,   // w.wbwwb
    25,    // .bwbwwb
    -21,   // bbwbwwb
    27,    // wbwbwwb
    21,    // .wwbwwb
    39,    // bwwbwwb
    19,    // wwwbwwb
    66,    // ...wwwb
    -6,    // b..wwwb
    1,     // w..wwwb
    32,    // .b.wwwb
    -7,    // bb.wwwb
    -4,    // wb.wwwb
    -59,   // .w.wwwb
    15,    // bw.wwwb
    -8,    // ww.wwwb
    26,    // ..bwwwb
    -21,   // b.bwwwb
    11,    // w.bwwwb
    -3,    // .bbwwwb
    -30,   // bbbwwwb
    13,    // wbbwwwb
    -14,   // .wbwwwb
    33,    // bwbwwwb
    13,    // wwbwwwb
    -57,   // ..wwwwb
    7,     // b.wwwwb
    20,    // w.wwwwb
    102,   // .bwwwwb
    3,     // bbwwwwb
    -31,   // wbwwwwb
    -36,   // .wwwwwb
    16,    // bwwwwwb
    15,    // wwwwwwb
    -5,    // ......w
    0,     // b.....w
    -18,   // w.....w
    -59,   // .b....w
    6,     // bb....w
    -8,    // wb....w
    9,     // .w....w
    -6,    // bw....w
    -37,   // ww....w
    18,    // ..b...w
    15,    // b.b...w
    31,    // w.b...w
    -3,    // .bb...w
    -26,   // bbb...w
    1,     // wbb...w
    -25,   // .wb...w
    12,    // bwb...w
    10,    // wwb...w
    0,     // ..w...w
    20,    // b.w...w
    -4,    // w.w...w
    -10,   // .bw...w
    32,    // bbw...w
    38,    // wbw...w
    7,     // .ww...w
    29,    // bww...w
    56,    // www...w
    9,     // ...b..w
    17,    // b..b..w
    36,    // w..b..w
    49,    // .b.b..w
    30,    // bb.b..w
    11,    // wb.b..w
    -13,   // .w.b..w
    5,     // bw.b..w
    -36,   // ww.b..w
    -3,    // ..bb..w
    1,     // b.bb..w
    -10,   // w.bb..w
    16,    // .bbb..w
    39,    // bbbb..w
    6,     // wbbb..w
    30,    // .wbb..w
    -17,   // bwbb..w
    -34,   // wwbb..w
    21,    // ..wb..w
    28,    // b.wb..w
    -1,    // w.wb..w
    -1,    // .bwb..w
    -5,    // bbwb..w
    43,    // wbwb..w
    -6,    // .wwb..w
    39,    // bwwb..w
    5,     // wwwb..w
    3,     // ...w..w
    -17,   // b..w..w
    -13,   // w..w..w
    -20,   // .b.w..w
    2,     // bb.w..w
    38,    // wb.w..w
    13,    // .w.w..w
    -13,   // bw.w..w
    -17,   // ww.w..w
    -12,   // ..bw..w
    5,     // b.bw..w
    -28,   // w.bw..w
    10,    // .bbw..w
    -7,    // bbbw..w
    6,     // wbbw..w
    11,    // .wbw..w
    30,    // bwbw..w
    -11,   // wwbw..w
    1,     // ..ww..w
    28,    // b.ww..w
    -17,   // w.ww..w
    20,    // .bww..w
    12,    // bbww..w
    27,    // wbww..w
    13,    // .www..w
    1,     // bwww..w
    -31,   // wwww..w
    -12,   // ....b.w
    -20,   // b...b.w
    31,    // w...b.w
    4,     // .b..b.w
    9,     // bb..b.w
    -5,    // wb..b.w
    26,    // .w..b.w
    -10,   // bw..b.w
    -46,   // ww..b.w
    -9,    // ..b.b.w
    13,    // b.b.b.w
    49,    // w.b.b.w
    22,    // .bb.b.w
    1,     // bbb.b.w
    -4,    // wbb.b.w
    -46,   // .wb.b.w
    11,    // bwb.b.w
    -14,   // wwb.b.w
    -41,   // ..w.b.w
    0,     // b.w.b.w
    16,    // w.w.b.w
    -31,   // .bw.b.w
    42,    // bbw.b.w
    -39,   // wbw.b.w
    5,     // .ww.b.w
    -20,   // bww.b.w
    -37,   // www.b.w
    -38,   // ...bb.w
    -28,   // b..bb.w
    -10,   // w..bb.w
    15,    // .b.bb.w
    10,    // bb.bb.w
    14,    // wb.bb.w
    4,     // .w.bb.w
    0,     // bw.bb.w
    8,     // ww.bb.w
    -41,   // ..bbb.w
    32,    // b.bbb.w
    -24,   // w.bbb.w
    16,    // .bbbb.w
    19,    // bbbbb.w
    -7,    // wbbbb.w
    -43,   // .wbbb.w
    15,    // bwbbb.w
    -23,   // wwbbb.w
    19,    // ..wbb.w
    -38,   // b.wbb.w
    -3,    // w.wbb.w
    18,    // .bwbb.w
    16,    // bbwbb.w
    -17,   // wbwbb.w
    35,    // .wwbb.w
    -8,    // bwwbb.w
    1,     // wwwbb.w
    -35,   // ...wb.w
    -28,   // b..wb.w
    -28,   // w..wb.w
    -5,    // .b.wb.w
    -22,   // bb.wb.w
    -29,   // wb.wb.w
    4,     // .w.wb.w
    -23,   // bw.wb.w
    3,     // ww.wb.w
    -8,    // ..bwb.w
    -47,   // b.bwb.w
    13,    // w.bwb.w
    -39,   // .bbwb.w
    -29,   // bbbwb.w
    11,    // wbbwb.w
    -26,   // .wbwb.w
    13,    // bwbwb.w
    -35,   // wwbwb.w
    13,    // ..wwb.w
    38,    // b.wwb.w
    -31,   // w.wwb.w
    -11,   // .bwwb.w
    0,     // bbwwb.w
    5,     // wbwwb.w
    1,     // .wwwb.w
    11,    // bwwwb.w
    42,    // wwwwb.w
    -21,   // ....w.w
    -15,   // b...w.w
    -4,    // w...w.w
    17,    // .b..w.w
    29,    // bb..w.w
    -48,   // wb..w.w
    -10,   // .w..w.w
    8,     // bw..w.w
    45,    // ww..w.w
    -19,   // ..b.w.w
    0,     // b.b.w.w
    16,    // w.b.w.w
    -62,   // .bb.w.w
    15,    // bbb.w.w
    5,     // wbb.w.w
    19,    // .wb.w.w
    8,     // bwb.w.w
    -15,   // wwb.w.w
    9,     // ..w.w.w
    -13,   // b.w.w.w
    19,    // w.w.w.w
    38,    // .bw.w.w
    -46,   // bbw.w.w
    -18,   // wbw.w.w
    1,     // .ww.w.w
    -1,    // bww.w.w
    14,    // www.w.w
    8,     // ...bw.w
    -5,    // b..bw.w
    -1,    // w..bw.w
    -10,   // .b.bw.w
    -46,   // bb.bw.w
    -34,   // wb.bw.w
    4,     // .w.bw.w
    14,    // bw.bw.w
    4,     // ww.bw.w
    3,     // ..bbw.w
    4,     // b.bbw.w
    -3,    // w.bbw.w
    -19,   // .bbbw.w
    7,     // bbbbw.w
    21,    // wbbbw.w
    -8,    // .wbbw.w
    27,    // bwbbw.w
    19,    // wwbbw.w
    21,    // ..wbw.w
    47,    // b.wbw.w
    -5,    // w.wbw.w
    -1,    // .bwbw.w
    -10,   // bbwbw.w
    16,    // wbwbw.w
    -4,    // .wwbw.w
    -16,   // bwwbw.w
    17,    // wwwbw.w
    0,     // ...ww.w
    -1,    // b..ww.w
    -17,   // w..ww.w
    -19,   // .b.ww.w
    27,    // bb.ww.w
    -17,   // wb.ww.w
    29,    // .w.ww.w
    8,     // bw.ww.w
    3,     // ww.ww.w
    4,     // ..bww.w
    -4,    // b.bww.w
    -31,   // w.bww.w
    14,    // .bbww.w
    27,    // bbbww.w
    -2,    // wbbww.w
    31,    // .wbww.w
    3,     // bwbww.w
    -33,   // wwbww.w
    -55,   // ..www.w
    -32,   // b.www.w
    -32,   // w.www.w
    -41,   // .bwww.w
    28,    // bbwww.w
    -17,   // wbwww.w
    -27,   // .wwww.w
    20,    // bwwww.w
    7,     // wwwww.w
    3,     // .....bw
    6,     // b....bw
    -8,    // w....bw
    13,    // .b...bw
    27,    // bb...bw
    -49,   // wb...bw
    2,     // .w...bw
    0,     // bw...bw
    11,    // ww...bw
    -24,   // ..b..bw
    -8,    // b.b..bw
    -5,    // w.b..bw
    34,    // .bb..bw
    21,    // bbb..bw
    -39,   // wbb..bw
    14,    // .wb..bw
    35,    // bwb..bw
    -10,   // wwb..bw
    20,    // ..w..bw
    10,    // b.w..bw
    -48,   // w.w..bw
    -27,   // .bw..bw
    -29,   // bbw..bw
    9,     // wbw..bw
    -18,   // .ww..bw
    6,     // bww..bw
    -20,   // www..bw
    -21,   // ...b.bw
    13,    // b..b.bw
    11,    // w..b.bw
    -7,    // .b.b.bw
    -22,   // bb.b.bw
    0,     // wb.b.bw
    -1,    // .w.b.bw
    19,    // bw.b.bw
    40,    // ww.b.bw
    -41,   // ..bb.bw
    -8,    // b.bb.bw
    14,    // w.bb.bw
    39,    // .bbb.bw
    -41,   // bbbb.bw
    -15,   // wbbb.bw
    13,    // .wbb.bw
    -23,   // bwbb.bw
    -54,   // wwbb.bw
    0,     // ..wb.bw
    23,    // b.wb.bw
    -34,   // w.wb.bw
    6,     // .bwb.bw
    14,    // bbwb.bw
    38,    // wbwb.bw
    23,    // .wwb.bw
    14,    // bwwb.bw
    45,    // wwwb.bw
    -13,   // ...w.bw
    -5,    // b..w.bw
    38,    // w..w.bw
    1,     // .b.w.bw
    -19,   // bb.w.bw
    8,     // wb.w.bw
    68,    // .w.w.bw
    -19,   // bw.w.bw
    5,     // ww.w.bw
    -1,    // ..bw.bw
    -14,   // b.bw.bw
    -29,   // w.bw.bw
    -23,   // .bbw.bw
    -2,    // bbbw.bw
    52,    // wbbw.bw
    -21,   // .wbw.bw
    9,     // bwbw.bw
    55,    // wwbw.bw
    -10,   // ..ww.bw
    0,     // b.ww.bw
    -17,   // w.ww.bw
    2,     // .bww.bw
    -1,    // bbww.bw
    9,     // wbww.bw
    -20,   // .www.bw
    -4,    // bwww.bw
    16,    // wwww.bw
    3,     // ....bbw
    -29,   // b...bbw
    1,     // w...bbw
    46,    // .b..bbw
    -33,   // bb..bbw
    -39,   // wb..bbw
    41,    // .w..bbw
    -6,    // bw..bbw
    -23,   // ww..bbw
    42,    // ..b.bbw
    1,     // b.b.bbw
    -4,    // w.b.bbw
    50,    // .bb.bbw
    13,    // bbb.bbw
    42,    // wbb.bbw
    0,     // .wb.bbw
    6,     // bwb.bbw
    3,     // wwb.bbw
    -2,    // ..w.bbw
    20,    // b.w.bbw
    5,     // w.w.bbw
    -35,   // .bw.bbw
    18,    // bbw.bbw
    20,    // wbw.bbw
    8,     // .ww.bbw
    0,     // bww.bbw
    7,     // www.bbw
    -66,   // ...bbbw
    -1,    // b..bbbw
    6,     // w..bbbw
    59,    // .b.bbbw
    8,     // bb.bbbw
    -15,   // wb.bbbw
    -32,   // .w.bbbw
    4,     // bw.bbbw
    7,     // ww.bbbw
    57,    // ..bbbbw
    -20,   // b.bbbbw
    -7,    // w.bbbbw
    36,    // .bbbbbw
    -15,   // bbbbbbw
    -16,   // wbbbbbw
    -102,  // .wbbbbw
    31,    // bwbbbbw
    -3,    // wwbbbbw
    -26,   // ..wbbbw
    -11,   // b.wbbbw
    21,    // w.wbbbw
    14,    // .bwbbbw
    -13,   // bbwbbbw
    -33,   // wbwbbbw
    3,     // .wwbbbw
    -13,   // bwwbbbw
    30,    // wwwbbbw
    21,    // ...wbbw
    -39,   // b..wbbw
    6,     // w..wbbw
    0,     // .b.wbbw
    11,    // bb.wbbw
    52,    // wb.wbbw
    0,     // .w.wbbw
    -14,   // bw.wbbw
    10,    // ww.wbbw
    63,    // ..bwbbw
    16,    // b.bwbbw
    11,    // w.bwbbw
    -21,   // .bbwbbw
    -19,   // bbbwbbw
    -39,   // wbbwbbw
    -25,   // .wbwbbw
    -27,   // bwbwbbw
    21,    // wwbwbbw
    23,    // ..wwbbw
    8,     // b.wwbbw
    -2,    // w.wwbbw
    -20,   // .bwwbbw
    -42,   // bbwwbbw
    -40,   // wbwwbbw
    17,    // .wwwbbw
    13,    // bwwwbbw
    6,     // wwwwbbw
    12,    // ....wbw
    -12,   // b...wbw
    38,    // w...wbw
    -48,   // .b..wbw
    15,    // bb..wbw
    9,     // wb..wbw
    7,     // .w..wbw
    -35,   // bw..wbw
    17,    // ww..wbw
    -6,    // ..b.wbw
    -8,    // b.b.wbw
    -39,   // w.b.wbw
    -3,    // .bb.wbw
    -27,   // bbb.wbw
    20,    // wbb.wbw
    34,    // .wb.wbw
    0,     // bwb.wbw
    18,    // wwb.wbw
    6,     // ..w.wbw
    -11,   // b.w.wbw
    -18,   // w.w.wbw
    -20,   // .bw.wbw
    3,     // bbw.wbw
    21,    // wbw.wbw
    -15,   // .ww.wbw
    -6,    // bww.wbw
    32,    // www.wbw
    8,     // ...bwbw
    -30,   // b..bwbw
    43,    // w..bwbw
    0,     // .b.bwbw
    -36,   // bb.bwbw
    38,    // wb.bwbw
    -7,    // .w.bwbw
    -9,    // bw.bwbw
    -24,   // ww.bwbw
    -25,   // ..bbwbw
    -3,    // b.bbwbw
    -17,   // w.bbwbw
    -35,   // .bbbwbw
    -23,   // bbbbwbw
    -33,   // wbbbwbw
    9,     // .wbbwbw
    -18,   // bwbbwbw
    27,    // wwbbwbw
    -15,   // ..wbwbw
    -13,   // b.wbwbw
    16,    // w.wbwbw
    15,    // .bwbwbw
    8,     // bbwbwbw
    -6,    // wbwbwbw
    4,     // .wwbwbw
    27,    // bwwbwbw
    23,    // wwwbwbw
    14,    // ...wwbw
    17,    // b..wwbw
    27,    // w..wwbw
    27,    // .b.wwbw
    34,    // bb.wwbw
    9,     // wb.wwbw
    -29,   // .w.wwbw
    23,    // bw.wwbw
    -26,   // ww.wwbw
    47,    // ..bwwbw
    -27,   // b.bwwbw
    5,     // w.bwwbw
    22,    // .bbwwbw
    -7,    // bbbwwbw
    -40,   // wbbwwbw
    14,    // .wbwwbw
    18,    // bwbwwbw
    21,    // wwbwwbw
    2,     // ..wwwbw
    -15,   // b.wwwbw
    -17,   // w.wwwbw
    15,    // .bwwwbw
    8,     // bbwwwbw
    32,    // wbwwwbw
    -27,   // .wwwwbw
    -31,   // bwwwwbw
    14,    // wwwwwbw
    -16,   // .....ww
    -6,    // b....ww
    -37,   // w....ww
    4,     // .b...ww
    0,     // bb...ww
    11,    // wb...ww
    -53,   // .w...ww
    -27,   // bw...ww
    20,    // ww...ww
    -44,   // ..b..ww
    -29,   // b.b..ww
    -46,   // w.b..ww
    -23,   // .bb..ww
    8,     // bbb..ww
    -23,   // wbb..ww
    19,    // .wb..ww
    -15,   // bwb..ww
    -28,   // wwb..ww
    7,     // ..w..ww
    -9,    // b.w..ww
    45,    // w.w..ww
    6,     // .bw..ww
    15,    // bbw..ww
    17,    // wbw..ww
    -4,    // .ww..ww
    33,    // bww..ww
    -63,   // www..ww
    -51,   // ...b.ww
    -2,    // b..b.ww
    -36,   // w..b.ww
    -31,   // .b.b.ww
    1,     // bb.b.ww
    40,    // wb.b.ww
    -26,   // .w.b.ww
    19,    // bw.b.ww
    -44,   // ww.b.ww
    4,     // ..bb.ww
    -27,   // b.bb.ww
    8,     // w.bb.ww
    -10,   // .bbb.ww
    -2,    // bbbb.ww
    7,     // wbbb.ww
    12,    // .wbb.ww
    -34,   // bwbb.ww
    -11,   // wwbb.ww
    8,     // ..wb.ww
    22,    // b.wb.ww
    4,     // w.wb.ww
    -19,   // .bwb.ww
    -14,   // bbwb.ww
    -24,   // wbwb.ww
    -24,   // .wwb.ww
    -11,   // bwwb.ww
    37,    // wwwb.ww
    -21,   // ...w.ww
    -30,   // b..w.ww
    -17,   // w..w.ww
    -7,    // .b.w.ww
    -1,    // bb.w.ww
    5,     // wb.w.ww
    -8,    // .w.w.ww
    22,    // bw.w.ww
    19,    // ww.w.ww
    -9,    // ..bw.ww
    46,    // b.bw.ww
    3,     // w.bw.ww
    -22,   // .bbw.ww
    -33,   // bbbw.ww
    10,    // wbbw.ww
    -3,    // .wbw.ww
    36,    // bwbw.ww
    -66,   // wwbw.ww
    -30,   // ..ww.ww
    -10,   // b.ww.ww
    3,     // w.ww.ww
    -5,    // .bww.ww
    -34,   // bbww.ww
    -26,   // wbww.ww
    0,     // .www.ww
    -8,    // bwww.ww
    -7,    // wwww.ww
    -2,    // ....bww
    -32,   // b...bww
    10,    // w...bww
    43,    // .b..bww
    -15,   // bb..bww
    -10,   // wb..bww
    21,    // .w..bww
    29,    // bw..bww
    -28,   // ww..bww
    1,     // ..b.bww
    46,    // b.b.bww
    -14,   // w.b.bww
    8,     // .bb.bww
    2,     // bbb.bww
    3,     // wbb.bww
    -10,   // .wb.bww
    -3,    // bwb.bww
    -41,   // wwb.bww
    2,     // ..w.bww
    -42,   // b.w.bww
    -15,   // w.w.bww
    8,     // .bw.bww
    0,     // bbw.bww
    18,    // wbw.bww
    -13,   // .ww.bww
    -18,   // bww.bww
    13,    // www.bww
    45,    // ...bbww
    -12,   // b..bbww
    -34,   // w..bbww
    -39,   // .b.bbww
    34,    // bb.bbww
    -54,   // wb.bbww
    37,    // .w.bbww
    1,     // bw.bbww
    -11,   // ww.bbww
    -7,    // ..bbbww
    -28,   // b.bbbww
    -23,   // w.bbbww
    13,    // .bbbbww
    -12,   // bbbbbww
    -3,    // wbbbbww
    -5,    // .wbbbww
    -8,    // bwbbbww
    7,     // wwbbbww
    -22,   // ..wbbww
    0,     // b.wbbww
    19,    // w.wbbww
    23,    // .bwbbww
    57,    // bbwbbww
    27,    // wbwbbww
    38,    // .wwbbww
    42,    // bwwbbww
    13,    // wwwbbww
    58,    // ...wbww
    5,     // b..wbww
    -11,   // w..wbww
    9,     // .b.wbww
    14,    // bb.wbww
    55,    // wb.wbww
    -10,   // .w.wbww
    -14,   // bw.wbww
    -66,   // ww.wbww
    -15,   // ..bwbww
    10,    // b.bwbww
    -35,   // w.bwbww
    51,    // .bbwbww
    12,    // bbbwbww
    21,    // wbbwbww
    -45,   // .wbwbww
    -8,    // bwbwbww
    3,     // wwbwbww
    16,    // ..wwbww
    -16,   // b.wwbww
    -33,   // w.wwbww
    7,     // .bwwbww
    -57,   // bbwwbww
    21,    // wbwwbww
    33,    // .wwwbww
    13,    // bwwwbww
    -6,    // wwwwbww
    -93,   // ....www
    26,    // b...www
    56,    // w...www
    -65,   // .b..www
    -8,    // bb..www
    -20,   // wb..www
    -7,    // .w..www
    -21,   // bw..www
    -63,   // ww..www
    -51,   // ..b.www
    -15,   // b.b.www
    -37,   // w.b.www
    -46,   // .bb.www
    0,     // bbb.www
    7,     // wbb.www
    -18,   // .wb.www
    27,    // bwb.www
    13,    // wwb.www
    -41,   // ..w.www
    -1,    // b.w.www
    14,    // w.w.www
    -47,   // .bw.www
    -2,    // bbw.www
    32,    // wbw.www
    -11,   // .ww.www
    -13,   // bww.www
    -19,   // www.www
    -5,    // ...bwww
    7,     // b..bwww
    5,     // w..bwww
    -20,   // .b.bwww
    33,    // bb.bwww
    45,    // wb.bwww
    -2,    // .w.bwww
    2,     // bw.bwww
    37,    // ww.bwww
    -18,   // ..bbwww
    -27,   // b.bbwww
    1,     // w.bbwww
    -5,    // .bbbwww
    12,    // bbbbwww
    30,    // wbbbwww
    21,    // .wbbwww
    7,     // bwbbwww
    13,    // wwbbwww
    24,    // ..wbwww
    29,    // b.wbwww
    17,    // w.wbwww
    -54,   // .bwbwww
    -12,   // bbwbwww
    23,    // wbwbwww
    24,    // .wwbwww
    19,    // bwwbwww
    15,    // wwwbwww
    -185,  // ...wwww
    -39,   // b..wwww
    -31,   // w..wwww
    -25,   // .b.wwww
    2,     // bb.wwww
    16,    // wb.wwww
    -4,    // .w.wwww
    41,    // bw.wwww
    -7,    // ww.wwww
    -35,   // ..bwwww
    -7,    // b.bwwww
    42,    // w.bwwww
    15,    // .bbwwww
    -12,   // bbbwwww
    6,     // wbbwwww
    9,     // .wbwwww
    23,    // bwbwwww
    -6,    // wwbwwww
    -43,   // ..wwwww
    -19,   // b.wwwww
    7,     // w.wwwww
    -1,    // .bwwwww
    12,    // bbwwwww
    14,    // wbwwwww
    2,     // .wwwwww
    15,    // bwwwwww
    -26,   // wwwwwww
    0,     // captures=0 threats=0
    68,    // captures=0 threats=1
    77,    // captures=0 threats=2
    144,   // captures=0 threats=3
    154,   // captures=0 threats=4
    0,     // captures=0 additional threats
    5,     // captures=1 threats=0
    81,    // captures=1 threats=1
    131,   // captures=1 threats=2
    294,   // captures=1 threats=3
    305,   // captures=1 threats=4
    166,   // captures=1 additional threats
    74,    // captures=2 threats=0
    97,    // captures=2 threats=1
    136,   // captures=2 threats=2
    306,   // captures=2 threats=3
    313,   // captures=2 threats=4
    113,   // captures=2 additional threats
    103,   // captures=3 threats=0
    191,   // captures=3 threats=1
    209,   // captures=3 threats=2
    312,   // captures=3 threats=3
    580,   // captures=3 threats=4
    101,   // captures=3 additional threats
    207,   // captures=4 threats=0
    229,   // captures=4 threats=1
    346,   // captures=4 threats=2
    627,   // captures=4 threats=3
    704,   // captures=4 threats=4
    82,    // captures=4 additional threats
].into_boxed_slice()
