vec![
    0,     // .......
    -1,    // b......
    1,     // w......
    -1,    // .b.....
    15,    // bb.....
    9,     // wb.....
    1,     // .w.....
    -9,    // bw.....
    -15,   // ww.....
    12,    // ..b....
    24,    // b.b....
    -12,   // w.b....
    9,     // .bb....
    91,    // bbb....
    -4,    // wbb....
    -29,   // .wb....
    -9,    // bwb....
    2,     // wwb....
    -12,   // ..w....
    12,    // b.w....
    -24,   // w.w....
    29,    // .bw....
    -2,    // bbw....
    9,     // wbw....
    -9,    // .ww....
    4,     // bww....
    -91,   // www....
    -8,    // ...b...
    -4,    // b..b...
    11,    // w..b...
    0,     // .b.b...
    12,    // bb.b...
    -29,   // wb.b...
    -3,    // .w.b...
    14,    // bw.b...
    -50,   // ww.b...
    -14,   // ..bb...
    4,     // b.bb...
    -38,   // w.bb...
    23,    // .bbb...
    173,   // bbbb...
    -49,   // wbbb...
    -35,   // .wbb...
    -5,    // bwbb...
    49,    // wwbb...
    3,     // ..wb...
    26,    // b.wb...
    4,     // w.wb...
    15,    // .bwb...
    -38,   // bbwb...
    -1,    // wbwb...
    34,    // .wwb...
    -14,   // bwwb...
    1,     // wwwb...
    8,     // ...w...
    -11,   // b..w...
    4,     // w..w...
    3,     // .b.w...
    50,    // bb.w...
    -14,   // wb.w...
    0,     // .w.w...
    29,    // bw.w...
    -12,   // ww.w...
    -3,    // ..bw...
    -4,    // b.bw...
    -26,   // w.bw...
    -34,   // .bbw...
    -1,    // bbbw...
    14,    // wbbw...
    -15,   // .wbw...
    1,     // bwbw...
    38,    // wwbw...
    14,    // ..ww...
    38,    // b.ww...
    -4,    // w.ww...
    35,    // .bww...
    -49,   // bbww...
    5,     // wbww...
    -23,   // .www...
    49,    // bwww...
    -173,  // wwww...
    12,    // ....b..
    -2,    // b...b..
    7,     // w...b..
    0,     // .b..b..
    -15,   // bb..b..
    -20,   // wb..b..
    3,     // .w..b..
    -22,   // bw..b..
    -37,   // ww..b..
    3,     // ..b.b..
    -16,   // b.b.b..
    -13,   // w.b.b..
    10,    // .bb.b..
    39,    // bbb.b..
    43,    // wbb.b..
    7,     // .wb.b..
    -12,   // bwb.b..
    -1,    // wwb.b..
    0,     // ..w.b..
    32,    // b.w.b..
    2,     // w.w.b..
    2,     // .bw.b..
    -8,    // bbw.b..
    -5,    // wbw.b..
    13,    // .ww.b..
    -7,    // bww.b..
    -43,   // www.b..
    -14,   // ...bb..
    0,     // b..bb..
    -7,    // w..bb..
    91,    // .b.bb..
    26,    // bb.bb..
    -40,   // wb.bb..
    -7,    // .w.bb..
    11,    // bw.bb..
    21,    // ww.bb..
    -14,   // ..bbb..
    51,    // b.bbb..
    -40,   // w.bbb..
    148,   // .bbbb..
    39,    // bbbbb..
    54,    // wbbbb..
    -51,   // .wbbb..
    -13,   // bwbbb..
    -9,    // wwbbb..
    6,     // ..wbb..
    -4,    // b.wbb..
    -1,    // w.wbb..
    -1,    // .bwbb..
    -4,    // bbwbb..
    -19,   // wbwbb..
    -30,   // .wwbb..
    -23,   // bwwbb..
    -11,   // wwwbb..
    -3,    // ...wb..
    -24,   // b..wb..
    -16,   // w..wb..
    -8,    // .b.wb..
    -4,    // bb.wb..
    9,     // wb.wb..
    -11,   // .w.wb..
    -3,    // bw.wb..
    -9,    // ww.wb..
    5,     // ..bwb..
    -7,    // b.bwb..
    -5,    // w.bwb..
    -24,   // .bbwb..
    -18,   // bbbwb..
    55,    // wbbwb..
    -16,   // .wbwb..
    14,    // bwbwb..
    -22,   // wwbwb..
    -6,    // ..wwb..
    -11,   // b.wwb..
    5,     // w.wwb..
    3,     // .bwwb..
    19,    // bbwwb..
    48,    // wbwwb..
    13,    // .wwwb..
    27,    // bwwwb..
    -38,   // wwwwb..
    -12,   // ....w..
    -7,    // b...w..
    2,     // w...w..
    -3,    // .b..w..
    37,    // bb..w..
    22,    // wb..w..
    0,     // .w..w..
    20,    // bw..w..
    15,    // ww..w..
    0,     // ..b.w..
    -2,    // b.b.w..
    -32,   // w.b.w..
    -13,   // .bb.w..
    43,    // bbb.w..
    7,     // wbb.w..
    -2,    // .wb.w..
    5,     // bwb.w..
    8,     // wwb.w..
    -3,    // ..w.w..
    13,    // b.w.w..
    16,    // w.w.w..
    -7,    // .bw.w..
    1,     // bbw.w..
    12,    // wbw.w..
    -10,   // .ww.w..
    -43,   // bww.w..
    -39,   // www.w..
    3,     // ...bw..
    16,    // b..bw..
    24,    // w..bw..
    11,    // .b.bw..
    9,     // bb.bw..
    3,     // wb.bw..
    8,     // .w.bw..
    -9,    // bw.bw..
    4,     // ww.bw..
    6,     // ..bbw..
    -5,    // b.bbw..
    11,    // w.bbw..
    -13,   // .bbbw..
    38,    // bbbbw..
    -27,   // wbbbw..
    -3,    // .wbbw..
    -48,   // bwbbw..
    -19,   // wwbbw..
    -5,    // ..wbw..
    5,     // b.wbw..
    7,     // w.wbw..
    16,    // .bwbw..
    22,    // bbwbw..
    -14,   // wbwbw..
    24,    // .wwbw..
    -55,   // bwwbw..
    18,    // wwwbw..
    14,    // ...ww..
    7,     // b..ww..
    0,     // w..ww..
    7,     // .b.ww..
    -21,   // bb.ww..
    -11,   // wb.ww..
    -91,   // .w.ww..
    40,    // bw.ww..
    -26,   // ww.ww..
    -6,    // ..bww..
    1,     // b.bww..
    4,     // w.bww..
    30,    // .bbww..
    11,    // bbbww..
    23,    // wbbww..
    1,     // .wbww..
    19,    // bwbww..
    4,     // wwbww..
    14,    // ..www..
    40,    // b.www..
    -51,   // w.www..
    51,    // .bwww..
    9,     // bbwww..
    13,    // wbwww..
    -148,  // .wwww..
    -54,   // bwwww..
    -39,   // wwwww..
    -1,    // .....b.
    -14,   // b....b.
    -58,   // w....b.
    18,    // .b...b.
    57,    // bb...b.
    13,    // wb...b.
    0,     // .w...b.
    9,     // bw...b.
    12,    // ww...b.
    0,     // ..b..b.
    1,     // b.b..b.
    4,     // w.b..b.
    19,    // .bb..b.
    0,     // bbb..b.
    48,    // wbb..b.
    8,     // .wb..b.
    -4,    // bwb..b.
    36,    // wwb..b.
    -3,    // ..w..b.
    -37,   // b.w..b.
    13,    // w.w..b.
    -10,   // .bw..b.
    -17,   // bbw..b.
    -46,   // wbw..b.
    27,    // .ww..b.
    -36,   // bww..b.
    -65,   // www..b.
    0,     // ...b.b.
    -11,   // b..b.b.
    43,    // w..b.b.
    25,    // .b.b.b.
    25,    // bb.b.b.
    -13,   // wb.b.b.
    -7,    // .w.b.b.
    -67,   // bw.b.b.
    -27,   // ww.b.b.
    91,    // ..bb.b.
    -31,   // b.bb.b.
    21,    // w.bb.b.
    15,    // .bbb.b.
    7,     // bbbb.b.
    53,    // wbbb.b.
    1,     // .wbb.b.
    29,    // bwbb.b.
    -32,   // wwbb.b.
    11,    // ..wb.b.
    -13,   // b.wb.b.
    -9,    // w.wb.b.
    16,    // .bwb.b.
    1,     // bbwb.b.
    -1,    // wbwb.b.
    29,    // .wwb.b.
    8,     // bwwb.b.
    -32,   // wwwb.b.
    3,     // ...w.b.
    13,    // b..w.b.
    -10,   // w..w.b.
    -45,   // .b.w.b.
    27,    // bb.w.b.
    1,     // wb.w.b.
    7,     // .w.w.b.
    2,     // bw.w.b.
    -13,   // ww.w.b.
    -8,    // ..bw.b.
    -13,   // b.bw.b.
    4,     // w.bw.b.
    -10,   // .bbw.b.
    2,     // bbbw.b.
    -2,    // wbbw.b.
    -21,   // .wbw.b.
    1,     // bwbw.b.
    15,    // wwbw.b.
    7,     // ..ww.b.
    -2,    // b.ww.b.
    -3,    // w.ww.b.
    -25,   // .bww.b.
    -31,   // bbww.b.
    28,    // wbww.b.
    -21,   // .www.b.
    13,    // bwww.b.
    -19,   // wwww.b.
    9,     // ....bb.
    -18,   // b...bb.
    -5,    // w...bb.
    19,    // .b..bb.
    11,    // bb..bb.
    25,    // wb..bb.
    -27,   // .w..bb.
    20,    // bw..bb.
    -16,   // ww..bb.
    10,    // ..b.bb.
    6,     // b.b.bb.
    24,    // w.b.bb.
    19,    // .bb.bb.
    3,     // bbb.bb.
    39,    // wbb.bb.
    2,     // .wb.bb.
    11,    // bwb.bb.
    11,    // wwb.bb.
    -13,   // ..w.bb.
    -8,    // b.w.bb.
    -60,   // w.w.bb.
    1,     // .bw.bb.
    16,    // bbw.bb.
    -15,   // wbw.bb.
    0,     // .ww.bb.
    4,     // bww.bb.
    -45,   // www.bb.
    23,    // ...bbb.
    -19,   // b..bbb.
    21,    // w..bbb.
    15,    // .b.bbb.
    -1,    // bb.bbb.
    44,    // wb.bbb.
    21,    // .w.bbb.
    24,    // bw.bbb.
    -11,   // ww.bbb.
    148,   // ..bbbb.
    30,    // b.bbbb.
    16,    // w.bbbb.
    11,    // .bbbbb.
    0,     // bbbbbb.
    30,    // wbbbbb.
    46,    // .wbbbb.
    22,    // bwbbbb.
    24,    // wwbbbb.
    -13,   // ..wbbb.
    3,     // b.wbbb.
    -11,   // w.wbbb.
    -1,    // .bwbbb.
    -19,   // bbwbbb.
    -36,   // wbwbbb.
    -5,    // .wwbbb.
    -31,   // bwwbbb.
    3,     // wwwbbb.
    -34,   // ...wbb.
    19,    // b..wbb.
    19,    // w..wbb.
    -10,   // .b.wbb.
    25,    // bb.wbb.
    -11,   // wb.wbb.
    -29,   // .w.wbb.
    -22,   // bw.wbb.
    -18,   // ww.wbb.
    -24,   // ..bwbb.
    -1,    // b.bwbb.
    -38,   // w.bwbb.
    9,     // .bbwbb.
    -20,   // bbbwbb.
    -19,   // wbbwbb.
    7,     // .wbwbb.
    -5,    // bwbwbb.
    41,    // wwbwbb.
    30,    // ..wwbb.
    -20,   // b.wwbb.
    -1,    // w.wwbb.
    -25,   // .bwwbb.
    -27,   // bbwwbb.
    26,    // wbwwbb.
    5,     // .wwwbb.
    -14,   // bwwwbb.
    8,     // wwwwbb.
    29,    // ....wb.
    20,    // b...wb.
    4,     // w...wb.
    -10,   // .b..wb.
    -20,   // bb..wb.
    -36,   // wb..wb.
    -8,    // .w..wb.
    -30,   // bw..wb.
    1,     // ww..wb.
    2,     // ..b.wb.
    -24,   // b.b.wb.
    -27,   // w.b.wb.
    1,     // .bb.wb.
    12,    // bbb.wb.
    -40,   // wbb.wb.
    0,     // .wb.wb.
    -27,   // bwb.wb.
    -1,    // wwb.wb.
    -7,    // ..w.wb.
    62,    // b.w.wb.
    37,    // w.w.wb.
    3,     // .bw.wb.
    1,     // bbw.wb.
    -23,   // wbw.wb.
    -2,    // .ww.wb.
    1,     // bww.wb.
    -45,   // www.wb.
    15,    // ...bwb.
    3,     // b..bwb.
    0,     // w..bwb.
    16,    // .b.bwb.
    -3,    // bb.bwb.
    15,    // wb.bwb.
    21,    // .w.bwb.
    16,    // bw.bwb.
    -21,   // ww.bwb.
    -1,    // ..bbwb.
    -31,   // b.bbwb.
    15,    // w.bbwb.
    -1,    // .bbbwb.
    -5,    // bbbbwb.
    9,     // wbbbwb.
    -24,   // .wbbwb.
    -24,   // bwbbwb.
    25,    // wwbbwb.
    16,    // ..wbwb.
    18,    // b.wbwb.
    -1,    // w.wbwb.
    -35,   // .bwbwb.
    40,    // bbwbwb.
    12,    // wbwbwb.
    -7,    // .wwbwb.
    32,    // bwwbwb.
    -50,   // wwwbwb.
    35,    // ...wwb.
    -36,   // b..wwb.
    23,    // w..wwb.
    -25,   // .b.wwb.
    -11,   // bb.wwb.
    2,     // wb.wwb.
    -1,    // .w.wwb.
    -35,   // bw.wwb.
    9,     // ww.wwb.
    3,     // ..bwwb.
    8,     // b.bwwb.
    -9,    // w.bwwb.
    -25,   // .bbwwb.
    -28,   // bbbwwb.
    -18,   // wbbwwb.
    24,    // .wbwwb.
    -11,   // bwbwwb.
    16,    // wwbwwb.
    51,    // ..wwwb.
    37,    // b.wwwb.
    -31,   // w.wwwb.
    -40,   // .bwwwb.
    1,     // bbwwwb.
    6,     // wbwwwb.
    -46,   // .wwwwb.
    93,    // bwwwwb.
    -5,    // wwwwwb.
    1,     // .....w.
    58,    // b....w.
    14,    // w....w.
    0,     // .b...w.
    -12,   // bb...w.
    -9,    // wb...w.
    -18,   // .w...w.
    -13,   // bw...w.
    -57,   // ww...w.
    3,     // ..b..w.
    -13,   // b.b..w.
    37,    // w.b..w.
    -27,   // .bb..w.
    65,    // bbb..w.
    36,    // wbb..w.
    10,    // .wb..w.
    46,    // bwb..w.
    17,    // wwb..w.
    0,     // ..w..w.
    -4,    // b.w..w.
    -1,    // w.w..w.
    -8,    // .bw..w.
    -36,   // bbw..w.
    4,     // wbw..w.
    -19,   // .ww..w.
    -48,   // bww..w.
    0,     // www..w.
    -3,    // ...b.w.
    10,    // b..b.w.
    -13,   // w..b.w.
    -7,    // .b.b.w.
    13,    // bb.b.w.
    -2,    // wb.b.w.
    45,    // .w.b.w.
    -1,    // bw.b.w.
    -27,   // ww.b.w.
    -7,    // ..bb.w.
    3,     // b.bb.w.
    2,     // w.bb.w.
    21,    // .bbb.w.
    19,    // bbbb.w.
    -13,   // wbbb.w.
    25,    // .wbb.w.
    -28,   // bwbb.w.
    31,    // wwbb.w.
    8,     // ..wb.w.
    -4,    // b.wb.w.
    13,    // w.wb.w.
    21,    // .bwb.w.
    -15,   // bbwb.w.
    -1,    // wbwb.w.
    10,    // .wwb.w.
    2,     // bwwb.w.
    -2,    // wwwb.w.
    0,     // ...w.w.
    -43,   // b..w.w.
    11,    // w..w.w.
    7,     // .b.w.w.
    27,    // bb.w.w.
    67,    // wb.w.w.
    -25,   // .w.w.w.
    13,    // bw.w.w.
    -25,   // ww.w.w.
    -11,   // ..bw.w.
    9,     // b.bw.w.
    13,    // w.bw.w.
    -29,   // .bbw.w.
    32,    // bbbw.w.
    -8,    // wbbw.w.
    -16,   // .wbw.w.
    1,     // bwbw.w.
    -1,    // wwbw.w.
    -91,   // ..ww.w.
    -21,   // b.ww.w.
    31,    // w.ww.w.
    -1,    // .bww.w.
    32,    // bbww.w.
    -29,   // wbww.w.
    -15,   // .www.w.
    -53,   // bwww.w.
    -7,    // wwww.w.
    -29,   // ....bw.
    -4,    // b...bw.
    -20,   // w...bw.
    8,     // .b..bw.
    -1,    // bb..bw.
    30,    // wb..bw.
    10,    // .w..bw.
    36,    // bw..bw.
    20,    // ww..bw.
    7,     // ..b.bw.
    -37,   // b.b.bw.
    -62,   // w.b.bw.
    2,     // .bb.bw.
    45,    // bbb.bw.
    -1,    // wbb.bw.
    -3,    // .wb.bw.
    23,    // bwb.bw.
    -1,    // wwb.bw.
    -2,    // ..w.bw.
    27,    // b.w.bw.
    24,    // w.w.bw.
    0,     // .bw.bw.
    1,     // bbw.bw.
    27,    // wbw.bw.
    -1,    // .ww.bw.
    40,    // bww.bw.
    -12,   // www.bw.
    -35,   // ...bbw.
    -23,   // b..bbw.
    36,    // w..bbw.
    1,     // .b.bbw.
    -9,    // bb.bbw.
    35,    // wb.bbw.
    25,    // .w.bbw.
    -2,    // bw.bbw.
    11,    // ww.bbw.
    -51,   // ..bbbw.
    31,    // b.bbbw.
    -37,   // w.bbbw.
    46,    // .bbbbw.
    5,     // bbbbbw.
    -93,   // wbbbbw.
    40,    // .wbbbw.
    -6,    // bwbbbw.
    -1,    // wwbbbw.
    -3,    // ..wbbw.
    9,     // b.wbbw.
    -8,    // w.wbbw.
    -24,   // .bwbbw.
    -16,   // bbwbbw.
    11,    // wbwbbw.
    25,    // .wwbbw.
    18,    // bwwbbw.
    28,    // wwwbbw.
    -15,   // ...wbw.
    0,     // b..wbw.
    -3,    // w..wbw.
    -21,   // .b.wbw.
    21,    // bb.wbw.
    -16,   // wb.wbw.
    -16,   // .w.wbw.
    -15,   // bw.wbw.
    3,     // ww.wbw.
    -16,   // ..bwbw.
    1,     // b.bwbw.
    -18,   // w.bwbw.
    7,     // .bbwbw.
    50,    // bbbwbw.
    -32,   // wbbwbw.
    35,    // .wbwbw.
    -12,   // bwbwbw.
    -40,   // wwbwbw.
    1,     // ..wwbw.
    -15,   // b.wwbw.
    31,    // w.wwbw.
    24,    // .bwwbw.
    -25,   // bbwwbw.
    24,    // wbwwbw.
    1,     // .wwwbw.
    -9,    // bwwwbw.
    5,     // wwwwbw.
    -9,    // ....ww.
    5,     // b...ww.
    18,    // w...ww.
    27,    // .b..ww.
    16,    // bb..ww.
    -20,   // wb..ww.
    -19,   // .w..ww.
    -25,   // bw..ww.
    -11,   // ww..ww.
    13,    // ..b.ww.
    60,    // b.b.ww.
    8,     // w.b.ww.
    0,     // .bb.ww.
    45,    // bbb.ww.
    -4,    // wbb.ww.
    -1,    // .wb.ww.
    15,    // bwb.ww.
    -16,   // wwb.ww.
    -10,   // ..w.ww.
    -24,   // b.w.ww.
    -6,    // w.w.ww.
    -2,    // .bw.ww.
    -11,   // bbw.ww.
    -11,   // wbw.ww.
    -19,   // .ww.ww.
    -39,   // bww.ww.
    -3,    // www.ww.
    34,    // ...bww.
    -19,   // b..bww.
    -19,   // w..bww.
    29,    // .b.bww.
    18,    // bb.bww.
    22,    // wb.bww.
    10,    // .w.bww.
    11,    // bw.bww.
    -25,   // ww.bww.
    -30,   // ..bbww.
    1,     // b.bbww.
    20,    // w.bbww.
    -5,    // .bbbww.
    -8,    // bbbbww.
    14,    // wbbbww.
    25,    // .wbbww.
    -26,   // bwbbww.
    27,    // wwbbww.
    24,    // ..wbww.
    38,    // b.wbww.
    1,     // w.wbww.
    -7,    // .bwbww.
    -41,   // bbwbww.
    5,     // wbwbww.
    -9,    // .wwbww.
    19,    // bwwbww.
    20,    // wwwbww.
    -23,   // ...www.
    -21,   // b..www.
    19,    // w..www.
    -21,   // .b.www.
    11,    // bb.www.
    -24,   // wb.www.
    -15,   // .w.www.
    -44,   // bw.www.
    1,     // ww.www.
    13,    // ..bwww.
    11,    // b.bwww.
    -3,    // w.bwww.
    5,     // .bbwww.
    -3,    // bbbwww.
    31,    // wbbwww.
    1,     // .wbwww.
    36,    // bwbwww.
    19,    // wwbwww.
    -148,  // ..wwww.
    -16,   // b.wwww.
    -30,   // w.wwww.
    -46,   // .bwwww.
    -24,   // bbwwww.
    -22,   // wbwwww.
    -11,   // .wwwww.
    -30,   // bwwwww.
    0,     // wwwwww.
    -1,    // ......b
    10,    // b.....b
    0,     // w.....b
    -14,   // .b....b
    26,    // bb....b
    21,    // wb....b
    58,    // .w....b
    -2,    // bw....b
    7,     // ww....b
    -2,    // ..b...b
    -5,    // b.b...b
    -13,   // w.b...b
    -18,   // .bb...b
    -56,   // bbb...b
    -30,   // wbb...b
    -4,    // .wb...b
    -37,   // bwb...b
    -13,   // wwb...b
    -7,    // ..w...b
    -22,   // b.w...b
    -11,   // w.w...b
    20,    // .bw...b
    -1,    // bbw...b
    -14,   // wbw...b
    5,     // .ww...b
    -8,    // bww...b
    18,    // www...b
    -4,    // ...b..b
    10,    // b..b..b
    13,    // w..b..b
    -11,   // .b.b..b
    11,    // bb.b..b
    13,    // wb.b..b
    10,    // .w.b..b
    -30,   // bw.b..b
    -10,   // ww.b..b
    0,     // ..bb..b
    9,     // b.bb..b
    -24,   // w.bb..b
    -19,   // .bbb..b
    22,    // bbbb..b
    -7,    // wbbb..b
    -23,   // .wbb..b
    -23,   // bwbb..b
    -3,    // wwbb..b
    16,    // ..wb..b
    33,    // b.wb..b
    -10,   // w.wb..b
    3,     // .bwb..b
    17,    // bbwb..b
    -12,   // wbwb..b
    -19,   // .wwb..b
    8,     // bwwb..b
    -3,    // wwwb..b
    -11,   // ...w..b
    -30,   // b..w..b
    -13,   // w..w..b
    13,    // .b.w..b
    20,    // bb.w..b
    -9,    // wb.w..b
    -43,   // .w.w..b
    -11,   // bw.w..b
    -31,   // ww.w..b
    -24,   // ..bw..b
    8,     // b.bw..b
    -18,   // w.bw..b
    19,    // .bbw..b
    -3,    // bbbw..b
    -31,   // wbbw..b
    0,     // .wbw..b
    -40,   // bwbw..b
    4,     // wwbw..b
    7,     // ..ww..b
    20,    // b.ww..b
    -14,   // w.ww..b
    -36,   // .bww..b
    26,    // bbww..b
    36,    // wbww..b
    -21,   // .www..b
    2,     // bwww..b
    -37,   // wwww..b
    24,    // ....b.b
    -5,    // b...b.b
    11,    // w...b.b
    1,     // .b..b.b
    -38,   // bb..b.b
    -2,    // wb..b.b
    -13,   // .w..b.b
    53,    // bw..b.b
    -28,   // ww..b.b
    -16,   // ..b.b.b
    -12,   // b.b.b.b
    12,    // w.b.b.b
    6,     // .bb.b.b
    -17,   // bbb.b.b
    -1,    // wbb.b.b
    -37,   // .wb.b.b
    4,     // bwb.b.b
    41,    // wwb.b.b
    -2,    // ..w.b.b
    -8,    // b.w.b.b
    0,     // w.w.b.b
    -24,   // .bw.b.b
    17,    // bbw.b.b
    -10,   // wbw.b.b
    60,    // .ww.b.b
    4,     // bww.b.b
    8,     // www.b.b
    4,     // ...bb.b
    9,     // b..bb.b
    14,    // w..bb.b
    -31,   // .b.bb.b
    4,     // bb.bb.b
    -20,   // wb.bb.b
    3,     // .w.bb.b
    13,    // bw.bb.b
    -21,   // ww.bb.b
    51,    // ..bbb.b
    30,    // b.bbb.b
    27,    // w.bbb.b
    30,    // .bbbb.b
    6,     // bbbbb.b
    -19,   // wbbbb.b
    31,    // .wbbb.b
    15,    // bwbbb.b
    -23,   // wwbbb.b
    -5,    // ..wbb.b
    37,    // b.wbb.b
    5,     // w.wbb.b
    -31,   // .bwbb.b
    33,    // bbwbb.b
    -13,   // wbwbb.b
    1,     // .wwbb.b
    20,    // bwwbb.b
    -22,   // wwwbb.b
    -4,    // ...wb.b
    8,     // b..wb.b
    10,    // w..wb.b
    -13,   // .b.wb.b
    -7,    // bb.wb.b
    -17,   // wb.wb.b
    9,     // .w.wb.b
    36,    // bw.wb.b
    44,    // ww.wb.b
    -7,    // ..bwb.b
    5,     // b.bwb.b
    -36,   // w.bwb.b
    -1,    // .bbwb.b
    -21,   // bbbwb.b
    13,    // wbbwb.b
    1,     // .wbwb.b
    -11,   // bwbwb.b
    12,    // wwbwb.b
    1,     // ..wwb.b
    10,    // b.wwb.b
    -5,    // w.wwb.b
    8,     // .bwwb.b
    -27,   // bbwwb.b
    -22,   // wbwwb.b
    11,    // .wwwb.b
    -9,    // bwwwb.b
    -9,    // wwwwb.b
    12,    // ....w.b
    -22,   // b...w.b
    13,    // w...w.b
    -37,   // .b..w.b
    44,    // bb..w.b
    17,    // wb..w.b
    -4,    // .w..w.b
    6,     // bw..w.b
    5,     // ww..w.b
    32,    // ..b.w.b
    -8,    // b.b.w.b
    0,     // w.b.w.b
    -8,    // .bb.w.b
    42,    // bbb.w.b
    14,    // wbb.w.b
    27,    // .wb.w.b
    25,    // bwb.w.b
    -40,   // wwb.w.b
    13,    // ..w.w.b
    -59,   // b.w.w.b
    -12,   // w.w.w.b
    62,    // .bw.w.b
    20,    // bbw.w.b
    0,     // wbw.w.b
    -24,   // .ww.w.b
    -5,    // bww.w.b
    -4,    // www.w.b
    26,    // ...bw.b
    33,    // b..bw.b
    18,    // w..bw.b
    -13,   // .b.bw.b
    -7,    // bb.bw.b
    24,    // wb.bw.b
    -4,    // .w.bw.b
    24,    // bw.bw.b
    19,    // ww.bw.b
    -4,    // ..bbw.b
    37,    // b.bbw.b
    -42,   // w.bbw.b
    3,     // .bbbw.b
    -44,   // bbbbw.b
    -12,   // wbbbw.b
    9,     // .wbbw.b
    -6,    // bwbbw.b
    8,     // wwbbw.b
    5,     // ..wbw.b
    -11,   // b.wbw.b
    36,    // w.wbw.b
    18,    // .bwbw.b
    25,    // bbwbw.b
    -17,   // wbwbw.b
    38,    // .wwbw.b
    -15,   // bwwbw.b
    23,    // wwwbw.b
    38,    // ...ww.b
    20,    // b..ww.b
    24,    // w..ww.b
    -2,    // .b.ww.b
    5,     // bb.ww.b
    2,     // wb.ww.b
    -21,   // .w.ww.b
    -15,   // bw.ww.b
    -12,   // ww.ww.b
    -11,   // ..bww.b
    10,    // b.bww.b
    42,    // w.bww.b
    -20,   // .bbww.b
    -6,    // bbbww.b
    14,    // wbbww.b
    -15,   // .wbww.b
    4,     // bwbww.b
    -12,   // wwbww.b
    40,    // ..www.b
    15,    // b.www.b
    -27,   // w.www.b
    37,    // .bwww.b
    17,    // bbwww.b
    -8,    // wbwww.b
    -16,   // .wwww.b
    5,     // bwwww.b
    -21,   // wwwww.b
    15,    // .....bb
    26,    // b....bb
    -7,    // w....bb
    57,    // .b...bb
    -24,   // bb...bb
    22,    // wb...bb
    -12,   // .w...bb
    -12,   // bw...bb
    0,     // ww...bb
    -15,   // ..b..bb
    -38,   // b.b..bb
    -5,    // w.b..bb
    11,    // .bb..bb
    58,    // bbb..bb
    -28,   // wbb..bb
    -1,    // .wb..bb
    -11,   // bwb..bb
    -5,    // wwb..bb
    37,    // ..w..bb
    44,    // b.w..bb
    28,    // w.w..bb
    -20,   // .bw..bb
    13,    // bbw..bb
    8,     // wbw..bb
    16,    // .ww..bb
    25,    // bww..bb
    -8,    // www..bb
    12,    // ...b.bb
    11,    // b..b.bb
    31,    // w..b.bb
    25,    // .b.b.bb
    -19,   // bb.b.bb
    -13,   // wb.b.bb
    13,    // .w.b.bb
    0,     // bw.b.bb
    8,     // ww.b.bb
    26,    // ..bb.bb
    4,     // b.bb.bb
    12,    // w.bb.bb
    -1,    // .bbb.bb
    6,     // bbbb.bb
    10,    // wbbb.bb
    -9,    // .wbb.bb
    28,    // bwbb.bb
    26,    // wwbb.bb
    9,     // ..wb.bb
    -7,    // b.wb.bb
    -44,   // w.wb.bb
    -3,    // .bwb.bb
    66,    // bbwb.bb
    -43,   // wbwb.bb
    18,    // .wwb.bb
    5,     // bwwb.bb
    34,    // wwwb.bb
    50,    // ...w.bb
    20,    // b..w.bb
    10,    // w..w.bb
    27,    // .b.w.bb
    38,    // bb.w.bb
    -10,   // wb.w.bb
    27,    // .w.w.bb
    -31,   // bw.w.bb
    -8,    // ww.w.bb
    -4,    // ..bw.bb
    -7,    // b.bw.bb
    -19,   // w.bw.bb
    25,    // .bbw.bb
    -44,   // bbbw.bb
    22,    // wbbw.bb
    21,    // .wbw.bb
    19,    // bwbw.bb
    11,    // wwbw.bb
    -21,   // ..ww.bb
    5,     // b.ww.bb
    21,    // w.ww.bb
    -11,   // .bww.bb
    15,    // bbww.bb
    29,    // wbww.bb
    11,    // .www.bb
    4,     // bwww.bb
    3,     // wwww.bb
    91,    // ....bbb
    -56,   // b...bbb
    -18,   // w...bbb
    0,     // .b..bbb
    58,    // bb..bbb
    2,     // wb..bbb
    65,    // .w..bbb
    31,    // bw..bbb
    8,     // ww..bbb
    39,    // ..b.bbb
    -17,   // b.b.bbb
    4,     // w.b.bbb
    3,     // .bb.bbb
    32,    // bbb.bbb
    5,     // wbb.bbb
    45,    // .wb.bbb
    -26,   // bwb.bbb
    -2,    // wwb.bbb
    43,    // ..w.bbb
    42,    // b.w.bbb
    -8,    // w.w.bbb
    12,    // .bw.bbb
    -17,   // bbw.bbb
    -34,   // wbw.bbb
    45,    // .ww.bbb
    -22,   // bww.bbb
    0,     // www.bbb
    173,   // ...bbbb
    22,    // b..bbbb
    37,    // w..bbbb
    7,     // .b.bbbb
    6,     // bb.bbbb
    -40,   // wb.bbbb
    19,    // .w.bbbb
    -26,   // bw.bbbb
    -3,    // ww.bbbb
    39,    // ..bbbbb
    6,     // b.bbbbb
    21,    // w.bbbbb
    0,     // .bbbbbb
    22,    // bbbbbbb
    -12,   // wbbbbbb
    5,     // .wbbbbb
    -15,   // bwbbbbb
    -6,    // wwbbbbb
    38,    // ..wbbbb
    -44,   // b.wbbbb
    9,     // w.wbbbb
    -5,    // .bwbbbb
    9,     // bbwbbbb
    -19,   // wbwbbbb
    -8,    // .wwbbbb
    -8,    // bwwbbbb
    10,    // wwwbbbb
    -1,    // ...wbbb
    -3,    // b..wbbb
    3,     // w..wbbb
    2,     // .b.wbbb
    -44,   // bb.wbbb
    -5,    // wb.wbbb
    32,    // .w.wbbb
    -44,   // bw.wbbb
    -34,   // ww.wbbb
    -18,   // ..bwbbb
    -21,   // b.bwbbb
    -23,   // w.bwbbb
    -20,   // .bbwbbb
    -5,    // bbbwbbb
    -17,   // wbbwbbb
    50,    // .wbwbbb
    -23,   // bwbwbbb
    2,     // wwbwbbb
    11,    // ..wwbbb
    -6,    // b.wwbbb
    22,    // w.wwbbb
    -28,   // .bwwbbb
    -10,   // bbwwbbb
    -6,    // wbwwbbb
    -3,    // .wwwbbb
    -29,   // bwwwbbb
    -10,   // wwwwbbb
    -2,    // ....wbb
    -1,    // b...wbb
    13,    // w...wbb
    -17,   // .b..wbb
    13,    // bb..wbb
    -22,   // wb..wbb
    -36,   // .w..wbb
    1,     // bw..wbb
    5,     // ww..wbb
    -8,    // ..b.wbb
    17,    // b.b.wbb
    40,    // w.b.wbb
    16,    // .bb.wbb
    -17,   // bbb.wbb
    27,    // wbb.wbb
    1,     // .wb.wbb
    -23,   // bwb.wbb
    0,     // wwb.wbb
    1,     // ..w.wbb
    20,    // b.w.wbb
    -41,   // w.w.wbb
    1,     // .bw.wbb
    31,    // bbw.wbb
    7,     // wbw.wbb
    -11,   // .ww.wbb
    -5,    // bww.wbb
    2,     // www.wbb
    -38,   // ...bwbb
    17,    // b..bwbb
    -4,    // w..bwbb
    1,     // .b.bwbb
    66,    // bb.bwbb
    2,     // wb.bwbb
    -15,   // .w.bwbb
    -55,   // bw.bwbb
    -11,   // ww.bwbb
    -4,    // ..bbwbb
    33,    // b.bbwbb
    12,    // w.bbwbb
    -19,   // .bbbwbb
    9,     // bbbbwbb
    -30,   // wbbbwbb
    -16,   // .wbbwbb
    -21,   // bwbbwbb
    55,    // wwbbwbb
    22,    // ..wbwbb
    25,    // b.wbwbb
    -12,   // w.wbwbb
    40,    // .bwbwbb
    1,     // bbwbwbb
    18,    // wbwbwbb
    -41,   // .wwbwbb
    -18,   // bwwbwbb
    -2,    // wwwbwbb
    -49,   // ...wwbb
    26,    // b..wwbb
    3,     // w..wwbb
    -31,   // .b.wwbb
    15,    // bb.wwbb
    4,     // wb.wwbb
    32,    // .w.wwbb
    64,    // bw.wwbb
    -26,   // ww.wwbb
    19,    // ..bwwbb
    -27,   // b.bwwbb
    -8,    // w.bwwbb
    -27,   // .bbwwbb
    -10,   // bbbwwbb
    -30,   // wbbwwbb
    -25,   // .wbwwbb
    -10,   // bwbwwbb
    -55,   // wwbwwbb
    9,     // ..wwwbb
    17,    // b.wwwbb
    23,    // w.wwwbb
    1,     // .bwwwbb
    -10,   // bbwwwbb
    5,     // wbwwwbb
    -24,   // .wwwwbb
    -1,    // bwwwwbb
    6,     // wwwwwbb
    -9,    // .....wb
    -2,    // b....wb
    -21,   // w....wb
    9,     // .b...wb
    -12,   // bb...wb
    0,     // wb...wb
    -13,   // .w...wb
    45,    // bw...wb
    -22,   // ww...wb
    -22,   // ..b..wb
    53,    // b.b..wb
    -17,   // w.b..wb
    20,    // .bb..wb
    31,    // bbb..wb
    7,     // wbb..wb
    36,    // .wb..wb
    -9,    // bwb..wb
    22,    // wwb..wb
    20,    // ..w..wb
    6,     // b.w..wb
    2,     // w.w..wb
    -30,   // .bw..wb
    1,     // bbw..wb
    -38,   // wbw..wb
    -25,   // .ww..wb
    32,    // bww..wb
    -2,    // www..wb
    14,    // ...b.wb
    -30,   // b..b.wb
    9,     // w..b.wb
    -67,   // .b.b.wb
    0,     // bb.b.wb
    11,    // wb.b.wb
    -1,    // .w.b.wb
    -6,    // bw.b.wb
    10,    // ww.b.wb
    11,    // ..bb.wb
    13,    // b.bb.wb
    -2,    // w.bb.wb
    24,    // .bbb.wb
    -26,   // bbbb.wb
    -2,    // wbbb.wb
    -2,    // .wbb.wb
    2,     // bwbb.wb
    -4,    // wwbb.wb
    -9,    // ..wb.wb
    24,    // b.wb.wb
    17,    // w.wb.wb
    16,    // .bwb.wb
    -55,   // bbwb.wb
    -7,    // wbwb.wb
    11,    // .wwb.wb
    -37,   // bwwb.wb
    5,     // wwwb.wb
    29,    // ...w.wb
    -11,   // b..w.wb
    -13,   // w..w.wb
    2,     // .b.w.wb
    -31,   // bb.w.wb
    -11,   // wb.w.wb
    13,    // .w.w.wb
    -8,    // bw.w.wb
    13,    // ww.w.wb
    -3,    // ..bw.wb
    36,    // b.bw.wb
    -24,   // w.bw.wb
    -22,   // .bbw.wb
    -44,   // bbbw.wb
    1,     // wbbw.wb
    -15,   // .wbw.wb
    -26,   // bwbw.wb
    -2,    // wwbw.wb
    40,    // ..ww.wb
    -15,   // b.ww.wb
    20,    // w.ww.wb
    -35,   // .bww.wb
    64,    // bbww.wb
    29,    // wbww.wb
    -44,   // .www.wb
    8,     // bwww.wb
    40,    // wwww.wb
    -9,    // ....bwb
    -37,   // b...bwb
    14,    // w...bwb
    -4,    // .b..bwb
    -11,   // bb..bwb
    38,    // wb..bwb
    46,    // .w..bwb
    -9,    // bw..bwb
    -8,    // ww..bwb
    -12,   // ..b.bwb
    4,     // b.b.bwb
    0,     // w.b.bwb
    11,    // .bb.bwb
    -26,   // bbb.bwb
    1,     // wbb.bwb
    23,    // .wb.bwb
    -11,   // bwb.bwb
    -7,    // wwb.bwb
    5,     // ..w.bwb
    25,    // b.w.bwb
    10,    // w.w.bwb
    -27,   // .bw.bwb
    -23,   // bbw.bwb
    0,     // wbw.bwb
    15,    // .ww.bwb
    -24,   // bww.bwb
    34,    // www.bwb
    -5,    // ...bbwb
    -23,   // b..bbwb
    -36,   // w..bbwb
    29,    // .b.bbwb
    28,    // bb.bbwb
    -29,   // wb.bbwb
    -28,   // .w.bbwb
    2,     // bw.bbwb
    -29,   // ww.bbwb
    -13,   // ..bbbwb
    15,    // b.bbbwb
    8,     // w.bbbwb
    22,    // .bbbbwb
    -15,   // bbbbbwb
    18,    // wbbbbwb
    -6,    // .wbbbwb
    -18,   // bwbbbwb
    -5,    // wwbbbwb
    -48,   // ..wbbwb
    -6,    // b.wbbwb
    22,    // w.wbbwb
    -24,   // .bwbbwb
    -21,   // bbwbbwb
    -14,   // wbwbbwb
    -26,   // .wwbbwb
    31,    // bwwbbwb
    6,     // wwwbbwb
    1,     // ...wbwb
    -40,   // b..wbwb
    12,    // w..wbwb
    1,     // .b.wbwb
    19,    // bb.wbwb
    7,     // wb.wbwb
    1,     // .w.wbwb
    -26,   // bw.wbwb
    43,    // ww.wbwb
    14,    // ..bwbwb
    -11,   // b.bwbwb
    17,    // w.bwbwb
    -5,    // .bbwbwb
    -23,   // bbbwbwb
    -18,   // wbbwbwb
    -12,   // .wbwbwb
    -1,    // bwbwbwb
    -18,   // wwbwbwb
    19,    // ..wwbwb
    4,     // b.wwbwb
    13,    // w.wwbwb
    -11,   // .bwwbwb
    -10,   // bbwwbwb
    14,    // wbwwbwb
    36,    // .wwwbwb
    32,    // bwwwbwb
    19,    // wwwwbwb
    4,     // ....wwb
    -8,    // b...wwb
    30,    // w...wwb
    -36,   // .b..wwb
    25,    // bb..wwb
    -7,    // wb..wwb
    -48,   // .w..wwb
    32,    // bw..wwb
    28,    // ww..wwb
    -7,    // ..b.wwb
    4,     // b.b.wwb
    -14,   // w.b.wwb
    4,     // .bb.wwb
    -22,   // bbb.wwb
    0,     // wbb.wwb
    40,    // .wb.wwb
    -24,   // bwb.wwb
    -27,   // wwb.wwb
    -43,   // ..w.wwb
    -5,    // b.w.wwb
    1,     // w.w.wwb
    1,     // .bw.wwb
    -5,    // bbw.wwb
    -1,    // wbw.wwb
    -39,   // .ww.wwb
    -30,   // bww.wwb
    -5,    // www.wwb
    -14,   // ...bwwb
    8,     // b..bwwb
    31,    // w..bwwb
    8,     // .b.bwwb
    5,     // bb.bwwb
    -1,    // wb.bwwb
    2,     // .w.bwwb
    -37,   // bw.bwwb
    -22,   // ww.bwwb
    -23,   // ..bbwwb
    20,    // b.bbwwb
    -14,   // w.bbwwb
    -31,   // .bbbwwb
    -8,    // bbbbwwb
    -7,    // wbbbwwb
    18,    // .wbbwwb
    31,    // bwbbwwb
    30,    // wwbbwwb
    -55,   // ..wbwwb
    -15,   // b.wbwwb
    -13,   // w.wbwwb
    32,    // .bwbwwb
    -18,   // bbwbwwb
    18,    // wbwbwwb
    19,    // .wwbwwb
    29,    // bwwbwwb
    17,    // wwwbwwb
    49,    // ...wwwb
    2,     // b..wwwb
    7,     // w..wwwb
    13,    // .b.wwwb
    4,     // bb.wwwb
    2,     // wb.wwwb
    -53,   // .w.wwwb
    8,     // bw.wwwb
    -10,   // ww.wwwb
    27,    // ..bwwwb
    -9,    // b.bwwwb
    12,    // w.bwwwb
    -14,   // .bbwwwb
    -29,   // bbbwwwb
    7,     // wbbwwwb
    -9,    // .wbwwwb
    32,    // bwbwwwb
    30,    // wwbwwwb
    -54,   // ..wwwwb
    5,     // b.wwwwb
    19,    // w.wwwwb
    93,    // .bwwwwb
    -1,    // bbwwwwb
    -18,   // wbwwwwb
    -30,   // .wwwwwb
    12,    // bwwwwwb
    12,    // wwwwwwb
    1,     // ......w
    0,     // b.....w
    -10,   // w.....w
    -58,   // .b....w
    -7,    // bb....w
    2,     // wb....w
    14,    // .w....w
    -21,   // bw....w
    -26,   // ww....w
    7,     // ..b...w
    11,    // b.b...w
    22,    // w.b...w
    -5,    // .bb...w
    -18,   // bbb...w
    8,     // wbb...w
    -20,   // .wb...w
    14,    // bwb...w
    1,     // wwb...w
    2,     // ..w...w
    13,    // b.w...w
    5,     // w.w...w
    4,     // .bw...w
    13,    // bbw...w
    37,    // wbw...w
    18,    // .ww...w
    30,    // bww...w
    56,    // www...w
    11,    // ...b..w
    13,    // b..b..w
    30,    // w..b..w
    43,    // .b.b..w
    31,    // bb.b..w
    11,    // wb.b..w
    -13,   // .w.b..w
    9,     // bw.b..w
    -20,   // ww.b..w
    -7,    // ..bb..w
    14,    // b.bb..w
    -20,   // w.bb..w
    21,    // .bbb..w
    37,    // bbbb..w
    -2,    // wbbb..w
    36,    // .wbb..w
    -36,   // bwbb..w
    -26,   // wwbb..w
    24,    // ..wb..w
    18,    // b.wb..w
    -8,    // w.wb..w
    0,     // .bwb..w
    -4,    // bbwb..w
    40,    // wbwb..w
    -19,   // .wwb..w
    31,    // bwwb..w
    3,     // wwwb..w
    4,     // ...w..w
    -13,   // b..w..w
    -10,   // w..w..w
    -10,   // .b.w..w
    10,    // bb.w..w
    30,    // wb.w..w
    11,    // .w.w..w
    -13,   // bw.w..w
    -11,   // ww.w..w
    -16,   // ..bw..w
    10,    // b.bw..w
    -33,   // w.bw..w
    19,    // .bbw..w
    3,     // bbbw..w
    -8,    // wbbw..w
    -3,    // .wbw..w
    12,    // bwbw..w
    -17,   // wwbw..w
    0,     // ..ww..w
    24,    // b.ww..w
    -9,    // w.ww..w
    23,    // .bww..w
    3,     // bbww..w
    23,    // wbww..w
    19,    // .www..w
    7,     // bwww..w
    -22,   // wwww..w
    -12,   // ....b.w
    -13,   // b...b.w
    22,    // w...b.w
    4,     // .b..b.w
    -5,    // bb..b.w
    -6,    // wb..b.w
    37,    // .w..b.w
    -17,   // bw..b.w
    -44,   // ww..b.w
    -13,   // ..b.b.w
    12,    // b.b.b.w
    59,    // w.b.b.w
    24,    // .bb.b.w
    4,     // bbb.b.w
    5,     // wbb.b.w
    -62,   // .wb.b.w
    0,     // bwb.b.w
    -20,   // wwb.b.w
    -32,   // ..w.b.w
    0,     // b.w.b.w
    8,     // w.w.b.w
    -27,   // .bw.b.w
    40,    // bbw.b.w
    -25,   // wbw.b.w
    8,     // .ww.b.w
    -14,   // bww.b.w
    -42,   // www.b.w
    -38,   // ...bb.w
    -24,   // b..bb.w
    -20,   // w..bb.w
    21,    // .b.bb.w
    12,    // bb.bb.w
    15,    // wb.bb.w
    2,     // .w.bb.w
    -2,    // bw.bb.w
    -5,    // ww.bb.w
    -40,   // ..bbb.w
    27,    // b.bbb.w
    -15,   // w.bbb.w
    16,    // .bbbb.w
    21,    // bbbbb.w
    -5,    // wbbbb.w
    -37,   // .wbbb.w
    8,     // bwbbb.w
    -17,   // wwbbb.w
    11,    // ..wbb.w
    -42,   // b.wbb.w
    -10,   // w.wbb.w
    15,    // .bwbb.w
    12,    // bbwbb.w
    -4,    // wbwbb.w
    20,    // .wwbb.w
    -14,   // bwwbb.w
    6,     // wwwbb.w
    -26,   // ...wb.w
    -18,   // b..wb.w
    -33,   // w..wb.w
    4,     // .b.wb.w
    -19,   // bb.wb.w
    -24,   // wb.wb.w
    13,    // .w.wb.w
    -24,   // bw.wb.w
    7,     // ww.wb.w
    -5,    // ..bwb.w
    -36,   // b.bwb.w
    11,    // w.bwb.w
    -38,   // .bbwb.w
    -23,   // bbbwb.w
    15,    // wbbwb.w
    -18,   // .wbwb.w
    17,    // bwbwb.w
    -25,   // wwbwb.w
    4,     // ..wwb.w
    42,    // b.wwb.w
    -37,   // w.wwb.w
    -9,    // .bwwb.w
    -8,    // bbwwb.w
    6,     // wbwwb.w
    -3,    // .wwwb.w
    12,    // bwwwb.w
    44,    // wwwwb.w
    -24,   // ....w.w
    -11,   // b...w.w
    5,     // w...w.w
    13,    // .b..w.w
    28,    // bb..w.w
    -53,   // wb..w.w
    -1,    // .w..w.w
    2,     // bw..w.w
    38,    // ww..w.w
    2,     // ..b.w.w
    0,     // b.b.w.w
    8,     // w.b.w.w
    -60,   // .bb.w.w
    -8,    // bbb.w.w
    -4,    // wbb.w.w
    24,    // .wb.w.w
    10,    // bwb.w.w
    -17,   // wwb.w.w
    16,    // ..w.w.w
    -12,   // b.w.w.w
    12,    // w.w.w.w
    37,    // .bw.w.w
    -41,   // bbw.w.w
    -4,    // wbw.w.w
    -6,    // .ww.w.w
    1,     // bww.w.w
    17,    // www.w.w
    4,     // ...bw.w
    -10,   // b..bw.w
    -8,    // w..bw.w
    -9,    // .b.bw.w
    -44,   // bb.bw.w
    -36,   // wb.bw.w
    13,    // .w.bw.w
    17,    // bw.bw.w
    7,     // ww.bw.w
    -1,    // ..bbw.w
    5,     // b.bbw.w
    -10,   // w.bbw.w
    -11,   // .bbbw.w
    9,     // bbbbw.w
    9,     // wbbbw.w
    -8,    // .wbbw.w
    22,    // bwbbw.w
    27,    // wwbbw.w
    7,     // ..wbw.w
    36,    // b.wbw.w
    -5,    // w.wbw.w
    -1,    // .bwbw.w
    -12,   // bbwbw.w
    11,    // wbwbw.w
    1,     // .wwbw.w
    -13,   // bwwbw.w
    21,    // wwwbw.w
    -4,    // ...ww.w
    -14,   // b..ww.w
    -9,    // w..ww.w
    -3,    // .b.ww.w
    21,    // bb.ww.w
    -13,   // wb.ww.w
    31,    // .w.ww.w
    20,    // bw.ww.w
    -4,    // ww.ww.w
    5,     // ..bww.w
    -5,    // b.bww.w
    -37,   // w.bww.w
    -1,    // .bbww.w
    22,    // bbbww.w
    -20,   // wbbww.w
    31,    // .wbww.w
    13,    // bwbww.w
    -33,   // wwbww.w
    -51,   // ..www.w
    -27,   // b.www.w
    -30,   // w.www.w
    -31,   // .bwww.w
    23,    // bbwww.w
    -15,   // wbwww.w
    -30,   // .wwww.w
    19,    // bwwww.w
    -6,    // wwwww.w
    9,     // .....bw
    21,    // b....bw
    2,     // w....bw
    13,    // .b...bw
    22,    // bb...bw
    -45,   // wb...bw
    -9,    // .w...bw
    0,     // bw...bw
    12,    // ww...bw
    -20,   // ..b..bw
    -2,    // b.b..bw
    -6,    // w.b..bw
    25,    // .bb..bw
    2,     // bbb..bw
    -32,   // wbb..bw
    30,    // .wb..bw
    38,    // bwb..bw
    -1,    // wwb..bw
    22,    // ..w..bw
    17,    // b.w..bw
    -53,   // w.w..bw
    -36,   // .bw..bw
    -22,   // bbw..bw
    9,     // wbw..bw
    -20,   // .ww..bw
    -7,    // bww..bw
    -31,   // www..bw
    -29,   // ...b.bw
    13,    // b..b.bw
    11,    // w..b.bw
    -13,   // .b.b.bw
    -13,   // bb.b.bw
    8,     // wb.b.bw
    -2,    // .w.b.bw
    11,    // bw.b.bw
    31,    // ww.b.bw
    -40,   // ..bb.bw
    -20,   // b.bb.bw
    15,    // w.bb.bw
    44,    // .bbb.bw
    -40,   // bbbb.bw
    -8,    // wbbb.bw
    35,    // .wbb.bw
    -29,   // bwbb.bw
    -64,   // wwbb.bw
    3,     // ..wb.bw
    24,    // b.wb.bw
    -36,   // w.wb.bw
    15,    // .bwb.bw
    2,     // bbwb.bw
    26,    // wbwb.bw
    22,    // .wwb.bw
    -1,    // bwwb.bw
    44,    // wwwb.bw
    -14,   // ...w.bw
    -9,    // b..w.bw
    30,    // w..w.bw
    1,     // .b.w.bw
    -10,   // bb.w.bw
    6,     // wb.w.bw
    67,    // .w.w.bw
    -11,   // bw.w.bw
    0,     // ww.w.bw
    9,     // ..bw.bw
    -17,   // b.bw.bw
    -24,   // w.bw.bw
    -11,   // .bbw.bw
    -5,    // bbbw.bw
    37,    // wbbw.bw
    -16,   // .wbw.bw
    7,     // bwbw.bw
    55,    // wwbw.bw
    -11,   // ..ww.bw
    2,     // b.ww.bw
    -13,   // w.ww.bw
    2,     // .bww.bw
    4,     // bbww.bw
    -2,    // wbww.bw
    -24,   // .www.bw
    2,     // bwww.bw
    26,    // wwww.bw
    -4,    // ....bbw
    -30,   // b...bbw
    8,     // w...bbw
    48,    // .b..bbw
    -28,   // bb..bbw
    -32,   // wb..bbw
    36,    // .w..bbw
    7,     // bw..bbw
    -25,   // ww..bbw
    43,    // ..b.bbw
    -1,    // b.b.bbw
    5,     // w.b.bbw
    39,    // .bb.bbw
    5,     // bbb.bbw
    30,    // wbb.bbw
    -1,    // .wb.bbw
    1,     // bwb.bbw
    5,     // wwb.bbw
    7,     // ..w.bbw
    14,    // b.w.bbw
    -4,    // w.w.bbw
    -40,   // .bw.bbw
    27,    // bbw.bbw
    24,    // wbw.bbw
    -4,    // .ww.bbw
    0,     // bww.bbw
    22,    // www.bbw
    -49,   // ...bbbw
    -7,    // b..bbbw
    -2,    // w..bbbw
    53,    // .b.bbbw
    10,    // bb.bbbw
    -8,    // wb.bbbw
    -13,   // .w.bbbw
    -2,    // bw.bbbw
    -4,    // ww.bbbw
    54,    // ..bbbbw
    -19,   // b.bbbbw
    -5,    // w.bbbbw
    30,    // .bbbbbw
    -12,   // bbbbbbw
    -12,   // wbbbbbw
    -93,   // .wbbbbw
    18,    // bwbbbbw
    1,     // wwbbbbw
    -27,   // ..wbbbw
    -12,   // b.wbbbw
    9,     // w.wbbbw
    9,     // .bwbbbw
    -30,   // bbwbbbw
    -32,   // wbwbbbw
    14,    // .wwbbbw
    -7,    // bwwbbbw
    29,    // wwwbbbw
    14,    // ...wbbw
    -31,   // b..wbbw
    -8,    // w..wbbw
    -2,    // .b.wbbw
    22,    // bb.wbbw
    37,    // wb.wbbw
    -8,    // .w.wbbw
    1,     // bw.wbbw
    -5,    // ww.wbbw
    55,    // ..bwbbw
    13,    // b.bwbbw
    15,    // w.bwbbw
    -19,   // .bbwbbw
    -17,   // bbbwbbw
    -29,   // wbbwbbw
    -32,   // .wbwbbw
    -18,   // bwbwbbw
    18,    // wwbwbbw
    23,    // ..wwbbw
    14,    // b.wwbbw
    -20,   // w.wwbbw
    -18,   // .bwwbbw
    -30,   // bbwwbbw
    -31,   // wbwwbbw
    31,    // .wwwbbw
    7,     // bwwwbbw
    8,     // wwwwbbw
    9,     // ....wbw
    -14,   // b...wbw
    37,    // w...wbw
    -46,   // .b..wbw
    8,     // bb..wbw
    9,     // wb..wbw
    4,     // .w..wbw
    -38,   // bw..wbw
    11,    // ww..wbw
    -5,    // ..b.wbw
    -10,   // b.b.wbw
    -25,   // w.b.wbw
    -15,   // .bb.wbw
    -34,   // bbb.wbw
    24,    // wbb.wbw
    27,    // .wb.wbw
    0,     // bwb.wbw
    23,    // wwb.wbw
    12,    // ..w.wbw
    0,     // b.w.wbw
    -4,    // w.w.wbw
    -23,   // .bw.wbw
    7,     // bbw.wbw
    11,    // wbw.wbw
    -11,   // .ww.wbw
    -1,    // bww.wbw
    26,    // www.wbw
    -1,    // ...bwbw
    -12,   // b..bwbw
    40,    // w..bwbw
    -1,    // .b.bwbw
    -43,   // bb.bwbw
    26,    // wb.bwbw
    -1,    // .w.bwbw
    -7,    // bw.bwbw
    -19,   // ww.bwbw
    -19,   // ..bbwbw
    -13,   // b.bbwbw
    -4,    // w.bbwbw
    -36,   // .bbbwbw
    -19,   // bbbbwbw
    -32,   // wbbbwbw
    11,    // .wbbwbw
    -14,   // bwbbwbw
    10,    // wwbbwbw
    -14,   // ..wbwbw
    -17,   // b.wbwbw
    11,    // w.wbwbw
    12,    // .bwbwbw
    18,    // bbwbwbw
    1,     // wbwbwbw
    5,     // .wwbwbw
    18,    // bwwbwbw
    23,    // wwwbwbw
    5,     // ...wwbw
    36,    // b..wwbw
    23,    // w..wwbw
    28,    // .b.wwbw
    29,    // bb.wwbw
    -2,    // wb.wwbw
    -29,   // .w.wwbw
    29,    // bw.wwbw
    -28,   // ww.wwbw
    48,    // ..bwwbw
    -22,   // b.bwwbw
    6,     // w.bwwbw
    26,    // .bbwwbw
    -6,    // bbbwwbw
    -31,   // wbbwwbw
    24,    // .wbwwbw
    14,    // bwbwwbw
    21,    // wwbwwbw
    13,    // ..wwwbw
    -8,    // b.wwwbw
    -15,   // w.wwwbw
    6,     // .bwwwbw
    5,     // bbwwwbw
    18,    // wbwwwbw
    -22,   // .wwwwbw
    -18,   // bwwwwbw
    15,    // wwwwwbw
    -15,   // .....ww
    7,     // b....ww
    -26,   // w....ww
    12,    // .b...ww
    0,     // bb...ww
    12,    // wb...ww
    -57,   // .w...ww
    -22,   // bw...ww
    24,    // ww...ww
    -37,   // ..b..ww
    -28,   // b.b..ww
    -44,   // w.b..ww
    -16,   // .bb..ww
    8,     // bbb..ww
    -25,   // wbb..ww
    20,    // .wb..ww
    -8,    // bwb..ww
    -13,   // wwb..ww
    15,    // ..w..ww
    5,     // b.w..ww
    38,    // w.w..ww
    1,     // .bw..ww
    5,     // bbw..ww
    11,    // wbw..ww
    -11,   // .ww..ww
    28,    // bww..ww
    -58,   // www..ww
    -50,   // ...b.ww
    -10,   // b..b.ww
    -20,   // w..b.ww
    -27,   // .b.b.ww
    8,     // bb.b.ww
    31,    // wb.b.ww
    -27,   // .w.b.ww
    10,    // bw.b.ww
    -38,   // ww.b.ww
    21,    // ..bb.ww
    -21,   // b.bb.ww
    -5,    // w.bb.ww
    -11,   // .bbb.ww
    -3,    // bbbb.ww
    -4,    // wbbb.ww
    11,    // .wbb.ww
    -29,   // bwbb.ww
    -15,   // wwbb.ww
    4,     // ..wb.ww
    19,    // b.wb.ww
    7,     // w.wb.ww
    -21,   // .bwb.ww
    -11,   // bbwb.ww
    -19,   // wbwb.ww
    -25,   // .wwb.ww
    -22,   // bwwb.ww
    44,    // wwwb.ww
    -12,   // ...w.ww
    -31,   // b..w.ww
    -11,   // w..w.ww
    -13,   // .b.w.ww
    -8,    // bb.w.ww
    0,     // wb.w.ww
    -25,   // .w.w.ww
    13,    // bw.w.ww
    19,    // ww.w.ww
    -9,    // ..bw.ww
    44,    // b.bw.ww
    7,     // w.bw.ww
    -18,   // .bbw.ww
    -34,   // bbbw.ww
    -5,    // wbbw.ww
    3,     // .wbw.ww
    43,    // bwbw.ww
    -66,   // wwbw.ww
    -26,   // ..ww.ww
    -12,   // b.ww.ww
    -4,    // w.ww.ww
    9,     // .bww.ww
    -26,   // bbww.ww
    -28,   // wbww.ww
    1,     // .www.ww
    -10,   // bwww.ww
    -6,    // wwww.ww
    2,     // ....bww
    -13,   // b...bww
    1,     // w...bww
    36,    // .b..bww
    -5,    // bb..bww
    -1,    // wb..bww
    17,    // .w..bww
    22,    // bw..bww
    -13,   // ww..bww
    -1,    // ..b.bww
    41,    // b.b.bww
    -20,   // w.b.bww
    11,    // .bb.bww
    -2,    // bbb.bww
    5,     // wbb.bww
    -1,    // .wb.bww
    -7,    // bwb.bww
    -31,   // wwb.bww
    8,     // ..w.bww
    -40,   // b.w.bww
    -17,   // w.w.bww
    -1,    // .bw.bww
    0,     // bbw.bww
    23,    // wbw.bww
    -16,   // .ww.bww
    -27,   // bww.bww
    17,    // www.bww
    49,    // ...bbww
    -3,    // b..bbww
    -26,   // w..bbww
    -32,   // .b.bbww
    26,    // bb.bbww
    -64,   // wb.bbww
    31,    // .w.bbww
    -4,    // bw.bbww
    -15,   // ww.bbww
    -9,    // ..bbbww
    -23,   // b.bbbww
    -17,   // w.bbbww
    24,    // .bbbbww
    -6,    // bbbbbww
    1,     // wbbbbww
    -1,    // .wbbbww
    -5,    // bwbbbww
    10,    // wwbbbww
    -19,   // ..wbbww
    8,     // b.wbbww
    27,    // w.wbbww
    25,    // .bwbbww
    55,    // bbwbbww
    10,    // wbwbbww
    27,    // .wwbbww
    30,    // bwwbbww
    10,    // wwwbbww
    38,    // ...wbww
    4,     // b..wbww
    -17,   // w..wbww
    15,    // .b.wbww
    11,    // bb.wbww
    55,    // wb.wbww
    -1,    // .w.wbww
    -2,    // bw.wbww
    -66,   // ww.wbww
    -22,   // ..bwbww
    12,    // b.bwbww
    -25,   // w.bwbww
    41,    // .bbwbww
    2,     // bbbwbww
    18,    // wbbwbww
    -40,   // .wbwbww
    -18,   // bwbwbww
    -1,    // wwbwbww
    4,     // ..wwbww
    -12,   // b.wwbww
    -33,   // w.wwbww
    16,    // .bwwbww
    -55,   // bbwwbww
    21,    // wbwwbww
    19,    // .wwwbww
    30,    // bwwwbww
    -9,    // wwwwbww
    -91,   // ....www
    18,    // b...www
    56,    // w...www
    -65,   // .b..www
    -8,    // bb..www
    -31,   // wb..www
    0,     // .w..www
    -2,    // bw..www
    -58,   // ww..www
    -43,   // ..b.www
    8,     // b.b.www
    -42,   // w.b.www
    -45,   // .bb.www
    0,     // bbb.www
    22,    // wbb.www
    -12,   // .wb.www
    34,    // bwb.www
    17,    // wwb.www
    -39,   // ..w.www
    -4,    // b.w.www
    17,    // w.w.www
    -45,   // .bw.www
    2,     // bbw.www
    26,    // wbw.www
    -3,    // .ww.www
    -5,    // bww.www
    -32,   // www.www
    1,     // ...bwww
    -3,    // b..bwww
    3,     // w..bwww
    -32,   // .b.bwww
    34,    // bb.bwww
    44,    // wb.bwww
    -2,    // .w.bwww
    5,     // bw.bwww
    44,    // ww.bwww
    -11,   // ..bbwww
    -22,   // b.bbwww
    6,     // w.bbwww
    3,     // .bbbwww
    10,    // bbbbwww
    29,    // wbbbwww
    28,    // .wbbwww
    6,     // bwbbwww
    10,    // wwbbwww
    18,    // ..wbwww
    23,    // b.wbwww
    21,    // w.wbwww
    -50,   // .bwbwww
    -2,    // bbwbwww
    23,    // wbwbwww
    20,    // .wwbwww
    17,    // bwwbwww
    5,     // wwwbwww
    -173,  // ...wwww
    -37,   // b..wwww
    -22,   // w..wwww
    -19,   // .b.wwww
    3,     // bb.wwww
    26,    // wb.wwww
    -7,    // .w.wwww
    40,    // bw.wwww
    -6,    // ww.wwww
    -38,   // ..bwwww
    -9,    // b.bwwww
    44,    // w.bwwww
    8,     // .bbwwww
    -10,   // bbbwwww
    8,     // wbbwwww
    5,     // .wbwwww
    19,    // bwbwwww
    -9,    // wwbwwww
    -39,   // ..wwwww
    -21,   // b.wwwww
    -6,    // w.wwwww
    -5,    // .bwwwww
    6,     // bbwwwww
    15,    // wbwwwww
    0,     // .wwwwww
    12,    // bwwwwww
    -22,   // wwwwwww
    0,     // captures=0 threats=0
    35,    // captures=0 threats=1
    67,    // captures=0 threats=2
    80,    // captures=0 threats=3
    119,   // captures=0 threats=4
    0,     // captures=0 additional threats
    23,    // captures=1 threats=0
    72,    // captures=1 threats=1
    124,   // captures=1 threats=2
    225,   // captures=1 threats=3
    307,   // captures=1 threats=4
    93,    // captures=1 additional threats
    99,    // captures=2 threats=0
    115,   // captures=2 threats=1
    195,   // captures=2 threats=2
    238,   // captures=2 threats=3
    326,   // captures=2 threats=4
    74,    // captures=2 additional threats
    112,   // captures=3 threats=0
    123,   // captures=3 threats=1
    226,   // captures=3 threats=2
    331,   // captures=3 threats=3
    339,   // captures=3 threats=4
    81,    // captures=3 additional threats
    117,   // captures=4 threats=0
    188,   // captures=4 threats=1
    250,   // captures=4 threats=2
    332,   // captures=4 threats=3
    385,   // captures=4 threats=4
    8,     // captures=4 additional threats
].into_boxed_slice()
