vec![
    0,     // .......
    16,    // b......
    -16,   // w......
    -12,   // .b.....
    30,    // bb.....
    -17,   // wb.....
    12,    // .w.....
    17,    // bw.....
    -30,   // ww.....
    19,    // ..b....
    87,    // b.b....
    -26,   // w.b....
    13,    // .bb....
    79,    // bbb....
    -101,  // wbb....
    -18,   // .wb....
    55,    // bwb....
    75,    // wwb....
    -19,   // ..w....
    26,    // b.w....
    -87,   // w.w....
    18,    // .bw....
    -75,   // bbw....
    -55,   // wbw....
    -13,   // .ww....
    101,   // bww....
    -79,   // www....
    -15,   // ...b...
    -4,    // b..b...
    -9,    // w..b...
    1,     // .b.b...
    123,   // bb.b...
    -80,   // wb.b...
    -3,    // .w.b...
    -15,   // bw.b...
    -41,   // ww.b...
    -12,   // ..bb...
    86,    // b.bb...
    -31,   // w.bb...
    181,   // .bbb...
    694,   // bbbb...
    -100,  // wbbb...
    41,    // .wbb...
    -15,   // bwbb...
    -4,    // wwbb...
    -4,    // ..wb...
    66,    // b.wb...
    -83,   // w.wb...
    -37,   // .bwb...
    -87,   // bbwb...
    -17,   // wbwb...
    -12,   // .wwb...
    27,    // bwwb...
    -117,  // wwwb...
    15,    // ...w...
    9,     // b..w...
    4,     // w..w...
    3,     // .b.w...
    41,    // bb.w...
    15,    // wb.w...
    -1,    // .w.w...
    80,    // bw.w...
    -123,  // ww.w...
    4,     // ..bw...
    83,    // b.bw...
    -66,   // w.bw...
    12,    // .bbw...
    117,   // bbbw...
    -27,   // wbbw...
    37,    // .wbw...
    17,    // bwbw...
    87,    // wwbw...
    12,    // ..ww...
    31,    // b.ww...
    -86,   // w.ww...
    -41,   // .bww...
    4,     // bbww...
    15,    // wbww...
    -181,  // .www...
    100,   // bwww...
    -694,  // wwww...
    19,    // ....b..
    31,    // b...b..
    -85,   // w...b..
    25,    // .b..b..
    -55,   // bb..b..
    23,    // wb..b..
    -13,   // .w..b..
    -63,   // bw..b..
    28,    // ww..b..
    -6,    // ..b.b..
    -34,   // b.b.b..
    -26,   // w.b.b..
    -1,    // .bb.b..
    190,   // bbb.b..
    -177,  // wbb.b..
    -25,   // .wb.b..
    -80,   // bwb.b..
    -39,   // wwb.b..
    0,     // ..w.b..
    -21,   // b.w.b..
    -79,   // w.w.b..
    -30,   // .bw.b..
    -40,   // bbw.b..
    -71,   // wbw.b..
    7,     // .ww.b..
    -49,   // bww.b..
    -39,   // www.b..
    -12,   // ...bb..
    42,    // b..bb..
    -39,   // w..bb..
    21,    // .b.bb..
    38,    // bb.bb..
    -9,    // wb.bb..
    -66,   // .w.bb..
    -8,    // bw.bb..
    -51,   // ww.bb..
    25,    // ..bbb..
    123,   // b.bbb..
    -5,    // w.bbb..
    306,   // .bbbb..
    85,    // bbbbb..
    9,     // wbbbb..
    -57,   // .wbbb..
    -51,   // bwbbb..
    27,    // wwbbb..
    -94,   // ..wbb..
    -49,   // b.wbb..
    -28,   // w.wbb..
    -54,   // .bwbb..
    -5,    // bbwbb..
    85,    // wbwbb..
    70,    // .wwbb..
    -110,  // bwwbb..
    -102,  // wwwbb..
    4,     // ...wb..
    104,   // b..wb..
    50,    // w..wb..
    16,    // .b.wb..
    -32,   // bb.wb..
    12,    // wb.wb..
    4,     // .w.wb..
    36,    // bw.wb..
    22,    // ww.wb..
    5,     // ..bwb..
    8,     // b.bwb..
    -10,   // w.bwb..
    -46,   // .bbwb..
    -158,  // bbbwb..
    14,    // wbbwb..
    -1,    // .wbwb..
    -61,   // bwbwb..
    26,    // wwbwb..
    94,    // ..wwb..
    65,    // b.wwb..
    76,    // w.wwb..
    89,    // .bwwb..
    -18,   // bbwwb..
    -11,   // wbwwb..
    -98,   // .wwwb..
    34,    // bwwwb..
    -106,  // wwwwb..
    -19,   // ....w..
    85,    // b...w..
    -31,   // w...w..
    13,    // .b..w..
    -28,   // bb..w..
    63,    // wb..w..
    -25,   // .w..w..
    -23,   // bw..w..
    55,    // ww..w..
    0,     // ..b.w..
    79,    // b.b.w..
    21,    // w.b.w..
    -7,    // .bb.w..
    39,    // bbb.w..
    49,    // wbb.w..
    30,    // .wb.w..
    71,    // bwb.w..
    40,    // wwb.w..
    6,     // ..w.w..
    26,    // b.w.w..
    34,    // w.w.w..
    25,    // .bw.w..
    39,    // bbw.w..
    80,    // wbw.w..
    1,     // .ww.w..
    177,   // bww.w..
    -190,  // www.w..
    -4,    // ...bw..
    -50,   // b..bw..
    -104,  // w..bw..
    -4,    // .b.bw..
    -22,   // bb.bw..
    -36,   // wb.bw..
    -16,   // .w.bw..
    -12,   // bw.bw..
    32,    // ww.bw..
    -94,   // ..bbw..
    -76,   // b.bbw..
    -65,   // w.bbw..
    98,    // .bbbw..
    106,   // bbbbw..
    -34,   // wbbbw..
    -89,   // .wbbw..
    11,    // bwbbw..
    18,    // wwbbw..
    -5,    // ..wbw..
    10,    // b.wbw..
    -8,    // w.wbw..
    1,     // .bwbw..
    -26,   // bbwbw..
    61,    // wbwbw..
    46,    // .wwbw..
    -14,   // bwwbw..
    158,   // wwwbw..
    12,    // ...ww..
    39,    // b..ww..
    -42,   // w..ww..
    66,    // .b.ww..
    51,    // bb.ww..
    8,     // wb.ww..
    -21,   // .w.ww..
    9,     // bw.ww..
    -38,   // ww.ww..
    94,    // ..bww..
    28,    // b.bww..
    49,    // w.bww..
    -70,   // .bbww..
    102,   // bbbww..
    110,   // wbbww..
    54,    // .wbww..
    -85,   // bwbww..
    5,     // wwbww..
    -25,   // ..www..
    5,     // b.www..
    -123,  // w.www..
    57,    // .bwww..
    -27,   // bbwww..
    51,    // wbwww..
    -306,  // .wwww..
    -9,    // bwwww..
    -85,   // wwwww..
    -12,   // .....b.
    -34,   // b....b.
    -74,   // w....b.
    -33,   // .b...b.
    -47,   // bb...b.
    29,    // wb...b.
    0,     // .w...b.
    -63,   // bw...b.
    29,    // ww...b.
    25,    // ..b..b.
    44,    // b.b..b.
    -73,   // w.b..b.
    39,    // .bb..b.
    25,    // bbb..b.
    89,    // wbb..b.
    21,    // .wb..b.
    -64,   // bwb..b.
    35,    // wwb..b.
    13,    // ..w..b.
    -20,   // b.w..b.
    -36,   // w.w..b.
    23,    // .bw..b.
    -21,   // bbw..b.
    -34,   // wbw..b.
    -18,   // .ww..b.
    15,    // bww..b.
    -90,   // www..b.
    1,     // ...b.b.
    -44,   // b..b.b.
    -19,   // w..b.b.
    -11,   // .b.b.b.
    -84,   // bb.b.b.
    10,    // wb.b.b.
    -20,   // .w.b.b.
    2,     // bw.b.b.
    -19,   // ww.b.b.
    21,    // ..bb.b.
    34,    // b.bb.b.
    112,   // w.bb.b.
    65,    // .bbb.b.
    -93,   // bbbb.b.
    89,    // wbbb.b.
    -24,   // .wbb.b.
    -56,   // bwbb.b.
    -2,    // wwbb.b.
    -4,    // ..wb.b.
    -18,   // b.wb.b.
    -30,   // w.wb.b.
    33,    // .bwb.b.
    40,    // bbwb.b.
    19,    // wbwb.b.
    95,    // .wwb.b.
    -73,   // bwwb.b.
    55,    // wwwb.b.
    3,     // ...w.b.
    -73,   // b..w.b.
    -14,   // w..w.b.
    30,    // .b.w.b.
    -44,   // bb.w.b.
    -79,   // wb.w.b.
    20,    // .w.w.b.
    116,   // bw.w.b.
    -141,  // ww.w.b.
    16,    // ..bw.b.
    48,    // b.bw.b.
    38,    // w.bw.b.
    -9,    // .bbw.b.
    -110,  // bbbw.b.
    -92,   // wbbw.b.
    48,    // .wbw.b.
    2,     // bwbw.b.
    58,    // wwbw.b.
    66,    // ..ww.b.
    4,     // b.ww.b.
    34,    // w.ww.b.
    48,    // .bww.b.
    -4,    // bbww.b.
    161,   // wbww.b.
    -105,  // .www.b.
    38,    // bwww.b.
    -263,  // wwww.b.
    13,    // ....bb.
    1,     // b...bb.
    22,    // w...bb.
    39,    // .b..bb.
    12,    // bb..bb.
    2,     // wb..bb.
    18,    // .w..bb.
    -14,   // bw..bb.
    -89,   // ww..bb.
    -1,    // ..b.bb.
    29,    // b.b.bb.
    18,    // w.b.bb.
    50,    // .bb.bb.
    -19,   // bbb.bb.
    -6,    // wbb.bb.
    -104,  // .wb.bb.
    31,    // bwb.bb.
    -22,   // wwb.bb.
    -7,    // ..w.bb.
    -7,    // b.w.bb.
    55,    // w.w.bb.
    -99,   // .bw.bb.
    56,    // bbw.bb.
    -123,  // wbw.bb.
    0,     // .ww.bb.
    95,    // bww.bb.
    -95,   // www.bb.
    181,   // ...bbb.
    -58,   // b..bbb.
    88,    // w..bbb.
    65,    // .b.bbb.
    21,    // bb.bbb.
    57,    // wb.bbb.
    105,   // .w.bbb.
    65,    // bw.bbb.
    -15,   // ww.bbb.
    306,   // ..bbbb.
    130,   // b.bbbb.
    81,    // w.bbbb.
    -75,   // .bbbbb.
    -69,   // bbbbbb.
    10,    // wbbbbb.
    52,    // .wbbbb.
    -78,   // bwbbbb.
    6,     // wwbbbb.
    98,    // ..wbbb.
    16,    // b.wbbb.
    -71,   // w.wbbb.
    69,    // .bwbbb.
    -110,  // bbwbbb.
    81,    // wbwbbb.
    21,    // .wwbbb.
    25,    // bwwbbb.
    -40,   // wwwbbb.
    12,    // ...wbb.
    65,    // b..wbb.
    36,    // w..wbb.
    -9,    // .b.wbb.
    82,    // bb.wbb.
    7,     // wb.wbb.
    -95,   // .w.wbb.
    -24,   // bw.wbb.
    -41,   // ww.wbb.
    -46,   // ..bwbb.
    -88,   // b.bwbb.
    -103,  // w.bwbb.
    -43,   // .bbwbb.
    -69,   // bbbwbb.
    -80,   // wbbwbb.
    39,    // .wbwbb.
    -45,   // bwbwbb.
    125,   // wwbwbb.
    -70,   // ..wwbb.
    -22,   // b.wwbb.
    -25,   // w.wwbb.
    -38,   // .bwwbb.
    -51,   // bbwwbb.
    -49,   // wbwwbb.
    -21,   // .wwwbb.
    110,   // bwwwbb.
    52,    // wwwwbb.
    18,    // ....wb.
    11,    // b...wb.
    93,    // w...wb.
    23,    // .b..wb.
    -13,   // bb..wb.
    -90,   // wb..wb.
    -21,   // .w..wb.
    -91,   // bw..wb.
    -135,  // ww..wb.
    -30,   // ..b.wb.
    -52,   // b.b.wb.
    -24,   // w.b.wb.
    -99,   // .bb.wb.
    -18,   // bbb.wb.
    -66,   // wbb.wb.
    0,     // .wb.wb.
    44,    // bwb.wb.
    3,     // wwb.wb.
    25,    // ..w.wb.
    -34,   // b.w.wb.
    122,   // w.w.wb.
    52,    // .bw.wb.
    -17,   // bbw.wb.
    -9,    // wbw.wb.
    104,   // .ww.wb.
    -48,   // bww.wb.
    9,     // www.wb.
    -37,   // ...bwb.
    38,    // b..bwb.
    69,    // w..bwb.
    33,    // .b.bwb.
    -16,   // bb.bwb.
    -38,   // wb.bwb.
    -48,   // .w.bwb.
    -27,   // bw.bwb.
    -20,   // ww.bwb.
    -54,   // ..bbwb.
    -55,   // b.bbwb.
    -20,   // w.bbwb.
    69,    // .bbbwb.
    -124,  // bbbbwb.
    -11,   // wbbbwb.
    24,    // .wbbwb.
    -107,  // bwbbwb.
    75,    // wwbbwb.
    1,     // ..wbwb.
    -44,   // b.wbwb.
    24,    // w.wbwb.
    -6,    // .bwbwb.
    0,     // bbwbwb.
    -61,   // wbwbwb.
    -39,   // .wwbwb.
    100,   // bwwbwb.
    42,    // wwwbwb.
    -41,   // ...wwb.
    25,    // b..wwb.
    10,    // w..wwb.
    48,    // .b.wwb.
    -20,   // bb.wwb.
    41,    // wb.wwb.
    24,    // .w.wwb.
    77,    // bw.wwb.
    -102,  // ww.wwb.
    89,    // ..bwwb.
    -84,   // b.bwwb.
    -21,   // w.bwwb.
    -38,   // .bbwwb.
    15,    // bbbwwb.
    -88,   // wbbwwb.
    -24,   // .wbwwb.
    -107,  // bwbwwb.
    -18,   // wwbwwb.
    57,    // ..wwwb.
    142,   // b.wwwb.
    -243,  // w.wwwb.
    -31,   // .bwwwb.
    100,   // bbwwwb.
    -14,   // wbwwwb.
    -52,   // .wwwwb.
    264,   // bwwwwb.
    -302,  // wwwwwb.
    12,    // .....w.
    74,    // b....w.
    34,    // w....w.
    0,     // .b...w.
    -29,   // bb...w.
    63,    // wb...w.
    33,    // .w...w.
    -29,   // bw...w.
    47,    // ww...w.
    -13,   // ..b..w.
    36,    // b.b..w.
    20,    // w.b..w.
    18,    // .bb..w.
    90,    // bbb..w.
    -15,   // wbb..w.
    -23,   // .wb..w.
    34,    // bwb..w.
    21,    // wwb..w.
    -25,   // ..w..w.
    73,    // b.w..w.
    -44,   // w.w..w.
    -21,   // .bw..w.
    -35,   // bbw..w.
    64,    // wbw..w.
    -39,   // .ww..w.
    -89,   // bww..w.
    -25,   // www..w.
    -3,    // ...b.w.
    14,    // b..b.w.
    73,    // w..b.w.
    -20,   // .b.b.w.
    141,   // bb.b.w.
    -116,  // wb.b.w.
    -30,   // .w.b.w.
    79,    // bw.b.w.
    44,    // ww.b.w.
    -66,   // ..bb.w.
    -34,   // b.bb.w.
    -4,    // w.bb.w.
    105,   // .bbb.w.
    263,   // bbbb.w.
    -38,   // wbbb.w.
    -48,   // .wbb.w.
    -161,  // bwbb.w.
    4,     // wwbb.w.
    -16,   // ..wb.w.
    -38,   // b.wb.w.
    -48,   // w.wb.w.
    -48,   // .bwb.w.
    -58,   // bbwb.w.
    -2,    // wbwb.w.
    9,     // .wwb.w.
    92,    // bwwb.w.
    110,   // wwwb.w.
    -1,    // ...w.w.
    19,    // b..w.w.
    44,    // w..w.w.
    20,    // .b.w.w.
    19,    // bb.w.w.
    -2,    // wb.w.w.
    11,    // .w.w.w.
    -10,   // bw.w.w.
    84,    // ww.w.w.
    4,     // ..bw.w.
    30,    // b.bw.w.
    18,    // w.bw.w.
    -95,   // .bbw.w.
    -55,   // bbbw.w.
    73,    // wbbw.w.
    -33,   // .wbw.w.
    -19,   // bwbw.w.
    -40,   // wwbw.w.
    -21,   // ..ww.w.
    -112,  // b.ww.w.
    -34,   // w.ww.w.
    24,    // .bww.w.
    2,     // bbww.w.
    56,    // wbww.w.
    -65,   // .www.w.
    -89,   // bwww.w.
    93,    // wwww.w.
    -18,   // ....bw.
    -93,   // b...bw.
    -11,   // w...bw.
    21,    // .b..bw.
    135,   // bb..bw.
    91,    // wb..bw.
    -23,   // .w..bw.
    90,    // bw..bw.
    13,    // ww..bw.
    -25,   // ..b.bw.
    -122,  // b.b.bw.
    34,    // w.b.bw.
    -104,  // .bb.bw.
    -9,    // bbb.bw.
    48,    // wbb.bw.
    -52,   // .wb.bw.
    9,     // bwb.bw.
    17,    // wwb.bw.
    30,    // ..w.bw.
    24,    // b.w.bw.
    52,    // w.w.bw.
    0,     // .bw.bw.
    -3,    // bbw.bw.
    -44,   // wbw.bw.
    99,    // .ww.bw.
    66,    // bww.bw.
    18,    // www.bw.
    41,    // ...bbw.
    -10,   // b..bbw.
    -25,   // w..bbw.
    -24,   // .b.bbw.
    102,   // bb.bbw.
    -77,   // wb.bbw.
    -48,   // .w.bbw.
    -41,   // bw.bbw.
    20,    // ww.bbw.
    -57,   // ..bbbw.
    243,   // b.bbbw.
    -142,  // w.bbbw.
    52,    // .bbbbw.
    302,   // bbbbbw.
    -264,  // wbbbbw.
    31,    // .wbbbw.
    14,    // bwbbbw.
    -100,  // wwbbbw.
    -89,   // ..wbbw.
    21,    // b.wbbw.
    84,    // w.wbbw.
    24,    // .bwbbw.
    18,    // bbwbbw.
    107,   // wbwbbw.
    38,    // .wwbbw.
    88,    // bwwbbw.
    -15,   // wwwbbw.
    37,    // ...wbw.
    -69,   // b..wbw.
    -38,   // w..wbw.
    48,    // .b.wbw.
    20,    // bb.wbw.
    27,    // wb.wbw.
    -33,   // .w.wbw.
    38,    // bw.wbw.
    16,    // ww.wbw.
    -1,    // ..bwbw.
    -24,   // b.bwbw.
    44,    // w.bwbw.
    39,    // .bbwbw.
    -42,   // bbbwbw.
    -100,  // wbbwbw.
    6,     // .wbwbw.
    61,    // bwbwbw.
    0,     // wwbwbw.
    54,    // ..wwbw.
    20,    // b.wwbw.
    55,    // w.wwbw.
    -24,   // .bwwbw.
    -75,   // bbwwbw.
    107,   // wbwwbw.
    -69,   // .wwwbw.
    11,    // bwwwbw.
    124,   // wwwwbw.
    -13,   // ....ww.
    -22,   // b...ww.
    -1,    // w...ww.
    -18,   // .b..ww.
    89,    // bb..ww.
    14,    // wb..ww.
    -39,   // .w..ww.
    -2,    // bw..ww.
    -12,   // ww..ww.
    7,     // ..b.ww.
    -55,   // b.b.ww.
    7,     // w.b.ww.
    0,     // .bb.ww.
    95,    // bbb.ww.
    -95,   // wbb.ww.
    99,    // .wb.ww.
    123,   // bwb.ww.
    -56,   // wwb.ww.
    1,     // ..w.ww.
    -18,   // b.w.ww.
    -29,   // w.w.ww.
    104,   // .bw.ww.
    22,    // bbw.ww.
    -31,   // wbw.ww.
    -50,   // .ww.ww.
    6,     // bww.ww.
    19,    // www.ww.
    -12,   // ...bww.
    -36,   // b..bww.
    -65,   // w..bww.
    95,    // .b.bww.
    41,    // bb.bww.
    24,    // wb.bww.
    9,     // .w.bww.
    -7,    // bw.bww.
    -82,   // ww.bww.
    70,    // ..bbww.
    25,    // b.bbww.
    22,    // w.bbww.
    21,    // .bbbww.
    -52,   // bbbbww.
    -110,  // wbbbww.
    38,    // .wbbww.
    49,    // bwbbww.
    51,    // wwbbww.
    46,    // ..wbww.
    103,   // b.wbww.
    88,    // w.wbww.
    -39,   // .bwbww.
    -125,  // bbwbww.
    45,    // wbwbww.
    43,    // .wwbww.
    80,    // bwwbww.
    69,    // wwwbww.
    -181,  // ...www.
    -88,   // b..www.
    58,    // w..www.
    -105,  // .b.www.
    15,    // bb.www.
    -65,   // wb.www.
    -65,   // .w.www.
    -57,   // bw.www.
    -21,   // ww.www.
    -98,   // ..bwww.
    71,    // b.bwww.
    -16,   // w.bwww.
    -21,   // .bbwww.
    40,    // bbbwww.
    -25,   // wbbwww.
    -69,   // .wbwww.
    -81,   // bwbwww.
    110,   // wwbwww.
    -306,  // ..wwww.
    -81,   // b.wwww.
    -130,  // w.wwww.
    -52,   // .bwwww.
    -6,    // bbwwww.
    78,    // wbwwww.
    75,    // .wwwww.
    -10,   // bwwwww.
    69,    // wwwwww.
    16,    // ......b
    29,    // b.....b
    0,     // w.....b
    -34,   // .b....b
    -10,   // bb....b
    11,    // wb....b
    74,    // .w....b
    6,     // bw....b
    -43,   // ww....b
    31,    // ..b...b
    7,     // b.b...b
    -77,   // w.b...b
    1,     // .bb...b
    -84,   // bbb...b
    -125,  // wbb...b
    -93,   // .wb...b
    5,     // bwb...b
    6,     // wwb...b
    85,    // ..w...b
    -7,    // b.w...b
    91,    // w.w...b
    11,    // .bw...b
    -46,   // bbw...b
    -42,   // wbw...b
    -22,   // .ww...b
    -38,   // bww...b
    -93,   // www...b
    -4,    // ...b..b
    -39,   // b..b..b
    41,    // w..b..b
    -44,   // .b.b..b
    -41,   // bb.b..b
    -104,  // wb.b..b
    14,    // .w.b..b
    -3,    // bw.b..b
    103,   // ww.b..b
    42,    // ..bb..b
    -26,   // b.bb..b
    -17,   // w.bb..b
    -58,   // .bbb..b
    10,    // bbbb..b
    -102,  // wbbb..b
    -10,   // .wbb..b
    112,   // bwbb..b
    -56,   // wwbb..b
    -50,   // ..wb..b
    -61,   // b.wb..b
    1,     // w.wb..b
    38,    // .bwb..b
    -85,   // bbwb..b
    -67,   // wbwb..b
    -36,   // .wwb..b
    -78,   // bwwb..b
    40,    // wwwb..b
    9,     // ...w..b
    -8,    // b..w..b
    -41,   // w..w..b
    -73,   // .b.w..b
    64,    // bb.w..b
    -24,   // wb.w..b
    19,    // .w.w..b
    -58,   // bw.w..b
    82,    // ww.w..b
    104,   // ..bw..b
    63,    // b.bw..b
    21,    // w.bw..b
    65,    // .bbw..b
    67,    // bbbw..b
    -64,   // wbbw..b
    -69,   // .wbw..b
    -30,   // bwbw..b
    -13,   // wwbw..b
    39,    // ..ww..b
    -6,    // b.ww..b
    41,    // w.ww..b
    25,    // .bww..b
    -55,   // bbww..b
    109,   // wbww..b
    -88,   // .www..b
    -27,   // bwww..b
    -70,   // wwww..b
    87,    // ....b.b
    7,     // b...b.b
    -91,   // w...b.b
    44,    // .b..b.b
    -93,   // bb..b.b
    122,   // wb..b.b
    36,    // .w..b.b
    18,    // bw..b.b
    28,    // ww..b.b
    -34,   // ..b.b.b
    28,    // b.b.b.b
    78,    // w.b.b.b
    29,    // .bb.b.b
    34,    // bbb.b.b
    15,    // wbb.b.b
    -122,  // .wb.b.b
    10,    // bwb.b.b
    -16,   // wwb.b.b
    79,    // ..w.b.b
    15,    // b.w.b.b
    0,     // w.w.b.b
    -52,   // .bw.b.b
    33,    // bbw.b.b
    28,    // wbw.b.b
    -55,   // .ww.b.b
    205,   // bww.b.b
    32,    // www.b.b
    86,    // ...bb.b
    -26,   // b..bb.b
    -41,   // w..bb.b
    34,    // .b.bb.b
    -33,   // bb.bb.b
    -65,   // wb.bb.b
    -34,   // .w.bb.b
    -27,   // bw.bb.b
    6,     // ww.bb.b
    123,   // ..bbb.b
    56,    // b.bbb.b
    -44,   // w.bbb.b
    130,   // .bbbb.b
    -88,   // bbbbb.b
    -30,   // wbbbb.b
    243,   // .wbbb.b
    -80,   // bwbbb.b
    2,     // wwbbb.b
    -76,   // ..wbb.b
    9,     // b.wbb.b
    83,    // w.wbb.b
    -55,   // .bwbb.b
    -51,   // bbwbb.b
    43,    // wbwbb.b
    25,    // .wwbb.b
    -52,   // bwwbb.b
    79,    // wwwbb.b
    83,    // ...wb.b
    63,    // b..wb.b
    -1,    // w..wb.b
    48,    // .b.wb.b
    0,     // bb.wb.b
    -3,    // wb.wb.b
    30,    // .w.wb.b
    31,    // bw.wb.b
    27,    // ww.wb.b
    8,     // ..bwb.b
    24,    // b.bwb.b
    -6,    // w.bwb.b
    -88,   // .bbwb.b
    -62,   // bbbwb.b
    16,    // wbbwb.b
    -24,   // .wbwb.b
    27,    // bwbwb.b
    106,   // wwbwb.b
    28,    // ..wwb.b
    -16,   // b.wwb.b
    -83,   // w.wwb.b
    -84,   // .bwwb.b
    -70,   // bbwwb.b
    31,    // wbwwb.b
    71,    // .wwwb.b
    -36,   // bwwwb.b
    14,    // wwwwb.b
    26,    // ....w.b
    -7,    // b...w.b
    77,    // w...w.b
    -20,   // .b..w.b
    -21,   // bb..w.b
    139,   // wb..w.b
    73,    // .w..w.b
    55,    // bw..w.b
    -35,   // ww..w.b
    -21,   // ..b.w.b
    15,    // b.b.w.b
    0,     // w.b.w.b
    -7,    // .bb.w.b
    -32,   // bbb.w.b
    -46,   // wbb.w.b
    24,    // .wb.w.b
    30,    // bwb.w.b
    -31,   // wwb.w.b
    26,    // ..w.w.b
    60,    // b.w.w.b
    -78,   // w.w.w.b
    -34,   // .bw.w.b
    -110,  // bbw.w.b
    45,    // wbw.w.b
    -18,   // .ww.w.b
    53,    // bww.w.b
    -1,    // www.w.b
    66,    // ...bw.b
    -61,   // b..bw.b
    -21,   // w..bw.b
    -18,   // .b.bw.b
    77,    // bb.bw.b
    -28,   // wb.bw.b
    -38,   // .w.bw.b
    41,    // bw.bw.b
    -39,   // ww.bw.b
    -49,   // ..bbw.b
    9,     // b.bbw.b
    40,    // w.bbw.b
    16,    // .bbbw.b
    101,   // bbbbw.b
    -28,   // wbbbw.b
    21,    // .wbbw.b
    101,   // bwbbw.b
    -2,    // wwbbw.b
    10,    // ..wbw.b
    -74,   // b.wbw.b
    6,     // w.wbw.b
    -44,   // .bwbw.b
    -4,    // bbwbw.b
    -48,   // wbwbw.b
    103,   // .wwbw.b
    77,    // bwwbw.b
    -47,   // wwwbw.b
    31,    // ...ww.b
    -6,    // b..ww.b
    17,    // w..ww.b
    4,     // .b.ww.b
    -14,   // bb.ww.b
    72,    // wb.ww.b
    -112,  // .w.ww.b
    -34,   // bw.ww.b
    4,     // ww.ww.b
    65,    // ..bww.b
    -16,   // b.bww.b
    -40,   // w.bww.b
    -22,   // .bbww.b
    125,   // bbbww.b
    59,    // wbbww.b
    20,    // .wbww.b
    69,    // bwbww.b
    -46,   // wwbww.b
    5,     // ..www.b
    -41,   // b.www.b
    44,    // w.www.b
    142,   // .bwww.b
    -42,   // bbwww.b
    -10,   // wbwww.b
    -81,   // .wwww.b
    3,     // bwwww.b
    -19,   // wwwww.b
    30,    // .....bb
    -10,   // b....bb
    43,    // w....bb
    -47,   // .b...bb
    7,     // bb...bb
    -56,   // wb...bb
    -29,   // .w...bb
    -34,   // bw...bb
    0,     // ww...bb
    -55,   // ..b..bb
    -93,   // b.b..bb
    35,    // w.b..bb
    12,    // .bb..bb
    143,   // bbb..bb
    -57,   // wbb..bb
    135,   // .wb..bb
    -52,   // bwb..bb
    36,    // wwb..bb
    -28,   // ..w..bb
    -21,   // b.w..bb
    -28,   // w.w..bb
    -13,   // .bw..bb
    -24,   // bbw..bb
    -8,    // wbw..bb
    89,    // .ww..bb
    -26,   // bww..bb
    -29,   // www..bb
    123,   // ...b.bb
    -41,   // b..b.bb
    -82,   // w..b.bb
    -84,   // .b.b.bb
    13,    // bb.b.bb
    83,    // wb.b.bb
    141,   // .w.b.bb
    -75,   // bw.b.bb
    37,    // ww.b.bb
    38,    // ..bb.bb
    -33,   // b.bb.bb
    -4,    // w.bb.bb
    21,    // .bbb.bb
    -43,   // bbbb.bb
    -6,    // wbbb.bb
    102,   // .wbb.bb
    47,    // bwbb.bb
    -120,  // wwbb.bb
    -22,   // ..wb.bb
    77,    // b.wb.bb
    -27,   // w.wb.bb
    -16,   // .bwb.bb
    -20,   // bbwb.bb
    -40,   // wbwb.bb
    41,    // .wwb.bb
    63,    // bwwb.bb
    54,    // wwwb.bb
    41,    // ...w.bb
    64,    // b..w.bb
    -103,  // w..w.bb
    -44,   // .b.w.bb
    70,    // bb.w.bb
    51,    // wb.w.bb
    19,    // .w.w.bb
    88,    // bw.w.bb
    -37,   // ww.w.bb
    -32,   // ..bw.bb
    0,     // b.bw.bb
    39,    // w.bw.bb
    82,    // .bbw.bb
    55,    // bbbw.bb
    98,    // wbbw.bb
    20,    // .wbw.bb
    175,   // bwbw.bb
    52,    // wwbw.bb
    51,    // ..ww.bb
    -14,   // b.ww.bb
    -6,    // w.ww.bb
    -20,   // .bww.bb
    -23,   // bbww.bb
    26,    // wbww.bb
    15,    // .www.bb
    10,    // bwww.bb
    -29,   // wwww.bb
    79,    // ....bbb
    -84,   // b...bbb
    93,    // w...bbb
    25,    // .b..bbb
    143,   // bb..bbb
    -20,   // wb..bbb
    90,    // .w..bbb
    6,     // bw..bbb
    29,    // ww..bbb
    190,   // ..b.bbb
    34,    // b.b.bbb
    1,     // w.b.bbb
    -19,   // .bb.bbb
    24,    // bbb.bbb
    5,     // wbb.bbb
    -9,    // .wb.bbb
    -75,   // bwb.bbb
    -87,   // wwb.bbb
    39,    // ..w.bbb
    -32,   // b.w.bbb
    -32,   // w.w.bbb
    -18,   // .bw.bbb
    55,    // bbw.bbb
    -68,   // wbw.bbb
    95,    // .ww.bbb
    -28,   // bww.bbb
    0,     // www.bbb
    694,   // ...bbbb
    10,    // b..bbbb
    70,    // w..bbbb
    -93,   // .b.bbbb
    -43,   // bb.bbbb
    61,    // wb.bbbb
    263,   // .w.bbbb
    108,   // bw.bbbb
    29,    // ww.bbbb
    85,    // ..bbbbb
    -88,   // b.bbbbb
    19,    // w.bbbbb
    -69,   // .bbbbbb
    -40,   // bbbbbbb
    -17,   // wbbbbbb
    302,   // .wbbbbb
    -12,   // bwbbbbb
    119,   // wwbbbbb
    106,   // ..wbbbb
    101,   // b.wbbbb
    -14,   // w.wbbbb
    -124,  // .bwbbbb
    -36,   // bbwbbbb
    58,    // wbwbbbb
    -52,   // .wwbbbb
    2,     // bwwbbbb
    -101,  // wwwbbbb
    117,   // ...wbbb
    67,    // b..wbbb
    -40,   // w..wbbb
    -110,  // .b.wbbb
    55,    // bb.wbbb
    -44,   // wb.wbbb
    -55,   // .w.wbbb
    26,    // bw.wbbb
    -54,   // ww.wbbb
    -158,  // ..bwbbb
    -62,   // b.bwbbb
    47,    // w.bwbbb
    -69,   // .bbwbbb
    -11,   // bbbwbbb
    -184,  // wbbwbbb
    -42,   // .wbwbbb
    53,    // bwbwbbb
    -18,   // wwbwbbb
    102,   // ..wwbbb
    125,   // b.wwbbb
    -79,   // w.wwbbb
    15,    // .bwwbbb
    70,    // bbwwbbb
    -94,   // wbwwbbb
    40,    // .wwwbbb
    13,    // bwwwbbb
    101,   // wwwwbbb
    -75,   // ....wbb
    -46,   // b...wbb
    -6,    // w...wbb
    -21,   // .b..wbb
    -24,   // bb..wbb
    -31,   // wb..wbb
    -35,   // .w..wbb
    50,    // bw..wbb
    -36,   // ww..wbb
    -40,   // ..b.wbb
    33,    // b.b.wbb
    31,    // w.b.wbb
    56,    // .bb.wbb
    55,    // bbb.wbb
    2,     // wbb.wbb
    -3,    // .wb.wbb
    27,    // bwb.wbb
    0,     // wwb.wbb
    39,    // ..w.wbb
    -110,  // b.w.wbb
    16,    // w.w.wbb
    -17,   // .bw.wbb
    -72,   // bbw.wbb
    -61,   // wbw.wbb
    22,    // .ww.wbb
    15,    // bww.wbb
    87,    // www.wbb
    -87,   // ...bwbb
    -85,   // b..bwbb
    13,    // w..bwbb
    40,    // .b.bwbb
    -20,   // bb.bwbb
    80,    // wb.bwbb
    -58,   // .w.bwbb
    -49,   // bw.bwbb
    -52,   // ww.bwbb
    -5,    // ..bbwbb
    -51,   // b.bbwbb
    46,    // w.bbwbb
    -110,  // .bbbwbb
    -36,   // bbbbwbb
    -21,   // wbbbwbb
    18,    // .wbbwbb
    -14,   // bwbbwbb
    35,    // wwbbwbb
    -26,   // ..wbwbb
    -4,    // b.wbwbb
    -106,  // w.wbwbb
    0,     // .bwbwbb
    45,    // bbwbwbb
    131,   // wbwbwbb
    -125,  // .wwbwbb
    21,    // bwwbwbb
    18,    // wwwbwbb
    4,     // ...wwbb
    -55,   // b..wwbb
    56,    // w..wwbb
    -4,    // .b.wwbb
    -23,   // bb.wwbb
    -14,   // wb.wwbb
    2,     // .w.wwbb
    99,    // bw.wwbb
    120,   // ww.wwbb
    -18,   // ..bwwbb
    -70,   // b.bwwbb
    2,     // w.bwwbb
    -51,   // .bbwwbb
    70,    // bbbwwbb
    17,    // wbbwwbb
    -75,   // .wbwwbb
    -34,   // bwbwwbb
    -35,   // wwbwwbb
    -27,   // ..wwwbb
    -42,   // b.wwwbb
    -2,    // w.wwwbb
    100,   // .bwwwbb
    -4,    // bbwwwbb
    13,    // wbwwwbb
    -6,    // .wwwwbb
    -4,    // bwwwwbb
    -119,  // wwwwwbb
    17,    // .....wb
    6,     // b....wb
    -11,   // w....wb
    -63,   // .b...wb
    -34,   // bb...wb
    0,     // wb...wb
    -29,   // .w...wb
    -152,  // bw...wb
    56,    // ww...wb
    -63,   // ..b..wb
    18,    // b.b..wb
    -139,  // w.b..wb
    -14,   // .bb..wb
    6,     // bbb..wb
    32,    // wbb..wb
    90,    // .wb..wb
    -95,   // bwb..wb
    31,    // wwb..wb
    -23,   // ..w..wb
    55,    // b.w..wb
    -122,  // w.w..wb
    -91,   // .bw..wb
    50,    // bbw..wb
    6,     // wbw..wb
    -2,    // .ww..wb
    -56,   // bww..wb
    20,    // www..wb
    -15,   // ...b.wb
    -3,    // b..b.wb
    24,    // w..b.wb
    2,     // .b.b.wb
    -75,   // bb.b.wb
    -52,   // wb.b.wb
    79,    // .w.b.wb
    46,    // bw.b.wb
    -51,   // ww.b.wb
    -8,    // ..bb.wb
    -27,   // b.bb.wb
    -72,   // w.bb.wb
    65,    // .bbb.wb
    108,   // bbbb.wb
    -29,   // wbbb.wb
    -41,   // .wbb.wb
    -47,   // bwbb.wb
    14,    // wwbb.wb
    -12,   // ..wb.wb
    41,    // b.wb.wb
    3,     // w.wb.wb
    -27,   // .bwb.wb
    -49,   // bbwb.wb
    -12,   // wbwb.wb
    -7,    // .wwb.wb
    68,    // bwwb.wb
    44,    // wwwb.wb
    80,    // ...w.wb
    -58,   // b..w.wb
    104,   // w..w.wb
    116,   // .b.w.wb
    88,    // bb.w.wb
    52,    // wb.w.wb
    -10,   // .w.w.wb
    22,    // bw.w.wb
    -83,   // ww.w.wb
    36,    // ..bw.wb
    31,    // b.bw.wb
    28,    // w.bw.wb
    -24,   // .bbw.wb
    26,    // bbbw.wb
    -21,   // wbbw.wb
    38,    // .wbw.wb
    44,    // bwbw.wb
    -80,   // wwbw.wb
    9,     // ..ww.wb
    -34,   // b.ww.wb
    65,    // w.ww.wb
    77,    // .bww.wb
    99,    // bbww.wb
    76,    // wbww.wb
    -57,   // .www.wb
    -43,   // bwww.wb
    -61,   // wwww.wb
    55,    // ....bwb
    5,     // b...bwb
    42,    // w...bwb
    -64,   // .b..bwb
    -52,   // bb..bwb
    -6,    // wb..bwb
    34,    // .w..bwb
    -95,   // bw..bwb
    8,     // ww..bwb
    -80,   // ..b.bwb
    10,    // b.b.bwb
    -45,   // w.b.bwb
    31,    // .bb.bwb
    -75,   // bbb.bwb
    -42,   // wbb.bwb
    9,     // .wb.bwb
    27,    // bwb.bwb
    61,    // wwb.bwb
    71,    // ..w.bwb
    30,    // b.w.bwb
    -28,   // w.w.bwb
    44,    // .bw.bwb
    27,    // bbw.bwb
    0,     // wbw.bwb
    123,   // .ww.bwb
    93,    // bww.bwb
    68,    // www.bwb
    -15,   // ...bbwb
    112,   // b..bbwb
    -109,  // w..bbwb
    -56,   // .b.bbwb
    47,    // bb.bbwb
    -76,   // wb.bbwb
    -161,  // .w.bbwb
    -47,   // bw.bbwb
    -26,   // ww.bbwb
    -51,   // ..bbbwb
    -80,   // b.bbbwb
    10,    // w.bbbwb
    -78,   // .bbbbwb
    -12,   // bbbbbwb
    -117,  // wbbbbwb
    14,    // .wbbbwb
    58,    // bwbbbwb
    -13,   // wwbbbwb
    11,    // ..wbbwb
    101,   // b.wbbwb
    -31,   // w.wbbwb
    -107,  // .bwbbwb
    -14,   // bbwbbwb
    66,    // wbwbbwb
    49,    // .wwbbwb
    10,    // bwwbbwb
    94,    // wwwbbwb
    17,    // ...wbwb
    -30,   // b..wbwb
    67,    // w..wbwb
    2,     // .b.wbwb
    175,   // bb.wbwb
    12,    // wb.wbwb
    -19,   // .w.wbwb
    44,    // bw.wbwb
    40,    // ww.wbwb
    -61,   // ..bwbwb
    27,    // b.bwbwb
    48,    // w.bwbwb
    -45,   // .bbwbwb
    53,    // bbbwbwb
    -45,   // wbbwbwb
    61,    // .wbwbwb
    -67,   // bwbwbwb
    -131,  // wwbwbwb
    -85,   // ..wwbwb
    69,    // b.wwbwb
    -43,   // w.wwbwb
    -107,  // .bwwbwb
    -34,   // bbwwbwb
    -66,   // wbwwbwb
    -81,   // .wwwbwb
    -111,  // bwwwbwb
    -58,   // wwwwbwb
    101,   // ....wwb
    -38,   // b...wwb
    125,   // w...wwb
    15,    // .b..wwb
    -26,   // bb..wwb
    -32,   // wb..wwb
    -89,   // .w..wwb
    -56,   // bw..wwb
    57,    // ww..wwb
    -49,   // ..b.wwb
    205,   // b.b.wwb
    46,    // w.b.wwb
    95,    // .bb.wwb
    -28,   // bbb.wwb
    0,     // wbb.wwb
    66,    // .wb.wwb
    93,    // bwb.wwb
    -2,    // wwb.wwb
    177,   // ..w.wwb
    53,    // b.w.wwb
    -15,   // w.w.wwb
    -48,   // .bw.wwb
    15,    // bbw.wwb
    42,    // wbw.wwb
    6,     // .ww.wwb
    -7,    // bww.wwb
    -5,    // www.wwb
    27,    // ...bwwb
    -78,   // b..bwwb
    64,    // w..bwwb
    -73,   // .b.bwwb
    63,    // bb.bwwb
    21,    // wb.bwwb
    92,    // .w.bwwb
    68,    // bw.bwwb
    -98,   // ww.bwwb
    -110,  // ..bbwwb
    -52,   // b.bbwwb
    -59,   // w.bbwwb
    25,    // .bbbwwb
    2,     // bbbbwwb
    15,    // wbbbwwb
    88,    // .wbbwwb
    10,    // bwbbwwb
    -17,   // wwbbwwb
    -14,   // ..wbwwb
    77,    // b.wbwwb
    -16,   // w.wbwwb
    100,   // .bwbwwb
    21,    // bbwbwwb
    45,    // wbwbwwb
    80,    // .wwbwwb
    -30,   // bwwbwwb
    184,   // wwwbwwb
    100,   // ...wwwb
    -27,   // b..wwwb
    102,   // w..wwwb
    38,    // .b.wwwb
    10,    // bb.wwwb
    29,    // wb.wwwb
    -89,   // .w.wwwb
    -43,   // bw.wwwb
    6,     // ww.wwwb
    34,    // ..bwwwb
    -36,   // b.bwwwb
    28,    // w.bwwwb
    110,   // .bbwwwb
    13,    // bbbwwwb
    -15,   // wbbwwwb
    11,    // .wbwwwb
    -111,  // bwbwwwb
    21,    // wwbwwwb
    -9,    // ..wwwwb
    3,     // b.wwwwb
    30,    // w.wwwwb
    264,   // .bwwwwb
    -4,    // bbwwwwb
    117,   // wbwwwwb
    -10,   // .wwwwwb
    89,    // bwwwwwb
    17,    // wwwwwwb
    -16,   // ......w
    0,     // b.....w
    -29,   // w.....w
    -74,   // .b....w
    43,    // bb....w
    -6,    // wb....w
    34,    // .w....w
    -11,   // bw....w
    10,    // ww....w
    -85,   // ..b...w
    -91,   // b.b...w
    7,     // w.b...w
    22,    // .bb...w
    93,    // bbb...w
    38,    // wbb...w
    -11,   // .wb...w
    42,    // bwb...w
    46,    // wwb...w
    -31,   // ..w...w
    77,    // b.w...w
    -7,    // w.w...w
    93,    // .bw...w
    -6,    // bbw...w
    -5,    // wbw...w
    -1,    // .ww...w
    125,   // bww...w
    84,    // www...w
    -9,    // ...b..w
    41,    // b..b..w
    8,     // w..b..w
    -19,   // .b.b..w
    -82,   // bb.b..w
    58,    // wb.b..w
    73,    // .w.b..w
    24,    // bw.b..w
    -64,   // ww.b..w
    -39,   // ..bb..w
    -41,   // b.bb..w
    6,     // w.bb..w
    88,    // .bbb..w
    70,    // bbbb..w
    27,    // wbbb..w
    -25,   // .wbb..w
    -109,  // bwbb..w
    55,    // wwbb..w
    -104,  // ..wb..w
    -21,   // b.wb..w
    -63,   // w.wb..w
    69,    // .bwb..w
    13,    // bbwb..w
    30,    // wbwb..w
    -65,   // .wwb..w
    64,    // bwwb..w
    -67,   // wwwb..w
    4,     // ...w..w
    -41,   // b..w..w
    39,    // w..w..w
    -14,   // .b.w..w
    -103,  // bb.w..w
    3,     // wb.w..w
    44,    // .w.w..w
    104,   // bw.w..w
    41,    // ww.w..w
    50,    // ..bw..w
    -1,    // b.bw..w
    61,    // w.bw..w
    36,    // .bbw..w
    -40,   // bbbw..w
    78,    // wbbw..w
    -38,   // .wbw..w
    67,    // bwbw..w
    85,    // wwbw..w
    -42,   // ..ww..w
    17,    // b.ww..w
    26,    // w.ww..w
    10,    // .bww..w
    56,    // bbww..w
    -112,  // wbww..w
    58,    // .www..w
    102,   // bwww..w
    -10,   // wwww..w
    -26,   // ....b.w
    -77,   // b...b.w
    7,     // w...b.w
    -73,   // .b..b.w
    35,    // bb..b.w
    -55,   // wb..b.w
    20,    // .w..b.w
    -139,  // bw..b.w
    21,    // ww..b.w
    -26,   // ..b.b.w
    78,    // b.b.b.w
    -60,   // w.b.b.w
    18,    // .bb.b.w
    1,     // bbb.b.w
    -53,   // wbb.b.w
    34,    // .wb.b.w
    -45,   // bwb.b.w
    110,   // wwb.b.w
    21,    // ..w.b.w
    0,     // b.w.b.w
    -15,   // w.w.b.w
    -24,   // .bw.b.w
    31,    // bbw.b.w
    -30,   // wbw.b.w
    7,     // .ww.b.w
    46,    // bww.b.w
    32,    // www.b.w
    -31,   // ...bb.w
    -17,   // b..bb.w
    6,     // w..bb.w
    112,   // .b.bb.w
    -4,    // bb.bb.w
    34,    // wb.bb.w
    -4,    // .w.bb.w
    -72,   // bw.bb.w
    14,    // ww.bb.w
    -5,    // ..bbb.w
    -44,   // b.bbb.w
    41,    // w.bbb.w
    81,    // .bbbb.w
    19,    // bbbbb.w
    -3,    // wbbbb.w
    -142,  // .wbbb.w
    10,    // bwbbb.w
    42,    // wwbbb.w
    -65,   // ..wbb.w
    40,    // b.wbb.w
    16,    // w.wbb.w
    -20,   // .bwbb.w
    46,    // bbwbb.w
    -69,   // wbwbb.w
    22,    // .wwbb.w
    -59,   // bwwbb.w
    -125,  // wwwbb.w
    -66,   // ...wb.w
    21,    // b..wb.w
    61,    // w..wb.w
    38,    // .b.wb.w
    39,    // bb.wb.w
    -41,   // wb.wb.w
    18,    // .w.wb.w
    28,    // bw.wb.w
    -77,   // ww.wb.w
    -10,   // ..bwb.w
    -6,    // b.bwb.w
    74,    // w.bwb.w
    -103,  // .bbwb.w
    47,    // bbbwb.w
    -77,   // wbbwb.w
    44,    // .wbwb.w
    48,    // bwbwb.w
    4,     // wwbwb.w
    49,    // ..wwb.w
    -40,   // b.wwb.w
    -9,    // w.wwb.w
    -21,   // .bwwb.w
    2,     // bbwwb.w
    -101,  // wbwwb.w
    -16,   // .wwwb.w
    28,    // bwwwb.w
    -101,  // wwwwb.w
    -87,   // ....w.w
    91,    // b...w.w
    -7,    // w...w.w
    -36,   // .b..w.w
    -28,   // bb..w.w
    -18,   // wb..w.w
    -44,   // .w..w.w
    -122,  // bw..w.w
    93,    // ww..w.w
    -79,   // ..b.w.w
    0,     // b.b.w.w
    -15,   // w.b.w.w
    55,    // .bb.w.w
    -32,   // bbb.w.w
    -205,  // wbb.w.w
    52,    // .wb.w.w
    -28,   // bwb.w.w
    -33,   // wwb.w.w
    34,    // ..w.w.w
    -78,   // b.w.w.w
    -28,   // w.w.w.w
    122,   // .bw.w.w
    16,    // bbw.w.w
    -10,   // wbw.w.w
    -29,   // .ww.w.w
    -15,   // bww.w.w
    -34,   // www.w.w
    -83,   // ...bw.w
    1,     // b..bw.w
    -63,   // w..bw.w
    -30,   // .b.bw.w
    -27,   // bb.bw.w
    -31,   // wb.bw.w
    -48,   // .w.bw.w
    3,     // bw.bw.w
    0,     // ww.bw.w
    -28,   // ..bbw.w
    83,    // b.bbw.w
    16,    // w.bbw.w
    -71,   // .bbbw.w
    -14,   // bbbbw.w
    36,    // wbbbw.w
    84,    // .wbbw.w
    -31,   // bwbbw.w
    70,    // wwbbw.w
    -8,    // ..wbw.w
    6,     // b.wbw.w
    -24,   // w.wbw.w
    24,    // .bwbw.w
    -106,  // bbwbw.w
    -27,   // wbwbw.w
    88,    // .wwbw.w
    -16,   // bwwbw.w
    62,    // wwwbw.w
    -86,   // ...ww.w
    41,    // b..ww.w
    26,    // w..ww.w
    34,    // .b.ww.w
    -6,    // bb.ww.w
    27,    // wb.ww.w
    -34,   // .w.ww.w
    65,    // bw.ww.w
    33,    // ww.ww.w
    76,    // ..bww.w
    -83,   // b.bww.w
    -9,    // w.bww.w
    -25,   // .bbww.w
    -79,   // bbbww.w
    52,    // wbbww.w
    55,    // .wbww.w
    -43,   // bwbww.w
    51,    // wwbww.w
    -123,  // ..www.w
    44,    // b.www.w
    -56,   // w.www.w
    -243,  // .bwww.w
    -2,    // bbwww.w
    80,    // wbwww.w
    -130,  // .wwww.w
    30,    // bwwww.w
    88,    // wwwww.w
    -17,   // .....bw
    11,    // b....bw
    -6,    // w....bw
    29,    // .b...bw
    -56,   // bb...bw
    152,   // wb...bw
    63,    // .w...bw
    0,     // bw...bw
    34,    // ww...bw
    23,    // ..b..bw
    122,   // b.b..bw
    -55,   // w.b..bw
    2,     // .bb..bw
    -20,   // bbb..bw
    56,    // wbb..bw
    91,    // .wb..bw
    -6,    // bwb..bw
    -50,   // wwb..bw
    63,    // ..w..bw
    139,   // b.w..bw
    -18,   // w.w..bw
    -90,   // .bw..bw
    -31,   // bbw..bw
    95,    // wbw..bw
    14,    // .ww..bw
    -32,   // bww..bw
    -6,    // www..bw
    -80,   // ...b.bw
    -104,  // b..b.bw
    58,    // w..b.bw
    10,    // .b.b.bw
    83,    // bb.b.bw
    -22,   // wb.b.bw
    -116,  // .w.b.bw
    -52,   // bw.b.bw
    -88,   // ww.b.bw
    -9,    // ..bb.bw
    -65,   // b.bb.bw
    34,    // w.bb.bw
    57,    // .bbb.bw
    61,    // bbbb.bw
    43,    // wbbb.bw
    -77,   // .wbb.bw
    -76,   // bwbb.bw
    -99,   // wwbb.bw
    -36,   // ..wb.bw
    -28,   // b.wb.bw
    -31,   // w.wb.bw
    -38,   // .bwb.bw
    80,    // bbwb.bw
    -44,   // wbwb.bw
    24,    // .wwb.bw
    21,    // bwwb.bw
    -26,   // wwwb.bw
    15,    // ...w.bw
    -24,   // b..w.bw
    3,     // w..w.bw
    -79,   // .b.w.bw
    51,    // bb.w.bw
    -46,   // wb.w.bw
    -2,    // .w.w.bw
    52,    // bw.w.bw
    75,    // ww.w.bw
    12,    // ..bw.bw
    -3,    // b.bw.bw
    -41,   // w.bw.bw
    7,     // .bbw.bw
    -44,   // bbbw.bw
    -68,   // wbbw.bw
    27,    // .wbw.bw
    12,    // bwbw.bw
    49,    // wwbw.bw
    8,     // ..ww.bw
    72,    // b.ww.bw
    27,    // w.ww.bw
    41,    // .bww.bw
    -14,   // bbww.bw
    47,    // wbww.bw
    -65,   // .www.bw
    29,    // bwww.bw
    -108,  // wwww.bw
    -101,  // ....bbw
    -125,  // b...bbw
    38,    // w...bbw
    89,    // .b..bbw
    -57,   // bb..bbw
    56,    // wb..bbw
    -15,   // .w..bbw
    32,    // bw..bbw
    26,    // ww..bbw
    -177,  // ..b.bbw
    15,    // b.b.bbw
    -53,   // w.b.bbw
    -6,    // .bb.bbw
    5,     // bbb.bbw
    7,     // wbb.bbw
    48,    // .wb.bbw
    -42,   // bwb.bbw
    -15,   // wwb.bbw
    49,    // ..w.bbw
    -46,   // b.w.bbw
    -205,  // w.w.bbw
    -66,   // .bw.bbw
    2,     // bbw.bbw
    -93,   // wbw.bbw
    -95,   // .ww.bbw
    0,     // bww.bbw
    28,    // www.bbw
    -100,  // ...bbbw
    -102,  // b..bbbw
    27,    // w..bbbw
    89,    // .b.bbbw
    -6,    // bb.bbbw
    43,    // wb.bbbw
    -38,   // .w.bbbw
    -29,   // bw.bbbw
    -10,   // ww.bbbw
    9,     // ..bbbbw
    -30,   // b.bbbbw
    -3,    // w.bbbbw
    10,    // .bbbbbw
    -17,   // bbbbbbw
    -89,   // wbbbbbw
    -264,  // .wbbbbw
    -117,  // bwbbbbw
    4,     // wwbbbbw
    -34,   // ..wbbbw
    -28,   // b.wbbbw
    36,    // w.wbbbw
    -11,   // .bwbbbw
    -21,   // bbwbbbw
    111,   // wbwbbbw
    -110,  // .wwbbbw
    15,    // bwwbbbw
    -13,   // wwwbbbw
    -27,   // ...wbbw
    -64,   // b..wbbw
    78,    // w..wbbw
    -92,   // .b.wbbw
    98,    // bb.wbbw
    -68,   // wb.wbbw
    73,    // .w.wbbw
    -21,   // bw.wbbw
    -63,   // ww.wbbw
    14,    // ..bwbbw
    16,    // b.bwbbw
    -77,   // w.bwbbw
    -80,   // .bbwbbw
    -184,  // bbbwbbw
    30,    // wbbwbbw
    -100,  // .wbwbbw
    -45,   // bwbwbbw
    -21,   // wwbwbbw
    110,   // ..wwbbw
    59,    // b.wwbbw
    52,    // w.wwbbw
    -88,   // .bwwbbw
    17,    // bbwwbbw
    -10,   // wbwwbbw
    -25,   // .wwwbbw
    -15,   // bwwwbbw
    -2,    // wwwwbbw
    -55,   // ....wbw
    -42,   // b...wbw
    -5,    // w...wbw
    -34,   // .b..wbw
    -8,    // bb..wbw
    95,    // wb..wbw
    64,    // .w..wbw
    6,     // bw..wbw
    52,    // ww..wbw
    -71,   // ..b.wbw
    28,    // b.b.wbw
    -30,   // w.b.wbw
    -123,  // .bb.wbw
    -68,   // bbb.wbw
    -93,   // wbb.wbw
    -44,   // .wb.wbw
    0,     // bwb.wbw
    -27,   // wwb.wbw
    80,    // ..w.wbw
    45,    // b.w.wbw
    -10,   // w.w.wbw
    -9,    // .bw.wbw
    -61,   // bbw.wbw
    -27,   // wbw.wbw
    -31,   // .ww.wbw
    42,    // bww.wbw
    75,    // www.wbw
    -17,   // ...bwbw
    -67,   // b..bwbw
    30,    // w..bwbw
    19,    // .b.bwbw
    -40,   // bb.bwbw
    -44,   // wb.bwbw
    -2,    // .w.bwbw
    -12,   // bw.bwbw
    -175,  // ww.bwbw
    85,    // ..bbwbw
    43,    // b.bbwbw
    -69,   // w.bbwbw
    81,    // .bbbwbw
    58,    // bbbbwbw
    111,   // wbbbwbw
    107,   // .wbbwbw
    66,    // bwbbwbw
    34,    // wwbbwbw
    61,    // ..wbwbw
    -48,   // b.wbwbw
    -27,   // w.wbwbw
    -61,   // .bwbwbw
    131,   // bbwbwbw
    67,    // wbwbwbw
    45,    // .wwbwbw
    45,    // bwwbwbw
    -53,   // wwwbwbw
    15,    // ...wwbw
    109,   // b..wwbw
    -112,  // w..wwbw
    161,   // .b.wwbw
    26,    // bb.wwbw
    47,    // wb.wwbw
    56,    // .w.wwbw
    76,    // bw.wwbw
    -47,   // ww.wwbw
    -11,   // ..bwwbw
    31,    // b.bwwbw
    -101,  // w.bwwbw
    -49,   // .bbwwbw
    -94,   // bbbwwbw
    -10,   // wbbwwbw
    107,   // .wbwwbw
    -66,   // bwbwwbw
    14,    // wwbwwbw
    51,    // ..wwwbw
    -10,   // b.wwwbw
    80,    // w.wwwbw
    -14,   // .bwwwbw
    13,    // bbwwwbw
    -58,   // wbwwwbw
    78,    // .wwwwbw
    117,   // bwwwwbw
    12,    // wwwwwbw
    -30,   // .....ww
    -43,   // b....ww
    10,    // w....ww
    29,    // .b...ww
    0,     // bb...ww
    34,    // wb...ww
    47,    // .w...ww
    56,    // bw...ww
    -7,    // ww...ww
    28,    // ..b..ww
    28,    // b.b..ww
    21,    // w.b..ww
    -89,   // .bb..ww
    29,    // bbb..ww
    26,    // wbb..ww
    13,    // .wb..ww
    8,     // bwb..ww
    24,    // wwb..ww
    55,    // ..w..ww
    -35,   // b.w..ww
    93,    // w.w..ww
    -135,  // .bw..ww
    -36,   // bbw..ww
    52,    // wbw..ww
    -12,   // .ww..ww
    57,    // bww..ww
    -143,  // www..ww
    -41,   // ...b.ww
    103,   // b..b.ww
    -64,   // w..b.ww
    -19,   // .b.b.ww
    37,    // bb.b.ww
    -88,   // wb.b.ww
    44,    // .w.b.ww
    -51,   // bw.b.ww
    -70,   // ww.b.ww
    -51,   // ..bb.ww
    6,     // b.bb.ww
    14,    // w.bb.ww
    -15,   // .bbb.ww
    29,    // bbbb.ww
    -10,   // wbbb.ww
    20,    // .wbb.ww
    -26,   // bwbb.ww
    23,    // wwbb.ww
    32,    // ..wb.ww
    -39,   // b.wb.ww
    0,     // w.wb.ww
    -20,   // .bwb.ww
    -52,   // bbwb.ww
    -175,  // wbwb.ww
    -82,   // .wwb.ww
    -98,   // bwwb.ww
    -55,   // wwwb.ww
    -123,  // ...w.ww
    82,    // b..w.ww
    41,    // w..w.ww
    -141,  // .b.w.ww
    -37,   // bb.w.ww
    75,    // wb.w.ww
    84,    // .w.w.ww
    -83,   // bw.w.ww
    -13,   // ww.w.ww
    22,    // ..bw.ww
    27,    // b.bw.ww
    -77,   // w.bw.ww
    -41,   // .bbw.ww
    -54,   // bbbw.ww
    -63,   // wbbw.ww
    16,    // .wbw.ww
    40,    // bwbw.ww
    20,    // wwbw.ww
    -38,   // ..ww.ww
    4,     // b.ww.ww
    33,    // w.ww.ww
    -102,  // .bww.ww
    120,   // bbww.ww
    -47,   // wbww.ww
    -21,   // .www.ww
    6,     // bwww.ww
    43,    // wwww.ww
    75,    // ....bww
    6,     // b...bww
    46,    // w...bww
    35,    // .b..bww
    36,    // bb..bww
    -50,   // wb..bww
    21,    // .w..bww
    31,    // bw..bww
    24,    // ww..bww
    -39,   // ..b.bww
    -16,   // b.b.bww
    110,   // w.b.bww
    -22,   // .bb.bww
    -87,   // bbb.bww
    -15,   // wbb.bww
    17,    // .wb.bww
    61,    // bwb.bww
    72,    // wwb.bww
    40,    // ..w.bww
    -31,   // b.w.bww
    -33,   // w.w.bww
    3,     // .bw.bww
    0,     // bbw.bww
    -27,   // wbw.bww
    -56,   // .ww.bww
    -2,    // bww.bww
    -55,   // www.bww
    -4,    // ...bbww
    -56,   // b..bbww
    55,    // w..bbww
    -2,    // .b.bbww
    -120,  // bb.bbww
    -99,   // wb.bbww
    4,     // .w.bbww
    14,    // bw.bbww
    23,    // ww.bbww
    27,    // ..bbbww
    2,     // b.bbbww
    42,    // w.bbbww
    6,     // .bbbbww
    119,   // bbbbbww
    4,     // wbbbbww
    -100,  // .wbbbww
    -13,   // bwbbbww
    4,     // wwbbbww
    18,    // ..wbbww
    -2,    // b.wbbww
    70,    // w.wbbww
    75,    // .bwbbww
    35,    // bbwbbww
    34,    // wbwbbww
    51,    // .wwbbww
    -17,   // bwwbbww
    -70,   // wwwbbww
    87,    // ...wbww
    -13,   // b..wbww
    85,    // w..wbww
    58,    // .b.wbww
    52,    // bb.wbww
    49,    // wb.wbww
    -40,   // .w.wbww
    -80,   // bw.wbww
    20,    // ww.wbww
    26,    // ..bwbww
    106,   // b.bwbww
    4,     // w.bwbww
    125,   // .bbwbww
    -18,   // bbbwbww
    -21,   // wbbwbww
    0,     // .wbwbww
    -131,  // bwbwbww
    -45,   // wwbwbww
    5,     // ..wwbww
    -46,   // b.wwbww
    51,    // w.wwbww
    -18,   // .bwwbww
    -35,   // bbwwbww
    14,    // wbwwbww
    110,   // .wwwbww
    21,    // bwwwbww
    36,    // wwwwbww
    -79,   // ....www
    -93,   // b...www
    84,    // w...www
    -90,   // .b..www
    -29,   // bb..www
    -6,    // wb..www
    -25,   // .w..www
    20,    // bw..www
    -143,  // ww..www
    -39,   // ..b.www
    32,    // b.b.www
    32,    // w.b.www
    -95,   // .bb.www
    0,     // bbb.www
    28,    // wbb.www
    18,    // .wb.www
    68,    // bwb.www
    -55,   // wwb.www
    -190,  // ..w.www
    -1,    // b.w.www
    -34,   // w.w.www
    9,     // .bw.www
    87,    // bbw.www
    75,    // wbw.www
    19,    // .ww.www
    -5,    // bww.www
    -24,   // www.www
    -117,  // ...bwww
    40,    // b..bwww
    -67,   // w..bwww
    55,    // .b.bwww
    54,    // bb.bwww
    -26,   // wb.bwww
    110,   // .w.bwww
    44,    // bw.bwww
    -55,   // ww.bwww
    -102,  // ..bbwww
    79,    // b.bbwww
    -125,  // w.bbwww
    -40,   // .bbbwww
    -101,  // bbbbwww
    -13,   // wbbbwww
    -15,   // .wbbwww
    94,    // bwbbwww
    -70,   // wwbbwww
    158,   // ..wbwww
    -47,   // b.wbwww
    62,    // w.wbwww
    42,    // .bwbwww
    18,    // bbwbwww
    -53,   // wbwbwww
    69,    // .wwbwww
    184,   // bwwbwww
    11,    // wwwbwww
    -694,  // ...wwww
    -70,   // b..wwww
    -10,   // w..wwww
    -263,  // .b.wwww
    -29,   // bb.wwww
    -108,  // wb.wwww
    93,    // .w.wwww
    -61,   // bw.wwww
    43,    // ww.wwww
    -106,  // ..bwwww
    14,    // b.bwwww
    -101,  // w.bwwww
    52,    // .bbwwww
    101,   // bbbwwww
    -2,    // wbbwwww
    124,   // .wbwwww
    -58,   // bwbwwww
    36,    // wwbwwww
    -85,   // ..wwwww
    -19,   // b.wwwww
    88,    // w.wwwww
    -302,  // .bwwwww
    -119,  // bbwwwww
    12,    // wbwwwww
    69,    // .wwwwww
    17,    // bwwwwww
    40,    // wwwwwww
    0,     // captures=0 threats=0
    57,    // captures=0 threats=1
    120,   // captures=0 threats=2
    165,   // captures=0 threats=3
    167,   // captures=0 threats=4
    73,    // captures=0 additional threats
    72,    // captures=1 threats=0
    127,   // captures=1 threats=1
    212,   // captures=1 threats=2
    448,   // captures=1 threats=3
    522,   // captures=1 threats=4
    9,     // captures=1 additional threats
    96,    // captures=2 threats=0
    275,   // captures=2 threats=1
    389,   // captures=2 threats=2
    674,   // captures=2 threats=3
    817,   // captures=2 threats=4
    145,   // captures=2 additional threats
    148,   // captures=3 threats=0
    455,   // captures=3 threats=1
    631,   // captures=3 threats=2
    761,   // captures=3 threats=3
    866,   // captures=3 threats=4
    190,   // captures=3 additional threats
    171,   // captures=4 threats=0
    468,   // captures=4 threats=1
    748,   // captures=4 threats=2
    963,   // captures=4 threats=3
    1218,  // captures=4 threats=4
    344,   // captures=4 additional threats
].into_boxed_slice()
