vec![
    0,     // .......
    8,     // b......
    -8,    // w......
    6,     // .b.....
    14,    // bb.....
    -12,   // wb.....
    -6,    // .w.....
    12,    // bw.....
    -14,   // ww.....
    1,     // ..b....
    65,    // b.b....
    -38,   // w.b....
    41,    // .bb....
    166,   // bbb....
    -88,   // wbb....
    -21,   // .wb....
    36,    // bwb....
    46,    // wwb....
    -1,    // ..w....
    38,    // b.w....
    -65,   // w.w....
    21,    // .bw....
    -46,   // bbw....
    -36,   // wbw....
    -41,   // .ww....
    88,    // bww....
    -166,  // www....
    -9,    // ...b...
    1,     // b..b...
    -7,    // w..b...
    -6,    // .b.b...
    148,   // bb.b...
    -40,   // wb.b...
    12,    // .w.b...
    35,    // bw.b...
    -24,   // ww.b...
    -22,   // ..bb...
    66,    // b.bb...
    37,    // w.bb...
    57,    // .bbb...
    308,   // bbbb...
    -100,  // wbbb...
    52,    // .wbb...
    2,     // bwbb...
    22,    // wwbb...
    7,     // ..wb...
    80,    // b.wb...
    -53,   // w.wb...
    -16,   // .bwb...
    -52,   // bbwb...
    -14,   // wbwb...
    8,     // .wwb...
    13,    // bwwb...
    -55,   // wwwb...
    9,     // ...w...
    7,     // b..w...
    -1,    // w..w...
    -12,   // .b.w...
    24,    // bb.w...
    -35,   // wb.w...
    6,     // .w.w...
    40,    // bw.w...
    -148,  // ww.w...
    -7,    // ..bw...
    53,    // b.bw...
    -80,   // w.bw...
    -8,    // .bbw...
    55,    // bbbw...
    -13,   // wbbw...
    16,    // .wbw...
    14,    // bwbw...
    52,    // wwbw...
    22,    // ..ww...
    -37,   // b.ww...
    -66,   // w.ww...
    -52,   // .bww...
    -22,   // bbww...
    -2,    // wbww...
    -57,   // .www...
    100,   // bwww...
    -308,  // wwww...
    1,     // ....b..
    19,    // b...b..
    -28,   // w...b..
    11,    // .b..b..
    24,    // bb..b..
    33,    // wb..b..
    -9,    // .w..b..
    9,     // bw..b..
    38,    // ww..b..
    -10,   // ..b.b..
    24,    // b.b.b..
    -33,   // w.b.b..
    -76,   // .bb.b..
    141,   // bbb.b..
    -62,   // wbb.b..
    -4,    // .wb.b..
    -53,   // bwb.b..
    -14,   // wwb.b..
    0,     // ..w.b..
    32,    // b.w.b..
    -36,   // w.w.b..
    -23,   // .bw.b..
    -23,   // bbw.b..
    -33,   // wbw.b..
    35,    // .ww.b..
    11,    // bww.b..
    -78,   // www.b..
    -22,   // ...bb..
    -41,   // b..bb..
    14,    // w..bb..
    -6,    // .b.bb..
    40,    // bb.bb..
    8,     // wb.bb..
    -67,   // .w.bb..
    6,     // bw.bb..
    -25,   // ww.bb..
    25,    // ..bbb..
    102,   // b.bbb..
    -20,   // w.bbb..
    274,   // .bbbb..
    46,    // bbbbb..
    51,    // wbbbb..
    -26,   // .wbbb..
    -48,   // bwbbb..
    -50,   // wwbbb..
    -66,   // ..wbb..
    -22,   // b.wbb..
    -45,   // w.wbb..
    -16,   // .bwbb..
    -26,   // bbwbb..
    43,    // wbwbb..
    21,    // .wwbb..
    -125,  // bwwbb..
    -73,   // wwwbb..
    -7,    // ...wb..
    74,    // b..wb..
    29,    // w..wb..
    -30,   // .b.wb..
    -63,   // bb.wb..
    -8,    // wb.wb..
    46,    // .w.wb..
    8,     // bw.wb..
    8,     // ww.wb..
    -3,    // ..bwb..
    30,    // b.bwb..
    -6,    // w.bwb..
    7,     // .bbwb..
    -145,  // bbbwb..
    73,    // wbbwb..
    17,    // .wbwb..
    -9,    // bwbwb..
    -30,   // wwbwb..
    66,    // ..wwb..
    34,    // b.wwb..
    113,   // w.wwb..
    -5,    // .bwwb..
    49,    // bbwwb..
    -18,   // wbwwb..
    -87,   // .wwwb..
    -7,    // bwwwb..
    -46,   // wwwwb..
    -1,    // ....w..
    28,    // b...w..
    -19,   // w...w..
    9,     // .b..w..
    -38,   // bb..w..
    -9,    // wb..w..
    -11,   // .w..w..
    -33,   // bw..w..
    -24,   // ww..w..
    0,     // ..b.w..
    36,    // b.b.w..
    -32,   // w.b.w..
    -35,   // .bb.w..
    78,    // bbb.w..
    -11,   // wbb.w..
    23,    // .wb.w..
    33,    // bwb.w..
    23,    // wwb.w..
    10,    // ..w.w..
    33,    // b.w.w..
    -24,   // w.w.w..
    4,     // .bw.w..
    14,    // bbw.w..
    53,    // wbw.w..
    76,    // .ww.w..
    62,    // bww.w..
    -141,  // www.w..
    7,     // ...bw..
    -29,   // b..bw..
    -74,   // w..bw..
    -46,   // .b.bw..
    -8,    // bb.bw..
    -8,    // wb.bw..
    30,    // .w.bw..
    8,     // bw.bw..
    63,    // ww.bw..
    -66,   // ..bbw..
    -113,  // b.bbw..
    -34,   // w.bbw..
    87,    // .bbbw..
    46,    // bbbbw..
    7,     // wbbbw..
    5,     // .wbbw..
    18,    // bwbbw..
    -49,   // wwbbw..
    3,     // ..wbw..
    6,     // b.wbw..
    -30,   // w.wbw..
    -17,   // .bwbw..
    30,    // bbwbw..
    9,     // wbwbw..
    -7,    // .wwbw..
    -73,   // bwwbw..
    145,   // wwwbw..
    22,    // ...ww..
    -14,   // b..ww..
    41,    // w..ww..
    67,    // .b.ww..
    25,    // bb.ww..
    -6,    // wb.ww..
    6,     // .w.ww..
    -8,    // bw.ww..
    -40,   // ww.ww..
    66,    // ..bww..
    45,    // b.bww..
    22,    // w.bww..
    -21,   // .bbww..
    73,    // bbbww..
    125,   // wbbww..
    16,    // .wbww..
    -43,   // bwbww..
    26,    // wwbww..
    -25,   // ..www..
    20,    // b.www..
    -102,  // w.www..
    26,    // .bwww..
    50,    // bbwww..
    48,    // wbwww..
    -274,  // .wwww..
    -51,   // bwwww..
    -46,   // wwwww..
    6,     // .....b.
    -9,    // b....b.
    -62,   // w....b.
    -14,   // .b...b.
    2,     // bb...b.
    -4,    // wb...b.
    0,     // .w...b.
    3,     // bw...b.
    -13,   // ww...b.
    11,    // ..b..b.
    25,    // b.b..b.
    -33,   // w.b..b.
    37,    // .bb..b.
    13,    // bbb..b.
    116,   // wbb..b.
    -12,   // .wb..b.
    -20,   // bwb..b.
    55,    // wwb..b.
    9,     // ..w..b.
    -21,   // b.w..b.
    -20,   // w.w..b.
    -21,   // .bw..b.
    -8,    // bbw..b.
    -42,   // wbw..b.
    -35,   // .ww..b.
    2,     // bww..b.
    -53,   // www..b.
    -6,    // ...b.b.
    -68,   // b..b.b.
    -32,   // w..b.b.
    -8,    // .b.b.b.
    -50,   // bb.b.b.
    -8,    // wb.b.b.
    -35,   // .w.b.b.
    0,     // bw.b.b.
    -18,   // ww.b.b.
    -6,    // ..bb.b.
    -27,   // b.bb.b.
    97,    // w.bb.b.
    62,    // .bbb.b.
    -74,   // bbbb.b.
    118,   // wbbb.b.
    1,     // .wbb.b.
    0,     // bwbb.b.
    -26,   // wwbb.b.
    -46,   // ..wb.b.
    -54,   // b.wb.b.
    -55,   // w.wb.b.
    26,    // .bwb.b.
    26,    // bbwb.b.
    17,    // wbwb.b.
    21,    // .wwb.b.
    35,    // bwwb.b.
    72,    // wwwb.b.
    -12,   // ...w.b.
    -21,   // b..w.b.
    -28,   // w..w.b.
    -8,    // .b.w.b.
    -45,   // bb.w.b.
    -33,   // wb.w.b.
    35,    // .w.w.b.
    71,    // bw.w.b.
    -119,  // ww.w.b.
    -30,   // ..bw.b.
    31,    // b.bw.b.
    27,    // w.bw.b.
    38,    // .bbw.b.
    -83,   // bbbw.b.
    -78,   // wbbw.b.
    30,    // .wbw.b.
    33,    // bwbw.b.
    17,    // wwbw.b.
    67,    // ..ww.b.
    -10,   // b.ww.b.
    -59,   // w.ww.b.
    43,    // .bww.b.
    -6,    // bbww.b.
    103,   // wbww.b.
    -1,    // .www.b.
    45,    // bwww.b.
    -260,  // wwww.b.
    41,    // ....bb.
    -24,   // b...bb.
    29,    // w...bb.
    37,    // .b..bb.
    12,    // bb..bb.
    -25,   // wb..bb.
    35,    // .w..bb.
    17,    // bw..bb.
    -83,   // ww..bb.
    -76,   // ..b.bb.
    -17,   // b.b.bb.
    22,    // w.b.bb.
    29,    // .bb.bb.
    14,    // bbb.bb.
    -48,   // wbb.bb.
    -65,   // .wb.bb.
    -34,   // bwb.bb.
    -38,   // wwb.bb.
    -35,   // ..w.bb.
    -53,   // b.w.bb.
    15,    // w.w.bb.
    -17,   // .bw.bb.
    -4,    // bbw.bb.
    -80,   // wbw.bb.
    0,     // .ww.bb.
    58,    // bww.bb.
    -55,   // www.bb.
    57,    // ...bbb.
    30,    // b..bbb.
    -27,   // w..bbb.
    62,    // .b.bbb.
    -31,   // bb.bbb.
    104,   // wb.bbb.
    1,     // .w.bbb.
    95,    // bw.bbb.
    4,     // ww.bbb.
    274,   // ..bbbb.
    46,    // b.bbbb.
    77,    // w.bbbb.
    -56,   // .bbbbb.
    -14,   // bbbbbb.
    -39,   // wbbbbb.
    105,   // .wbbbb.
    -16,   // bwbbbb.
    -35,   // wwbbbb.
    87,    // ..wbbb.
    1,     // b.wbbb.
    -13,   // w.wbbb.
    64,    // .bwbbb.
    -110,  // bbwbbb.
    50,    // wbwbbb.
    -5,    // .wwbbb.
    49,    // bwwbbb.
    -17,   // wwwbbb.
    -8,    // ...wbb.
    15,    // b..wbb.
    -10,   // w..wbb.
    38,    // .b.wbb.
    54,    // bb.wbb.
    52,    // wb.wbb.
    -21,   // .w.wbb.
    -34,   // bw.wbb.
    -69,   // ww.wbb.
    7,     // ..bwbb.
    -120,  // b.bwbb.
    -34,   // w.bwbb.
    31,    // .bbwbb.
    -21,   // bbbwbb.
    -65,   // wbbwbb.
    30,    // .wbwbb.
    -57,   // bwbwbb.
    118,   // wwbwbb.
    -21,   // ..wwbb.
    -38,   // b.wwbb.
    19,    // w.wwbb.
    4,     // .bwwbb.
    -102,  // bbwwbb.
    3,     // wbwwbb.
    5,     // .wwwbb.
    55,    // bwwwbb.
    -17,   // wwwwbb.
    21,    // ....wb.
    -13,   // b...wb.
    23,    // w...wb.
    -21,   // .b..wb.
    43,    // bb..wb.
    -72,   // wb..wb.
    12,    // .w..wb.
    -19,   // bw..wb.
    -37,   // ww..wb.
    -23,   // ..b.wb.
    -34,   // b.b.wb.
    17,    // w.b.wb.
    -17,   // .bb.wb.
    35,    // bbb.wb.
    29,    // wbb.wb.
    0,     // .wb.wb.
    -2,    // bwb.wb.
    3,     // wwb.wb.
    4,     // ..w.wb.
    -1,    // b.w.wb.
    72,    // w.w.wb.
    49,    // .bw.wb.
    3,     // bbw.wb.
    -3,    // wbw.wb.
    65,    // .ww.wb.
    -76,   // bww.wb.
    -3,    // www.wb.
    -16,   // ...bwb.
    44,    // b..bwb.
    56,    // w..bwb.
    26,    // .b.bwb.
    31,    // bb.bwb.
    -71,   // wb.bwb.
    -30,   // .w.bwb.
    -33,   // bw.bwb.
    -20,   // ww.bwb.
    -16,   // ..bbwb.
    -15,   // b.bbwb.
    -28,   // w.bbwb.
    64,    // .bbbwb.
    -79,   // bbbbwb.
    -12,   // wbbbwb.
    7,     // .wbbwb.
    -48,   // bwbbwb.
    83,    // wwbbwb.
    -17,   // ..wbwb.
    -40,   // b.wbwb.
    11,    // w.wbwb.
    33,    // .bwbwb.
    7,     // bbwbwb.
    -27,   // wbwbwb.
    -30,   // .wwbwb.
    113,   // bwwbwb.
    -2,    // wwwbwb.
    -52,   // ...wwb.
    -16,   // b..wwb.
    23,    // w..wwb.
    43,    // .b.wwb.
    -68,   // bb.wwb.
    -19,   // wb.wwb.
    -1,    // .w.wwb.
    32,    // bw.wwb.
    -69,   // ww.wwb.
    -5,    // ..bwwb.
    -43,   // b.bwwb.
    -39,   // w.bwwb.
    4,     // .bbwwb.
    -23,   // bbbwwb.
    -78,   // wbbwwb.
    -7,    // .wbwwb.
    -51,   // bwbwwb.
    -15,   // wwbwwb.
    26,    // ..wwwb.
    108,   // b.wwwb.
    -131,  // w.wwwb.
    2,     // .bwwwb.
    30,    // bbwwwb.
    -68,   // wbwwwb.
    -105,  // .wwwwb.
    114,   // bwwwwb.
    -108,  // wwwwwb.
    -6,    // .....w.
    62,    // b....w.
    9,     // w....w.
    0,     // .b...w.
    13,    // bb...w.
    -3,    // wb...w.
    14,    // .w...w.
    4,     // bw...w.
    -2,    // ww...w.
    -9,    // ..b..w.
    20,    // b.b..w.
    21,    // w.b..w.
    35,    // .bb..w.
    53,    // bbb..w.
    -2,    // wbb..w.
    21,    // .wb..w.
    42,    // bwb..w.
    8,     // wwb..w.
    -11,   // ..w..w.
    33,    // b.w..w.
    -25,   // w.w..w.
    12,    // .bw..w.
    -55,   // bbw..w.
    20,    // wbw..w.
    -37,   // .ww..w.
    -116,  // bww..w.
    -13,   // www..w.
    12,    // ...b.w.
    28,    // b..b.w.
    21,    // w..b.w.
    -35,   // .b.b.w.
    119,   // bb.b.w.
    -71,   // wb.b.w.
    8,     // .w.b.w.
    33,    // bw.b.w.
    45,    // ww.b.w.
    -67,   // ..bb.w.
    59,    // b.bb.w.
    10,    // w.bb.w.
    1,     // .bbb.w.
    260,   // bbbb.w.
    -45,   // wbbb.w.
    -43,   // .wbb.w.
    -103,  // bwbb.w.
    6,     // wwbb.w.
    30,    // ..wb.w.
    -27,   // b.wb.w.
    -31,   // w.wb.w.
    -30,   // .bwb.w.
    -17,   // bbwb.w.
    -33,   // wbwb.w.
    -38,   // .wwb.w.
    78,    // bwwb.w.
    83,    // wwwb.w.
    6,     // ...w.w.
    32,    // b..w.w.
    68,    // w..w.w.
    35,    // .b.w.w.
    18,    // bb.w.w.
    0,     // wb.w.w.
    8,     // .w.w.w.
    8,     // bw.w.w.
    50,    // ww.w.w.
    46,    // ..bw.w.
    55,    // b.bw.w.
    54,    // w.bw.w.
    -21,   // .bbw.w.
    -72,   // bbbw.w.
    -35,   // wbbw.w.
    -26,   // .wbw.w.
    -17,   // bwbw.w.
    -26,   // wwbw.w.
    6,     // ..ww.w.
    -97,   // b.ww.w.
    27,    // w.ww.w.
    -1,    // .bww.w.
    26,    // bbww.w.
    0,     // wbww.w.
    -62,   // .www.w.
    -118,  // bwww.w.
    74,    // wwww.w.
    -21,   // ....bw.
    -23,   // b...bw.
    13,    // w...bw.
    -12,   // .b..bw.
    37,    // bb..bw.
    19,    // wb..bw.
    21,    // .w..bw.
    72,    // bw..bw.
    -43,   // ww..bw.
    -4,    // ..b.bw.
    -72,   // b.b.bw.
    1,     // w.b.bw.
    -65,   // .bb.bw.
    3,     // bbb.bw.
    76,    // wbb.bw.
    -49,   // .wb.bw.
    3,     // bwb.bw.
    -3,    // wwb.bw.
    23,    // ..w.bw.
    -17,   // b.w.bw.
    34,    // w.w.bw.
    0,     // .bw.bw.
    -3,    // bbw.bw.
    2,     // wbw.bw.
    17,    // .ww.bw.
    -29,   // bww.bw.
    -35,   // www.bw.
    52,    // ...bbw.
    -23,   // b..bbw.
    16,    // w..bbw.
    1,     // .b.bbw.
    69,    // bb.bbw.
    -32,   // wb.bbw.
    -43,   // .w.bbw.
    19,    // bw.bbw.
    68,    // ww.bbw.
    -26,   // ..bbbw.
    131,   // b.bbbw.
    -108,  // w.bbbw.
    105,   // .bbbbw.
    108,   // bbbbbw.
    -114,  // wbbbbw.
    -2,    // .wbbbw.
    68,    // bwbbbw.
    -30,   // wwbbbw.
    5,     // ..wbbw.
    39,    // b.wbbw.
    43,    // w.wbbw.
    7,     // .bwbbw.
    15,    // bbwbbw.
    51,    // wbwbbw.
    -4,    // .wwbbw.
    78,    // bwwbbw.
    23,    // wwwbbw.
    16,    // ...wbw.
    -56,   // b..wbw.
    -44,   // w..wbw.
    30,    // .b.wbw.
    20,    // bb.wbw.
    33,    // wb.wbw.
    -26,   // .w.wbw.
    71,    // bw.wbw.
    -31,   // ww.wbw.
    17,    // ..bwbw.
    -11,   // b.bwbw.
    40,    // w.bwbw.
    30,    // .bbwbw.
    2,     // bbbwbw.
    -113,  // wbbwbw.
    -33,   // .wbwbw.
    27,    // bwbwbw.
    -7,    // wwbwbw.
    16,    // ..wwbw.
    28,    // b.wwbw.
    15,    // w.wwbw.
    -7,    // .bwwbw.
    -83,   // bbwwbw.
    48,    // wbwwbw.
    -64,   // .wwwbw.
    12,    // bwwwbw.
    79,    // wwwwbw.
    -41,   // ....ww.
    -29,   // b...ww.
    24,    // w...ww.
    -35,   // .b..ww.
    83,    // bb..ww.
    -17,   // wb..ww.
    -37,   // .w..ww.
    25,    // bw..ww.
    -12,   // ww..ww.
    35,    // ..b.ww.
    -15,   // b.b.ww.
    53,    // w.b.ww.
    0,     // .bb.ww.
    55,    // bbb.ww.
    -58,   // wbb.ww.
    17,    // .wb.ww.
    80,    // bwb.ww.
    4,     // wwb.ww.
    76,    // ..w.ww.
    -22,   // b.w.ww.
    17,    // w.w.ww.
    65,    // .bw.ww.
    38,    // bbw.ww.
    34,    // wbw.ww.
    -29,   // .ww.ww.
    48,    // bww.ww.
    -14,   // www.ww.
    8,     // ...bww.
    10,    // b..bww.
    -15,   // w..bww.
    21,    // .b.bww.
    69,    // bb.bww.
    34,    // wb.bww.
    -38,   // .w.bww.
    -52,   // bw.bww.
    -54,   // ww.bww.
    21,    // ..bbww.
    -19,   // b.bbww.
    38,    // w.bbww.
    -5,    // .bbbww.
    17,    // bbbbww.
    -55,   // wbbbww.
    -4,    // .wbbww.
    -3,    // bwbbww.
    102,   // wwbbww.
    -7,    // ..wbww.
    34,    // b.wbww.
    120,   // w.wbww.
    -30,   // .bwbww.
    -118,  // bbwbww.
    57,    // wbwbww.
    -31,   // .wwbww.
    65,    // bwwbww.
    21,    // wwwbww.
    -57,   // ...www.
    27,    // b..www.
    -30,   // w..www.
    -1,    // .b.www.
    -4,    // bb.www.
    -95,   // wb.www.
    -62,   // .w.www.
    -104,  // bw.www.
    31,    // ww.www.
    -87,   // ..bwww.
    13,    // b.bwww.
    -1,    // w.bwww.
    5,     // .bbwww.
    17,    // bbbwww.
    -49,   // wbbwww.
    -64,   // .wbwww.
    -50,   // bwbwww.
    110,   // wwbwww.
    -274,  // ..wwww.
    -77,   // b.wwww.
    -46,   // w.wwww.
    -105,  // .bwwww.
    35,    // bbwwww.
    16,    // wbwwww.
    56,    // .wwwww.
    39,    // bwwwww.
    14,    // wwwwww.
    8,     // ......b
    -47,   // b.....b
    0,     // w.....b
    -9,    // .b....b
    -22,   // bb....b
    9,     // wb....b
    62,    // .w....b
    55,    // bw....b
    20,    // ww....b
    19,    // ..b...b
    64,    // b.b...b
    -28,   // w.b...b
    -24,   // .bb...b
    -27,   // bbb...b
    -73,   // wbb...b
    -23,   // .wb...b
    -11,   // bwb...b
    8,     // wwb...b
    28,    // ..w...b
    8,     // b.w...b
    58,    // w.w...b
    -13,   // .bw...b
    7,     // bbw...b
    -7,    // wbw...b
    -29,   // .ww...b
    -47,   // bww...b
    -52,   // www...b
    1,     // ...b..b
    2,     // b..b..b
    59,    // w..b..b
    -68,   // .b.b..b
    30,    // bb.b..b
    -59,   // wb.b..b
    28,    // .w.b..b
    -50,   // bw.b..b
    117,   // ww.b..b
    -41,   // ..bb..b
    -67,   // b.bb..b
    36,    // w.bb..b
    30,    // .bbb..b
    22,    // bbbb..b
    -99,   // wbbb..b
    -23,   // .wbb..b
    133,   // bwbb..b
    -68,   // wwbb..b
    -29,   // ..wb..b
    -2,    // b.wb..b
    10,    // w.wb..b
    44,    // .bwb..b
    -43,   // bbwb..b
    -39,   // wbwb..b
    10,    // .wwb..b
    -12,   // bwwb..b
    6,     // wwwb..b
    7,     // ...w..b
    -55,   // b..w..b
    -59,   // w..w..b
    -21,   // .b.w..b
    0,     // bb.w..b
    -62,   // wb.w..b
    32,    // .w.w..b
    -48,   // bw.w..b
    25,    // ww.w..b
    74,    // ..bw..b
    21,    // b.bw..b
    34,    // w.bw..b
    15,    // .bbw..b
    52,    // bbbw..b
    -16,   // wbbw..b
    -56,   // .wbw..b
    -73,   // bwbw..b
    -5,    // wwbw..b
    -14,   // ..ww..b
    -43,   // b.ww..b
    46,    // w.ww..b
    -16,   // .bww..b
    -42,   // bbww..b
    34,    // wbww..b
    27,    // .www..b
    18,    // bwww..b
    -74,   // wwww..b
    65,    // ....b.b
    64,    // b...b.b
    -58,   // w...b.b
    25,    // .b..b.b
    -77,   // bb..b.b
    90,    // wb..b.b
    20,    // .w..b.b
    49,    // bw..b.b
    3,     // ww..b.b
    24,    // ..b.b.b
    20,    // b.b.b.b
    64,    // w.b.b.b
    -17,   // .bb.b.b
    46,    // bbb.b.b
    2,     // wbb.b.b
    -72,   // .wb.b.b
    -46,   // bwb.b.b
    -57,   // wwb.b.b
    36,    // ..w.b.b
    24,    // b.w.b.b
    0,     // w.w.b.b
    -34,   // .bw.b.b
    19,    // bbw.b.b
    13,    // wbw.b.b
    -15,   // .ww.b.b
    65,    // bww.b.b
    -21,   // www.b.b
    66,    // ...bb.b
    -67,   // b..bb.b
    -46,   // w..bb.b
    -27,   // .b.bb.b
    -50,   // bb.bb.b
    -71,   // wb.bb.b
    59,    // .w.bb.b
    29,    // bw.bb.b
    -56,   // ww.bb.b
    102,   // ..bbb.b
    56,    // b.bbb.b
    -41,   // w.bbb.b
    46,    // .bbbb.b
    -57,   // bbbbb.b
    16,    // wbbbb.b
    131,   // .wbbb.b
    -35,   // bwbbb.b
    17,    // wwbbb.b
    -113,  // ..wbb.b
    7,     // b.wbb.b
    88,    // w.wbb.b
    -15,   // .bwbb.b
    -17,   // bbwbb.b
    19,    // wbwbb.b
    -19,   // .wwbb.b
    -78,   // bwwbb.b
    88,    // wwwbb.b
    53,    // ...wb.b
    21,    // b..wb.b
    -10,   // w..wb.b
    31,    // .b.wb.b
    25,    // bb.wb.b
    48,    // wb.wb.b
    55,    // .w.wb.b
    -24,   // bw.wb.b
    42,    // ww.wb.b
    30,    // ..bwb.b
    33,    // b.bwb.b
    7,     // w.bwb.b
    -120,  // .bbwb.b
    -51,   // bbbwb.b
    -57,   // wbbwb.b
    -11,   // .wbwb.b
    35,    // bwbwb.b
    73,    // wwbwb.b
    45,    // ..wwb.b
    21,    // b.wwb.b
    -88,   // w.wwb.b
    -43,   // .bwwb.b
    -9,    // bbwwb.b
    20,    // wbwwb.b
    13,    // .wwwb.b
    22,    // bwwwb.b
    17,    // wwwwb.b
    38,    // ....w.b
    8,     // b...w.b
    28,    // w...w.b
    -21,   // .b..w.b
    14,    // bb..w.b
    106,   // wb..w.b
    33,    // .w..w.b
    14,    // bw..w.b
    -42,   // ww..w.b
    32,    // ..b.w.b
    24,    // b.b.w.b
    0,     // w.b.w.b
    -53,   // .bb.w.b
    28,    // bbb.w.b
    80,    // wbb.w.b
    -17,   // .wb.w.b
    73,    // bwb.w.b
    -3,    // wwb.w.b
    33,    // ..w.w.b
    47,    // b.w.w.b
    -64,   // w.w.w.b
    -1,    // .bw.w.b
    -6,    // bbw.w.b
    71,    // wbw.w.b
    -22,   // .ww.w.b
    11,    // bww.w.b
    16,    // www.w.b
    80,    // ...bw.b
    -2,    // b..bw.b
    -34,   // w..bw.b
    -54,   // .b.bw.b
    3,     // bb.bw.b
    17,    // wb.bw.b
    -27,   // .w.bw.b
    52,    // bw.bw.b
    7,     // ww.bw.b
    -22,   // ..bbw.b
    7,     // b.bbw.b
    -12,   // w.bbw.b
    1,     // .bbbw.b
    60,    // bbbbw.b
    0,     // wbbbw.b
    39,    // .wbbw.b
    17,    // bwbbw.b
    -55,   // wwbbw.b
    6,     // ..wbw.b
    -38,   // b.wbw.b
    -7,    // w.wbw.b
    -40,   // .bwbw.b
    10,    // bbwbw.b
    -66,   // wbwbw.b
    34,    // .wwbw.b
    38,    // bwwbw.b
    -87,   // wwwbw.b
    -37,   // ...ww.b
    -43,   // b..ww.b
    -36,   // w..ww.b
    -10,   // .b.ww.b
    -24,   // bb.ww.b
    59,    // wb.ww.b
    -97,   // .w.ww.b
    14,    // bw.ww.b
    -28,   // ww.ww.b
    34,    // ..bww.b
    21,    // b.bww.b
    12,    // w.bww.b
    -38,   // .bbww.b
    65,    // bbbww.b
    66,    // wbbww.b
    28,    // .wbww.b
    29,    // bwbww.b
    -58,   // wwbww.b
    20,    // ..www.b
    -73,   // b.www.b
    41,    // w.www.b
    108,   // .bwww.b
    3,     // bbwww.b
    28,    // wbwww.b
    -77,   // .wwww.b
    -5,    // bwwww.b
    -48,   // wwwww.b
    14,    // .....bb
    -22,   // b....bb
    -20,   // w....bb
    2,     // .b...bb
    -22,   // bb...bb
    -34,   // wb...bb
    13,    // .w...bb
    18,    // bw...bb
    0,     // ww...bb
    24,    // ..b..bb
    -77,   // b.b..bb
    42,    // w.b..bb
    12,    // .bb..bb
    60,    // bbb..bb
    -14,   // wbb..bb
    37,    // .wb..bb
    -87,   // bwb..bb
    16,    // wwb..bb
    -38,   // ..w..bb
    14,    // b.w..bb
    -3,    // w.w..bb
    43,    // .bw..bb
    19,    // bbw..bb
    12,    // wbw..bb
    83,    // .ww..bb
    14,    // bww..bb
    18,    // www..bb
    148,   // ...b.bb
    30,    // b..b.bb
    -25,   // w..b.bb
    -50,   // .b.b.bb
    25,    // bb.b.bb
    50,    // wb.b.bb
    119,   // .w.b.bb
    -44,   // bw.b.bb
    -3,    // ww.b.bb
    40,    // ..bb.bb
    -50,   // b.bb.bb
    28,    // w.bb.bb
    -31,   // .bbb.bb
    -53,   // bbbb.bb
    5,     // wbbb.bb
    69,    // .wbb.bb
    -14,   // bwbb.bb
    -84,   // wwbb.bb
    -8,    // ..wb.bb
    3,     // b.wb.bb
    -42,   // w.wb.bb
    31,    // .bwb.bb
    25,    // bbwb.bb
    0,     // wbwb.bb
    69,    // .wwb.bb
    3,     // bwwb.bb
    27,    // wwwb.bb
    24,    // ...w.bb
    0,     // b..w.bb
    -117,  // w..w.bb
    -45,   // .b.w.bb
    84,    // bb.w.bb
    9,     // wb.w.bb
    18,    // .w.w.bb
    30,    // bw.w.bb
    3,     // ww.w.bb
    -63,   // ..bw.bb
    25,    // b.bw.bb
    -7,    // w.bw.bb
    54,    // .bbw.bb
    64,    // bbbw.bb
    42,    // wbbw.bb
    20,    // .wbw.bb
    60,    // bwbw.bb
    123,   // wwbw.bb
    25,    // ..ww.bb
    -24,   // b.ww.bb
    56,    // w.ww.bb
    -68,   // .bww.bb
    -51,   // bbww.bb
    -21,   // wbww.bb
    -4,    // .www.bb
    0,     // bwww.bb
    -46,   // wwww.bb
    166,   // ....bbb
    -27,   // b...bbb
    52,    // w...bbb
    13,    // .b..bbb
    60,    // bb..bbb
    42,    // wb..bbb
    53,    // .w..bbb
    -8,    // bw..bbb
    -18,   // ww..bbb
    141,   // ..b.bbb
    46,    // b.b.bbb
    -16,   // w.b.bbb
    14,    // .bb.bbb
    35,    // bbb.bbb
    17,    // wbb.bbb
    3,     // .wb.bbb
    -42,   // bwb.bbb
    -63,   // wwb.bbb
    78,    // ..w.bbb
    28,    // b.w.bbb
    21,    // w.w.bbb
    35,    // .bw.bbb
    59,    // bbw.bbb
    -55,   // wbw.bbb
    55,    // .ww.bbb
    -28,   // bww.bbb
    0,     // www.bbb
    308,   // ...bbbb
    22,    // b..bbbb
    74,    // w..bbbb
    -74,   // .b.bbbb
    -53,   // bb.bbbb
    49,    // wb.bbbb
    260,   // .w.bbbb
    72,    // bw.bbbb
    46,    // ww.bbbb
    46,    // ..bbbbb
    -57,   // b.bbbbb
    48,    // w.bbbbb
    -14,   // .bbbbbb
    -36,   // bbbbbbb
    -27,   // wbbbbbb
    108,   // .wbbbbb
    -16,   // bwbbbbb
    67,    // wwbbbbb
    46,    // ..wbbbb
    60,    // b.wbbbb
    -17,   // w.wbbbb
    -79,   // .bwbbbb
    -24,   // bbwbbbb
    64,    // wbwbbbb
    17,    // .wwbbbb
    -21,   // bwwbbbb
    -89,   // wwwbbbb
    55,    // ...wbbb
    52,    // b..wbbb
    -6,    // w..wbbb
    -83,   // .b.wbbb
    64,    // bb.wbbb
    29,    // wb.wbbb
    -72,   // .w.wbbb
    21,    // bw.wbbb
    -27,   // ww.wbbb
    -145,  // ..bwbbb
    -51,   // b.bwbbb
    87,    // w.bwbbb
    -21,   // .bbwbbb
    47,    // bbbwbbb
    -164,  // wbbwbbb
    2,     // .wbwbbb
    19,    // bwbwbbb
    -18,   // wwbwbbb
    73,    // ..wwbbb
    65,    // b.wwbbb
    -88,   // w.wwbbb
    -23,   // .bwwbbb
    19,    // bbwwbbb
    -46,   // wbwwbbb
    17,    // .wwwbbb
    33,    // bwwwbbb
    89,    // wwwwbbb
    -46,   // ....wbb
    7,     // b...wbb
    -8,    // w...wbb
    -8,    // .b..wbb
    19,    // bb..wbb
    39,    // wb..wbb
    -55,   // .w..wbb
    55,    // bw..wbb
    -16,   // ww..wbb
    -23,   // ..b.wbb
    19,    // b.b.wbb
    3,     // w.b.wbb
    -4,    // .bb.wbb
    59,    // bbb.wbb
    -11,   // wbb.wbb
    -3,    // .wb.wbb
    32,    // bwb.wbb
    0,     // wwb.wbb
    14,    // ..w.wbb
    -6,    // b.w.wbb
    57,    // w.w.wbb
    3,     // .bw.wbb
    -100,  // bbw.wbb
    -67,   // wbw.wbb
    38,    // .ww.wbb
    -12,   // bww.wbb
    63,    // www.wbb
    -52,   // ...bwbb
    -43,   // b..bwbb
    5,     // w..bwbb
    26,    // .b.bwbb
    25,    // bb.bwbb
    16,    // wb.bwbb
    -17,   // .w.bwbb
    -55,   // bw.bwbb
    -123,  // ww.bwbb
    -26,   // ..bbwbb
    -17,   // b.bbwbb
    58,    // w.bbwbb
    -110,  // .bbbwbb
    -24,   // bbbbwbb
    13,    // wbbbwbb
    15,    // .wbbwbb
    17,    // bwbbwbb
    62,    // wwbbwbb
    30,    // ..wbwbb
    10,    // b.wbwbb
    -73,   // w.wbwbb
    7,     // .bwbwbb
    -35,   // bbwbwbb
    130,   // wbwbwbb
    -118,  // .wwbwbb
    -5,    // bwwbwbb
    18,    // wwwbwbb
    -22,   // ...wwbb
    -42,   // b..wwbb
    68,    // w..wwbb
    -6,    // .b.wwbb
    -51,   // bb.wwbb
    -4,    // wb.wwbb
    26,    // .w.wwbb
    84,    // bw.wwbb
    84,    // ww.wwbb
    49,    // ..bwwbb
    -9,    // b.bwwbb
    55,    // w.bwwbb
    -102,  // .bbwwbb
    19,    // bbbwwbb
    25,    // wbbwwbb
    -83,   // .wbwwbb
    -16,   // bwbwwbb
    -62,   // wwbwwbb
    50,    // ..wwwbb
    3,     // b.wwwbb
    -17,   // w.wwwbb
    30,    // .bwwwbb
    2,     // bbwwwbb
    -21,   // wbwwwbb
    35,    // .wwwwbb
    -19,   // bwwwwbb
    -67,   // wwwwwbb
    12,    // .....wb
    55,    // b....wb
    -9,    // w....wb
    3,     // .b...wb
    18,    // bb...wb
    0,     // wb...wb
    4,     // .w...wb
    -102,  // bw...wb
    34,    // ww...wb
    9,     // ..b..wb
    49,    // b.b..wb
    -106,  // w.b..wb
    17,    // .bb..wb
    -8,    // bbb..wb
    -61,   // wbb..wb
    72,    // .wb..wb
    -43,   // bwb..wb
    -39,   // wwb..wb
    -33,   // ..w..wb
    14,    // b.w..wb
    -90,   // w.w..wb
    -19,   // .bw..wb
    55,    // bbw..wb
    29,    // wbw..wb
    25,    // .ww..wb
    -43,   // bww..wb
    -42,   // www..wb
    35,    // ...b.wb
    -50,   // b..b.wb
    62,    // w..b.wb
    0,     // .b.b.wb
    -44,   // bb.b.wb
    13,    // wb.b.wb
    33,    // .w.b.wb
    -82,   // bw.b.wb
    -9,    // ww.b.wb
    6,     // ..bb.wb
    29,    // b.bb.wb
    -59,   // w.bb.wb
    95,    // .bbb.wb
    72,    // bbbb.wb
    -8,    // wbbb.wb
    19,    // .wbb.wb
    -37,   // bwbb.wb
    4,     // wwbb.wb
    8,     // ..wb.wb
    52,    // b.wb.wb
    -48,   // w.wb.wb
    -33,   // .bwb.wb
    -55,   // bbwb.wb
    -48,   // wbwb.wb
    -52,   // .wwb.wb
    126,   // bwwb.wb
    -29,   // wwwb.wb
    40,    // ...w.wb
    -48,   // b..w.wb
    59,    // w..w.wb
    71,    // .b.w.wb
    30,    // bb.w.wb
    -13,   // wb.w.wb
    8,     // .w.w.wb
    -1,    // bw.w.wb
    -50,   // ww.w.wb
    8,     // ..bw.wb
    -24,   // b.bw.wb
    -17,   // w.bw.wb
    -34,   // .bbw.wb
    21,    // bbbw.wb
    -30,   // wbbw.wb
    71,    // .wbw.wb
    31,    // bwbw.wb
    -16,   // wwbw.wb
    -8,    // ..ww.wb
    14,    // b.ww.wb
    71,    // w.ww.wb
    32,    // .bww.wb
    84,    // bbww.wb
    43,    // wbww.wb
    -104,  // .www.wb
    -68,   // bwww.wb
    -49,   // wwww.wb
    36,    // ....bwb
    -11,   // b...bwb
    7,     // w...bwb
    -20,   // .b..bwb
    -87,   // bb..bwb
    -29,   // wb..bwb
    42,    // .w..bwb
    -43,   // bw..bwb
    -12,   // ww..bwb
    -53,   // ..b.bwb
    -46,   // b.b.bwb
    -71,   // w.b.bwb
    -34,   // .bb.bwb
    -42,   // bbb.bwb
    31,    // wbb.bwb
    3,     // .wb.bwb
    -3,    // bwb.bwb
    67,    // wwb.bwb
    33,    // ..w.bwb
    73,    // b.w.bwb
    -13,   // w.w.bwb
    -2,    // .bw.bwb
    32,    // bbw.bwb
    0,     // wbw.bwb
    80,    // .ww.bwb
    46,    // bww.bwb
    55,    // www.bwb
    2,     // ...bbwb
    133,   // b..bbwb
    -34,   // w..bbwb
    0,     // .b.bbwb
    -14,   // bb.bbwb
    -43,   // wb.bbwb
    -103,  // .w.bbwb
    -37,   // bw.bbwb
    21,    // ww.bbwb
    -48,   // ..bbbwb
    -35,   // b.bbbwb
    -28,   // w.bbbwb
    -16,   // .bbbbwb
    -16,   // bbbbbwb
    -101,  // wbbbbwb
    68,    // .wbbbwb
    55,    // bwbbbwb
    21,    // wwbbbwb
    18,    // ..wbbwb
    17,    // b.wbbwb
    -20,   // w.wbbwb
    -48,   // .bwbbwb
    17,    // bbwbbwb
    95,    // wbwbbwb
    -3,    // .wwbbwb
    -4,    // bwwbbwb
    46,    // wwwbbwb
    14,    // ...wbwb
    -73,   // b..wbwb
    39,    // w..wbwb
    33,    // .b.wbwb
    60,    // bb.wbwb
    48,    // wb.wbwb
    -17,   // .w.wbwb
    31,    // bw.wbwb
    0,     // ww.wbwb
    -9,    // ..bwbwb
    35,    // b.bwbwb
    66,    // w.bwbwb
    -57,   // .bbwbwb
    19,    // bbbwbwb
    -7,    // wbbwbwb
    27,    // .wbwbwb
    -65,   // bwbwbwb
    -130,  // wwbwbwb
    -43,   // ..wwbwb
    29,    // b.wwbwb
    -19,   // w.wwbwb
    -51,   // .bwwbwb
    -16,   // bbwwbwb
    -95,   // wbwwbwb
    -50,   // .wwwbwb
    -3,    // bwwwbwb
    -64,   // wwwwbwb
    88,    // ....wwb
    -47,   // b...wwb
    73,    // w...wwb
    2,     // .b..wwb
    14,    // bb..wwb
    61,    // wb..wwb
    -116,  // .w..wwb
    -43,   // bw..wwb
    14,    // ww..wwb
    11,    // ..b.wwb
    65,    // b.b.wwb
    -80,   // w.b.wwb
    58,    // .bb.wwb
    -28,   // bbb.wwb
    0,     // wbb.wwb
    -29,   // .wb.wwb
    46,    // bwb.wwb
    11,    // wwb.wwb
    62,    // ..w.wwb
    11,    // b.w.wwb
    -2,    // w.w.wwb
    -76,   // .bw.wwb
    -12,   // bbw.wwb
    -31,   // wbw.wwb
    48,    // .ww.wwb
    -57,   // bww.wwb
    -17,   // www.wwb
    13,    // ...bwwb
    -12,   // b..bwwb
    16,    // w..bwwb
    35,    // .b.bwwb
    3,     // bb.bwwb
    30,    // wb.bwwb
    78,    // .w.bwwb
    126,   // bw.bwwb
    -42,   // ww.bwwb
    -125,  // ..bbwwb
    -78,   // b.bbwwb
    -66,   // w.bbwwb
    49,    // .bbbwwb
    -21,   // bbbbwwb
    15,    // wbbbwwb
    78,    // .wbbwwb
    -4,    // bwbbwwb
    -25,   // wwbbwwb
    -73,   // ..wbwwb
    38,    // b.wbwwb
    57,    // w.wbwwb
    113,   // .bwbwwb
    -5,    // bbwbwwb
    7,     // wbwbwwb
    65,    // .wwbwwb
    12,    // bwwbwwb
    164,   // wwwbwwb
    100,   // ...wwwb
    18,    // b..wwwb
    99,    // w..wwwb
    45,    // .b.wwwb
    0,     // bb.wwwb
    8,     // wb.wwwb
    -118,  // .w.wwwb
    -68,   // bw.wwwb
    -5,    // ww.wwwb
    -7,    // ..bwwwb
    22,    // b.bwwwb
    0,     // w.bwwwb
    55,    // .bbwwwb
    33,    // bbbwwwb
    -15,   // wbbwwwb
    12,    // .wbwwwb
    -3,    // bwbwwwb
    -13,   // wwbwwwb
    -51,   // ..wwwwb
    -5,    // b.wwwwb
    -16,   // w.wwwwb
    114,   // .bwwwwb
    -19,   // bbwwwwb
    101,   // wbwwwwb
    39,    // .wwwwwb
    31,    // bwwwwwb
    27,    // wwwwwwb
    -8,    // ......w
    0,     // b.....w
    47,    // w.....w
    -62,   // .b....w
    -20,   // bb....w
    -55,   // wb....w
    9,     // .w....w
    -9,    // bw....w
    22,    // ww....w
    -28,   // ..b...w
    -58,   // b.b...w
    -8,    // w.b...w
    29,    // .bb...w
    52,    // bbb...w
    47,    // wbb...w
    13,    // .wb...w
    7,     // bwb...w
    -7,    // wwb...w
    -19,   // ..w...w
    28,    // b.w...w
    -64,   // w.w...w
    23,    // .bw...w
    -8,    // bbw...w
    11,    // wbw...w
    24,    // .ww...w
    73,    // bww...w
    27,    // www...w
    -7,    // ...b..w
    59,    // b..b..w
    55,    // w..b..w
    -32,   // .b.b..w
    -25,   // bb.b..w
    48,    // wb.b..w
    21,    // .w.b..w
    62,    // bw.b..w
    0,     // ww.b..w
    14,    // ..bb..w
    -46,   // b.bb..w
    43,    // w.bb..w
    -27,   // .bbb..w
    74,    // bbbb..w
    -18,   // wbbb..w
    16,    // .wbb..w
    -34,   // bwbb..w
    42,    // wwbb..w
    -74,   // ..wb..w
    -34,   // b.wb..w
    -21,   // w.wb..w
    56,    // .bwb..w
    5,     // bbwb..w
    73,    // wbwb..w
    -15,   // .wwb..w
    16,    // bwwb..w
    -52,   // wwwb..w
    -1,    // ...w..w
    -59,   // b..w..w
    -2,    // w..w..w
    -28,   // .b.w..w
    -117,  // bb.w..w
    50,    // wb.w..w
    68,    // .w.w..w
    59,    // bw.w..w
    -30,   // ww.w..w
    29,    // ..bw..w
    -10,   // b.bw..w
    2,     // w.bw..w
    -10,   // .bbw..w
    -6,    // bbbw..w
    12,    // wbbw..w
    -44,   // .wbw..w
    39,    // bwbw..w
    43,    // wwbw..w
    41,    // ..ww..w
    -36,   // b.ww..w
    67,    // w.ww..w
    23,    // .bww..w
    68,    // bbww..w
    -133,  // wbww..w
    -30,   // .www..w
    99,    // bwww..w
    -22,   // wwww..w
    -38,   // ....b.w
    -28,   // b...b.w
    -8,    // w...b.w
    -33,   // .b..b.w
    42,    // bb..b.w
    -14,   // wb..b.w
    21,    // .w..b.w
    -106,  // bw..b.w
    -14,   // ww..b.w
    -33,   // ..b.b.w
    64,    // b.b.b.w
    -47,   // w.b.b.w
    22,    // .bb.b.w
    -16,   // bbb.b.w
    -11,   // wbb.b.w
    1,     // .wb.b.w
    -71,   // bwb.b.w
    6,     // wwb.b.w
    -32,   // ..w.b.w
    0,     // b.w.b.w
    -24,   // w.w.b.w
    17,    // .bw.b.w
    3,     // bbw.b.w
    -73,   // wbw.b.w
    53,    // .ww.b.w
    -80,   // bww.b.w
    -28,   // www.b.w
    37,    // ...bb.w
    36,    // b..bb.w
    43,    // w..bb.w
    97,    // .b.bb.w
    28,    // bb.bb.w
    -14,   // wb.bb.w
    10,    // .w.bb.w
    -59,   // bw.bb.w
    24,    // ww.bb.w
    -20,   // ..bbb.w
    -41,   // b.bbb.w
    73,    // w.bbb.w
    77,    // .bbbb.w
    48,    // bbbbb.w
    5,     // wbbbb.w
    -108,  // .wbbb.w
    -28,   // bwbbb.w
    -3,    // wwbbb.w
    -34,   // ..wbb.w
    -12,   // b.wbb.w
    -21,   // w.wbb.w
    -28,   // .bwbb.w
    58,    // bbwbb.w
    -29,   // wbwbb.w
    38,    // .wwbb.w
    -66,   // bwwbb.w
    -65,   // wwwbb.w
    -80,   // ...wb.w
    34,    // b..wb.w
    2,     // w..wb.w
    27,    // .b.wb.w
    -7,    // bb.wb.w
    -52,   // wb.wb.w
    54,    // .w.wb.w
    -17,   // bw.wb.w
    -3,    // ww.wb.w
    -6,    // ..bwb.w
    7,     // b.bwb.w
    38,    // w.bwb.w
    -34,   // .bbwb.w
    87,    // bbbwb.w
    -38,   // wbbwb.w
    40,    // .wbwb.w
    66,    // bwbwb.w
    -10,   // wwbwb.w
    22,    // ..wwb.w
    12,    // b.wwb.w
    -7,    // w.wwb.w
    -39,   // .bwwb.w
    55,    // bbwwb.w
    -17,   // wbwwb.w
    -1,    // .wwwb.w
    0,     // bwwwb.w
    -60,   // wwwwb.w
    -65,   // ....w.w
    58,    // b...w.w
    -64,   // w...w.w
    -20,   // .b..w.w
    -3,    // bb..w.w
    -49,   // wb..w.w
    -25,   // .w..w.w
    -90,   // bw..w.w
    77,    // ww..w.w
    -36,   // ..b.w.w
    0,     // b.b.w.w
    -24,   // w.b.w.w
    15,    // .bb.w.w
    21,    // bbb.w.w
    -65,   // wbb.w.w
    34,    // .wb.w.w
    -13,   // bwb.w.w
    -19,   // wwb.w.w
    -24,   // ..w.w.w
    -64,   // b.w.w.w
    -20,   // w.w.w.w
    72,    // .bw.w.w
    57,    // bbw.w.w
    46,    // wbw.w.w
    17,    // .ww.w.w
    -2,    // bww.w.w
    -46,   // www.w.w
    -53,   // ...bw.w
    10,    // b..bw.w
    -21,   // w..bw.w
    -55,   // .b.bw.w
    -42,   // bb.bw.w
    24,    // wb.bw.w
    -31,   // .w.bw.w
    -48,   // bw.bw.w
    -25,   // ww.bw.w
    -45,   // ..bbw.w
    88,    // b.bbw.w
    -21,   // w.bbw.w
    -13,   // .bbbw.w
    -17,   // bbbbw.w
    -22,   // wbbbw.w
    43,    // .wbbw.w
    -20,   // bwbbw.w
    9,     // wwbbw.w
    -30,   // ..wbw.w
    -7,    // b.wbw.w
    -33,   // w.wbw.w
    11,    // .bwbw.w
    -73,   // bbwbw.w
    -35,   // wbwbw.w
    120,   // .wwbw.w
    57,    // bwwbw.w
    51,    // wwwbw.w
    -66,   // ...ww.w
    46,    // b..ww.w
    67,    // w..ww.w
    -59,   // .b.ww.w
    56,    // bb.ww.w
    -29,   // wb.ww.w
    27,    // .w.ww.w
    71,    // bw.ww.w
    50,    // ww.ww.w
    113,   // ..bww.w
    -88,   // b.bww.w
    -7,    // w.bww.w
    19,    // .bbww.w
    -88,   // bbbww.w
    78,    // wbbww.w
    15,    // .wbww.w
    -19,   // bwbww.w
    17,    // wwbww.w
    -102,  // ..www.w
    41,    // b.www.w
    -56,   // w.www.w
    -131,  // .bwww.w
    -17,   // bbwww.w
    35,    // wbwww.w
    -46,   // .wwww.w
    -16,   // bwwww.w
    57,    // wwwww.w
    -12,   // .....bw
    9,     // b....bw
    -55,   // w....bw
    -4,    // .b...bw
    -34,   // bb...bw
    102,   // wb...bw
    -3,    // .w...bw
    0,     // bw...bw
    -18,   // ww...bw
    33,    // ..b..bw
    90,    // b.b..bw
    -14,   // w.b..bw
    -25,   // .bb..bw
    42,    // bbb..bw
    43,    // wbb..bw
    19,    // .wb..bw
    -29,   // bwb..bw
    -55,   // wwb..bw
    -9,    // ..w..bw
    106,   // b.w..bw
    -49,   // w.w..bw
    -72,   // .bw..bw
    39,    // bbw..bw
    43,    // wbw..bw
    -17,   // .ww..bw
    61,    // bww..bw
    8,     // www..bw
    -40,   // ...b.bw
    -59,   // b..b.bw
    48,    // w..b.bw
    -8,    // .b.b.bw
    50,    // bb.b.bw
    1,     // wb.b.bw
    -71,   // .w.b.bw
    13,    // bw.b.bw
    -30,   // ww.b.bw
    8,     // ..bb.bw
    -71,   // b.bb.bw
    -14,   // w.bb.bw
    104,   // .bbb.bw
    49,    // bbbb.bw
    68,    // wbbb.bw
    -32,   // .wbb.bw
    -43,   // bwbb.bw
    -84,   // wwbb.bw
    -8,    // ..wb.bw
    17,    // b.wb.bw
    24,    // w.wb.bw
    -71,   // .bwb.bw
    16,    // bbwb.bw
    -31,   // wbwb.bw
    34,    // .wwb.bw
    30,    // bwwb.bw
    -21,   // wwwb.bw
    -35,   // ...w.bw
    -62,   // b..w.bw
    50,    // w..w.bw
    -33,   // .b.w.bw
    9,     // bb.w.bw
    82,    // wb.w.bw
    0,     // .w.w.bw
    -13,   // bw.w.bw
    44,    // ww.w.bw
    -8,    // ..bw.bw
    48,    // b.bw.bw
    -52,   // w.bw.bw
    52,    // .bbw.bw
    29,    // bbbw.bw
    -126,  // wbbw.bw
    33,    // .wbw.bw
    48,    // bwbw.bw
    55,    // wwbw.bw
    -6,    // ..ww.bw
    59,    // b.ww.bw
    -29,   // w.ww.bw
    -19,   // .bww.bw
    -4,    // bbww.bw
    37,    // wbww.bw
    -95,   // .www.bw
    8,     // bwww.bw
    -72,   // wwww.bw
    -88,   // ....bbw
    -73,   // b...bbw
    47,    // w...bbw
    116,   // .b..bbw
    -14,   // bb..bbw
    43,    // wb..bbw
    -2,    // .w..bbw
    -61,   // bw..bbw
    -14,   // ww..bbw
    -62,   // ..b.bbw
    2,     // b.b.bbw
    -11,   // w.b.bbw
    -48,   // .bb.bbw
    17,    // bbb.bbw
    57,    // wbb.bbw
    76,    // .wb.bbw
    31,    // bwb.bbw
    12,    // wwb.bbw
    -11,   // ..w.bbw
    80,    // b.w.bbw
    -65,   // w.w.bbw
    29,    // .bw.bbw
    -11,   // bbw.bbw
    -46,   // wbw.bbw
    -58,   // .ww.bbw
    0,     // bww.bbw
    28,    // www.bbw
    -100,  // ...bbbw
    -99,   // b..bbbw
    -18,   // w..bbbw
    118,   // .b.bbbw
    5,     // bb.bbbw
    68,    // wb.bbbw
    -45,   // .w.bbbw
    -8,    // bw.bbbw
    0,     // ww.bbbw
    51,    // ..bbbbw
    16,    // b.bbbbw
    5,     // w.bbbbw
    -39,   // .bbbbbw
    -27,   // bbbbbbw
    -31,   // wbbbbbw
    -114,  // .wbbbbw
    -101,  // bwbbbbw
    19,    // wwbbbbw
    7,     // ..wbbbw
    0,     // b.wbbbw
    -22,   // w.wbbbw
    -12,   // .bwbbbw
    13,    // bbwbbbw
    3,     // wbwbbbw
    -55,   // .wwbbbw
    15,    // bwwbbbw
    -33,   // wwwbbbw
    -13,   // ...wbbw
    -16,   // b..wbbw
    12,    // w..wbbw
    -78,   // .b.wbbw
    42,    // bb.wbbw
    -126,  // wb.wbbw
    -35,   // .w.wbbw
    -30,   // bw.wbbw
    -3,    // ww.wbbw
    73,    // ..bwbbw
    -57,   // b.bwbbw
    -38,   // w.bwbbw
    -65,   // .bbwbbw
    -164,  // bbbwbbw
    -12,   // wbbwbbw
    -113,  // .wbwbbw
    -7,    // bwbwbbw
    5,     // wwbwbbw
    125,   // ..wwbbw
    66,    // b.wwbbw
    78,    // w.wwbbw
    -78,   // .bwwbbw
    25,    // bbwwbbw
    4,     // wbwwbbw
    -49,   // .wwwbbw
    -15,   // bwwwbbw
    21,    // wwwwbbw
    -36,   // ....wbw
    -7,    // b...wbw
    11,    // w...wbw
    -42,   // .b..wbw
    12,    // bb..wbw
    43,    // wb..wbw
    20,    // .w..wbw
    29,    // bw..wbw
    87,    // ww..wbw
    -33,   // ..b.wbw
    13,    // b.b.wbw
    -73,   // w.b.wbw
    -80,   // .bb.wbw
    -55,   // bbb.wbw
    -46,   // wbb.wbw
    2,     // .wb.wbw
    0,     // bwb.wbw
    -32,   // wwb.wbw
    53,    // ..w.wbw
    71,    // b.w.wbw
    46,    // w.w.wbw
    -3,    // .bw.wbw
    -67,   // bbw.wbw
    3,     // wbw.wbw
    34,    // .ww.wbw
    -31,   // bww.wbw
    42,    // www.wbw
    -14,   // ...bwbw
    -39,   // b..bwbw
    73,    // w..bwbw
    17,    // .b.bwbw
    0,     // bb.bwbw
    -31,   // wb.bwbw
    -33,   // .w.bwbw
    -48,   // bw.bwbw
    -60,   // ww.bwbw
    43,    // ..bbwbw
    19,    // b.bbwbw
    -29,   // w.bbwbw
    50,    // .bbbwbw
    64,    // bbbbwbw
    3,     // wbbbwbw
    51,    // .wbbwbw
    95,    // bwbbwbw
    16,    // wwbbwbw
    9,     // ..wbwbw
    -66,   // b.wbwbw
    -35,   // w.wbwbw
    -27,   // .bwbwbw
    130,   // bbwbwbw
    65,    // wbwbwbw
    57,    // .wwbwbw
    7,     // bwwbwbw
    -19,   // wwwbwbw
    -2,    // ...wwbw
    34,    // b..wwbw
    -133,  // w..wwbw
    103,   // .b.wwbw
    -21,   // bb.wwbw
    37,    // wb.wwbw
    0,     // .w.wwbw
    43,    // bw.wwbw
    14,    // ww.wwbw
    -18,   // ..bwwbw
    20,    // b.bwwbw
    -17,   // w.bwwbw
    3,     // .bbwwbw
    -46,   // bbbwwbw
    4,     // wbbwwbw
    48,    // .wbwwbw
    -95,   // bwbwwbw
    -17,   // wwbwwbw
    48,    // ..wwwbw
    28,    // b.wwwbw
    35,    // w.wwwbw
    -68,   // .bwwwbw
    -21,   // bbwwwbw
    -55,   // wbwwwbw
    16,    // .wwwwbw
    101,   // bwwwwbw
    16,    // wwwwwbw
    -14,   // .....ww
    20,    // b....ww
    22,    // w....ww
    -13,   // .b...ww
    0,     // bb...ww
    -18,   // wb...ww
    -2,    // .w...ww
    34,    // bw...ww
    22,    // ww...ww
    38,    // ..b..ww
    3,     // b.b..ww
    -14,   // w.b..ww
    -83,   // .bb..ww
    -18,   // bbb..ww
    -14,   // wbb..ww
    -43,   // .wb..ww
    -12,   // bwb..ww
    -19,   // wwb..ww
    -24,   // ..w..ww
    -42,   // b.w..ww
    77,    // w.w..ww
    -37,   // .bw..ww
    -16,   // bbw..ww
    87,    // wbw..ww
    -12,   // .ww..ww
    14,    // bww..ww
    -60,   // www..ww
    -24,   // ...b.ww
    117,   // b..b.ww
    0,     // w..b.ww
    -18,   // .b.b.ww
    -3,    // bb.b.ww
    -30,   // wb.b.ww
    45,    // .w.b.ww
    -9,    // bw.b.ww
    -84,   // ww.b.ww
    -25,   // ..bb.ww
    -56,   // b.bb.ww
    24,    // w.bb.ww
    4,     // .bbb.ww
    46,    // bbbb.ww
    0,     // wbbb.ww
    68,    // .wbb.ww
    21,    // bwbb.ww
    51,    // wwbb.ww
    63,    // ..wb.ww
    7,     // b.wb.ww
    -25,   // w.wb.ww
    -20,   // .bwb.ww
    -123,  // bbwb.ww
    -60,   // wbwb.ww
    -54,   // .wwb.ww
    -42,   // bwwb.ww
    -64,   // wwwb.ww
    -148,  // ...w.ww
    25,    // b..w.ww
    -30,   // w..w.ww
    -119,  // .b.w.ww
    3,     // bb.w.ww
    44,    // wb.w.ww
    50,    // .w.w.ww
    -50,   // bw.w.ww
    -25,   // ww.w.ww
    8,     // ..bw.ww
    42,    // b.bw.ww
    -3,    // w.bw.ww
    -69,   // .bbw.ww
    -27,   // bbbw.ww
    -3,    // wbbw.ww
    -31,   // .wbw.ww
    0,     // bwbw.ww
    -25,   // wwbw.ww
    -40,   // ..ww.ww
    -28,   // b.ww.ww
    50,    // w.ww.ww
    -69,   // .bww.ww
    84,    // bbww.ww
    14,    // wbww.ww
    31,    // .www.ww
    -5,    // bwww.ww
    53,    // wwww.ww
    46,    // ....bww
    8,     // b...bww
    -7,    // w...bww
    55,    // .b..bww
    16,    // bb..bww
    -55,   // wb..bww
    8,     // .w..bww
    -39,   // bw..bww
    -19,   // ww..bww
    -14,   // ..b.bww
    -57,   // b.b.bww
    6,     // w.b.bww
    -38,   // .bb.bww
    -63,   // bbb.bww
    12,    // wbb.bww
    -3,    // .wb.bww
    67,    // bwb.bww
    100,   // wwb.bww
    23,    // ..w.bww
    -3,    // b.w.bww
    -19,   // w.w.bww
    3,     // .bw.bww
    0,     // bbw.bww
    -32,   // wbw.bww
    4,     // .ww.bww
    11,    // bww.bww
    -59,   // www.bww
    22,    // ...bbww
    -68,   // b..bbww
    42,    // w..bbww
    -26,   // .b.bbww
    -84,   // bb.bbww
    -84,   // wb.bbww
    6,     // .w.bbww
    4,     // bw.bbww
    51,    // ww.bbww
    -50,   // ..bbbww
    17,    // b.bbbww
    -3,    // w.bbbww
    -35,   // .bbbbww
    67,    // bbbbbww
    19,    // wbbbbww
    -30,   // .wbbbww
    21,    // bwbbbww
    -2,    // wwbbbww
    -49,   // ..wbbww
    -55,   // b.wbbww
    9,     // w.wbbww
    83,    // .bwbbww
    62,    // bbwbbww
    16,    // wbwbbww
    102,   // .wwbbww
    -25,   // bwwbbww
    -19,   // wwwbbww
    52,    // ...wbww
    -5,    // b..wbww
    43,    // w..wbww
    17,    // .b.wbww
    123,   // bb.wbww
    55,    // wb.wbww
    -26,   // .w.wbww
    -16,   // bw.wbww
    -25,   // ww.wbww
    -30,   // ..bwbww
    73,    // b.bwbww
    -10,   // w.bwbww
    118,   // .bbwbww
    -18,   // bbbwbww
    5,     // wbbwbww
    -7,    // .wbwbww
    -130,  // bwbwbww
    35,    // wwbwbww
    26,    // ..wwbww
    -58,   // b.wwbww
    17,    // w.wwbww
    -15,   // .bwwbww
    -62,   // bbwwbww
    -17,   // wbwwbww
    110,   // .wwwbww
    -13,   // bwwwbww
    24,    // wwwwbww
    -166,  // ....www
    -52,   // b...www
    27,    // w...www
    -53,   // .b..www
    18,    // bb..www
    8,     // wb..www
    -13,   // .w..www
    -42,   // bw..www
    -60,   // ww..www
    -78,   // ..b.www
    -21,   // b.b.www
    -28,   // w.b.www
    -55,   // .bb.www
    0,     // bbb.www
    28,    // wbb.www
    -35,   // .wb.www
    55,    // bwb.www
    -59,   // wwb.www
    -141,  // ..w.www
    16,    // b.w.www
    -46,   // w.w.www
    -3,    // .bw.www
    63,    // bbw.www
    42,    // wbw.www
    -14,   // .ww.www
    -17,   // bww.www
    -35,   // www.www
    -55,   // ...bwww
    6,     // b..bwww
    -52,   // w..bwww
    72,    // .b.bwww
    27,    // bb.bwww
    -21,   // wb.bwww
    83,    // .w.bwww
    -29,   // bw.bwww
    -64,   // ww.bwww
    -73,   // ..bbwww
    88,    // b.bbwww
    -65,   // w.bbwww
    -17,   // .bbbwww
    -89,   // bbbbwww
    -33,   // wbbbwww
    23,    // .wbbwww
    46,    // bwbbwww
    -19,   // wwbbwww
    145,   // ..wbwww
    -87,   // b.wbwww
    51,    // w.wbwww
    -2,    // .bwbwww
    18,    // bbwbwww
    -19,   // wbwbwww
    21,    // .wwbwww
    164,   // bwwbwww
    -47,   // wwwbwww
    -308,  // ...wwww
    -74,   // b..wwww
    -22,   // w..wwww
    -260,  // .b.wwww
    -46,   // bb.wwww
    -72,   // wb.wwww
    74,    // .w.wwww
    -49,   // bw.wwww
    53,    // ww.wwww
    -46,   // ..bwwww
    17,    // b.bwwww
    -60,   // w.bwwww
    -17,   // .bbwwww
    89,    // bbbwwww
    21,    // wbbwwww
    79,    // .wbwwww
    -64,   // bwbwwww
    24,    // wwbwwww
    -46,   // ..wwwww
    -48,   // b.wwwww
    57,    // w.wwwww
    -108,  // .bwwwww
    -67,   // bbwwwww
    16,    // wbwwwww
    14,    // .wwwwww
    27,    // bwwwwww
    36,    // wwwwwww
    0,     // captures=0 threats=0
    62,    // captures=0 threats=1
    66,    // captures=0 threats=2
    69,    // captures=0 threats=3
    70,    // captures=0 threats=4
    134,   // captures=0 additional threats
    60,    // captures=1 threats=0
    162,   // captures=1 threats=1
    196,   // captures=1 threats=2
    199,   // captures=1 threats=3
    208,   // captures=1 threats=4
    5,     // captures=1 additional threats
    66,    // captures=2 threats=0
    168,   // captures=2 threats=1
    207,   // captures=2 threats=2
    209,   // captures=2 threats=3
    221,   // captures=2 threats=4
    67,    // captures=2 additional threats
    66,    // captures=3 threats=0
    293,   // captures=3 threats=1
    646,   // captures=3 threats=2
    804,   // captures=3 threats=3
    842,   // captures=3 threats=4
    117,   // captures=3 additional threats
    300,   // captures=4 threats=0
    1467,  // captures=4 threats=1
    1557,  // captures=4 threats=2
    1730,  // captures=4 threats=3
    1754,  // captures=4 threats=4
    35,    // captures=4 additional threats
].into_boxed_slice()
