vec![
    0,     // .......
    16,    // b......
    -16,   // w......
    -12,   // .b.....
    41,    // bb.....
    -20,   // wb.....
    12,    // .w.....
    20,    // bw.....
    -41,   // ww.....
    28,    // ..b....
    80,    // b.b....
    -27,   // w.b....
    15,    // .bb....
    71,    // bbb....
    -106,  // wbb....
    -18,   // .wb....
    57,    // bwb....
    71,    // wwb....
    -28,   // ..w....
    27,    // b.w....
    -80,   // w.w....
    18,    // .bw....
    -71,   // bbw....
    -57,   // wbw....
    -15,   // .ww....
    106,   // bww....
    -71,   // www....
    -23,   // ...b...
    -14,   // b..b...
    -8,    // w..b...
    -2,    // .b.b...
    126,   // bb.b...
    -69,   // wb.b...
    4,     // .w.b...
    -29,   // bw.b...
    -50,   // ww.b...
    -4,    // ..bb...
    95,    // b.bb...
    -19,   // w.bb...
    201,   // .bbb...
    670,   // bbbb...
    -97,   // wbbb...
    39,    // .wbb...
    -17,   // bwbb...
    5,     // wwbb...
    -3,    // ..wb...
    65,    // b.wb...
    -81,   // w.wb...
    -24,   // .bwb...
    -86,   // bbwb...
    -4,    // wbwb...
    -5,    // .wwb...
    33,    // bwwb...
    -115,  // wwwb...
    23,    // ...w...
    8,     // b..w...
    14,    // w..w...
    -4,    // .b.w...
    50,    // bb.w...
    29,    // wb.w...
    2,     // .w.w...
    69,    // bw.w...
    -126,  // ww.w...
    3,     // ..bw...
    81,    // b.bw...
    -65,   // w.bw...
    5,     // .bbw...
    115,   // bbbw...
    -33,   // wbbw...
    24,    // .wbw...
    4,     // bwbw...
    86,    // wwbw...
    4,     // ..ww...
    19,    // b.ww...
    -95,   // w.ww...
    -39,   // .bww...
    -5,    // bbww...
    17,    // wbww...
    -201,  // .www...
    97,    // bwww...
    -670,  // wwww...
    28,    // ....b..
    32,    // b...b..
    -79,   // w...b..
    31,    // .b..b..
    -53,   // bb..b..
    20,    // wb..b..
    4,     // .w..b..
    -53,   // bw..b..
    28,    // ww..b..
    -10,   // ..b.b..
    -30,   // b.b.b..
    -26,   // w.b.b..
    -6,    // .bb.b..
    171,   // bbb.b..
    -152,  // wbb.b..
    -17,   // .wb.b..
    -66,   // bwb.b..
    -32,   // wwb.b..
    0,     // ..w.b..
    -19,   // b.w.b..
    -66,   // w.w.b..
    -34,   // .bw.b..
    -45,   // bbw.b..
    -69,   // wbw.b..
    8,     // .ww.b..
    -39,   // bww.b..
    -40,   // www.b..
    -4,    // ...bb..
    34,    // b..bb..
    -41,   // w..bb..
    13,    // .b.bb..
    46,    // bb.bb..
    -9,    // wb.bb..
    -55,   // .w.bb..
    -9,    // bw.bb..
    -47,   // ww.bb..
    31,    // ..bbb..
    100,   // b.bbb..
    -7,    // w.bbb..
    311,   // .bbbb..
    81,    // bbbbb..
    15,    // wbbbb..
    -54,   // .wbbb..
    -55,   // bwbbb..
    11,    // wwbbb..
    -99,   // ..wbb..
    -56,   // b.wbb..
    -32,   // w.wbb..
    -52,   // .bwbb..
    -12,   // bbwbb..
    89,    // wbwbb..
    61,    // .wwbb..
    -113,  // bwwbb..
    -95,   // wwwbb..
    3,     // ...wb..
    102,   // b..wb..
    58,    // w..wb..
    11,    // .b.wb..
    -35,   // bb.wb..
    15,    // wb.wb..
    16,    // .w.wb..
    37,    // bw.wb..
    18,    // ww.wb..
    11,    // ..bwb..
    7,     // b.bwb..
    -16,   // w.bwb..
    -52,   // .bbwb..
    -166,  // bbbwb..
    13,    // wbbwb..
    -3,    // .wbwb..
    -45,   // bwbwb..
    26,    // wwbwb..
    99,    // ..wwb..
    63,    // b.wwb..
    78,    // w.wwb..
    100,   // .bwwb..
    -13,   // bbwwb..
    -8,    // wbwwb..
    -104,  // .wwwb..
    39,    // bwwwb..
    -110,  // wwwwb..
    -28,   // ....w..
    79,    // b...w..
    -32,   // w...w..
    -4,    // .b..w..
    -28,   // bb..w..
    53,    // wb..w..
    -31,   // .w..w..
    -20,   // bw..w..
    53,    // ww..w..
    0,     // ..b.w..
    66,    // b.b.w..
    19,    // w.b.w..
    -8,    // .bb.w..
    40,    // bbb.w..
    39,    // wbb.w..
    34,    // .wb.w..
    69,    // bwb.w..
    45,    // wwb.w..
    10,    // ..w.w..
    26,    // b.w.w..
    30,    // w.w.w..
    17,    // .bw.w..
    32,    // bbw.w..
    66,    // wbw.w..
    6,     // .ww.w..
    152,   // bww.w..
    -171,  // www.w..
    -3,    // ...bw..
    -58,   // b..bw..
    -102,  // w..bw..
    -16,   // .b.bw..
    -18,   // bb.bw..
    -37,   // wb.bw..
    -11,   // .w.bw..
    -15,   // bw.bw..
    35,    // ww.bw..
    -99,   // ..bbw..
    -78,   // b.bbw..
    -63,   // w.bbw..
    104,   // .bbbw..
    110,   // bbbbw..
    -39,   // wbbbw..
    -100,  // .wbbw..
    8,     // bwbbw..
    13,    // wwbbw..
    -11,   // ..wbw..
    16,    // b.wbw..
    -7,    // w.wbw..
    3,     // .bwbw..
    -26,   // bbwbw..
    45,    // wbwbw..
    52,    // .wwbw..
    -13,   // bwwbw..
    166,   // wwwbw..
    4,     // ...ww..
    41,    // b..ww..
    -34,   // w..ww..
    55,    // .b.ww..
    47,    // bb.ww..
    9,     // wb.ww..
    -13,   // .w.ww..
    9,     // bw.ww..
    -46,   // ww.ww..
    99,    // ..bww..
    32,    // b.bww..
    56,    // w.bww..
    -61,   // .bbww..
    95,    // bbbww..
    113,   // wbbww..
    52,    // .wbww..
    -89,   // bwbww..
    12,    // wwbww..
    -31,   // ..www..
    7,     // b.www..
    -100,  // w.www..
    54,    // .bwww..
    -11,   // bbwww..
    55,    // wbwww..
    -311,  // .wwww..
    -15,   // bwwww..
    -81,   // wwwww..
    -12,   // .....b.
    -38,   // b....b.
    -79,   // w....b.
    -47,   // .b...b.
    -45,   // bb...b.
    27,    // wb...b.
    0,     // .w...b.
    -62,   // bw...b.
    17,    // ww...b.
    31,    // ..b..b.
    56,    // b.b..b.
    -64,   // w.b..b.
    46,    // .bb..b.
    22,    // bbb..b.
    99,    // wbb..b.
    19,    // .wb..b.
    -66,   // bwb..b.
    26,    // wwb..b.
    -4,    // ..w..b.
    -24,   // b.w..b.
    -31,   // w.w..b.
    27,    // .bw..b.
    -19,   // bbw..b.
    -37,   // wbw..b.
    -23,   // .ww..b.
    8,     // bww..b.
    -92,   // www..b.
    -2,    // ...b.b.
    -43,   // b..b.b.
    -26,   // w..b.b.
    -7,    // .b.b.b.
    -83,   // bb.b.b.
    11,    // wb.b.b.
    -15,   // .w.b.b.
    0,     // bw.b.b.
    -27,   // ww.b.b.
    13,    // ..bb.b.
    29,    // b.bb.b.
    109,   // w.bb.b.
    66,    // .bbb.b.
    -67,   // bbbb.b.
    98,    // wbbb.b.
    -31,   // .wbb.b.
    -42,   // bwbb.b.
    -1,    // wwbb.b.
    -16,   // ..wb.b.
    -10,   // b.wb.b.
    -25,   // w.wb.b.
    37,    // .bwb.b.
    32,    // bbwb.b.
    30,    // wbwb.b.
    83,    // .wwb.b.
    -75,   // bwwb.b.
    42,    // wwwb.b.
    -4,    // ...w.b.
    -78,   // b..w.b.
    -3,    // w..w.b.
    34,    // .b.w.b.
    -48,   // bb.w.b.
    -85,   // wb.w.b.
    15,    // .w.w.b.
    119,   // bw.w.b.
    -138,  // ww.w.b.
    11,    // ..bw.b.
    48,    // b.bw.b.
    49,    // w.bw.b.
    2,     // .bbw.b.
    -112,  // bbbw.b.
    -93,   // wbbw.b.
    37,    // .wbw.b.
    10,    // bwbw.b.
    49,    // wwbw.b.
    55,    // ..ww.b.
    4,     // b.ww.b.
    27,    // w.ww.b.
    54,    // .bww.b.
    -4,    // bbww.b.
    145,   // wbww.b.
    -105,  // .www.b.
    38,    // bwww.b.
    -256,  // wwww.b.
    15,    // ....bb.
    -4,    // b...bb.
    26,    // w...bb.
    46,    // .b..bb.
    7,     // bb..bb.
    14,    // wb..bb.
    23,    // .w..bb.
    -5,    // bw..bb.
    -91,   // ww..bb.
    -6,    // ..b.bb.
    29,    // b.b.bb.
    9,     // w.b.bb.
    38,    // .bb.bb.
    -18,   // bbb.bb.
    -6,    // wbb.bb.
    -91,   // .wb.bb.
    25,    // bwb.bb.
    -24,   // wwb.bb.
    -8,    // ..w.bb.
    -4,    // b.w.bb.
    40,    // w.w.bb.
    -102,  // .bw.bb.
    55,    // bbw.bb.
    -131,  // wbw.bb.
    0,     // .ww.bb.
    83,    // bww.bb.
    -97,   // www.bb.
    201,   // ...bbb.
    -53,   // b..bbb.
    93,    // w..bbb.
    66,    // .b.bbb.
    11,    // bb.bbb.
    58,    // wb.bbb.
    105,   // .w.bbb.
    57,    // bw.bbb.
    -6,    // ww.bbb.
    311,   // ..bbbb.
    129,   // b.bbbb.
    87,    // w.bbbb.
    -66,   // .bbbbb.
    -81,   // bbbbbb.
    -2,    // wbbbbb.
    52,    // .wbbbb.
    -71,   // bwbbbb.
    -9,    // wwbbbb.
    104,   // ..wbbb.
    7,     // b.wbbb.
    -86,   // w.wbbb.
    74,    // .bwbbb.
    -109,  // bbwbbb.
    94,    // wbwbbb.
    33,    // .wwbbb.
    21,    // bwwbbb.
    -39,   // wwwbbb.
    5,     // ...wbb.
    61,    // b..wbb.
    34,    // w..wbb.
    2,     // .b.wbb.
    68,    // bb.wbb.
    4,     // wb.wbb.
    -83,   // .w.wbb.
    -29,   // bw.wbb.
    -40,   // ww.wbb.
    -52,   // ..bwbb.
    -91,   // b.bwbb.
    -97,   // w.bwbb.
    -51,   // .bbwbb.
    -70,   // bbbwbb.
    -85,   // wbbwbb.
    28,    // .wbwbb.
    -42,   // bwbwbb.
    131,   // wwbwbb.
    -61,   // ..wwbb.
    -12,   // b.wwbb.
    -29,   // w.wwbb.
    -39,   // .bwwbb.
    -58,   // bbwwbb.
    -37,   // wbwwbb.
    -33,   // .wwwbb.
    99,    // bwwwbb.
    56,    // wwwwbb.
    18,    // ....wb.
    7,     // b...wb.
    91,    // w...wb.
    27,    // .b..wb.
    -9,    // bb..wb.
    -88,   // wb..wb.
    -19,   // .w..wb.
    -98,   // bw..wb.
    -125,  // ww..wb.
    -34,   // ..b.wb.
    -44,   // b.b.wb.
    -32,   // w.b.wb.
    -102,  // .bb.wb.
    -14,   // bbb.wb.
    -58,   // wbb.wb.
    0,     // .wb.wb.
    46,    // bwb.wb.
    9,     // wwb.wb.
    17,    // ..w.wb.
    -40,   // b.w.wb.
    99,    // w.w.wb.
    58,    // .bw.wb.
    -13,   // bbw.wb.
    0,     // wbw.wb.
    91,    // .ww.wb.
    -51,   // bww.wb.
    4,     // www.wb.
    -24,   // ...bwb.
    46,    // b..bwb.
    58,    // w..bwb.
    37,    // .b.bwb.
    -21,   // bb.bwb.
    -32,   // wb.bwb.
    -37,   // .w.bwb.
    -25,   // bw.bwb.
    -32,   // ww.bwb.
    -52,   // ..bbwb.
    -55,   // b.bbwb.
    -20,   // w.bbwb.
    74,    // .bbbwb.
    -111,  // bbbbwb.
    -14,   // wbbbwb.
    21,    // .wbbwb.
    -106,  // bwbbwb.
    72,    // wwbbwb.
    3,     // ..wbwb.
    -38,   // b.wbwb.
    12,    // w.wbwb.
    -11,   // .bwbwb.
    -6,    // bbwbwb.
    -67,   // wbwbwb.
    -28,   // .wwbwb.
    100,   // bwwbwb.
    35,    // wwwbwb.
    -39,   // ...wwb.
    30,    // b..wwb.
    10,    // w..wwb.
    54,    // .b.wwb.
    -20,   // bb.wwb.
    36,    // wb.wwb.
    31,    // .w.wwb.
    77,    // bw.wwb.
    -102,  // ww.wwb.
    100,   // ..bwwb.
    -77,   // b.bwwb.
    -22,   // w.bwwb.
    -39,   // .bbwwb.
    11,    // bbbwwb.
    -95,   // wbbwwb.
    -21,   // .wbwwb.
    -122,  // bwbwwb.
    -14,   // wwbwwb.
    54,    // ..wwwb.
    147,   // b.wwwb.
    -214,  // w.wwwb.
    -32,   // .bwwwb.
    89,    // bbwwwb.
    -7,    // wbwwwb.
    -52,   // .wwwwb.
    201,   // bwwwwb.
    -289,  // wwwwwb.
    12,    // .....w.
    79,    // b....w.
    38,    // w....w.
    0,     // .b...w.
    -17,   // bb...w.
    62,    // wb...w.
    47,    // .w...w.
    -27,   // bw...w.
    45,    // ww...w.
    4,     // ..b..w.
    31,    // b.b..w.
    24,    // w.b..w.
    23,    // .bb..w.
    92,    // bbb..w.
    -8,    // wbb..w.
    -27,   // .wb..w.
    37,    // bwb..w.
    19,    // wwb..w.
    -31,   // ..w..w.
    64,    // b.w..w.
    -56,   // w.w..w.
    -19,   // .bw..w.
    -26,   // bbw..w.
    66,    // wbw..w.
    -46,   // .ww..w.
    -99,   // bww..w.
    -22,   // www..w.
    4,     // ...b.w.
    3,     // b..b.w.
    78,    // w..b.w.
    -15,   // .b.b.w.
    138,   // bb.b.w.
    -119,  // wb.b.w.
    -34,   // .w.b.w.
    85,    // bw.b.w.
    48,    // ww.b.w.
    -55,   // ..bb.w.
    -27,   // b.bb.w.
    -4,    // w.bb.w.
    105,   // .bbb.w.
    256,   // bbbb.w.
    -38,   // wbbb.w.
    -54,   // .wbb.w.
    -145,  // bwbb.w.
    4,     // wwbb.w.
    -11,   // ..wb.w.
    -49,   // b.wb.w.
    -48,   // w.wb.w.
    -37,   // .bwb.w.
    -49,   // bbwb.w.
    -10,   // wbwb.w.
    -2,    // .wwb.w.
    93,    // bwwb.w.
    112,   // wwwb.w.
    2,     // ...w.w.
    26,    // b..w.w.
    43,    // w..w.w.
    15,    // .b.w.w.
    27,    // bb.w.w.
    0,     // wb.w.w.
    7,     // .w.w.w.
    -11,   // bw.w.w.
    83,    // ww.w.w.
    16,    // ..bw.w.
    25,    // b.bw.w.
    10,    // w.bw.w.
    -83,   // .bbw.w.
    -42,   // bbbw.w.
    75,    // wbbw.w.
    -37,   // .wbw.w.
    -30,   // bwbw.w.
    -32,   // wwbw.w.
    -13,   // ..ww.w.
    -109,  // b.ww.w.
    -29,   // w.ww.w.
    31,    // .bww.w.
    1,     // bbww.w.
    42,    // wbww.w.
    -66,   // .www.w.
    -98,   // bwww.w.
    67,    // wwww.w.
    -18,   // ....bw.
    -91,   // b...bw.
    -7,    // w...bw.
    19,    // .b..bw.
    125,   // bb..bw.
    98,    // wb..bw.
    -27,   // .w..bw.
    88,    // bw..bw.
    9,     // ww..bw.
    -17,   // ..b.bw.
    -99,   // b.b.bw.
    40,    // w.b.bw.
    -91,   // .bb.bw.
    -4,    // bbb.bw.
    51,    // wbb.bw.
    -58,   // .wb.bw.
    0,     // bwb.bw.
    13,    // wwb.bw.
    34,    // ..w.bw.
    32,    // b.w.bw.
    44,    // w.w.bw.
    0,     // .bw.bw.
    -9,    // bbw.bw.
    -46,   // wbw.bw.
    102,   // .ww.bw.
    58,    // bww.bw.
    14,    // www.bw.
    39,    // ...bbw.
    -10,   // b..bbw.
    -30,   // w..bbw.
    -31,   // .b.bbw.
    102,   // bb.bbw.
    -77,   // wb.bbw.
    -54,   // .w.bbw.
    -36,   // bw.bbw.
    20,    // ww.bbw.
    -54,   // ..bbbw.
    214,   // b.bbbw.
    -147,  // w.bbbw.
    52,    // .bbbbw.
    289,   // bbbbbw.
    -201,  // wbbbbw.
    32,    // .wbbbw.
    7,     // bwbbbw.
    -89,   // wwbbbw.
    -100,  // ..wbbw.
    22,    // b.wbbw.
    77,    // w.wbbw.
    21,    // .bwbbw.
    14,    // bbwbbw.
    122,   // wbwbbw.
    39,    // .wwbbw.
    95,    // bwwbbw.
    -11,   // wwwbbw.
    24,    // ...wbw.
    -58,   // b..wbw.
    -46,   // w..wbw.
    37,    // .b.wbw.
    32,    // bb.wbw.
    25,    // wb.wbw.
    -37,   // .w.wbw.
    32,    // bw.wbw.
    21,    // ww.wbw.
    -3,    // ..bwbw.
    -12,   // b.bwbw.
    38,    // w.bwbw.
    28,    // .bbwbw.
    -35,   // bbbwbw.
    -100,  // wbbwbw.
    11,    // .wbwbw.
    67,    // bwbwbw.
    6,     // wwbwbw.
    52,    // ..wwbw.
    20,    // b.wwbw.
    55,    // w.wwbw.
    -21,   // .bwwbw.
    -72,   // bbwwbw.
    106,   // wbwwbw.
    -74,   // .wwwbw.
    14,    // bwwwbw.
    111,   // wwwwbw.
    -15,   // ....ww.
    -26,   // b...ww.
    4,     // w...ww.
    -23,   // .b..ww.
    91,    // bb..ww.
    5,     // wb..ww.
    -46,   // .w..ww.
    -14,   // bw..ww.
    -7,    // ww..ww.
    8,     // ..b.ww.
    -40,   // b.b.ww.
    4,     // w.b.ww.
    0,     // .bb.ww.
    97,    // bbb.ww.
    -83,   // wbb.ww.
    102,   // .wb.ww.
    131,   // bwb.ww.
    -55,   // wwb.ww.
    6,     // ..w.ww.
    -9,    // b.w.ww.
    -29,   // w.w.ww.
    91,    // .bw.ww.
    24,    // bbw.ww.
    -25,   // wbw.ww.
    -38,   // .ww.ww.
    6,     // bww.ww.
    18,    // www.ww.
    -5,    // ...bww.
    -34,   // b..bww.
    -61,   // w..bww.
    83,    // .b.bww.
    40,    // bb.bww.
    29,    // wb.bww.
    -2,    // .w.bww.
    -4,    // bw.bww.
    -68,   // ww.bww.
    61,    // ..bbww.
    29,    // b.bbww.
    12,    // w.bbww.
    33,    // .bbbww.
    -56,   // bbbbww.
    -99,   // wbbbww.
    39,    // .wbbww.
    37,    // bwbbww.
    58,    // wwbbww.
    52,    // ..wbww.
    97,    // b.wbww.
    91,    // w.wbww.
    -28,   // .bwbww.
    -131,  // bbwbww.
    42,    // wbwbww.
    51,    // .wwbww.
    85,    // bwwbww.
    70,    // wwwbww.
    -201,  // ...www.
    -93,   // b..www.
    53,    // w..www.
    -105,  // .b.www.
    6,     // bb.www.
    -57,   // wb.www.
    -66,   // .w.www.
    -58,   // bw.www.
    -11,   // ww.www.
    -104,  // ..bwww.
    86,    // b.bwww.
    -7,    // w.bwww.
    -33,   // .bbwww.
    39,    // bbbwww.
    -21,   // wbbwww.
    -74,   // .wbwww.
    -94,   // bwbwww.
    109,   // wwbwww.
    -311,  // ..wwww.
    -87,   // b.wwww.
    -129,  // w.wwww.
    -52,   // .bwwww.
    9,     // bbwwww.
    71,    // wbwwww.
    66,    // .wwwww.
    2,     // bwwwww.
    81,    // wwwwww.
    16,    // ......b
    26,    // b.....b
    0,     // w.....b
    -38,   // .b....b
    -24,   // bb....b
    6,     // wb....b
    79,    // .w....b
    4,     // bw....b
    -36,   // ww....b
    32,    // ..b...b
    13,    // b.b...b
    -82,   // w.b...b
    -4,    // .bb...b
    -97,   // bbb...b
    -125,  // wbb...b
    -91,   // .wb...b
    20,    // bwb...b
    2,     // wwb...b
    79,    // ..w...b
    -8,    // b.w...b
    83,    // w.w...b
    7,     // .bw...b
    -42,   // bbw...b
    -40,   // wbw...b
    -26,   // .ww...b
    -31,   // bww...b
    -98,   // www...b
    -14,   // ...b..b
    -57,   // b..b..b
    30,    // w..b..b
    -43,   // .b.b..b
    -42,   // bb.b..b
    -98,   // wb.b..b
    3,     // .w.b..b
    -4,    // bw.b..b
    93,    // ww.b..b
    34,    // ..bb..b
    -46,   // b.bb..b
    -27,   // w.bb..b
    -53,   // .bbb..b
    14,    // bbbb..b
    -104,  // wbbb..b
    -10,   // .wbb..b
    108,   // bwbb..b
    -64,   // wwbb..b
    -58,   // ..wb..b
    -52,   // b.wb..b
    12,    // w.wb..b
    46,    // .bwb..b
    -94,   // bbwb..b
    -65,   // wbwb..b
    -34,   // .wwb..b
    -82,   // bwwb..b
    36,    // wwwb..b
    8,     // ...w..b
    -11,   // b..w..b
    -30,   // w..w..b
    -78,   // .b.w..b
    66,    // bb.w..b
    -19,   // wb.w..b
    26,    // .w.w..b
    -59,   // bw.w..b
    88,    // ww.w..b
    102,   // ..bw..b
    65,    // b.bw..b
    24,    // w.bw..b
    61,    // .bbw..b
    66,    // bbbw..b
    -64,   // wbbw..b
    -58,   // .wbw..b
    -38,   // bwbw..b
    -10,   // wwbw..b
    41,    // ..ww..b
    -5,    // b.ww..b
    46,    // w.ww..b
    30,    // .bww..b
    -52,   // bbww..b
    97,    // wbww..b
    -93,   // .www..b
    -23,   // bwww..b
    -66,   // wwww..b
    80,    // ....b.b
    13,    // b...b.b
    -83,   // w...b.b
    56,    // .b..b.b
    -94,   // bb..b.b
    123,   // wb..b.b
    31,    // .w..b.b
    23,    // bw..b.b
    30,    // ww..b.b
    -30,   // ..b.b.b
    32,    // b.b.b.b
    77,    // w.b.b.b
    29,    // .bb.b.b
    37,    // bbb.b.b
    14,    // wbb.b.b
    -99,   // .wb.b.b
    7,     // bwb.b.b
    -18,   // wwb.b.b
    66,    // ..w.b.b
    21,    // b.w.b.b
    0,     // w.w.b.b
    -44,   // .bw.b.b
    28,    // bbw.b.b
    22,    // wbw.b.b
    -40,   // .ww.b.b
    185,   // bww.b.b
    23,    // www.b.b
    95,    // ...bb.b
    -46,   // b..bb.b
    -46,   // w..bb.b
    29,    // .b.bb.b
    -30,   // bb.bb.b
    -73,   // wb.bb.b
    -27,   // .w.bb.b
    -30,   // bw.bb.b
    -4,    // ww.bb.b
    100,   // ..bbb.b
    51,    // b.bbb.b
    -42,   // w.bbb.b
    129,   // .bbbb.b
    -84,   // bbbbb.b
    -37,   // wbbbb.b
    214,   // .wbbb.b
    -73,   // bwbbb.b
    10,    // wwbbb.b
    -78,   // ..wbb.b
    10,    // b.wbb.b
    85,    // w.wbb.b
    -55,   // .bwbb.b
    -60,   // bbwbb.b
    33,    // wbwbb.b
    29,    // .wwbb.b
    -60,   // bwwbb.b
    74,    // wwwbb.b
    81,    // ...wb.b
    65,    // b..wb.b
    -12,   // w..wb.b
    48,    // .b.wb.b
    3,     // bb.wb.b
    4,     // wb.wb.b
    25,    // .w.wb.b
    17,    // bw.wb.b
    23,    // ww.wb.b
    7,     // ..bwb.b
    27,    // b.bwb.b
    -5,    // w.bwb.b
    -91,   // .bbwb.b
    -56,   // bbbwb.b
    8,     // wbbwb.b
    -12,   // .wbwb.b
    26,    // bwbwb.b
    111,   // wwbwb.b
    32,    // ..wwb.b
    -15,   // b.wwb.b
    -85,   // w.wwb.b
    -77,   // .bwwb.b
    -64,   // bbwwb.b
    37,    // wbwwb.b
    86,    // .wwwb.b
    -37,   // bwwwb.b
    14,    // wwwwb.b
    27,    // ....w.b
    -8,    // b...w.b
    82,    // w...w.b
    -24,   // .b..w.b
    -21,   // bb..w.b
    141,   // wb..w.b
    64,    // .w..w.b
    67,    // bw..w.b
    -21,   // ww..w.b
    -19,   // ..b.w.b
    21,    // b.b.w.b
    0,     // w.b.w.b
    -4,    // .bb.w.b
    -25,   // bbb.w.b
    -39,   // wbb.w.b
    32,    // .wb.w.b
    31,    // bwb.w.b
    -29,   // wwb.w.b
    26,    // ..w.w.b
    67,    // b.w.w.b
    -77,   // w.w.w.b
    -40,   // .bw.w.b
    -106,  // bbw.w.b
    53,    // wbw.w.b
    -9,    // .ww.w.b
    43,    // bww.w.b
    -9,    // www.w.b
    65,    // ...bw.b
    -52,   // b..bw.b
    -24,   // w..bw.b
    -10,   // .b.bw.b
    63,    // bb.bw.b
    -21,   // wb.bw.b
    -49,   // .w.bw.b
    43,    // bw.bw.b
    -32,   // ww.bw.b
    -56,   // ..bbw.b
    10,    // b.bbw.b
    45,    // w.bbw.b
    7,     // .bbbw.b
    101,   // bbbbw.b
    -27,   // wbbbw.b
    22,    // .wbbw.b
    102,   // bwbbw.b
    -3,    // wwbbw.b
    16,    // ..wbw.b
    -58,   // b.wbw.b
    5,     // w.wbw.b
    -38,   // .bwbw.b
    -6,    // bbwbw.b
    -47,   // wbwbw.b
    97,    // .wwbw.b
    75,    // bwwbw.b
    -44,   // wwwbw.b
    19,    // ...ww.b
    -5,    // b..ww.b
    27,    // w..ww.b
    4,     // .b.ww.b
    1,     // bb.ww.b
    66,    // wb.ww.b
    -109,  // .w.ww.b
    -23,   // bw.ww.b
    3,     // ww.ww.b
    63,    // ..bww.b
    -15,   // b.bww.b
    -45,   // w.bww.b
    -12,   // .bbww.b
    101,   // bbbww.b
    51,    // wbbww.b
    20,    // .wbww.b
    74,    // bwbww.b
    -49,   // wwbww.b
    7,     // ..www.b
    -58,   // b.www.b
    42,    // w.www.b
    147,   // .bwww.b
    -49,   // bbwww.b
    -4,    // wbwww.b
    -87,   // .wwww.b
    -6,    // bwwww.b
    -19,   // wwwww.b
    41,    // .....bb
    -24,   // b....bb
    36,    // w....bb
    -45,   // .b...bb
    10,    // bb...bb
    -57,   // wb...bb
    -17,   // .w...bb
    -34,   // bw...bb
    0,     // ww...bb
    -53,   // ..b..bb
    -94,   // b.b..bb
    21,    // w.b..bb
    7,     // .bb..bb
    144,   // bbb..bb
    -50,   // wbb..bb
    125,   // .wb..bb
    -56,   // bwb..bb
    34,    // wwb..bb
    -28,   // ..w..bb
    -21,   // b.w..bb
    -30,   // w.w..bb
    -9,    // .bw..bb
    -20,   // bbw..bb
    -8,    // wbw..bb
    91,    // .ww..bb
    -16,   // bww..bb
    -37,   // www..bb
    126,   // ...b.bb
    -42,   // b..b.bb
    -88,   // w..b.bb
    -83,   // .b.b.bb
    10,    // bb.b.bb
    76,    // wb.b.bb
    138,   // .w.b.bb
    -61,   // bw.b.bb
    32,    // ww.b.bb
    46,    // ..bb.bb
    -30,   // b.bb.bb
    -3,    // w.bb.bb
    11,    // .bbb.bb
    -40,   // bbbb.bb
    -2,    // wbbb.bb
    102,   // .wbb.bb
    39,    // bwbb.bb
    -123,  // wwbb.bb
    -18,   // ..wb.bb
    63,    // b.wb.bb
    -23,   // w.wb.bb
    -21,   // .bwb.bb
    -17,   // bbwb.bb
    -42,   // wbwb.bb
    40,    // .wwb.bb
    54,    // bwwb.bb
    53,    // wwwb.bb
    50,    // ...w.bb
    66,    // b..w.bb
    -93,   // w..w.bb
    -48,   // .b.w.bb
    82,    // bb.w.bb
    37,    // wb.w.bb
    27,    // .w.w.bb
    74,    // bw.w.bb
    -32,   // ww.w.bb
    -35,   // ..bw.bb
    3,     // b.bw.bb
    32,    // w.bw.bb
    68,    // .bbw.bb
    58,    // bbbw.bb
    102,   // wbbw.bb
    32,    // .wbw.bb
    177,   // bwbw.bb
    53,    // wwbw.bb
    47,    // ..ww.bb
    1,     // b.ww.bb
    4,     // w.ww.bb
    -20,   // .bww.bb
    -23,   // bbww.bb
    33,    // wbww.bb
    6,     // .www.bb
    17,    // bwww.bb
    -34,   // wwww.bb
    71,    // ....bbb
    -97,   // b...bbb
    98,    // w...bbb
    22,    // .b..bbb
    144,   // bb..bbb
    -18,   // wb..bbb
    92,    // .w..bbb
    9,     // bw..bbb
    37,    // ww..bbb
    171,   // ..b.bbb
    37,    // b.b.bbb
    9,     // w.b.bbb
    -18,   // .bb.bbb
    23,    // bbb.bbb
    -12,   // wbb.bbb
    -4,    // .wb.bbb
    -66,   // bwb.bbb
    -78,   // wwb.bbb
    40,    // ..w.bbb
    -25,   // b.w.bbb
    -23,   // w.w.bbb
    -14,   // .bw.bbb
    63,    // bbw.bbb
    -72,   // wbw.bbb
    97,    // .ww.bbb
    -14,   // bww.bbb
    0,     // www.bbb
    670,   // ...bbbb
    14,    // b..bbbb
    66,    // w..bbbb
    -67,   // .b.bbbb
    -40,   // bb.bbbb
    72,    // wb.bbbb
    256,   // .w.bbbb
    120,   // bw.bbbb
    34,    // ww.bbbb
    81,    // ..bbbbb
    -84,   // b.bbbbb
    19,    // w.bbbbb
    -81,   // .bbbbbb
    -45,   // bbbbbbb
    -22,   // wbbbbbb
    289,   // .wbbbbb
    -10,   // bwbbbbb
    123,   // wwbbbbb
    110,   // ..wbbbb
    101,   // b.wbbbb
    -14,   // w.wbbbb
    -111,  // .bwbbbb
    -25,   // bbwbbbb
    67,    // wbwbbbb
    -56,   // .wwbbbb
    -1,    // bwwbbbb
    -101,  // wwwbbbb
    115,   // ...wbbb
    66,    // b..wbbb
    -36,   // w..wbbb
    -112,  // .b.wbbb
    58,    // bb.wbbb
    -47,   // wb.wbbb
    -42,   // .w.wbbb
    26,    // bw.wbbb
    -53,   // ww.wbbb
    -166,  // ..bwbbb
    -56,   // b.bwbbb
    44,    // w.bwbbb
    -70,   // .bbwbbb
    -9,    // bbbwbbb
    -186,  // wbbwbbb
    -35,   // .wbwbbb
    40,    // bwbwbbb
    -28,   // wwbwbbb
    95,    // ..wwbbb
    101,   // b.wwbbb
    -74,   // w.wwbbb
    11,    // .bwwbbb
    67,    // bbwwbbb
    -99,   // wbwwbbb
    39,    // .wwwbbb
    18,    // bwwwbbb
    101,   // wwwwbbb
    -71,   // ....wbb
    -42,   // b...wbb
    -2,    // w...wbb
    -19,   // .b..wbb
    -20,   // bb..wbb
    -28,   // wb..wbb
    -26,   // .w..wbb
    56,    // bw..wbb
    -34,   // ww..wbb
    -45,   // ..b.wbb
    28,    // b.b.wbb
    29,    // w.b.wbb
    55,    // .bb.wbb
    63,    // bbb.wbb
    5,     // wbb.wbb
    -9,    // .wb.wbb
    13,    // bwb.wbb
    0,     // wwb.wbb
    32,    // ..w.wbb
    -106,  // b.w.wbb
    18,    // w.w.wbb
    -13,   // .bw.wbb
    -68,   // bbw.wbb
    -68,   // wbw.wbb
    24,    // .ww.wbb
    6,     // bww.wbb
    78,    // www.wbb
    -86,   // ...bwbb
    -94,   // b..bwbb
    10,    // w..bwbb
    32,    // .b.bwbb
    -17,   // bb.bwbb
    72,    // wb.bwbb
    -49,   // .w.bwbb
    -30,   // bw.bwbb
    -53,   // ww.bwbb
    -12,   // ..bbwbb
    -60,   // b.bbwbb
    49,    // w.bbwbb
    -109,  // .bbbwbb
    -25,   // bbbbwbb
    -31,   // wbbbwbb
    14,    // .wbbwbb
    -6,    // bwbbwbb
    38,    // wwbbwbb
    -26,   // ..wbwbb
    -6,    // b.wbwbb
    -111,  // w.wbwbb
    -6,    // .bwbwbb
    47,    // bbwbwbb
    129,   // wbwbwbb
    -131,  // .wwbwbb
    25,    // bwwbwbb
    28,    // wwwbwbb
    -5,    // ...wwbb
    -52,   // b..wwbb
    64,    // w..wwbb
    -4,    // .b.wwbb
    -23,   // bb.wwbb
    -17,   // wb.wwbb
    1,     // .w.wwbb
    100,   // bw.wwbb
    123,   // ww.wwbb
    -13,   // ..bwwbb
    -64,   // b.bwwbb
    3,     // w.bwwbb
    -58,   // .bbwwbb
    67,    // bbbwwbb
    2,     // wbbwwbb
    -72,   // .wbwwbb
    -33,   // bwbwwbb
    -38,   // wwbwwbb
    -11,   // ..wwwbb
    -49,   // b.wwwbb
    -10,   // w.wwwbb
    89,    // .bwwwbb
    -3,    // bbwwwbb
    5,     // wbwwwbb
    9,     // .wwwwbb
    -9,    // bwwwwbb
    -123,  // wwwwwbb
    20,    // .....wb
    4,     // b....wb
    -6,    // w....wb
    -62,   // .b...wb
    -34,   // bb...wb
    0,     // wb...wb
    -27,   // .w...wb
    -144,  // bw...wb
    57,    // ww...wb
    -53,   // ..b..wb
    23,    // b.b..wb
    -141,  // w.b..wb
    -5,    // .bb..wb
    9,     // bbb..wb
    24,    // wbb..wb
    88,    // .wb..wb
    -88,   // bwb..wb
    28,    // wwb..wb
    -20,   // ..w..wb
    67,    // b.w..wb
    -123,  // w.w..wb
    -98,   // .bw..wb
    56,    // bbw..wb
    -2,    // wbw..wb
    -14,   // .ww..wb
    -54,   // bww..wb
    18,    // www..wb
    -29,   // ...b.wb
    -4,    // b..b.wb
    19,    // w..b.wb
    0,     // .b.b.wb
    -61,   // bb.b.wb
    -54,   // wb.b.wb
    85,    // .w.b.wb
    45,    // bw.b.wb
    -37,   // ww.b.wb
    -9,    // ..bb.wb
    -30,   // b.bb.wb
    -66,   // w.bb.wb
    57,    // .bbb.wb
    120,   // bbbb.wb
    -24,   // wbbb.wb
    -36,   // .wbb.wb
    -45,   // bwbb.wb
    17,    // wwbb.wb
    -15,   // ..wb.wb
    43,    // b.wb.wb
    -4,    // w.wb.wb
    -25,   // .bwb.wb
    -30,   // bbwb.wb
    -2,    // wbwb.wb
    -4,    // .wwb.wb
    80,    // bwwb.wb
    47,    // wwwb.wb
    69,    // ...w.wb
    -59,   // b..w.wb
    98,    // w..w.wb
    119,   // .b.w.wb
    74,    // bb.w.wb
    54,    // wb.w.wb
    -11,   // .w.w.wb
    16,    // bw.w.wb
    -76,   // ww.w.wb
    37,    // ..bw.wb
    17,    // b.bw.wb
    21,    // w.bw.wb
    -29,   // .bbw.wb
    26,    // bbbw.wb
    -35,   // wbbw.wb
    32,    // .wbw.wb
    51,    // bwbw.wb
    -72,   // wwbw.wb
    9,     // ..ww.wb
    -23,   // b.ww.wb
    73,    // w.ww.wb
    77,    // .bww.wb
    100,   // bbww.wb
    82,    // wbww.wb
    -58,   // .www.wb
    -49,   // bwww.wb
    -72,   // wwww.wb
    57,    // ....bwb
    20,    // b...bwb
    40,    // w...bwb
    -66,   // .b..bwb
    -56,   // bb..bwb
    2,     // wb..bwb
    37,    // .w..bwb
    -88,   // bw..bwb
    8,     // ww..bwb
    -66,   // ..b.bwb
    7,     // b.b.bwb
    -53,   // w.b.bwb
    25,    // .bb.bwb
    -66,   // bbb.bwb
    -44,   // wbb.bwb
    0,     // .wb.bwb
    26,    // bwb.bwb
    68,    // wwb.bwb
    69,    // ..w.bwb
    31,    // b.w.bwb
    -22,   // w.w.bwb
    46,    // .bw.bwb
    13,    // bbw.bwb
    0,     // wbw.bwb
    131,   // .ww.bwb
    90,    // bww.bwb
    72,    // www.bwb
    -17,   // ...bbwb
    108,   // b..bbwb
    -97,   // w..bbwb
    -42,   // .b.bbwb
    39,    // bb.bbwb
    -82,   // wb.bbwb
    -145,  // .w.bbwb
    -45,   // bw.bbwb
    -33,   // ww.bbwb
    -55,   // ..bbbwb
    -73,   // b.bbbwb
    4,     // w.bbbwb
    -71,   // .bbbbwb
    -10,   // bbbbbwb
    -118,  // wbbbbwb
    7,     // .wbbbwb
    57,    // bwbbbwb
    -5,    // wwbbbwb
    8,     // ..wbbwb
    102,   // b.wbbwb
    -37,   // w.wbbwb
    -106,  // .bwbbwb
    -6,    // bbwbbwb
    69,    // wbwbbwb
    37,    // .wwbbwb
    19,    // bwwbbwb
    99,    // wwwbbwb
    4,     // ...wbwb
    -38,   // b..wbwb
    65,    // w..wbwb
    10,    // .b.wbwb
    177,   // bb.wbwb
    2,     // wb.wbwb
    -30,   // .w.wbwb
    51,    // bw.wbwb
    42,    // ww.wbwb
    -45,   // ..bwbwb
    26,    // b.bwbwb
    47,    // w.bwbwb
    -42,   // .bbwbwb
    40,    // bbbwbwb
    -50,   // wbbwbwb
    67,    // .wbwbwb
    -65,   // bwbwbwb
    -129,  // wwbwbwb
    -89,   // ..wwbwb
    74,    // b.wwbwb
    -33,   // w.wwbwb
    -122,  // .bwwbwb
    -33,   // bbwwbwb
    -69,   // wbwwbwb
    -94,   // .wwwbwb
    -104,  // bwwwbwb
    -67,   // wwwwbwb
    106,   // ....wwb
    -31,   // b...wwb
    125,   // w...wwb
    8,     // .b..wwb
    -16,   // bb..wwb
    -24,   // wb..wwb
    -99,   // .w..wwb
    -54,   // bw..wwb
    50,    // ww..wwb
    -39,   // ..b.wwb
    185,   // b.b.wwb
    39,    // w.b.wwb
    83,    // .bb.wwb
    -14,   // bbb.wwb
    0,     // wbb.wwb
    58,    // .wb.wwb
    90,    // bwb.wwb
    -5,    // wwb.wwb
    152,   // ..w.wwb
    43,    // b.w.wwb
    -14,   // w.w.wwb
    -51,   // .bw.wwb
    6,     // bbw.wwb
    44,    // wbw.wwb
    6,     // .ww.wwb
    -5,    // bww.wwb
    12,    // www.wwb
    33,    // ...bwwb
    -82,   // b..bwwb
    64,    // w..bwwb
    -75,   // .b.bwwb
    54,    // bb.bwwb
    35,    // wb.bwwb
    93,    // .w.bwwb
    80,    // bw.bwwb
    -102,  // ww.bwwb
    -113,  // ..bbwwb
    -60,   // b.bbwwb
    -51,   // w.bbwwb
    21,    // .bbbwwb
    -1,    // bbbbwwb
    22,    // wbbbwwb
    95,    // .wbbwwb
    19,    // bwbbwwb
    -2,    // wwbbwwb
    -13,   // ..wbwwb
    75,    // b.wbwwb
    -8,    // w.wbwwb
    100,   // .bwbwwb
    25,    // bbwbwwb
    50,    // wbwbwwb
    85,    // .wwbwwb
    -12,   // bwwbwwb
    186,   // wwwbwwb
    97,    // ...wwwb
    -23,   // b..wwwb
    104,   // w..wwwb
    38,    // .b.wwwb
    17,    // bb.wwwb
    24,    // wb.wwwb
    -98,   // .w.wwwb
    -49,   // bw.wwwb
    2,     // ww.wwwb
    39,    // ..bwwwb
    -37,   // b.bwwwb
    27,    // w.bwwwb
    99,    // .bbwwwb
    18,    // bbbwwwb
    -22,   // wbbwwwb
    14,    // .wbwwwb
    -104,  // bwbwwwb
    31,    // wwbwwwb
    -15,   // ..wwwwb
    -6,    // b.wwwwb
    37,    // w.wwwwb
    201,   // .bwwwwb
    -9,    // bbwwwwb
    118,   // wbwwwwb
    2,     // .wwwwwb
    81,    // bwwwwwb
    22,    // wwwwwwb
    -16,   // ......w
    0,     // b.....w
    -26,   // w.....w
    -79,   // .b....w
    36,    // bb....w
    -4,    // wb....w
    38,    // .w....w
    -6,    // bw....w
    24,    // ww....w
    -79,   // ..b...w
    -83,   // b.b...w
    8,     // w.b...w
    26,    // .bb...w
    98,    // bbb...w
    31,    // wbb...w
    -7,    // .wb...w
    40,    // bwb...w
    42,    // wwb...w
    -32,   // ..w...w
    82,    // b.w...w
    -13,   // w.w...w
    91,    // .bw...w
    -2,    // bbw...w
    -20,   // wbw...w
    4,     // .ww...w
    125,   // bww...w
    97,    // www...w
    -8,    // ...b..w
    30,    // b..b..w
    11,    // w..b..w
    -26,   // .b.b..w
    -88,   // bb.b..w
    59,    // wb.b..w
    78,    // .w.b..w
    19,    // bw.b..w
    -66,   // ww.b..w
    -41,   // ..bb..w
    -46,   // b.bb..w
    5,     // w.bb..w
    93,    // .bbb..w
    66,    // bbbb..w
    23,    // wbbb..w
    -30,   // .wbb..w
    -97,   // bwbb..w
    52,    // wwbb..w
    -102,  // ..wb..w
    -24,   // b.wb..w
    -65,   // w.wb..w
    58,    // .bwb..w
    10,    // bbwb..w
    38,    // wbwb..w
    -61,   // .wwb..w
    64,    // bwwb..w
    -66,   // wwwb..w
    14,    // ...w..w
    -30,   // b..w..w
    57,    // w..w..w
    -3,    // .b.w..w
    -93,   // bb.w..w
    4,     // wb.w..w
    43,    // .w.w..w
    98,    // bw.w..w
    42,    // ww.w..w
    58,    // ..bw..w
    -12,   // b.bw..w
    52,    // w.bw..w
    34,    // .bbw..w
    -36,   // bbbw..w
    82,    // wbbw..w
    -46,   // .wbw..w
    65,    // bwbw..w
    94,    // wwbw..w
    -34,   // ..ww..w
    27,    // b.ww..w
    46,    // w.ww..w
    10,    // .bww..w
    64,    // bbww..w
    -108,  // wbww..w
    53,    // .www..w
    104,   // bwww..w
    -14,   // wwww..w
    -27,   // ....b.w
    -82,   // b...b.w
    8,     // w...b.w
    -64,   // .b..b.w
    21,    // bb..b.w
    -67,   // wb..b.w
    24,    // .w..b.w
    -141,  // bw..b.w
    21,    // ww..b.w
    -26,   // ..b.b.w
    77,    // b.b.b.w
    -67,   // w.b.b.w
    9,     // .bb.b.w
    9,     // bbb.b.w
    -43,   // wbb.b.w
    40,    // .wb.b.w
    -53,   // bwb.b.w
    106,   // wwb.b.w
    19,    // ..w.b.w
    0,     // b.w.b.w
    -21,   // w.w.b.w
    -32,   // .bw.b.w
    29,    // bbw.b.w
    -31,   // wbw.b.w
    4,     // .ww.b.w
    39,    // bww.b.w
    25,    // www.b.w
    -19,   // ...bb.w
    -27,   // b..bb.w
    5,     // w..bb.w
    109,   // .b.bb.w
    -3,    // bb.bb.w
    23,    // wb.bb.w
    -4,    // .w.bb.w
    -66,   // bw.bb.w
    -1,    // ww.bb.w
    -7,    // ..bbb.w
    -42,   // b.bbb.w
    58,    // w.bbb.w
    87,    // .bbbb.w
    19,    // bbbbb.w
    6,     // wbbbb.w
    -147,  // .wbbb.w
    4,     // bwbbb.w
    49,    // wwbbb.w
    -63,   // ..wbb.w
    45,    // b.wbb.w
    15,    // w.wbb.w
    -20,   // .bwbb.w
    49,    // bbwbb.w
    -74,   // wbwbb.w
    12,    // .wwbb.w
    -51,   // bwwbb.w
    -101,  // wwwbb.w
    -65,   // ...wb.w
    24,    // b..wb.w
    52,    // w..wb.w
    49,    // .b.wb.w
    32,    // bb.wb.w
    -43,   // wb.wb.w
    10,    // .w.wb.w
    21,    // bw.wb.w
    -63,   // ww.wb.w
    -16,   // ..bwb.w
    -5,    // b.bwb.w
    58,    // w.bwb.w
    -97,   // .bbwb.w
    44,    // bbbwb.w
    -75,   // wbbwb.w
    38,    // .wbwb.w
    47,    // bwbwb.w
    6,     // wwbwb.w
    56,    // ..wwb.w
    -45,   // b.wwb.w
    -10,   // w.wwb.w
    -22,   // .bwwb.w
    3,     // bbwwb.w
    -102,  // wbwwb.w
    -7,    // .wwwb.w
    27,    // bwwwb.w
    -101,  // wwwwb.w
    -80,   // ....w.w
    83,    // b...w.w
    -13,   // w...w.w
    -31,   // .b..w.w
    -30,   // bb..w.w
    -23,   // wb..w.w
    -56,   // .w..w.w
    -123,  // bw..w.w
    94,    // ww..w.w
    -66,   // ..b.w.w
    0,     // b.b.w.w
    -21,   // w.b.w.w
    40,    // .bb.w.w
    -23,   // bbb.w.w
    -185,  // wbb.w.w
    44,    // .wb.w.w
    -22,   // bwb.w.w
    -28,   // wwb.w.w
    30,    // ..w.w.w
    -77,   // b.w.w.w
    -32,   // w.w.w.w
    99,    // .bw.w.w
    18,    // bbw.w.w
    -7,    // wbw.w.w
    -29,   // .ww.w.w
    -14,   // bww.w.w
    -37,   // www.w.w
    -81,   // ...bw.w
    12,    // b..bw.w
    -65,   // w..bw.w
    -25,   // .b.bw.w
    -23,   // bb.bw.w
    -17,   // wb.bw.w
    -48,   // .w.bw.w
    -4,    // bw.bw.w
    -3,    // ww.bw.w
    -32,   // ..bbw.w
    85,    // b.bbw.w
    15,    // w.bbw.w
    -86,   // .bbbw.w
    -14,   // bbbbw.w
    37,    // wbbbw.w
    77,    // .wbbw.w
    -37,   // bwbbw.w
    64,    // wwbbw.w
    -7,    // ..wbw.w
    5,     // b.wbw.w
    -27,   // w.wbw.w
    12,    // .bwbw.w
    -111,  // bbwbw.w
    -26,   // wbwbw.w
    91,    // .wwbw.w
    -8,    // bwwbw.w
    56,    // wwwbw.w
    -95,   // ...ww.w
    46,    // b..ww.w
    46,    // w..ww.w
    27,    // .b.ww.w
    4,     // bb.ww.w
    30,    // wb.ww.w
    -29,   // .w.ww.w
    73,    // bw.ww.w
    30,    // ww.ww.w
    78,    // ..bww.w
    -85,   // b.bww.w
    -10,   // w.bww.w
    -29,   // .bbww.w
    -74,   // bbbww.w
    60,    // wbbww.w
    55,    // .wbww.w
    -33,   // bwbww.w
    60,    // wwbww.w
    -100,  // ..www.w
    42,    // b.www.w
    -51,   // w.www.w
    -214,  // .bwww.w
    -10,   // bbwww.w
    73,    // wbwww.w
    -129,  // .wwww.w
    37,    // bwwww.w
    84,    // wwwww.w
    -20,   // .....bw
    6,     // b....bw
    -4,    // w....bw
    27,    // .b...bw
    -57,   // bb...bw
    144,   // wb...bw
    62,    // .w...bw
    0,     // bw...bw
    34,    // ww...bw
    20,    // ..b..bw
    123,   // b.b..bw
    -67,   // w.b..bw
    14,    // .bb..bw
    -18,   // bbb..bw
    54,    // wbb..bw
    98,    // .wb..bw
    2,     // bwb..bw
    -56,   // wwb..bw
    53,    // ..w..bw
    141,   // b.w..bw
    -23,   // w.w..bw
    -88,   // .bw..bw
    -28,   // bbw..bw
    88,    // wbw..bw
    5,     // .ww..bw
    -24,   // bww..bw
    -9,    // www..bw
    -69,   // ...b.bw
    -98,   // b..b.bw
    59,    // w..b.bw
    11,    // .b.b.bw
    76,    // bb.b.bw
    -16,   // wb.b.bw
    -119,  // .w.b.bw
    -54,   // bw.b.bw
    -74,   // ww.b.bw
    -9,    // ..bb.bw
    -73,   // b.bb.bw
    23,    // w.bb.bw
    58,    // .bbb.bw
    72,    // bbbb.bw
    49,    // wbbb.bw
    -77,   // .wbb.bw
    -82,   // bwbb.bw
    -100,  // wwbb.bw
    -37,   // ..wb.bw
    -21,   // b.wb.bw
    -17,   // w.wb.bw
    -32,   // .bwb.bw
    72,    // bbwb.bw
    -51,   // wbwb.bw
    29,    // .wwb.bw
    35,    // bwwb.bw
    -26,   // wwwb.bw
    29,    // ...w.bw
    -19,   // b..w.bw
    4,     // w..w.bw
    -85,   // .b.w.bw
    37,    // bb.w.bw
    -45,   // wb.w.bw
    0,     // .w.w.bw
    54,    // bw.w.bw
    61,    // ww.w.bw
    15,    // ..bw.bw
    4,     // b.bw.bw
    -43,   // w.bw.bw
    4,     // .bbw.bw
    -47,   // bbbw.bw
    -80,   // wbbw.bw
    25,    // .wbw.bw
    2,     // bwbw.bw
    30,    // wwbw.bw
    9,     // ..ww.bw
    66,    // b.ww.bw
    30,    // w.ww.bw
    36,    // .bww.bw
    -17,   // bbww.bw
    45,    // wbww.bw
    -57,   // .www.bw
    24,    // bwww.bw
    -120,  // wwww.bw
    -106,  // ....bbw
    -125,  // b...bbw
    31,    // w...bbw
    99,    // .b..bbw
    -50,   // bb..bbw
    54,    // wb..bbw
    -8,    // .w..bbw
    24,    // bw..bbw
    16,    // ww..bbw
    -152,  // ..b.bbw
    14,    // b.b.bbw
    -43,   // w.b.bbw
    -6,    // .bb.bbw
    -12,   // bbb.bbw
    5,     // wbb.bbw
    51,    // .wb.bbw
    -44,   // bwb.bbw
    -6,    // wwb.bbw
    39,    // ..w.bbw
    -39,   // b.w.bbw
    -185,  // w.w.bbw
    -58,   // .bw.bbw
    5,     // bbw.bbw
    -90,   // wbw.bbw
    -83,   // .ww.bbw
    0,     // bww.bbw
    14,    // www.bbw
    -97,   // ...bbbw
    -104,  // b..bbbw
    23,    // w..bbbw
    98,    // .b.bbbw
    -2,    // bb.bbbw
    49,    // wb.bbbw
    -38,   // .w.bbbw
    -24,   // bw.bbbw
    -17,   // ww.bbbw
    15,    // ..bbbbw
    -37,   // b.bbbbw
    6,     // w.bbbbw
    -2,    // .bbbbbw
    -22,   // bbbbbbw
    -81,   // wbbbbbw
    -201,  // .wbbbbw
    -118,  // bwbbbbw
    9,     // wwbbbbw
    -39,   // ..wbbbw
    -27,   // b.wbbbw
    37,    // w.wbbbw
    -14,   // .bwbbbw
    -31,   // bbwbbbw
    104,   // wbwbbbw
    -99,   // .wwbbbw
    22,    // bwwbbbw
    -18,   // wwwbbbw
    -33,   // ...wbbw
    -64,   // b..wbbw
    82,    // w..wbbw
    -93,   // .b.wbbw
    102,   // bb.wbbw
    -80,   // wb.wbbw
    75,    // .w.wbbw
    -35,   // bw.wbbw
    -54,   // ww.wbbw
    13,    // ..bwbbw
    8,     // b.bwbbw
    -75,   // w.bwbbw
    -85,   // .bbwbbw
    -186,  // bbbwbbw
    12,    // wbbwbbw
    -100,  // .wbwbbw
    -50,   // bwbwbbw
    -25,   // wwbwbbw
    113,   // ..wwbbw
    51,    // b.wwbbw
    60,    // w.wwbbw
    -95,   // .bwwbbw
    2,     // bbwwbbw
    -19,   // wbwwbbw
    -21,   // .wwwbbw
    -22,   // bwwwbbw
    1,     // wwwwbbw
    -57,   // ....wbw
    -40,   // b...wbw
    -20,   // w...wbw
    -37,   // .b..wbw
    -8,    // bb..wbw
    88,    // wb..wbw
    66,    // .w..wbw
    -2,    // bw..wbw
    56,    // ww..wbw
    -69,   // ..b.wbw
    22,    // b.b.wbw
    -31,   // w.b.wbw
    -131,  // .bb.wbw
    -72,   // bbb.wbw
    -90,   // wbb.wbw
    -46,   // .wb.wbw
    0,     // bwb.wbw
    -13,   // wwb.wbw
    66,    // ..w.wbw
    53,    // b.w.wbw
    -7,    // w.w.wbw
    0,     // .bw.wbw
    -68,   // bbw.wbw
    -26,   // wbw.wbw
    -25,   // .ww.wbw
    44,    // bww.wbw
    66,    // www.wbw
    -4,    // ...bwbw
    -65,   // b..bwbw
    38,    // w..bwbw
    30,    // .b.bwbw
    -42,   // bb.bwbw
    -51,   // wb.bwbw
    -10,   // .w.bwbw
    -2,    // bw.bwbw
    -177,  // ww.bwbw
    89,    // ..bbwbw
    33,    // b.bbwbw
    -74,   // w.bbwbw
    94,    // .bbbwbw
    67,    // bbbbwbw
    104,   // wbbbwbw
    122,   // .wbbwbw
    69,    // bwbbwbw
    33,    // wwbbwbw
    45,    // ..wbwbw
    -47,   // b.wbwbw
    -26,   // w.wbwbw
    -67,   // .bwbwbw
    129,   // bbwbwbw
    65,    // wbwbwbw
    42,    // .wwbwbw
    50,    // bwwbwbw
    -40,   // wwwbwbw
    17,    // ...wwbw
    97,    // b..wwbw
    -108,  // w..wwbw
    145,   // .b.wwbw
    33,    // bb.wwbw
    45,    // wb.wwbw
    42,    // .w.wwbw
    82,    // bw.wwbw
    -39,   // ww.wwbw
    -8,    // ..bwwbw
    37,    // b.bwwbw
    -102,  // w.bwwbw
    -37,   // .bbwwbw
    -99,   // bbbwwbw
    -19,   // wbbwwbw
    106,   // .wbwwbw
    -69,   // bwbwwbw
    6,     // wwbwwbw
    55,    // ..wwwbw
    -4,    // b.wwwbw
    73,    // w.wwwbw
    -7,    // .bwwwbw
    5,     // bbwwwbw
    -57,   // wbwwwbw
    71,    // .wwwwbw
    118,   // bwwwwbw
    10,    // wwwwwbw
    -41,   // .....ww
    -36,   // b....ww
    24,    // w....ww
    17,    // .b...ww
    0,     // bb...ww
    34,    // wb...ww
    45,    // .w...ww
    57,    // bw...ww
    -10,   // ww...ww
    28,    // ..b..ww
    30,    // b.b..ww
    21,    // w.b..ww
    -91,   // .bb..ww
    37,    // bbb..ww
    16,    // wbb..ww
    9,     // .wb..ww
    8,     // bwb..ww
    20,    // wwb..ww
    53,    // ..w..ww
    -21,   // b.w..ww
    94,    // w.w..ww
    -125,  // .bw..ww
    -34,   // bbw..ww
    56,    // wbw..ww
    -7,    // .ww..ww
    50,    // bww..ww
    -144,  // www..ww
    -50,   // ...b.ww
    93,    // b..b.ww
    -66,   // w..b.ww
    -27,   // .b.b.ww
    32,    // bb.b.ww
    -74,   // wb.b.ww
    48,    // .w.b.ww
    -37,   // bw.b.ww
    -82,   // ww.b.ww
    -47,   // ..bb.ww
    -4,    // b.bb.ww
    -1,    // w.bb.ww
    -6,    // .bbb.ww
    34,    // bbbb.ww
    -17,   // wbbb.ww
    20,    // .wbb.ww
    -33,   // bwbb.ww
    23,    // wwbb.ww
    35,    // ..wb.ww
    -32,   // b.wb.ww
    -3,    // w.wb.ww
    -32,   // .bwb.ww
    -53,   // bbwb.ww
    -177,  // wbwb.ww
    -68,   // .wwb.ww
    -102,  // bwwb.ww
    -58,   // wwwb.ww
    -126,  // ...w.ww
    88,    // b..w.ww
    42,    // w..w.ww
    -138,  // .b.w.ww
    -32,   // bb.w.ww
    61,    // wb.w.ww
    83,    // .w.w.ww
    -76,   // bw.w.ww
    -10,   // ww.w.ww
    18,    // ..bw.ww
    23,    // b.bw.ww
    -63,   // w.bw.ww
    -40,   // .bbw.ww
    -53,   // bbbw.ww
    -54,   // wbbw.ww
    21,    // .wbw.ww
    42,    // bwbw.ww
    17,    // wwbw.ww
    -46,   // ..ww.ww
    3,     // b.ww.ww
    30,    // w.ww.ww
    -102,  // .bww.ww
    123,   // bbww.ww
    -39,   // wbww.ww
    -11,   // .www.ww
    2,     // bwww.ww
    40,    // wwww.ww
    71,    // ....bww
    2,     // b...bww
    42,    // w...bww
    26,    // .b..bww
    34,    // bb..bww
    -56,   // wb..bww
    19,    // .w..bww
    28,    // bw..bww
    20,    // ww..bww
    -32,   // ..b.bww
    -18,   // b.b.bww
    106,   // w.b.bww
    -24,   // .bb.bww
    -78,   // bbb.bww
    -6,    // wbb.bww
    13,    // .wb.bww
    68,    // bwb.bww
    68,    // wwb.bww
    45,    // ..w.bww
    -29,   // b.w.bww
    -28,   // w.w.bww
    9,     // .bw.bww
    0,     // bbw.bww
    -13,   // wbw.bww
    -55,   // .ww.bww
    -5,    // bww.bww
    -63,   // www.bww
    5,     // ...bbww
    -64,   // b..bbww
    52,    // w..bbww
    -1,    // .b.bbww
    -123,  // bb.bbww
    -100,  // wb.bbww
    4,     // .w.bbww
    17,    // bw.bbww
    23,    // ww.bbww
    11,    // ..bbbww
    10,    // b.bbbww
    49,    // w.bbbww
    -9,    // .bbbbww
    123,   // bbbbbww
    9,     // wbbbbww
    -89,   // .wbbbww
    -5,    // bwbbbww
    3,     // wwbbbww
    13,    // ..wbbww
    -3,    // b.wbbww
    64,    // w.wbbww
    72,    // .bwbbww
    38,    // bbwbbww
    33,    // wbwbbww
    58,    // .wwbbww
    -2,    // bwwbbww
    -67,   // wwwbbww
    86,    // ...wbww
    -10,   // b..wbww
    94,    // w..wbww
    49,    // .b.wbww
    53,    // bb.wbww
    30,    // wb.wbww
    -32,   // .w.wbww
    -72,   // bw.wbww
    17,    // ww.wbww
    26,    // ..bwbww
    111,   // b.bwbww
    6,     // w.bwbww
    131,   // .bbwbww
    -28,   // bbbwbww
    -25,   // wbbwbww
    6,     // .wbwbww
    -129,  // bwbwbww
    -47,   // wwbwbww
    12,    // ..wwbww
    -49,   // b.wwbww
    60,    // w.wwbww
    -14,   // .bwwbww
    -38,   // bbwwbww
    6,     // wbwwbww
    109,   // .wwwbww
    31,    // bwwwbww
    25,    // wwwwbww
    -71,   // ....www
    -98,   // b...www
    97,    // w...www
    -92,   // .b..www
    -37,   // bb..www
    -9,    // wb..www
    -22,   // .w..www
    18,    // bw..www
    -144,  // ww..www
    -40,   // ..b.www
    23,    // b.b.www
    25,    // w.b.www
    -97,   // .bb.www
    0,     // bbb.www
    14,    // wbb.www
    14,    // .wb.www
    72,    // bwb.www
    -63,   // wwb.www
    -171,  // ..w.www
    -9,    // b.w.www
    -37,   // w.w.www
    4,     // .bw.www
    78,    // bbw.www
    66,    // wbw.www
    18,    // .ww.www
    12,    // bww.www
    -23,   // www.www
    -115,  // ...bwww
    36,    // b..bwww
    -66,   // w..bwww
    42,    // .b.bwww
    53,    // bb.bwww
    -26,   // wb.bwww
    112,   // .w.bwww
    47,    // bw.bwww
    -58,   // ww.bwww
    -95,   // ..bbwww
    74,    // b.bbwww
    -101,  // w.bbwww
    -39,   // .bbbwww
    -101,  // bbbbwww
    -18,   // wbbbwww
    -11,   // .wbbwww
    99,    // bwbbwww
    -67,   // wwbbwww
    166,   // ..wbwww
    -44,   // b.wbwww
    56,    // w.wbwww
    35,    // .bwbwww
    28,    // bbwbwww
    -40,   // wbwbwww
    70,    // .wwbwww
    186,   // bwwbwww
    9,     // wwwbwww
    -670,  // ...wwww
    -66,   // b..wwww
    -14,   // w..wwww
    -256,  // .b.wwww
    -34,   // bb.wwww
    -120,  // wb.wwww
    67,    // .w.wwww
    -72,   // bw.wwww
    40,    // ww.wwww
    -110,  // ..bwwww
    14,    // b.bwwww
    -101,  // w.bwwww
    56,    // .bbwwww
    101,   // bbbwwww
    1,     // wbbwwww
    111,   // .wbwwww
    -67,   // bwbwwww
    25,    // wwbwwww
    -81,   // ..wwwww
    -19,   // b.wwwww
    84,    // w.wwwww
    -289,  // .bwwwww
    -123,  // bbwwwww
    10,    // wbwwwww
    81,    // .wwwwww
    22,    // bwwwwww
    45,    // wwwwwww
    0,     // captures=0 threats=0
    52,    // captures=0 threats=1
    113,   // captures=0 threats=2
    162,   // captures=0 threats=3
    179,   // captures=0 threats=4
    56,    // captures=0 additional threats
    79,    // captures=1 threats=0
    139,   // captures=1 threats=1
    207,   // captures=1 threats=2
    469,   // captures=1 threats=3
    487,   // captures=1 threats=4
    10,    // captures=1 additional threats
    109,   // captures=2 threats=0
    278,   // captures=2 threats=1
    385,   // captures=2 threats=2
    622,   // captures=2 threats=3
    745,   // captures=2 threats=4
    144,   // captures=2 additional threats
    155,   // captures=3 threats=0
    456,   // captures=3 threats=1
    622,   // captures=3 threats=2
    823,   // captures=3 threats=3
    866,   // captures=3 threats=4
    177,   // captures=3 additional threats
    166,   // captures=4 threats=0
    479,   // captures=4 threats=1
    668,   // captures=4 threats=2
    951,   // captures=4 threats=3
    1237,  // captures=4 threats=4
    317,   // captures=4 additional threats
].into_boxed_slice()
