[
    0,     // ......
    -11,   // b.....
    11,    // w.....
    -37,   // .b....
    23,    // bb....
    0,     // wb....
    37,    // .w....
    0,     // bw....
    -23,   // ww....
    -5,    // ..b...
    38,    // b.b...
    71,    // w.b...
    -33,   // .bb...
    148,   // bbb...
    21,    // wbb...
    0,     // .wb...
    -19,   // bwb...
    0,     // wwb...
    5,     // ..w...
    -71,   // b.w...
    -38,   // w.w...
    0,     // .bw...
    0,     // bbw...
    19,    // wbw...
    33,    // .ww...
    -21,   // bww...
    -148,  // www...
    -5,    // ...b..
    -5,    // b..b..
    -158,  // w..b..
    21,    // .b.b..
    -18,   // bb.b..
    -6,    // wb.b..
    20,    // .w.b..
    1,     // bw.b..
    -77,   // ww.b..
    77,    // ..bb..
    101,   // b.bb..
    65,    // w.bb..
    83,    // .bbb..
    84,    // bbbb..
    -27,   // wbbb..
    -70,   // .wbb..
    -2,    // bwbb..
    12,    // wwbb..
    0,     // ..wb..
    -13,   // b.wb..
    -103,  // w.wb..
    87,    // .bwb..
    72,    // bbwb..
    -55,   // wbwb..
    -20,   // .wwb..
    -77,   // bwwb..
    -19,   // wwwb..
    5,     // ...w..
    158,   // b..w..
    5,     // w..w..
    -20,   // .b.w..
    77,    // bb.w..
    -1,    // wb.w..
    -21,   // .w.w..
    6,     // bw.w..
    18,    // ww.w..
    0,     // ..bw..
    103,   // b.bw..
    13,    // w.bw..
    20,    // .bbw..
    19,    // bbbw..
    77,    // wbbw..
    -87,   // .wbw..
    55,    // bwbw..
    -72,   // wwbw..
    -77,   // ..ww..
    -65,   // b.ww..
    -101,  // w.ww..
    70,    // .bww..
    -12,   // bbww..
    2,     // wbww..
    -83,   // .www..
    27,    // bwww..
    -84,   // wwww..
    -37,   // ....b.
    0,     // b...b.
    61,    // w...b.
    121,   // .b..b.
    8,     // bb..b.
    55,    // wb..b.
    0,     // .w..b.
    19,    // bw..b.
    -69,   // ww..b.
    21,    // ..b.b.
    0,     // b.b.b.
    -13,   // w.b.b.
    42,    // .bb.b.
    107,   // bbb.b.
    32,    // wbb.b.
    39,    // .wb.b.
    0,     // bwb.b.
    -13,   // wwb.b.
    -20,   // ..w.b.
    -55,   // b.w.b.
    -23,   // w.w.b.
    24,    // .bw.b.
    -23,   // bbw.b.
    97,    // wbw.b.
    55,    // .ww.b.
    2,     // bww.b.
    -22,   // www.b.
    -33,   // ...bb.
    105,   // b..bb.
    8,     // w..bb.
    42,    // .b.bb.
    -35,   // bb.bb.
    -64,   // wb.bb.
    -55,   // .w.bb.
    0,     // bw.bb.
    9,     // ww.bb.
    83,    // ..bbb.
    -16,   // b.bbb.
    9,     // w.bbb.
    70,    // .bbbb.
    -69,   // bbbbb.
    103,   // wbbbb.
    -125,  // .wbbb.
    -167,  // bwbbb.
    -108,  // wwbbb.
    20,    // ..wbb.
    2,     // b.wbb.
    0,     // w.wbb.
    -74,   // .bwbb.
    0,     // bbwbb.
    -39,   // wbwbb.
    0,     // .wwbb.
    9,     // bwwbb.
    -27,   // wwwbb.
    0,     // ...wb.
    -36,   // b..wb.
    26,    // w..wb.
    24,    // .b.wb.
    66,    // bb.wb.
    -47,   // wb.wb.
    -39,   // .w.wb.
    -31,   // bw.wb.
    -67,   // ww.wb.
    87,    // ..bwb.
    -7,    // b.bwb.
    18,    // w.bwb.
    -74,   // .bbwb.
    23,    // bbbwb.
    -34,   // wbbwb.
    0,     // .wbwb.
    35,    // bwbwb.
    48,    // wwbwb.
    70,    // ..wwb.
    158,   // b.wwb.
    93,    // w.wwb.
    109,   // .bwwb.
    -17,   // bbwwb.
    -61,   // wbwwb.
    125,   // .wwwb.
    77,    // bwwwb.
    0,     // wwwwb.
    37,    // ....w.
    -61,   // b...w.
    0,     // w...w.
    0,     // .b..w.
    69,    // bb..w.
    -19,   // wb..w.
    -121,  // .w..w.
    -55,   // bw..w.
    -8,    // ww..w.
    20,    // ..b.w.
    23,    // b.b.w.
    55,    // w.b.w.
    -55,   // .bb.w.
    22,    // bbb.w.
    -2,    // wbb.w.
    -24,   // .wb.w.
    -97,   // bwb.w.
    23,    // wwb.w.
    -21,   // ..w.w.
    13,    // b.w.w.
    0,     // w.w.w.
    -39,   // .bw.w.
    13,    // bbw.w.
    0,     // wbw.w.
    -42,   // .ww.w.
    -32,   // bww.w.
    -107,  // www.w.
    0,     // ...bw.
    -26,   // b..bw.
    36,    // w..bw.
    39,    // .b.bw.
    67,    // bb.bw.
    31,    // wb.bw.
    -24,   // .w.bw.
    47,    // bw.bw.
    -66,   // ww.bw.
    -70,   // ..bbw.
    -93,   // b.bbw.
    -158,  // w.bbw.
    -125,  // .bbbw.
    0,     // bbbbw.
    -77,   // wbbbw.
    -109,  // .wbbw.
    61,    // bwbbw.
    17,    // wwbbw.
    -87,   // ..wbw.
    -18,   // b.wbw.
    7,     // w.wbw.
    0,     // .bwbw.
    -48,   // bbwbw.
    -35,   // wbwbw.
    74,    // .wwbw.
    34,    // bwwbw.
    -23,   // wwwbw.
    33,    // ...ww.
    -8,    // b..ww.
    -105,  // w..ww.
    55,    // .b.ww.
    -9,    // bb.ww.
    0,     // wb.ww.
    -42,   // .w.ww.
    64,    // bw.ww.
    35,    // ww.ww.
    -20,   // ..bww.
    0,     // b.bww.
    -2,    // w.bww.
    0,     // .bbww.
    27,    // bbbww.
    -9,    // wbbww.
    74,    // .wbww.
    39,    // bwbww.
    0,     // wwbww.
    -83,   // ..www.
    -9,    // b.www.
    16,    // w.www.
    125,   // .bwww.
    108,   // bbwww.
    167,   // wbwww.
    -70,   // .wwww.
    -103,  // bwwww.
    69,    // wwwww.
    -11,   // .....b
    -71,   // b....b
    0,     // w....b
    0,     // .b...b
    -26,   // bb...b
    107,   // wb...b
    -61,   // .w...b
    123,   // bw...b
    -20,   // ww...b
    -5,    // ..b..b
    -59,   // b.b..b
    65,    // w.b..b
    105,   // .bb..b
    68,    // bbb..b
    53,    // wbb..b
    -26,   // .wb..b
    0,     // bwb..b
    31,    // wwb..b
    158,   // ..w..b
    58,    // b.w..b
    9,     // w.w..b
    -36,   // .bw..b
    -1,    // bbw..b
    -4,    // wbw..b
    -8,    // .ww..b
    -71,   // bww..b
    16,    // www..b
    38,    // ...b.b
    -59,   // b..b.b
    -9,    // w..b.b
    0,     // .b.b.b
    -19,   // bb.b.b
    43,    // wb.b.b
    23,    // .w.b.b
    -79,   // bw.b.b
    33,    // ww.b.b
    101,   // ..bb.b
    50,    // b.bb.b
    0,     // w.bb.b
    -16,   // .bbb.b
    -42,   // bbbb.b
    75,    // wbbb.b
    -93,   // .wbb.b
    -132,  // bwbb.b
    39,    // wwbb.b
    103,   // ..wb.b
    30,    // b.wb.b
    0,     // w.wb.b
    -7,    // .bwb.b
    -10,   // bbwb.b
    -157,  // wbwb.b
    0,     // .wwb.b
    -54,   // bwwb.b
    -22,   // wwwb.b
    -71,   // ...w.b
    58,    // b..w.b
    -65,   // w..w.b
    -55,   // .b.w.b
    0,     // bb.w.b
    0,     // wb.w.b
    13,    // .w.w.b
    -23,   // bw.w.b
    21,    // ww.w.b
    -13,   // ..bw.b
    30,    // b.bw.b
    0,     // w.bw.b
    2,     // .bbw.b
    14,    // bbbw.b
    13,    // wbbw.b
    -18,   // .wbw.b
    34,    // bwbw.b
    -50,   // wwbw.b
    -65,   // ..ww.b
    21,    // b.ww.b
    0,     // w.ww.b
    158,   // .bww.b
    -75,   // bbww.b
    49,    // wbww.b
    -9,    // .www.b
    49,    // bwww.b
    39,    // wwww.b
    23,    // ....bb
    -26,   // b...bb
    20,    // w...bb
    8,     // .b..bb
    -39,   // bb..bb
    44,    // wb..bb
    69,    // .w..bb
    108,   // bw..bb
    0,     // ww..bb
    -18,   // ..b.bb
    -19,   // b.b.bb
    -21,   // w.b.bb
    -35,   // .bb.bb
    -60,   // bbb.bb
    25,    // wbb.bb
    67,    // .wb.bb
    0,     // bwb.bb
    -39,   // wwb.bb
    77,    // ..w.bb
    0,     // b.w.bb
    -33,   // w.w.bb
    66,    // .bw.bb
    -65,   // bbw.bb
    16,    // wbw.bb
    -9,    // .ww.bb
    0,     // bww.bb
    0,     // www.bb
    148,   // ...bbb
    68,    // b..bbb
    -16,   // w..bbb
    107,   // .b.bbb
    -60,   // bb.bbb
    -32,   // wb.bbb
    22,    // .w.bbb
    -40,   // bw.bbb
    0,     // ww.bbb
    84,    // ..bbbb
    -42,   // b.bbbb
    -39,   // w.bbbb
    -69,   // .bbbbb
    6,     // bbbbbb
    -68,   // wbbbbb
    0,     // .wbbbb
    -73,   // bwbbbb
    -21,   // wwbbbb
    19,    // ..wbbb
    14,    // b.wbbb
    22,    // w.wbbb
    23,    // .bwbbb
    -50,   // bbwbbb
    -91,   // wbwbbb
    27,    // .wwbbb
    -31,   // bwwbbb
    0,     // wwwbbb
    0,     // ...wbb
    -1,    // b..wbb
    -31,   // w..wbb
    -23,   // .b.wbb
    -65,   // bb.wbb
    -102,  // wb.wbb
    13,    // .w.wbb
    -75,   // bw.wbb
    39,    // ww.wbb
    72,    // ..bwbb
    -10,   // b.bwbb
    50,    // w.bwbb
    0,     // .bbwbb
    -50,   // bbbwbb
    84,    // wbbwbb
    -48,   // .wbwbb
    -41,   // bwbwbb
    0,     // wwbwbb
    -12,   // ..wwbb
    -75,   // b.wwbb
    -39,   // w.wwbb
    -17,   // .bwwbb
    -70,   // bbwwbb
    -46,   // wbwwbb
    108,   // .wwwbb
    113,   // bwwwbb
    21,    // wwwwbb
    0,     // ....wb
    123,   // b...wb
    -107,  // w...wb
    19,    // .b..wb
    108,   // bb..wb
    0,     // wb..wb
    -55,   // .w..wb
    -51,   // bw..wb
    -44,   // ww..wb
    1,     // ..b.wb
    -79,   // b.b.wb
    0,     // w.b.wb
    0,     // .bb.wb
    -40,   // bbb.wb
    79,    // wbb.wb
    47,    // .wb.wb
    -11,   // bwb.wb
    102,   // wwb.wb
    6,     // ..w.wb
    -23,   // b.w.wb
    -43,   // w.w.wb
    -31,   // .bw.wb
    -75,   // bbw.wb
    51,    // wbw.wb
    64,    // .ww.wb
    -101,  // bww.wb
    32,    // www.wb
    -19,   // ...bwb
    0,     // b..bwb
    4,     // w..bwb
    0,     // .b.bwb
    0,     // bb.bwb
    -51,   // wb.bwb
    -97,   // .w.bwb
    -11,   // bw.bwb
    -16,   // ww.bwb
    -2,    // ..bbwb
    -132,  // b.bbwb
    -49,   // w.bbwb
    -167,  // .bbbwb
    -73,   // bbbbwb
    -83,   // wbbbwb
    61,    // .wbbwb
    25,    // bwbbwb
    46,    // wwbbwb
    55,    // ..wbwb
    34,    // b.wbwb
    157,   // w.wbwb
    35,    // .bwbwb
    -41,   // bbwbwb
    0,     // wbwbwb
    39,    // .wwbwb
    11,    // bwwbwb
    91,    // wwwbwb
    -21,   // ...wwb
    -71,   // b..wwb
    -53,   // w..wwb
    2,     // .b.wwb
    0,     // bb.wwb
    -79,   // wb.wwb
    -32,   // .w.wwb
    -101,  // bw.wwb
    -25,   // ww.wwb
    -77,   // ..bwwb
    -54,   // b.bwwb
    -13,   // w.bwwb
    9,     // .bbwwb
    -31,   // bbbwwb
    0,     // wbbwwb
    34,    // .wbwwb
    11,    // bwbwwb
    -84,   // wwbwwb
    27,    // ..wwwb
    49,    // b.wwwb
    -75,   // w.wwwb
    77,    // .bwwwb
    113,   // bbwwwb
    83,    // wbwwwb
    -103,  // .wwwwb
    -73,   // bwwwwb
    68,    // wwwwwb
    11,    // .....w
    0,     // b....w
    71,    // w....w
    61,    // .b...w
    20,    // bb...w
    -123,  // wb...w
    0,     // .w...w
    -107,  // bw...w
    26,    // ww...w
    -158,  // ..b..w
    -9,    // b.b..w
    -58,   // w.b..w
    8,     // .bb..w
    -16,   // bbb..w
    71,    // wbb..w
    36,    // .wb..w
    4,     // bwb..w
    1,     // wwb..w
    5,     // ..w..w
    -65,   // b.w..w
    59,    // w.w..w
    26,    // .bw..w
    -31,   // bbw..w
    0,     // wbw..w
    -105,  // .ww..w
    -53,   // bww..w
    -68,   // www..w
    71,    // ...b.w
    65,    // b..b.w
    -58,   // w..b.w
    -13,   // .b.b.w
    -21,   // bb.b.w
    23,    // wb.b.w
    55,    // .w.b.w
    0,     // bw.b.w
    0,     // ww.b.w
    65,    // ..bb.w
    0,     // b.bb.w
    -21,   // w.bb.w
    9,     // .bbb.w
    -39,   // bbbb.w
    -49,   // wbbb.w
    -158,  // .wbb.w
    -49,   // bwbb.w
    75,    // wwbb.w
    13,    // ..wb.w
    0,     // b.wb.w
    -30,   // w.wb.w
    18,    // .bwb.w
    50,    // bbwb.w
    -34,   // wbwb.w
    -2,    // .wwb.w
    -13,   // bwwb.w
    -14,   // wwwb.w
    -38,   // ...w.w
    9,     // b..w.w
    59,    // w..w.w
    -23,   // .b.w.w
    -33,   // bb.w.w
    79,    // wb.w.w
    0,     // .w.w.w
    -43,   // bw.w.w
    19,    // ww.w.w
    -103,  // ..bw.w
    0,     // b.bw.w
    -30,   // w.bw.w
    0,     // .bbw.w
    22,    // bbbw.w
    54,    // wbbw.w
    7,     // .wbw.w
    157,   // bwbw.w
    10,    // wwbw.w
    -101,  // ..ww.w
    0,     // b.ww.w
    -50,   // w.ww.w
    93,    // .bww.w
    -39,   // bbww.w
    132,   // wbww.w
    16,    // .www.w
    -75,   // bwww.w
    42,    // wwww.w
    0,     // ....bw
    107,   // b...bw
    -123,  // w...bw
    55,    // .b..bw
    44,    // bb..bw
    51,    // wb..bw
    -19,   // .w..bw
    0,     // bw..bw
    -108,  // ww..bw
    -6,    // ..b.bw
    43,    // b.b.bw
    23,    // w.b.bw
    -64,   // .bb.bw
    -32,   // bbb.bw
    101,   // wbb.bw
    31,    // .wb.bw
    -51,   // bwb.bw
    75,    // wwb.bw
    -1,    // ..w.bw
    0,     // b.w.bw
    79,    // w.w.bw
    -47,   // .bw.bw
    -102,  // bbw.bw
    11,    // wbw.bw
    0,     // .ww.bw
    -79,   // bww.bw
    40,    // www.bw
    21,    // ...bbw
    53,    // b..bbw
    71,    // w..bbw
    32,    // .b.bbw
    25,    // bb.bbw
    101,   // wb.bbw
    -2,    // .w.bbw
    79,    // bw.bbw
    0,     // ww.bbw
    -27,   // ..bbbw
    75,    // b.bbbw
    -49,   // w.bbbw
    103,   // .bbbbw
    -68,   // bbbbbw
    73,    // wbbbbw
    -77,   // .wbbbw
    -83,   // bwbbbw
    -113,  // wwbbbw
    77,    // ..wbbw
    13,    // b.wbbw
    54,    // w.wbbw
    -34,   // .bwbbw
    84,    // bbwbbw
    -11,   // wbwbbw
    -9,    // .wwbbw
    0,     // bwwbbw
    31,    // wwwbbw
    19,    // ...wbw
    -4,    // b..wbw
    0,     // w..wbw
    97,    // .b.wbw
    16,    // bb.wbw
    11,    // wb.wbw
    0,     // .w.wbw
    51,    // bw.wbw
    0,     // ww.wbw
    -55,   // ..bwbw
    -157,  // b.bwbw
    -34,   // w.bwbw
    -39,   // .bbwbw
    -91,   // bbbwbw
    -11,   // wbbwbw
    -35,   // .wbwbw
    0,     // bwbwbw
    41,    // wwbwbw
    2,     // ..wwbw
    49,    // b.wwbw
    132,   // w.wwbw
    -61,   // .bwwbw
    -46,   // bbwwbw
    -25,   // wbwwbw
    167,   // .wwwbw
    83,    // bwwwbw
    73,    // wwwwbw
    -23,   // ....ww
    -20,   // b...ww
    26,    // w...ww
    -69,   // .b..ww
    0,     // bb..ww
    -108,  // wb..ww
    -8,    // .w..ww
    -44,   // bw..ww
    39,    // ww..ww
    -77,   // ..b.ww
    33,    // b.b.ww
    0,     // w.b.ww
    9,     // .bb.ww
    0,     // bbb.ww
    0,     // wbb.ww
    -66,   // .wb.ww
    -16,   // bwb.ww
    65,    // wwb.ww
    18,    // ..w.ww
    21,    // b.w.ww
    19,    // w.w.ww
    -67,   // .bw.ww
    39,    // bbw.ww
    0,     // wbw.ww
    35,    // .ww.ww
    -25,   // bww.ww
    60,    // www.ww
    0,     // ...bww
    31,    // b..bww
    1,     // w..bww
    -13,   // .b.bww
    -39,   // bb.bww
    75,    // wb.bww
    23,    // .w.bww
    102,   // bw.bww
    65,    // ww.bww
    12,    // ..bbww
    39,    // b.bbww
    75,    // w.bbww
    -108,  // .bbbww
    -21,   // bbbbww
    -113,  // wbbbww
    17,    // .wbbww
    46,    // bwbbww
    70,    // wwbbww
    -72,   // ..wbww
    -50,   // b.wbww
    10,    // w.wbww
    48,    // .bwbww
    0,     // bbwbww
    41,    // wbwbww
    0,     // .wwbww
    -84,   // bwwbww
    50,    // wwwbww
    -148,  // ...www
    16,    // b..www
    -68,   // w..www
    -22,   // .b.www
    0,     // bb.www
    40,    // wb.www
    -107,  // .w.www
    32,    // bw.www
    60,    // ww.www
    -19,   // ..bwww
    -22,   // b.bwww
    -14,   // w.bwww
    -27,   // .bbwww
    0,     // bbbwww
    31,    // wbbwww
    -23,   // .wbwww
    91,    // bwbwww
    50,    // wwbwww
    -84,   // ..wwww
    39,    // b.wwww
    42,    // w.wwww
    0,     // .bwwww
    21,    // bbwwww
    73,    // wbwwww
    69,    // .wwwww
    68,    // bwwwww
    -6,    // wwwwww
    187,   // ccc
    88,    // cc
    113,   // c
    14,    // ttt
    0,     // tt
    204,   // t
    79,    // ct
    72,    // cct
    107,   // ctt
]
