vec![
    0,     // .......
    7,     // b......
    -7,    // w......
    0,     // .b.....
    35,    // bb.....
    -3,    // wb.....
    0,     // .w.....
    3,     // bw.....
    -35,   // ww.....
    0,     // ..b....
    0,     // b.b....
    7,     // w.b....
    0,     // .bb....
    0,     // bbb....
    0,     // wbb....
    0,     // .wb....
    0,     // bwb....
    0,     // wwb....
    0,     // ..w....
    -7,    // b.w....
    0,     // w.w....
    0,     // .bw....
    0,     // bbw....
    0,     // wbw....
    0,     // .ww....
    0,     // bww....
    0,     // www....
    0,     // ...b...
    0,     // b..b...
    16,    // w..b...
    0,     // .b.b...
    37,    // bb.b...
    0,     // wb.b...
    0,     // .w.b...
    -84,   // bw.b...
    27,    // ww.b...
    0,     // ..bb...
    25,    // b.bb...
    8,     // w.bb...
    0,     // .bbb...
    0,     // bbbb...
    0,     // wbbb...
    0,     // .wbb...
    0,     // bwbb...
    -3,    // wwbb...
    -6,    // ..wb...
    0,     // b.wb...
    1,     // w.wb...
    -5,    // .bwb...
    0,     // bbwb...
    -11,   // wbwb...
    0,     // .wwb...
    0,     // bwwb...
    0,     // wwwb...
    0,     // ...w...
    -16,   // b..w...
    0,     // w..w...
    0,     // .b.w...
    -27,   // bb.w...
    84,    // wb.w...
    0,     // .w.w...
    0,     // bw.w...
    -37,   // ww.w...
    6,     // ..bw...
    -1,    // b.bw...
    0,     // w.bw...
    0,     // .bbw...
    0,     // bbbw...
    0,     // wbbw...
    5,     // .wbw...
    11,    // bwbw...
    0,     // wwbw...
    0,     // ..ww...
    -8,    // b.ww...
    -25,   // w.ww...
    0,     // .bww...
    3,     // bbww...
    0,     // wbww...
    0,     // .www...
    0,     // bwww...
    0,     // wwww...
    0,     // ....b..
    0,     // b...b..
    -16,   // w...b..
    0,     // .b..b..
    0,     // bb..b..
    5,     // wb..b..
    0,     // .w..b..
    0,     // bw..b..
    2,     // ww..b..
    0,     // ..b.b..
    0,     // b.b.b..
    0,     // w.b.b..
    9,     // .bb.b..
    -3,    // bbb.b..
    0,     // wbb.b..
    0,     // .wb.b..
    15,    // bwb.b..
    0,     // wwb.b..
    0,     // ..w.b..
    0,     // b.w.b..
    0,     // w.w.b..
    0,     // .bw.b..
    0,     // bbw.b..
    0,     // wbw.b..
    -2,    // .ww.b..
    -42,   // bww.b..
    0,     // www.b..
    0,     // ...bb..
    0,     // b..bb..
    29,    // w..bb..
    3,     // .b.bb..
    0,     // bb.bb..
    21,    // wb.bb..
    -16,   // .w.bb..
    -53,   // bw.bb..
    -13,   // ww.bb..
    -50,   // ..bbb..
    0,     // b.bbb..
    0,     // w.bbb..
    0,     // .bbbb..
    17,    // bbbbb..
    14,    // wbbbb..
    0,     // .wbbb..
    1,     // bwbbb..
    19,    // wwbbb..
    11,    // ..wbb..
    24,    // b.wbb..
    -25,   // w.wbb..
    -25,   // .bwbb..
    18,    // bbwbb..
    0,     // wbwbb..
    0,     // .wwbb..
    11,    // bwwbb..
    0,     // wwwbb..
    6,     // ...wb..
    -13,   // b..wb..
    0,     // w..wb..
    40,    // .b.wb..
    -21,   // bb.wb..
    29,    // wb.wb..
    4,     // .w.wb..
    0,     // bw.wb..
    0,     // ww.wb..
    0,     // ..bwb..
    -17,   // b.bwb..
    0,     // w.bwb..
    10,    // .bbwb..
    -57,   // bbbwb..
    0,     // wbbwb..
    40,    // .wbwb..
    -30,   // bwbwb..
    0,     // wwbwb..
    -11,   // ..wwb..
    12,    // b.wwb..
    0,     // w.wwb..
    0,     // .bwwb..
    31,    // bbwwb..
    -31,   // wbwwb..
    -5,    // .wwwb..
    0,     // bwwwb..
    2,     // wwwwb..
    0,     // ....w..
    16,    // b...w..
    0,     // w...w..
    0,     // .b..w..
    -2,    // bb..w..
    0,     // wb..w..
    0,     // .w..w..
    -5,    // bw..w..
    0,     // ww..w..
    0,     // ..b.w..
    0,     // b.b.w..
    0,     // w.b.w..
    2,     // .bb.w..
    0,     // bbb.w..
    42,    // wbb.w..
    0,     // .wb.w..
    0,     // bwb.w..
    0,     // wwb.w..
    0,     // ..w.w..
    0,     // b.w.w..
    0,     // w.w.w..
    0,     // .bw.w..
    0,     // bbw.w..
    -15,   // wbw.w..
    -9,    // .ww.w..
    0,     // bww.w..
    3,     // www.w..
    -6,    // ...bw..
    0,     // b..bw..
    13,    // w..bw..
    -4,    // .b.bw..
    0,     // bb.bw..
    0,     // wb.bw..
    -40,   // .w.bw..
    -29,   // bw.bw..
    21,    // ww.bw..
    11,    // ..bbw..
    0,     // b.bbw..
    -12,   // w.bbw..
    5,     // .bbbw..
    -2,    // bbbbw..
    0,     // wbbbw..
    0,     // .wbbw..
    31,    // bwbbw..
    -31,   // wwbbw..
    0,     // ..wbw..
    0,     // b.wbw..
    17,    // w.wbw..
    -40,   // .bwbw..
    0,     // bbwbw..
    30,    // wbwbw..
    -10,   // .wwbw..
    0,     // bwwbw..
    57,    // wwwbw..
    0,     // ...ww..
    -29,   // b..ww..
    0,     // w..ww..
    16,    // .b.ww..
    13,    // bb.ww..
    53,    // wb.ww..
    -3,    // .w.ww..
    -21,   // bw.ww..
    0,     // ww.ww..
    -11,   // ..bww..
    25,    // b.bww..
    -24,   // w.bww..
    0,     // .bbww..
    0,     // bbbww..
    -11,   // wbbww..
    25,    // .wbww..
    0,     // bwbww..
    -18,   // wwbww..
    50,    // ..www..
    0,     // b.www..
    0,     // w.www..
    0,     // .bwww..
    -19,   // bbwww..
    -1,    // wbwww..
    0,     // .wwww..
    -14,   // bwwww..
    -17,   // wwwww..
    0,     // .....b.
    0,     // b....b.
    44,    // w....b.
    -23,   // .b...b.
    -30,   // bb...b.
    0,     // wb...b.
    0,     // .w...b.
    0,     // bw...b.
    0,     // ww...b.
    0,     // ..b..b.
    0,     // b.b..b.
    19,    // w.b..b.
    0,     // .bb..b.
    0,     // bbb..b.
    0,     // wbb..b.
    0,     // .wb..b.
    0,     // bwb..b.
    0,     // wwb..b.
    0,     // ..w..b.
    0,     // b.w..b.
    -52,   // w.w..b.
    0,     // .bw..b.
    0,     // bbw..b.
    0,     // wbw..b.
    -54,   // .ww..b.
    -6,    // bww..b.
    30,    // www..b.
    0,     // ...b.b.
    0,     // b..b.b.
    0,     // w..b.b.
    0,     // .b.b.b.
    -27,   // bb.b.b.
    -23,   // wb.b.b.
    -31,   // .w.b.b.
    0,     // bw.b.b.
    0,     // ww.b.b.
    3,     // ..bb.b.
    -39,   // b.bb.b.
    16,    // w.bb.b.
    29,    // .bbb.b.
    0,     // bbbb.b.
    27,    // wbbb.b.
    0,     // .wbb.b.
    3,     // bwbb.b.
    13,    // wwbb.b.
    -4,    // ..wb.b.
    27,    // b.wb.b.
    24,    // w.wb.b.
    0,     // .bwb.b.
    15,    // bbwb.b.
    0,     // wbwb.b.
    37,    // .wwb.b.
    0,     // bwwb.b.
    0,     // wwwb.b.
    0,     // ...w.b.
    0,     // b..w.b.
    0,     // w..w.b.
    0,     // .b.w.b.
    0,     // bb.w.b.
    -45,   // wb.w.b.
    31,    // .w.w.b.
    0,     // bw.w.b.
    0,     // ww.w.b.
    40,    // ..bw.b.
    0,     // b.bw.b.
    -48,   // w.bw.b.
    0,     // .bbw.b.
    27,    // bbbw.b.
    27,    // wbbw.b.
    0,     // .wbw.b.
    0,     // bwbw.b.
    0,     // wwbw.b.
    16,    // ..ww.b.
    0,     // b.ww.b.
    7,     // w.ww.b.
    -28,   // .bww.b.
    8,     // bbww.b.
    0,     // wbww.b.
    -28,   // .www.b.
    -52,   // bwww.b.
    24,    // wwww.b.
    0,     // ....bb.
    -6,    // b...bb.
    0,     // w...bb.
    0,     // .b..bb.
    0,     // bb..bb.
    0,     // wb..bb.
    54,    // .w..bb.
    0,     // bw..bb.
    -20,   // ww..bb.
    9,     // ..b.bb.
    0,     // b.b.bb.
    0,     // w.b.bb.
    -9,    // .bb.bb.
    -22,   // bbb.bb.
    0,     // wbb.bb.
    13,    // .wb.bb.
    -1,    // bwb.bb.
    0,     // wwb.bb.
    2,     // ..w.bb.
    14,    // b.w.bb.
    -5,    // w.w.bb.
    17,    // .bw.bb.
    -13,   // bbw.bb.
    0,     // wbw.bb.
    0,     // .ww.bb.
    0,     // bww.bb.
    -7,    // www.bb.
    0,     // ...bbb.
    10,    // b..bbb.
    26,    // w..bbb.
    29,    // .b.bbb.
    -30,   // bb.bbb.
    -26,   // wb.bbb.
    28,    // .w.bbb.
    73,    // bw.bbb.
    30,    // ww.bbb.
    0,     // ..bbbb.
    0,     // b.bbbb.
    30,    // w.bbbb.
    0,     // .bbbbb.
    9,     // bbbbbb.
    4,     // wbbbbb.
    -27,   // .wbbbb.
    22,    // bwbbbb.
    13,    // wwbbbb.
    5,     // ..wbbb.
    -26,   // b.wbbb.
    23,    // w.wbbb.
    16,    // .bwbbb.
    0,     // bbwbbb.
    10,    // wbwbbb.
    0,     // .wwbbb.
    -28,   // bwwbbb.
    44,    // wwwbbb.
    0,     // ...wbb.
    -29,   // b..wbb.
    0,     // w..wbb.
    0,     // .b.wbb.
    13,    // bb.wbb.
    0,     // wb.wbb.
    -37,   // .w.wbb.
    -19,   // bw.wbb.
    0,     // ww.wbb.
    10,    // ..bwbb.
    17,    // b.bwbb.
    11,    // w.bwbb.
    0,     // .bbwbb.
    10,    // bbbwbb.
    0,     // wbbwbb.
    26,    // .wbwbb.
    0,     // bwbwbb.
    23,    // wwbwbb.
    0,     // ..wwbb.
    32,    // b.wwbb.
    0,     // w.wwbb.
    -22,   // .bwwbb.
    26,    // bbwwbb.
    -15,   // wbwwbb.
    0,     // .wwwbb.
    0,     // bwwwbb.
    0,     // wwwwbb.
    0,     // ....wb.
    -2,    // b...wb.
    17,    // w...wb.
    0,     // .b..wb.
    0,     // bb..wb.
    0,     // wb..wb.
    0,     // .w..wb.
    17,    // bw..wb.
    0,     // ww..wb.
    0,     // ..b.wb.
    16,    // b.b.wb.
    -8,    // w.b.wb.
    17,    // .bb.wb.
    21,    // bbb.wb.
    -25,   // wbb.wb.
    0,     // .wb.wb.
    -25,   // bwb.wb.
    0,     // wwb.wb.
    0,     // ..w.wb.
    -22,   // b.w.wb.
    -14,   // w.w.wb.
    -6,    // .bw.wb.
    -3,    // bbw.wb.
    19,    // wbw.wb.
    -13,   // .ww.wb.
    -22,   // bww.wb.
    0,     // www.wb.
    -5,    // ...bwb.
    0,     // b..bwb.
    26,    // w..bwb.
    0,     // .b.bwb.
    52,    // bb.bwb.
    16,    // wb.bwb.
    0,     // .w.bwb.
    0,     // bw.bwb.
    0,     // ww.bwb.
    -25,   // ..bbwb.
    0,     // b.bbwb.
    -27,   // w.bbwb.
    16,    // .bbbwb.
    31,    // bbbbwb.
    -15,   // wbbbwb.
    0,     // .wbbwb.
    0,     // bwbbwb.
    0,     // wwbbwb.
    -40,   // ..wbwb.
    -20,   // b.wbwb.
    17,    // w.wbwb.
    43,    // .bwbwb.
    -32,   // bbwbwb.
    0,     // wbwbwb.
    -26,   // .wwbwb.
    0,     // bwwbwb.
    0,     // wwwbwb.
    0,     // ...wwb.
    19,    // b..wwb.
    0,     // w..wwb.
    -28,   // .b.wwb.
    0,     // bb.wwb.
    -7,    // wb.wwb.
    0,     // .w.wwb.
    31,    // bw.wwb.
    0,     // ww.wwb.
    0,     // ..bwwb.
    0,     // b.bwwb.
    52,    // w.bwwb.
    -22,   // .bbwwb.
    10,    // bbbwwb.
    -44,   // wbbwwb.
    0,     // .wbwwb.
    -24,   // bwbwwb.
    0,     // wwbwwb.
    0,     // ..wwwb.
    11,    // b.wwwb.
    -14,   // w.wwwb.
    0,     // .bwwwb.
    -10,   // bbwwwb.
    0,     // wbwwwb.
    27,    // .wwwwb.
    0,     // bwwwwb.
    0,     // wwwwwb.
    0,     // .....w.
    -44,   // b....w.
    0,     // w....w.
    0,     // .b...w.
    0,     // bb...w.
    0,     // wb...w.
    23,    // .w...w.
    0,     // bw...w.
    30,    // ww...w.
    0,     // ..b..w.
    52,    // b.b..w.
    0,     // w.b..w.
    54,    // .bb..w.
    -30,   // bbb..w.
    6,     // wbb..w.
    0,     // .wb..w.
    0,     // bwb..w.
    0,     // wwb..w.
    0,     // ..w..w.
    -19,   // b.w..w.
    0,     // w.w..w.
    0,     // .bw..w.
    0,     // bbw..w.
    0,     // wbw..w.
    0,     // .ww..w.
    0,     // bww..w.
    0,     // www..w.
    0,     // ...b.w.
    0,     // b..b.w.
    0,     // w..b.w.
    -31,   // .b.b.w.
    0,     // bb.b.w.
    0,     // wb.b.w.
    0,     // .w.b.w.
    45,    // bw.b.w.
    0,     // ww.b.w.
    -16,   // ..bb.w.
    -7,    // b.bb.w.
    0,     // w.bb.w.
    28,    // .bbb.w.
    -24,   // bbbb.w.
    52,    // wbbb.w.
    28,    // .wbb.w.
    0,     // bwbb.w.
    -8,    // wwbb.w.
    -40,   // ..wb.w.
    48,    // b.wb.w.
    0,     // w.wb.w.
    0,     // .bwb.w.
    0,     // bbwb.w.
    0,     // wbwb.w.
    0,     // .wwb.w.
    -27,   // bwwb.w.
    -27,   // wwwb.w.
    0,     // ...w.w.
    0,     // b..w.w.
    0,     // w..w.w.
    31,    // .b.w.w.
    0,     // bb.w.w.
    0,     // wb.w.w.
    0,     // .w.w.w.
    23,    // bw.w.w.
    27,    // ww.w.w.
    4,     // ..bw.w.
    -24,   // b.bw.w.
    -27,   // w.bw.w.
    -37,   // .bbw.w.
    0,     // bbbw.w.
    0,     // wbbw.w.
    0,     // .wbw.w.
    0,     // bwbw.w.
    -15,   // wwbw.w.
    -3,    // ..ww.w.
    -16,   // b.ww.w.
    39,    // w.ww.w.
    0,     // .bww.w.
    -13,   // bbww.w.
    -3,    // wbww.w.
    -29,   // .www.w.
    -27,   // bwww.w.
    0,     // wwww.w.
    0,     // ....bw.
    -17,   // b...bw.
    2,     // w...bw.
    0,     // .b..bw.
    0,     // bb..bw.
    -17,   // wb..bw.
    0,     // .w..bw.
    0,     // bw..bw.
    0,     // ww..bw.
    0,     // ..b.bw.
    14,    // b.b.bw.
    22,    // w.b.bw.
    13,    // .bb.bw.
    0,     // bbb.bw.
    22,    // wbb.bw.
    6,     // .wb.bw.
    -19,   // bwb.bw.
    3,     // wwb.bw.
    0,     // ..w.bw.
    8,     // b.w.bw.
    -16,   // w.w.bw.
    0,     // .bw.bw.
    0,     // bbw.bw.
    25,    // wbw.bw.
    -17,   // .ww.bw.
    25,    // bww.bw.
    -21,   // www.bw.
    0,     // ...bbw.
    0,     // b..bbw.
    -19,   // w..bbw.
    0,     // .b.bbw.
    0,     // bb.bbw.
    -31,   // wb.bbw.
    28,    // .w.bbw.
    7,     // bw.bbw.
    0,     // ww.bbw.
    0,     // ..bbbw.
    14,    // b.bbbw.
    -11,   // w.bbbw.
    -27,   // .bbbbw.
    0,     // bbbbbw.
    0,     // wbbbbw.
    0,     // .wbbbw.
    0,     // bwbbbw.
    10,    // wwbbbw.
    0,     // ..wbbw.
    -52,   // b.wbbw.
    0,     // w.wbbw.
    0,     // .bwbbw.
    0,     // bbwbbw.
    24,    // wbwbbw.
    22,    // .wwbbw.
    44,    // bwwbbw.
    -10,   // wwwbbw.
    5,     // ...wbw.
    -26,   // b..wbw.
    0,     // w..wbw.
    0,     // .b.wbw.
    0,     // bb.wbw.
    0,     // wb.wbw.
    0,     // .w.wbw.
    -16,   // bw.wbw.
    -52,   // ww.wbw.
    40,    // ..bwbw.
    -17,   // b.bwbw.
    20,    // w.bwbw.
    26,    // .bbwbw.
    0,     // bbbwbw.
    0,     // wbbwbw.
    -43,   // .wbwbw.
    0,     // bwbwbw.
    32,    // wwbwbw.
    25,    // ..wwbw.
    27,    // b.wwbw.
    0,     // w.wwbw.
    0,     // .bwwbw.
    0,     // bbwwbw.
    0,     // wbwwbw.
    -16,   // .wwwbw.
    15,    // bwwwbw.
    -31,   // wwwwbw.
    0,     // ....ww.
    0,     // b...ww.
    6,     // w...ww.
    -54,   // .b..ww.
    20,    // bb..ww.
    0,     // wb..ww.
    0,     // .w..ww.
    0,     // bw..ww.
    0,     // ww..ww.
    -2,    // ..b.ww.
    5,     // b.b.ww.
    -14,   // w.b.ww.
    0,     // .bb.ww.
    7,     // bbb.ww.
    0,     // wbb.ww.
    -17,   // .wb.ww.
    0,     // bwb.ww.
    13,    // wwb.ww.
    -9,    // ..w.ww.
    0,     // b.w.ww.
    0,     // w.w.ww.
    -13,   // .bw.ww.
    0,     // bbw.ww.
    1,     // wbw.ww.
    9,     // .ww.ww.
    0,     // bww.ww.
    22,    // www.ww.
    0,     // ...bww.
    0,     // b..bww.
    29,    // w..bww.
    37,    // .b.bww.
    0,     // bb.bww.
    19,    // wb.bww.
    0,     // .w.bww.
    0,     // bw.bww.
    -13,   // ww.bww.
    0,     // ..bbww.
    0,     // b.bbww.
    -32,   // w.bbww.
    0,     // .bbbww.
    0,     // bbbbww.
    0,     // wbbbww.
    22,    // .wbbww.
    15,    // bwbbww.
    -26,   // wwbbww.
    -10,   // ..wbww.
    -11,   // b.wbww.
    -17,   // w.wbww.
    -26,   // .bwbww.
    -23,   // bbwbww.
    0,     // wbwbww.
    0,     // .wwbww.
    0,     // bwwbww.
    -10,   // wwwbww.
    0,     // ...www.
    -26,   // b..www.
    -10,   // w..www.
    -28,   // .b.www.
    -30,   // bb.www.
    -73,   // wb.www.
    -29,   // .w.www.
    26,    // bw.www.
    30,    // ww.www.
    -5,    // ..bwww.
    -23,   // b.bwww.
    26,    // w.bwww.
    0,     // .bbwww.
    -44,   // bbbwww.
    28,    // wbbwww.
    -16,   // .wbwww.
    -10,   // bwbwww.
    0,     // wwbwww.
    0,     // ..wwww.
    -30,   // b.wwww.
    0,     // w.wwww.
    27,    // .bwwww.
    -13,   // bbwwww.
    -22,   // wbwwww.
    0,     // .wwwww.
    -4,    // bwwwww.
    -9,    // wwwwww.
    7,     // ......b
    -17,   // b.....b
    0,     // w.....b
    0,     // .b....b
    -6,    // bb....b
    -9,    // wb....b
    -44,   // .w....b
    30,    // bw....b
    26,    // ww....b
    0,     // ..b...b
    -21,   // b.b...b
    15,    // w.b...b
    -6,    // .bb...b
    30,    // bbb...b
    -3,    // wbb...b
    -17,   // .wb...b
    -16,   // bwb...b
    0,     // wwb...b
    16,    // ..w...b
    -10,   // b.w...b
    30,    // w.w...b
    -2,    // .bw...b
    -21,   // bbw...b
    0,     // wbw...b
    0,     // .ww...b
    -7,    // bww...b
    -24,   // www...b
    0,     // ...b..b
    30,    // b..b..b
    -34,   // w..b..b
    0,     // .b.b..b
    0,     // bb.b..b
    0,     // wb.b..b
    0,     // .w.b..b
    0,     // bw.b..b
    0,     // ww.b..b
    0,     // ..bb..b
    0,     // b.bb..b
    37,    // w.bb..b
    10,    // .bbb..b
    0,     // bbbb..b
    0,     // wbbb..b
    0,     // .wbb..b
    0,     // bwbb..b
    45,    // wwbb..b
    0,     // ..wb..b
    7,     // b.wb..b
    0,     // w.wb..b
    0,     // .bwb..b
    17,    // bbwb..b
    -32,   // wbwb..b
    0,     // .wwb..b
    0,     // bwwb..b
    0,     // wwwb..b
    -16,   // ...w..b
    -14,   // b..w..b
    34,    // w..w..b
    0,     // .b.w..b
    0,     // bb.w..b
    14,    // wb.w..b
    0,     // .w.w..b
    0,     // bw.w..b
    0,     // ww.w..b
    -13,   // ..bw..b
    0,     // b.bw..b
    -13,   // w.bw..b
    -29,   // .bbw..b
    -25,   // bbbw..b
    0,     // wbbw..b
    -26,   // .wbw..b
    0,     // bwbw..b
    1,     // wwbw..b
    -29,   // ..ww..b
    0,     // b.ww..b
    0,     // w.ww..b
    19,    // .bww..b
    0,     // bbww..b
    0,     // wbww..b
    -26,   // .www..b
    11,    // bwww..b
    0,     // wwww..b
    0,     // ....b.b
    -21,   // b...b.b
    -30,   // w...b.b
    0,     // .b..b.b
    -36,   // bb..b.b
    0,     // wb..b.b
    52,    // .w..b.b
    0,     // bw..b.b
    0,     // ww..b.b
    0,     // ..b.b.b
    0,     // b.b.b.b
    -3,    // w.b.b.b
    0,     // .bb.b.b
    24,    // bbb.b.b
    3,     // wbb.b.b
    14,    // .wb.b.b
    0,     // bwb.b.b
    0,     // wwb.b.b
    0,     // ..w.b.b
    20,    // b.w.b.b
    0,     // w.w.b.b
    16,    // .bw.b.b
    0,     // bbw.b.b
    -24,   // wbw.b.b
    5,     // .ww.b.b
    0,     // bww.b.b
    0,     // www.b.b
    25,    // ...bb.b
    0,     // b..bb.b
    0,     // w..bb.b
    -39,   // .b.bb.b
    -19,   // bb.bb.b
    13,    // wb.bb.b
    -7,    // .w.bb.b
    0,     // bw.bb.b
    2,     // ww.bb.b
    0,     // ..bbb.b
    0,     // b.bbb.b
    0,     // w.bbb.b
    0,     // .bbbb.b
    0,     // bbbbb.b
    0,     // wbbbb.b
    14,    // .wbbb.b
    0,     // bwbbb.b
    0,     // wwbbb.b
    0,     // ..wbb.b
    17,    // b.wbb.b
    0,     // w.wbb.b
    0,     // .bwbb.b
    0,     // bbwbb.b
    -14,   // wbwbb.b
    0,     // .wwbb.b
    13,    // bwwbb.b
    0,     // wwwbb.b
    -1,    // ...wb.b
    0,     // b..wb.b
    0,     // w..wb.b
    0,     // .b.wb.b
    19,    // bb.wb.b
    48,    // wb.wb.b
    -24,   // .w.wb.b
    0,     // bw.wb.b
    0,     // ww.wb.b
    -17,   // ..bwb.b
    -31,   // b.bwb.b
    0,     // w.bwb.b
    17,    // .bbwb.b
    -47,   // bbbwb.b
    -4,    // wbbwb.b
    -17,   // .wbwb.b
    0,     // bwbwb.b
    -11,   // wwbwb.b
    25,    // ..wwb.b
    -29,   // b.wwb.b
    0,     // w.wwb.b
    0,     // .bwwb.b
    0,     // bbwwb.b
    29,    // wbwwb.b
    -23,   // .wwwb.b
    0,     // bwwwb.b
    0,     // wwwwb.b
    -7,    // ....w.b
    -10,   // b...w.b
    -15,   // w...w.b
    0,     // .b..w.b
    -9,    // bb..w.b
    0,     // wb..w.b
    -19,   // .w..w.b
    11,    // bw..w.b
    -12,   // ww..w.b
    0,     // ..b.w.b
    20,    // b.b.w.b
    0,     // w.b.w.b
    14,    // .bb.w.b
    11,    // bbb.w.b
    5,     // wbb.w.b
    8,     // .wb.w.b
    -29,   // bwb.w.b
    0,     // wwb.w.b
    0,     // ..w.w.b
    0,     // b.w.w.b
    3,     // w.w.w.b
    -22,   // .bw.w.b
    -27,   // bbw.w.b
    26,    // wbw.w.b
    0,     // .ww.w.b
    0,     // bww.w.b
    -24,   // www.w.b
    0,     // ...bw.b
    7,     // b..bw.b
    13,    // w..bw.b
    27,    // .b.bw.b
    23,    // bb.bw.b
    -16,   // wb.bw.b
    48,    // .w.bw.b
    -32,   // bw.bw.b
    7,     // ww.bw.b
    24,    // ..bbw.b
    17,    // b.bbw.b
    0,     // w.bbw.b
    -26,   // .bbbw.b
    -28,   // bbbbw.b
    0,     // wbbbw.b
    -52,   // .wbbw.b
    0,     // bwbbw.b
    -25,   // wwbbw.b
    0,     // ..wbw.b
    -24,   // b.wbw.b
    0,     // w.wbw.b
    -20,   // .bwbw.b
    0,     // bbwbw.b
    0,     // wbwbw.b
    -11,   // .wwbw.b
    0,     // bwwbw.b
    -18,   // wwwbw.b
    -8,    // ...ww.b
    0,     // b..ww.b
    -37,   // w..ww.b
    0,     // .b.ww.b
    -5,    // bb.ww.b
    14,    // wb.ww.b
    -16,   // .w.ww.b
    -2,    // bw.ww.b
    -10,   // ww.ww.b
    12,    // ..bww.b
    -29,   // b.bww.b
    0,     // w.bww.b
    32,    // .bbww.b
    0,     // bbbww.b
    -30,   // wbbww.b
    27,    // .wbww.b
    0,     // bwbww.b
    -2,    // wwbww.b
    0,     // ..www.b
    -47,   // b.www.b
    0,     // w.www.b
    11,    // .bwww.b
    0,     // bbwww.b
    0,     // wbwww.b
    -30,   // .wwww.b
    0,     // bwwww.b
    -32,   // wwwww.b
    35,    // .....bb
    -6,    // b....bb
    -26,   // w....bb
    -30,   // .b...bb
    0,     // bb...bb
    -54,   // wb...bb
    0,     // .w...bb
    -16,   // bw...bb
    0,     // ww...bb
    0,     // ..b..bb
    -36,   // b.b..bb
    12,    // w.b..bb
    0,     // .bb..bb
    -23,   // bbb..bb
    0,     // wbb..bb
    0,     // .wb..bb
    0,     // bwb..bb
    -17,   // wwb..bb
    -2,    // ..w..bb
    -9,    // b.w..bb
    0,     // w.w..bb
    0,     // .bw..bb
    -9,    // bbw..bb
    -8,    // wbw..bb
    20,    // .ww..bb
    -5,    // bww..bb
    22,    // www..bb
    37,    // ...b.bb
    0,     // b..b.bb
    0,     // w..b.bb
    -27,   // .b.b.bb
    31,    // bb.b.bb
    -18,   // wb.b.bb
    0,     // .w.b.bb
    -4,    // bw.b.bb
    25,    // ww.b.bb
    0,     // ..bb.bb
    -19,   // b.bb.bb
    10,    // w.bb.bb
    -30,   // .bbb.bb
    -10,   // bbbb.bb
    0,     // wbbb.bb
    0,     // .wbb.bb
    0,     // bwbb.bb
    0,     // wwbb.bb
    0,     // ..wb.bb
    23,    // b.wb.bb
    0,     // w.wb.bb
    52,    // .bwb.bb
    -3,    // bbwb.bb
    13,    // wbwb.bb
    0,     // .wwb.bb
    -29,   // bwwb.bb
    8,     // wwwb.bb
    -27,   // ...w.bb
    0,     // b..w.bb
    0,     // w..w.bb
    0,     // .b.w.bb
    0,     // bb.w.bb
    0,     // wb.w.bb
    0,     // .w.w.bb
    -14,   // bw.w.bb
    -25,   // ww.w.bb
    -21,   // ..bw.bb
    19,    // b.bw.bb
    -7,    // w.bw.bb
    13,    // .bbw.bb
    6,     // bbbw.bb
    0,     // wbbw.bb
    0,     // .wbw.bb
    0,     // bwbw.bb
    0,     // wwbw.bb
    13,    // ..ww.bb
    -5,    // b.ww.bb
    -2,    // w.ww.bb
    0,     // .bww.bb
    0,     // bbww.bb
    18,    // wbww.bb
    -30,   // .www.bb
    0,     // bwww.bb
    -2,    // wwww.bb
    0,     // ....bbb
    30,    // b...bbb
    24,    // w...bbb
    0,     // .b..bbb
    -23,   // bb..bbb
    30,    // wb..bbb
    -30,   // .w..bbb
    0,     // bw..bbb
    -22,   // ww..bbb
    -3,    // ..b.bbb
    24,    // b.b.bbb
    24,    // w.b.bbb
    -22,   // .bb.bbb
    -29,   // bbb.bbb
    0,     // wbb.bbb
    0,     // .wb.bbb
    -14,   // bwb.bbb
    -1,    // wwb.bbb
    0,     // ..w.bbb
    11,    // b.w.bbb
    0,     // w.w.bbb
    21,    // .bw.bbb
    0,     // bbw.bbb
    14,    // wbw.bbb
    7,     // .ww.bbb
    7,     // bww.bbb
    0,     // www.bbb
    0,     // ...bbbb
    0,     // b..bbbb
    0,     // w..bbbb
    0,     // .b.bbbb
    -10,   // bb.bbbb
    0,     // wb.bbbb
    -24,   // .w.bbbb
    0,     // bw.bbbb
    2,     // ww.bbbb
    17,    // ..bbbbb
    0,     // b.bbbbb
    32,    // w.bbbbb
    9,     // .bbbbbb
    0,     // bbbbbbb
    0,     // wbbbbbb
    0,     // .wbbbbb
    0,     // bwbbbbb
    31,    // wwbbbbb
    -2,    // ..wbbbb
    -28,   // b.wbbbb
    0,     // w.wbbbb
    31,    // .bwbbbb
    3,     // bbwbbbb
    48,    // wbwbbbb
    0,     // .wwbbbb
    0,     // bwwbbbb
    0,     // wwwbbbb
    0,     // ...wbbb
    -25,   // b..wbbb
    0,     // w..wbbb
    27,    // .b.wbbb
    6,     // bb.wbbb
    9,     // wb.wbbb
    0,     // .w.wbbb
    -21,   // bw.wbbb
    -8,    // ww.wbbb
    -57,   // ..bwbbb
    -47,   // b.bwbbb
    18,    // w.bwbbb
    10,    // .bbwbbb
    -1,    // bbbwbbb
    0,     // wbbwbbb
    0,     // .wbwbbb
    12,    // bwbwbbb
    25,    // wwbwbbb
    0,     // ..wwbbb
    0,     // b.wwbbb
    0,     // w.wwbbb
    10,    // .bwwbbb
    0,     // bbwwbbb
    4,     // wbwwbbb
    -44,   // .wwwbbb
    0,     // bwwwbbb
    0,     // wwwwbbb
    0,     // ....wbb
    -21,   // b...wbb
    0,     // w...wbb
    0,     // .b..wbb
    -9,    // bb..wbb
    -6,    // wb..wbb
    0,     // .w..wbb
    24,    // bw..wbb
    17,    // ww..wbb
    0,     // ..b.wbb
    0,     // b.b.wbb
    0,     // w.b.wbb
    -13,   // .bb.wbb
    0,     // bbb.wbb
    0,     // wbb.wbb
    0,     // .wb.wbb
    5,     // bwb.wbb
    0,     // wwb.wbb
    0,     // ..w.wbb
    -27,   // b.w.wbb
    0,     // w.w.wbb
    -3,    // .bw.wbb
    -25,   // bbw.wbb
    0,     // wbw.wbb
    0,     // .ww.wbb
    0,     // bww.wbb
    1,     // www.wbb
    0,     // ...bwbb
    17,    // b..bwbb
    -1,    // w..bwbb
    15,    // .b.bwbb
    -3,    // bb.bwbb
    0,     // wb.bwbb
    0,     // .w.bwbb
    0,     // bw.bwbb
    0,     // ww.bwbb
    18,    // ..bbwbb
    0,     // b.bbwbb
    2,     // w.bbwbb
    0,     // .bbbwbb
    3,     // bbbbwbb
    -28,   // wbbbwbb
    0,     // .wbbwbb
    -32,   // bwbbwbb
    0,     // wwbbwbb
    0,     // ..wbwbb
    0,     // b.wbwbb
    11,    // w.wbwbb
    -32,   // .bwbwbb
    -32,   // bbwbwbb
    21,    // wbwbwbb
    -23,   // .wwbwbb
    18,    // bwwbwbb
    -25,   // wwwbwbb
    3,     // ...wwbb
    0,     // b..wwbb
    -45,   // w..wwbb
    8,     // .b.wwbb
    0,     // bb.wwbb
    -18,   // wb.wwbb
    -13,   // .w.wwbb
    13,    // bw.wwbb
    0,     // ww.wwbb
    31,    // ..bwwbb
    0,     // b.bwwbb
    25,    // w.bwwbb
    26,    // .bbwwbb
    0,     // bbbwwbb
    -19,   // wbbwwbb
    0,     // .wbwwbb
    2,     // bwbwwbb
    0,     // wwbwwbb
    -19,   // ..wwwbb
    0,     // b.wwwbb
    0,     // w.wwwbb
    -10,   // .bwwwbb
    -18,   // bbwwwbb
    9,     // wbwwwbb
    -13,   // .wwwwbb
    3,     // bwwwwbb
    -31,   // wwwwwbb
    3,     // .....wb
    30,    // b....wb
    9,     // w....wb
    0,     // .b...wb
    -16,   // bb...wb
    0,     // wb...wb
    0,     // .w...wb
    0,     // bw...wb
    54,    // ww...wb
    0,     // ..b..wb
    0,     // b.b..wb
    0,     // w.b..wb
    0,     // .bb..wb
    0,     // bbb..wb
    -10,   // wbb..wb
    0,     // .wb..wb
    -8,    // bwb..wb
    6,     // wwb..wb
    -5,    // ..w..wb
    11,    // b.w..wb
    0,     // w.w..wb
    17,    // .bw..wb
    24,    // bbw..wb
    20,    // wbw..wb
    0,     // .ww..wb
    0,     // bww..wb
    -30,   // www..wb
    -84,   // ...b.wb
    0,     // b..b.wb
    -14,   // w..b.wb
    0,     // .b.b.wb
    -4,    // bb.b.wb
    11,    // wb.b.wb
    45,    // .w.b.wb
    0,     // bw.b.wb
    0,     // ww.b.wb
    -53,   // ..bb.wb
    0,     // b.bb.wb
    -14,   // w.bb.wb
    73,    // .bbb.wb
    0,     // bbbb.wb
    0,     // wbbb.wb
    7,     // .wbb.wb
    -43,   // bwbb.wb
    18,    // wwbb.wb
    -29,   // ..wb.wb
    -32,   // b.wb.wb
    -48,   // w.wb.wb
    0,     // .bwb.wb
    0,     // bbwb.wb
    0,     // wbwb.wb
    0,     // .wwb.wb
    0,     // bwwb.wb
    -9,    // wwwb.wb
    0,     // ...w.wb
    0,     // b..w.wb
    0,     // w..w.wb
    0,     // .b.w.wb
    -14,   // bb.w.wb
    -11,   // wb.w.wb
    23,    // .w.w.wb
    0,     // bw.w.wb
    18,    // ww.w.wb
    0,     // ..bw.wb
    0,     // b.bw.wb
    16,    // w.bw.wb
    -19,   // .bbw.wb
    -21,   // bbbw.wb
    -9,    // wbbw.wb
    -16,   // .wbw.wb
    0,     // bwbw.wb
    0,     // wwbw.wb
    -21,   // ..ww.wb
    -2,    // b.ww.wb
    -13,   // w.ww.wb
    31,    // .bww.wb
    13,    // bbww.wb
    -13,   // wbww.wb
    26,    // .www.wb
    0,     // bwww.wb
    0,     // wwww.wb
    0,     // ....bwb
    -16,   // b...bwb
    0,     // w...bwb
    0,     // .b..bwb
    0,     // bb..bwb
    -20,   // wb..bwb
    0,     // .w..bwb
    -8,    // bw..bwb
    8,     // ww..bwb
    15,    // ..b.bwb
    0,     // b.b.bwb
    -26,   // w.b.bwb
    -1,    // .bb.bwb
    -14,   // bbb.bwb
    0,     // wbb.bwb
    -19,   // .wb.bwb
    34,    // bwb.bwb
    0,     // wwb.bwb
    0,     // ..w.bwb
    -29,   // b.w.bwb
    24,    // w.w.bwb
    -25,   // .bw.bwb
    5,     // bbw.bwb
    0,     // wbw.bwb
    0,     // .ww.bwb
    0,     // bww.bwb
    -14,   // www.bwb
    0,     // ...bbwb
    0,     // b..bbwb
    0,     // w..bbwb
    3,     // .b.bbwb
    0,     // bb.bbwb
    13,    // wb.bbwb
    0,     // .w.bbwb
    -43,   // bw.bbwb
    -18,   // ww.bbwb
    1,     // ..bbbwb
    0,     // b.bbbwb
    0,     // w.bbbwb
    22,    // .bbbbwb
    0,     // bbbbbwb
    0,     // wbbbbwb
    0,     // .wbbbwb
    0,     // bwbbbwb
    -9,    // wwbbbwb
    31,    // ..wbbwb
    0,     // b.wbbwb
    -29,   // w.wbbwb
    0,     // .bwbbwb
    -32,   // bbwbbwb
    0,     // wbwbbwb
    15,    // .wwbbwb
    0,     // bwwbbwb
    -4,    // wwwbbwb
    11,    // ...wbwb
    0,     // b..wbwb
    32,    // w..wbwb
    0,     // .b.wbwb
    0,     // bb.wbwb
    0,     // wb.wbwb
    0,     // .w.wbwb
    0,     // bw.wbwb
    -13,   // ww.wbwb
    -30,   // ..bwbwb
    0,     // b.bwbwb
    0,     // w.bwbwb
    0,     // .bbwbwb
    12,    // bbbwbwb
    0,     // wbbwbwb
    0,     // .wbwbwb
    0,     // bwbwbwb
    -21,   // wwbwbwb
    0,     // ..wwbwb
    0,     // b.wwbwb
    14,    // w.wwbwb
    -24,   // .bwwbwb
    2,     // bbwwbwb
    0,     // wbwwbwb
    -10,   // .wwwbwb
    0,     // bwwwbwb
    -48,   // wwwwbwb
    0,     // ....wwb
    -7,    // b...wwb
    3,     // w...wwb
    -6,    // .b..wwb
    -5,    // bb..wwb
    10,    // wb..wwb
    0,     // .w..wwb
    0,     // bw..wwb
    0,     // ww..wwb
    -42,   // ..b.wwb
    0,     // b.b.wwb
    -5,    // w.b.wwb
    0,     // .bb.wwb
    7,     // bbb.wwb
    0,     // wbb.wwb
    25,    // .wb.wwb
    0,     // bwb.wwb
    0,     // wwb.wwb
    0,     // ..w.wwb
    0,     // b.w.wwb
    -3,    // w.w.wwb
    -22,   // .bw.wwb
    0,     // bbw.wwb
    0,     // wbw.wwb
    0,     // .ww.wwb
    0,     // bww.wwb
    0,     // www.wwb
    0,     // ...bwwb
    0,     // b..bwwb
    0,     // w..bwwb
    0,     // .b.bwwb
    -29,   // bb.bwwb
    9,     // wb.bwwb
    -27,   // .w.bwwb
    0,     // bw.bwwb
    0,     // ww.bwwb
    11,    // ..bbwwb
    13,    // b.bbwwb
    30,    // w.bbwwb
    -28,   // .bbbwwb
    0,     // bbbbwwb
    0,     // wbbbwwb
    44,    // .wbbwwb
    0,     // bwbbwwb
    19,    // wwbbwwb
    0,     // ..wbwwb
    0,     // b.wbwwb
    4,     // w.wbwwb
    0,     // .bwbwwb
    18,    // bbwbwwb
    0,     // wbwbwwb
    0,     // .wwbwwb
    0,     // bwwbwwb
    0,     // wwwbwwb
    0,     // ...wwwb
    11,    // b..wwwb
    0,     // w..wwwb
    -52,   // .b.wwwb
    0,     // bb.wwwb
    0,     // wb.wwwb
    -27,   // .w.wwwb
    0,     // bw.wwwb
    0,     // ww.wwwb
    0,     // ..bwwwb
    0,     // b.bwwwb
    0,     // w.bwwwb
    0,     // .bbwwwb
    0,     // bbbwwwb
    0,     // wbbwwwb
    15,    // .wbwwwb
    0,     // bwbwwwb
    28,    // wwbwwwb
    -14,   // ..wwwwb
    0,     // b.wwwwb
    0,     // w.wwwwb
    0,     // .bwwwwb
    3,     // bbwwwwb
    0,     // wbwwwwb
    -4,    // .wwwwwb
    0,     // bwwwwwb
    0,     // wwwwwwb
    -7,    // ......w
    0,     // b.....w
    17,    // w.....w
    44,    // .b....w
    -26,   // bb....w
    -30,   // wb....w
    0,     // .w....w
    9,     // bw....w
    6,     // ww....w
    -16,   // ..b...w
    -30,   // b.b...w
    10,    // w.b...w
    0,     // .bb...w
    24,    // bbb...w
    7,     // wbb...w
    2,     // .wb...w
    0,     // bwb...w
    21,    // wwb...w
    0,     // ..w...w
    -15,   // b.w...w
    21,    // w.w...w
    17,    // .bw...w
    0,     // bbw...w
    16,    // wbw...w
    6,     // .ww...w
    3,     // bww...w
    -30,   // www...w
    16,    // ...b..w
    -34,   // b..b..w
    14,    // w..b..w
    0,     // .b.b..w
    0,     // bb.b..w
    0,     // wb.b..w
    0,     // .w.b..w
    -14,   // bw.b..w
    0,     // ww.b..w
    29,    // ..bb..w
    0,     // b.bb..w
    0,     // w.bb..w
    26,    // .bbb..w
    0,     // bbbb..w
    -11,   // wbbb..w
    -19,   // .wbb..w
    0,     // bwbb..w
    0,     // wwbb..w
    13,    // ..wb..w
    13,    // b.wb..w
    0,     // w.wb..w
    26,    // .bwb..w
    -1,    // bbwb..w
    0,     // wbwb..w
    29,    // .wwb..w
    0,     // bwwb..w
    25,    // wwwb..w
    0,     // ...w..w
    34,    // b..w..w
    -30,   // w..w..w
    0,     // .b.w..w
    0,     // bb.w..w
    0,     // wb.w..w
    0,     // .w.w..w
    0,     // bw.w..w
    0,     // ww.w..w
    0,     // ..bw..w
    0,     // b.bw..w
    -7,    // w.bw..w
    0,     // .bbw..w
    0,     // bbbw..w
    0,     // wbbw..w
    0,     // .wbw..w
    32,    // bwbw..w
    -17,   // wwbw..w
    0,     // ..ww..w
    -37,   // b.ww..w
    0,     // w.ww..w
    0,     // .bww..w
    -45,   // bbww..w
    0,     // wbww..w
    -10,   // .www..w
    0,     // bwww..w
    0,     // wwww..w
    7,     // ....b.w
    15,    // b...b.w
    10,    // w...b.w
    19,    // .b..b.w
    12,    // bb..b.w
    -11,   // wb..b.w
    0,     // .w..b.w
    0,     // bw..b.w
    9,     // ww..b.w
    0,     // ..b.b.w
    -3,    // b.b.b.w
    0,     // w.b.b.w
    0,     // .bb.b.w
    24,    // bbb.b.w
    0,     // wbb.b.w
    22,    // .wb.b.w
    -26,   // bwb.b.w
    27,    // wwb.b.w
    0,     // ..w.b.w
    0,     // b.w.b.w
    -20,   // w.w.b.w
    -8,    // .bw.b.w
    0,     // bbw.b.w
    29,    // wbw.b.w
    -14,   // .ww.b.w
    -5,    // bww.b.w
    -11,   // www.b.w
    8,     // ...bb.w
    37,    // b..bb.w
    0,     // w..bb.w
    16,    // .b.bb.w
    10,    // bb.bb.w
    2,     // wb.bb.w
    0,     // .w.bb.w
    -14,   // bw.bb.w
    5,     // ww.bb.w
    0,     // ..bbb.w
    0,     // b.bbb.w
    47,    // w.bbb.w
    30,    // .bbbb.w
    32,    // bbbbb.w
    0,     // wbbbb.w
    -11,   // .wbbb.w
    0,     // bwbbb.w
    0,     // wwbbb.w
    -12,   // ..wbb.w
    0,     // b.wbb.w
    29,    // w.wbb.w
    -27,   // .bwbb.w
    2,     // bbwbb.w
    0,     // wbwbb.w
    -32,   // .wwbb.w
    30,    // bwwbb.w
    0,     // wwwbb.w
    0,     // ...wb.w
    -13,   // b..wb.w
    -7,    // w..wb.w
    -48,   // .b.wb.w
    -7,    // bb.wb.w
    32,    // wb.wb.w
    -27,   // .w.wb.w
    16,    // bw.wb.w
    -23,   // ww.wb.w
    0,     // ..bwb.w
    0,     // b.bwb.w
    24,    // w.bwb.w
    11,    // .bbwb.w
    18,    // bbbwb.w
    0,     // wbbwb.w
    20,    // .wbwb.w
    0,     // bwbwb.w
    0,     // wwbwb.w
    -24,   // ..wwb.w
    0,     // b.wwb.w
    -17,   // w.wwb.w
    52,    // .bwwb.w
    25,    // bbwwb.w
    0,     // wbwwb.w
    26,    // .wwwb.w
    0,     // bwwwb.w
    28,    // wwwwb.w
    0,     // ....w.w
    30,    // b...w.w
    21,    // w...w.w
    -52,   // .b..w.w
    0,     // bb..w.w
    0,     // wb..w.w
    0,     // .w..w.w
    0,     // bw..w.w
    36,    // ww..w.w
    0,     // ..b.w.w
    0,     // b.b.w.w
    -20,   // w.b.w.w
    -5,    // .bb.w.w
    0,     // bbb.w.w
    0,     // wbb.w.w
    -16,   // .wb.w.w
    24,    // bwb.w.w
    0,     // wwb.w.w
    0,     // ..w.w.w
    3,     // b.w.w.w
    0,     // w.w.w.w
    -14,   // .bw.w.w
    0,     // bbw.w.w
    0,     // wbw.w.w
    0,     // .ww.w.w
    -3,    // bww.w.w
    -24,   // www.w.w
    1,     // ...bw.w
    0,     // b..bw.w
    0,     // w..bw.w
    24,    // .b.bw.w
    0,     // bb.bw.w
    0,     // wb.bw.w
    0,     // .w.bw.w
    -48,   // bw.bw.w
    -19,   // ww.bw.w
    -25,   // ..bbw.w
    0,     // b.bbw.w
    29,    // w.bbw.w
    23,    // .bbbw.w
    0,     // bbbbw.w
    0,     // wbbbw.w
    0,     // .wbbw.w
    -29,   // bwbbw.w
    0,     // wwbbw.w
    17,    // ..wbw.w
    0,     // b.wbw.w
    31,    // w.wbw.w
    17,    // .bwbw.w
    11,    // bbwbw.w
    0,     // wbwbw.w
    -17,   // .wwbw.w
    4,     // bwwbw.w
    47,    // wwwbw.w
    -25,   // ...ww.w
    0,     // b..ww.w
    0,     // w..ww.w
    7,     // .b.ww.w
    -2,    // bb.ww.w
    0,     // wb.ww.w
    39,    // .w.ww.w
    -13,   // bw.ww.w
    19,    // ww.ww.w
    0,     // ..bww.w
    0,     // b.bww.w
    -17,   // w.bww.w
    0,     // .bbww.w
    0,     // bbbww.w
    -13,   // wbbww.w
    0,     // .wbww.w
    14,    // bwbww.w
    0,     // wwbww.w
    0,     // ..www.w
    0,     // b.www.w
    0,     // w.www.w
    -14,   // .bwww.w
    0,     // bbwww.w
    0,     // wbwww.w
    0,     // .wwww.w
    0,     // bwwww.w
    0,     // wwwww.w
    -3,    // .....bw
    -9,    // b....bw
    -30,   // w....bw
    0,     // .b...bw
    -54,   // bb...bw
    0,     // wb...bw
    0,     // .w...bw
    0,     // bw...bw
    16,    // ww...bw
    5,     // ..b..bw
    0,     // b.b..bw
    -11,   // w.b..bw
    0,     // .bb..bw
    30,    // bbb..bw
    0,     // wbb..bw
    -17,   // .wb..bw
    -20,   // bwb..bw
    -24,   // wwb..bw
    0,     // ..w..bw
    0,     // b.w..bw
    0,     // w.w..bw
    0,     // .bw..bw
    -6,    // bbw..bw
    8,     // wbw..bw
    0,     // .ww..bw
    10,    // bww..bw
    0,     // www..bw
    0,     // ...b.bw
    0,     // b..b.bw
    0,     // w..b.bw
    -23,   // .b.b.bw
    -18,   // bb.b.bw
    0,     // wb.b.bw
    0,     // .w.b.bw
    11,    // bw.b.bw
    14,    // ww.b.bw
    21,    // ..bb.bw
    13,    // b.bb.bw
    2,     // w.bb.bw
    -26,   // .bbb.bw
    0,     // bbbb.bw
    0,     // wbbb.bw
    -31,   // .wbb.bw
    13,    // bwbb.bw
    -13,   // wwbb.bw
    0,     // ..wb.bw
    -16,   // b.wb.bw
    0,     // w.wb.bw
    16,    // .bwb.bw
    0,     // bbwb.bw
    0,     // wbwb.bw
    19,    // .wwb.bw
    9,     // bwwb.bw
    21,    // wwwb.bw
    84,    // ...w.bw
    14,    // b..w.bw
    0,     // w..w.bw
    -45,   // .b.w.bw
    0,     // bb.w.bw
    0,     // wb.w.bw
    0,     // .w.w.bw
    -11,   // bw.w.bw
    4,     // ww.w.bw
    29,    // ..bw.bw
    48,    // b.bw.bw
    32,    // w.bw.bw
    0,     // .bbw.bw
    9,     // bbbw.bw
    0,     // wbbw.bw
    0,     // .wbw.bw
    0,     // bwbw.bw
    0,     // wwbw.bw
    53,    // ..ww.bw
    14,    // b.ww.bw
    0,     // w.ww.bw
    -7,    // .bww.bw
    -18,   // bbww.bw
    43,    // wbww.bw
    -73,   // .www.bw
    0,     // bwww.bw
    0,     // wwww.bw
    0,     // ....bbw
    -3,    // b...bbw
    7,     // w...bbw
    0,     // .b..bbw
    0,     // bb..bbw
    0,     // wb..bbw
    6,     // .w..bbw
    -10,   // bw..bbw
    5,     // ww..bbw
    0,     // ..b.bbw
    3,     // b.b.bbw
    0,     // w.b.bbw
    0,     // .bb.bbw
    0,     // bbb.bbw
    0,     // wbb.bbw
    22,    // .wb.bbw
    0,     // bwb.bbw
    0,     // wwb.bbw
    42,    // ..w.bbw
    5,     // b.w.bbw
    0,     // w.w.bbw
    -25,   // .bw.bbw
    0,     // bbw.bbw
    0,     // wbw.bbw
    0,     // .ww.bbw
    0,     // bww.bbw
    -7,    // www.bbw
    0,     // ...bbbw
    0,     // b..bbbw
    -11,   // w..bbbw
    27,    // .b.bbbw
    0,     // bb.bbbw
    0,     // wb.bbbw
    52,    // .w.bbbw
    0,     // bw.bbbw
    0,     // ww.bbbw
    14,    // ..bbbbw
    0,     // b.bbbbw
    0,     // w.bbbbw
    4,     // .bbbbbw
    0,     // bbbbbbw
    0,     // wbbbbbw
    0,     // .wbbbbw
    0,     // bwbbbbw
    -3,    // wwbbbbw
    0,     // ..wbbbw
    0,     // b.wbbbw
    0,     // w.wbbbw
    -15,   // .bwbbbw
    -28,   // bbwbbbw
    0,     // wbwbbbw
    0,     // .wwbbbw
    0,     // bwwbbbw
    0,     // wwwbbbw
    0,     // ...wbbw
    0,     // b..wbbw
    0,     // w..wbbw
    27,    // .b.wbbw
    0,     // bb.wbbw
    0,     // wb.wbbw
    0,     // .w.wbbw
    -9,    // bw.wbbw
    29,    // ww.wbbw
    0,     // ..bwbbw
    -4,    // b.bwbbw
    0,     // w.bwbbw
    0,     // .bbwbbw
    0,     // bbbwbbw
    0,     // wbbwbbw
    0,     // .wbwbbw
    0,     // bwbwbbw
    -18,   // wwbwbbw
    -11,   // ..wwbbw
    -30,   // b.wwbbw
    -13,   // w.wwbbw
    -44,   // .bwwbbw
    -19,   // bbwwbbw
    0,     // wbwwbbw
    28,    // .wwwbbw
    0,     // bwwwbbw
    0,     // wwwwbbw
    0,     // ....wbw
    0,     // b...wbw
    16,    // w...wbw
    0,     // .b..wbw
    -8,    // bb..wbw
    8,     // wb..wbw
    0,     // .w..wbw
    20,    // bw..wbw
    0,     // ww..wbw
    0,     // ..b.wbw
    -24,   // b.b.wbw
    29,    // w.b.wbw
    0,     // .bb.wbw
    14,    // bbb.wbw
    0,     // wbb.wbw
    25,    // .wb.wbw
    0,     // bwb.wbw
    -5,    // wwb.wbw
    -15,   // ..w.wbw
    26,    // b.w.wbw
    0,     // w.w.wbw
    19,    // .bw.wbw
    0,     // bbw.wbw
    -34,   // wbw.wbw
    1,     // .ww.wbw
    0,     // bww.wbw
    14,    // www.wbw
    -11,   // ...bwbw
    -32,   // b..bwbw
    0,     // w..bwbw
    0,     // .b.bwbw
    13,    // bb.bwbw
    0,     // wb.bwbw
    0,     // .w.bwbw
    0,     // bw.bwbw
    0,     // ww.bwbw
    0,     // ..bbwbw
    -14,   // b.bbwbw
    0,     // w.bbwbw
    10,    // .bbbwbw
    48,    // bbbbwbw
    0,     // wbbbwbw
    24,    // .wbbwbw
    0,     // bwbbwbw
    -2,    // wwbbwbw
    30,    // ..wbwbw
    0,     // b.wbwbw
    0,     // w.wbwbw
    0,     // .bwbwbw
    21,    // bbwbwbw
    0,     // wbwbwbw
    0,     // .wwbwbw
    0,     // bwwbwbw
    -12,   // wwwbwbw
    0,     // ...wwbw
    0,     // b..wwbw
    0,     // w..wwbw
    0,     // .b.wwbw
    18,    // bb.wwbw
    43,    // wb.wwbw
    -3,    // .w.wwbw
    -13,   // bw.wwbw
    0,     // ww.wwbw
    -31,   // ..bwwbw
    29,    // b.bwwbw
    0,     // w.bwwbw
    -15,   // .bbwwbw
    4,     // bbbwwbw
    0,     // wbbwwbw
    0,     // .wbwwbw
    0,     // bwbwwbw
    32,    // wwbwwbw
    -1,    // ..wwwbw
    0,     // b.wwwbw
    0,     // w.wwwbw
    0,     // .bwwwbw
    9,     // bbwwwbw
    0,     // wbwwwbw
    -22,   // .wwwwbw
    0,     // bwwwwbw
    0,     // wwwwwbw
    -35,   // .....ww
    26,    // b....ww
    6,     // w....ww
    0,     // .b...ww
    0,     // bb...ww
    16,    // wb...ww
    30,    // .w...ww
    54,    // bw...ww
    0,     // ww...ww
    2,     // ..b..ww
    0,     // b.b..ww
    9,     // w.b..ww
    -20,   // .bb..ww
    -22,   // bbb..ww
    5,     // wbb..ww
    0,     // .wb..ww
    8,     // bwb..ww
    9,     // wwb..ww
    0,     // ..w..ww
    -12,   // b.w..ww
    36,    // w.w..ww
    0,     // .bw..ww
    17,    // bbw..ww
    0,     // wbw..ww
    0,     // .ww..ww
    0,     // bww..ww
    23,    // www..ww
    27,    // ...b.ww
    0,     // b..b.ww
    0,     // w..b.ww
    0,     // .b.b.ww
    25,    // bb.b.ww
    14,    // wb.b.ww
    0,     // .w.b.ww
    0,     // bw.b.ww
    0,     // ww.b.ww
    -13,   // ..bb.ww
    2,     // b.bb.ww
    5,     // w.bb.ww
    30,    // .bbb.ww
    2,     // bbbb.ww
    0,     // wbbb.ww
    0,     // .wbb.ww
    -18,   // bwbb.ww
    0,     // wwbb.ww
    21,    // ..wb.ww
    7,     // b.wb.ww
    -19,   // w.wb.ww
    0,     // .bwb.ww
    0,     // bbwb.ww
    0,     // wbwb.ww
    -13,   // .wwb.ww
    0,     // bwwb.ww
    -6,    // wwwb.ww
    -37,   // ...w.ww
    0,     // b..w.ww
    0,     // w..w.ww
    0,     // .b.w.ww
    -25,   // bb.w.ww
    4,     // wb.w.ww
    27,    // .w.w.ww
    18,    // bw.w.ww
    -31,   // ww.w.ww
    0,     // ..bw.ww
    0,     // b.bw.ww
    -23,   // w.bw.ww
    0,     // .bbw.ww
    -8,    // bbbw.ww
    29,    // wbbw.ww
    -52,   // .wbw.ww
    -13,   // bwbw.ww
    3,     // wwbw.ww
    0,     // ..ww.ww
    -10,   // b.ww.ww
    19,    // w.ww.ww
    0,     // .bww.ww
    0,     // bbww.ww
    0,     // wbww.ww
    30,    // .www.ww
    0,     // bwww.ww
    10,    // wwww.ww
    0,     // ....bww
    0,     // b...bww
    21,    // w...bww
    0,     // .b..bww
    -17,   // bb..bww
    -24,   // wb..bww
    0,     // .w..bww
    6,     // bw..bww
    9,     // ww..bww
    0,     // ..b.bww
    0,     // b.b.bww
    27,    // w.b.bww
    0,     // .bb.bww
    -1,    // bbb.bww
    0,     // wbb.bww
    3,     // .wb.bww
    0,     // bwb.bww
    25,    // wwb.bww
    0,     // ..w.bww
    0,     // b.w.bww
    0,     // w.w.bww
    0,     // .bw.bww
    0,     // bbw.bww
    -5,    // wbw.bww
    13,    // .ww.bww
    0,     // bww.bww
    0,     // www.bww
    -3,    // ...bbww
    45,    // b..bbww
    0,     // w..bbww
    13,    // .b.bbww
    0,     // bb.bbww
    -13,   // wb.bbww
    -8,    // .w.bbww
    18,    // bw.bbww
    0,     // ww.bbww
    19,    // ..bbbww
    0,     // b.bbbww
    0,     // w.bbbww
    13,    // .bbbbww
    31,    // bbbbbww
    -3,    // wbbbbww
    10,    // .wbbbww
    -9,    // bwbbbww
    18,    // wwbbbww
    -31,   // ..wbbww
    -25,   // b.wbbww
    0,     // w.wbbww
    0,     // .bwbbww
    0,     // bbwbbww
    -2,    // wbwbbww
    -26,   // .wwbbww
    19,    // bwwbbww
    0,     // wwwbbww
    0,     // ...wbww
    1,     // b..wbww
    -17,   // w..wbww
    0,     // .b.wbww
    0,     // bb.wbww
    0,     // wb.wbww
    -15,   // .w.wbww
    0,     // bw.wbww
    3,     // ww.wbww
    0,     // ..bwbww
    -11,   // b.bwbww
    0,     // w.bwbww
    23,    // .bbwbww
    25,    // bbbwbww
    -18,   // wbbwbww
    32,    // .wbwbww
    -21,   // bwbwbww
    32,    // wwbwbww
    -18,   // ..wwbww
    -2,    // b.wwbww
    0,     // w.wwbww
    0,     // .bwwbww
    0,     // bbwwbww
    32,    // wbwwbww
    0,     // .wwwbww
    28,    // bwwwbww
    -3,    // wwwwbww
    0,     // ....www
    -24,   // b...www
    -30,   // w...www
    30,    // .b..www
    22,    // bb..www
    0,     // wb..www
    0,     // .w..www
    -30,   // bw..www
    23,    // ww..www
    0,     // ..b.www
    0,     // b.b.www
    -11,   // w.b.www
    -7,    // .bb.www
    0,     // bbb.www
    -7,    // wbb.www
    -21,   // .wb.www
    -14,   // bwb.www
    0,     // wwb.www
    3,     // ..w.www
    -24,   // b.w.www
    -24,   // w.w.www
    0,     // .bw.www
    1,     // bbw.www
    14,    // wbw.www
    22,    // .ww.www
    0,     // bww.www
    29,    // www.www
    0,     // ...bwww
    0,     // b..bwww
    25,    // w..bwww
    0,     // .b.bwww
    8,     // bb.bwww
    21,    // wb.bwww
    -27,   // .w.bwww
    -9,    // bw.bwww
    -6,    // ww.bwww
    0,     // ..bbwww
    0,     // b.bbwww
    0,     // w.bbwww
    44,    // .bbbwww
    0,     // bbbbwww
    0,     // wbbbwww
    -10,   // .wbbwww
    -4,    // bwbbwww
    0,     // wwbbwww
    57,    // ..wbwww
    -18,   // b.wbwww
    47,    // w.wbwww
    0,     // .bwbwww
    -25,   // bbwbwww
    -12,   // wbwbwww
    -10,   // .wwbwww
    0,     // bwwbwww
    1,     // wwwbwww
    0,     // ...wwww
    0,     // b..wwww
    0,     // w..wwww
    24,    // .b.wwww
    -2,    // bb.wwww
    0,     // wb.wwww
    0,     // .w.wwww
    0,     // bw.wwww
    10,    // ww.wwww
    2,     // ..bwwww
    0,     // b.bwwww
    28,    // w.bwwww
    0,     // .bbwwww
    0,     // bbbwwww
    0,     // wbbwwww
    -31,   // .wbwwww
    -48,   // bwbwwww
    -3,    // wwbwwww
    -17,   // ..wwwww
    -32,   // b.wwwww
    0,     // w.wwwww
    0,     // .bwwwww
    -31,   // bbwwwww
    0,     // wbwwwww
    -9,    // .wwwwww
    0,     // bwwwwww
    0,     // wwwwwww
    17,    // ccc
    20,    // cc
    37,    // c
    73,    // ttt
    57,    // tt
    5,     // t
    2,     // ct
    9,     // cct
    51,    // ctt
].into_boxed_slice()
