vec![
    0,     // ......
    -28,   // b.....
    28,    // w.....
    -49,   // .b....
    32,    // bb....
    -21,   // wb....
    49,    // .w....
    21,    // bw....
    -32,   // ww....
    -18,   // ..b...
    33,    // b.b...
    113,   // w.b...
    -31,   // .bb...
    101,   // bbb...
    -50,   // wbb...
    0,     // .wb...
    -8,    // bwb...
    30,    // wwb...
    18,    // ..w...
    -113,  // b.w...
    -33,   // w.w...
    0,     // .bw...
    -30,   // bbw...
    8,     // wbw...
    31,    // .ww...
    50,    // bww...
    -101,  // www...
    -18,   // ...b..
    -9,    // b..b..
    -130,  // w..b..
    11,    // .b.b..
    32,    // bb.b..
    -100,  // wb.b..
    33,    // .w.b..
    34,    // bw.b..
    -22,   // ww.b..
    59,    // ..bb..
    134,   // b.bb..
    58,    // w.bb..
    112,   // .bbb..
    114,   // bbbb..
    -43,   // wbbb..
    -85,   // .wbb..
    0,     // bwbb..
    5,     // wwbb..
    0,     // ..wb..
    -98,   // b.wb..
    -84,   // w.wb..
    149,   // .bwb..
    104,   // bbwb..
    -58,   // wbwb..
    -27,   // .wwb..
    -131,  // bwwb..
    19,    // wwwb..
    18,    // ...w..
    130,   // b..w..
    9,     // w..w..
    -33,   // .b.w..
    22,    // bb.w..
    -34,   // wb.w..
    -11,   // .w.w..
    100,   // bw.w..
    -32,   // ww.w..
    0,     // ..bw..
    84,    // b.bw..
    98,    // w.bw..
    27,    // .bbw..
    -19,   // bbbw..
    131,   // wbbw..
    -149,  // .wbw..
    58,    // bwbw..
    -104,  // wwbw..
    -59,   // ..ww..
    -58,   // b.ww..
    -134,  // w.ww..
    85,    // .bww..
    -5,    // bbww..
    0,     // wbww..
    -112,  // .www..
    43,    // bwww..
    -114,  // wwww..
    -49,   // ....b.
    108,   // b...b.
    103,   // w...b.
    137,   // .b..b.
    0,     // bb..b.
    17,    // wb..b.
    0,     // .w..b.
    0,     // bw..b.
    -219,  // ww..b.
    11,    // ..b.b.
    15,    // b.b.b.
    -8,    // w.b.b.
    -66,   // .bb.b.
    44,    // bbb.b.
    67,    // wbb.b.
    -56,   // .wb.b.
    -7,    // bwb.b.
    0,     // wwb.b.
    -33,   // ..w.b.
    -41,   // b.w.b.
    -49,   // w.w.b.
    116,   // .bw.b.
    -59,   // bbw.b.
    44,    // wbw.b.
    42,    // .ww.b.
    -1,    // bww.b.
    -7,    // www.b.
    -31,   // ...bb.
    70,    // b..bb.
    -20,   // w..bb.
    -66,   // .b.bb.
    -40,   // bb.bb.
    -148,  // wb.bb.
    -42,   // .w.bb.
    -29,   // bw.bb.
    53,    // ww.bb.
    112,   // ..bbb.
    -65,   // b.bbb.
    22,    // w.bbb.
    85,    // .bbbb.
    -7,    // bbbbb.
    1676,  // wbbbb.
    -63,   // .wbbb.
    -239,  // bwbbb.
    -76,   // wwbbb.
    27,    // ..wbb.
    63,    // b.wbb.
    38,    // w.wbb.
    -43,   // .bwbb.
    -47,   // bbwbb.
    -51,   // wbwbb.
    0,     // .wwbb.
    -22,   // bwwbb.
    -18,   // wwwbb.
    0,     // ...wb.
    -8,    // b..wb.
    77,    // w..wb.
    116,   // .b.wb.
    19,    // bb.wb.
    -35,   // wb.wb.
    56,    // .w.wb.
    -80,   // bw.wb.
    -17,   // ww.wb.
    149,   // ..bwb.
    -56,   // b.bwb.
    -49,   // w.bwb.
    -43,   // .bbwb.
    -47,   // bbbwb.
    -17,   // wbbwb.
    0,     // .wbwb.
    80,    // bwbwb.
    31,    // wwbwb.
    85,    // ..wwb.
    86,    // b.wwb.
    125,   // w.wwb.
    88,    // .bwwb.
    -85,   // bbwwb.
    -27,   // wbwwb.
    63,    // .wwwb.
    158,   // bwwwb.
    0,     // wwwwb.
    49,    // ....w.
    -103,  // b...w.
    -108,  // w...w.
    0,     // .b..w.
    219,   // bb..w.
    0,     // wb..w.
    -137,  // .w..w.
    -17,   // bw..w.
    0,     // ww..w.
    33,    // ..b.w.
    49,    // b.b.w.
    41,    // w.b.w.
    -42,   // .bb.w.
    7,     // bbb.w.
    1,     // wbb.w.
    -116,  // .wb.w.
    -44,   // bwb.w.
    59,    // wwb.w.
    -11,   // ..w.w.
    8,     // b.w.w.
    -15,   // w.w.w.
    56,    // .bw.w.
    0,     // bbw.w.
    7,     // wbw.w.
    66,    // .ww.w.
    -67,   // bww.w.
    -44,   // www.w.
    0,     // ...bw.
    -77,   // b..bw.
    8,     // w..bw.
    -56,   // .b.bw.
    17,    // bb.bw.
    80,    // wb.bw.
    -116,  // .w.bw.
    35,    // bw.bw.
    -19,   // ww.bw.
    -85,   // ..bbw.
    -125,  // b.bbw.
    -86,   // w.bbw.
    -63,   // .bbbw.
    0,     // bbbbw.
    -158,  // wbbbw.
    -88,   // .wbbw.
    27,    // bwbbw.
    85,    // wwbbw.
    -149,  // ..wbw.
    49,    // b.wbw.
    56,    // w.wbw.
    0,     // .bwbw.
    -31,   // bbwbw.
    -80,   // wbwbw.
    43,    // .wwbw.
    17,    // bwwbw.
    47,    // wwwbw.
    31,    // ...ww.
    20,    // b..ww.
    -70,   // w..ww.
    42,    // .b.ww.
    -53,   // bb.ww.
    29,    // wb.ww.
    66,    // .w.ww.
    148,   // bw.ww.
    40,    // ww.ww.
    -27,   // ..bww.
    -38,   // b.bww.
    -63,   // w.bww.
    0,     // .bbww.
    18,    // bbbww.
    22,    // wbbww.
    43,    // .wbww.
    51,    // bwbww.
    47,    // wwbww.
    -112,  // ..www.
    -22,   // b.www.
    65,    // w.www.
    63,    // .bwww.
    76,    // bbwww.
    239,   // wbwww.
    -85,   // .wwww.
    -1676, // bwwww.
    7,     // wwwww.
    -28,   // .....b
    -232,  // b....b
    0,     // w....b
    108,   // .b...b
    71,    // bb...b
    223,   // wb...b
    -103,  // .w...b
    87,    // bw...b
    -50,   // ww...b
    -9,    // ..b..b
    -110,  // b.b..b
    135,   // w.b..b
    70,    // .bb..b
    122,   // bbb..b
    6,     // wbb..b
    -77,   // .wb..b
    25,    // bwb..b
    50,    // wwb..b
    130,   // ..w..b
    101,   // b.w..b
    62,    // w.w..b
    -8,    // .bw..b
    35,    // bbw..b
    52,    // wbw..b
    20,    // .ww..b
    -205,  // bww..b
    28,    // www..b
    33,    // ...b.b
    -110,  // b..b.b
    -62,   // w..b.b
    15,    // .b.b.b
    -12,   // bb.b.b
    297,   // wb.b.b
    49,    // .w.b.b
    -61,   // bw.b.b
    46,    // ww.b.b
    134,   // ..bb.b
    6,     // b.bb.b
    0,     // w.bb.b
    -65,   // .bbb.b
    -57,   // bbbb.b
    101,   // wbbb.b
    -125,  // .wbb.b
    -139,  // bwbb.b
    51,    // wwbb.b
    84,    // ..wb.b
    0,     // b.wb.b
    0,     // w.wb.b
    -56,   // .bwb.b
    -16,   // bbwb.b
    -177,  // wbwb.b
    -38,   // .wwb.b
    15,    // bwwb.b
    -12,   // wwwb.b
    -113,  // ...w.b
    101,   // b..w.b
    -135,  // w..w.b
    -41,   // .b.w.b
    -57,   // bb.w.b
    50,    // wb.w.b
    8,     // .w.w.b
    -19,   // bw.w.b
    0,     // ww.w.b
    -98,   // ..bw.b
    0,     // b.bw.b
    0,     // w.bw.b
    63,    // .bbw.b
    7,     // bbbw.b
    59,    // wbbw.b
    49,    // .wbw.b
    42,    // bwbw.b
    -95,   // wwbw.b
    -58,   // ..ww.b
    21,    // b.ww.b
    0,     // w.ww.b
    86,    // .bww.b
    -146,  // bbww.b
    36,    // wbww.b
    -22,   // .www.b
    77,    // bwww.b
    35,    // wwww.b
    32,    // ....bb
    71,    // b...bb
    50,    // w...bb
    0,     // .b..bb
    -57,   // bb..bb
    42,    // wb..bb
    219,   // .w..bb
    198,   // bw..bb
    0,     // ww..bb
    32,    // ..b.bb
    -12,   // b.b.bb
    0,     // w.b.bb
    -40,   // .bb.bb
    -77,   // bbb.bb
    73,    // wbb.bb
    17,    // .wb.bb
    2,     // bwb.bb
    -89,   // wwb.bb
    22,    // ..w.bb
    -57,   // b.w.bb
    -46,   // w.w.bb
    19,    // .bw.bb
    -3,    // bbw.bb
    14,    // wbw.bb
    -53,   // .ww.bb
    84,    // bww.bb
    11,    // www.bb
    101,   // ...bbb
    122,   // b..bbb
    -28,   // w..bbb
    44,    // .b.bbb
    -77,   // bb.bbb
    -130,  // wb.bbb
    7,     // .w.bbb
    -16,   // bw.bbb
    -11,   // ww.bbb
    114,   // ..bbbb
    -57,   // b.bbbb
    -35,   // w.bbbb
    -7,    // .bbbbb
    37,    // bbbbbb
    -98,   // wbbbbb
    0,     // .wbbbb
    26,    // bwbbbb
    -39,   // wwbbbb
    -19,   // ..wbbb
    7,     // b.wbbb
    12,    // w.wbbb
    -47,   // .bwbbb
    -71,   // bbwbbb
    -48,   // wbwbbb
    18,    // .wwbbb
    -38,   // bwwbbb
    0,     // wwwbbb
    -30,   // ...wbb
    35,    // b..wbb
    -50,   // w..wbb
    -59,   // .b.wbb
    -3,    // bb.wbb
    -15,   // wb.wbb
    0,     // .w.wbb
    -60,   // bw.wbb
    89,    // ww.wbb
    104,   // ..bwbb
    -16,   // b.bwbb
    95,    // w.bwbb
    -47,   // .bbwbb
    -71,   // bbbwbb
    105,   // wbbwbb
    -31,   // .wbwbb
    -100,  // bwbwbb
    0,     // wwbwbb
    -5,    // ..wwbb
    -146,  // b.wwbb
    -51,   // w.wwbb
    -85,   // .bwwbb
    -64,   // bbwwbb
    -35,   // wbwwbb
    76,    // .wwwbb
    120,   // bwwwbb
    39,    // wwwwbb
    21,    // ....wb
    87,    // b...wb
    -223,  // w...wb
    0,     // .b..wb
    198,   // bb..wb
    0,     // wb..wb
    -17,   // .w..wb
    -47,   // bw..wb
    -42,   // ww..wb
    34,    // ..b.wb
    -61,   // b.b.wb
    -50,   // w.b.wb
    -29,   // .bb.wb
    -16,   // bbb.wb
    105,   // wbb.wb
    35,    // .wb.wb
    3,     // bwb.wb
    15,    // wwb.wb
    100,   // ..w.wb
    -19,   // b.w.wb
    -297,  // w.w.wb
    -80,   // .bw.wb
    -60,   // bbw.wb
    123,   // wbw.wb
    148,   // .ww.wb
    -3,    // bww.wb
    130,   // www.wb
    -8,    // ...bwb
    25,    // b..bwb
    -52,   // w..bwb
    -7,    // .b.bwb
    2,     // bb.bwb
    -123,  // wb.bwb
    -44,   // .w.bwb
    3,     // bw.bwb
    -14,   // ww.bwb
    0,     // ..bbwb
    -139,  // b.bbwb
    -36,   // w.bbwb
    -239,  // .bbbwb
    26,    // bbbbwb
    -87,   // wbbbwb
    27,    // .wbbwb
    41,    // bwbbwb
    35,    // wwbbwb
    58,    // ..wbwb
    42,    // b.wbwb
    177,   // w.wbwb
    80,    // .bwbwb
    -100,  // bbwbwb
    0,     // wbwbwb
    51,    // .wwbwb
    109,   // bwwbwb
    48,    // wwwbwb
    50,    // ...wwb
    -205,  // b..wwb
    -6,    // w..wwb
    -1,    // .b.wwb
    84,    // bb.wwb
    -105,  // wb.wwb
    -67,   // .w.wwb
    -3,    // bw.wwb
    -73,   // ww.wwb
    -131,  // ..bwwb
    15,    // b.bwwb
    -59,   // w.bwwb
    -22,   // .bbwwb
    -38,   // bbbwwb
    0,     // wbbwwb
    17,    // .wbwwb
    109,   // bwbwwb
    -105,  // wwbwwb
    43,    // ..wwwb
    77,    // b.wwwb
    -101,  // w.wwwb
    158,   // .bwwwb
    120,   // bbwwwb
    87,    // wbwwwb
    -1676, // .wwwwb
    -105,  // bwwwwb
    98,    // wwwwwb
    28,    // .....w
    0,     // b....w
    232,   // w....w
    103,   // .b...w
    50,    // bb...w
    -87,   // wb...w
    -108,  // .w...w
    -223,  // bw...w
    -71,   // ww...w
    -130,  // ..b..w
    -62,   // b.b..w
    -101,  // w.b..w
    -20,   // .bb..w
    -28,   // bbb..w
    205,   // wbb..w
    8,     // .wb..w
    -52,   // bwb..w
    -35,   // wwb..w
    9,     // ..w..w
    -135,  // b.w..w
    110,   // w.w..w
    77,    // .bw..w
    -50,   // bbw..w
    -25,   // wbw..w
    -70,   // .ww..w
    -6,    // bww..w
    -122,  // www..w
    113,   // ...b.w
    135,   // b..b.w
    -101,  // w..b.w
    -8,    // .b.b.w
    0,     // bb.b.w
    19,    // wb.b.w
    41,    // .w.b.w
    -50,   // bw.b.w
    57,    // ww.b.w
    58,    // ..bb.w
    0,     // b.bb.w
    -21,   // w.bb.w
    22,    // .bbb.w
    -35,   // bbbb.w
    -77,   // wbbb.w
    -86,   // .wbb.w
    -36,   // bwbb.w
    146,   // wwbb.w
    98,    // ..wb.w
    0,     // b.wb.w
    0,     // w.wb.w
    -49,   // .bwb.w
    95,    // bbwb.w
    -42,   // wbwb.w
    -63,   // .wwb.w
    -59,   // bwwb.w
    -7,    // wwwb.w
    -33,   // ...w.w
    62,    // b..w.w
    110,   // w..w.w
    -49,   // .b.w.w
    -46,   // bb.w.w
    61,    // wb.w.w
    -15,   // .w.w.w
    -297,  // bw.w.w
    12,    // ww.w.w
    -84,   // ..bw.w
    0,     // b.bw.w
    0,     // w.bw.w
    38,    // .bbw.w
    12,    // bbbw.w
    -15,   // wbbw.w
    56,    // .wbw.w
    177,   // bwbw.w
    16,    // wwbw.w
    -134,  // ..ww.w
    0,     // b.ww.w
    -6,    // w.ww.w
    125,   // .bww.w
    -51,   // bbww.w
    139,   // wbww.w
    65,    // .www.w
    -101,  // bwww.w
    57,    // wwww.w
    -21,   // ....bw
    223,   // b...bw
    -87,   // w...bw
    17,    // .b..bw
    42,    // bb..bw
    47,    // wb..bw
    0,     // .w..bw
    0,     // bw..bw
    -198,  // ww..bw
    -100,  // ..b.bw
    297,   // b.b.bw
    19,    // w.b.bw
    -148,  // .bb.bw
    -130,  // bbb.bw
    3,     // wbb.bw
    80,    // .wb.bw
    -123,  // bwb.bw
    60,    // wwb.bw
    -34,   // ..w.bw
    50,    // b.w.bw
    61,    // w.w.bw
    -35,   // .bw.bw
    -15,   // bbw.bw
    -3,    // wbw.bw
    29,    // .ww.bw
    -105,  // bww.bw
    16,    // www.bw
    -50,   // ...bbw
    6,     // b..bbw
    205,   // w..bbw
    67,    // .b.bbw
    73,    // bb.bbw
    3,     // wb.bbw
    1,     // .w.bbw
    105,   // bw.bbw
    -84,   // ww.bbw
    -43,   // ..bbbw
    101,   // b.bbbw
    -77,   // w.bbbw
    1676,  // .bbbbw
    -98,   // bbbbbw
    105,   // wbbbbw
    -158,  // .wbbbw
    -87,   // bwbbbw
    -120,  // wwbbbw
    131,   // ..wbbw
    59,    // b.wbbw
    -15,   // w.wbbw
    -17,   // .bwbbw
    105,   // bbwbbw
    -109,  // wbwbbw
    22,    // .wwbbw
    0,     // bwwbbw
    38,    // wwwbbw
    8,     // ...wbw
    52,    // b..wbw
    -25,   // w..wbw
    44,    // .b.wbw
    14,    // bb.wbw
    -3,    // wb.wbw
    7,     // .w.wbw
    123,   // bw.wbw
    -2,    // ww.wbw
    -58,   // ..bwbw
    -177,  // b.bwbw
    -42,   // w.bwbw
    -51,   // .bbwbw
    -48,   // bbbwbw
    -109,  // wbbwbw
    -80,   // .wbwbw
    0,     // bwbwbw
    100,   // wwbwbw
    0,     // ..wwbw
    36,    // b.wwbw
    139,   // w.wwbw
    -27,   // .bwwbw
    -35,   // bbwwbw
    -41,   // wbwwbw
    239,   // .wwwbw
    87,    // bwwwbw
    -26,   // wwwwbw
    -32,   // ....ww
    -50,   // b...ww
    -71,   // w...ww
    -219,  // .b..ww
    0,     // bb..ww
    -198,  // wb..ww
    0,     // .w..ww
    -42,   // bw..ww
    57,    // ww..ww
    -22,   // ..b.ww
    46,    // b.b.ww
    57,    // w.b.ww
    53,    // .bb.ww
    -11,   // bbb.ww
    -84,   // wbb.ww
    -19,   // .wb.ww
    -14,   // bwb.ww
    3,     // wwb.ww
    -32,   // ..w.ww
    0,     // b.w.ww
    12,    // w.w.ww
    -17,   // .bw.ww
    89,    // bbw.ww
    -2,    // wbw.ww
    40,    // .ww.ww
    -73,   // bww.ww
    77,    // www.ww
    30,    // ...bww
    50,    // b..bww
    -35,   // w..bww
    0,     // .b.bww
    -89,   // bb.bww
    60,    // wb.bww
    59,    // .w.bww
    15,    // bw.bww
    3,     // ww.bww
    5,     // ..bbww
    51,    // b.bbww
    146,   // w.bbww
    -76,   // .bbbww
    -39,   // bbbbww
    -120,  // wbbbww
    85,    // .wbbww
    35,    // bwbbww
    64,    // wwbbww
    -104,  // ..wbww
    -95,   // b.wbww
    16,    // w.wbww
    31,    // .bwbww
    0,     // bbwbww
    100,   // wbwbww
    47,    // .wwbww
    -105,  // bwwbww
    71,    // wwwbww
    -101,  // ...www
    28,    // b..www
    -122,  // w..www
    -7,    // .b.www
    11,    // bb.www
    16,    // wb.www
    -44,   // .w.www
    130,   // bw.www
    77,    // ww.www
    19,    // ..bwww
    -12,   // b.bwww
    -7,    // w.bwww
    -18,   // .bbwww
    0,     // bbbwww
    38,    // wbbwww
    47,    // .wbwww
    48,    // bwbwww
    71,    // wwbwww
    -114,  // ..wwww
    35,    // b.wwww
    57,    // w.wwww
    0,     // .bwwww
    39,    // bbwwww
    -26,   // wbwwww
    7,     // .wwwww
    98,    // bwwwww
    -37,   // wwwwww
    185,   // ccc
    58,    // cc
    6,     // c
    18,    // ttt
    65,    // tt
    16,    // t
    60,    // ct
    92,    // cct
    110,   // ctt
].into_boxed_slice()
