vec![
    0,     // .......
    21,    // b......
    -21,   // w......
    1,     // .b.....
    8,     // bb.....
    -1,    // wb.....
    -1,    // .w.....
    1,     // bw.....
    -8,    // ww.....
    -12,   // ..b....
    -25,   // b.b....
    -16,   // w.b....
    -11,   // .bb....
    16,    // bbb....
    -8,    // wbb....
    -32,   // .wb....
    -25,   // bwb....
    18,    // wwb....
    12,    // ..w....
    16,    // b.w....
    25,    // w.w....
    32,    // .bw....
    -18,   // bbw....
    25,    // wbw....
    11,    // .ww....
    8,     // bww....
    -16,   // www....
    -15,   // ...b...
    -3,    // b..b...
    13,    // w..b...
    -11,   // .b.b...
    7,     // bb.b...
    -14,   // wb.b...
    -13,   // .w.b...
    1,     // bw.b...
    11,    // ww.b...
    -19,   // ..bb...
    -17,   // b.bb...
    -11,   // w.bb...
    10,    // .bbb...
    52,    // bbbb...
    -8,    // wbbb...
    -8,    // .wbb...
    -23,   // bwbb...
    6,     // wwbb...
    8,     // ..wb...
    19,    // b.wb...
    12,    // w.wb...
    -2,    // .bwb...
    -4,    // bbwb...
    -6,    // wbwb...
    -6,    // .wwb...
    -2,    // bwwb...
    8,     // wwwb...
    15,    // ...w...
    -13,   // b..w...
    3,     // w..w...
    13,    // .b.w...
    -11,   // bb.w...
    -1,    // wb.w...
    11,    // .w.w...
    14,    // bw.w...
    -7,    // ww.w...
    -8,    // ..bw...
    -12,   // b.bw...
    -19,   // w.bw...
    6,     // .bbw...
    -8,    // bbbw...
    2,     // wbbw...
    2,     // .wbw...
    6,     // bwbw...
    4,     // wwbw...
    19,    // ..ww...
    11,    // b.ww...
    17,    // w.ww...
    8,     // .bww...
    -6,    // bbww...
    23,    // wbww...
    -10,   // .www...
    8,     // bwww...
    -52,   // wwww...
    -12,   // ....b..
    3,     // b...b..
    -8,    // w...b..
    -4,    // .b..b..
    8,     // bb..b..
    -15,   // wb..b..
    21,    // .w..b..
    -3,    // bw..b..
    8,     // ww..b..
    -4,    // ..b.b..
    12,    // b.b.b..
    2,     // w.b.b..
    -11,   // .bb.b..
    30,    // bbb.b..
    -5,    // wbb.b..
    1,     // .wb.b..
    13,    // bwb.b..
    8,     // wwb.b..
    0,     // ..w.b..
    -10,   // b.w.b..
    -2,    // w.w.b..
    -16,   // .bw.b..
    -31,   // bbw.b..
    -9,    // wbw.b..
    -18,   // .ww.b..
    0,     // bww.b..
    -20,   // www.b..
    -19,   // ...bb..
    -16,   // b..bb..
    -18,   // w..bb..
    -17,   // .b.bb..
    -1,    // bb.bb..
    -27,   // wb.bb..
    22,    // .w.bb..
    -3,    // bw.bb..
    17,    // ww.bb..
    9,     // ..bbb..
    1,     // b.bbb..
    18,    // w.bbb..
    20,    // .bbbb..
    -11,   // bbbbb..
    15,    // wbbbb..
    8,     // .wbbb..
    6,     // bwbbb..
    -2,    // wwbbb..
    -19,   // ..wbb..
    -6,    // b.wbb..
    -3,    // w.wbb..
    -10,   // .bwbb..
    8,     // bbwbb..
    10,    // wbwbb..
    -28,   // .wwbb..
    11,    // bwwbb..
    1,     // wwwbb..
    -8,    // ...wb..
    -6,    // b..wb..
    -7,    // w..wb..
    -15,   // .b.wb..
    -1,    // bb.wb..
    6,     // wb.wb..
    -24,   // .w.wb..
    23,    // bw.wb..
    7,     // ww.wb..
    7,     // ..bwb..
    0,     // b.bwb..
    -3,    // w.bwb..
    -15,   // .bbwb..
    15,    // bbbwb..
    -1,    // wbbwb..
    16,    // .wbwb..
    1,     // bwbwb..
    -19,   // wwbwb..
    19,    // ..wwb..
    -7,    // b.wwb..
    -37,   // w.wwb..
    8,     // .bwwb..
    15,    // bbwwb..
    -9,    // wbwwb..
    14,    // .wwwb..
    -6,    // bwwwb..
    8,     // wwwwb..
    12,    // ....w..
    8,     // b...w..
    -3,    // w...w..
    -21,   // .b..w..
    -8,    // bb..w..
    3,     // wb..w..
    4,     // .w..w..
    15,    // bw..w..
    -8,    // ww..w..
    0,     // ..b.w..
    2,     // b.b.w..
    10,    // w.b.w..
    18,    // .bb.w..
    20,    // bbb.w..
    0,     // wbb.w..
    16,    // .wb.w..
    9,     // bwb.w..
    31,    // wwb.w..
    4,     // ..w.w..
    -2,    // b.w.w..
    -12,   // w.w.w..
    -1,    // .bw.w..
    -8,    // bbw.w..
    -13,   // wbw.w..
    11,    // .ww.w..
    5,     // bww.w..
    -30,   // www.w..
    8,     // ...bw..
    7,     // b..bw..
    6,     // w..bw..
    24,    // .b.bw..
    -7,    // bb.bw..
    -23,   // wb.bw..
    15,    // .w.bw..
    -6,    // bw.bw..
    1,     // ww.bw..
    -19,   // ..bbw..
    37,    // b.bbw..
    7,     // w.bbw..
    -14,   // .bbbw..
    -8,    // bbbbw..
    6,     // wbbbw..
    -8,    // .wbbw..
    9,     // bwbbw..
    -15,   // wwbbw..
    -7,    // ..wbw..
    3,     // b.wbw..
    0,     // w.wbw..
    -16,   // .bwbw..
    19,    // bbwbw..
    -1,    // wbwbw..
    15,    // .wwbw..
    1,     // bwwbw..
    -15,   // wwwbw..
    19,    // ...ww..
    18,    // b..ww..
    16,    // w..ww..
    -22,   // .b.ww..
    -17,   // bb.ww..
    3,     // wb.ww..
    17,    // .w.ww..
    27,    // bw.ww..
    1,     // ww.ww..
    19,    // ..bww..
    3,     // b.bww..
    6,     // w.bww..
    28,    // .bbww..
    -1,    // bbbww..
    -11,   // wbbww..
    10,    // .wbww..
    -10,   // bwbww..
    -8,    // wwbww..
    -9,    // ..www..
    -18,   // b.www..
    -1,    // w.www..
    -8,    // .bwww..
    2,     // bbwww..
    -6,    // wbwww..
    -20,   // .wwww..
    -15,   // bwwww..
    11,    // wwwww..
    1,     // .....b.
    18,    // b....b.
    8,     // w....b.
    -16,   // .b...b.
    17,    // bb...b.
    -4,    // wb...b.
    0,     // .w...b.
    9,     // bw...b.
    -9,    // ww...b.
    -4,    // ..b..b.
    -1,    // b.b..b.
    8,     // w.b..b.
    15,    // .bb..b.
    20,    // bbb..b.
    34,    // wbb..b.
    -7,    // .wb..b.
    -24,   // bwb..b.
    1,     // wwb..b.
    -21,   // ..w..b.
    -1,    // b.w..b.
    5,     // w.w..b.
    8,     // .bw..b.
    -10,   // bbw..b.
    -3,    // wbw..b.
    3,     // .ww..b.
    -21,   // bww..b.
    -13,   // www..b.
    -11,   // ...b.b.
    -16,   // b..b.b.
    17,    // w..b.b.
    -15,   // .b.b.b.
    -5,    // bb.b.b.
    11,    // wb.b.b.
    -6,    // .w.b.b.
    -6,    // bw.b.b.
    -22,   // ww.b.b.
    -17,   // ..bb.b.
    -4,    // b.bb.b.
    -20,   // w.bb.b.
    -11,   // .bbb.b.
    -6,    // bbbb.b.
    13,    // wbbb.b.
    16,    // .wbb.b.
    -15,   // bwbb.b.
    -4,    // wwbb.b.
    24,    // ..wb.b.
    -21,   // b.wb.b.
    1,     // w.wb.b.
    4,     // .bwb.b.
    15,    // bbwb.b.
    -8,    // wbwb.b.
    4,     // .wwb.b.
    -7,    // bwwb.b.
    3,     // wwwb.b.
    13,    // ...w.b.
    -1,    // b..w.b.
    -6,    // w..w.b.
    33,    // .b.w.b.
    -21,   // bb.w.b.
    -12,   // wb.w.b.
    6,     // .w.w.b.
    2,     // bw.w.b.
    5,     // ww.w.b.
    -15,   // ..bw.b.
    22,    // b.bw.b.
    10,    // w.bw.b.
    0,     // .bbw.b.
    -11,   // bbbw.b.
    6,     // wbbw.b.
    7,     // .wbw.b.
    7,     // bwbw.b.
    -10,   // wwbw.b.
    -22,   // ..ww.b.
    -20,   // b.ww.b.
    -10,   // w.ww.b.
    -16,   // .bww.b.
    -12,   // bbww.b.
    -6,    // wbww.b.
    -3,    // .www.b.
    8,     // bwww.b.
    6,     // wwww.b.
    -11,   // ....bb.
    -3,    // b...bb.
    -4,    // w...bb.
    15,    // .b..bb.
    -10,   // bb..bb.
    -8,    // wb..bb.
    -3,    // .w..bb.
    20,    // bw..bb.
    20,    // ww..bb.
    -11,   // ..b.bb.
    -8,    // b.b.bb.
    15,    // w.b.bb.
    13,    // .bb.bb.
    -2,    // bbb.bb.
    7,     // wbb.bb.
    -9,    // .wb.bb.
    -4,    // bwb.bb.
    -1,    // wwb.bb.
    18,    // ..w.bb.
    6,     // b.w.bb.
    0,     // w.w.bb.
    -8,    // .bw.bb.
    4,     // bbw.bb.
    19,    // wbw.bb.
    0,     // .ww.bb.
    -19,   // bww.bb.
    -16,   // www.bb.
    10,    // ...bbb.
    7,     // b..bbb.
    1,     // w..bbb.
    -11,   // .b.bbb.
    19,    // bb.bbb.
    0,     // wb.bbb.
    3,     // .w.bbb.
    -14,   // bw.bbb.
    4,     // ww.bbb.
    20,    // ..bbbb.
    36,    // b.bbbb.
    14,    // w.bbbb.
    11,    // .bbbbb.
    21,    // bbbbbb.
    8,     // wbbbbb.
    5,     // .wbbbb.
    -12,   // bwbbbb.
    12,    // wwbbbb.
    -14,   // ..wbbb.
    12,    // b.wbbb.
    -29,   // w.wbbb.
    -7,    // .bwbbb.
    9,     // bbwbbb.
    19,    // wbwbbb.
    -10,   // .wwbbb.
    -18,   // bwwbbb.
    0,     // wwwbbb.
    6,     // ...wbb.
    -7,    // b..wbb.
    -12,   // w..wbb.
    0,     // .b.wbb.
    11,    // bb.wbb.
    -2,    // wb.wbb.
    -4,    // .w.wbb.
    22,    // bw.wbb.
    7,     // ww.wbb.
    -15,   // ..bwbb.
    -18,   // b.bwbb.
    23,    // w.bwbb.
    -2,    // .bbwbb.
    9,     // bbbwbb.
    -21,   // wbbwbb.
    12,    // .wbwbb.
    -17,   // bwbwbb.
    -18,   // wwbwbb.
    28,    // ..wwbb.
    13,    // b.wwbb.
    14,    // w.wwbb.
    -3,    // .bwwbb.
    -21,   // bbwwbb.
    -18,   // wbwwbb.
    10,    // .wwwbb.
    -9,    // bwwwbb.
    -2,    // wwwwbb.
    32,    // ....wb.
    4,     // b...wb.
    0,     // w...wb.
    8,     // .b..wb.
    11,    // bb..wb.
    -12,   // wb..wb.
    7,     // .w..wb.
    -16,   // bw..wb.
    21,    // ww..wb.
    -16,   // ..b.wb.
    -7,    // b.b.wb.
    -7,    // w.b.wb.
    -8,    // .bb.wb.
    0,     // bbb.wb.
    8,     // wbb.wb.
    0,     // .wb.wb.
    10,    // bwb.wb.
    -16,   // wwb.wb.
    -1,    // ..w.wb.
    5,     // b.w.wb.
    0,     // w.w.wb.
    21,    // .bw.wb.
    -1,    // bbw.wb.
    -1,    // wbw.wb.
    9,     // .ww.wb.
    -4,    // bww.wb.
    -17,   // www.wb.
    -2,    // ...bwb.
    -7,    // b..bwb.
    -6,    // w..bwb.
    4,     // .b.bwb.
    10,    // bb.bwb.
    -4,    // wb.bwb.
    -7,    // .w.bwb.
    -26,   // bw.bwb.
    -11,   // ww.bwb.
    -10,   // ..bbwb.
    -8,    // b.bbwb.
    -9,    // w.bbwb.
    -7,    // .bbbwb.
    5,     // bbbbwb.
    16,    // wbbbwb.
    -10,   // .wbbwb.
    5,     // bwbbwb.
    -19,   // wwbbwb.
    -16,   // ..wbwb.
    -29,   // b.wbwb.
    4,     // w.wbwb.
    5,     // .bwbwb.
    3,     // bbwbwb.
    5,     // wbwbwb.
    -12,   // .wwbwb.
    6,     // bwwbwb.
    2,     // wwwbwb.
    8,     // ...wwb.
    -14,   // b..wwb.
    -1,    // w..wwb.
    -16,   // .b.wwb.
    -8,    // bb.wwb.
    -29,   // wb.wwb.
    -16,   // .w.wwb.
    14,    // bw.wwb.
    -6,    // ww.wwb.
    8,     // ..bwwb.
    -22,   // b.bwwb.
    25,    // w.bwwb.
    -3,    // .bbwwb.
    -17,   // bbbwwb.
    -18,   // wbbwwb.
    10,    // .wbwwb.
    -11,   // bwbwwb.
    0,     // wwbwwb.
    -8,    // ..wwwb.
    -3,    // b.wwwb.
    -3,    // w.wwwb.
    5,     // .bwwwb.
    -23,   // bbwwwb.
    3,     // wbwwwb.
    -5,    // .wwwwb.
    -31,   // bwwwwb.
    -16,   // wwwwwb.
    -1,    // .....w.
    -8,    // b....w.
    -18,   // w....w.
    0,     // .b...w.
    9,     // bb...w.
    -9,    // wb...w.
    16,    // .w...w.
    4,     // bw...w.
    -17,   // ww...w.
    21,    // ..b..w.
    -5,    // b.b..w.
    1,     // w.b..w.
    -3,    // .bb..w.
    13,    // bbb..w.
    21,    // wbb..w.
    -8,    // .wb..w.
    3,     // bwb..w.
    10,    // wwb..w.
    4,     // ..w..w.
    -8,    // b.w..w.
    1,     // w.w..w.
    7,     // .bw..w.
    -1,    // bbw..w.
    24,    // wbw..w.
    -15,   // .ww..w.
    -34,   // bww..w.
    -20,   // www..w.
    -13,   // ...b.w.
    6,     // b..b.w.
    1,     // w..b.w.
    -6,    // .b.b.w.
    -5,    // bb.b.w.
    -2,    // wb.b.w.
    -33,   // .w.b.w.
    12,    // bw.b.w.
    21,    // ww.b.w.
    22,    // ..bb.w.
    10,    // b.bb.w.
    20,    // w.bb.w.
    3,     // .bbb.w.
    -6,    // bbbb.w.
    -8,    // wbbb.w.
    16,    // .wbb.w.
    6,     // bwbb.w.
    12,    // wwbb.w.
    15,    // ..wb.w.
    -10,   // b.wb.w.
    -22,   // w.wb.w.
    -7,    // .bwb.w.
    10,    // bbwb.w.
    -7,    // wbwb.w.
    0,     // .wwb.w.
    -6,    // bwwb.w.
    11,    // wwwb.w.
    11,    // ...w.w.
    -17,   // b..w.w.
    16,    // w..w.w.
    6,     // .b.w.w.
    22,    // bb.w.w.
    6,     // wb.w.w.
    15,    // .w.w.w.
    -11,   // bw.w.w.
    5,     // ww.w.w.
    -24,   // ..bw.w.
    -1,    // b.bw.w.
    21,    // w.bw.w.
    -4,    // .bbw.w.
    -3,    // bbbw.w.
    7,     // wbbw.w.
    -4,    // .wbw.w.
    8,     // bwbw.w.
    -15,   // wwbw.w.
    17,    // ..ww.w.
    20,    // b.ww.w.
    4,     // w.ww.w.
    -16,   // .bww.w.
    4,     // bbww.w.
    15,    // wbww.w.
    11,    // .www.w.
    -13,   // bwww.w.
    6,     // wwww.w.
    -32,   // ....bw.
    0,     // b...bw.
    -4,    // w...bw.
    -7,    // .b..bw.
    -21,   // bb..bw.
    16,    // wb..bw.
    -8,    // .w..bw.
    12,    // bw..bw.
    -11,   // ww..bw.
    1,     // ..b.bw.
    0,     // b.b.bw.
    -5,    // w.b.bw.
    -9,    // .bb.bw.
    17,    // bbb.bw.
    4,     // wbb.bw.
    -21,   // .wb.bw.
    1,     // bwb.bw.
    1,     // wwb.bw.
    16,    // ..w.bw.
    7,     // b.w.bw.
    7,     // w.w.bw.
    0,     // .bw.bw.
    16,    // bbw.bw.
    -10,   // wbw.bw.
    8,     // .ww.bw.
    -8,    // bww.bw.
    0,     // www.bw.
    -8,    // ...bbw.
    1,     // b..bbw.
    14,    // w..bbw.
    16,    // .b.bbw.
    6,     // bb.bbw.
    -14,   // wb.bbw.
    16,    // .w.bbw.
    29,    // bw.bbw.
    8,     // ww.bbw.
    8,     // ..bbbw.
    3,     // b.bbbw.
    3,     // w.bbbw.
    5,     // .bbbbw.
    16,    // bbbbbw.
    31,    // wbbbbw.
    -5,    // .wbbbw.
    -3,    // bwbbbw.
    23,    // wwbbbw.
    -8,    // ..wbbw.
    -25,   // b.wbbw.
    22,    // w.wbbw.
    -10,   // .bwbbw.
    0,     // bbwbbw.
    11,    // wbwbbw.
    3,     // .wwbbw.
    18,    // bwwbbw.
    17,    // wwwbbw.
    2,     // ...wbw.
    6,     // b..wbw.
    7,     // w..wbw.
    7,     // .b.wbw.
    11,    // bb.wbw.
    26,    // wb.wbw.
    -4,    // .w.wbw.
    4,     // bw.wbw.
    -10,   // ww.wbw.
    16,    // ..bwbw.
    -4,    // b.bwbw.
    29,    // w.bwbw.
    12,    // .bbwbw.
    -2,    // bbbwbw.
    -6,    // wbbwbw.
    -5,    // .wbwbw.
    -5,    // bwbwbw.
    -3,    // wwbwbw.
    10,    // ..wwbw.
    9,     // b.wwbw.
    8,     // w.wwbw.
    10,    // .bwwbw.
    19,    // bbwwbw.
    -5,    // wbwwbw.
    7,     // .wwwbw.
    -16,   // bwwwbw.
    -5,    // wwwwbw.
    11,    // ....ww.
    4,     // b...ww.
    3,     // w...ww.
    3,     // .b..ww.
    -20,   // bb..ww.
    -20,   // wb..ww.
    -15,   // .w..ww.
    8,     // bw..ww.
    10,    // ww..ww.
    -18,   // ..b.ww.
    0,     // b.b.ww.
    -6,    // w.b.ww.
    0,     // .bb.ww.
    16,    // bbb.ww.
    19,    // wbb.ww.
    8,     // .wb.ww.
    -19,   // bwb.ww.
    -4,    // wwb.ww.
    11,    // ..w.ww.
    -15,   // b.w.ww.
    8,     // w.w.ww.
    9,     // .bw.ww.
    1,     // bbw.ww.
    4,     // wbw.ww.
    -13,   // .ww.ww.
    -7,    // bww.ww.
    2,     // www.ww.
    -6,    // ...bww.
    12,    // b..bww.
    7,     // w..bww.
    4,     // .b.bww.
    -7,    // bb.bww.
    -22,   // wb.bww.
    0,     // .w.bww.
    2,     // bw.bww.
    -11,   // ww.bww.
    -28,   // ..bbww.
    -14,   // b.bbww.
    -13,   // w.bbww.
    -10,   // .bbbww.
    2,     // bbbbww.
    9,     // wbbbww.
    3,     // .wbbww.
    18,    // bwbbww.
    21,    // wwbbww.
    15,    // ..wbww.
    -23,   // b.wbww.
    18,    // w.wbww.
    -12,   // .bwbww.
    18,    // bbwbww.
    17,    // wbwbww.
    2,     // .wwbww.
    21,    // bwwbww.
    -9,    // wwwbww.
    -10,   // ...www.
    -1,    // b..www.
    -7,    // w..www.
    -3,    // .b.www.
    -4,    // bb.www.
    14,    // wb.www.
    11,    // .w.www.
    0,     // bw.www.
    -19,   // ww.www.
    14,    // ..bwww.
    29,    // b.bwww.
    -12,   // w.bwww.
    10,    // .bbwww.
    0,     // bbbwww.
    18,    // wbbwww.
    7,     // .wbwww.
    -19,   // bwbwww.
    -9,    // wwbwww.
    -20,   // ..wwww.
    -14,   // b.wwww.
    -36,   // w.wwww.
    -5,    // .bwwww.
    -12,   // bbwwww.
    12,    // wbwwww.
    -11,   // .wwwww.
    -8,    // bwwwww.
    -21,   // wwwwww.
    21,    // ......b
    -5,    // b.....b
    0,     // w.....b
    18,    // .b....b
    -13,   // bb....b
    -2,    // wb....b
    -8,    // .w....b
    19,    // bw....b
    17,    // ww....b
    3,     // ..b...b
    -23,   // b.b...b
    -16,   // w.b...b
    -3,    // .bb...b
    -2,    // bbb...b
    -12,   // wbb...b
    0,     // .wb...b
    -7,    // bwb...b
    9,     // wwb...b
    8,     // ..w...b
    2,     // b.w...b
    -1,    // w.w...b
    4,     // .bw...b
    -3,    // bbw...b
    18,    // wbw...b
    4,     // .ww...b
    8,     // bww...b
    7,     // www...b
    -3,    // ...b..b
    -7,    // b..b..b
    -9,    // w..b..b
    -16,   // .b.b..b
    -3,    // bb.b..b
    3,     // wb.b..b
    6,     // .w.b..b
    0,     // bw.b..b
    -2,    // ww.b..b
    -16,   // ..bb..b
    1,     // b.bb..b
    9,     // w.bb..b
    7,     // .bbb..b
    4,     // bbbb..b
    0,     // wbbb..b
    1,     // .wbb..b
    7,     // bwbb..b
    -9,    // wwbb..b
    7,     // ..wb..b
    -13,   // b.wb..b
    -14,   // w.wb..b
    -7,    // .bwb..b
    10,    // bbwb..b
    2,     // wbwb..b
    12,    // .wwb..b
    21,    // bwwb..b
    -10,   // wwwb..b
    -13,   // ...w..b
    14,    // b..w..b
    9,     // w..w..b
    -1,    // .b.w..b
    21,    // bb.w..b
    12,    // wb.w..b
    -17,   // .w.w..b
    -7,    // bw.w..b
    -4,    // ww.w..b
    -6,    // ..bw..b
    42,    // b.bw..b
    -12,   // w.bw..b
    -7,    // .bbw..b
    2,     // bbbw..b
    12,    // wbbw..b
    6,     // .wbw..b
    -18,   // bwbw..b
    0,     // wwbw..b
    18,    // ..ww..b
    23,    // b.ww..b
    3,     // w.ww..b
    -14,   // .bww..b
    1,     // bbww..b
    17,    // wbww..b
    -1,    // .www..b
    -12,   // bwww..b
    -1,    // wwww..b
    -25,   // ....b.b
    -23,   // b...b.b
    1,     // w...b.b
    -1,    // .b..b.b
    11,    // bb..b.b
    -23,   // wb..b.b
    -5,    // .w..b.b
    4,     // bw..b.b
    -17,   // ww..b.b
    12,    // ..b.b.b
    11,    // b.b.b.b
    7,     // w.b.b.b
    -8,    // .bb.b.b
    10,    // bbb.b.b
    16,    // wbb.b.b
    0,     // .wb.b.b
    36,    // bwb.b.b
    13,    // wwb.b.b
    2,     // ..w.b.b
    4,     // b.w.b.b
    0,     // w.w.b.b
    -7,    // .bw.b.b
    0,     // bbw.b.b
    12,    // wbw.b.b
    0,     // .ww.b.b
    -8,    // bww.b.b
    33,    // www.b.b
    -17,   // ...bb.b
    1,     // b..bb.b
    -3,    // w..bb.b
    -4,    // .b.bb.b
    -1,    // bb.bb.b
    9,     // wb.bb.b
    10,    // .w.bb.b
    14,    // bw.bb.b
    -16,   // ww.bb.b
    1,     // ..bbb.b
    8,     // b.bbb.b
    -2,    // w.bbb.b
    36,    // .bbbb.b
    -6,    // bbbbb.b
    11,    // wbbbb.b
    3,     // .wbbb.b
    -20,   // bwbbb.b
    -15,   // wwbbb.b
    37,    // ..wbb.b
    -3,    // b.wbb.b
    -7,    // w.wbb.b
    -8,    // .bwbb.b
    21,    // bbwbb.b
    19,    // wbwbb.b
    -14,   // .wwbb.b
    12,    // bwwbb.b
    -3,    // wwwbb.b
    -12,   // ...wb.b
    42,    // b..wb.b
    14,    // w..wb.b
    22,    // .b.wb.b
    12,    // bb.wb.b
    14,    // wb.wb.b
    -1,    // .w.wb.b
    5,     // bw.wb.b
    16,    // ww.wb.b
    0,     // ..bwb.b
    -5,    // b.bwb.b
    -15,   // w.bwb.b
    -18,   // .bbwb.b
    4,     // bbbwb.b
    -25,   // wbbwb.b
    -4,    // .wbwb.b
    -3,    // bwbwb.b
    21,    // wwbwb.b
    3,     // ..wwb.b
    -3,    // b.wwb.b
    7,     // w.wwb.b
    -22,   // .bwwb.b
    7,     // bbwwb.b
    1,     // wbwwb.b
    29,    // .wwwb.b
    -9,    // bwwwb.b
    -5,    // wwwwb.b
    16,    // ....w.b
    2,     // b...w.b
    16,    // w...w.b
    -1,    // .b..w.b
    -6,    // bb..w.b
    -35,   // wb..w.b
    -8,    // .w..w.b
    -20,   // bw..w.b
    2,     // ww..w.b
    -10,   // ..b.w.b
    4,     // b.b.w.b
    0,     // w.b.w.b
    6,     // .bb.w.b
    2,     // bbb.w.b
    14,    // wbb.w.b
    7,     // .wb.w.b
    14,    // bwb.w.b
    12,    // wwb.w.b
    -2,    // ..w.w.b
    -1,    // b.w.w.b
    -7,    // w.w.w.b
    5,     // .bw.w.b
    7,     // bbw.w.b
    -5,    // wbw.w.b
    -15,   // .ww.w.b
    12,    // bww.w.b
    16,    // www.w.b
    19,    // ...bw.b
    -13,   // b..bw.b
    12,    // w..bw.b
    -21,   // .b.bw.b
    -4,    // bb.bw.b
    -11,   // wb.bw.b
    -10,   // .w.bw.b
    1,     // bw.bw.b
    -7,    // ww.bw.b
    -6,    // ..bbw.b
    -3,    // b.bbw.b
    -16,   // w.bbw.b
    12,    // .bbbw.b
    17,    // bbbbw.b
    3,     // wbbbw.b
    -25,   // .wbbw.b
    -17,   // bwbbw.b
    -13,   // wwbbw.b
    3,     // ..wbw.b
    -8,    // b.wbw.b
    15,    // w.wbw.b
    -29,   // .bwbw.b
    3,     // bbwbw.b
    -4,    // wbwbw.b
    -23,   // .wwbw.b
    -1,    // bwwbw.b
    0,     // wwwbw.b
    11,    // ...ww.b
    23,    // b..ww.b
    -9,    // w..ww.b
    -20,   // .b.ww.b
    8,     // bb.ww.b
    -19,   // wb.ww.b
    20,    // .w.ww.b
    -16,   // bw.ww.b
    -8,    // ww.ww.b
    -7,    // ..bww.b
    -3,    // b.bww.b
    16,    // w.bww.b
    13,    // .bbww.b
    0,     // bbbww.b
    2,     // wbbww.b
    9,     // .wbww.b
    3,     // bwbww.b
    4,     // wwbww.b
    -18,   // ..www.b
    -4,    // b.www.b
    2,     // w.www.b
    -3,    // .bwww.b
    26,    // bbwww.b
    12,    // wbwww.b
    -14,   // .wwww.b
    -3,    // bwwww.b
    0,     // wwwww.b
    8,     // .....bb
    -13,   // b....bb
    -17,   // w....bb
    17,    // .b...bb
    -13,   // bb...bb
    1,     // wb...bb
    9,     // .w...bb
    -5,    // bw...bb
    0,     // ww...bb
    8,     // ..b..bb
    11,    // b.b..bb
    -2,    // w.b..bb
    -10,   // .bb..bb
    -7,    // bbb..bb
    0,     // wbb..bb
    -21,   // .wb..bb
    4,     // bwb..bb
    -3,    // wwb..bb
    -8,    // ..w..bb
    -6,    // b.w..bb
    17,    // w.w..bb
    11,    // .bw..bb
    1,     // bbw..bb
    9,     // wbw..bb
    -20,   // .ww..bb
    -1,    // bww..bb
    -8,    // www..bb
    7,     // ...b.bb
    -3,    // b..b.bb
    4,     // w..b.bb
    -5,    // .b.b.bb
    0,     // bb.b.bb
    3,     // wb.b.bb
    -5,    // .w.b.bb
    6,     // bw.b.bb
    -20,   // ww.b.bb
    -1,    // ..bb.bb
    -1,    // b.bb.bb
    8,     // w.bb.bb
    19,    // .bbb.bb
    -11,   // bbbb.bb
    14,    // wbbb.bb
    6,     // .wbb.bb
    6,     // bwbb.bb
    9,     // wwbb.bb
    -7,    // ..wb.bb
    -4,    // b.wb.bb
    -16,   // w.wb.bb
    10,    // .bwb.bb
    -2,    // bbwb.bb
    -1,    // wbwb.bb
    -7,    // .wwb.bb
    25,    // bwwb.bb
    5,     // wwwb.bb
    -11,   // ...w.bb
    21,    // b..w.bb
    2,     // w..w.bb
    -21,   // .b.w.bb
    -11,   // bb.w.bb
    -4,    // wb.w.bb
    22,    // .w.w.bb
    -1,    // bw.w.bb
    20,    // ww.w.bb
    -1,    // ..bw.bb
    12,    // b.bw.bb
    7,     // w.bw.bb
    11,    // .bbw.bb
    2,     // bbbw.bb
    9,     // wbbw.bb
    11,    // .wbw.bb
    7,     // bwbw.bb
    -5,    // wwbw.bb
    -17,   // ..ww.bb
    8,     // b.ww.bb
    16,    // w.ww.bb
    -8,    // .bww.bb
    -10,   // bbww.bb
    -12,   // wbww.bb
    -4,    // .www.bb
    -5,    // bwww.bb
    -4,    // wwww.bb
    16,    // ....bbb
    -2,    // b...bbb
    -7,    // w...bbb
    20,    // .b..bbb
    -7,    // bb..bbb
    -1,    // wb..bbb
    13,    // .w..bbb
    10,    // bw..bbb
    8,     // ww..bbb
    30,    // ..b.bbb
    10,    // b.b.bbb
    -16,   // w.b.bbb
    -2,    // .bb.bbb
    30,    // bbb.bbb
    20,    // wbb.bbb
    17,    // .wb.bbb
    12,    // bwb.bbb
    -2,    // wwb.bbb
    20,    // ..w.bbb
    2,     // b.w.bbb
    -33,   // w.w.bbb
    0,     // .bw.bbb
    11,    // bbw.bbb
    -4,    // wbw.bbb
    16,    // .ww.bbb
    -20,   // bww.bbb
    0,     // www.bbb
    52,    // ...bbbb
    4,     // b..bbbb
    1,     // w..bbbb
    -6,    // .b.bbbb
    -11,   // bb.bbbb
    -8,    // wb.bbbb
    -6,    // .w.bbbb
    13,    // bw.bbbb
    4,     // ww.bbbb
    -11,   // ..bbbbb
    -6,    // b.bbbbb
    0,     // w.bbbbb
    21,    // .bbbbbb
    -11,   // bbbbbbb
    -12,   // wbbbbbb
    16,    // .wbbbbb
    19,    // bwbbbbb
    -9,    // wwbbbbb
    -8,    // ..wbbbb
    17,    // b.wbbbb
    5,     // w.wbbbb
    5,     // .bwbbbb
    1,     // bbwbbbb
    -16,   // wbwbbbb
    2,     // .wwbbbb
    6,     // bwwbbbb
    22,    // wwwbbbb
    -8,    // ...wbbb
    2,     // b..wbbb
    10,    // w..wbbb
    -11,   // .b.wbbb
    2,     // bb.wbbb
    -14,   // wb.wbbb
    -3,    // .w.wbbb
    3,     // bw.wbbb
    -5,    // ww.wbbb
    15,    // ..bwbbb
    4,     // b.bwbbb
    0,     // w.bwbbb
    9,     // .bbwbbb
    8,     // bbbwbbb
    6,     // wbbwbbb
    -2,    // .wbwbbb
    -2,    // bwbwbbb
    15,    // wwbwbbb
    -1,    // ..wwbbb
    0,     // b.wwbbb
    3,     // w.wwbbb
    -17,   // .bwwbbb
    7,     // bbwwbbb
    -11,   // wbwwbbb
    0,     // .wwwbbb
    -7,    // bwwwbbb
    -22,   // wwwwbbb
    -18,   // ....wbb
    -3,    // b...wbb
    -9,    // w...wbb
    -10,   // .b..wbb
    1,     // bb..wbb
    5,     // wb..wbb
    -1,    // .w..wbb
    19,    // bw..wbb
    3,     // ww..wbb
    -31,   // ..b.wbb
    0,     // b.b.wbb
    -12,   // w.b.wbb
    4,     // .bb.wbb
    11,    // bbb.wbb
    -11,   // wbb.wbb
    16,    // .wb.wbb
    47,    // bwb.wbb
    0,     // wwb.wbb
    -8,    // ..w.wbb
    7,     // b.w.wbb
    -13,   // w.w.wbb
    -1,    // .bw.wbb
    -13,   // bbw.wbb
    -12,   // wbw.wbb
    1,     // .ww.wbb
    -5,    // bww.wbb
    2,     // www.wbb
    -4,    // ...bwbb
    10,    // b..bwbb
    0,     // w..bwbb
    15,    // .b.bwbb
    -2,    // bb.bwbb
    -3,    // wb.bwbb
    10,    // .w.bwbb
    -2,    // bw.bwbb
    5,     // ww.bwbb
    8,     // ..bbwbb
    21,    // b.bbwbb
    -4,    // w.bbwbb
    9,     // .bbbwbb
    1,     // bbbbwbb
    19,    // wbbbwbb
    0,     // .wbbwbb
    -10,   // bwbbwbb
    -12,   // wwbbwbb
    19,    // ..wbwbb
    3,     // b.wbwbb
    -21,   // w.wbwbb
    3,     // .bwbwbb
    0,     // bbwbwbb
    2,     // wbwbwbb
    18,    // .wwbwbb
    -13,   // bwwbwbb
    -15,   // wwwbwbb
    -6,    // ...wwbb
    1,     // b..wwbb
    9,     // w..wwbb
    -12,   // .b.wwbb
    -10,   // bb.wwbb
    -21,   // wb.wwbb
    4,     // .w.wwbb
    3,     // bw.wwbb
    -9,    // ww.wwbb
    15,    // ..bwwbb
    7,     // b.bwwbb
    13,    // w.bwwbb
    -21,   // .bbwwbb
    7,     // bbbwwbb
    6,     // wbbwwbb
    19,    // .wbwwbb
    -3,    // bwbwwbb
    12,    // wwbwwbb
    2,     // ..wwwbb
    26,    // b.wwwbb
    15,    // w.wwwbb
    -23,   // .bwwwbb
    0,     // bbwwwbb
    14,    // wbwwwbb
    -12,   // .wwwwbb
    13,    // bwwwwbb
    9,     // wwwwwbb
    1,     // .....wb
    19,    // b....wb
    2,     // w....wb
    9,     // .b...wb
    -5,    // bb...wb
    0,     // wb...wb
    4,     // .w...wb
    18,    // bw...wb
    -1,    // ww...wb
    -3,    // ..b..wb
    4,     // b.b..wb
    35,    // w.b..wb
    20,    // .bb..wb
    10,    // bbb..wb
    4,     // wbb..wb
    12,    // .wb..wb
    -1,    // bwb..wb
    -5,    // wwb..wb
    15,    // ..w..wb
    -20,   // b.w..wb
    23,    // w.w..wb
    -16,   // .bw..wb
    19,    // bbw..wb
    11,    // wbw..wb
    8,     // .ww..wb
    -11,   // bww..wb
    1,     // www..wb
    1,     // ...b.wb
    0,     // b..b.wb
    -12,   // w..b.wb
    -6,    // .b.b.wb
    6,     // bb.b.wb
    17,    // wb.b.wb
    12,    // .w.b.wb
    -25,   // bw.b.wb
    4,     // ww.b.wb
    -3,    // ..bb.wb
    14,    // b.bb.wb
    19,    // w.bb.wb
    -14,   // .bbb.wb
    13,    // bbbb.wb
    1,     // wbbb.wb
    29,    // .wbb.wb
    -12,   // bwbb.wb
    21,    // wwbb.wb
    -6,    // ..wb.wb
    1,     // b.wb.wb
    -14,   // w.wb.wb
    -26,   // .bwb.wb
    -2,    // bbwb.wb
    -13,   // wbwb.wb
    2,     // .wwb.wb
    -7,    // bwwb.wb
    14,    // wwwb.wb
    14,    // ...w.wb
    -7,    // b..w.wb
    -3,    // w..w.wb
    2,     // .b.w.wb
    -1,    // bb.w.wb
    -17,   // wb.w.wb
    -11,   // .w.w.wb
    -3,    // bw.w.wb
    -3,    // ww.w.wb
    23,    // ..bw.wb
    5,     // b.bw.wb
    11,    // w.bw.wb
    22,    // .bbw.wb
    3,     // bbbw.wb
    -6,    // wbbw.wb
    4,     // .wbw.wb
    4,     // bwbw.wb
    3,     // wwbw.wb
    27,    // ..ww.wb
    -16,   // b.ww.wb
    -9,    // w.ww.wb
    14,    // .bww.wb
    3,     // bbww.wb
    6,     // wbww.wb
    0,     // .www.wb
    10,    // bwww.wb
    8,     // wwww.wb
    -25,   // ....bwb
    -7,    // b...bwb
    -18,   // w...bwb
    -24,   // .b..bwb
    4,     // bb..bwb
    -11,   // wb..bwb
    3,     // .w..bwb
    -1,    // bw..bwb
    -9,    // ww..bwb
    13,    // ..b.bwb
    36,    // b.b.bwb
    5,     // w.b.bwb
    -4,    // .bb.bwb
    12,    // bbb.bwb
    -2,    // wbb.bwb
    1,     // .wb.bwb
    15,    // bwb.bwb
    12,    // wwb.bwb
    9,     // ..w.bwb
    14,    // b.w.bwb
    -12,   // w.w.bwb
    10,    // .bw.bwb
    47,    // bbw.bwb
    0,     // wbw.bwb
    -19,   // .ww.bwb
    -2,    // bww.bwb
    4,     // www.bwb
    -23,   // ...bbwb
    7,     // b..bbwb
    -17,   // w..bbwb
    -15,   // .b.bbwb
    6,     // bb.bbwb
    -6,    // wb.bbwb
    6,     // .w.bbwb
    -12,   // bw.bbwb
    12,    // ww.bbwb
    6,     // ..bbbwb
    -20,   // b.bbbwb
    -12,   // w.bbbwb
    -12,   // .bbbbwb
    19,    // bbbbbwb
    -4,    // wbbbbwb
    -3,    // .wbbbwb
    -1,    // bwbbbwb
    -14,   // wwbbbwb
    9,     // ..wbbwb
    -17,   // b.wbbwb
    -1,    // w.wbbwb
    5,     // .bwbbwb
    -10,   // bbwbbwb
    -13,   // wbwbbwb
    18,    // .wwbbwb
    -10,   // bwwbbwb
    11,    // wwwbbwb
    6,     // ...wbwb
    -18,   // b..wbwb
    -2,    // w..wbwb
    7,     // .b.wbwb
    7,     // bb.wbwb
    13,    // wb.wbwb
    8,     // .w.wbwb
    4,     // bw.wbwb
    1,     // ww.wbwb
    1,     // ..bwbwb
    -3,    // b.bwbwb
    4,     // w.bwbwb
    -17,   // .bbwbwb
    -2,    // bbbwbwb
    -23,   // wbbwbwb
    -5,    // .wbwbwb
    3,     // bwbwbwb
    -2,    // wwbwbwb
    -10,   // ..wwbwb
    3,     // b.wwbwb
    -19,   // w.wwbwb
    -11,   // .bwwbwb
    -3,    // bbwwbwb
    13,    // wbwwbwb
    -19,   // .wwwbwb
    8,     // bwwwbwb
    16,    // wwwwbwb
    8,     // ....wwb
    8,     // b...wwb
    12,    // w...wwb
    -21,   // .b..wwb
    -1,    // bb..wwb
    -4,    // wb..wwb
    -34,   // .w..wwb
    -11,   // bw..wwb
    0,     // ww..wwb
    0,     // ..b.wwb
    -8,    // b.b.wwb
    -14,   // w.b.wwb
    -19,   // .bb.wwb
    -20,   // bbb.wwb
    0,     // wbb.wwb
    -8,    // .wb.wwb
    -2,    // bwb.wwb
    11,    // wwb.wwb
    5,     // ..w.wwb
    12,    // b.w.wwb
    -16,   // w.w.wwb
    -4,    // .bw.wwb
    -5,    // bbw.wwb
    2,     // wbw.wwb
    -7,    // .ww.wwb
    2,     // bww.wwb
    -20,   // www.wwb
    -2,    // ...bwwb
    21,    // b..bwwb
    -12,   // w..bwwb
    -7,    // .b.bwwb
    25,    // bb.bwwb
    6,     // wb.bwwb
    -6,    // .w.bwwb
    -7,    // bw.bwwb
    -9,    // ww.bwwb
    11,    // ..bbwwb
    12,    // b.bbwwb
    -2,    // w.bbwwb
    -18,   // .bbbwwb
    6,     // bbbbwwb
    -7,    // wbbbwwb
    18,    // .wbbwwb
    -10,   // bwbbwwb
    -6,    // wwbbwwb
    1,     // ..wbwwb
    -1,    // b.wbwwb
    25,    // w.wbwwb
    6,     // .bwbwwb
    -13,   // bbwbwwb
    23,    // wbwbwwb
    21,    // .wwbwwb
    -4,    // bwwbwwb
    -6,    // wwwbwwb
    8,     // ...wwwb
    -12,   // b..wwwb
    0,     // w..wwwb
    8,     // .b.wwwb
    -5,    // bb.wwwb
    -1,    // wb.wwwb
    -13,   // .w.wwwb
    10,    // bw.wwwb
    -14,   // ww.wwwb
    -6,    // ..bwwwb
    -9,    // b.bwwwb
    -3,    // w.bwwwb
    -9,    // .bbwwwb
    -7,    // bbbwwwb
    7,     // wbbwwwb
    -16,   // .wbwwwb
    8,     // bwbwwwb
    -19,   // wwbwwwb
    -15,   // ..wwwwb
    -3,    // b.wwwwb
    -11,   // w.wwwwb
    -31,   // .bwwwwb
    13,    // bbwwwwb
    4,     // wbwwwwb
    -8,    // .wwwwwb
    7,     // bwwwwwb
    12,    // wwwwwwb
    -21,   // ......w
    0,     // b.....w
    5,     // w.....w
    8,     // .b....w
    -17,   // bb....w
    -19,   // wb....w
    -18,   // .w....w
    2,     // bw....w
    13,    // ww....w
    -8,    // ..b...w
    1,     // b.b...w
    -2,    // w.b...w
    -4,    // .bb...w
    -7,    // bbb...w
    -8,    // wbb...w
    -4,    // .wb...w
    -18,   // bwb...w
    3,     // wwb...w
    -3,    // ..w...w
    16,    // b.w...w
    23,    // w.w...w
    0,     // .bw...w
    -9,    // bbw...w
    7,     // wbw...w
    3,     // .ww...w
    12,    // bww...w
    2,     // www...w
    13,    // ...b..w
    -9,    // b..b..w
    -14,   // w..b..w
    17,    // .b.b..w
    4,     // bb.b..w
    7,     // wb.b..w
    1,     // .w.b..w
    -12,   // bw.b..w
    -21,   // ww.b..w
    -18,   // ..bb..w
    -3,    // b.bb..w
    -23,   // w.bb..w
    1,     // .bbb..w
    1,     // bbbb..w
    12,    // wbbb..w
    14,    // .wbb..w
    -17,   // bwbb..w
    -1,    // wwbb..w
    6,     // ..wb..w
    12,    // b.wb..w
    -42,   // w.wb..w
    -6,    // .bwb..w
    0,     // bbwb..w
    18,    // wbwb..w
    7,     // .wwb..w
    -12,   // bwwb..w
    -2,    // wwwb..w
    3,     // ...w..w
    9,     // b..w..w
    7,     // w..w..w
    -6,    // .b.w..w
    2,     // bb.w..w
    0,     // wb.w..w
    16,    // .w.w..w
    -3,    // bw.w..w
    3,     // ww.w..w
    -7,    // ..bw..w
    14,    // b.bw..w
    13,    // w.bw..w
    -12,   // .bbw..w
    10,    // bbbw..w
    -21,   // wbbw..w
    7,     // .wbw..w
    -2,    // bwbw..w
    -10,   // wwbw..w
    16,    // ..ww..w
    -9,    // b.ww..w
    -1,    // w.ww..w
    -1,    // .bww..w
    9,     // bbww..w
    -7,    // wbww..w
    -7,    // .www..w
    0,     // bwww..w
    -4,    // wwww..w
    -16,   // ....b.w
    -16,   // b...b.w
    -2,    // w...b.w
    8,     // .b..b.w
    -2,    // bb..b.w
    20,    // wb..b.w
    1,     // .w..b.w
    35,    // bw..b.w
    6,     // ww..b.w
    2,     // ..b.b.w
    7,     // b.b.b.w
    1,     // w.b.b.w
    15,    // .bb.b.w
    -16,   // bbb.b.w
    -12,   // wbb.b.w
    -5,    // .wb.b.w
    5,     // bwb.b.w
    -7,    // wwb.b.w
    10,    // ..w.b.w
    0,     // b.w.b.w
    -4,    // w.w.b.w
    -7,    // .bw.b.w
    -12,   // bbw.b.w
    -14,   // wbw.b.w
    -6,    // .ww.b.w
    -14,   // bww.b.w
    -2,    // www.b.w
    -11,   // ...bb.w
    9,     // b..bb.w
    -23,   // w..bb.w
    -20,   // .b.bb.w
    8,     // bb.bb.w
    16,    // wb.bb.w
    20,    // .w.bb.w
    19,    // bw.bb.w
    -8,    // ww.bb.w
    18,    // ..bbb.w
    -2,    // b.bbb.w
    4,     // w.bbb.w
    14,    // .bbbb.w
    0,     // bbbbb.w
    3,     // wbbbb.w
    3,     // .wbbb.w
    -12,   // bwbbb.w
    -26,   // wwbbb.w
    7,     // ..wbb.w
    -16,   // b.wbb.w
    3,     // w.wbb.w
    -9,    // .bwbb.w
    -4,    // bbwbb.w
    -3,    // wbwbb.w
    -13,   // .wwbb.w
    -2,    // bwwbb.w
    0,     // wwwbb.w
    -19,   // ...wb.w
    -12,   // b..wb.w
    13,    // w..wb.w
    10,    // .b.wb.w
    7,     // bb.wb.w
    -1,    // wb.wb.w
    21,    // .w.wb.w
    11,    // bw.wb.w
    4,     // ww.wb.w
    -3,    // ..bwb.w
    -15,   // b.bwb.w
    8,     // w.bwb.w
    23,    // .bbwb.w
    0,     // bbbwb.w
    1,     // wbbwb.w
    29,    // .wbwb.w
    4,     // bwbwb.w
    -3,    // wwbwb.w
    6,     // ..wwb.w
    16,    // b.wwb.w
    3,     // w.wwb.w
    25,    // .bwwb.w
    13,    // bbwwb.w
    17,    // wbwwb.w
    -12,   // .wwwb.w
    -3,    // bwwwb.w
    -17,   // wwwwb.w
    25,    // ....w.w
    -1,    // b...w.w
    23,    // w...w.w
    5,     // .b..w.w
    17,    // bb..w.w
    -4,    // wb..w.w
    1,     // .w..w.w
    23,    // bw..w.w
    -11,   // ww..w.w
    -2,    // ..b.w.w
    0,     // b.b.w.w
    -4,    // w.b.w.w
    0,     // .bb.w.w
    -33,   // bbb.w.w
    8,     // wbb.w.w
    7,     // .wb.w.w
    -12,   // bwb.w.w
    0,     // wwb.w.w
    -12,   // ..w.w.w
    -7,    // b.w.w.w
    -11,   // w.w.w.w
    0,     // .bw.w.w
    -13,   // bbw.w.w
    -36,   // wbw.w.w
    8,     // .ww.w.w
    -16,   // bww.w.w
    -10,   // www.w.w
    12,    // ...bw.w
    -14,   // b..bw.w
    -42,   // w..bw.w
    1,     // .b.bw.w
    -16,   // bb.bw.w
    -5,    // wb.bw.w
    -22,   // .w.bw.w
    -14,   // bw.bw.w
    -12,   // ww.bw.w
    -3,    // ..bbw.w
    -7,    // b.bbw.w
    3,     // w.bbw.w
    -29,   // .bbbw.w
    5,     // bbbbw.w
    9,     // wbbbw.w
    22,    // .wbbw.w
    -1,    // bwbbw.w
    -7,    // wwbbw.w
    0,     // ..wbw.w
    15,    // b.wbw.w
    5,     // w.wbw.w
    4,     // .bwbw.w
    -21,   // bbwbw.w
    3,     // wbwbw.w
    18,    // .wwbw.w
    25,    // bwwbw.w
    -4,    // wwwbw.w
    17,    // ...ww.w
    3,     // b..ww.w
    -1,    // w..ww.w
    -10,   // .b.ww.w
    16,    // bb.ww.w
    -14,   // wb.ww.w
    4,     // .w.ww.w
    -9,    // bw.ww.w
    1,     // ww.ww.w
    -37,   // ..bww.w
    7,     // b.bww.w
    3,     // w.bww.w
    14,    // .bbww.w
    3,     // bbbww.w
    -12,   // wbbww.w
    8,     // .wbww.w
    -19,   // bwbww.w
    -21,   // wwbww.w
    -1,    // ..www.w
    2,     // b.www.w
    -8,    // w.www.w
    -3,    // .bwww.w
    15,    // bbwww.w
    20,    // wbwww.w
    -36,   // .wwww.w
    -11,   // bwwww.w
    6,     // wwwww.w
    -1,    // .....bw
    -2,    // b....bw
    -19,   // w....bw
    -4,    // .b...bw
    1,     // bb...bw
    -18,   // wb...bw
    -9,    // .w...bw
    0,     // bw...bw
    5,     // ww...bw
    -15,   // ..b..bw
    -23,   // b.b..bw
    20,    // w.b..bw
    -8,    // .bb..bw
    -1,    // bbb..bw
    11,    // wbb..bw
    16,    // .wb..bw
    -11,   // bwb..bw
    -19,   // wwb..bw
    3,     // ..w..bw
    -35,   // b.w..bw
    -4,    // w.w..bw
    -12,   // .bw..bw
    5,     // bbw..bw
    1,     // wbw..bw
    -20,   // .ww..bw
    -4,    // bww..bw
    -10,   // www..bw
    -14,   // ...b.bw
    3,     // b..b.bw
    7,     // w..b.bw
    11,    // .b.b.bw
    3,     // bb.b.bw
    3,     // wb.b.bw
    -2,    // .w.b.bw
    17,    // bw.b.bw
    1,     // ww.b.bw
    -27,   // ..bb.bw
    9,     // b.bb.bw
    16,    // w.bb.bw
    0,     // .bbb.bw
    -8,    // bbbb.bw
    -10,   // wbbb.bw
    -14,   // .wbb.bw
    -6,    // bwbb.bw
    -3,    // wwbb.bw
    -23,   // ..wb.bw
    -11,   // b.wb.bw
    -5,    // w.wb.bw
    -4,    // .bwb.bw
    -3,    // bbwb.bw
    -4,    // wbwb.bw
    -22,   // .wwb.bw
    6,     // bwwb.bw
    -3,    // wwwb.bw
    -1,    // ...w.bw
    12,    // b..w.bw
    0,     // w..w.bw
    -12,   // .b.w.bw
    -4,    // bb.w.bw
    25,    // wb.w.bw
    6,     // .w.w.bw
    -17,   // bw.w.bw
    -6,    // ww.w.bw
    6,     // ..bw.bw
    14,    // b.bw.bw
    -1,    // w.bw.bw
    -2,    // .bbw.bw
    -14,   // bbbw.bw
    7,     // wbbw.bw
    26,    // .wbw.bw
    13,    // bwbw.bw
    2,     // wwbw.bw
    3,     // ..ww.bw
    -19,   // b.ww.bw
    -14,   // w.ww.bw
    -29,   // .bww.bw
    -21,   // bbww.bw
    12,    // wbww.bw
    14,    // .www.bw
    -1,    // bwww.bw
    -13,   // wwww.bw
    -8,    // ....bbw
    -12,   // b...bbw
    -8,    // w...bbw
    34,    // .b..bbw
    0,     // bb..bbw
    11,    // wb..bbw
    21,    // .w..bbw
    4,     // bw..bbw
    1,     // ww..bbw
    -5,    // ..b.bbw
    16,    // b.b.bbw
    -12,   // w.b.bbw
    7,     // .bb.bbw
    20,    // bbb.bbw
    -2,    // wbb.bbw
    4,     // .wb.bbw
    -2,    // bwb.bbw
    5,     // wwb.bbw
    0,     // ..w.bbw
    14,    // b.w.bbw
    8,     // w.w.bbw
    8,     // .bw.bbw
    -11,   // bbw.bbw
    2,     // wbw.bbw
    19,    // .ww.bbw
    0,     // bww.bbw
    20,    // www.bbw
    -8,    // ...bbbw
    0,     // b..bbbw
    12,    // w..bbbw
    13,    // .b.bbbw
    14,    // bb.bbbw
    -10,   // wb.bbbw
    -8,    // .w.bbbw
    1,     // bw.bbbw
    5,     // ww.bbbw
    15,    // ..bbbbw
    11,    // b.bbbbw
    3,     // w.bbbbw
    8,     // .bbbbbw
    -12,   // bbbbbbw
    -7,    // wbbbbbw
    31,    // .wbbbbw
    -4,    // bwbbbbw
    -13,   // wwbbbbw
    6,     // ..wbbbw
    3,     // b.wbbbw
    9,     // w.wbbbw
    16,    // .bwbbbw
    19,    // bbwbbbw
    -8,    // wbwbbbw
    9,     // .wwbbbw
    -7,    // bwwbbbw
    7,     // wwwbbbw
    2,     // ...wbbw
    12,    // b..wbbw
    -21,   // w..wbbw
    6,     // .b.wbbw
    9,     // bb.wbbw
    7,     // wb.wbbw
    7,     // .w.wbbw
    -6,    // bw.wbbw
    -25,   // ww.wbbw
    -1,    // ..bwbbw
    -25,   // b.bwbbw
    1,     // w.bwbbw
    -21,   // .bbwbbw
    6,     // bbbwbbw
    4,     // wbbwbbw
    -6,    // .wbwbbw
    -23,   // bwbwbbw
    13,    // wwbwbbw
    -11,   // ..wwbbw
    2,     // b.wwbbw
    -12,   // w.wwbbw
    -18,   // .bwwbbw
    6,     // bbwwbbw
    10,    // wbwwbbw
    18,    // .wwwbbw
    7,     // bwwwbbw
    -6,    // wwwwbbw
    25,    // ....wbw
    18,    // b...wbw
    7,     // w...wbw
    -3,    // .b..wbw
    9,     // bb..wbw
    1,     // wb..wbw
    24,    // .w..wbw
    11,    // bw..wbw
    -4,    // ww..wbw
    -9,    // ..b.wbw
    12,    // b.b.wbw
    -14,   // w.b.wbw
    19,    // .bb.wbw
    -4,    // bbb.wbw
    2,     // wbb.wbw
    -10,   // .wb.wbw
    0,     // bwb.wbw
    -47,   // wwb.wbw
    -13,   // ..w.wbw
    -5,    // b.w.wbw
    -36,   // w.w.wbw
    -1,    // .bw.wbw
    -12,   // bbw.wbw
    -15,   // wbw.wbw
    4,     // .ww.wbw
    2,     // bww.wbw
    -12,   // www.wbw
    -6,    // ...bwbw
    2,     // b..bwbw
    18,    // w..bwbw
    -8,    // .b.bwbw
    -1,    // bb.bwbw
    -4,    // wb.bwbw
    -7,    // .w.bwbw
    -13,   // bw.bwbw
    -7,    // ww.bwbw
    10,    // ..bbwbw
    19,    // b.bbwbw
    -3,    // w.bbwbw
    19,    // .bbbwbw
    -16,   // bbbbwbw
    -8,    // wbbbwbw
    11,    // .wbbwbw
    -13,   // bwbbwbw
    3,     // wwbbwbw
    -1,    // ..wbwbw
    -4,    // b.wbwbw
    3,     // w.wbwbw
    5,     // .bwbwbw
    2,     // bbwbwbw
    -3,    // wbwbwbw
    17,    // .wwbwbw
    23,    // bwwbwbw
    2,     // wwwbwbw
    23,    // ...wwbw
    17,    // b..wwbw
    -7,    // w..wwbw
    -6,    // .b.wwbw
    -12,   // bb.wwbw
    12,    // wb.wwbw
    15,    // .w.wwbw
    6,     // bw.wwbw
    -6,    // ww.wwbw
    -9,    // ..bwwbw
    1,     // b.bwwbw
    17,    // w.bwwbw
    -18,   // .bbwwbw
    -11,   // bbbwwbw
    10,    // wbbwwbw
    -5,    // .wbwwbw
    13,    // bwbwwbw
    10,    // wwbwwbw
    -6,    // ..wwwbw
    12,    // b.wwwbw
    20,    // w.wwwbw
    3,     // .bwwwbw
    14,    // bbwwwbw
    1,     // wbwwwbw
    12,    // .wwwwbw
    4,     // bwwwwbw
    -19,   // wwwwwbw
    -8,    // .....ww
    17,    // b....ww
    13,    // w....ww
    -9,    // .b...ww
    0,     // bb...ww
    5,     // wb...ww
    -17,   // .w...ww
    -1,    // bw...ww
    13,    // ww...ww
    8,     // ..b..ww
    -17,   // b.b..ww
    6,     // w.b..ww
    20,    // .bb..ww
    8,     // bbb..ww
    1,     // wbb..ww
    -11,   // .wb..ww
    -9,    // bwb..ww
    -1,    // wwb..ww
    -8,    // ..w..ww
    2,     // b.w..ww
    -11,   // w.w..ww
    21,    // .bw..ww
    3,     // bbw..ww
    -4,    // wbw..ww
    10,    // .ww..ww
    0,     // bww..ww
    7,     // www..ww
    11,    // ...b.ww
    -2,    // b..b.ww
    -21,   // w..b.ww
    -22,   // .b.b.ww
    -20,   // bb.b.ww
    1,     // wb.b.ww
    21,    // .w.b.ww
    4,     // bw.b.ww
    11,    // ww.b.ww
    17,    // ..bb.ww
    -16,   // b.bb.ww
    -8,    // w.bb.ww
    4,     // .bbb.ww
    4,     // bbbb.ww
    5,     // wbbb.ww
    8,     // .wbb.ww
    12,    // bwbb.ww
    10,    // wwbb.ww
    1,     // ..wb.ww
    -7,    // b.wb.ww
    -12,   // w.wb.ww
    -11,   // .bwb.ww
    5,     // bbwb.ww
    -7,    // wbwb.ww
    -11,   // .wwb.ww
    -9,    // bwwb.ww
    -2,    // wwwb.ww
    -7,    // ...w.ww
    -4,    // b..w.ww
    3,     // w..w.ww
    5,     // .b.w.ww
    20,    // bb.w.ww
    -6,    // wb.w.ww
    5,     // .w.w.ww
    -3,    // bw.w.ww
    0,     // ww.w.ww
    7,     // ..bw.ww
    16,    // b.bw.ww
    4,     // w.bw.ww
    7,     // .bbw.ww
    -5,    // bbbw.ww
    -25,   // wbbw.ww
    -10,   // .wbw.ww
    1,     // bwbw.ww
    2,     // wwbw.ww
    1,     // ..ww.ww
    -8,    // b.ww.ww
    1,     // w.ww.ww
    -6,    // .bww.ww
    -9,    // bbww.ww
    -6,    // wbww.ww
    -19,   // .www.ww
    -14,   // bwww.ww
    11,    // wwww.ww
    18,    // ....bww
    9,     // b...bww
    3,     // w...bww
    1,     // .b..bww
    -3,    // bb..bww
    -19,   // wb..bww
    10,    // .w..bww
    -5,    // bw..bww
    -1,    // ww..bww
    8,     // ..b.bww
    13,    // b.b.bww
    -7,    // w.b.bww
    -1,    // .bb.bww
    -2,    // bbb.bww
    5,     // wbb.bww
    1,     // .wb.bww
    12,    // bwb.bww
    13,    // wwb.bww
    31,    // ..w.bww
    12,    // b.w.bww
    0,     // w.w.bww
    -16,   // .bw.bww
    0,     // bbw.bww
    -47,   // wbw.bww
    -4,    // .ww.bww
    11,    // bww.bww
    -11,   // www.bww
    6,     // ...bbww
    -9,    // b..bbww
    -1,    // w..bbww
    -4,    // .b.bbww
    9,     // bb.bbww
    -3,    // wb.bbww
    12,    // .w.bbww
    21,    // bw.bbww
    10,    // ww.bbww
    -2,    // ..bbbww
    -15,   // b.bbbww
    -26,   // w.bbbww
    12,    // .bbbbww
    -9,    // bbbbbww
    -13,   // wbbbbww
    23,    // .wbbbww
    -14,   // bwbbbww
    0,     // wwbbbww
    -15,   // ..wbbww
    -13,   // b.wbbww
    -7,    // w.wbbww
    -19,   // .bwbbww
    -12,   // bbwbbww
    3,     // wbwbbww
    21,    // .wwbbww
    -6,    // bwwbbww
    -7,    // wwwbbww
    4,     // ...wbww
    0,     // b..wbww
    -10,   // w..wbww
    -10,   // .b.wbww
    -5,    // bb.wbww
    2,     // wb.wbww
    -15,   // .w.wbww
    3,     // bw.wbww
    2,     // ww.wbww
    -19,   // ..bwbww
    21,    // b.bwbww
    -3,    // w.bwbww
    -18,   // .bbwbww
    15,    // bbbwbww
    13,    // wbbwbww
    -3,    // .wbwbww
    -2,    // bwbwbww
    0,     // wwbwbww
    -8,    // ..wwbww
    4,     // b.wwbww
    -21,   // w.wwbww
    0,     // .bwwbww
    12,    // bbwwbww
    10,    // wbwwbww
    -9,    // .wwwbww
    -19,   // bwwwbww
    -1,    // wwwwbww
    -16,   // ....www
    7,     // b...www
    2,     // w...www
    -13,   // .b..www
    -8,    // bb..www
    -10,   // wb..www
    -20,   // .w..www
    1,     // bw..www
    7,     // ww..www
    -20,   // ..b.www
    33,    // b.b.www
    -2,    // w.b.www
    -16,   // .bb.www
    0,     // bbb.www
    20,    // wbb.www
    0,     // .wb.www
    4,     // bwb.www
    -11,   // wwb.www
    -30,   // ..w.www
    16,    // b.w.www
    -10,   // w.w.www
    -17,   // .bw.www
    2,     // bbw.www
    -12,   // wbw.www
    2,     // .ww.www
    -20,   // bww.www
    -30,   // www.www
    8,     // ...bwww
    -10,   // b..bwww
    -2,    // w..bwww
    3,     // .b.bwww
    5,     // bb.bwww
    -3,    // wb.bwww
    11,    // .w.bwww
    14,    // bw.bwww
    -2,    // ww.bwww
    1,     // ..bbwww
    -3,    // b.bbwww
    0,     // w.bbwww
    0,     // .bbbwww
    22,    // bbbbwww
    7,     // wbbbwww
    17,    // .wbbwww
    11,    // bwbbwww
    -7,    // wwbbwww
    -15,   // ..wbwww
    0,     // b.wbwww
    -4,    // w.wbwww
    2,     // .bwbwww
    -15,   // bbwbwww
    2,     // wbwbwww
    -9,    // .wwbwww
    -6,    // bwwbwww
    -8,    // wwwbwww
    -52,   // ...wwww
    -1,    // b..wwww
    -4,    // w..wwww
    6,     // .b.wwww
    -4,    // bb.wwww
    -13,   // wb.wwww
    6,     // .w.wwww
    8,     // bw.wwww
    11,    // ww.wwww
    8,     // ..bwwww
    -5,    // b.bwwww
    -17,   // w.bwwww
    -2,    // .bbwwww
    -22,   // bbbwwww
    -6,    // wbbwwww
    -5,    // .wbwwww
    16,    // bwbwwww
    -1,    // wwbwwww
    11,    // ..wwwww
    0,     // b.wwwww
    6,     // w.wwwww
    -16,   // .bwwwww
    9,     // bbwwwww
    -19,   // wbwwwww
    -21,   // .wwwwww
    12,    // bwwwwww
    11,    // wwwwwww
    -2,    // ccc
    -10,   // cc
    16,    // c
    -1,    // ttt
    10,    // tt
    -1,    // t
    5,     // ct
    25,    // cct
    -1,    // ctt
].into_boxed_slice()
