vec![
    0,     // .......
    2,     // b......
    -2,    // w......
    -1,    // .b.....
    3,     // bb.....
    16,    // wb.....
    1,     // .w.....
    -16,   // bw.....
    -3,    // ww.....
    -2,    // ..b....
    -7,    // b.b....
    -5,    // w.b....
    -3,    // .bb....
    27,    // bbb....
    -26,   // wbb....
    -7,    // .wb....
    -14,   // bwb....
    13,    // wwb....
    2,     // ..w....
    5,     // b.w....
    7,     // w.w....
    7,     // .bw....
    -13,   // bbw....
    14,    // wbw....
    3,     // .ww....
    26,    // bww....
    -27,   // www....
    -1,    // ...b...
    8,     // b..b...
    -21,   // w..b...
    2,     // .b.b...
    -9,    // bb.b...
    5,     // wb.b...
    3,     // .w.b...
    12,    // bw.b...
    8,     // ww.b...
    -11,   // ..bb...
    14,    // b.bb...
    8,     // w.bb...
    16,    // .bbb...
    4,     // bbbb...
    0,     // wbbb...
    -12,   // .wbb...
    13,    // bwbb...
    10,    // wwbb...
    -6,    // ..wb...
    3,     // b.wb...
    -10,   // w.wb...
    9,     // .bwb...
    -2,    // bbwb...
    -5,    // wbwb...
    -11,   // .wwb...
    -6,    // bwwb...
    7,     // wwwb...
    1,     // ...w...
    21,    // b..w...
    -8,    // w..w...
    -3,    // .b.w...
    -8,    // bb.w...
    -12,   // wb.w...
    -2,    // .w.w...
    -5,    // bw.w...
    9,     // ww.w...
    6,     // ..bw...
    10,    // b.bw...
    -3,    // w.bw...
    11,    // .bbw...
    -7,    // bbbw...
    6,     // wbbw...
    -9,    // .wbw...
    5,     // bwbw...
    2,     // wwbw...
    11,    // ..ww...
    -8,    // b.ww...
    -14,   // w.ww...
    12,    // .bww...
    -10,   // bbww...
    -13,   // wbww...
    -16,   // .www...
    0,     // bwww...
    -4,    // wwww...
    -2,    // ....b..
    -7,    // b...b..
    6,     // w...b..
    -12,   // .b..b..
    10,    // bb..b..
    4,     // wb..b..
    10,    // .w..b..
    13,    // bw..b..
    2,     // ww..b..
    0,     // ..b.b..
    -6,    // b.b.b..
    0,     // w.b.b..
    -3,    // .bb.b..
    6,     // bbb.b..
    2,     // wbb.b..
    -11,   // .wb.b..
    6,     // bwb.b..
    1,     // wwb.b..
    0,     // ..w.b..
    -8,    // b.w.b..
    3,     // w.w.b..
    -7,    // .bw.b..
    -14,   // bbw.b..
    -2,    // wbw.b..
    7,     // .ww.b..
    3,     // bww.b..
    8,     // www.b..
    -11,   // ...bb..
    -9,    // b..bb..
    12,    // w..bb..
    1,     // .b.bb..
    2,     // bb.bb..
    3,     // wb.bb..
    5,     // .w.bb..
    4,     // bw.bb..
    2,     // ww.bb..
    3,     // ..bbb..
    -3,    // b.bbb..
    2,     // w.bbb..
    8,     // .bbbb..
    13,    // bbbbb..
    16,    // wbbbb..
    5,     // .wbbb..
    -4,    // bwbbb..
    -4,    // wwbbb..
    -9,    // ..wbb..
    5,     // b.wbb..
    -5,    // w.wbb..
    3,     // .bwbb..
    6,     // bbwbb..
    4,     // wbwbb..
    -2,    // .wwbb..
    17,    // bwwbb..
    10,    // wwwbb..
    6,     // ...wb..
    0,     // b..wb..
    0,     // w..wb..
    -5,    // .b.wb..
    -12,   // bb.wb..
    29,    // wb.wb..
    -9,    // .w.wb..
    -4,    // bw.wb..
    -3,    // ww.wb..
    18,    // ..bwb..
    10,    // b.bwb..
    1,     // w.bwb..
    0,     // .bbwb..
    0,     // bbbwb..
    6,     // wbbwb..
    3,     // .wbwb..
    -1,    // bwbwb..
    -16,   // wwbwb..
    9,     // ..wwb..
    13,    // b.wwb..
    -2,    // w.wwb..
    10,    // .bwwb..
    3,     // bbwwb..
    -1,    // wbwwb..
    1,     // .wwwb..
    -1,    // bwwwb..
    12,    // wwwwb..
    2,     // ....w..
    -6,    // b...w..
    7,     // w...w..
    -10,   // .b..w..
    -2,    // bb..w..
    -13,   // wb..w..
    12,    // .w..w..
    -4,    // bw..w..
    -10,   // ww..w..
    0,     // ..b.w..
    -3,    // b.b.w..
    8,     // w.b.w..
    -7,    // .bb.w..
    -8,    // bbb.w..
    -3,    // wbb.w..
    7,     // .wb.w..
    2,     // bwb.w..
    14,    // wwb.w..
    0,     // ..w.w..
    0,     // b.w.w..
    6,     // w.w.w..
    11,    // .bw.w..
    -1,    // bbw.w..
    -6,    // wbw.w..
    3,     // .ww.w..
    -2,    // bww.w..
    -6,    // www.w..
    -6,    // ...bw..
    0,     // b..bw..
    0,     // w..bw..
    9,     // .b.bw..
    3,     // bb.bw..
    4,     // wb.bw..
    5,     // .w.bw..
    -29,   // bw.bw..
    12,    // ww.bw..
    -9,    // ..bbw..
    2,     // b.bbw..
    -13,   // w.bbw..
    -1,    // .bbbw..
    -12,   // bbbbw..
    1,     // wbbbw..
    -10,   // .wbbw..
    1,     // bwbbw..
    -3,    // wwbbw..
    -18,   // ..wbw..
    -1,    // b.wbw..
    -10,   // w.wbw..
    -3,    // .bwbw..
    16,    // bbwbw..
    1,     // wbwbw..
    0,     // .wwbw..
    -6,    // bwwbw..
    0,     // wwwbw..
    11,    // ...ww..
    -12,   // b..ww..
    9,     // w..ww..
    -5,    // .b.ww..
    -2,    // bb.ww..
    -4,    // wb.ww..
    -1,    // .w.ww..
    -3,    // bw.ww..
    -2,    // ww.ww..
    9,     // ..bww..
    5,     // b.bww..
    -5,    // w.bww..
    2,     // .bbww..
    -10,   // bbbww..
    -17,   // wbbww..
    -3,    // .wbww..
    -4,    // bwbww..
    -6,    // wwbww..
    -3,    // ..www..
    -2,    // b.www..
    3,     // w.www..
    -5,    // .bwww..
    4,     // bbwww..
    4,     // wbwww..
    -8,    // .wwww..
    -16,   // bwwww..
    -13,   // wwwww..
    -1,    // .....b.
    -10,   // b....b.
    -14,   // w....b.
    -7,    // .b...b.
    15,    // bb...b.
    -5,    // wb...b.
    0,     // .w...b.
    -17,   // bw...b.
    -7,    // ww...b.
    -12,   // ..b..b.
    1,     // b.b..b.
    2,     // w.b..b.
    1,     // .bb..b.
    0,     // bbb..b.
    0,     // wbb..b.
    -7,    // .wb..b.
    -2,    // bwb..b.
    4,     // wwb..b.
    -10,   // ..w..b.
    -7,    // b.w..b.
    -19,   // w.w..b.
    -5,    // .bw..b.
    7,     // bbw..b.
    -33,   // wbw..b.
    -2,    // .ww..b.
    5,     // bww..b.
    8,     // www..b.
    2,     // ...b.b.
    -7,    // b..b.b.
    -9,    // w..b.b.
    9,     // .b.b.b.
    6,     // bb.b.b.
    0,     // wb.b.b.
    -7,    // .w.b.b.
    -11,   // bw.b.b.
    -12,   // ww.b.b.
    1,     // ..bb.b.
    -3,    // b.bb.b.
    -14,   // w.bb.b.
    3,     // .bbb.b.
    -1,    // bbbb.b.
    1,     // wbbb.b.
    -8,    // .wbb.b.
    -5,    // bwbb.b.
    -4,    // wwbb.b.
    9,     // ..wb.b.
    9,     // b.wb.b.
    1,     // w.wb.b.
    -16,   // .bwb.b.
    -13,   // bbwb.b.
    -6,    // wbwb.b.
    -9,    // .wwb.b.
    4,     // bwwb.b.
    -8,    // wwwb.b.
    -3,    // ...w.b.
    -15,   // b..w.b.
    1,     // w..w.b.
    0,     // .b.w.b.
    -7,    // bb.w.b.
    8,     // wb.w.b.
    7,     // .w.w.b.
    -24,   // bw.w.b.
    -2,    // ww.w.b.
    -5,    // ..bw.b.
    -12,   // b.bw.b.
    3,     // w.bw.b.
    6,     // .bbw.b.
    -6,    // bbbw.b.
    6,     // wbbw.b.
    9,     // .wbw.b.
    13,    // bwbw.b.
    7,     // wwbw.b.
    -5,    // ..ww.b.
    8,     // b.ww.b.
    -1,    // w.ww.b.
    -2,    // .bww.b.
    13,    // bbww.b.
    7,     // wbww.b.
    -3,    // .www.b.
    9,     // bwww.b.
    0,     // wwww.b.
    -3,    // ....bb.
    11,    // b...bb.
    -9,    // w...bb.
    1,     // .b..bb.
    1,     // bb..bb.
    -4,    // wb..bb.
    2,     // .w..bb.
    14,    // bw..bb.
    3,     // ww..bb.
    -3,    // ..b.bb.
    -5,    // b.b.bb.
    15,    // w.b.bb.
    -16,   // .bb.bb.
    -12,   // bbb.bb.
    2,     // wbb.bb.
    2,     // .wb.bb.
    -13,   // bwb.bb.
    -3,    // wwb.bb.
    -7,    // ..w.bb.
    -10,   // b.w.bb.
    -15,   // w.w.bb.
    -2,    // .bw.bb.
    10,    // bbw.bb.
    -7,    // wbw.bb.
    0,     // .ww.bb.
    3,     // bww.bb.
    -3,    // www.bb.
    16,    // ...bbb.
    17,    // b..bbb.
    -8,    // w..bbb.
    3,     // .b.bbb.
    9,     // bb.bbb.
    1,     // wb.bbb.
    3,     // .w.bbb.
    -1,    // bw.bbb.
    -7,    // ww.bbb.
    8,     // ..bbbb.
    -6,    // b.bbbb.
    10,    // w.bbbb.
    5,     // .bbbbb.
    21,    // bbbbbb.
    -11,   // wbbbbb.
    7,     // .wbbbb.
    -9,    // bwbbbb.
    2,     // wwbbbb.
    -1,    // ..wbbb.
    -7,    // b.wbbb.
    3,     // w.wbbb.
    5,     // .bwbbb.
    -1,    // bbwbbb.
    -6,    // wbwbbb.
    6,     // .wwbbb.
    -1,    // bwwbbb.
    14,    // wwwbbb.
    11,    // ...wbb.
    -9,    // b..wbb.
    -7,    // w..wbb.
    6,     // .b.wbb.
    8,     // bb.wbb.
    5,     // wb.wbb.
    9,     // .w.wbb.
    -1,    // bw.wbb.
    -4,    // ww.wbb.
    0,     // ..bwbb.
    4,     // b.bwbb.
    4,     // w.bwbb.
    -4,    // .bbwbb.
    0,     // bbbwbb.
    -1,    // wbbwbb.
    -2,    // .wbwbb.
    -8,    // bwbwbb.
    10,    // wwbwbb.
    2,     // ..wwbb.
    5,     // b.wwbb.
    4,     // w.wwbb.
    -16,   // .bwwbb.
    -16,   // bbwwbb.
    -1,    // wbwwbb.
    -6,    // .wwwbb.
    -4,    // bwwwbb.
    -5,    // wwwwbb.
    7,     // ....wb.
    0,     // b...wb.
    -1,    // w...wb.
    -5,    // .b..wb.
    5,     // bb..wb.
    -11,   // wb..wb.
    7,     // .w..wb.
    3,     // bw..wb.
    -10,   // ww..wb.
    -7,    // ..b.wb.
    -4,    // b.b.wb.
    -14,   // w.b.wb.
    -2,    // .bb.wb.
    1,     // bbb.wb.
    17,    // wbb.wb.
    0,     // .wb.wb.
    0,     // bwb.wb.
    7,     // wwb.wb.
    11,    // ..w.wb.
    -6,    // b.w.wb.
    6,     // w.w.wb.
    11,    // .bw.wb.
    -3,    // bbw.wb.
    -12,   // wbw.wb.
    -2,    // .ww.wb.
    8,     // bww.wb.
    4,     // www.wb.
    9,     // ...bwb.
    7,     // b..bwb.
    10,    // w..bwb.
    -16,   // .b.bwb.
    -6,    // bb.bwb.
    8,     // wb.bwb.
    -9,    // .w.bwb.
    -2,    // bw.bwb.
    -2,    // ww.bwb.
    3,     // ..bbwb.
    8,     // b.bbwb.
    -9,    // w.bbwb.
    5,     // .bbbwb.
    2,     // bbbbwb.
    -14,   // wbbbwb.
    -3,    // .wbbwb.
    5,     // bwbbwb.
    -15,   // wwbbwb.
    -3,    // ..wbwb.
    5,     // b.wbwb.
    18,    // w.wbwb.
    -6,    // .bwbwb.
    9,     // bbwbwb.
    3,     // wbwbwb.
    2,     // .wwbwb.
    7,     // bwwbwb.
    2,     // wwwbwb.
    12,    // ...wwb.
    -7,    // b..wwb.
    -7,    // w..wwb.
    -2,    // .b.wwb.
    6,     // bb.wwb.
    -3,    // wb.wwb.
    8,     // .w.wwb.
    -1,    // bw.wwb.
    -11,   // ww.wwb.
    10,    // ..bwwb.
    17,    // b.bwwb.
    6,     // w.bwwb.
    -16,   // .bbwwb.
    -1,    // bbbwwb.
    2,     // wbbwwb.
    3,     // .wbwwb.
    -7,    // bwbwwb.
    0,     // wwbwwb.
    -5,    // ..wwwb.
    -10,   // b.wwwb.
    8,     // w.wwwb.
    21,    // .bwwwb.
    -14,   // bbwwwb.
    -3,    // wbwwwb.
    -7,    // .wwwwb.
    -9,    // bwwwwb.
    9,     // wwwwwb.
    1,     // .....w.
    14,    // b....w.
    10,    // w....w.
    0,     // .b...w.
    7,     // bb...w.
    17,    // wb...w.
    7,     // .w...w.
    5,     // bw...w.
    -15,   // ww...w.
    10,    // ..b..w.
    19,    // b.b..w.
    7,     // w.b..w.
    2,     // .bb..w.
    -8,    // bbb..w.
    -5,    // wbb..w.
    5,     // .wb..w.
    33,    // bwb..w.
    -7,    // wwb..w.
    12,    // ..w..w.
    -2,    // b.w..w.
    -1,    // w.w..w.
    7,     // .bw..w.
    -4,    // bbw..w.
    2,     // wbw..w.
    -1,    // .ww..w.
    0,     // bww..w.
    0,     // www..w.
    3,     // ...b.w.
    -1,    // b..b.w.
    15,    // w..b.w.
    -7,    // .b.b.w.
    2,     // bb.b.w.
    24,    // wb.b.w.
    0,     // .w.b.w.
    -8,    // bw.b.w.
    7,     // ww.b.w.
    5,     // ..bb.w.
    1,     // b.bb.w.
    -8,    // w.bb.w.
    3,     // .bbb.w.
    0,     // bbbb.w.
    -9,    // wbbb.w.
    2,     // .wbb.w.
    -7,    // bwbb.w.
    -13,   // wwbb.w.
    5,     // ..wb.w.
    -3,    // b.wb.w.
    12,    // w.wb.w.
    -9,    // .bwb.w.
    -7,    // bbwb.w.
    -13,   // wbwb.w.
    -6,    // .wwb.w.
    -6,    // bwwb.w.
    6,     // wwwb.w.
    -2,    // ...w.w.
    9,     // b..w.w.
    7,     // w..w.w.
    7,     // .b.w.w.
    12,    // bb.w.w.
    11,    // wb.w.w.
    -9,    // .w.w.w.
    0,     // bw.w.w.
    -6,    // ww.w.w.
    -9,    // ..bw.w.
    -1,    // b.bw.w.
    -9,    // w.bw.w.
    9,     // .bbw.w.
    8,     // bbbw.w.
    -4,    // wbbw.w.
    16,    // .wbw.w.
    6,     // bwbw.w.
    13,    // wwbw.w.
    -1,    // ..ww.w.
    14,    // b.ww.w.
    3,     // w.ww.w.
    8,     // .bww.w.
    4,     // bbww.w.
    5,     // wbww.w.
    -3,    // .www.w.
    -1,    // bwww.w.
    1,     // wwww.w.
    -7,    // ....bw.
    1,     // b...bw.
    0,     // w...bw.
    -7,    // .b..bw.
    10,    // bb..bw.
    -3,    // wb..bw.
    5,     // .w..bw.
    11,    // bw..bw.
    -5,    // ww..bw.
    -11,   // ..b.bw.
    -6,    // b.b.bw.
    6,     // w.b.bw.
    2,     // .bb.bw.
    -4,    // bbb.bw.
    -8,    // wbb.bw.
    -11,   // .wb.bw.
    12,    // bwb.bw.
    3,     // wwb.bw.
    7,     // ..w.bw.
    14,    // b.w.bw.
    4,     // w.w.bw.
    0,     // .bw.bw.
    -7,    // bbw.bw.
    0,     // wbw.bw.
    2,     // .ww.bw.
    -17,   // bww.bw.
    -1,    // www.bw.
    -12,   // ...bbw.
    7,     // b..bbw.
    7,     // w..bbw.
    -8,    // .b.bbw.
    11,    // bb.bbw.
    1,     // wb.bbw.
    2,     // .w.bbw.
    3,     // bw.bbw.
    -6,    // ww.bbw.
    5,     // ..bbbw.
    -8,    // b.bbbw.
    10,    // w.bbbw.
    7,     // .bbbbw.
    -9,    // bbbbbw.
    9,     // wbbbbw.
    -21,   // .wbbbw.
    3,     // bwbbbw.
    14,    // wwbbbw.
    -10,   // ..wbbw.
    -6,    // b.wbbw.
    -17,   // w.wbbw.
    -3,    // .bwbbw.
    0,     // bbwbbw.
    7,     // wbwbbw.
    16,    // .wwbbw.
    -2,    // bwwbbw.
    1,     // wwwbbw.
    -9,    // ...wbw.
    -10,   // b..wbw.
    -7,    // w..wbw.
    9,     // .b.wbw.
    2,     // bb.wbw.
    2,     // wb.wbw.
    16,    // .w.wbw.
    -8,    // bw.wbw.
    6,     // ww.wbw.
    3,     // ..bwbw.
    -18,   // b.bwbw.
    -5,    // w.bwbw.
    -2,    // .bbwbw.
    -2,    // bbbwbw.
    -7,    // wbbwbw.
    6,     // .wbwbw.
    -3,    // bwbwbw.
    -9,    // wwbwbw.
    -3,    // ..wwbw.
    9,     // b.wwbw.
    -8,    // w.wwbw.
    3,     // .bwwbw.
    15,    // bbwwbw.
    -5,    // wbwwbw.
    -5,    // .wwwbw.
    14,    // bwwwbw.
    -2,    // wwwwbw.
    3,     // ....ww.
    9,     // b...ww.
    -11,   // w...ww.
    -2,    // .b..ww.
    -3,    // bb..ww.
    -14,   // wb..ww.
    -1,    // .w..ww.
    4,     // bw..ww.
    -1,    // ww..ww.
    7,     // ..b.ww.
    15,    // b.b.ww.
    10,    // w.b.ww.
    0,     // .bb.ww.
    3,     // bbb.ww.
    -3,    // wbb.ww.
    2,     // .wb.ww.
    7,     // bwb.ww.
    -10,   // wwb.ww.
    3,     // ..w.ww.
    -15,   // b.w.ww.
    5,     // w.w.ww.
    -2,    // .bw.ww.
    3,     // bbw.ww.
    13,    // wbw.ww.
    16,    // .ww.ww.
    -2,    // bww.ww.
    12,    // www.ww.
    -11,   // ...bww.
    7,     // b..bww.
    9,     // w..bww.
    -9,    // .b.bww.
    4,     // bb.bww.
    1,     // wb.bww.
    -6,    // .w.bww.
    -5,    // bw.bww.
    -8,    // ww.bww.
    -2,    // ..bbww.
    -4,    // b.bbww.
    -5,    // w.bbww.
    6,     // .bbbww.
    5,     // bbbbww.
    4,     // wbbbww.
    16,    // .wbbww.
    1,     // bwbbww.
    16,    // wwbbww.
    0,     // ..wbww.
    -4,    // b.wbww.
    -4,    // w.wbww.
    2,     // .bwbww.
    -10,   // bbwbww.
    8,     // wbwbww.
    4,     // .wwbww.
    1,     // bwwbww.
    0,     // wwwbww.
    -16,   // ...www.
    8,     // b..www.
    -17,   // w..www.
    -3,    // .b.www.
    7,     // bb.www.
    1,     // wb.www.
    -3,    // .w.www.
    -1,    // bw.www.
    -9,    // ww.www.
    1,     // ..bwww.
    -3,    // b.bwww.
    7,     // w.bwww.
    -6,    // .bbwww.
    -14,   // bbbwww.
    1,     // wbbwww.
    -5,    // .wbwww.
    6,     // bwbwww.
    1,     // wwbwww.
    -8,    // ..wwww.
    -10,   // b.wwww.
    6,     // w.wwww.
    -7,    // .bwwww.
    -2,    // bbwwww.
    9,     // wbwwww.
    -5,    // .wwwww.
    11,    // bwwwww.
    -21,   // wwwwww.
    2,     // ......b
    -11,   // b.....b
    0,     // w.....b
    -10,   // .b....b
    10,    // bb....b
    -8,    // wb....b
    14,    // .w....b
    0,     // bw....b
    -6,    // ww....b
    -7,    // ..b...b
    5,     // b.b...b
    4,     // w.b...b
    11,    // .bb...b
    15,    // bbb...b
    8,     // wbb...b
    1,     // .wb...b
    14,    // bwb...b
    -7,    // wwb...b
    -6,    // ..w...b
    -4,    // b.w...b
    12,    // w.w...b
    0,     // .bw...b
    7,     // bbw...b
    11,    // wbw...b
    9,     // .ww...b
    -1,    // bww...b
    -12,   // www...b
    8,     // ...b..b
    32,    // b..b..b
    18,    // w..b..b
    -7,    // .b.b..b
    4,     // bb.b..b
    6,     // wb.b..b
    -1,    // .w.b..b
    13,    // bw.b..b
    -6,    // ww.b..b
    -9,    // ..bb..b
    -5,    // b.bb..b
    -3,    // w.bb..b
    17,    // .bbb..b
    -17,   // bbbb..b
    3,     // wbbb..b
    7,     // .wbb..b
    -10,   // bwbb..b
    9,     // wwbb..b
    0,     // ..wb..b
    -5,    // b.wb..b
    6,     // w.wb..b
    7,     // .bwb..b
    6,     // bbwb..b
    -2,    // wbwb..b
    7,     // .wwb..b
    -1,    // bwwb..b
    3,     // wwwb..b
    21,    // ...w..b
    12,    // b..w..b
    -18,   // w..w..b
    -15,   // .b.w..b
    -20,   // bb.w..b
    -6,    // wb.w..b
    9,     // .w.w..b
    14,    // bw.w..b
    3,     // ww.w..b
    0,     // ..bw..b
    8,     // b.bw..b
    -4,    // w.bw..b
    -9,    // .bbw..b
    5,     // bbbw..b
    -12,   // wbbw..b
    -10,   // .wbw..b
    -7,    // bwbw..b
    0,     // wwbw..b
    -12,   // ..ww..b
    -10,   // b.ww..b
    12,    // w.ww..b
    -7,    // .bww..b
    6,     // bbww..b
    -5,    // wbww..b
    8,     // .www..b
    -1,    // bwww..b
    12,    // wwww..b
    -7,    // ....b.b
    5,     // b...b.b
    -12,   // w...b.b
    1,     // .b..b.b
    4,     // bb..b.b
    -10,   // wb..b.b
    19,    // .w..b.b
    -11,   // bw..b.b
    -12,   // ww..b.b
    -6,    // ..b.b.b
    1,     // b.b.b.b
    7,     // w.b.b.b
    -5,    // .bb.b.b
    6,     // bbb.b.b
    -3,    // wbb.b.b
    -6,    // .wb.b.b
    9,     // bwb.b.b
    3,     // wwb.b.b
    -3,    // ..w.b.b
    8,     // b.w.b.b
    0,     // w.w.b.b
    -4,    // .bw.b.b
    -4,    // bbw.b.b
    5,     // wbw.b.b
    15,    // .ww.b.b
    -9,    // bww.b.b
    13,    // www.b.b
    14,    // ...bb.b
    -5,    // b..bb.b
    -12,   // w..bb.b
    -3,    // .b.bb.b
    2,     // bb.bb.b
    17,    // wb.bb.b
    1,     // .w.bb.b
    -24,   // bw.bb.b
    8,     // ww.bb.b
    -3,    // ..bbb.b
    6,     // b.bbb.b
    5,     // w.bbb.b
    -6,    // .bbbb.b
    5,     // bbbbb.b
    -1,    // wbbbb.b
    -8,    // .wbbb.b
    -12,   // bwbbb.b
    16,    // wwbbb.b
    2,     // ..wbb.b
    -12,   // b.wbb.b
    -8,    // w.wbb.b
    8,     // .bwbb.b
    -5,    // bbwbb.b
    14,    // wbwbb.b
    -4,    // .wwbb.b
    1,     // bwwbb.b
    -11,   // wwwbb.b
    10,    // ...wb.b
    8,     // b..wb.b
    -6,    // w..wb.b
    -12,   // .b.wb.b
    -2,    // bb.wb.b
    6,     // wb.wb.b
    -1,    // .w.wb.b
    9,     // bw.wb.b
    1,     // ww.wb.b
    10,    // ..bwb.b
    0,     // b.bwb.b
    14,    // w.bwb.b
    4,     // .bbwb.b
    1,     // bbbwb.b
    5,     // wbbwb.b
    -18,   // .wbwb.b
    13,    // bwbwb.b
    -5,    // wwbwb.b
    5,     // ..wwb.b
    -4,    // b.wwb.b
    8,     // w.wwb.b
    17,    // .bwwb.b
    -24,   // bbwwb.b
    10,    // wbwwb.b
    -3,    // .wwwb.b
    16,    // bwwwb.b
    6,     // wwwwb.b
    5,     // ....w.b
    -4,    // b...w.b
    -4,    // w...w.b
    -7,    // .b..w.b
    1,     // bb..w.b
    16,    // wb..w.b
    -2,    // .w..w.b
    -12,   // bw..w.b
    0,     // ww..w.b
    -8,    // ..b.w.b
    8,     // b.b.w.b
    0,     // w.b.w.b
    -10,   // .bb.w.b
    14,    // bbb.w.b
    -10,   // wbb.w.b
    14,    // .wb.w.b
    -1,    // bwb.w.b
    7,     // wwb.w.b
    0,     // ..w.w.b
    -7,    // b.w.w.b
    -7,    // w.w.w.b
    -6,    // .bw.w.b
    5,     // bbw.w.b
    1,     // wbw.w.b
    -15,   // .ww.w.b
    -7,    // bww.w.b
    -19,   // www.w.b
    3,     // ...bw.b
    -5,    // b..bw.b
    4,     // w..bw.b
    9,     // .b.bw.b
    -15,   // bb.bw.b
    -3,    // wb.bw.b
    -3,    // .w.bw.b
    -11,   // bw.bw.b
    -10,   // ww.bw.b
    5,     // ..bbw.b
    -12,   // b.bbw.b
    7,     // w.bbw.b
    -7,    // .bbbw.b
    9,     // bbbbw.b
    6,     // wbbbw.b
    -6,    // .wbbw.b
    14,    // bwbbw.b
    2,     // wwbbw.b
    -1,    // ..wbw.b
    24,    // b.wbw.b
    -14,   // w.wbw.b
    5,     // .bwbw.b
    8,     // bbwbw.b
    9,     // wbwbw.b
    -4,    // .wwbw.b
    2,     // bwwbw.b
    -4,    // wwwbw.b
    -8,    // ...ww.b
    -10,   // b..ww.b
    3,     // w..ww.b
    8,     // .b.ww.b
    14,    // bb.ww.b
    1,     // wb.ww.b
    14,    // .w.ww.b
    13,    // bw.ww.b
    -10,   // ww.ww.b
    13,    // ..bww.b
    -4,    // b.bww.b
    -7,    // w.bww.b
    5,     // .bbww.b
    -5,    // bbbww.b
    -2,    // wbbww.b
    9,     // .wbww.b
    11,    // bwbww.b
    9,     // wwbww.b
    -2,    // ..www.b
    14,    // b.www.b
    -5,    // w.www.b
    -10,   // .bwww.b
    -4,    // bbwww.b
    8,     // wbwww.b
    -10,   // .wwww.b
    8,     // bwwww.b
    6,     // wwwww.b
    3,     // .....bb
    10,    // b....bb
    6,     // w....bb
    15,    // .b...bb
    3,     // bb...bb
    -19,   // wb...bb
    7,     // .w...bb
    10,    // bw...bb
    0,     // ww...bb
    10,    // ..b..bb
    4,     // b.b..bb
    0,     // w.b..bb
    1,     // .bb..bb
    -5,    // bbb..bb
    -1,    // wbb..bb
    10,    // .wb..bb
    3,     // bwb..bb
    14,    // wwb..bb
    -2,    // ..w..bb
    1,     // b.w..bb
    12,    // w.w..bb
    5,     // .bw..bb
    -1,    // bbw..bb
    -2,    // wbw..bb
    -3,    // .ww..bb
    -8,    // bww..bb
    -1,    // www..bb
    -9,    // ...b.bb
    4,     // b..b.bb
    -3,    // w..b.bb
    6,     // .b.b.bb
    7,     // bb.b.bb
    8,     // wb.b.bb
    2,     // .w.b.bb
    -4,    // bw.b.bb
    -4,    // ww.b.bb
    2,     // ..bb.bb
    2,     // b.bb.bb
    10,    // w.bb.bb
    9,     // .bbb.bb
    11,    // bbbb.bb
    -10,   // wbbb.bb
    11,    // .wbb.bb
    -11,   // bwbb.bb
    -15,   // wwbb.bb
    3,     // ..wb.bb
    -15,   // b.wb.bb
    -1,    // w.wb.bb
    -6,    // .bwb.bb
    3,     // bbwb.bb
    -7,    // wbwb.bb
    4,     // .wwb.bb
    11,    // bwwb.bb
    3,     // wwwb.bb
    -8,    // ...w.bb
    -20,   // b..w.bb
    6,     // w..w.bb
    -7,    // .b.w.bb
    0,     // bb.w.bb
    -1,    // wb.w.bb
    12,    // .w.w.bb
    -7,    // bw.w.bb
    4,     // ww.w.bb
    -12,   // ..bw.bb
    -2,    // b.bw.bb
    10,    // w.bw.bb
    8,     // .bbw.bb
    -4,    // bbbw.bb
    -3,    // wbbw.bb
    2,     // .wbw.bb
    -8,    // bwbw.bb
    -6,    // wwbw.bb
    -2,    // ..ww.bb
    14,    // b.ww.bb
    -8,    // w.ww.bb
    6,     // .bww.bb
    -1,    // bbww.bb
    2,     // wbww.bb
    7,     // .www.bb
    3,     // bwww.bb
    3,     // wwww.bb
    27,    // ....bbb
    15,    // b...bbb
    12,    // w...bbb
    0,     // .b..bbb
    -5,    // bb..bbb
    6,     // wb..bbb
    -8,    // .w..bbb
    -9,    // bw..bbb
    1,     // ww..bbb
    6,     // ..b.bbb
    6,     // b.b.bbb
    19,    // w.b.bbb
    -12,   // .bb.bbb
    -7,    // bbb.bbb
    -9,    // wbb.bbb
    -4,    // .wb.bbb
    11,    // bwb.bbb
    8,     // wwb.bbb
    -8,    // ..w.bbb
    14,    // b.w.bbb
    -13,   // w.w.bbb
    1,     // .bw.bbb
    -6,    // bbw.bbb
    -8,    // wbw.bbb
    3,     // .ww.bbb
    -10,   // bww.bbb
    0,     // www.bbb
    4,     // ...bbbb
    -17,   // b..bbbb
    -12,   // w..bbbb
    -1,    // .b.bbbb
    11,    // bb.bbbb
    -3,    // wb.bbbb
    0,     // .w.bbbb
    -1,    // bw.bbbb
    -3,    // ww.bbbb
    13,    // ..bbbbb
    5,     // b.bbbbb
    -6,    // w.bbbbb
    21,    // .bbbbbb
    -8,    // bbbbbbb
    4,     // wbbbbbb
    -9,    // .wbbbbb
    5,     // bwbbbbb
    4,     // wwbbbbb
    -12,   // ..wbbbb
    9,     // b.wbbbb
    -6,    // w.wbbbb
    2,     // .bwbbbb
    -4,    // bbwbbbb
    3,     // wbwbbbb
    5,     // .wwbbbb
    -2,    // bwwbbbb
    6,     // wwwbbbb
    -7,    // ...wbbb
    5,     // b..wbbb
    -3,    // w..wbbb
    -6,    // .b.wbbb
    -4,    // bb.wbbb
    0,     // wb.wbbb
    8,     // .w.wbbb
    1,     // bw.wbbb
    -3,    // ww.wbbb
    0,     // ..bwbbb
    1,     // b.bwbbb
    4,     // w.bwbbb
    0,     // .bbwbbb
    7,     // bbbwbbb
    -1,    // wbbwbbb
    -2,    // .wbwbbb
    6,     // bwbwbbb
    7,     // wwbwbbb
    -10,   // ..wwbbb
    -5,    // b.wwbbb
    11,    // w.wwbbb
    -1,    // .bwwbbb
    -18,   // bbwwbbb
    4,     // wbwwbbb
    -14,   // .wwwbbb
    11,    // bwwwbbb
    -6,    // wwwwbbb
    -13,   // ....wbb
    7,     // b...wbb
    7,     // w...wbb
    7,     // .b..wbb
    -1,    // bb..wbb
    1,     // wb..wbb
    -4,    // .w..wbb
    11,    // bw..wbb
    -14,   // ww..wbb
    -14,   // ..b.wbb
    -4,    // b.b.wbb
    -7,    // w.b.wbb
    10,    // .bb.wbb
    -6,    // bbb.wbb
    6,     // wbb.wbb
    -7,    // .wb.wbb
    5,     // bwb.wbb
    0,     // wwb.wbb
    -1,    // ..w.wbb
    5,     // b.w.wbb
    -3,    // w.w.wbb
    -3,    // .bw.wbb
    -19,   // bbw.wbb
    -3,    // wbw.wbb
    3,     // .ww.wbb
    -2,    // bww.wbb
    -8,    // www.wbb
    -2,    // ...bwbb
    6,     // b..bwbb
    0,     // w..bwbb
    -13,   // .b.bwbb
    3,     // bb.bwbb
    6,     // wb.bwbb
    -7,    // .w.bwbb
    16,    // bw.bwbb
    6,     // ww.bwbb
    6,     // ..bbwbb
    -5,    // b.bbwbb
    -9,    // w.bbwbb
    -1,    // .bbbwbb
    -4,    // bbbbwbb
    -21,   // wbbbwbb
    0,     // .wbbwbb
    11,    // bwbbwbb
    -1,    // wwbbwbb
    16,    // ..wbwbb
    8,     // b.wbwbb
    5,     // w.wbwbb
    9,     // .bwbwbb
    4,     // bbwbwbb
    -9,    // wbwbwbb
    -10,   // .wwbwbb
    -1,    // bwwbwbb
    -7,    // wwwbwbb
    -10,   // ...wwbb
    6,     // b..wwbb
    -9,    // w..wwbb
    13,    // .b.wwbb
    -1,    // bb.wwbb
    17,    // wb.wwbb
    4,     // .w.wwbb
    0,     // bw.wwbb
    15,    // ww.wwbb
    3,     // ..bwwbb
    -24,   // b.bwwbb
    -2,    // w.bwwbb
    -16,   // .bbwwbb
    -18,   // bbbwwbb
    1,     // wbbwwbb
    15,    // .wbwwbb
    -11,   // bwbwwbb
    1,     // wwbwwbb
    4,     // ..wwwbb
    -4,    // b.wwwbb
    -16,   // w.wwwbb
    -14,   // .bwwwbb
    -1,    // bbwwwbb
    -12,   // wbwwwbb
    -2,    // .wwwwbb
    -3,    // bwwwwbb
    -4,    // wwwwwbb
    -16,   // .....wb
    0,     // b....wb
    8,     // w....wb
    -17,   // .b...wb
    10,    // bb...wb
    0,     // wb...wb
    5,     // .w...wb
    -8,    // bw...wb
    19,    // ww...wb
    13,    // ..b..wb
    -11,   // b.b..wb
    -16,   // w.b..wb
    14,    // .bb..wb
    -9,    // bbb..wb
    -4,    // wbb..wb
    11,    // .wb..wb
    8,     // bwb..wb
    -1,    // wwb..wb
    -4,    // ..w..wb
    -12,   // b.w..wb
    10,    // w.w..wb
    3,     // .bw..wb
    11,    // bbw..wb
    11,    // wbw..wb
    4,     // .ww..wb
    -12,   // bww..wb
    -6,    // www..wb
    12,    // ...b.wb
    13,    // b..b.wb
    6,     // w..b.wb
    -11,   // .b.b.wb
    -4,    // bb.b.wb
    12,    // wb.b.wb
    -8,    // .w.b.wb
    -2,    // bw.b.wb
    1,     // ww.b.wb
    4,     // ..bb.wb
    -24,   // b.bb.wb
    -1,    // w.bb.wb
    -1,    // .bbb.wb
    -1,    // bbbb.wb
    3,     // wbbb.wb
    3,     // .wbb.wb
    -15,   // bwbb.wb
    -17,   // wwbb.wb
    -29,   // ..wb.wb
    -11,   // b.wb.wb
    -6,    // w.wb.wb
    -2,    // .bwb.wb
    16,    // bbwb.wb
    -7,    // wbwb.wb
    -5,    // .wwb.wb
    14,    // bwwb.wb
    0,     // wwwb.wb
    -5,    // ...w.wb
    14,    // b..w.wb
    -6,    // w..w.wb
    -24,   // .b.w.wb
    -7,    // bb.w.wb
    -12,   // wb.w.wb
    0,     // .w.w.wb
    -4,    // bw.w.wb
    -8,    // ww.w.wb
    -4,    // ..bw.wb
    9,     // b.bw.wb
    3,     // w.bw.wb
    -1,    // .bbw.wb
    1,     // bbbw.wb
    -19,   // wbbw.wb
    -8,    // .wbw.wb
    -15,   // bwbw.wb
    -6,    // wwbw.wb
    -3,    // ..ww.wb
    13,    // b.ww.wb
    -17,   // w.ww.wb
    -1,    // .bww.wb
    0,     // bbww.wb
    1,     // wbww.wb
    -1,    // .www.wb
    -20,   // bwww.wb
    3,     // wwww.wb
    -14,   // ....bwb
    14,    // b...bwb
    -11,   // w...bwb
    -2,    // .b..bwb
    3,     // bb..bwb
    -11,   // wb..bwb
    33,    // .w..bwb
    8,     // bw..bwb
    2,     // ww..bwb
    6,     // ..b.bwb
    9,     // b.b.bwb
    -1,    // w.b.bwb
    -13,   // .bb.bwb
    11,    // bbb.bwb
    -7,    // wbb.bwb
    12,    // .wb.bwb
    -11,   // bwb.bwb
    3,     // wwb.bwb
    2,     // ..w.bwb
    -1,    // b.w.bwb
    -5,    // w.w.bwb
    0,     // .bw.bwb
    5,     // bbw.bwb
    0,     // wbw.bwb
    7,     // .ww.bwb
    -25,   // bww.bwb
    8,     // www.bwb
    13,    // ...bbwb
    -10,   // b..bbwb
    5,     // w..bbwb
    -5,    // .b.bbwb
    -11,   // bb.bbwb
    -1,    // wb.bbwb
    -7,    // .w.bbwb
    -15,   // bw.bbwb
    -2,    // ww.bbwb
    -4,    // ..bbbwb
    -12,   // b.bbbwb
    -8,    // w.bbbwb
    -9,    // .bbbbwb
    5,     // bbbbbwb
    -7,    // wbbbbwb
    3,     // .wbbbwb
    -6,    // bwbbbwb
    12,    // wwbbbwb
    1,     // ..wbbwb
    14,    // b.wbbwb
    -10,   // w.wbbwb
    5,     // .bwbbwb
    11,    // bbwbbwb
    -10,   // wbwbbwb
    1,     // .wwbbwb
    -11,   // bwwbbwb
    -4,    // wwwbbwb
    5,     // ...wbwb
    -7,    // b..wbwb
    2,     // w..wbwb
    13,    // .b.wbwb
    -8,    // bb.wbwb
    7,     // wb.wbwb
    6,     // .w.wbwb
    -15,   // bw.wbwb
    7,     // ww.wbwb
    -1,    // ..bwbwb
    13,    // b.bwbwb
    -9,    // w.bwbwb
    -8,    // .bbwbwb
    6,     // bbbwbwb
    -9,    // wbbwbwb
    -3,    // .wbwbwb
    -7,    // bwbwbwb
    9,     // wwbwbwb
    -4,    // ..wwbwb
    11,    // b.wwbwb
    -14,   // w.wwbwb
    -7,    // .bwwbwb
    -11,   // bbwwbwb
    10,    // wbwwbwb
    6,     // .wwwbwb
    -2,    // bwwwbwb
    -3,    // wwwwbwb
    26,    // ....wwb
    -1,    // b...wwb
    -8,    // w...wwb
    5,     // .b..wwb
    -8,    // bb..wwb
    4,     // wb..wwb
    0,     // .w..wwb
    -12,   // bw..wwb
    1,     // ww..wwb
    3,     // ..b.wwb
    -9,    // b.b.wwb
    10,    // w.b.wwb
    3,     // .bb.wwb
    -10,   // bbb.wwb
    0,     // wbb.wwb
    -17,   // .wb.wwb
    -25,   // bwb.wwb
    -6,    // wwb.wwb
    -2,    // ..w.wwb
    -7,    // b.w.wwb
    3,     // w.w.wwb
    8,     // .bw.wwb
    -2,    // bbw.wwb
    7,     // wbw.wwb
    -2,    // .ww.wwb
    6,     // bww.wwb
    9,     // www.wwb
    -6,    // ...bwwb
    -1,    // b..bwwb
    12,    // w..bwwb
    4,     // .b.bwwb
    11,    // bb.bwwb
    19,    // wb.bwwb
    -6,    // .w.bwwb
    14,    // bw.bwwb
    3,     // ww.bwwb
    17,    // ..bbwwb
    1,     // b.bbwwb
    2,     // w.bbwwb
    -1,    // .bbbwwb
    -2,    // bbbbwwb
    -3,    // wbbbwwb
    -2,    // .wbbwwb
    -11,   // bwbbwwb
    -1,    // wwbbwwb
    -6,    // ..wbwwb
    2,     // b.wbwwb
    -5,    // w.wbwwb
    7,     // .bwbwwb
    -1,    // bbwbwwb
    9,     // wbwbwwb
    1,     // .wwbwwb
    2,     // bwwbwwb
    1,     // wwwbwwb
    0,     // ...wwwb
    -1,    // b..wwwb
    -3,    // w..wwwb
    9,     // .b.wwwb
    3,     // bb.wwwb
    -3,    // wb.wwwb
    -1,    // .w.wwwb
    -20,   // bw.wwwb
    10,    // ww.wwwb
    -1,    // ..bwwwb
    16,    // b.bwwwb
    -6,    // w.bwwwb
    -4,    // .bbwwwb
    11,    // bbbwwwb
    3,     // wbbwwwb
    14,    // .wbwwwb
    -2,    // bwbwwwb
    21,    // wwbwwwb
    -16,   // ..wwwwb
    8,     // b.wwwwb
    1,     // w.wwwwb
    -9,    // .bwwwwb
    -3,    // bbwwwwb
    7,     // wbwwwwb
    11,    // .wwwwwb
    5,     // bwwwwwb
    -4,    // wwwwwwb
    -2,    // ......w
    0,     // b.....w
    11,    // w.....w
    -14,   // .b....w
    6,     // bb....w
    0,     // wb....w
    10,    // .w....w
    8,     // bw....w
    -10,   // ww....w
    6,     // ..b...w
    -12,   // b.b...w
    4,     // w.b...w
    -9,    // .bb...w
    12,    // bbb...w
    1,     // wbb...w
    0,     // .wb...w
    -11,   // bwb...w
    -7,    // wwb...w
    7,     // ..w...w
    -4,    // b.w...w
    -5,    // w.w...w
    -1,    // .bw...w
    7,     // bbw...w
    -14,   // wbw...w
    -11,   // .ww...w
    -8,    // bww...w
    -15,   // www...w
    -21,   // ...b..w
    18,    // b..b..w
    -12,   // w..b..w
    -9,    // .b.b..w
    -3,    // bb.b..w
    -14,   // wb.b..w
    15,    // .w.b..w
    6,     // bw.b..w
    20,    // ww.b..w
    12,    // ..bb..w
    -12,   // b.bb..w
    10,    // w.bb..w
    -8,    // .bbb..w
    -12,   // bbbb..w
    1,     // wbbb..w
    7,     // .wbb..w
    5,     // bwbb..w
    -6,    // wwbb..w
    0,     // ..wb..w
    4,     // b.wb..w
    -8,    // w.wb..w
    10,    // .bwb..w
    0,     // bbwb..w
    7,     // wbwb..w
    9,     // .wwb..w
    12,    // bwwb..w
    -5,    // wwwb..w
    -8,    // ...w..w
    -18,   // b..w..w
    -32,   // w..w..w
    1,     // .b.w..w
    6,     // bb.w..w
    -13,   // wb.w..w
    7,     // .w.w..w
    -6,    // bw.w..w
    -4,    // ww.w..w
    0,     // ..bw..w
    -6,    // b.bw..w
    5,     // w.bw..w
    -7,    // .bbw..w
    -3,    // bbbw..w
    1,     // wbbw..w
    -7,    // .wbw..w
    2,     // bwbw..w
    -6,    // wwbw..w
    9,     // ..ww..w
    3,     // b.ww..w
    5,     // w.ww..w
    -7,    // .bww..w
    -9,    // bbww..w
    10,    // wbww..w
    -17,   // .www..w
    -3,    // bwww..w
    17,    // wwww..w
    -5,    // ....b.w
    4,     // b...b.w
    4,     // w...b.w
    2,     // .b..b.w
    0,     // bb..b.w
    12,    // wb..b.w
    7,     // .w..b.w
    -16,   // bw..b.w
    -1,    // ww..b.w
    0,     // ..b.b.w
    7,     // b.b.b.w
    7,     // w.b.b.w
    15,    // .bb.b.w
    19,    // bbb.b.w
    7,     // wbb.b.w
    6,     // .wb.b.w
    -1,    // bwb.b.w
    -5,    // wwb.b.w
    8,     // ..w.b.w
    0,     // b.w.b.w
    -8,    // w.w.b.w
    -14,   // .bw.b.w
    -7,    // bbw.b.w
    1,     // wbw.b.w
    10,    // .ww.b.w
    10,    // bww.b.w
    -14,   // www.b.w
    8,     // ...bb.w
    -3,    // b..bb.w
    10,    // w..bb.w
    -14,   // .b.bb.w
    10,    // bb.bb.w
    -13,   // wb.bb.w
    -8,    // .w.bb.w
    -1,    // bw.bb.w
    -14,   // ww.bb.w
    2,     // ..bbb.w
    5,     // b.bbb.w
    -14,   // w.bbb.w
    10,    // .bbbb.w
    -6,    // bbbbb.w
    -8,    // wbbbb.w
    10,    // .wbbb.w
    -8,    // bwbbb.w
    4,     // wwbbb.w
    -13,   // ..wbb.w
    7,     // b.wbb.w
    4,     // w.wbb.w
    -9,    // .bwbb.w
    -9,    // bbwbb.w
    -11,   // wbwbb.w
    -5,    // .wwbb.w
    2,     // bwwbb.w
    5,     // wwwbb.w
    -3,    // ...wb.w
    -4,    // b..wb.w
    5,     // w..wb.w
    3,     // .b.wb.w
    10,    // bb.wb.w
    11,    // wb.wb.w
    -9,    // .w.wb.w
    3,     // bw.wb.w
    15,    // ww.wb.w
    1,     // ..bwb.w
    14,    // b.bwb.w
    -24,   // w.bwb.w
    4,     // .bbwb.w
    4,     // bbbwb.w
    -2,    // wbbwb.w
    -5,    // .wbwb.w
    -9,    // bwbwb.w
    -8,    // wwbwb.w
    -5,    // ..wwb.w
    -7,    // b.wwb.w
    12,    // w.wwb.w
    6,     // .bwwb.w
    -2,    // bbwwb.w
    -14,   // wbwwb.w
    7,     // .wwwb.w
    -6,    // bwwwb.w
    -9,    // wwwwb.w
    7,     // ....w.w
    12,    // b...w.w
    -5,    // w...w.w
    -19,   // .b..w.w
    12,    // bb..w.w
    11,    // wb..w.w
    -1,    // .w..w.w
    10,    // bw..w.w
    -4,    // ww..w.w
    3,     // ..b.w.w
    0,     // b.b.w.w
    -8,    // w.b.w.w
    -15,   // .bb.w.w
    -13,   // bbb.w.w
    9,     // wbb.w.w
    4,     // .wb.w.w
    -5,    // bwb.w.w
    4,     // wwb.w.w
    6,     // ..w.w.w
    -7,    // b.w.w.w
    -1,    // w.w.w.w
    6,     // .bw.w.w
    -3,    // bbw.w.w
    -9,    // wbw.w.w
    5,     // .ww.w.w
    3,     // bww.w.w
    -6,    // www.w.w
    -10,   // ...bw.w
    6,     // b..bw.w
    -8,    // w..bw.w
    1,     // .b.bw.w
    -1,    // bb.bw.w
    -9,    // wb.bw.w
    12,    // .w.bw.w
    -6,    // bw.bw.w
    2,     // ww.bw.w
    -5,    // ..bbw.w
    -8,    // b.bbw.w
    4,     // w.bbw.w
    3,     // .bbbw.w
    -6,    // bbbbw.w
    -16,   // wbbbw.w
    -17,   // .wbbw.w
    -10,   // bwbbw.w
    24,    // wwbbw.w
    -10,   // ..wbw.w
    -14,   // b.wbw.w
    0,     // w.wbw.w
    18,    // .bwbw.w
    5,     // bbwbw.w
    -13,   // wbwbw.w
    -4,    // .wwbw.w
    -5,    // bwwbw.w
    -1,    // wwwbw.w
    -14,   // ...ww.w
    12,    // b..ww.w
    5,     // w..ww.w
    -1,    // .b.ww.w
    -8,    // bb.ww.w
    24,    // wb.ww.w
    3,     // .w.ww.w
    -17,   // bw.ww.w
    -2,    // ww.ww.w
    -2,    // ..bww.w
    8,     // b.bww.w
    12,    // w.bww.w
    4,     // .bbww.w
    11,    // bbbww.w
    -1,    // wbbww.w
    -8,    // .wbww.w
    -14,   // bwbww.w
    5,     // wwbww.w
    3,     // ..www.w
    -5,    // b.www.w
    -6,    // w.www.w
    8,     // .bwww.w
    -16,   // bbwww.w
    12,    // wbwww.w
    6,     // .wwww.w
    1,     // bwwww.w
    -5,    // wwwww.w
    16,    // .....bw
    -8,    // b....bw
    0,     // w....bw
    -5,    // .b...bw
    -19,   // bb...bw
    8,     // wb...bw
    17,    // .w...bw
    0,     // bw...bw
    -10,   // ww...bw
    4,     // ..b..bw
    -10,   // b.b..bw
    12,    // w.b..bw
    -4,    // .bb..bw
    6,     // bbb..bw
    12,    // wbb..bw
    -3,    // .wb..bw
    -11,   // bwb..bw
    -11,   // wwb..bw
    -13,   // ..w..bw
    16,    // b.w..bw
    11,    // w.w..bw
    -11,   // .bw..bw
    1,     // bbw..bw
    -8,    // wbw..bw
    -14,   // .ww..bw
    4,     // bww..bw
    9,     // www..bw
    5,     // ...b.bw
    6,     // b..b.bw
    -14,   // w..b.bw
    0,     // .b.b.bw
    8,     // bb.b.bw
    4,     // wb.b.bw
    24,    // .w.b.bw
    12,    // bw.b.bw
    7,     // ww.b.bw
    3,     // ..bb.bw
    17,    // b.bb.bw
    -13,   // w.bb.bw
    1,     // .bbb.bw
    -3,    // bbbb.bw
    20,    // wbbb.bw
    1,     // .wbb.bw
    -1,    // bwbb.bw
    0,     // wwbb.bw
    4,     // ..wb.bw
    -3,    // b.wb.bw
    -9,    // w.wb.bw
    8,     // .bwb.bw
    6,     // bbwb.bw
    15,    // wbwb.bw
    1,     // .wwb.bw
    19,    // bwwb.bw
    -1,    // wwwb.bw
    -12,   // ...w.bw
    -6,    // b..w.bw
    -13,   // w..w.bw
    8,     // .b.w.bw
    -1,    // bb.w.bw
    2,     // wb.w.bw
    11,    // .w.w.bw
    -12,   // bw.w.bw
    4,     // ww.w.bw
    29,    // ..bw.bw
    6,     // b.bw.bw
    11,    // w.bw.bw
    5,     // .bbw.bw
    0,     // bbbw.bw
    -14,   // wbbw.bw
    2,     // .wbw.bw
    7,     // bwbw.bw
    -16,   // wwbw.bw
    -4,    // ..ww.bw
    1,     // b.ww.bw
    24,    // w.ww.bw
    -3,    // .bww.bw
    17,    // bbww.bw
    15,    // wbww.bw
    1,     // .www.bw
    -3,    // bwww.bw
    1,     // wwww.bw
    -26,   // ....bbw
    8,     // b...bbw
    1,     // w...bbw
    0,     // .b..bbw
    -1,    // bb..bbw
    12,    // wb..bbw
    -5,    // .w..bbw
    -4,    // bw..bbw
    8,     // ww..bbw
    2,     // ..b.bbw
    -3,    // b.b.bbw
    7,     // w.b.bbw
    2,     // .bb.bbw
    -9,    // bbb.bbw
    -6,    // wbb.bbw
    -8,    // .wb.bbw
    -7,    // bwb.bbw
    2,     // wwb.bbw
    -3,    // ..w.bbw
    -10,   // b.w.bbw
    9,     // w.w.bbw
    17,    // .bw.bbw
    6,     // bbw.bbw
    25,    // wbw.bbw
    -3,    // .ww.bbw
    0,     // bww.bbw
    10,    // www.bbw
    0,     // ...bbbw
    3,     // b..bbbw
    1,     // w..bbbw
    1,     // .b.bbbw
    -10,   // bb.bbbw
    20,    // wb.bbbw
    -9,    // .w.bbbw
    3,     // bw.bbbw
    -3,    // ww.bbbw
    16,    // ..bbbbw
    -1,    // b.bbbbw
    -8,    // w.bbbbw
    -11,   // .bbbbbw
    4,     // bbbbbbw
    -5,    // wbbbbbw
    9,     // .wbbbbw
    -7,    // bwbbbbw
    3,     // wwbbbbw
    1,     // ..wbbbw
    6,     // b.wbbbw
    -16,   // w.wbbbw
    -14,   // .bwbbbw
    -21,   // bbwbbbw
    2,     // wbwbbbw
    4,     // .wwbbbw
    -3,    // bwwbbbw
    -11,   // wwwbbbw
    6,     // ...wbbw
    -12,   // b..wbbw
    1,     // w..wbbw
    6,     // .b.wbbw
    -3,    // bb.wbbw
    -14,   // wb.wbbw
    -4,    // .w.wbbw
    -19,   // bw.wbbw
    -11,   // ww.wbbw
    6,     // ..bwbbw
    5,     // b.bwbbw
    -2,    // w.bwbbw
    -1,    // .bbwbbw
    -1,    // bbbwbbw
    -2,    // wbbwbbw
    -7,    // .wbwbbw
    -9,    // bwbwbbw
    1,     // wwbwbbw
    -17,   // ..wwbbw
    -2,    // b.wwbbw
    -1,    // w.wwbbw
    2,     // .bwwbbw
    1,     // bbwwbbw
    11,    // wbwwbbw
    1,     // .wwwbbw
    3,     // bwwwbbw
    2,     // wwwwbbw
    14,    // ....wbw
    11,    // b...wbw
    -14,   // w...wbw
    -33,   // .b..wbw
    -2,    // bb..wbw
    -8,    // wb..wbw
    2,     // .w..wbw
    11,    // bw..wbw
    -3,    // ww..wbw
    -2,    // ..b.wbw
    5,     // b.b.wbw
    1,     // w.b.wbw
    -7,    // .bb.wbw
    -8,    // bbb.wbw
    25,    // wbb.wbw
    0,     // .wb.wbw
    0,     // bwb.wbw
    -5,    // wwb.wbw
    -6,    // ..w.wbw
    1,     // b.w.wbw
    -9,    // w.w.wbw
    -12,   // .bw.wbw
    -3,    // bbw.wbw
    11,    // wbw.wbw
    13,    // .ww.wbw
    7,     // bww.wbw
    -11,   // www.wbw
    -5,    // ...bwbw
    -2,    // b..bwbw
    7,     // w..bwbw
    -6,    // .b.bwbw
    -7,    // bb.bwbw
    15,    // wb.bwbw
    -13,   // .w.bwbw
    -7,    // bw.bwbw
    8,     // ww.bwbw
    4,     // ..bbwbw
    14,    // b.bbwbw
    -11,   // w.bbwbw
    -6,    // .bbbwbw
    3,     // bbbbwbw
    2,     // wbbbwbw
    7,     // .wbbwbw
    -10,   // bwbbwbw
    11,    // wwbbwbw
    1,     // ..wbwbw
    9,     // b.wbwbw
    -13,   // w.wbwbw
    3,     // .bwbwbw
    -9,    // bbwbwbw
    7,     // wbwbwbw
    8,     // .wwbwbw
    9,     // bwwbwbw
    -6,    // wwwbwbw
    -13,   // ...wwbw
    -5,    // b..wwbw
    10,    // w..wwbw
    7,     // .b.wwbw
    2,     // bb.wwbw
    15,    // wb.wwbw
    5,     // .w.wwbw
    1,     // bw.wwbw
    11,    // ww.wwbw
    -1,    // ..bwwbw
    10,    // b.bwwbw
    -14,   // w.bwwbw
    -1,    // .bbwwbw
    4,     // bbbwwbw
    11,    // wbbwwbw
    -5,    // .wbwwbw
    10,    // bwbwwbw
    -11,   // wwbwwbw
    4,     // ..wwwbw
    8,     // b.wwwbw
    12,    // w.wwwbw
    -3,    // .bwwwbw
    -12,   // bbwwwbw
    6,     // wbwwwbw
    9,     // .wwwwbw
    7,     // bwwwwbw
    -5,    // wwwwwbw
    -3,    // .....ww
    -6,    // b....ww
    -10,   // w....ww
    -7,    // .b...ww
    0,     // bb...ww
    -10,   // wb...ww
    -15,   // .w...ww
    19,    // bw...ww
    -3,    // ww...ww
    2,     // ..b..ww
    -12,   // b.b..ww
    -1,    // w.b..ww
    3,     // .bb..ww
    1,     // bbb..ww
    8,     // wbb..ww
    -5,    // .wb..ww
    2,     // bwb..ww
    1,     // wwb..ww
    -10,   // ..w..ww
    0,     // b.w..ww
    -4,    // w.w..ww
    -10,   // .bw..ww
    -14,   // bbw..ww
    -3,    // wbw..ww
    -1,    // .ww..ww
    1,     // bww..ww
    5,     // www..ww
    8,     // ...b.ww
    -6,    // b..b.ww
    20,    // w..b.ww
    -12,   // .b.b.ww
    -4,    // bb.b.ww
    7,     // wb.b.ww
    7,     // .w.b.ww
    1,     // bw.b.ww
    0,     // ww.b.ww
    2,     // ..bb.ww
    8,     // b.bb.ww
    -14,   // w.bb.ww
    -7,    // .bbb.ww
    -3,    // bbbb.ww
    -3,    // wbbb.ww
    -6,    // .wbb.ww
    -2,    // bwbb.ww
    1,     // wwbb.ww
    12,    // ..wb.ww
    -10,   // b.wb.ww
    2,     // w.wb.ww
    -2,    // .bwb.ww
    6,     // bbwb.ww
    8,     // wbwb.ww
    -8,    // .wwb.ww
    3,     // bwwb.ww
    4,     // wwwb.ww
    9,     // ...w.ww
    3,     // b..w.ww
    -4,    // w..w.ww
    -2,    // .b.w.ww
    4,     // bb.w.ww
    4,     // wb.w.ww
    -6,    // .w.w.ww
    -8,    // bw.w.ww
    -7,    // ww.w.ww
    -3,    // ..bw.ww
    1,     // b.bw.ww
    15,    // w.bw.ww
    -4,    // .bbw.ww
    -3,    // bbbw.ww
    -11,   // wbbw.ww
    6,     // .wbw.ww
    7,     // bwbw.ww
    -3,    // wwbw.ww
    -2,    // ..ww.ww
    -10,   // b.ww.ww
    -2,    // w.ww.ww
    -11,   // .bww.ww
    15,    // bbww.ww
    11,    // wbww.ww
    -9,    // .www.ww
    10,    // bwww.ww
    -11,   // wwww.ww
    13,    // ....bww
    -7,    // b...bww
    -7,    // w...bww
    4,     // .b..bww
    14,    // bb..bww
    -11,   // wb..bww
    -7,    // .w..bww
    -1,    // bw..bww
    1,     // ww..bww
    1,     // ..b.bww
    3,     // b.b.bww
    -5,    // w.b.bww
    -3,    // .bb.bww
    8,     // bbb.bww
    2,     // wbb.bww
    3,     // .wb.bww
    3,     // bwb.bww
    19,    // wwb.bww
    14,    // ..w.bww
    7,     // b.w.bww
    4,     // w.w.bww
    7,     // .bw.bww
    0,     // bbw.bww
    -5,    // wbw.bww
    -10,   // .ww.bww
    -6,    // bww.bww
    6,     // www.bww
    10,    // ...bbww
    9,     // b..bbww
    -6,    // w..bbww
    -4,    // .b.bbww
    -15,   // bb.bbww
    0,     // wb.bbww
    -13,   // .w.bbww
    -17,   // bw.bbww
    1,     // ww.bbww
    -4,    // ..bbbww
    16,    // b.bbbww
    4,     // w.bbbww
    2,     // .bbbbww
    4,     // bbbbbww
    3,     // wbbbbww
    14,    // .wbbbww
    12,    // bwbbbww
    1,     // wwbbbww
    -3,    // ..wbbww
    2,     // b.wbbww
    24,    // w.wbbww
    -15,   // .bwbbww
    -1,    // bbwbbww
    11,    // wbwbbww
    16,    // .wwbbww
    -1,    // bwwbbww
    18,    // wwwbbww
    2,     // ...wbww
    0,     // b..wbww
    -6,    // w..wbww
    7,     // .b.wbww
    -6,    // bb.wbww
    -16,   // wb.wbww
    13,    // .w.wbww
    -6,    // bw.wbww
    -3,    // ww.wbww
    -16,   // ..bwbww
    -5,    // b.bwbww
    -8,    // w.bwbww
    10,    // .bbwbww
    7,     // bbbwbww
    1,     // wbbwbww
    -9,    // .wbwbww
    9,     // bwbwbww
    -4,    // wwbwbww
    -6,    // ..wwbww
    9,     // b.wwbww
    5,     // w.wwbww
    0,     // .bwwbww
    1,     // bbwwbww
    -11,   // wbwwbww
    1,     // .wwwbww
    21,    // bwwwbww
    4,     // wwwwbww
    -27,   // ....www
    -12,   // b...www
    -15,   // w...www
    8,     // .b..www
    -1,    // bb..www
    9,     // wb..www
    0,     // .w..www
    -6,    // bw..www
    5,     // ww..www
    8,     // ..b.www
    13,    // b.b.www
    -14,   // w.b.www
    -3,    // .bb.www
    0,     // bbb.www
    10,    // wbb.www
    -1,    // .wb.www
    8,     // bwb.www
    6,     // wwb.www
    -6,    // ..w.www
    -19,   // b.w.www
    -6,    // w.w.www
    4,     // .bw.www
    -8,    // bbw.www
    -11,   // wbw.www
    12,    // .ww.www
    9,     // bww.www
    7,     // www.www
    7,     // ...bwww
    3,     // b..bwww
    -5,    // w..bwww
    -8,    // .b.bwww
    3,     // bb.bwww
    -1,    // wb.bwww
    6,     // .w.bwww
    0,     // bw.bwww
    4,     // ww.bwww
    10,    // ..bbwww
    -11,   // b.bbwww
    5,     // w.bbwww
    14,    // .bbbwww
    6,     // bbbbwww
    -11,   // wbbbwww
    1,     // .wbbwww
    -4,    // bwbbwww
    18,    // wwbbwww
    0,     // ..wbwww
    -4,    // b.wbwww
    -1,    // w.wbwww
    2,     // .bwbwww
    -7,    // bbwbwww
    -6,    // wbwbwww
    0,     // .wwbwww
    1,     // bwwbwww
    -7,    // wwwbwww
    -4,    // ...wwww
    12,    // b..wwww
    17,    // w..wwww
    0,     // .b.wwww
    3,     // bb.wwww
    1,     // wb.wwww
    1,     // .w.wwww
    3,     // bw.wwww
    -11,   // ww.wwww
    12,    // ..bwwww
    6,     // b.bwwww
    -9,    // w.bwwww
    -5,    // .bbwwww
    -6,    // bbbwwww
    2,     // wbbwwww
    -2,    // .wbwwww
    -3,    // bwbwwww
    4,     // wwbwwww
    -13,   // ..wwwww
    6,     // b.wwwww
    -5,    // w.wwwww
    9,     // .bwwwww
    -4,    // bbwwwww
    -5,    // wbwwwww
    -21,   // .wwwwww
    -4,    // bwwwwww
    8,     // wwwwwww
    -12,   // ccc
    0,     // cc
    1,     // c
    26,    // ttt
    9,     // tt
    2,     // t
    -3,    // ct
    -1,    // cct
    -14,   // ctt
].into_boxed_slice()
