vec![
    0,     // ......
    15,    // b.....
    -15,   // w.....
    -25,   // .b....
    73,    // bb....
    -40,   // wb....
    25,    // .w....
    40,    // bw....
    -73,   // ww....
    -6,    // ..b...
    62,    // b.b...
    -15,   // w.b...
    -50,   // .bb...
    192,   // bbb...
    -67,   // wbb...
    -49,   // .wb...
    8,     // bwb...
    34,    // wwb...
    6,     // ..w...
    15,    // b.w...
    -62,   // w.w...
    49,    // .bw...
    -34,   // bbw...
    -8,    // wbw...
    50,    // .ww...
    67,    // bww...
    -192,  // www...
    -6,    // ...b..
    -10,   // b..b..
    -8,    // w..b..
    -12,   // .b.b..
    159,   // bb.b..
    -67,   // wb.b..
    68,    // .w.b..
    74,    // bw.b..
    -81,   // ww.b..
    -68,   // ..bb..
    1,     // b.bb..
    -50,   // w.bb..
    -19,   // .bbb..
    446,   // bbbb..
    -150,  // wbbb..
    -95,   // .wbb..
    -5,    // bwbb..
    57,    // wwbb..
    0,     // ..wb..
    -77,   // b.wb..
    -34,   // w.wb..
    18,    // .bwb..
    -109,  // bbwb..
    15,    // wbwb..
    -1,    // .wwb..
    85,    // bwwb..
    22,    // wwwb..
    6,     // ...w..
    8,     // b..w..
    10,    // w..w..
    -68,   // .b.w..
    81,    // bb.w..
    -74,   // wb.w..
    12,    // .w.w..
    67,    // bw.w..
    -159,  // ww.w..
    0,     // ..bw..
    34,    // b.bw..
    77,    // w.bw..
    1,     // .bbw..
    -22,   // bbbw..
    -85,   // wbbw..
    -18,   // .wbw..
    -15,   // bwbw..
    109,   // wwbw..
    68,    // ..ww..
    50,    // b.ww..
    -1,    // w.ww..
    95,    // .bww..
    -57,   // bbww..
    5,     // wbww..
    19,    // .www..
    150,   // bwww..
    -446,  // wwww..
    -25,   // ....b.
    -18,   // b...b.
    -95,   // w...b.
    17,    // .b..b.
    75,    // bb..b.
    -30,   // wb..b.
    0,     // .w..b.
    27,    // bw..b.
    -7,    // ww..b.
    -12,   // ..b.b.
    -2,    // b.b.b.
    -19,   // w.b.b.
    -63,   // .bb.b.
    185,   // bbb.b.
    -72,   // wbb.b.
    -71,   // .wb.b.
    58,    // bwb.b.
    10,    // wwb.b.
    -68,   // ..w.b.
    -109,  // b.w.b.
    -19,   // w.w.b.
    58,    // .bw.b.
    -16,   // bbw.b.
    -21,   // wbw.b.
    60,    // .ww.b.
    -48,   // bww.b.
    -161,  // www.b.
    -50,   // ...bb.
    -114,  // b..bb.
    -44,   // w..bb.
    -63,   // .b.bb.
    -59,   // bb.bb.
    -87,   // wb.bb.
    -60,   // .w.bb.
    -75,   // bw.bb.
    -3,    // ww.bb.
    -19,   // ..bbb.
    108,   // b.bbb.
    -60,   // w.bbb.
    324,   // .bbbb.
    112,   // bbbbb.
    326,   // wbbbb.
    -27,   // .wbbb.
    -42,   // bwbbb.
    -134,  // wwbbb.
    1,     // ..wbb.
    -8,    // b.wbb.
    -57,   // w.wbb.
    -43,   // .bwbb.
    -135,  // bbwbb.
    -66,   // wbwbb.
    0,     // .wwbb.
    -55,   // bwwbb.
    -113,  // wwwbb.
    49,    // ...wb.
    19,    // b..wb.
    71,    // w..wb.
    58,    // .b.wb.
    33,    // bb.wb.
    -11,   // wb.wb.
    71,    // .w.wb.
    -55,   // bw.wb.
    45,    // ww.wb.
    18,    // ..bwb.
    -102,  // b.bwb.
    -44,   // w.bwb.
    -43,   // .bbwb.
    -82,   // bbbwb.
    -5,    // wbbwb.
    0,     // .wbwb.
    -81,   // bwbwb.
    52,    // wwbwb.
    95,    // ..wwb.
    -26,   // b.wwb.
    79,    // w.wwb.
    -14,   // .bwwb.
    -111,  // bbwwb.
    -18,   // wbwwb.
    27,    // .wwwb.
    8,     // bwwwb.
    101,   // wwwwb.
    25,    // ....w.
    95,    // b...w.
    18,    // w...w.
    0,     // .b..w.
    7,     // bb..w.
    -27,   // wb..w.
    -17,   // .w..w.
    30,    // bw..w.
    -75,   // ww..w.
    68,    // ..b.w.
    19,    // b.b.w.
    109,   // w.b.w.
    -60,   // .bb.w.
    161,   // bbb.w.
    48,    // wbb.w.
    -58,   // .wb.w.
    21,    // bwb.w.
    16,    // wwb.w.
    12,    // ..w.w.
    19,    // b.w.w.
    2,     // w.w.w.
    71,    // .bw.w.
    -10,   // bbw.w.
    -58,   // wbw.w.
    63,    // .ww.w.
    72,    // bww.w.
    -185,  // www.w.
    -49,   // ...bw.
    -71,   // b..bw.
    -19,   // w..bw.
    -71,   // .b.bw.
    -45,   // bb.bw.
    55,    // wb.bw.
    -58,   // .w.bw.
    11,    // bw.bw.
    -33,   // ww.bw.
    -95,   // ..bbw.
    -79,   // b.bbw.
    26,    // w.bbw.
    -27,   // .bbbw.
    -101,  // bbbbw.
    -8,    // wbbbw.
    14,    // .wbbw.
    18,    // bwbbw.
    111,   // wwbbw.
    -18,   // ..wbw.
    44,    // b.wbw.
    102,   // w.wbw.
    0,     // .bwbw.
    -52,   // bbwbw.
    81,    // wbwbw.
    43,    // .wwbw.
    5,     // bwwbw.
    82,    // wwwbw.
    50,    // ...ww.
    44,    // b..ww.
    114,   // w..ww.
    60,    // .b.ww.
    3,     // bb.ww.
    75,    // wb.ww.
    63,    // .w.ww.
    87,    // bw.ww.
    59,    // ww.ww.
    -1,    // ..bww.
    57,    // b.bww.
    8,     // w.bww.
    0,     // .bbww.
    113,   // bbbww.
    55,    // wbbww.
    43,    // .wbww.
    66,    // bwbww.
    135,   // wwbww.
    19,    // ..www.
    60,    // b.www.
    -108,  // w.www.
    27,    // .bwww.
    134,   // bbwww.
    42,    // wbwww.
    -324,  // .wwww.
    -326,  // bwwww.
    -112,  // wwwww.
    15,    // .....b
    24,    // b....b
    0,     // w....b
    -18,   // .b...b
    -59,   // bb...b
    -14,   // wb...b
    95,    // .w...b
    87,    // bw...b
    15,    // ww...b
    -10,   // ..b..b
    -33,   // b.b..b
    -51,   // w.b..b
    -114,  // .bb..b
    152,   // bbb..b
    -209,  // wbb..b
    -71,   // .wb..b
    -122,  // bwb..b
    -91,   // wwb..b
    8,     // ..w..b
    24,    // b.w..b
    9,     // w.w..b
    19,    // .bw..b
    181,   // bbw..b
    -53,   // wbw..b
    44,    // .ww..b
    -42,   // bww..b
    2,     // www..b
    62,    // ...b.b
    -33,   // b..b.b
    -9,    // w..b.b
    -2,    // .b.b.b
    59,    // bb.b.b
    -165,  // wb.b.b
    19,    // .w.b.b
    -64,   // bw.b.b
    78,    // ww.b.b
    1,     // ..bb.b
    -61,   // b.bb.b
    -102,  // w.bb.b
    108,   // .bbb.b
    44,    // bbbb.b
    331,   // wbbb.b
    -79,   // .wbb.b
    -142,  // bwbb.b
    40,    // wwbb.b
    34,    // ..wb.b
    -99,   // b.wb.b
    0,     // w.wb.b
    -102,  // .bwb.b
    -36,   // bbwb.b
    67,    // wbwb.b
    57,    // .wwb.b
    -30,   // bwwb.b
    -14,   // wwwb.b
    15,    // ...w.b
    24,    // b..w.b
    51,    // w..w.b
    -109,  // .b.w.b
    -9,    // bb.w.b
    -24,   // wb.w.b
    19,    // .w.w.b
    -2,    // bw.w.b
    -55,   // ww.w.b
    -77,   // ..bw.b
    -99,   // b.bw.b
    0,     // w.bw.b
    -8,    // .bbw.b
    -19,   // bbbw.b
    -96,   // wbbw.b
    44,    // .wbw.b
    -29,   // bwbw.b
    -15,   // wwbw.b
    50,    // ..ww.b
    -120,  // b.ww.b
    102,   // w.ww.b
    -26,   // .bww.b
    100,   // bbww.b
    13,    // wbww.b
    60,    // .www.b
    124,   // bwww.b
    -224,  // wwww.b
    73,    // ....bb
    -59,   // b...bb
    -15,   // w...bb
    75,    // .b..bb
    33,    // bb..bb
    69,    // wb..bb
    7,     // .w..bb
    -63,   // bw..bb
    0,     // ww..bb
    159,   // ..b.bb
    59,    // b.b.bb
    55,    // w.b.bb
    -59,   // .bb.bb
    116,   // bbb.bb
    117,   // wbb.bb
    -45,   // .wb.bb
    72,    // bwb.bb
    -19,   // wwb.bb
    81,    // ..w.bb
    -9,    // b.w.bb
    -78,   // w.w.bb
    33,    // .bw.bb
    184,   // bbw.bb
    36,    // wbw.bb
    3,     // .ww.bb
    148,   // bww.bb
    54,    // www.bb
    192,   // ...bbb
    152,   // b..bbb
    -2,    // w..bbb
    185,   // .b.bbb
    116,   // bb.bbb
    17,    // wb.bbb
    161,   // .w.bbb
    116,   // bw.bbb
    -54,   // ww.bbb
    446,   // ..bbbb
    44,    // b.bbbb
    224,   // w.bbbb
    112,   // .bbbbb
    21,    // bbbbbb
    -25,   // wbbbbb
    -101,  // .wbbbb
    -64,   // bwbbbb
    -9,    // wwbbbb
    -22,   // ..wbbb
    -19,   // b.wbbb
    14,    // w.wbbb
    -82,   // .bwbbb
    78,    // bbwbbb
    -59,   // wbwbbb
    113,   // .wwbbb
    46,    // bwwbbb
    0,     // wwwbbb
    -34,   // ...wbb
    181,   // b..wbb
    91,    // w..wbb
    -16,   // .b.wbb
    184,   // bb.wbb
    -164,  // wb.wbb
    -10,   // .w.wbb
    11,    // bw.wbb
    19,    // ww.wbb
    -109,  // ..bwbb
    -36,   // b.bwbb
    15,    // w.bwbb
    -135,  // .bbwbb
    78,    // bbbwbb
    -19,   // wbbwbb
    -52,   // .wbwbb
    88,    // bwbwbb
    0,     // wwbwbb
    -57,   // ..wwbb
    100,   // b.wwbb
    -40,   // w.wwbb
    -111,  // .bwwbb
    -18,   // bbwwbb
    19,    // wbwwbb
    134,   // .wwwbb
    61,    // bwwwbb
    9,     // wwwwbb
    40,    // ....wb
    87,    // b...wb
    14,    // w...wb
    27,    // .b..wb
    -63,   // bb..wb
    0,     // wb..wb
    30,    // .w..wb
    36,    // bw..wb
    -69,   // ww..wb
    74,    // ..b.wb
    -64,   // b.b.wb
    24,    // w.b.wb
    -75,   // .bb.wb
    116,   // bbb.wb
    -155,  // wbb.wb
    11,    // .wb.wb
    131,   // bwb.wb
    164,   // wwb.wb
    67,    // ..w.wb
    -2,    // b.w.wb
    165,   // w.w.wb
    -55,   // .bw.wb
    11,    // bbw.wb
    38,    // wbw.wb
    87,    // .ww.wb
    -64,   // bww.wb
    -17,   // www.wb
    8,     // ...bwb
    -122,  // b..bwb
    53,    // w..bwb
    58,    // .b.bwb
    72,    // bb.bwb
    -38,   // wb.bwb
    21,    // .w.bwb
    131,   // bw.bwb
    -36,   // ww.bwb
    -5,    // ..bbwb
    -142,  // b.bbwb
    -13,   // w.bbwb
    -42,   // .bbbwb
    -64,   // bbbbwb
    14,    // wbbbwb
    18,    // .wbbwb
    -114,  // bwbbwb
    -19,   // wwbbwb
    -15,   // ..wbwb
    -29,   // b.wbwb
    -67,   // w.wbwb
    -81,   // .bwbwb
    88,    // bbwbwb
    0,     // wbwbwb
    66,    // .wwbwb
    -94,   // bwwbwb
    59,    // wwwbwb
    67,    // ...wwb
    -42,   // b..wwb
    209,   // w..wwb
    -48,   // .b.wwb
    148,   // bb.wwb
    155,   // wb.wwb
    72,    // .w.wwb
    -64,   // bw.wwb
    -117,  // ww.wwb
    85,    // ..bwwb
    -30,   // b.bwwb
    96,    // w.bwwb
    -55,   // .bbwwb
    46,    // bbbwwb
    0,     // wbbwwb
    5,     // .wbwwb
    -94,   // bwbwwb
    19,    // wwbwwb
    150,   // ..wwwb
    124,   // b.wwwb
    -331,  // w.wwwb
    8,     // .bwwwb
    61,    // bbwwwb
    -14,   // wbwwwb
    -326,  // .wwwwb
    94,    // bwwwwb
    25,    // wwwwwb
    -15,   // .....w
    0,     // b....w
    -24,   // w....w
    -95,   // .b...w
    -15,   // bb...w
    -87,   // wb...w
    18,    // .w...w
    14,    // bw...w
    59,    // ww...w
    -8,    // ..b..w
    -9,    // b.b..w
    -24,   // w.b..w
    -44,   // .bb..w
    -2,    // bbb..w
    42,    // wbb..w
    -19,   // .wb..w
    53,    // bwb..w
    -181,  // wwb..w
    10,    // ..w..w
    51,    // b.w..w
    33,    // w.w..w
    71,    // .bw..w
    91,    // bbw..w
    122,   // wbw..w
    114,   // .ww..w
    209,   // bww..w
    -152,  // www..w
    -15,   // ...b.w
    -51,   // b..b.w
    -24,   // w..b.w
    -19,   // .b.b.w
    55,    // bb.b.w
    2,     // wb.b.w
    109,   // .w.b.w
    24,    // bw.b.w
    9,     // ww.b.w
    -50,   // ..bb.w
    -102,  // b.bb.w
    120,   // w.bb.w
    -60,   // .bbb.w
    224,   // bbbb.w
    -124,  // wbbb.w
    26,    // .wbb.w
    -13,   // bwbb.w
    -100,  // wwbb.w
    77,    // ..wb.w
    0,     // b.wb.w
    99,    // w.wb.w
    -44,   // .bwb.w
    15,    // bbwb.w
    29,    // wbwb.w
    8,     // .wwb.w
    96,    // bwwb.w
    19,    // wwwb.w
    -62,   // ...w.w
    9,     // b..w.w
    33,    // w..w.w
    -19,   // .b.w.w
    -78,   // bb.w.w
    64,    // wb.w.w
    2,     // .w.w.w
    165,   // bw.w.w
    -59,   // ww.w.w
    -34,   // ..bw.w
    0,     // b.bw.w
    99,    // w.bw.w
    -57,   // .bbw.w
    14,    // bbbw.w
    30,    // wbbw.w
    102,   // .wbw.w
    -67,   // bwbw.w
    36,    // wwbw.w
    -1,    // ..ww.w
    102,   // b.ww.w
    61,    // w.ww.w
    79,    // .bww.w
    -40,   // bbww.w
    142,   // wbww.w
    -108,  // .www.w
    -331,  // bwww.w
    -44,   // wwww.w
    -40,   // ....bw
    -14,   // b...bw
    -87,   // w...bw
    -30,   // .b..bw
    69,    // bb..bw
    -36,   // wb..bw
    -27,   // .w..bw
    0,     // bw..bw
    63,    // ww..bw
    -67,   // ..b.bw
    -165,  // b.b.bw
    2,     // w.b.bw
    -87,   // .bb.bw
    17,    // bbb.bw
    64,    // wbb.bw
    55,    // .wb.bw
    -38,   // bwb.bw
    -11,   // wwb.bw
    -74,   // ..w.bw
    -24,   // b.w.bw
    64,    // w.w.bw
    -11,   // .bw.bw
    -164,  // bbw.bw
    -131,  // wbw.bw
    75,    // .ww.bw
    155,   // bww.bw
    -116,  // www.bw
    -67,   // ...bbw
    -209,  // b..bbw
    42,    // w..bbw
    -72,   // .b.bbw
    117,   // bb.bbw
    64,    // wb.bbw
    48,    // .w.bbw
    -155,  // bw.bbw
    -148,  // ww.bbw
    -150,  // ..bbbw
    331,   // b.bbbw
    -124,  // w.bbbw
    326,   // .bbbbw
    -25,   // bbbbbw
    -94,   // wbbbbw
    -8,    // .wbbbw
    14,    // bwbbbw
    -61,   // wwbbbw
    -85,   // ..wbbw
    -96,   // b.wbbw
    30,    // w.wbbw
    -5,    // .bwbbw
    -19,   // bbwbbw
    94,    // wbwbbw
    55,    // .wwbbw
    0,     // bwwbbw
    -46,   // wwwbbw
    -8,    // ...wbw
    -53,   // b..wbw
    122,   // w..wbw
    -21,   // .b.wbw
    36,    // bb.wbw
    -131,  // wb.wbw
    -58,   // .w.wbw
    38,    // bw.wbw
    -72,   // ww.wbw
    15,    // ..bwbw
    67,    // b.bwbw
    29,    // w.bwbw
    -66,   // .bbwbw
    -59,   // bbbwbw
    94,    // wbbwbw
    81,    // .wbwbw
    0,     // bwbwbw
    -88,   // wwbwbw
    5,     // ..wwbw
    13,    // b.wwbw
    142,   // w.wwbw
    -18,   // .bwwbw
    19,    // bbwwbw
    114,   // wbwwbw
    42,    // .wwwbw
    -14,   // bwwwbw
    64,    // wwwwbw
    -73,   // ....ww
    15,    // b...ww
    59,    // w...ww
    -7,    // .b..ww
    0,     // bb..ww
    63,    // wb..ww
    -75,   // .w..ww
    -69,   // bw..ww
    -33,   // ww..ww
    -81,   // ..b.ww
    78,    // b.b.ww
    9,     // w.b.ww
    -3,    // .bb.ww
    -54,   // bbb.ww
    -148,  // wbb.ww
    -33,   // .wb.ww
    -36,   // bwb.ww
    -184,  // wwb.ww
    -159,  // ..w.ww
    -55,   // b.w.ww
    -59,   // w.w.ww
    45,    // .bw.ww
    19,    // bbw.ww
    -72,   // wbw.ww
    59,    // .ww.ww
    -117,  // bww.ww
    -116,  // www.ww
    34,    // ...bww
    -91,   // b..bww
    -181,  // w..bww
    10,    // .b.bww
    -19,   // bb.bww
    -11,   // wb.bww
    16,    // .w.bww
    164,   // bw.bww
    -184,  // ww.bww
    57,    // ..bbww
    40,    // b.bbww
    -100,  // w.bbww
    -134,  // .bbbww
    -9,    // bbbbww
    -61,   // wbbbww
    111,   // .wbbww
    -19,   // bwbbww
    18,    // wwbbww
    109,   // ..wbww
    -15,   // b.wbww
    36,    // w.wbww
    52,    // .bwbww
    0,     // bbwbww
    -88,   // wbwbww
    135,   // .wwbww
    19,    // bwwbww
    -78,   // wwwbww
    -192,  // ...www
    2,     // b..www
    -152,  // w..www
    -161,  // .b.www
    54,    // bb.www
    -116,  // wb.www
    -185,  // .w.www
    -17,   // bw.www
    -116,  // ww.www
    22,    // ..bwww
    -14,   // b.bwww
    19,    // w.bwww
    -113,  // .bbwww
    0,     // bbbwww
    -46,   // wbbwww
    82,    // .wbwww
    59,    // bwbwww
    -78,   // wwbwww
    -446,  // ..wwww
    -224,  // b.wwww
    -44,   // w.wwww
    101,   // .bwwww
    9,     // bbwwww
    64,    // wbwwww
    -112,  // .wwwww
    25,    // bwwwww
    -21,   // wwwwww
    0,     // ccc
    123,   // cc
    123,   // c
    -45,   // ttt
    164,   // tt
    113,   // t
    -59,   // ct
    44,    // cct
    59,    // ctt
].into_boxed_slice()
