vec![
    0,     // ......
    13,    // b.....
    -13,   // w.....
    -3,    // .b....
    27,    // bb....
    -33,   // wb....
    3,     // .w....
    33,    // bw....
    -27,   // ww....
    -1,    // ..b...
    -23,   // b.b...
    -5,    // w.b...
    -13,   // .bb...
    29,    // bbb...
    -9,    // wbb...
    7,     // .wb...
    15,    // bwb...
    -9,    // wwb...
    1,     // ..w...
    5,     // b.w...
    23,    // w.w...
    -7,    // .bw...
    9,     // bbw...
    -15,   // wbw...
    13,    // .ww...
    9,     // bww...
    -29,   // www...
    -1,    // ...b..
    -31,   // b..b..
    5,     // w..b..
    -21,   // .b.b..
    53,    // bb.b..
    29,    // wb.b..
    19,    // .w.b..
    -1,    // bw.b..
    1,     // ww.b..
    -45,   // ..bb..
    5,     // b.bb..
    -29,   // w.bb..
    31,    // .bbb..
    3,     // bbbb..
    -35,   // wbbb..
    -13,   // .wbb..
    9,     // bwbb..
    43,    // wwbb..
    0,     // ..wb..
    -11,   // b.wb..
    -3,    // w.wb..
    -29,   // .bwb..
    57,    // bbwb..
    33,    // wbwb..
    1,     // .wwb..
    7,     // bwwb..
    47,    // wwwb..
    1,     // ...w..
    -5,    // b..w..
    31,    // w..w..
    -19,   // .b.w..
    -1,    // bb.w..
    1,     // wb.w..
    21,    // .w.w..
    -29,   // bw.w..
    -53,   // ww.w..
    0,     // ..bw..
    3,     // b.bw..
    11,    // w.bw..
    -1,    // .bbw..
    -47,   // bbbw..
    -7,    // wbbw..
    29,    // .wbw..
    -33,   // bwbw..
    -57,   // wwbw..
    45,    // ..ww..
    29,    // b.ww..
    -5,    // w.ww..
    13,    // .bww..
    -43,   // bbww..
    -9,    // wbww..
    -31,   // .www..
    35,    // bwww..
    -3,    // wwww..
    -3,    // ....b.
    -11,   // b...b.
    39,    // w...b.
    29,    // .b..b.
    31,    // bb..b.
    3,     // wb..b.
    0,     // .w..b.
    -23,   // bw..b.
    23,    // ww..b.
    -21,   // ..b.b.
    25,    // b.b.b.
    21,    // w.b.b.
    13,    // .bb.b.
    9,     // bbb.b.
    -25,   // wbb.b.
    -3,    // .wb.b.
    -27,   // bwb.b.
    -11,   // wwb.b.
    -19,   // ..w.b.
    -31,   // b.w.b.
    -19,   // w.w.b.
    -5,    // .bw.b.
    15,    // bbw.b.
    -5,    // wbw.b.
    -1,    // .ww.b.
    3,     // bww.b.
    17,    // www.b.
    -13,   // ...bb.
    -15,   // b..bb.
    11,    // w..bb.
    13,    // .b.bb.
    -1,    // bb.bb.
    17,    // wb.bb.
    1,     // .w.bb.
    -23,   // bw.bb.
    -1,    // ww.bb.
    31,    // ..bbb.
    19,    // b.bbb.
    5,     // w.bbb.
    35,    // .bbbb.
    5,     // bbbbb.
    53,    // wbbbb.
    -23,   // .wbbb.
    11,    // bwbbb.
    49,    // wwbbb.
    -1,    // ..wbb.
    31,    // b.wbb.
    3,     // w.wbb.
    1,     // .bwbb.
    -25,   // bbwbb.
    13,    // wbwbb.
    0,     // .wwbb.
    -25,   // bwwbb.
    39,    // wwwbb.
    -7,    // ...wb.
    -75,   // b..wb.
    -21,   // w..wb.
    -5,    // .b.wb.
    -31,   // bb.wb.
    -47,   // wb.wb.
    3,     // .w.wb.
    11,    // bw.wb.
    -27,   // ww.wb.
    -29,   // ..bwb.
    9,     // b.bwb.
    21,    // w.bwb.
    1,     // .bbwb.
    -13,   // bbbwb.
    15,    // wbbwb.
    0,     // .wbwb.
    -65,   // bwbwb.
    -13,   // wwbwb.
    13,    // ..wwb.
    -31,   // b.wwb.
    -27,   // w.wwb.
    39,    // .bwwb.
    -43,   // bbwwb.
    -9,    // wbwwb.
    23,    // .wwwb.
    -11,   // bwwwb.
    37,    // wwwwb.
    3,     // ....w.
    -39,   // b...w.
    11,    // w...w.
    0,     // .b..w.
    -23,   // bb..w.
    23,    // wb..w.
    -29,   // .w..w.
    -3,    // bw..w.
    -31,   // ww..w.
    19,    // ..b.w.
    19,    // b.b.w.
    31,    // w.b.w.
    1,     // .bb.w.
    -17,   // bbb.w.
    -3,    // wbb.w.
    5,     // .wb.w.
    5,     // bwb.w.
    -15,   // wwb.w.
    21,    // ..w.w.
    -21,   // b.w.w.
    -25,   // w.w.w.
    3,     // .bw.w.
    11,    // bbw.w.
    27,    // wbw.w.
    -13,   // .ww.w.
    25,    // bww.w.
    -9,    // www.w.
    7,     // ...bw.
    21,    // b..bw.
    75,    // w..bw.
    -3,    // .b.bw.
    27,    // bb.bw.
    -11,   // wb.bw.
    5,     // .w.bw.
    47,    // bw.bw.
    31,    // ww.bw.
    -13,   // ..bbw.
    27,    // b.bbw.
    31,    // w.bbw.
    -23,   // .bbbw.
    -37,   // bbbbw.
    11,    // wbbbw.
    -39,   // .wbbw.
    9,     // bwbbw.
    43,    // wwbbw.
    29,    // ..wbw.
    -21,   // b.wbw.
    -9,    // w.wbw.
    0,     // .bwbw.
    13,    // bbwbw.
    65,    // wbwbw.
    -1,    // .wwbw.
    -15,   // bwwbw.
    13,    // wwwbw.
    13,    // ...ww.
    -11,   // b..ww.
    15,    // w..ww.
    -1,    // .b.ww.
    1,     // bb.ww.
    23,    // wb.ww.
    -13,   // .w.ww.
    -17,   // bw.ww.
    1,     // ww.ww.
    1,     // ..bww.
    -3,    // b.bww.
    -31,   // w.bww.
    0,     // .bbww.
    -39,   // bbbww.
    25,    // wbbww.
    -1,    // .wbww.
    -13,   // bwbww.
    25,    // wwbww.
    -31,   // ..www.
    -5,    // b.www.
    -19,   // w.www.
    23,    // .bwww.
    -49,   // bbwww.
    -11,   // wbwww.
    -35,   // .wwww.
    -53,   // bwwww.
    -5,    // wwwww.
    13,    // .....b
    -19,   // b....b
    0,     // w....b
    -11,   // .b...b
    5,     // bb...b
    33,    // wb...b
    -39,   // .w...b
    5,     // bw...b
    -13,   // ww...b
    -31,   // ..b..b
    29,    // b.b..b
    -17,   // w.b..b
    -15,   // .bb..b
    1,     // bbb..b
    -29,   // wbb..b
    21,    // .wb..b
    -23,   // bwb..b
    -15,   // wwb..b
    -5,    // ..w..b
    -9,    // b.w..b
    17,    // w.w..b
    -75,   // .bw..b
    35,    // bbw..b
    -7,    // wbw..b
    -11,   // .ww..b
    -13,   // bww..b
    -17,   // www..b
    -23,   // ...b.b
    29,    // b..b.b
    -17,   // w..b.b
    25,    // .b.b.b
    -21,   // bb.b.b
    -53,   // wb.b.b
    19,    // .w.b.b
    49,    // bw.b.b
    -47,   // ww.b.b
    5,     // ..bb.b
    21,    // b.bb.b
    29,    // w.bb.b
    19,    // .bbb.b
    19,    // bbbb.b
    -29,   // wbbb.b
    27,    // .wbb.b
    7,     // bwbb.b
    -23,   // wwbb.b
    3,     // ..wb.b
    5,     // b.wb.b
    0,     // w.wb.b
    9,     // .bwb.b
    27,    // bbwb.b
    7,     // wbwb.b
    -3,    // .wwb.b
    -43,   // bwwb.b
    -7,    // wwwb.b
    5,     // ...w.b
    -9,    // b..w.b
    17,    // w..w.b
    -31,   // .b.w.b
    25,    // bb.w.b
    41,    // wb.w.b
    -21,   // .w.w.b
    9,     // bw.w.b
    39,    // ww.w.b
    -11,   // ..bw.b
    5,     // b.bw.b
    0,     // w.bw.b
    31,    // .bbw.b
    -13,   // bbbw.b
    1,     // wbbw.b
    -21,   // .wbw.b
    3,     // bwbw.b
    3,     // wwbw.b
    29,    // ..ww.b
    13,    // b.ww.b
    -29,   // w.ww.b
    -31,   // .bww.b
    -33,   // bbww.b
    -15,   // wbww.b
    -5,    // .www.b
    43,    // bwww.b
    -47,   // wwww.b
    27,    // ....bb
    5,     // b...bb
    13,    // w...bb
    31,    // .b..bb
    43,    // bb..bb
    -1,    // wb..bb
    -23,   // .w..bb
    -9,    // bw..bb
    0,     // ww..bb
    53,    // ..b.bb
    -21,   // b.b.bb
    -39,   // w.b.bb
    -1,    // .bb.bb
    25,    // bbb.bb
    -15,   // wbb.bb
    27,    // .wb.bb
    5,     // bwb.bb
    43,    // wwb.bb
    -1,    // ..w.bb
    25,    // b.w.bb
    47,    // w.w.bb
    -31,   // .bw.bb
    51,    // bbw.bb
    13,    // wbw.bb
    1,     // .ww.bb
    3,     // bww.bb
    3,     // www.bb
    29,    // ...bbb
    1,     // b..bbb
    17,    // w..bbb
    9,     // .b.bbb
    25,    // bb.bbb
    -45,   // wb.bbb
    -17,   // .w.bbb
    -13,   // bw.bbb
    -3,    // ww.bbb
    3,     // ..bbbb
    19,    // b.bbbb
    47,    // w.bbbb
    5,     // .bbbbb
    7,     // bbbbbb
    -1,    // wbbbbb
    -37,   // .wbbbb
    31,    // bwbbbb
    5,     // wwbbbb
    -47,   // ..wbbb
    -13,   // b.wbbb
    7,     // w.wbbb
    -13,   // .bwbbb
    53,    // bbwbbb
    -33,   // wbwbbb
    -39,   // .wwbbb
    -5,    // bwwbbb
    0,     // wwwbbb
    9,     // ...wbb
    35,    // b..wbb
    15,    // w..wbb
    15,    // .b.wbb
    51,    // bb.wbb
    13,    // wb.wbb
    11,    // .w.wbb
    -21,   // bw.wbb
    -43,   // ww.wbb
    57,    // ..bwbb
    27,    // b.bwbb
    -3,    // w.bwbb
    -25,   // .bbwbb
    53,    // bbbwbb
    61,    // wbbwbb
    13,    // .wbwbb
    -45,   // bwbwbb
    0,     // wwbwbb
    -43,   // ..wwbb
    -33,   // b.wwbb
    23,    // w.wwbb
    -43,   // .bwwbb
    -3,    // bbwwbb
    15,    // wbwwbb
    -49,   // .wwwbb
    19,    // bwwwbb
    -5,    // wwwwbb
    33,    // ....wb
    5,     // b...wb
    -33,   // w...wb
    -23,   // .b..wb
    -9,    // bb..wb
    0,     // wb..wb
    -3,    // .w..wb
    19,    // bw..wb
    1,     // ww..wb
    -1,    // ..b.wb
    49,    // b.b.wb
    -41,   // w.b.wb
    -23,   // .bb.wb
    -13,   // bbb.wb
    -11,   // wbb.wb
    47,    // .wb.wb
    9,     // bwb.wb
    -13,   // wwb.wb
    -29,   // ..w.wb
    9,     // b.w.wb
    53,    // w.w.wb
    11,    // .bw.wb
    -21,   // bbw.wb
    9,     // wbw.wb
    -17,   // .ww.wb
    37,    // bww.wb
    45,    // www.wb
    15,    // ...bwb
    -23,   // b..bwb
    7,     // w..bwb
    -27,   // .b.bwb
    5,     // bb.bwb
    -9,    // wb.bwb
    5,     // .w.bwb
    9,     // bw.bwb
    -13,   // ww.bwb
    9,     // ..bbwb
    7,     // b.bbwb
    15,    // w.bbwb
    11,    // .bbbwb
    31,    // bbbbwb
    1,     // wbbbwb
    9,     // .wbbwb
    21,    // bwbbwb
    -15,   // wwbbwb
    -33,   // ..wbwb
    3,     // b.wbwb
    -7,    // w.wbwb
    -65,   // .bwbwb
    -45,   // bbwbwb
    0,     // wbwbwb
    -13,   // .wwbwb
    -57,   // bwwbwb
    33,    // wwwbwb
    9,     // ...wwb
    -13,   // b..wwb
    29,    // w..wwb
    3,     // .b.wwb
    3,     // bb.wwb
    11,    // wb.wwb
    25,    // .w.wwb
    37,    // bw.wwb
    15,    // ww.wwb
    7,     // ..bwwb
    -43,   // b.bwwb
    -1,    // w.bwwb
    -25,   // .bbwwb
    -5,    // bbbwwb
    0,     // wbbwwb
    -15,   // .wbwwb
    -57,   // bwbwwb
    -61,   // wwbwwb
    35,    // ..wwwb
    43,    // b.wwwb
    29,    // w.wwwb
    -11,   // .bwwwb
    19,    // bbwwwb
    -1,    // wbwwwb
    -53,   // .wwwwb
    85,    // bwwwwb
    1,     // wwwwwb
    -13,   // .....w
    0,     // b....w
    19,    // w....w
    39,    // .b...w
    13,    // bb...w
    -5,    // wb...w
    11,    // .w...w
    -33,   // bw...w
    -5,    // ww...w
    5,     // ..b..w
    -17,   // b.b..w
    9,     // w.b..w
    11,    // .bb..w
    17,    // bbb..w
    13,    // wbb..w
    75,    // .wb..w
    7,     // bwb..w
    -35,   // wwb..w
    31,    // ..w..w
    17,    // b.w..w
    -29,   // w.w..w
    -21,   // .bw..w
    15,    // bbw..w
    23,    // wbw..w
    15,    // .ww..w
    29,    // bww..w
    -1,    // www..w
    -5,    // ...b.w
    -17,   // b..b.w
    9,     // w..b.w
    21,    // .b.b.w
    -39,   // bb.b.w
    -9,    // wb.b.w
    31,    // .w.b.w
    -41,   // bw.b.w
    -25,   // ww.b.w
    -29,   // ..bb.w
    29,    // b.bb.w
    -13,   // w.bb.w
    5,     // .bbb.w
    47,    // bbbb.w
    -43,   // wbbb.w
    31,    // .wbb.w
    15,    // bwbb.w
    33,    // wwbb.w
    11,    // ..wb.w
    0,     // b.wb.w
    -5,    // w.wb.w
    21,    // .bwb.w
    -3,    // bbwb.w
    -3,    // wbwb.w
    -31,   // .wwb.w
    -1,    // bwwb.w
    13,    // wwwb.w
    23,    // ...w.w
    17,    // b..w.w
    -29,   // w..w.w
    -19,   // .b.w.w
    47,    // bb.w.w
    -49,   // wb.w.w
    -25,   // .w.w.w
    53,    // bw.w.w
    21,    // ww.w.w
    -3,    // ..bw.w
    0,     // b.bw.w
    -5,    // w.bw.w
    3,     // .bbw.w
    7,     // bbbw.w
    43,    // wbbw.w
    -9,    // .wbw.w
    -7,    // bwbw.w
    -27,   // wwbw.w
    -5,    // ..ww.w
    -29,   // b.ww.w
    -21,   // w.ww.w
    -27,   // .bww.w
    23,    // bbww.w
    -7,    // wbww.w
    -19,   // .www.w
    29,    // bwww.w
    -19,   // wwww.w
    -33,   // ....bw
    33,    // b...bw
    -5,    // w...bw
    3,     // .b..bw
    -1,    // bb..bw
    -19,   // wb..bw
    23,    // .w..bw
    0,     // bw..bw
    9,     // ww..bw
    29,    // ..b.bw
    -53,   // b.b.bw
    -9,    // w.b.bw
    17,    // .bb.bw
    -45,   // bbb.bw
    -37,   // wbb.bw
    -11,   // .wb.bw
    -9,    // bwb.bw
    21,    // wwb.bw
    1,     // ..w.bw
    41,    // b.w.bw
    -49,   // w.w.bw
    -47,   // .bw.bw
    13,    // bbw.bw
    -9,    // wbw.bw
    23,    // .ww.bw
    11,    // bww.bw
    13,    // www.bw
    -9,    // ...bbw
    -29,   // b..bbw
    13,    // w..bbw
    -25,   // .b.bbw
    -15,   // bb.bbw
    -37,   // wb.bbw
    -3,    // .w.bbw
    -11,   // bw.bbw
    -3,    // ww.bbw
    -35,   // ..bbbw
    -29,   // b.bbbw
    -43,   // w.bbbw
    53,    // .bbbbw
    -1,    // bbbbbw
    -85,   // wbbbbw
    11,    // .wbbbw
    1,     // bwbbbw
    -19,   // wwbbbw
    -7,    // ..wbbw
    1,     // b.wbbw
    43,    // w.wbbw
    15,    // .bwbbw
    61,    // bbwbbw
    57,    // wbwbbw
    25,    // .wwbbw
    0,     // bwwbbw
    5,     // wwwbbw
    -15,   // ...wbw
    -7,    // b..wbw
    23,    // w..wbw
    -5,    // .b.wbw
    13,    // bb.wbw
    -9,    // wb.wbw
    27,    // .w.wbw
    9,     // bw.wbw
    -5,    // ww.wbw
    33,    // ..bwbw
    7,     // b.bwbw
    -3,    // w.bwbw
    13,    // .bbwbw
    -33,   // bbbwbw
    57,    // wbbwbw
    65,    // .wbwbw
    0,     // bwbwbw
    45,    // wwbwbw
    -9,    // ..wwbw
    -15,   // b.wwbw
    -7,    // w.wwbw
    -9,    // .bwwbw
    15,    // bbwwbw
    -21,   // wbwwbw
    -11,   // .wwwbw
    -1,    // bwwwbw
    -31,   // wwwwbw
    -27,   // ....ww
    -13,   // b...ww
    -5,    // w...ww
    23,    // .b..ww
    0,     // bb..ww
    9,     // wb..ww
    -31,   // .w..ww
    1,     // bw..ww
    -43,   // ww..ww
    1,     // ..b.ww
    -47,   // b.b.ww
    -25,   // w.b.ww
    -1,    // .bb.ww
    -3,    // bbb.ww
    -3,    // wbb.ww
    31,    // .wb.ww
    -13,   // bwb.ww
    -51,   // wwb.ww
    -53,   // ..w.ww
    39,    // b.w.ww
    21,    // w.w.ww
    -27,   // .bw.ww
    -43,   // bbw.ww
    -5,    // wbw.ww
    1,     // .ww.ww
    15,    // bww.ww
    -25,   // www.ww
    -9,    // ...bww
    -15,   // b..bww
    -35,   // w..bww
    -11,   // .b.bww
    43,    // bb.bww
    21,    // wb.bww
    -15,   // .w.bww
    -13,   // bw.bww
    -51,   // ww.bww
    43,    // ..bbww
    -23,   // b.bbww
    33,    // w.bbww
    49,    // .bbbww
    5,     // bbbbww
    -19,   // wbbbww
    43,    // .wbbww
    -15,   // bwbbww
    3,     // wwbbww
    -57,   // ..wbww
    3,     // b.wbww
    -27,   // w.wbww
    -13,   // .bwbww
    0,     // bbwbww
    45,    // wbwbww
    25,    // .wwbww
    -61,   // bwwbww
    -53,   // wwwbww
    -29,   // ...www
    -17,   // b..www
    -1,    // w..www
    17,    // .b.www
    3,     // bb.www
    13,    // wb.www
    -9,    // .w.www
    45,    // bw.www
    -25,   // ww.www
    47,    // ..bwww
    -7,    // b.bwww
    13,    // w.bwww
    39,    // .bbwww
    0,     // bbbwww
    5,     // wbbwww
    13,    // .wbwww
    33,    // bwbwww
    -53,   // wwbwww
    -3,    // ..wwww
    -47,   // b.wwww
    -19,   // w.wwww
    37,    // .bwwww
    -5,    // bbwwww
    -31,   // wbwwww
    -5,    // .wwwww
    1,     // bwwwww
    -7,    // wwwwww
    5,     // ccc
    65,    // cc
    -1,    // c
    29,    // ttt
    17,    // tt
    -3,    // t
    -25,   // ct
    21,    // cct
    -21,   // ctt
].into_boxed_slice()
