vec![
    0,     // ......
    -16,   // b.....
    16,    // w.....
    -21,   // .b....
    -11,   // bb....
    2,     // wb....
    21,    // .w....
    -2,    // bw....
    11,    // ww....
    -10,   // ..b...
    -10,   // b.b...
    3,     // w.b...
    -13,   // .bb...
    11,    // bbb...
    -13,   // wbb...
    -17,   // .wb...
    -17,   // bwb...
    -9,    // wwb...
    10,    // ..w...
    -3,    // b.w...
    10,    // w.w...
    17,    // .bw...
    9,     // bbw...
    17,    // wbw...
    13,    // .ww...
    13,    // bww...
    -11,   // www...
    -10,   // ...b..
    -9,    // b..b..
    1,     // w..b..
    -1,    // .b.b..
    -9,    // bb.b..
    1,     // wb.b..
    -6,    // .w.b..
    -16,   // bw.b..
    11,    // ww.b..
    1,     // ..bb..
    14,    // b.bb..
    6,     // w.bb..
    13,    // .bbb..
    -9,    // bbbb..
    -10,   // wbbb..
    5,     // .wbb..
    -1,    // bwbb..
    -1,    // wwbb..
    0,     // ..wb..
    -9,    // b.wb..
    -12,   // w.wb..
    -8,    // .bwb..
    -6,    // bbwb..
    17,    // wbwb..
    -15,   // .wwb..
    -11,   // bwwb..
    -3,    // wwwb..
    10,    // ...w..
    -1,    // b..w..
    9,     // w..w..
    6,     // .b.w..
    -11,   // bb.w..
    16,    // wb.w..
    1,     // .w.w..
    -1,    // bw.w..
    9,     // ww.w..
    0,     // ..bw..
    12,    // b.bw..
    9,     // w.bw..
    15,    // .bbw..
    3,     // bbbw..
    11,    // wbbw..
    8,     // .wbw..
    -17,   // bwbw..
    6,     // wwbw..
    -1,    // ..ww..
    -6,    // b.ww..
    -14,   // w.ww..
    -5,    // .bww..
    1,     // bbww..
    1,     // wbww..
    -13,   // .www..
    10,    // bwww..
    9,     // wwww..
    -21,   // ....b.
    -4,    // b...b.
    6,     // w...b.
    -5,    // .b..b.
    -9,    // bb..b.
    5,     // wb..b.
    0,     // .w..b.
    -1,    // bw..b.
    -8,    // ww..b.
    -1,    // ..b.b.
    -19,   // b.b.b.
    12,    // w.b.b.
    16,    // .bb.b.
    -2,    // bbb.b.
    16,    // wbb.b.
    -22,   // .wb.b.
    6,     // bwb.b.
    2,     // wwb.b.
    6,     // ..w.b.
    -28,   // b.w.b.
    -5,    // w.w.b.
    -6,    // .bw.b.
    0,     // bbw.b.
    9,     // wbw.b.
    28,    // .ww.b.
    3,     // bww.b.
    5,     // www.b.
    -13,   // ...bb.
    -8,    // b..bb.
    -1,    // w..bb.
    16,    // .b.bb.
    12,    // bb.bb.
    13,    // wb.bb.
    -28,   // .w.bb.
    -8,    // bw.bb.
    -5,    // ww.bb.
    13,    // ..bbb.
    21,    // b.bbb.
    6,     // w.bbb.
    34,    // .bbbb.
    -2,    // bbbbb.
    -8,    // wbbbb.
    -1,    // .wbbb.
    0,     // bwbbb.
    6,     // wwbbb.
    15,    // ..wbb.
    -13,   // b.wbb.
    -1,    // w.wbb.
    -11,   // .bwbb.
    -1,    // bbwbb.
    7,     // wbwbb.
    0,     // .wwbb.
    -5,    // bwwbb.
    -18,   // wwwbb.
    17,    // ...wb.
    5,     // b..wb.
    1,     // w..wb.
    -6,    // .b.wb.
    -11,   // bb.wb.
    6,     // wb.wb.
    22,    // .w.wb.
    -8,    // bw.wb.
    0,     // ww.wb.
    -8,    // ..bwb.
    6,     // b.bwb.
    1,     // w.bwb.
    -11,   // .bbwb.
    -10,   // bbbwb.
    -3,    // wbbwb.
    0,     // .wbwb.
    3,     // bwbwb.
    -7,    // wwbwb.
    -5,    // ..wwb.
    10,    // b.wwb.
    16,    // w.wwb.
    -10,   // .bwwb.
    4,     // bbwwb.
    18,    // wbwwb.
    1,     // .wwwb.
    -7,    // bwwwb.
    0,     // wwwwb.
    21,    // ....w.
    -6,    // b...w.
    4,     // w...w.
    0,     // .b..w.
    8,     // bb..w.
    1,     // wb..w.
    5,     // .w..w.
    -5,    // bw..w.
    9,     // ww..w.
    -6,    // ..b.w.
    5,     // b.b.w.
    28,    // w.b.w.
    -28,   // .bb.w.
    -5,    // bbb.w.
    -3,    // wbb.w.
    6,     // .wb.w.
    -9,    // bwb.w.
    0,     // wwb.w.
    1,     // ..w.w.
    -12,   // b.w.w.
    19,    // w.w.w.
    22,    // .bw.w.
    -2,    // bbw.w.
    -6,    // wbw.w.
    -16,   // .ww.w.
    -16,   // bww.w.
    2,     // www.w.
    -17,   // ...bw.
    -1,    // b..bw.
    -5,    // w..bw.
    -22,   // .b.bw.
    0,     // bb.bw.
    8,     // wb.bw.
    6,     // .w.bw.
    -6,    // bw.bw.
    11,    // ww.bw.
    5,     // ..bbw.
    -16,   // b.bbw.
    -10,   // w.bbw.
    -1,    // .bbbw.
    0,     // bbbbw.
    7,     // wbbbw.
    10,    // .wbbw.
    -18,   // bwbbw.
    -4,    // wwbbw.
    8,     // ..wbw.
    -1,    // b.wbw.
    -6,    // w.wbw.
    0,     // .bwbw.
    7,     // bbwbw.
    -3,    // wbwbw.
    11,    // .wwbw.
    3,     // bwwbw.
    10,    // wwwbw.
    13,    // ...ww.
    1,     // b..ww.
    8,     // w..ww.
    28,    // .b.ww.
    5,     // bb.ww.
    8,     // wb.ww.
    -16,   // .w.ww.
    -13,   // bw.ww.
    -12,   // ww.ww.
    -15,   // ..bww.
    1,     // b.bww.
    13,    // w.bww.
    0,     // .bbww.
    18,    // bbbww.
    5,     // wbbww.
    11,    // .wbww.
    -7,    // bwbww.
    1,     // wwbww.
    -13,   // ..www.
    -6,    // b.www.
    -21,   // w.www.
    1,     // .bwww.
    -6,    // bbwww.
    0,     // wbwww.
    -34,   // .wwww.
    8,     // bwwww.
    2,     // wwwww.
    -16,   // .....b
    -8,    // b....b
    0,     // w....b
    -4,    // .b...b
    -9,    // bb...b
    7,     // wb...b
    -6,    // .w...b
    -11,   // bw...b
    16,    // ww...b
    -9,    // ..b..b
    -10,   // b.b..b
    6,     // w.b..b
    -8,    // .bb..b
    25,    // bbb..b
    -9,    // wbb..b
    -1,    // .wb..b
    4,     // bwb..b
    22,    // wwb..b
    -1,    // ..w..b
    1,     // b.w..b
    -13,   // w.w..b
    5,     // .bw..b
    6,     // bbw..b
    3,     // wbw..b
    1,     // .ww..b
    1,     // bww..b
    -8,    // www..b
    -10,   // ...b.b
    -10,   // b..b.b
    13,    // w..b.b
    -19,   // .b.b.b
    -2,    // bb.b.b
    24,    // wb.b.b
    5,     // .w.b.b
    -4,    // bw.b.b
    -6,    // ww.b.b
    14,    // ..bb.b
    -9,    // b.bb.b
    23,    // w.bb.b
    21,    // .bbb.b
    23,    // bbbb.b
    6,     // wbbb.b
    -16,   // .wbb.b
    10,    // bwbb.b
    11,    // wwbb.b
    12,    // ..wb.b
    3,     // b.wb.b
    0,     // w.wb.b
    6,     // .bwb.b
    1,     // bbwb.b
    8,     // wbwb.b
    1,     // .wwb.b
    -2,    // bwwb.b
    -18,   // wwwb.b
    -3,    // ...w.b
    1,     // b..w.b
    -6,    // w..w.b
    -28,   // .b.w.b
    -3,    // bb.w.b
    8,     // wb.w.b
    -12,   // .w.w.b
    -17,   // bw.w.b
    -9,    // ww.w.b
    -9,    // ..bw.b
    3,     // b.bw.b
    0,     // w.bw.b
    -13,   // .bbw.b
    -9,    // bbbw.b
    3,     // wbbw.b
    -1,    // .wbw.b
    -4,    // bwbw.b
    2,     // wwbw.b
    -6,    // ..ww.b
    1,     // b.ww.b
    -23,   // w.ww.b
    10,    // .bww.b
    -3,    // bbww.b
    11,    // wbww.b
    -6,    // .www.b
    6,     // bwww.b
    -9,    // wwww.b
    -11,   // ....bb
    -9,    // b...bb
    -16,   // w...bb
    -9,    // .b..bb
    6,     // bb..bb
    24,    // wb..bb
    8,     // .w..bb
    -12,   // bw..bb
    0,     // ww..bb
    -9,    // ..b.bb
    -2,    // b.b.bb
    9,     // w.b.bb
    12,    // .bb.bb
    9,     // bbb.bb
    -8,    // wbb.bb
    0,     // .wb.bb
    -7,    // bwb.bb
    3,     // wwb.bb
    -11,   // ..w.bb
    -3,    // b.w.bb
    6,     // w.w.bb
    -11,   // .bw.bb
    9,     // bbw.bb
    -2,    // wbw.bb
    5,     // .ww.bb
    -11,   // bww.bb
    -7,    // www.bb
    11,    // ...bbb
    25,    // b..bbb
    8,     // w..bbb
    -2,    // .b.bbb
    9,     // bb.bbb
    -30,   // wb.bbb
    -5,    // .w.bbb
    -12,   // bw.bbb
    7,     // ww.bbb
    -9,    // ..bbbb
    23,    // b.bbbb
    9,     // w.bbbb
    -2,    // .bbbbb
    -12,   // bbbbbb
    -13,   // wbbbbb
    0,     // .wbbbb
    6,     // bwbbbb
    -8,    // wwbbbb
    3,     // ..wbbb
    -9,    // b.wbbb
    18,    // w.wbbb
    -10,   // .bwbbb
    2,     // bbwbbb
    4,     // wbwbbb
    18,    // .wwbbb
    12,    // bwwbbb
    0,     // wwwbbb
    9,     // ...wbb
    6,     // b..wbb
    -22,   // w..wbb
    0,     // .b.wbb
    9,     // bb.wbb
    14,    // wb.wbb
    -2,    // .w.wbb
    2,     // bw.wbb
    -3,    // ww.wbb
    -6,    // ..bwbb
    1,     // b.bwbb
    -2,    // w.bwbb
    -1,    // .bbwbb
    2,     // bbbwbb
    -6,    // wbbwbb
    7,     // .wbwbb
    -3,    // bwbwbb
    0,     // wwbwbb
    1,     // ..wwbb
    -3,    // b.wwbb
    -11,   // w.wwbb
    4,     // .bwwbb
    -3,    // bbwwbb
    13,    // wbwwbb
    -6,    // .wwwbb
    20,    // bwwwbb
    8,     // wwwwbb
    -2,    // ....wb
    -11,   // b...wb
    -7,    // w...wb
    -1,    // .b..wb
    -12,   // bb..wb
    0,     // wb..wb
    -5,    // .w..wb
    -8,    // bw..wb
    -24,   // ww..wb
    -16,   // ..b.wb
    -4,    // b.b.wb
    -8,    // w.b.wb
    -8,    // .bb.wb
    -12,   // bbb.wb
    3,     // wbb.wb
    -6,    // .wb.wb
    4,     // bwb.wb
    -14,   // wwb.wb
    -1,    // ..w.wb
    -17,   // b.w.wb
    -24,   // w.w.wb
    -8,    // .bw.wb
    2,     // bbw.wb
    5,     // wbw.wb
    -13,   // .ww.wb
    -9,    // bww.wb
    30,    // www.wb
    -17,   // ...bwb
    4,     // b..bwb
    -3,    // w..bwb
    6,     // .b.bwb
    -7,    // bb.bwb
    -5,    // wb.bwb
    -9,    // .w.bwb
    4,     // bw.bwb
    2,     // ww.bwb
    -1,    // ..bbwb
    10,    // b.bbwb
    -11,   // w.bbwb
    0,     // .bbbwb
    6,     // bbbbwb
    -4,    // wbbbwb
    -18,   // .wbbwb
    -24,   // bwbbwb
    -13,   // wwbbwb
    -17,   // ..wbwb
    -4,    // b.wbwb
    -8,    // w.wbwb
    3,     // .bwbwb
    -3,    // bbwbwb
    0,     // wbwbwb
    -7,    // .wwbwb
    0,     // bwwbwb
    -4,    // wwwbwb
    13,    // ...wwb
    1,     // b..wwb
    9,     // w..wwb
    3,     // .b.wwb
    -11,   // bb.wwb
    -3,    // wb.wwb
    -16,   // .w.wwb
    -9,    // bw.wwb
    8,     // ww.wwb
    -11,   // ..bwwb
    -2,    // b.bwwb
    -3,    // w.bwwb
    -5,    // .bbwwb
    12,    // bbbwwb
    0,     // wbbwwb
    3,     // .wbwwb
    0,     // bwbwwb
    6,     // wwbwwb
    10,    // ..wwwb
    6,     // b.wwwb
    -6,    // w.wwwb
    -7,    // .bwwwb
    20,    // bbwwwb
    4,     // wbwwwb
    8,     // .wwwwb
    -3,    // bwwwwb
    13,    // wwwwwb
    16,    // .....w
    0,     // b....w
    8,     // w....w
    6,     // .b...w
    -16,   // bb...w
    11,    // wb...w
    4,     // .w...w
    -7,    // bw...w
    9,     // ww...w
    1,     // ..b..w
    13,    // b.b..w
    -1,    // w.b..w
    -1,    // .bb..w
    8,     // bbb..w
    -1,    // wbb..w
    -5,    // .wb..w
    -3,    // bwb..w
    -6,    // wwb..w
    9,     // ..w..w
    -6,    // b.w..w
    10,    // w.w..w
    1,     // .bw..w
    -22,   // bbw..w
    -4,    // wbw..w
    8,     // .ww..w
    9,     // bww..w
    -25,   // www..w
    3,     // ...b.w
    6,     // b..b.w
    -1,    // w..b.w
    12,    // .b.b.w
    9,     // bb.b.w
    17,    // wb.b.w
    28,    // .w.b.w
    -8,    // bw.b.w
    3,     // ww.b.w
    6,     // ..bb.w
    23,    // b.bb.w
    -1,    // w.bb.w
    6,     // .bbb.w
    9,     // bbbb.w
    -6,    // wbbb.w
    -10,   // .wbb.w
    -11,   // bwbb.w
    3,     // wwbb.w
    9,     // ..wb.w
    0,     // b.wb.w
    -3,    // w.wb.w
    1,     // .bwb.w
    -2,    // bbwb.w
    4,     // wbwb.w
    13,    // .wwb.w
    -3,    // bwwb.w
    9,     // wwwb.w
    10,    // ...w.w
    -13,   // b..w.w
    10,    // w..w.w
    -5,    // .b.w.w
    6,     // bb.w.w
    4,     // wb.w.w
    19,    // .w.w.w
    -24,   // bw.w.w
    2,     // ww.w.w
    -12,   // ..bw.w
    0,     // b.bw.w
    -3,    // w.bw.w
    -1,    // .bbw.w
    18,    // bbbw.w
    2,     // wbbw.w
    -6,    // .wbw.w
    -8,    // bwbw.w
    -1,    // wwbw.w
    -14,   // ..ww.w
    -23,   // b.ww.w
    9,     // w.ww.w
    16,    // .bww.w
    -11,   // bbww.w
    -10,   // wbww.w
    -21,   // .www.w
    -6,    // bwww.w
    -23,   // wwww.w
    2,     // ....bw
    7,     // b...bw
    11,    // w...bw
    5,     // .b..bw
    24,    // bb..bw
    8,     // wb..bw
    1,     // .w..bw
    0,     // bw..bw
    12,    // ww..bw
    1,     // ..b.bw
    24,    // b.b.bw
    17,    // w.b.bw
    13,    // .bb.bw
    -30,   // bbb.bw
    9,     // wbb.bw
    8,     // .wb.bw
    -5,    // bwb.bw
    -2,    // wwb.bw
    16,    // ..w.bw
    8,     // b.w.bw
    4,     // w.w.bw
    6,     // .bw.bw
    14,    // bbw.bw
    -4,    // wbw.bw
    8,     // .ww.bw
    -3,    // bww.bw
    12,    // www.bw
    -13,   // ...bbw
    -9,    // b..bbw
    -1,    // w..bbw
    16,    // .b.bbw
    -8,    // bb.bbw
    9,     // wb.bbw
    -3,    // .w.bbw
    3,     // bw.bbw
    11,    // ww.bbw
    -10,   // ..bbbw
    6,     // b.bbbw
    -6,    // w.bbbw
    -8,    // .bbbbw
    -13,   // bbbbbw
    3,     // wbbbbw
    7,     // .wbbbw
    -4,    // bwbbbw
    -20,   // wwbbbw
    11,    // ..wbbw
    3,     // b.wbbw
    2,     // w.wbbw
    -3,    // .bwbbw
    -6,    // bbwbbw
    0,     // wbwbbw
    5,     // .wwbbw
    0,     // bwwbbw
    -12,   // wwwbbw
    17,    // ...wbw
    3,     // b..wbw
    -4,    // w..wbw
    9,     // .b.wbw
    -2,    // bb.wbw
    -4,    // wb.wbw
    -6,    // .w.wbw
    5,     // bw.wbw
    7,     // ww.wbw
    17,    // ..bwbw
    8,     // b.bwbw
    4,     // w.bwbw
    7,     // .bbwbw
    4,     // bbbwbw
    0,     // wbbwbw
    -3,    // .wbwbw
    0,     // bwbwbw
    3,     // wwbwbw
    1,     // ..wwbw
    11,    // b.wwbw
    -10,   // w.wwbw
    18,    // .bwwbw
    13,    // bbwwbw
    24,    // wbwwbw
    0,     // .wwwbw
    4,     // bwwwbw
    -6,    // wwwwbw
    11,    // ....ww
    16,    // b...ww
    9,     // w...ww
    -8,    // .b..ww
    0,     // bb..ww
    12,    // wb..ww
    9,     // .w..ww
    -24,   // bw..ww
    -6,    // ww..ww
    11,    // ..b.ww
    -6,    // b.b.ww
    3,     // w.b.ww
    -5,    // .bb.ww
    7,     // bbb.ww
    11,    // wbb.ww
    11,    // .wb.ww
    2,     // bwb.ww
    -9,    // wwb.ww
    9,     // ..w.ww
    -9,    // b.w.ww
    2,     // w.w.ww
    0,     // .bw.ww
    -3,    // bbw.ww
    7,     // wbw.ww
    -12,   // .ww.ww
    8,     // bww.ww
    -9,    // www.ww
    -9,    // ...bww
    22,    // b..bww
    -6,    // w..bww
    2,     // .b.bww
    3,     // bb.bww
    -2,    // wb.bww
    0,     // .w.bww
    -14,   // bw.bww
    -9,    // ww.bww
    -1,    // ..bbww
    11,    // b.bbww
    3,     // w.bbww
    6,     // .bbbww
    -8,    // bbbbww
    -20,   // wbbbww
    -4,    // .wbbww
    -13,   // bwbbww
    3,     // wwbbww
    6,     // ..wbww
    2,     // b.wbww
    -1,    // w.wbww
    -7,    // .bwbww
    0,     // bbwbww
    3,     // wbwbww
    1,     // .wwbww
    6,     // bwwbww
    -2,    // wwwbww
    -11,   // ...www
    -8,    // b..www
    -25,   // w..www
    5,     // .b.www
    -7,    // bb.www
    12,    // wb.www
    2,     // .w.www
    30,    // bw.www
    -9,    // ww.www
    -3,    // ..bwww
    -18,   // b.bwww
    9,     // w.bwww
    -18,   // .bbwww
    0,     // bbbwww
    -12,   // wbbwww
    10,    // .wbwww
    -4,    // bwbwww
    -2,    // wwbwww
    9,     // ..wwww
    -9,    // b.wwww
    -23,   // w.wwww
    0,     // .bwwww
    8,     // bbwwww
    -6,    // wbwwww
    2,     // .wwwww
    13,    // bwwwww
    12,    // wwwwww
    4,     // ccc
    -3,    // cc
    13,    // c
    10,    // ttt
    2,     // tt
    29,    // t
    -5,    // ct
    3,     // cct
    -11,   // ctt
].into_boxed_slice()
