vec![
    0,     // ......
    -19,   // b.....
    19,    // w.....
    -5,    // .b....
    24,    // bb....
    17,    // wb....
    5,     // .w....
    -17,   // bw....
    -24,   // ww....
    -11,   // ..b...
    15,    // b.b...
    -16,   // w.b...
    -21,   // .bb...
    49,    // bbb...
    -37,   // wbb...
    -11,   // .wb...
    -54,   // bwb...
    57,    // wwb...
    11,    // ..w...
    16,    // b.w...
    -15,   // w.w...
    11,    // .bw...
    -57,   // bbw...
    54,    // wbw...
    21,    // .ww...
    37,    // bww...
    -49,   // www...
    -11,   // ...b..
    -5,    // b..b..
    -24,   // w..b..
    -34,   // .b.b..
    12,    // bb.b..
    -10,   // wb.b..
    -4,    // .w.b..
    -20,   // bw.b..
    -5,    // ww.b..
    -13,   // ..bb..
    22,    // b.bb..
    45,    // w.bb..
    26,    // .bbb..
    183,   // bbbb..
    -75,   // wbbb..
    0,     // .wbb..
    10,    // bwbb..
    4,     // wwbb..
    0,     // ..wb..
    22,    // b.wb..
    25,    // w.wb..
    23,    // .bwb..
    -35,   // bbwb..
    18,    // wbwb..
    -35,   // .wwb..
    -28,   // bwwb..
    -14,   // wwwb..
    11,    // ...w..
    24,    // b..w..
    5,     // w..w..
    4,     // .b.w..
    5,     // bb.w..
    20,    // wb.w..
    34,    // .w.w..
    10,    // bw.w..
    -12,   // ww.w..
    0,     // ..bw..
    -25,   // b.bw..
    -22,   // w.bw..
    35,    // .bbw..
    14,    // bbbw..
    28,    // wbbw..
    -23,   // .wbw..
    -18,   // bwbw..
    35,    // wwbw..
    13,    // ..ww..
    -45,   // b.ww..
    -22,   // w.ww..
    0,     // .bww..
    -4,    // bbww..
    -10,   // wbww..
    -26,   // .www..
    75,    // bwww..
    -183,  // wwww..
    -5,    // ....b.
    -45,   // b...b.
    16,    // w...b.
    -3,    // .b..b.
    44,    // bb..b.
    8,     // wb..b.
    0,     // .w..b.
    0,     // bw..b.
    33,    // ww..b.
    -34,   // ..b.b.
    -8,    // b.b.b.
    -71,   // w.b.b.
    -16,   // .bb.b.
    -26,   // bbb.b.
    -33,   // wbb.b.
    -11,   // .wb.b.
    1,     // bwb.b.
    -13,   // wwb.b.
    4,     // ..w.b.
    -34,   // b.w.b.
    -38,   // w.w.b.
    15,    // .bw.b.
    -30,   // bbw.b.
    42,    // wbw.b.
    97,    // .ww.b.
    24,    // bww.b.
    -32,   // www.b.
    -21,   // ...bb.
    -8,    // b..bb.
    43,    // w..bb.
    -16,   // .b.bb.
    -49,   // bb.bb.
    -18,   // wb.bb.
    -97,   // .w.bb.
    -3,    // bw.bb.
    -42,   // ww.bb.
    26,    // ..bbb.
    106,   // b.bbb.
    1,     // w.bbb.
    72,    // .bbbb.
    41,    // bbbbb.
    69,    // wbbbb.
    -26,   // .wbbb.
    11,    // bwbbb.
    26,    // wwbbb.
    35,    // ..wbb.
    -22,   // b.wbb.
    -9,    // w.wbb.
    1,     // .bwbb.
    -3,    // bbwbb.
    -9,    // wbwbb.
    0,     // .wwbb.
    32,    // bwwbb.
    -20,   // wwwbb.
    11,    // ...wb.
    35,    // b..wb.
    -6,    // w..wb.
    15,    // .b.wb.
    -27,   // bb.wb.
    0,     // wb.wb.
    11,    // .w.wb.
    23,    // bw.wb.
    9,     // ww.wb.
    23,    // ..bwb.
    -35,   // b.bwb.
    -19,   // w.bwb.
    1,     // .bbwb.
    1,     // bbbwb.
    24,    // wbbwb.
    0,     // .wbwb.
    11,    // bwbwb.
    -20,   // wwbwb.
    0,     // ..wwb.
    -25,   // b.wwb.
    -12,   // w.wwb.
    -16,   // .bwwb.
    7,     // bbwwb.
    12,    // wbwwb.
    26,    // .wwwb.
    2,     // bwwwb.
    29,    // wwwwb.
    5,     // ....w.
    -16,   // b...w.
    45,    // w...w.
    0,     // .b..w.
    -33,   // bb..w.
    0,     // wb..w.
    3,     // .w..w.
    -8,    // bw..w.
    -44,   // ww..w.
    -4,    // ..b.w.
    38,    // b.b.w.
    34,    // w.b.w.
    -97,   // .bb.w.
    32,    // bbb.w.
    -24,   // wbb.w.
    -15,   // .wb.w.
    -42,   // bwb.w.
    30,    // wwb.w.
    34,    // ..w.w.
    71,    // b.w.w.
    8,     // w.w.w.
    11,    // .bw.w.
    13,    // bbw.w.
    -1,    // wbw.w.
    16,    // .ww.w.
    33,    // bww.w.
    26,    // www.w.
    -11,   // ...bw.
    6,     // b..bw.
    -35,   // w..bw.
    -11,   // .b.bw.
    -9,    // bb.bw.
    -23,   // wb.bw.
    -15,   // .w.bw.
    0,     // bw.bw.
    27,    // ww.bw.
    0,     // ..bbw.
    12,    // b.bbw.
    25,    // w.bbw.
    -26,   // .bbbw.
    -29,   // bbbbw.
    -2,    // wbbbw.
    16,    // .wbbw.
    -12,   // bwbbw.
    -7,    // wwbbw.
    -23,   // ..wbw.
    19,    // b.wbw.
    35,    // w.wbw.
    0,     // .bwbw.
    20,    // bbwbw.
    -11,   // wbwbw.
    -1,    // .wwbw.
    -24,   // bwwbw.
    -1,    // wwwbw.
    21,    // ...ww.
    -43,   // b..ww.
    8,     // w..ww.
    97,    // .b.ww.
    42,    // bb.ww.
    3,     // wb.ww.
    16,    // .w.ww.
    18,    // bw.ww.
    49,    // ww.ww.
    -35,   // ..bww.
    9,     // b.bww.
    22,    // w.bww.
    0,     // .bbww.
    20,    // bbbww.
    -32,   // wbbww.
    -1,    // .wbww.
    9,     // bwbww.
    3,     // wwbww.
    -26,   // ..www.
    -1,    // b.www.
    -106,  // w.www.
    26,    // .bwww.
    -26,   // bbwww.
    -11,   // wbwww.
    -72,   // .wwww.
    -69,   // bwwww.
    -41,   // wwwww.
    -19,   // .....b
    9,     // b....b
    0,     // w....b
    -45,   // .b...b
    3,     // bb...b
    33,    // wb...b
    -16,   // .w...b
    -21,   // bw...b
    -44,   // ww...b
    -5,    // ..b..b
    23,    // b.b..b
    -32,   // w.b..b
    -8,    // .bb..b
    5,     // bbb..b
    2,     // wbb..b
    6,     // .wb..b
    -22,   // bwb..b
    14,    // wwb..b
    24,    // ..w..b
    22,    // b.w..b
    27,    // w.w..b
    35,    // .bw..b
    6,     // bbw..b
    22,    // wbw..b
    -43,   // .ww..b
    -3,    // bww..b
    -13,   // www..b
    15,    // ...b.b
    23,    // b..b.b
    -27,   // w..b.b
    -8,    // .b.b.b
    4,     // bb.b.b
    -24,   // wb.b.b
    38,    // .w.b.b
    5,     // bw.b.b
    58,    // ww.b.b
    22,    // ..bb.b
    -15,   // b.bb.b
    -56,   // w.bb.b
    106,   // .bbb.b
    6,     // bbbb.b
    48,    // wbbb.b
    12,    // .wbb.b
    -66,   // bwbb.b
    -8,    // wwbb.b
    -25,   // ..wb.b
    21,    // b.wb.b
    0,     // w.wb.b
    -35,   // .bwb.b
    0,     // bbwb.b
    8,     // wbwb.b
    9,     // .wwb.b
    24,    // bwwb.b
    -14,   // wwwb.b
    16,    // ...w.b
    22,    // b..w.b
    32,    // w..w.b
    -34,   // .b.w.b
    -31,   // bb.w.b
    10,    // wb.w.b
    71,    // .w.w.b
    44,    // bw.w.b
    -2,    // ww.w.b
    22,    // ..bw.b
    21,    // b.bw.b
    0,     // w.bw.b
    -22,   // .bbw.b
    -21,   // bbbw.b
    -55,   // wbbw.b
    19,    // .wbw.b
    -2,    // bwbw.b
    13,    // wwbw.b
    -45,   // ..ww.b
    -32,   // b.ww.b
    56,    // w.ww.b
    -25,   // .bww.b
    81,    // bbww.b
    33,    // wbww.b
    -1,    // .www.b
    -10,   // bwww.b
    -10,   // wwww.b
    24,    // ....bb
    3,     // b...bb
    44,    // w...bb
    44,    // .b..bb
    37,    // bb..bb
    -23,   // wb..bb
    -33,   // .w..bb
    -42,   // bw..bb
    0,     // ww..bb
    12,    // ..b.bb
    4,     // b.b.bb
    2,     // w.b.bb
    -49,   // .bb.bb
    44,    // bbb.bb
    36,    // wbb.bb
    -9,    // .wb.bb
    26,    // bwb.bb
    -25,   // wwb.bb
    5,     // ..w.bb
    -31,   // b.w.bb
    -58,   // w.w.bb
    -27,   // .bw.bb
    25,    // bbw.bb
    -8,    // wbw.bb
    42,    // .ww.bb
    -35,   // bww.bb
    15,    // www.bb
    49,    // ...bbb
    5,     // b..bbb
    13,    // w..bbb
    -26,   // .b.bbb
    44,    // bb.bbb
    -28,   // wb.bbb
    32,    // .w.bbb
    8,     // bw.bbb
    -15,   // ww.bbb
    183,   // ..bbbb
    6,     // b.bbbb
    10,    // w.bbbb
    41,    // .bbbbb
    -6,    // bbbbbb
    -22,   // wbbbbb
    -29,   // .wbbbb
    -36,   // bwbbbb
    33,    // wwbbbb
    14,    // ..wbbb
    -21,   // b.wbbb
    14,    // w.wbbb
    1,     // .bwbbb
    -11,   // bbwbbb
    -10,   // wbwbbb
    20,    // .wwbbb
    5,     // bwwbbb
    0,     // wwwbbb
    -57,   // ...wbb
    6,     // b..wbb
    -14,   // w..wbb
    -30,   // .b.wbb
    25,    // bb.wbb
    -19,   // wb.wbb
    13,    // .w.wbb
    15,    // bw.wbb
    25,    // ww.wbb
    -35,   // ..bwbb
    0,     // b.bwbb
    -13,   // w.bwbb
    -3,    // .bbwbb
    -11,   // bbbwbb
    -10,   // wbbwbb
    20,    // .wbwbb
    -13,   // bwbwbb
    0,     // wwbwbb
    -4,    // ..wwbb
    81,    // b.wwbb
    8,     // w.wwbb
    7,     // .bwwbb
    -11,   // bbwwbb
    -21,   // wbwwbb
    -26,   // .wwwbb
    -33,   // bwwwbb
    -33,   // wwwwbb
    -17,   // ....wb
    -21,   // b...wb
    -33,   // w...wb
    0,     // .b..wb
    -42,   // bb..wb
    0,     // wb..wb
    -8,    // .w..wb
    -63,   // bw..wb
    23,    // ww..wb
    -20,   // ..b.wb
    5,     // b.b.wb
    -10,   // w.b.wb
    -3,    // .bb.wb
    8,     // bbb.wb
    -78,   // wbb.wb
    0,     // .wb.wb
    33,    // bwb.wb
    19,    // wwb.wb
    10,    // ..w.wb
    44,    // b.w.wb
    24,    // w.w.wb
    23,    // .bw.wb
    15,    // bbw.wb
    16,    // wbw.wb
    18,    // .ww.wb
    -2,    // bww.wb
    28,    // www.wb
    -54,   // ...bwb
    -22,   // b..bwb
    -22,   // w..bwb
    1,     // .b.bwb
    26,    // bb.bwb
    -16,   // wb.bwb
    -42,   // .w.bwb
    33,    // bw.bwb
    8,     // ww.bwb
    10,    // ..bbwb
    -66,   // b.bbwb
    -33,   // w.bbwb
    11,    // .bbbwb
    -36,   // bbbbwb
    -45,   // wbbbwb
    -12,   // .wbbwb
    6,     // bwbbwb
    21,    // wwbbwb
    -18,   // ..wbwb
    -2,    // b.wbwb
    -8,    // w.wbwb
    11,    // .bwbwb
    -13,   // bbwbwb
    0,     // wbwbwb
    9,     // .wwbwb
    -10,   // bwwbwb
    10,    // wwwbwb
    37,    // ...wwb
    -3,    // b..wwb
    -2,    // w..wwb
    24,    // .b.wwb
    -35,   // bb.wwb
    78,    // wb.wwb
    33,    // .w.wwb
    -2,    // bw.wwb
    -36,   // ww.wwb
    -28,   // ..bwwb
    24,    // b.bwwb
    55,    // w.bwwb
    32,    // .bbwwb
    5,     // bbbwwb
    0,     // wbbwwb
    -24,   // .wbwwb
    -10,   // bwbwwb
    10,    // wwbwwb
    75,    // ..wwwb
    -10,   // b.wwwb
    -48,   // w.wwwb
    2,     // .bwwwb
    -33,   // bbwwwb
    45,    // wbwwwb
    -69,   // .wwwwb
    68,    // bwwwwb
    22,    // wwwwwb
    19,    // .....w
    0,     // b....w
    -9,    // w....w
    16,    // .b...w
    44,    // bb...w
    21,    // wb...w
    45,    // .w...w
    -33,   // bw...w
    -3,    // ww...w
    -24,   // ..b..w
    -27,   // b.b..w
    -22,   // w.b..w
    43,    // .bb..w
    13,    // bbb..w
    3,     // wbb..w
    -35,   // .wb..w
    -22,   // bwb..w
    -6,    // wwb..w
    5,     // ..w..w
    32,    // b.w..w
    -23,   // w.w..w
    -6,    // .bw..w
    -14,   // bbw..w
    22,    // wbw..w
    8,     // .ww..w
    -2,    // bww..w
    -5,    // www..w
    -16,   // ...b.w
    -32,   // b..b.w
    -22,   // w..b.w
    -71,   // .b.b.w
    2,     // bb.b.w
    -44,   // wb.b.w
    34,    // .w.b.w
    -10,   // bw.b.w
    31,    // ww.b.w
    45,    // ..bb.w
    -56,   // b.bb.w
    32,    // w.bb.w
    1,     // .bbb.w
    10,    // bbbb.w
    10,    // wbbb.w
    25,    // .wbb.w
    -33,   // bwbb.w
    -81,   // wwbb.w
    -22,   // ..wb.w
    0,     // b.wb.w
    -21,   // w.wb.w
    -19,   // .bwb.w
    -13,   // bbwb.w
    2,     // wbwb.w
    22,    // .wwb.w
    55,    // bwwb.w
    21,    // wwwb.w
    -15,   // ...w.w
    27,    // b..w.w
    -23,   // w..w.w
    -38,   // .b.w.w
    -58,   // bb.w.w
    -5,    // wb.w.w
    8,     // .w.w.w
    24,    // bw.w.w
    -4,    // ww.w.w
    25,    // ..bw.w
    0,     // b.bw.w
    -21,   // w.bw.w
    -9,    // .bbw.w
    14,    // bbbw.w
    -24,   // wbbw.w
    35,    // .wbw.w
    -8,    // bwbw.w
    0,     // wwbw.w
    -22,   // ..ww.w
    56,    // b.ww.w
    15,    // w.ww.w
    -12,   // .bww.w
    8,     // bbww.w
    66,    // wbww.w
    -106,  // .www.w
    -48,   // bwww.w
    -6,    // wwww.w
    17,    // ....bw
    33,    // b...bw
    21,    // w...bw
    8,     // .b..bw
    -23,   // bb..bw
    63,    // wb..bw
    0,     // .w..bw
    0,     // bw..bw
    42,    // ww..bw
    -10,   // ..b.bw
    -24,   // b.b.bw
    -44,   // w.b.bw
    -18,   // .bb.bw
    -28,   // bbb.bw
    2,     // wbb.bw
    -23,   // .wb.bw
    -16,   // bwb.bw
    -15,   // wwb.bw
    20,    // ..w.bw
    10,    // b.w.bw
    -5,    // w.w.bw
    0,     // .bw.bw
    -19,   // bbw.bw
    -33,   // wbw.bw
    3,     // .ww.bw
    78,    // bww.bw
    -8,    // www.bw
    -37,   // ...bbw
    2,     // b..bbw
    3,     // w..bbw
    -33,   // .b.bbw
    36,    // bb.bbw
    2,     // wb.bbw
    -24,   // .w.bbw
    -78,   // bw.bbw
    35,    // ww.bbw
    -75,   // ..bbbw
    48,    // b.bbbw
    10,    // w.bbbw
    69,    // .bbbbw
    -22,   // bbbbbw
    -68,   // wbbbbw
    -2,    // .wbbbw
    -45,   // bwbbbw
    33,    // wwbbbw
    28,    // ..wbbw
    -55,   // b.wbbw
    -24,   // w.wbbw
    24,    // .bwbbw
    -10,   // bbwbbw
    10,    // wbwbbw
    -32,   // .wwbbw
    0,     // bwwbbw
    -5,    // wwwbbw
    54,    // ...wbw
    22,    // b..wbw
    22,    // w..wbw
    42,    // .b.wbw
    -8,    // bb.wbw
    -33,   // wb.wbw
    -1,    // .w.wbw
    16,    // bw.wbw
    -26,   // ww.wbw
    18,    // ..bwbw
    8,     // b.bwbw
    2,     // w.bwbw
    -9,    // .bbwbw
    -10,   // bbbwbw
    10,    // wbbwbw
    -11,   // .wbwbw
    0,     // bwbwbw
    13,    // wwbwbw
    -10,   // ..wwbw
    33,    // b.wwbw
    66,    // w.wwbw
    12,    // .bwwbw
    -21,   // bbwwbw
    -6,    // wbwwbw
    -11,   // .wwwbw
    45,    // bwwwbw
    36,    // wwwwbw
    -24,   // ....ww
    -44,   // b...ww
    -3,    // w...ww
    33,    // .b..ww
    0,     // bb..ww
    42,    // wb..ww
    -44,   // .w..ww
    23,    // bw..ww
    -37,   // ww..ww
    -5,    // ..b.ww
    58,    // b.b.ww
    31,    // w.b.ww
    -42,   // .bb.ww
    -15,   // bbb.ww
    35,    // wbb.ww
    27,    // .wb.ww
    8,     // bwb.ww
    -25,   // wwb.ww
    -12,   // ..w.ww
    -2,    // b.w.ww
    -4,    // w.w.ww
    9,     // .bw.ww
    25,    // bbw.ww
    -26,   // wbw.ww
    49,    // .ww.ww
    -36,   // bww.ww
    -44,   // www.ww
    57,    // ...bww
    14,    // b..bww
    -6,    // w..bww
    -13,   // .b.bww
    -25,   // bb.bww
    -15,   // wb.bww
    30,    // .w.bww
    19,    // bw.bww
    -25,   // ww.bww
    4,     // ..bbww
    -8,    // b.bbww
    -81,   // w.bbww
    26,    // .bbbww
    33,    // bbbbww
    33,    // wbbbww
    -7,    // .wbbww
    21,    // bwbbww
    11,    // wwbbww
    35,    // ..wbww
    13,    // b.wbww
    0,     // w.wbww
    -20,   // .bwbww
    0,     // bbwbww
    13,    // wbwbww
    3,     // .wwbww
    10,    // bwwbww
    11,    // wwwbww
    -49,   // ...www
    -13,   // b..www
    -5,    // w..www
    -32,   // .b.www
    15,    // bb.www
    -8,    // wb.www
    26,    // .w.www
    28,    // bw.www
    -44,   // ww.www
    -14,   // ..bwww
    -14,   // b.bwww
    21,    // w.bwww
    -20,   // .bbwww
    0,     // bbbwww
    -5,    // wbbwww
    -1,    // .wbwww
    10,    // bwbwww
    11,    // wwbwww
    -183,  // ..wwww
    -10,   // b.wwww
    -6,    // w.wwww
    29,    // .bwwww
    -33,   // bbwwww
    36,    // wbwwww
    -41,   // .wwwww
    22,    // bwwwww
    6,     // wwwwww
    -60,   // ccc
    -42,   // cc
    22,    // c
    4,     // ttt
    20,    // tt
    16,    // t
    -20,   // ct
    16,    // cct
    29,    // ctt
].into_boxed_slice()
