vec![
    0,     // ......
    3,     // b.....
    -3,    // w.....
    3,     // .b....
    -5,    // bb....
    3,     // wb....
    -3,    // .w....
    -3,    // bw....
    5,     // ww....
    -13,   // ..b...
    -21,   // b.b...
    -7,    // w.b...
    -11,   // .bb...
    21,    // bbb...
    -1,    // wbb...
    3,     // .wb...
    1,     // bwb...
    27,    // wwb...
    13,    // ..w...
    7,     // b.w...
    21,    // w.w...
    -3,    // .bw...
    -27,   // bbw...
    -1,    // wbw...
    11,    // .ww...
    1,     // bww...
    -21,   // www...
    -13,   // ...b..
    -7,    // b..b..
    -13,   // w..b..
    -7,    // .b.b..
    -17,   // bb.b..
    -3,    // wb.b..
    17,    // .w.b..
    9,     // bw.b..
    31,    // ww.b..
    38,    // ..bb..
    7,     // b.bb..
    7,     // w.bb..
    7,     // .bbb..
    41,    // bbbb..
    -1,    // wbbb..
    -19,   // .wbb..
    5,     // bwbb..
    -5,    // wwbb..
    0,     // ..wb..
    1,     // b.wb..
    -3,    // w.wb..
    9,     // .bwb..
    -7,    // bbwb..
    7,     // wbwb..
    -5,    // .wwb..
    7,     // bwwb..
    -5,    // wwwb..
    13,    // ...w..
    13,    // b..w..
    7,     // w..w..
    -17,   // .b.w..
    -31,   // bb.w..
    -9,    // wb.w..
    7,     // .w.w..
    3,     // bw.w..
    17,    // ww.w..
    0,     // ..bw..
    3,     // b.bw..
    -1,    // w.bw..
    5,     // .bbw..
    5,     // bbbw..
    -7,    // wbbw..
    -9,    // .wbw..
    -7,    // bwbw..
    7,     // wwbw..
    -38,   // ..ww..
    -7,    // b.ww..
    -7,    // w.ww..
    19,    // .bww..
    5,     // bbww..
    -5,    // wbww..
    -7,    // .www..
    1,     // bwww..
    -41,   // wwww..
    3,     // ....b.
    -1,    // b...b.
    -7,    // w...b.
    -30,   // .b..b.
    -7,    // bb..b.
    15,    // wb..b.
    0,     // .w..b.
    -19,   // bw..b.
    -1,    // ww..b.
    -7,    // ..b.b.
    -5,    // b.b.b.
    1,     // w.b.b.
    -7,    // .bb.b.
    -27,   // bbb.b.
    17,    // wbb.b.
    7,     // .wb.b.
    -23,   // bwb.b.
    3,     // wwb.b.
    -17,   // ..w.b.
    5,     // b.w.b.
    -3,    // w.w.b.
    -7,    // .bw.b.
    -9,    // bbw.b.
    -9,    // wbw.b.
    1,     // .ww.b.
    3,     // bww.b.
    -3,    // www.b.
    -11,   // ...bb.
    1,     // b..bb.
    -3,    // w..bb.
    -7,    // .b.bb.
    -7,    // bb.bb.
    -5,    // wb.bb.
    -1,    // .w.bb.
    13,    // bw.bb.
    1,     // ww.bb.
    7,     // ..bbb.
    -19,   // b.bbb.
    -3,    // w.bbb.
    18,    // .bbbb.
    7,     // bbbbb.
    1,     // wbbbb.
    1,     // .wbbb.
    3,     // bwbbb.
    -29,   // wwbbb.
    5,     // ..wbb.
    5,     // b.wbb.
    -1,    // w.wbb.
    -9,    // .bwbb.
    3,     // bbwbb.
    3,     // wbwbb.
    0,     // .wwbb.
    -3,    // bwwbb.
    5,     // wwwbb.
    -3,    // ...wb.
    -1,    // b..wb.
    -19,   // w..wb.
    -7,    // .b.wb.
    -5,    // bb.wb.
    -17,   // wb.wb.
    -7,    // .w.wb.
    -13,   // bw.wb.
    19,    // ww.wb.
    9,     // ..bwb.
    19,    // b.bwb.
    -13,   // w.bwb.
    -9,    // .bbwb.
    -3,    // bbbwb.
    7,     // wbbwb.
    0,     // .wbwb.
    11,    // bwbwb.
    -3,    // wwbwb.
    19,    // ..wwb.
    -7,    // b.wwb.
    13,    // w.wwb.
    22,    // .bwwb.
    1,     // bbwwb.
    -3,    // wbwwb.
    -1,    // .wwwb.
    9,     // bwwwb.
    11,    // wwwwb.
    -3,    // ....w.
    7,     // b...w.
    1,     // w...w.
    0,     // .b..w.
    1,     // bb..w.
    19,    // wb..w.
    30,    // .w..w.
    -15,   // bw..w.
    7,     // ww..w.
    17,    // ..b.w.
    3,     // b.b.w.
    -5,    // w.b.w.
    -1,    // .bb.w.
    3,     // bbb.w.
    -3,    // wbb.w.
    7,     // .wb.w.
    9,     // bwb.w.
    9,     // wwb.w.
    7,     // ..w.w.
    -1,    // b.w.w.
    5,     // w.w.w.
    -7,    // .bw.w.
    -3,    // bbw.w.
    23,    // wbw.w.
    7,     // .ww.w.
    -17,   // bww.w.
    27,    // www.w.
    3,     // ...bw.
    19,    // b..bw.
    1,     // w..bw.
    7,     // .b.bw.
    -19,   // bb.bw.
    13,    // wb.bw.
    7,     // .w.bw.
    17,    // bw.bw.
    5,     // ww.bw.
    -19,   // ..bbw.
    -13,   // b.bbw.
    7,     // w.bbw.
    1,     // .bbbw.
    -11,   // bbbbw.
    -9,    // wbbbw.
    -22,   // .wbbw.
    3,     // bwbbw.
    -1,    // wwbbw.
    -9,    // ..wbw.
    13,    // b.wbw.
    -19,   // w.wbw.
    0,     // .bwbw.
    3,     // bbwbw.
    -11,   // wbwbw.
    9,     // .wwbw.
    -7,    // bwwbw.
    3,     // wwwbw.
    11,    // ...ww.
    3,     // b..ww.
    -1,    // w..ww.
    1,     // .b.ww.
    -1,    // bb.ww.
    -13,   // wb.ww.
    7,     // .w.ww.
    5,     // bw.ww.
    7,     // ww.ww.
    -5,    // ..bww.
    1,     // b.bww.
    -5,    // w.bww.
    0,     // .bbww.
    -5,    // bbbww.
    3,     // wbbww.
    9,     // .wbww.
    -3,    // bwbww.
    -3,    // wwbww.
    -7,    // ..www.
    3,     // b.www.
    19,    // w.www.
    -1,    // .bwww.
    29,    // bbwww.
    -3,    // wbwww.
    -18,   // .wwww.
    -1,    // bwwww.
    -7,    // wwwww.
    3,     // .....b
    14,    // b....b
    0,     // w....b
    -1,    // .b...b
    -3,    // bb...b
    -11,   // wb...b
    7,     // .w...b
    3,     // bw...b
    17,    // ww...b
    -7,    // ..b..b
    13,    // b.b..b
    -27,   // w.b..b
    1,     // .bb..b
    -9,    // bbb..b
    21,    // wbb..b
    19,    // .wb..b
    19,    // bwb..b
    -3,    // wwb..b
    13,    // ..w..b
    -11,   // b.w..b
    -15,   // w.w..b
    -1,    // .bw..b
    3,     // bbw..b
    -1,    // wbw..b
    3,     // .ww..b
    9,     // bww..b
    -13,   // www..b
    -21,   // ...b.b
    13,    // b..b.b
    15,    // w..b.b
    -5,    // .b.b.b
    -13,   // bb.b.b
    17,    // wb.b.b
    3,     // .w.b.b
    3,     // bw.b.b
    -9,    // ww.b.b
    7,     // ..bb.b
    6,     // b.bb.b
    -27,   // w.bb.b
    -19,   // .bbb.b
    1,     // bbbb.b
    -5,    // wbbb.b
    -13,   // .wbb.b
    -5,    // bwbb.b
    -15,   // wwbb.b
    3,     // ..wb.b
    17,    // b.wb.b
    0,     // w.wb.b
    19,    // .bwb.b
    -7,    // bbwb.b
    5,     // wbwb.b
    1,     // .wwb.b
    1,     // bwwb.b
    -9,    // wwwb.b
    7,     // ...w.b
    -11,   // b..w.b
    27,    // w..w.b
    5,     // .b.w.b
    11,    // bb.w.b
    -7,    // wb.w.b
    -1,    // .w.w.b
    -9,    // bw.w.b
    11,    // ww.w.b
    1,     // ..bw.b
    17,    // b.bw.b
    0,     // w.bw.b
    5,     // .bbw.b
    -3,    // bbbw.b
    -17,   // wbbw.b
    13,    // .wbw.b
    -9,    // bwbw.b
    3,     // wwbw.b
    -7,    // ..ww.b
    -42,   // b.ww.b
    27,    // w.ww.b
    -7,    // .bww.b
    13,    // bbww.b
    -5,    // wbww.b
    3,     // .www.b
    7,     // bwww.b
    -1,    // wwww.b
    -5,    // ....bb
    -3,    // b...bb
    -17,   // w...bb
    -7,    // .b..bb
    -38,   // bb..bb
    13,    // wb..bb
    1,     // .w..bb
    -9,    // bw..bb
    0,     // ww..bb
    -17,   // ..b.bb
    -13,   // b.b.bb
    -11,   // w.b.bb
    -7,    // .bb.bb
    -25,   // bbb.bb
    -3,    // wbb.bb
    -19,   // .wb.bb
    1,     // bwb.bb
    15,    // wwb.bb
    -31,   // ..w.bb
    11,    // b.w.bb
    9,     // w.w.bb
    -5,    // .bw.bb
    15,    // bbw.bb
    1,     // wbw.bb
    -1,    // .ww.bb
    -9,    // bww.bb
    -3,    // www.bb
    21,    // ...bbb
    -9,    // b..bbb
    13,    // w..bbb
    -27,   // .b.bbb
    -25,   // bb.bbb
    -13,   // wb.bbb
    3,     // .w.bbb
    -1,    // bw.bbb
    3,     // ww.bbb
    41,    // ..bbbb
    1,     // b.bbbb
    1,     // w.bbbb
    7,     // .bbbbb
    22,    // bbbbbb
    17,    // wbbbbb
    -11,   // .wbbbb
    11,    // bwbbbb
    9,     // wwbbbb
    5,     // ..wbbb
    -3,    // b.wbbb
    9,     // w.wbbb
    -3,    // .bwbbb
    9,     // bbwbbb
    -9,    // wbwbbb
    -5,    // .wwbbb
    7,     // bwwbbb
    0,     // wwwbbb
    -27,   // ...wbb
    3,     // b..wbb
    3,     // w..wbb
    -9,    // .b.wbb
    15,    // bb.wbb
    19,    // wb.wbb
    -3,    // .w.wbb
    9,     // bw.wbb
    -15,   // ww.wbb
    -7,    // ..bwbb
    -7,    // b.bwbb
    -3,    // w.bwbb
    3,     // .bbwbb
    9,     // bbbwbb
    21,    // wbbwbb
    3,     // .wbwbb
    11,    // bwbwbb
    0,     // wwbwbb
    5,     // ..wwbb
    13,    // b.wwbb
    15,    // w.wwbb
    1,     // .bwwbb
    -10,   // bbwwbb
    21,    // wbwwbb
    29,    // .wwwbb
    3,     // bwwwbb
    -9,    // wwwwbb
    -3,    // ....wb
    3,     // b...wb
    11,    // w...wb
    -19,   // .b..wb
    -9,    // bb..wb
    0,     // wb..wb
    -15,   // .w..wb
    10,    // bw..wb
    -13,   // ww..wb
    9,     // ..b.wb
    3,     // b.b.wb
    7,     // w.b.wb
    13,    // .bb.wb
    -1,    // bbb.wb
    17,    // wbb.wb
    17,    // .wb.wb
    -13,   // bwb.wb
    -19,   // wwb.wb
    3,     // ..w.wb
    -9,    // b.w.wb
    -17,   // w.w.wb
    -13,   // .bw.wb
    9,     // bbw.wb
    -21,   // wbw.wb
    5,     // .ww.wb
    -11,   // bww.wb
    13,    // www.wb
    1,     // ...bwb
    19,    // b..bwb
    1,     // w..bwb
    -23,   // .b.bwb
    1,     // bb.bwb
    21,    // wb.bwb
    9,     // .w.bwb
    -13,   // bw.bwb
    -1,    // ww.bwb
    5,     // ..bbwb
    -5,    // b.bbwb
    5,     // w.bbwb
    3,     // .bbbwb
    11,    // bbbbwb
    5,     // wbbbwb
    3,     // .wbbwb
    34,    // bwbbwb
    -21,   // wwbbwb
    -7,    // ..wbwb
    -9,    // b.wbwb
    -5,    // w.wbwb
    11,    // .bwbwb
    11,    // bbwbwb
    0,     // wbwbwb
    -3,    // .wwbwb
    -11,   // bwwbwb
    9,     // wwwbwb
    1,     // ...wwb
    9,     // b..wwb
    -21,   // w..wwb
    3,     // .b.wwb
    -9,    // bb.wwb
    -17,   // wb.wwb
    -17,   // .w.wwb
    -11,   // bw.wwb
    3,     // ww.wwb
    7,     // ..bwwb
    1,     // b.bwwb
    17,    // w.bwwb
    -3,    // .bbwwb
    7,     // bbbwwb
    0,     // wbbwwb
    -7,    // .wbwwb
    -11,   // bwbwwb
    -21,   // wwbwwb
    1,     // ..wwwb
    7,     // b.wwwb
    5,     // w.wwwb
    9,     // .bwwwb
    3,     // bbwwwb
    -5,    // wbwwwb
    -1,    // .wwwwb
    18,    // bwwwwb
    -17,   // wwwwwb
    -3,    // .....w
    0,     // b....w
    -14,   // w....w
    -7,    // .b...w
    -17,   // bb...w
    -3,    // wb...w
    1,     // .w...w
    11,    // bw...w
    3,     // ww...w
    -13,   // ..b..w
    15,    // b.b..w
    11,    // w.b..w
    -3,    // .bb..w
    13,    // bbb..w
    -9,    // wbb..w
    1,     // .wb..w
    1,     // bwb..w
    -3,    // wwb..w
    7,     // ..w..w
    27,    // b.w..w
    -13,   // w.w..w
    -19,   // .bw..w
    3,     // bbw..w
    -19,   // wbw..w
    -1,    // .ww..w
    -21,   // bww..w
    9,     // www..w
    -7,    // ...b.w
    -27,   // b..b.w
    11,    // w..b.w
    1,     // .b.b.w
    -11,   // bb.b.w
    9,     // wb.b.w
    -5,    // .w.b.w
    7,     // bw.b.w
    -11,   // ww.b.w
    7,     // ..bb.w
    -27,   // b.bb.w
    42,    // w.bb.w
    -3,    // .bbb.w
    1,     // bbbb.w
    -7,    // wbbb.w
    7,     // .wbb.w
    5,     // bwbb.w
    -13,   // wwbb.w
    -1,    // ..wb.w
    0,     // b.wb.w
    -17,   // w.wb.w
    -13,   // .bwb.w
    -3,    // bbwb.w
    9,     // wbwb.w
    -5,    // .wwb.w
    17,    // bwwb.w
    3,     // wwwb.w
    21,    // ...w.w
    -15,   // b..w.w
    -13,   // w..w.w
    -3,    // .b.w.w
    9,     // bb.w.w
    -3,    // wb.w.w
    5,     // .w.w.w
    -17,   // bw.w.w
    13,    // ww.w.w
    -3,    // ..bw.w
    0,     // b.bw.w
    -17,   // w.bw.w
    -1,    // .bbw.w
    9,     // bbbw.w
    -1,    // wbbw.w
    -19,   // .wbw.w
    -5,    // bwbw.w
    7,     // wwbw.w
    -7,    // ..ww.w
    27,    // b.ww.w
    -6,    // w.ww.w
    13,    // .bww.w
    15,    // bbww.w
    5,     // wbww.w
    19,    // .www.w
    5,     // bwww.w
    -1,    // wwww.w
    3,     // ....bw
    -11,   // b...bw
    -3,    // w...bw
    15,    // .b..bw
    13,    // bb..bw
    -10,   // wb..bw
    19,    // .w..bw
    0,     // bw..bw
    9,     // ww..bw
    -3,    // ..b.bw
    17,    // b.b.bw
    9,     // w.b.bw
    -5,    // .bb.bw
    -13,   // bbb.bw
    11,    // wbb.bw
    13,    // .wb.bw
    21,    // bwb.bw
    -9,    // wwb.bw
    -9,    // ..w.bw
    -7,    // b.w.bw
    -3,    // w.w.bw
    -17,   // .bw.bw
    19,    // bbw.bw
    13,    // wbw.bw
    -13,   // .ww.bw
    -17,   // bww.bw
    1,     // www.bw
    -1,    // ...bbw
    21,    // b..bbw
    -9,    // w..bbw
    17,    // .b.bbw
    -3,    // bb.bbw
    11,    // wb.bbw
    -3,    // .w.bbw
    17,    // bw.bbw
    9,     // ww.bbw
    -1,    // ..bbbw
    -5,    // b.bbbw
    -7,    // w.bbbw
    1,     // .bbbbw
    17,    // bbbbbw
    -18,   // wbbbbw
    -9,    // .wbbbw
    5,     // bwbbbw
    -3,    // wwbbbw
    -7,    // ..wbbw
    -17,   // b.wbbw
    -1,    // w.wbbw
    7,     // .bwbbw
    21,    // bbwbbw
    11,    // wbwbbw
    3,     // .wwbbw
    0,     // bwwbbw
    -7,    // wwwbbw
    -1,    // ...wbw
    -1,    // b..wbw
    -19,   // w..wbw
    -9,    // .b.wbw
    1,     // bb.wbw
    13,    // wb.wbw
    23,    // .w.wbw
    -21,   // bw.wbw
    -1,    // ww.wbw
    7,     // ..bwbw
    5,     // b.bwbw
    9,     // w.bwbw
    3,     // .bbwbw
    -9,    // bbbwbw
    11,    // wbbwbw
    -11,   // .wbwbw
    0,     // bwbwbw
    -11,   // wwbwbw
    -5,    // ..wwbw
    -5,    // b.wwbw
    5,     // w.wwbw
    -3,    // .bwwbw
    21,    // bbwwbw
    -34,   // wbwwbw
    -3,    // .wwwbw
    -5,    // bwwwbw
    -11,   // wwwwbw
    5,     // ....ww
    17,    // b...ww
    3,     // w...ww
    -1,    // .b..ww
    0,     // bb..ww
    9,     // wb..ww
    7,     // .w..ww
    -13,   // bw..ww
    38,    // ww..ww
    31,    // ..b.ww
    -9,    // b.b.ww
    -11,   // w.b.ww
    1,     // .bb.ww
    3,     // bbb.ww
    9,     // wbb.ww
    5,     // .wb.ww
    -1,    // bwb.ww
    -15,   // wwb.ww
    17,    // ..w.ww
    11,    // b.w.ww
    13,    // w.w.ww
    19,    // .bw.ww
    -15,   // bbw.ww
    -1,    // wbw.ww
    7,     // .ww.ww
    3,     // bww.ww
    25,    // www.ww
    27,    // ...bww
    -3,    // b..bww
    -3,    // w..bww
    3,     // .b.bww
    15,    // bb.bww
    -9,    // wb.bww
    9,     // .w.bww
    -19,   // bw.bww
    -15,   // ww.bww
    -5,    // ..bbww
    -15,   // b.bbww
    -13,   // w.bbww
    -29,   // .bbbww
    9,     // bbbbww
    -3,    // wbbbww
    -1,    // .wbbww
    -21,   // bwbbww
    10,    // wwbbww
    7,     // ..wbww
    3,     // b.wbww
    7,     // w.wbww
    -3,    // .bwbww
    0,     // bbwbww
    -11,   // wbwbww
    -3,    // .wwbww
    -21,   // bwwbww
    -9,    // wwwbww
    -21,   // ...www
    -13,   // b..www
    9,     // w..www
    -3,    // .b.www
    -3,    // bb.www
    1,     // wb.www
    27,    // .w.www
    13,    // bw.www
    25,    // ww.www
    -5,    // ..bwww
    -9,    // b.bwww
    3,     // w.bwww
    5,     // .bbwww
    0,     // bbbwww
    -7,    // wbbwww
    3,     // .wbwww
    9,     // bwbwww
    -9,    // wwbwww
    -41,   // ..wwww
    -1,    // b.wwww
    -1,    // w.wwww
    11,    // .bwwww
    -9,    // bbwwww
    -11,   // wbwwww
    -7,    // .wwwww
    -17,   // bwwwww
    -22,   // wwwwww
    -1,    // ccc
    13,    // cc
    1,     // c
    3,     // ttt
    5,     // tt
    -5,    // t
    13,    // ct
    11,    // cct
    -5,    // ctt
].into_boxed_slice()
