vec![
    0,     // ......
    3,     // b.....
    -3,    // w.....
    -6,    // .b....
    -10,   // bb....
    7,     // wb....
    6,     // .w....
    -7,    // bw....
    10,    // ww....
    -1,    // ..b...
    -12,   // b.b...
    7,     // w.b...
    -14,   // .bb...
    32,    // bbb...
    -4,    // wbb...
    -16,   // .wb...
    -18,   // bwb...
    -12,   // wwb...
    1,     // ..w...
    -7,    // b.w...
    12,    // w.w...
    16,    // .bw...
    12,    // bbw...
    18,    // wbw...
    14,    // .ww...
    4,     // bww...
    -32,   // www...
    -1,    // ...b..
    -15,   // b..b..
    8,     // w..b..
    -9,    // .b.b..
    -4,    // bb.b..
    2,     // wb.b..
    -11,   // .w.b..
    -34,   // bw.b..
    5,     // ww.b..
    3,     // ..bb..
    16,    // b.bb..
    9,     // w.bb..
    26,    // .bbb..
    -4,    // bbbb..
    -23,   // wbbb..
    10,    // .wbb..
    3,     // bwbb..
    -5,    // wwbb..
    0,     // ..wb..
    -14,   // b.wb..
    -6,    // w.wb..
    -5,    // .bwb..
    -11,   // bbwb..
    32,    // wbwb..
    -18,   // .wwb..
    1,     // bwwb..
    10,    // wwwb..
    1,     // ...w..
    -8,    // b..w..
    15,    // w..w..
    11,    // .b.w..
    -5,    // bb.w..
    34,    // wb.w..
    9,     // .w.w..
    -2,    // bw.w..
    4,     // ww.w..
    0,     // ..bw..
    6,     // b.bw..
    14,    // w.bw..
    18,    // .bbw..
    -10,   // bbbw..
    -1,    // wbbw..
    5,     // .wbw..
    -32,   // bwbw..
    11,    // wwbw..
    -3,    // ..ww..
    -9,    // b.ww..
    -16,   // w.ww..
    -10,   // .bww..
    5,     // bbww..
    -3,    // wbww..
    -26,   // .www..
    23,    // bwww..
    4,     // wwww..
    -6,    // ....b.
    -6,    // b...b.
    2,     // w...b.
    -16,   // .b..b.
    -13,   // bb..b.
    14,    // wb..b.
    0,     // .w..b.
    -12,   // bw..b.
    8,     // ww..b.
    -9,    // ..b.b.
    -27,   // b.b.b.
    21,    // w.b.b.
    19,    // .bb.b.
    8,     // bbb.b.
    6,     // wbb.b.
    -29,   // .wb.b.
    10,    // bwb.b.
    2,     // wwb.b.
    11,    // ..w.b.
    -29,   // b.w.b.
    -11,   // w.w.b.
    5,     // .bw.b.
    -2,    // bbw.b.
    5,     // wbw.b.
    25,    // .ww.b.
    12,    // bww.b.
    9,     // www.b.
    -14,   // ...bb.
    3,     // b..bb.
    -11,   // w..bb.
    19,    // .b.bb.
    26,    // bb.bb.
    8,     // wb.bb.
    -25,   // .w.bb.
    -1,    // bw.bb.
    0,     // ww.bb.
    26,    // ..bbb.
    27,    // b.bbb.
    2,     // w.bbb.
    49,    // .bbbb.
    6,     // bbbbb.
    -17,   // wbbbb.
    10,    // .wbbb.
    -3,    // bwbbb.
    8,     // wwbbb.
    18,    // ..wbb.
    -1,    // b.wbb.
    -4,    // w.wbb.
    -1,    // .bwbb.
    5,     // bbwbb.
    -3,    // wbwbb.
    0,     // .wwbb.
    -13,   // bwwbb.
    -14,   // wwwbb.
    16,    // ...wb.
    -1,    // b..wb.
    6,     // w..wb.
    5,     // .b.wb.
    -21,   // bb.wb.
    8,     // wb.wb.
    29,    // .w.wb.
    7,     // bw.wb.
    -9,    // ww.wb.
    -5,    // ..bwb.
    2,     // b.bwb.
    0,     // w.bwb.
    -1,    // .bbwb.
    -11,   // bbbwb.
    -8,    // wbbwb.
    0,     // .wbwb.
    5,     // bwbwb.
    -12,   // wwbwb.
    -10,   // ..wwb.
    11,    // b.wwb.
    21,    // w.wwb.
    -8,    // .bwwb.
    15,    // bbwwb.
    33,    // wbwwb.
    -10,   // .wwwb.
    -16,   // bwwwb.
    9,     // wwwwb.
    6,     // ....w.
    -2,    // b...w.
    6,     // w...w.
    0,     // .b..w.
    -8,    // bb..w.
    12,    // wb..w.
    16,    // .w..w.
    -14,   // bw..w.
    13,    // ww..w.
    -11,   // ..b.w.
    11,    // b.b.w.
    29,    // w.b.w.
    -25,   // .bb.w.
    -9,    // bbb.w.
    -12,   // wbb.w.
    -5,    // .wb.w.
    -5,    // bwb.w.
    2,     // wwb.w.
    9,     // ..w.w.
    -21,   // b.w.w.
    27,    // w.w.w.
    29,    // .bw.w.
    -2,    // bbw.w.
    -10,   // wbw.w.
    -19,   // .ww.w.
    -6,    // bww.w.
    -8,    // www.w.
    -16,   // ...bw.
    -6,    // b..bw.
    1,     // w..bw.
    -29,   // .b.bw.
    9,     // bb.bw.
    -7,    // wb.bw.
    -5,    // .w.bw.
    -8,    // bw.bw.
    21,    // ww.bw.
    10,    // ..bbw.
    -21,   // b.bbw.
    -11,   // w.bbw.
    10,    // .bbbw.
    -9,    // bbbbw.
    16,    // wbbbw.
    8,     // .wbbw.
    -33,   // bwbbw.
    -15,   // wwbbw.
    5,     // ..wbw.
    0,     // b.wbw.
    -2,    // w.wbw.
    0,     // .bwbw.
    12,    // bbwbw.
    -5,    // wbwbw.
    1,     // .wwbw.
    8,     // bwwbw.
    11,    // wwwbw.
    14,    // ...ww.
    11,    // b..ww.
    -3,    // w..ww.
    25,    // .b.ww.
    0,     // bb.ww.
    1,     // wb.ww.
    -19,   // .w.ww.
    -8,    // bw.ww.
    -26,   // ww.ww.
    -18,   // ..bww.
    4,     // b.bww.
    1,     // w.bww.
    0,     // .bbww.
    14,    // bbbww.
    13,    // wbbww.
    1,     // .wbww.
    3,     // bwbww.
    -5,    // wwbww.
    -26,   // ..www.
    -2,    // b.www.
    -27,   // w.www.
    -10,   // .bwww.
    -8,    // bbwww.
    3,     // wbwww.
    -49,   // .wwww.
    17,    // bwwww.
    -6,    // wwwww.
    3,     // .....b
    -24,   // b....b
    0,     // w....b
    -6,    // .b...b
    -21,   // bb...b
    -2,    // wb...b
    -2,    // .w...b
    -5,    // bw...b
    29,    // ww...b
    -15,   // ..b..b
    -16,   // b.b..b
    -11,   // w.b..b
    3,     // .bb..b
    12,    // bbb..b
    -18,   // wbb..b
    -6,    // .wb..b
    -1,    // bwb..b
    14,    // wwb..b
    -8,    // ..w..b
    2,     // b.w..b
    -13,   // w.w..b
    -1,    // .bw..b
    4,     // bbw..b
    2,     // wbw..b
    11,    // .ww..b
    7,     // bww..b
    -5,    // www..b
    -12,   // ...b.b
    -16,   // b..b.b
    13,    // w..b.b
    -27,   // .b.b.b
    -1,    // bb.b.b
    19,    // wb.b.b
    11,    // .w.b.b
    -13,   // bw.b.b
    -2,    // ww.b.b
    16,    // ..bb.b
    -4,    // b.bb.b
    14,    // w.bb.b
    27,    // .bbb.b
    24,    // bbbb.b
    3,     // wbbb.b
    -21,   // .wbb.b
    -5,    // bwbb.b
    6,     // wwbb.b
    6,     // ..wb.b
    -8,    // b.wb.b
    0,     // w.wb.b
    2,     // .bwb.b
    -13,   // bbwb.b
    7,     // wbwb.b
    4,     // .wwb.b
    6,     // bwwb.b
    -33,   // wwwb.b
    -7,    // ...w.b
    2,     // b..w.b
    11,    // w..w.b
    -29,   // .b.w.b
    8,     // bb.w.b
    0,     // wb.w.b
    -21,   // .w.w.b
    -28,   // bw.w.b
    -2,    // ww.w.b
    -14,   // ..bw.b
    -8,    // b.bw.b
    0,     // w.bw.b
    -1,    // .bbw.b
    -13,   // bbbw.b
    -9,    // wbbw.b
    0,     // .wbw.b
    -11,   // bwbw.b
    -16,   // wwbw.b
    -9,    // ..ww.b
    4,     // b.ww.b
    -14,   // w.ww.b
    11,    // .bww.b
    -6,    // bbww.b
    17,    // wbww.b
    -2,    // .www.b
    -1,    // bwww.b
    -15,   // wwww.b
    -10,   // ....bb
    -21,   // b...bb
    -29,   // w...bb
    -13,   // .b..bb
    17,    // bb..bb
    31,    // wb..bb
    -8,    // .w..bb
    -34,   // bw..bb
    0,     // ww..bb
    -4,    // ..b.bb
    -1,    // b.b.bb
    2,     // w.b.bb
    26,    // .bb.bb
    17,    // bbb.bb
    -26,   // wbb.bb
    9,     // .wb.bb
    -6,    // bwb.bb
    -5,    // wwb.bb
    -5,    // ..w.bb
    8,     // b.w.bb
    2,     // w.w.bb
    -21,   // .bw.bb
    -1,    // bbw.bb
    -8,    // wbw.bb
    0,     // .ww.bb
    -15,   // bww.bb
    -24,   // www.bb
    32,    // ...bbb
    12,    // b..bbb
    5,     // w..bbb
    8,     // .b.bbb
    17,    // bb.bbb
    -30,   // wb.bbb
    -9,    // .w.bbb
    -15,   // bw.bbb
    24,    // ww.bbb
    -4,    // ..bbbb
    24,    // b.bbbb
    15,    // w.bbbb
    6,     // .bbbbb
    -7,    // bbbbbb
    -2,    // wbbbbb
    -9,    // .wbbbb
    9,     // bwbbbb
    2,     // wwbbbb
    -10,   // ..wbbb
    -13,   // b.wbbb
    33,    // w.wbbb
    -11,   // .bwbbb
    2,     // bbwbbb
    15,    // wbwbbb
    14,    // .wwbbb
    8,     // bwwbbb
    0,     // wwwbbb
    12,    // ...wbb
    4,     // b..wbb
    -14,   // w..wbb
    -2,    // .b.wbb
    -1,    // bb.wbb
    11,    // wb.wbb
    -2,    // .w.wbb
    2,     // bw.wbb
    5,     // ww.wbb
    -11,   // ..bwbb
    -13,   // b.bwbb
    16,    // w.bwbb
    5,     // .bbwbb
    2,     // bbbwbb
    -20,   // wbbwbb
    12,    // .wbwbb
    -4,    // bwbwbb
    0,     // wwbwbb
    5,     // ..wwbb
    -6,    // b.wwbb
    -6,    // w.wwbb
    15,    // .bwwbb
    -16,   // bbwwbb
    9,     // wbwwbb
    -8,    // .wwwbb
    17,    // bwwwbb
    -2,    // wwwwbb
    -7,    // ....wb
    -5,    // b...wb
    2,     // w...wb
    -12,   // .b..wb
    -34,   // bb..wb
    0,     // wb..wb
    -14,   // .w..wb
    -2,    // bw..wb
    -31,   // ww..wb
    -34,   // ..b.wb
    -13,   // b.b.wb
    0,     // w.b.wb
    -1,    // .bb.wb
    -15,   // bbb.wb
    12,    // wbb.wb
    -8,    // .wb.wb
    -1,    // bwb.wb
    -11,   // wwb.wb
    -2,    // ..w.wb
    -28,   // b.w.wb
    -19,   // w.w.wb
    7,     // .bw.wb
    2,     // bbw.wb
    5,     // wbw.wb
    -8,    // .ww.wb
    -12,   // bww.wb
    30,    // www.wb
    -18,   // ...bwb
    -1,    // b..bwb
    -2,    // w..bwb
    10,    // .b.bwb
    -6,    // bb.bwb
    -5,    // wb.bwb
    -5,    // .w.bwb
    -1,    // bw.bwb
    8,     // ww.bwb
    3,     // ..bbwb
    -5,    // b.bbwb
    -17,   // w.bbwb
    -3,    // .bbbwb
    9,     // bbbbwb
    0,     // wbbbwb
    -33,   // .wbbwb
    -39,   // bwbbwb
    -9,    // wwbbwb
    -32,   // ..wbwb
    -11,   // b.wbwb
    -7,    // w.wbwb
    5,     // .bwbwb
    -4,    // bbwbwb
    0,     // wbwbwb
    3,     // .wwbwb
    6,     // bwwbwb
    -15,   // wwwbwb
    4,     // ...wwb
    7,     // b..wwb
    18,    // w..wwb
    12,    // .b.wwb
    -15,   // bb.wwb
    -12,   // wb.wwb
    -6,    // .w.wwb
    -12,   // bw.wwb
    26,    // ww.wwb
    1,     // ..bwwb
    6,     // b.bwwb
    9,     // w.bwwb
    -13,   // .bbwwb
    8,     // bbbwwb
    0,     // wbbwwb
    8,     // .wbwwb
    6,     // bwbwwb
    20,    // wwbwwb
    23,    // ..wwwb
    -1,    // b.wwwb
    -3,    // w.wwwb
    -16,   // .bwwwb
    17,    // bbwwwb
    0,     // wbwwwb
    17,    // .wwwwb
    -2,    // bwwwwb
    2,     // wwwwwb
    -3,    // .....w
    0,     // b....w
    24,    // w....w
    2,     // .b...w
    -29,   // bb...w
    5,     // wb...w
    6,     // .w...w
    2,     // bw...w
    21,    // ww...w
    8,     // ..b..w
    13,    // b.b..w
    -2,    // w.b..w
    -11,   // .bb..w
    5,     // bbb..w
    -7,    // wbb..w
    1,     // .wb..w
    -2,    // bwb..w
    -4,    // wwb..w
    15,    // ..w..w
    11,    // b.w..w
    16,    // w.w..w
    6,     // .bw..w
    -14,   // bbw..w
    1,     // wbw..w
    -3,    // .ww..w
    18,    // bww..w
    -12,   // www..w
    7,     // ...b.w
    -11,   // b..b.w
    -2,    // w..b.w
    21,    // .b.b.w
    2,     // bb.b.w
    28,    // wb.b.w
    29,    // .w.b.w
    0,     // bw.b.w
    -8,    // ww.b.w
    9,     // ..bb.w
    14,    // b.bb.w
    -4,    // w.bb.w
    2,     // .bbb.w
    15,    // bbbb.w
    1,     // wbbb.w
    -11,   // .wbb.w
    -17,   // bwbb.w
    6,     // wwbb.w
    14,    // ..wb.w
    0,     // b.wb.w
    8,     // w.wb.w
    0,     // .bwb.w
    16,    // bbwb.w
    11,    // wbwb.w
    1,     // .wwb.w
    9,     // bwwb.w
    13,    // wwwb.w
    12,    // ...w.w
    -13,   // b..w.w
    16,    // w..w.w
    -11,   // .b.w.w
    2,     // bb.w.w
    13,    // wb.w.w
    27,    // .w.w.w
    -19,   // bw.w.w
    1,     // ww.w.w
    -6,    // ..bw.w
    0,     // b.bw.w
    8,     // w.bw.w
    -4,    // .bbw.w
    33,    // bbbw.w
    -6,    // wbbw.w
    -2,    // .wbw.w
    -7,    // bwbw.w
    13,    // wwbw.w
    -16,   // ..ww.w
    -14,   // b.ww.w
    4,     // w.ww.w
    21,    // .bww.w
    -6,    // bbww.w
    5,     // wbww.w
    -27,   // .www.w
    -3,    // bwww.w
    -24,   // wwww.w
    7,     // ....bw
    -2,    // b...bw
    5,     // w...bw
    14,    // .b..bw
    31,    // bb..bw
    2,     // wb..bw
    12,    // .w..bw
    0,     // bw..bw
    34,    // ww..bw
    2,     // ..b.bw
    19,    // b.b.bw
    28,    // w.b.bw
    8,     // .bb.bw
    -30,   // bbb.bw
    12,    // wbb.bw
    -7,    // .wb.bw
    -5,    // bwb.bw
    -2,    // wwb.bw
    34,    // ..w.bw
    0,     // b.w.bw
    13,    // w.w.bw
    8,     // .bw.bw
    11,    // bbw.bw
    1,     // wbw.bw
    1,     // .ww.bw
    -12,   // bww.bw
    15,    // www.bw
    -4,    // ...bbw
    -18,   // b..bbw
    -7,    // w..bbw
    6,     // .b.bbw
    -26,   // bb.bbw
    12,    // wb.bbw
    -12,   // .w.bbw
    12,    // bw.bbw
    15,    // ww.bbw
    -23,   // ..bbbw
    3,     // b.bbbw
    1,     // w.bbbw
    -17,   // .bbbbw
    -2,    // bbbbbw
    2,     // wbbbbw
    16,    // .wbbbw
    0,     // bwbbbw
    -17,   // wwbbbw
    -1,    // ..wbbw
    -9,    // b.wbbw
    -6,    // w.wbbw
    -8,    // .bwbbw
    -20,   // bbwbbw
    -6,    // wbwbbw
    13,    // .wwbbw
    0,     // bwwbbw
    -8,    // wwwbbw
    18,    // ...wbw
    2,     // b..wbw
    1,     // w..wbw
    5,     // .b.wbw
    -8,    // bb.wbw
    1,     // wb.wbw
    -10,   // .w.wbw
    5,     // bw.wbw
    6,     // ww.wbw
    32,    // ..bwbw
    7,     // b.bwbw
    11,    // w.bwbw
    -3,    // .bbwbw
    15,    // bbbwbw
    -6,    // wbbwbw
    -5,    // .wbwbw
    0,     // bwbwbw
    4,     // wwbwbw
    -3,    // ..wwbw
    17,    // b.wwbw
    5,     // w.wwbw
    33,    // .bwwbw
    9,     // bbwwbw
    39,    // wbwwbw
    3,     // .wwwbw
    0,     // bwwwbw
    -9,    // wwwwbw
    10,    // ....ww
    29,    // b...ww
    21,    // w...ww
    8,     // .b..ww
    0,     // bb..ww
    34,    // wb..ww
    13,    // .w..ww
    -31,   // bw..ww
    -17,   // ww..ww
    5,     // ..b.ww
    -2,    // b.b.ww
    -8,    // w.b.ww
    0,     // .bb.ww
    24,    // bbb.ww
    15,    // wbb.ww
    21,    // .wb.ww
    8,     // bwb.ww
    1,     // wwb.ww
    4,     // ..w.ww
    -2,    // b.w.ww
    1,     // w.w.ww
    -9,    // .bw.ww
    5,     // bbw.ww
    6,     // wbw.ww
    -26,   // .ww.ww
    26,    // bww.ww
    -17,   // www.ww
    -12,   // ...bww
    14,    // b..bww
    -4,    // w..bww
    2,     // .b.bww
    -5,    // bb.bww
    -2,    // wb.bww
    2,     // .w.bww
    -11,   // bw.bww
    1,     // ww.bww
    -5,    // ..bbww
    6,     // b.bbww
    6,     // w.bbww
    8,     // .bbbww
    2,     // bbbbww
    -17,   // wbbbww
    -15,   // .wbbww
    -9,    // bwbbww
    16,    // wwbbww
    11,    // ..wbww
    -16,   // b.wbww
    13,    // w.wbww
    -12,   // .bwbww
    0,     // bbwbww
    4,     // wbwbww
    -5,    // .wwbww
    20,    // bwwbww
    -2,    // wwwbww
    -32,   // ...www
    -5,    // b..www
    -12,   // w..www
    9,     // .b.www
    -24,   // bb.www
    15,    // wb.www
    -8,    // .w.www
    30,    // bw.www
    -17,   // ww.www
    10,    // ..bwww
    -33,   // b.bwww
    13,    // w.bwww
    -14,   // .bbwww
    0,     // bbbwww
    -8,    // wbbwww
    11,    // .wbwww
    -15,   // bwbwww
    -2,    // wwbwww
    4,     // ..wwww
    -15,   // b.wwww
    -24,   // w.wwww
    9,     // .bwwww
    -2,    // bbwwww
    -9,    // wbwwww
    -6,    // .wwwww
    2,     // bwwwww
    7,     // wwwwww
    2,     // ccc
    2,     // cc
    9,     // c
    16,    // ttt
    -10,   // tt
    33,    // t
    -3,    // ct
    -6,    // cct
    -24,   // ctt
].into_boxed_slice()
