vec![
    0,     // ......
    -2,    // b.....
    2,     // w.....
    -2,    // .b....
    4,     // bb....
    -18,   // wb....
    2,     // .w....
    18,    // bw....
    -4,    // ww....
    -20,   // ..b...
    -12,   // b.b...
    -2,    // w.b...
    2,     // .bb...
    26,    // bbb...
    8,     // wbb...
    14,    // .wb...
    4,     // bwb...
    4,     // wwb...
    20,    // ..w...
    2,     // b.w...
    12,    // w.w...
    -14,   // .bw...
    -4,    // bbw...
    -4,    // wbw...
    -2,    // .ww...
    -8,    // bww...
    -26,   // www...
    -20,   // ...b..
    -22,   // b..b..
    2,     // w..b..
    -14,   // .b.b..
    18,    // bb.b..
    8,     // wb.b..
    10,    // .w.b..
    -8,    // bw.b..
    -6,    // ww.b..
    -36,   // ..bb..
    12,    // b.bb..
    -14,   // w.bb..
    18,    // .bbb..
    -6,    // bbbb..
    -18,   // wbbb..
    -20,   // .wbb..
    6,     // bwbb..
    0,     // wwbb..
    0,     // ..wb..
    -22,   // b.wb..
    4,     // w.wb..
    -6,    // .bwb..
    12,    // bbwb..
    18,    // wbwb..
    0,     // .wwb..
    18,    // bwwb..
    30,    // wwwb..
    20,    // ...w..
    -2,    // b..w..
    22,    // w..w..
    -10,   // .b.w..
    6,     // bb.w..
    8,     // wb.w..
    14,    // .w.w..
    -8,    // bw.w..
    -18,   // ww.w..
    0,     // ..bw..
    -4,    // b.bw..
    22,    // w.bw..
    0,     // .bbw..
    -30,   // bbbw..
    -18,   // wbbw..
    6,     // .wbw..
    -18,   // bwbw..
    -12,   // wwbw..
    36,    // ..ww..
    14,    // b.ww..
    -12,   // w.ww..
    20,    // .bww..
    0,     // bbww..
    -6,    // wbww..
    -18,   // .www..
    18,    // bwww..
    6,     // wwww..
    -2,    // ....b.
    -20,   // b...b.
    -2,    // w...b.
    28,    // .b..b.
    -4,    // bb..b.
    20,    // wb..b.
    0,     // .w..b.
    -28,   // bw..b.
    30,    // ww..b.
    -14,   // ..b.b.
    22,    // b.b.b.
    8,     // w.b.b.
    14,    // .bb.b.
    12,    // bbb.b.
    -4,    // wbb.b.
    -22,   // .wb.b.
    -2,    // bwb.b.
    -20,   // wwb.b.
    -10,   // ..w.b.
    -30,   // b.w.b.
    -18,   // w.w.b.
    4,     // .bw.b.
    -4,    // bbw.b.
    14,    // wbw.b.
    -14,   // .ww.b.
    20,    // bww.b.
    -24,   // www.b.
    2,     // ...bb.
    -12,   // b..bb.
    -2,    // w..bb.
    14,    // .b.bb.
    0,     // bb.bb.
    -4,    // wb.bb.
    14,    // .w.bb.
    -14,   // bw.bb.
    -14,   // ww.bb.
    18,    // ..bbb.
    14,    // b.bbb.
    22,    // w.bbb.
    32,    // .bbbb.
    6,     // bbbbb.
    24,    // wbbbb.
    -8,    // .wbbb.
    18,    // bwbbb.
    36,    // wwbbb.
    0,     // ..wbb.
    2,     // b.wbb.
    -28,   // w.wbb.
    -24,   // .bwbb.
    -22,   // bbwbb.
    14,    // wbwbb.
    0,     // .wwbb.
    -12,   // bwwbb.
    12,    // wwwbb.
    -14,   // ...wb.
    -46,   // b..wb.
    -30,   // w..wb.
    4,     // .b.wb.
    -34,   // bb.wb.
    -12,   // wb.wb.
    22,    // .w.wb.
    -4,    // bw.wb.
    -12,   // ww.wb.
    -6,    // ..bwb.
    -14,   // b.bwb.
    16,    // w.bwb.
    -24,   // .bbwb.
    -32,   // bbbwb.
    14,    // wbbwb.
    0,     // .wbwb.
    -28,   // bwbwb.
    -14,   // wwbwb.
    20,    // ..wwb.
    -18,   // b.wwb.
    -20,   // w.wwb.
    28,    // .bwwb.
    -26,   // bbwwb.
    -14,   // wbwwb.
    8,     // .wwwb.
    -12,   // bwwwb.
    50,    // wwwwb.
    2,     // ....w.
    2,     // b...w.
    20,    // w...w.
    0,     // .b..w.
    -30,   // bb..w.
    28,    // wb..w.
    -28,   // .w..w.
    -20,   // bw..w.
    4,     // ww..w.
    10,    // ..b.w.
    18,    // b.b.w.
    30,    // w.b.w.
    14,    // .bb.w.
    24,    // bbb.w.
    -20,   // wbb.w.
    -4,    // .wb.w.
    -14,   // bwb.w.
    4,     // wwb.w.
    14,    // ..w.w.
    -8,    // b.w.w.
    -22,   // w.w.w.
    22,    // .bw.w.
    20,    // bbw.w.
    2,     // wbw.w.
    -14,   // .ww.w.
    4,     // bww.w.
    -12,   // www.w.
    14,    // ...bw.
    30,    // b..bw.
    46,    // w..bw.
    -22,   // .b.bw.
    12,    // bb.bw.
    4,     // wb.bw.
    -4,    // .w.bw.
    12,    // bw.bw.
    34,    // ww.bw.
    -20,   // ..bbw.
    20,    // b.bbw.
    18,    // w.bbw.
    -8,    // .bbbw.
    -50,   // bbbbw.
    12,    // wbbbw.
    -28,   // .wbbw.
    14,    // bwbbw.
    26,    // wwbbw.
    6,     // ..wbw.
    -16,   // b.wbw.
    14,    // w.wbw.
    0,     // .bwbw.
    14,    // bbwbw.
    28,    // wbwbw.
    24,    // .wwbw.
    -14,   // bwwbw.
    32,    // wwwbw.
    -2,    // ...ww.
    2,     // b..ww.
    12,    // w..ww.
    -14,   // .b.ww.
    14,    // bb.ww.
    14,    // wb.ww.
    -14,   // .w.ww.
    4,     // bw.ww.
    0,     // ww.ww.
    0,     // ..bww.
    28,    // b.bww.
    -2,    // w.bww.
    0,     // .bbww.
    -12,   // bbbww.
    12,    // wbbww.
    24,    // .wbww.
    -14,   // bwbww.
    22,    // wwbww.
    -18,   // ..www.
    -22,   // b.www.
    -14,   // w.www.
    8,     // .bwww.
    -36,   // bbwww.
    -18,   // wbwww.
    -32,   // .wwww.
    -24,   // bwwww.
    -6,    // wwwww.
    -2,    // .....b
    -8,    // b....b
    0,     // w....b
    -20,   // .b...b
    34,    // bb...b
    10,    // wb...b
    2,     // .w...b
    20,    // bw...b
    0,     // ww...b
    -22,   // ..b..b
    22,    // b.b..b
    -22,   // w.b..b
    -12,   // .bb..b
    -32,   // bbb..b
    2,     // wbb..b
    30,    // .wb..b
    -16,   // bwb..b
    20,    // wwb..b
    -2,    // ..w..b
    -2,    // b.w..b
    0,     // w.w..b
    -46,   // .bw..b
    18,    // bbw..b
    -34,   // wbw..b
    2,     // .ww..b
    2,     // bww..b
    2,     // www..b
    -12,   // ...b.b
    22,    // b..b.b
    0,     // w..b.b
    22,    // .b.b.b
    6,     // bb.b.b
    -30,   // wb.b.b
    18,    // .w.b.b
    0,     // bw.b.b
    -26,   // ww.b.b
    12,    // ..bb.b
    48,    // b.bb.b
    36,    // w.bb.b
    14,    // .bbb.b
    14,    // bbbb.b
    -22,   // wbbb.b
    20,    // .wbb.b
    4,     // bwbb.b
    -14,   // wwbb.b
    -4,    // ..wb.b
    -10,   // b.wb.b
    0,     // w.wb.b
    -14,   // .bwb.b
    6,     // bbwb.b
    24,    // wbwb.b
    28,    // .wwb.b
    -4,    // bwwb.b
    -18,   // wwwb.b
    2,     // ...w.b
    -2,    // b..w.b
    22,    // w..w.b
    -30,   // .b.w.b
    28,    // bb.w.b
    46,    // wb.w.b
    -8,    // .w.w.b
    0,     // bw.w.b
    24,    // ww.w.b
    -22,   // ..bw.b
    -10,   // b.bw.b
    0,     // w.bw.b
    2,     // .bbw.b
    14,    // bbbw.b
    40,    // wbbw.b
    -16,   // .wbw.b
    6,     // bwbw.b
    -8,    // wwbw.b
    14,    // ..ww.b
    24,    // b.ww.b
    -36,   // w.ww.b
    -18,   // .bww.b
    -24,   // bbww.b
    8,     // wbww.b
    -22,   // .www.b
    34,    // bwww.b
    -12,   // wwww.b
    4,     // ....bb
    34,    // b...bb
    0,     // w...bb
    -4,    // .b..bb
    32,    // bb..bb
    -2,    // wb..bb
    -30,   // .w..bb
    -6,    // bw..bb
    0,     // ww..bb
    18,    // ..b.bb
    6,     // b.b.bb
    -24,   // w.b.bb
    0,     // .bb.bb
    10,    // bbb.bb
    -4,    // wbb.bb
    12,    // .wb.bb
    2,     // bwb.bb
    36,    // wwb.bb
    6,     // ..w.bb
    28,    // b.w.bb
    26,    // w.w.bb
    -34,   // .bw.bb
    22,    // bbw.bb
    32,    // wbw.bb
    14,    // .ww.bb
    2,     // bww.bb
    -12,   // www.bb
    26,    // ...bbb
    -32,   // b..bbb
    -2,    // w..bbb
    12,    // .b.bbb
    10,    // bb.bbb
    -22,   // wb.bbb
    24,    // .w.bbb
    -40,   // bw.bbb
    12,    // ww.bbb
    -6,    // ..bbbb
    14,    // b.bbbb
    12,    // w.bbbb
    6,     // .bbbbb
    0,     // bbbbbb
    8,     // wbbbbb
    -50,   // .wbbbb
    8,     // bwbbbb
    20,    // wwbbbb
    -30,   // ..wbbb
    14,    // b.wbbb
    18,    // w.wbbb
    -32,   // .bwbbb
    30,    // bbwbbb
    -10,   // wbwbbb
    -12,   // .wwbbb
    -10,   // bwwbbb
    0,     // wwwbbb
    -4,    // ...wbb
    18,    // b..wbb
    -20,   // w..wbb
    -4,    // .b.wbb
    22,    // bb.wbb
    28,    // wb.wbb
    20,    // .w.wbb
    -30,   // bw.wbb
    -36,   // ww.wbb
    12,    // ..bwbb
    6,     // b.bwbb
    8,     // w.bwbb
    -22,   // .bbwbb
    30,    // bbbwbb
    14,    // wbbwbb
    14,    // .wbwbb
    -18,   // bwbwbb
    0,     // wwbwbb
    0,     // ..wwbb
    -24,   // b.wwbb
    14,    // w.wwbb
    -26,   // .bwwbb
    16,    // bbwwbb
    32,    // wbwwbb
    -36,   // .wwwbb
    20,    // bwwwbb
    -20,   // wwwwbb
    18,    // ....wb
    20,    // b...wb
    -10,   // w...wb
    -28,   // .b..wb
    -6,    // bb..wb
    0,     // wb..wb
    -20,   // .w..wb
    16,    // bw..wb
    2,     // ww..wb
    -8,    // ..b.wb
    0,     // b.b.wb
    -46,   // w.b.wb
    -14,   // .bb.wb
    -40,   // bbb.wb
    -14,   // wbb.wb
    12,    // .wb.wb
    4,     // bwb.wb
    -28,   // wwb.wb
    -8,    // ..w.wb
    0,     // b.w.wb
    30,    // w.w.wb
    -4,    // .bw.wb
    -30,   // bbw.wb
    18,    // wbw.wb
    4,     // .ww.wb
    24,    // bww.wb
    22,    // www.wb
    4,     // ...bwb
    -16,   // b..bwb
    34,    // w..bwb
    -2,    // .b.bwb
    2,     // bb.bwb
    -18,   // wb.bwb
    -14,   // .w.bwb
    4,     // bw.bwb
    -32,   // ww.bwb
    6,     // ..bbwb
    4,     // b.bbwb
    -8,    // w.bbwb
    18,    // .bbbwb
    8,     // bbbbwb
    -2,    // wbbbwb
    14,    // .wbbwb
    24,    // bwbbwb
    -32,   // wwbbwb
    -18,   // ..wbwb
    6,     // b.wbwb
    -24,   // w.wbwb
    -28,   // .bwbwb
    -18,   // bbwbwb
    0,     // wbwbwb
    -14,   // .wwbwb
    -26,   // bwwbwb
    10,    // wwwbwb
    -8,    // ...wwb
    2,     // b..wwb
    -2,    // w..wwb
    20,    // .b.wwb
    2,     // bb.wwb
    14,    // wb.wwb
    4,     // .w.wwb
    24,    // bw.wwb
    4,     // ww.wwb
    18,    // ..bwwb
    -4,    // b.bwwb
    -40,   // w.bwwb
    -12,   // .bbwwb
    -10,   // bbbwwb
    0,     // wbbwwb
    -14,   // .wbwwb
    -26,   // bwbwwb
    -14,   // wwbwwb
    18,    // ..wwwb
    34,    // b.wwwb
    22,    // w.wwwb
    -12,   // .bwwwb
    20,    // bbwwwb
    2,     // wbwwwb
    -24,   // .wwwwb
    52,    // bwwwwb
    -8,    // wwwwwb
    2,     // .....w
    0,     // b....w
    8,     // w....w
    -2,    // .b...w
    0,     // bb...w
    -20,   // wb...w
    20,    // .w...w
    -10,   // bw...w
    -34,   // ww...w
    2,     // ..b..w
    0,     // b.b..w
    2,     // w.b..w
    -2,    // .bb..w
    -2,    // bbb..w
    -2,    // wbb..w
    46,    // .wb..w
    34,    // bwb..w
    -18,   // wwb..w
    22,    // ..w..w
    22,    // b.w..w
    -22,   // w.w..w
    -30,   // .bw..w
    -20,   // bbw..w
    16,    // wbw..w
    12,    // .ww..w
    -2,    // bww..w
    32,    // www..w
    -2,    // ...b.w
    -22,   // b..b.w
    2,     // w..b.w
    8,     // .b.b.w
    -24,   // bb.b.w
    0,     // wb.b.w
    30,    // .w.b.w
    -46,   // bw.b.w
    -28,   // ww.b.w
    -14,   // ..bb.w
    36,    // b.bb.w
    -24,   // w.bb.w
    22,    // .bbb.w
    12,    // bbbb.w
    -34,   // wbbb.w
    18,    // .wbb.w
    -8,    // bwbb.w
    24,    // wwbb.w
    22,    // ..wb.w
    0,     // b.wb.w
    10,    // w.wb.w
    16,    // .bwb.w
    8,     // bbwb.w
    -6,    // wbwb.w
    -2,    // .wwb.w
    -40,   // bwwb.w
    -14,   // wwwb.w
    12,    // ...w.w
    0,     // b..w.w
    -22,   // w..w.w
    -18,   // .b.w.w
    26,    // bb.w.w
    0,     // wb.w.w
    -22,   // .w.w.w
    30,    // bw.w.w
    -6,    // ww.w.w
    4,     // ..bw.w
    0,     // b.bw.w
    10,    // w.bw.w
    -28,   // .bbw.w
    18,    // bbbw.w
    4,     // wbbw.w
    14,    // .wbw.w
    -24,   // bwbw.w
    -6,    // wwbw.w
    -12,   // ..ww.w
    -36,   // b.ww.w
    -48,   // w.ww.w
    -20,   // .bww.w
    14,    // bbww.w
    -4,    // wbww.w
    -14,   // .www.w
    22,    // bwww.w
    -14,   // wwww.w
    -18,   // ....bw
    10,    // b...bw
    -20,   // w...bw
    20,    // .b..bw
    -2,    // bb..bw
    -16,   // wb..bw
    28,    // .w..bw
    0,     // bw..bw
    6,     // ww..bw
    8,     // ..b.bw
    -30,   // b.b.bw
    0,     // w.b.bw
    -4,    // .bb.bw
    -22,   // bbb.bw
    -24,   // wbb.bw
    4,     // .wb.bw
    -18,   // bwb.bw
    30,    // wwb.bw
    8,     // ..w.bw
    46,    // b.w.bw
    0,     // w.w.bw
    -12,   // .bw.bw
    28,    // bbw.bw
    -4,    // wbw.bw
    14,    // .ww.bw
    14,    // bww.bw
    40,    // www.bw
    8,     // ...bbw
    2,     // b..bbw
    -2,    // w..bbw
    -4,    // .b.bbw
    -4,    // bb.bbw
    -24,   // wb.bbw
    -20,   // .w.bbw
    -14,   // bw.bbw
    -2,    // ww.bbw
    -18,   // ..bbbw
    -22,   // b.bbbw
    -34,   // w.bbbw
    24,    // .bbbbw
    8,     // bbbbbw
    -52,   // wbbbbw
    12,    // .wbbbw
    -2,    // bwbbbw
    -20,   // wwbbbw
    -18,   // ..wbbw
    40,    // b.wbbw
    4,     // w.wbbw
    14,    // .bwbbw
    14,    // bbwbbw
    26,    // wbwbbw
    12,    // .wwbbw
    0,     // bwwbbw
    10,    // wwwbbw
    -4,    // ...wbw
    -34,   // b..wbw
    16,    // w..wbw
    14,    // .b.wbw
    32,    // bb.wbw
    -4,    // wb.wbw
    2,     // .w.wbw
    18,    // bw.wbw
    -2,    // ww.wbw
    18,    // ..bwbw
    24,    // b.bwbw
    -6,    // w.bwbw
    14,    // .bbwbw
    -10,   // bbbwbw
    26,    // wbbwbw
    28,    // .wbwbw
    0,     // bwbwbw
    18,    // wwbwbw
    -6,    // ..wwbw
    8,     // b.wwbw
    -4,    // w.wwbw
    -14,   // .bwwbw
    32,    // bbwwbw
    -24,   // wbwwbw
    -18,   // .wwwbw
    2,     // bwwwbw
    -8,    // wwwwbw
    -4,    // ....ww
    0,     // b...ww
    -34,   // w...ww
    30,    // .b..ww
    0,     // bb..ww
    6,     // wb..ww
    4,     // .w..ww
    2,     // bw..ww
    -32,   // ww..ww
    -6,    // ..b.ww
    -26,   // b.b.ww
    -28,   // w.b.ww
    -14,   // .bb.ww
    12,    // bbb.ww
    -2,    // wbb.ww
    34,    // .wb.ww
    -32,   // bwb.ww
    -22,   // wwb.ww
    -18,   // ..w.ww
    24,    // b.w.ww
    -6,    // w.w.ww
    -12,   // .bw.ww
    -36,   // bbw.ww
    -2,    // wbw.ww
    0,     // .ww.ww
    4,     // bww.ww
    -10,   // www.ww
    4,     // ...bww
    20,    // b..bww
    -18,   // w..bww
    -20,   // .b.bww
    36,    // bb.bww
    30,    // wb.bww
    4,     // .w.bww
    -28,   // bw.bww
    -22,   // ww.bww
    0,     // ..bbww
    -14,   // b.bbww
    24,    // w.bbww
    36,    // .bbbww
    20,    // bbbbww
    -20,   // wbbbww
    26,    // .wbbww
    -32,   // bwbbww
    -16,   // wwbbww
    -12,   // ..wbww
    -8,    // b.wbww
    -6,    // w.wbww
    -14,   // .bwbww
    0,     // bbwbww
    18,    // wbwbww
    22,    // .wwbww
    -14,   // bwwbww
    -30,   // wwwbww
    -26,   // ...www
    2,     // b..www
    32,    // w..www
    -24,   // .b.www
    -12,   // bb.www
    40,    // wb.www
    -12,   // .w.www
    22,    // bw.www
    -10,   // ww.www
    30,    // ..bwww
    -18,   // b.bwww
    -14,   // w.bwww
    12,    // .bbwww
    0,     // bbbwww
    10,    // wbbwww
    32,    // .wbwww
    10,    // bwbwww
    -30,   // wwbwww
    6,     // ..wwww
    -12,   // b.wwww
    -14,   // w.wwww
    50,    // .bwwww
    -20,   // bbwwww
    -8,    // wbwwww
    -6,    // .wwwww
    -8,    // bwwwww
    0,     // wwwwww
    -16,   // ccc
    32,    // cc
    4,     // c
    6,     // ttt
    2,     // tt
    14,    // t
    -14,   // ct
    18,    // cct
    -10,   // ctt
].into_boxed_slice()
