vec![
    0,     // .......
    0,     // b......
    0,     // w......
    -8,    // .b.....
    6,     // bb.....
    5,     // wb.....
    8,     // .w.....
    -5,    // bw.....
    -6,    // ww.....
    -2,    // ..b....
    -14,   // b.b....
    0,     // w.b....
    -6,    // .bb....
    38,    // bbb....
    -18,   // wbb....
    -20,   // .wb....
    -20,   // bwb....
    20,    // wwb....
    2,     // ..w....
    0,     // b.w....
    14,    // w.w....
    20,    // .bw....
    -20,   // bbw....
    20,    // wbw....
    6,     // .ww....
    18,    // bww....
    -38,   // www....
    2,     // ...b...
    9,     // b..b...
    -19,   // w..b...
    2,     // .b.b...
    -2,    // bb.b...
    18,    // wb.b...
    -3,    // .w.b...
    4,     // bw.b...
    8,     // ww.b...
    -14,   // ..bb...
    11,    // b.bb...
    15,    // w.bb...
    13,    // .bbb...
    7,     // bbbb...
    5,     // wbbb...
    -8,    // .wbb...
    26,    // bwbb...
    17,    // wwbb...
    -2,    // ..wb...
    10,    // b.wb...
    3,     // w.wb...
    -6,    // .bwb...
    -13,   // bbwb...
    -16,   // wbwb...
    -7,    // .wwb...
    -1,    // bwwb...
    11,    // wwwb...
    -2,    // ...w...
    19,    // b..w...
    -9,    // w..w...
    3,     // .b.w...
    -8,    // bb.w...
    -4,    // wb.w...
    -2,    // .w.w...
    -18,   // bw.w...
    2,     // ww.w...
    2,     // ..bw...
    -3,    // b.bw...
    -10,   // w.bw...
    7,     // .bbw...
    -11,   // bbbw...
    1,     // wbbw...
    6,     // .wbw...
    16,    // bwbw...
    13,    // wwbw...
    14,    // ..ww...
    -15,   // b.ww...
    -11,   // w.ww...
    8,     // .bww...
    -17,   // bbww...
    -26,   // wbww...
    -13,   // .www...
    -5,    // bwww...
    -7,    // wwww...
    -2,    // ....b..
    -19,   // b...b..
    10,    // w...b..
    -12,   // .b..b..
    8,     // bb..b..
    0,     // wb..b..
    2,     // .w..b..
    8,     // bw..b..
    -3,    // ww..b..
    -8,    // ..b.b..
    -11,   // b.b.b..
    -3,    // w.b.b..
    3,     // .bb.b..
    1,     // bbb.b..
    2,     // wbb.b..
    -6,    // .wb.b..
    9,     // bwb.b..
    -1,    // wwb.b..
    0,     // ..w.b..
    -22,   // b.w.b..
    7,     // w.w.b..
    -9,    // .bw.b..
    -18,   // bbw.b..
    3,     // wbw.b..
    10,    // .ww.b..
    0,     // bww.b..
    7,     // www.b..
    -14,   // ...bb..
    -17,   // b..bb..
    9,     // w..bb..
    -13,   // .b.bb..
    -13,   // bb.bb..
    -5,    // wb.bb..
    6,     // .w.bb..
    8,     // bw.bb..
    2,     // ww.bb..
    3,     // ..bbb..
    -7,    // b.bbb..
    13,    // w.bbb..
    20,    // .bbbb..
    12,    // bbbbb..
    24,    // wbbbb..
    -1,    // .wbbb..
    1,     // bwbbb..
    -10,   // wwbbb..
    -9,    // ..wbb..
    -6,    // b.wbb..
    -10,   // w.wbb..
    5,     // .bwbb..
    10,    // bbwbb..
    12,    // wbwbb..
    0,     // .wwbb..
    14,    // bwwbb..
    13,    // wwwbb..
    2,     // ...wb..
    -9,    // b..wb..
    3,     // w..wb..
    1,     // .b.wb..
    -10,   // bb.wb..
    29,    // wb.wb..
    -7,    // .w.wb..
    4,     // bw.wb..
    0,     // ww.wb..
    15,    // ..bwb..
    0,     // b.bwb..
    5,     // w.bwb..
    -3,    // .bbwb..
    -3,    // bbbwb..
    12,    // wbbwb..
    6,     // .wbwb..
    -1,    // bwbwb..
    -7,    // wwbwb..
    9,     // ..wwb..
    17,    // b.wwb..
    -5,    // w.wwb..
    3,     // .bwwb..
    4,     // bbwwb..
    -11,   // wbwwb..
    5,     // .wwwb..
    -6,    // bwwwb..
    21,    // wwwwb..
    2,     // ....w..
    -10,   // b...w..
    19,    // w...w..
    -2,    // .b..w..
    3,     // bb..w..
    -8,    // wb..w..
    12,    // .w..w..
    0,     // bw..w..
    -8,    // ww..w..
    0,     // ..b.w..
    -7,    // b.b.w..
    22,    // w.b.w..
    -10,   // .bb.w..
    -7,    // bbb.w..
    0,     // wbb.w..
    9,     // .wb.w..
    -3,    // bwb.w..
    18,    // wwb.w..
    8,     // ..w.w..
    3,     // b.w.w..
    11,    // w.w.w..
    6,     // .bw.w..
    1,     // bbw.w..
    -9,    // wbw.w..
    -3,    // .ww.w..
    -2,    // bww.w..
    -1,    // www.w..
    -2,    // ...bw..
    -3,    // b..bw..
    9,     // w..bw..
    7,     // .b.bw..
    0,     // bb.bw..
    -4,    // wb.bw..
    -1,    // .w.bw..
    -29,   // bw.bw..
    10,    // ww.bw..
    -9,    // ..bbw..
    5,     // b.bbw..
    -17,   // w.bbw..
    -5,    // .bbbw..
    -21,   // bbbbw..
    6,     // wbbbw..
    -3,    // .wbbw..
    11,    // bwbbw..
    -4,    // wwbbw..
    -15,   // ..wbw..
    -5,    // b.wbw..
    0,     // w.wbw..
    -6,    // .bwbw..
    7,     // bbwbw..
    1,     // wbwbw..
    3,     // .wwbw..
    -12,   // bwwbw..
    3,     // wwwbw..
    14,    // ...ww..
    -9,    // b..ww..
    17,    // w..ww..
    -6,    // .b.ww..
    -2,    // bb.ww..
    -8,    // wb.ww..
    13,    // .w.ww..
    5,     // bw.ww..
    13,    // ww.ww..
    9,     // ..bww..
    10,    // b.bww..
    6,     // w.bww..
    0,     // .bbww..
    -13,   // bbbww..
    -14,   // wbbww..
    -5,    // .wbww..
    -12,   // bwbww..
    -10,   // wwbww..
    -3,    // ..www..
    -13,   // b.www..
    7,     // w.www..
    1,     // .bwww..
    10,    // bbwww..
    -1,    // wbwww..
    -20,   // .wwww..
    -24,   // bwwww..
    -12,   // wwwww..
    -8,    // .....b.
    -10,   // b....b.
    -20,   // w....b.
    -12,   // .b...b.
    14,    // bb...b.
    -13,   // wb...b.
    0,     // .w...b.
    -16,   // bw...b.
    -11,   // ww...b.
    -12,   // ..b..b.
    -3,    // b.b..b.
    -7,    // w.b..b.
    -4,    // .bb..b.
    3,     // bbb..b.
    6,     // wbb..b.
    -7,    // .wb..b.
    4,     // bwb..b.
    4,     // wwb..b.
    -2,    // ..w..b.
    -6,    // b.w..b.
    -17,   // w.w..b.
    -14,   // .bw..b.
    5,     // bbw..b.
    -32,   // wbw..b.
    5,     // .ww..b.
    13,    // bww..b.
    -2,    // www..b.
    2,     // ...b.b.
    -8,    // b..b.b.
    -5,    // w..b.b.
    4,     // .b.b.b.
    12,    // bb.b.b.
    -1,    // wb.b.b.
    -9,    // .w.b.b.
    -19,   // bw.b.b.
    -12,   // ww.b.b.
    -13,   // ..bb.b.
    12,    // b.bb.b.
    -18,   // w.bb.b.
    8,     // .bbb.b.
    -11,   // bbbb.b.
    -1,    // wbbb.b.
    -11,   // .wbb.b.
    5,     // bwbb.b.
    -12,   // wwbb.b.
    7,     // ..wb.b.
    5,     // b.wb.b.
    -1,    // w.wb.b.
    -15,   // .bwb.b.
    -20,   // bbwb.b.
    -4,    // wbwb.b.
    -8,    // .wwb.b.
    9,     // bwwb.b.
    -5,    // wwwb.b.
    3,     // ...w.b.
    -4,    // b..w.b.
    -3,    // w..w.b.
    8,     // .b.w.b.
    -11,   // bb.w.b.
    8,     // wb.w.b.
    9,     // .w.w.b.
    -21,   // bw.w.b.
    4,     // ww.w.b.
    1,     // ..bw.b.
    -15,   // b.bw.b.
    4,     // w.bw.b.
    4,     // .bbw.b.
    -4,    // bbbw.b.
    4,     // wbbw.b.
    8,     // .wbw.b.
    13,    // bwbw.b.
    9,     // wwbw.b.
    -6,    // ..ww.b.
    4,     // b.ww.b.
    -17,   // w.ww.b.
    -3,    // .bww.b.
    19,    // bbww.b.
    7,     // wbww.b.
    -9,    // .www.b.
    12,    // bwww.b.
    -3,    // wwww.b.
    -6,    // ....bb.
    20,    // b...bb.
    -2,    // w...bb.
    -4,    // .b..bb.
    1,     // bb..bb.
    -4,    // wb..bb.
    -5,    // .w..bb.
    9,     // bw..bb.
    -3,    // ww..bb.
    3,     // ..b.bb.
    2,     // b.b.bb.
    17,    // w.b.bb.
    -8,    // .bb.bb.
    -14,   // bbb.bb.
    -3,    // wbb.bb.
    1,     // .wb.bb.
    -2,    // bwb.bb.
    1,     // wwb.bb.
    -10,   // ..w.bb.
    -6,    // b.w.bb.
    -17,   // w.w.bb.
    1,     // .bw.bb.
    11,    // bbw.bb.
    3,     // wbw.bb.
    0,     // .ww.bb.
    -17,   // bww.bb.
    -10,   // www.bb.
    13,    // ...bbb.
    8,     // b..bbb.
    -3,    // w..bbb.
    8,     // .b.bbb.
    19,    // bb.bbb.
    2,     // wb.bbb.
    9,     // .w.bbb.
    -6,    // bw.bbb.
    -9,    // ww.bbb.
    20,    // ..bbbb.
    -9,    // b.bbbb.
    16,    // w.bbbb.
    18,    // .bbbbb.
    25,    // bbbbbb.
    -8,    // wbbbbb.
    6,     // .wbbbb.
    -18,   // bwbbbb.
    1,     // wwbbbb.
    -5,    // ..wbbb.
    -4,    // b.wbbb.
    4,     // w.wbbb.
    1,     // .bwbbb.
    2,     // bbwbbb.
    -10,   // wbwbbb.
    11,    // .wwbbb.
    4,     // bwwbbb.
    9,     // wwwbbb.
    7,     // ...wbb.
    -14,   // b..wbb.
    -3,    // w..wbb.
    4,     // .b.wbb.
    8,     // bb.wbb.
    -2,    // wb.wbb.
    8,     // .w.wbb.
    -6,    // bw.wbb.
    8,     // ww.wbb.
    -3,    // ..bwbb.
    5,     // b.bwbb.
    6,     // w.bwbb.
    -9,    // .bbwbb.
    0,     // bbbwbb.
    -9,    // wbbwbb.
    13,    // .wbwbb.
    -10,   // bwbwbb.
    11,    // wwbwbb.
    0,     // ..wwbb.
    3,     // b.wwbb.
    7,     // w.wwbb.
    -18,   // .bwwbb.
    -18,   // bbwwbb.
    2,     // wbwwbb.
    -11,   // .wwwbb.
    -5,    // bwwwbb.
    -2,    // wwwwbb.
    20,    // ....wb.
    7,     // b...wb.
    -4,    // w...wb.
    -14,   // .b..wb.
    2,     // bb..wb.
    -16,   // wb..wb.
    7,     // .w..wb.
    9,     // bw..wb.
    -3,    // ww..wb.
    -9,    // ..b.wb.
    -8,    // b.b.wb.
    -11,   // w.b.wb.
    1,     // .bb.wb.
    0,     // bbb.wb.
    19,    // wbb.wb.
    0,     // .wb.wb.
    -5,    // bwb.wb.
    4,     // wwb.wb.
    6,     // ..w.wb.
    7,     // b.w.wb.
    2,     // w.w.wb.
    14,    // .bw.wb.
    6,     // bbw.wb.
    -7,    // wbw.wb.
    -1,    // .ww.wb.
    10,    // bww.wb.
    -10,   // www.wb.
    -6,    // ...bwb.
    16,    // b..bwb.
    7,     // w..bwb.
    -15,   // .b.bwb.
    2,     // bb.bwb.
    24,    // wb.bwb.
    -8,    // .w.bwb.
    -6,    // bw.bwb.
    6,     // ww.bwb.
    5,     // ..bbwb.
    13,    // b.bbwb.
    -17,   // w.bbwb.
    1,     // .bbbwb.
    -4,    // bbbbwb.
    -13,   // wbbbwb.
    -18,   // .wbbwb.
    5,     // bwbbwb.
    -5,    // wwbbwb.
    -6,    // ..wbwb.
    -8,    // b.wbwb.
    26,    // w.wbwb.
    4,     // .bwbwb.
    8,     // bbwbwb.
    7,     // wbwbwb.
    -13,   // .wwbwb.
    8,     // bwwbwb.
    4,     // wwwbwb.
    8,     // ...wwb.
    -1,    // b..wwb.
    2,     // w..wwb.
    -3,    // .b.wwb.
    7,     // bb.wwb.
    2,     // wb.wwb.
    11,    // .w.wwb.
    2,     // bw.wwb.
    -7,    // ww.wwb.
    3,     // ..bwwb.
    23,    // b.bwwb.
    21,    // w.bwwb.
    -18,   // .bbwwb.
    1,     // bbbwwb.
    6,     // wbbwwb.
    18,    // .wbwwb.
    11,    // bwbwwb.
    4,     // wwbwwb.
    1,     // ..wwwb.
    -7,    // b.wwwb.
    11,    // w.wwwb.
    17,    // .bwwwb.
    -11,   // bbwwwb.
    15,    // wbwwwb.
    -6,    // .wwwwb.
    -3,    // bwwwwb.
    14,    // wwwwwb.
    8,     // .....w.
    20,    // b....w.
    10,    // w....w.
    0,     // .b...w.
    11,    // bb...w.
    16,    // wb...w.
    12,    // .w...w.
    13,    // bw...w.
    -14,   // ww...w.
    2,     // ..b..w.
    17,    // b.b..w.
    6,     // w.b..w.
    -5,    // .bb..w.
    2,     // bbb..w.
    -13,   // wbb..w.
    14,    // .wb..w.
    32,    // bwb..w.
    -5,    // wwb..w.
    12,    // ..w..w.
    7,     // b.w..w.
    3,     // w.w..w.
    7,     // .bw..w.
    -4,    // bbw..w.
    -4,    // wbw..w.
    4,     // .ww..w.
    -6,    // bww..w.
    -3,    // www..w.
    -3,    // ...b.w.
    3,     // b..b.w.
    4,     // w..b.w.
    -9,    // .b.b.w.
    -4,    // bb.b.w.
    21,    // wb.b.w.
    -8,    // .w.b.w.
    -8,    // bw.b.w.
    11,    // ww.b.w.
    6,     // ..bb.w.
    17,    // b.bb.w.
    -4,    // w.bb.w.
    9,     // .bbb.w.
    3,     // bbbb.w.
    -12,   // wbbb.w.
    3,     // .wbb.w.
    -7,    // bwbb.w.
    -19,   // wwbb.w.
    -1,    // ..wb.w.
    -4,    // b.wb.w.
    15,    // w.wb.w.
    -8,    // .bwb.w.
    -9,    // bbwb.w.
    -13,   // wbwb.w.
    -4,    // .wwb.w.
    -4,    // bwwb.w.
    4,     // wwwb.w.
    -2,    // ...w.w.
    5,     // b..w.w.
    8,     // w..w.w.
    9,     // .b.w.w.
    12,    // bb.w.w.
    19,    // wb.w.w.
    -4,    // .w.w.w.
    1,     // bw.w.w.
    -12,   // ww.w.w.
    -7,    // ..bw.w.
    1,     // b.bw.w.
    -5,    // w.bw.w.
    8,     // .bbw.w.
    5,     // bbbw.w.
    -9,    // wbbw.w.
    15,    // .wbw.w.
    4,     // bwbw.w.
    20,    // wwbw.w.
    13,    // ..ww.w.
    18,    // b.ww.w.
    -12,   // w.ww.w.
    11,    // .bww.w.
    12,    // bbww.w.
    -5,    // wbww.w.
    -8,    // .www.w.
    1,     // bwww.w.
    11,    // wwww.w.
    -20,   // ....bw.
    4,     // b...bw.
    -7,    // w...bw.
    -7,    // .b..bw.
    3,     // bb..bw.
    -9,    // wb..bw.
    14,    // .w..bw.
    16,    // bw..bw.
    -2,    // ww..bw.
    -6,    // ..b.bw.
    -2,    // b.b.bw.
    -7,    // w.b.bw.
    1,     // .bb.bw.
    10,    // bbb.bw.
    -10,   // wbb.bw.
    -14,   // .wb.bw.
    7,     // bwb.bw.
    -6,    // wwb.bw.
    9,     // ..w.bw.
    11,    // b.w.bw.
    8,     // w.w.bw.
    0,     // .bw.bw.
    -4,    // bbw.bw.
    5,     // wbw.bw.
    -1,    // .ww.bw.
    -19,   // bww.bw.
    0,     // www.bw.
    -8,    // ...bbw.
    -2,    // b..bbw.
    1,     // w..bbw.
    -11,   // .b.bbw.
    7,     // bb.bbw.
    -2,    // wb.bbw.
    3,     // .w.bbw.
    -2,    // bw.bbw.
    -7,    // ww.bbw.
    -1,    // ..bbbw.
    -11,   // b.bbbw.
    7,     // w.bbbw.
    6,     // .bbbbw.
    -14,   // bbbbbw.
    3,     // wbbbbw.
    -17,   // .wbbbw.
    -15,   // bwbbbw.
    11,    // wwbbbw.
    -3,    // ..wbbw.
    -21,   // b.wbbw.
    -23,   // w.wbbw.
    -18,   // .bwbbw.
    -4,    // bbwbbw.
    -11,   // wbwbbw.
    18,    // .wwbbw.
    -6,    // bwwbbw.
    -1,    // wwwbbw.
    6,     // ...wbw.
    -7,    // b..wbw.
    -16,   // w..wbw.
    8,     // .b.wbw.
    -6,    // bb.wbw.
    6,     // wb.wbw.
    15,    // .w.wbw.
    -24,   // bw.wbw.
    -2,    // ww.wbw.
    6,     // ..bwbw.
    -26,   // b.bwbw.
    8,     // w.bwbw.
    13,    // .bbwbw.
    -4,    // bbbwbw.
    -8,    // wbbwbw.
    -4,    // .wbwbw.
    -7,    // bwbwbw.
    -8,    // wwbwbw.
    -5,    // ..wwbw.
    17,    // b.wwbw.
    -13,   // w.wwbw.
    18,    // .bwwbw.
    5,     // bbwwbw.
    -5,    // wbwwbw.
    -1,    // .wwwbw.
    13,    // bwwwbw.
    4,     // wwwwbw.
    6,     // ....ww.
    2,     // b...ww.
    -20,   // w...ww.
    5,     // .b..ww.
    3,     // bb..ww.
    -9,    // wb..ww.
    4,     // .w..ww.
    4,     // bw..ww.
    -1,    // ww..ww.
    10,    // ..b.ww.
    17,    // b.b.ww.
    6,     // w.b.ww.
    0,     // .bb.ww.
    10,    // bbb.ww.
    17,    // wbb.ww.
    -1,    // .wb.ww.
    -3,    // bwb.ww.
    -11,   // wwb.ww.
    -3,    // ..w.ww.
    -17,   // b.w.ww.
    -2,    // w.w.ww.
    -1,    // .bw.ww.
    -1,    // bbw.ww.
    2,     // wbw.ww.
    8,     // .ww.ww.
    3,     // bww.ww.
    14,    // www.ww.
    -7,    // ...bww.
    3,     // b..bww.
    14,    // w..bww.
    -8,    // .b.bww.
    -8,    // bb.bww.
    6,     // wb.bww.
    -4,    // .w.bww.
    2,     // bw.bww.
    -8,    // ww.bww.
    0,     // ..bbww.
    -7,    // b.bbww.
    -3,    // w.bbww.
    11,    // .bbbww.
    2,     // bbbbww.
    5,     // wbbbww.
    18,    // .wbbww.
    -2,    // bwbbww.
    18,    // wwbbww.
    3,     // ..wbww.
    -6,    // b.wbww.
    -5,    // w.wbww.
    -13,   // .bwbww.
    -11,   // bbwbww.
    10,    // wbwbww.
    9,     // .wwbww.
    9,     // bwwbww.
    0,     // wwwbww.
    -13,   // ...www.
    3,     // b..www.
    -8,    // w..www.
    -9,    // .b.www.
    9,     // bb.www.
    6,     // wb.www.
    -8,    // .w.www.
    -2,    // bw.www.
    -19,   // ww.www.
    5,     // ..bwww.
    -4,    // b.bwww.
    4,     // w.bwww.
    -11,   // .bbwww.
    -9,    // bbbwww.
    -4,    // wbbwww.
    -1,    // .wbwww.
    10,    // bwbwww.
    -2,    // wwbwww.
    -20,   // ..wwww.
    -16,   // b.wwww.
    9,     // w.wwww.
    -6,    // .bwwww.
    -1,    // bbwwww.
    18,    // wbwwww.
    -18,   // .wwwww.
    8,     // bwwwww.
    -25,   // wwwwww.
    0,     // ......b
    -12,   // b.....b
    0,     // w.....b
    -10,   // .b....b
    11,    // bb....b
    -11,   // wb....b
    20,    // .w....b
    4,     // bw....b
    -1,    // ww....b
    -19,   // ..b...b
    6,     // b.b...b
    4,     // w.b...b
    20,    // .bb...b
    20,    // bbb...b
    -1,    // wbb...b
    4,     // .wb...b
    25,    // bwb...b
    -8,    // wwb...b
    -10,   // ..w...b
    -2,    // b.w...b
    8,     // w.w...b
    7,     // .bw...b
    0,     // bbw...b
    18,    // wbw...b
    2,     // .ww...b
    -9,    // bww...b
    -22,   // www...b
    9,     // ...b..b
    33,    // b..b..b
    18,    // w..b..b
    -8,    // .b.b..b
    -15,   // bb.b..b
    4,     // wb.b..b
    3,     // .w.b..b
    11,    // bw.b..b
    0,     // ww.b..b
    -17,   // ..bb..b
    -5,    // b.bb..b
    0,     // w.bb..b
    8,     // .bbb..b
    -29,   // bbbb..b
    9,     // wbbb..b
    -2,    // .wbb..b
    -10,   // bwbb..b
    0,     // wwbb..b
    -3,    // ..wb..b
    5,     // b.wb..b
    -4,    // w.wb..b
    16,    // .bwb..b
    -13,   // bbwb..b
    -10,   // wbwb..b
    3,     // .wwb..b
    -2,    // bwwb..b
    -8,    // wwwb..b
    19,    // ...w..b
    11,    // b..w..b
    -18,   // w..w..b
    -4,    // .b.w..b
    -30,   // bb.w..b
    -9,    // wb.w..b
    5,     // .w.w..b
    -2,    // bw.w..b
    5,     // ww.w..b
    -9,    // ..bw..b
    23,    // b.bw..b
    2,     // w.bw..b
    -14,   // .bbw..b
    7,     // bbbw..b
    -14,   // wbbw..b
    -7,    // .wbw..b
    -12,   // bwbw..b
    3,     // wwbw..b
    -9,    // ..ww..b
    -20,   // b.ww..b
    16,    // w.ww..b
    -1,    // .bww..b
    9,     // bbww..b
    -11,   // wbww..b
    3,     // .www..b
    3,     // bwww..b
    11,    // wwww..b
    -14,   // ....b.b
    6,     // b...b.b
    -8,    // w...b.b
    -3,    // .b..b.b
    1,     // bb..b.b
    3,     // wb..b.b
    17,    // .w..b.b
    -15,   // bw..b.b
    -8,    // ww..b.b
    -11,   // ..b.b.b
    3,     // b.b.b.b
    7,     // w.b.b.b
    2,     // .bb.b.b
    21,    // bbb.b.b
    1,     // wbb.b.b
    -2,    // .wb.b.b
    16,    // bwb.b.b
    -2,    // wwb.b.b
    -7,    // ..w.b.b
    13,    // b.w.b.b
    0,     // w.w.b.b
    -8,    // .bw.b.b
    -9,    // bbw.b.b
    1,     // wbw.b.b
    17,    // .ww.b.b
    -6,    // bww.b.b
    20,    // www.b.b
    11,    // ...bb.b
    -5,    // b..bb.b
    -16,   // w..bb.b
    12,    // .b.bb.b
    0,     // bb.bb.b
    36,    // wb.bb.b
    17,    // .w.bb.b
    -19,   // bw.bb.b
    2,     // ww.bb.b
    -7,    // ..bbb.b
    3,     // b.bbb.b
    -6,    // w.bbb.b
    -9,    // .bbbb.b
    6,     // bbbbb.b
    -12,   // wbbbb.b
    -11,   // .wbbb.b
    -8,    // bwbbb.b
    19,    // wwbbb.b
    5,     // ..wbb.b
    -4,    // b.wbb.b
    -3,    // w.wbb.b
    13,    // .bwbb.b
    -8,    // bbwbb.b
    23,    // wbwbb.b
    -7,    // .wwbb.b
    -16,   // bwwbb.b
    -9,    // wwwbb.b
    -3,    // ...wb.b
    23,    // b..wb.b
    4,     // w..wb.b
    -15,   // .b.wb.b
    -7,    // bb.wb.b
    -3,    // wb.wb.b
    1,     // .w.wb.b
    9,     // bw.wb.b
    0,     // ww.wb.b
    0,     // ..bwb.b
    4,     // b.bwb.b
    7,     // w.bwb.b
    5,     // .bbwb.b
    -1,    // bbbwb.b
    0,     // wbbwb.b
    -26,   // .wbwb.b
    16,    // bwbwb.b
    4,     // wwbwb.b
    10,    // ..wwb.b
    6,     // b.wwb.b
    3,     // w.wwb.b
    23,    // .bwwb.b
    -23,   // bbwwb.b
    18,    // wbwwb.b
    -4,    // .wwwb.b
    8,     // bwwwb.b
    6,     // wwwwb.b
    0,     // ....w.b
    -2,    // b...w.b
    -4,    // w...w.b
    -6,    // .b..w.b
    0,     // bb..w.b
    24,    // wb..w.b
    7,     // .w..w.b
    -14,   // bw..w.b
    3,     // ww..w.b
    -22,   // ..b.w.b
    13,    // b.b.w.b
    0,     // w.b.w.b
    -6,    // .bb.w.b
    15,    // bbb.w.b
    -19,   // wbb.w.b
    11,    // .wb.w.b
    -4,    // bwb.w.b
    3,     // wwb.w.b
    3,     // ..w.w.b
    -9,    // b.w.w.b
    -7,    // w.w.w.b
    7,     // .bw.w.b
    7,     // bbw.w.b
    -8,    // wbw.w.b
    -17,   // .ww.w.b
    -7,    // bww.w.b
    -20,   // www.w.b
    10,    // ...bw.b
    5,     // b..bw.b
    -2,    // w..bw.b
    5,     // .b.bw.b
    -15,   // bb.bw.b
    -11,   // wb.bw.b
    -4,    // .w.bw.b
    -17,   // bw.bw.b
    -13,   // ww.bw.b
    -6,    // ..bbw.b
    -4,    // b.bbw.b
    0,     // w.bbw.b
    -4,    // .bbbw.b
    7,     // bbbbw.b
    0,     // wbbbw.b
    -21,   // .wbbw.b
    12,    // bwbbw.b
    2,     // wwbbw.b
    -5,    // ..wbw.b
    37,    // b.wbw.b
    -7,    // w.wbw.b
    -8,    // .bwbw.b
    15,    // bbwbw.b
    5,     // wbwbw.b
    -6,    // .wwbw.b
    -3,    // bwwbw.b
    -2,    // wwwbw.b
    -15,   // ...ww.b
    -20,   // b..ww.b
    0,     // w..ww.b
    4,     // .b.ww.b
    16,    // bb.ww.b
    9,     // wb.ww.b
    18,    // .w.ww.b
    13,    // bw.ww.b
    0,     // ww.ww.b
    17,    // ..bww.b
    6,     // b.bww.b
    0,     // w.bww.b
    3,     // .bbww.b
    -10,   // bbbww.b
    -1,    // wbbww.b
    17,    // .wbww.b
    2,     // bwbww.b
    2,     // wwbww.b
    -13,   // ..www.b
    6,     // b.www.b
    6,     // w.www.b
    -7,    // .bwww.b
    7,     // bbwww.b
    13,    // wbwww.b
    -16,   // .wwww.b
    20,    // bwwww.b
    13,    // wwwww.b
    6,     // .....bb
    11,    // b....bb
    1,     // w....bb
    14,    // .b...bb
    -1,    // bb...bb
    -13,   // wb...bb
    11,    // .w...bb
    12,    // bw...bb
    0,     // ww...bb
    8,     // ..b..bb
    1,     // b.b..bb
    -3,    // w.b..bb
    1,     // .bb..bb
    -10,   // bbb..bb
    -6,    // wbb..bb
    3,     // .wb..bb
    7,     // bwb..bb
    19,    // wwb..bb
    3,     // ..w..bb
    0,     // b.w..bb
    8,     // w.w..bb
    2,     // .bw..bb
    1,     // bbw..bb
    -4,    // wbw..bb
    3,     // .ww..bb
    -6,    // bww..bb
    13,    // www..bb
    -2,    // ...b.bb
    -15,   // b..b.bb
    -5,    // w..b.bb
    12,    // .b.b.bb
    8,     // bb.b.bb
    10,    // wb.b.bb
    -4,    // .w.b.bb
    -14,   // bw.b.bb
    9,     // ww.b.bb
    -13,   // ..bb.bb
    0,     // b.bb.bb
    0,     // w.bb.bb
    19,    // .bbb.bb
    12,    // bbbb.bb
    -12,   // wbbb.bb
    7,     // .wbb.bb
    -11,   // bwbb.bb
    -22,   // wwbb.bb
    0,     // ..wb.bb
    -15,   // b.wb.bb
    0,     // w.wb.bb
    2,     // .bwb.bb
    18,    // bbwb.bb
    8,     // wbwb.bb
    -8,    // .wwb.bb
    -4,    // bwwb.bb
    -1,    // wwwb.bb
    -8,    // ...w.bb
    -30,   // b..w.bb
    0,     // w..w.bb
    -11,   // .b.w.bb
    8,     // bb.w.bb
    -7,    // wb.w.bb
    12,    // .w.w.bb
    3,     // bw.w.bb
    -9,    // ww.w.bb
    -10,   // ..bw.bb
    -7,    // b.bw.bb
    13,    // w.bw.bb
    8,     // .bbw.bb
    -1,    // bbbw.bb
    -7,    // wbbw.bb
    -6,    // .wbw.bb
    5,     // bwbw.bb
    -22,   // wwbw.bb
    -2,    // ..ww.bb
    16,    // b.ww.bb
    -2,    // w.ww.bb
    7,     // .bww.bb
    3,     // bbww.bb
    9,     // wbww.bb
    9,     // .www.bb
    10,    // bwww.bb
    20,    // wwww.bb
    38,    // ....bbb
    20,    // b...bbb
    22,    // w...bbb
    3,     // .b..bbb
    -10,   // bb..bbb
    -1,    // wb..bbb
    2,     // .w..bbb
    -10,   // bw..bbb
    -13,   // ww..bbb
    1,     // ..b.bbb
    21,    // b.b.bbb
    20,    // w.b.bbb
    -14,   // .bb.bbb
    -2,    // bbb.bbb
    -9,    // wbb.bbb
    10,    // .wb.bbb
    12,    // bwb.bbb
    12,    // wwb.bbb
    -7,    // ..w.bbb
    15,    // b.w.bbb
    -20,   // w.w.bbb
    0,     // .bw.bbb
    5,     // bbw.bbb
    -1,    // wbw.bbb
    10,    // .ww.bbb
    -11,   // bww.bbb
    0,     // www.bbb
    7,     // ...bbbb
    -29,   // b..bbbb
    -11,   // w..bbbb
    -11,   // .b.bbbb
    12,    // bb.bbbb
    7,     // wb.bbbb
    3,     // .w.bbbb
    3,     // bw.bbbb
    -20,   // ww.bbbb
    12,    // ..bbbbb
    6,     // b.bbbbb
    -13,   // w.bbbbb
    25,    // .bbbbbb
    -1,    // bbbbbbb
    -1,    // wbbbbbb
    -14,   // .wbbbbb
    1,     // bwbbbbb
    -8,    // wwbbbbb
    -21,   // ..wbbbb
    7,     // b.wbbbb
    -6,    // w.wbbbb
    -4,    // .bwbbbb
    2,     // bbwbbbb
    -5,    // wbwbbbb
    2,     // .wwbbbb
    -9,    // bwwbbbb
    4,     // wwwbbbb
    -11,   // ...wbbb
    7,     // b..wbbb
    8,     // w..wbbb
    -4,    // .b.wbbb
    -1,    // bb.wbbb
    3,     // wb.wbbb
    5,     // .w.wbbb
    0,     // bw.wbbb
    1,     // ww.wbbb
    -3,    // ..bwbbb
    -1,    // b.bwbbb
    2,     // w.bwbbb
    0,     // .bbwbbb
    1,     // bbbwbbb
    2,     // wbbwbbb
    -4,    // .wbwbbb
    -2,    // bwbwbbb
    32,    // wwbwbbb
    -13,   // ..wwbbb
    -10,   // b.wwbbb
    9,     // w.wwbbb
    1,     // .bwwbbb
    -25,   // bbwwbbb
    5,     // wbwwbbb
    -9,    // .wwwbbb
    8,     // bwwwbbb
    -4,    // wwwwbbb
    -20,   // ....wbb
    0,     // b...wbb
    8,     // w...wbb
    5,     // .b..wbb
    1,     // bb..wbb
    -3,    // wb..wbb
    -4,    // .w..wbb
    20,    // bw..wbb
    -19,   // ww..wbb
    -18,   // ..b.wbb
    -9,    // b.b.wbb
    -3,    // w.b.wbb
    11,    // .bb.wbb
    5,     // bbb.wbb
    2,     // wbb.wbb
    -4,    // .wb.wbb
    -5,    // bwb.wbb
    0,     // wwb.wbb
    1,     // ..w.wbb
    7,     // b.w.wbb
    2,     // w.w.wbb
    6,     // .bw.wbb
    -14,   // bbw.wbb
    8,     // wbw.wbb
    -1,    // .ww.wbb
    -2,    // bww.wbb
    -12,   // www.wbb
    -13,   // ...bwbb
    -13,   // b..bwbb
    -3,    // w..bwbb
    -20,   // .b.bwbb
    18,    // bb.bwbb
    16,    // wb.bwbb
    -9,    // .w.bwbb
    10,    // bw.bwbb
    22,    // ww.bwbb
    10,    // ..bbwbb
    -8,    // b.bbwbb
    -2,    // w.bbwbb
    2,     // .bbbwbb
    2,     // bbbbwbb
    -19,   // wbbbwbb
    -4,    // .wbbwbb
    8,     // bwbbwbb
    -10,   // wwbbwbb
    7,     // ..wbwbb
    15,    // b.wbwbb
    -4,    // w.wbwbb
    8,     // .bwbwbb
    1,     // bbwbwbb
    -7,    // wbwbwbb
    -11,   // .wwbwbb
    -15,   // bwwbwbb
    -32,   // wwwbwbb
    -17,   // ...wwbb
    9,     // b..wwbb
    0,     // w..wwbb
    19,    // .b.wwbb
    3,     // bb.wwbb
    12,    // wb.wwbb
    12,    // .w.wwbb
    5,     // bw.wwbb
    22,    // ww.wwbb
    4,     // ..bwwbb
    -23,   // b.bwwbb
    -2,    // w.bwwbb
    -18,   // .bbwwbb
    -25,   // bbbwwbb
    9,     // wbbwwbb
    5,     // .wbwwbb
    -3,    // bwbwwbb
    10,    // wwbwwbb
    10,    // ..wwwbb
    7,     // b.wwwbb
    -19,   // w.wwwbb
    -11,   // .bwwwbb
    6,     // bbwwwbb
    -21,   // wbwwwbb
    -1,    // .wwwwbb
    -2,    // bwwwwbb
    8,     // wwwwwbb
    -5,    // .....wb
    4,     // b....wb
    11,    // w....wb
    -16,   // .b...wb
    12,    // bb...wb
    0,     // wb...wb
    13,    // .w...wb
    1,     // bw...wb
    13,    // ww...wb
    8,     // ..b..wb
    -15,   // b.b..wb
    -24,   // w.b..wb
    9,     // .bb..wb
    -10,   // bbb..wb
    5,     // wbb..wb
    16,    // .wb..wb
    13,    // bwb..wb
    3,     // wwb..wb
    0,     // ..w..wb
    -14,   // b.w..wb
    -3,    // w.w..wb
    9,     // .bw..wb
    20,    // bbw..wb
    19,    // wbw..wb
    4,     // .ww..wb
    -14,   // bww..wb
    1,     // www..wb
    4,     // ...b.wb
    11,    // b..b.wb
    9,     // w..b.wb
    -19,   // .b.b.wb
    -14,   // bb.b.wb
    9,     // wb.b.wb
    -8,    // .w.b.wb
    2,     // bw.b.wb
    7,     // ww.b.wb
    8,     // ..bb.wb
    -19,   // b.bb.wb
    -9,    // w.bb.wb
    -6,    // .bbb.wb
    3,     // bbbb.wb
    -3,    // wbbb.wb
    -2,    // .wbb.wb
    -2,    // bwbb.wb
    -12,   // wwbb.wb
    -29,   // ..wb.wb
    -17,   // b.wb.wb
    3,     // w.wb.wb
    -6,    // .bwb.wb
    10,    // bbwb.wb
    -3,    // wbwb.wb
    2,     // .wwb.wb
    22,    // bwwb.wb
    -3,    // wwwb.wb
    -18,   // ...w.wb
    -2,    // b..w.wb
    -4,    // w..w.wb
    -21,   // .b.w.wb
    3,     // bb.w.wb
    -9,    // wb.w.wb
    1,     // .w.w.wb
    -2,    // bw.w.wb
    -10,   // ww.w.wb
    4,     // ..bw.wb
    9,     // b.bw.wb
    11,    // w.bw.wb
    -6,    // .bbw.wb
    0,     // bbbw.wb
    -21,   // wbbw.wb
    -24,   // .wbw.wb
    -1,    // bwbw.wb
    -16,   // wwbw.wb
    5,     // ..ww.wb
    13,    // b.ww.wb
    -36,   // w.ww.wb
    2,     // .bww.wb
    5,     // bbww.wb
    -12,   // wbww.wb
    -2,    // .www.wb
    -35,   // bwww.wb
    -7,    // wwww.wb
    -20,   // ....bwb
    25,    // b...bwb
    -18,   // w...bwb
    4,     // .b..bwb
    7,     // bb..bwb
    -19,   // wb..bwb
    32,    // .w..bwb
    13,    // bw..bwb
    4,     // ww..bwb
    9,     // ..b.bwb
    16,    // b.b.bwb
    8,     // w.b.bwb
    -2,    // .bb.bwb
    12,    // bbb.bwb
    -15,   // wbb.bwb
    7,     // .wb.bwb
    -13,   // bwb.bwb
    -8,    // wwb.bwb
    -3,    // ..w.bwb
    -4,    // b.w.bwb
    -1,    // w.w.bwb
    -5,    // .bw.bwb
    -5,    // bbw.bwb
    0,     // wbw.bwb
    -3,    // .ww.bwb
    -28,   // bww.bwb
    1,     // www.bwb
    26,    // ...bbwb
    -10,   // b..bbwb
    11,    // w..bbwb
    5,     // .b.bbwb
    -11,   // bb.bbwb
    12,    // wb.bbwb
    -7,    // .w.bbwb
    -2,    // bw.bbwb
    -9,    // ww.bbwb
    1,     // ..bbbwb
    -8,    // b.bbbwb
    -13,   // w.bbbwb
    -18,   // .bbbbwb
    1,     // bbbbbwb
    -5,    // wbbbbwb
    -15,   // .wbbbwb
    -4,    // bwbbbwb
    21,    // wwbbbwb
    11,    // ..wbbwb
    12,    // b.wbbwb
    -18,   // w.wbbwb
    5,     // .bwbbwb
    8,     // bbwbbwb
    -10,   // wbwbbwb
    -2,    // .wwbbwb
    -23,   // bwwbbwb
    -5,    // wwwbbwb
    16,    // ...wbwb
    -12,   // b..wbwb
    10,    // w..wbwb
    13,    // .b.wbwb
    5,     // bb.wbwb
    3,     // wb.wbwb
    4,     // .w.wbwb
    -1,    // bw.wbwb
    -8,    // ww.wbwb
    -1,    // ..bwbwb
    16,    // b.bwbwb
    -5,    // w.bwbwb
    -10,   // .bbwbwb
    -2,    // bbbwbwb
    -11,   // wbbwbwb
    -7,    // .wbwbwb
    -10,   // bwbwbwb
    7,     // wwbwbwb
    -12,   // ..wwbwb
    2,     // b.wwbwb
    -23,   // w.wwbwb
    11,    // .bwwbwb
    -3,    // bbwwbwb
    10,    // wbwwbwb
    10,    // .wwwbwb
    -1,    // bwwwbwb
    5,     // wwwwbwb
    18,    // ....wwb
    -9,    // b...wwb
    1,     // w...wwb
    13,    // .b..wwb
    -6,    // bb..wwb
    -5,    // wb..wwb
    -6,    // .w..wwb
    -14,   // bw..wwb
    6,     // ww..wwb
    0,     // ..b.wwb
    -6,    // b.b.wwb
    19,    // w.b.wwb
    -17,   // .bb.wwb
    -11,   // bbb.wwb
    0,     // wbb.wwb
    -19,   // .wb.wwb
    -28,   // bwb.wwb
    -2,    // wwb.wwb
    -2,    // ..w.wwb
    -7,    // b.w.wwb
    -1,    // w.w.wwb
    10,    // .bw.wwb
    -2,    // bbw.wwb
    15,    // wbw.wwb
    3,     // .ww.wwb
    -1,    // bww.wwb
    9,     // www.wwb
    -1,    // ...bwwb
    -2,    // b..bwwb
    14,    // w..bwwb
    9,     // .b.bwwb
    -4,    // bb.bwwb
    21,    // wb.bwwb
    -4,    // .w.bwwb
    22,    // bw.bwwb
    7,     // ww.bwwb
    14,    // ..bbwwb
    -16,   // b.bbwwb
    1,     // w.bbwwb
    4,     // .bbbwwb
    -9,    // bbbbwwb
    -8,    // wbbbwwb
    -6,    // .wbbwwb
    -23,   // bwbbwwb
    -9,    // wwbbwwb
    -12,   // ..wbwwb
    -3,    // b.wbwwb
    0,     // w.wbwwb
    8,     // .bwbwwb
    -15,   // bbwbwwb
    11,    // wbwbwwb
    9,     // .wwbwwb
    1,     // bwwbwwb
    -2,    // wwwbwwb
    -5,    // ...wwwb
    3,     // b..wwwb
    -9,    // w..wwwb
    12,    // .b.wwwb
    10,    // bb.wwwb
    3,     // wb.wwwb
    1,     // .w.wwwb
    -35,   // bw.wwwb
    12,    // ww.wwwb
    -6,    // ..bwwwb
    8,     // b.bwwwb
    0,     // w.bwwwb
    -5,    // .bbwwwb
    8,     // bbbwwwb
    8,     // wbbwwwb
    13,    // .wbwwwb
    -1,    // bwbwwwb
    19,    // wwbwwwb
    -24,   // ..wwwwb
    20,    // b.wwwwb
    12,    // w.wwwwb
    -3,    // .bwwwwb
    -2,    // bbwwwwb
    5,     // wbwwwwb
    8,     // .wwwwwb
    4,     // bwwwwwb
    1,     // wwwwwwb
    0,     // ......w
    0,     // b.....w
    12,    // w.....w
    -20,   // .b....w
    1,     // bb....w
    -4,    // wb....w
    10,    // .w....w
    11,    // bw....w
    -11,   // ww....w
    10,    // ..b...w
    -8,    // b.b...w
    2,     // w.b...w
    -2,    // .bb...w
    22,    // bbb...w
    9,     // wbb...w
    -7,    // .wb...w
    -18,   // bwb...w
    0,     // wwb...w
    19,    // ..w...w
    -4,    // b.w...w
    -6,    // w.w...w
    -4,    // .bw...w
    8,     // bbw...w
    -25,   // wbw...w
    -20,   // .ww...w
    1,     // bww...w
    -20,   // www...w
    -19,   // ...b..w
    18,    // b..b..w
    -11,   // w..b..w
    -5,    // .b.b..w
    -5,    // bb.b..w
    2,     // wb.b..w
    4,     // .w.b..w
    9,     // bw.b..w
    30,    // ww.b..w
    9,     // ..bb..w
    -16,   // b.bb..w
    20,    // w.bb..w
    -3,    // .bbb..w
    -11,   // bbbb..w
    -3,    // wbbb..w
    1,     // .wbb..w
    11,    // bwbb..w
    -9,    // wwbb..w
    9,     // ..wb..w
    -2,    // b.wb..w
    -23,   // w.wb..w
    7,     // .bwb..w
    -3,    // bbwb..w
    12,    // wbwb..w
    14,    // .wwb..w
    14,    // bwwb..w
    -7,    // wwwb..w
    -9,    // ...w..w
    -18,   // b..w..w
    -33,   // w..w..w
    -3,    // .b.w..w
    0,     // bb.w..w
    -11,   // wb.w..w
    8,     // .w.w..w
    -4,    // bw.w..w
    15,    // ww.w..w
    3,     // ..bw..w
    4,     // b.bw..w
    -5,    // w.bw..w
    -3,    // .bbw..w
    8,     // bbbw..w
    2,     // wbbw..w
    -16,   // .wbw..w
    10,    // bwbw..w
    13,    // wwbw..w
    17,    // ..ww..w
    0,     // b.ww..w
    5,     // w.ww..w
    2,     // .bww..w
    0,     // bbww..w
    10,    // wbww..w
    -8,    // .www..w
    -9,    // bwww..w
    29,    // wwww..w
    0,     // ....b.w
    4,     // b...b.w
    2,     // w...b.w
    -7,    // .b..b.w
    -3,    // bb..b.w
    14,    // wb..b.w
    6,     // .w..b.w
    -24,   // bw..b.w
    0,     // ww..b.w
    -3,    // ..b.b.w
    7,     // b.b.b.w
    9,     // w.b.b.w
    17,    // .bb.b.w
    20,    // bbb.b.w
    7,     // wbb.b.w
    -7,    // .wb.b.w
    8,     // bwb.b.w
    -7,    // wwb.b.w
    22,    // ..w.b.w
    0,     // b.w.b.w
    -13,   // w.w.b.w
    -11,   // .bw.b.w
    -3,    // bbw.b.w
    4,     // wbw.b.w
    6,     // .ww.b.w
    19,    // bww.b.w
    -15,   // www.b.w
    15,    // ...bb.w
    0,     // b..bb.w
    20,    // w..bb.w
    -18,   // .b.bb.w
    0,     // bb.bb.w
    -13,   // wb.bb.w
    -4,    // .w.bb.w
    -9,    // bw.bb.w
    -16,   // ww.bb.w
    13,    // ..bbb.w
    -6,    // b.bbb.w
    -6,    // w.bbb.w
    16,    // .bbbb.w
    -13,   // bbbbb.w
    -20,   // wbbbb.w
    7,     // .wbbb.w
    -13,   // bwbbb.w
    -7,    // wwbbb.w
    -17,   // ..wbb.w
    0,     // b.wbb.w
    -6,    // w.wbb.w
    -17,   // .bwbb.w
    -2,    // bbwbb.w
    -2,    // wbwbb.w
    -3,    // .wwbb.w
    1,     // bwwbb.w
    10,    // wwwbb.w
    -10,   // ...wb.w
    2,     // b..wb.w
    -5,    // w..wb.w
    4,     // .b.wb.w
    13,    // bb.wb.w
    17,    // wb.wb.w
    -5,    // .w.wb.w
    11,    // bw.wb.w
    15,    // ww.wb.w
    5,     // ..bwb.w
    7,     // b.bwb.w
    -37,   // w.bwb.w
    6,     // .bbwb.w
    2,     // bbbwb.w
    3,     // wbbwb.w
    8,     // .wbwb.w
    -5,    // bwbwb.w
    -15,   // wwbwb.w
    6,     // ..wwb.w
    0,     // b.wwb.w
    4,     // w.wwb.w
    21,    // .bwwb.w
    -2,    // bbwwb.w
    -12,   // wbwwb.w
    4,     // .wwwb.w
    0,     // bwwwb.w
    -7,    // wwwwb.w
    14,    // ....w.w
    8,     // b...w.w
    -6,    // w...w.w
    -17,   // .b..w.w
    8,     // bb..w.w
    15,    // wb..w.w
    3,     // .w..w.w
    -3,    // bw..w.w
    -1,    // ww..w.w
    7,     // ..b.w.w
    0,     // b.b.w.w
    -13,   // w.b.w.w
    -17,   // .bb.w.w
    -20,   // bbb.w.w
    6,     // wbb.w.w
    8,     // .wb.w.w
    -1,    // bwb.w.w
    9,     // wwb.w.w
    11,    // ..w.w.w
    -7,    // b.w.w.w
    -3,    // w.w.w.w
    2,     // .bw.w.w
    2,     // bbw.w.w
    -16,   // wbw.w.w
    -2,    // .ww.w.w
    -1,    // bww.w.w
    -21,   // www.w.w
    3,     // ...bw.w
    -4,    // b..bw.w
    -23,   // w..bw.w
    -1,    // .b.bw.w
    0,     // bb.bw.w
    -9,    // wb.bw.w
    15,    // .w.bw.w
    3,     // bw.bw.w
    7,     // ww.bw.w
    -10,   // ..bbw.w
    -3,    // b.bbw.w
    -6,    // w.bbw.w
    4,     // .bbbw.w
    -6,    // bbbbw.w
    -8,    // wbbbw.w
    -23,   // .wbbw.w
    -18,   // bwbbw.w
    23,    // wwbbw.w
    0,     // ..wbw.w
    -7,    // b.wbw.w
    -4,    // w.wbw.w
    26,    // .bwbw.w
    -4,    // bbwbw.w
    -16,   // wbwbw.w
    -5,    // .wwbw.w
    0,     // bwwbw.w
    1,     // wwwbw.w
    -11,   // ...ww.w
    16,    // b..ww.w
    5,     // w..ww.w
    -17,   // .b.ww.w
    -2,    // bb.ww.w
    19,    // wb.ww.w
    -12,   // .w.ww.w
    -36,   // bw.ww.w
    0,     // ww.ww.w
    -5,    // ..bww.w
    3,     // b.bww.w
    4,     // w.bww.w
    7,     // .bbww.w
    9,     // bbbww.w
    16,    // wbbww.w
    -13,   // .wbww.w
    -23,   // bwbww.w
    8,     // wwbww.w
    7,     // ..www.w
    6,     // b.www.w
    -3,    // w.www.w
    11,    // .bwww.w
    -19,   // bbwww.w
    8,     // wbwww.w
    9,     // .wwww.w
    12,    // bwwww.w
    -6,    // wwwww.w
    5,     // .....bw
    -11,   // b....bw
    -4,    // w....bw
    -13,   // .b...bw
    -13,   // bb...bw
    -1,    // wb...bw
    16,    // .w...bw
    0,     // bw...bw
    -12,   // ww...bw
    0,     // ..b..bw
    3,     // b.b..bw
    14,    // w.b..bw
    -4,    // .bb..bw
    -1,    // bbb..bw
    14,    // wbb..bw
    -9,    // .wb..bw
    -19,   // bwb..bw
    -20,   // wwb..bw
    -8,    // ..w..bw
    24,    // b.w..bw
    15,    // w.w..bw
    -16,   // .bw..bw
    -3,    // bbw..bw
    -13,   // wbw..bw
    -9,    // .ww..bw
    -5,    // bww..bw
    10,    // www..bw
    18,    // ...b.bw
    4,     // b..b.bw
    2,     // w..b.bw
    -1,    // .b.b.bw
    10,    // bb.b.bw
    2,     // wb.b.bw
    21,    // .w.b.bw
    9,     // bw.b.bw
    -3,    // ww.b.bw
    -5,    // ..bb.bw
    36,    // b.bb.bw
    -13,   // w.bb.bw
    2,     // .bbb.bw
    7,     // bbbb.bw
    35,    // wbbb.bw
    -2,    // .wbb.bw
    12,    // bwbb.bw
    -5,    // wwbb.bw
    -4,    // ..wb.bw
    -11,   // b.wb.bw
    -9,    // w.wb.bw
    24,    // .bwb.bw
    16,    // bbwb.bw
    1,     // wbwb.bw
    6,     // .wwb.bw
    21,    // bwwb.bw
    0,     // wwwb.bw
    -4,    // ...w.bw
    -9,    // b..w.bw
    -11,   // w..w.bw
    8,     // .b.w.bw
    -7,    // bb.w.bw
    -2,    // wb.w.bw
    19,    // .w.w.bw
    -9,    // bw.w.bw
    14,    // ww.w.bw
    29,    // ..bw.bw
    -3,    // b.bw.bw
    17,    // w.bw.bw
    -2,    // .bbw.bw
    3,     // bbbw.bw
    -22,   // wbbw.bw
    6,     // .wbw.bw
    3,     // bwbw.bw
    -10,   // wwbw.bw
    -8,    // ..ww.bw
    9,     // b.ww.bw
    19,    // w.ww.bw
    2,     // .bww.bw
    12,    // bbww.bw
    2,     // wbww.bw
    6,     // .www.bw
    3,     // bwww.bw
    -3,    // wwww.bw
    -18,   // ....bbw
    -1,    // b...bbw
    9,     // w...bbw
    6,     // .b..bbw
    -6,    // bb..bbw
    14,    // wb..bbw
    -13,   // .w..bbw
    5,     // bw..bbw
    6,     // ww..bbw
    2,     // ..b.bbw
    1,     // b.b.bbw
    7,     // w.b.bbw
    -3,    // .bb.bbw
    -9,    // bbb.bbw
    1,     // wbb.bbw
    -10,   // .wb.bbw
    -15,   // bwb.bbw
    2,     // wwb.bbw
    0,     // ..w.bbw
    -19,   // b.w.bbw
    6,     // w.w.bbw
    19,    // .bw.bbw
    2,     // bbw.bbw
    28,    // wbw.bbw
    17,    // .ww.bbw
    0,     // bww.bbw
    11,    // www.bbw
    5,     // ...bbbw
    9,     // b..bbbw
    -3,    // w..bbbw
    -1,    // .b.bbbw
    -12,   // bb.bbbw
    35,    // wb.bbbw
    -12,   // .w.bbbw
    -3,    // bw.bbbw
    -10,   // ww.bbbw
    24,    // ..bbbbw
    -12,   // b.bbbbw
    -20,   // w.bbbbw
    -8,    // .bbbbbw
    -1,    // bbbbbbw
    -4,    // wbbbbbw
    3,     // .wbbbbw
    -5,    // bwbbbbw
    2,     // wwbbbbw
    6,     // ..wbbbw
    0,     // b.wbbbw
    -8,    // w.wbbbw
    -13,   // .bwbbbw
    -19,   // bbwbbbw
    1,     // wbwbbbw
    5,     // .wwbbbw
    -8,    // bwwbbbw
    -8,    // wwwbbbw
    1,     // ...wbbw
    -14,   // b..wbbw
    2,     // w..wbbw
    4,     // .b.wbbw
    -7,    // bb.wbbw
    -22,   // wb.wbbw
    -9,    // .w.wbbw
    -21,   // bw.wbbw
    4,     // ww.wbbw
    12,    // ..bwbbw
    0,     // b.bwbbw
    3,     // w.bwbbw
    -9,    // .bbwbbw
    2,     // bbbwbbw
    -1,    // wbbwbbw
    -8,    // .wbwbbw
    -11,   // bwbwbbw
    15,    // wwbwbbw
    -14,   // ..wwbbw
    -1,    // b.wwbbw
    16,    // w.wwbbw
    6,     // .bwwbbw
    9,     // bbwwbbw
    23,    // wbwwbbw
    -4,    // .wwwbbw
    8,     // bwwwbbw
    9,     // wwwwbbw
    20,    // ....wbw
    18,    // b...wbw
    -25,   // w...wbw
    -32,   // .b..wbw
    -4,    // bb..wbw
    -13,   // wb..wbw
    -4,    // .w..wbw
    19,    // bw..wbw
    -7,    // ww..wbw
    3,     // ..b.wbw
    1,     // b.b.wbw
    4,     // w.b.wbw
    3,     // .bb.wbw
    -1,    // bbb.wbw
    28,    // wbb.wbw
    5,     // .wb.wbw
    0,     // bwb.wbw
    5,     // wwb.wbw
    -9,    // ..w.wbw
    -8,    // b.w.wbw
    -16,   // w.w.wbw
    -7,    // .bw.wbw
    8,     // bbw.wbw
    13,    // wbw.wbw
    2,     // .ww.wbw
    15,    // bww.wbw
    -12,   // www.wbw
    -16,   // ...bwbw
    -10,   // b..bwbw
    12,    // w..bwbw
    -4,    // .b.bwbw
    8,     // bb.bwbw
    1,     // wb.bwbw
    -13,   // .w.bwbw
    -3,    // bw.bwbw
    -5,    // ww.bwbw
    12,    // ..bbwbw
    23,    // b.bbwbw
    -2,    // w.bbwbw
    -10,   // .bbbwbw
    -5,    // bbbbwbw
    1,     // wbbbwbw
    -11,   // .wbbwbw
    -10,   // bwbbwbw
    3,     // wwbbwbw
    1,     // ..wbwbw
    5,     // b.wbwbw
    -16,   // w.wbwbw
    7,     // .bwbwbw
    -7,    // bbwbwbw
    10,    // wbwbwbw
    10,    // .wwbwbw
    11,    // bwwbwbw
    2,     // wwwbwbw
    -26,   // ...wwbw
    -11,   // b..wwbw
    10,    // w..wwbw
    7,     // .b.wwbw
    9,     // bb.wwbw
    2,     // wb.wwbw
    -5,    // .w.wwbw
    -12,   // bw.wwbw
    11,    // ww.wwbw
    -11,   // ..bwwbw
    18,    // b.bwwbw
    -12,   // w.bwwbw
    2,     // .bbwwbw
    5,     // bbbwwbw
    23,    // wbbwwbw
    -5,    // .wbwwbw
    10,    // bwbwwbw
    -8,    // wwbwwbw
    -1,    // ..wwwbw
    13,    // b.wwwbw
    8,     // w.wwwbw
    15,    // .bwwwbw
    -21,   // bbwwwbw
    4,     // wbwwwbw
    18,    // .wwwwbw
    5,     // bwwwwbw
    -1,    // wwwwwbw
    -6,    // .....ww
    -1,    // b....ww
    -11,   // w....ww
    -11,   // .b...ww
    0,     // bb...ww
    -12,   // wb...ww
    -14,   // .w...ww
    13,    // bw...ww
    1,     // ww...ww
    -3,    // ..b..ww
    -8,    // b.b..ww
    0,     // w.b..ww
    -3,    // .bb..ww
    -13,   // bbb..ww
    6,     // wbb..ww
    -2,    // .wb..ww
    4,     // bwb..ww
    -1,    // wwb..ww
    -8,    // ..w..ww
    3,     // b.w..ww
    -1,    // w.w..ww
    -3,    // .bw..ww
    -19,   // bbw..ww
    -7,    // wbw..ww
    -1,    // .ww..ww
    6,     // bww..ww
    10,    // www..ww
    8,     // ...b.ww
    0,     // b..b.ww
    30,    // w..b.ww
    -12,   // .b.b.ww
    9,     // bb.b.ww
    -3,    // wb.b.ww
    11,    // .w.b.ww
    7,     // bw.b.ww
    -8,    // ww.b.ww
    2,     // ..bb.ww
    2,     // b.bb.ww
    -16,   // w.bb.ww
    -9,    // .bbb.ww
    -20,   // bbbb.ww
    -10,   // wbbb.ww
    -7,    // .wbb.ww
    -9,    // bwbb.ww
    -3,    // wwbb.ww
    10,    // ..wb.ww
    -13,   // b.wb.ww
    7,     // w.wb.ww
    6,     // .bwb.ww
    22,    // bbwb.ww
    -5,    // wbwb.ww
    -8,    // .wwb.ww
    7,     // bwwb.ww
    1,     // wwwb.ww
    2,     // ...w.ww
    5,     // b..w.ww
    15,    // w..w.ww
    4,     // .b.w.ww
    -9,    // bb.w.ww
    14,    // wb.w.ww
    -12,   // .w.w.ww
    -10,   // bw.w.ww
    -8,    // ww.w.ww
    0,     // ..bw.ww
    0,     // b.bw.ww
    15,    // w.bw.ww
    8,     // .bbw.ww
    1,     // bbbw.ww
    4,     // wbbw.ww
    -2,    // .wbw.ww
    -8,    // bwbw.ww
    -18,   // wwbw.ww
    13,    // ..ww.ww
    0,     // b.ww.ww
    0,     // w.ww.ww
    -7,    // .bww.ww
    22,    // bbww.ww
    11,    // wbww.ww
    -19,   // .www.ww
    12,    // bwww.ww
    -12,   // wwww.ww
    20,    // ....bww
    -8,    // b...bww
    0,     // w...bww
    4,     // .b..bww
    19,    // bb..bww
    -20,   // wb..bww
    -5,    // .w..bww
    3,     // bw..bww
    -1,    // ww..bww
    -1,    // ..b.bww
    -2,    // b.b.bww
    -7,    // w.b.bww
    1,     // .bb.bww
    12,    // bbb.bww
    2,     // wbb.bww
    -6,    // .wb.bww
    -8,    // bwb.bww
    14,    // wwb.bww
    18,    // ..w.bww
    3,     // b.w.bww
    9,     // w.w.bww
    4,     // .bw.bww
    0,     // bbw.bww
    5,     // wbw.bww
    -11,   // .ww.bww
    -2,    // bww.bww
    -5,    // www.bww
    17,    // ...bbww
    0,     // b..bbww
    -9,    // w..bbww
    -12,   // .b.bbww
    -22,   // bb.bbww
    -5,    // wb.bbww
    -19,   // .w.bbww
    -12,   // bw.bbww
    -3,    // ww.bbww
    -10,   // ..bbbww
    19,    // b.bbbww
    -7,    // w.bbbww
    1,     // .bbbbww
    -8,    // bbbbbww
    2,     // wbbbbww
    11,    // .wbbbww
    21,    // bwbbbww
    -6,    // wwbbbww
    -4,    // ..wbbww
    2,     // b.wbbww
    23,    // w.wbbww
    -5,    // .bwbbww
    -10,   // bbwbbww
    3,     // wbwbbww
    18,    // .wwbbww
    -9,    // bwwbbww
    25,    // wwwbbww
    13,    // ...wbww
    3,     // b..wbww
    13,    // w..wbww
    9,     // .b.wbww
    -22,   // bb.wbww
    -10,   // wb.wbww
    20,    // .w.wbww
    -16,   // bw.wbww
    -18,   // ww.wbww
    -7,    // ..bwbww
    4,     // b.bwbww
    -15,   // w.bwbww
    11,    // .bbwbww
    32,    // bbbwbww
    15,    // wbbwbww
    -8,    // .wbwbww
    7,     // bwbwbww
    -1,    // wwbwbww
    -10,   // ..wwbww
    2,     // b.wwbww
    8,     // w.wwbww
    4,     // .bwwbww
    10,    // bbwwbww
    -8,    // wbwwbww
    -2,    // .wwwbww
    19,    // bwwwbww
    -2,    // wwwwbww
    -38,   // ....www
    -22,   // b...www
    -20,   // w...www
    -2,    // .b..www
    13,    // bb..www
    10,    // wb..www
    -3,    // .w..www
    1,     // bw..www
    10,    // ww..www
    7,     // ..b.www
    20,    // b.b.www
    -15,   // w.b.www
    -10,   // .bb.www
    0,     // bbb.www
    11,    // wbb.www
    0,     // .wb.www
    1,     // bwb.www
    -5,    // wwb.www
    -1,    // ..w.www
    -20,   // b.w.www
    -21,   // w.w.www
    -10,   // .bw.www
    -12,   // bbw.www
    -12,   // wbw.www
    14,    // .ww.www
    9,     // bww.www
    2,     // www.www
    11,    // ...bwww
    -8,    // b..bwww
    -7,    // w..bwww
    -5,    // .b.bwww
    -1,    // bb.bwww
    0,     // wb.bwww
    4,     // .w.bwww
    -3,    // bw.bwww
    1,     // ww.bwww
    13,    // ..bbwww
    -9,    // b.bbwww
    10,    // w.bbwww
    9,     // .bbbwww
    4,     // bbbbwww
    -8,    // wbbbwww
    -1,    // .wbbwww
    -5,    // bwbbwww
    25,    // wwbbwww
    3,     // ..wbwww
    -2,    // b.wbwww
    1,     // w.wbwww
    4,     // .bwbwww
    -32,   // bbwbwww
    2,     // wbwbwww
    0,     // .wwbwww
    -2,    // bwwbwww
    -1,    // wwwbwww
    -7,    // ...wwww
    11,    // b..wwww
    29,    // w..wwww
    -3,    // .b.wwww
    20,    // bb.wwww
    -3,    // wb.wwww
    11,    // .w.wwww
    -7,    // bw.wwww
    -12,   // ww.wwww
    21,    // ..bwwww
    6,     // b.bwwww
    -7,    // w.bwwww
    -2,    // .bbwwww
    -4,    // bbbwwww
    9,     // wbbwwww
    4,     // .wbwwww
    5,     // bwbwwww
    -2,    // wwbwwww
    -12,   // ..wwwww
    13,    // b.wwwww
    -6,    // w.wwwww
    14,    // .bwwwww
    8,     // bbwwwww
    -1,    // wbwwwww
    -25,   // .wwwwww
    1,     // bwwwwww
    1,     // wwwwwww
    -10,   // ccc
    -12,   // cc
    1,     // c
    28,    // ttt
    1,     // tt
    -2,    // t
    -14,   // ct
    -2,    // cct
    -17,   // ctt
].into_boxed_slice()
