vec![
    0,     // ......
    -4,    // b.....
    4,     // w.....
    -17,   // .b....
    0,     // bb....
    2,     // wb....
    17,    // .w....
    -2,    // bw....
    0,     // ww....
    -16,   // ..b...
    3,     // b.b...
    4,     // w.b...
    2,     // .bb...
    -2,    // bbb...
    -8,    // wbb...
    -8,    // .wb...
    -15,   // bwb...
    -3,    // wwb...
    16,    // ..w...
    -4,    // b.w...
    -3,    // w.w...
    8,     // .bw...
    3,     // bbw...
    15,    // wbw...
    -2,    // .ww...
    8,     // bww...
    2,     // www...
    -16,   // ...b..
    3,     // b..b..
    10,    // w..b..
    3,     // .b.b..
    -2,    // bb.b..
    -1,    // wb.b..
    6,     // .w.b..
    -9,    // bw.b..
    4,     // ww.b..
    5,     // ..bb..
    6,     // b.bb..
    9,     // w.bb..
    3,     // .bbb..
    -2,    // bbbb..
    -4,    // wbbb..
    8,     // .wbb..
    10,    // bwbb..
    1,     // wwbb..
    0,     // ..wb..
    5,     // b.wb..
    -1,    // w.wb..
    -2,    // .bwb..
    1,     // bbwb..
    11,    // wbwb..
    -2,    // .wwb..
    -14,   // bwwb..
    2,     // wwwb..
    16,    // ...w..
    -10,   // b..w..
    -3,    // w..w..
    -6,    // .b.w..
    -4,    // bb.w..
    9,     // wb.w..
    -3,    // .w.w..
    1,     // bw.w..
    2,     // ww.w..
    0,     // ..bw..
    1,     // b.bw..
    -5,    // w.bw..
    2,     // .bbw..
    -2,    // bbbw..
    14,    // wbbw..
    2,     // .wbw..
    -11,   // bwbw..
    -1,    // wwbw..
    -5,    // ..ww..
    -9,    // b.ww..
    -6,    // w.ww..
    -8,    // .bww..
    -1,    // bbww..
    -10,   // wbww..
    -3,    // .www..
    4,     // bwww..
    2,     // wwww..
    -17,   // ....b.
    1,     // b...b.
    0,     // w...b.
    0,     // .b..b.
    4,     // bb..b.
    -6,    // wb..b.
    0,     // .w..b.
    -6,    // bw..b.
    1,     // ww..b.
    3,     // ..b.b.
    -17,   // b.b.b.
    8,     // w.b.b.
    11,    // .bb.b.
    1,     // bbb.b.
    0,     // wbb.b.
    -14,   // .wb.b.
    9,     // bwb.b.
    -3,    // wwb.b.
    -6,    // ..w.b.
    -14,   // b.w.b.
    4,     // w.w.b.
    1,     // .bw.b.
    7,     // bbw.b.
    11,    // wbw.b.
    7,     // .ww.b.
    1,     // bww.b.
    -4,    // www.b.
    2,     // ...bb.
    0,     // b..bb.
    -2,    // w..bb.
    11,    // .b.bb.
    0,     // bb.bb.
    5,     // wb.bb.
    -7,    // .w.bb.
    -3,    // bw.bb.
    2,     // ww.bb.
    3,     // ..bbb.
    17,    // b.bbb.
    4,     // w.bbb.
    21,    // .bbbb.
    1,     // bbbbb.
    4,     // wbbbb.
    9,     // .wbbb.
    -5,    // bwbbb.
    -2,    // wwbbb.
    2,     // ..wbb.
    -14,   // b.wbb.
    3,     // w.wbb.
    -6,    // .bwbb.
    -4,    // bbwbb.
    4,     // wbwbb.
    0,     // .wwbb.
    -5,    // bwwbb.
    -7,    // wwwbb.
    8,     // ...wb.
    -1,    // b..wb.
    -1,    // w..wb.
    1,     // .b.wb.
    10,    // bb.wb.
    3,     // wb.wb.
    14,    // .w.wb.
    -1,    // bw.wb.
    2,     // ww.wb.
    -2,    // ..bwb.
    2,     // b.bwb.
    -2,    // w.bwb.
    -6,    // .bbwb.
    -10,   // bbbwb.
    -9,    // wbbwb.
    0,     // .wbwb.
    1,     // bwbwb.
    1,     // wwbwb.
    -8,    // ..wwb.
    3,     // b.wwb.
    2,     // w.wwb.
    -4,    // .bwwb.
    7,     // bbwwb.
    14,    // wbwwb.
    -9,    // .wwwb.
    -9,    // bwwwb.
    2,     // wwwwb.
    17,    // ....w.
    0,     // b...w.
    -1,    // w...w.
    0,     // .b..w.
    -1,    // bb..w.
    6,     // wb..w.
    0,     // .w..w.
    6,     // bw..w.
    -4,    // ww..w.
    6,     // ..b.w.
    -4,    // b.b.w.
    14,    // w.b.w.
    -7,    // .bb.w.
    4,     // bbb.w.
    -1,    // wbb.w.
    -1,    // .wb.w.
    -11,   // bwb.w.
    -7,    // wwb.w.
    -3,    // ..w.w.
    -8,    // b.w.w.
    17,    // w.w.w.
    14,    // .bw.w.
    3,     // bbw.w.
    -9,    // wbw.w.
    -11,   // .ww.w.
    0,     // bww.w.
    -1,    // www.w.
    -8,    // ...bw.
    1,     // b..bw.
    1,     // w..bw.
    -14,   // .b.bw.
    -2,    // bb.bw.
    1,     // wb.bw.
    -1,    // .w.bw.
    -3,    // bw.bw.
    -10,   // ww.bw.
    8,     // ..bbw.
    -2,    // b.bbw.
    -3,    // w.bbw.
    9,     // .bbbw.
    -2,    // bbbbw.
    9,     // wbbbw.
    4,     // .wbbw.
    -14,   // bwbbw.
    -7,    // wwbbw.
    2,     // ..wbw.
    2,     // b.wbw.
    -2,    // w.wbw.
    0,     // .bwbw.
    -1,    // bbwbw.
    -1,    // wbwbw.
    6,     // .wwbw.
    9,     // bwwbw.
    10,    // wwwbw.
    -2,    // ...ww.
    2,     // b..ww.
    0,     // w..ww.
    7,     // .b.ww.
    -2,    // bb.ww.
    3,     // wb.ww.
    -11,   // .w.ww.
    -5,    // bw.ww.
    0,     // ww.ww.
    -2,    // ..bww.
    -3,    // b.bww.
    14,    // w.bww.
    0,     // .bbww.
    7,     // bbbww.
    5,     // wbbww.
    6,     // .wbww.
    -4,    // bwbww.
    4,     // wwbww.
    -3,    // ..www.
    -4,    // b.www.
    -17,   // w.www.
    -9,    // .bwww.
    2,     // bbwww.
    5,     // wbwww.
    -21,   // .wwww.
    -4,    // bwwww.
    -1,    // wwwww.
    -4,    // .....b
    -1,    // b....b
    0,     // w....b
    1,     // .b...b
    -6,    // bb...b
    -5,    // wb...b
    0,     // .w...b
    -12,   // bw...b
    15,    // ww...b
    3,     // ..b..b
    -2,    // b.b..b
    9,     // w.b..b
    0,     // .bb..b
    8,     // bbb..b
    -11,   // wbb..b
    1,     // .wb..b
    -1,    // bwb..b
    7,     // wwb..b
    -10,   // ..w..b
    8,     // b.w..b
    4,     // w.w..b
    -1,    // .bw..b
    10,    // bbw..b
    2,     // wbw..b
    2,     // .ww..b
    2,     // bww..b
    -2,    // www..b
    3,     // ...b.b
    -2,    // b..b.b
    -4,    // w..b.b
    -17,   // .b.b.b
    2,     // bb.b.b
    14,    // wb.b.b
    -4,    // .w.b.b
    3,     // bw.b.b
    -4,    // ww.b.b
    6,     // ..bb.b
    -5,    // b.bb.b
    16,    // w.bb.b
    17,    // .bbb.b
    10,    // bbbb.b
    -5,    // wbbb.b
    -2,    // .wbb.b
    0,     // bwbb.b
    2,     // wwbb.b
    1,     // ..wb.b
    -3,    // b.wb.b
    0,     // w.wb.b
    2,     // .bwb.b
    2,     // bbwb.b
    5,     // wbwb.b
    -3,    // .wwb.b
    -13,   // bwwb.b
    -10,   // wwwb.b
    -4,    // ...w.b
    8,     // b..w.b
    -9,    // w..w.b
    -14,   // .b.w.b
    0,     // bb.w.b
    8,     // wb.w.b
    -8,    // .w.w.b
    -6,    // bw.w.b
    -8,    // ww.w.b
    5,     // ..bw.b
    -3,    // b.bw.b
    0,     // w.bw.b
    -14,   // .bbw.b
    4,     // bbbw.b
    -12,   // wbbw.b
    2,     // .wbw.b
    -11,   // bwbw.b
    -3,    // wwbw.b
    -9,    // ..ww.b
    -1,    // b.ww.b
    -16,   // w.ww.b
    3,     // .bww.b
    -2,    // bbww.b
    8,     // wbww.b
    -4,    // .www.b
    7,     // bwww.b
    -8,    // wwww.b
    0,     // ....bb
    -6,    // b...bb
    -15,   // w...bb
    4,     // .b..bb
    -2,    // bb..bb
    6,     // wb..bb
    -1,    // .w..bb
    -10,   // bw..bb
    0,     // ww..bb
    -2,    // ..b.bb
    2,     // b.b.bb
    8,     // w.b.bb
    0,     // .bb.bb
    3,     // bbb.bb
    -2,    // wbb.bb
    -2,    // .wb.bb
    -7,    // bwb.bb
    -1,    // wwb.bb
    -4,    // ..w.bb
    0,     // b.w.bb
    4,     // w.w.bb
    10,    // .bw.bb
    4,     // bbw.bb
    -1,    // wbw.bb
    -2,    // .ww.bb
    -8,    // bww.bb
    2,     // www.bb
    -2,    // ...bbb
    8,     // b..bbb
    2,     // w..bbb
    1,     // .b.bbb
    3,     // bb.bbb
    -11,   // wb.bbb
    4,     // .w.bbb
    -4,    // bw.bbb
    -2,    // ww.bbb
    -2,    // ..bbbb
    10,    // b.bbbb
    8,     // w.bbbb
    1,     // .bbbbb
    1,     // bbbbbb
    -5,    // wbbbbb
    -2,    // .wbbbb
    8,     // bwbbbb
    -6,    // wwbbbb
    -2,    // ..wbbb
    4,     // b.wbbb
    10,    // w.wbbb
    -10,   // .bwbbb
    6,     // bbwbbb
    2,     // wbwbbb
    7,     // .wwbbb
    4,     // bwwbbb
    0,     // wwwbbb
    3,     // ...wbb
    10,    // b..wbb
    -7,    // w..wbb
    7,     // .b.wbb
    4,     // bb.wbb
    7,     // wb.wbb
    3,     // .w.wbb
    -8,    // bw.wbb
    1,     // ww.wbb
    1,     // ..bwbb
    2,     // b.bwbb
    3,     // w.bwbb
    -4,    // .bbwbb
    6,     // bbbwbb
    -9,    // wbbwbb
    -1,    // .wbwbb
    2,     // bwbwbb
    0,     // wwbwbb
    -1,    // ..wwbb
    -2,    // b.wwbb
    -2,    // w.wwbb
    7,     // .bwwbb
    -9,    // bbwwbb
    -1,    // wbwwbb
    2,     // .wwwbb
    6,     // bwwwbb
    6,     // wwwwbb
    -2,    // ....wb
    -12,   // b...wb
    5,     // w...wb
    -6,    // .b..wb
    -10,   // bb..wb
    0,     // wb..wb
    6,     // .w..wb
    -2,    // bw..wb
    -6,    // ww..wb
    -9,    // ..b.wb
    3,     // b.b.wb
    -8,    // w.b.wb
    -3,    // .bb.wb
    -4,    // bbb.wb
    -6,    // wbb.wb
    -3,    // .wb.wb
    -3,    // bwb.wb
    -7,    // wwb.wb
    1,     // ..w.wb
    -6,    // b.w.wb
    -14,   // w.w.wb
    -1,    // .bw.wb
    -8,    // bbw.wb
    3,     // wbw.wb
    -5,    // .ww.wb
    -4,    // bww.wb
    11,    // www.wb
    -15,   // ...bwb
    -1,    // b..bwb
    -2,    // w..bwb
    9,     // .b.bwb
    -7,    // bb.bwb
    -3,    // wb.bwb
    -11,   // .w.bwb
    -3,    // bw.bwb
    1,     // ww.bwb
    10,    // ..bbwb
    0,     // b.bbwb
    -8,    // w.bbwb
    -5,    // .bbbwb
    8,     // bbbbwb
    -3,    // wbbbwb
    -14,   // .wbbwb
    -6,    // bwbbwb
    1,     // wwbbwb
    -11,   // ..wbwb
    -11,   // b.wbwb
    -5,    // w.wbwb
    1,     // .bwbwb
    2,     // bbwbwb
    0,     // wbwbwb
    -4,    // .wwbwb
    -1,    // bwwbwb
    -2,    // wwwbwb
    8,     // ...wwb
    2,     // b..wwb
    11,    // w..wwb
    1,     // .b.wwb
    -8,    // bb.wwb
    6,     // wb.wwb
    0,     // .w.wwb
    -4,    // bw.wwb
    2,     // ww.wwb
    -14,   // ..bwwb
    -13,   // b.bwwb
    12,    // w.bwwb
    -5,    // .bbwwb
    4,     // bbbwwb
    0,     // wbbwwb
    9,     // .wbwwb
    -1,    // bwbwwb
    9,     // wwbwwb
    4,     // ..wwwb
    7,     // b.wwwb
    5,     // w.wwwb
    -9,    // .bwwwb
    6,     // bbwwwb
    3,     // wbwwwb
    -4,    // .wwwwb
    -2,    // bwwwwb
    5,     // wwwwwb
    4,     // .....w
    0,     // b....w
    1,     // w....w
    0,     // .b...w
    -15,   // bb...w
    12,    // wb...w
    -1,    // .w...w
    5,     // bw...w
    6,     // ww...w
    10,    // ..b..w
    -4,    // b.b..w
    -8,    // w.b..w
    -2,    // .bb..w
    2,     // bbb..w
    -2,    // wbb..w
    1,     // .wb..w
    -2,    // bwb..w
    -10,   // wwb..w
    -3,    // ..w..w
    -9,    // b.w..w
    2,     // w.w..w
    -1,    // .bw..w
    -7,    // bbw..w
    1,     // wbw..w
    0,     // .ww..w
    11,    // bww..w
    -8,    // www..w
    4,     // ...b.w
    9,     // b..b.w
    -8,    // w..b.w
    8,     // .b.b.w
    8,     // bb.b.w
    6,     // wb.b.w
    14,    // .w.b.w
    -8,    // bw.b.w
    0,     // ww.b.w
    9,     // ..bb.w
    16,    // b.bb.w
    1,     // w.bb.w
    4,     // .bbb.w
    8,     // bbbb.w
    -7,    // wbbb.w
    -3,    // .wbb.w
    -8,    // bwbb.w
    2,     // wwbb.w
    -5,    // ..wb.w
    0,     // b.wb.w
    3,     // w.wb.w
    -2,    // .bwb.w
    3,     // bbwb.w
    11,    // wbwb.w
    14,    // .wwb.w
    12,    // bwwb.w
    -4,    // wwwb.w
    -3,    // ...w.w
    4,     // b..w.w
    2,     // w..w.w
    4,     // .b.w.w
    4,     // bb.w.w
    -3,    // wb.w.w
    17,    // .w.w.w
    -14,   // bw.w.w
    -2,    // ww.w.w
    -1,    // ..bw.w
    0,     // b.bw.w
    3,     // w.bw.w
    3,     // .bbw.w
    10,    // bbbw.w
    13,    // wbbw.w
    -2,    // .wbw.w
    -5,    // bwbw.w
    -2,    // wwbw.w
    -6,    // ..ww.w
    -16,   // b.ww.w
    5,     // w.ww.w
    2,     // .bww.w
    -2,    // bbww.w
    0,     // wbww.w
    -17,   // .www.w
    5,     // bwww.w
    -10,   // wwww.w
    2,     // ....bw
    -5,    // b...bw
    12,    // w...bw
    -6,    // .b..bw
    6,     // bb..bw
    2,     // wb..bw
    6,     // .w..bw
    0,     // bw..bw
    10,    // ww..bw
    -1,    // ..b.bw
    14,    // b.b.bw
    6,     // w.b.bw
    5,     // .bb.bw
    -11,   // bbb.bw
    4,     // wbb.bw
    1,     // .wb.bw
    -3,    // bwb.bw
    8,     // wwb.bw
    9,     // ..w.bw
    8,     // b.w.bw
    -3,    // w.w.bw
    3,     // .bw.bw
    7,     // bbw.bw
    3,     // wbw.bw
    3,     // .ww.bw
    6,     // bww.bw
    4,     // www.bw
    -8,    // ...bbw
    -11,   // b..bbw
    -2,    // w..bbw
    0,     // .b.bbw
    -2,    // bb.bbw
    4,     // wb.bbw
    -1,    // .w.bbw
    -6,    // bw.bbw
    8,     // ww.bbw
    -4,    // ..bbbw
    -5,    // b.bbbw
    -7,    // w.bbbw
    4,     // .bbbbw
    -5,    // bbbbbw
    2,     // wbbbbw
    9,     // .wbbbw
    -3,    // bwbbbw
    -6,    // wwbbbw
    14,    // ..wbbw
    -12,   // b.wbbw
    13,    // w.wbbw
    -9,    // .bwbbw
    -9,    // bbwbbw
    1,     // wbwbbw
    5,     // .wwbbw
    0,     // bwwbbw
    -4,    // wwwbbw
    15,    // ...wbw
    2,     // b..wbw
    1,     // w..wbw
    11,    // .b.wbw
    -1,    // bb.wbw
    3,     // wb.wbw
    -9,    // .w.wbw
    3,     // bw.wbw
    7,     // ww.wbw
    11,    // ..bwbw
    5,     // b.bwbw
    11,    // w.bwbw
    4,     // .bbwbw
    2,     // bbbwbw
    1,     // wbbwbw
    -1,    // .wbwbw
    0,     // bwbwbw
    -2,    // wwbwbw
    -10,   // ..wwbw
    8,     // b.wwbw
    0,     // w.wwbw
    14,    // .bwwbw
    -1,    // bbwwbw
    6,     // wbwwbw
    5,     // .wwwbw
    3,     // bwwwbw
    -8,    // wwwwbw
    0,     // ....ww
    15,    // b...ww
    6,     // w...ww
    1,     // .b..ww
    0,     // bb..ww
    10,    // wb..ww
    -4,    // .w..ww
    -6,    // bw..ww
    2,     // ww..ww
    4,     // ..b.ww
    -4,    // b.b.ww
    0,     // w.b.ww
    2,     // .bb.ww
    -2,    // bbb.ww
    8,     // wbb.ww
    -10,   // .wb.ww
    1,     // bwb.ww
    -4,    // wwb.ww
    2,     // ..w.ww
    -8,    // b.w.ww
    -2,    // w.w.ww
    2,     // .bw.ww
    1,     // bbw.ww
    7,     // wbw.ww
    0,     // .ww.ww
    2,     // bww.ww
    -3,    // www.ww
    -3,    // ...bww
    7,     // b..bww
    -10,   // w..bww
    -3,    // .b.bww
    -1,    // bb.bww
    8,     // wb.bww
    -7,    // .w.bww
    -7,    // bw.bww
    -4,    // ww.bww
    1,     // ..bbww
    2,     // b.bbww
    2,     // w.bbww
    -2,    // .bbbww
    -6,    // bbbbww
    -6,    // wbbbww
    -7,    // .wbbww
    1,     // bwbbww
    9,     // wwbbww
    -1,    // ..wbww
    -3,    // b.wbww
    -2,    // w.wbww
    1,     // .bwbww
    0,     // bbwbww
    -2,    // wbwbww
    4,     // .wwbww
    9,     // bwwbww
    -6,    // wwwbww
    2,     // ...www
    -2,    // b..www
    -8,    // w..www
    -4,    // .b.www
    2,     // bb.www
    4,     // wb.www
    -1,    // .w.www
    11,    // bw.www
    -3,    // ww.www
    2,     // ..bwww
    -10,   // b.bwww
    -4,    // w.bwww
    -7,    // .bbwww
    0,     // bbbwww
    -4,    // wbbwww
    10,    // .wbwww
    -2,    // bwbwww
    -6,    // wwbwww
    2,     // ..wwww
    -8,    // b.wwww
    -10,   // w.wwww
    2,     // .bwwww
    6,     // bbwwww
    -8,    // wbwwww
    -1,    // .wwwww
    5,     // bwwwww
    -1,    // wwwwww
    0,     // ccc
    -3,    // cc
    1,     // c
    16,    // ttt
    -1,    // tt
    14,    // t
    5,     // ct
    -7,    // cct
    -7,    // ctt
].into_boxed_slice()
