vec![
    0,     // .......
    1,     // b......
    -1,    // w......
    -5,    // .b.....
    11,    // bb.....
    -16,   // wb.....
    5,     // .w.....
    16,    // bw.....
    -11,   // ww.....
    -9,    // ..b....
    81,    // b.b....
    -30,   // w.b....
    9,     // .bb....
    140,   // bbb....
    -76,   // wbb....
    -9,    // .wb....
    39,    // bwb....
    64,    // wwb....
    9,     // ..w....
    30,    // b.w....
    -81,   // w.w....
    9,     // .bw....
    -64,   // bbw....
    -39,   // wbw....
    -9,    // .ww....
    76,    // bww....
    -140,  // www....
    -9,    // ...b...
    -6,    // b..b...
    -7,    // w..b...
    -34,   // .b.b...
    138,   // bb.b...
    -48,   // wb.b...
    14,    // .w.b...
    21,    // bw.b...
    -38,   // ww.b...
    -17,   // ..bb...
    33,    // b.bb...
    32,    // w.bb...
    68,    // .bbb...
    396,   // bbbb...
    -116,  // wbbb...
    68,    // .wbb...
    2,     // bwbb...
    17,    // wwbb...
    8,     // ..wb...
    45,    // b.wb...
    -55,   // w.wb...
    -35,   // .bwb...
    -54,   // bbwb...
    4,     // wbwb...
    -31,   // .wwb...
    29,    // bwwb...
    -23,   // wwwb...
    9,     // ...w...
    7,     // b..w...
    6,     // w..w...
    -14,   // .b.w...
    38,    // bb.w...
    -21,   // wb.w...
    34,    // .w.w...
    48,    // bw.w...
    -138,  // ww.w...
    -8,    // ..bw...
    55,    // b.bw...
    -45,   // w.bw...
    31,    // .bbw...
    23,    // bbbw...
    -29,   // wbbw...
    35,    // .wbw...
    -4,    // bwbw...
    54,    // wwbw...
    17,    // ..ww...
    -32,   // b.ww...
    -33,   // w.ww...
    -68,   // .bww...
    -17,   // bbww...
    -2,    // wbww...
    -68,   // .www...
    116,   // bwww...
    -396,  // wwww...
    -9,    // ....b..
    18,    // b...b..
    -20,   // w...b..
    -7,    // .b..b..
    6,     // bb..b..
    36,    // wb..b..
    6,     // .w..b..
    13,    // bw..b..
    59,    // ww..b..
    -34,   // ..b.b..
    16,    // b.b.b..
    -62,   // w.b.b..
    -71,   // .bb.b..
    96,    // bbb.b..
    -42,   // wbb.b..
    -15,   // .wb.b..
    -76,   // bwb.b..
    -12,   // wwb.b..
    0,     // ..w.b..
    30,    // b.w.b..
    -61,   // w.w.b..
    -21,   // .bw.b..
    -36,   // bbw.b..
    -29,   // wbw.b..
    38,    // .ww.b..
    11,    // bww.b..
    -31,   // www.b..
    -17,   // ...bb..
    -36,   // b..bb..
    26,    // w..bb..
    6,     // .b.bb..
    11,    // bb.bb..
    0,     // wb.bb..
    -80,   // .w.bb..
    21,    // bw.bb..
    -17,   // ww.bb..
    34,    // ..bbb..
    71,    // b.bbb..
    -32,   // w.bbb..
    244,   // .bbbb..
    44,    // bbbbb..
    61,    // wbbbb..
    -53,   // .wbbb..
    -31,   // bwbbb..
    -24,   // wwbbb..
    -70,   // ..wbb..
    -26,   // b.wbb..
    -27,   // w.wbb..
    -25,   // .bwbb..
    -19,   // bbwbb..
    59,    // wbwbb..
    14,    // .wwbb..
    -92,   // bwwbb..
    -60,   // wwwbb..
    -8,    // ...wb..
    86,    // b..wb..
    41,    // w..wb..
    -43,   // .b.wb..
    -58,   // bb.wb..
    2,     // wb.wb..
    52,    // .w.wb..
    25,    // bw.wb..
    9,     // ww.wb..
    6,     // ..bwb..
    18,    // b.bwb..
    6,     // w.bwb..
    4,     // .bbwb..
    -167,  // bbbwb..
    48,    // wbbwb..
    37,    // .wbwb..
    -1,    // bwbwb..
    -44,   // wwbwb..
    70,    // ..wwb..
    14,    // b.wwb..
    68,    // w.wwb..
    1,     // .bwwb..
    85,    // bbwwb..
    -5,    // wbwwb..
    -72,   // .wwwb..
    1,     // bwwwb..
    -51,   // wwwwb..
    9,     // ....w..
    20,    // b...w..
    -18,   // w...w..
    -6,    // .b..w..
    -59,   // bb..w..
    -13,   // wb..w..
    7,     // .w..w..
    -36,   // bw..w..
    -6,    // ww..w..
    0,     // ..b.w..
    61,    // b.b.w..
    -30,   // w.b.w..
    -38,   // .bb.w..
    31,    // bbb.w..
    -11,   // wbb.w..
    21,    // .wb.w..
    29,    // bwb.w..
    36,    // wwb.w..
    34,    // ..w.w..
    62,    // b.w.w..
    -16,   // w.w.w..
    15,    // .bw.w..
    12,    // bbw.w..
    76,    // wbw.w..
    71,    // .ww.w..
    42,    // bww.w..
    -96,   // www.w..
    8,     // ...bw..
    -41,   // b..bw..
    -86,   // w..bw..
    -52,   // .b.bw..
    -9,    // bb.bw..
    -25,   // wb.bw..
    43,    // .w.bw..
    -2,    // bw.bw..
    58,    // ww.bw..
    -70,   // ..bbw..
    -68,   // b.bbw..
    -14,   // w.bbw..
    72,    // .bbbw..
    51,    // bbbbw..
    -1,    // wbbbw..
    -1,    // .wbbw..
    5,     // bwbbw..
    -85,   // wwbbw..
    -6,    // ..wbw..
    -6,    // b.wbw..
    -18,   // w.wbw..
    -37,   // .bwbw..
    44,    // bbwbw..
    1,     // wbwbw..
    -4,    // .wwbw..
    -48,   // bwwbw..
    167,   // wwwbw..
    17,    // ...ww..
    -26,   // b..ww..
    36,    // w..ww..
    80,    // .b.ww..
    17,    // bb.ww..
    -21,   // wb.ww..
    -6,    // .w.ww..
    0,     // bw.ww..
    -11,   // ww.ww..
    70,    // ..bww..
    27,    // b.bww..
    26,    // w.bww..
    -14,   // .bbww..
    60,    // bbbww..
    92,    // wbbww..
    25,    // .wbww..
    -59,   // bwbww..
    19,    // wwbww..
    -34,   // ..www..
    32,    // b.www..
    -71,   // w.www..
    53,    // .bwww..
    24,    // bbwww..
    31,    // wbwww..
    -244,  // .wwww..
    -61,   // bwwww..
    -44,   // wwwww..
    -5,    // .....b.
    7,     // b....b.
    -48,   // w....b.
    -30,   // .b...b.
    11,    // bb...b.
    7,     // wb...b.
    0,     // .w...b.
    18,    // bw...b.
    -14,   // ww...b.
    -7,    // ..b..b.
    27,    // b.b..b.
    -47,   // w.b..b.
    7,     // .bb..b.
    28,    // bbb..b.
    102,   // wbb..b.
    -15,   // .wb..b.
    5,     // bwb..b.
    37,    // wwb..b.
    -6,    // ..w..b.
    -25,   // b.w..b.
    -9,    // w.w..b.
    -29,   // .bw..b.
    -8,    // bbw..b.
    -76,   // wbw..b.
    -24,   // .ww..b.
    -6,    // bww..b.
    -40,   // www..b.
    -34,   // ...b.b.
    -58,   // b..b.b.
    -29,   // w..b.b.
    -11,   // .b.b.b.
    -54,   // bb.b.b.
    7,     // wb.b.b.
    -36,   // .w.b.b.
    4,     // bw.b.b.
    -29,   // ww.b.b.
    6,     // ..bb.b.
    -31,   // b.bb.b.
    97,    // w.bb.b.
    55,    // .bbb.b.
    -58,   // bbbb.b.
    81,    // wbbb.b.
    3,     // .wbb.b.
    11,    // bwbb.b.
    -6,    // wwbb.b.
    -52,   // ..wb.b.
    -37,   // b.wb.b.
    -64,   // w.wb.b.
    30,    // .bwb.b.
    23,    // bbwb.b.
    25,    // wbwb.b.
    17,    // .wwb.b.
    28,    // bwwb.b.
    48,    // wwwb.b.
    -14,   // ...w.b.
    -38,   // b..w.b.
    2,     // w..w.b.
    -6,    // .b.w.b.
    -71,   // bb.w.b.
    -30,   // wb.w.b.
    36,    // .w.w.b.
    48,    // bw.w.b.
    -105,  // ww.w.b.
    -43,   // ..bw.b.
    20,    // b.bw.b.
    33,    // w.bw.b.
    42,    // .bbw.b.
    -50,   // bbbw.b.
    -80,   // wbbw.b.
    39,    // .wbw.b.
    21,    // bwbw.b.
    16,    // wwbw.b.
    80,    // ..ww.b.
    0,     // b.ww.b.
    -72,   // w.ww.b.
    43,    // .bww.b.
    -9,    // bbww.b.
    111,   // wbww.b.
    -19,   // .www.b.
    37,    // bwww.b.
    -163,  // wwww.b.
    9,     // ....bb.
    -29,   // b...bb.
    30,    // w...bb.
    7,     // .b..bb.
    4,     // bb..bb.
    -11,   // wb..bb.
    24,    // .w..bb.
    15,    // bw..bb.
    -63,   // ww..bb.
    -71,   // ..b.bb.
    -12,   // b.b.bb.
    4,     // w.b.bb.
    17,    // .bb.bb.
    45,    // bbb.bb.
    -37,   // wbb.bb.
    -69,   // .wb.bb.
    -60,   // bwb.bb.
    -37,   // wwb.bb.
    -38,   // ..w.bb.
    -48,   // b.w.bb.
    29,    // w.w.bb.
    -20,   // .bw.bb.
    -6,    // bbw.bb.
    -72,   // wbw.bb.
    0,     // .ww.bb.
    52,    // bww.bb.
    -48,   // www.bb.
    68,    // ...bbb.
    38,    // b..bbb.
    -21,   // w..bbb.
    55,    // .b.bbb.
    -31,   // bb.bbb.
    72,    // wb.bbb.
    19,    // .w.bbb.
    95,    // bw.bbb.
    33,    // ww.bbb.
    244,   // ..bbbb.
    54,    // b.bbbb.
    65,    // w.bbbb.
    -59,   // .bbbbb.
    -14,   // bbbbbb.
    -32,   // wbbbbb.
    101,   // .wbbbb.
    -5,    // bwbbbb.
    -15,   // wwbbbb.
    72,    // ..wbbb.
    -16,   // b.wbbb.
    -1,    // w.wbbb.
    32,    // .bwbbb.
    -91,   // bbwbbb.
    63,    // wbwbbb.
    8,     // .wwbbb.
    40,    // bwwbbb.
    0,     // wwwbbb.
    31,    // ...wbb.
    17,    // b..wbb.
    4,     // w..wbb.
    42,    // .b.wbb.
    61,    // bb.wbb.
    76,    // wb.wbb.
    -17,   // .w.wbb.
    -30,   // bw.wbb.
    -58,   // ww.wbb.
    4,     // ..bwbb.
    -135,  // b.bwbb.
    -30,   // w.bwbb.
    23,    // .bbwbb.
    -2,    // bbbwbb.
    -54,   // wbbwbb.
    2,     // .wbwbb.
    -56,   // bwbwbb.
    126,   // wwbwbb.
    -14,   // ..wwbb.
    -46,   // b.wwbb.
    9,     // w.wwbb.
    16,    // .bwwbb.
    -105,  // bbwwbb.
    20,    // wbwwbb.
    -8,    // .wwwbb.
    54,    // bwwwbb.
    11,    // wwwwbb.
    9,     // ....wb.
    -19,   // b...wb.
    29,    // w...wb.
    -29,   // .b..wb.
    40,    // bb..wb.
    -78,   // wb..wb.
    15,    // .w..wb.
    -19,   // bw..wb.
    -68,   // ww..wb.
    -21,   // ..b.wb.
    -39,   // b.b.wb.
    30,    // w.b.wb.
    -20,   // .bb.wb.
    58,    // bbb.wb.
    10,    // wbb.wb.
    0,     // .wb.wb.
    -16,   // bwb.wb.
    7,     // wwb.wb.
    15,    // ..w.wb.
    -2,    // b.w.wb.
    62,    // w.w.wb.
    50,    // .bw.wb.
    -7,    // bbw.wb.
    -7,    // wbw.wb.
    69,    // .ww.wb.
    -60,   // bww.wb.
    -1,    // www.wb.
    -35,   // ...bwb.
    29,    // b..bwb.
    47,    // w..bwb.
    30,    // .b.bwb.
    16,    // bb.bwb.
    -89,   // wb.bwb.
    -39,   // .w.bwb.
    -15,   // bw.bwb.
    -26,   // ww.bwb.
    -25,   // ..bbwb.
    -3,    // b.bbwb.
    -19,   // w.bbwb.
    32,    // .bbbwb.
    -63,   // bbbbwb.
    -18,   // wbbbwb.
    15,    // .wbbwb.
    -33,   // bwbbwb.
    103,   // wwbbwb.
    -37,   // ..wbwb.
    -34,   // b.wbwb.
    -6,    // w.wbwb.
    8,     // .bwbwb.
    4,     // bbwbwb.
    -36,   // wbwbwb.
    -2,    // .wwbwb.
    105,   // bwwbwb.
    30,    // wwwbwb.
    -68,   // ...wwb.
    -22,   // b..wwb.
    6,     // w..wwb.
    43,    // .b.wwb.
    -85,   // bb.wwb.
    -16,   // wb.wwb.
    -3,    // .w.wwb.
    3,     // bw.wwb.
    -57,   // ww.wwb.
    1,     // ..bwwb.
    -49,   // b.bwwb.
    -50,   // w.bwwb.
    16,    // .bbwwb.
    -30,   // bbbwwb.
    -54,   // wbbwwb.
    -15,   // .wbwwb.
    -53,   // bwbwwb.
    -20,   // wwbwwb.
    53,    // ..wwwb.
    106,   // b.wwwb.
    -98,   // w.wwwb.
    1,     // .bwwwb.
    22,    // bbwwwb.
    -80,   // wbwwwb.
    -101,  // .wwwwb.
    124,   // bwwwwb.
    -98,   // wwwwwb.
    5,     // .....w.
    48,    // b....w.
    -7,    // w....w.
    0,     // .b...w.
    14,    // bb...w.
    -18,   // wb...w.
    30,    // .w...w.
    -7,    // bw...w.
    -11,   // ww...w.
    6,     // ..b..w.
    9,     // b.b..w.
    25,    // w.b..w.
    24,    // .bb..w.
    40,    // bbb..w.
    6,     // wbb..w.
    29,    // .wb..w.
    76,    // bwb..w.
    8,     // wwb..w.
    7,     // ..w..w.
    47,    // b.w..w.
    -27,   // w.w..w.
    15,    // .bw..w.
    -37,   // bbw..w.
    -5,    // wbw..w.
    -7,    // .ww..w.
    -102,  // bww..w.
    -28,   // www..w.
    14,    // ...b.w.
    -2,    // b..b.w.
    38,    // w..b.w.
    -36,   // .b.b.w.
    105,   // bb.b.w.
    -48,   // wb.b.w.
    6,     // .w.b.w.
    30,    // bw.b.w.
    71,    // ww.b.w.
    -80,   // ..bb.w.
    72,    // b.bb.w.
    0,     // w.bb.w.
    19,    // .bbb.w.
    163,   // bbbb.w.
    -37,   // wbbb.w.
    -43,   // .wbb.w.
    -111,  // bwbb.w.
    9,     // wwbb.w.
    43,    // ..wb.w.
    -33,   // b.wb.w.
    -20,   // w.wb.w.
    -39,   // .bwb.w.
    -16,   // bbwb.w.
    -21,   // wbwb.w.
    -42,   // .wwb.w.
    80,    // bwwb.w.
    50,    // wwwb.w.
    34,    // ...w.w.
    29,    // b..w.w.
    58,    // w..w.w.
    36,    // .b.w.w.
    29,    // bb.w.w.
    -4,    // wb.w.w.
    11,    // .w.w.w.
    -7,    // bw.w.w.
    54,    // ww.w.w.
    52,    // ..bw.w.
    64,    // b.bw.w.
    37,    // w.bw.w.
    -17,   // .bbw.w.
    -48,   // bbbw.w.
    -28,   // wbbw.w.
    -30,   // .wbw.w.
    -25,   // bwbw.w.
    -23,   // wwbw.w.
    -6,    // ..ww.w.
    -97,   // b.ww.w.
    31,    // w.ww.w.
    -3,    // .bww.w.
    6,     // bbww.w.
    -11,   // wbww.w.
    -55,   // .www.w.
    -81,   // bwww.w.
    58,    // wwww.w.
    -9,    // ....bw.
    -29,   // b...bw.
    19,    // w...bw.
    -15,   // .b..bw.
    68,    // bb..bw.
    19,    // wb..bw.
    29,    // .w..bw.
    78,    // bw..bw.
    -40,   // ww..bw.
    -15,   // ..b.bw.
    -62,   // b.b.bw.
    2,     // w.b.bw.
    -69,   // .bb.bw.
    1,     // bbb.bw.
    60,    // wbb.bw.
    -50,   // .wb.bw.
    7,     // bwb.bw.
    7,     // wwb.bw.
    21,    // ..w.bw.
    -30,   // b.w.bw.
    39,    // w.w.bw.
    0,     // .bw.bw.
    -7,    // bbw.bw.
    16,    // wbw.bw.
    20,    // .ww.bw.
    -10,   // bww.bw.
    -58,   // www.bw.
    68,    // ...bbw.
    -6,    // b..bbw.
    22,    // w..bbw.
    3,     // .b.bbw.
    57,    // bb.bbw.
    -3,    // wb.bbw.
    -43,   // .w.bbw.
    16,    // bw.bbw.
    85,    // ww.bbw.
    -53,   // ..bbbw.
    98,    // b.bbbw.
    -106,  // w.bbbw.
    101,   // .bbbbw.
    98,    // bbbbbw.
    -124,  // wbbbbw.
    -1,    // .wbbbw.
    80,    // bwbbbw.
    -22,   // wwbbbw.
    -1,    // ..wbbw.
    50,    // b.wbbw.
    49,    // w.wbbw.
    15,    // .bwbbw.
    20,    // bbwbbw.
    53,    // wbwbbw.
    -16,   // .wwbbw.
    54,    // bwwbbw.
    30,    // wwwbbw.
    35,    // ...wbw.
    -47,   // b..wbw.
    -29,   // w..wbw.
    39,    // .b.wbw.
    26,    // bb.wbw.
    15,    // wb.wbw.
    -30,   // .w.wbw.
    89,    // bw.wbw.
    -16,   // ww.wbw.
    37,    // ..bwbw.
    6,     // b.bwbw.
    34,    // w.bwbw.
    2,     // .bbwbw.
    -30,   // bbbwbw.
    -105,  // wbbwbw.
    -8,    // .wbwbw.
    36,    // bwbwbw.
    -4,    // wwbwbw.
    25,    // ..wwbw.
    19,    // b.wwbw.
    3,     // w.wwbw.
    -15,   // .bwwbw.
    -103,  // bbwwbw.
    33,    // wbwwbw.
    -32,   // .wwwbw.
    18,    // bwwwbw.
    63,    // wwwwbw.
    -9,    // ....ww.
    -30,   // b...ww.
    29,    // w...ww.
    -24,   // .b..ww.
    63,    // bb..ww.
    -15,   // wb..ww.
    -7,    // .w..ww.
    11,    // bw..ww.
    -4,    // ww..ww.
    38,    // ..b.ww.
    -29,   // b.b.ww.
    48,    // w.b.ww.
    0,     // .bb.ww.
    48,    // bbb.ww.
    -52,   // wbb.ww.
    20,    // .wb.ww.
    72,    // bwb.ww.
    6,     // wwb.ww.
    71,    // ..w.ww.
    -4,    // b.w.ww.
    12,    // w.w.ww.
    69,    // .bw.ww.
    37,    // bbw.ww.
    60,    // wbw.ww.
    -17,   // .ww.ww.
    37,    // bww.ww.
    -45,   // www.ww.
    -31,   // ...bww.
    -4,    // b..bww.
    -17,   // w..bww.
    17,    // .b.bww.
    58,    // bb.bww.
    30,    // wb.bww.
    -42,   // .w.bww.
    -76,   // bw.bww.
    -61,   // ww.bww.
    14,    // ..bbww.
    -9,    // b.bbww.
    46,    // w.bbww.
    8,     // .bbbww.
    -11,   // bbbbww.
    -54,   // wbbbww.
    -16,   // .wbbww.
    -20,   // bwbbww.
    105,   // wwbbww.
    -4,    // ..wbww.
    30,    // b.wbww.
    135,   // w.wbww.
    -2,    // .bwbww.
    -126,  // bbwbww.
    56,    // wbwbww.
    -23,   // .wwbww.
    54,    // bwwbww.
    2,     // wwwbww.
    -68,   // ...www.
    21,    // b..www.
    -38,   // w..www.
    -19,   // .b.www.
    -33,   // bb.www.
    -95,   // wb.www.
    -55,   // .w.www.
    -72,   // bw.www.
    31,    // ww.www.
    -72,   // ..bwww.
    1,     // b.bwww.
    16,    // w.bwww.
    -8,    // .bbwww.
    0,     // bbbwww.
    -40,   // wbbwww.
    -32,   // .wbwww.
    -63,   // bwbwww.
    91,    // wwbwww.
    -244,  // ..wwww.
    -65,   // b.wwww.
    -54,   // w.wwww.
    -101,  // .bwwww.
    15,    // bbwwww.
    5,     // wbwwww.
    59,    // .wwwww.
    32,    // bwwwww.
    14,    // wwwwww.
    1,     // ......b
    -51,   // b.....b
    0,     // w.....b
    7,     // .b....b
    -5,    // bb....b
    0,     // wb....b
    48,    // .w....b
    41,    // bw....b
    -7,    // ww....b
    18,    // ..b...b
    44,    // b.b...b
    -32,   // w.b...b
    -29,   // .bb...b
    -34,   // bbb...b
    -49,   // wbb...b
    -29,   // .wb...b
    -28,   // bwb...b
    7,     // wwb...b
    20,    // ..w...b
    -12,   // b.w...b
    37,    // w.w...b
    -19,   // .bw...b
    -6,    // bbw...b
    9,     // wbw...b
    -30,   // .ww...b
    -57,   // bww...b
    -39,   // www...b
    -6,    // ...b..b
    0,     // b..b..b
    71,    // w..b..b
    -58,   // .b.b..b
    2,     // bb.b..b
    -29,   // wb.b..b
    -2,    // .w.b..b
    -56,   // bw.b..b
    108,   // ww.b..b
    -36,   // ..bb..b
    -79,   // b.bb..b
    3,     // w.bb..b
    38,    // .bbb..b
    1,     // bbbb..b
    -99,   // wbbb..b
    -6,    // .wbb..b
    141,   // bwbb..b
    -59,   // wwbb..b
    -41,   // ..wb..b
    -3,    // b.wb..b
    23,    // w.wb..b
    29,    // .bwb..b
    -55,   // bbwb..b
    -32,   // wbwb..b
    -4,    // .wwb..b
    -11,   // bwwb..b
    21,    // wwwb..b
    7,     // ...w..b
    -71,   // b..w..b
    -71,   // w..w..b
    -38,   // .b.w..b
    -1,    // bb.w..b
    -39,   // wb.w..b
    29,    // .w.w..b
    -50,   // bw.w..b
    1,     // ww.w..b
    86,    // ..bw..b
    15,    // b.bw..b
    23,    // w.bw..b
    17,    // .bbw..b
    42,    // bbbw..b
    -23,   // wbbw..b
    -47,   // .wbw..b
    -85,   // bwbw..b
    -13,   // wwbw..b
    -26,   // ..ww..b
    -50,   // b.ww..b
    33,    // w.ww..b
    -22,   // .bww..b
    -39,   // bbww..b
    21,    // wbww..b
    21,    // .www..b
    16,    // bwww..b
    -45,   // wwww..b
    81,    // ....b.b
    44,    // b...b.b
    -37,   // w...b.b
    27,    // .b..b.b
    -53,   // bb..b.b
    93,    // wb..b.b
    9,     // .w..b.b
    52,    // bw..b.b
    0,     // ww..b.b
    16,    // ..b.b.b
    19,    // b.b.b.b
    30,    // w.b.b.b
    -12,   // .bb.b.b
    53,    // bbb.b.b
    -17,   // wbb.b.b
    -62,   // .wb.b.b
    -42,   // bwb.b.b
    -71,   // wwb.b.b
    61,    // ..w.b.b
    27,    // b.w.b.b
    0,     // w.w.b.b
    -39,   // .bw.b.b
    12,    // bbw.b.b
    26,    // wbw.b.b
    -29,   // .ww.b.b
    67,    // bww.b.b
    -12,   // www.b.b
    33,    // ...bb.b
    -79,   // b..bb.b
    -33,   // w..bb.b
    -31,   // .b.bb.b
    -50,   // bb.bb.b
    -55,   // wb.bb.b
    72,    // .w.bb.b
    31,    // bw.bb.b
    -42,   // ww.bb.b
    71,    // ..bbb.b
    39,    // b.bbb.b
    -30,   // w.bbb.b
    54,    // .bbbb.b
    -64,   // bbbbb.b
    -1,    // wbbbb.b
    98,    // .wbbb.b
    -41,   // bwbbb.b
    -5,    // wwbbb.b
    -68,   // ..wbb.b
    11,    // b.wbb.b
    93,    // w.wbb.b
    -3,    // .bwbb.b
    -29,   // bbwbb.b
    29,    // wbwbb.b
    -9,    // .wwbb.b
    -73,   // bwwbb.b
    92,    // wwwbb.b
    55,    // ...wb.b
    15,    // b..wb.b
    -23,   // w..wb.b
    20,    // .b.wb.b
    24,    // bb.wb.b
    38,    // wb.wb.b
    64,    // .w.wb.b
    -19,   // bw.wb.b
    38,    // ww.wb.b
    18,    // ..bwb.b
    41,    // b.bwb.b
    7,     // w.bwb.b
    -135,  // .bbwb.b
    -56,   // bbbwb.b
    -52,   // wbbwb.b
    6,     // .wbwb.b
    39,    // bwbwb.b
    66,    // wwbwb.b
    27,    // ..wwb.b
    10,    // b.wwb.b
    -93,   // w.wwb.b
    -49,   // .bwwb.b
    -11,   // bbwwb.b
    1,     // wbwwb.b
    1,     // .wwwb.b
    19,    // bwwwb.b
    27,    // wwwwb.b
    30,    // ....w.b
    -12,   // b...w.b
    32,    // w...w.b
    -25,   // .b..w.b
    9,     // bb..w.b
    113,   // wb..w.b
    47,    // .w..w.b
    20,    // bw..w.b
    -52,   // ww..w.b
    30,    // ..b.w.b
    27,    // b.b.w.b
    0,     // w.b.w.b
    -48,   // .bb.w.b
    17,    // bbb.w.b
    85,    // wbb.w.b
    -30,   // .wb.w.b
    64,    // bwb.w.b
    1,     // wwb.w.b
    62,    // ..w.w.b
    41,    // b.w.w.b
    -30,   // w.w.w.b
    -2,    // .bw.w.b
    -19,   // bbw.w.b
    69,    // wbw.w.b
    -4,    // .ww.w.b
    7,     // bww.w.b
    30,    // www.w.b
    45,    // ...bw.b
    -3,    // b..bw.b
    -23,   // w..bw.b
    -37,   // .b.bw.b
    14,    // bb.bw.b
    46,    // wb.bw.b
    -33,   // .w.bw.b
    53,    // bw.bw.b
    1,     // ww.bw.b
    -26,   // ..bbw.b
    11,    // b.bbw.b
    13,    // w.bbw.b
    -16,   // .bbbw.b
    39,    // bbbbw.b
    -23,   // wbbbw.b
    50,    // .wbbw.b
    37,    // bwbbw.b
    -61,   // wwbbw.b
    -6,    // ..wbw.b
    -33,   // b.wbw.b
    -7,    // w.wbw.b
    -34,   // .bwbw.b
    -31,   // bbwbw.b
    -68,   // wbwbw.b
    30,    // .wwbw.b
    49,    // bwwbw.b
    -100,  // wwwbw.b
    -32,   // ...ww.b
    -50,   // b..ww.b
    -3,    // w..ww.b
    0,     // .b.ww.b
    -6,    // bb.ww.b
    70,    // wb.ww.b
    -97,   // .w.ww.b
    30,    // bw.ww.b
    -35,   // ww.ww.b
    14,    // ..bww.b
    10,    // b.bww.b
    -13,   // w.bww.b
    -46,   // .bbww.b
    51,    // bbbww.b
    66,    // wbbww.b
    19,    // .wbww.b
    44,    // bwbww.b
    -65,   // wwbww.b
    32,    // ..www.b
    -60,   // b.www.b
    30,    // w.www.b
    106,   // .bwww.b
    4,     // bbwww.b
    20,    // wbwww.b
    -65,   // .wwww.b
    -3,    // bwwww.b
    -34,   // wwwww.b
    11,    // .....bb
    -5,    // b....bb
    7,     // w....bb
    11,    // .b...bb
    -32,   // bb...bb
    -41,   // wb...bb
    14,    // .w...bb
    6,     // bw...bb
    0,     // ww...bb
    6,     // ..b..bb
    -53,   // b.b..bb
    52,    // w.b..bb
    4,     // .bb..bb
    76,    // bbb..bb
    -23,   // wbb..bb
    68,    // .wb..bb
    -75,   // bwb..bb
    22,    // wwb..bb
    -59,   // ..w..bb
    9,     // b.w..bb
    0,     // w.w..bb
    40,    // .bw..bb
    21,    // bbw..bb
    2,     // wbw..bb
    63,    // .ww..bb
    2,     // bww..bb
    36,    // www..bb
    138,   // ...b.bb
    2,     // b..b.bb
    -1,    // w..b.bb
    -54,   // .b.b.bb
    15,    // bb.b.bb
    66,    // wb.b.bb
    105,   // .w.b.bb
    -49,   // bw.b.bb
    11,    // ww.b.bb
    11,    // ..bb.bb
    -50,   // b.bb.bb
    35,    // w.bb.bb
    -31,   // .bbb.bb
    -65,   // bbbb.bb
    7,     // wbbb.bb
    57,    // .wbb.bb
    -11,   // bwbb.bb
    -77,   // wwbb.bb
    -9,    // ..wb.bb
    14,    // b.wb.bb
    -38,   // w.wb.bb
    16,    // .bwb.bb
    35,    // bbwb.bb
    7,     // wbwb.bb
    58,    // .wwb.bb
    4,     // bwwb.bb
    -4,    // wwwb.bb
    38,    // ...w.bb
    -1,    // b..w.bb
    -108,  // w..w.bb
    -71,   // .b.w.bb
    109,   // bb.w.bb
    -1,    // wb.w.bb
    29,    // .w.w.bb
    46,    // bw.w.bb
    -11,   // ww.w.bb
    -58,   // ..bw.bb
    24,    // b.bw.bb
    -1,    // w.bw.bb
    61,    // .bbw.bb
    40,    // bbbw.bb
    29,    // wbbw.bb
    26,    // .wbw.bb
    51,    // bwbw.bb
    92,    // wwbw.bb
    17,    // ..ww.bb
    -6,    // b.ww.bb
    42,    // w.ww.bb
    -85,   // .bww.bb
    -45,   // bbww.bb
    -35,   // wbww.bb
    -33,   // .www.bb
    -4,    // bwww.bb
    -49,   // wwww.bb
    140,   // ....bbb
    -34,   // b...bbb
    39,    // w...bbb
    28,    // .b..bbb
    76,    // bb..bbb
    41,    // wb..bbb
    40,    // .w..bbb
    -15,   // bw..bbb
    -36,   // ww..bbb
    96,    // ..b.bbb
    53,    // b.b.bbb
    -30,   // w.b.bbb
    45,    // .bb.bbb
    51,    // bbb.bbb
    -9,    // wbb.bbb
    1,     // .wb.bbb
    -60,   // bwb.bbb
    -59,   // wwb.bbb
    31,    // ..w.bbb
    17,    // b.w.bbb
    12,    // w.w.bbb
    58,    // .bw.bbb
    43,    // bbw.bbb
    -33,   // wbw.bbb
    48,    // .ww.bbb
    -33,   // bww.bbb
    0,     // www.bbb
    396,   // ...bbbb
    1,     // b..bbbb
    45,    // w..bbbb
    -58,   // .b.bbbb
    -65,   // bb.bbbb
    56,    // wb.bbbb
    163,   // .w.bbbb
    80,    // bw.bbbb
    49,    // ww.bbbb
    44,    // ..bbbbb
    -64,   // b.bbbbb
    34,    // w.bbbbb
    -14,   // .bbbbbb
    -41,   // bbbbbbb
    -6,    // wbbbbbb
    98,    // .wbbbbb
    -8,    // bwbbbbb
    48,    // wwbbbbb
    51,    // ..wbbbb
    39,    // b.wbbbb
    -27,   // w.wbbbb
    -63,   // .bwbbbb
    -31,   // bbwbbbb
    60,    // wbwbbbb
    -11,   // .wwbbbb
    -28,   // bwwbbbb
    -77,   // wwwbbbb
    23,    // ...wbbb
    42,    // b..wbbb
    -21,   // w..wbbb
    -50,   // .b.wbbb
    40,    // bb.wbbb
    40,    // wb.wbbb
    -48,   // .w.wbbb
    36,    // bw.wbbb
    4,     // ww.wbbb
    -167,  // ..bwbbb
    -56,   // b.bwbbb
    100,   // w.bwbbb
    -2,    // .bbwbbb
    31,    // bbbwbbb
    -161,  // wbbwbbb
    -30,   // .wbwbbb
    19,    // bwbwbbb
    -2,    // wwbwbbb
    60,    // ..wwbbb
    51,    // b.wwbbb
    -92,   // w.wwbbb
    -30,   // .bwwbbb
    20,    // bbwwbbb
    -35,   // wbwwbbb
    0,     // .wwwbbb
    16,    // bwwwbbb
    77,    // wwwwbbb
    -64,   // ....wbb
    -6,    // b...wbb
    -7,    // w...wbb
    -8,    // .b..wbb
    21,    // bb..wbb
    30,    // wb..wbb
    -37,   // .w..wbb
    63,    // bw..wbb
    -22,   // ww..wbb
    -36,   // ..b.wbb
    12,    // b.b.wbb
    -1,    // w.b.wbb
    -6,    // .bb.wbb
    43,    // bbb.wbb
    -1,    // wbb.wbb
    -7,    // .wb.wbb
    17,    // bwb.wbb
    0,     // wwb.wbb
    12,    // ..w.wbb
    -19,   // b.w.wbb
    71,    // w.w.wbb
    -7,    // .bw.wbb
    -86,   // bbw.wbb
    -93,   // wbw.wbb
    37,    // .ww.wbb
    -9,    // bww.wbb
    59,    // www.wbb
    -54,   // ...bwbb
    -55,   // b..bwbb
    13,    // w..bwbb
    23,    // .b.bwbb
    35,    // bb.bwbb
    43,    // wb.bwbb
    -16,   // .w.bwbb
    -56,   // bw.bwbb
    -92,   // ww.bwbb
    -19,   // ..bbwbb
    -29,   // b.bbwbb
    65,    // w.bbwbb
    -91,   // .bbbwbb
    -31,   // bbbbwbb
    34,    // wbbbwbb
    20,    // .wbbwbb
    19,    // bwbbwbb
    82,    // wwbbwbb
    44,    // ..wbwbb
    -31,   // b.wbwbb
    -66,   // w.wbwbb
    4,     // .bwbwbb
    -33,   // bbwbwbb
    127,   // wbwbwbb
    -126,  // .wwbwbb
    8,     // bwwbwbb
    2,     // wwwbwbb
    -17,   // ...wwbb
    -39,   // b..wwbb
    59,    // w..wwbb
    -9,    // .b.wwbb
    -45,   // bb.wwbb
    -6,    // wb.wwbb
    6,     // .w.wwbb
    81,    // bw.wwbb
    77,    // ww.wwbb
    85,    // ..bwwbb
    -11,   // b.bwwbb
    61,    // w.bwwbb
    -105,  // .bbwwbb
    20,    // bbbwwbb
    16,    // wbbwwbb
    -103,  // .wbwwbb
    -34,   // bwbwwbb
    -82,   // wwbwwbb
    24,    // ..wwwbb
    4,     // b.wwwbb
    5,     // w.wwwbb
    22,    // .bwwwbb
    -4,    // bbwwwbb
    -40,   // wbwwwbb
    15,    // .wwwwbb
    0,     // bwwwwbb
    -48,   // wwwwwbb
    16,    // .....wb
    41,    // b....wb
    0,     // w....wb
    18,    // .b...wb
    6,     // bb...wb
    0,     // wb...wb
    -7,    // .w...wb
    -107,  // bw...wb
    41,    // ww...wb
    13,    // ..b..wb
    52,    // b.b..wb
    -113,  // w.b..wb
    15,    // .bb..wb
    -15,   // bbb..wb
    -56,   // wbb..wb
    78,    // .wb..wb
    -51,   // bwb..wb
    -30,   // wwb..wb
    -36,   // ..w..wb
    20,    // b.w..wb
    -93,   // w.w..wb
    -19,   // .bw..wb
    63,    // bbw..wb
    51,    // wbw..wb
    11,    // .ww..wb
    -54,   // bww..wb
    -41,   // www..wb
    21,    // ...b.wb
    -56,   // b..b.wb
    39,    // w..b.wb
    4,     // .b.b.wb
    -49,   // bb.b.wb
    36,    // wb.b.wb
    30,    // .w.b.wb
    -60,   // bw.b.wb
    1,     // ww.b.wb
    21,    // ..bb.wb
    31,    // b.bb.wb
    -70,   // w.bb.wb
    95,    // .bbb.wb
    80,    // bbbb.wb
    -13,   // wbbb.wb
    16,    // .wbb.wb
    -51,   // bwbb.wb
    6,     // wwbb.wb
    -2,    // ..wb.wb
    53,    // b.wb.wb
    -38,   // w.wb.wb
    -15,   // .bwb.wb
    -56,   // bbwb.wb
    -54,   // wbwb.wb
    -76,   // .wwb.wb
    133,   // bwwb.wb
    -40,   // wwwb.wb
    48,    // ...w.wb
    -50,   // b..w.wb
    29,    // w..w.wb
    48,    // .b.w.wb
    46,    // bb.w.wb
    -36,   // wb.w.wb
    -7,    // .w.w.wb
    8,     // bw.w.wb
    -66,   // ww.w.wb
    25,    // ..bw.wb
    -19,   // b.bw.wb
    -46,   // w.bw.wb
    -30,   // .bbw.wb
    36,    // bbbw.wb
    -32,   // wbbw.wb
    89,    // .wbw.wb
    60,    // bwbw.wb
    -43,   // wwbw.wb
    0,     // ..ww.wb
    30,    // b.ww.wb
    55,    // w.ww.wb
    3,     // .bww.wb
    81,    // bbww.wb
    45,    // wbww.wb
    -72,   // .www.wb
    -80,   // bwww.wb
    -56,   // wwww.wb
    39,    // ....bwb
    -28,   // b...bwb
    -9,    // w...bwb
    5,     // .b..bwb
    -75,   // bb..bwb
    -51,   // wb..bwb
    76,    // .w..bwb
    -51,   // bw..bwb
    -2,    // ww..bwb
    -76,   // ..b.bwb
    -42,   // b.b.bwb
    -69,   // w.b.bwb
    -60,   // .bb.bwb
    -60,   // bbb.bwb
    51,    // wbb.bwb
    7,     // .wb.bwb
    -9,    // bwb.bwb
    93,    // wwb.bwb
    29,    // ..w.bwb
    64,    // b.w.bwb
    -26,   // w.w.bwb
    -16,   // .bw.bwb
    17,    // bbw.bwb
    0,     // wbw.bwb
    72,    // .ww.bwb
    47,    // bww.bwb
    33,    // www.bwb
    2,     // ...bbwb
    141,   // b..bbwb
    -21,   // w..bbwb
    11,    // .b.bbwb
    -11,   // bb.bbwb
    -45,   // wb.bbwb
    -111,  // .w.bbwb
    -51,   // bw.bbwb
    35,    // ww.bbwb
    -31,   // ..bbbwb
    -41,   // b.bbbwb
    -20,   // w.bbbwb
    -5,    // .bbbbwb
    -8,    // bbbbbwb
    -115,  // wbbbbwb
    80,    // .wbbbwb
    66,    // bwbbbwb
    40,    // wwbbbwb
    5,     // ..wbbwb
    37,    // b.wbbwb
    -1,    // w.wbbwb
    -33,   // .bwbbwb
    19,    // bbwbbwb
    88,    // wbwbbwb
    -20,   // .wwbbwb
    -23,   // bwwbbwb
    35,    // wwwbbwb
    -4,    // ...wbwb
    -85,   // b..wbwb
    32,    // w..wbwb
    21,    // .b.wbwb
    51,    // bb.wbwb
    54,    // wb.wbwb
    -25,   // .w.wbwb
    60,    // bw.wbwb
    -7,    // ww.wbwb
    -1,    // ..bwbwb
    39,    // b.bwbwb
    68,    // w.bwbwb
    -56,   // .bbwbwb
    19,    // bbbwbwb
    2,     // wbbwbwb
    36,    // .wbwbwb
    -45,   // bwbwbwb
    -127,  // wwbwbwb
    -59,   // ..wwbwb
    44,    // b.wwbwb
    -29,   // w.wwbwb
    -53,   // .bwwbwb
    -34,   // bbwwbwb
    -88,   // wbwwbwb
    -63,   // .wwwbwb
    0,     // bwwwbwb
    -60,   // wwwwbwb
    76,    // ....wwb
    -57,   // b...wwb
    49,    // w...wwb
    -6,    // .b..wwb
    2,     // bb..wwb
    56,    // wb..wwb
    -102,  // .w..wwb
    -54,   // bw..wwb
    23,    // ww..wwb
    11,    // ..b.wwb
    67,    // b.b.wwb
    -85,   // w.b.wwb
    52,    // .bb.wwb
    -33,   // bbb.wwb
    0,     // wbb.wwb
    -10,   // .wb.wwb
    47,    // bwb.wwb
    1,     // wwb.wwb
    42,    // ..w.wwb
    7,     // b.w.wwb
    17,    // w.w.wwb
    -60,   // .bw.wwb
    -9,    // bbw.wwb
    -51,   // wbw.wwb
    37,    // .ww.wwb
    -66,   // bww.wwb
    9,     // www.wwb
    29,    // ...bwwb
    -11,   // b..bwwb
    23,    // w..bwwb
    28,    // .b.bwwb
    4,     // bb.bwwb
    32,    // wb.bwwb
    80,    // .w.bwwb
    133,   // bw.bwwb
    -29,   // ww.bwwb
    -92,   // ..bbwwb
    -73,   // b.bbwwb
    -66,   // w.bbwwb
    40,    // .bbbwwb
    -28,   // bbbbwwb
    37,    // wbbbwwb
    54,    // .wbbwwb
    -23,   // bwbbwwb
    -16,   // wwbbwwb
    -48,   // ..wbwwb
    49,    // b.wbwwb
    52,    // w.wbwwb
    105,   // .bwbwwb
    8,     // bbwbwwb
    -2,    // wbwbwwb
    54,    // .wwbwwb
    13,    // bwwbwwb
    161,   // wwwbwwb
    116,   // ...wwwb
    16,    // b..wwwb
    99,    // w..wwwb
    37,    // .b.wwwb
    -4,    // bb.wwwb
    13,    // wb.wwwb
    -81,   // .w.wwwb
    -80,   // bw.wwwb
    -7,    // ww.wwwb
    1,     // ..bwwwb
    19,    // b.bwwwb
    23,    // w.bwwwb
    54,    // .bbwwwb
    16,    // bbbwwwb
    -37,   // wbbwwwb
    18,    // .wbwwwb
    0,     // bwbwwwb
    -34,   // wwbwwwb
    -61,   // ..wwwwb
    -3,    // b.wwwwb
    1,     // w.wwwwb
    124,   // .bwwwwb
    0,     // bbwwwwb
    115,   // wbwwwwb
    32,    // .wwwwwb
    6,     // bwwwwwb
    6,     // wwwwwwb
    -1,    // ......w
    0,     // b.....w
    51,    // w.....w
    -48,   // .b....w
    7,     // bb....w
    -41,   // wb....w
    -7,    // .w....w
    0,     // bw....w
    5,     // ww....w
    -20,   // ..b...w
    -37,   // b.b...w
    12,    // w.b...w
    30,    // .bb...w
    39,    // bbb...w
    57,    // wbb...w
    19,    // .wb...w
    -9,    // bwb...w
    6,     // wwb...w
    -18,   // ..w...w
    32,    // b.w...w
    -44,   // w.w...w
    29,    // .bw...w
    -7,    // bbw...w
    28,    // wbw...w
    29,    // .ww...w
    49,    // bww...w
    34,    // www...w
    -7,    // ...b..w
    71,    // b..b..w
    71,    // w..b..w
    -29,   // .b.b..w
    -1,    // bb.b..w
    50,    // wb.b..w
    38,    // .w.b..w
    39,    // bw.b..w
    1,     // ww.b..w
    26,    // ..bb..w
    -33,   // b.bb..w
    50,    // w.bb..w
    -21,   // .bbb..w
    45,    // bbbb..w
    -16,   // wbbb..w
    22,    // .wbb..w
    -21,   // bwbb..w
    39,    // wwbb..w
    -86,   // ..wb..w
    -23,   // b.wb..w
    -15,   // w.wb..w
    47,    // .bwb..w
    13,    // bbwb..w
    85,    // wbwb..w
    -17,   // .wwb..w
    23,    // bwwb..w
    -42,   // wwwb..w
    6,     // ...w..w
    -71,   // b..w..w
    0,     // w..w..w
    2,     // .b.w..w
    -108,  // bb.w..w
    56,    // wb.w..w
    58,    // .w.w..w
    29,    // bw.w..w
    -2,    // ww.w..w
    41,    // ..bw..w
    -23,   // b.bw..w
    3,     // w.bw..w
    4,     // .bbw..w
    -21,   // bbbw..w
    11,    // wbbw..w
    -29,   // .wbw..w
    32,    // bwbw..w
    55,    // wwbw..w
    36,    // ..ww..w
    -3,    // b.ww..w
    79,    // w.ww..w
    6,     // .bww..w
    59,    // bbww..w
    -141,  // wbww..w
    -38,   // .www..w
    99,    // bwww..w
    -1,    // wwww..w
    -30,   // ....b.w
    -32,   // b...b.w
    12,    // w...b.w
    -47,   // .b..b.w
    52,    // bb..b.w
    -20,   // wb..b.w
    25,    // .w..b.w
    -113,  // bw..b.w
    -9,    // ww..b.w
    -62,   // ..b.b.w
    30,    // b.b.b.w
    -41,   // w.b.b.w
    4,     // .bb.b.w
    -30,   // bbb.b.w
    -7,    // wbb.b.w
    2,     // .wb.b.w
    -69,   // bwb.b.w
    19,    // wwb.b.w
    -30,   // ..w.b.w
    0,     // b.w.b.w
    -27,   // w.w.b.w
    30,    // .bw.b.w
    -1,    // bbw.b.w
    -64,   // wbw.b.w
    48,    // .ww.b.w
    -85,   // bww.b.w
    -17,   // www.b.w
    32,    // ...bb.w
    3,     // b..bb.w
    50,    // w..bb.w
    97,    // .b.bb.w
    35,    // bb.bb.w
    -30,   // wb.bb.w
    0,     // .w.bb.w
    -70,   // bw.bb.w
    6,     // ww.bb.w
    -32,   // ..bbb.w
    -30,   // b.bbb.w
    60,    // w.bbb.w
    65,    // .bbbb.w
    34,    // bbbbb.w
    3,     // wbbbb.w
    -106,  // .wbbb.w
    -20,   // bwbbb.w
    -4,    // wwbbb.w
    -14,   // ..wbb.w
    13,    // b.wbb.w
    -10,   // w.wbb.w
    -19,   // .bwbb.w
    65,    // bbwbb.w
    -44,   // wbwbb.w
    46,    // .wwbb.w
    -66,   // bwwbb.w
    -51,   // wwwbb.w
    -45,   // ...wb.w
    23,    // b..wb.w
    3,     // w..wb.w
    33,    // .b.wb.w
    -1,    // bb.wb.w
    -53,   // wb.wb.w
    37,    // .w.wb.w
    -46,   // bw.wb.w
    -14,   // ww.wb.w
    6,     // ..bwb.w
    7,     // b.bwb.w
    33,    // w.bwb.w
    -30,   // .bbwb.w
    100,   // bbbwb.w
    -49,   // wbbwb.w
    34,    // .wbwb.w
    68,    // bwbwb.w
    31,    // wwbwb.w
    26,    // ..wwb.w
    -13,   // b.wwb.w
    -11,   // w.wwb.w
    -50,   // .bwwb.w
    61,    // bbwwb.w
    -37,   // wbwwb.w
    16,    // .wwwb.w
    23,    // bwwwb.w
    -39,   // wwwwb.w
    -81,   // ....w.w
    37,    // b...w.w
    -44,   // w...w.w
    -9,    // .b..w.w
    0,     // bb..w.w
    -52,   // wb..w.w
    -27,   // .w..w.w
    -93,   // bw..w.w
    53,    // ww..w.w
    -61,   // ..b.w.w
    0,     // b.b.w.w
    -27,   // w.b.w.w
    29,    // .bb.w.w
    12,    // bbb.w.w
    -67,   // wbb.w.w
    39,    // .wb.w.w
    -26,   // bwb.w.w
    -12,   // wwb.w.w
    -16,   // ..w.w.w
    -30,   // b.w.w.w
    -19,   // w.w.w.w
    62,    // .bw.w.w
    71,    // bbw.w.w
    42,    // wbw.w.w
    12,    // .ww.w.w
    17,    // bww.w.w
    -53,   // www.w.w
    -55,   // ...bw.w
    23,    // b..bw.w
    -15,   // w..bw.w
    -64,   // .b.bw.w
    -38,   // bb.bw.w
    19,    // wb.bw.w
    -20,   // .w.bw.w
    -38,   // bw.bw.w
    -24,   // ww.bw.w
    -27,   // ..bbw.w
    93,    // b.bbw.w
    -10,   // w.bbw.w
    -1,    // .bbbw.w
    -27,   // bbbbw.w
    -19,   // wbbbw.w
    49,    // .wbbw.w
    -1,    // bwbbw.w
    11,    // wwbbw.w
    -18,   // ..wbw.w
    -7,    // b.wbw.w
    -41,   // w.wbw.w
    -6,    // .bwbw.w
    -66,   // bbwbw.w
    -39,   // wbwbw.w
    135,   // .wwbw.w
    52,    // bwwbw.w
    56,    // wwwbw.w
    -33,   // ...ww.w
    33,    // b..ww.w
    79,    // w..ww.w
    -72,   // .b.ww.w
    42,    // bb.ww.w
    -31,   // wb.ww.w
    31,    // .w.ww.w
    55,    // bw.ww.w
    50,    // ww.ww.w
    68,    // ..bww.w
    -93,   // b.bww.w
    -11,   // w.bww.w
    9,     // .bbww.w
    -92,   // bbbww.w
    73,    // wbbww.w
    3,     // .wbww.w
    -29,   // bwbww.w
    29,    // wwbww.w
    -71,   // ..www.w
    30,    // b.www.w
    -39,   // w.www.w
    -98,   // .bwww.w
    5,     // bbwww.w
    41,    // wbwww.w
    -54,   // .wwww.w
    1,     // bwwww.w
    64,    // wwwww.w
    -16,   // .....bw
    0,     // b....bw
    -41,   // w....bw
    7,     // .b...bw
    -41,   // bb...bw
    107,   // wb...bw
    -18,   // .w...bw
    0,     // bw...bw
    -6,    // ww...bw
    36,    // ..b..bw
    93,    // b.b..bw
    -20,   // w.b..bw
    -11,   // .bb..bw
    41,    // bbb..bw
    54,    // wbb..bw
    19,    // .wb..bw
    -51,   // bwb..bw
    -63,   // wwb..bw
    -13,   // ..w..bw
    113,   // b.w..bw
    -52,   // w.w..bw
    -78,   // .bw..bw
    30,    // bbw..bw
    51,    // wbw..bw
    -15,   // .ww..bw
    56,    // bww..bw
    15,    // www..bw
    -48,   // ...b.bw
    -29,   // b..b.bw
    50,    // w..b.bw
    7,     // .b.b.bw
    66,    // bb.b.bw
    -8,    // wb.b.bw
    -48,   // .w.b.bw
    36,    // bw.b.bw
    -46,   // ww.b.bw
    0,     // ..bb.bw
    -55,   // b.bb.bw
    -30,   // w.bb.bw
    72,    // .bbb.bw
    56,    // bbbb.bw
    80,    // wbbb.bw
    -3,    // .wbb.bw
    -45,   // bwbb.bw
    -81,   // wwbb.bw
    -25,   // ..wb.bw
    46,    // b.wb.bw
    19,    // w.wb.bw
    -89,   // .bwb.bw
    43,    // bbwb.bw
    -60,   // wbwb.bw
    30,    // .wwb.bw
    32,    // bwwb.bw
    -36,   // wwwb.bw
    -21,   // ...w.bw
    -39,   // b..w.bw
    56,    // w..w.bw
    -30,   // .b.w.bw
    -1,    // bb.w.bw
    60,    // wb.w.bw
    -4,    // .w.w.bw
    -36,   // bw.w.bw
    49,    // ww.w.bw
    2,     // ..bw.bw
    38,    // b.bw.bw
    -53,   // w.bw.bw
    76,    // .bbw.bw
    40,    // bbbw.bw
    -133,  // wbbw.bw
    15,    // .wbw.bw
    54,    // bwbw.bw
    56,    // wwbw.bw
    -21,   // ..ww.bw
    70,    // b.ww.bw
    -31,   // w.ww.bw
    -16,   // .bww.bw
    -6,    // bbww.bw
    51,    // wbww.bw
    -95,   // .www.bw
    13,    // bwww.bw
    -80,   // wwww.bw
    -76,   // ....bbw
    -49,   // b...bbw
    57,    // w...bbw
    102,   // .b..bbw
    -23,   // bb..bbw
    54,    // wb..bbw
    6,     // .w..bbw
    -56,   // bw..bbw
    -2,    // ww..bbw
    -42,   // ..b.bbw
    -17,   // b.b.bbw
    -7,    // w.b.bbw
    -37,   // .bb.bbw
    -9,    // bbb.bbw
    66,    // wbb.bbw
    60,    // .wb.bbw
    51,    // bwb.bbw
    9,     // wwb.bbw
    -11,   // ..w.bbw
    85,    // b.w.bbw
    -67,   // w.w.bbw
    10,    // .bw.bbw
    -1,    // bbw.bbw
    -47,   // wbw.bbw
    -52,   // .ww.bbw
    0,     // bww.bbw
    33,    // www.bbw
    -116,  // ...bbbw
    -99,   // b..bbbw
    -16,   // w..bbbw
    81,    // .b.bbbw
    7,     // bb.bbbw
    80,    // wb.bbbw
    -37,   // .w.bbbw
    -13,   // bw.bbbw
    4,     // ww.bbbw
    61,    // ..bbbbw
    -1,    // b.bbbbw
    3,     // w.bbbbw
    -32,   // .bbbbbw
    -6,    // bbbbbbw
    -6,    // wbbbbbw
    -124,  // .wbbbbw
    -115,  // bwbbbbw
    0,     // wwbbbbw
    -1,    // ..wbbbw
    -23,   // b.wbbbw
    -19,   // w.wbbbw
    -18,   // .bwbbbw
    34,    // bbwbbbw
    0,     // wbwbbbw
    -54,   // .wwbbbw
    37,    // bwwbbbw
    -16,   // wwwbbbw
    -29,   // ...wbbw
    -23,   // b..wbbw
    11,    // w..wbbw
    -80,   // .b.wbbw
    29,    // bb.wbbw
    -133,  // wb.wbbw
    -28,   // .w.wbbw
    -32,   // bw.wbbw
    -4,    // ww.wbbw
    48,    // ..bwbbw
    -52,   // b.bwbbw
    -49,   // w.bwbbw
    -54,   // .bbwbbw
    -161,  // bbbwbbw
    -13,   // wbbwbbw
    -105,  // .wbwbbw
    2,     // bwbwbbw
    -8,    // wwbwbbw
    92,    // ..wwbbw
    66,    // b.wwbbw
    73,    // w.wwbbw
    -54,   // .bwwbbw
    16,    // bbwwbbw
    23,    // wbwwbbw
    -40,   // .wwwbbw
    -37,   // bwwwbbw
    28,    // wwwwbbw
    -39,   // ....wbw
    9,     // b...wbw
    28,    // w...wbw
    -76,   // .b..wbw
    2,     // bb..wbw
    51,    // wb..wbw
    -5,    // .w..wbw
    51,    // bw..wbw
    75,    // ww..wbw
    -29,   // ..b.wbw
    26,    // b.b.wbw
    -64,   // w.b.wbw
    -72,   // .bb.wbw
    -33,   // bbb.wbw
    -47,   // wbb.wbw
    16,    // .wb.wbw
    0,     // bwb.wbw
    -17,   // wwb.wbw
    76,    // ..w.wbw
    69,    // b.w.wbw
    42,    // w.w.wbw
    -7,    // .bw.wbw
    -93,   // bbw.wbw
    9,     // wbw.wbw
    60,    // .ww.wbw
    -51,   // bww.wbw
    60,    // www.wbw
    4,     // ...bwbw
    -32,   // b..bwbw
    85,    // w..bwbw
    25,    // .b.bwbw
    7,     // bb.bwbw
    -60,   // wb.bwbw
    -21,   // .w.bwbw
    -54,   // bw.bwbw
    -51,   // ww.bwbw
    59,    // ..bbwbw
    29,    // b.bbwbw
    -44,   // w.bbwbw
    63,    // .bbbwbw
    60,    // bbbbwbw
    0,     // wbbbwbw
    53,    // .wbbwbw
    88,    // bwbbwbw
    34,    // wwbbwbw
    1,     // ..wbwbw
    -68,   // b.wbwbw
    -39,   // w.wbwbw
    -36,   // .bwbwbw
    127,   // bbwbwbw
    45,    // wbwbwbw
    56,    // .wwbwbw
    -2,    // bwwbwbw
    -19,   // wwwbwbw
    -2,    // ...wwbw
    21,    // b..wwbw
    -141,  // w..wwbw
    111,   // .b.wwbw
    -35,   // bb.wwbw
    51,    // wb.wwbw
    -11,   // .w.wwbw
    45,    // bw.wwbw
    11,    // ww.wwbw
    -5,    // ..bwwbw
    1,     // b.bwwbw
    -37,   // w.bwwbw
    20,    // .bbwwbw
    -35,   // bbbwwbw
    23,    // wbbwwbw
    33,    // .wbwwbw
    -88,   // bwbwwbw
    -19,   // wwbwwbw
    31,    // ..wwwbw
    20,    // b.wwwbw
    41,    // w.wwwbw
    -80,   // .bwwwbw
    -40,   // bbwwwbw
    -66,   // wbwwwbw
    5,     // .wwwwbw
    115,   // bwwwwbw
    8,     // wwwwwbw
    -11,   // .....ww
    -7,    // b....ww
    5,     // w....ww
    -14,   // .b...ww
    0,     // bb...ww
    -6,    // wb...ww
    -11,   // .w...ww
    41,    // bw...ww
    32,    // ww...ww
    59,    // ..b..ww
    0,     // b.b..ww
    -9,    // w.b..ww
    -63,   // .bb..ww
    -36,   // bbb..ww
    -2,    // wbb..ww
    -40,   // .wb..ww
    -2,    // bwb..ww
    -21,   // wwb..ww
    -6,    // ..w..ww
    -52,   // b.w..ww
    53,    // w.w..ww
    -68,   // .bw..ww
    -22,   // bbw..ww
    75,    // wbw..ww
    -4,    // .ww..ww
    23,    // bww..ww
    -76,   // www..ww
    -38,   // ...b.ww
    108,   // b..b.ww
    1,     // w..b.ww
    -29,   // .b.b.ww
    11,    // bb.b.ww
    -46,   // wb.b.ww
    71,    // .w.b.ww
    1,     // bw.b.ww
    -109,  // ww.b.ww
    -17,   // ..bb.ww
    -42,   // b.bb.ww
    6,     // w.bb.ww
    33,    // .bbb.ww
    49,    // bbbb.ww
    4,     // wbbb.ww
    85,    // .wbb.ww
    35,    // bwbb.ww
    45,    // wwbb.ww
    58,    // ..wb.ww
    1,     // b.wb.ww
    -24,   // w.wb.ww
    -26,   // .bwb.ww
    -92,   // bbwb.ww
    -51,   // wbwb.ww
    -61,   // .wwb.ww
    -29,   // bwwb.ww
    -40,   // wwwb.ww
    -138,  // ...w.ww
    1,     // b..w.ww
    -2,    // w..w.ww
    -105,  // .b.w.ww
    -11,   // bb.w.ww
    49,    // wb.w.ww
    54,    // .w.w.ww
    -66,   // bw.w.ww
    -15,   // ww.w.ww
    9,     // ..bw.ww
    38,    // b.bw.ww
    -14,   // w.bw.ww
    -58,   // .bbw.ww
    4,     // bbbw.ww
    -4,    // wbbw.ww
    -16,   // .wbw.ww
    -7,    // bwbw.ww
    -35,   // wwbw.ww
    -11,   // ..ww.ww
    -35,   // b.ww.ww
    50,    // w.ww.ww
    -57,   // .bww.ww
    77,    // bbww.ww
    11,    // wbww.ww
    31,    // .www.ww
    -7,    // bwww.ww
    65,    // wwww.ww
    64,    // ....bww
    7,     // b...bww
    6,     // w...bww
    37,    // .b..bww
    22,    // bb..bww
    -63,   // wb..bww
    8,     // .w..bww
    -30,   // bw..bww
    -21,   // ww..bww
    -12,   // ..b.bww
    -71,   // b.b.bww
    19,    // w.b.bww
    -37,   // .bb.bww
    -59,   // bbb.bww
    9,     // wbb.bww
    7,     // .wb.bww
    93,    // bwb.bww
    86,    // wwb.bww
    36,    // ..w.bww
    1,     // b.w.bww
    -12,   // w.w.bww
    7,     // .bw.bww
    0,     // bbw.bww
    -17,   // wbw.bww
    6,     // .ww.bww
    1,     // bww.bww
    -43,   // www.bww
    17,    // ...bbww
    -59,   // b..bbww
    39,    // w..bbww
    -6,    // .b.bbww
    -77,   // bb.bbww
    -81,   // wb.bbww
    9,     // .w.bbww
    6,     // bw.bbww
    45,    // ww.bbww
    -24,   // ..bbbww
    -5,    // b.bbbww
    -4,    // w.bbbww
    -15,   // .bbbbww
    48,    // bbbbbww
    0,     // wbbbbww
    -22,   // .wbbbww
    40,    // bwbbbww
    4,     // wwbbbww
    -85,   // ..wbbww
    -61,   // b.wbbww
    11,    // w.wbbww
    103,   // .bwbbww
    82,    // bbwbbww
    34,    // wbwbbww
    105,   // .wwbbww
    -16,   // bwwbbww
    -20,   // wwwbbww
    54,    // ...wbww
    -13,   // b..wbww
    55,    // w..wbww
    16,    // .b.wbww
    92,    // bb.wbww
    56,    // wb.wbww
    -23,   // .w.wbww
    -43,   // bw.wbww
    -35,   // ww.wbww
    -44,   // ..bwbww
    66,    // b.bwbww
    31,    // w.bwbww
    126,   // .bbwbww
    -2,    // bbbwbww
    -8,    // wbbwbww
    -4,    // .wbwbww
    -127,  // bwbwbww
    33,    // wwbwbww
    19,    // ..wwbww
    -65,   // b.wwbww
    29,    // w.wwbww
    -20,   // .bwwbww
    -82,   // bbwwbww
    -19,   // wbwwbww
    91,    // .wwwbww
    -34,   // bwwwbww
    31,    // wwwwbww
    -140,  // ....www
    -39,   // b...www
    34,    // w...www
    -40,   // .b..www
    36,    // bb..www
    15,    // wb..www
    -28,   // .w..www
    -41,   // bw..www
    -76,   // ww..www
    -31,   // ..b.www
    -12,   // b.b.www
    -17,   // w.b.www
    -48,   // .bb.www
    0,     // bbb.www
    33,    // wbb.www
    -58,   // .wb.www
    33,    // bwb.www
    -43,   // wwb.www
    -96,   // ..w.www
    30,    // b.w.www
    -53,   // w.w.www
    -1,    // .bw.www
    59,    // bbw.www
    60,    // wbw.www
    -45,   // .ww.www
    9,     // bww.www
    -51,   // www.www
    -23,   // ...bwww
    21,    // b..bwww
    -42,   // w..bwww
    48,    // .b.bwww
    -4,    // bb.bwww
    -36,   // wb.bwww
    50,    // .w.bwww
    -40,   // bw.bwww
    -40,   // ww.bwww
    -60,   // ..bbwww
    92,    // b.bbwww
    -51,   // w.bbwww
    0,     // .bbbwww
    -77,   // bbbbwww
    -16,   // wbbbwww
    30,    // .wbbwww
    35,    // bwbbwww
    -20,   // wwbbwww
    167,   // ..wbwww
    -100,  // b.wbwww
    56,    // w.wbwww
    30,    // .bwbwww
    2,     // bbwbwww
    -19,   // wbwbwww
    2,     // .wwbwww
    161,   // bwwbwww
    -31,   // wwwbwww
    -396,  // ...wwww
    -45,   // b..wwww
    -1,    // w..wwww
    -163,  // .b.wwww
    -49,   // bb.wwww
    -80,   // wb.wwww
    58,    // .w.wwww
    -56,   // bw.wwww
    65,    // ww.wwww
    -51,   // ..bwwww
    27,    // b.bwwww
    -39,   // w.bwwww
    11,    // .bbwwww
    77,    // bbbwwww
    28,    // wbbwwww
    63,    // .wbwwww
    -60,   // bwbwwww
    31,    // wwbwwww
    -44,   // ..wwwww
    -34,   // b.wwwww
    64,    // w.wwwww
    -98,   // .bwwwww
    -48,   // bbwwwww
    8,     // wbwwwww
    14,    // .wwwwww
    6,     // bwwwwww
    41,    // wwwwwww
    -2,    // captures=0 threats=0
    78,    // captures=0 threats=1
    271,   // captures=0 threats=2
    496,   // captures=0 threats=3
    753,   // captures=0 threats=4
    -24,   // captures=0 additional threats
    94,    // captures=1 threats=0
    362,   // captures=1 threats=1
    424,   // captures=1 threats=2
    784,   // captures=1 threats=3
    1051,  // captures=1 threats=4
    15,    // captures=1 additional threats
    222,   // captures=2 threats=0
    480,   // captures=2 threats=1
    581,   // captures=2 threats=2
    836,   // captures=2 threats=3
    1270,  // captures=2 threats=4
    5,     // captures=2 additional threats
    -23,   // captures=3 threats=0
    267,   // captures=3 threats=1
    487,   // captures=3 threats=2
    1046,  // captures=3 threats=3
    673,   // captures=3 threats=4
    -32,   // captures=3 additional threats
    -32,   // captures=4 threats=0
    28,    // captures=4 threats=1
    105,   // captures=4 threats=2
    851,   // captures=4 threats=3
    1049,  // captures=4 threats=4
    -15,   // captures=4 additional threats
].into_boxed_slice()
