vec![
    0,     // .......
    3,     // b......
    -3,    // w......
    -4,    // .b.....
    13,    // bb.....
    -16,   // wb.....
    4,     // .w.....
    16,    // bw.....
    -13,   // ww.....
    -8,    // ..b....
    81,    // b.b....
    -32,   // w.b....
    10,    // .bb....
    144,   // bbb....
    -75,   // wbb....
    -9,    // .wb....
    38,    // bwb....
    63,    // wwb....
    8,     // ..w....
    32,    // b.w....
    -81,   // w.w....
    9,     // .bw....
    -63,   // bbw....
    -38,   // wbw....
    -10,   // .ww....
    75,    // bww....
    -144,  // www....
    -11,   // ...b...
    -5,    // b..b...
    -8,    // w..b...
    -33,   // .b.b...
    139,   // bb.b...
    -50,   // wb.b...
    16,    // .w.b...
    20,    // bw.b...
    -39,   // ww.b...
    -17,   // ..bb...
    33,    // b.bb...
    31,    // w.bb...
    67,    // .bbb...
    405,   // bbbb...
    -116,  // wbbb...
    69,    // .wbb...
    2,     // bwbb...
    17,    // wwbb...
    6,     // ..wb...
    47,    // b.wb...
    -54,   // w.wb...
    -34,   // .bwb...
    -55,   // bbwb...
    4,     // wbwb...
    -31,   // .wwb...
    28,    // bwwb...
    -23,   // wwwb...
    11,    // ...w...
    8,     // b..w...
    5,     // w..w...
    -16,   // .b.w...
    39,    // bb.w...
    -20,   // wb.w...
    33,    // .w.w...
    50,    // bw.w...
    -139,  // ww.w...
    -6,    // ..bw...
    54,    // b.bw...
    -47,   // w.bw...
    31,    // .bbw...
    23,    // bbbw...
    -28,   // wbbw...
    34,    // .wbw...
    -4,    // bwbw...
    55,    // wwbw...
    17,    // ..ww...
    -31,   // b.ww...
    -33,   // w.ww...
    -69,   // .bww...
    -17,   // bbww...
    -2,    // wbww...
    -67,   // .www...
    116,   // bwww...
    -405,  // wwww...
    -8,    // ....b..
    18,    // b...b..
    -20,   // w...b..
    -8,    // .b..b..
    7,     // bb..b..
    37,    // wb..b..
    5,     // .w..b..
    15,    // bw..b..
    61,    // ww..b..
    -35,   // ..b.b..
    18,    // b.b.b..
    -63,   // w.b.b..
    -72,   // .bb.b..
    94,    // bbb.b..
    -42,   // wbb.b..
    -15,   // .wb.b..
    -77,   // bwb.b..
    -13,   // wwb.b..
    0,     // ..w.b..
    30,    // b.w.b..
    -61,   // w.w.b..
    -22,   // .bw.b..
    -36,   // bbw.b..
    -30,   // wbw.b..
    39,    // .ww.b..
    11,    // bww.b..
    -31,   // www.b..
    -17,   // ...bb..
    -37,   // b..bb..
    26,    // w..bb..
    7,     // .b.bb..
    10,    // bb.bb..
    1,     // wb.bb..
    -79,   // .w.bb..
    21,    // bw.bb..
    -18,   // ww.bb..
    33,    // ..bbb..
    71,    // b.bbb..
    -32,   // w.bbb..
    241,   // .bbbb..
    44,    // bbbbb..
    62,    // wbbbb..
    -51,   // .wbbb..
    -31,   // bwbbb..
    -22,   // wwbbb..
    -69,   // ..wbb..
    -23,   // b.wbb..
    -26,   // w.wbb..
    -23,   // .bwbb..
    -19,   // bbwbb..
    60,    // wbwbb..
    15,    // .wwbb..
    -92,   // bwwbb..
    -60,   // wwwbb..
    -6,    // ...wb..
    86,    // b..wb..
    39,    // w..wb..
    -41,   // .b.wb..
    -58,   // bb.wb..
    0,     // wb.wb..
    51,    // .w.wb..
    25,    // bw.wb..
    8,     // ww.wb..
    7,     // ..bwb..
    18,    // b.bwb..
    6,     // w.bwb..
    4,     // .bbwb..
    -166,  // bbbwb..
    48,    // wbbwb..
    35,    // .wbwb..
    -2,    // bwbwb..
    -44,   // wwbwb..
    69,    // ..wwb..
    13,    // b.wwb..
    70,    // w.wwb..
    0,     // .bwwb..
    85,    // bbwwb..
    -5,    // wbwwb..
    -71,   // .wwwb..
    -1,    // bwwwb..
    -50,   // wwwwb..
    8,     // ....w..
    20,    // b...w..
    -18,   // w...w..
    -5,    // .b..w..
    -61,   // bb..w..
    -15,   // wb..w..
    8,     // .w..w..
    -37,   // bw..w..
    -7,    // ww..w..
    0,     // ..b.w..
    61,    // b.b.w..
    -30,   // w.b.w..
    -39,   // .bb.w..
    31,    // bbb.w..
    -11,   // wbb.w..
    22,    // .wb.w..
    30,    // bwb.w..
    36,    // wwb.w..
    35,    // ..w.w..
    63,    // b.w.w..
    -18,   // w.w.w..
    15,    // .bw.w..
    13,    // bbw.w..
    77,    // wbw.w..
    72,    // .ww.w..
    42,    // bww.w..
    -94,   // www.w..
    6,     // ...bw..
    -39,   // b..bw..
    -86,   // w..bw..
    -51,   // .b.bw..
    -8,    // bb.bw..
    -25,   // wb.bw..
    41,    // .w.bw..
    0,     // bw.bw..
    58,    // ww.bw..
    -69,   // ..bbw..
    -70,   // b.bbw..
    -13,   // w.bbw..
    71,    // .bbbw..
    50,    // bbbbw..
    1,     // wbbbw..
    0,     // .wbbw..
    5,     // bwbbw..
    -85,   // wwbbw..
    -7,    // ..wbw..
    -6,    // b.wbw..
    -18,   // w.wbw..
    -35,   // .bwbw..
    44,    // bbwbw..
    2,     // wbwbw..
    -4,    // .wwbw..
    -48,   // bwwbw..
    166,   // wwwbw..
    17,    // ...ww..
    -26,   // b..ww..
    37,    // w..ww..
    79,    // .b.ww..
    18,    // bb.ww..
    -21,   // wb.ww..
    -7,    // .w.ww..
    -1,    // bw.ww..
    -10,   // ww.ww..
    69,    // ..bww..
    26,    // b.bww..
    23,    // w.bww..
    -15,   // .bbww..
    60,    // bbbww..
    92,    // wbbww..
    23,    // .wbww..
    -60,   // bwbww..
    19,    // wwbww..
    -33,   // ..www..
    32,    // b.www..
    -71,   // w.www..
    51,    // .bwww..
    22,    // bbwww..
    31,    // wbwww..
    -241,  // .wwww..
    -62,   // bwwww..
    -44,   // wwwww..
    -4,    // .....b.
    7,     // b....b.
    -49,   // w....b.
    -31,   // .b...b.
    12,    // bb...b.
    5,     // wb...b.
    0,     // .w...b.
    17,    // bw...b.
    -13,   // ww...b.
    -8,    // ..b..b.
    27,    // b.b..b.
    -47,   // w.b..b.
    7,     // .bb..b.
    27,    // bbb..b.
    101,   // wbb..b.
    -15,   // .wb..b.
    5,     // bwb..b.
    38,    // wwb..b.
    -5,    // ..w..b.
    -24,   // b.w..b.
    -9,    // w.w..b.
    -30,   // .bw..b.
    -9,    // bbw..b.
    -76,   // wbw..b.
    -24,   // .ww..b.
    -7,    // bww..b.
    -41,   // www..b.
    -33,   // ...b.b.
    -58,   // b..b.b.
    -30,   // w..b.b.
    -11,   // .b.b.b.
    -54,   // bb.b.b.
    6,     // wb.b.b.
    -35,   // .w.b.b.
    4,     // bw.b.b.
    -29,   // ww.b.b.
    7,     // ..bb.b.
    -31,   // b.bb.b.
    97,    // w.bb.b.
    55,    // .bbb.b.
    -58,   // bbbb.b.
    80,    // wbbb.b.
    3,     // .wbb.b.
    12,    // bwbb.b.
    -5,    // wwbb.b.
    -51,   // ..wb.b.
    -38,   // b.wb.b.
    -66,   // w.wb.b.
    30,    // .bwb.b.
    23,    // bbwb.b.
    24,    // wbwb.b.
    17,    // .wwb.b.
    27,    // bwwb.b.
    49,    // wwwb.b.
    -16,   // ...w.b.
    -37,   // b..w.b.
    5,     // w..w.b.
    -7,    // .b.w.b.
    -71,   // bb.w.b.
    -30,   // wb.w.b.
    35,    // .w.w.b.
    48,    // bw.w.b.
    -107,  // ww.w.b.
    -41,   // ..bw.b.
    19,    // b.bw.b.
    33,    // w.bw.b.
    42,    // .bbw.b.
    -51,   // bbbw.b.
    -80,   // wbbw.b.
    40,    // .wbw.b.
    21,    // bwbw.b.
    16,    // wwbw.b.
    79,    // ..ww.b.
    0,     // b.ww.b.
    -72,   // w.ww.b.
    42,    // .bww.b.
    -9,    // bbww.b.
    110,   // wbww.b.
    -18,   // .www.b.
    36,    // bwww.b.
    -164,  // wwww.b.
    10,    // ....bb.
    -30,   // b...bb.
    29,    // w...bb.
    7,     // .b..bb.
    4,     // bb..bb.
    -10,   // wb..bb.
    24,    // .w..bb.
    14,    // bw..bb.
    -63,   // ww..bb.
    -72,   // ..b.bb.
    -13,   // b.b.bb.
    5,     // w.b.bb.
    16,    // .bb.bb.
    44,    // bbb.bb.
    -37,   // wbb.bb.
    -67,   // .wb.bb.
    -60,   // bwb.bb.
    -36,   // wwb.bb.
    -39,   // ..w.bb.
    -47,   // b.w.bb.
    29,    // w.w.bb.
    -21,   // .bw.bb.
    -6,    // bbw.bb.
    -72,   // wbw.bb.
    0,     // .ww.bb.
    52,    // bww.bb.
    -47,   // www.bb.
    67,    // ...bbb.
    37,    // b..bbb.
    -21,   // w..bbb.
    55,    // .b.bbb.
    -31,   // bb.bbb.
    71,    // wb.bbb.
    18,    // .w.bbb.
    95,    // bw.bbb.
    33,    // ww.bbb.
    241,   // ..bbbb.
    55,    // b.bbbb.
    64,    // w.bbbb.
    -59,   // .bbbbb.
    -14,   // bbbbbb.
    -34,   // wbbbbb.
    102,   // .wbbbb.
    -4,    // bwbbbb.
    -15,   // wwbbbb.
    71,    // ..wbbb.
    -16,   // b.wbbb.
    -2,    // w.wbbb.
    32,    // .bwbbb.
    -89,   // bbwbbb.
    60,    // wbwbbb.
    9,     // .wwbbb.
    39,    // bwwbbb.
    0,     // wwwbbb.
    31,    // ...wbb.
    17,    // b..wbb.
    4,     // w..wbb.
    42,    // .b.wbb.
    62,    // bb.wbb.
    77,    // wb.wbb.
    -17,   // .w.wbb.
    -30,   // bw.wbb.
    -58,   // ww.wbb.
    4,     // ..bwbb.
    -132,  // b.bwbb.
    -31,   // w.bwbb.
    23,    // .bbwbb.
    -5,    // bbbwbb.
    -55,   // wbbwbb.
    1,     // .wbwbb.
    -56,   // bwbwbb.
    126,   // wwbwbb.
    -15,   // ..wwbb.
    -47,   // b.wwbb.
    10,    // w.wwbb.
    17,    // .bwwbb.
    -104,  // bbwwbb.
    23,    // wbwwbb.
    -9,    // .wwwbb.
    55,    // bwwwbb.
    10,    // wwwwbb.
    9,     // ....wb.
    -20,   // b...wb.
    27,    // w...wb.
    -30,   // .b..wb.
    42,    // bb..wb.
    -77,   // wb..wb.
    15,    // .w..wb.
    -20,   // bw..wb.
    -67,   // ww..wb.
    -22,   // ..b.wb.
    -39,   // b.b.wb.
    29,    // w.b.wb.
    -21,   // .bb.wb.
    57,    // bbb.wb.
    11,    // wbb.wb.
    0,     // .wb.wb.
    -16,   // bwb.wb.
    6,     // wwb.wb.
    15,    // ..w.wb.
    -2,    // b.w.wb.
    61,    // w.w.wb.
    50,    // .bw.wb.
    -10,   // bbw.wb.
    -5,    // wbw.wb.
    67,    // .ww.wb.
    -59,   // bww.wb.
    -1,    // www.wb.
    -34,   // ...bwb.
    29,    // b..bwb.
    46,    // w..bwb.
    30,    // .b.bwb.
    14,    // bb.bwb.
    -90,   // wb.bwb.
    -40,   // .w.bwb.
    -15,   // bw.bwb.
    -25,   // ww.bwb.
    -23,   // ..bbwb.
    -3,    // b.bbwb.
    -21,   // w.bbwb.
    32,    // .bbbwb.
    -61,   // bbbbwb.
    -20,   // wbbbwb.
    16,    // .wbbwb.
    -32,   // bwbbwb.
    102,   // wwbbwb.
    -35,   // ..wbwb.
    -34,   // b.wbwb.
    -7,    // w.wbwb.
    10,    // .bwbwb.
    5,     // bbwbwb.
    -37,   // wbwbwb.
    -1,    // .wwbwb.
    107,   // bwwbwb.
    29,    // wwwbwb.
    -69,   // ...wwb.
    -23,   // b..wwb.
    8,     // w..wwb.
    42,    // .b.wwb.
    -86,   // bb.wwb.
    -16,   // wb.wwb.
    -3,    // .w.wwb.
    2,     // bw.wwb.
    -58,   // ww.wwb.
    0,     // ..bwwb.
    -51,   // b.bwwb.
    -49,   // w.bwwb.
    17,    // .bbwwb.
    -31,   // bbbwwb.
    -56,   // wbbwwb.
    -16,   // .wbwwb.
    -53,   // bwbwwb.
    -21,   // wwbwwb.
    51,    // ..wwwb.
    106,   // b.wwwb.
    -98,   // w.wwwb.
    0,     // .bwwwb.
    21,    // bbwwwb.
    -80,   // wbwwwb.
    -102,  // .wwwwb.
    123,   // bwwwwb.
    -99,   // wwwwwb.
    4,     // .....w.
    49,    // b....w.
    -7,    // w....w.
    0,     // .b...w.
    13,    // bb...w.
    -17,   // wb...w.
    31,    // .w...w.
    -5,    // bw...w.
    -12,   // ww...w.
    5,     // ..b..w.
    9,     // b.b..w.
    24,    // w.b..w.
    24,    // .bb..w.
    41,    // bbb..w.
    7,     // wbb..w.
    30,    // .wb..w.
    76,    // bwb..w.
    9,     // wwb..w.
    8,     // ..w..w.
    47,    // b.w..w.
    -27,   // w.w..w.
    15,    // .bw..w.
    -38,   // bbw..w.
    -5,    // wbw..w.
    -7,    // .ww..w.
    -101,  // bww..w.
    -27,   // www..w.
    16,    // ...b.w.
    -5,    // b..b.w.
    37,    // w..b.w.
    -35,   // .b.b.w.
    107,   // bb.b.w.
    -48,   // wb.b.w.
    7,     // .w.b.w.
    30,    // bw.b.w.
    71,    // ww.b.w.
    -79,   // ..bb.w.
    72,    // b.bb.w.
    0,     // w.bb.w.
    18,    // .bbb.w.
    164,   // bbbb.w.
    -36,   // wbbb.w.
    -42,   // .wbb.w.
    -110,  // bwbb.w.
    9,     // wwbb.w.
    41,    // ..wb.w.
    -33,   // b.wb.w.
    -19,   // w.wb.w.
    -40,   // .bwb.w.
    -16,   // bbwb.w.
    -21,   // wbwb.w.
    -42,   // .wwb.w.
    80,    // bwwb.w.
    51,    // wwwb.w.
    33,    // ...w.w.
    30,    // b..w.w.
    58,    // w..w.w.
    35,    // .b.w.w.
    29,    // bb.w.w.
    -4,    // wb.w.w.
    11,    // .w.w.w.
    -6,    // bw.w.w.
    54,    // ww.w.w.
    51,    // ..bw.w.
    66,    // b.bw.w.
    38,    // w.bw.w.
    -17,   // .bbw.w.
    -49,   // bbbw.w.
    -27,   // wbbw.w.
    -30,   // .wbw.w.
    -24,   // bwbw.w.
    -23,   // wwbw.w.
    -7,    // ..ww.w.
    -97,   // b.ww.w.
    31,    // w.ww.w.
    -3,    // .bww.w.
    5,     // bbww.w.
    -12,   // wbww.w.
    -55,   // .www.w.
    -80,   // bwww.w.
    58,    // wwww.w.
    -9,    // ....bw.
    -27,   // b...bw.
    20,    // w...bw.
    -15,   // .b..bw.
    67,    // bb..bw.
    20,    // wb..bw.
    30,    // .w..bw.
    77,    // bw..bw.
    -42,   // ww..bw.
    -15,   // ..b.bw.
    -61,   // b.b.bw.
    2,     // w.b.bw.
    -67,   // .bb.bw.
    1,     // bbb.bw.
    59,    // wbb.bw.
    -50,   // .wb.bw.
    5,     // bwb.bw.
    10,    // wwb.bw.
    22,    // ..w.bw.
    -29,   // b.w.bw.
    39,    // w.w.bw.
    0,     // .bw.bw.
    -6,    // bbw.bw.
    16,    // wbw.bw.
    21,    // .ww.bw.
    -11,   // bww.bw.
    -57,   // www.bw.
    69,    // ...bbw.
    -8,    // b..bbw.
    23,    // w..bbw.
    3,     // .b.bbw.
    58,    // bb.bbw.
    -2,    // wb.bbw.
    -42,   // .w.bbw.
    16,    // bw.bbw.
    86,    // ww.bbw.
    -51,   // ..bbbw.
    98,    // b.bbbw.
    -106,  // w.bbbw.
    102,   // .bbbbw.
    99,    // bbbbbw.
    -123,  // wbbbbw.
    0,     // .wbbbw.
    80,    // bwbbbw.
    -21,   // wwbbbw.
    0,     // ..wbbw.
    49,    // b.wbbw.
    51,    // w.wbbw.
    16,    // .bwbbw.
    21,    // bbwbbw.
    53,    // wbwbbw.
    -17,   // .wwbbw.
    56,    // bwwbbw.
    31,    // wwwbbw.
    34,    // ...wbw.
    -46,   // b..wbw.
    -29,   // w..wbw.
    40,    // .b.wbw.
    25,    // bb.wbw.
    15,    // wb.wbw.
    -30,   // .w.wbw.
    90,    // bw.wbw.
    -14,   // ww.wbw.
    35,    // ..bwbw.
    7,     // b.bwbw.
    34,    // w.bwbw.
    1,     // .bbwbw.
    -29,   // bbbwbw.
    -107,  // wbbwbw.
    -10,   // .wbwbw.
    37,    // bwbwbw.
    -5,    // wwbwbw.
    23,    // ..wwbw.
    21,    // b.wwbw.
    3,     // w.wwbw.
    -16,   // .bwwbw.
    -102,  // bbwwbw.
    32,    // wbwwbw.
    -32,   // .wwwbw.
    20,    // bwwwbw.
    61,    // wwwwbw.
    -10,   // ....ww.
    -29,   // b...ww.
    30,    // w...ww.
    -24,   // .b..ww.
    63,    // bb..ww.
    -14,   // wb..ww.
    -7,    // .w..ww.
    10,    // bw..ww.
    -4,    // ww..ww.
    39,    // ..b.ww.
    -29,   // b.b.ww.
    47,    // w.b.ww.
    0,     // .bb.ww.
    47,    // bbb.ww.
    -52,   // wbb.ww.
    21,    // .wb.ww.
    72,    // bwb.ww.
    6,     // wwb.ww.
    72,    // ..w.ww.
    -5,    // b.w.ww.
    13,    // w.w.ww.
    67,    // .bw.ww.
    36,    // bbw.ww.
    60,    // wbw.ww.
    -16,   // .ww.ww.
    37,    // bww.ww.
    -44,   // www.ww.
    -31,   // ...bww.
    -4,    // b..bww.
    -17,   // w..bww.
    17,    // .b.bww.
    58,    // bb.bww.
    30,    // wb.bww.
    -42,   // .w.bww.
    -77,   // bw.bww.
    -62,   // ww.bww.
    15,    // ..bbww.
    -10,   // b.bbww.
    47,    // w.bbww.
    9,     // .bbbww.
    -10,   // bbbbww.
    -55,   // wbbbww.
    -17,   // .wbbww.
    -23,   // bwbbww.
    104,   // wwbbww.
    -4,    // ..wbww.
    31,    // b.wbww.
    132,   // w.wbww.
    -1,    // .bwbww.
    -126,  // bbwbww.
    56,    // wbwbww.
    -23,   // .wwbww.
    55,    // bwwbww.
    5,     // wwwbww.
    -67,   // ...www.
    21,    // b..www.
    -37,   // w..www.
    -18,   // .b.www.
    -33,   // bb.www.
    -95,   // wb.www.
    -55,   // .w.www.
    -71,   // bw.www.
    31,    // ww.www.
    -71,   // ..bwww.
    2,     // b.bwww.
    16,    // w.bwww.
    -9,    // .bbwww.
    0,     // bbbwww.
    -39,   // wbbwww.
    -32,   // .wbwww.
    -60,   // bwbwww.
    89,    // wwbwww.
    -241,  // ..wwww.
    -64,   // b.wwww.
    -55,   // w.wwww.
    -102,  // .bwwww.
    15,    // bbwwww.
    4,     // wbwwww.
    59,    // .wwwww.
    34,    // bwwwww.
    14,    // wwwwww.
    3,     // ......b
    -51,   // b.....b
    0,     // w.....b
    7,     // .b....b
    -5,    // bb....b
    0,     // wb....b
    49,    // .w....b
    41,    // bw....b
    -5,    // ww....b
    18,    // ..b...b
    44,    // b.b...b
    -30,   // w.b...b
    -30,   // .bb...b
    -35,   // bbb...b
    -50,   // wbb...b
    -27,   // .wb...b
    -28,   // bwb...b
    7,     // wwb...b
    20,    // ..w...b
    -12,   // b.w...b
    37,    // w.w...b
    -20,   // .bw...b
    -6,    // bbw...b
    9,     // wbw...b
    -29,   // .ww...b
    -56,   // bww...b
    -38,   // www...b
    -5,    // ...b..b
    0,     // b..b..b
    72,    // w..b..b
    -58,   // .b.b..b
    2,     // bb.b..b
    -28,   // wb.b..b
    -5,    // .w.b..b
    -57,   // bw.b..b
    108,   // ww.b..b
    -37,   // ..bb..b
    -78,   // b.bb..b
    4,     // w.bb..b
    37,    // .bbb..b
    1,     // bbbb..b
    -99,   // wbbb..b
    -8,    // .wbb..b
    140,   // bwbb..b
    -60,   // wwbb..b
    -39,   // ..wb..b
    -3,    // b.wb..b
    23,    // w.wb..b
    29,    // .bwb..b
    -57,   // bbwb..b
    -30,   // wbwb..b
    -4,    // .wwb..b
    -10,   // bwwb..b
    22,    // wwwb..b
    8,     // ...w..b
    -69,   // b..w..b
    -72,   // w..w..b
    -37,   // .b.w..b
    -2,    // bb.w..b
    -39,   // wb.w..b
    30,    // .w.w..b
    -51,   // bw.w..b
    1,     // ww.w..b
    86,    // ..bw..b
    14,    // b.bw..b
    21,    // w.bw..b
    17,    // .bbw..b
    44,    // bbbw..b
    -22,   // wbbw..b
    -46,   // .wbw..b
    -85,   // bwbw..b
    -14,   // wwbw..b
    -26,   // ..ww..b
    -49,   // b.ww..b
    35,    // w.ww..b
    -23,   // .bww..b
    -40,   // bbww..b
    21,    // wbww..b
    21,    // .www..b
    15,    // bwww..b
    -45,   // wwww..b
    81,    // ....b.b
    44,    // b...b.b
    -37,   // w...b.b
    27,    // .b..b.b
    -52,   // bb..b.b
    94,    // wb..b.b
    9,     // .w..b.b
    51,    // bw..b.b
    -1,    // ww..b.b
    18,    // ..b.b.b
    19,    // b.b.b.b
    30,    // w.b.b.b
    -13,   // .bb.b.b
    51,    // bbb.b.b
    -18,   // wbb.b.b
    -61,   // .wb.b.b
    -43,   // bwb.b.b
    -70,   // wwb.b.b
    61,    // ..w.b.b
    27,    // b.w.b.b
    0,     // w.w.b.b
    -39,   // .bw.b.b
    13,    // bbw.b.b
    27,    // wbw.b.b
    -29,   // .ww.b.b
    67,    // bww.b.b
    -12,   // www.b.b
    33,    // ...bb.b
    -78,   // b..bb.b
    -35,   // w..bb.b
    -31,   // .b.bb.b
    -50,   // bb.bb.b
    -56,   // wb.bb.b
    72,    // .w.bb.b
    30,    // bw.bb.b
    -42,   // ww.bb.b
    71,    // ..bbb.b
    40,    // b.bbb.b
    -28,   // w.bbb.b
    55,    // .bbbb.b
    -64,   // bbbbb.b
    -1,    // wbbbb.b
    98,    // .wbbb.b
    -41,   // bwbbb.b
    -6,    // wwbbb.b
    -70,   // ..wbb.b
    9,     // b.wbb.b
    94,    // w.wbb.b
    -3,    // .bwbb.b
    -29,   // bbwbb.b
    31,    // wbwbb.b
    -10,   // .wwbb.b
    -72,   // bwwbb.b
    91,    // wwwbb.b
    54,    // ...wb.b
    14,    // b..wb.b
    -23,   // w..wb.b
    19,    // .b.wb.b
    26,    // bb.wb.b
    41,    // wb.wb.b
    66,    // .w.wb.b
    -20,   // bw.wb.b
    40,    // ww.wb.b
    18,    // ..bwb.b
    39,    // b.bwb.b
    7,     // w.bwb.b
    -132,  // .bbwb.b
    -56,   // bbbwb.b
    -50,   // wbbwb.b
    7,     // .wbwb.b
    38,    // bwbwb.b
    68,    // wwbwb.b
    26,    // ..wwb.b
    11,    // b.wwb.b
    -94,   // w.wwb.b
    -51,   // .bwwb.b
    -11,   // bbwwb.b
    1,     // wbwwb.b
    2,     // .wwwb.b
    20,    // bwwwb.b
    27,    // wwwwb.b
    32,    // ....w.b
    -12,   // b...w.b
    30,    // w...w.b
    -24,   // .b..w.b
    9,     // bb..w.b
    112,   // wb..w.b
    47,    // .w..w.b
    19,    // bw..w.b
    -49,   // ww..w.b
    30,    // ..b.w.b
    27,    // b.b.w.b
    0,     // w.b.w.b
    -47,   // .bb.w.b
    16,    // bbb.w.b
    83,    // wbb.w.b
    -29,   // .wb.w.b
    64,    // bwb.w.b
    1,     // wwb.w.b
    63,    // ..w.w.b
    40,    // b.w.w.b
    -30,   // w.w.w.b
    -2,    // .bw.w.b
    -20,   // bbw.w.b
    71,    // wbw.w.b
    -5,    // .ww.w.b
    7,     // bww.w.b
    28,    // www.w.b
    47,    // ...bw.b
    -3,    // b..bw.b
    -21,   // w..bw.b
    -38,   // .b.bw.b
    13,    // bb.bw.b
    45,    // wb.bw.b
    -33,   // .w.bw.b
    54,    // bw.bw.b
    1,     // ww.bw.b
    -23,   // ..bbw.b
    9,     // b.bbw.b
    13,    // w.bbw.b
    -16,   // .bbbw.b
    40,    // bbbbw.b
    -22,   // wbbbw.b
    49,    // .wbbw.b
    37,    // bwbbw.b
    -60,   // wwbbw.b
    -6,    // ..wbw.b
    -33,   // b.wbw.b
    -7,    // w.wbw.b
    -34,   // .bwbw.b
    -30,   // bbwbw.b
    -68,   // wbwbw.b
    31,    // .wwbw.b
    49,    // bwwbw.b
    -101,  // wwwbw.b
    -31,   // ...ww.b
    -49,   // b..ww.b
    -4,    // w..ww.b
    0,     // .b.ww.b
    -5,    // bb.ww.b
    71,    // wb.ww.b
    -97,   // .w.ww.b
    28,    // bw.ww.b
    -35,   // ww.ww.b
    13,    // ..bww.b
    11,    // b.bww.b
    -13,   // w.bww.b
    -47,   // .bbww.b
    52,    // bbbww.b
    66,    // wbbww.b
    21,    // .wbww.b
    46,    // bwbww.b
    -64,   // wwbww.b
    32,    // ..www.b
    -63,   // b.www.b
    28,    // w.www.b
    106,   // .bwww.b
    5,     // bbwww.b
    19,    // wbwww.b
    -64,   // .wwww.b
    -4,    // bwwww.b
    -37,   // wwwww.b
    13,    // .....bb
    -5,    // b....bb
    5,     // w....bb
    12,    // .b...bb
    -31,   // bb...bb
    -41,   // wb...bb
    13,    // .w...bb
    6,     // bw...bb
    0,     // ww...bb
    7,     // ..b..bb
    -52,   // b.b..bb
    49,    // w.b..bb
    4,     // .bb..bb
    75,    // bbb..bb
    -23,   // wbb..bb
    67,    // .wb..bb
    -75,   // bwb..bb
    23,    // wwb..bb
    -61,   // ..w..bb
    9,     // b.w..bb
    1,     // w.w..bb
    42,    // .bw..bb
    21,    // bbw..bb
    4,     // wbw..bb
    63,    // .ww..bb
    1,     // bww..bb
    36,    // www..bb
    139,   // ...b.bb
    2,     // b..b.bb
    -1,    // w..b.bb
    -54,   // .b.b.bb
    15,    // bb.b.bb
    67,    // wb.b.bb
    107,   // .w.b.bb
    -49,   // bw.b.bb
    9,     // ww.b.bb
    10,    // ..bb.bb
    -50,   // b.bb.bb
    35,    // w.bb.bb
    -31,   // .bbb.bb
    -65,   // bbbb.bb
    8,     // wbbb.bb
    58,    // .wbb.bb
    -12,   // bwbb.bb
    -76,   // wwbb.bb
    -8,    // ..wb.bb
    13,    // b.wb.bb
    -40,   // w.wb.bb
    14,    // .bwb.bb
    36,    // bbwb.bb
    6,     // wbwb.bb
    58,    // .wwb.bb
    6,     // bwwb.bb
    -3,    // wwwb.bb
    39,    // ...w.bb
    -2,    // b..w.bb
    -108,  // w..w.bb
    -71,   // .b.w.bb
    107,   // bb.w.bb
    2,     // wb.w.bb
    29,    // .w.w.bb
    45,    // bw.w.bb
    -9,    // ww.w.bb
    -58,   // ..bw.bb
    26,    // b.bw.bb
    -1,    // w.bw.bb
    62,    // .bbw.bb
    39,    // bbbw.bb
    31,    // wbbw.bb
    25,    // .wbw.bb
    49,    // bwbw.bb
    94,    // wwbw.bb
    18,    // ..ww.bb
    -5,    // b.ww.bb
    42,    // w.ww.bb
    -86,   // .bww.bb
    -44,   // bbww.bb
    -34,   // wbww.bb
    -33,   // .www.bb
    -4,    // bwww.bb
    -48,   // wwww.bb
    144,   // ....bbb
    -35,   // b...bbb
    38,    // w...bbb
    27,    // .b..bbb
    75,    // bb..bbb
    43,    // wb..bbb
    41,    // .w..bbb
    -16,   // bw..bbb
    -36,   // ww..bbb
    94,    // ..b.bbb
    51,    // b.b.bbb
    -28,   // w.b.bbb
    44,    // .bb.bbb
    49,    // bbb.bbb
    -8,    // wbb.bbb
    1,     // .wb.bbb
    -58,   // bwb.bbb
    -57,   // wwb.bbb
    31,    // ..w.bbb
    16,    // b.w.bbb
    12,    // w.w.bbb
    57,    // .bw.bbb
    44,    // bbw.bbb
    -33,   // wbw.bbb
    47,    // .ww.bbb
    -33,   // bww.bbb
    0,     // www.bbb
    405,   // ...bbbb
    1,     // b..bbbb
    45,    // w..bbbb
    -58,   // .b.bbbb
    -65,   // bb.bbbb
    55,    // wb.bbbb
    164,   // .w.bbbb
    80,    // bw.bbbb
    48,    // ww.bbbb
    44,    // ..bbbbb
    -64,   // b.bbbbb
    37,    // w.bbbbb
    -14,   // .bbbbbb
    -40,   // bbbbbbb
    -7,    // wbbbbbb
    99,    // .wbbbbb
    -8,    // bwbbbbb
    46,    // wwbbbbb
    50,    // ..wbbbb
    40,    // b.wbbbb
    -27,   // w.wbbbb
    -61,   // .bwbbbb
    -31,   // bbwbbbb
    58,    // wbwbbbb
    -10,   // .wwbbbb
    -28,   // bwwbbbb
    -78,   // wwwbbbb
    23,    // ...wbbb
    44,    // b..wbbb
    -22,   // w..wbbb
    -51,   // .b.wbbb
    39,    // bb.wbbb
    39,    // wb.wbbb
    -49,   // .w.wbbb
    36,    // bw.wbbb
    3,     // ww.wbbb
    -166,  // ..bwbbb
    -56,   // b.bwbbb
    101,   // w.bwbbb
    -5,    // .bbwbbb
    30,    // bbbwbbb
    -163,  // wbbwbbb
    -29,   // .wbwbbb
    20,    // bwbwbbb
    -2,    // wwbwbbb
    60,    // ..wwbbb
    52,    // b.wwbbb
    -91,   // w.wwbbb
    -31,   // .bwwbbb
    21,    // bbwwbbb
    -35,   // wbwwbbb
    0,     // .wwwbbb
    17,    // bwwwbbb
    78,    // wwwwbbb
    -63,   // ....wbb
    -6,    // b...wbb
    -7,    // w...wbb
    -9,    // .b..wbb
    21,    // bb..wbb
    30,    // wb..wbb
    -38,   // .w..wbb
    61,    // bw..wbb
    -23,   // ww..wbb
    -36,   // ..b.wbb
    13,    // b.b.wbb
    -1,    // w.b.wbb
    -6,    // .bb.wbb
    44,    // bbb.wbb
    0,     // wbb.wbb
    -6,    // .wb.wbb
    17,    // bwb.wbb
    0,     // wwb.wbb
    13,    // ..w.wbb
    -20,   // b.w.wbb
    70,    // w.w.wbb
    -10,   // .bw.wbb
    -87,   // bbw.wbb
    -92,   // wbw.wbb
    36,    // .ww.wbb
    -8,    // bww.wbb
    57,    // www.wbb
    -55,   // ...bwbb
    -57,   // b..bwbb
    14,    // w..bwbb
    23,    // .b.bwbb
    36,    // bb.bwbb
    41,    // wb.bwbb
    -16,   // .w.bwbb
    -55,   // bw.bwbb
    -94,   // ww.bwbb
    -19,   // ..bbwbb
    -29,   // b.bbwbb
    64,    // w.bbwbb
    -89,   // .bbbwbb
    -31,   // bbbbwbb
    35,    // wbbbwbb
    21,    // .wbbwbb
    19,    // bwbbwbb
    82,    // wwbbwbb
    44,    // ..wbwbb
    -30,   // b.wbwbb
    -68,   // w.wbwbb
    5,     // .bwbwbb
    -33,   // bbwbwbb
    130,   // wbwbwbb
    -126,  // .wwbwbb
    7,     // bwwbwbb
    2,     // wwwbwbb
    -17,   // ...wwbb
    -40,   // b..wwbb
    60,    // w..wwbb
    -9,    // .b.wwbb
    -44,   // bb.wwbb
    -8,    // wb.wwbb
    5,     // .w.wwbb
    83,    // bw.wwbb
    76,    // ww.wwbb
    85,    // ..bwwbb
    -11,   // b.bwwbb
    60,    // w.bwwbb
    -104,  // .bbwwbb
    21,    // bbbwwbb
    16,    // wbbwwbb
    -102,  // .wbwwbb
    -33,   // bwbwwbb
    -82,   // wwbwwbb
    22,    // ..wwwbb
    5,     // b.wwwbb
    6,     // w.wwwbb
    21,    // .bwwwbb
    -3,    // bbwwwbb
    -40,   // wbwwwbb
    15,    // .wwwwbb
    -1,    // bwwwwbb
    -46,   // wwwwwbb
    16,    // .....wb
    41,    // b....wb
    0,     // w....wb
    17,    // .b...wb
    6,     // bb...wb
    0,     // wb...wb
    -5,    // .w...wb
    -107,  // bw...wb
    41,    // ww...wb
    15,    // ..b..wb
    51,    // b.b..wb
    -112,  // w.b..wb
    14,    // .bb..wb
    -16,   // bbb..wb
    -55,   // wbb..wb
    77,    // .wb..wb
    -51,   // bwb..wb
    -30,   // wwb..wb
    -37,   // ..w..wb
    19,    // b.w..wb
    -94,   // w.w..wb
    -20,   // .bw..wb
    61,    // bbw..wb
    51,    // wbw..wb
    10,    // .ww..wb
    -54,   // bww..wb
    -43,   // www..wb
    20,    // ...b.wb
    -57,   // b..b.wb
    39,    // w..b.wb
    4,     // .b.b.wb
    -49,   // bb.b.wb
    36,    // wb.b.wb
    30,    // .w.b.wb
    -59,   // bw.b.wb
    -2,    // ww.b.wb
    21,    // ..bb.wb
    30,    // b.bb.wb
    -71,   // w.bb.wb
    95,    // .bbb.wb
    80,    // bbbb.wb
    -14,   // wbbb.wb
    16,    // .wbb.wb
    -51,   // bwbb.wb
    8,     // wwbb.wb
    0,     // ..wb.wb
    54,    // b.wb.wb
    -41,   // w.wb.wb
    -15,   // .bwb.wb
    -55,   // bbwb.wb
    -52,   // wbwb.wb
    -77,   // .wwb.wb
    132,   // bwwb.wb
    -39,   // wwwb.wb
    50,    // ...w.wb
    -51,   // b..w.wb
    28,    // w..w.wb
    48,    // .b.w.wb
    45,    // bb.w.wb
    -36,   // wb.w.wb
    -6,    // .w.w.wb
    8,     // bw.w.wb
    -67,   // ww.w.wb
    25,    // ..bw.wb
    -20,   // b.bw.wb
    -45,   // w.bw.wb
    -30,   // .bbw.wb
    36,    // bbbw.wb
    -32,   // wbbw.wb
    90,    // .wbw.wb
    60,    // bwbw.wb
    -41,   // wwbw.wb
    -1,    // ..ww.wb
    28,    // b.ww.wb
    56,    // w.ww.wb
    2,     // .bww.wb
    83,    // bbww.wb
    44,    // wbww.wb
    -71,   // .www.wb
    -80,   // bwww.wb
    -55,   // wwww.wb
    38,    // ....bwb
    -28,   // b...bwb
    -9,    // w...bwb
    5,     // .b..bwb
    -75,   // bb..bwb
    -51,   // wb..bwb
    76,    // .w..bwb
    -51,   // bw..bwb
    -4,    // ww..bwb
    -77,   // ..b.bwb
    -43,   // b.b.bwb
    -71,   // w.b.bwb
    -60,   // .bb.bwb
    -58,   // bbb.bwb
    50,    // wbb.bwb
    5,     // .wb.bwb
    -12,   // bwb.bwb
    92,    // wwb.bwb
    30,    // ..w.bwb
    64,    // b.w.bwb
    -27,   // w.w.bwb
    -16,   // .bw.bwb
    17,    // bbw.bwb
    0,     // wbw.bwb
    72,    // .ww.bwb
    47,    // bww.bwb
    33,    // www.bwb
    2,     // ...bbwb
    140,   // b..bbwb
    -21,   // w..bbwb
    12,    // .b.bbwb
    -12,   // bb.bbwb
    -44,   // wb.bbwb
    -110,  // .w.bbwb
    -51,   // bw.bbwb
    34,    // ww.bbwb
    -31,   // ..bbbwb
    -41,   // b.bbbwb
    -19,   // w.bbbwb
    -4,    // .bbbbwb
    -8,    // bbbbbwb
    -113,  // wbbbbwb
    80,    // .wbbbwb
    67,    // bwbbbwb
    40,    // wwbbbwb
    5,     // ..wbbwb
    37,    // b.wbbwb
    -1,    // w.wbbwb
    -32,   // .bwbbwb
    19,    // bbwbbwb
    88,    // wbwbbwb
    -23,   // .wwbbwb
    -22,   // bwwbbwb
    35,    // wwwbbwb
    -4,    // ...wbwb
    -85,   // b..wbwb
    30,    // w..wbwb
    21,    // .b.wbwb
    49,    // bb.wbwb
    52,    // wb.wbwb
    -24,   // .w.wbwb
    60,    // bw.wbwb
    -6,    // ww.wbwb
    -2,    // ..bwbwb
    38,    // b.bwbwb
    68,    // w.bwbwb
    -56,   // .bbwbwb
    20,    // bbbwbwb
    4,     // wbbwbwb
    37,    // .wbwbwb
    -46,   // bwbwbwb
    -130,  // wwbwbwb
    -60,   // ..wwbwb
    46,    // b.wwbwb
    -31,   // w.wwbwb
    -53,   // .bwwbwb
    -33,   // bbwwbwb
    -88,   // wbwwbwb
    -60,   // .wwwbwb
    0,     // bwwwbwb
    -58,   // wwwwbwb
    75,    // ....wwb
    -56,   // b...wwb
    50,    // w...wwb
    -7,    // .b..wwb
    1,     // bb..wwb
    55,    // wb..wwb
    -101,  // .w..wwb
    -54,   // bw..wwb
    23,    // ww..wwb
    11,    // ..b.wwb
    67,    // b.b.wwb
    -83,   // w.b.wwb
    52,    // .bb.wwb
    -33,   // bbb.wwb
    0,     // wbb.wwb
    -11,   // .wb.wwb
    47,    // bwb.wwb
    0,     // wwb.wwb
    42,    // ..w.wwb
    7,     // b.w.wwb
    18,    // w.w.wwb
    -59,   // .bw.wwb
    -8,    // bbw.wwb
    -50,   // wbw.wwb
    37,    // .ww.wwb
    -67,   // bww.wwb
    8,     // www.wwb
    28,    // ...bwwb
    -10,   // b..bwwb
    22,    // w..bwwb
    27,    // .b.bwwb
    6,     // bb.bwwb
    32,    // wb.bwwb
    80,    // .w.bwwb
    132,   // bw.bwwb
    -31,   // ww.bwwb
    -92,   // ..bbwwb
    -72,   // b.bbwwb
    -66,   // w.bbwwb
    39,    // .bbbwwb
    -28,   // bbbbwwb
    35,    // wbbbwwb
    56,    // .wbbwwb
    -22,   // bwbbwwb
    -16,   // wwbbwwb
    -48,   // ..wbwwb
    49,    // b.wbwwb
    50,    // w.wbwwb
    107,   // .bwbwwb
    7,     // bbwbwwb
    -4,    // wbwbwwb
    55,    // .wwbwwb
    13,    // bwwbwwb
    163,   // wwwbwwb
    116,   // ...wwwb
    15,    // b..wwwb
    99,    // w..wwwb
    36,    // .b.wwwb
    -4,    // bb.wwwb
    14,    // wb.wwwb
    -80,   // .w.wwwb
    -80,   // bw.wwwb
    -8,    // ww.wwwb
    -1,    // ..bwwwb
    20,    // b.bwwwb
    22,    // w.bwwwb
    55,    // .bbwwwb
    17,    // bbbwwwb
    -35,   // wbbwwwb
    20,    // .wbwwwb
    0,     // bwbwwwb
    -35,   // wwbwwwb
    -62,   // ..wwwwb
    -4,    // b.wwwwb
    1,     // w.wwwwb
    123,   // .bwwwwb
    -1,    // bbwwwwb
    113,   // wbwwwwb
    34,    // .wwwwwb
    8,     // bwwwwwb
    7,     // wwwwwwb
    -3,    // ......w
    0,     // b.....w
    51,    // w.....w
    -49,   // .b....w
    5,     // bb....w
    -41,   // wb....w
    -7,    // .w....w
    0,     // bw....w
    5,     // ww....w
    -20,   // ..b...w
    -37,   // b.b...w
    12,    // w.b...w
    29,    // .bb...w
    38,    // bbb...w
    56,    // wbb...w
    20,    // .wb...w
    -9,    // bwb...w
    6,     // wwb...w
    -18,   // ..w...w
    30,    // b.w...w
    -44,   // w.w...w
    27,    // .bw...w
    -7,    // bbw...w
    28,    // wbw...w
    30,    // .ww...w
    50,    // bww...w
    35,    // www...w
    -8,    // ...b..w
    72,    // b..b..w
    69,    // w..b..w
    -30,   // .b.b..w
    -1,    // bb.b..w
    51,    // wb.b..w
    37,    // .w.b..w
    39,    // bw.b..w
    2,     // ww.b..w
    26,    // ..bb..w
    -35,   // b.bb..w
    49,    // w.bb..w
    -21,   // .bbb..w
    45,    // bbbb..w
    -15,   // wbbb..w
    23,    // .wbb..w
    -21,   // bwbb..w
    40,    // wwbb..w
    -86,   // ..wb..w
    -21,   // b.wb..w
    -14,   // w.wb..w
    46,    // .bwb..w
    14,    // bbwb..w
    85,    // wbwb..w
    -17,   // .wwb..w
    22,    // bwwb..w
    -44,   // wwwb..w
    5,     // ...w..w
    -72,   // b..w..w
    0,     // w..w..w
    5,     // .b.w..w
    -108,  // bb.w..w
    57,    // wb.w..w
    58,    // .w.w..w
    28,    // bw.w..w
    -2,    // ww.w..w
    39,    // ..bw..w
    -23,   // b.bw..w
    3,     // w.bw..w
    4,     // .bbw..w
    -22,   // bbbw..w
    10,    // wbbw..w
    -29,   // .wbw..w
    30,    // bwbw..w
    57,    // wwbw..w
    37,    // ..ww..w
    -4,    // b.ww..w
    78,    // w.ww..w
    8,     // .bww..w
    60,    // bbww..w
    -140,  // wbww..w
    -37,   // .www..w
    99,    // bwww..w
    -1,    // wwww..w
    -32,   // ....b.w
    -30,   // b...b.w
    12,    // w...b.w
    -47,   // .b..b.w
    49,    // bb..b.w
    -19,   // wb..b.w
    24,    // .w..b.w
    -112,  // bw..b.w
    -9,    // ww..b.w
    -63,   // ..b.b.w
    30,    // b.b.b.w
    -40,   // w.b.b.w
    5,     // .bb.b.w
    -28,   // bbb.b.w
    -7,    // wbb.b.w
    2,     // .wb.b.w
    -71,   // bwb.b.w
    20,    // wwb.b.w
    -30,   // ..w.b.w
    0,     // b.w.b.w
    -27,   // w.w.b.w
    29,    // .bw.b.w
    -1,    // bbw.b.w
    -64,   // wbw.b.w
    47,    // .ww.b.w
    -83,   // bww.b.w
    -16,   // www.b.w
    31,    // ...bb.w
    4,     // b..bb.w
    49,    // w..bb.w
    97,    // .b.bb.w
    35,    // bb.bb.w
    -28,   // wb.bb.w
    0,     // .w.bb.w
    -71,   // bw.bb.w
    5,     // ww.bb.w
    -32,   // ..bbb.w
    -28,   // b.bbb.w
    63,    // w.bbb.w
    64,    // .bbbb.w
    37,    // bbbbb.w
    4,     // wbbbb.w
    -106,  // .wbbb.w
    -19,   // bwbbb.w
    -5,    // wwbbb.w
    -13,   // ..wbb.w
    13,    // b.wbb.w
    -11,   // w.wbb.w
    -21,   // .bwbb.w
    64,    // bbwbb.w
    -46,   // wbwbb.w
    47,    // .wwbb.w
    -66,   // bwwbb.w
    -52,   // wwwbb.w
    -47,   // ...wb.w
    21,    // b..wb.w
    3,     // w..wb.w
    33,    // .b.wb.w
    -1,    // bb.wb.w
    -54,   // wb.wb.w
    38,    // .w.wb.w
    -45,   // bw.wb.w
    -13,   // ww.wb.w
    6,     // ..bwb.w
    7,     // b.bwb.w
    33,    // w.bwb.w
    -31,   // .bbwb.w
    101,   // bbbwb.w
    -49,   // wbbwb.w
    34,    // .wbwb.w
    68,    // bwbwb.w
    30,    // wwbwb.w
    23,    // ..wwb.w
    -13,   // b.wwb.w
    -9,    // w.wwb.w
    -49,   // .bwwb.w
    60,    // bbwwb.w
    -37,   // wbwwb.w
    16,    // .wwwb.w
    22,    // bwwwb.w
    -40,   // wwwwb.w
    -81,   // ....w.w
    37,    // b...w.w
    -44,   // w...w.w
    -9,    // .b..w.w
    1,     // bb..w.w
    -51,   // wb..w.w
    -27,   // .w..w.w
    -94,   // bw..w.w
    52,    // ww..w.w
    -61,   // ..b.w.w
    0,     // b.b.w.w
    -27,   // w.b.w.w
    29,    // .bb.w.w
    12,    // bbb.w.w
    -67,   // wbb.w.w
    39,    // .wb.w.w
    -27,   // bwb.w.w
    -13,   // wwb.w.w
    -18,   // ..w.w.w
    -30,   // b.w.w.w
    -19,   // w.w.w.w
    61,    // .bw.w.w
    70,    // bbw.w.w
    43,    // wbw.w.w
    13,    // .ww.w.w
    18,    // bww.w.w
    -51,   // www.w.w
    -54,   // ...bw.w
    23,    // b..bw.w
    -14,   // w..bw.w
    -66,   // .b.bw.w
    -40,   // bb.bw.w
    20,    // wb.bw.w
    -19,   // .w.bw.w
    -41,   // bw.bw.w
    -26,   // ww.bw.w
    -26,   // ..bbw.w
    94,    // b.bbw.w
    -11,   // w.bbw.w
    -2,    // .bbbw.w
    -27,   // bbbbw.w
    -20,   // wbbbw.w
    51,    // .wbbw.w
    -1,    // bwbbw.w
    11,    // wwbbw.w
    -18,   // ..wbw.w
    -7,    // b.wbw.w
    -39,   // w.wbw.w
    -7,    // .bwbw.w
    -68,   // bbwbw.w
    -38,   // wbwbw.w
    132,   // .wwbw.w
    50,    // bwwbw.w
    56,    // wwwbw.w
    -33,   // ...ww.w
    35,    // b..ww.w
    78,    // w..ww.w
    -72,   // .b.ww.w
    42,    // bb.ww.w
    -30,   // wb.ww.w
    31,    // .w.ww.w
    56,    // bw.ww.w
    50,    // ww.ww.w
    70,    // ..bww.w
    -94,   // b.bww.w
    -9,    // w.bww.w
    10,    // .bbww.w
    -91,   // bbbww.w
    72,    // wbbww.w
    3,     // .wbww.w
    -31,   // bwbww.w
    29,    // wwbww.w
    -71,   // ..www.w
    28,    // b.www.w
    -40,   // w.www.w
    -98,   // .bwww.w
    6,     // bbwww.w
    41,    // wbwww.w
    -55,   // .wwww.w
    1,     // bwwww.w
    64,    // wwwww.w
    -16,   // .....bw
    0,     // b....bw
    -41,   // w....bw
    5,     // .b...bw
    -41,   // bb...bw
    107,   // wb...bw
    -17,   // .w...bw
    0,     // bw...bw
    -6,    // ww...bw
    37,    // ..b..bw
    94,    // b.b..bw
    -19,   // w.b..bw
    -10,   // .bb..bw
    43,    // bbb..bw
    54,    // wbb..bw
    20,    // .wb..bw
    -51,   // bwb..bw
    -61,   // wwb..bw
    -15,   // ..w..bw
    112,   // b.w..bw
    -51,   // w.w..bw
    -77,   // .bw..bw
    30,    // bbw..bw
    51,    // wbw..bw
    -14,   // .ww..bw
    55,    // bww..bw
    16,    // www..bw
    -50,   // ...b.bw
    -28,   // b..b.bw
    51,    // w..b.bw
    6,     // .b.b.bw
    67,    // bb.b.bw
    -8,    // wb.b.bw
    -48,   // .w.b.bw
    36,    // bw.b.bw
    -45,   // ww.b.bw
    1,     // ..bb.bw
    -56,   // b.bb.bw
    -28,   // w.bb.bw
    71,    // .bbb.bw
    55,    // bbbb.bw
    80,    // wbbb.bw
    -2,    // .wbb.bw
    -44,   // bwbb.bw
    -83,   // wwbb.bw
    -25,   // ..wb.bw
    45,    // b.wb.bw
    20,    // w.wb.bw
    -90,   // .bwb.bw
    41,    // bbwb.bw
    -60,   // wbwb.bw
    30,    // .wwb.bw
    32,    // bwwb.bw
    -36,   // wwwb.bw
    -20,   // ...w.bw
    -39,   // b..w.bw
    57,    // w..w.bw
    -30,   // .b.w.bw
    2,     // bb.w.bw
    59,    // wb.w.bw
    -4,    // .w.w.bw
    -36,   // bw.w.bw
    49,    // ww.w.bw
    0,     // ..bw.bw
    41,    // b.bw.bw
    -54,   // w.bw.bw
    77,    // .bbw.bw
    39,    // bbbw.bw
    -132,  // wbbw.bw
    15,    // .wbw.bw
    52,    // bwbw.bw
    55,    // wwbw.bw
    -21,   // ..ww.bw
    71,    // b.ww.bw
    -30,   // w.ww.bw
    -16,   // .bww.bw
    -8,    // bbww.bw
    51,    // wbww.bw
    -95,   // .www.bw
    14,    // bwww.bw
    -80,   // wwww.bw
    -75,   // ....bbw
    -50,   // b...bbw
    56,    // w...bbw
    101,   // .b..bbw
    -23,   // bb..bbw
    54,    // wb..bbw
    7,     // .w..bbw
    -55,   // bw..bbw
    -1,    // ww..bbw
    -42,   // ..b.bbw
    -18,   // b.b.bbw
    -7,    // w.b.bbw
    -37,   // .bb.bbw
    -8,    // bbb.bbw
    67,    // wbb.bbw
    59,    // .wb.bbw
    50,    // bwb.bbw
    8,     // wwb.bbw
    -11,   // ..w.bbw
    83,    // b.w.bbw
    -67,   // w.w.bbw
    11,    // .bw.bbw
    0,     // bbw.bbw
    -47,   // wbw.bbw
    -52,   // .ww.bbw
    0,     // bww.bbw
    33,    // www.bbw
    -116,  // ...bbbw
    -99,   // b..bbbw
    -15,   // w..bbbw
    80,    // .b.bbbw
    8,     // bb.bbbw
    80,    // wb.bbbw
    -36,   // .w.bbbw
    -14,   // bw.bbbw
    4,     // ww.bbbw
    62,    // ..bbbbw
    -1,    // b.bbbbw
    4,     // w.bbbbw
    -34,   // .bbbbbw
    -7,    // bbbbbbw
    -8,    // wbbbbbw
    -123,  // .wbbbbw
    -113,  // bwbbbbw
    1,     // wwbbbbw
    1,     // ..wbbbw
    -22,   // b.wbbbw
    -20,   // w.wbbbw
    -20,   // .bwbbbw
    35,    // bbwbbbw
    0,     // wbwbbbw
    -55,   // .wwbbbw
    35,    // bwwbbbw
    -17,   // wwwbbbw
    -28,   // ...wbbw
    -22,   // b..wbbw
    10,    // w..wbbw
    -80,   // .b.wbbw
    31,    // bb.wbbw
    -132,  // wb.wbbw
    -27,   // .w.wbbw
    -32,   // bw.wbbw
    -6,    // ww.wbbw
    48,    // ..bwbbw
    -50,   // b.bwbbw
    -49,   // w.bwbbw
    -55,   // .bbwbbw
    -163,  // bbbwbbw
    -13,   // wbbwbbw
    -107,  // .wbwbbw
    4,     // bwbwbbw
    -7,    // wwbwbbw
    92,    // ..wwbbw
    66,    // b.wwbbw
    72,    // w.wwbbw
    -56,   // .bwwbbw
    16,    // bbwwbbw
    22,    // wbwwbbw
    -39,   // .wwwbbw
    -35,   // bwwwbbw
    28,    // wwwwbbw
    -38,   // ....wbw
    9,     // b...wbw
    28,    // w...wbw
    -76,   // .b..wbw
    4,     // bb..wbw
    51,    // wb..wbw
    -5,    // .w..wbw
    51,    // bw..wbw
    75,    // ww..wbw
    -30,   // ..b.wbw
    27,    // b.b.wbw
    -64,   // w.b.wbw
    -72,   // .bb.wbw
    -33,   // bbb.wbw
    -47,   // wbb.wbw
    16,    // .wb.wbw
    0,     // bwb.wbw
    -17,   // wwb.wbw
    77,    // ..w.wbw
    71,    // b.w.wbw
    43,    // w.w.wbw
    -5,    // .bw.wbw
    -92,   // bbw.wbw
    12,    // wbw.wbw
    60,    // .ww.wbw
    -50,   // bww.wbw
    58,    // www.wbw
    4,     // ...bwbw
    -30,   // b..bwbw
    85,    // w..bwbw
    24,    // .b.bwbw
    6,     // bb.bwbw
    -60,   // wb.bwbw
    -21,   // .w.bwbw
    -52,   // bw.bwbw
    -49,   // ww.bwbw
    60,    // ..bbwbw
    31,    // b.bbwbw
    -46,   // w.bbwbw
    60,    // .bbbwbw
    58,    // bbbbwbw
    0,     // wbbbwbw
    53,    // .wbbwbw
    88,    // bwbbwbw
    33,    // wwbbwbw
    2,     // ..wbwbw
    -68,   // b.wbwbw
    -38,   // w.wbwbw
    -37,   // .bwbwbw
    130,   // bbwbwbw
    46,    // wbwbwbw
    56,    // .wwbwbw
    -4,    // bwwbwbw
    -20,   // wwwbwbw
    -2,    // ...wwbw
    21,    // b..wwbw
    -140,  // w..wwbw
    110,   // .b.wwbw
    -34,   // bb.wwbw
    51,    // wb.wwbw
    -12,   // .w.wwbw
    44,    // bw.wwbw
    12,    // ww.wwbw
    -5,    // ..bwwbw
    1,     // b.bwwbw
    -37,   // w.bwwbw
    23,    // .bbwwbw
    -35,   // bbbwwbw
    22,    // wbbwwbw
    32,    // .wbwwbw
    -88,   // bwbwwbw
    -19,   // wwbwwbw
    31,    // ..wwwbw
    19,    // b.wwwbw
    41,    // w.wwwbw
    -80,   // .bwwwbw
    -40,   // bbwwwbw
    -67,   // wbwwwbw
    4,     // .wwwwbw
    113,   // bwwwwbw
    8,     // wwwwwbw
    -13,   // .....ww
    -5,    // b....ww
    5,     // w....ww
    -13,   // .b...ww
    0,     // bb...ww
    -6,    // wb...ww
    -12,   // .w...ww
    41,    // bw...ww
    31,    // ww...ww
    61,    // ..b..ww
    -1,    // b.b..ww
    -9,    // w.b..ww
    -63,   // .bb..ww
    -36,   // bbb..ww
    -1,    // wbb..ww
    -42,   // .wb..ww
    -4,    // bwb..ww
    -21,   // wwb..ww
    -7,    // ..w..ww
    -49,   // b.w..ww
    52,    // w.w..ww
    -67,   // .bw..ww
    -23,   // bbw..ww
    75,    // wbw..ww
    -4,    // .ww..ww
    23,    // bww..ww
    -75,   // www..ww
    -39,   // ...b.ww
    108,   // b..b.ww
    2,     // w..b.ww
    -29,   // .b.b.ww
    9,     // bb.b.ww
    -45,   // wb.b.ww
    71,    // .w.b.ww
    -2,    // bw.b.ww
    -107,  // ww.b.ww
    -18,   // ..bb.ww
    -42,   // b.bb.ww
    5,     // w.bb.ww
    33,    // .bbb.ww
    48,    // bbbb.ww
    4,     // wbbb.ww
    86,    // .wbb.ww
    34,    // bwbb.ww
    44,    // wwbb.ww
    58,    // ..wb.ww
    1,     // b.wb.ww
    -26,   // w.wb.ww
    -25,   // .bwb.ww
    -94,   // bbwb.ww
    -49,   // wbwb.ww
    -62,   // .wwb.ww
    -31,   // bwwb.ww
    -39,   // wwwb.ww
    -139,  // ...w.ww
    1,     // b..w.ww
    -2,    // w..w.ww
    -107,  // .b.w.ww
    -9,    // bb.w.ww
    49,    // wb.w.ww
    54,    // .w.w.ww
    -67,   // bw.w.ww
    -15,   // ww.w.ww
    8,     // ..bw.ww
    40,    // b.bw.ww
    -13,   // w.bw.ww
    -58,   // .bbw.ww
    3,     // bbbw.ww
    -6,    // wbbw.ww
    -14,   // .wbw.ww
    -6,    // bwbw.ww
    -36,   // wwbw.ww
    -10,   // ..ww.ww
    -35,   // b.ww.ww
    50,    // w.ww.ww
    -58,   // .bww.ww
    76,    // bbww.ww
    12,    // wbww.ww
    31,    // .www.ww
    -8,    // bwww.ww
    65,    // wwww.ww
    63,    // ....bww
    7,     // b...bww
    6,     // w...bww
    38,    // .b..bww
    23,    // bb..bww
    -61,   // wb..bww
    9,     // .w..bww
    -30,   // bw..bww
    -21,   // ww..bww
    -13,   // ..b.bww
    -70,   // b.b.bww
    20,    // w.b.bww
    -36,   // .bb.bww
    -57,   // bbb.bww
    8,     // wbb.bww
    10,    // .wb.bww
    92,    // bwb.bww
    87,    // wwb.bww
    36,    // ..w.bww
    1,     // b.w.bww
    -13,   // w.w.bww
    6,     // .bw.bww
    0,     // bbw.bww
    -17,   // wbw.bww
    6,     // .ww.bww
    0,     // bww.bww
    -44,   // www.bww
    17,    // ...bbww
    -60,   // b..bbww
    40,    // w..bbww
    -5,    // .b.bbww
    -76,   // bb.bbww
    -83,   // wb.bbww
    9,     // .w.bbww
    8,     // bw.bbww
    44,    // ww.bbww
    -22,   // ..bbbww
    -6,    // b.bbbww
    -5,    // w.bbbww
    -15,   // .bbbbww
    46,    // bbbbbww
    1,     // wbbbbww
    -21,   // .wbbbww
    40,    // bwbbbww
    3,     // wwbbbww
    -85,   // ..wbbww
    -60,   // b.wbbww
    11,    // w.wbbww
    102,   // .bwbbww
    82,    // bbwbbww
    33,    // wbwbbww
    104,   // .wwbbww
    -16,   // bwwbbww
    -21,   // wwwbbww
    55,    // ...wbww
    -14,   // b..wbww
    57,    // w..wbww
    16,    // .b.wbww
    94,    // bb.wbww
    55,    // wb.wbww
    -23,   // .w.wbww
    -41,   // bw.wbww
    -36,   // ww.wbww
    -44,   // ..bwbww
    68,    // b.bwbww
    30,    // w.bwbww
    126,   // .bbwbww
    -2,    // bbbwbww
    -7,    // wbbwbww
    -5,    // .wbwbww
    -130,  // bwbwbww
    33,    // wwbwbww
    19,    // ..wwbww
    -64,   // b.wwbww
    29,    // w.wwbww
    -21,   // .bwwbww
    -82,   // bbwwbww
    -19,   // wbwwbww
    89,    // .wwwbww
    -35,   // bwwwbww
    31,    // wwwwbww
    -144,  // ....www
    -38,   // b...www
    35,    // w...www
    -41,   // .b..www
    36,    // bb..www
    16,    // wb..www
    -27,   // .w..www
    -43,   // bw..www
    -75,   // ww..www
    -31,   // ..b.www
    -12,   // b.b.www
    -16,   // w.b.www
    -47,   // .bb.www
    0,     // bbb.www
    33,    // wbb.www
    -57,   // .wb.www
    33,    // bwb.www
    -44,   // wwb.www
    -94,   // ..w.www
    28,    // b.w.www
    -51,   // w.w.www
    -1,    // .bw.www
    57,    // bbw.www
    58,    // wbw.www
    -44,   // .ww.www
    8,     // bww.www
    -49,   // www.www
    -23,   // ...bwww
    22,    // b..bwww
    -44,   // w..bwww
    49,    // .b.bwww
    -3,    // bb.bwww
    -36,   // wb.bwww
    51,    // .w.bwww
    -39,   // bw.bwww
    -39,   // ww.bwww
    -60,   // ..bbwww
    91,    // b.bbwww
    -52,   // w.bbwww
    0,     // .bbbwww
    -78,   // bbbbwww
    -17,   // wbbbwww
    31,    // .wbbwww
    35,    // bwbbwww
    -21,   // wwbbwww
    166,   // ..wbwww
    -101,  // b.wbwww
    56,    // w.wbwww
    29,    // .bwbwww
    2,     // bbwbwww
    -20,   // wbwbwww
    5,     // .wwbwww
    163,   // bwwbwww
    -30,   // wwwbwww
    -405,  // ...wwww
    -45,   // b..wwww
    -1,    // w..wwww
    -164,  // .b.wwww
    -48,   // bb.wwww
    -80,   // wb.wwww
    58,    // .w.wwww
    -55,   // bw.wwww
    65,    // ww.wwww
    -50,   // ..bwwww
    27,    // b.bwwww
    -40,   // w.bwwww
    10,    // .bbwwww
    78,    // bbbwwww
    28,    // wbbwwww
    61,    // .wbwwww
    -58,   // bwbwwww
    31,    // wwbwwww
    -44,   // ..wwwww
    -37,   // b.wwwww
    64,    // w.wwwww
    -99,   // .bwwwww
    -46,   // bbwwwww
    8,     // wbwwwww
    14,    // .wwwwww
    7,     // bwwwwww
    40,    // wwwwwww
    0,     // captures=0 threats=0
    0,     // captures=0 threats=1
    0,     // captures=0 threats=2
    0,     // captures=0 threats=3
    0,     // captures=0 threats=4
    0,     // captures=0 additional threats
    0,     // captures=1 threats=0
    0,     // captures=1 threats=1
    0,     // captures=1 threats=2
    0,     // captures=1 threats=3
    0,     // captures=1 threats=4
    0,     // captures=1 additional threats
    0,     // captures=2 threats=0
    0,     // captures=2 threats=1
    0,     // captures=2 threats=2
    0,     // captures=2 threats=3
    0,     // captures=2 threats=4
    0,     // captures=2 additional threats
    0,     // captures=3 threats=0
    0,     // captures=3 threats=1
    0,     // captures=3 threats=2
    0,     // captures=3 threats=3
    0,     // captures=3 threats=4
    0,     // captures=3 additional threats
    0,     // captures=4 threats=0
    0,     // captures=4 threats=1
    0,     // captures=4 threats=2
    0,     // captures=4 threats=3
    0,     // captures=4 threats=4
    0,     // captures=4 additional threats
].into_boxed_slice()
