vec![
    0,     // .......
    -9,    // b......
    9,     // w......
    -5,    // .b.....
    23,    // bb.....
    13,    // wb.....
    5,     // .w.....
    -13,   // bw.....
    -23,   // ww.....
    4,     // ..b....
    -4,    // b.b....
    -16,   // w.b....
    -8,    // .bb....
    29,    // bbb....
    -34,   // wbb....
    -15,   // .wb....
    -10,   // bwb....
    8,     // wwb....
    -4,    // ..w....
    16,    // b.w....
    4,     // w.w....
    15,    // .bw....
    -8,    // bbw....
    10,    // wbw....
    8,     // .ww....
    34,    // bww....
    -29,   // www....
    -4,    // ...b...
    -14,   // b..b...
    4,     // w..b...
    -7,    // .b.b...
    4,     // bb.b...
    -4,    // wb.b...
    21,    // .w.b...
    -9,    // bw.b...
    0,     // ww.b...
    -16,   // ..bb...
    -11,   // b.bb...
    -6,    // w.bb...
    7,     // .bbb...
    39,    // bbbb...
    -27,   // wbbb...
    3,     // .wbb...
    -6,    // bwbb...
    -26,   // wwbb...
    4,     // ..wb...
    8,     // b.wb...
    -3,    // w.wb...
    -13,   // .bwb...
    -1,    // bbwb...
    -14,   // wbwb...
    14,    // .wwb...
    -3,    // bwwb...
    20,    // wwwb...
    4,     // ...w...
    -4,    // b..w...
    14,    // w..w...
    -21,   // .b.w...
    0,     // bb.w...
    9,     // wb.w...
    7,     // .w.w...
    4,     // bw.w...
    -4,    // ww.w...
    -4,    // ..bw...
    3,     // b.bw...
    -8,    // w.bw...
    -14,   // .bbw...
    -20,   // bbbw...
    3,     // wbbw...
    13,    // .wbw...
    14,    // bwbw...
    1,     // wwbw...
    16,    // ..ww...
    6,     // b.ww...
    11,    // w.ww...
    -3,    // .bww...
    26,    // bbww...
    6,     // wbww...
    -7,    // .www...
    27,    // bwww...
    -39,   // wwww...
    4,     // ....b..
    -2,    // b...b..
    9,     // w...b..
    -3,    // .b..b..
    -6,    // bb..b..
    -4,    // wb..b..
    1,     // .w..b..
    0,     // bw..b..
    -9,    // ww..b..
    -1,    // ..b.b..
    -34,   // b.b.b..
    15,    // w.b.b..
    9,     // .bb.b..
    -1,    // bbb.b..
    -9,    // wbb.b..
    20,    // .wb.b..
    -5,    // bwb.b..
    2,     // wwb.b..
    0,     // ..w.b..
    -10,   // b.w.b..
    -3,    // w.w.b..
    3,     // .bw.b..
    -6,    // bbw.b..
    -4,    // wbw.b..
    16,    // .ww.b..
    -5,    // bww.b..
    11,    // www.b..
    -16,   // ...bb..
    -5,    // b..bb..
    -8,    // w..bb..
    29,    // .b.bb..
    -19,   // bb.bb..
    0,     // wb.bb..
    12,    // .w.bb..
    -5,    // bw.bb..
    -5,    // ww.bb..
    -7,    // ..bbb..
    3,     // b.bbb..
    -10,   // w.bbb..
    45,    // .bbbb..
    19,    // bbbbb..
    5,     // wbbbb..
    -28,   // .wbbb..
    -4,    // bwbbb..
    -6,    // wwbbb..
    2,     // ..wbb..
    -12,   // b.wbb..
    -5,    // w.wbb..
    -10,   // .bwbb..
    -15,   // bbwbb..
    -24,   // wbwbb..
    -7,    // .wwbb..
    9,     // bwwbb..
    4,     // wwwbb..
    -4,    // ...wb..
    2,     // b..wb..
    0,     // w..wb..
    -6,    // .b.wb..
    3,     // bb.wb..
    2,     // wb.wb..
    9,     // .w.wb..
    -8,    // bw.wb..
    -9,    // ww.wb..
    1,     // ..bwb..
    -2,    // b.bwb..
    -5,    // w.bwb..
    27,    // .bbwb..
    3,     // bbbwb..
    2,     // wbbwb..
    -7,    // .wbwb..
    8,     // bwbwb..
    4,     // wwbwb..
    -2,    // ..wwb..
    -2,    // b.wwb..
    -22,   // w.wwb..
    -6,    // .bwwb..
    5,     // bbwwb..
    9,     // wbwwb..
    25,    // .wwwb..
    9,     // bwwwb..
    -13,   // wwwwb..
    -4,    // ....w..
    -9,    // b...w..
    2,     // w...w..
    -1,    // .b..w..
    9,     // bb..w..
    0,     // wb..w..
    3,     // .w..w..
    4,     // bw..w..
    6,     // ww..w..
    0,     // ..b.w..
    3,     // b.b.w..
    10,    // w.b.w..
    -16,   // .bb.w..
    -11,   // bbb.w..
    5,     // wbb.w..
    -3,    // .wb.w..
    4,     // bwb.w..
    6,     // wwb.w..
    1,     // ..w.w..
    -15,   // b.w.w..
    34,    // w.w.w..
    -20,   // .bw.w..
    -2,    // bbw.w..
    5,     // wbw.w..
    -9,    // .ww.w..
    9,     // bww.w..
    1,     // www.w..
    4,     // ...bw..
    0,     // b..bw..
    -2,    // w..bw..
    -9,    // .b.bw..
    9,     // bb.bw..
    8,     // wb.bw..
    6,     // .w.bw..
    -2,    // bw.bw..
    -3,    // ww.bw..
    2,     // ..bbw..
    22,    // b.bbw..
    2,     // w.bbw..
    -25,   // .bbbw..
    13,    // bbbbw..
    -9,    // wbbbw..
    6,     // .wbbw..
    -9,    // bwbbw..
    -5,    // wwbbw..
    -1,    // ..wbw..
    5,     // b.wbw..
    2,     // w.wbw..
    7,     // .bwbw..
    -4,    // bbwbw..
    -8,    // wbwbw..
    -27,   // .wwbw..
    -2,    // bwwbw..
    -3,    // wwwbw..
    16,    // ...ww..
    8,     // b..ww..
    5,     // w..ww..
    -12,   // .b.ww..
    5,     // bb.ww..
    5,     // wb.ww..
    -29,   // .w.ww..
    0,     // bw.ww..
    19,    // ww.ww..
    -2,    // ..bww..
    5,     // b.bww..
    12,    // w.bww..
    7,     // .bbww..
    -4,    // bbbww..
    -9,    // wbbww..
    10,    // .wbww..
    24,    // bwbww..
    15,    // wwbww..
    7,     // ..www..
    10,    // b.www..
    -3,    // w.www..
    28,    // .bwww..
    6,     // bbwww..
    4,     // wbwww..
    -45,   // .wwww..
    -5,    // bwwww..
    -19,   // wwwww..
    -5,    // .....b.
    -19,   // b....b.
    3,     // w....b.
    12,    // .b...b.
    15,    // bb...b.
    0,     // wb...b.
    0,     // .w...b.
    14,    // bw...b.
    7,     // ww...b.
    -3,    // ..b..b.
    -3,    // b.b..b.
    -1,    // w.b..b.
    -19,   // .bb..b.
    6,     // bbb..b.
    15,    // wbb..b.
    9,     // .wb..b.
    9,     // bwb..b.
    6,     // wwb..b.
    -1,    // ..w..b.
    -17,   // b.w..b.
    21,    // w.w..b.
    -13,   // .bw..b.
    -23,   // bbw..b.
    -30,   // wbw..b.
    12,    // .ww..b.
    -29,   // bww..b.
    -26,   // www..b.
    -7,    // ...b.b.
    -2,    // b..b.b.
    5,     // w..b.b.
    7,     // .b.b.b.
    7,     // bb.b.b.
    -3,    // wb.b.b.
    -6,    // .w.b.b.
    -23,   // bw.b.b.
    3,     // ww.b.b.
    29,    // ..bb.b.
    -3,    // b.bb.b.
    9,     // w.bb.b.
    -7,    // .bbb.b.
    8,     // bbbb.b.
    18,    // wbbb.b.
    5,     // .wbb.b.
    0,     // bwbb.b.
    -30,   // wwbb.b.
    -9,    // ..wb.b.
    -4,    // b.wb.b.
    6,     // w.wb.b.
    -6,    // .bwb.b.
    1,     // bbwb.b.
    -9,    // wbwb.b.
    12,    // .wwb.b.
    11,    // bwwb.b.
    -4,    // wwwb.b.
    -21,   // ...w.b.
    15,    // b..w.b.
    -24,   // w..w.b.
    -25,   // .b.w.b.
    5,     // bb.w.b.
    7,     // wb.w.b.
    6,     // .w.w.b.
    11,    // bw.w.b.
    6,     // ww.w.b.
    -6,    // ..bw.b.
    3,     // b.bw.b.
    1,     // w.bw.b.
    -3,    // .bbw.b.
    4,     // bbbw.b.
    -21,   // wbbw.b.
    -10,   // .wbw.b.
    -9,    // bwbw.b.
    28,    // wwbw.b.
    -12,   // ..ww.b.
    5,     // b.ww.b.
    0,     // w.ww.b.
    -19,   // .bww.b.
    -30,   // bbww.b.
    19,    // wbww.b.
    -22,   // .www.b.
    -7,    // bwww.b.
    3,     // wwww.b.
    -8,    // ....bb.
    -15,   // b...bb.
    -10,   // w...bb.
    -19,   // .b..bb.
    6,     // bb..bb.
    9,     // wb..bb.
    -12,   // .w..bb.
    -7,    // bw..bb.
    20,    // ww..bb.
    9,     // ..b.bb.
    15,    // b.b.bb.
    -15,   // w.b.bb.
    -1,    // .bb.bb.
    -7,    // bbb.bb.
    11,    // wbb.bb.
    10,    // .wb.bb.
    23,    // bwb.bb.
    0,     // wwb.bb.
    -16,   // ..w.bb.
    2,     // b.w.bb.
    -14,   // w.w.bb.
    12,    // .bw.bb.
    -10,   // bbw.bb.
    -12,   // wbw.bb.
    0,     // .ww.bb.
    -5,    // bww.bb.
    -11,   // www.bb.
    7,     // ...bbb.
    -4,    // b..bbb.
    -1,    // w..bbb.
    -7,    // .b.bbb.
    9,     // bb.bbb.
    9,     // wb.bbb.
    22,    // .w.bbb.
    17,    // bw.bbb.
    -10,   // ww.bbb.
    45,    // ..bbbb.
    1,     // b.bbbb.
    -3,    // w.bbbb.
    -4,    // .bbbbb.
    6,     // bbbbbb.
    15,    // wbbbbb.
    21,    // .wbbbb.
    8,     // bwbbbb.
    21,    // wwbbbb.
    -25,   // ..wbbb.
    16,    // b.wbbb.
    4,     // w.wbbb.
    -20,   // .bwbbb.
    -6,    // bbwbbb.
    1,     // wbwbbb.
    2,     // .wwbbb.
    0,     // bwwbbb.
    1,     // wwwbbb.
    -14,   // ...wbb.
    17,    // b..wbb.
    2,     // w..wbb.
    -3,    // .b.wbb.
    22,    // bb.wbb.
    -13,   // wb.wbb.
    -12,   // .w.wbb.
    -4,    // bw.wbb.
    -6,    // ww.wbb.
    27,    // ..bwbb.
    5,     // b.bwbb.
    -7,    // w.bwbb.
    -19,   // .bbwbb.
    -4,    // bbbwbb.
    4,     // wbbwbb.
    9,     // .wbwbb.
    1,     // bwbwbb.
    0,     // wwbwbb.
    7,     // ..wwbb.
    -16,   // b.wwbb.
    -3,    // w.wwbb.
    -1,    // .bwwbb.
    -12,   // bbwwbb.
    5,     // wbwwbb.
    -2,    // .wwwbb.
    11,    // bwwwbb.
    14,    // wwwwbb.
    15,    // ....wb.
    18,    // b...wb.
    -11,   // w...wb.
    -13,   // .b..wb.
    -5,    // bb..wb.
    -12,   // wb..wb.
    -9,    // .w..wb.
    -4,    // bw..wb.
    0,     // ww..wb.
    3,     // ..b.wb.
    -6,    // b.b.wb.
    -10,   // w.b.wb.
    12,    // .bb.wb.
    0,     // bbb.wb.
    -17,   // wbb.wb.
    0,     // .wb.wb.
    13,    // bwb.wb.
    9,     // wwb.wb.
    -20,   // ..w.wb.
    5,     // b.w.wb.
    29,    // w.w.wb.
    -6,    // .bw.wb.
    7,     // bbw.wb.
    3,     // wbw.wb.
    -10,   // .ww.wb.
    -4,    // bww.wb.
    8,     // www.wb.
    -13,   // ...bwb.
    5,     // b..bwb.
    0,     // w..bwb.
    -6,    // .b.bwb.
    -5,    // bb.bwb.
    -2,    // wb.bwb.
    10,    // .w.bwb.
    4,     // bw.bwb.
    9,     // ww.bwb.
    -10,   // ..bbwb.
    -11,   // b.bbwb.
    13,    // w.bbwb.
    -20,   // .bbbwb.
    3,     // bbbbwb.
    2,     // wbbbwb.
    -5,    // .wbbwb.
    -12,   // bwbbwb.
    12,    // wwbbwb.
    7,     // ..wbwb.
    -13,   // b.wbwb.
    -14,   // w.wbwb.
    -12,   // .bwbwb.
    23,    // bbwbwb.
    14,    // wbwbwb.
    -9,    // .wwbwb.
    -4,    // bwwbwb.
    -8,    // wwwbwb.
    -3,    // ...wwb.
    -4,    // b..wwb.
    -13,   // w..wwb.
    -19,   // .b.wwb.
    0,     // bb.wwb.
    8,     // wb.wwb.
    -5,    // .w.wwb.
    4,     // bw.wwb.
    1,     // ww.wwb.
    -6,    // ..bwwb.
    10,    // b.bwwb.
    -2,    // w.bwwb.
    -1,    // .bbwwb.
    -23,   // bbbwwb.
    -15,   // wbbwwb.
    5,     // .wbwwb.
    6,     // bwbwwb.
    0,     // wwbwwb.
    28,    // ..wwwb.
    4,     // b.wwwb.
    -7,    // w.wwwb.
    -3,    // .bwwwb.
    -12,   // bbwwwb.
    -3,    // wbwwwb.
    -21,   // .wwwwb.
    4,     // bwwwwb.
    10,    // wwwwwb.
    5,     // .....w.
    -3,    // b....w.
    19,    // w....w.
    0,     // .b...w.
    -7,    // bb...w.
    -14,   // wb...w.
    -12,   // .w...w.
    0,     // bw...w.
    -15,   // ww...w.
    1,     // ..b..w.
    -21,   // b.b..w.
    17,    // w.b..w.
    -12,   // .bb..w.
    26,    // bbb..w.
    29,    // wbb..w.
    13,    // .wb..w.
    30,    // bwb..w.
    23,    // wwb..w.
    3,     // ..w..w.
    1,     // b.w..w.
    3,     // w.w..w.
    -9,    // .bw..w.
    -6,    // bbw..w.
    -9,    // wbw..w.
    19,    // .ww..w.
    -15,   // bww..w.
    -6,    // www..w.
    21,    // ...b.w.
    24,    // b..b.w.
    -15,   // w..b.w.
    -6,    // .b.b.w.
    -6,    // bb.b.w.
    -11,   // wb.b.w.
    25,    // .w.b.w.
    -7,    // bw.b.w.
    -5,    // ww.b.w.
    12,    // ..bb.w.
    0,     // b.bb.w.
    -5,    // w.bb.w.
    22,    // .bbb.w.
    -3,    // bbbb.w.
    7,     // wbbb.w.
    19,    // .wbb.w.
    -19,   // bwbb.w.
    30,    // wwbb.w.
    6,     // ..wb.w.
    -1,    // b.wb.w.
    -3,    // w.wb.w.
    10,    // .bwb.w.
    -28,   // bbwb.w.
    9,     // wbwb.w.
    3,     // .wwb.w.
    21,    // bwwb.w.
    -4,    // wwwb.w.
    7,     // ...w.w.
    -5,    // b..w.w.
    2,     // w..w.w.
    6,     // .b.w.w.
    -3,    // bb.w.w.
    23,    // wb.w.w.
    -7,    // .w.w.w.
    3,     // bw.w.w.
    -7,    // ww.w.w.
    9,     // ..bw.w.
    -6,    // b.bw.w.
    4,     // w.bw.w.
    -12,   // .bbw.w.
    4,     // bbbw.w.
    -11,   // wbbw.w.
    6,     // .wbw.w.
    9,     // bwbw.w.
    -1,    // wwbw.w.
    -29,   // ..ww.w.
    -9,    // b.ww.w.
    3,     // w.ww.w.
    -5,    // .bww.w.
    30,    // bbww.w.
    0,     // wbww.w.
    7,     // .www.w.
    -18,   // bwww.w.
    -8,    // wwww.w.
    -15,   // ....bw.
    11,    // b...bw.
    -18,   // w...bw.
    9,     // .b..bw.
    0,     // bb..bw.
    4,     // wb..bw.
    13,    // .w..bw.
    12,    // bw..bw.
    5,     // ww..bw.
    20,    // ..b.bw.
    -29,   // b.b.bw.
    -5,    // w.b.bw.
    10,    // .bb.bw.
    -8,    // bbb.bw.
    4,     // wbb.bw.
    6,     // .wb.bw.
    -3,    // bwb.bw.
    -7,    // wwb.bw.
    -3,    // ..w.bw.
    10,    // b.w.bw.
    6,     // w.w.bw.
    0,     // .bw.bw.
    -9,    // bbw.bw.
    -13,   // wbw.bw.
    -12,   // .ww.bw.
    17,    // bww.bw.
    0,     // www.bw.
    3,     // ...bbw.
    13,    // b..bbw.
    4,     // w..bbw.
    5,     // .b.bbw.
    -1,    // bb.bbw.
    -4,    // wb.bbw.
    19,    // .w.bbw.
    -8,    // bw.bbw.
    0,     // ww.bbw.
    -28,   // ..bbbw.
    7,     // b.bbbw.
    -4,    // w.bbbw.
    21,    // .bbbbw.
    -10,   // bbbbbw.
    -4,    // wbbbbw.
    3,     // .wbbbw.
    3,     // bwbbbw.
    12,    // wwbbbw.
    6,     // ..wbbw.
    2,     // b.wbbw.
    -10,   // w.wbbw.
    -5,    // .bwbbw.
    0,     // bbwbbw.
    -6,    // wbwbbw.
    1,     // .wwbbw.
    15,    // bwwbbw.
    23,    // wwwbbw.
    13,    // ...wbw.
    0,     // b..wbw.
    -5,    // w..wbw.
    -10,   // .b.wbw.
    -9,    // bb.wbw.
    -4,    // wb.wbw.
    6,     // .w.wbw.
    2,     // bw.wbw.
    5,     // ww.wbw.
    -7,    // ..bwbw.
    14,    // b.bwbw.
    13,    // w.bwbw.
    9,     // .bbwbw.
    8,     // bbbwbw.
    4,     // wbbwbw.
    12,    // .wbwbw.
    -14,   // bwbwbw.
    -23,   // wwbwbw.
    10,    // ..wwbw.
    -13,   // b.wwbw.
    11,    // w.wwbw.
    5,     // .bwwbw.
    -12,   // bbwwbw.
    12,    // wbwwbw.
    20,    // .wwwbw.
    -2,    // bwwwbw.
    -3,    // wwwwbw.
    8,     // ....ww.
    10,    // b...ww.
    15,    // w...ww.
    12,    // .b..ww.
    -20,   // bb..ww.
    7,     // wb..ww.
    19,    // .w..ww.
    -9,    // bw..ww.
    -6,    // ww..ww.
    16,    // ..b.ww.
    14,    // b.b.ww.
    -2,    // w.b.ww.
    0,     // .bb.ww.
    11,    // bbb.ww.
    5,     // wbb.ww.
    -12,   // .wb.ww.
    12,    // bwb.ww.
    10,    // wwb.ww.
    -9,    // ..w.ww.
    15,    // b.w.ww.
    -15,   // w.w.ww.
    -10,   // .bw.ww.
    0,     // bbw.ww.
    -23,   // wbw.ww.
    1,     // .ww.ww.
    -11,   // bww.ww.
    7,     // www.ww.
    14,    // ...bww.
    -2,    // b..bww.
    -17,   // w..bww.
    12,    // .b.bww.
    6,     // bb.bww.
    4,     // wb.bww.
    3,     // .w.bww.
    13,    // bw.bww.
    -22,   // ww.bww.
    -7,    // ..bbww.
    3,     // b.bbww.
    16,    // w.bbww.
    2,     // .bbbww.
    -14,   // bbbbww.
    -11,   // wbbbww.
    1,     // .wbbww.
    -5,    // bwbbww.
    12,    // wwbbww.
    -27,   // ..wbww.
    7,     // b.wbww.
    -5,    // w.wbww.
    -9,    // .bwbww.
    0,     // bbwbww.
    -1,    // wbwbww.
    19,    // .wwbww.
    -4,    // bwwbww.
    4,     // wwwbww.
    -7,    // ...www.
    1,     // b..www.
    4,     // w..www.
    -22,   // .b.www.
    10,    // bb.www.
    -17,   // wb.www.
    7,     // .w.www.
    -9,    // bw.www.
    -9,    // ww.www.
    25,    // ..bwww.
    -4,    // b.bwww.
    -16,   // w.bwww.
    -2,    // .bbwww.
    -1,    // bbbwww.
    0,     // wbbwww.
    20,    // .wbwww.
    -1,    // bwbwww.
    6,     // wwbwww.
    -45,   // ..wwww.
    3,     // b.wwww.
    -1,    // w.wwww.
    -21,   // .bwwww.
    -21,   // bbwwww.
    -8,    // wbwwww.
    4,     // .wwwww.
    -15,   // bwwwww.
    -6,    // wwwwww.
    -9,    // ......b
    15,    // b.....b
    0,     // w.....b
    -19,   // .b....b
    9,     // bb....b
    13,    // wb....b
    -3,    // .w....b
    24,    // bw....b
    -8,    // ww....b
    -2,    // ..b...b
    -5,    // b.b...b
    -15,   // w.b...b
    -15,   // .bb...b
    -21,   // bbb...b
    -10,   // wbb...b
    11,    // .wb...b
    -17,   // bwb...b
    -19,   // wwb...b
    -9,    // ..w...b
    -13,   // b.w...b
    19,    // w.w...b
    18,    // .bw...b
    -2,    // bbw...b
    -16,   // wbw...b
    10,    // .ww...b
    -8,    // bww...b
    -1,    // www...b
    -14,   // ...b..b
    -16,   // b..b..b
    -3,    // w..b..b
    -2,    // .b.b..b
    6,     // bb.b..b
    -5,    // wb.b..b
    24,    // .w.b..b
    -13,   // bw.b..b
    6,     // ww.b..b
    -5,    // ..bb..b
    2,     // b.bb..b
    -7,    // w.bb..b
    -4,    // .bbb..b
    8,     // bbbb..b
    19,    // wbbb..b
    13,    // .wbb..b
    0,     // bwbb..b
    -4,    // wwbb..b
    0,     // ..wb..b
    19,    // b.wb..b
    -9,    // w.wb..b
    5,     // .bwb..b
    10,    // bbwb..b
    -4,    // wbwb..b
    -2,    // .wwb..b
    -3,    // bwwb..b
    -19,   // wwwb..b
    -4,    // ...w..b
    -10,   // b..w..b
    3,     // w..w..b
    15,    // .b.w..b
    0,     // bb.w..b
    1,     // wb.w..b
    -5,    // .w.w..b
    8,     // bw.w..b
    -7,    // ww.w..b
    2,     // ..bw..b
    17,    // b.bw..b
    -22,   // w.bw..b
    17,    // .bbw..b
    -16,   // bbbw..b
    -17,   // wbbw..b
    0,     // .wbw..b
    -16,   // bwbw..b
    5,     // wwbw..b
    8,     // ..ww..b
    6,     // b.ww..b
    -9,    // w.ww..b
    -4,    // .bww..b
    -1,    // bbww..b
    10,    // wbww..b
    1,     // .www..b
    -8,    // bwww..b
    7,     // wwww..b
    -4,    // ....b.b
    -5,    // b...b.b
    -19,   // w...b.b
    -3,    // .b..b.b
    -14,   // bb..b.b
    -4,    // wb..b.b
    -21,   // .w..b.b
    15,    // bw..b.b
    2,     // ww..b.b
    -34,   // ..b.b.b
    -13,   // b.b.b.b
    -10,   // w.b.b.b
    15,    // .bb.b.b
    -6,    // bbb.b.b
    -6,    // wbb.b.b
    -29,   // .wb.b.b
    -10,   // bwb.b.b
    -10,   // wwb.b.b
    3,     // ..w.b.b
    4,     // b.w.b.b
    0,     // w.w.b.b
    -6,    // .bw.b.b
    1,     // bbw.b.b
    3,     // wbw.b.b
    14,    // .ww.b.b
    13,    // bww.b.b
    -5,    // www.b.b
    -11,   // ...bb.b
    2,     // b..bb.b
    9,     // w..bb.b
    -3,    // .b.bb.b
    9,     // bb.bb.b
    -2,    // wb.bb.b
    0,     // .w.bb.b
    11,    // bw.bb.b
    -9,    // ww.bb.b
    3,     // ..bbb.b
    -10,   // b.bbb.b
    33,    // w.bbb.b
    1,     // .bbbb.b
    11,    // bbbbb.b
    2,     // wbbbb.b
    7,     // .wbbb.b
    0,     // bwbbb.b
    2,     // wwbbb.b
    22,    // ..wbb.b
    27,    // b.wbb.b
    -19,   // w.wbb.b
    -11,   // .bwbb.b
    5,     // bbwbb.b
    -15,   // wbwbb.b
    3,     // .wwbb.b
    -2,    // bwwbb.b
    -10,   // wwwbb.b
    3,     // ...wb.b
    17,    // b..wb.b
    9,     // w..wb.b
    3,     // .b.wb.b
    5,     // bb.wb.b
    -2,    // wb.wb.b
    -6,    // .w.wb.b
    9,     // bw.wb.b
    5,     // ww.wb.b
    -2,    // ..bwb.b
    5,     // b.bwb.b
    -29,   // w.bwb.b
    5,     // .bbwb.b
    4,     // bbbwb.b
    -6,    // wbbwb.b
    14,    // .wbwb.b
    -18,   // bwbwb.b
    1,     // wwbwb.b
    5,     // ..wwb.b
    4,     // b.wwb.b
    19,    // w.wwb.b
    10,    // .bwwb.b
    1,     // bbwwb.b
    -10,   // wbwwb.b
    -4,    // .wwwb.b
    1,     // bwwwb.b
    -2,    // wwwwb.b
    16,    // ....w.b
    -13,   // b...w.b
    15,    // w...w.b
    -17,   // .b..w.b
    -1,    // bb..w.b
    29,    // wb..w.b
    1,     // .w..w.b
    -1,    // bw..w.b
    -10,   // ww..w.b
    -10,   // ..b.w.b
    4,     // b.b.w.b
    0,     // w.b.w.b
    2,     // .bb.w.b
    15,    // bbb.w.b
    10,    // wbb.w.b
    10,    // .wb.w.b
    19,    // bwb.w.b
    -8,    // wwb.w.b
    -15,   // ..w.w.b
    -18,   // b.w.w.b
    10,    // w.w.w.b
    5,     // .bw.w.b
    -5,    // bbw.w.b
    -7,    // wbw.w.b
    15,    // .ww.w.b
    1,     // bww.w.b
    11,    // www.w.b
    8,     // ...bw.b
    19,    // b..bw.b
    22,    // w..bw.b
    -4,    // .b.bw.b
    -7,    // bb.bw.b
    -3,    // wb.bw.b
    -1,    // .w.bw.b
    24,    // bw.bw.b
    -4,    // ww.bw.b
    -12,   // ..bbw.b
    27,    // b.bbw.b
    -8,    // w.bbw.b
    16,    // .bbbw.b
    -6,    // bbbbw.b
    -6,    // wbbbw.b
    2,     // .wbbw.b
    11,    // bwbbw.b
    -2,    // wwbbw.b
    5,     // ..wbw.b
    -5,    // b.wbw.b
    29,    // w.wbw.b
    -13,   // .bwbw.b
    11,    // bbwbw.b
    7,     // wbwbw.b
    7,     // .wwbw.b
    -6,    // bwwbw.b
    5,     // wwwbw.b
    6,     // ...ww.b
    6,     // b..ww.b
    7,     // w..ww.b
    5,     // .b.ww.b
    2,     // bb.ww.b
    4,     // wb.ww.b
    -9,    // .w.ww.b
    -8,    // bw.ww.b
    -1,    // ww.ww.b
    -2,    // ..bww.b
    4,     // b.bww.b
    8,     // w.bww.b
    -16,   // .bbww.b
    -9,    // bbbww.b
    7,     // wbbww.b
    -13,   // .wbww.b
    -5,    // bwbww.b
    -11,   // wwbww.b
    10,    // ..www.b
    -10,   // b.www.b
    -33,   // w.www.b
    4,     // .bwww.b
    3,     // bbwww.b
    17,    // wbwww.b
    3,     // .wwww.b
    -5,    // bwwww.b
    -16,   // wwwww.b
    23,    // .....bb
    9,     // b....bb
    8,     // w....bb
    15,    // .b...bb
    -18,   // bb...bb
    31,    // wb...bb
    -7,    // .w...bb
    0,     // bw...bb
    0,     // ww...bb
    -6,    // ..b..bb
    -14,   // b.b..bb
    10,    // w.b..bb
    6,     // .bb..bb
    21,    // bbb..bb
    2,     // wbb..bb
    0,     // .wb..bb
    -2,    // bwb..bb
    -3,    // wwb..bb
    9,     // ..w..bb
    -1,    // b.w..bb
    -2,    // w.w..bb
    -5,    // .bw..bb
    -13,   // bbw..bb
    1,     // wbw..bb
    -20,   // .ww..bb
    -11,   // bww..bb
    17,    // www..bb
    4,     // ...b.bb
    6,     // b..b.bb
    7,     // w..b.bb
    7,     // .b.b.bb
    -2,    // bb.b.bb
    -12,   // wb.b.bb
    -6,    // .w.b.bb
    -9,    // bw.b.bb
    -11,   // ww.b.bb
    -19,   // ..bb.bb
    9,     // b.bb.bb
    1,     // w.bb.bb
    9,     // .bbb.bb
    0,     // bbbb.bb
    0,     // wbbb.bb
    -1,    // .wbb.bb
    0,     // bwbb.bb
    -27,   // wwbb.bb
    9,     // ..wb.bb
    -7,    // b.wb.bb
    -5,    // w.wb.bb
    -5,    // .bwb.bb
    3,     // bbwb.bb
    -7,    // wbwb.bb
    6,     // .wwb.bb
    1,     // bwwb.bb
    3,     // wwwb.bb
    0,     // ...w.bb
    0,     // b..w.bb
    -6,    // w..w.bb
    5,     // .b.w.bb
    4,     // bb.w.bb
    -1,    // wb.w.bb
    -3,    // .w.w.bb
    -20,   // bw.w.bb
    11,    // ww.w.bb
    3,     // ..bw.bb
    5,     // b.bw.bb
    4,     // w.bw.bb
    22,    // .bbw.bb
    5,     // bbbw.bb
    -3,    // wbbw.bb
    -9,    // .wbw.bb
    1,     // bwbw.bb
    -6,    // wwbw.bb
    5,     // ..ww.bb
    2,     // b.ww.bb
    9,     // w.ww.bb
    0,     // .bww.bb
    2,     // bbww.bb
    12,    // wbww.bb
    10,    // .www.bb
    -10,   // bwww.bb
    4,     // wwww.bb
    29,    // ....bbb
    -21,   // b...bbb
    1,     // w...bbb
    6,     // .b..bbb
    21,    // bb..bbb
    0,     // wb..bbb
    26,    // .w..bbb
    6,     // bw..bbb
    -17,   // ww..bbb
    -1,    // ..b.bbb
    -6,    // b.b.bbb
    -11,   // w.b.bbb
    -7,    // .bb.bbb
    17,    // bbb.bbb
    6,     // wbb.bbb
    -8,    // .wb.bbb
    -3,    // bwb.bbb
    -16,   // wwb.bbb
    -11,   // ..w.bbb
    15,    // b.w.bbb
    5,     // w.w.bbb
    0,     // .bw.bbb
    6,     // bbw.bbb
    -10,   // wbw.bbb
    11,    // .ww.bbb
    -8,    // bww.bbb
    0,     // www.bbb
    39,    // ...bbbb
    8,     // b..bbbb
    -7,    // w..bbbb
    8,     // .b.bbbb
    0,     // bb.bbbb
    -8,    // wb.bbbb
    -3,    // .w.bbbb
    7,     // bw.bbbb
    -4,    // ww.bbbb
    19,    // ..bbbbb
    11,    // b.bbbbb
    16,    // w.bbbbb
    6,     // .bbbbbb
    12,    // bbbbbbb
    14,    // wbbbbbb
    -10,   // .wbbbbb
    -6,    // bwbbbbb
    19,    // wwbbbbb
    13,    // ..wbbbb
    -6,    // b.wbbbb
    2,     // w.wbbbb
    3,     // .bwbbbb
    18,    // bbwbbbb
    -13,   // wbwbbbb
    -14,   // .wwbbbb
    5,     // bwwbbbb
    -7,    // wwwbbbb
    -20,   // ...wbbb
    -16,   // b..wbbb
    19,    // w..wbbb
    4,     // .b.wbbb
    5,     // bb.wbbb
    -2,    // wb.wbbb
    4,     // .w.wbbb
    8,     // bw.wbbb
    -3,    // ww.wbbb
    3,     // ..bwbbb
    4,     // b.bwbbb
    -5,    // w.bwbbb
    -4,    // .bbwbbb
    -7,    // bbbwbbb
    -4,    // wbbwbbb
    8,     // .wbwbbb
    -2,    // bwbwbbb
    14,    // wwbwbbb
    -4,    // ..wwbbb
    -9,    // b.wwbbb
    10,    // w.wwbbb
    -23,   // .bwwbbb
    -12,   // bbwwbbb
    2,     // wbwwbbb
    -1,    // .wwwbbb
    -13,   // bwwwbbb
    7,     // wwwwbbb
    -8,    // ....wbb
    -2,    // b...wbb
    19,    // w...wbb
    -23,   // .b..wbb
    -13,   // bb..wbb
    1,     // wb..wbb
    -6,    // .w..wbb
    -5,    // bw..wbb
    3,     // ww..wbb
    -6,    // ..b.wbb
    1,     // b.b.wbb
    8,     // w.b.wbb
    -10,   // .bb.wbb
    6,     // bbb.wbb
    5,     // wbb.wbb
    -9,    // .wb.wbb
    0,     // bwb.wbb
    0,     // wwb.wbb
    -2,    // ..w.wbb
    -5,    // b.w.wbb
    10,    // w.w.wbb
    7,     // .bw.wbb
    15,    // bbw.wbb
    -13,   // wbw.wbb
    0,     // .ww.wbb
    -3,    // bww.wbb
    16,    // www.wbb
    -1,    // ...bwbb
    10,    // b..bwbb
    -5,    // w..bwbb
    1,     // .b.bwbb
    3,     // bb.bwbb
    10,    // wb.bwbb
    -28,   // .w.bwbb
    -9,    // bw.bwbb
    6,     // ww.bwbb
    -15,   // ..bbwbb
    5,     // b.bbwbb
    11,    // w.bbwbb
    -6,    // .bbbwbb
    18,    // bbbbwbb
    -21,   // wbbbwbb
    0,     // .wbbwbb
    9,     // bwbbwbb
    0,     // wwbbwbb
    -4,    // ..wbwbb
    11,    // b.wbwbb
    -1,    // w.wbwbb
    23,    // .bwbwbb
    0,     // bbwbwbb
    0,     // wbwbwbb
    0,     // .wwbwbb
    -25,   // bwwbwbb
    -14,   // wwwbwbb
    26,    // ...wwbb
    -1,    // b..wwbb
    4,     // w..wwbb
    -30,   // .b.wwbb
    2,     // bb.wwbb
    -1,    // wb.wwbb
    30,    // .w.wwbb
    24,    // bw.wwbb
    27,    // ww.wwbb
    5,     // ..bwwbb
    1,     // b.bwwbb
    2,     // w.bwwbb
    -12,   // .bbwwbb
    -12,   // bbbwwbb
    3,     // wbbwwbb
    -12,   // .wbwwbb
    -8,    // bwbwwbb
    0,     // wwbwwbb
    6,     // ..wwwbb
    3,     // b.wwwbb
    -2,    // w.wwwbb
    -12,   // .bwwwbb
    -8,    // bbwwwbb
    -3,    // wbwwwbb
    -21,   // .wwwwbb
    -8,    // bwwwwbb
    -19,   // wwwwwbb
    -13,   // .....wb
    24,    // b....wb
    -13,   // w....wb
    14,    // .b...wb
    0,     // bb...wb
    0,     // wb...wb
    0,     // .w...wb
    4,     // bw...wb
    -31,   // ww...wb
    0,     // ..b..wb
    15,    // b.b..wb
    -29,   // w.b..wb
    -7,    // .bb..wb
    6,     // bbb..wb
    7,     // wbb..wb
    12,    // .wb..wb
    -5,    // bwb..wb
    -1,    // wwb..wb
    4,     // ..w..wb
    -1,    // b.w..wb
    4,     // w.w..wb
    -4,    // .bw..wb
    -5,    // bbw..wb
    -21,   // wbw..wb
    -9,    // .ww..wb
    3,     // bww..wb
    0,     // www..wb
    -9,    // ...b.wb
    -13,   // b..b.wb
    -1,    // w..b.wb
    -23,   // .b.b.wb
    -9,    // bb.b.wb
    -1,    // wb.b.wb
    -7,    // .w.b.wb
    15,    // bw.b.wb
    1,     // ww.b.wb
    -5,    // ..bb.wb
    11,    // b.bb.wb
    -4,    // w.bb.wb
    17,    // .bbb.wb
    7,     // bbbb.wb
    16,    // wbbb.wb
    -8,    // .wbb.wb
    0,     // bwbb.wb
    1,     // wwbb.wb
    -2,    // ..wb.wb
    24,    // b.wb.wb
    2,     // w.wb.wb
    4,     // .bwb.wb
    -9,    // bbwb.wb
    13,    // wbwb.wb
    13,    // .wwb.wb
    -17,   // bwwb.wb
    2,     // wwwb.wb
    4,     // ...w.wb
    8,     // b..w.wb
    5,     // w..w.wb
    11,    // .b.w.wb
    -20,   // bb.w.wb
    1,     // wb.w.wb
    3,     // .w.w.wb
    -11,   // bw.w.wb
    12,    // ww.w.wb
    -8,    // ..bw.wb
    9,     // b.bw.wb
    3,     // w.bw.wb
    -4,    // .bbw.wb
    8,     // bbbw.wb
    1,     // wbbw.wb
    2,     // .wbw.wb
    -6,    // bwbw.wb
    -10,   // wwbw.wb
    0,     // ..ww.wb
    -8,    // b.ww.wb
    2,     // w.ww.wb
    4,     // .bww.wb
    24,    // bbww.wb
    5,     // wbww.wb
    -9,    // .www.wb
    -7,    // bwww.wb
    8,     // wwww.wb
    -10,   // ....bwb
    -17,   // b...bwb
    16,    // w...bwb
    9,     // .b..bwb
    -2,    // bb..bwb
    21,    // wb..bwb
    30,    // .w..bwb
    -5,    // bw..bwb
    -1,    // ww..bwb
    -5,    // ..b.bwb
    -10,   // b.b.bwb
    7,     // w.b.bwb
    23,    // .bb.bwb
    -3,    // bbb.bwb
    -12,   // wbb.bwb
    -3,    // .wb.bwb
    -11,   // bwb.bwb
    13,    // wwb.bwb
    4,     // ..w.bwb
    19,    // b.w.bwb
    -3,    // w.w.bwb
    13,    // .bw.bwb
    0,     // bbw.bwb
    0,     // wbw.bwb
    12,    // .ww.bwb
    -8,    // bww.bwb
    10,    // www.bwb
    -6,    // ...bbwb
    0,     // b..bbwb
    -10,   // w..bbwb
    0,     // .b.bbwb
    0,     // bb.bbwb
    -5,    // wb.bbwb
    -19,   // .w.bbwb
    0,     // bw.bbwb
    -12,   // ww.bbwb
    -4,    // ..bbbwb
    0,     // b.bbbwb
    -17,   // w.bbbwb
    8,     // .bbbbwb
    -6,    // bbbbbwb
    4,     // wbbbbwb
    3,     // .wbbbwb
    -16,   // bwbbbwb
    3,     // wwbbbwb
    -9,    // ..wbbwb
    11,    // b.wbbwb
    10,    // w.wbbwb
    -12,   // .bwbbwb
    9,     // bbwbbwb
    17,    // wbwbbwb
    -5,    // .wwbbwb
    2,     // bwwbbwb
    -2,    // wwwbbwb
    14,    // ...wbwb
    -16,   // b..wbwb
    4,     // w..wbwb
    -9,    // .b.wbwb
    1,     // bb.wbwb
    -13,   // wb.wbwb
    9,     // .w.wbwb
    -6,    // bw.wbwb
    7,     // ww.wbwb
    8,     // ..bwbwb
    -18,   // b.bwbwb
    -7,    // w.bwbwb
    1,     // .bbwbwb
    -2,    // bbbwbwb
    6,     // wbbwbwb
    -14,   // .wbwbwb
    -13,   // bwbwbwb
    0,     // wwbwbwb
    24,    // ..wwbwb
    -5,    // b.wwbwb
    15,    // w.wwbwb
    6,     // .bwwbwb
    -8,    // bbwwbwb
    -17,   // wbwwbwb
    -1,    // .wwwbwb
    19,    // bwwwbwb
    13,    // wwwwbwb
    34,    // ....wwb
    -8,    // b...wwb
    10,    // w...wwb
    -29,   // .b..wwb
    -11,   // bb..wwb
    -7,    // wb..wwb
    -15,   // .w..wwb
    3,     // bw..wwb
    -2,    // ww..wwb
    -5,    // ..b.wwb
    13,    // b.b.wwb
    -10,   // w.b.wwb
    -5,    // .bb.wwb
    -8,    // bbb.wwb
    0,     // wbb.wwb
    17,    // .wb.wwb
    -8,    // bwb.wwb
    -5,    // wwb.wwb
    9,     // ..w.wwb
    1,     // b.w.wwb
    6,     // w.w.wwb
    -4,    // .bw.wwb
    -3,    // bbw.wwb
    12,    // wbw.wwb
    -11,   // .ww.wwb
    4,     // bww.wwb
    -6,    // www.wwb
    -3,    // ...bwwb
    -3,    // b..bwwb
    17,    // w..bwwb
    11,    // .b.bwwb
    1,     // bb.bwwb
    -1,    // wb.bwwb
    21,    // .w.bwwb
    -17,   // bw.bwwb
    3,     // ww.bwwb
    9,     // ..bbwwb
    -2,    // b.bbwwb
    -7,    // w.bbwwb
    0,     // .bbbwwb
    5,     // bbbbwwb
    16,    // wbbbwwb
    15,    // .wbbwwb
    2,     // bwbbwwb
    -3,    // wwbbwwb
    -2,    // ..wbwwb
    -6,    // b.wbwwb
    6,     // w.wbwwb
    -4,    // .bwbwwb
    -25,   // bbwbwwb
    -6,    // wbwbwwb
    -4,    // .wwbwwb
    8,     // bwwbwwb
    4,     // wwwbwwb
    27,    // ...wwwb
    -8,    // b..wwwb
    -19,   // w..wwwb
    -7,    // .b.wwwb
    -10,   // bb.wwwb
    -16,   // wb.wwwb
    -18,   // .w.wwwb
    -7,    // bw.wwwb
    0,     // ww.wwwb
    9,     // ..bwwwb
    1,     // b.bwwwb
    6,     // w.bwwwb
    11,    // .bbwwwb
    -13,   // bbbwwwb
    -16,   // wbbwwwb
    -2,    // .wbwwwb
    19,    // bwbwwwb
    21,    // wwbwwwb
    -5,    // ..wwwwb
    -5,    // b.wwwwb
    -2,    // w.wwwwb
    4,     // .bwwwwb
    -8,    // bbwwwwb
    -4,    // wbwwwwb
    -15,   // .wwwwwb
    6,     // bwwwwwb
    -14,   // wwwwwwb
    9,     // ......w
    0,     // b.....w
    -15,   // w.....w
    3,     // .b....w
    8,     // bb....w
    -24,   // wb....w
    19,    // .w....w
    -13,   // bw....w
    -9,    // ww....w
    9,     // ..b...w
    -19,   // b.b...w
    13,    // w.b...w
    -10,   // .bb...w
    1,     // bbb...w
    8,     // wbb...w
    -18,   // .wb...w
    16,    // bwb...w
    2,     // wwb...w
    2,     // ..w...w
    15,    // b.w...w
    5,     // w.w...w
    -11,   // .bw...w
    19,    // bbw...w
    17,    // wbw...w
    15,    // .ww...w
    10,    // bww...w
    21,    // www...w
    4,     // ...b..w
    -3,    // b..b..w
    10,    // w..b..w
    5,     // .b.b..w
    7,     // bb.b..w
    -8,    // wb.b..w
    -15,   // .w.b..w
    -1,    // bw.b..w
    0,     // ww.b..w
    -8,    // ..bb..w
    9,     // b.bb..w
    -6,    // w.bb..w
    -1,    // .bbb..w
    -7,    // bbbb..w
    8,     // wbbb..w
    4,     // .wbb..w
    -10,   // bwbb..w
    1,     // wwbb..w
    -2,    // ..wb..w
    22,    // b.wb..w
    -17,   // w.wb..w
    0,     // .bwb..w
    -5,    // bbwb..w
    16,    // wbwb..w
    -17,   // .wwb..w
    17,    // bwwb..w
    16,    // wwwb..w
    14,    // ...w..w
    3,     // b..w..w
    16,    // w..w..w
    -24,   // .b.w..w
    -6,    // bb.w..w
    13,    // wb.w..w
    2,     // .w.w..w
    5,     // bw.w..w
    -6,    // ww.w..w
    0,     // ..bw..w
    9,     // b.bw..w
    -19,   // w.bw..w
    2,     // .bbw..w
    19,    // bbbw..w
    3,     // wbbw..w
    -5,    // .wbw..w
    4,     // bwbw..w
    -10,   // wwbw..w
    5,     // ..ww..w
    7,     // b.ww..w
    -2,    // w.ww..w
    -13,   // .bww..w
    4,     // bbww..w
    0,     // wbww..w
    4,     // .www..w
    -19,   // bwww..w
    -8,    // wwww..w
    -16,   // ....b.w
    -15,   // b...b.w
    13,    // w...b.w
    -1,    // .b..b.w
    10,    // bb..b.w
    1,     // wb..b.w
    17,    // .w..b.w
    -29,   // bw..b.w
    1,     // ww..b.w
    15,    // ..b.b.w
    -10,   // b.b.b.w
    18,    // w.b.b.w
    -15,   // .bb.b.w
    -11,   // bbb.b.w
    -1,    // wbb.b.w
    -5,    // .wb.b.w
    7,     // bwb.b.w
    5,     // wwb.b.w
    10,    // ..w.b.w
    0,     // b.w.b.w
    -4,    // w.w.b.w
    -10,   // .bw.b.w
    8,     // bbw.b.w
    -19,   // wbw.b.w
    -2,    // .ww.b.w
    -10,   // bww.b.w
    -15,   // www.b.w
    -6,    // ...bb.w
    -7,    // b..bb.w
    -6,    // w..bb.w
    9,     // .b.bb.w
    1,     // bb.bb.w
    8,     // wb.bb.w
    -5,    // .w.bb.w
    -4,    // bw.bb.w
    -2,    // ww.bb.w
    -10,   // ..bbb.w
    33,    // b.bbb.w
    10,    // w.bbb.w
    -3,    // .bbbb.w
    16,    // bbbbb.w
    5,     // wbbbb.w
    -4,    // .wbbb.w
    -17,   // bwbbb.w
    -3,    // wwbbb.w
    2,     // ..wbb.w
    -8,    // b.wbb.w
    -4,    // w.wbb.w
    13,    // .bwbb.w
    11,    // bbwbb.w
    5,     // wbwbb.w
    16,    // .wwbb.w
    -7,    // bwwbb.w
    9,     // wwwbb.w
    -8,    // ...wb.w
    -22,   // b..wb.w
    -19,   // w..wb.w
    1,     // .b.wb.w
    4,     // bb.wb.w
    -24,   // wb.wb.w
    4,     // .w.wb.w
    3,     // bw.wb.w
    7,     // ww.wb.w
    -5,    // ..bwb.w
    -29,   // b.bwb.w
    5,     // w.bwb.w
    -7,    // .bbwb.w
    -5,    // bbbwb.w
    6,     // wbbwb.w
    13,    // .wbwb.w
    -7,    // bwbwb.w
    -11,   // wwbwb.w
    12,    // ..wwb.w
    8,     // b.wwb.w
    -27,   // w.wwb.w
    -2,    // .bwwb.w
    2,     // bbwwb.w
    -11,   // wbwwb.w
    -16,   // .wwwb.w
    6,     // bwwwb.w
    6,     // wwwwb.w
    4,     // ....w.w
    19,    // b...w.w
    5,     // w...w.w
    21,    // .b..w.w
    -2,    // bb..w.w
    -15,   // wb..w.w
    3,     // .w..w.w
    4,     // bw..w.w
    14,    // ww..w.w
    -3,    // ..b.w.w
    0,     // b.b.w.w
    -4,    // w.b.w.w
    -14,   // .bb.w.w
    5,     // bbb.w.w
    -13,   // wbb.w.w
    6,     // .wb.w.w
    -3,    // bwb.w.w
    -1,    // wwb.w.w
    34,    // ..w.w.w
    10,    // b.w.w.w
    13,    // w.w.w.w
    29,    // .bw.w.w
    10,    // bbw.w.w
    10,    // wbw.w.w
    -15,   // .ww.w.w
    6,     // bww.w.w
    6,     // www.w.w
    -3,    // ...bw.w
    -9,    // b..bw.w
    -17,   // w..bw.w
    6,     // .b.bw.w
    -5,    // bb.bw.w
    -9,    // wb.bw.w
    -3,    // .w.bw.w
    2,     // bw.bw.w
    -5,    // ww.bw.w
    -5,    // ..bbw.w
    -19,   // b.bbw.w
    -4,    // w.bbw.w
    4,     // .bbbw.w
    2,     // bbbbw.w
    -1,    // wbbbw.w
    -10,   // .wbbw.w
    10,    // bwbbw.w
    -1,    // wwbbw.w
    2,     // ..wbw.w
    29,    // b.wbw.w
    -5,    // w.wbw.w
    -14,   // .bwbw.w
    -1,    // bbwbw.w
    18,    // wbwbw.w
    -5,    // .wwbw.w
    6,     // bwwbw.w
    -4,    // wwwbw.w
    11,    // ...ww.w
    -9,    // b..ww.w
    -2,    // w..ww.w
    0,     // .b.ww.w
    9,     // bb.ww.w
    -11,   // wb.ww.w
    3,     // .w.ww.w
    2,     // bw.ww.w
    -9,    // ww.ww.w
    -22,   // ..bww.w
    19,    // b.bww.w
    -27,   // w.bww.w
    -3,    // .bbww.w
    10,    // bbbww.w
    2,     // wbbww.w
    11,    // .wbww.w
    15,    // bwbww.w
    -5,    // wwbww.w
    -3,    // ..www.w
    -33,   // b.www.w
    10,    // w.www.w
    -7,    // .bwww.w
    -2,    // bbwww.w
    0,     // wbwww.w
    -1,    // .wwww.w
    -2,    // bwwww.w
    -11,   // wwwww.w
    13,    // .....bw
    13,    // b....bw
    -24,   // w....bw
    0,     // .b...bw
    31,    // bb...bw
    -4,    // wb...bw
    -14,   // .w...bw
    0,     // bw...bw
    0,     // ww...bw
    -4,    // ..b..bw
    -4,    // b.b..bw
    1,     // w.b..bw
    9,     // .bb..bw
    0,     // bbb..bw
    -3,    // wbb..bw
    4,     // .wb..bw
    21,    // bwb..bw
    5,     // wwb..bw
    0,     // ..w..bw
    29,    // b.w..bw
    -15,   // w.w..bw
    -12,   // .bw..bw
    1,     // bbw..bw
    5,     // wbw..bw
    7,     // .ww..bw
    -7,    // bww..bw
    -6,    // www..bw
    -4,    // ...b.bw
    -5,    // b..b.bw
    -8,    // w..b.bw
    -3,    // .b.b.bw
    -12,   // bb.b.bw
    11,    // wb.b.bw
    -11,   // .w.b.bw
    -1,    // bw.b.bw
    20,    // ww.b.bw
    0,     // ..bb.bw
    -2,    // b.bb.bw
    8,     // w.bb.bw
    9,     // .bbb.bw
    -8,    // bbbb.bw
    7,     // wbbb.bw
    -4,    // .wbb.bw
    -5,    // bwbb.bw
    -24,   // wwbb.bw
    8,     // ..wb.bw
    -3,    // b.wb.bw
    -9,    // w.wb.bw
    -2,    // .bwb.bw
    10,    // bbwb.bw
    6,     // wbwb.bw
    4,     // .wwb.bw
    -1,    // bwwb.bw
    -8,    // wwwb.bw
    9,     // ...w.bw
    1,     // b..w.bw
    13,    // w..w.bw
    7,     // .b.w.bw
    -1,    // bb.w.bw
    -15,   // wb.w.bw
    23,    // .w.w.bw
    1,     // bw.w.bw
    9,     // ww.w.bw
    2,     // ..bw.bw
    -2,    // b.bw.bw
    -24,   // w.bw.bw
    -13,   // .bbw.bw
    -2,    // bbbw.bw
    17,    // wbbw.bw
    -4,    // .wbw.bw
    -13,   // bwbw.bw
    9,     // wwbw.bw
    5,     // ..ww.bw
    4,     // b.ww.bw
    -11,   // w.ww.bw
    8,     // .bww.bw
    -1,    // bbww.bw
    0,     // wbww.bw
    -17,   // .www.bw
    -16,   // bwww.bw
    -7,    // wwww.bw
    -34,   // ....bbw
    -10,   // b...bbw
    8,     // w...bbw
    15,    // .b..bbw
    2,     // bb..bbw
    -3,    // wb..bbw
    29,    // .w..bbw
    7,     // bw..bbw
    11,    // ww..bbw
    -9,    // ..b.bbw
    -6,    // b.b.bbw
    -1,    // w.b.bbw
    11,    // .bb.bbw
    6,     // bbb.bbw
    -4,    // wbb.bbw
    4,     // .wb.bbw
    -12,   // bwb.bbw
    3,     // wwb.bbw
    5,     // ..w.bbw
    10,    // b.w.bbw
    -13,   // w.w.bbw
    -17,   // .bw.bbw
    5,     // bbw.bbw
    8,     // wbw.bbw
    5,     // .ww.bbw
    0,     // bww.bbw
    8,     // www.bbw
    -27,   // ...bbbw
    19,    // b..bbbw
    8,     // w..bbbw
    18,    // .b.bbbw
    0,     // bb.bbbw
    7,     // wb.bbbw
    7,     // .w.bbbw
    16,    // bw.bbbw
    10,    // ww.bbbw
    5,     // ..bbbbw
    2,     // b.bbbbw
    5,     // w.bbbbw
    15,    // .bbbbbw
    14,    // bbbbbbw
    -6,    // wbbbbbw
    -4,    // .wbbbbw
    4,     // bwbbbbw
    8,     // wwbbbbw
    -9,    // ..wbbbw
    -6,    // b.wbbbw
    -1,    // w.wbbbw
    2,     // .bwbbbw
    -21,   // bbwbbbw
    -19,   // wbwbbbw
    -11,   // .wwbbbw
    16,    // bwwbbbw
    13,    // wwwbbbw
    3,     // ...wbbw
    -17,   // b..wbbw
    3,     // w..wbbw
    -21,   // .b.wbbw
    -3,    // bb.wbbw
    17,    // wb.wbbw
    -11,   // .w.wbbw
    1,     // bw.wbbw
    -1,    // ww.wbbw
    2,     // ..bwbbw
    -6,    // b.bwbbw
    6,     // w.bwbbw
    4,     // .bbwbbw
    -4,    // bbbwbbw
    -8,    // wbbwbbw
    4,     // .wbwbbw
    6,     // bwbwbbw
    25,    // wwbwbbw
    -9,    // ..wwbbw
    7,     // b.wwbbw
    2,     // w.wwbbw
    -15,   // .bwwbbw
    3,     // bbwwbbw
    -2,    // wbwwbbw
    0,     // .wwwbbw
    -16,   // bwwwbbw
    -5,    // wwwwbbw
    10,    // ....wbw
    -16,   // b...wbw
    17,    // w...wbw
    -30,   // .b..wbw
    1,     // bb..wbw
    5,     // wb..wbw
    -9,    // .w..wbw
    -21,   // bw..wbw
    2,     // ww..wbw
    -4,    // ..b.wbw
    3,     // b.b.wbw
    -19,   // w.b.wbw
    -12,   // .bb.wbw
    -10,   // bbb.wbw
    8,     // wbb.wbw
    -13,   // .wb.wbw
    0,     // bwb.wbw
    0,     // wwb.wbw
    5,     // ..w.wbw
    -7,    // b.w.wbw
    10,    // w.w.wbw
    3,     // .bw.wbw
    -13,   // bbw.wbw
    11,    // wbw.wbw
    -23,   // .ww.wbw
    12,    // bww.wbw
    3,     // www.wbw
    -14,   // ...bwbw
    -4,    // b..bwbw
    16,    // w..bwbw
    -9,    // .b.bwbw
    -7,    // bb.bwbw
    6,     // wb.bwbw
    9,     // .w.bwbw
    13,    // bw.bwbw
    -1,    // ww.bwbw
    -24,   // ..bbwbw
    -15,   // b.bbwbw
    5,     // w.bbwbw
    1,     // .bbbwbw
    -13,   // bbbbwbw
    -19,   // wbbbwbw
    -6,    // .wbbwbw
    17,    // bwbbwbw
    8,     // wwbbwbw
    -8,    // ..wbwbw
    7,     // b.wbwbw
    18,    // w.wbwbw
    14,    // .bwbwbw
    0,     // bbwbwbw
    13,    // wbwbwbw
    -1,    // .wwbwbw
    -6,    // bwwbwbw
    2,     // wwwbwbw
    6,     // ...wwbw
    10,    // b..wwbw
    0,     // w..wwbw
    19,    // .b.wwbw
    12,    // bb.wwbw
    0,     // wb.wwbw
    0,     // .w.wwbw
    5,     // bw.wwbw
    0,     // ww.wwbw
    9,     // ..bwwbw
    -10,   // b.bwwbw
    -11,   // w.bwwbw
    5,     // .bbwwbw
    2,     // bbbwwbw
    -2,    // wbbwwbw
    12,    // .wbwwbw
    -17,   // bwbwwbw
    -9,    // wwbwwbw
    4,     // ..wwwbw
    17,    // b.wwwbw
    0,     // w.wwwbw
    -3,    // .bwwwbw
    -3,    // bbwwwbw
    16,    // wbwwwbw
    -8,    // .wwwwbw
    -4,    // bwwwwbw
    6,     // wwwwwbw
    -23,   // .....ww
    -8,    // b....ww
    -9,    // w....ww
    7,     // .b...ww
    0,     // bb...ww
    0,     // wb...ww
    -15,   // .w...ww
    -31,   // bw...ww
    18,    // ww...ww
    -9,    // ..b..ww
    2,     // b.b..ww
    1,     // w.b..ww
    20,    // .bb..ww
    -17,   // bbb..ww
    11,    // wbb..ww
    5,     // .wb..ww
    -1,    // bwb..ww
    13,    // wwb..ww
    6,     // ..w..ww
    -10,   // b.w..ww
    14,    // w.w..ww
    0,     // .bw..ww
    3,     // bbw..ww
    2,     // wbw..ww
    -6,    // .ww..ww
    -2,    // bww..ww
    -21,   // www..ww
    0,     // ...b.ww
    6,     // b..b.ww
    0,     // w..b.ww
    3,     // .b.b.ww
    -11,   // bb.b.ww
    20,    // wb.b.ww
    -5,    // .w.b.ww
    1,     // bw.b.ww
    -4,    // ww.b.ww
    -5,    // ..bb.ww
    -9,    // b.bb.ww
    -2,    // w.bb.ww
    -10,   // .bbb.ww
    -4,    // bbbb.ww
    10,    // wbbb.ww
    0,     // .wbb.ww
    -12,   // bwbb.ww
    -2,    // wwbb.ww
    -3,    // ..wb.ww
    -4,    // b.wb.ww
    -5,    // w.wb.ww
    9,     // .bwb.ww
    6,     // bbwb.ww
    -1,    // wbwb.ww
    -22,   // .wwb.ww
    3,     // bwwb.ww
    -5,    // wwwb.ww
    -4,    // ...w.ww
    -7,    // b..w.ww
    -6,    // w..w.ww
    6,     // .b.w.ww
    11,    // bb.w.ww
    9,     // wb.w.ww
    -7,    // .w.w.ww
    12,    // bw.w.ww
    2,     // ww.w.ww
    -9,    // ..bw.ww
    5,     // b.bw.ww
    7,     // w.bw.ww
    -6,    // .bbw.ww
    -3,    // bbbw.ww
    -1,    // wbbw.ww
    5,     // .wbw.ww
    7,     // bwbw.ww
    -3,    // wwbw.ww
    19,    // ..ww.ww
    -1,    // b.ww.ww
    -9,    // w.ww.ww
    1,     // .bww.ww
    27,    // bbww.ww
    0,     // wbww.ww
    -9,    // .www.ww
    0,     // bwww.ww
    0,     // wwww.ww
    8,     // ....bww
    -19,   // b...bww
    2,     // w...bww
    6,     // .b..bww
    -3,    // bb..bww
    5,     // wb..bww
    23,    // .w..bww
    -1,    // bw..bww
    13,    // ww..bww
    2,     // ..b.bww
    -10,   // b.b.bww
    5,     // w.b.bww
    0,     // .bb.bww
    -16,   // bbb.bww
    3,     // wbb.bww
    -7,    // .wb.bww
    13,    // bwb.bww
    -15,   // wwb.bww
    6,     // ..w.bww
    -8,    // b.w.bww
    -1,    // w.w.bww
    9,     // .bw.bww
    0,     // bbw.bww
    0,     // wbw.bww
    10,    // .ww.bww
    -5,    // bww.bww
    -6,    // www.bww
    -26,   // ...bbww
    -4,    // b..bbww
    1,     // w..bbww
    -30,   // .b.bbww
    -27,   // bb.bbww
    -24,   // wb.bbww
    30,    // .w.bbww
    1,     // bw.bbww
    -2,    // ww.bbww
    -6,    // ..bbbww
    2,     // b.bbbww
    -3,    // w.bbbww
    21,    // .bbbbww
    19,    // bbbbbww
    8,     // wbbbbww
    12,    // .wbbbww
    3,     // bwbbbww
    8,     // wwbbbww
    -5,    // ..wbbww
    -2,    // b.wbbww
    -1,    // w.wbbww
    12,    // .bwbbww
    0,     // bbwbbww
    8,     // wbwbbww
    12,    // .wwbbww
    -3,    // bwwbbww
    12,    // wwwbbww
    1,     // ...wbww
    5,     // b..wbww
    -10,   // w..wbww
    28,    // .b.wbww
    -6,    // bb.wbww
    9,     // wb.wbww
    -1,    // .w.wbww
    -10,   // bw.wbww
    -3,    // ww.wbww
    4,     // ..bwbww
    1,     // b.bwbww
    -11,   // w.bwbww
    0,     // .bbwbww
    14,    // bbbwbww
    25,    // wbbwbww
    -23,   // .wbwbww
    0,     // bwbwbww
    0,     // wwbwbww
    15,    // ..wwbww
    -11,   // b.wwbww
    -5,    // w.wwbww
    0,     // .bwwbww
    0,     // bbwwbww
    -9,    // wbwwbww
    6,     // .wwwbww
    21,    // bwwwbww
    -18,   // wwwwbww
    -29,   // ....www
    -1,    // b...www
    21,    // w...www
    -26,   // .b..www
    17,    // bb..www
    -6,    // wb..www
    -6,    // .w..www
    0,     // bw..www
    -21,   // ww..www
    11,    // ..b.www
    -5,    // b.b.www
    -15,   // w.b.www
    -11,   // .bb.www
    0,     // bbb.www
    8,     // wbb.www
    0,     // .wb.www
    10,    // bwb.www
    -6,    // wwb.www
    1,     // ..w.www
    11,    // b.w.www
    6,     // w.w.www
    8,     // .bw.www
    16,    // bbw.www
    3,     // wbw.www
    7,     // .ww.www
    -6,    // bww.www
    -17,   // www.www
    20,    // ...bwww
    -19,   // b..bwww
    16,    // w..bwww
    -4,    // .b.bwww
    3,     // bb.bwww
    -8,    // wb.bwww
    -4,    // .w.bwww
    2,     // bw.bwww
    -5,    // ww.bwww
    4,     // ..bbwww
    -10,   // b.bbwww
    9,     // w.bbwww
    1,     // .bbbwww
    -7,    // bbbbwww
    13,    // wbbbwww
    23,    // .wbbwww
    -2,    // bwbbwww
    12,    // wwbbwww
    -3,    // ..wbwww
    5,     // b.wbwww
    -4,    // w.wbwww
    -8,    // .bwbwww
    -14,   // bbwbwww
    2,     // wbwbwww
    4,     // .wwbwww
    4,     // bwwbwww
    7,     // wwwbwww
    -39,   // ...wwww
    7,     // b..wwww
    -8,    // w..wwww
    3,     // .b.wwww
    4,     // bb.wwww
    -7,    // wb.wwww
    -8,    // .w.wwww
    8,     // bw.wwww
    0,     // ww.wwww
    -13,   // ..bwwww
    -2,    // b.bwwww
    6,     // w.bwwww
    14,    // .bbwwww
    7,     // bbbwwww
    -5,    // wbbwwww
    -3,    // .wbwwww
    13,    // bwbwwww
    -18,   // wwbwwww
    -19,   // ..wwwww
    -16,   // b.wwwww
    -11,   // w.wwwww
    10,    // .bwwwww
    -19,   // bbwwwww
    6,     // wbwwwww
    -6,    // .wwwwww
    -14,   // bwwwwww
    -12,   // wwwwwww
    0,     // captures=0 threats=0
    8,     // captures=0 threats=1
    28,    // captures=0 threats=2
    28,    // captures=0 threats=3
    32,    // captures=0 threats=4
    6,     // captures=0 additional threats
    1,     // captures=1 threats=0
    25,    // captures=1 threats=1
    31,    // captures=1 threats=2
    37,    // captures=1 threats=3
    37,    // captures=1 threats=4
    10,    // captures=1 additional threats
    18,    // captures=2 threats=0
    25,    // captures=2 threats=1
    32,    // captures=2 threats=2
    37,    // captures=2 threats=3
    38,    // captures=2 threats=4
    14,    // captures=2 additional threats
    18,    // captures=3 threats=0
    28,    // captures=3 threats=1
    34,    // captures=3 threats=2
    44,    // captures=3 threats=3
    48,    // captures=3 threats=4
    21,    // captures=3 additional threats
    34,    // captures=4 threats=0
    34,    // captures=4 threats=1
    39,    // captures=4 threats=2
    51,    // captures=4 threats=3
    58,    // captures=4 threats=4
    14,    // captures=4 additional threats
].into_boxed_slice()
