vec![
    0,     // .......
    0,     // b......
    0,     // w......
    13,    // .b.....
    35,    // bb.....
    7,     // wb.....
    -13,   // .w.....
    -7,    // bw.....
    -35,   // ww.....
    3,     // ..b....
    24,    // b.b....
    -16,   // w.b....
    0,     // .bb....
    82,    // bbb....
    -22,   // wbb....
    -18,   // .wb....
    -14,   // bwb....
    -9,    // wwb....
    -3,    // ..w....
    16,    // b.w....
    -24,   // w.w....
    18,    // .bw....
    9,     // bbw....
    14,    // wbw....
    0,     // .ww....
    22,    // bww....
    -82,   // www....
    -13,   // ...b...
    9,     // b..b...
    17,    // w..b...
    -2,    // .b.b...
    7,     // bb.b...
    -31,   // wb.b...
    -5,    // .w.b...
    -6,    // bw.b...
    -45,   // ww.b...
    -8,    // ..bb...
    5,     // b.bb...
    -30,   // w.bb...
    28,    // .bbb...
    144,   // bbbb...
    -38,   // wbbb...
    -27,   // .wbb...
    3,     // bwbb...
    32,    // wwbb...
    -3,    // ..wb...
    24,    // b.wb...
    2,     // w.wb...
    25,    // .bwb...
    -34,   // bbwb...
    -4,    // wbwb...
    24,    // .wwb...
    -3,    // bwwb...
    0,     // wwwb...
    13,    // ...w...
    -17,   // b..w...
    -9,    // w..w...
    5,     // .b.w...
    45,    // bb.w...
    6,     // wb.w...
    2,     // .w.w...
    31,    // bw.w...
    -7,    // ww.w...
    3,     // ..bw...
    -2,    // b.bw...
    -24,   // w.bw...
    -24,   // .bbw...
    0,     // bbbw...
    3,     // wbbw...
    -25,   // .wbw...
    4,     // bwbw...
    34,    // wwbw...
    8,     // ..ww...
    30,    // b.ww...
    -5,    // w.ww...
    27,    // .bww...
    -32,   // bbww...
    -3,    // wbww...
    -28,   // .www...
    38,    // bwww...
    -144,  // wwww...
    3,     // ....b..
    0,     // b...b..
    15,    // w...b..
    -7,    // .b..b..
    -33,   // bb..b..
    -9,    // wb..b..
    -11,   // .w..b..
    -22,   // bw..b..
    -36,   // ww..b..
    0,     // ..b.b..
    -28,   // b.b.b..
    -2,    // w.b.b..
    0,     // .bb.b..
    32,    // bbb.b..
    0,     // wbb.b..
    20,    // .wb.b..
    -20,   // bwb.b..
    15,    // wwb.b..
    0,     // ..w.b..
    -2,    // b.w.b..
    -2,    // w.w.b..
    7,     // .bw.b..
    2,     // bbw.b..
    7,     // wbw.b..
    20,    // .ww.b..
    -7,    // bww.b..
    -26,   // www.b..
    -8,    // ...bb..
    -5,    // b..bb..
    0,     // w..bb..
    64,    // .b.bb..
    11,    // bb.bb..
    -28,   // wb.bb..
    -1,    // .w.bb..
    -6,    // bw.bb..
    26,    // ww.bb..
    -12,   // ..bbb..
    33,    // b.bbb..
    -40,   // w.bbb..
    119,   // .bbbb..
    28,    // bbbbb..
    42,    // wbbbb..
    -54,   // .wbbb..
    -13,   // bwbbb..
    -4,    // wwbbb..
    -14,   // ..wbb..
    -9,    // b.wbb..
    4,     // w.wbb..
    0,     // .bwbb..
    -19,   // bbwbb..
    -26,   // wbwbb..
    -30,   // .wwbb..
    -8,    // bwwbb..
    -26,   // wwwbb..
    3,     // ...wb..
    -16,   // b..wb..
    -5,    // w..wb..
    -12,   // .b.wb..
    -3,    // bb.wb..
    16,    // wb.wb..
    -4,    // .w.wb..
    -3,    // bw.wb..
    2,     // ww.wb..
    9,     // ..bwb..
    -7,    // b.bwb..
    -15,   // w.bwb..
    -8,    // .bbwb..
    -22,   // bbbwb..
    39,    // wbbwb..
    -26,   // .wbwb..
    14,    // bwbwb..
    -18,   // wwbwb..
    14,    // ..wwb..
    -8,    // b.wwb..
    2,     // w.wwb..
    6,     // .bwwb..
    15,    // bbwwb..
    46,    // wbwwb..
    15,    // .wwwb..
    10,    // bwwwb..
    -41,   // wwwwb..
    -3,    // ....w..
    -15,   // b...w..
    0,     // w...w..
    11,    // .b..w..
    36,    // bb..w..
    22,    // wb..w..
    7,     // .w..w..
    9,     // bw..w..
    33,    // ww..w..
    0,     // ..b.w..
    2,     // b.b.w..
    2,     // w.b.w..
    -20,   // .bb.w..
    26,    // bbb.w..
    7,     // wbb.w..
    -7,    // .wb.w..
    -7,    // bwb.w..
    -2,    // wwb.w..
    0,     // ..w.w..
    2,     // b.w.w..
    28,    // w.w.w..
    -20,   // .bw.w..
    -15,   // bbw.w..
    20,    // wbw.w..
    0,     // .ww.w..
    0,     // bww.w..
    -32,   // www.w..
    -3,    // ...bw..
    5,     // b..bw..
    16,    // w..bw..
    4,     // .b.bw..
    -2,    // bb.bw..
    3,     // wb.bw..
    12,    // .w.bw..
    -16,   // bw.bw..
    3,     // ww.bw..
    -14,   // ..bbw..
    -2,    // b.bbw..
    8,     // w.bbw..
    -15,   // .bbbw..
    41,    // bbbbw..
    -10,   // wbbbw..
    -6,    // .wbbw..
    -46,   // bwbbw..
    -15,   // wwbbw..
    -9,    // ..wbw..
    15,    // b.wbw..
    7,     // w.wbw..
    26,    // .bwbw..
    18,    // bbwbw..
    -14,   // wbwbw..
    8,     // .wwbw..
    -39,   // bwwbw..
    22,    // wwwbw..
    8,     // ...ww..
    0,     // b..ww..
    5,     // w..ww..
    1,     // .b.ww..
    -26,   // bb.ww..
    6,     // wb.ww..
    -64,   // .w.ww..
    28,    // bw.ww..
    -11,   // ww.ww..
    14,    // ..bww..
    -4,    // b.bww..
    9,     // w.bww..
    30,    // .bbww..
    26,    // bbbww..
    8,     // wbbww..
    0,     // .wbww..
    26,    // bwbww..
    19,    // wwbww..
    12,    // ..www..
    40,    // b.www..
    -33,   // w.www..
    54,    // .bwww..
    4,     // bbwww..
    13,    // wbwww..
    -119,  // .wwww..
    -42,   // bwwww..
    -28,   // wwwww..
    13,    // .....b.
    -6,    // b....b.
    -41,   // w....b.
    21,    // .b...b.
    40,    // bb...b.
    17,    // wb...b.
    0,     // .w...b.
    22,    // bw...b.
    15,    // ww...b.
    -7,    // ..b..b.
    17,    // b.b..b.
    7,     // w.b..b.
    15,    // .bb..b.
    -7,    // bbb..b.
    51,    // wbb..b.
    -13,   // .wb..b.
    8,     // bwb..b.
    33,    // wwb..b.
    11,    // ..w..b.
    -41,   // b.w..b.
    9,     // w.w..b.
    11,    // .bw..b.
    -16,   // bbw..b.
    -41,   // wbw..b.
    41,    // .ww..b.
    -47,   // bww..b.
    -44,   // www..b.
    -2,    // ...b.b.
    -9,    // b..b.b.
    51,    // w..b.b.
    22,    // .b.b.b.
    17,    // bb.b.b.
    -4,    // wb.b.b.
    -5,    // .w.b.b.
    -69,   // bw.b.b.
    -26,   // ww.b.b.
    64,    // ..bb.b.
    -38,   // b.bb.b.
    9,     // w.bb.b.
    8,     // .bbb.b.
    10,    // bbbb.b.
    55,    // wbbb.b.
    -1,    // .wbb.b.
    18,    // bwbb.b.
    -48,   // wwbb.b.
    4,     // ..wb.b.
    -4,    // b.wb.b.
    0,     // w.wb.b.
    5,     // .bwb.b.
    3,     // bbwb.b.
    -2,    // wbwb.b.
    26,    // .wwb.b.
    -13,   // bwwb.b.
    -28,   // wwwb.b.
    5,     // ...w.b.
    23,    // b..w.b.
    -1,    // w..w.b.
    -36,   // .b.w.b.
    28,    // bb.w.b.
    2,     // wb.w.b.
    5,     // .w.w.b.
    -2,    // bw.w.b.
    -10,   // ww.w.b.
    -12,   // ..bw.b.
    -2,    // b.bw.b.
    1,     // w.bw.b.
    -15,   // .bbw.b.
    -3,    // bbbw.b.
    -2,    // wbbw.b.
    -10,   // .wbw.b.
    -10,   // bwbw.b.
    19,    // wwbw.b.
    1,     // ..ww.b.
    4,     // b.ww.b.
    -2,    // w.ww.b.
    -4,    // .bww.b.
    -31,   // bbww.b.
    37,    // wbww.b.
    -30,   // .www.b.
    2,     // bwww.b.
    -18,   // wwww.b.
    0,     // ....bb.
    -14,   // b...bb.
    -2,    // w...bb.
    15,    // .b..bb.
    9,     // bb..bb.
    30,    // wb..bb.
    -41,   // .w..bb.
    18,    // bw..bb.
    -10,   // ww..bb.
    0,     // ..b.bb.
    2,     // b.b.bb.
    6,     // w.b.bb.
    21,    // .bb.bb.
    -20,   // bbb.bb.
    35,    // wbb.bb.
    30,    // .wb.bb.
    9,     // bwb.bb.
    17,    // wwb.bb.
    -20,   // ..w.bb.
    5,     // b.w.bb.
    -41,   // w.w.bb.
    5,     // .bw.bb.
    4,     // bbw.bb.
    -5,    // wbw.bb.
    0,     // .ww.bb.
    -1,    // bww.bb.
    -44,   // www.bb.
    28,    // ...bbb.
    -11,   // b..bbb.
    8,     // w..bbb.
    8,     // .b.bbb.
    9,     // bb.bbb.
    35,    // wb.bbb.
    30,    // .w.bbb.
    33,    // bw.bbb.
    -12,   // ww.bbb.
    119,   // ..bbbb.
    19,    // b.bbbb.
    6,     // w.bbbb.
    14,    // .bbbbb.
    7,     // bbbbbb.
    18,    // wbbbbb.
    60,    // .wbbbb.
    25,    // bwbbbb.
    27,    // wwbbbb.
    -15,   // ..wbbb.
    1,     // b.wbbb.
    -9,    // w.wbbb.
    -10,   // .bwbbb.
    -27,   // bbwbbb.
    -45,   // wbwbbb.
    -3,    // .wwbbb.
    -24,   // bwwbbb.
    10,    // wwwbbb.
    -24,   // ...wbb.
    14,    // b..wbb.
    17,    // w..wbb.
    -15,   // .b.wbb.
    22,    // bb.wbb.
    3,     // wb.wbb.
    -26,   // .w.wbb.
    -23,   // bw.wbb.
    -9,    // ww.wbb.
    -8,    // ..bwbb.
    -2,    // b.bwbb.
    -33,   // w.bwbb.
    12,    // .bbwbb.
    -24,   // bbbwbb.
    -22,   // wbbwbb.
    -3,    // .wbwbb.
    8,     // bwbwbb.
    35,    // wwbwbb.
    30,    // ..wwbb.
    -17,   // b.wwbb.
    -4,    // w.wwbb.
    -21,   // .bwwbb.
    -33,   // bbwwbb.
    27,    // wbwwbb.
    3,     // .wwwbb.
    -13,   // bwwwbb.
    9,     // wwwwbb.
    18,    // ....wb.
    25,    // b...wb.
    -9,    // w...wb.
    11,    // .b..wb.
    -17,   // bb..wb.
    -39,   // wb..wb.
    13,    // .w..wb.
    -32,   // bw..wb.
    3,     // ww..wb.
    7,     // ..b.wb.
    -38,   // b.b.wb.
    -6,    // w.b.wb.
    5,     // .bb.wb.
    0,     // bbb.wb.
    -25,   // wbb.wb.
    0,     // .wb.wb.
    -23,   // bwb.wb.
    12,    // wwb.wb.
    -20,   // ..w.wb.
    54,    // b.w.wb.
    40,    // w.w.wb.
    2,     // .bw.wb.
    15,    // bbw.wb.
    -21,   // wbw.wb.
    -30,   // .ww.wb.
    15,    // bww.wb.
    -40,   // www.wb.
    25,    // ...bwb.
    4,     // b..bwb.
    -18,   // w..bwb.
    5,     // .b.bwb.
    -6,    // bb.bwb.
    29,    // wb.bwb.
    10,    // .w.bwb.
    21,    // bw.bwb.
    -18,   // ww.bwb.
    0,     // ..bbwb.
    -32,   // b.bbwb.
    12,    // w.bbwb.
    -10,   // .bbbwb.
    -8,    // bbbbwb.
    13,    // wbbbwb.
    -20,   // .wbbwb.
    -9,    // bwbbwb.
    39,    // wwbbwb.
    26,    // ..wbwb.
    9,     // b.wbwb.
    -7,    // w.wbwb.
    -31,   // .bwbwb.
    37,    // bbwbwb.
    13,    // wbwbwb.
    3,     // .wwbwb.
    38,    // bwwbwb.
    -49,   // wwwbwb.
    27,    // ...wwb.
    -24,   // b..wwb.
    19,    // w..wwb.
    -4,    // .b.wwb.
    -19,   // bb.wwb.
    -20,   // wb.wwb.
    1,     // .w.wwb.
    -14,   // bw.wwb.
    1,     // ww.wwb.
    6,     // ..bwwb.
    11,    // b.bwwb.
    -22,   // w.bwwb.
    -21,   // .bbwwb.
    -10,   // bbbwwb.
    -30,   // wbbwwb.
    20,    // .wbwwb.
    -3,    // bwbwwb.
    29,    // wwbwwb.
    54,    // ..wwwb.
    44,    // b.wwwb.
    -24,   // w.wwwb.
    -23,   // .bwwwb.
    2,     // bbwwwb.
    15,    // wbwwwb.
    -60,   // .wwwwb.
    74,    // bwwwwb.
    -6,    // wwwwwb.
    -13,   // .....w.
    41,    // b....w.
    6,     // w....w.
    0,     // .b...w.
    -15,   // bb...w.
    -22,   // wb...w.
    -21,   // .w...w.
    -17,   // bw...w.
    -40,   // ww...w.
    -11,   // ..b..w.
    -9,    // b.b..w.
    41,    // w.b..w.
    -41,   // .bb..w.
    44,    // bbb..w.
    47,    // wbb..w.
    -11,   // .wb..w.
    41,    // bwb..w.
    16,    // wwb..w.
    7,     // ..w..w.
    -7,    // b.w..w.
    -17,   // w.w..w.
    13,    // .bw..w.
    -33,   // bbw..w.
    -8,    // wbw..w.
    -15,   // .ww..w.
    -51,   // bww..w.
    7,     // www..w.
    -5,    // ...b.w.
    1,     // b..b.w.
    -23,   // w..b.w.
    -5,    // .b.b.w.
    10,    // bb.b.w.
    2,     // wb.b.w.
    36,    // .w.b.w.
    -2,    // bw.b.w.
    -28,   // ww.b.w.
    -1,    // ..bb.w.
    2,     // b.bb.w.
    -4,    // w.bb.w.
    30,    // .bbb.w.
    18,    // bbbb.w.
    -2,    // wbbb.w.
    4,     // .wbb.w.
    -37,   // bwbb.w.
    31,    // wwbb.w.
    12,    // ..wb.w.
    -1,    // b.wb.w.
    2,     // w.wb.w.
    10,    // .bwb.w.
    -19,   // bbwb.w.
    10,    // wbwb.w.
    15,    // .wwb.w.
    2,     // bwwb.w.
    3,     // wwwb.w.
    2,     // ...w.w.
    -51,   // b..w.w.
    9,     // w..w.w.
    5,     // .b.w.w.
    26,    // bb.w.w.
    69,    // wb.w.w.
    -22,   // .w.w.w.
    4,     // bw.w.w.
    -17,   // ww.w.w.
    -4,    // ..bw.w.
    0,     // b.bw.w.
    4,     // w.bw.w.
    -26,   // .bbw.w.
    28,    // bbbw.w.
    13,    // wbbw.w.
    -5,    // .wbw.w.
    2,     // bwbw.w.
    -3,    // wwbw.w.
    -64,   // ..ww.w.
    -9,    // b.ww.w.
    38,    // w.ww.w.
    1,     // .bww.w.
    48,    // bbww.w.
    -18,   // wbww.w.
    -8,    // .www.w.
    -55,   // bwww.w.
    -10,   // wwww.w.
    -18,   // ....bw.
    9,     // b...bw.
    -25,   // w...bw.
    -13,   // .b..bw.
    -3,    // bb..bw.
    32,    // wb..bw.
    -11,   // .w..bw.
    39,    // bw..bw.
    17,    // ww..bw.
    20,    // ..b.bw.
    -40,   // b.b.bw.
    -54,   // w.b.bw.
    30,    // .bb.bw.
    40,    // bbb.bw.
    -15,   // wbb.bw.
    -2,    // .wb.bw.
    21,    // bwb.bw.
    -15,   // wwb.bw.
    -7,    // ..w.bw.
    6,     // b.w.bw.
    38,    // w.w.bw.
    0,     // .bw.bw.
    -12,   // bbw.bw.
    23,    // wbw.bw.
    -5,    // .ww.bw.
    25,    // bww.bw.
    0,     // www.bw.
    -27,   // ...bbw.
    -19,   // b..bbw.
    24,    // w..bbw.
    -1,    // .b.bbw.
    -1,    // bb.bbw.
    14,    // wb.bbw.
    4,     // .w.bbw.
    20,    // bw.bbw.
    19,    // ww.bbw.
    -54,   // ..bbbw.
    24,    // b.bbbw.
    -44,   // w.bbbw.
    60,    // .bbbbw.
    6,     // bbbbbw.
    -74,   // wbbbbw.
    23,    // .wbbbw.
    -15,   // bwbbbw.
    -2,    // wwbbbw.
    -6,    // ..wbbw.
    22,    // b.wbbw.
    -11,   // w.wbbw.
    -20,   // .bwbbw.
    -29,   // bbwbbw.
    3,     // wbwbbw.
    21,    // .wwbbw.
    30,    // bwwbbw.
    10,    // wwwbbw.
    -25,   // ...wbw.
    18,    // b..wbw.
    -4,    // w..wbw.
    -10,   // .b.wbw.
    18,    // bb.wbw.
    -21,   // wb.wbw.
    -5,    // .w.wbw.
    -29,   // bw.wbw.
    6,     // ww.wbw.
    -26,   // ..bwbw.
    7,     // b.bwbw.
    -9,    // w.bwbw.
    -3,    // .bbwbw.
    49,    // bbbwbw.
    -38,   // wbbwbw.
    31,    // .wbwbw.
    -13,   // bwbwbw.
    -37,   // wwbwbw.
    0,     // ..wwbw.
    -12,   // b.wwbw.
    32,    // w.wwbw.
    20,    // .bwwbw.
    -39,   // bbwwbw.
    9,     // wbwwbw.
    10,    // .wwwbw.
    -13,   // bwwwbw.
    8,     // wwwwbw.
    0,     // ....ww.
    2,     // b...ww.
    14,    // w...ww.
    41,    // .b..ww.
    10,    // bb..ww.
    -18,   // wb..ww.
    -15,   // .w..ww.
    -30,   // bw..ww.
    -9,    // ww..ww.
    20,    // ..b.ww.
    41,    // b.b.ww.
    -5,    // w.b.ww.
    0,     // .bb.ww.
    44,    // bbb.ww.
    1,     // wbb.ww.
    -5,    // .wb.ww.
    5,     // bwb.ww.
    -4,    // wwb.ww.
    0,     // ..w.ww.
    -6,    // b.w.ww.
    -2,    // w.w.ww.
    -30,   // .bw.ww.
    -17,   // bbw.ww.
    -9,    // wbw.ww.
    -21,   // .ww.ww.
    -35,   // bww.ww.
    20,    // www.ww.
    24,    // ...bww.
    -17,   // b..bww.
    -14,   // w..bww.
    26,    // .b.bww.
    9,     // bb.bww.
    23,    // wb.bww.
    15,    // .w.bww.
    -3,    // bw.bww.
    -22,   // ww.bww.
    -30,   // ..bbww.
    4,     // b.bbww.
    17,    // w.bbww.
    -3,    // .bbbww.
    -9,    // bbbbww.
    13,    // wbbbww.
    21,    // .wbbww.
    -27,   // bwbbww.
    33,    // wwbbww.
    8,     // ..wbww.
    33,    // b.wbww.
    2,     // w.wbww.
    3,     // .bwbww.
    -35,   // bbwbww.
    -8,    // wbwbww.
    -12,   // .wwbww.
    22,    // bwwbww.
    24,    // wwwbww.
    -28,   // ...www.
    -8,    // b..www.
    11,    // w..www.
    -30,   // .b.www.
    12,    // bb.www.
    -33,   // wb.www.
    -8,    // .w.www.
    -35,   // bw.www.
    -9,    // ww.www.
    15,    // ..bwww.
    9,     // b.bwww.
    -1,    // w.bwww.
    3,     // .bbwww.
    -10,   // bbbwww.
    24,    // wbbwww.
    10,    // .wbwww.
    45,    // bwbwww.
    27,    // wwbwww.
    -119,  // ..wwww.
    -6,    // b.wwww.
    -19,   // w.wwww.
    -60,   // .bwwww.
    -27,   // bbwwww.
    -25,   // wbwwww.
    -14,   // .wwwww.
    -18,   // bwwwww.
    -7,    // wwwwww.
    0,     // ......b
    10,    // b.....b
    0,     // w.....b
    -6,    // .b....b
    16,    // bb....b
    10,    // wb....b
    41,    // .w....b
    -7,    // bw....b
    7,     // ww....b
    0,     // ..b...b
    -6,    // b.b...b
    -7,    // w.b...b
    -14,   // .bb...b
    -44,   // bbb...b
    -30,   // wbb...b
    9,     // .wb...b
    -47,   // bwb...b
    -16,   // wwb...b
    -15,   // ..w...b
    -27,   // b.w...b
    -4,    // w.w...b
    25,    // .bw...b
    -11,   // bbw...b
    -14,   // wbw...b
    2,     // .ww...b
    -6,    // bww...b
    20,    // www...b
    9,     // ...b..b
    -1,    // b..b..b
    7,     // w..b..b
    -9,    // .b.b..b
    17,    // bb.b..b
    14,    // wb.b..b
    1,     // .w.b..b
    -26,   // bw.b..b
    -13,   // ww.b..b
    -5,    // ..bb..b
    -5,    // b.bb..b
    -32,   // w.bb..b
    -11,   // .bbb..b
    15,    // bbbb..b
    9,     // wbbb..b
    -19,   // .wbb..b
    -20,   // bwbb..b
    0,     // wwbb..b
    5,     // ..wb..b
    34,    // b.wb..b
    -15,   // w.wb..b
    4,     // .bwb..b
    25,    // bbwb..b
    -14,   // wbwb..b
    -17,   // .wwb..b
    13,    // bwwb..b
    -10,   // wwwb..b
    -17,   // ...w..b
    -17,   // b..w..b
    -7,    // w..w..b
    23,    // .b.w..b
    11,    // bb.w..b
    -18,   // wb.w..b
    -51,   // .w.w..b
    -12,   // bw.w..b
    -30,   // ww.w..b
    -16,   // ..bw..b
    10,    // b.bw..b
    -22,   // w.bw..b
    14,    // .bbw..b
    3,     // bbbw..b
    -29,   // wbbw..b
    18,    // .wbw..b
    -50,   // bwbw..b
    6,     // wwbw..b
    0,     // ..ww..b
    33,    // b.ww..b
    -33,   // w.ww..b
    -24,   // .bww..b
    5,     // bbww..b
    31,    // wbww..b
    -8,    // .www..b
    -10,   // bwww..b
    -9,    // wwww..b
    24,    // ....b.b
    -6,    // b...b.b
    4,     // w...b.b
    17,    // .b..b.b
    -16,   // bb..b.b
    -5,    // wb..b.b
    -9,    // .w..b.b
    57,    // bw..b.b
    -38,   // ww..b.b
    -28,   // ..b.b.b
    -17,   // b.b.b.b
    19,    // w.b.b.b
    2,     // .bb.b.b
    -20,   // bbb.b.b
    -17,   // wbb.b.b
    -40,   // .wb.b.b
    11,    // bwb.b.b
    35,    // wwb.b.b
    2,     // ..w.b.b
    -10,   // b.w.b.b
    0,     // w.w.b.b
    -38,   // .bw.b.b
    13,    // bbw.b.b
    -3,    // wbw.b.b
    41,    // .ww.b.b
    5,     // bww.b.b
    -7,    // www.b.b
    5,     // ...bb.b
    -5,    // b..bb.b
    33,    // w..bb.b
    -38,   // .b.bb.b
    8,     // bb.bb.b
    -4,    // wb.bb.b
    2,     // .w.bb.b
    22,    // bw.bb.b
    -7,    // ww.bb.b
    33,    // ..bbb.b
    31,    // b.bbb.b
    30,    // w.bbb.b
    19,    // .bbbb.b
    18,    // bbbbb.b
    -29,   // wbbbb.b
    24,    // .wbbb.b
    13,    // bwbbb.b
    -12,   // wwbbb.b
    -2,    // ..wbb.b
    36,    // b.wbb.b
    7,     // w.wbb.b
    -32,   // .bwbb.b
    13,    // bbwbb.b
    2,     // wbwbb.b
    4,     // .wwbb.b
    9,     // bwwbb.b
    -27,   // wwwbb.b
    -2,    // ...wb.b
    10,    // b..wb.b
    15,    // w..wb.b
    -2,    // .b.wb.b
    -3,    // bb.wb.b
    -10,   // wb.wb.b
    0,     // .w.wb.b
    32,    // bw.wb.b
    47,    // ww.wb.b
    -7,    // ..bwb.b
    13,    // b.bwb.b
    -30,   // w.bwb.b
    -2,    // .bbwb.b
    -8,    // bbbwb.b
    2,     // wbbwb.b
    7,     // .wbwb.b
    -24,   // bwbwb.b
    0,     // wwbwb.b
    -4,    // ..wwb.b
    10,    // b.wwb.b
    -7,    // w.wwb.b
    11,    // .bwwb.b
    -25,   // bbwwb.b
    0,     // wbwwb.b
    9,     // .wwwb.b
    6,     // bwwwb.b
    12,    // wwwwb.b
    16,    // ....w.b
    -27,   // b...w.b
    7,     // w...w.b
    -41,   // .b..w.b
    27,    // bb..w.b
    19,    // wb..w.b
    -7,    // .w..w.b
    19,    // bw..w.b
    -3,    // ww..w.b
    -2,    // ..b.w.b
    -10,   // b.b.w.b
    0,     // w.b.w.b
    5,     // .bb.w.b
    29,    // bbb.w.b
    9,     // wbb.w.b
    6,     // .wb.w.b
    22,    // bwb.w.b
    -20,   // wwb.w.b
    2,     // ..w.w.b
    -60,   // b.w.w.b
    -19,   // w.w.w.b
    54,    // .bw.w.b
    17,    // bbw.w.b
    -2,    // wbw.w.b
    -6,    // .ww.w.b
    -16,   // bww.w.b
    1,     // www.w.b
    24,    // ...bw.b
    34,    // b..bw.b
    22,    // w..bw.b
    -4,    // .b.bw.b
    -6,    // bb.bw.b
    1,     // wb.bw.b
    -1,    // .w.bw.b
    16,    // bw.bw.b
    14,    // ww.bw.b
    -9,    // ..bbw.b
    36,    // b.bbw.b
    -30,   // w.bbw.b
    1,     // .bbbw.b
    -30,   // bbbbw.b
    -11,   // wbbbw.b
    22,    // .wbbw.b
    6,     // bwbbw.b
    1,     // wwbbw.b
    15,    // ..wbw.b
    -22,   // b.wbw.b
    30,    // w.wbw.b
    9,     // .bwbw.b
    13,    // bbwbw.b
    3,     // wbwbw.b
    33,    // .wwbw.b
    -8,    // bwwbw.b
    27,    // wwwbw.b
    30,    // ...ww.b
    33,    // b..ww.b
    32,    // w..ww.b
    4,     // .b.ww.b
    -8,    // bb.ww.b
    18,    // wb.ww.b
    -9,    // .w.ww.b
    -23,   // bw.ww.b
    -10,   // ww.ww.b
    -8,    // ..bww.b
    10,    // b.bww.b
    30,    // w.bww.b
    -17,   // .bbww.b
    -2,    // bbbww.b
    11,    // wbbww.b
    -12,   // .wbww.b
    -6,    // bwbww.b
    -32,   // wwbww.b
    40,    // ..www.b
    10,    // b.www.b
    -30,   // w.www.b
    44,    // .bwww.b
    29,    // bbwww.b
    5,     // wbwww.b
    -6,    // .wwww.b
    -5,    // bwwww.b
    -4,    // wwwww.b
    35,    // .....bb
    16,    // b....bb
    -7,    // w....bb
    40,    // .b...bb
    -19,   // bb...bb
    28,    // wb...bb
    -15,   // .w...bb
    -20,   // bw...bb
    0,     // ww...bb
    -33,   // ..b..bb
    -16,   // b.b..bb
    3,     // w.b..bb
    9,     // .bb..bb
    52,    // bbb..bb
    -38,   // wbb..bb
    -3,    // .wb..bb
    -15,   // bwb..bb
    6,     // wwb..bb
    36,    // ..w..bb
    27,    // b.w..bb
    38,    // w.w..bb
    -17,   // .bw..bb
    0,     // bbw..bb
    7,     // wbw..bb
    10,    // .ww..bb
    13,    // bww..bb
    -9,    // www..bb
    7,     // ...b.bb
    17,    // b..b.bb
    30,    // w..b.bb
    17,    // .b.b.bb
    -27,   // bb.b.bb
    -19,   // wb.b.bb
    10,    // .w.b.bb
    13,    // bw.b.bb
    12,    // ww.b.bb
    11,    // ..bb.bb
    8,     // b.bb.bb
    10,    // w.bb.bb
    9,     // .bbb.bb
    10,    // bbbb.bb
    2,     // wbbb.bb
    -1,    // .wbb.bb
    19,    // bwbb.bb
    20,    // wwbb.bb
    -2,    // ..wb.bb
    -6,    // b.wb.bb
    -47,   // w.wb.bb
    -6,    // .bwb.bb
    52,    // bbwb.bb
    -46,   // wbwb.bb
    9,     // .wwb.bb
    5,     // bwwb.bb
    20,    // wwwb.bb
    45,    // ...w.bb
    11,    // b..w.bb
    13,    // w..w.bb
    28,    // .b.w.bb
    22,    // bb.w.bb
    -1,    // wb.w.bb
    26,    // .w.w.bb
    -42,   // bw.w.bb
    -12,   // ww.w.bb
    -3,    // ..bw.bb
    -3,    // b.bw.bb
    -14,   // w.bw.bb
    22,    // .bbw.bb
    -41,   // bbbw.bb
    18,    // wbbw.bb
    18,    // .wbw.bb
    23,    // bwbw.bb
    11,    // wwbw.bb
    -26,   // ..ww.bb
    -8,    // b.ww.bb
    7,     // w.ww.bb
    -19,   // .bww.bb
    5,     // bbww.bb
    4,     // wbww.bb
    12,    // .www.bb
    14,    // bwww.bb
    13,    // wwww.bb
    82,    // ....bbb
    -44,   // b...bbb
    -20,   // w...bbb
    -7,    // .b..bbb
    52,    // bb..bbb
    14,    // wb..bbb
    44,    // .w..bbb
    14,    // bw..bbb
    9,     // ww..bbb
    32,    // ..b.bbb
    -20,   // b.b.bbb
    -1,    // w.b.bbb
    -20,   // .bb.bbb
    46,    // bbb.bbb
    16,    // wbb.bbb
    40,    // .wb.bbb
    -3,    // bwb.bbb
    8,     // wwb.bbb
    26,    // ..w.bbb
    29,    // b.w.bbb
    7,     // w.w.bbb
    0,     // .bw.bbb
    -4,    // bbw.bbb
    -26,   // wbw.bbb
    44,    // .ww.bbb
    -29,   // bww.bbb
    0,     // www.bbb
    144,   // ...bbbb
    15,    // b..bbbb
    9,     // w..bbbb
    10,    // .b.bbbb
    10,    // bb.bbbb
    -56,   // wb.bbbb
    18,    // .w.bbbb
    -10,   // bw.bbbb
    -13,   // ww.bbbb
    28,    // ..bbbbb
    18,    // b.bbbbb
    4,     // w.bbbbb
    7,     // .bbbbbb
    39,    // bbbbbbb
    -6,    // wbbbbbb
    6,     // .wbbbbb
    -19,   // bwbbbbb
    -12,   // wwbbbbb
    41,    // ..wbbbb
    -30,   // b.wbbbb
    -12,   // w.wbbbb
    -8,    // .bwbbbb
    31,    // bbwbbbb
    -17,   // wbwbbbb
    -9,    // .wwbbbb
    0,     // bwwbbbb
    8,     // wwwbbbb
    0,     // ...wbbb
    3,     // b..wbbb
    10,    // w..wbbb
    -3,    // .b.wbbb
    -41,   // bb.wbbb
    -20,   // wb.wbbb
    28,    // .w.wbbb
    -31,   // bw.wbbb
    -20,   // ww.wbbb
    -22,   // ..bwbbb
    -8,    // b.bwbbb
    -27,   // w.bwbbb
    -24,   // .bbwbbb
    -8,    // bbbwbbb
    -13,   // wbbwbbb
    49,    // .wbwbbb
    -9,    // bwbwbbb
    -4,    // wwbwbbb
    26,    // ..wwbbb
    -2,    // b.wwbbb
    27,    // w.wwbbb
    -10,   // .bwwbbb
    -28,   // bbwwbbb
    -3,    // wbwwbbb
    -10,   // .wwwbbb
    -8,    // bwwwbbb
    -8,    // wwwwbbb
    9,     // ....wbb
    -11,   // b...wbb
    16,    // w...wbb
    -16,   // .b..wbb
    0,     // bb..wbb
    -16,   // wb..wbb
    -33,   // .w..wbb
    -11,   // bw..wbb
    -6,    // ww..wbb
    2,     // ..b.wbb
    13,    // b.b.wbb
    20,    // w.b.wbb
    4,     // .bb.wbb
    -4,    // bbb.wbb
    26,    // wbb.wbb
    -12,   // .wb.wbb
    -1,    // bwb.wbb
    0,     // wwb.wbb
    -15,   // ..w.wbb
    17,    // b.w.wbb
    -35,   // w.w.wbb
    15,    // .bw.wbb
    30,    // bbw.wbb
    -4,    // wbw.wbb
    -17,   // .ww.wbb
    -18,   // bww.wbb
    -8,    // www.wbb
    -34,   // ...bwbb
    25,    // b..bwbb
    -6,    // w..bwbb
    3,     // .b.bwbb
    52,    // bb.bwbb
    -7,    // wb.bwbb
    -19,   // .w.bwbb
    -50,   // bw.bwbb
    -11,   // ww.bwbb
    -19,   // ..bbwbb
    13,    // b.bbwbb
    32,    // w.bbwbb
    -27,   // .bbbwbb
    31,    // bbbbwbb
    -42,   // wbbbwbb
    -29,   // .wbbwbb
    -13,   // bwbbwbb
    53,    // wwbbwbb
    18,    // ..wbwbb
    13,    // b.wbwbb
    0,     // w.wbwbb
    37,    // .bwbwbb
    -10,   // bbwbwbb
    1,     // wbwbwbb
    -35,   // .wwbwbb
    -3,    // bwwbwbb
    4,     // wwwbwbb
    -32,   // ...wwbb
    5,     // b..wwbb
    0,     // w..wwbb
    -31,   // .b.wwbb
    5,     // bb.wwbb
    -3,    // wb.wwbb
    48,    // .w.wwbb
    52,    // bw.wwbb
    -20,   // ww.wwbb
    15,    // ..bwwbb
    -25,   // b.bwwbb
    -1,    // w.bwwbb
    -33,   // .bbwwbb
    -28,   // bbbwwbb
    -20,   // wbbwwbb
    -39,   // .wbwwbb
    -2,    // bwbwwbb
    -53,   // wwbwwbb
    4,     // ..wwwbb
    29,    // b.wwwbb
    12,    // w.wwwbb
    2,     // .bwwwbb
    -14,   // bbwwwbb
    7,     // wbwwwbb
    -27,   // .wwwwbb
    -6,    // bwwwwbb
    12,    // wwwwwbb
    -7,    // .....wb
    -7,    // b....wb
    -10,   // w....wb
    22,    // .b...wb
    -20,   // bb...wb
    0,     // wb...wb
    -17,   // .w...wb
    31,    // bw...wb
    -28,   // ww...wb
    -22,   // ..b..wb
    57,    // b.b..wb
    -19,   // w.b..wb
    18,    // .bb..wb
    14,    // bbb..wb
    20,    // wbb..wb
    39,    // .wb..wb
    -6,    // bwb..wb
    16,    // wwb..wb
    9,     // ..w..wb
    19,    // b.w..wb
    5,     // w.w..wb
    -32,   // .bw..wb
    -11,   // bbw..wb
    -36,   // wbw..wb
    -30,   // .ww..wb
    25,    // bww..wb
    -14,   // www..wb
    -6,    // ...b.wb
    -26,   // b..b.wb
    18,    // w..b.wb
    -69,   // .b.b.wb
    13,    // bb.b.wb
    13,    // wb.b.wb
    -2,    // .w.b.wb
    -15,   // bw.b.wb
    1,     // ww.b.wb
    -6,    // ..bb.wb
    22,    // b.bb.wb
    -18,   // w.bb.wb
    33,    // .bbb.wb
    -10,   // bbbb.wb
    -1,    // wbbb.wb
    20,    // .wbb.wb
    0,     // bwbb.wb
    3,     // wwbb.wb
    -16,   // ..wb.wb
    16,    // b.wb.wb
    10,    // w.wb.wb
    21,    // .bwb.wb
    -50,   // bbwb.wb
    -6,    // wbwb.wb
    -3,    // .wwb.wb
    -25,   // bwwb.wb
    20,    // wwwb.wb
    31,    // ...w.wb
    -12,   // b..w.wb
    -14,   // w..w.wb
    -2,    // .b.w.wb
    -42,   // bb.w.wb
    -13,   // wb.w.wb
    4,     // .w.w.wb
    3,     // bw.w.wb
    19,    // ww.w.wb
    -3,    // ..bw.wb
    32,    // b.bw.wb
    -1,    // w.bw.wb
    -23,   // .bbw.wb
    -31,   // bbbw.wb
    -1,    // wbbw.wb
    -29,   // .wbw.wb
    -18,   // bwbw.wb
    7,     // wwbw.wb
    28,    // ..ww.wb
    -23,   // b.ww.wb
    4,     // w.ww.wb
    -14,   // .bww.wb
    52,    // bbww.wb
    21,    // wbww.wb
    -35,   // .www.wb
    -4,    // bwww.wb
    56,    // wwww.wb
    -14,   // ....bwb
    -47,   // b...bwb
    14,    // w...bwb
    8,     // .b..bwb
    -15,   // bb..bwb
    36,    // wb..bwb
    41,    // .w..bwb
    -6,    // bw..bwb
    -7,    // ww..bwb
    -20,   // ..b.bwb
    11,    // b.b.bwb
    2,     // w.b.bwb
    9,     // .bb.bwb
    -3,    // bbb.bwb
    -1,    // wbb.bwb
    21,    // .wb.bwb
    -22,   // bwb.bwb
    4,     // wwb.bwb
    -7,    // ..w.bwb
    22,    // b.w.bwb
    3,     // w.w.bwb
    -23,   // .bw.bwb
    -1,    // bbw.bwb
    0,     // wbw.bwb
    5,     // .ww.bwb
    -17,   // bww.bwb
    26,    // www.bwb
    3,     // ...bbwb
    -20,   // b..bbwb
    -31,   // w..bbwb
    18,    // .b.bbwb
    19,    // bb.bbwb
    -21,   // wb.bbwb
    -37,   // .w.bbwb
    0,     // bw.bbwb
    -4,    // ww.bbwb
    -13,   // ..bbbwb
    13,    // b.bbbwb
    -5,    // w.bbbwb
    25,    // .bbbbwb
    -19,   // bbbbbwb
    17,    // wbbbbwb
    -15,   // .wbbbwb
    -29,   // bwbbbwb
    -7,    // wwbbbwb
    -46,   // ..wbbwb
    6,     // b.wbbwb
    0,     // w.wbbwb
    -9,    // .bwbbwb
    -13,   // bbwbbwb
    -17,   // wbwbbwb
    -27,   // .wwbbwb
    20,    // bwwbbwb
    3,     // wwwbbwb
    4,     // ...wbwb
    -50,   // b..wbwb
    14,    // w..wbwb
    -10,   // .b.wbwb
    23,    // bb.wbwb
    6,     // wb.wbwb
    2,     // .w.wbwb
    -18,   // bw.wbwb
    46,    // ww.wbwb
    14,    // ..bwbwb
    -24,   // b.bwbwb
    -3,    // w.bwbwb
    8,     // .bbwbwb
    -9,    // bbbwbwb
    -20,   // wbbwbwb
    -13,   // .wbwbwb
    5,     // bwbwbwb
    -1,    // wwbwbwb
    26,    // ..wwbwb
    -6,    // b.wwbwb
    -2,    // w.wwbwb
    -3,    // .bwwbwb
    -2,    // bbwwbwb
    17,    // wbwwbwb
    45,    // .wwwbwb
    26,    // bwwwbwb
    17,    // wwwwbwb
    22,    // ....wwb
    -6,    // b...wwb
    30,    // w...wwb
    -47,   // .b..wwb
    13,    // bb..wwb
    -20,   // wb..wwb
    -51,   // .w..wwb
    25,    // bw..wwb
    38,    // ww..wwb
    -7,    // ..b.wwb
    5,     // b.b.wwb
    -9,    // w.b.wwb
    -1,    // .bb.wwb
    -29,   // bbb.wwb
    0,     // wbb.wwb
    25,    // .wb.wwb
    -17,   // bwb.wwb
    -26,   // wwb.wwb
    0,     // ..w.wwb
    -16,   // b.w.wwb
    17,    // w.w.wwb
    15,    // .bw.wwb
    -18,   // bbw.wwb
    1,     // wbw.wwb
    -35,   // .ww.wwb
    -37,   // bww.wwb
    -16,   // www.wwb
    -3,    // ...bwwb
    13,    // b..bwwb
    29,    // w..bwwb
    -13,   // .b.bwwb
    5,     // bb.bwwb
    1,     // wb.bwwb
    2,     // .w.bwwb
    -25,   // bw.bwwb
    -18,   // ww.bwwb
    -8,    // ..bbwwb
    9,     // b.bbwwb
    -11,   // w.bbwwb
    -24,   // .bbbwwb
    0,     // bbbbwwb
    11,    // wbbbwwb
    30,    // .wbbwwb
    20,    // bwbbwwb
    20,    // wwbbwwb
    -39,   // ..wbwwb
    -8,    // b.wbwwb
    -2,    // w.wbwwb
    38,    // .bwbwwb
    -3,    // bbwbwwb
    20,    // wbwbwwb
    22,    // .wwbwwb
    29,    // bwwbwwb
    13,    // wwwbwwb
    38,    // ...wwwb
    -10,   // b..wwwb
    -9,    // w..wwwb
    2,     // .b.wwwb
    14,    // bb.wwwb
    1,     // wb.wwwb
    -55,   // .w.wwwb
    -4,    // bw.wwwb
    -2,    // ww.wwwb
    10,    // ..bwwwb
    6,     // b.bwwwb
    11,    // w.bwwwb
    -13,   // .bbwwwb
    -8,    // bbbwwwb
    -11,   // wbbwwwb
    -13,   // .wbwwwb
    26,    // bwbwwwb
    42,    // wwbwwwb
    -42,   // ..wwwwb
    -5,    // b.wwwwb
    29,    // w.wwwwb
    74,    // .bwwwwb
    -6,    // bbwwwwb
    -17,   // wbwwwwb
    -18,   // .wwwwwb
    6,     // bwwwwwb
    6,     // wwwwwwb
    0,     // ......w
    0,     // b.....w
    -10,   // w.....w
    -41,   // .b....w
    -7,    // bb....w
    7,     // wb....w
    6,     // .w....w
    -10,   // bw....w
    -16,   // ww....w
    15,    // ..b...w
    4,     // b.b...w
    27,    // w.b...w
    -2,    // .bb...w
    -20,   // bbb...w
    6,     // wbb...w
    -25,   // .wb...w
    14,    // bwb...w
    11,    // wwb...w
    0,     // ..w...w
    7,     // b.w...w
    6,     // w.w...w
    -9,    // .bw...w
    16,    // bbw...w
    47,    // wbw...w
    14,    // .ww...w
    30,    // bww...w
    44,    // www...w
    17,    // ...b..w
    7,     // b..b..w
    17,    // w..b..w
    51,    // .b.b..w
    30,    // bb.b..w
    12,    // wb.b..w
    -23,   // .w.b..w
    18,    // bw.b..w
    -11,   // ww.b..w
    0,     // ..bb..w
    33,    // b.bb..w
    -33,   // w.bb..w
    8,     // .bbb..w
    9,     // bbbb..w
    10,    // wbbb..w
    24,    // .wbb..w
    -31,   // bwbb..w
    -5,    // wwbb..w
    16,    // ..wb..w
    22,    // b.wb..w
    -10,   // w.wb..w
    -18,   // .bwb..w
    -6,    // bbwb..w
    50,    // wbwb..w
    -14,   // .wwb..w
    29,    // bwwb..w
    -3,    // wwwb..w
    -9,    // ...w..w
    -7,    // b..w..w
    1,     // w..w..w
    -1,    // .b.w..w
    13,    // bb.w..w
    26,    // wb.w..w
    9,     // .w.w..w
    -14,   // bw.w..w
    -17,   // ww.w..w
    -5,    // ..bw..w
    15,    // b.bw..w
    -34,   // w.bw..w
    17,    // .bbw..w
    10,    // bbbw..w
    -13,   // wbbw..w
    -4,    // .wbw..w
    14,    // bwbw..w
    -25,   // wwbw..w
    5,     // ..ww..w
    32,    // b.ww..w
    5,     // w.ww..w
    19,    // .bww..w
    0,     // bbww..w
    20,    // wbww..w
    11,    // .www..w
    -9,    // bwww..w
    -15,   // wwww..w
    -16,   // ....b.w
    -7,    // b...b.w
    27,    // w...b.w
    7,     // .b..b.w
    3,     // bb..b.w
    -19,   // wb..b.w
    41,    // .w..b.w
    -19,   // bw..b.w
    -27,   // ww..b.w
    -2,    // ..b.b.w
    19,    // b.b.b.w
    60,    // w.b.b.w
    6,     // .bb.b.w
    -1,    // bbb.b.w
    16,    // wbb.b.w
    -54,   // .wb.b.w
    2,     // bwb.b.w
    -17,   // wwb.b.w
    2,     // ..w.b.w
    0,     // b.w.b.w
    10,    // w.w.b.w
    -6,    // .bw.b.w
    20,    // bbw.b.w
    -22,   // wbw.b.w
    -5,    // .ww.b.w
    -9,    // bww.b.w
    -29,   // www.b.w
    -30,   // ...bb.w
    -32,   // b..bb.w
    -33,   // w..bb.w
    9,     // .b.bb.w
    10,    // bb.bb.w
    23,    // wb.bb.w
    -4,    // .w.bb.w
    -18,   // bw.bb.w
    8,     // ww.bb.w
    -40,   // ..bbb.w
    30,    // b.bbb.w
    -10,   // w.bbb.w
    6,     // .bbbb.w
    4,     // bbbbb.w
    5,     // wbbbb.w
    -44,   // .wbbb.w
    -5,    // bwbbb.w
    -29,   // wwbbb.w
    8,     // ..wbb.w
    -30,   // b.wbb.w
    -10,   // w.wbb.w
    12,    // .bwbb.w
    32,    // bbwbb.w
    6,     // wbwbb.w
    17,    // .wwbb.w
    -11,   // bwwbb.w
    2,     // wwwbb.w
    -24,   // ...wb.w
    -22,   // b..wb.w
    -34,   // w..wb.w
    1,     // .b.wb.w
    -14,   // bb.wb.w
    -16,   // wb.wb.w
    4,     // .w.wb.w
    -1,    // bw.wb.w
    6,     // ww.wb.w
    -15,   // ..bwb.w
    -30,   // b.bwb.w
    22,    // w.bwb.w
    -33,   // .bbwb.w
    -27,   // bbbwb.w
    8,     // wbbwb.w
    -9,    // .wbwb.w
    -3,    // bwbwb.w
    -13,   // wwbwb.w
    9,     // ..wwb.w
    30,    // b.wwb.w
    -36,   // w.wwb.w
    -22,   // .bwwb.w
    -1,    // bbwwb.w
    -6,    // wbwwb.w
    -1,    // .wwwb.w
    11,    // bwwwb.w
    30,    // wwwwb.w
    -24,   // ....w.w
    -4,    // b...w.w
    6,     // w...w.w
    9,     // .b..w.w
    38,    // bb..w.w
    -57,   // wb..w.w
    -17,   // .w..w.w
    5,     // bw..w.w
    16,    // ww..w.w
    -2,    // ..b.w.w
    0,     // b.b.w.w
    10,    // w.b.w.w
    -41,   // .bb.w.w
    7,     // bbb.w.w
    -5,    // wbb.w.w
    38,    // .wb.w.w
    3,     // bwb.w.w
    -13,   // wwb.w.w
    28,    // ..w.w.w
    -19,   // b.w.w.w
    17,    // w.w.w.w
    40,    // .bw.w.w
    -35,   // bbw.w.w
    -11,   // wbw.w.w
    -2,    // .ww.w.w
    17,    // bww.w.w
    20,    // www.w.w
    2,     // ...bw.w
    -15,   // b..bw.w
    -10,   // w..bw.w
    0,     // .b.bw.w
    -47,   // bb.bw.w
    -32,   // wb.bw.w
    2,     // .w.bw.w
    10,    // bw.bw.w
    3,     // ww.bw.w
    4,     // ..bbw.w
    7,     // b.bbw.w
    -10,   // w.bbw.w
    -9,    // .bbbw.w
    -12,   // bbbbw.w
    -6,    // wbbbw.w
    -11,   // .wbbw.w
    0,     // bwbbw.w
    25,    // wwbbw.w
    7,     // ..wbw.w
    30,    // b.wbw.w
    -13,   // w.wbw.w
    -7,    // .bwbw.w
    0,     // bbwbw.w
    24,    // wbwbw.w
    2,     // .wwbw.w
    -2,    // bwwbw.w
    8,     // wwwbw.w
    -5,    // ...ww.w
    -33,   // b..ww.w
    5,     // w..ww.w
    -2,    // .b.ww.w
    7,     // bb.ww.w
    -22,   // wb.ww.w
    38,    // .w.ww.w
    4,     // bw.ww.w
    -8,    // ww.ww.w
    2,     // ..bww.w
    -7,    // b.bww.w
    -36,   // w.bww.w
    -4,    // .bbww.w
    27,    // bbbww.w
    -9,    // wbbww.w
    32,    // .wbww.w
    -2,    // bwbww.w
    -13,   // wwbww.w
    -33,   // ..www.w
    -30,   // b.www.w
    -31,   // w.www.w
    -24,   // .bwww.w
    12,    // bbwww.w
    -13,   // wbwww.w
    -19,   // .wwww.w
    29,    // bwwww.w
    -18,   // wwwww.w
    7,     // .....bw
    10,    // b....bw
    7,     // w....bw
    17,    // .b...bw
    28,    // bb...bw
    -31,   // wb...bw
    -22,   // .w...bw
    0,     // bw...bw
    20,    // ww...bw
    -9,    // ..b..bw
    -5,    // b.b..bw
    -19,   // w.b..bw
    30,    // .bb..bw
    14,    // bbb..bw
    -25,   // wbb..bw
    32,    // .wb..bw
    36,    // bwb..bw
    11,    // wwb..bw
    22,    // ..w..bw
    19,    // b.w..bw
    -57,   // w.w..bw
    -39,   // .bw..bw
    -16,   // bbw..bw
    6,     // wbw..bw
    -18,   // .ww..bw
    -20,   // bww..bw
    -14,   // www..bw
    -31,   // ...b.bw
    14,    // b..b.bw
    12,    // w..b.bw
    -4,    // .b.b.bw
    -19,   // bb.b.bw
    -3,    // wb.b.bw
    2,     // .w.b.bw
    13,    // bw.b.bw
    42,    // ww.b.bw
    -28,   // ..bb.bw
    -4,    // b.bb.bw
    23,    // w.bb.bw
    35,    // .bbb.bw
    -56,   // bbbb.bw
    4,     // wbbb.bw
    14,    // .wbb.bw
    -21,   // bwbb.bw
    -52,   // wwbb.bw
    3,     // ..wb.bw
    1,     // b.wb.bw
    -32,   // w.wb.bw
    29,    // .bwb.bw
    -7,    // bbwb.bw
    18,    // wbwb.bw
    23,    // .wwb.bw
    1,     // bwwb.bw
    31,    // wwwb.bw
    6,     // ...w.bw
    -18,   // b..w.bw
    26,    // w..w.bw
    2,     // .b.w.bw
    -1,    // bb.w.bw
    15,    // wb.w.bw
    69,    // .w.w.bw
    -13,   // bw.w.bw
    -13,   // ww.w.bw
    16,    // ..bw.bw
    -10,   // b.bw.bw
    -16,   // w.bw.bw
    3,     // .bbw.bw
    -20,   // bbbw.bw
    25,    // wbbw.bw
    -21,   // .wbw.bw
    6,     // bwbw.bw
    50,    // wwbw.bw
    6,     // ..ww.bw
    18,    // b.ww.bw
    -22,   // w.ww.bw
    -20,   // .bww.bw
    -3,    // bbww.bw
    0,     // wbww.bw
    -33,   // .www.bw
    1,     // bwww.bw
    10,    // wwww.bw
    -22,   // ....bbw
    -30,   // b...bbw
    6,     // w...bbw
    51,    // .b..bbw
    -38,   // bb..bbw
    -25,   // wb..bbw
    47,    // .w..bbw
    20,    // bw..bbw
    -13,   // ww..bbw
    0,     // ..b.bbw
    -17,   // b.b.bbw
    16,    // w.b.bbw
    35,    // .bb.bbw
    16,    // bbb.bbw
    37,    // wbb.bbw
    -15,   // .wb.bbw
    -1,    // bwb.bbw
    18,    // wwb.bbw
    7,     // ..w.bbw
    9,     // b.w.bbw
    -5,    // w.w.bbw
    -25,   // .bw.bbw
    26,    // bbw.bbw
    17,    // wbw.bbw
    1,     // .ww.bbw
    0,     // bww.bbw
    29,    // www.bbw
    -38,   // ...bbbw
    9,     // b..bbbw
    10,    // w..bbbw
    55,    // .b.bbbw
    2,     // bb.bbbw
    4,     // wb.bbbw
    -2,    // .w.bbbw
    -1,    // bw.bbbw
    -14,   // ww.bbbw
    42,    // ..bbbbw
    -29,   // b.bbbbw
    5,     // w.bbbbw
    18,    // .bbbbbw
    -6,    // bbbbbbw
    -6,    // wbbbbbw
    -74,   // .wbbbbw
    17,    // bwbbbbw
    6,     // wwbbbbw
    -10,   // ..wbbbw
    -11,   // b.wbbbw
    -6,    // w.wbbbw
    13,    // .bwbbbw
    -42,   // bbwbbbw
    -26,   // wbwbbbw
    13,    // .wwbbbw
    11,    // bwwbbbw
    8,     // wwwbbbw
    3,     // ...wbbw
    -29,   // b..wbbw
    -13,   // w..wbbw
    -2,    // .b.wbbw
    18,    // bb.wbbw
    25,    // wb.wbbw
    13,    // .w.wbbw
    -1,    // bw.wbbw
    -5,    // ww.wbbw
    39,    // ..bwbbw
    2,     // b.bwbbw
    8,     // w.bwbbw
    -22,   // .bbwbbw
    -13,   // bbbwbbw
    -29,   // wbbwbbw
    -38,   // .wbwbbw
    -20,   // bwbwbbw
    3,     // wwbwbbw
    8,     // ..wwbbw
    11,    // b.wwbbw
    -9,    // w.wwbbw
    -30,   // .bwwbbw
    -20,   // bbwwbbw
    -20,   // wbwwbbw
    24,    // .wwwbbw
    -11,   // bwwwbbw
    0,     // wwwwbbw
    14,    // ....wbw
    -14,   // b...wbw
    47,    // w...wbw
    -41,   // .b..wbw
    7,     // bb..wbw
    6,     // wb..wbw
    -8,    // .w..wbw
    -36,   // bw..wbw
    15,    // ww..wbw
    7,     // ..b.wbw
    -3,    // b.b.wbw
    -22,   // w.b.wbw
    -5,    // .bb.wbw
    -26,   // bbb.wbw
    17,    // wbb.wbw
    23,    // .wb.wbw
    0,     // bwb.wbw
    1,     // wwb.wbw
    20,    // ..w.wbw
    -2,    // b.w.wbw
    -11,   // w.w.wbw
    -21,   // .bw.wbw
    -4,    // bbw.wbw
    22,    // wbw.wbw
    -9,    // .ww.wbw
    1,     // bww.wbw
    3,     // www.wbw
    -4,    // ...bwbw
    -14,   // b..bwbw
    50,    // w..bwbw
    -2,    // .b.bwbw
    -46,   // bb.bwbw
    18,    // wb.bwbw
    10,    // .w.bwbw
    -6,    // bw.bwbw
    -23,   // ww.bwbw
    -26,   // ..bbwbw
    2,     // b.bbwbw
    6,     // w.bbwbw
    -45,   // .bbbwbw
    -17,   // bbbbwbw
    -26,   // wbbbwbw
    3,     // .wbbwbw
    -17,   // bwbbwbw
    2,     // wwbbwbw
    -14,   // ..wbwbw
    3,     // b.wbwbw
    24,    // w.wbwbw
    13,    // .bwbwbw
    1,     // bbwbwbw
    -5,    // wbwbwbw
    -8,    // .wwbwbw
    20,    // bwwbwbw
    9,     // wwwbwbw
    -3,    // ...wwbw
    31,    // b..wwbw
    20,    // w..wwbw
    37,    // .b.wwbw
    4,     // bb.wwbw
    0,     // wb.wwbw
    -18,   // .w.wwbw
    21,    // bw.wwbw
    -19,   // ww.wwbw
    46,    // ..bwwbw
    0,     // b.bwwbw
    -6,    // w.bwwbw
    27,    // .bbwwbw
    -3,    // bbbwwbw
    -20,   // wbbwwbw
    9,     // .wbwwbw
    17,    // bwbwwbw
    13,    // wwbwwbw
    13,    // ..wwwbw
    5,     // b.wwwbw
    -13,   // w.wwwbw
    15,    // .bwwwbw
    7,     // bbwwwbw
    29,    // wbwwwbw
    -25,   // .wwwwbw
    -17,   // bwwwwbw
    19,    // wwwwwbw
    -35,   // .....ww
    7,     // b....ww
    -16,   // w....ww
    15,    // .b...ww
    0,     // bb...ww
    20,    // wb...ww
    -40,   // .w...ww
    -28,   // bw...ww
    19,    // ww...ww
    -36,   // ..b..ww
    -38,   // b.b..ww
    -27,   // w.b..ww
    -10,   // .bb..ww
    9,     // bbb..ww
    -13,   // wbb..ww
    17,    // .wb..ww
    -7,    // bwb..ww
    0,     // wwb..ww
    33,    // ..w..ww
    -3,    // b.w..ww
    16,    // w.w..ww
    3,     // .bw..ww
    -6,    // bbw..ww
    15,    // wbw..ww
    -9,    // .ww..ww
    38,    // bww..ww
    -52,   // www..ww
    -45,   // ...b.ww
    -13,   // b..b.ww
    -11,   // w..b.ww
    -26,   // .b.b.ww
    12,    // bb.b.ww
    42,    // wb.b.ww
    -28,   // .w.b.ww
    1,     // bw.b.ww
    -22,   // ww.b.ww
    26,    // ..bb.ww
    -7,    // b.bb.ww
    8,     // w.bb.ww
    -12,   // .bbb.ww
    -13,   // bbbb.ww
    -14,   // wbbb.ww
    19,    // .wbb.ww
    -4,    // bwbb.ww
    -5,    // wwbb.ww
    3,     // ..wb.ww
    14,    // b.wb.ww
    3,     // w.wb.ww
    -18,   // .bwb.ww
    -11,   // bbwb.ww
    -23,   // wbwb.ww
    -22,   // .wwb.ww
    -18,   // bwwb.ww
    41,    // wwwb.ww
    -7,    // ...w.ww
    -30,   // b..w.ww
    -17,   // w..w.ww
    -10,   // .b.w.ww
    -12,   // bb.w.ww
    -13,   // wb.w.ww
    -17,   // .w.w.ww
    19,    // bw.w.ww
    27,    // ww.w.ww
    2,     // ..bw.ww
    47,    // b.bw.ww
    6,     // w.bw.ww
    -9,    // .bbw.ww
    -20,   // bbbw.ww
    -5,    // wbbw.ww
    6,     // .wbw.ww
    46,    // bwbw.ww
    -52,   // wwbw.ww
    -11,   // ..ww.ww
    -10,   // b.ww.ww
    -8,    // w.ww.ww
    1,     // .bww.ww
    -20,   // bbww.ww
    -19,   // wbww.ww
    -9,    // .www.ww
    -2,    // bwww.ww
    -10,   // wwww.ww
    -9,    // ....bww
    -16,   // b...bww
    11,    // w...bww
    33,    // .b..bww
    6,     // bb..bww
    11,    // wb..bww
    16,    // .w..bww
    16,    // bw..bww
    0,     // ww..bww
    15,    // ..b.bww
    35,    // b.b.bww
    -17,   // w.b.bww
    17,    // .bb.bww
    8,     // bbb.bww
    18,    // wbb.bww
    -15,   // .wb.bww
    4,     // bwb.bww
    -30,   // wwb.bww
    -2,    // ..w.bww
    -20,   // b.w.bww
    -13,   // w.w.bww
    12,    // .bw.bww
    0,     // bbw.bww
    1,     // wbw.bww
    -4,    // .ww.bww
    -26,   // bww.bww
    4,     // www.bww
    32,    // ...bbww
    0,     // b..bbww
    -5,    // w..bbww
    -48,   // .b.bbww
    20,    // bb.bbww
    -52,   // wb.bbww
    31,    // .w.bbww
    3,     // bw.bbww
    -5,    // ww.bbww
    -4,    // ..bbbww
    -12,   // b.bbbww
    -29,   // w.bbbww
    27,    // .bbbbww
    -12,   // bbbbbww
    6,     // wbbbbww
    -2,    // .wbbbww
    -7,    // bwbbbww
    14,    // wwbbbww
    -15,   // ..wbbww
    1,     // b.wbbww
    25,    // w.wbbww
    39,    // .bwbbww
    53,    // bbwbbww
    2,     // wbwbbww
    33,    // .wwbbww
    20,    // bwwbbww
    28,    // wwwbbww
    34,    // ...wbww
    6,     // b..wbww
    -25,   // w..wbww
    19,    // .b.wbww
    11,    // bb.wbww
    50,    // wb.wbww
    -3,    // .w.wbww
    7,     // bw.wbww
    -52,   // ww.wbww
    -18,   // ..bwbww
    0,     // b.bwbww
    -13,   // w.bwbww
    35,    // .bbwbww
    -4,    // bbbwbww
    3,     // wbbwbww
    -37,   // .wbwbww
    -1,    // bwbwbww
    10,    // wwbwbww
    19,    // ..wwbww
    -32,   // b.wwbww
    -13,   // w.wwbww
    29,    // .bwwbww
    -53,   // bbwwbww
    13,    // wbwwbww
    27,    // .wwwbww
    42,    // bwwwbww
    -31,   // wwwwbww
    -82,   // ....www
    20,    // b...www
    44,    // w...www
    -44,   // .b..www
    -9,    // bb..www
    -14,   // wb..www
    7,     // .w..www
    -14,   // bw..www
    -52,   // ww..www
    -26,   // ..b.www
    -7,    // b.b.www
    -29,   // w.b.www
    -44,   // .bb.www
    0,     // bbb.www
    29,    // wbb.www
    0,     // .wb.www
    26,    // bwb.www
    4,     // wwb.www
    -32,   // ..w.www
    1,     // b.w.www
    20,    // w.w.www
    -40,   // .bw.www
    -8,    // bbw.www
    3,     // wbw.www
    20,    // .ww.www
    -16,   // bww.www
    -46,   // www.www
    0,     // ...bwww
    -10,   // b..bwww
    -3,    // w..bwww
    -28,   // .b.bwww
    20,    // bb.bwww
    31,    // wb.bwww
    3,     // .w.bwww
    20,    // bw.bwww
    41,    // ww.bwww
    -26,   // ..bbwww
    -27,   // b.bbwww
    2,     // w.bbwww
    10,    // .bbbwww
    8,     // bbbbwww
    8,     // wbbbwww
    10,    // .wbbwww
    3,     // bwbbwww
    28,    // wwbbwww
    22,    // ..wbwww
    27,    // b.wbwww
    8,     // w.wbwww
    -49,   // .bwbwww
    4,     // bbwbwww
    9,     // wbwbwww
    24,    // .wwbwww
    13,    // bwwbwww
    8,     // wwwbwww
    -144,  // ...wwww
    -9,    // b..wwww
    -15,   // w..wwww
    -18,   // .b.wwww
    13,    // bb.wwww
    10,    // wb.wwww
    -10,   // .w.wwww
    56,    // bw.wwww
    -10,   // ww.wwww
    -41,   // ..bwwww
    12,    // b.bwwww
    30,    // w.bwwww
    9,     // .bbwwww
    -8,    // bbbwwww
    0,     // wbbwwww
    8,     // .wbwwww
    17,    // bwbwwww
    -31,   // wwbwwww
    -28,   // ..wwwww
    -4,    // b.wwwww
    -18,   // w.wwwww
    -6,    // .bwwwww
    12,    // bbwwwww
    19,    // wbwwwww
    -7,    // .wwwwww
    6,     // bwwwwww
    -39,   // wwwwwww
    0,     // captures=0 threats=0
    16,    // captures=0 threats=1
    34,    // captures=0 threats=2
    42,    // captures=0 threats=3
    67,    // captures=0 threats=4
    19,    // captures=0 additional threats
    7,     // captures=1 threats=0
    52,    // captures=1 threats=1
    55,    // captures=1 threats=2
    77,    // captures=1 threats=3
    86,    // captures=1 threats=4
    41,    // captures=1 additional threats
    14,    // captures=2 threats=0
    53,    // captures=2 threats=1
    86,    // captures=2 threats=2
    98,    // captures=2 threats=3
    99,    // captures=2 threats=4
    24,    // captures=2 additional threats
    25,    // captures=3 threats=0
    70,    // captures=3 threats=1
    92,    // captures=3 threats=2
    103,   // captures=3 threats=3
    104,   // captures=3 threats=4
    45,    // captures=3 additional threats
    55,    // captures=4 threats=0
    92,    // captures=4 threats=1
    100,   // captures=4 threats=2
    112,   // captures=4 threats=3
    122,   // captures=4 threats=4
    28,    // captures=4 additional threats
].into_boxed_slice()
