vec![
    0,     // .......
    -2,    // b......
    2,     // w......
    -14,   // .b.....
    -6,    // bb.....
    10,    // wb.....
    14,    // .w.....
    -10,   // bw.....
    6,     // ww.....
    9,     // ..b....
    69,    // b.b....
    -11,   // w.b....
    5,     // .bb....
    50,    // bbb....
    -139,  // wbb....
    -45,   // .wb....
    30,    // bwb....
    121,   // wwb....
    -9,    // ..w....
    11,    // b.w....
    -69,   // w.w....
    45,    // .bw....
    -121,  // bbw....
    -30,   // wbw....
    -5,    // .ww....
    139,   // bww....
    -50,   // www....
    -12,   // ...b...
    -31,   // b..b...
    -18,   // w..b...
    -17,   // .b.b...
    104,   // bb.b...
    -79,   // wb.b...
    23,    // .w.b...
    -14,   // bw.b...
    -34,   // ww.b...
    -18,   // ..bb...
    87,    // b.bb...
    -30,   // w.bb...
    151,   // .bbb...
    486,   // bbbb...
    -111,  // wbbb...
    38,    // .wbb...
    -46,   // bwbb...
    3,     // wwbb...
    7,     // ..wb...
    77,    // b.wb...
    -62,   // w.wb...
    -64,   // .bwb...
    -98,   // bbwb...
    0,     // wbwb...
    -14,   // .wwb...
    39,    // bwwb...
    -85,   // wwwb...
    12,    // ...w...
    18,    // b..w...
    31,    // w..w...
    -23,   // .b.w...
    34,    // bb.w...
    14,    // wb.w...
    17,    // .w.w...
    79,    // bw.w...
    -104,  // ww.w...
    -7,    // ..bw...
    62,    // b.bw...
    -77,   // w.bw...
    14,    // .bbw...
    85,    // bbbw...
    -39,   // wbbw...
    64,    // .wbw...
    0,     // bwbw...
    98,    // wwbw...
    18,    // ..ww...
    30,    // b.ww...
    -87,   // w.ww...
    -38,   // .bww...
    -3,    // bbww...
    46,    // wbww...
    -151,  // .www...
    111,   // bwww...
    -486,  // wwww...
    9,     // ....b..
    35,    // b...b..
    -69,   // w...b..
    20,    // .b..b..
    -26,   // bb..b..
    14,    // wb..b..
    1,     // .w..b..
    -49,   // bw..b..
    58,    // ww..b..
    -36,   // ..b.b..
    -23,   // b.b.b..
    -41,   // w.b.b..
    -41,   // .bb.b..
    126,   // bbb.b..
    -110,  // wbb.b..
    -34,   // .wb.b..
    -64,   // bwb.b..
    -38,   // wwb.b..
    0,     // ..w.b..
    -22,   // b.w.b..
    -52,   // w.w.b..
    -20,   // .bw.b..
    -57,   // bbw.b..
    -61,   // wbw.b..
    20,    // .ww.b..
    -47,   // bww.b..
    -50,   // www.b..
    -18,   // ...bb..
    5,     // b..bb..
    -41,   // w..bb..
    4,     // .b.bb..
    42,    // bb.bb..
    14,    // wb.bb..
    -55,   // .w.bb..
    17,    // bw.bb..
    -41,   // ww.bb..
    24,    // ..bbb..
    104,   // b.bbb..
    -18,   // w.bbb..
    319,   // .bbbb..
    67,    // bbbbb..
    11,    // wbbbb..
    -71,   // .wbbb..
    -44,   // bwbbb..
    3,     // wwbbb..
    -104,  // ..wbb..
    -53,   // b.wbb..
    1,     // w.wbb..
    -44,   // .bwbb..
    -18,   // bbwbb..
    78,    // wbwbb..
    41,    // .wwbb..
    -96,   // bwwbb..
    -96,   // wwwbb..
    -7,    // ...wb..
    90,    // b..wb..
    68,    // w..wb..
    -21,   // .b.wb..
    -37,   // bb.wb..
    1,     // wb.wb..
    16,    // .w.wb..
    40,    // bw.wb..
    28,    // ww.wb..
    6,     // ..bwb..
    13,    // b.bwb..
    -22,   // w.bwb..
    -70,   // .bbwb..
    -167,  // bbbwb..
    38,    // wbbwb..
    -5,    // .wbwb..
    -39,   // bwbwb..
    -6,    // wwbwb..
    104,   // ..wwb..
    57,    // b.wwb..
    93,    // w.wwb..
    95,    // .bwwb..
    -3,    // bbwwb..
    -22,   // wbwwb..
    -72,   // .wwwb..
    37,    // bwwwb..
    -71,   // wwwwb..
    -9,    // ....w..
    69,    // b...w..
    -35,   // w...w..
    -1,    // .b..w..
    -58,   // bb..w..
    49,    // wb..w..
    -20,   // .w..w..
    -14,   // bw..w..
    26,    // ww..w..
    0,     // ..b.w..
    52,    // b.b.w..
    22,    // w.b.w..
    -20,   // .bb.w..
    50,    // bbb.w..
    47,    // wbb.w..
    20,    // .wb.w..
    61,    // bwb.w..
    57,    // wwb.w..
    36,    // ..w.w..
    41,    // b.w.w..
    23,    // w.w.w..
    34,    // .bw.w..
    38,    // bbw.w..
    64,    // wbw.w..
    41,    // .ww.w..
    110,   // bww.w..
    -126,  // www.w..
    7,     // ...bw..
    -68,   // b..bw..
    -90,   // w..bw..
    -16,   // .b.bw..
    -28,   // bb.bw..
    -40,   // wb.bw..
    21,    // .w.bw..
    -1,    // bw.bw..
    37,    // ww.bw..
    -104,  // ..bbw..
    -93,   // b.bbw..
    -57,   // w.bbw..
    72,    // .bbbw..
    71,    // bbbbw..
    -37,   // wbbbw..
    -95,   // .wbbw..
    22,    // bwbbw..
    3,     // wwbbw..
    -6,    // ..wbw..
    22,    // b.wbw..
    -13,   // w.wbw..
    5,     // .bwbw..
    6,     // bbwbw..
    39,    // wbwbw..
    70,    // .wwbw..
    -38,   // bwwbw..
    167,   // wwwbw..
    18,    // ...ww..
    41,    // b..ww..
    -5,    // w..ww..
    55,    // .b.ww..
    41,    // bb.ww..
    -17,   // wb.ww..
    -4,    // .w.ww..
    -14,   // bw.ww..
    -42,   // ww.ww..
    104,   // ..bww..
    -1,    // b.bww..
    53,    // w.bww..
    -41,   // .bbww..
    96,    // bbbww..
    96,    // wbbww..
    44,    // .wbww..
    -78,   // bwbww..
    18,    // wwbww..
    -24,   // ..www..
    18,    // b.www..
    -104,  // w.www..
    71,    // .bwww..
    -3,    // bbwww..
    44,    // wbwww..
    -319,  // .wwww..
    -11,   // bwwww..
    -67,   // wwwww..
    -14,   // .....b.
    -31,   // b....b.
    -95,   // w....b.
    -38,   // .b...b.
    -43,   // bb...b.
    24,    // wb...b.
    0,     // .w...b.
    -49,   // bw...b.
    14,    // ww...b.
    20,    // ..b..b.
    45,    // b.b..b.
    -60,   // w.b..b.
    36,    // .bb..b.
    4,     // bbb..b.
    130,   // wbb..b.
    29,    // .wb..b.
    -34,   // bwb..b.
    39,    // wwb..b.
    -1,    // ..w..b.
    -17,   // b.w..b.
    -33,   // w.w..b.
    10,    // .bw..b.
    -13,   // bbw..b.
    -29,   // wbw..b.
    -26,   // .ww..b.
    32,    // bww..b.
    -86,   // www..b.
    -17,   // ...b.b.
    -18,   // b..b.b.
    -46,   // w..b.b.
    7,     // .b.b.b.
    -87,   // bb.b.b.
    -6,    // wb.b.b.
    -26,   // .w.b.b.
    18,    // bw.b.b.
    -39,   // ww.b.b.
    4,     // ..bb.b.
    -11,   // b.bb.b.
    109,   // w.bb.b.
    41,    // .bbb.b.
    -79,   // bbbb.b.
    99,    // wbbb.b.
    -4,    // .wbb.b.
    -54,   // bwbb.b.
    -26,   // wwbb.b.
    -16,   // ..wb.b.
    -27,   // b.wb.b.
    -53,   // w.wb.b.
    18,    // .bwb.b.
    23,    // bbwb.b.
    22,    // wbwb.b.
    65,    // .wwb.b.
    -61,   // bwwb.b.
    50,    // wwwb.b.
    -23,   // ...w.b.
    -82,   // b..w.b.
    6,     // w..w.b.
    24,    // .b.w.b.
    -68,   // bb.w.b.
    -78,   // wb.w.b.
    26,    // .w.w.b.
    103,   // bw.w.b.
    -108,  // ww.w.b.
    -21,   // ..bw.b.
    36,    // b.bw.b.
    64,    // w.bw.b.
    -14,   // .bbw.b.
    -100,  // bbbw.b.
    -82,   // wbbw.b.
    25,    // .wbw.b.
    -9,    // bwbw.b.
    84,    // wwbw.b.
    55,    // ..ww.b.
    -1,    // b.ww.b.
    29,    // w.ww.b.
    30,    // .bww.b.
    3,     // bbww.b.
    115,   // wbww.b.
    -85,   // .www.b.
    44,    // bwww.b.
    -204,  // wwww.b.
    5,     // ....bb.
    -16,   // b...bb.
    26,    // w...bb.
    36,    // .b..bb.
    7,     // bb..bb.
    -12,   // wb..bb.
    26,    // .w..bb.
    -44,   // bw..bb.
    -79,   // ww..bb.
    -41,   // ..b.bb.
    42,    // b.b.bb.
    17,    // w.b.bb.
    39,    // .bb.bb.
    -32,   // bbb.bb.
    7,     // wbb.bb.
    -101,  // .wb.bb.
    1,     // bwb.bb.
    -23,   // wwb.bb.
    -20,   // ..w.bb.
    4,     // b.w.bb.
    39,    // w.w.bb.
    -82,   // .bw.bb.
    37,    // bbw.bb.
    -109,  // wbw.bb.
    0,     // .ww.bb.
    80,    // bww.bb.
    -114,  // www.bb.
    151,   // ...bbb.
    -45,   // b..bbb.
    68,    // w..bbb.
    41,    // .b.bbb.
    4,     // bb.bbb.
    64,    // wb.bbb.
    85,    // .w.bbb.
    88,    // bw.bbb.
    -5,    // ww.bbb.
    319,   // ..bbbb.
    135,   // b.bbbb.
    96,    // w.bbbb.
    -72,   // .bbbbb.
    -69,   // bbbbbb.
    -9,    // wbbbbb.
    48,    // .wbbbb.
    -53,   // bwbbbb.
    -13,   // wwbbbb.
    72,    // ..wbbb.
    22,    // b.wbbb.
    -76,   // w.wbbb.
    87,    // .bwbbb.
    -130,  // bbwbbb.
    92,    // wbwbbb.
    44,    // .wwbbb.
    18,    // bwwbbb.
    -57,   // wwwbbb.
    14,    // ...wbb.
    67,    // b..wbb.
    16,    // w..wbb.
    -14,   // .b.wbb.
    76,    // bb.wbb.
    20,    // wb.wbb.
    -65,   // .w.wbb.
    -27,   // bw.wbb.
    -25,   // ww.wbb.
    -70,   // ..bwbb.
    -86,   // b.bwbb.
    -99,   // w.bwbb.
    -53,   // .bbwbb.
    -83,   // bbbwbb.
    -71,   // wbbwbb.
    43,    // .wbwbb.
    -52,   // bwbwbb.
    132,   // wwbwbb.
    -41,   // ..wwbb.
    6,     // b.wwbb.
    -24,   // w.wwbb.
    -33,   // .bwwbb.
    -57,   // bbwwbb.
    -16,   // wbwwbb.
    -44,   // .wwwbb.
    72,    // bwwwbb.
    46,    // wwwwbb.
    45,    // ....wb.
    -16,   // b...wb.
    80,    // w...wb.
    10,    // .b..wb.
    -13,   // bb..wb.
    -88,   // wb..wb.
    -29,   // .w..wb.
    -62,   // bw..wb.
    -107,  // ww..wb.
    -20,   // ..b.wb.
    -79,   // b.b.wb.
    -18,   // w.b.wb.
    -82,   // .bb.wb.
    13,    // bbb.wb.
    -60,   // wbb.wb.
    0,     // .wb.wb.
    54,    // bwb.wb.
    6,     // wwb.wb.
    34,    // ..w.wb.
    -39,   // b.w.wb.
    107,   // w.w.wb.
    59,    // .bw.wb.
    -22,   // bbw.wb.
    -7,    // wbw.wb.
    101,   // .ww.wb.
    -72,   // bww.wb.
    9,     // www.wb.
    -64,   // ...bwb.
    28,    // b..bwb.
    88,    // w..bwb.
    18,    // .b.bwb.
    -26,   // bb.bwb.
    -25,   // wb.bwb.
    -25,   // .w.bwb.
    -34,   // bw.bwb.
    -22,   // ww.bwb.
    -44,   // ..bbwb.
    -25,   // b.bbwb.
    -28,   // w.bbwb.
    87,    // .bbbwb.
    -121,  // bbbbwb.
    -20,   // wbbbwb.
    3,     // .wbbwb.
    -125,  // bwbbwb.
    63,    // wwbbwb.
    5,     // ..wbwb.
    -25,   // b.wbwb.
    -11,   // w.wbwb.
    5,     // .bwbwb.
    11,    // bbwbwb.
    -60,   // wbwbwb.
    -43,   // .wwbwb.
    105,   // bwwbwb.
    24,    // wwwbwb.
    -38,   // ...wwb.
    5,     // b..wwb.
    3,     // w..wwb.
    30,    // .b.wwb.
    -27,   // bb.wwb.
    22,    // wb.wwb.
    4,     // .w.wwb.
    81,    // bw.wwb.
    -73,   // ww.wwb.
    95,    // ..bwwb.
    -72,   // b.bwwb.
    -22,   // w.bwwb.
    -33,   // .bbwwb.
    17,    // bbbwwb.
    -102,  // wbbwwb.
    -3,    // .wbwwb.
    -94,   // bwbwwb.
    -32,   // wwbwwb.
    71,    // ..wwwb.
    143,   // b.wwwb.
    -165,  // w.wwwb.
    1,     // .bwwwb.
    74,    // bbwwwb.
    -9,    // wbwwwb.
    -48,   // .wwwwb.
    222,   // bwwwwb.
    -159,  // wwwwwb.
    14,    // .....w.
    95,    // b....w.
    31,    // w....w.
    0,     // .b...w.
    -14,   // bb...w.
    49,    // wb...w.
    38,    // .w...w.
    -24,   // bw...w.
    43,    // ww...w.
    1,     // ..b..w.
    33,    // b.b..w.
    17,    // w.b..w.
    26,    // .bb..w.
    86,    // bbb..w.
    -32,   // wbb..w.
    -10,   // .wb..w.
    29,    // bwb..w.
    13,    // wwb..w.
    -20,   // ..w..w.
    60,    // b.w..w.
    -45,   // w.w..w.
    -29,   // .bw..w.
    -39,   // bbw..w.
    34,    // wbw..w.
    -36,   // .ww..w.
    -130,  // bww..w.
    -4,    // www..w.
    23,    // ...b.w.
    -6,    // b..b.w.
    82,    // w..b.w.
    -26,   // .b.b.w.
    108,   // bb.b.w.
    -103,  // wb.b.w.
    -24,   // .w.b.w.
    78,    // bw.b.w.
    68,    // ww.b.w.
    -55,   // ..bb.w.
    -29,   // b.bb.w.
    1,     // w.bb.w.
    85,    // .bbb.w.
    204,   // bbbb.w.
    -44,   // wbbb.w.
    -30,   // .wbb.w.
    -115,  // bwbb.w.
    -3,    // wwbb.w.
    21,    // ..wb.w.
    -64,   // b.wb.w.
    -36,   // w.wb.w.
    -25,   // .bwb.w.
    -84,   // bbwb.w.
    9,     // wbwb.w.
    14,    // .wwb.w.
    82,    // bwwb.w.
    100,   // wwwb.w.
    17,    // ...w.w.
    46,    // b..w.w.
    18,    // w..w.w.
    26,    // .b.w.w.
    39,    // bb.w.w.
    -18,   // wb.w.w.
    -7,    // .w.w.w.
    6,     // bw.w.w.
    87,    // ww.w.w.
    16,    // ..bw.w.
    53,    // b.bw.w.
    27,    // w.bw.w.
    -65,   // .bbw.w.
    -50,   // bbbw.w.
    61,    // wbbw.w.
    -18,   // .wbw.w.
    -22,   // bwbw.w.
    -23,   // wwbw.w.
    -4,    // ..ww.w.
    -109,  // b.ww.w.
    11,    // w.ww.w.
    4,     // .bww.w.
    26,    // bbww.w.
    54,    // wbww.w.
    -41,   // .www.w.
    -99,   // bwww.w.
    79,    // wwww.w.
    -45,   // ....bw.
    -80,   // b...bw.
    16,    // w...bw.
    29,    // .b..bw.
    107,   // bb..bw.
    62,    // wb..bw.
    -10,   // .w..bw.
    88,    // bw..bw.
    13,    // ww..bw.
    -34,   // ..b.bw.
    -107,  // b.b.bw.
    39,    // w.b.bw.
    -101,  // .bb.bw.
    -9,    // bbb.bw.
    72,    // wbb.bw.
    -59,   // .wb.bw.
    7,     // bwb.bw.
    22,    // wwb.bw.
    20,    // ..w.bw.
    18,    // b.w.bw.
    79,    // w.w.bw.
    0,     // .bw.bw.
    -6,    // bbw.bw.
    -54,   // wbw.bw.
    82,    // .ww.bw.
    60,    // bww.bw.
    -13,   // www.bw.
    38,    // ...bbw.
    -3,    // b..bbw.
    -5,    // w..bbw.
    -4,    // .b.bbw.
    73,    // bb.bbw.
    -81,   // wb.bbw.
    -30,   // .w.bbw.
    -22,   // bw.bbw.
    27,    // ww.bbw.
    -71,   // ..bbbw.
    165,   // b.bbbw.
    -143,  // w.bbbw.
    48,    // .bbbbw.
    159,   // bbbbbw.
    -222,  // wbbbbw.
    -1,    // .wbbbw.
    9,     // bwbbbw.
    -74,   // wwbbbw.
    -95,   // ..wbbw.
    22,    // b.wbbw.
    72,    // w.wbbw.
    3,     // .bwbbw.
    32,    // bbwbbw.
    94,    // wbwbbw.
    33,    // .wwbbw.
    102,   // bwwbbw.
    -17,   // wwwbbw.
    64,    // ...wbw.
    -88,   // b..wbw.
    -28,   // w..wbw.
    25,    // .b.wbw.
    22,    // bb.wbw.
    34,    // wb.wbw.
    -18,   // .w.wbw.
    25,    // bw.wbw.
    26,    // ww.wbw.
    -5,    // ..bwbw.
    11,    // b.bwbw.
    25,    // w.bwbw.
    43,    // .bbwbw.
    -24,   // bbbwbw.
    -105,  // wbbwbw.
    -5,    // .wbwbw.
    60,    // bwbwbw.
    -11,   // wwbwbw.
    44,    // ..wwbw.
    28,    // b.wwbw.
    25,    // w.wwbw.
    -3,    // .bwwbw.
    -63,   // bbwwbw.
    125,   // wbwwbw.
    -87,   // .wwwbw.
    20,    // bwwwbw.
    121,   // wwwwbw.
    -5,    // ....ww.
    -26,   // b...ww.
    16,    // w...ww.
    -26,   // .b..ww.
    79,    // bb..ww.
    44,    // wb..ww.
    -36,   // .w..ww.
    12,    // bw..ww.
    -7,    // ww..ww.
    20,    // ..b.ww.
    -39,   // b.b.ww.
    -4,    // w.b.ww.
    0,     // .bb.ww.
    114,   // bbb.ww.
    -80,   // wbb.ww.
    82,    // .wb.ww.
    109,   // bwb.ww.
    -37,   // wwb.ww.
    41,    // ..w.ww.
    -17,   // b.w.ww.
    -42,   // w.w.ww.
    101,   // .bw.ww.
    23,    // bbw.ww.
    -1,    // wbw.ww.
    -39,   // .ww.ww.
    -7,    // bww.ww.
    32,    // www.ww.
    -14,   // ...bww.
    -16,   // b..bww.
    -67,   // w..bww.
    65,    // .b.bww.
    25,    // bb.bww.
    27,    // wb.bww.
    14,    // .w.bww.
    -20,   // bw.bww.
    -76,   // ww.bww.
    41,    // ..bbww.
    24,    // b.bbww.
    -6,    // w.bbww.
    44,    // .bbbww.
    -46,   // bbbbww.
    -72,   // wbbbww.
    33,    // .wbbww.
    16,    // bwbbww.
    57,    // wwbbww.
    70,    // ..wbww.
    99,    // b.wbww.
    86,    // w.wbww.
    -43,   // .bwbww.
    -132,  // bbwbww.
    52,    // wbwbww.
    53,    // .wwbww.
    71,    // bwwbww.
    83,    // wwwbww.
    -151,  // ...www.
    -68,   // b..www.
    45,    // w..www.
    -85,   // .b.www.
    5,     // bb.www.
    -88,   // wb.www.
    -41,   // .w.www.
    -64,   // bw.www.
    -4,    // ww.www.
    -72,   // ..bwww.
    76,    // b.bwww.
    -22,   // w.bwww.
    -44,   // .bbwww.
    57,    // bbbwww.
    -18,   // wbbwww.
    -87,   // .wbwww.
    -92,   // bwbwww.
    130,   // wwbwww.
    -319,  // ..wwww.
    -96,   // b.wwww.
    -135,  // w.wwww.
    -48,   // .bwwww.
    13,    // bbwwww.
    53,    // wbwwww.
    72,    // .wwwww.
    9,     // bwwwww.
    69,    // wwwwww.
    -2,    // ......b
    36,    // b.....b
    0,     // w.....b
    -31,   // .b....b
    -28,   // bb....b
    2,     // wb....b
    95,    // .w....b
    45,    // bw....b
    -29,   // ww....b
    35,    // ..b...b
    8,     // b.b...b
    -87,   // w.b...b
    -16,   // .bb...b
    -119,  // bbb...b
    -105,  // wbb...b
    -80,   // .wb...b
    2,     // bwb...b
    15,    // wwb...b
    69,    // ..w...b
    9,     // b.w...b
    82,    // w.w...b
    -16,   // .bw...b
    -39,   // bbw...b
    -34,   // wbw...b
    -26,   // .ww...b
    -41,   // bww...b
    -111,  // www...b
    -31,   // ...b..b
    -54,   // b..b..b
    37,    // w..b..b
    -18,   // .b.b..b
    -25,   // bb.b..b
    -79,   // wb.b..b
    -6,    // .w.b..b
    -17,   // bw.b..b
    109,   // ww.b..b
    5,     // ..bb..b
    -52,   // b.bb..b
    -10,   // w.bb..b
    -45,   // .bbb..b
    -9,    // bbbb..b
    -99,   // wbbb..b
    -3,    // .wbb..b
    115,   // bwbb..b
    -52,   // wwbb..b
    -68,   // ..wb..b
    -59,   // b.wb..b
    2,     // w.wb..b
    28,    // .bwb..b
    -95,   // bbwb..b
    -66,   // wbwb..b
    -16,   // .wwb..b
    -47,   // bwwb..b
    31,    // wwwb..b
    18,    // ...w..b
    -38,   // b..w..b
    -37,   // w..w..b
    -82,   // .b.w..b
    60,    // bb.w..b
    -61,   // wb.w..b
    46,    // .w.w..b
    -86,   // bw.w..b
    59,    // ww.w..b
    90,    // ..bw..b
    61,    // b.bw..b
    17,    // w.bw..b
    67,    // .bbw..b
    65,    // bbbw..b
    -38,   // wbbw..b
    -88,   // .wbw..b
    -41,   // bwbw..b
    0,     // wwbw..b
    41,    // ..ww..b
    -10,   // b.ww..b
    65,    // w.ww..b
    5,     // .bww..b
    -62,   // bbww..b
    99,    // wbww..b
    -68,   // .www..b
    -20,   // bwww..b
    -93,   // wwww..b
    69,    // ....b.b
    8,     // b...b.b
    -82,   // w...b.b
    45,    // .b..b.b
    -89,   // bb..b.b
    148,   // wb..b.b
    33,    // .w..b.b
    47,    // bw..b.b
    31,    // ww..b.b
    -23,   // ..b.b.b
    57,    // b.b.b.b
    75,    // w.b.b.b
    42,    // .bb.b.b
    30,    // bbb.b.b
    1,     // wbb.b.b
    -107,  // .wb.b.b
    7,     // bwb.b.b
    -16,   // wwb.b.b
    52,    // ..w.b.b
    25,    // b.w.b.b
    0,     // w.w.b.b
    -79,   // .bw.b.b
    50,    // bbw.b.b
    29,    // wbw.b.b
    -39,   // .ww.b.b
    150,   // bww.b.b
    19,    // www.b.b
    87,    // ...bb.b
    -52,   // b..bb.b
    -65,   // w..bb.b
    -11,   // .b.bb.b
    -35,   // bb.bb.b
    -59,   // wb.bb.b
    -29,   // .w.bb.b
    -32,   // bw.bb.b
    -8,    // ww.bb.b
    104,   // ..bbb.b
    62,    // b.bbb.b
    -21,   // w.bbb.b
    135,   // .bbbb.b
    -80,   // bbbbb.b
    -47,   // wbbbb.b
    165,   // .wbbb.b
    -79,   // bwbbb.b
    25,    // wwbbb.b
    -93,   // ..wbb.b
    -14,   // b.wbb.b
    96,    // w.wbb.b
    -25,   // .bwbb.b
    -43,   // bbwbb.b
    27,    // wbwbb.b
    24,    // .wwbb.b
    -46,   // bwwbb.b
    91,    // wwwbb.b
    62,    // ...wb.b
    61,    // b..wb.b
    -2,    // w..wb.b
    36,    // .b.wb.b
    -19,   // bb.wb.b
    3,     // wb.wb.b
    53,    // .w.wb.b
    27,    // bw.wb.b
    55,    // ww.wb.b
    13,    // ..bwb.b
    13,    // b.bwb.b
    -14,   // w.bwb.b
    -86,   // .bbwb.b
    -54,   // bbbwb.b
    -23,   // wbbwb.b
    11,    // .wbwb.b
    30,    // bwbwb.b
    103,   // wwbwb.b
    -1,    // ..wwb.b
    -32,   // b.wwb.b
    -96,   // w.wwb.b
    -72,   // .bwwb.b
    -38,   // bbwwb.b
    40,    // wbwwb.b
    76,    // .wwwb.b
    -42,   // bwwwb.b
    10,    // wwwwb.b
    11,    // ....w.b
    9,     // b...w.b
    87,    // w...w.b
    -17,   // .b..w.b
    -9,    // bb..w.b
    111,   // wb..w.b
    60,    // .w..w.b
    74,    // bw..w.b
    -18,   // ww..w.b
    -22,   // ..b.w.b
    25,    // b.b.w.b
    0,     // w.b.w.b
    4,     // .bb.w.b
    -22,   // bbb.w.b
    -21,   // wbb.w.b
    18,    // .wb.w.b
    55,    // bwb.w.b
    -8,    // wwb.w.b
    41,    // ..w.w.b
    84,    // b.w.w.b
    -75,   // w.w.w.b
    -39,   // .bw.w.b
    -99,   // bbw.w.b
    75,    // wbw.w.b
    -17,   // .ww.w.b
    45,    // bww.w.b
    -7,    // www.w.b
    77,    // ...bw.b
    -59,   // b..bw.b
    -17,   // w..bw.b
    -27,   // .b.bw.b
    39,    // bb.bw.b
    -11,   // wb.bw.b
    -64,   // .w.bw.b
    30,    // bw.bw.b
    -28,   // ww.bw.b
    -53,   // ..bbw.b
    -14,   // b.bbw.b
    30,    // w.bbw.b
    22,    // .bbbw.b
    81,    // bbbbw.b
    -16,   // wbbbw.b
    22,    // .wbbw.b
    78,    // bwbbw.b
    -18,   // wwbbw.b
    22,    // ..wbw.b
    -45,   // b.wbw.b
    14,    // w.wbw.b
    -25,   // .bwbw.b
    -12,   // bbwbw.b
    -54,   // wbwbw.b
    99,    // .wwbw.b
    70,    // bwwbw.b
    -72,   // wwwbw.b
    30,    // ...ww.b
    -10,   // b..ww.b
    10,    // w..ww.b
    -1,    // .b.ww.b
    18,    // bb.ww.b
    106,   // wb.ww.b
    -109,  // .w.ww.b
    -15,   // bw.ww.b
    8,     // ww.ww.b
    57,    // ..bww.b
    -32,   // b.bww.b
    -30,   // w.bww.b
    6,     // .bbww.b
    106,   // bbbww.b
    44,    // wbbww.b
    28,    // .wbww.b
    88,    // bwbww.b
    -73,   // wwbww.b
    18,    // ..www.b
    -55,   // b.www.b
    21,    // w.www.b
    143,   // .bwww.b
    -73,   // bbwww.b
    -30,   // wbwww.b
    -96,   // .wwww.b
    7,     // bwwww.b
    -11,   // wwwww.b
    -6,    // .....bb
    -28,   // b....bb
    29,    // w....bb
    -43,   // .b...bb
    6,     // bb...bb
    -46,   // wb...bb
    -14,   // .w...bb
    -5,    // bw...bb
    0,     // ww...bb
    -26,   // ..b..bb
    -89,   // b.b..bb
    18,    // w.b..bb
    7,     // .bb..bb
    122,   // bbb..bb
    -48,   // wbb..bb
    107,   // .wb..bb
    -64,   // bwb..bb
    32,    // wwb..bb
    -58,   // ..w..bb
    -9,    // b.w..bb
    -31,   // w.w..bb
    -13,   // .bw..bb
    -15,   // bbw..bb
    -24,   // wbw..bb
    79,    // .ww..bb
    -15,   // bww..bb
    -31,   // www..bb
    104,   // ...b.bb
    -25,   // b..b.bb
    -59,   // w..b.bb
    -87,   // .b.b.bb
    21,    // bb.b.bb
    69,    // wb.b.bb
    108,   // .w.b.bb
    -49,   // bw.b.bb
    31,    // ww.b.bb
    42,    // ..bb.bb
    -35,   // b.bb.bb
    -8,    // w.bb.bb
    4,     // .bbb.bb
    -51,   // bbbb.bb
    -14,   // wbbb.bb
    73,    // .wbb.bb
    39,    // bwbb.bb
    -119,  // wwbb.bb
    -28,   // ..wb.bb
    39,    // b.wb.bb
    -55,   // w.wb.bb
    -26,   // .bwb.bb
    -8,    // bbwb.bb
    -47,   // wbwb.bb
    25,    // .wwb.bb
    35,    // bwwb.bb
    41,    // wwwb.bb
    34,    // ...w.bb
    60,    // b..w.bb
    -109,  // w..w.bb
    -68,   // .b.w.bb
    90,    // bb.w.bb
    54,    // wb.w.bb
    39,    // .w.w.bb
    52,    // bw.w.bb
    -31,   // ww.w.bb
    -37,   // ..bw.bb
    -19,   // b.bw.bb
    28,    // w.bw.bb
    76,    // .bbw.bb
    63,    // bbbw.bb
    77,    // wbbw.bb
    22,    // .wbw.bb
    194,   // bwbw.bb
    77,    // wwbw.bb
    41,    // ..ww.bb
    18,    // b.ww.bb
    8,     // w.ww.bb
    -27,   // .bww.bb
    -19,   // bbww.bb
    20,    // wbww.bb
    5,     // .www.bb
    22,    // bwww.bb
    -47,   // wwww.bb
    50,    // ....bbb
    -119,  // b...bbb
    111,   // w...bbb
    4,     // .b..bbb
    122,   // bb..bbb
    -22,   // wb..bbb
    86,    // .w..bbb
    22,    // bw..bbb
    31,    // ww..bbb
    126,   // ..b.bbb
    30,    // b.b.bbb
    7,     // w.b.bbb
    -32,   // .bb.bbb
    39,    // bbb.bbb
    -29,   // wbb.bbb
    -9,    // .wb.bbb
    -36,   // bwb.bbb
    -111,  // wwb.bbb
    50,    // ..w.bbb
    -22,   // b.w.bbb
    -19,   // w.w.bbb
    13,    // .bw.bbb
    70,    // bbw.bbb
    -52,   // wbw.bbb
    114,   // .ww.bbb
    -27,   // bww.bbb
    0,     // www.bbb
    486,   // ...bbbb
    -9,    // b..bbbb
    93,    // w..bbbb
    -79,   // .b.bbbb
    -51,   // bb.bbbb
    80,    // wb.bbbb
    204,   // .w.bbbb
    95,    // bw.bbbb
    47,    // ww.bbbb
    67,    // ..bbbbb
    -80,   // b.bbbbb
    11,    // w.bbbbb
    -69,   // .bbbbbb
    -36,   // bbbbbbb
    -24,   // wbbbbbb
    159,   // .wbbbbb
    -32,   // bwbbbbb
    115,   // wwbbbbb
    71,    // ..wbbbb
    81,    // b.wbbbb
    -10,   // w.wbbbb
    -121,  // .bwbbbb
    -23,   // bbwbbbb
    74,    // wbwbbbb
    -46,   // .wwbbbb
    6,     // bwwbbbb
    -93,   // wwwbbbb
    85,    // ...wbbb
    65,    // b..wbbb
    -31,   // w..wbbb
    -100,  // .b.wbbb
    63,    // bb.wbbb
    -25,   // wb.wbbb
    -50,   // .w.wbbb
    31,    // bw.wbbb
    -41,   // ww.wbbb
    -167,  // ..bwbbb
    -54,   // b.bwbbb
    72,    // w.bwbbb
    -83,   // .bbwbbb
    14,    // bbbwbbb
    -208,  // wbbwbbb
    -24,   // .wbwbbb
    28,    // bwbwbbb
    -39,   // wwbwbbb
    96,    // ..wwbbb
    106,   // b.wwbbb
    -91,   // w.wwbbb
    17,    // .bwwbbb
    55,    // bbwwbbb
    -117,  // wbwwbbb
    57,    // .wwwbbb
    44,    // bwwwbbb
    93,    // wwwwbbb
    -121,  // ....wbb
    -39,   // b...wbb
    -15,   // w...wbb
    -13,   // .b..wbb
    -15,   // bb..wbb
    -11,   // wb..wbb
    -39,   // .w..wbb
    59,    // bw..wbb
    -32,   // ww..wbb
    -57,   // ..b.wbb
    50,    // b.b.wbb
    8,     // w.b.wbb
    37,    // .bb.wbb
    70,    // bbb.wbb
    13,    // wbb.wbb
    -6,    // .wb.wbb
    16,    // bwb.wbb
    0,     // wwb.wbb
    38,    // ..w.wbb
    -99,   // b.w.wbb
    16,    // w.w.wbb
    -22,   // .bw.wbb
    -91,   // bbw.wbb
    -79,   // wbw.wbb
    23,    // .ww.wbb
    -14,   // bww.wbb
    111,   // www.wbb
    -98,   // ...bwbb
    -95,   // b..bwbb
    0,     // w..bwbb
    23,    // .b.bwbb
    -8,    // bb.bwbb
    74,    // wb.bwbb
    -84,   // .w.bwbb
    -33,   // bw.bwbb
    -77,   // ww.bwbb
    -18,   // ..bbwbb
    -43,   // b.bbwbb
    73,    // w.bbwbb
    -130,  // .bbbwbb
    -23,   // bbbbwbb
    -9,    // wbbbwbb
    32,    // .wbbwbb
    1,     // bwbbwbb
    58,    // wwbbwbb
    6,     // ..wbwbb
    -12,   // b.wbwbb
    -103,  // w.wbwbb
    11,    // .bwbwbb
    29,    // bbwbwbb
    107,   // wbwbwbb
    -132,  // .wwbwbb
    46,    // bwwbwbb
    39,    // wwwbwbb
    -3,    // ...wwbb
    -62,   // b..wwbb
    52,    // w..wwbb
    3,     // .b.wwbb
    -19,   // bb.wwbb
    -13,   // wb.wwbb
    26,    // .w.wwbb
    94,    // bw.wwbb
    119,   // ww.wwbb
    -3,    // ..bwwbb
    -38,   // b.bwwbb
    18,    // w.bwwbb
    -57,   // .bbwwbb
    55,    // bbbwwbb
    -11,   // wbbwwbb
    -63,   // .wbwwbb
    -30,   // bwbwwbb
    -58,   // wwbwwbb
    -3,    // ..wwwbb
    -73,   // b.wwwbb
    -25,   // w.wwwbb
    74,    // .bwwwbb
    1,     // bbwwwbb
    -5,    // wbwwwbb
    13,    // .wwwwbb
    -22,   // bwwwwbb
    -115,  // wwwwwbb
    -10,   // .....wb
    45,    // b....wb
    -2,    // w....wb
    -49,   // .b...wb
    -5,    // bb...wb
    0,     // wb...wb
    -24,   // .w...wb
    -139,  // bw...wb
    46,    // ww...wb
    -49,   // ..b..wb
    47,    // b.b..wb
    -111,  // w.b..wb
    -44,   // .bb..wb
    22,    // bbb..wb
    25,    // wbb..wb
    88,    // .wb..wb
    -87,   // bwb..wb
    11,    // wwb..wb
    -14,   // ..w..wb
    74,    // b.w..wb
    -148,  // w.w..wb
    -62,   // .bw..wb
    59,    // bbw..wb
    13,    // wbw..wb
    12,    // .ww..wb
    -50,   // bww..wb
    22,    // www..wb
    -14,   // ...b.wb
    -17,   // b..b.wb
    61,    // w..b.wb
    18,    // .b.b.wb
    -49,   // bb.b.wb
    -71,   // wb.b.wb
    78,    // .w.b.wb
    29,    // bw.b.wb
    -54,   // ww.b.wb
    17,    // ..bb.wb
    -32,   // b.bb.wb
    -106,  // w.bb.wb
    88,    // .bbb.wb
    95,    // bbbb.wb
    -9,    // wbbb.wb
    -22,   // .wbb.wb
    -39,   // bwbb.wb
    13,    // wwbb.wb
    -1,    // ..wb.wb
    30,    // b.wb.wb
    -3,    // w.wb.wb
    -34,   // .bwb.wb
    -33,   // bbwb.wb
    -9,    // wbwb.wb
    -20,   // .wwb.wb
    82,    // bwwb.wb
    25,    // wwwb.wb
    79,    // ...w.wb
    -86,   // b..w.wb
    79,    // w..w.wb
    103,   // .b.w.wb
    52,    // bb.w.wb
    71,    // wb.w.wb
    6,     // .w.w.wb
    33,    // bw.w.wb
    -69,   // ww.w.wb
    40,    // ..bw.wb
    27,    // b.bw.wb
    11,    // w.bw.wb
    -27,   // .bbw.wb
    31,    // bbbw.wb
    -32,   // wbbw.wb
    25,    // .wbw.wb
    42,    // bwbw.wb
    -74,   // wwbw.wb
    -14,   // ..ww.wb
    -15,   // b.ww.wb
    59,    // w.ww.wb
    81,    // .bww.wb
    94,    // bbww.wb
    78,    // wbww.wb
    -64,   // .www.wb
    -74,   // bwww.wb
    -80,   // wwww.wb
    30,    // ....bwb
    2,     // b...bwb
    34,    // w...bwb
    -34,   // .b..bwb
    -64,   // bb..bwb
    -13,   // wb..bwb
    29,    // .w..bwb
    -87,   // bw..bwb
    24,    // ww..bwb
    -64,   // ..b.bwb
    7,     // b.b.bwb
    -75,   // w.b.bwb
    1,     // .bb.bwb
    -36,   // bbb.bwb
    -23,   // wbb.bwb
    7,     // .wb.bwb
    33,    // bwb.bwb
    79,    // wwb.bwb
    61,    // ..w.bwb
    55,    // b.w.bwb
    -29,   // w.w.bwb
    54,    // .bw.bwb
    16,    // bbw.bwb
    0,     // wbw.bwb
    109,   // .ww.bwb
    92,    // bww.bwb
    52,    // www.bwb
    -46,   // ...bbwb
    115,   // b..bbwb
    -99,   // w..bbwb
    -54,   // .b.bbwb
    39,    // bb.bbwb
    -78,   // wb.bbwb
    -115,  // .w.bbwb
    -39,   // bw.bbwb
    -20,   // ww.bbwb
    -44,   // ..bbbwb
    -79,   // b.bbbwb
    30,    // w.bbbwb
    -53,   // .bbbbwb
    -32,   // bbbbbwb
    -100,  // wbbbbwb
    9,     // .wbbbwb
    58,    // bwbbbwb
    5,     // wwbbbwb
    22,    // ..wbbwb
    78,    // b.wbbwb
    -40,   // w.wbbwb
    -125,  // .bwbbwb
    1,     // bbwbbwb
    68,    // wbwbbwb
    16,    // .wwbbwb
    14,    // bwwbbwb
    117,   // wwwbbwb
    0,     // ...wbwb
    -41,   // b..wbwb
    66,    // w..wbwb
    -9,    // .b.wbwb
    194,   // bb.wbwb
    9,     // wb.wbwb
    -22,   // .w.wbwb
    42,    // bw.wbwb
    47,    // ww.wbwb
    -39,   // ..bwbwb
    30,    // b.bwbwb
    54,    // w.bwbwb
    -52,   // .bbwbwb
    28,    // bbbwbwb
    -25,   // wbbwbwb
    60,    // .wbwbwb
    -48,   // bwbwbwb
    -107,  // wwbwbwb
    -78,   // ..wwbwb
    88,    // b.wwbwb
    -27,   // w.wwbwb
    -94,   // .bwwbwb
    -30,   // bbwwbwb
    -68,   // wbwwbwb
    -92,   // .wwwbwb
    -103,  // bwwwbwb
    -74,   // wwwwbwb
    139,   // ....wwb
    -41,   // b...wwb
    105,   // w...wwb
    32,    // .b..wwb
    -15,   // bb..wwb
    -25,   // wb..wwb
    -130,  // .w..wwb
    -50,   // bw..wwb
    48,    // ww..wwb
    -47,   // ..b.wwb
    150,   // b.b.wwb
    21,    // w.b.wwb
    80,    // .bb.wwb
    -27,   // bbb.wwb
    0,     // wbb.wwb
    60,    // .wb.wwb
    92,    // bwb.wwb
    -13,   // wwb.wwb
    110,   // ..w.wwb
    45,    // b.w.wwb
    -1,    // w.w.wwb
    -72,   // .bw.wwb
    -14,   // bbw.wwb
    23,    // wbw.wwb
    -7,    // .ww.wwb
    -16,   // bww.wwb
    29,    // www.wwb
    39,    // ...bwwb
    -47,   // b..bwwb
    38,    // w..bwwb
    -61,   // .b.bwwb
    35,    // bb.bwwb
    32,    // wb.bwwb
    82,    // .w.bwwb
    82,    // bw.bwwb
    -77,   // ww.bwwb
    -96,   // ..bbwwb
    -46,   // b.bbwwb
    -44,   // w.bbwwb
    18,    // .bbbwwb
    6,     // bbbbwwb
    19,    // wbbbwwb
    102,   // .wbbwwb
    14,    // bwbbwwb
    11,    // wwbbwwb
    -38,   // ..wbwwb
    70,    // b.wbwwb
    23,    // w.wbwwb
    105,   // .bwbwwb
    46,    // bbwbwwb
    25,    // wbwbwwb
    71,    // .wwbwwb
    -14,   // bwwbwwb
    208,   // wwwbwwb
    111,   // ...wwwb
    -20,   // b..wwwb
    99,    // w..wwwb
    44,    // .b.wwwb
    22,    // bb.wwwb
    9,     // wb.wwwb
    -99,   // .w.wwwb
    -74,   // bw.wwwb
    14,    // ww.wwwb
    37,    // ..bwwwb
    -42,   // b.bwwwb
    16,    // w.bwwwb
    72,    // .bbwwwb
    44,    // bbbwwwb
    -19,   // wbbwwwb
    20,    // .wbwwwb
    -103,  // bwbwwwb
    9,     // wwbwwwb
    -11,   // ..wwwwb
    7,     // b.wwwwb
    47,    // w.wwwwb
    222,   // .bwwwwb
    -22,   // bbwwwwb
    100,   // wbwwwwb
    9,     // .wwwwwb
    66,    // bwwwwwb
    24,    // wwwwwwb
    2,     // ......w
    0,     // b.....w
    -36,   // w.....w
    -95,   // .b....w
    29,    // bb....w
    -45,   // wb....w
    31,    // .w....w
    -2,    // bw....w
    28,    // ww....w
    -69,   // ..b...w
    -82,   // b.b...w
    -9,    // w.b...w
    26,    // .bb...w
    111,   // bbb...w
    41,    // wbb...w
    16,    // .wb...w
    34,    // bwb...w
    39,    // wwb...w
    -35,   // ..w...w
    87,    // b.w...w
    -8,    // w.w...w
    80,    // .bw...w
    -15,   // bbw...w
    -2,    // wbw...w
    16,    // .ww...w
    105,   // bww...w
    119,   // www...w
    -18,   // ...b..w
    37,    // b..b..w
    38,    // w..b..w
    -46,   // .b.b..w
    -59,   // bb.b..w
    86,    // wb.b..w
    82,    // .w.b..w
    61,    // bw.b..w
    -60,   // ww.b..w
    -41,   // ..bb..w
    -65,   // b.bb..w
    10,    // w.bb..w
    68,    // .bbb..w
    93,    // bbbb..w
    20,    // wbbb..w
    -5,    // .wbb..w
    -99,   // bwbb..w
    62,    // wwbb..w
    -90,   // ..wb..w
    -17,   // b.wb..w
    -61,   // w.wb..w
    88,    // .bwb..w
    0,     // bbwb..w
    41,    // wbwb..w
    -67,   // .wwb..w
    38,    // bwwb..w
    -65,   // wwwb..w
    31,    // ...w..w
    -37,   // b..w..w
    54,    // w..w..w
    6,     // .b.w..w
    -109,  // bb.w..w
    17,    // wb.w..w
    18,    // .w.w..w
    79,    // bw.w..w
    25,    // ww.w..w
    68,    // ..bw..w
    -2,    // b.bw..w
    59,    // w.bw..w
    16,    // .bbw..w
    -31,   // bbbw..w
    47,    // wbbw..w
    -28,   // .wbw..w
    66,    // bwbw..w
    95,    // wwbw..w
    -5,    // ..ww..w
    10,    // b.ww..w
    52,    // w.ww..w
    3,     // .bww..w
    52,    // bbww..w
    -115,  // wbww..w
    45,    // .www..w
    99,    // bwww..w
    9,     // wwww..w
    -11,   // ....b.w
    -87,   // b...b.w
    -9,    // w...b.w
    -60,   // .b..b.w
    18,    // bb..b.w
    -74,   // wb..b.w
    17,    // .w..b.w
    -111,  // bw..b.w
    9,     // ww..b.w
    -41,   // ..b.b.w
    75,    // b.b.b.w
    -84,   // w.b.b.w
    17,    // .bb.b.w
    7,     // bbb.b.w
    -45,   // wbb.b.w
    39,    // .wb.b.w
    -75,   // bwb.b.w
    99,    // wwb.b.w
    22,    // ..w.b.w
    0,     // b.w.b.w
    -25,   // w.w.b.w
    -18,   // .bw.b.w
    8,     // bbw.b.w
    -55,   // wbw.b.w
    -4,    // .ww.b.w
    21,    // bww.b.w
    22,    // www.b.w
    -30,   // ...bb.w
    -10,   // b..bb.w
    10,    // w..bb.w
    109,   // .b.bb.w
    -8,    // bb.bb.w
    15,    // wb.bb.w
    1,     // .w.bb.w
    -106,  // bw.bb.w
    -18,   // ww.bb.w
    -18,   // ..bbb.w
    -21,   // b.bbb.w
    55,    // w.bbb.w
    96,    // .bbbb.w
    11,    // bbbbb.w
    -7,    // wbbbb.w
    -143,  // .wbbb.w
    30,    // bwbbb.w
    73,    // wwbbb.w
    -57,   // ..wbb.w
    30,    // b.wbb.w
    32,    // w.wbb.w
    -28,   // .bwbb.w
    73,    // bbwbb.w
    -88,   // wbwbb.w
    -6,    // .wwbb.w
    -44,   // bwwbb.w
    -106,  // wwwbb.w
    -77,   // ...wb.w
    17,    // b..wb.w
    59,    // w..wb.w
    64,    // .b.wb.w
    28,    // bb.wb.w
    -30,   // wb.wb.w
    27,    // .w.wb.w
    11,    // bw.wb.w
    -39,   // ww.wb.w
    -22,   // ..bwb.w
    -14,   // b.bwb.w
    45,    // w.bwb.w
    -99,   // .bbwb.w
    72,    // bbbwb.w
    -70,   // wbbwb.w
    25,    // .wbwb.w
    54,    // bwbwb.w
    12,    // wwbwb.w
    53,    // ..wwb.w
    -30,   // b.wwb.w
    14,    // w.wwb.w
    -22,   // .bwwb.w
    18,    // bbwwb.w
    -78,   // wbwwb.w
    -22,   // .wwwb.w
    16,    // bwwwb.w
    -81,   // wwwwb.w
    -69,   // ....w.w
    82,    // b...w.w
    -8,    // w...w.w
    -33,   // .b..w.w
    -31,   // bb..w.w
    -47,   // wb..w.w
    -45,   // .w..w.w
    -148,  // bw..w.w
    89,    // ww..w.w
    -52,   // ..b.w.w
    0,     // b.b.w.w
    -25,   // w.b.w.w
    39,    // .bb.w.w
    -19,   // bbb.w.w
    -150,  // wbb.w.w
    79,    // .wb.w.w
    -29,   // bwb.w.w
    -50,   // wwb.w.w
    23,    // ..w.w.w
    -75,   // b.w.w.w
    -57,   // w.w.w.w
    107,   // .bw.w.w
    16,    // bbw.w.w
    -7,    // wbw.w.w
    -42,   // .ww.w.w
    -1,    // bww.w.w
    -30,   // www.w.w
    -62,   // ...bw.w
    2,     // b..bw.w
    -61,   // w..bw.w
    -53,   // .b.bw.w
    -55,   // bb.bw.w
    -27,   // wb.bw.w
    -36,   // .w.bw.w
    -3,    // bw.bw.w
    19,    // ww.bw.w
    1,     // ..bbw.w
    96,    // b.bbw.w
    32,    // w.bbw.w
    -76,   // .bbbw.w
    -10,   // bbbbw.w
    42,    // wbbbw.w
    72,    // .wbbw.w
    -40,   // bwbbw.w
    38,    // wwbbw.w
    -13,   // ..wbw.w
    14,    // b.wbw.w
    -13,   // w.wbw.w
    -11,   // .bwbw.w
    -103,  // bbwbw.w
    -30,   // wbwbw.w
    86,    // .wwbw.w
    23,    // bwwbw.w
    54,    // wwwbw.w
    -87,   // ...ww.w
    65,    // b..ww.w
    52,    // w..ww.w
    29,    // .b.ww.w
    8,     // bb.ww.w
    32,    // wb.ww.w
    11,    // .w.ww.w
    59,    // bw.ww.w
    35,    // ww.ww.w
    93,    // ..bww.w
    -96,   // b.bww.w
    14,    // w.bww.w
    -24,   // .bbww.w
    -91,   // bbbww.w
    46,    // wbbww.w
    25,    // .wbww.w
    -27,   // bwbww.w
    43,    // wwbww.w
    -104,  // ..www.w
    21,    // b.www.w
    -62,   // w.www.w
    -165,  // .bwww.w
    -25,   // bbwww.w
    79,    // wbwww.w
    -135,  // .wwww.w
    47,    // bwwww.w
    80,    // wwwww.w
    10,    // .....bw
    2,     // b....bw
    -45,   // w....bw
    24,    // .b...bw
    -46,   // bb...bw
    139,   // wb...bw
    49,    // .w...bw
    0,     // bw...bw
    5,     // ww...bw
    14,    // ..b..bw
    148,   // b.b..bw
    -74,   // w.b..bw
    -12,   // .bb..bw
    -22,   // bbb..bw
    50,    // wbb..bw
    62,    // .wb..bw
    -13,   // bwb..bw
    -59,   // wwb..bw
    49,    // ..w..bw
    111,   // b.w..bw
    -47,   // w.w..bw
    -88,   // .bw..bw
    -11,   // bbw..bw
    87,    // wbw..bw
    44,    // .ww..bw
    -25,   // bww..bw
    -22,   // www..bw
    -79,   // ...b.bw
    -79,   // b..b.bw
    86,    // w..b.bw
    -6,    // .b.b.bw
    69,    // bb.b.bw
    -33,   // wb.b.bw
    -103,  // .w.b.bw
    -71,   // bw.b.bw
    -52,   // ww.b.bw
    14,    // ..bb.bw
    -59,   // b.bb.bw
    15,    // w.bb.bw
    64,    // .bbb.bw
    80,    // bbbb.bw
    74,    // wbbb.bw
    -81,   // .wbb.bw
    -78,   // bwbb.bw
    -94,   // wwbb.bw
    -40,   // ..wb.bw
    -11,   // b.wb.bw
    -27,   // w.wb.bw
    -25,   // .bwb.bw
    74,    // bbwb.bw
    -42,   // wbwb.bw
    27,    // .wwb.bw
    32,    // bwwb.bw
    -31,   // wwwb.bw
    14,    // ...w.bw
    -61,   // b..w.bw
    17,    // w..w.bw
    -78,   // .b.w.bw
    54,    // bb.w.bw
    -29,   // wb.w.bw
    -18,   // .w.w.bw
    71,    // bw.w.bw
    49,    // ww.w.bw
    1,     // ..bw.bw
    3,     // b.bw.bw
    -30,   // w.bw.bw
    20,    // .bbw.bw
    -25,   // bbbw.bw
    -82,   // wbbw.bw
    34,    // .wbw.bw
    9,     // bwbw.bw
    33,    // wwbw.bw
    -17,   // ..ww.bw
    106,   // b.ww.bw
    32,    // w.ww.bw
    22,    // .bww.bw
    -13,   // bbww.bw
    39,    // wbww.bw
    -88,   // .www.bw
    9,     // bwww.bw
    -95,   // wwww.bw
    -139,  // ....bbw
    -105,  // b...bbw
    41,    // w...bbw
    130,   // .b..bbw
    -48,   // bb..bbw
    50,    // wb..bbw
    -32,   // .w..bbw
    25,    // bw..bbw
    15,    // ww..bbw
    -110,  // ..b.bbw
    1,     // b.b.bbw
    -45,   // w.b.bbw
    7,     // .bb.bbw
    -29,   // bbb.bbw
    16,    // wbb.bbw
    72,    // .wb.bbw
    -23,   // bwb.bbw
    14,    // wwb.bbw
    47,    // ..w.bbw
    -21,   // b.w.bbw
    -150,  // w.w.bbw
    -60,   // .bw.bbw
    13,    // bbw.bbw
    -92,   // wbw.bbw
    -80,   // .ww.bbw
    0,     // bww.bbw
    27,    // www.bbw
    -111,  // ...bbbw
    -99,   // b..bbbw
    20,    // w..bbbw
    99,    // .b.bbbw
    -14,   // bb.bbbw
    74,    // wb.bbbw
    -44,   // .w.bbbw
    -9,    // bw.bbbw
    -22,   // ww.bbbw
    11,    // ..bbbbw
    -47,   // b.bbbbw
    -7,    // w.bbbbw
    -9,    // .bbbbbw
    -24,   // bbbbbbw
    -66,   // wbbbbbw
    -222,  // .wbbbbw
    -100,  // bwbbbbw
    22,    // wwbbbbw
    -37,   // ..wbbbw
    -16,   // b.wbbbw
    42,    // w.wbbbw
    -20,   // .bwbbbw
    -9,    // bbwbbbw
    103,   // wbwbbbw
    -72,   // .wwbbbw
    19,    // bwwbbbw
    -44,   // wwwbbbw
    -39,   // ...wbbw
    -38,   // b..wbbw
    47,    // w..wbbw
    -82,   // .b.wbbw
    77,    // bb.wbbw
    -82,   // wb.wbbw
    61,    // .w.wbbw
    -32,   // bw.wbbw
    -35,   // ww.wbbw
    38,    // ..bwbbw
    -23,   // b.bwbbw
    -70,   // w.bwbbw
    -71,   // .bbwbbw
    -208,  // bbbwbbw
    14,    // wbbwbbw
    -105,  // .wbwbbw
    -25,   // bwbwbbw
    -46,   // wwbwbbw
    96,    // ..wwbbw
    44,    // b.wwbbw
    46,    // w.wwbbw
    -102,  // .bwwbbw
    -11,   // bbwwbbw
    -14,   // wbwwbbw
    -18,   // .wwwbbw
    -19,   // bwwwbbw
    -6,    // wwwwbbw
    -30,   // ....wbw
    -34,   // b...wbw
    -2,    // w...wbw
    -29,   // .b..wbw
    -24,   // bb..wbw
    87,    // wb..wbw
    34,    // .w..wbw
    13,    // bw..wbw
    64,    // ww..wbw
    -61,   // ..b.wbw
    29,    // b.b.wbw
    -55,   // w.b.wbw
    -109,  // .bb.wbw
    -52,   // bbb.wbw
    -92,   // wbb.wbw
    -54,   // .wb.wbw
    0,     // bwb.wbw
    -16,   // wwb.wbw
    64,    // ..w.wbw
    75,    // b.w.wbw
    -7,    // w.w.wbw
    -7,    // .bw.wbw
    -79,   // bbw.wbw
    -33,   // wbw.wbw
    -1,    // .ww.wbw
    23,    // bww.wbw
    36,    // www.wbw
    0,     // ...bwbw
    -66,   // b..bwbw
    41,    // w..bwbw
    22,    // .b.bwbw
    -47,   // bb.bwbw
    -42,   // wb.bwbw
    9,     // .w.bwbw
    -9,    // bw.bwbw
    -194,  // ww.bwbw
    78,    // ..bbwbw
    27,    // b.bbwbw
    -88,   // w.bbwbw
    92,    // .bbbwbw
    74,    // bbbbwbw
    103,   // wbbbwbw
    94,    // .wbbwbw
    68,    // bwbbwbw
    30,    // wwbbwbw
    39,    // ..wbwbw
    -54,   // b.wbwbw
    -30,   // w.wbwbw
    -60,   // .bwbwbw
    107,   // bbwbwbw
    48,    // wbwbwbw
    52,    // .wwbwbw
    25,    // bwwbwbw
    -28,   // wwwbwbw
    46,    // ...wwbw
    99,    // b..wwbw
    -115,  // w..wwbw
    115,   // .b.wwbw
    20,    // bb.wwbw
    39,    // wb.wwbw
    54,    // .w.wwbw
    78,    // bw.wwbw
    -39,   // ww.wwbw
    -22,   // ..bwwbw
    40,    // b.bwwbw
    -78,   // w.bwwbw
    -16,   // .bbwwbw
    -117,  // bbbwwbw
    -14,   // wbbwwbw
    125,   // .wbwwbw
    -68,   // bwbwwbw
    -1,    // wwbwwbw
    44,    // ..wwwbw
    -30,   // b.wwwbw
    79,    // w.wwwbw
    -9,    // .bwwwbw
    -5,    // bbwwwbw
    -58,   // wbwwwbw
    53,    // .wwwwbw
    100,   // bwwwwbw
    32,    // wwwwwbw
    6,     // .....ww
    -29,   // b....ww
    28,    // w....ww
    14,    // .b...ww
    0,     // bb...ww
    5,     // wb...ww
    43,    // .w...ww
    46,    // bw...ww
    -6,    // ww...ww
    58,    // ..b..ww
    31,    // b.b..ww
    9,     // w.b..ww
    -79,   // .bb..ww
    31,    // bbb..ww
    15,    // wbb..ww
    13,    // .wb..ww
    24,    // bwb..ww
    15,    // wwb..ww
    26,    // ..w..ww
    -18,   // b.w..ww
    89,    // w.w..ww
    -107,  // .bw..ww
    -32,   // bbw..ww
    64,    // wbw..ww
    -7,    // .ww..ww
    48,    // bww..ww
    -122,  // www..ww
    -34,   // ...b.ww
    109,   // b..b.ww
    -60,   // w..b.ww
    -39,   // .b.b.ww
    31,    // bb.b.ww
    -52,   // wb.b.ww
    68,    // .w.b.ww
    -54,   // bw.b.ww
    -90,   // ww.b.ww
    -41,   // ..bb.ww
    -8,    // b.bb.ww
    -18,   // w.bb.ww
    -5,    // .bbb.ww
    47,    // bbbb.ww
    -22,   // wbbb.ww
    27,    // .wbb.ww
    -20,   // bwbb.ww
    19,    // wwbb.ww
    37,    // ..wb.ww
    -28,   // b.wb.ww
    19,    // w.wb.ww
    -22,   // .bwb.ww
    -77,   // bbwb.ww
    -194,  // wbwb.ww
    -76,   // .wwb.ww
    -77,   // bwwb.ww
    -63,   // wwwb.ww
    -104,  // ...w.ww
    59,    // b..w.ww
    25,    // w..w.ww
    -108,  // .b.w.ww
    -31,   // bb.w.ww
    49,    // wb.w.ww
    87,    // .w.w.ww
    -69,   // bw.w.ww
    -21,   // ww.w.ww
    28,    // ..bw.ww
    55,    // b.bw.ww
    -39,   // w.bw.ww
    -25,   // .bbw.ww
    -41,   // bbbw.ww
    -35,   // wbbw.ww
    26,    // .wbw.ww
    47,    // bwbw.ww
    8,     // wwbw.ww
    -42,   // ..ww.ww
    8,     // b.ww.ww
    35,    // w.ww.ww
    -73,   // .bww.ww
    119,   // bbww.ww
    -39,   // wbww.ww
    -4,    // .www.ww
    14,    // bwww.ww
    51,    // wwww.ww
    121,   // ....bww
    15,    // b...bww
    39,    // w...bww
    39,    // .b..bww
    32,    // bb..bww
    -59,   // wb..bww
    13,    // .w..bww
    11,    // bw..bww
    15,    // ww..bww
    -38,   // ..b.bww
    -16,   // b.b.bww
    99,    // w.b.bww
    -23,   // .bb.bww
    -111,  // bbb.bww
    14,    // wbb.bww
    22,    // .wb.bww
    79,    // bwb.bww
    91,    // wwb.bww
    57,    // ..w.bww
    -8,    // b.w.bww
    -50,   // w.w.bww
    6,     // .bw.bww
    0,     // bbw.bww
    -16,   // wbw.bww
    -37,   // .ww.bww
    -13,   // bww.bww
    -70,   // www.bww
    3,     // ...bbww
    -52,   // b..bbww
    62,    // w..bbww
    -26,   // .b.bbww
    -119,  // bb.bbww
    -94,   // wb.bbww
    -3,    // .w.bbww
    13,    // bw.bbww
    19,    // ww.bbww
    3,     // ..bbbww
    25,    // b.bbbww
    73,    // w.bbbww
    -13,   // .bbbbww
    115,   // bbbbbww
    22,    // wbbbbww
    -74,   // .wbbbww
    5,     // bwbbbww
    -1,    // wwbbbww
    3,     // ..wbbww
    -18,   // b.wbbww
    38,    // w.wbbww
    63,    // .bwbbww
    58,    // bbwbbww
    30,    // wbwbbww
    57,    // .wwbbww
    11,    // bwwbbww
    -55,   // wwwbbww
    98,    // ...wbww
    0,     // b..wbww
    95,    // w..wbww
    84,    // .b.wbww
    77,    // bb.wbww
    33,    // wb.wbww
    -23,   // .w.wbww
    -74,   // bw.wbww
    8,     // ww.wbww
    -6,    // ..bwbww
    103,   // b.bwbww
    12,    // w.bwbww
    132,   // .bbwbww
    -39,   // bbbwbww
    -46,   // wbbwbww
    -11,   // .wbwbww
    -107,  // bwbwbww
    -29,   // wwbwbww
    18,    // ..wwbww
    -73,   // b.wwbww
    43,    // w.wwbww
    -32,   // .bwwbww
    -58,   // bbwwbww
    -1,    // wbwwbww
    130,   // .wwwbww
    9,     // bwwwbww
    23,    // wwwwbww
    -50,   // ....www
    -111,  // b...www
    119,   // w...www
    -86,   // .b..www
    -31,   // bb..www
    -22,   // wb..www
    -4,    // .w..www
    22,    // bw..www
    -122,  // ww..www
    -50,   // ..b.www
    19,    // b.b.www
    22,    // w.b.www
    -114,  // .bb.www
    0,     // bbb.www
    27,    // wbb.www
    -13,   // .wb.www
    52,    // bwb.www
    -70,   // wwb.www
    -126,  // ..w.www
    -7,    // b.w.www
    -30,   // w.w.www
    9,     // .bw.www
    111,   // bbw.www
    36,    // wbw.www
    32,    // .ww.www
    29,    // bww.www
    -39,   // www.www
    -85,   // ...bwww
    31,    // b..bwww
    -65,   // w..bwww
    50,    // .b.bwww
    41,    // bb.bwww
    -31,   // wb.bwww
    100,   // .w.bwww
    25,    // bw.bwww
    -63,   // ww.bwww
    -96,   // ..bbwww
    91,    // b.bbwww
    -106,  // w.bbwww
    -57,   // .bbbwww
    -93,   // bbbbwww
    -44,   // wbbbwww
    -17,   // .wbbwww
    117,   // bwbbwww
    -55,   // wwbbwww
    167,   // ..wbwww
    -72,   // b.wbwww
    54,    // w.wbwww
    24,    // .bwbwww
    39,    // bbwbwww
    -28,   // wbwbwww
    83,    // .wwbwww
    208,   // bwwbwww
    -14,   // wwwbwww
    -486,  // ...wwww
    -93,   // b..wwww
    9,     // w..wwww
    -204,  // .b.wwww
    -47,   // bb.wwww
    -95,   // wb.wwww
    79,    // .w.wwww
    -80,   // bw.wwww
    51,    // ww.wwww
    -71,   // ..bwwww
    10,    // b.bwwww
    -81,   // w.bwwww
    46,    // .bbwwww
    93,    // bbbwwww
    -6,    // wbbwwww
    121,   // .wbwwww
    -74,   // bwbwwww
    23,    // wwbwwww
    -67,   // ..wwwww
    -11,   // b.wwwww
    80,    // w.wwwww
    -159,  // .bwwwww
    -115,  // bbwwwww
    32,    // wbwwwww
    69,    // .wwwwww
    24,    // bwwwwww
    36,    // wwwwwww
    0,     // captures=0 threats=0
    60,    // captures=0 threats=1
    119,   // captures=0 threats=2
    145,   // captures=0 threats=3
    195,   // captures=0 threats=4
    21,    // captures=0 additional threats
    86,    // captures=1 threats=0
    157,   // captures=1 threats=1
    196,   // captures=1 threats=2
    465,   // captures=1 threats=3
    503,   // captures=1 threats=4
    13,    // captures=1 additional threats
    98,    // captures=2 threats=0
    294,   // captures=2 threats=1
    441,   // captures=2 threats=2
    465,   // captures=2 threats=3
    790,   // captures=2 threats=4
    162,   // captures=2 additional threats
    101,   // captures=3 threats=0
    297,   // captures=3 threats=1
    519,   // captures=3 threats=2
    537,   // captures=3 threats=3
    790,   // captures=3 threats=4
    191,   // captures=3 additional threats
    118,   // captures=4 threats=0
    318,   // captures=4 threats=1
    609,   // captures=4 threats=2
    941,   // captures=4 threats=3
    1422,  // captures=4 threats=4
    305,   // captures=4 additional threats
].into_boxed_slice()
