vec![
    0,     // .......
    9,     // b......
    -9,    // w......
    6,     // .b.....
    10,    // bb.....
    -9,    // wb.....
    -6,    // .w.....
    9,     // bw.....
    -10,   // ww.....
    5,     // ..b....
    75,    // b.b....
    -32,   // w.b....
    35,    // .bb....
    170,   // bbb....
    -83,   // wbb....
    -26,   // .wb....
    46,    // bwb....
    55,    // wwb....
    -5,    // ..w....
    32,    // b.w....
    -75,   // w.w....
    26,    // .bw....
    -55,   // bbw....
    -46,   // wbw....
    -35,   // .ww....
    83,    // bww....
    -170,  // www....
    -17,   // ...b...
    1,     // b..b...
    -16,   // w..b...
    -9,    // .b.b...
    154,   // bb.b...
    -41,   // wb.b...
    13,    // .w.b...
    18,    // bw.b...
    -43,   // ww.b...
    -11,   // ..bb...
    61,    // b.bb...
    38,    // w.bb...
    66,    // .bbb...
    323,   // bbbb...
    -105,  // wbbb...
    56,    // .wbb...
    3,     // bwbb...
    26,    // wwbb...
    2,     // ..wb...
    70,    // b.wb...
    -50,   // w.wb...
    -20,   // .bwb...
    -55,   // bbwb...
    -2,    // wbwb...
    -3,    // .wwb...
    28,    // bwwb...
    -50,   // wwwb...
    17,    // ...w...
    16,    // b..w...
    -1,    // w..w...
    -13,   // .b.w...
    43,    // bb.w...
    -18,   // wb.w...
    9,     // .w.w...
    41,    // bw.w...
    -154,  // ww.w...
    -2,    // ..bw...
    50,    // b.bw...
    -70,   // w.bw...
    3,     // .bbw...
    50,    // bbbw...
    -28,   // wbbw...
    20,    // .wbw...
    2,     // bwbw...
    55,    // wwbw...
    11,    // ..ww...
    -38,   // b.ww...
    -61,   // w.ww...
    -56,   // .bww...
    -26,   // bbww...
    -3,    // wbww...
    -66,   // .www...
    105,   // bwww...
    -323,  // wwww...
    5,     // ....b..
    22,    // b...b..
    -20,   // w...b..
    3,     // .b..b..
    23,    // bb..b..
    45,    // wb..b..
    -17,   // .w..b..
    16,    // bw..b..
    40,    // ww..b..
    -25,   // ..b.b..
    25,    // b.b.b..
    -41,   // w.b.b..
    -72,   // .bb.b..
    123,   // bbb.b..
    -48,   // wbb.b..
    -6,    // .wb.b..
    -64,   // bwb.b..
    -14,   // wwb.b..
    0,     // ..w.b..
    31,    // b.w.b..
    -47,   // w.w.b..
    -22,   // .bw.b..
    -39,   // bbw.b..
    -38,   // wbw.b..
    36,    // .ww.b..
    7,     // bww.b..
    -46,   // www.b..
    -11,   // ...bb..
    -29,   // b..bb..
    20,    // w..bb..
    -4,    // .b.bb..
    10,    // bb.bb..
    10,    // wb.bb..
    -69,   // .w.bb..
    11,    // bw.bb..
    -29,   // ww.bb..
    39,    // ..bbb..
    97,    // b.bbb..
    -31,   // w.bbb..
    276,   // .bbbb..
    51,    // bbbbb..
    48,    // wbbbb..
    -30,   // .wbbb..
    -44,   // bwbbb..
    -38,   // wwbbb..
    -82,   // ..wbb..
    -15,   // b.wbb..
    -35,   // w.wbb..
    -8,    // .bwbb..
    -25,   // bbwbb..
    44,    // wbwbb..
    18,    // .wwbb..
    -114,  // bwwbb..
    -70,   // wwwbb..
    -2,    // ...wb..
    81,    // b..wb..
    40,    // w..wb..
    -21,   // .b.wb..
    -57,   // bb.wb..
    -12,   // wb.wb..
    53,    // .w.wb..
    19,    // bw.wb..
    21,    // ww.wb..
    -5,    // ..bwb..
    28,    // b.bwb..
    -1,    // w.bwb..
    8,     // .bbwb..
    -139,  // bbbwb..
    65,    // wbbwb..
    25,    // .wbwb..
    -18,   // bwbwb..
    -29,   // wwbwb..
    82,    // ..wwb..
    28,    // b.wwb..
    81,    // w.wwb..
    0,     // .bwwb..
    63,    // bbwwb..
    -3,    // wbwwb..
    -86,   // .wwwb..
    -1,    // bwwwb..
    -49,   // wwwwb..
    -5,    // ....w..
    20,    // b...w..
    -22,   // w...w..
    17,    // .b..w..
    -40,   // bb..w..
    -16,   // wb..w..
    -3,    // .w..w..
    -45,   // bw..w..
    -23,   // ww..w..
    0,     // ..b.w..
    47,    // b.b.w..
    -31,   // w.b.w..
    -36,   // .bb.w..
    46,    // bbb.w..
    -7,    // wbb.w..
    22,    // .wb.w..
    38,    // bwb.w..
    39,    // wwb.w..
    25,    // ..w.w..
    41,    // b.w.w..
    -25,   // w.w.w..
    6,     // .bw.w..
    14,    // bbw.w..
    64,    // wbw.w..
    72,    // .ww.w..
    48,    // bww.w..
    -123,  // www.w..
    2,     // ...bw..
    -40,   // b..bw..
    -81,   // w..bw..
    -53,   // .b.bw..
    -21,   // bb.bw..
    -19,   // wb.bw..
    21,    // .w.bw..
    12,    // bw.bw..
    57,    // ww.bw..
    -82,   // ..bbw..
    -81,   // b.bbw..
    -28,   // w.bbw..
    86,    // .bbbw..
    49,    // bbbbw..
    1,     // wbbbw..
    0,     // .wbbw..
    3,     // bwbbw..
    -63,   // wwbbw..
    5,     // ..wbw..
    1,     // b.wbw..
    -28,   // w.wbw..
    -25,   // .bwbw..
    29,    // bbwbw..
    18,    // wbwbw..
    -8,    // .wwbw..
    -65,   // bwwbw..
    139,   // wwwbw..
    11,    // ...ww..
    -20,   // b..ww..
    29,    // w..ww..
    69,    // .b.ww..
    29,    // bb.ww..
    -11,   // wb.ww..
    4,     // .w.ww..
    -10,   // bw.ww..
    -10,   // ww.ww..
    82,    // ..bww..
    35,    // b.bww..
    15,    // w.bww..
    -18,   // .bbww..
    70,    // bbbww..
    114,   // wbbww..
    8,     // .wbww..
    -44,   // bwbww..
    25,    // wwbww..
    -39,   // ..www..
    31,    // b.www..
    -97,   // w.www..
    30,    // .bwww..
    38,    // bbwww..
    44,    // wbwww..
    -276,  // .wwww..
    -48,   // bwwww..
    -51,   // wwwww..
    6,     // .....b.
    -4,    // b....b.
    -51,   // w....b.
    -28,   // .b...b.
    5,     // bb...b.
    16,    // wb...b.
    0,     // .w...b.
    11,    // bw...b.
    -6,    // ww...b.
    3,     // ..b..b.
    35,    // b.b..b.
    -33,   // w.b..b.
    24,    // .bb..b.
    22,    // bbb..b.
    116,   // wbb..b.
    -12,   // .wb..b.
    -10,   // bwb..b.
    43,    // wwb..b.
    17,    // ..w..b.
    -31,   // b.w..b.
    -15,   // w.w..b.
    -23,   // .bw..b.
    -10,   // bbw..b.
    -57,   // wbw..b.
    -26,   // .ww..b.
    7,     // bww..b.
    -55,   // www..b.
    -9,    // ...b.b.
    -61,   // b..b.b.
    -31,   // w..b.b.
    -14,   // .b.b.b.
    -44,   // bb.b.b.
    2,     // wb.b.b.
    -23,   // .w.b.b.
    4,     // bw.b.b.
    -26,   // ww.b.b.
    -4,    // ..bb.b.
    -19,   // b.bb.b.
    92,    // w.bb.b.
    69,    // .bbb.b.
    -74,   // bbbb.b.
    93,    // wbbb.b.
    -1,    // .wbb.b.
    0,     // bwbb.b.
    -20,   // wwbb.b.
    -53,   // ..wb.b.
    -51,   // b.wb.b.
    -70,   // w.wb.b.
    35,    // .bwb.b.
    20,    // bbwb.b.
    16,    // wbwb.b.
    25,    // .wwb.b.
    26,    // bwwb.b.
    62,    // wwwb.b.
    -13,   // ...w.b.
    -26,   // b..w.b.
    -17,   // w..w.b.
    -3,    // .b.w.b.
    -68,   // bb.w.b.
    -36,   // wb.w.b.
    23,    // .w.w.b.
    55,    // bw.w.b.
    -113,  // ww.w.b.
    -21,   // ..bw.b.
    31,    // b.bw.b.
    34,    // w.bw.b.
    37,    // .bbw.b.
    -72,   // bbbw.b.
    -79,   // wbbw.b.
    32,    // .wbw.b.
    31,    // bwbw.b.
    17,    // wwbw.b.
    69,    // ..ww.b.
    0,     // b.ww.b.
    -63,   // w.ww.b.
    44,    // .bww.b.
    -9,    // bbww.b.
    131,   // wbww.b.
    -3,    // .www.b.
    48,    // bwww.b.
    -207,  // wwww.b.
    35,    // ....bb.
    -25,   // b...bb.
    36,    // w...bb.
    24,    // .b..bb.
    3,     // bb..bb.
    -22,   // wb..bb.
    26,    // .w..bb.
    22,    // bw..bb.
    -86,   // ww..bb.
    -72,   // ..b.bb.
    4,     // b.b.bb.
    20,    // w.b.bb.
    22,    // .bb.bb.
    23,    // bbb.bb.
    -41,   // wbb.bb.
    -56,   // .wb.bb.
    -45,   // bwb.bb.
    -47,   // wwb.bb.
    -36,   // ..w.bb.
    -49,   // b.w.bb.
    16,    // w.w.bb.
    -25,   // .bw.bb.
    -17,   // bbw.bb.
    -75,   // wbw.bb.
    0,     // .ww.bb.
    58,    // bww.bb.
    -58,   // www.bb.
    66,    // ...bbb.
    32,    // b..bbb.
    -26,   // w..bbb.
    69,    // .b.bbb.
    -33,   // bb.bbb.
    85,    // wb.bbb.
    3,     // .w.bbb.
    102,   // bw.bbb.
    5,     // ww.bbb.
    276,   // ..bbbb.
    57,    // b.bbbb.
    68,    // w.bbbb.
    -46,   // .bbbbb.
    -20,   // bbbbbb.
    -31,   // wbbbbb.
    77,    // .wbbbb.
    -11,   // bwbbbb.
    -25,   // wwbbbb.
    86,    // ..wbbb.
    -13,   // b.wbbb.
    -13,   // w.wbbb.
    50,    // .bwbbb.
    -90,   // bbwbbb.
    56,    // wbwbbb.
    10,    // .wwbbb.
    41,    // bwwbbb.
    -18,   // wwwbbb.
    3,     // ...wbb.
    21,    // b..wbb.
    -4,    // w..wbb.
    37,    // .b.wbb.
    58,    // bb.wbb.
    53,    // wb.wbb.
    -25,   // .w.wbb.
    -34,   // bw.wbb.
    -72,   // ww.wbb.
    8,     // ..bwbb.
    -128,  // b.bwbb.
    -33,   // w.bwbb.
    35,    // .bbwbb.
    -18,   // bbbwbb.
    -66,   // wbbwbb.
    5,     // .wbwbb.
    -50,   // bwbwbb.
    113,   // wwbwbb.
    -18,   // ..wwbb.
    -39,   // b.wwbb.
    24,    // w.wwbb.
    0,     // .bwwbb.
    -105,  // bbwwbb.
    15,    // wbwwbb.
    -10,   // .wwwbb.
    61,    // bwwwbb.
    -8,    // wwwwbb.
    26,    // ....wb.
    -9,    // b...wb.
    36,    // w...wb.
    -23,   // .b..wb.
    42,    // bb..wb.
    -79,   // wb..wb.
    12,    // .w..wb.
    -12,   // bw..wb.
    -58,   // ww..wb.
    -22,   // ..b.wb.
    -38,   // b.b.wb.
    18,    // w.b.wb.
    -25,   // .bb.wb.
    42,    // bbb.wb.
    23,    // wbb.wb.
    0,     // .wb.wb.
    -16,   // bwb.wb.
    1,     // wwb.wb.
    6,     // ..w.wb.
    6,     // b.w.wb.
    68,    // w.w.wb.
    53,    // .bw.wb.
    -4,    // bbw.wb.
    4,     // wbw.wb.
    56,    // .ww.wb.
    -64,   // bww.wb.
    -10,   // www.wb.
    -20,   // ...bwb.
    26,    // b..bwb.
    59,    // w..bwb.
    35,    // .b.bwb.
    22,    // bb.bwb.
    -70,   // wb.bwb.
    -32,   // .w.bwb.
    -26,   // bw.bwb.
    -17,   // ww.bwb.
    -8,    // ..bbwb.
    -21,   // b.bbwb.
    -12,   // w.bbwb.
    50,    // .bbbwb.
    -67,   // bbbbwb.
    -3,    // wbbbwb.
    18,    // .wbbwb.
    -42,   // bwbbwb.
    85,    // wwbbwb.
    -25,   // ..wbwb.
    -48,   // b.wbwb.
    5,     // w.wbwb.
    19,    // .bwbwb.
    4,     // bbwbwb.
    -31,   // wbwbwb.
    -5,    // .wwbwb.
    110,   // bwwbwb.
    14,    // wwwbwb.
    -56,   // ...wwb.
    -16,   // b..wwb.
    13,    // w..wwb.
    44,    // .b.wwb.
    -70,   // bb.wwb.
    -10,   // wb.wwb.
    1,     // .w.wwb.
    16,    // bw.wwb.
    -70,   // ww.wwb.
    0,     // ..bwwb.
    -48,   // b.bwwb.
    -50,   // w.bwwb.
    0,     // .bbwwb.
    -25,   // bbbwwb.
    -64,   // wbbwwb.
    -18,   // .wbwwb.
    -58,   // bwbwwb.
    -21,   // wwbwwb.
    30,    // ..wwwb.
    106,   // b.wwwb.
    -114,  // w.wwwb.
    13,    // .bwwwb.
    29,    // bbwwwb.
    -74,   // wbwwwb.
    -77,   // .wwwwb.
    105,   // bwwwwb.
    -98,   // wwwwwb.
    -6,    // .....w.
    51,    // b....w.
    4,     // w....w.
    0,     // .b...w.
    6,     // bb...w.
    -11,   // wb...w.
    28,    // .w...w.
    -16,   // bw...w.
    -5,    // ww...w.
    -17,   // ..b..w.
    15,    // b.b..w.
    31,    // w.b..w.
    26,    // .bb..w.
    55,    // bbb..w.
    -7,    // wbb..w.
    23,    // .wb..w.
    57,    // bwb..w.
    10,    // wwb..w.
    -3,    // ..w..w.
    33,    // b.w..w.
    -35,   // w.w..w.
    12,    // .bw..w.
    -43,   // bbw..w.
    10,    // wbw..w.
    -24,   // .ww..w.
    -116,  // bww..w.
    -22,   // www..w.
    13,    // ...b.w.
    17,    // b..b.w.
    26,    // w..b.w.
    -23,   // .b.b.w.
    113,   // bb.b.w.
    -55,   // wb.b.w.
    3,     // .w.b.w.
    36,    // bw.b.w.
    68,    // ww.b.w.
    -69,   // ..bb.w.
    63,    // b.bb.w.
    0,     // w.bb.w.
    3,     // .bbb.w.
    207,   // bbbb.w.
    -48,   // wbbb.w.
    -44,   // .wbb.w.
    -131,  // bwbb.w.
    9,     // wwbb.w.
    21,    // ..wb.w.
    -34,   // b.wb.w.
    -31,   // w.wb.w.
    -32,   // .bwb.w.
    -17,   // bbwb.w.
    -31,   // wbwb.w.
    -37,   // .wwb.w.
    79,    // bwwb.w.
    72,    // wwwb.w.
    9,     // ...w.w.
    31,    // b..w.w.
    61,    // w..w.w.
    23,    // .b.w.w.
    26,    // bb.w.w.
    -4,    // wb.w.w.
    14,    // .w.w.w.
    -2,    // bw.w.w.
    44,    // ww.w.w.
    53,    // ..bw.w.
    70,    // b.bw.w.
    51,    // w.bw.w.
    -25,   // .bbw.w.
    -62,   // bbbw.w.
    -26,   // wbbw.w.
    -35,   // .wbw.w.
    -16,   // bwbw.w.
    -20,   // wwbw.w.
    4,     // ..ww.w.
    -92,   // b.ww.w.
    19,    // w.ww.w.
    1,     // .bww.w.
    20,    // bbww.w.
    0,     // wbww.w.
    -69,   // .www.w.
    -93,   // bwww.w.
    74,    // wwww.w.
    -26,   // ....bw.
    -36,   // b...bw.
    9,     // w...bw.
    -12,   // .b..bw.
    58,    // bb..bw.
    12,    // wb..bw.
    23,    // .w..bw.
    79,    // bw..bw.
    -42,   // ww..bw.
    -6,    // ..b.bw.
    -68,   // b.b.bw.
    -6,    // w.b.bw.
    -56,   // .bb.bw.
    10,    // bbb.bw.
    64,    // wbb.bw.
    -53,   // .wb.bw.
    -4,    // bwb.bw.
    4,     // wwb.bw.
    22,    // ..w.bw.
    -18,   // b.w.bw.
    38,    // w.w.bw.
    0,     // .bw.bw.
    -1,    // bbw.bw.
    16,    // wbw.bw.
    25,    // .ww.bw.
    -23,   // bww.bw.
    -42,   // www.bw.
    56,    // ...bbw.
    -13,   // b..bbw.
    16,    // w..bbw.
    -1,    // .b.bbw.
    70,    // bb.bbw.
    -16,   // wb.bbw.
    -44,   // .w.bbw.
    10,    // bw.bbw.
    70,    // ww.bbw.
    -30,   // ..bbbw.
    114,   // b.bbbw.
    -106,  // w.bbbw.
    77,    // .bbbbw.
    98,    // bbbbbw.
    -105,  // wbbbbw.
    -13,   // .wbbbw.
    74,    // bwbbbw.
    -29,   // wwbbbw.
    0,     // ..wbbw.
    50,    // b.wbbw.
    48,    // w.wbbw.
    18,    // .bwbbw.
    21,    // bbwbbw.
    58,    // wbwbbw.
    0,     // .wwbbw.
    64,    // bwwbbw.
    25,    // wwwbbw.
    20,    // ...wbw.
    -59,   // b..wbw.
    -26,   // w..wbw.
    32,    // .b.wbw.
    17,    // bb.wbw.
    26,    // wb.wbw.
    -35,   // .w.wbw.
    70,    // bw.wbw.
    -22,   // ww.wbw.
    25,    // ..bwbw.
    -5,    // b.bwbw.
    48,    // w.bwbw.
    5,     // .bbwbw.
    -14,   // bbbwbw.
    -110,  // wbbwbw.
    -19,   // .wbwbw.
    31,    // bwbwbw.
    -4,    // wwbwbw.
    8,     // ..wwbw.
    12,    // b.wwbw.
    21,    // w.wwbw.
    -18,   // .bwwbw.
    -85,   // bbwwbw.
    42,    // wbwwbw.
    -50,   // .wwwbw.
    3,     // bwwwbw.
    67,    // wwwwbw.
    -35,   // ....ww.
    -36,   // b...ww.
    25,    // w...ww.
    -26,   // .b..ww.
    86,    // bb..ww.
    -22,   // wb..ww.
    -24,   // .w..ww.
    22,    // bw..ww.
    -3,    // ww..ww.
    36,    // ..b.ww.
    -16,   // b.b.ww.
    49,    // w.b.ww.
    0,     // .bb.ww.
    58,    // bbb.ww.
    -58,   // wbb.ww.
    25,    // .wb.ww.
    75,    // bwb.ww.
    17,    // wwb.ww.
    72,    // ..w.ww.
    -20,   // b.w.ww.
    -4,    // w.w.ww.
    56,    // .bw.ww.
    47,    // bbw.ww.
    45,    // wbw.ww.
    -22,   // .ww.ww.
    41,    // bww.ww.
    -23,   // www.ww.
    -3,    // ...bww.
    4,     // b..bww.
    -21,   // w..bww.
    25,    // .b.bww.
    72,    // bb.bww.
    34,    // wb.bww.
    -37,   // .w.bww.
    -53,   // bw.bww.
    -58,   // ww.bww.
    18,    // ..bbww.
    -24,   // b.bbww.
    39,    // w.bbww.
    10,    // .bbbww.
    8,     // bbbbww.
    -61,   // wbbbww.
    0,     // .wbbww.
    -15,   // bwbbww.
    105,   // wwbbww.
    -8,    // ..wbww.
    33,    // b.wbww.
    128,   // w.wbww.
    -5,    // .bwbww.
    -113,  // bbwbww.
    50,    // wbwbww.
    -35,   // .wwbww.
    66,    // bwwbww.
    18,    // wwwbww.
    -66,   // ...www.
    26,    // b..www.
    -32,   // w..www.
    -3,    // .b.www.
    -5,    // bb.www.
    -102,  // wb.www.
    -69,   // .w.www.
    -85,   // bw.www.
    33,    // ww.www.
    -86,   // ..bwww.
    13,    // b.bwww.
    13,    // w.bwww.
    -10,   // .bbwww.
    18,    // bbbwww.
    -41,   // wbbwww.
    -50,   // .wbwww.
    -56,   // bwbwww.
    90,    // wwbwww.
    -276,  // ..wwww.
    -68,   // b.wwww.
    -57,   // w.wwww.
    -77,   // .bwwww.
    25,    // bbwwww.
    11,    // wbwwww.
    46,    // .wwwww.
    31,    // bwwwww.
    20,    // wwwwww.
    9,     // ......b
    -50,   // b.....b
    0,     // w.....b
    -4,    // .b....b
    -10,   // bb....b
    4,     // wb....b
    51,    // .w....b
    40,    // bw....b
    11,    // ww....b
    22,    // ..b...b
    57,    // b.b...b
    -23,   // w.b...b
    -25,   // .bb...b
    -27,   // bbb...b
    -65,   // wbb...b
    -36,   // .wb...b
    -10,   // bwb...b
    16,    // wwb...b
    20,    // ..w...b
    1,     // b.w...b
    56,    // w.w...b
    -9,    // .bw...b
    -7,    // bbw...b
    -16,   // wbw...b
    -36,   // .ww...b
    -48,   // bww...b
    -45,   // www...b
    1,     // ...b..b
    8,     // b..b..b
    74,    // w..b..b
    -61,   // .b.b..b
    17,    // bb.b..b
    -41,   // wb.b..b
    17,    // .w.b..b
    -58,   // bw.b..b
    110,   // ww.b..b
    -29,   // ..bb..b
    -60,   // b.bb..b
    22,    // w.bb..b
    32,    // .bbb..b
    8,     // bbbb..b
    -97,   // wbbb..b
    -13,   // .wbb..b
    154,   // bwbb..b
    -67,   // wwbb..b
    -40,   // ..wb..b
    -6,    // b.wb..b
    19,    // w.wb..b
    26,    // .bwb..b
    -57,   // bbwb..b
    -32,   // wbwb..b
    4,     // .wwb..b
    -5,    // bwwb..b
    13,    // wwwb..b
    16,    // ...w..b
    -72,   // b..w..b
    -74,   // w..w..b
    -26,   // .b.w..b
    4,     // bb.w..b
    -53,   // wb.w..b
    31,    // .w.w..b
    -57,   // bw.w..b
    17,    // ww.w..b
    81,    // ..bw..b
    26,    // b.bw..b
    23,    // w.bw..b
    21,    // .bbw..b
    54,    // bbbw..b
    -19,   // wbbw..b
    -59,   // .wbw..b
    -75,   // bwbw..b
    -3,    // wwbw..b
    -20,   // ..ww..b
    -44,   // b.ww..b
    35,    // w.ww..b
    -16,   // .bww..b
    -50,   // bbww..b
    33,    // wbww..b
    26,    // .www..b
    13,    // bwww..b
    -68,   // wwww..b
    75,    // ....b.b
    57,    // b...b.b
    -56,   // w...b.b
    35,    // .b..b.b
    -53,   // bb..b.b
    93,    // wb..b.b
    15,    // .w..b.b
    47,    // bw..b.b
    -11,   // ww..b.b
    25,    // ..b.b.b
    25,    // b.b.b.b
    51,    // w.b.b.b
    4,     // .bb.b.b
    54,    // bbb.b.b
    -4,    // wbb.b.b
    -68,   // .wb.b.b
    -52,   // bwb.b.b
    -61,   // wwb.b.b
    47,    // ..w.b.b
    28,    // b.w.b.b
    0,     // w.w.b.b
    -38,   // .bw.b.b
    17,    // bbw.b.b
    19,    // wbw.b.b
    -16,   // .ww.b.b
    58,    // bww.b.b
    -13,   // www.b.b
    61,    // ...bb.b
    -60,   // b..bb.b
    -35,   // w..bb.b
    -19,   // .b.bb.b
    -50,   // bb.bb.b
    -76,   // wb.bb.b
    63,    // .w.bb.b
    29,    // bw.bb.b
    -46,   // ww.bb.b
    97,    // ..bbb.b
    54,    // b.bbb.b
    -31,   // w.bbb.b
    57,    // .bbbb.b
    -68,   // bbbbb.b
    6,     // wbbbb.b
    114,   // .wbbb.b
    -40,   // bwbbb.b
    8,     // wwbbb.b
    -81,   // ..wbb.b
    5,     // b.wbb.b
    88,    // w.wbb.b
    -21,   // .bwbb.b
    -19,   // bbwbb.b
    38,    // wbwbb.b
    -24,   // .wwbb.b
    -76,   // bwwbb.b
    87,    // wwwbb.b
    50,    // ...wb.b
    26,    // b..wb.b
    -19,   // w..wb.b
    31,    // .b.wb.b
    35,    // bb.wb.b
    38,    // wb.wb.b
    70,    // .w.wb.b
    -16,   // bw.wb.b
    41,    // ww.wb.b
    28,    // ..bwb.b
    46,    // b.bwb.b
    15,    // w.bwb.b
    -128,  // .bbwb.b
    -55,   // bbbwb.b
    -56,   // wbbwb.b
    -5,    // .wbwb.b
    31,    // bwbwb.b
    84,    // wwbwb.b
    35,    // ..wwb.b
    25,    // b.wwb.b
    -88,   // w.wwb.b
    -48,   // .bwwb.b
    -10,   // bbwwb.b
    14,    // wbwwb.b
    13,    // .wwwb.b
    25,    // bwwwb.b
    16,    // wwwwb.b
    32,    // ....w.b
    1,     // b...w.b
    23,    // w...w.b
    -31,   // .b..w.b
    9,     // bb..w.b
    120,   // wb..w.b
    33,    // .w..w.b
    19,    // bw..w.b
    -55,   // ww..w.b
    31,    // ..b.w.b
    28,    // b.b.w.b
    0,     // w.b.w.b
    -49,   // .bb.w.b
    15,    // bbb.w.b
    80,    // wbb.w.b
    -18,   // .wb.w.b
    78,    // bwb.w.b
    -9,    // wwb.w.b
    41,    // ..w.w.b
    44,    // b.w.w.b
    -51,   // w.w.w.b
    6,     // .bw.w.b
    -7,    // bbw.w.b
    69,    // wbw.w.b
    -20,   // .ww.w.b
    15,    // bww.w.b
    25,    // www.w.b
    70,    // ...bw.b
    -6,    // b..bw.b
    -23,   // w..bw.b
    -51,   // .b.bw.b
    1,     // bb.bw.b
    29,    // wb.bw.b
    -34,   // .w.bw.b
    51,    // bw.bw.b
    3,     // ww.bw.b
    -15,   // ..bbw.b
    5,     // b.bbw.b
    2,     // w.bbw.b
    -13,   // .bbbw.b
    56,    // bbbbw.b
    -5,    // wbbbw.b
    50,    // .wbbw.b
    17,    // bwbbw.b
    -61,   // wwbbw.b
    1,     // ..wbw.b
    -37,   // b.wbw.b
    -15,   // w.wbw.b
    -48,   // .bwbw.b
    -11,   // bbwbw.b
    -52,   // wbwbw.b
    33,    // .wwbw.b
    31,    // bwwbw.b
    -99,   // wwwbw.b
    -38,   // ...ww.b
    -44,   // b..ww.b
    -22,   // w..ww.b
    0,     // .b.ww.b
    -30,   // bb.ww.b
    60,    // wb.ww.b
    -92,   // .w.ww.b
    23,    // bw.ww.b
    -33,   // ww.ww.b
    28,    // ..bww.b
    25,    // b.bww.b
    -2,    // w.bww.b
    -39,   // .bbww.b
    67,    // bbbww.b
    67,    // wbbww.b
    12,    // .wbww.b
    36,    // bwbww.b
    -61,   // wwbww.b
    31,    // ..www.b
    -64,   // b.www.b
    31,    // w.www.b
    106,   // .bwww.b
    4,     // bbwww.b
    27,    // wbwww.b
    -68,   // .wwww.b
    2,     // bwwww.b
    -45,   // wwwww.b
    10,    // .....bb
    -10,   // b....bb
    -11,   // w....bb
    5,     // .b...bb
    -6,    // bb...bb
    -40,   // wb...bb
    6,     // .w...bb
    17,    // bw...bb
    0,     // ww...bb
    23,    // ..b..bb
    -53,   // b.b..bb
    55,    // w.b..bb
    3,     // .bb..bb
    80,    // bbb..bb
    -19,   // wbb..bb
    58,    // .wb..bb
    -69,   // bwb..bb
    13,    // wwb..bb
    -40,   // ..w..bb
    9,     // b.w..bb
    11,    // w.w..bb
    42,    // .bw..bb
    33,    // bbw..bb
    9,     // wbw..bb
    86,    // .ww..bb
    -5,    // bww..bb
    26,    // www..bb
    154,   // ...b.bb
    17,    // b..b.bb
    -17,   // w..b.bb
    -44,   // .b.b.bb
    26,    // bb.b.bb
    59,    // wb.b.bb
    113,   // .w.b.bb
    -49,   // bw.b.bb
    -3,    // ww.b.bb
    10,    // ..bb.bb
    -50,   // b.bb.bb
    33,    // w.bb.bb
    -33,   // .bbb.bb
    -67,   // bbbb.bb
    4,     // wbbb.bb
    70,    // .wbb.bb
    -16,   // bwbb.bb
    -73,   // wwbb.bb
    -21,   // ..wb.bb
    1,     // b.wb.bb
    -41,   // w.wb.bb
    22,    // .bwb.bb
    29,    // bbwb.bb
    3,     // wbwb.bb
    72,    // .wwb.bb
    3,     // bwwb.bb
    6,     // wwwb.bb
    43,    // ...w.bb
    4,     // b..w.bb
    -110,  // w..w.bb
    -68,   // .b.w.bb
    113,   // bb.w.bb
    2,     // wb.w.bb
    26,    // .w.w.bb
    23,    // bw.w.bb
    3,     // ww.w.bb
    -57,   // ..bw.bb
    35,    // b.bw.bb
    -3,    // w.bw.bb
    58,    // .bbw.bb
    50,    // bbbw.bb
    38,    // wbbw.bb
    17,    // .wbw.bb
    53,    // bwbw.bb
    108,   // wwbw.bb
    29,    // ..ww.bb
    -30,   // b.ww.bb
    46,    // w.ww.bb
    -70,   // .bww.bb
    -40,   // bbww.bb
    -36,   // wbww.bb
    -5,    // .www.bb
    7,     // bwww.bb
    -48,   // wwww.bb
    170,   // ....bbb
    -27,   // b...bbb
    45,    // w...bbb
    22,    // .b..bbb
    80,    // bb..bbb
    32,    // wb..bbb
    55,    // .w..bbb
    -4,    // bw..bbb
    -26,   // ww..bbb
    123,   // ..b.bbb
    54,    // b.b.bbb
    -25,   // w.b.bbb
    23,    // .bb.bbb
    44,    // bbb.bbb
    5,     // wbb.bbb
    10,    // .wb.bbb
    -61,   // bwb.bbb
    -63,   // wwb.bbb
    46,    // ..w.bbb
    15,    // b.w.bbb
    13,    // w.w.bbb
    42,    // .bw.bbb
    63,    // bbw.bbb
    -50,   // wbw.bbb
    58,    // .ww.bbb
    -15,   // bww.bbb
    0,     // www.bbb
    323,   // ...bbbb
    8,     // b..bbbb
    68,    // w..bbbb
    -74,   // .b.bbbb
    -67,   // bb.bbbb
    57,    // wb.bbbb
    207,   // .w.bbbb
    69,    // bw.bbbb
    48,    // ww.bbbb
    51,    // ..bbbbb
    -68,   // b.bbbbb
    45,    // w.bbbbb
    -20,   // .bbbbbb
    -34,   // bbbbbbb
    -27,   // wbbbbbb
    98,    // .wbbbbb
    -13,   // bwbbbbb
    60,    // wwbbbbb
    49,    // ..wbbbb
    56,    // b.wbbbb
    -16,   // w.wbbbb
    -67,   // .bwbbbb
    -26,   // bbwbbbb
    63,    // wbwbbbb
    8,     // .wwbbbb
    -19,   // bwwbbbb
    -80,   // wwwbbbb
    50,    // ...wbbb
    54,    // b..wbbb
    -13,   // w..wbbb
    -72,   // .b.wbbb
    50,    // bb.wbbb
    27,    // wb.wbbb
    -62,   // .w.wbbb
    26,    // bw.wbbb
    -6,    // ww.wbbb
    -139,  // ..bwbbb
    -55,   // b.bwbbb
    99,    // w.bwbbb
    -18,   // .bbwbbb
    40,    // bbbwbbb
    -160,  // wbbwbbb
    -14,   // .wbwbbb
    15,    // bwbwbbb
    -9,    // wwbwbbb
    70,    // ..wwbbb
    67,    // b.wwbbb
    -87,   // w.wwbbb
    -25,   // .bwwbbb
    24,    // bbwwbbb
    -48,   // wbwwbbb
    18,    // .wwwbbb
    27,    // bwwwbbb
    80,    // wwwwbbb
    -55,   // ....wbb
    -7,    // b...wbb
    -16,   // w...wbb
    -10,   // .b..wbb
    33,    // bb..wbb
    24,    // wb..wbb
    -43,   // .w..wbb
    72,    // bw..wbb
    -13,   // ww..wbb
    -39,   // ..b.wbb
    17,    // b.b.wbb
    9,     // w.b.wbb
    -17,   // .bb.wbb
    63,    // bbb.wbb
    -6,    // wbb.wbb
    -1,    // .wb.wbb
    30,    // bwb.wbb
    0,     // wwb.wbb
    14,    // ..w.wbb
    -7,    // b.w.wbb
    61,    // w.w.wbb
    -4,    // .bw.wbb
    -95,   // bbw.wbb
    -78,   // wbw.wbb
    47,    // .ww.wbb
    -4,    // bww.wbb
    63,    // www.wbb
    -55,   // ...bwbb
    -57,   // b..bwbb
    3,     // w..bwbb
    20,    // .b.bwbb
    29,    // bb.bwbb
    40,    // wb.bwbb
    -17,   // .w.bwbb
    -53,   // bw.bwbb
    -108,  // ww.bwbb
    -25,   // ..bbwbb
    -19,   // b.bbwbb
    61,    // w.bbwbb
    -90,   // .bbbwbb
    -26,   // bbbbwbb
    27,    // wbbbwbb
    21,    // .wbbwbb
    20,    // bwbbwbb
    53,    // wwbbwbb
    29,    // ..wbwbb
    -11,   // b.wbwbb
    -84,   // w.wbwbb
    4,     // .bwbwbb
    -28,   // bbwbwbb
    142,   // wbwbwbb
    -113,  // .wwbwbb
    -1,    // bwwbwbb
    9,     // wwwbwbb
    -26,   // ...wwbb
    -50,   // b..wwbb
    67,    // w..wwbb
    -9,    // .b.wwbb
    -40,   // bb.wwbb
    3,     // wb.wwbb
    20,    // .w.wwbb
    82,    // bw.wwbb
    73,    // ww.wwbb
    63,    // ..bwwbb
    -10,   // b.bwwbb
    61,    // w.bwwbb
    -105,  // .bbwwbb
    24,    // bbbwwbb
    15,    // wbbwwbb
    -85,   // .wbwwbb
    -21,   // bwbwwbb
    -53,   // wwbwwbb
    38,    // ..wwwbb
    4,     // b.wwwbb
    -8,    // w.wwwbb
    29,    // .bwwwbb
    0,     // bbwwwbb
    -21,   // wbwwwbb
    25,    // .wwwwbb
    -11,   // bwwwwbb
    -60,   // wwwwwbb
    9,     // .....wb
    40,    // b....wb
    -4,    // w....wb
    11,    // .b...wb
    17,    // bb...wb
    0,     // wb...wb
    -16,   // .w...wb
    -114,  // bw...wb
    40,    // ww...wb
    16,    // ..b..wb
    47,    // b.b..wb
    -120,  // w.b..wb
    22,    // .bb..wb
    -4,    // bbb..wb
    -55,   // wbb..wb
    79,    // .wb..wb
    -48,   // bwb..wb
    -24,   // wwb..wb
    -45,   // ..w..wb
    19,    // b.w..wb
    -93,   // w.w..wb
    -12,   // .bw..wb
    72,    // bbw..wb
    40,    // wbw..wb
    22,    // .ww..wb
    -45,   // bww..wb
    -32,   // www..wb
    18,    // ...b.wb
    -58,   // b..b.wb
    53,    // w..b.wb
    4,     // .b.b.wb
    -49,   // bb.b.wb
    25,    // wb.b.wb
    36,    // .w.b.wb
    -69,   // bw.b.wb
    -2,    // ww.b.wb
    11,    // ..bb.wb
    29,    // b.bb.wb
    -60,   // w.bb.wb
    102,   // .bbb.wb
    69,    // bbbb.wb
    -10,   // wbbb.wb
    10,    // .wbb.wb
    -36,   // bwbb.wb
    -3,    // wwbb.wb
    12,    // ..wb.wb
    51,    // b.wb.wb
    -38,   // w.wb.wb
    -26,   // .bwb.wb
    -53,   // bbwb.wb
    -46,   // wbwb.wb
    -53,   // .wwb.wb
    123,   // bwwb.wb
    -27,   // wwwb.wb
    41,    // ...w.wb
    -57,   // b..w.wb
    41,    // w..w.wb
    55,    // .b.w.wb
    23,    // bb.w.wb
    -25,   // wb.w.wb
    -2,    // .w.w.wb
    8,     // bw.w.wb
    -59,   // ww.w.wb
    19,    // ..bw.wb
    -16,   // b.bw.wb
    -29,   // w.bw.wb
    -34,   // .bbw.wb
    26,    // bbbw.wb
    -34,   // wbbw.wb
    70,    // .wbw.wb
    28,    // bwbw.wb
    -40,   // wwbw.wb
    -10,   // ..ww.wb
    23,    // b.ww.wb
    76,    // w.ww.wb
    16,    // .bww.wb
    82,    // bbww.wb
    48,    // wbww.wb
    -85,   // .www.wb
    -76,   // bwww.wb
    -57,   // wwww.wb
    46,    // ....bwb
    -10,   // b...bwb
    16,    // w...bwb
    -10,   // .b..bwb
    -69,   // bb..bwb
    -40,   // wb..bwb
    57,    // .w..bwb
    -48,   // bw..bwb
    -9,    // ww..bwb
    -64,   // ..b.bwb
    -52,   // b.b.bwb
    -69,   // w.b.bwb
    -45,   // .bb.bwb
    -61,   // bbb.bwb
    33,    // wbb.bwb
    -4,    // .wb.bwb
    -1,    // bwb.bwb
    78,    // wwb.bwb
    38,    // ..w.bwb
    78,    // b.w.bwb
    -19,   // w.w.bwb
    -16,   // .bw.bwb
    30,    // bbw.bwb
    0,     // wbw.bwb
    75,    // .ww.bwb
    45,    // bww.bwb
    50,    // www.bwb
    3,     // ...bbwb
    154,   // b..bbwb
    -33,   // w..bbwb
    0,     // .b.bbwb
    -16,   // bb.bbwb
    -48,   // wb.bbwb
    -131,  // .w.bbwb
    -36,   // bw.bbwb
    36,    // ww.bbwb
    -44,   // ..bbbwb
    -40,   // b.bbbwb
    -27,   // w.bbbwb
    -11,   // .bbbbwb
    -13,   // bbbbbwb
    -107,  // wbbbbwb
    74,    // .wbbbwb
    72,    // bwbbbwb
    21,    // wwbbbwb
    3,     // ..wbbwb
    17,    // b.wbbwb
    -14,   // w.wbbwb
    -42,   // .bwbbwb
    20,    // bbwbbwb
    83,    // wbwbbwb
    -15,   // .wwbbwb
    -15,   // bwwbbwb
    48,    // wwwbbwb
    2,     // ...wbwb
    -75,   // b..wbwb
    32,    // w..wbwb
    31,    // .b.wbwb
    53,    // bb.wbwb
    46,    // wb.wbwb
    -16,   // .w.wbwb
    28,    // bw.wbwb
    -3,    // ww.wbwb
    -18,   // ..bwbwb
    31,    // b.bwbwb
    52,    // w.bwbwb
    -50,   // .bbwbwb
    15,    // bbbwbwb
    -2,    // wbbwbwb
    31,    // .wbwbwb
    -58,   // bwbwbwb
    -142,  // wwbwbwb
    -44,   // ..wwbwb
    36,    // b.wwbwb
    -38,   // w.wwbwb
    -58,   // .bwwbwb
    -21,   // bbwwbwb
    -83,   // wbwwbwb
    -56,   // .wwwbwb
    -9,    // bwwwbwb
    -63,   // wwwwbwb
    83,    // ....wwb
    -48,   // b...wwb
    65,    // w...wwb
    7,     // .b..wwb
    -5,    // bb..wwb
    55,    // wb..wwb
    -116,  // .w..wwb
    -45,   // bw..wwb
    19,    // ww..wwb
    7,     // ..b.wwb
    58,    // b.b.wwb
    -80,   // w.b.wwb
    58,    // .bb.wwb
    -15,   // bbb.wwb
    0,     // wbb.wwb
    -23,   // .wb.wwb
    45,    // bwb.wwb
    6,     // wwb.wwb
    48,    // ..w.wwb
    15,    // b.w.wwb
    4,     // w.w.wwb
    -64,   // .bw.wwb
    -4,    // bbw.wwb
    -33,   // wbw.wwb
    41,    // .ww.wwb
    -65,   // bww.wwb
    -5,    // www.wwb
    28,    // ...bwwb
    -5,    // b..bwwb
    19,    // w..bwwb
    26,    // .b.bwwb
    3,     // bb.bwwb
    34,    // wb.bwwb
    79,    // .w.bwwb
    123,   // bw.bwwb
    -38,   // ww.bwwb
    -114,  // ..bbwwb
    -76,   // b.bbwwb
    -67,   // w.bbwwb
    41,    // .bbbwwb
    -19,   // bbbbwwb
    35,    // wbbbwwb
    64,    // .wbbwwb
    -15,   // bwbbwwb
    -15,   // wwbbwwb
    -65,   // ..wbwwb
    31,    // b.wbwwb
    56,    // w.wbwwb
    110,   // .bwbwwb
    -1,    // bbwbwwb
    2,     // wbwbwwb
    66,    // .wwbwwb
    10,    // bwwbwwb
    160,   // wwwbwwb
    105,   // ...wwwb
    13,    // b..wwwb
    97,    // w..wwwb
    48,    // .b.wwwb
    7,     // bb.wwwb
    10,    // wb.wwwb
    -93,   // .w.wwwb
    -76,   // bw.wwwb
    -4,    // ww.wwwb
    -1,    // ..bwwwb
    25,    // b.bwwwb
    5,     // w.bwwwb
    61,    // .bbwwwb
    27,    // bbbwwwb
    -35,   // wbbwwwb
    3,     // .wbwwwb
    -9,    // bwbwwwb
    -27,   // wwbwwwb
    -48,   // ..wwwwb
    2,     // b.wwwwb
    -6,    // w.wwwwb
    105,   // .bwwwwb
    -11,   // bbwwwwb
    107,   // wbwwwwb
    31,    // .wwwwwb
    23,    // bwwwwwb
    27,    // wwwwwwb
    -9,    // ......w
    0,     // b.....w
    50,    // w.....w
    -51,   // .b....w
    -11,   // bb....w
    -40,   // wb....w
    4,     // .w....w
    -4,    // bw....w
    10,    // ww....w
    -20,   // ..b...w
    -56,   // b.b...w
    -1,    // w.b...w
    36,    // .bb...w
    45,    // bbb...w
    48,    // wbb...w
    9,     // .wb...w
    16,    // bwb...w
    7,     // wwb...w
    -22,   // ..w...w
    23,    // b.w...w
    -57,   // w.w...w
    36,    // .bw...w
    -16,   // bbw...w
    10,    // wbw...w
    25,    // .ww...w
    65,    // bww...w
    27,    // www...w
    -16,   // ...b..w
    74,    // b..b..w
    72,    // w..b..w
    -31,   // .b.b..w
    -17,   // bb.b..w
    57,    // wb.b..w
    26,    // .w.b..w
    53,    // bw.b..w
    -4,    // ww.b..w
    20,    // ..bb..w
    -35,   // b.bb..w
    44,    // w.bb..w
    -26,   // .bbb..w
    68,    // bbbb..w
    -13,   // wbbb..w
    16,    // .wbb..w
    -33,   // bwbb..w
    50,    // wwbb..w
    -81,   // ..wb..w
    -23,   // b.wb..w
    -26,   // w.wb..w
    59,    // .bwb..w
    3,     // bbwb..w
    75,    // wbwb..w
    -21,   // .wwb..w
    19,    // bwwb..w
    -54,   // wwwb..w
    -1,    // ...w..w
    -74,   // b..w..w
    -8,    // w..w..w
    -17,   // .b.w..w
    -110,  // bb.w..w
    58,    // wb.w..w
    61,    // .w.w..w
    41,    // bw.w..w
    -17,   // ww.w..w
    40,    // ..bw..w
    -19,   // b.bw..w
    6,     // w.bw..w
    -4,    // .bbw..w
    -13,   // bbbw..w
    5,     // wbbw..w
    -26,   // .wbw..w
    32,    // bwbw..w
    57,    // wwbw..w
    29,    // ..ww..w
    -22,   // b.ww..w
    60,    // w.ww..w
    13,    // .bww..w
    67,    // bbww..w
    -154,  // wbww..w
    -32,   // .www..w
    97,    // bwww..w
    -8,    // wwww..w
    -32,   // ....b.w
    -23,   // b...b.w
    -1,    // w...b.w
    -33,   // .b..b.w
    55,    // bb..b.w
    -19,   // wb..b.w
    31,    // .w..b.w
    -120,  // bw..b.w
    -9,    // ww..b.w
    -41,   // ..b.b.w
    51,    // b.b.b.w
    -44,   // w.b.b.w
    20,    // .bb.b.w
    -25,   // bbb.b.w
    -15,   // wbb.b.w
    -6,    // .wb.b.w
    -69,   // bwb.b.w
    7,     // wwb.b.w
    -31,   // ..w.b.w
    0,     // b.w.b.w
    -28,   // w.w.b.w
    18,    // .bw.b.w
    9,     // bbw.b.w
    -78,   // wbw.b.w
    49,    // .ww.b.w
    -80,   // bww.b.w
    -15,   // www.b.w
    38,    // ...bb.w
    22,    // b..bb.w
    44,    // w..bb.w
    92,    // .b.bb.w
    33,    // bb.bb.w
    -23,   // wb.bb.w
    0,     // .w.bb.w
    -60,   // bw.bb.w
    30,    // ww.bb.w
    -31,   // ..bbb.w
    -31,   // b.bbb.w
    64,    // w.bbb.w
    68,    // .bbbb.w
    45,    // bbbbb.w
    -2,    // wbbbb.w
    -106,  // .wbbb.w
    -27,   // bwbbb.w
    -4,    // wwbbb.w
    -28,   // ..wbb.w
    2,     // b.wbb.w
    -25,   // w.wbb.w
    -12,   // .bwbb.w
    61,    // bbwbb.w
    -36,   // wbwbb.w
    39,    // .wwbb.w
    -67,   // bwwbb.w
    -67,   // wwwbb.w
    -70,   // ...wb.w
    23,    // b..wb.w
    6,     // w..wb.w
    34,    // .b.wb.w
    -3,    // bb.wb.w
    -51,   // wb.wb.w
    51,    // .w.wb.w
    -29,   // bw.wb.w
    -1,    // ww.wb.w
    -1,    // ..bwb.w
    15,    // b.bwb.w
    37,    // w.bwb.w
    -33,   // .bbwb.w
    99,    // bbbwb.w
    -31,   // wbbwb.w
    48,    // .wbwb.w
    52,    // bwbwb.w
    11,    // wwbwb.w
    15,    // ..wwb.w
    -2,    // b.wwb.w
    -5,    // w.wwb.w
    -50,   // .bwwb.w
    61,    // bbwwb.w
    -17,   // wbwwb.w
    13,    // .wwwb.w
    5,     // bwwwb.w
    -56,   // wwwwb.w
    -75,   // ....w.w
    56,    // b...w.w
    -57,   // w...w.w
    -15,   // .b..w.w
    11,    // bb..w.w
    -47,   // wb..w.w
    -35,   // .w..w.w
    -93,   // bw..w.w
    53,    // ww..w.w
    -47,   // ..b.w.w
    0,     // b.b.w.w
    -28,   // w.b.w.w
    16,    // .bb.w.w
    13,    // bbb.w.w
    -58,   // wbb.w.w
    38,    // .wb.w.w
    -19,   // bwb.w.w
    -17,   // wwb.w.w
    -25,   // ..w.w.w
    -51,   // b.w.w.w
    -25,   // w.w.w.w
    68,    // .bw.w.w
    61,    // bbw.w.w
    52,    // wbw.w.w
    -4,    // .ww.w.w
    4,     // bww.w.w
    -54,   // www.w.w
    -50,   // ...bw.w
    19,    // b..bw.w
    -26,   // w..bw.w
    -70,   // .b.bw.w
    -41,   // bb.bw.w
    16,    // wb.bw.w
    -31,   // .w.bw.w
    -38,   // bw.bw.w
    -35,   // ww.bw.w
    -35,   // ..bbw.w
    88,    // b.bbw.w
    -25,   // w.bbw.w
    -13,   // .bbbw.w
    -16,   // bbbbw.w
    -25,   // wbbbw.w
    48,    // .wbbw.w
    -14,   // bwbbw.w
    10,    // wwbbw.w
    -28,   // ..wbw.w
    -15,   // b.wbw.w
    -46,   // w.wbw.w
    5,     // .bwbw.w
    -84,   // bbwbw.w
    -31,   // wbwbw.w
    128,   // .wwbw.w
    56,    // bwwbw.w
    55,    // wwwbw.w
    -61,   // ...ww.w
    35,    // b..ww.w
    60,    // w..ww.w
    -63,   // .b.ww.w
    46,    // bb.ww.w
    -29,   // wb.ww.w
    19,    // .w.ww.w
    76,    // bw.ww.w
    50,    // ww.ww.w
    81,    // ..bww.w
    -88,   // b.bww.w
    -5,    // w.bww.w
    24,    // .bbww.w
    -87,   // bbbww.w
    76,    // wbbww.w
    21,    // .wbww.w
    -38,   // bwbww.w
    19,    // wwbww.w
    -97,   // ..www.w
    31,    // b.www.w
    -54,   // w.www.w
    -114,  // .bwww.w
    -8,    // bbwww.w
    40,    // wbwww.w
    -57,   // .wwww.w
    -6,    // bwwww.w
    68,    // wwwww.w
    -9,    // .....bw
    4,     // b....bw
    -40,   // w....bw
    16,    // .b...bw
    -40,   // bb...bw
    114,   // wb...bw
    -11,   // .w...bw
    0,     // bw...bw
    -17,   // ww...bw
    45,    // ..b..bw
    93,    // b.b..bw
    -19,   // w.b..bw
    -22,   // .bb..bw
    32,    // bbb..bw
    45,    // wbb..bw
    12,    // .wb..bw
    -40,   // bwb..bw
    -72,   // wwb..bw
    -16,   // ..w..bw
    120,   // b.w..bw
    -47,   // w.w..bw
    -79,   // .bw..bw
    24,    // bbw..bw
    48,    // wbw..bw
    -22,   // .ww..bw
    55,    // bww..bw
    4,     // www..bw
    -41,   // ...b.bw
    -41,   // b..b.bw
    57,    // w..b.bw
    2,     // .b.b.bw
    59,    // bb.b.bw
    -8,    // wb.b.bw
    -55,   // .w.b.bw
    25,    // bw.b.bw
    -23,   // ww.b.bw
    10,    // ..bb.bw
    -76,   // b.bb.bw
    -23,   // w.bb.bw
    85,    // .bbb.bw
    57,    // bbbb.bw
    76,    // wbbb.bw
    -16,   // .wbb.bw
    -48,   // bwbb.bw
    -82,   // wwbb.bw
    -19,   // ..wb.bw
    29,    // b.wb.bw
    16,    // w.wb.bw
    -70,   // .bwb.bw
    40,    // bbwb.bw
    -28,   // wbwb.bw
    34,    // .wwb.bw
    34,    // bwwb.bw
    -26,   // wwwb.bw
    -18,   // ...w.bw
    -53,   // b..w.bw
    58,    // w..w.bw
    -36,   // .b.w.bw
    2,     // bb.w.bw
    69,    // wb.w.bw
    -4,    // .w.w.bw
    -25,   // bw.w.bw
    49,    // ww.w.bw
    -12,   // ..bw.bw
    38,    // b.bw.bw
    -51,   // w.bw.bw
    53,    // .bbw.bw
    27,    // bbbw.bw
    -123,  // wbbw.bw
    26,    // .wbw.bw
    46,    // bwbw.bw
    53,    // wwbw.bw
    -11,   // ..ww.bw
    60,    // b.ww.bw
    -29,   // w.ww.bw
    -10,   // .bww.bw
    3,     // bbww.bw
    36,    // wbww.bw
    -102,  // .www.bw
    10,    // bwww.bw
    -69,   // wwww.bw
    -83,   // ....bbw
    -65,   // b...bbw
    48,    // w...bbw
    116,   // .b..bbw
    -19,   // bb..bbw
    45,    // wb..bbw
    -7,    // .w..bbw
    -55,   // bw..bbw
    5,     // ww..bbw
    -48,   // ..b.bbw
    -4,    // b.b.bbw
    -15,   // w.b.bbw
    -41,   // .bb.bbw
    5,     // bbb.bbw
    65,    // wbb.bbw
    64,    // .wb.bbw
    33,    // bwb.bbw
    4,     // wwb.bbw
    -7,    // ..w.bbw
    80,    // b.w.bbw
    -58,   // w.w.bbw
    23,    // .bw.bbw
    -6,    // bbw.bbw
    -45,   // wbw.bbw
    -58,   // .ww.bbw
    0,     // bww.bbw
    15,    // www.bbw
    -105,  // ...bbbw
    -97,   // b..bbbw
    -13,   // w..bbbw
    93,    // .b.bbbw
    4,     // bb.bbbw
    76,    // wb.bbbw
    -48,   // .w.bbbw
    -10,   // bw.bbbw
    -7,    // ww.bbbw
    48,    // ..bbbbw
    6,     // b.bbbbw
    -2,    // w.bbbbw
    -31,   // .bbbbbw
    -27,   // bbbbbbw
    -23,   // wbbbbbw
    -105,  // .wbbbbw
    -107,  // bwbbbbw
    11,    // wwbbbbw
    1,     // ..wbbbw
    -5,    // b.wbbbw
    -25,   // w.wbbbw
    -3,    // .bwbbbw
    27,    // bbwbbbw
    9,     // wbwbbbw
    -61,   // .wwbbbw
    35,    // bwwbbbw
    -27,   // wwwbbbw
    -28,   // ...wbbw
    -19,   // b..wbbw
    5,     // w..wbbw
    -79,   // .b.wbbw
    38,    // bb.wbbw
    -123,  // wb.wbbw
    -26,   // .w.wbbw
    -34,   // bw.wbbw
    -3,    // ww.wbbw
    65,    // ..bwbbw
    -56,   // b.bwbbw
    -31,   // w.bwbbw
    -66,   // .bbwbbw
    -160,  // bbbwbbw
    -10,   // wbbwbbw
    -110,  // .wbwbbw
    -2,    // bwbwbbw
    1,     // wwbwbbw
    114,   // ..wwbbw
    67,    // b.wwbbw
    76,    // w.wwbbw
    -64,   // .bwwbbw
    15,    // bbwwbbw
    15,    // wbwwbbw
    -41,   // .wwwbbw
    -35,   // bwwwbbw
    19,    // wwwwbbw
    -46,   // ....wbw
    -16,   // b...wbw
    10,    // w...wbw
    -57,   // .b..wbw
    9,     // bb..wbw
    48,    // wb..wbw
    10,    // .w..wbw
    40,    // bw..wbw
    69,    // ww..wbw
    -38,   // ..b.wbw
    19,    // b.b.wbw
    -78,   // w.b.wbw
    -75,   // .bb.wbw
    -50,   // bbb.wbw
    -45,   // wbb.wbw
    16,    // .wb.wbw
    0,     // bwb.wbw
    -30,   // wwb.wbw
    64,    // ..w.wbw
    69,    // b.w.wbw
    52,    // w.w.wbw
    4,     // .bw.wbw
    -78,   // bbw.wbw
    1,     // wbw.wbw
    45,    // .ww.wbw
    -33,   // bww.wbw
    61,    // www.wbw
    -2,    // ...bwbw
    -32,   // b..bwbw
    75,    // w..bwbw
    16,    // .b.bwbw
    3,     // bb.bwbw
    -28,   // wb.bwbw
    -31,   // .w.bwbw
    -46,   // bw.bwbw
    -53,   // ww.bwbw
    44,    // ..bbwbw
    38,    // b.bbwbw
    -36,   // w.bbwbw
    56,    // .bbbwbw
    63,    // bbbbwbw
    9,     // wbbbwbw
    58,    // .wbbwbw
    83,    // bwbbwbw
    21,    // wwbbwbw
    18,    // ..wbwbw
    -52,   // b.wbwbw
    -31,   // w.wbwbw
    -31,   // .bwbwbw
    142,   // bbwbwbw
    58,    // wbwbwbw
    50,    // .wwbwbw
    2,     // bwwbwbw
    -15,   // wwwbwbw
    -3,    // ...wwbw
    33,    // b..wwbw
    -154,  // w..wwbw
    131,   // .b.wwbw
    -36,   // bb.wwbw
    36,    // wb.wwbw
    0,     // .w.wwbw
    48,    // bw.wwbw
    16,    // ww.wwbw
    -3,    // ..bwwbw
    14,    // b.bwwbw
    -17,   // w.bwwbw
    15,    // .bbwwbw
    -48,   // bbbwwbw
    15,    // wbbwwbw
    42,    // .wbwwbw
    -83,   // bwbwwbw
    -20,   // wwbwwbw
    44,    // ..wwwbw
    27,    // b.wwwbw
    40,    // w.wwwbw
    -74,   // .bwwwbw
    -21,   // bbwwwbw
    -72,   // wbwwwbw
    11,    // .wwwwbw
    107,   // bwwwwbw
    13,    // wwwwwbw
    -10,   // .....ww
    11,    // b....ww
    10,    // w....ww
    -6,    // .b...ww
    0,     // bb...ww
    -17,   // wb...ww
    -5,    // .w...ww
    40,    // bw...ww
    6,     // ww...ww
    40,    // ..b..ww
    -11,   // b.b..ww
    -9,    // w.b..ww
    -86,   // .bb..ww
    -26,   // bbb..ww
    5,     // wbb..ww
    -42,   // .wb..ww
    -9,    // bwb..ww
    -33,   // wwb..ww
    -23,   // ..w..ww
    -55,   // b.w..ww
    53,    // w.w..ww
    -58,   // .bw..ww
    -13,   // bbw..ww
    69,    // wbw..ww
    -3,    // .ww..ww
    19,    // bww..ww
    -80,   // www..ww
    -43,   // ...b.ww
    110,   // b..b.ww
    -4,    // w..b.ww
    -26,   // .b.b.ww
    -3,    // bb.b.ww
    -23,   // wb.b.ww
    68,    // .w.b.ww
    -2,    // bw.b.ww
    -113,  // ww.b.ww
    -29,   // ..bb.ww
    -46,   // b.bb.ww
    30,    // w.bb.ww
    5,     // .bbb.ww
    48,    // bbbb.ww
    -7,    // wbbb.ww
    70,    // .wbb.ww
    36,    // bwbb.ww
    40,    // wwbb.ww
    57,    // ..wb.ww
    3,     // b.wb.ww
    -35,   // w.wb.ww
    -17,   // .bwb.ww
    -108,  // bbwb.ww
    -53,   // wbwb.ww
    -58,   // .wwb.ww
    -38,   // bwwb.ww
    -50,   // wwwb.ww
    -154,  // ...w.ww
    17,    // b..w.ww
    -17,   // w..w.ww
    -113,  // .b.w.ww
    3,     // bb.w.ww
    49,    // wb.w.ww
    44,    // .w.w.ww
    -59,   // bw.w.ww
    -26,   // ww.w.ww
    21,    // ..bw.ww
    41,    // b.bw.ww
    -1,    // w.bw.ww
    -72,   // .bbw.ww
    -6,    // bbbw.ww
    -3,    // wbbw.ww
    -22,   // .wbw.ww
    -3,    // bwbw.ww
    -29,   // wwbw.ww
    -10,   // ..ww.ww
    -33,   // b.ww.ww
    50,    // w.ww.ww
    -70,   // .bww.ww
    73,    // bbww.ww
    16,    // wbww.ww
    33,    // .www.ww
    -4,    // bwww.ww
    67,    // wwww.ww
    55,    // ....bww
    16,    // b...bww
    7,     // w...bww
    43,    // .b..bww
    13,    // bb..bww
    -72,   // wb..bww
    10,    // .w..bww
    -24,   // bw..bww
    -33,   // ww..bww
    -14,   // ..b.bww
    -61,   // b.b.bww
    7,     // w.b.bww
    -47,   // .bb.bww
    -63,   // bbb.bww
    4,     // wbb.bww
    4,     // .wb.bww
    78,    // bwb.bww
    95,    // wwb.bww
    39,    // ..w.bww
    -9,    // b.w.bww
    -17,   // w.w.bww
    1,     // .bw.bww
    0,     // bbw.bww
    -30,   // wbw.bww
    17,    // .ww.bww
    6,     // bww.bww
    -63,   // www.bww
    26,    // ...bbww
    -67,   // b..bbww
    50,    // w..bbww
    -20,   // .b.bbww
    -73,   // bb.bbww
    -82,   // wb.bbww
    9,     // .w.bbww
    -3,    // bw.bbww
    40,    // ww.bbww
    -38,   // ..bbbww
    8,     // b.bbbww
    -4,    // w.bbbww
    -25,   // .bbbbww
    60,    // bbbbbww
    11,    // wbbbbww
    -29,   // .wbbbww
    21,    // bwbbbww
    0,     // wwbbbww
    -63,   // ..wbbww
    -61,   // b.wbbww
    10,    // w.wbbww
    85,    // .bwbbww
    53,    // bbwbbww
    21,    // wbwbbww
    105,   // .wwbbww
    -15,   // bwwbbww
    -24,   // wwwbbww
    55,    // ...wbww
    -3,    // b..wbww
    57,    // w..wbww
    17,    // .b.wbww
    108,   // bb.wbww
    53,    // wb.wbww
    -20,   // .w.wbww
    -40,   // bw.wbww
    -29,   // ww.wbww
    -29,   // ..bwbww
    84,    // b.bwbww
    11,    // w.bwbww
    113,   // .bbwbww
    -9,    // bbbwbww
    1,     // wbbwbww
    -4,    // .wbwbww
    -142,  // bwbwbww
    28,    // wwbwbww
    25,    // ..wwbww
    -61,   // b.wwbww
    19,    // w.wwbww
    -21,   // .bwwbww
    -53,   // bbwwbww
    -20,   // wbwwbww
    90,    // .wwwbww
    -27,   // bwwwbww
    26,    // wwwwbww
    -170,  // ....www
    -45,   // b...www
    27,    // w...www
    -55,   // .b..www
    26,    // bb..www
    4,     // wb..www
    -22,   // .w..www
    -32,   // bw..www
    -80,   // ww..www
    -46,   // ..b.www
    -13,   // b.b.www
    -15,   // w.b.www
    -58,   // .bb.www
    0,     // bbb.www
    15,    // wbb.www
    -42,   // .wb.www
    50,    // bwb.www
    -63,   // wwb.www
    -123,  // ..w.www
    25,    // b.w.www
    -54,   // w.w.www
    -10,   // .bw.www
    63,    // bbw.www
    61,    // wbw.www
    -23,   // .ww.www
    -5,    // bww.www
    -44,   // www.www
    -50,   // ...bwww
    13,    // b..bwww
    -54,   // w..bwww
    62,    // .b.bwww
    6,     // bb.bwww
    -26,   // wb.bwww
    72,    // .w.bwww
    -27,   // bw.bwww
    -50,   // ww.bwww
    -70,   // ..bbwww
    87,    // b.bbwww
    -67,   // w.bbwww
    -18,   // .bbbwww
    -80,   // bbbbwww
    -27,   // wbbbwww
    25,    // .wbbwww
    48,    // bwbbwww
    -24,   // wwbbwww
    139,   // ..wbwww
    -99,   // b.wbwww
    55,    // w.wbwww
    14,    // .bwbwww
    9,     // bbwbwww
    -15,   // wbwbwww
    18,    // .wwbwww
    160,   // bwwbwww
    -40,   // wwwbwww
    -323,  // ...wwww
    -68,   // b..wwww
    -8,    // w..wwww
    -207,  // .b.wwww
    -48,   // bb.wwww
    -69,   // wb.wwww
    74,    // .w.wwww
    -57,   // bw.wwww
    67,    // ww.wwww
    -49,   // ..bwwww
    16,    // b.bwwww
    -56,   // w.bwwww
    -8,    // .bbwwww
    80,    // bbbwwww
    19,    // wbbwwww
    67,    // .wbwwww
    -63,   // bwbwwww
    26,    // wwbwwww
    -51,   // ..wwwww
    -45,   // b.wwwww
    68,    // w.wwwww
    -98,   // .bwwwww
    -60,   // bbwwwww
    13,    // wbwwwww
    20,    // .wwwwww
    27,    // bwwwwww
    34,    // wwwwwww
    0,     // captures=0 threats=0
    50,    // captures=0 threats=1
    50,    // captures=0 threats=2
    50,    // captures=0 threats=3
    50,    // captures=0 threats=4
    143,   // captures=0 additional threats
    50,    // captures=1 threats=0
    148,   // captures=1 threats=1
    148,   // captures=1 threats=2
    149,   // captures=1 threats=3
    149,   // captures=1 threats=4
    0,     // captures=1 additional threats
    50,    // captures=2 threats=0
    158,   // captures=2 threats=1
    159,   // captures=2 threats=2
    159,   // captures=2 threats=3
    160,   // captures=2 threats=4
    72,    // captures=2 additional threats
    60,    // captures=3 threats=0
    307,   // captures=3 threats=1
    666,   // captures=3 threats=2
    827,   // captures=3 threats=3
    831,   // captures=3 threats=4
    107,   // captures=3 additional threats
    231,   // captures=4 threats=0
    1500,  // captures=4 threats=1
    1503,  // captures=4 threats=2
    1503,  // captures=4 threats=3
    1503,  // captures=4 threats=4
    36,    // captures=4 additional threats
].into_boxed_slice()
