vec![
    0,     // .......
    4,     // b......
    -4,    // w......
    -5,    // .b.....
    11,    // bb.....
    -18,   // wb.....
    5,     // .w.....
    18,    // bw.....
    -11,   // ww.....
    -10,   // ..b....
    80,    // b.b....
    -28,   // w.b....
    5,     // .bb....
    148,   // bbb....
    -82,   // wbb....
    -11,   // .wb....
    38,    // bwb....
    60,    // wwb....
    10,    // ..w....
    28,    // b.w....
    -80,   // w.w....
    11,    // .bw....
    -60,   // bbw....
    -38,   // wbw....
    -5,    // .ww....
    82,    // bww....
    -148,  // www....
    -11,   // ...b...
    -6,    // b..b...
    0,     // w..b...
    -30,   // .b.b...
    135,   // bb.b...
    -53,   // wb.b...
    11,    // .w.b...
    22,    // bw.b...
    -35,   // ww.b...
    -14,   // ..bb...
    33,    // b.bb...
    33,    // w.bb...
    70,    // .bbb...
    363,   // bbbb...
    -119,  // wbbb...
    65,    // .wbb...
    -1,    // bwbb...
    14,    // wwbb...
    9,     // ..wb...
    42,    // b.wb...
    -55,   // w.wb...
    -42,   // .bwb...
    -54,   // bbwb...
    5,     // wbwb...
    -27,   // .wwb...
    26,    // bwwb...
    -19,   // wwwb...
    11,    // ...w...
    0,     // b..w...
    6,     // w..w...
    -11,   // .b.w...
    35,    // bb.w...
    -22,   // wb.w...
    30,    // .w.w...
    53,    // bw.w...
    -135,  // ww.w...
    -9,    // ..bw...
    55,    // b.bw...
    -42,   // w.bw...
    27,    // .bbw...
    19,    // bbbw...
    -26,   // wbbw...
    42,    // .wbw...
    -5,    // bwbw...
    54,    // wwbw...
    14,    // ..ww...
    -33,   // b.ww...
    -33,   // w.ww...
    -65,   // .bww...
    -14,   // bbww...
    1,     // wbww...
    -70,   // .www...
    119,   // bwww...
    -363,  // wwww...
    -10,   // ....b..
    22,    // b...b..
    -13,   // w...b..
    -10,   // .b..b..
    6,     // bb..b..
    36,    // wb..b..
    3,     // .w..b..
    15,    // bw..b..
    58,    // ww..b..
    -39,   // ..b.b..
    21,    // b.b.b..
    -66,   // w.b.b..
    -67,   // .bb.b..
    93,    // bbb.b..
    -42,   // wbb.b..
    -15,   // .wb.b..
    -72,   // bwb.b..
    -14,   // wwb.b..
    0,     // ..w.b..
    29,    // b.w.b..
    -61,   // w.w.b..
    -23,   // .bw.b..
    -40,   // bbw.b..
    -27,   // wbw.b..
    34,    // .ww.b..
    10,    // bww.b..
    -34,   // www.b..
    -14,   // ...bb..
    -36,   // b..bb..
    22,    // w..bb..
    6,     // .b.bb..
    9,     // bb.bb..
    0,     // wb.bb..
    -82,   // .w.bb..
    24,    // bw.bb..
    -22,   // ww.bb..
    35,    // ..bbb..
    70,    // b.bbb..
    -29,   // w.bbb..
    226,   // .bbbb..
    42,    // bbbbb..
    60,    // wbbbb..
    -57,   // .wbbb..
    -33,   // bwbbb..
    -23,   // wwbbb..
    -68,   // ..wbb..
    -26,   // b.wbb..
    -28,   // w.wbb..
    -24,   // .bwbb..
    -18,   // bbwbb..
    61,    // wbwbb..
    14,    // .wwbb..
    -90,   // bwwbb..
    -58,   // wwwbb..
    -9,    // ...wb..
    85,    // b..wb..
    37,    // w..wb..
    -43,   // .b.wb..
    -61,   // bb.wb..
    1,     // wb.wb..
    57,    // .w.wb..
    19,    // bw.wb..
    8,     // ww.wb..
    3,     // ..bwb..
    13,    // b.bwb..
    7,     // w.bwb..
    2,     // .bbwb..
    -173,  // bbbwb..
    48,    // wbbwb..
    38,    // .wbwb..
    0,     // bwbwb..
    -43,   // wwbwb..
    68,    // ..wwb..
    17,    // b.wwb..
    66,    // w.wwb..
    4,     // .bwwb..
    81,    // bbwwb..
    -9,    // wbwwb..
    -71,   // .wwwb..
    0,     // bwwwb..
    -57,   // wwwwb..
    10,    // ....w..
    13,    // b...w..
    -22,   // w...w..
    -3,    // .b..w..
    -58,   // bb..w..
    -15,   // wb..w..
    10,    // .w..w..
    -36,   // bw..w..
    -6,    // ww..w..
    0,     // ..b.w..
    61,    // b.b.w..
    -29,   // w.b.w..
    -34,   // .bb.w..
    34,    // bbb.w..
    -10,   // wbb.w..
    23,    // .wb.w..
    27,    // bwb.w..
    40,    // wwb.w..
    39,    // ..w.w..
    66,    // b.w.w..
    -21,   // w.w.w..
    15,    // .bw.w..
    14,    // bbw.w..
    72,    // wbw.w..
    67,    // .ww.w..
    42,    // bww.w..
    -93,   // www.w..
    9,     // ...bw..
    -37,   // b..bw..
    -85,   // w..bw..
    -57,   // .b.bw..
    -8,    // bb.bw..
    -19,   // wb.bw..
    43,    // .w.bw..
    -1,    // bw.bw..
    61,    // ww.bw..
    -68,   // ..bbw..
    -66,   // b.bbw..
    -17,   // w.bbw..
    71,    // .bbbw..
    57,    // bbbbw..
    0,     // wbbbw..
    -4,    // .wbbw..
    9,     // bwbbw..
    -81,   // wwbbw..
    -3,    // ..wbw..
    -7,    // b.wbw..
    -13,   // w.wbw..
    -38,   // .bwbw..
    43,    // bbwbw..
    0,     // wbwbw..
    -2,    // .wwbw..
    -48,   // bwwbw..
    173,   // wwwbw..
    14,    // ...ww..
    -22,   // b..ww..
    36,    // w..ww..
    82,    // .b.ww..
    22,    // bb.ww..
    -24,   // wb.ww..
    -6,    // .w.ww..
    0,     // bw.ww..
    -9,    // ww.ww..
    68,    // ..bww..
    28,    // b.bww..
    26,    // w.bww..
    -14,   // .bbww..
    58,    // bbbww..
    90,    // wbbww..
    24,    // .wbww..
    -61,   // bwbww..
    18,    // wwbww..
    -35,   // ..www..
    29,    // b.www..
    -70,   // w.www..
    57,    // .bwww..
    23,    // bbwww..
    33,    // wbwww..
    -226,  // .wwww..
    -60,   // bwwww..
    -42,   // wwwww..
    -5,    // .....b.
    1,     // b....b.
    -41,   // w....b.
    -24,   // .b...b.
    10,    // bb...b.
    8,     // wb...b.
    0,     // .w...b.
    16,    // bw...b.
    -14,   // ww...b.
    -10,   // ..b..b.
    25,    // b.b..b.
    -45,   // w.b..b.
    4,     // .bb..b.
    30,    // bbb..b.
    103,   // wbb..b.
    -18,   // .wb..b.
    5,     // bwb..b.
    37,    // wwb..b.
    -3,    // ..w..b.
    -22,   // b.w..b.
    -9,    // w.w..b.
    -27,   // .bw..b.
    -10,   // bbw..b.
    -69,   // wbw..b.
    -21,   // .ww..b.
    -10,   // bww..b.
    -41,   // www..b.
    -30,   // ...b.b.
    -56,   // b..b.b.
    -29,   // w..b.b.
    -14,   // .b.b.b.
    -50,   // bb.b.b.
    7,     // wb.b.b.
    -39,   // .w.b.b.
    5,     // bw.b.b.
    -29,   // ww.b.b.
    6,     // ..bb.b.
    -34,   // b.bb.b.
    98,    // w.bb.b.
    48,    // .bbb.b.
    -57,   // bbbb.b.
    82,    // wbbb.b.
    4,     // .wbb.b.
    9,     // bwbb.b.
    -9,    // wwbb.b.
    -57,   // ..wb.b.
    -33,   // b.wb.b.
    -65,   // w.wb.b.
    33,    // .bwb.b.
    27,    // bbwb.b.
    25,    // wbwb.b.
    17,    // .wwb.b.
    27,    // bwwb.b.
    49,    // wwwb.b.
    -11,   // ...w.b.
    -41,   // b..w.b.
    -1,    // w..w.b.
    -7,    // .b.w.b.
    -69,   // bb.w.b.
    -26,   // wb.w.b.
    39,    // .w.w.b.
    46,    // bw.w.b.
    -109,  // ww.w.b.
    -43,   // ..bw.b.
    18,    // b.bw.b.
    28,    // w.bw.b.
    41,    // .bbw.b.
    -45,   // bbbw.b.
    -76,   // wbbw.b.
    39,    // .wbw.b.
    24,    // bwbw.b.
    16,    // wwbw.b.
    82,    // ..ww.b.
    4,     // b.ww.b.
    -75,   // w.ww.b.
    42,    // .bww.b.
    -8,    // bbww.b.
    106,   // wbww.b.
    -13,   // .www.b.
    34,    // bwww.b.
    -162,  // wwww.b.
    5,     // ....bb.
    -28,   // b...bb.
    25,    // w...bb.
    4,     // .b..bb.
    6,     // bb..bb.
    -10,   // wb..bb.
    21,    // .w..bb.
    14,    // bw..bb.
    -63,   // ww..bb.
    -67,   // ..b.bb.
    -13,   // b.b.bb.
    3,     // w.b.bb.
    16,    // .bb.bb.
    48,    // bbb.bb.
    -32,   // wbb.bb.
    -65,   // .wb.bb.
    -60,   // bwb.bb.
    -37,   // wwb.bb.
    -34,   // ..w.bb.
    -50,   // b.w.bb.
    30,    // w.w.bb.
    -19,   // .bw.bb.
    -9,    // bbw.bb.
    -74,   // wbw.bb.
    0,     // .ww.bb.
    54,    // bww.bb.
    -47,   // www.bb.
    70,    // ...bbb.
    37,    // b..bbb.
    -21,   // w..bbb.
    48,    // .b.bbb.
    -25,   // bb.bbb.
    71,    // wb.bbb.
    13,    // .w.bbb.
    94,    // bw.bbb.
    36,    // ww.bbb.
    226,   // ..bbbb.
    56,    // b.bbbb.
    64,    // w.bbbb.
    -57,   // .bbbbb.
    -18,   // bbbbbb.
    -37,   // wbbbbb.
    101,   // .wbbbb.
    -9,    // bwbbbb.
    -17,   // wwbbbb.
    71,    // ..wbbb.
    -18,   // b.wbbb.
    1,     // w.wbbb.
    38,    // .bwbbb.
    -90,   // bbwbbb.
    64,    // wbwbbb.
    14,    // .wwbbb.
    36,    // bwwbbb.
    1,     // wwwbbb.
    27,    // ...wbb.
    19,    // b..wbb.
    5,     // w..wbb.
    41,    // .b.wbb.
    57,    // bb.wbb.
    78,    // wb.wbb.
    -17,   // .w.wbb.
    -34,   // bw.wbb.
    -58,   // ww.wbb.
    2,     // ..bwbb.
    -138,  // b.bwbb.
    -29,   // w.bwbb.
    25,    // .bbwbb.
    -7,    // bbbwbb.
    -53,   // wbbwbb.
    -3,    // .wbwbb.
    -60,   // bwbwbb.
    130,   // wwbwbb.
    -14,   // ..wwbb.
    -50,   // b.wwbb.
    13,    // w.wwbb.
    15,    // .bwwbb.
    -105,  // bbwwbb.
    20,    // wbwwbb.
    -14,   // .wwwbb.
    51,    // bwwwbb.
    14,    // wwwwbb.
    11,    // ....wb.
    -11,   // b...wb.
    30,    // w...wb.
    -27,   // .b..wb.
    39,    // bb..wb.
    -78,   // wb..wb.
    18,    // .w..wb.
    -20,   // bw..wb.
    -68,   // ww..wb.
    -23,   // ..b.wb.
    -43,   // b.b.wb.
    35,    // w.b.wb.
    -19,   // .bb.wb.
    57,    // bbb.wb.
    10,    // wbb.wb.
    0,     // .wb.wb.
    -19,   // bwb.wb.
    9,     // wwb.wb.
    15,    // ..w.wb.
    5,     // b.w.wb.
    61,    // w.w.wb.
    51,    // .bw.wb.
    -8,    // bbw.wb.
    -6,    // wbw.wb.
    65,    // .ww.wb.
    -62,   // bww.wb.
    -1,    // www.wb.
    -42,   // ...bwb.
    30,    // b..bwb.
    52,    // w..bwb.
    33,    // .b.bwb.
    18,    // bb.bwb.
    -89,   // wb.bwb.
    -39,   // .w.bwb.
    -15,   // bw.bwb.
    -21,   // ww.bwb.
    -24,   // ..bbwb.
    -2,    // b.bbwb.
    -21,   // w.bbwb.
    38,    // .bbbwb.
    -60,   // bbbbwb.
    -18,   // wbbbwb.
    15,    // .wbbwb.
    -32,   // bwbbwb.
    103,   // wwbbwb.
    -38,   // ..wbwb.
    -32,   // b.wbwb.
    -2,    // w.wbwb.
    4,     // .bwbwb.
    5,     // bbwbwb.
    -37,   // wbwbwb.
    3,     // .wwbwb.
    103,   // bwwbwb.
    29,    // wwwbwb.
    -65,   // ...wwb.
    -22,   // b..wwb.
    8,     // w..wwb.
    42,    // .b.wwb.
    -87,   // bb.wwb.
    -15,   // wb.wwb.
    -4,    // .w.wwb.
    4,     // bw.wwb.
    -54,   // ww.wwb.
    4,     // ..bwwb.
    -54,   // b.bwwb.
    -55,   // w.bwwb.
    15,    // .bbwwb.
    -29,   // bbbwwb.
    -55,   // wbbwwb.
    -15,   // .wbwwb.
    -54,   // bwbwwb.
    -24,   // wwbwwb.
    57,    // ..wwwb.
    105,   // b.wwwb.
    -98,   // w.wwwb.
    2,     // .bwwwb.
    21,    // bbwwwb.
    -81,   // wbwwwb.
    -101,  // .wwwwb.
    120,   // bwwwwb.
    -98,   // wwwwwb.
    5,     // .....w.
    41,    // b....w.
    -1,    // w....w.
    0,     // .b...w.
    14,    // bb...w.
    -16,   // wb...w.
    24,    // .w...w.
    -8,    // bw...w.
    -10,   // ww...w.
    3,     // ..b..w.
    9,     // b.b..w.
    22,    // w.b..w.
    21,    // .bb..w.
    41,    // bbb..w.
    10,    // wbb..w.
    27,    // .wb..w.
    69,    // bwb..w.
    10,    // wwb..w.
    10,    // ..w..w.
    45,    // b.w..w.
    -25,   // w.w..w.
    18,    // .bw..w.
    -37,   // bbw..w.
    -5,    // wbw..w.
    -4,    // .ww..w.
    -103,  // bww..w.
    -30,   // www..w.
    11,    // ...b.w.
    1,     // b..b.w.
    41,    // w..b.w.
    -39,   // .b.b.w.
    109,   // bb.b.w.
    -46,   // wb.b.w.
    7,     // .w.b.w.
    26,    // bw.b.w.
    69,    // ww.b.w.
    -82,   // ..bb.w.
    75,    // b.bb.w.
    -4,    // w.bb.w.
    13,    // .bbb.w.
    162,   // bbbb.w.
    -34,   // wbbb.w.
    -42,   // .wbb.w.
    -106,  // bwbb.w.
    8,     // wwbb.w.
    43,    // ..wb.w.
    -28,   // b.wb.w.
    -18,   // w.wb.w.
    -39,   // .bwb.w.
    -16,   // bbwb.w.
    -24,   // wbwb.w.
    -41,   // .wwb.w.
    76,    // bwwb.w.
    45,    // wwwb.w.
    30,    // ...w.w.
    29,    // b..w.w.
    56,    // w..w.w.
    39,    // .b.w.w.
    29,    // bb.w.w.
    -5,    // wb.w.w.
    14,    // .w.w.w.
    -7,    // bw.w.w.
    50,    // ww.w.w.
    57,    // ..bw.w.
    65,    // b.bw.w.
    33,    // w.bw.w.
    -17,   // .bbw.w.
    -49,   // bbbw.w.
    -27,   // wbbw.w.
    -33,   // .wbw.w.
    -25,   // bwbw.w.
    -27,   // wwbw.w.
    -6,    // ..ww.w.
    -98,   // b.ww.w.
    34,    // w.ww.w.
    -4,    // .bww.w.
    9,     // bbww.w.
    -9,    // wbww.w.
    -48,   // .www.w.
    -82,   // bwww.w.
    57,    // wwww.w.
    -11,   // ....bw.
    -30,   // b...bw.
    11,    // w...bw.
    -18,   // .b..bw.
    68,    // bb..bw.
    20,    // wb..bw.
    27,    // .w..bw.
    78,    // bw..bw.
    -39,   // ww..bw.
    -15,   // ..b.bw.
    -61,   // b.b.bw.
    -5,    // w.b.bw.
    -65,   // .bb.bw.
    1,     // bbb.bw.
    62,    // wbb.bw.
    -51,   // .wb.bw.
    6,     // bwb.bw.
    8,     // wwb.bw.
    23,    // ..w.bw.
    -35,   // b.w.bw.
    43,    // w.w.bw.
    0,     // .bw.bw.
    -9,    // bbw.bw.
    19,    // wbw.bw.
    19,    // .ww.bw.
    -10,   // bww.bw.
    -57,   // www.bw.
    65,    // ...bbw.
    -8,    // b..bbw.
    22,    // w..bbw.
    4,     // .b.bbw.
    54,    // bb.bbw.
    -4,    // wb.bbw.
    -42,   // .w.bbw.
    15,    // bw.bbw.
    87,    // ww.bbw.
    -57,   // ..bbbw.
    98,    // b.bbbw.
    -105,  // w.bbbw.
    101,   // .bbbbw.
    98,    // bbbbbw.
    -120,  // wbbbbw.
    -2,    // .wbbbw.
    81,    // bwbbbw.
    -21,   // wwbbbw.
    -4,    // ..wbbw.
    55,    // b.wbbw.
    54,    // w.wbbw.
    15,    // .bwbbw.
    24,    // bbwbbw.
    54,    // wbwbbw.
    -15,   // .wwbbw.
    55,    // bwwbbw.
    29,    // wwwbbw.
    42,    // ...wbw.
    -52,   // b..wbw.
    -30,   // w..wbw.
    39,    // .b.wbw.
    21,    // bb.wbw.
    15,    // wb.wbw.
    -33,   // .w.wbw.
    89,    // bw.wbw.
    -18,   // ww.wbw.
    38,    // ..bwbw.
    2,     // b.bwbw.
    32,    // w.bwbw.
    -3,    // .bbwbw.
    -29,   // bbbwbw.
    -103,  // wbbwbw.
    -4,    // .wbwbw.
    37,    // bwbwbw.
    -5,    // wwbwbw.
    24,    // ..wwbw.
    21,    // b.wwbw.
    2,     // w.wwbw.
    -15,   // .bwwbw.
    -103,  // bbwwbw.
    32,    // wbwwbw.
    -38,   // .wwwbw.
    18,    // bwwwbw.
    60,    // wwwwbw.
    -5,    // ....ww.
    -25,   // b...ww.
    28,    // w...ww.
    -21,   // .b..ww.
    63,    // bb..ww.
    -14,   // wb..ww.
    -4,    // .w..ww.
    10,    // bw..ww.
    -6,    // ww..ww.
    34,    // ..b.ww.
    -30,   // b.b.ww.
    50,    // w.b.ww.
    0,     // .bb.ww.
    47,    // bbb.ww.
    -54,   // wbb.ww.
    19,    // .wb.ww.
    74,    // bwb.ww.
    9,     // wwb.ww.
    67,    // ..w.ww.
    -3,    // b.w.ww.
    13,    // w.w.ww.
    65,    // .bw.ww.
    37,    // bbw.ww.
    60,    // wbw.ww.
    -16,   // .ww.ww.
    32,    // bww.ww.
    -48,   // www.ww.
    -27,   // ...bww.
    -5,    // b..bww.
    -19,   // w..bww.
    17,    // .b.bww.
    58,    // bb.bww.
    34,    // wb.bww.
    -41,   // .w.bww.
    -78,   // bw.bww.
    -57,   // ww.bww.
    14,    // ..bbww.
    -13,   // b.bbww.
    50,    // w.bbww.
    14,    // .bbbww.
    -14,   // bbbbww.
    -51,   // wbbbww.
    -15,   // .wbbww.
    -20,   // bwbbww.
    105,   // wwbbww.
    -2,    // ..wbww.
    29,    // b.wbww.
    138,   // w.wbww.
    3,     // .bwbww.
    -130,  // bbwbww.
    60,    // wbwbww.
    -25,   // .wwbww.
    53,    // bwwbww.
    7,     // wwwbww.
    -70,   // ...www.
    21,    // b..www.
    -37,   // w..www.
    -13,   // .b.www.
    -36,   // bb.www.
    -94,   // wb.www.
    -48,   // .w.www.
    -71,   // bw.www.
    25,    // ww.www.
    -71,   // ..bwww.
    -1,    // b.bwww.
    18,    // w.bwww.
    -14,   // .bbwww.
    -1,    // bbbwww.
    -36,   // wbbwww.
    -38,   // .wbwww.
    -64,   // bwbwww.
    90,    // wwbwww.
    -226,  // ..wwww.
    -64,   // b.wwww.
    -56,   // w.wwww.
    -101,  // .bwwww.
    17,    // bbwwww.
    9,     // wbwwww.
    57,    // .wwwww.
    37,    // bwwwww.
    18,    // wwwwww.
    4,     // ......b
    -51,   // b.....b
    0,     // w.....b
    1,     // .b....b
    -5,    // bb....b
    -2,    // wb....b
    41,    // .w....b
    38,    // bw....b
    -4,    // ww....b
    22,    // ..b...b
    47,    // b.b...b
    -34,   // w.b...b
    -28,   // .bb...b
    -36,   // bbb...b
    -50,   // wbb...b
    -30,   // .wb...b
    -29,   // bwb...b
    7,     // wwb...b
    13,    // ..w...b
    -11,   // b.w...b
    40,    // w.w...b
    -11,   // .bw...b
    -2,    // bbw...b
    7,     // wbw...b
    -25,   // .ww...b
    -56,   // bww...b
    -37,   // www...b
    -6,    // ...b..b
    -3,    // b..b..b
    71,    // w..b..b
    -56,   // .b.b..b
    3,     // bb.b..b
    -28,   // wb.b..b
    1,     // .w.b..b
    -59,   // bw.b..b
    108,   // ww.b..b
    -36,   // ..bb..b
    -79,   // b.bb..b
    0,     // w.bb..b
    37,    // .bbb..b
    3,     // bbbb..b
    -100,  // wbbb..b
    -8,    // .wbb..b
    138,   // bwbb..b
    -56,   // wwbb..b
    -37,   // ..wb..b
    2,     // b.wb..b
    27,    // w.wb..b
    30,    // .bwb..b
    -57,   // bbwb..b
    -33,   // wbwb..b
    -5,    // .wwb..b
    -6,    // bwwb..b
    20,    // wwwb..b
    0,     // ...w..b
    -67,   // b..w..b
    -71,   // w..w..b
    -41,   // .b.w..b
    4,     // bb.w..b
    -34,   // wb.w..b
    29,    // .w.w..b
    -48,   // bw.w..b
    4,     // ww.w..b
    85,    // ..bw..b
    16,    // b.bw..b
    23,    // w.bw..b
    19,    // .bbw..b
    48,    // bbbw..b
    -20,   // wbbw..b
    -52,   // .wbw..b
    -88,   // bwbw..b
    -9,    // wwbw..b
    -22,   // ..ww..b
    -47,   // b.ww..b
    36,    // w.ww..b
    -22,   // .bww..b
    -34,   // bbww..b
    18,    // wbww..b
    21,    // .www..b
    18,    // bwww..b
    -49,   // wwww..b
    80,    // ....b.b
    47,    // b...b.b
    -40,   // w...b.b
    25,    // .b..b.b
    -50,   // bb..b.b
    92,    // wb..b.b
    9,     // .w..b.b
    58,    // bw..b.b
    5,     // ww..b.b
    21,    // ..b.b.b
    18,    // b.b.b.b
    29,    // w.b.b.b
    -13,   // .bb.b.b
    55,    // bbb.b.b
    -19,   // wbb.b.b
    -61,   // .wb.b.b
    -37,   // bwb.b.b
    -73,   // wwb.b.b
    61,    // ..w.b.b
    23,    // b.w.b.b
    0,     // w.w.b.b
    -43,   // .bw.b.b
    14,    // bbw.b.b
    22,    // wbw.b.b
    -30,   // .ww.b.b
    66,    // bww.b.b
    -10,   // www.b.b
    33,    // ...bb.b
    -79,   // b..bb.b
    -36,   // w..bb.b
    -34,   // .b.bb.b
    -49,   // bb.bb.b
    -57,   // wb.bb.b
    75,    // .w.bb.b
    29,    // bw.bb.b
    -44,   // ww.bb.b
    70,    // ..bbb.b
    40,    // b.bbb.b
    -31,   // w.bbb.b
    56,    // .bbbb.b
    -64,   // bbbbb.b
    2,     // wbbbb.b
    98,    // .wbbb.b
    -41,   // bwbbb.b
    2,     // wwbbb.b
    -66,   // ..wbb.b
    14,    // b.wbb.b
    96,    // w.wbb.b
    -2,    // .bwbb.b
    -30,   // bbwbb.b
    25,    // wbwbb.b
    -13,   // .wwbb.b
    -73,   // bwwbb.b
    90,    // wwwbb.b
    55,    // ...wb.b
    16,    // b..wb.b
    -27,   // w..wb.b
    18,    // .b.wb.b
    26,    // bb.wb.b
    42,    // wb.wb.b
    65,    // .w.wb.b
    -16,   // bw.wb.b
    39,    // ww.wb.b
    13,    // ..bwb.b
    43,    // b.bwb.b
    5,     // w.bwb.b
    -138,  // .bbwb.b
    -56,   // bbbwb.b
    -50,   // wbbwb.b
    2,     // .wbwb.b
    31,    // bwbwb.b
    62,    // wwbwb.b
    28,    // ..wwb.b
    12,    // b.wwb.b
    -96,   // w.wwb.b
    -54,   // .bwwb.b
    -13,   // bbwwb.b
    5,     // wbwwb.b
    -1,    // .wwwb.b
    18,    // bwwwb.b
    23,    // wwwwb.b
    28,    // ....w.b
    -11,   // b...w.b
    34,    // w...w.b
    -22,   // .b..w.b
    7,     // bb..w.b
    109,   // wb..w.b
    45,    // .w..w.b
    21,    // bw..w.b
    -56,   // ww..w.b
    29,    // ..b.w.b
    23,    // b.b.w.b
    0,     // w.b.w.b
    -50,   // .bb.w.b
    14,    // bbb.w.b
    78,    // wbb.w.b
    -35,   // .wb.w.b
    63,    // bwb.w.b
    -1,    // wwb.w.b
    66,    // ..w.w.b
    45,    // b.w.w.b
    -29,   // w.w.w.b
    5,     // .bw.w.b
    -18,   // bbw.w.b
    70,    // wbw.w.b
    -3,    // .ww.w.b
    10,    // bww.w.b
    33,    // www.w.b
    42,    // ...bw.b
    2,     // b..bw.b
    -23,   // w..bw.b
    -33,   // .b.bw.b
    16,    // bb.bw.b
    51,    // wb.bw.b
    -28,   // .w.bw.b
    53,    // bw.bw.b
    5,     // ww.bw.b
    -26,   // ..bbw.b
    14,    // b.bbw.b
    15,    // w.bbw.b
    -18,   // .bbbw.b
    43,    // bbbbw.b
    -25,   // wbbbw.b
    55,    // .wbbw.b
    39,    // bwbbw.b
    -61,   // wwbbw.b
    -7,    // ..wbw.b
    -32,   // b.wbw.b
    -5,    // w.wbw.b
    -32,   // .bwbw.b
    -30,   // bbwbw.b
    -66,   // wbwbw.b
    29,    // .wwbw.b
    51,    // bwwbw.b
    -100,  // wwwbw.b
    -33,   // ...ww.b
    -47,   // b..ww.b
    0,     // w..ww.b
    4,     // .b.ww.b
    -7,    // bb.ww.b
    66,    // wb.ww.b
    -98,   // .w.ww.b
    35,    // bw.ww.b
    -38,   // ww.ww.b
    17,    // ..bww.b
    12,    // b.bww.b
    -15,   // w.bww.b
    -50,   // .bbww.b
    50,    // bbbww.b
    64,    // wbbww.b
    21,    // .wbww.b
    43,    // bwbww.b
    -60,   // wwbww.b
    29,    // ..www.b
    -60,   // b.www.b
    31,    // w.www.b
    105,   // .bwww.b
    5,     // bbwww.b
    19,    // wbwww.b
    -64,   // .wwww.b
    -4,    // bwwww.b
    -37,   // wwwww.b
    11,    // .....bb
    -5,    // b....bb
    4,     // w....bb
    10,    // .b...bb
    -25,   // bb...bb
    -39,   // wb...bb
    14,    // .w...bb
    7,     // bw...bb
    0,     // ww...bb
    6,     // ..b..bb
    -50,   // b.b..bb
    56,    // w.b..bb
    6,     // .bb..bb
    72,    // bbb..bb
    -23,   // wbb..bb
    68,    // .wb..bb
    -75,   // bwb..bb
    19,    // wwb..bb
    -58,   // ..w..bb
    7,     // b.w..bb
    -5,    // w.w..bb
    39,    // .bw..bb
    24,    // bbw..bb
    0,     // wbw..bb
    63,    // .ww..bb
    3,     // bww..bb
    36,    // www..bb
    135,   // ...b.bb
    3,     // b..b.bb
    -4,    // w..b.bb
    -50,   // .b.b.bb
    18,    // bb.b.bb
    66,    // wb.b.bb
    109,   // .w.b.bb
    -49,   // bw.b.bb
    15,    // ww.b.bb
    9,     // ..bb.bb
    -49,   // b.bb.bb
    38,    // w.bb.bb
    -25,   // .bbb.bb
    -62,   // bbbb.bb
    7,     // wbbb.bb
    54,    // .wbb.bb
    -10,   // bwbb.bb
    -77,   // wwbb.bb
    -8,    // ..wb.bb
    16,    // b.wb.bb
    -39,   // w.wb.bb
    18,    // .bwb.bb
    40,    // bbwb.bb
    6,     // wbwb.bb
    58,    // .wwb.bb
    2,     // bwwb.bb
    -1,    // wwwb.bb
    35,    // ...w.bb
    4,     // b..w.bb
    -108,  // w..w.bb
    -69,   // .b.w.bb
    109,   // bb.w.bb
    4,     // wb.w.bb
    29,    // .w.w.bb
    45,    // bw.w.bb
    -15,   // ww.w.bb
    -61,   // ..bw.bb
    26,    // b.bw.bb
    -5,    // w.bw.bb
    57,    // .bbw.bb
    40,    // bbbw.bb
    24,    // wbbw.bb
    21,    // .wbw.bb
    50,    // bwbw.bb
    92,    // wwbw.bb
    22,    // ..ww.bb
    -7,    // b.ww.bb
    44,    // w.ww.bb
    -87,   // .bww.bb
    -46,   // bbww.bb
    -35,   // wbww.bb
    -36,   // .www.bb
    -5,    // bwww.bb
    -50,   // wwww.bb
    148,   // ....bbb
    -36,   // b...bbb
    37,    // w...bbb
    30,    // .b..bbb
    72,    // bb..bbb
    45,    // wb..bbb
    41,    // .w..bbb
    -17,   // bw..bbb
    -36,   // ww..bbb
    93,    // ..b.bbb
    55,    // b.b.bbb
    -33,   // w.b.bbb
    48,    // .bb.bbb
    51,    // bbb.bbb
    -10,   // wbb.bbb
    1,     // .wb.bbb
    -61,   // bwb.bbb
    -62,   // wwb.bbb
    34,    // ..w.bbb
    14,    // b.w.bbb
    10,    // w.w.bbb
    57,    // .bw.bbb
    46,    // bbw.bbb
    -32,   // wbw.bbb
    47,    // .ww.bbb
    -36,   // bww.bbb
    0,     // www.bbb
    363,   // ...bbbb
    3,     // b..bbbb
    49,    // w..bbbb
    -57,   // .b.bbbb
    -62,   // bb.bbbb
    54,    // wb.bbbb
    162,   // .w.bbbb
    86,    // bw.bbbb
    50,    // ww.bbbb
    42,    // ..bbbbb
    -64,   // b.bbbbb
    37,    // w.bbbbb
    -18,   // .bbbbbb
    -44,   // bbbbbbb
    -8,    // wbbbbbb
    98,    // .wbbbbb
    -8,    // bwbbbbb
    43,    // wwbbbbb
    57,    // ..wbbbb
    43,    // b.wbbbb
    -23,   // w.wbbbb
    -60,   // .bwbbbb
    -23,   // bbwbbbb
    61,    // wbwbbbb
    -14,   // .wwbbbb
    -24,   // bwwbbbb
    -76,   // wwwbbbb
    19,    // ...wbbb
    48,    // b..wbbb
    -20,   // w..wbbb
    -45,   // .b.wbbb
    40,    // bb.wbbb
    41,    // wb.wbbb
    -49,   // .w.wbbb
    38,    // bw.wbbb
    1,     // ww.wbbb
    -173,  // ..bwbbb
    -56,   // b.bwbbb
    100,   // w.bwbbb
    -7,    // .bbwbbb
    32,    // bbbwbbb
    -167,  // wbbwbbb
    -29,   // .wbwbbb
    15,    // bwbwbbb
    2,     // wwbwbbb
    58,    // ..wwbbb
    50,    // b.wwbbb
    -90,   // w.wwbbb
    -29,   // .bwwbbb
    20,    // bbwwbbb
    -36,   // wbwwbbb
    -1,    // .wwwbbb
    17,    // bwwwbbb
    76,    // wwwwbbb
    -60,   // ....wbb
    -2,    // b...wbb
    -7,    // w...wbb
    -10,   // .b..wbb
    24,    // bb..wbb
    32,    // wb..wbb
    -37,   // .w..wbb
    62,    // bw..wbb
    -19,   // ww..wbb
    -40,   // ..b.wbb
    14,    // b.b.wbb
    1,     // w.b.wbb
    -9,    // .bb.wbb
    46,    // bbb.wbb
    -3,    // wbb.wbb
    -9,    // .wb.wbb
    19,    // bwb.wbb
    0,     // wwb.wbb
    14,    // ..w.wbb
    -18,   // b.w.wbb
    73,    // w.w.wbb
    -8,    // .bw.wbb
    -84,   // bbw.wbb
    -94,   // wbw.wbb
    37,    // .ww.wbb
    -8,    // bww.wbb
    62,    // www.wbb
    -54,   // ...bwbb
    -57,   // b..bwbb
    9,     // w..bwbb
    27,    // .b.bwbb
    40,    // bb.bwbb
    43,    // wb.bwbb
    -16,   // .w.bwbb
    -60,   // bw.bwbb
    -92,   // ww.bwbb
    -18,   // ..bbwbb
    -30,   // b.bbwbb
    60,    // w.bbwbb
    -90,   // .bbbwbb
    -23,   // bbbbwbb
    35,    // wbbbwbb
    24,    // .wbbwbb
    14,    // bwbbwbb
    80,    // wwbbwbb
    43,    // ..wbwbb
    -30,   // b.wbwbb
    -62,   // w.wbwbb
    5,     // .bwbwbb
    -31,   // bbwbwbb
    132,   // wbwbwbb
    -130,  // .wwbwbb
    4,     // bwwbwbb
    -2,    // wwwbwbb
    -14,   // ...wwbb
    -34,   // b..wwbb
    56,    // w..wwbb
    -8,    // .b.wwbb
    -46,   // bb.wwbb
    -5,    // wb.wwbb
    9,     // .w.wwbb
    80,    // bw.wwbb
    77,    // ww.wwbb
    81,    // ..bwwbb
    -13,   // b.bwwbb
    61,    // w.bwwbb
    -105,  // .bbwwbb
    20,    // bbbwwbb
    20,    // wbbwwbb
    -103,  // .wbwwbb
    -35,   // bwbwwbb
    -80,   // wwbwwbb
    23,    // ..wwwbb
    5,     // b.wwwbb
    -2,    // w.wwwbb
    21,    // .bwwwbb
    0,     // bbwwwbb
    -37,   // wbwwwbb
    17,    // .wwwwbb
    0,     // bwwwwbb
    -43,   // wwwwwbb
    18,    // .....wb
    38,    // b....wb
    2,     // w....wb
    16,    // .b...wb
    7,     // bb...wb
    0,     // wb...wb
    -8,    // .w...wb
    -109,  // bw...wb
    39,    // ww...wb
    15,    // ..b..wb
    58,    // b.b..wb
    -109,  // w.b..wb
    14,    // .bb..wb
    -17,   // bbb..wb
    -53,   // wbb..wb
    78,    // .wb..wb
    -47,   // bwb..wb
    -32,   // wwb..wb
    -36,   // ..w..wb
    21,    // b.w..wb
    -92,   // w.w..wb
    -20,   // .bw..wb
    62,    // bbw..wb
    49,    // wbw..wb
    10,    // .ww..wb
    -53,   // bww..wb
    -45,   // www..wb
    22,    // ...b.wb
    -59,   // b..b.wb
    34,    // w..b.wb
    5,     // .b.b.wb
    -49,   // bb.b.wb
    35,    // wb.b.wb
    26,    // .w.b.wb
    -61,   // bw.b.wb
    -4,    // ww.b.wb
    24,    // ..bb.wb
    29,    // b.bb.wb
    -66,   // w.bb.wb
    94,    // .bbb.wb
    86,    // bbbb.wb
    -11,   // wbbb.wb
    15,    // .wbb.wb
    -47,   // bwbb.wb
    5,     // wwbb.wb
    -1,    // ..wb.wb
    53,    // b.wb.wb
    -42,   // w.wb.wb
    -15,   // .bwb.wb
    -60,   // bbwb.wb
    -62,   // wbwb.wb
    -78,   // .wwb.wb
    129,   // bwwb.wb
    -41,   // wwwb.wb
    53,    // ...w.wb
    -48,   // b..w.wb
    28,    // w..w.wb
    46,    // .b.w.wb
    45,    // bb.w.wb
    -35,   // wb.w.wb
    -7,    // .w.w.wb
    9,     // bw.w.wb
    -66,   // ww.w.wb
    19,    // ..bw.wb
    -16,   // b.bw.wb
    -51,   // w.bw.wb
    -34,   // .bbw.wb
    38,    // bbbw.wb
    -33,   // wbbw.wb
    89,    // .wbw.wb
    57,    // bwbw.wb
    -43,   // wwbw.wb
    0,     // ..ww.wb
    35,    // b.ww.wb
    57,    // w.ww.wb
    4,     // .bww.wb
    80,    // bbww.wb
    44,    // wbww.wb
    -71,   // .www.wb
    -79,   // bwww.wb
    -54,   // wwww.wb
    38,    // ....bwb
    -29,   // b...bwb
    -7,    // w...bwb
    5,     // .b..bwb
    -75,   // bb..bwb
    -49,   // wb..bwb
    69,    // .w..bwb
    -47,   // bw..bwb
    0,     // ww..bwb
    -72,   // ..b.bwb
    -37,   // b.b.bwb
    -70,   // w.b.bwb
    -60,   // .bb.bwb
    -61,   // bbb.bwb
    51,    // wbb.bwb
    6,     // .wb.bwb
    -12,   // bwb.bwb
    94,    // wwb.bwb
    27,    // ..w.bwb
    63,    // b.w.bwb
    -22,   // w.w.bwb
    -19,   // .bw.bwb
    19,    // bbw.bwb
    0,     // wbw.bwb
    74,    // .ww.bwb
    48,    // bww.bwb
    32,    // www.bwb
    -1,    // ...bbwb
    138,   // b..bbwb
    -18,   // w..bbwb
    9,     // .b.bbwb
    -10,   // bb.bbwb
    -44,   // wb.bbwb
    -106,  // .w.bbwb
    -47,   // bw.bbwb
    35,    // ww.bbwb
    -33,   // ..bbbwb
    -41,   // b.bbbwb
    -19,   // w.bbbwb
    -9,    // .bbbbwb
    -8,    // bbbbbwb
    -113,  // wbbbbwb
    81,    // .wbbbwb
    66,    // bwbbbwb
    37,    // wwbbbwb
    9,     // ..wbbwb
    39,    // b.wbbwb
    -5,    // w.wbbwb
    -32,   // .bwbbwb
    14,    // bbwbbwb
    81,    // wbwbbwb
    -20,   // .wwbbwb
    -22,   // bwwbbwb
    36,    // wwwbbwb
    -5,    // ...wbwb
    -88,   // b..wbwb
    33,    // w..wbwb
    24,    // .b.wbwb
    50,    // bb.wbwb
    62,    // wb.wbwb
    -25,   // .w.wbwb
    57,    // bw.wbwb
    -6,    // ww.wbwb
    0,     // ..bwbwb
    31,    // b.bwbwb
    66,    // w.bwbwb
    -60,   // .bbwbwb
    15,    // bbbwbwb
    4,     // wbbwbwb
    37,    // .wbwbwb
    -42,   // bwbwbwb
    -132,  // wwbwbwb
    -61,   // ..wwbwb
    43,    // b.wwbwb
    -25,   // w.wwbwb
    -54,   // .bwwbwb
    -35,   // bbwwbwb
    -81,   // wbwwbwb
    -64,   // .wwwbwb
    7,     // bwwwbwb
    -61,   // wwwwbwb
    82,    // ....wwb
    -56,   // b...wwb
    50,    // w...wwb
    -10,   // .b..wwb
    3,     // bb..wwb
    53,    // wb..wwb
    -103,  // .w..wwb
    -53,   // bw..wwb
    23,    // ww..wwb
    10,    // ..b.wwb
    66,    // b.b.wwb
    -78,   // w.b.wwb
    54,    // .bb.wwb
    -36,   // bbb.wwb
    0,     // wbb.wwb
    -10,   // .wb.wwb
    48,    // bwb.wwb
    3,     // wwb.wwb
    42,    // ..w.wwb
    10,    // b.w.wwb
    19,    // w.w.wwb
    -62,   // .bw.wwb
    -8,    // bbw.wwb
    -51,   // wbw.wwb
    32,    // .ww.wwb
    -71,   // bww.wwb
    10,    // www.wwb
    26,    // ...bwwb
    -6,    // b..bwwb
    20,    // w..bwwb
    27,    // .b.bwwb
    2,     // bb.bwwb
    33,    // wb.bwwb
    76,    // .w.bwwb
    129,   // bw.bwwb
    -24,   // ww.bwwb
    -90,   // ..bbwwb
    -73,   // b.bbwwb
    -64,   // w.bbwwb
    36,    // .bbbwwb
    -24,   // bbbbwwb
    37,    // wbbbwwb
    55,    // .wbbwwb
    -22,   // bwbbwwb
    -20,   // wwbbwwb
    -48,   // ..wbwwb
    51,    // b.wbwwb
    50,    // w.wbwwb
    103,   // .bwbwwb
    4,     // bbwbwwb
    -4,    // wbwbwwb
    53,    // .wwbwwb
    12,    // bwwbwwb
    167,   // wwwbwwb
    119,   // ...wwwb
    18,    // b..wwwb
    100,   // w..wwwb
    34,    // .b.wwwb
    -5,    // bb.wwwb
    11,    // wb.wwwb
    -82,   // .w.wwwb
    -79,   // bw.wwwb
    -7,    // ww.wwwb
    0,     // ..bwwwb
    18,    // b.bwwwb
    25,    // w.bwwwb
    51,    // .bbwwwb
    17,    // bbbwwwb
    -37,   // wbbwwwb
    18,    // .wbwwwb
    7,     // bwbwwwb
    -35,   // wwbwwwb
    -60,   // ..wwwwb
    -4,    // b.wwwwb
    -2,    // w.wwwwb
    120,   // .bwwwwb
    0,     // bbwwwwb
    113,   // wbwwwwb
    37,    // .wwwwwb
    5,     // bwwwwwb
    8,     // wwwwwwb
    -4,    // ......w
    0,     // b.....w
    51,    // w.....w
    -41,   // .b....w
    4,     // bb....w
    -38,   // wb....w
    -1,    // .w....w
    2,     // bw....w
    5,     // ww....w
    -13,   // ..b...w
    -40,   // b.b...w
    11,    // w.b...w
    25,    // .bb...w
    37,    // bbb...w
    56,    // wbb...w
    11,    // .wb...w
    -7,    // bwb...w
    2,     // wwb...w
    -22,   // ..w...w
    34,    // b.w...w
    -47,   // w.w...w
    30,    // .bw...w
    -7,    // bbw...w
    29,    // wbw...w
    28,    // .ww...w
    50,    // bww...w
    36,    // www...w
    0,     // ...b..w
    71,    // b..b..w
    67,    // w..b..w
    -29,   // .b.b..w
    -4,    // bb.b..w
    48,    // wb.b..w
    41,    // .w.b..w
    34,    // bw.b..w
    -4,    // ww.b..w
    22,    // ..bb..w
    -36,   // b.bb..w
    47,    // w.bb..w
    -21,   // .bbb..w
    49,    // bbbb..w
    -18,   // wbbb..w
    22,    // .wbb..w
    -18,   // bwbb..w
    34,    // wwbb..w
    -85,   // ..wb..w
    -23,   // b.wb..w
    -16,   // w.wb..w
    52,    // .bwb..w
    9,     // bbwb..w
    88,    // wbwb..w
    -19,   // .wwb..w
    20,    // bwwb..w
    -48,   // wwwb..w
    6,     // ...w..w
    -71,   // b..w..w
    3,     // w..w..w
    -1,    // .b.w..w
    -108,  // bb.w..w
    59,    // wb.w..w
    56,    // .w.w..w
    28,    // bw.w..w
    -3,    // ww.w..w
    37,    // ..bw..w
    -27,   // b.bw..w
    -2,    // w.bw..w
    5,     // .bbw..w
    -20,   // bbbw..w
    6,     // wbbw..w
    -30,   // .wbw..w
    33,    // bwbw..w
    57,    // wwbw..w
    36,    // ..ww..w
    0,     // b.ww..w
    79,    // w.ww..w
    8,     // .bww..w
    56,    // bbww..w
    -138,  // wbww..w
    -37,   // .www..w
    100,   // bwww..w
    -3,    // wwww..w
    -28,   // ....b.w
    -34,   // b...b.w
    11,    // w...b.w
    -45,   // .b..b.w
    56,    // bb..b.w
    -21,   // wb..b.w
    22,    // .w..b.w
    -109,  // bw..b.w
    -7,    // ww..b.w
    -66,   // ..b.b.w
    29,    // b.b.b.w
    -45,   // w.b.b.w
    3,     // .bb.b.w
    -33,   // bbb.b.w
    -10,   // wbb.b.w
    -5,    // .wb.b.w
    -70,   // bwb.b.w
    18,    // wwb.b.w
    -29,   // ..w.b.w
    0,     // b.w.b.w
    -23,   // w.w.b.w
    35,    // .bw.b.w
    1,     // bbw.b.w
    -63,   // wbw.b.w
    50,    // .ww.b.w
    -78,   // bww.b.w
    -14,   // www.b.w
    33,    // ...bb.w
    0,     // b..bb.w
    47,    // w..bb.w
    98,    // .b.bb.w
    38,    // bb.bb.w
    -35,   // wb.bb.w
    -4,    // .w.bb.w
    -66,   // bw.bb.w
    7,     // ww.bb.w
    -29,   // ..bbb.w
    -31,   // b.bbb.w
    60,    // w.bbb.w
    64,    // .bbbb.w
    37,    // bbbbb.w
    4,     // wbbbb.w
    -105,  // .wbbb.w
    -19,   // bwbbb.w
    -5,    // wwbbb.w
    -17,   // ..wbb.w
    15,    // b.wbb.w
    -12,   // w.wbb.w
    -21,   // .bwbb.w
    60,    // bbwbb.w
    -43,   // wbwbb.w
    50,    // .wwbb.w
    -64,   // bwwbb.w
    -50,   // wwwbb.w
    -42,   // ...wb.w
    23,    // b..wb.w
    -2,    // w..wb.w
    28,    // .b.wb.w
    -5,    // bb.wb.w
    -53,   // wb.wb.w
    33,    // .w.wb.w
    -51,   // bw.wb.w
    -16,   // ww.wb.w
    7,     // ..bwb.w
    5,     // b.bwb.w
    32,    // w.bwb.w
    -29,   // .bbwb.w
    100,   // bbbwb.w
    -51,   // wbbwb.w
    32,    // .wbwb.w
    66,    // bwbwb.w
    30,    // wwbwb.w
    26,    // ..wwb.w
    -15,   // b.wwb.w
    -14,   // w.wwb.w
    -55,   // .bwwb.w
    61,    // bbwwb.w
    -39,   // wbwwb.w
    18,    // .wwwb.w
    25,    // bwwwb.w
    -43,   // wwwwb.w
    -80,   // ....w.w
    40,    // b...w.w
    -47,   // w...w.w
    -9,    // .b..w.w
    -5,    // bb..w.w
    -58,   // wb..w.w
    -25,   // .w..w.w
    -92,   // bw..w.w
    50,    // ww..w.w
    -61,   // ..b.w.w
    0,     // b.b.w.w
    -23,   // w.b.w.w
    30,    // .bb.w.w
    10,    // bbb.w.w
    -66,   // wbb.w.w
    43,    // .wb.w.w
    -22,   // bwb.w.w
    -14,   // wwb.w.w
    -21,   // ..w.w.w
    -29,   // b.w.w.w
    -18,   // w.w.w.w
    61,    // .bw.w.w
    73,    // bbw.w.w
    37,    // wbw.w.w
    13,    // .ww.w.w
    19,    // bww.w.w
    -55,   // www.w.w
    -55,   // ...bw.w
    27,    // b..bw.w
    -16,   // w..bw.w
    -65,   // .b.bw.w
    -39,   // bb.bw.w
    16,    // wb.bw.w
    -18,   // .w.bw.w
    -42,   // bw.bw.w
    -26,   // ww.bw.w
    -28,   // ..bbw.w
    96,    // b.bbw.w
    -12,   // w.bbw.w
    1,     // .bbbw.w
    -23,   // bbbbw.w
    -18,   // wbbbw.w
    54,    // .wbbw.w
    -5,    // bwbbw.w
    13,    // wwbbw.w
    -13,   // ..wbw.w
    -5,    // b.wbw.w
    -43,   // w.wbw.w
    -2,    // .bwbw.w
    -62,   // bbwbw.w
    -31,   // wbwbw.w
    138,   // .wwbw.w
    50,    // bwwbw.w
    56,    // wwwbw.w
    -33,   // ...ww.w
    36,    // b..ww.w
    79,    // w..ww.w
    -75,   // .b.ww.w
    44,    // bb.ww.w
    -29,   // wb.ww.w
    34,    // .w.ww.w
    57,    // bw.ww.w
    49,    // ww.ww.w
    66,    // ..bww.w
    -96,   // b.bww.w
    -14,   // w.bww.w
    13,    // .bbww.w
    -90,   // bbbww.w
    73,    // wbbww.w
    2,     // .wbww.w
    -25,   // bwbww.w
    30,    // wwbww.w
    -70,   // ..www.w
    31,    // b.www.w
    -40,   // w.www.w
    -98,   // .bwww.w
    -2,    // bbwww.w
    41,    // wbwww.w
    -56,   // .wwww.w
    -2,    // bwwww.w
    64,    // wwwww.w
    -18,   // .....bw
    -2,    // b....bw
    -38,   // w....bw
    8,     // .b...bw
    -39,   // bb...bw
    109,   // wb...bw
    -16,   // .w...bw
    0,     // bw...bw
    -7,    // ww...bw
    36,    // ..b..bw
    92,    // b.b..bw
    -21,   // w.b..bw
    -10,   // .bb..bw
    45,    // bbb..bw
    53,    // wbb..bw
    20,    // .wb..bw
    -49,   // bwb..bw
    -62,   // wwb..bw
    -15,   // ..w..bw
    109,   // b.w..bw
    -58,   // w.w..bw
    -78,   // .bw..bw
    32,    // bbw..bw
    47,    // wbw..bw
    -14,   // .ww..bw
    53,    // bww..bw
    17,    // www..bw
    -53,   // ...b.bw
    -28,   // b..b.bw
    48,    // w..b.bw
    7,     // .b.b.bw
    66,    // bb.b.bw
    -9,    // wb.b.bw
    -46,   // .w.b.bw
    35,    // bw.b.bw
    -45,   // ww.b.bw
    0,     // ..bb.bw
    -57,   // b.bb.bw
    -35,   // w.bb.bw
    71,    // .bbb.bw
    54,    // bbbb.bw
    79,    // wbbb.bw
    -4,    // .wbb.bw
    -44,   // bwbb.bw
    -80,   // wwbb.bw
    -19,   // ..wb.bw
    51,    // b.wb.bw
    16,    // w.wb.bw
    -89,   // .bwb.bw
    43,    // bbwb.bw
    -57,   // wbwb.bw
    34,    // .wwb.bw
    33,    // bwwb.bw
    -38,   // wwwb.bw
    -22,   // ...w.bw
    -34,   // b..w.bw
    59,    // w..w.bw
    -26,   // .b.w.bw
    4,     // bb.w.bw
    61,    // wb.w.bw
    -5,    // .w.w.bw
    -35,   // bw.w.bw
    49,    // ww.w.bw
    1,     // ..bw.bw
    42,    // b.bw.bw
    -53,   // w.bw.bw
    78,    // .bbw.bw
    41,    // bbbw.bw
    -129,  // wbbw.bw
    15,    // .wbw.bw
    62,    // bwbw.bw
    60,    // wwbw.bw
    -24,   // ..ww.bw
    66,    // b.ww.bw
    -29,   // w.ww.bw
    -15,   // .bww.bw
    -5,    // bbww.bw
    47,    // wbww.bw
    -94,   // .www.bw
    11,    // bwww.bw
    -86,   // wwww.bw
    -82,   // ....bbw
    -50,   // b...bbw
    56,    // w...bbw
    103,   // .b..bbw
    -23,   // bb..bbw
    53,    // wb..bbw
    10,    // .w..bbw
    -53,   // bw..bbw
    -3,    // ww..bbw
    -42,   // ..b.bbw
    -19,   // b.b.bbw
    -10,   // w.b.bbw
    -32,   // .bb.bbw
    -10,   // bbb.bbw
    71,    // wbb.bbw
    62,    // .wb.bbw
    51,    // bwb.bbw
    8,     // wwb.bbw
    -10,   // ..w.bbw
    78,    // b.w.bbw
    -66,   // w.w.bbw
    10,    // .bw.bbw
    -3,    // bbw.bbw
    -48,   // wbw.bbw
    -54,   // .ww.bbw
    0,     // bww.bbw
    36,    // www.bbw
    -119,  // ...bbbw
    -100,  // b..bbbw
    -18,   // w..bbbw
    82,    // .b.bbbw
    7,     // bb.bbbw
    79,    // wb.bbbw
    -34,   // .w.bbbw
    -11,   // bw.bbbw
    5,     // ww.bbbw
    60,    // ..bbbbw
    2,     // b.bbbbw
    4,     // w.bbbbw
    -37,   // .bbbbbw
    -8,    // bbbbbbw
    -5,    // wbbbbbw
    -120,  // .wbbbbw
    -113,  // bwbbbbw
    0,     // wwbbbbw
    0,     // ..wbbbw
    -25,   // b.wbbbw
    -18,   // w.wbbbw
    -18,   // .bwbbbw
    35,    // bbwbbbw
    -7,    // wbwbbbw
    -51,   // .wwbbbw
    37,    // bwwbbbw
    -17,   // wwwbbbw
    -26,   // ...wbbw
    -20,   // b..wbbw
    6,     // w..wbbw
    -76,   // .b.wbbw
    24,    // bb.wbbw
    -129,  // wb.wbbw
    -27,   // .w.wbbw
    -33,   // bw.wbbw
    -2,    // ww.wbbw
    48,    // ..bwbbw
    -50,   // b.bwbbw
    -51,   // w.bwbbw
    -53,   // .bbwbbw
    -167,  // bbbwbbw
    -12,   // wbbwbbw
    -103,  // .wbwbbw
    4,     // bwbwbbw
    -4,    // wwbwbbw
    90,    // ..wwbbw
    64,    // b.wwbbw
    73,    // w.wwbbw
    -55,   // .bwwbbw
    20,    // bbwwbbw
    22,    // wbwwbbw
    -36,   // .wwwbbw
    -37,   // bwwwbbw
    24,    // wwwwbbw
    -38,   // ....wbw
    7,     // b...wbw
    29,    // w...wbw
    -69,   // .b..wbw
    0,     // bb..wbw
    47,    // wb..wbw
    -5,    // .w..wbw
    49,    // bw..wbw
    75,    // ww..wbw
    -27,   // ..b.wbw
    22,    // b.b.wbw
    -63,   // w.b.wbw
    -74,   // .bb.wbw
    -32,   // bbb.wbw
    -48,   // wbb.wbw
    19,    // .wb.wbw
    0,     // bwb.wbw
    -19,   // wwb.wbw
    72,    // ..w.wbw
    70,    // b.w.wbw
    37,    // w.w.wbw
    -6,    // .bw.wbw
    -94,   // bbw.wbw
    12,    // wbw.wbw
    60,    // .ww.wbw
    -51,   // bww.wbw
    61,    // www.wbw
    5,     // ...bwbw
    -33,   // b..bwbw
    88,    // w..bwbw
    25,    // .b.bwbw
    6,     // bb.bwbw
    -57,   // wb.bwbw
    -24,   // .w.bwbw
    -62,   // bw.bwbw
    -50,   // ww.bwbw
    61,    // ..bbwbw
    25,    // b.bbwbw
    -43,   // w.bbwbw
    64,    // .bbbwbw
    61,    // bbbbwbw
    -7,    // wbbbwbw
    54,    // .wbbwbw
    81,    // bwbbwbw
    35,    // wwbbwbw
    0,     // ..wbwbw
    -66,   // b.wbwbw
    -31,   // w.wbwbw
    -37,   // .bwbwbw
    132,   // bbwbwbw
    42,    // wbwbwbw
    60,    // .wwbwbw
    -4,    // bwwbwbw
    -15,   // wwwbwbw
    1,     // ...wwbw
    18,    // b..wwbw
    -138,  // w..wwbw
    106,   // .b.wwbw
    -35,   // bb.wwbw
    47,    // wb.wwbw
    -9,    // .w.wwbw
    44,    // bw.wwbw
    10,    // ww.wwbw
    -9,    // ..bwwbw
    5,     // b.bwwbw
    -39,   // w.bwwbw
    20,    // .bbwwbw
    -36,   // bbbwwbw
    22,    // wbbwwbw
    32,    // .wbwwbw
    -81,   // bwbwwbw
    -14,   // wwbwwbw
    33,    // ..wwwbw
    19,    // b.wwwbw
    41,    // w.wwwbw
    -81,   // .bwwwbw
    -37,   // bbwwwbw
    -66,   // wbwwwbw
    9,     // .wwwwbw
    113,   // bwwwwbw
    8,     // wwwwwbw
    -11,   // .....ww
    -4,    // b....ww
    5,     // w....ww
    -14,   // .b...ww
    0,     // bb...ww
    -7,    // wb...ww
    -10,   // .w...ww
    39,    // bw...ww
    25,    // ww...ww
    58,    // ..b..ww
    5,     // b.b..ww
    -7,    // w.b..ww
    -63,   // .bb..ww
    -36,   // bbb..ww
    -3,    // wbb..ww
    -39,   // .wb..ww
    0,     // bwb..ww
    -24,   // wwb..ww
    -6,    // ..w..ww
    -56,   // b.w..ww
    50,    // w.w..ww
    -68,   // .bw..ww
    -19,   // bbw..ww
    75,    // wbw..ww
    -6,    // .ww..ww
    23,    // bww..ww
    -72,   // www..ww
    -35,   // ...b.ww
    108,   // b..b.ww
    -4,    // w..b.ww
    -29,   // .b.b.ww
    15,    // bb.b.ww
    -45,   // wb.b.ww
    69,    // .w.b.ww
    -4,    // bw.b.ww
    -109,  // ww.b.ww
    -22,   // ..bb.ww
    -44,   // b.bb.ww
    7,     // w.bb.ww
    36,    // .bbb.ww
    50,    // bbbb.ww
    5,     // wbbb.ww
    87,    // .wbb.ww
    35,    // bwbb.ww
    46,    // wwbb.ww
    61,    // ..wb.ww
    5,     // b.wb.ww
    -26,   // w.wb.ww
    -21,   // .bwb.ww
    -92,   // bbwb.ww
    -50,   // wbwb.ww
    -57,   // .wwb.ww
    -24,   // bwwb.ww
    -40,   // wwwb.ww
    -135,  // ...w.ww
    4,     // b..w.ww
    -3,    // w..w.ww
    -109,  // .b.w.ww
    -15,   // bb.w.ww
    49,    // wb.w.ww
    50,    // .w.w.ww
    -66,   // bw.w.ww
    -18,   // ww.w.ww
    8,     // ..bw.ww
    39,    // b.bw.ww
    -16,   // w.bw.ww
    -58,   // .bbw.ww
    1,     // bbbw.ww
    -2,    // wbbw.ww
    -18,   // .wbw.ww
    -6,    // bwbw.ww
    -40,   // wwbw.ww
    -9,    // ..ww.ww
    -38,   // b.ww.ww
    49,    // w.ww.ww
    -54,   // .bww.ww
    77,    // bbww.ww
    10,    // wbww.ww
    25,    // .www.ww
    -7,    // bwww.ww
    62,    // wwww.ww
    60,    // ....bww
    7,     // b...bww
    2,     // w...bww
    37,    // .b..bww
    19,    // bb..bww
    -62,   // wb..bww
    10,    // .w..bww
    -32,   // bw..bww
    -24,   // ww..bww
    -14,   // ..b.bww
    -73,   // b.b.bww
    18,    // w.b.bww
    -37,   // .bb.bww
    -62,   // bbb.bww
    8,     // wbb.bww
    8,     // .wb.bww
    94,    // bwb.bww
    84,    // wwb.bww
    40,    // ..w.bww
    -1,    // b.w.bww
    -14,   // w.w.bww
    9,     // .bw.bww
    0,     // bbw.bww
    -19,   // wbw.bww
    9,     // .ww.bww
    3,     // bww.bww
    -46,   // www.bww
    14,    // ...bbww
    -56,   // b..bbww
    34,    // w..bbww
    -9,    // .b.bbww
    -77,   // bb.bbww
    -80,   // wb.bbww
    8,     // .w.bbww
    5,     // bw.bbww
    46,    // ww.bbww
    -23,   // ..bbbww
    2,     // b.bbbww
    -5,    // w.bbbww
    -17,   // .bbbbww
    43,    // bbbbbww
    0,     // wbbbbww
    -21,   // .wbbbww
    37,    // bwbbbww
    0,     // wwbbbww
    -81,   // ..wbbww
    -61,   // b.wbbww
    13,    // w.wbbww
    103,   // .bwbbww
    80,    // bbwbbww
    35,    // wbwbbww
    105,   // .wwbbww
    -20,   // bwwbbww
    -20,   // wwwbbww
    54,    // ...wbww
    -9,    // b..wbww
    57,    // w..wbww
    16,    // .b.wbww
    92,    // bb.wbww
    60,    // wb.wbww
    -27,   // .w.wbww
    -43,   // bw.wbww
    -40,   // ww.wbww
    -43,   // ..bwbww
    62,    // b.bwbww
    30,    // w.bwbww
    130,   // .bbwbww
    2,     // bbbwbww
    -4,    // wbbwbww
    -5,    // .wbwbww
    -132,  // bwbwbww
    31,    // wwbwbww
    18,    // ..wwbww
    -60,   // b.wwbww
    30,    // w.wwbww
    -24,   // .bwwbww
    -80,   // bbwwbww
    -14,   // wbwwbww
    90,    // .wwwbww
    -35,   // bwwwbww
    23,    // wwwwbww
    -148,  // ....www
    -37,   // b...www
    36,    // w...www
    -41,   // .b..www
    36,    // bb..www
    17,    // wb..www
    -30,   // .w..www
    -45,   // bw..www
    -72,   // ww..www
    -34,   // ..b.www
    -10,   // b.b.www
    -14,   // w.b.www
    -47,   // .bb.www
    0,     // bbb.www
    36,    // wbb.www
    -57,   // .wb.www
    32,    // bwb.www
    -46,   // wwb.www
    -93,   // ..w.www
    33,    // b.w.www
    -55,   // w.w.www
    -1,    // .bw.www
    62,    // bbw.www
    61,    // wbw.www
    -48,   // .ww.www
    10,    // bww.www
    -51,   // www.www
    -19,   // ...bwww
    20,    // b..bwww
    -48,   // w..bwww
    49,    // .b.bwww
    -1,    // bb.bwww
    -38,   // wb.bwww
    45,    // .w.bwww
    -41,   // bw.bwww
    -40,   // ww.bwww
    -58,   // ..bbwww
    90,    // b.bbwww
    -50,   // w.bbwww
    1,     // .bbbwww
    -76,   // bbbbwww
    -17,   // wbbbwww
    29,    // .wbbwww
    36,    // bwbbwww
    -20,   // wwbbwww
    173,   // ..wbwww
    -100,  // b.wbwww
    56,    // w.wbwww
    29,    // .bwbwww
    -2,    // bbwbwww
    -15,   // wbwbwww
    7,     // .wwbwww
    167,   // bwwbwww
    -32,   // wwwbwww
    -363,  // ...wwww
    -49,   // b..wwww
    -3,    // w..wwww
    -162,  // .b.wwww
    -50,   // bb.wwww
    -86,   // wb.wwww
    57,    // .w.wwww
    -54,   // bw.wwww
    62,    // ww.wwww
    -57,   // ..bwwww
    23,    // b.bwwww
    -43,   // w.bwwww
    14,    // .bbwwww
    76,    // bbbwwww
    24,    // wbbwwww
    60,    // .wbwwww
    -61,   // bwbwwww
    23,    // wwbwwww
    -42,   // ..wwwww
    -37,   // b.wwwww
    64,    // w.wwwww
    -98,   // .bwwwww
    -43,   // bbwwwww
    8,     // wbwwwww
    18,    // .wwwwww
    8,     // bwwwwww
    44,    // wwwwwww
    0,     // captures=0 threats=0
    107,   // captures=0 threats=1
    340,   // captures=0 threats=2
    669,   // captures=0 threats=3
    1064,  // captures=0 threats=4
    0,     // captures=0 additional threats
    143,   // captures=1 threats=0
    308,   // captures=1 threats=1
    587,   // captures=1 threats=2
    950,   // captures=1 threats=3
    1367,  // captures=1 threats=4
    0,     // captures=1 additional threats
    218,   // captures=2 threats=0
    481,   // captures=2 threats=1
    846,   // captures=2 threats=2
    1283,  // captures=2 threats=3
    1762,  // captures=2 threats=4
    0,     // captures=2 additional threats
    0,     // captures=3 threats=0
    302,   // captures=3 threats=1
    793,   // captures=3 threats=2
    1344,  // captures=3 threats=3
    1925,  // captures=3 threats=4
    0,     // captures=3 additional threats
    0,     // captures=4 threats=0
    0,     // captures=4 threats=1
    104,   // captures=4 threats=2
    809,   // captures=4 threats=3
    1532,  // captures=4 threats=4
    0,     // captures=4 additional threats
].into_boxed_slice()
