vec![
    0,     // .......
    14,    // b......
    -14,   // w......
    -8,    // .b.....
    19,    // bb.....
    -20,   // wb.....
    8,     // .w.....
    20,    // bw.....
    -19,   // ww.....
    -4,    // ..b....
    73,    // b.b....
    -16,   // w.b....
    15,    // .bb....
    153,   // bbb....
    -60,   // wbb....
    -12,   // .wb....
    35,    // bwb....
    40,    // wwb....
    4,     // ..w....
    16,    // b.w....
    -73,   // w.w....
    12,    // .bw....
    -40,   // bbw....
    -35,   // wbw....
    -15,   // .ww....
    60,    // bww....
    -153,  // www....
    -8,    // ...b...
    13,    // b..b...
    -28,   // w..b...
    -22,   // .b.b...
    84,    // bb.b...
    -39,   // wb.b...
    -18,   // .w.b...
    10,    // bw.b...
    -30,   // ww.b...
    -26,   // ..bb...
    24,    // b.bb...
    22,    // w.bb...
    44,    // .bbb...
    312,   // bbbb...
    -104,  // wbbb...
    85,    // .wbb...
    7,     // bwbb...
    40,    // wwbb...
    -16,   // ..wb...
    63,    // b.wb...
    -53,   // w.wb...
    -45,   // .bwb...
    -61,   // bbwb...
    7,     // wbwb...
    -33,   // .wwb...
    -12,   // bwwb...
    9,     // wwwb...
    8,     // ...w...
    28,    // b..w...
    -13,   // w..w...
    18,    // .b.w...
    30,    // bb.w...
    -10,   // wb.w...
    22,    // .w.w...
    39,    // bw.w...
    -84,   // ww.w...
    16,    // ..bw...
    53,    // b.bw...
    -63,   // w.bw...
    33,    // .bbw...
    -9,    // bbbw...
    12,    // wbbw...
    45,    // .wbw...
    -7,    // bwbw...
    61,    // wwbw...
    26,    // ..ww...
    -22,   // b.ww...
    -24,   // w.ww...
    -85,   // .bww...
    -40,   // bbww...
    -7,    // wbww...
    -44,   // .www...
    104,   // bwww...
    -312,  // wwww...
    -4,    // ....b..
    17,    // b...b..
    -29,   // w...b..
    -12,   // .b..b..
    -5,    // bb..b..
    21,    // wb..b..
    -7,    // .w..b..
    11,    // bw..b..
    67,    // ww..b..
    -30,   // ..b.b..
    26,    // b.b.b..
    -55,   // w.b.b..
    -68,   // .bb.b..
    77,    // bbb.b..
    -22,   // wbb.b..
    -12,   // .wb.b..
    -88,   // bwb.b..
    -16,   // wwb.b..
    0,     // ..w.b..
    13,    // b.w.b..
    -30,   // w.w.b..
    -6,    // .bw.b..
    -31,   // bbw.b..
    -20,   // wbw.b..
    28,    // .ww.b..
    -4,    // bww.b..
    -46,   // www.b..
    -26,   // ...bb..
    -28,   // b..bb..
    8,     // w..bb..
    32,    // .b.bb..
    -7,    // bb.bb..
    0,     // wb.bb..
    -83,   // .w.bb..
    47,    // bw.bb..
    -10,   // ww.bb..
    38,    // ..bbb..
    60,    // b.bbb..
    -34,   // w.bbb..
    178,   // .bbbb..
    56,    // bbbbb..
    64,    // wbbbb..
    -58,   // .wbbb..
    -23,   // bwbbb..
    0,     // wwbbb..
    -79,   // ..wbb..
    -38,   // b.wbb..
    -32,   // w.wbb..
    -13,   // .bwbb..
    -8,    // bbwbb..
    31,    // wbwbb..
    5,     // .wwbb..
    -98,   // bwwbb..
    -53,   // wwwbb..
    16,    // ...wb..
    90,    // b..wb..
    36,    // w..wb..
    -38,   // .b.wb..
    -65,   // bb.wb..
    -7,    // wb.wb..
    53,    // .w.wb..
    27,    // bw.wb..
    19,    // ww.wb..
    14,    // ..bwb..
    5,     // b.bwb..
    -2,    // w.bwb..
    3,     // .bbwb..
    -126,  // bbbwb..
    44,    // wbbwb..
    49,    // .wbwb..
    -26,   // bwbwb..
    -21,   // wwbwb..
    79,    // ..wwb..
    34,    // b.wwb..
    30,    // w.wwb..
    27,    // .bwwb..
    50,    // bbwwb..
    -17,   // wbwwb..
    -58,   // .wwwb..
    20,    // bwwwb..
    -67,   // wwwwb..
    4,     // ....w..
    29,    // b...w..
    -17,   // w...w..
    7,     // .b..w..
    -67,   // bb..w..
    -11,   // wb..w..
    12,    // .w..w..
    -21,   // bw..w..
    5,     // ww..w..
    0,     // ..b.w..
    30,    // b.b.w..
    -13,   // w.b.w..
    -28,   // .bb.w..
    46,    // bbb.w..
    4,     // wbb.w..
    6,     // .wb.w..
    20,    // bwb.w..
    31,    // wwb.w..
    30,    // ..w.w..
    55,    // b.w.w..
    -26,   // w.w.w..
    12,    // .bw.w..
    16,    // bbw.w..
    88,    // wbw.w..
    68,    // .ww.w..
    22,    // bww.w..
    -77,   // www.w..
    -16,   // ...bw..
    -36,   // b..bw..
    -90,   // w..bw..
    -53,   // .b.bw..
    -19,   // bb.bw..
    -27,   // wb.bw..
    38,    // .w.bw..
    7,     // bw.bw..
    65,    // ww.bw..
    -79,   // ..bbw..
    -30,   // b.bbw..
    -34,   // w.bbw..
    58,    // .bbbw..
    67,    // bbbbw..
    -20,   // wbbbw..
    -27,   // .wbbw..
    17,    // bwbbw..
    -50,   // wwbbw..
    -14,   // ..wbw..
    2,     // b.wbw..
    -5,    // w.wbw..
    -49,   // .bwbw..
    21,    // bbwbw..
    26,    // wbwbw..
    -3,    // .wwbw..
    -44,   // bwwbw..
    126,   // wwwbw..
    26,    // ...ww..
    -8,    // b..ww..
    28,    // w..ww..
    83,    // .b.ww..
    10,    // bb.ww..
    -47,   // wb.ww..
    -32,   // .w.ww..
    0,     // bw.ww..
    7,     // ww.ww..
    79,    // ..bww..
    32,    // b.bww..
    38,    // w.bww..
    -5,    // .bbww..
    53,    // bbbww..
    98,    // wbbww..
    13,    // .wbww..
    -31,   // bwbww..
    8,     // wwbww..
    -38,   // ..www..
    34,    // b.www..
    -60,   // w.www..
    58,    // .bwww..
    0,     // bbwww..
    23,    // wbwww..
    -178,  // .wwww..
    -64,   // bwwww..
    -56,   // wwwww..
    -8,    // .....b.
    14,    // b....b.
    -49,   // w....b.
    -28,   // .b...b.
    13,    // bb...b.
    17,    // wb...b.
    0,     // .w...b.
    28,    // bw...b.
    -2,    // ww...b.
    -12,   // ..b..b.
    15,    // b.b..b.
    2,     // w.b..b.
    -5,    // .bb..b.
    42,    // bbb..b.
    82,    // wbb..b.
    3,     // .wb..b.
    2,     // bwb..b.
    39,    // wwb..b.
    7,     // ..w..b.
    -18,   // b.w..b.
    -5,    // w.w..b.
    -38,   // .bw..b.
    -1,    // bbw..b.
    -80,   // wbw..b.
    19,    // .ww..b.
    -26,   // bww..b.
    -52,   // www..b.
    -22,   // ...b.b.
    -37,   // b..b.b.
    -20,   // w..b.b.
    -22,   // .b.b.b.
    -33,   // bb.b.b.
    18,    // wb.b.b.
    -31,   // .w.b.b.
    16,    // bw.b.b.
    -21,   // ww.b.b.
    32,    // ..bb.b.
    -42,   // b.bb.b.
    92,    // w.bb.b.
    36,    // .bbb.b.
    -47,   // bbbb.b.
    80,    // wbbb.b.
    -11,   // .wbb.b.
    18,    // bwbb.b.
    -14,   // wwbb.b.
    -53,   // ..wb.b.
    -26,   // b.wb.b.
    -57,   // w.wb.b.
    8,     // .bwb.b.
    37,    // bbwb.b.
    53,    // wbwb.b.
    -21,   // .wwb.b.
    36,    // bwwb.b.
    68,    // wwwb.b.
    18,    // ...w.b.
    -40,   // b..w.b.
    18,    // w..w.b.
    -24,   // .b.w.b.
    -84,   // bb.w.b.
    -17,   // wb.w.b.
    31,    // .w.w.b.
    50,    // bw.w.b.
    -79,   // ww.w.b.
    -38,   // ..bw.b.
    25,    // b.bw.b.
    24,    // w.bw.b.
    36,    // .bbw.b.
    -16,   // bbbw.b.
    -76,   // wbbw.b.
    36,    // .wbw.b.
    28,    // bwbw.b.
    22,    // wwbw.b.
    83,    // ..ww.b.
    1,     // b.ww.b.
    -71,   // w.ww.b.
    37,    // .bww.b.
    -26,   // bbww.b.
    81,    // wbww.b.
    -21,   // .www.b.
    24,    // bwww.b.
    -121,  // wwww.b.
    15,    // ....bb.
    -27,   // b...bb.
    22,    // w...bb.
    -5,    // .b..bb.
    -4,    // bb..bb.
    -33,   // wb..bb.
    -19,   // .w..bb.
    30,    // bw..bb.
    -53,   // ww..bb.
    -68,   // ..b.bb.
    -2,    // b.b.bb.
    19,    // w.b.bb.
    29,    // .bb.bb.
    24,    // bbb.bb.
    -15,   // wbb.bb.
    -52,   // .wb.bb.
    -54,   // bwb.bb.
    -57,   // wwb.bb.
    -28,   // ..w.bb.
    -50,   // b.w.bb.
    -9,    // w.w.bb.
    5,     // .bw.bb.
    -13,   // bbw.bb.
    -81,   // wbw.bb.
    0,     // .ww.bb.
    53,    // bww.bb.
    -22,   // www.bb.
    44,    // ...bbb.
    33,    // b..bbb.
    -15,   // w..bbb.
    36,    // .b.bbb.
    -37,   // bb.bbb.
    50,    // wb.bbb.
    21,    // .w.bbb.
    66,    // bw.bbb.
    47,    // ww.bbb.
    178,   // ..bbbb.
    66,    // b.bbbb.
    58,    // w.bbbb.
    -68,   // .bbbbb.
    -19,   // bbbbbb.
    -36,   // wbbbbb.
    83,    // .wbbbb.
    18,    // bwbbbb.
    12,    // wwbbbb.
    58,    // ..wbbb.
    -9,    // b.wbbb.
    -10,   // w.wbbb.
    61,    // .bwbbb.
    -108,  // bbwbbb.
    50,    // wbwbbb.
    36,    // .wwbbb.
    72,    // bwwbbb.
    -33,   // wwwbbb.
    33,    // ...wbb.
    0,     // b..wbb.
    -2,    // w..wbb.
    36,    // .b.wbb.
    59,    // bb.wbb.
    80,    // wb.wbb.
    21,    // .w.wbb.
    0,     // bw.wbb.
    -78,   // ww.wbb.
    3,     // ..bwbb.
    -126,  // b.bwbb.
    -29,   // w.bwbb.
    0,     // .bbwbb.
    -8,    // bbbwbb.
    -56,   // wbbwbb.
    -19,   // .wbwbb.
    -57,   // bwbwbb.
    127,   // wwbwbb.
    -5,    // ..wwbb.
    -68,   // b.wwbb.
    19,    // w.wwbb.
    -15,   // .bwwbb.
    -116,  // bbwwbb.
    27,    // wbwwbb.
    -36,   // .wwwbb.
    36,    // bwwwbb.
    18,    // wwwwbb.
    12,    // ....wb.
    -25,   // b...wb.
    24,    // w...wb.
    -38,   // .b..wb.
    46,    // bb..wb.
    -87,   // wb..wb.
    -3,    // .w..wb.
    -32,   // bw..wb.
    -34,   // ww..wb.
    -6,    // ..b.wb.
    -52,   // b.b.wb.
    36,    // w.b.wb.
    5,     // .bb.wb.
    44,    // bbb.wb.
    -13,   // wbb.wb.
    0,     // .wb.wb.
    -22,   // bwb.wb.
    -2,    // wwb.wb.
    12,    // ..w.wb.
    16,    // b.w.wb.
    62,    // w.w.wb.
    51,    // .bw.wb.
    -6,    // bbw.wb.
    1,     // wbw.wb.
    52,    // .ww.wb.
    -80,   // bww.wb.
    12,    // www.wb.
    -45,   // ...bwb.
    46,    // b..bwb.
    58,    // w..bwb.
    8,     // .b.bwb.
    13,    // bb.bwb.
    -68,   // wb.bwb.
    -36,   // .w.bwb.
    -1,    // bw.bwb.
    -6,    // ww.bwb.
    -13,   // ..bbwb.
    9,     // b.bbwb.
    8,     // w.bbwb.
    61,    // .bbbwb.
    -48,   // bbbbwb.
    6,     // wbbbwb.
    33,    // .wbbwb.
    -21,   // bwbbwb.
    71,    // wwbbwb.
    -49,   // ..wbwb.
    -37,   // b.wbwb.
    17,    // w.wbwb.
    -16,   // .bwbwb.
    15,    // bbwbwb.
    -28,   // wbwbwb.
    19,    // .wwbwb.
    85,    // bwwbwb.
    9,     // wwwbwb.
    -85,   // ...wwb.
    -19,   // b..wwb.
    16,    // w..wwb.
    37,    // .b.wwb.
    -83,   // bb.wwb.
    -10,   // wb.wwb.
    11,    // .w.wwb.
    -1,    // bw.wwb.
    -52,   // ww.wwb.
    27,    // ..bwwb.
    -52,   // b.bwwb.
    -20,   // w.bwwb.
    -15,   // .bbwwb.
    -29,   // bbbwwb.
    -80,   // wbbwwb.
    -33,   // .wbwwb.
    -75,   // bwbwwb.
    -34,   // wwbwwb.
    58,    // ..wwwb.
    92,    // b.wwwb.
    -95,   // w.wwwb.
    2,     // .bwwwb.
    26,    // bbwwwb.
    -37,   // wbwwwb.
    -83,   // .wwwwb.
    105,   // bwwwwb.
    -91,   // wwwwwb.
    8,     // .....w.
    49,    // b....w.
    -14,   // w....w.
    0,     // .b...w.
    2,     // bb...w.
    -28,   // wb...w.
    28,    // .w...w.
    -17,   // bw...w.
    -13,   // ww...w.
    -7,    // ..b..w.
    5,     // b.b..w.
    18,    // w.b..w.
    -19,   // .bb..w.
    52,    // bbb..w.
    26,    // wbb..w.
    38,    // .wb..w.
    80,    // bwb..w.
    1,     // wwb..w.
    12,    // ..w..w.
    -2,    // b.w..w.
    -15,   // w.w..w.
    -3,    // .bw..w.
    -39,   // bbw..w.
    -2,    // wbw..w.
    5,     // .ww..w.
    -82,   // bww..w.
    -42,   // www..w.
    -18,   // ...b.w.
    -18,   // b..b.w.
    40,    // w..b.w.
    -31,   // .b.b.w.
    79,    // bb.b.w.
    -50,   // wb.b.w.
    24,    // .w.b.w.
    17,    // bw.b.w.
    84,    // ww.b.w.
    -83,   // ..bb.w.
    71,    // b.bb.w.
    -1,    // w.bb.w.
    21,    // .bbb.w.
    121,   // bbbb.w.
    -24,   // wbbb.w.
    -37,   // .wbb.w.
    -81,   // bwbb.w.
    26,    // wwbb.w.
    38,    // ..wb.w.
    -24,   // b.wb.w.
    -25,   // w.wb.w.
    -36,   // .bwb.w.
    -22,   // bbwb.w.
    -28,   // wbwb.w.
    -36,   // .wwb.w.
    76,    // bwwb.w.
    16,    // wwwb.w.
    22,    // ...w.w.
    20,    // b..w.w.
    37,    // w..w.w.
    31,    // .b.w.w.
    21,    // bb.w.w.
    -16,   // wb.w.w.
    22,    // .w.w.w.
    -18,   // bw.w.w.
    33,    // ww.w.w.
    53,    // ..bw.w.
    57,    // b.bw.w.
    26,    // w.bw.w.
    21,    // .bbw.w.
    -68,   // bbbw.w.
    -36,   // wbbw.w.
    -8,    // .wbw.w.
    -53,   // bwbw.w.
    -37,   // wwbw.w.
    -32,   // ..ww.w.
    -92,   // b.ww.w.
    42,    // w.ww.w.
    11,    // .bww.w.
    14,    // bbww.w.
    -18,   // wbww.w.
    -36,   // .www.w.
    -80,   // bwww.w.
    47,    // wwww.w.
    -12,   // ....bw.
    -24,   // b...bw.
    25,    // w...bw.
    3,     // .b..bw.
    34,    // bb..bw.
    32,    // wb..bw.
    38,    // .w..bw.
    87,    // bw..bw.
    -46,   // ww..bw.
    -12,   // ..b.bw.
    -62,   // b.b.bw.
    -16,   // w.b.bw.
    -52,   // .bb.bw.
    -12,   // bbb.bw.
    80,    // wbb.bw.
    -51,   // .wb.bw.
    -1,    // bwb.bw.
    6,     // wwb.bw.
    6,     // ..w.bw.
    -36,   // b.w.bw.
    52,    // w.w.bw.
    0,     // .bw.bw.
    2,     // bbw.bw.
    22,    // wbw.bw.
    -5,    // .ww.bw.
    13,    // bww.bw.
    -44,   // www.bw.
    85,    // ...bbw.
    -16,   // b..bbw.
    19,    // w..bbw.
    -11,   // .b.bbw.
    52,    // bb.bbw.
    1,     // wb.bbw.
    -37,   // .w.bbw.
    10,    // bw.bbw.
    83,    // ww.bbw.
    -58,   // ..bbbw.
    95,    // b.bbbw.
    -92,   // w.bbbw.
    83,    // .bbbbw.
    91,    // bbbbbw.
    -105,  // wbbbbw.
    -2,    // .wbbbw.
    37,    // bwbbbw.
    -26,   // wwbbbw.
    -27,   // ..wbbw.
    20,    // b.wbbw.
    52,    // w.wbbw.
    33,    // .bwbbw.
    34,    // bbwbbw.
    75,    // wbwbbw.
    15,    // .wwbbw.
    80,    // bwwbbw.
    29,    // wwwbbw.
    45,    // ...wbw.
    -58,   // b..wbw.
    -46,   // w..wbw.
    36,    // .b.wbw.
    6,     // bb.wbw.
    1,     // wb.wbw.
    -8,    // .w.wbw.
    68,    // bw.wbw.
    -13,   // ww.wbw.
    49,    // ..bwbw.
    -17,   // b.bwbw.
    37,    // w.bwbw.
    -19,   // .bbwbw.
    -9,    // bbbwbw.
    -85,   // wbbwbw.
    16,    // .wbwbw.
    28,    // bwbwbw.
    -15,   // wwbwbw.
    13,    // ..wwbw.
    -8,    // b.wwbw.
    -9,    // w.wwbw.
    -33,   // .bwwbw.
    -71,   // bbwwbw.
    21,    // wbwwbw.
    -61,   // .wwwbw.
    -6,    // bwwwbw.
    48,    // wwwwbw.
    -15,   // ....ww.
    -22,   // b...ww.
    27,    // w...ww.
    19,    // .b..ww.
    53,    // bb..ww.
    -30,   // wb..ww.
    5,     // .w..ww.
    33,    // bw..ww.
    4,     // ww..ww.
    28,    // ..b.ww.
    9,     // b.b.ww.
    50,    // w.b.ww.
    0,     // .bb.ww.
    22,    // bbb.ww.
    -53,   // wbb.ww.
    -5,    // .wb.ww.
    81,    // bwb.ww.
    13,    // wwb.ww.
    68,    // ..w.ww.
    -19,   // b.w.ww.
    2,     // w.w.ww.
    52,    // .bw.ww.
    57,    // bbw.ww.
    54,    // wbw.ww.
    -29,   // .ww.ww.
    15,    // bww.ww.
    -24,   // www.ww.
    -33,   // ...bww.
    2,     // b..bww.
    0,     // w..bww.
    -21,   // .b.bww.
    78,    // bb.bww.
    0,     // wb.bww.
    -36,   // .w.bww.
    -80,   // bw.bww.
    -59,   // ww.bww.
    5,     // ..bbww.
    -19,   // b.bbww.
    68,    // w.bbww.
    36,    // .bbbww.
    -18,   // bbbbww.
    -36,   // wbbbww.
    15,    // .wbbww.
    -27,   // bwbbww.
    116,   // wwbbww.
    -3,    // ..wbww.
    29,    // b.wbww.
    126,   // w.wbww.
    19,    // .bwbww.
    -127,  // bbwbww.
    57,    // wbwbww.
    0,     // .wwbww.
    56,    // bwwbww.
    8,     // wwwbww.
    -44,   // ...www.
    15,    // b..www.
    -33,   // w..www.
    -21,   // .b.www.
    -47,   // bb.www.
    -66,   // wb.www.
    -36,   // .w.www.
    -50,   // bw.www.
    37,    // ww.www.
    -58,   // ..bwww.
    10,    // b.bwww.
    9,     // w.bwww.
    -36,   // .bbwww.
    33,    // bbbwww.
    -72,   // wbbwww.
    -61,   // .wbwww.
    -50,   // bwbwww.
    108,   // wwbwww.
    -178,  // ..wwww.
    -58,   // b.wwww.
    -66,   // w.wwww.
    -83,   // .bwwww.
    -12,   // bbwwww.
    -18,   // wbwwww.
    68,    // .wwwww.
    36,    // bwwwww.
    19,    // wwwwww.
    14,    // ......b
    -38,   // b.....b
    0,     // w.....b
    14,    // .b....b
    -35,   // bb....b
    -12,   // wb....b
    49,    // .w....b
    41,    // bw....b
    -16,   // ww....b
    17,    // ..b...b
    42,    // b.b...b
    -58,   // w.b...b
    -27,   // .bb...b
    -42,   // bbb...b
    -47,   // wbb...b
    -24,   // .wb...b
    -16,   // bwb...b
    10,    // wwb...b
    29,    // ..w...b
    15,    // b.w...b
    25,    // w.w...b
    -25,   // .bw...b
    1,     // bbw...b
    -15,   // wbw...b
    -22,   // .ww...b
    -34,   // bww...b
    -30,   // www...b
    13,    // ...b..b
    14,    // b..b..b
    58,    // w..b..b
    -37,   // .b.b..b
    23,    // bb.b..b
    -5,    // wb.b..b
    -18,   // .w.b..b
    -77,   // bw.b..b
    104,   // ww.b..b
    -28,   // ..bb..b
    -88,   // b.bb..b
    8,     // w.bb..b
    33,    // .bbb..b
    27,    // bbbb..b
    -101,  // wbbb..b
    -16,   // .wbb..b
    134,   // bwbb..b
    -76,   // wwbb..b
    -36,   // ..wb..b
    13,    // b.wb..b
    42,    // w.wb..b
    46,    // .bwb..b
    -52,   // bbwb..b
    -20,   // wbwb..b
    2,     // .wwb..b
    -1,    // bwwb..b
    24,    // wwwb..b
    28,    // ...w..b
    -56,   // b..w..b
    -58,   // w..w..b
    -40,   // .b.w..b
    -2,    // bb.w..b
    -6,    // wb.w..b
    20,    // .w.w..b
    -46,   // bw.w..b
    25,    // ww.w..b
    90,    // ..bw..b
    13,    // b.bw..b
    27,    // w.bw..b
    0,     // .bbw..b
    25,    // bbbw..b
    -13,   // wbbw..b
    -58,   // .wbw..b
    -68,   // bwbw..b
    19,    // wwbw..b
    -8,    // ..ww..b
    -40,   // b.ww..b
    11,    // w.ww..b
    -19,   // .bww..b
    -52,   // bbww..b
    35,    // wbww..b
    15,    // .www..b
    13,    // bwww..b
    -11,   // wwww..b
    73,    // ....b.b
    42,    // b...b.b
    -25,   // w...b.b
    15,    // .b..b.b
    -41,   // bb..b.b
    82,    // wb..b.b
    5,     // .w..b.b
    69,    // bw..b.b
    11,    // ww..b.b
    26,    // ..b.b.b
    29,    // b.b.b.b
    36,    // w.b.b.b
    -2,    // .bb.b.b
    61,    // bbb.b.b
    -40,   // wbb.b.b
    -62,   // .wb.b.b
    -24,   // bwb.b.b
    -59,   // wwb.b.b
    30,    // ..w.b.b
    30,    // b.w.b.b
    0,     // w.w.b.b
    -52,   // .bw.b.b
    1,     // bbw.b.b
    27,    // wbw.b.b
    9,     // .ww.b.b
    68,    // bww.b.b
    -8,    // www.b.b
    24,    // ...bb.b
    -88,   // b..bb.b
    -11,   // w..bb.b
    -42,   // .b.bb.b
    -49,   // bb.bb.b
    -30,   // wb.bb.b
    71,    // .w.bb.b
    35,    // bw.bb.b
    -45,   // ww.bb.b
    60,    // ..bbb.b
    45,    // b.bbb.b
    -14,   // w.bbb.b
    66,    // .bbbb.b
    -64,   // bbbbb.b
    -2,    // wbbbb.b
    95,    // .wbbb.b
    -65,   // bwbbb.b
    22,    // wwbbb.b
    -30,   // ..wbb.b
    -5,    // b.wbb.b
    73,    // w.wbb.b
    9,     // .bwbb.b
    -28,   // bbwbb.b
    2,     // wbwbb.b
    -19,   // .wwbb.b
    -62,   // bwwbb.b
    81,    // wwwbb.b
    53,    // ...wb.b
    13,    // b..wb.b
    -42,   // w..wb.b
    25,    // .b.wb.b
    26,    // bb.wb.b
    55,    // wb.wb.b
    57,    // .w.wb.b
    -56,   // bw.wb.b
    49,    // ww.wb.b
    5,     // ..bwb.b
    49,    // b.bwb.b
    7,     // w.bwb.b
    -126,  // .bbwb.b
    -27,   // bbbwb.b
    -49,   // wbbwb.b
    -17,   // .wbwb.b
    17,    // bwbwb.b
    58,    // wwbwb.b
    32,    // ..wwb.b
    22,    // b.wwb.b
    -73,   // w.wwb.b
    -52,   // .bwwb.b
    25,    // bbwwb.b
    3,     // wbwwb.b
    10,    // .wwwb.b
    -6,    // bwwwb.b
    18,    // wwwwb.b
    16,    // ....w.b
    15,    // b...w.b
    58,    // w...w.b
    -18,   // .b..w.b
    2,     // bb..w.b
    93,    // wb..w.b
    -2,    // .w..w.b
    -5,    // bw..w.b
    -61,   // ww..w.b
    13,    // ..b.w.b
    30,    // b.b.w.b
    0,     // w.b.w.b
    -50,   // .bb.w.b
    53,    // bbb.w.b
    65,    // wbb.w.b
    -36,   // .wb.w.b
    43,    // bwb.w.b
    22,    // wwb.w.b
    55,    // ..w.w.b
    60,    // b.w.w.b
    -36,   // w.w.w.b
    16,    // .bw.w.b
    -25,   // bbw.w.b
    60,    // wbw.w.b
    -19,   // .ww.w.b
    1,     // bww.w.b
    22,    // www.w.b
    63,    // ...bw.b
    13,    // b..bw.b
    -27,   // w..bw.b
    -26,   // .b.bw.b
    -5,    // bb.bw.b
    25,    // wb.bw.b
    -24,   // .w.bw.b
    19,    // bw.bw.b
    -18,   // ww.bw.b
    -38,   // ..bbw.b
    -5,    // b.bbw.b
    -14,   // w.bbw.b
    -9,    // .bbbw.b
    28,    // bbbbw.b
    -35,   // wbbbw.b
    20,    // .wbbw.b
    39,    // bwbbw.b
    -45,   // wwbbw.b
    2,     // ..wbw.b
    -40,   // b.wbw.b
    -7,    // w.wbw.b
    -37,   // .bwbw.b
    -12,   // bbwbw.b
    -51,   // wbwbw.b
    29,    // .wwbw.b
    41,    // bwwbw.b
    -93,   // wwwbw.b
    -22,   // ...ww.b
    -40,   // b..ww.b
    -8,    // w..ww.b
    1,     // .b.ww.b
    3,     // bb.ww.b
    47,    // wb.ww.b
    -92,   // .w.ww.b
    55,    // bw.ww.b
    -47,   // ww.ww.b
    34,    // ..bww.b
    22,    // b.bww.b
    14,    // w.bww.b
    -68,   // .bbww.b
    30,    // bbbww.b
    67,    // wbbww.b
    -8,    // .wbww.b
    30,    // bwbww.b
    -61,   // wwbww.b
    34,    // ..www.b
    -56,   // b.www.b
    14,    // w.www.b
    92,    // .bwww.b
    12,    // bbwww.b
    32,    // wbwww.b
    -58,   // .wwww.b
    -10,   // bwwww.b
    -47,   // wwwww.b
    19,    // .....bb
    -35,   // b....bb
    16,    // w....bb
    13,    // .b...bb
    -22,   // bb...bb
    -23,   // wb...bb
    2,     // .w...bb
    16,    // bw...bb
    0,     // ww...bb
    -5,    // ..b..bb
    -41,   // b.b..bb
    61,    // w.b..bb
    -4,    // .bb..bb
    74,    // bbb..bb
    1,     // wbb..bb
    34,    // .wb..bb
    -59,   // bwb..bb
    22,    // wwb..bb
    -67,   // ..w..bb
    2,     // b.w..bb
    -11,   // w.w..bb
    46,    // .bw..bb
    0,     // bbw..bb
    -16,   // wbw..bb
    53,    // .ww..bb
    13,    // bww..bb
    58,    // www..bb
    84,    // ...b.bb
    23,    // b..b.bb
    -25,   // w..b.bb
    -33,   // .b.b.bb
    5,     // bb.b.bb
    85,    // wb.b.bb
    79,    // .w.b.bb
    -18,   // bw.b.bb
    21,    // ww.b.bb
    -7,    // ..bb.bb
    -49,   // b.bb.bb
    47,    // w.bb.bb
    -37,   // .bbb.bb
    -37,   // bbbb.bb
    12,    // wbbb.bb
    52,    // .wbb.bb
    -22,   // bwbb.bb
    -69,   // wwbb.bb
    -19,   // ..wb.bb
    -5,    // b.wb.bb
    -49,   // w.wb.bb
    13,    // .bwb.bb
    73,    // bbwb.bb
    32,    // wbwb.bb
    78,    // .wwb.bb
    -16,   // bwwb.bb
    11,    // wwwb.bb
    30,    // ...w.bb
    -2,    // b..w.bb
    -104,  // w..w.bb
    -84,   // .b.w.bb
    86,    // bb.w.bb
    3,     // wb.w.bb
    21,    // .w.w.bb
    34,    // bw.w.bb
    -21,   // ww.w.bb
    -65,   // ..bw.bb
    26,    // b.bw.bb
    18,    // w.bw.bb
    59,    // .bbw.bb
    -3,    // bbbw.bb
    18,    // wbbw.bb
    6,     // .wbw.bb
    18,    // bwbw.bb
    95,    // wwbw.bb
    10,    // ..ww.bb
    3,     // b.ww.bb
    45,    // w.ww.bb
    -83,   // .bww.bb
    -38,   // bbww.bb
    -41,   // wbww.bb
    -47,   // .www.bb
    -14,   // bwww.bb
    -39,   // wwww.bb
    153,   // ....bbb
    -42,   // b...bbb
    30,    // w...bbb
    42,    // .b..bbb
    74,    // bb..bbb
    31,    // wb..bbb
    52,    // .w..bbb
    6,     // bw..bbb
    -58,   // ww..bbb
    77,    // ..b.bbb
    61,    // b.b.bbb
    -22,   // w.b.bbb
    24,    // .bb.bbb
    61,    // bbb.bbb
    12,    // wbb.bbb
    -12,   // .wb.bbb
    -57,   // bwb.bbb
    -47,   // wwb.bbb
    46,    // ..w.bbb
    53,    // b.w.bbb
    8,     // w.w.bbb
    44,    // .bw.bbb
    49,    // bbw.bbb
    -34,   // wbw.bbb
    22,    // .ww.bbb
    -34,   // bww.bbb
    0,     // www.bbb
    312,   // ...bbbb
    27,    // b..bbbb
    11,    // w..bbbb
    -47,   // .b.bbbb
    -37,   // bb.bbbb
    38,    // wb.bbbb
    121,   // .w.bbbb
    83,    // bw.bbbb
    39,    // ww.bbbb
    56,    // ..bbbbb
    -64,   // b.bbbbb
    47,    // w.bbbbb
    -19,   // .bbbbbb
    -49,   // bbbbbbb
    -19,   // wbbbbbb
    91,    // .wbbbbb
    1,     // bwbbbbb
    32,    // wwbbbbb
    67,    // ..wbbbb
    28,    // b.wbbbb
    -18,   // w.wbbbb
    -48,   // .bwbbbb
    8,     // bbwbbbb
    64,    // wbwbbbb
    -18,   // .wwbbbb
    -4,    // bwwbbbb
    -57,   // wwwbbbb
    -9,    // ...wbbb
    25,    // b..wbbb
    -24,   // w..wbbb
    -16,   // .b.wbbb
    -3,    // bb.wbbb
    45,    // wb.wbbb
    -68,   // .w.wbbb
    37,    // bw.wbbb
    -11,   // ww.wbbb
    -126,  // ..bwbbb
    -27,   // b.bwbbb
    93,    // w.bwbbb
    -8,    // .bbwbbb
    24,    // bbbwbbb
    -174,  // wbbwbbb
    -9,    // .wbwbbb
    18,    // bwbwbbb
    -2,    // wwbwbbb
    53,    // ..wwbbb
    30,    // b.wwbbb
    -81,   // w.wwbbb
    -29,   // .bwwbbb
    -1,    // bbwwbbb
    -23,   // wbwwbbb
    33,    // .wwwbbb
    21,    // bwwwbbb
    57,    // wwwwbbb
    -40,   // ....wbb
    1,     // b...wbb
    -10,   // w...wbb
    -1,    // .b..wbb
    0,     // bb..wbb
    19,    // wb..wbb
    -39,   // .w..wbb
    33,    // bw..wbb
    -22,   // ww..wbb
    -31,   // ..b.wbb
    1,     // b.b.wbb
    -22,   // w.b.wbb
    -13,   // .bb.wbb
    49,    // bbb.wbb
    -11,   // wbb.wbb
    2,     // .wb.wbb
    42,    // bwb.wbb
    0,     // wwb.wbb
    16,    // ..w.wbb
    -25,   // b.w.wbb
    59,    // w.w.wbb
    -6,    // .bw.wbb
    -78,   // bbw.wbb
    -97,   // wbw.wbb
    57,    // .ww.wbb
    -2,    // bww.wbb
    47,    // www.wbb
    -61,   // ...bwbb
    -52,   // b..bwbb
    -19,   // w..bwbb
    37,    // .b.bwbb
    73,    // bb.bwbb
    17,    // wb.bwbb
    -22,   // .w.bwbb
    -37,   // bw.bwbb
    -95,   // ww.bwbb
    -8,    // ..bbwbb
    -28,   // b.bbwbb
    61,    // w.bbwbb
    -108,  // .bbbwbb
    8,     // bbbbwbb
    50,    // wbbbwbb
    34,    // .wbbwbb
    -6,    // bwbbwbb
    52,    // wwbbwbb
    21,    // ..wbwbb
    -12,   // b.wbwbb
    -58,   // w.wbwbb
    15,    // .bwbwbb
    -7,    // bbwbwbb
    99,    // wbwbwbb
    -127,  // .wwbwbb
    12,    // bwwbwbb
    2,     // wwwbwbb
    -40,   // ...wwbb
    -52,   // b..wwbb
    76,    // w..wwbb
    -26,   // .b.wwbb
    -38,   // bb.wwbb
    3,     // wb.wwbb
    14,    // .w.wwbb
    95,    // bw.wwbb
    69,    // ww.wwbb
    50,    // ..bwwbb
    25,    // b.bwwbb
    45,    // w.bwwbb
    -116,  // .bbwwbb
    -1,    // bbbwwbb
    -8,    // wbbwwbb
    -71,   // .wbwwbb
    -55,   // bwbwwbb
    -52,   // wwbwwbb
    0,     // ..wwwbb
    12,    // b.wwwbb
    -22,   // w.wwwbb
    26,    // .bwwwbb
    1,     // bbwwwbb
    -70,   // wbwwwbb
    -12,   // .wwwwbb
    10,    // bwwwwbb
    -32,   // wwwwwbb
    20,    // .....wb
    41,    // b....wb
    12,    // w....wb
    28,    // .b...wb
    16,    // bb...wb
    0,     // wb...wb
    -17,   // .w...wb
    -117,  // bw...wb
    23,    // ww...wb
    11,    // ..b..wb
    69,    // b.b..wb
    -93,   // w.b..wb
    30,    // .bb..wb
    6,     // bbb..wb
    -65,   // wbb..wb
    87,    // .wb..wb
    -49,   // bwb..wb
    -19,   // wwb..wb
    -21,   // ..w..wb
    -5,    // b.w..wb
    -82,   // w.w..wb
    -32,   // .bw..wb
    33,    // bbw..wb
    55,    // wbw..wb
    33,    // .ww..wb
    -19,   // bww..wb
    -31,   // www..wb
    10,    // ...b.wb
    -77,   // b..b.wb
    6,     // w..b.wb
    16,    // .b.b.wb
    -18,   // bb.b.wb
    32,    // wb.b.wb
    17,    // .w.b.wb
    -55,   // bw.b.wb
    -3,    // ww.b.wb
    47,    // ..bb.wb
    35,    // b.bb.wb
    -47,   // w.bb.wb
    66,    // .bbb.wb
    83,    // bbbb.wb
    -24,   // wbbb.wb
    10,    // .wbb.wb
    -30,   // bwbb.wb
    -3,    // wwbb.wb
    7,     // ..wb.wb
    19,    // b.wb.wb
    -55,   // w.wb.wb
    -1,    // .bwb.wb
    -37,   // bbwb.wb
    -59,   // wbwb.wb
    -80,   // .wwb.wb
    67,    // bwwb.wb
    -45,   // wwwb.wb
    39,    // ...w.wb
    -46,   // b..w.wb
    5,     // w..w.wb
    50,    // .b.w.wb
    34,    // bb.w.wb
    -32,   // wb.w.wb
    -18,   // .w.w.wb
    14,    // bw.w.wb
    -85,   // ww.w.wb
    27,    // ..bw.wb
    -56,   // b.bw.wb
    -25,   // w.bw.wb
    0,     // .bbw.wb
    37,    // bbbw.wb
    -44,   // wbbw.wb
    68,    // .wbw.wb
    60,    // bwbw.wb
    -17,   // wwbw.wb
    0,     // ..ww.wb
    55,    // b.ww.wb
    30,    // w.ww.wb
    -1,    // .bww.wb
    95,    // bbww.wb
    37,    // wbww.wb
    -50,   // .www.wb
    -72,   // bwww.wb
    -38,   // wwww.wb
    35,    // ....bwb
    -16,   // b...bwb
    15,    // w...bwb
    2,     // .b..bwb
    -59,   // bb..bwb
    -55,   // wb..bwb
    80,    // .w..bwb
    -49,   // bw..bwb
    16,    // ww..bwb
    -88,   // ..b.bwb
    -24,   // b.b.bwb
    -60,   // w.b.bwb
    -54,   // .bb.bwb
    -57,   // bbb.bwb
    33,    // wbb.bwb
    -1,    // .wb.bwb
    -17,   // bwb.bwb
    97,    // wwb.bwb
    20,    // ..w.bwb
    43,    // b.w.bwb
    -27,   // w.w.bwb
    -22,   // .bw.bwb
    42,    // bbw.bwb
    0,     // wbw.bwb
    81,    // .ww.bwb
    30,    // bww.bwb
    34,    // www.bwb
    7,     // ...bbwb
    134,   // b..bbwb
    -35,   // w..bbwb
    18,    // .b.bbwb
    -22,   // bb.bbwb
    -37,   // wb.bbwb
    -81,   // .w.bbwb
    -30,   // bw.bbwb
    41,    // ww.bbwb
    -23,   // ..bbbwb
    -65,   // b.bbbwb
    -32,   // w.bbbwb
    18,    // .bbbbwb
    1,     // bbbbbwb
    -104,  // wbbbbwb
    37,    // .wbbbwb
    69,    // bwbbbwb
    70,    // wwbbbwb
    17,    // ..wbbwb
    39,    // b.wbbwb
    -3,    // w.wbbwb
    -21,   // .bwbbwb
    -6,    // bbwbbwb
    72,    // wbwbbwb
    -27,   // .wwbbwb
    -36,   // bwwbbwb
    23,    // wwwbbwb
    -7,    // ...wbwb
    -68,   // b..wbwb
    20,    // w..wbwb
    28,    // .b.wbwb
    18,    // bb.wbwb
    59,    // wb.wbwb
    -53,   // .w.wbwb
    60,    // bw.wbwb
    -32,   // ww.wbwb
    -26,   // ..bwbwb
    17,    // b.bwbwb
    51,    // w.bwbwb
    -57,   // .bbwbwb
    18,    // bbbwbwb
    22,    // wbbwbwb
    28,    // .wbwbwb
    -51,   // bwbwbwb
    -99,   // wwbwbwb
    -31,   // ..wwbwb
    30,    // b.wwbwb
    -2,    // w.wwbwb
    -75,   // .bwwbwb
    -55,   // bbwwbwb
    -72,   // wbwwbwb
    -50,   // .wwwbwb
    17,    // bwwwbwb
    -64,   // wwwwbwb
    60,    // ....wwb
    -34,   // b...wwb
    47,    // w...wwb
    -26,   // .b..wwb
    13,    // bb..wwb
    65,    // wb..wwb
    -82,   // .w..wwb
    -19,   // bw..wwb
    -1,    // ww..wwb
    -4,    // ..b.wwb
    68,    // b.b.wwb
    -65,   // w.b.wwb
    53,    // .bb.wwb
    -34,   // bbb.wwb
    0,     // wbb.wwb
    13,    // .wb.wwb
    30,    // bwb.wwb
    11,    // wwb.wwb
    22,    // ..w.wwb
    1,     // b.w.wwb
    40,    // w.w.wwb
    -80,   // .bw.wwb
    -2,    // bbw.wwb
    -33,   // wbw.wwb
    15,    // .ww.wwb
    -75,   // bww.wwb
    -12,   // www.wwb
    -12,   // ...bwwb
    -1,    // b..bwwb
    13,    // w..bwwb
    36,    // .b.bwwb
    -16,   // bb.bwwb
    44,    // wb.bwwb
    76,    // .w.bwwb
    67,    // bw.bwwb
    -18,   // ww.bwwb
    -98,   // ..bbwwb
    -62,   // b.bbwwb
    -67,   // w.bbwwb
    72,    // .bbbwwb
    -4,    // bbbbwwb
    45,    // wbbbwwb
    80,    // .wbbwwb
    -36,   // bwbbwwb
    8,     // wwbbwwb
    -44,   // ..wbwwb
    41,    // b.wbwwb
    49,    // w.wbwwb
    85,    // .bwbwwb
    12,    // bbwbwwb
    -22,   // wbwbwwb
    56,    // .wwbwwb
    6,     // bwwbwwb
    174,   // wwwbwwb
    104,   // ...wwwb
    13,    // b..wwwb
    101,   // w..wwwb
    24,    // .b.wwwb
    -14,   // bb.wwwb
    24,    // wb.wwwb
    -80,   // .w.wwwb
    -72,   // bw.wwwb
    -12,   // ww.wwwb
    20,    // ..bwwwb
    -6,    // b.bwwwb
    35,    // w.bwwwb
    36,    // .bbwwwb
    21,    // bbbwwwb
    -45,   // wbbwwwb
    -6,    // .wbwwwb
    17,    // bwbwwwb
    -50,   // wwbwwwb
    -64,   // ..wwwwb
    -10,   // b.wwwwb
    2,     // w.wwwwb
    105,   // .bwwwwb
    10,    // bbwwwwb
    104,   // wbwwwwb
    36,    // .wwwwwb
    22,    // bwwwwwb
    19,    // wwwwwwb
    -14,   // ......w
    0,     // b.....w
    38,    // w.....w
    -49,   // .b....w
    16,    // bb....w
    -41,   // wb....w
    -14,   // .w....w
    12,    // bw....w
    35,    // ww....w
    -29,   // ..b...w
    -25,   // b.b...w
    -15,   // w.b...w
    22,    // .bb...w
    30,    // bbb...w
    34,    // wbb...w
    25,    // .wb...w
    15,    // bwb...w
    -1,    // wwb...w
    -17,   // ..w...w
    58,    // b.w...w
    -42,   // w.w...w
    24,    // .bw...w
    -10,   // bbw...w
    16,    // wbw...w
    27,    // .ww...w
    47,    // bww...w
    42,    // www...w
    -28,   // ...b..w
    58,    // b..b..w
    56,    // w..b..w
    -20,   // .b.b..w
    -25,   // bb.b..w
    46,    // wb.b..w
    40,    // .w.b..w
    6,     // bw.b..w
    2,     // ww.b..w
    8,     // ..bb..w
    -11,   // b.bb..w
    40,    // w.bb..w
    -15,   // .bbb..w
    11,    // bbbb..w
    -13,   // wbbb..w
    19,    // .wbb..w
    -35,   // bwbb..w
    52,    // wwbb..w
    -90,   // ..wb..w
    -27,   // b.wb..w
    -13,   // w.wb..w
    58,    // .bwb..w
    -19,   // bbwb..w
    68,    // wbwb..w
    0,     // .wwb..w
    13,    // bwwb..w
    -25,   // wwwb..w
    -13,   // ...w..w
    -58,   // b..w..w
    -14,   // w..w..w
    18,    // .b.w..w
    -104,  // bb.w..w
    77,    // wb.w..w
    37,    // .w.w..w
    5,     // bw.w..w
    -23,   // ww.w..w
    36,    // ..bw..w
    -42,   // b.bw..w
    -13,   // w.bw..w
    -2,    // .bbw..w
    -24,   // bbbw..w
    1,     // wbbw..w
    -46,   // .wbw..w
    20,    // bwbw..w
    52,    // wwbw..w
    28,    // ..ww..w
    -8,    // b.ww..w
    88,    // w.ww..w
    16,    // .bww..w
    76,    // bbww..w
    -134,  // wbww..w
    -33,   // .www..w
    101,   // bwww..w
    -27,   // wwww..w
    -16,   // ....b.w
    -58,   // b...b.w
    -15,   // w...b.w
    2,     // .b..b.w
    61,    // bb..b.w
    5,     // wb..b.w
    18,    // .w..b.w
    -93,   // bw..b.w
    -2,    // ww..b.w
    -55,   // ..b.b.w
    36,    // b.b.b.w
    -60,   // w.b.b.w
    19,    // .bb.b.w
    -22,   // bbb.b.w
    -1,    // wbb.b.w
    -16,   // .wb.b.w
    -60,   // bwb.b.w
    25,    // wwb.b.w
    -13,   // ..w.b.w
    0,     // b.w.b.w
    -30,   // w.w.b.w
    36,    // .bw.b.w
    -22,   // bbw.b.w
    -43,   // wbw.b.w
    50,    // .ww.b.w
    -65,   // bww.b.w
    -53,   // www.b.w
    22,    // ...bb.w
    8,     // b..bb.w
    40,    // w..bb.w
    92,    // .b.bb.w
    47,    // bb.bb.w
    -55,   // wb.bb.w
    -1,    // .w.bb.w
    -47,   // bw.bb.w
    -3,    // ww.bb.w
    -34,   // ..bbb.w
    -14,   // b.bbb.w
    56,    // w.bbb.w
    58,    // .bbbb.w
    47,    // bbbbb.w
    10,    // wbbbb.w
    -92,   // .wbbb.w
    -32,   // bwbbb.w
    -12,   // wwbbb.w
    -34,   // ..wbb.w
    -14,   // b.wbb.w
    -22,   // w.wbb.w
    8,     // .bwbb.w
    61,    // bbwbb.w
    -30,   // wbwbb.w
    68,    // .wwbb.w
    -67,   // bwwbb.w
    -30,   // wwwbb.w
    -63,   // ...wb.w
    27,    // b..wb.w
    -13,   // w..wb.w
    24,    // .b.wb.w
    18,    // bb.wb.w
    -19,   // wb.wb.w
    26,    // .w.wb.w
    -25,   // bw.wb.w
    5,     // ww.wb.w
    -2,    // ..bwb.w
    7,     // b.bwb.w
    40,    // w.bwb.w
    -29,   // .bbwb.w
    93,    // bbbwb.w
    -41,   // wbbwb.w
    37,    // .wbwb.w
    51,    // bwbwb.w
    12,    // wwbwb.w
    38,    // ..wwb.w
    14,    // b.wwb.w
    5,     // w.wwb.w
    -20,   // .bwwb.w
    45,    // bbwwb.w
    -39,   // wbwwb.w
    9,     // .wwwb.w
    35,    // bwwwb.w
    -28,   // wwwwb.w
    -73,   // ....w.w
    25,    // b...w.w
    -42,   // w...w.w
    -5,    // .b..w.w
    -11,   // bb..w.w
    -69,   // wb..w.w
    -15,   // .w..w.w
    -82,   // bw..w.w
    41,    // ww..w.w
    -30,   // ..b.w.w
    0,     // b.b.w.w
    -30,   // w.b.w.w
    -9,    // .bb.w.w
    8,     // bbb.w.w
    -68,   // wbb.w.w
    52,    // .wb.w.w
    -27,   // bwb.w.w
    -1,    // wwb.w.w
    -26,   // ..w.w.w
    -36,   // b.w.w.w
    -29,   // w.w.w.w
    62,    // .bw.w.w
    59,    // bbw.w.w
    24,    // wbw.w.w
    2,     // .ww.w.w
    40,    // bww.w.w
    -61,   // www.w.w
    -53,   // ...bw.w
    42,    // b..bw.w
    -13,   // w..bw.w
    -57,   // .b.bw.w
    -49,   // bb.bw.w
    56,    // wb.bw.w
    -25,   // .w.bw.w
    -55,   // bw.bw.w
    -26,   // ww.bw.w
    -32,   // ..bbw.w
    73,    // b.bbw.w
    -22,   // w.bbw.w
    -10,   // .bbbw.w
    -18,   // bbbbw.w
    6,     // wbbbw.w
    52,    // .wbbw.w
    -3,    // bwbbw.w
    -25,   // wwbbw.w
    -5,    // ..wbw.w
    -7,    // b.wbw.w
    -49,   // w.wbw.w
    17,    // .bwbw.w
    -58,   // bbwbw.w
    -17,   // wbwbw.w
    126,   // .wwbw.w
    49,    // bwwbw.w
    27,    // wwwbw.w
    -24,   // ...ww.w
    11,    // b..ww.w
    88,    // w..ww.w
    -71,   // .b.ww.w
    45,    // bb.ww.w
    -35,   // wb.ww.w
    42,    // .w.ww.w
    30,    // bw.ww.w
    49,    // ww.ww.w
    30,    // ..bww.w
    -73,   // b.bww.w
    5,     // w.bww.w
    19,    // .bbww.w
    -81,   // bbbww.w
    62,    // wbbww.w
    -9,    // .wbww.w
    -2,    // bwbww.w
    28,    // wwbww.w
    -60,   // ..www.w
    14,    // b.www.w
    -45,   // w.www.w
    -95,   // .bwww.w
    -22,   // bbwww.w
    65,    // wbwww.w
    -66,   // .wwww.w
    2,     // bwwww.w
    64,    // wwwww.w
    -20,   // .....bw
    -12,   // b....bw
    -41,   // w....bw
    17,    // .b...bw
    -23,   // bb...bw
    117,   // wb...bw
    -28,   // .w...bw
    0,     // bw...bw
    -16,   // ww...bw
    21,    // ..b..bw
    82,    // b.b..bw
    5,     // w.b..bw
    -33,   // .bb..bw
    31,    // bbb..bw
    19,    // wbb..bw
    32,    // .wb..bw
    -55,   // bwb..bw
    -33,   // wwb..bw
    -11,   // ..w..bw
    93,    // b.w..bw
    -69,   // w.w..bw
    -87,   // .bw..bw
    19,    // bbw..bw
    49,    // wbw..bw
    -30,   // .ww..bw
    65,    // bww..bw
    -6,    // www..bw
    -39,   // ...b.bw
    -5,    // b..b.bw
    46,    // w..b.bw
    18,    // .b.b.bw
    85,    // bb.b.bw
    -14,   // wb.b.bw
    -50,   // .w.b.bw
    32,    // bw.b.bw
    -34,   // ww.b.bw
    0,     // ..bb.bw
    -30,   // b.bb.bw
    -55,   // w.bb.bw
    50,    // .bbb.bw
    38,    // bbbb.bw
    72,    // wbbb.bw
    1,     // .wbb.bw
    -37,   // bwbb.bw
    -95,   // wwbb.bw
    -27,   // ..wb.bw
    25,    // b.wb.bw
    56,    // w.wb.bw
    -68,   // .bwb.bw
    17,    // bbwb.bw
    -60,   // wbwb.bw
    0,     // .wwb.bw
    44,    // bwwb.bw
    -37,   // wwwb.bw
    -10,   // ...w.bw
    -6,    // b..w.bw
    77,    // w..w.bw
    -17,   // .b.w.bw
    3,     // bb.w.bw
    55,    // wb.w.bw
    -16,   // .w.w.bw
    -32,   // bw.w.bw
    18,    // ww.w.bw
    -7,    // ..bw.bw
    55,    // b.bw.bw
    -19,   // w.bw.bw
    80,    // .bbw.bw
    45,    // bbbw.bw
    -67,   // wbbw.bw
    1,     // .wbw.bw
    59,    // bwbw.bw
    37,    // wwbw.bw
    -47,   // ..ww.bw
    47,    // b.ww.bw
    -35,   // w.ww.bw
    -10,   // .bww.bw
    3,     // bbww.bw
    30,    // wbww.bw
    -66,   // .www.bw
    24,    // bwww.bw
    -83,   // wwww.bw
    -60,   // ....bbw
    -47,   // b...bbw
    34,    // w...bbw
    82,    // .b..bbw
    1,     // bb..bbw
    19,    // wb..bbw
    26,    // .w..bbw
    -65,   // bw..bbw
    -13,   // ww..bbw
    -22,   // ..b.bbw
    -40,   // b.b.bbw
    -1,    // w.b.bbw
    -15,   // .bb.bbw
    12,    // bbb.bbw
    75,    // wbb.bbw
    80,    // .wb.bbw
    33,    // bwb.bbw
    2,     // wwb.bbw
    4,     // ..w.bbw
    65,    // b.w.bbw
    -68,   // w.w.bbw
    -13,   // .bw.bbw
    -11,   // bbw.bbw
    -30,   // wbw.bbw
    -53,   // .ww.bbw
    0,     // bww.bbw
    34,    // www.bbw
    -104,  // ...bbbw
    -101,  // b..bbbw
    -13,   // w..bbbw
    80,    // .b.bbbw
    12,    // bb.bbbw
    72,    // wb.bbbw
    -24,   // .w.bbbw
    -24,   // bw.bbbw
    14,    // ww.bbbw
    64,    // ..bbbbw
    -2,    // b.bbbbw
    10,    // w.bbbbw
    -36,   // .bbbbbw
    -19,   // bbbbbbw
    -22,   // wbbbbbw
    -105,  // .wbbbbw
    -104,  // bwbbbbw
    -10,   // wwbbbbw
    -20,   // ..wbbbw
    -35,   // b.wbbbw
    6,     // w.wbbbw
    6,     // .bwbbbw
    50,    // bbwbbbw
    -17,   // wbwbbbw
    -36,   // .wwbbbw
    45,    // bwwbbbw
    -21,   // wwwbbbw
    12,    // ...wbbw
    -13,   // b..wbbw
    1,     // w..wbbw
    -76,   // .b.wbbw
    18,    // bb.wbbw
    -67,   // wb.wbbw
    -36,   // .w.wbbw
    -44,   // bw.wbbw
    16,    // ww.wbbw
    44,    // ..bwbbw
    -49,   // b.bwbbw
    -41,   // w.bwbbw
    -56,   // .bbwbbw
    -174,  // bbbwbbw
    -6,    // wbbwbbw
    -85,   // .wbwbbw
    22,    // bwbwbbw
    -12,   // wwbwbbw
    98,    // ..wwbbw
    67,    // b.wwbbw
    62,    // w.wwbbw
    -80,   // .bwwbbw
    -8,    // bbwwbbw
    36,    // wbwwbbw
    -72,   // .wwwbbw
    -45,   // bwwwbbw
    4,     // wwwwbbw
    -35,   // ....wbw
    -15,   // b...wbw
    16,    // w...wbw
    -80,   // .b..wbw
    -16,   // bb..wbw
    49,    // wb..wbw
    -2,    // .w..wbw
    55,    // bw..wbw
    59,    // ww..wbw
    -20,   // ..b.wbw
    27,    // b.b.wbw
    -43,   // w.b.wbw
    -81,   // .bb.wbw
    -34,   // bbb.wbw
    -30,   // wbb.wbw
    22,    // .wb.wbw
    0,     // bwb.wbw
    -42,   // wwb.wbw
    88,    // ..w.wbw
    60,    // b.w.wbw
    24,    // w.w.wbw
    1,     // .bw.wbw
    -97,   // bbw.wbw
    17,    // wbw.wbw
    54,    // .ww.wbw
    -33,   // bww.wbw
    57,    // www.wbw
    7,     // ...bwbw
    -20,   // b..bwbw
    68,    // w..bwbw
    53,    // .b.bwbw
    32,    // bb.bwbw
    -60,   // wb.bwbw
    -28,   // .w.bwbw
    -59,   // bw.bwbw
    -18,   // ww.bwbw
    31,    // ..bbwbw
    2,     // b.bbwbw
    -30,   // w.bbwbw
    50,    // .bbbwbw
    64,    // bbbbwbw
    -17,   // wbbbwbw
    75,    // .wbbwbw
    72,    // bwbbwbw
    55,    // wwbbwbw
    26,    // ..wbwbw
    -51,   // b.wbwbw
    -17,   // w.wbwbw
    -28,   // .bwbwbw
    99,    // bbwbwbw
    51,    // wbwbwbw
    57,    // .wwbwbw
    -22,   // bwwbwbw
    -18,   // wwwbwbw
    -7,    // ...wwbw
    35,    // b..wwbw
    -134,  // w..wwbw
    81,    // .b.wwbw
    -41,   // bb.wwbw
    30,    // wb.wwbw
    -18,   // .w.wwbw
    37,    // bw.wwbw
    22,    // ww.wwbw
    -17,   // ..bwwbw
    3,     // b.bwwbw
    -39,   // w.bwwbw
    27,    // .bbwwbw
    -23,   // bbbwwbw
    36,    // wbbwwbw
    21,    // .wbwwbw
    -72,   // bwbwwbw
    6,     // wwbwwbw
    23,    // ..wwwbw
    32,    // b.wwwbw
    65,    // w.wwwbw
    -37,   // .bwwwbw
    -70,   // bbwwwbw
    -69,   // wbwwwbw
    -18,   // .wwwwbw
    104,   // bwwwwbw
    -1,    // wwwwwbw
    -19,   // .....ww
    -16,   // b....ww
    35,    // w....ww
    -2,    // .b...ww
    0,     // bb...ww
    -16,   // wb...ww
    -13,   // .w...ww
    23,    // bw...ww
    22,    // ww...ww
    67,    // ..b..ww
    11,    // b.b..ww
    -2,    // w.b..ww
    -53,   // .bb..ww
    -58,   // bbb..ww
    -13,   // wbb..ww
    -46,   // .wb..ww
    16,    // bwb..ww
    0,     // wwb..ww
    5,     // ..w..ww
    -61,   // b.w..ww
    41,    // w.w..ww
    -34,   // .bw..ww
    -22,   // bbw..ww
    59,    // wbw..ww
    4,     // .ww..ww
    -1,    // bww..ww
    -74,   // www..ww
    -30,   // ...b.ww
    104,   // b..b.ww
    2,     // w..b.ww
    -21,   // .b.b.ww
    21,    // bb.b.ww
    -34,   // wb.b.ww
    84,    // .w.b.ww
    -3,    // bw.b.ww
    -86,   // ww.b.ww
    -10,   // ..bb.ww
    -45,   // b.bb.ww
    -3,    // w.bb.ww
    47,    // .bbb.ww
    39,    // bbbb.ww
    14,    // wbbb.ww
    83,    // .wbb.ww
    41,    // bwbb.ww
    38,    // wwbb.ww
    65,    // ..wb.ww
    -18,   // b.wb.ww
    -26,   // w.wb.ww
    -6,    // .bwb.ww
    -95,   // bbwb.ww
    -18,   // wbwb.ww
    -59,   // .wwb.ww
    -18,   // bwwb.ww
    3,     // wwwb.ww
    -84,   // ...w.ww
    25,    // b..w.ww
    -23,   // w..w.ww
    -79,   // .b.w.ww
    -21,   // bb.w.ww
    18,    // wb.w.ww
    33,    // .w.w.ww
    -85,   // bw.w.ww
    -5,    // ww.w.ww
    19,    // ..bw.ww
    49,    // b.bw.ww
    5,     // w.bw.ww
    -78,   // .bbw.ww
    -11,   // bbbw.ww
    16,    // wbbw.ww
    -13,   // .wbw.ww
    -32,   // bwbw.ww
    -73,   // wwbw.ww
    7,     // ..ww.ww
    -47,   // b.ww.ww
    49,    // w.ww.ww
    -52,   // .bww.ww
    69,    // bbww.ww
    22,    // wbww.ww
    37,    // .www.ww
    -12,   // bwww.ww
    37,    // wwww.ww
    40,    // ....bww
    10,    // b...bww
    -1,    // w...bww
    39,    // .b..bww
    22,    // bb..bww
    -33,   // wb..bww
    1,     // .w..bww
    -19,   // bw..bww
    0,     // ww..bww
    -16,   // ..b.bww
    -59,   // b.b.bww
    25,    // w.b.bww
    -57,   // .bb.bww
    -47,   // bbb.bww
    2,     // wbb.bww
    6,     // .wb.bww
    97,    // bwb.bww
    78,    // wwb.bww
    31,    // ..w.bww
    22,    // b.w.bww
    -1,    // w.w.bww
    -2,    // .bw.bww
    0,     // bbw.bww
    -42,   // wbw.bww
    13,    // .ww.bww
    11,    // bww.bww
    -49,   // www.bww
    40,    // ...bbww
    -76,   // b..bbww
    52,    // w..bbww
    -14,   // .b.bbww
    -69,   // bb.bbww
    -95,   // wb.bbww
    26,    // .w.bbww
    -3,    // bw.bbww
    38,    // ww.bbww
    0,     // ..bbbww
    22,    // b.bbbww
    -12,   // w.bbbww
    12,    // .bbbbww
    32,    // bbbbbww
    -10,   // wbbbbww
    -26,   // .wbbbww
    70,    // bwbbbww
    -1,    // wwbbbww
    -50,   // ..wbbww
    -45,   // b.wbbww
    -25,   // w.wbbww
    71,    // .bwbbww
    52,    // bbwbbww
    55,    // wbwbbww
    116,   // .wwbbww
    8,     // bwwbbww
    1,     // wwwbbww
    61,    // ...wbww
    19,    // b..wbww
    52,    // w..wbww
    22,    // .b.wbww
    95,    // bb.wbww
    37,    // wb.wbww
    -37,   // .w.wbww
    -17,   // bw.wbww
    -73,   // ww.wbww
    -21,   // ..bwbww
    58,    // b.bwbww
    12,    // w.bwbww
    127,   // .bbwbww
    -2,    // bbbwbww
    -12,   // wbbwbww
    -15,   // .wbwbww
    -99,   // bwbwbww
    7,     // wwbwbww
    8,     // ..wwbww
    -61,   // b.wwbww
    28,    // w.wwbww
    -34,   // .bwwbww
    -52,   // bbwwbww
    6,     // wbwwbww
    108,   // .wwwbww
    -50,   // bwwwbww
    -8,    // wwwwbww
    -153,  // ....www
    -30,   // b...www
    42,    // w...www
    -52,   // .b..www
    58,    // bb..www
    -6,    // wb..www
    -42,   // .w..www
    -31,   // bw..www
    -74,   // ww..www
    -46,   // ..b.www
    -8,    // b.b.www
    -53,   // w.b.www
    -22,   // .bb.www
    0,     // bbb.www
    34,    // wbb.www
    -44,   // .wb.www
    34,    // bwb.www
    -49,   // wwb.www
    -77,   // ..w.www
    22,    // b.w.www
    -61,   // w.w.www
    12,    // .bw.www
    47,    // bbw.www
    57,    // wbw.www
    -24,   // .ww.www
    -12,   // bww.www
    -61,   // www.www
    9,     // ...bwww
    24,    // b..bwww
    -25,   // w..bwww
    68,    // .b.bwww
    11,    // bb.bwww
    -37,   // wb.bwww
    16,    // .w.bwww
    -45,   // bw.bwww
    3,     // ww.bwww
    -53,   // ..bbwww
    81,    // b.bbwww
    -30,   // w.bbwww
    -33,   // .bbbwww
    -57,   // bbbbwww
    -21,   // wbbbwww
    29,    // .wbbwww
    23,    // bwbbwww
    1,     // wwbbwww
    126,   // ..wbwww
    -93,   // b.wbwww
    27,    // w.wbwww
    9,     // .bwbwww
    2,     // bbwbwww
    -18,   // wbwbwww
    8,     // .wwbwww
    174,   // bwwbwww
    -24,   // wwwbwww
    -312,  // ...wwww
    -11,   // b..wwww
    -27,   // w..wwww
    -121,  // .b.wwww
    -39,   // bb.wwww
    -83,   // wb.wwww
    47,    // .w.wwww
    -38,   // bw.wwww
    37,    // ww.wwww
    -67,   // ..bwwww
    18,    // b.bwwww
    -28,   // w.bwwww
    18,    // .bbwwww
    57,    // bbbwwww
    4,     // wbbwwww
    48,    // .wbwwww
    -64,   // bwbwwww
    -8,    // wwbwwww
    -56,   // ..wwwww
    -47,   // b.wwwww
    64,    // w.wwwww
    -91,   // .bwwwww
    -32,   // bbwwwww
    -1,    // wbwwwww
    19,    // .wwwwww
    19,    // bwwwwww
    49,    // wwwwwww
    0,     // ccc
    128,   // cc
    62,    // c
    -5,    // ttt
    59,    // tt
    31,    // t
    48,    // ct
    13,    // cct
    -4,    // ctt
].into_boxed_slice()
