#!/bin/sh

# Activate with the following command: make setup_git_hooks

make test

sed -e 's/pub fn new/pub fn old/g' < src/heuristics/new.rs > /tmp/old.rs
diff /tmp/old.rs src/heuristics/old.rs

sed -e 's/pub fn abp_new/pub fn abp_old/g' < src/bots/abp_new.rs > /tmp/abp_old.rs
diff /tmp/abp_old.rs src/bots/abp_old.rs
