#!/bin/sh

# Activate with the following command: make setup_git_hooks

set -e

make test

diff coeffs/coeffs_002ms_new.rs coeffs/coeffs_002ms_old.rs
diff coeffs/coeffs_008ms_new.rs coeffs/coeffs_008ms_old.rs
diff coeffs/coeffs_032ms_new.rs coeffs/coeffs_032ms_old.rs

sed -e 's/pub fn idabp_new/pub fn idabp_old/g' < src/bots/idabp_new.rs > /tmp/idabp_old.rs
diff /tmp/idabp_old.rs src/bots/idabp_old.rs
