use crate::{
    bots::idabp::idabp,
    game::{Game, state::GameState},
    heuristics::{Heuristic, coeffistic::coeffistic},
    player::{Player, PlayerColor},
};
use itertools::Itertools as _;
use nannou::rand::{Rng as _, rngs::ThreadRng, thread_rng};
use rayon::{
    ThreadPoolBuilder,
    iter::{IntoParallelIterator as _, ParallelIterator as _},
};
use std::{
    cmp::{max, min},
    fs::File,
    io::{self, BufWriter, Write as _},
    sync::{Arc, Mutex},
    thread::available_parallelism,
};

// Generated by scripts/unique_coeffs.py

const STENCIL_INDICES: [usize; 182] = [
    1, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 82, 83, 84, 85, 86, 88, 89, 91, 92, 93, 94,
    95, 96, 97, 98, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 112, 113, 115, 116, 118, 119,
    120, 121, 122, 123, 124, 125, 127, 128, 129, 130, 131, 133, 134, 136, 137, 139, 140, 142, 143,
    145, 146, 148, 149, 151, 152, 154, 155, 156, 157, 158, 160, 161, 244, 247, 248, 250, 251, 253,
    254, 256, 257, 259, 260, 262, 263, 265, 266, 268, 269, 274, 275, 277, 278, 280, 281, 283, 284,
    286, 287, 289, 292, 293, 295, 296, 301, 302, 304, 305, 310, 311, 313, 314, 316, 319, 320, 322,
    323, 328, 329, 331, 337, 338, 340, 341, 346, 347, 349, 350, 356, 358, 364, 365, 367, 368, 373,
    374, 376, 383, 385, 392, 394, 400, 401, 403, 412, 419, 421, 428, 430, 446, 448, 457, 484,
];
const STENCIL_INDICES_SYM: [usize; 182] = [
    243, 81, 324, 567, 27, 270, 513, 108, 351, 594, 189, 432, 675, 252, 495, 90, 333, 576, 171,
    414, 657, 36, 279, 522, 117, 360, 603, 198, 441, 684, 306, 549, 144, 387, 630, 225, 468, 711,
    246, 489, 84, 327, 570, 408, 651, 273, 516, 111, 354, 597, 192, 435, 678, 300, 543, 138, 381,
    624, 219, 462, 705, 255, 498, 336, 579, 417, 660, 282, 525, 120, 363, 606, 201, 444, 687, 309,
    552, 147, 390, 633, 471, 714, 264, 507, 345, 588, 426, 669, 291, 534, 372, 615, 453, 696, 318,
    561, 156, 399, 642, 480, 723, 244, 325, 568, 406, 649, 271, 514, 352, 595, 433, 676, 298, 541,
    379, 622, 460, 703, 334, 577, 415, 658, 280, 523, 361, 604, 442, 685, 307, 388, 631, 469, 712,
    343, 586, 424, 667, 370, 613, 451, 694, 316, 397, 640, 478, 721, 328, 571, 409, 355, 598, 436,
    679, 382, 625, 463, 706, 580, 418, 364, 607, 445, 688, 391, 634, 472, 589, 427, 616, 454, 400,
    643, 481, 412, 601, 439, 628, 466, 610, 448, 475, 484,
];
const STENCIL_INDICES_OPP: [usize; 182] = [
    2, 6, 8, 7, 18, 20, 19, 24, 26, 25, 21, 23, 22, 56, 55, 60, 62, 61, 57, 59, 58, 72, 74, 73, 78,
    80, 79, 75, 77, 76, 65, 64, 69, 71, 70, 66, 68, 67, 164, 163, 168, 170, 169, 167, 166, 182,
    181, 186, 188, 187, 183, 185, 184, 173, 172, 177, 179, 178, 174, 176, 175, 218, 217, 224, 223,
    221, 220, 236, 235, 240, 242, 241, 237, 239, 238, 227, 226, 231, 233, 232, 230, 229, 191, 190,
    197, 196, 194, 193, 209, 208, 215, 214, 212, 211, 200, 199, 204, 206, 205, 203, 202, 488, 494,
    493, 491, 490, 506, 505, 512, 511, 509, 508, 497, 496, 503, 502, 500, 499, 548, 547, 545, 544,
    560, 559, 566, 565, 563, 562, 551, 557, 556, 554, 553, 521, 520, 518, 517, 539, 538, 536, 535,
    524, 530, 529, 527, 526, 656, 655, 653, 674, 673, 671, 670, 665, 664, 662, 661, 709, 707, 728,
    727, 725, 724, 719, 718, 716, 682, 680, 700, 698, 692, 691, 689, 572, 592, 590, 583, 581, 646,
    644, 635, 608,
];
const STENCIL_INDICES_SYM_OPP: [usize; 182] = [
    486, 162, 648, 405, 54, 540, 297, 216, 702, 459, 135, 621, 378, 504, 261, 180, 666, 423, 99,
    585, 342, 72, 558, 315, 234, 720, 477, 153, 639, 396, 531, 288, 207, 693, 450, 126, 612, 369,
    492, 249, 168, 654, 411, 573, 330, 546, 303, 222, 708, 465, 141, 627, 384, 519, 276, 195, 681,
    438, 114, 600, 357, 510, 267, 672, 429, 591, 348, 564, 321, 240, 726, 483, 159, 645, 402, 537,
    294, 213, 699, 456, 618, 375, 501, 258, 663, 420, 582, 339, 555, 312, 717, 474, 636, 393, 528,
    285, 204, 690, 447, 609, 366, 488, 650, 407, 569, 326, 542, 299, 704, 461, 623, 380, 515, 272,
    677, 434, 596, 353, 668, 425, 587, 344, 560, 317, 722, 479, 641, 398, 533, 695, 452, 614, 371,
    659, 416, 578, 335, 713, 470, 632, 389, 524, 686, 443, 605, 362, 656, 413, 575, 710, 467, 629,
    386, 683, 440, 602, 359, 431, 593, 728, 485, 647, 404, 701, 458, 620, 422, 584, 476, 638, 692,
    449, 611, 572, 464, 626, 437, 599, 482, 644, 617, 608,
];

const COEFFS_FILE: &str = "./coeffs/current.rs";

const N_STENCIL_COEFFS: usize = 3usize.pow(6);
const N_COEFFS: usize = N_STENCIL_COEFFS + 9;

const N_MUTATIONS: usize = 4;
const REQUIRED_WINS: u32 = 11;

const MAX_ADDITIVE_MUTATION: i64 = 32;
// bias towards values closer to 0
const MIN_MULTIPLICATIVE_MUTATION: f64 = 0.74;
const MAX_MULTIPLICATIVE_MUTATION: f64 = 1.25;

const MAX_COEFF_VALUE: i64 = 999_999;
const MIN_COEFF_VALUE: i64 = -MAX_COEFF_VALUE;

#[expect(clippy::too_many_lines)]
pub fn run(num_threads: Option<usize>) {
    let initial_coeffs = include!("../coeffs/current.rs");

    let coeffs = Arc::new(Mutex::new(initial_coeffs));
    let stats = Arc::new(Mutex::new((0u32, 0u32)));

    // TODO: if 1 thread, no parallelism
    // TODO: no global (if we need to do stuff after training)
    // TODO: understand why 10 threads is faster than 20
    let num_threads = num_threads.unwrap_or(1); // TODO: if 1, no par_iter
    let available_cpus = available_parallelism().unwrap().get();
    assert!(num_threads > 0, "Can't run with 0 threads.");
    assert!(
        num_threads <= available_cpus,
        "You asked for {num_threads} threads but only {available_cpus} threads are available.",
    );
    ThreadPoolBuilder::new().num_threads(num_threads).build_global().unwrap();

    // TODO: find a cleaner infinite loop
    (0..usize::MAX).into_par_iter().for_each(|_| {
        let prev_coeffs = *coeffs.lock().unwrap();
        let prev_player = Player::Bot {
            bot: idabp,
            heuristic: Heuristic { fun: coeffistic, coeffs: Some(*coeffs.lock().unwrap()) },
        };

        let mut rng = thread_rng();

        let mut mutations = [(usize::MAX, 0); N_MUTATIONS];
        let mut n_mutations = 0;
        while n_mutations < N_MUTATIONS {
            if rng.gen_ratio(1, 8) {
                let coeff_idx = rng.gen_range(N_STENCIL_COEFFS..N_COEFFS);
                if mutations.iter().any(|(j, _)| coeff_idx == *j) {
                    continue;
                }
                let new_coeff = random_coeff(&mut rng, prev_coeffs[coeff_idx]).max(0);
                mutations[n_mutations] = (coeff_idx, new_coeff);
                n_mutations += 1;
                continue;
            }

            let i = rng.gen_range(0..STENCIL_INDICES.len());
            if mutations.iter().any(|(j, _)| i == *j) {
                continue;
            }

            let new_coeff = random_coeff(&mut rng, prev_coeffs[STENCIL_INDICES[i]]);
            mutations[n_mutations] = (i, new_coeff);
            n_mutations += 1;
        }

        let mut total_wins = [0; N_MUTATIONS];
        for mutated_indices in (0..N_MUTATIONS).powerset() {
            if mutated_indices.is_empty() {
                continue;
            }

            let mut new_coeffs = prev_coeffs;
            for i in &mutated_indices {
                let (coeff_idx, new_value) = mutations[*i];
                if coeff_idx >= N_STENCIL_COEFFS {
                    new_coeffs[coeff_idx] = new_value;
                } else {
                    new_coeffs[STENCIL_INDICES[coeff_idx]] = new_value;
                    new_coeffs[STENCIL_INDICES_SYM[coeff_idx]] = new_value;
                    new_coeffs[STENCIL_INDICES_OPP[coeff_idx]] = -new_value;
                    new_coeffs[STENCIL_INDICES_SYM_OPP[coeff_idx]] = -new_value;
                }
            }

            let new_player = Player::Bot {
                bot: idabp,
                heuristic: Heuristic { fun: coeffistic, coeffs: Some(new_coeffs) },
            };
            let wins = play_pair(&prev_player, &new_player, &mut rng);
            for i in &mutated_indices {
                total_wins[*i] += wins;
            }
        }

        let new_updates = total_wins.iter().filter(|w| **w >= REQUIRED_WINS).count() as u32;

        let mut stats = stats.lock().unwrap();
        stats.1 += 1;
        if new_updates > 0 {
            stats.0 += new_updates;
            println!("Updated! ({} updates in {} epochs)", stats.0, stats.1);
        }
        let epoch = stats.1;
        drop(stats);

        if new_updates > 0 {
            let mut coeffs_lock = coeffs.lock().unwrap();
            for i in 0..N_MUTATIONS {
                if total_wins[i] < REQUIRED_WINS {
                    continue;
                }
                let (coeff_idx, new_value) = mutations[i];
                if coeff_idx >= N_STENCIL_COEFFS {
                    coeffs_lock[coeff_idx] = new_value;
                } else {
                    coeffs_lock[STENCIL_INDICES[coeff_idx]] = new_value;
                    coeffs_lock[STENCIL_INDICES_SYM[coeff_idx]] = new_value;
                    coeffs_lock[STENCIL_INDICES_OPP[coeff_idx]] = -new_value;
                    coeffs_lock[STENCIL_INDICES_SYM_OPP[coeff_idx]] = -new_value;
                }
            }
            let coeffs_to_write = *coeffs_lock;
            drop(coeffs_lock);
            if let Err(err) = write_coeffs(&coeffs_to_write) {
                eprintln!("Failed to write coeffs to file {COEFFS_FILE}: `{err}`");
            }
        }

        if epoch.is_multiple_of(200) {
            let best_player = Player::Bot {
                bot: idabp,
                heuristic: Heuristic { fun: coeffistic, coeffs: Some(*coeffs.lock().unwrap()) },
            };
            let initial_player = Player::Bot {
                bot: idabp,
                heuristic: Heuristic { fun: coeffistic, coeffs: Some(initial_coeffs) },
            };
            let pairs = 50;
            let total_games = 2 * pairs;
            let wins_against_initial = play_pairs(pairs, &initial_player, &best_player, &mut rng);
            let wins_against_manual = play_pairs(pairs, &Player::MANUAL, &best_player, &mut rng);
            let dividing_line = "=".repeat(80);
            println!("{dividing_line}");
            println!("Current won {wins_against_initial}/{total_games} games against initial bot");
            println!("Current won {wins_against_manual}/{total_games} games against manual bot");
            println!("{dividing_line}");
        }
    });
}

fn random_coeff(rng: &mut ThreadRng, old_coeff: i64) -> i64 {
    let min_mul = (old_coeff as f64 * MIN_MULTIPLICATIVE_MUTATION).round() as i64;
    let max_mul = (old_coeff as f64 * MAX_MULTIPLICATIVE_MUTATION).round() as i64;
    let min_range =
        max(MIN_COEFF_VALUE, min(old_coeff - MAX_ADDITIVE_MUTATION, min(min_mul, max_mul)));
    let max_range =
        min(MAX_COEFF_VALUE, max(old_coeff + MAX_ADDITIVE_MUTATION, max(min_mul, max_mul)));

    // trick to avoid returning old_coeff
    let new_coeff = rng.gen_range(min_range..max_range);
    if new_coeff * old_coeff < 0 {
        0 // prefer setting to 0 than opposite sign to keep a parcimonious model
    } else if new_coeff >= old_coeff {
        new_coeff + 1
    } else {
        new_coeff
    }
}

fn play_pairs(pairs: usize, old_player: &Player, new_player: &Player, rng: &mut ThreadRng) -> u32 {
    std::iter::repeat_with(|| play_pair(old_player, new_player, rng)).take(pairs).sum()
}

fn play_pair(old_player: &Player, new_player: &Player, rng: &mut ThreadRng) -> u32 {
    let mut old_new = Game::new(old_player, new_player);
    let random_moves = rng.gen_range(3..=4);
    old_new.play_random_moves(random_moves, 5);

    let mut new_old = old_new.clone();
    (new_old.black_player, new_old.white_player) = (new_old.white_player, new_old.black_player);

    old_new.play_game();
    new_old.play_game();

    matches!(old_new.state, GameState::Won(PlayerColor::White, _)) as u32
        + matches!(new_old.state, GameState::Won(PlayerColor::Black, _)) as u32
}

fn write_coeffs(coeffs: &[i64; N_COEFFS]) -> io::Result<()> {
    let mut buf = BufWriter::with_capacity(1 << 15, Vec::new());
    writeln!(buf, "[")?;

    for i in 0..N_STENCIL_COEFFS {
        let c = coeffs[i];
        // TODO: check correct direction (might be symmetric)
        let pat: String = (0..6).map(|j| ['.', 'b', 'w'][i / 3usize.pow(j) % 3]).collect();
        let num = format!("{c},");
        writeln!(buf, "    {num:7}// {pat}")?;
    }

    for (i, poly_coeff) in
        ["ccc", "cc", "c", "ttt", "tt", "t", "ct", "cct", "ctt"].iter().enumerate()
    {
        let c = coeffs[N_STENCIL_COEFFS + i];
        let num = format!("{c},");
        writeln!(buf, "    {num:7}// {poly_coeff}")?;
    }

    writeln!(buf, "]")?;

    let mut file = File::create(COEFFS_FILE)?;
    file.write_all(buf.buffer())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn required_wins() {
        assert!(REQUIRED_WINS > 2u32.pow(N_MUTATIONS as u32 - 1));
        assert!(REQUIRED_WINS <= 2u32.pow(N_MUTATIONS as u32));
    }

    #[test]
    fn multiplicative_bias_towards_zero() {
        assert!(MIN_MULTIPLICATIVE_MUTATION > 0.);
        assert!(MIN_MULTIPLICATIVE_MUTATION < 1.);
        assert!(MAX_MULTIPLICATIVE_MUTATION > 1.);
        assert!(MAX_MULTIPLICATIVE_MUTATION < 2.);
        let mean = f64::midpoint(MIN_MULTIPLICATIVE_MUTATION, MAX_MULTIPLICATIVE_MUTATION);
        assert!(mean > 0.95);
        assert!(mean < 1.00);
    }
}
