[
    0,     // ......
    -4,    // b.....
    4,     // w.....
    -30,   // .b....
    50,    // bb....
    0,     // wb....
    30,    // .w....
    0,     // bw....
    -50,   // ww....
    34,    // ..b...
    0,     // b.b...
    73,    // w.b...
    -33,   // .bb...
    79,    // bbb...
    6,     // wbb...
    9,     // .wb...
    -67,   // bwb...
    14,    // wwb...
    -34,   // ..w...
    -73,   // b.w...
    0,     // w.w...
    -9,    // .bw...
    -14,   // bbw...
    67,    // wbw...
    33,    // .ww...
    -6,    // bww...
    -79,   // www...
    34,    // ...b..
    8,     // b..b..
    -97,   // w..b..
    3,     // .b.b..
    0,     // bb.b..
    0,     // wb.b..
    -39,   // .w.b..
    9,     // bw.b..
    -13,   // ww.b..
    44,    // ..bb..
    66,    // b.bb..
    65,    // w.bb..
    67,    // .bbb..
    79,    // bbbb..
    -25,   // wbbb..
    -35,   // .wbb..
    -24,   // bwbb..
    34,    // wwbb..
    0,     // ..wb..
    -30,   // b.wb..
    -48,   // w.wb..
    27,    // .bwb..
    43,    // bbwb..
    -85,   // wbwb..
    7,     // .wwb..
    -58,   // bwwb..
    -4,    // wwwb..
    -34,   // ...w..
    97,    // b..w..
    -8,    // w..w..
    39,    // .b.w..
    13,    // bb.w..
    -9,    // wb.w..
    -3,    // .w.w..
    0,     // bw.w..
    0,     // ww.w..
    0,     // ..bw..
    48,    // b.bw..
    30,    // w.bw..
    -7,    // .bbw..
    4,     // bbbw..
    58,    // wbbw..
    -27,   // .wbw..
    85,    // bwbw..
    -43,   // wwbw..
    -44,   // ..ww..
    -65,   // b.ww..
    -66,   // w.ww..
    35,    // .bww..
    -34,   // bbww..
    24,    // wbww..
    -67,   // .www..
    25,    // bwww..
    -79,   // wwww..
    -30,   // ....b.
    51,    // b...b.
    61,    // w...b.
    97,    // .b..b.
    8,     // bb..b.
    45,    // wb..b.
    0,     // .w..b.
    2,     // bw..b.
    -70,   // ww..b.
    3,     // ..b.b.
    0,     // b.b.b.
    -9,    // w.b.b.
    48,    // .bb.b.
    112,   // bbb.b.
    32,    // wbb.b.
    33,    // .wb.b.
    -17,   // bwb.b.
    -35,   // wwb.b.
    39,    // ..w.b.
    -42,   // b.w.b.
    0,     // w.w.b.
    11,    // .bw.b.
    19,    // bbw.b.
    51,    // wbw.b.
    29,    // .ww.b.
    19,    // bww.b.
    -20,   // www.b.
    -33,   // ...bb.
    181,   // b..bb.
    -7,    // w..bb.
    48,    // .b.bb.
    -41,   // bb.bb.
    -57,   // wb.bb.
    -29,   // .w.bb.
    -3,    // bw.bb.
    38,    // ww.bb.
    67,    // ..bbb.
    22,    // b.bbb.
    31,    // w.bbb.
    84,    // .bbbb.
    -46,   // bbbbb.
    80,    // wbbbb.
    -99,   // .wbbb.
    -118,  // bwbbb.
    -47,   // wwbbb.
    -7,    // ..wbb.
    0,     // b.wbb.
    0,     // w.wbb.
    -57,   // .bwbb.
    0,     // bbwbb.
    -21,   // wbwbb.
    0,     // .wwbb.
    11,    // bwwbb.
    0,     // wwwbb.
    -9,    // ...wb.
    -21,   // b..wb.
    6,     // w..wb.
    11,    // .b.wb.
    42,    // bb.wb.
    -25,   // wb.wb.
    -33,   // .w.wb.
    11,    // bw.wb.
    -43,   // ww.wb.
    27,    // ..bwb.
    -12,   // b.bwb.
    47,    // w.bwb.
    -57,   // .bbwb.
    19,    // bbbwb.
    -58,   // wbbwb.
    0,     // .wbwb.
    35,    // bwbwb.
    20,    // wwbwb.
    35,    // ..wwb.
    77,    // b.wwb.
    114,   // w.wwb.
    52,    // .bwwb.
    -17,   // bbwwb.
    0,     // wbwwb.
    99,    // .wwwb.
    50,    // bwwwb.
    42,    // wwwwb.
    30,    // ....w.
    -61,   // b...w.
    -51,   // w...w.
    0,     // .b..w.
    70,    // bb..w.
    -2,    // wb..w.
    -97,   // .w..w.
    -45,   // bw..w.
    -8,    // ww..w.
    -39,   // ..b.w.
    0,     // b.b.w.
    42,    // w.b.w.
    -29,   // .bb.w.
    20,    // bbb.w.
    -19,   // wbb.w.
    -11,   // .wb.w.
    -51,   // bwb.w.
    -19,   // wwb.w.
    -3,    // ..w.w.
    9,     // b.w.w.
    0,     // w.w.w.
    -33,   // .bw.w.
    35,    // bbw.w.
    17,    // wbw.w.
    -48,   // .ww.w.
    -32,   // bww.w.
    -112,  // www.w.
    9,     // ...bw.
    -6,    // b..bw.
    21,    // w..bw.
    33,    // .b.bw.
    43,    // bb.bw.
    -11,   // wb.bw.
    -11,   // .w.bw.
    25,    // bw.bw.
    -42,   // ww.bw.
    -35,   // ..bbw.
    -114,  // b.bbw.
    -77,   // w.bbw.
    -99,   // .bbbw.
    -42,   // bbbbw.
    -50,   // wbbbw.
    -52,   // .wbbw.
    0,     // bwbbw.
    17,    // wwbbw.
    -27,   // ..wbw.
    -47,   // b.wbw.
    12,    // w.wbw.
    0,     // .bwbw.
    -20,   // bbwbw.
    -35,   // wbwbw.
    57,    // .wwbw.
    58,    // bwwbw.
    -19,   // wwwbw.
    33,    // ...ww.
    7,     // b..ww.
    -181,  // w..ww.
    29,    // .b.ww.
    -38,   // bb.ww.
    3,     // wb.ww.
    -48,   // .w.ww.
    57,    // bw.ww.
    41,    // ww.ww.
    7,     // ..bww.
    0,     // b.bww.
    0,     // w.bww.
    0,     // .bbww.
    0,     // bbbww.
    -11,   // wbbww.
    57,    // .wbww.
    21,    // bwbww.
    0,     // wwbww.
    -67,   // ..www.
    -31,   // b.www.
    -22,   // w.www.
    99,    // .bwww.
    47,    // bbwww.
    118,   // wbwww.
    -84,   // .wwww.
    -80,   // bwwww.
    46,    // wwwww.
    -4,    // .....b
    -32,   // b....b
    0,     // w....b
    51,    // .b...b
    -49,   // bb...b
    67,    // wb...b
    -61,   // .w...b
    58,    // bw...b
    -17,   // ww...b
    8,     // ..b..b
    -63,   // b.b..b
    49,    // w.b..b
    181,   // .bb..b
    68,    // bbb..b
    34,    // wbb..b
    -6,    // .wb..b
    -6,    // bwb..b
    15,    // wwb..b
    97,    // ..w..b
    13,    // b.w..b
    32,    // w.w..b
    -21,   // .bw..b
    -33,   // bbw..b
    -10,   // wbw..b
    7,     // .ww..b
    -102,  // bww..b
    0,     // www..b
    0,     // ...b.b
    -63,   // b..b.b
    -32,   // w..b.b
    0,     // .b.b.b
    -6,    // bb.b.b
    43,    // wb.b.b
    0,     // .w.b.b
    -82,   // bw.b.b
    8,     // ww.b.b
    66,    // ..bb.b
    20,    // b.bb.b
    0,     // w.bb.b
    22,    // .bbb.b
    -37,   // bbbb.b
    29,    // wbbb.b
    -114,  // .wbb.b
    -113,  // bwbb.b
    39,    // wwbb.b
    48,    // ..wb.b
    61,    // b.wb.b
    0,     // w.wb.b
    -12,   // .bwb.b
    -32,   // bbwb.b
    -78,   // wbwb.b
    0,     // .wwb.b
    -57,   // bwwb.b
    -26,   // wwwb.b
    -73,   // ...w.b
    13,    // b..w.b
    -49,   // w..w.b
    -42,   // .b.w.b
    29,    // bb.w.b
    -34,   // wb.w.b
    9,     // .w.w.b
    -3,    // bw.w.b
    -21,   // ww.w.b
    -30,   // ..bw.b
    61,    // b.bw.b
    0,     // w.bw.b
    0,     // .bbw.b
    -24,   // bbbw.b
    35,    // wbbw.b
    -47,   // .wbw.b
    57,    // bwbw.b
    -50,   // wwbw.b
    -65,   // ..ww.b
    20,    // b.ww.b
    0,     // w.ww.b
    77,    // .bww.b
    -56,   // bbww.b
    16,    // wbww.b
    -31,   // .www.b
    48,    // bwww.b
    22,    // wwww.b
    50,    // ....bb
    -49,   // b...bb
    17,    // w...bb
    8,     // .b..bb
    11,    // bb..bb
    27,    // wb..bb
    70,    // .w..bb
    92,    // bw..bb
    0,     // ww..bb
    0,     // ..b.bb
    -6,    // b.b.bb
    21,    // w.b.bb
    -41,   // .bb.bb
    -7,    // bbb.bb
    25,    // wbb.bb
    43,    // .wb.bb
    -16,   // bwb.bb
    -23,   // wwb.bb
    13,    // ..w.bb
    29,    // b.w.bb
    -8,    // w.w.bb
    42,    // .bw.bb
    -59,   // bbw.bb
    -6,    // wbw.bb
    -38,   // .ww.bb
    12,    // bww.bb
    0,     // www.bb
    79,    // ...bbb
    68,    // b..bbb
    0,     // w..bbb
    112,   // .b.bbb
    -7,    // bb.bbb
    -25,   // wb.bbb
    20,    // .w.bbb
    -28,   // bw.bbb
    0,     // ww.bbb
    79,    // ..bbbb
    -37,   // b.bbbb
    -22,   // w.bbbb
    -46,   // .bbbbb
    36,    // bbbbbb
    -53,   // wbbbbb
    -42,   // .wbbbb
    -42,   // bwbbbb
    -42,   // wwbbbb
    4,     // ..wbbb
    -24,   // b.wbbb
    26,    // w.wbbb
    19,    // .bwbbb
    -50,   // bbwbbb
    -104,  // wbwbbb
    0,     // .wwbbb
    0,     // bwwbbb
    0,     // wwwbbb
    -14,   // ...wbb
    -33,   // b..wbb
    -15,   // w..wbb
    19,    // .b.wbb
    -59,   // bb.wbb
    -43,   // wb.wbb
    35,    // .w.wbb
    -51,   // bw.wbb
    23,    // ww.wbb
    43,    // ..bwbb
    -32,   // b.bwbb
    50,    // w.bwbb
    0,     // .bbwbb
    -50,   // bbbwbb
    0,     // wbbwbb
    -20,   // .wbwbb
    -41,   // bwbwbb
    0,     // wwbwbb
    -34,   // ..wwbb
    -56,   // b.wwbb
    -39,   // w.wwbb
    -17,   // .bwwbb
    -62,   // bbwwbb
    -66,   // wbwwbb
    47,    // .wwwbb
    90,    // bwwwbb
    42,    // wwwwbb
    0,     // ....wb
    58,    // b...wb
    -67,   // w...wb
    2,     // .b..wb
    92,    // bb..wb
    0,     // wb..wb
    -45,   // .w..wb
    -44,   // bw..wb
    -27,   // ww..wb
    9,     // ..b.wb
    -82,   // b.b.wb
    34,    // w.b.wb
    -3,    // .bb.wb
    -28,   // bbb.wb
    55,    // wbb.wb
    25,    // .wb.wb
    -39,   // bwb.wb
    43,    // wwb.wb
    0,     // ..w.wb
    -3,    // b.w.wb
    -43,   // w.w.wb
    11,    // .bw.wb
    -51,   // bbw.wb
    52,    // wbw.wb
    57,    // .ww.wb
    -101,  // bww.wb
    25,    // www.wb
    -67,   // ...bwb
    -6,    // b..bwb
    10,    // w..bwb
    -17,   // .b.bwb
    -16,   // bb.bwb
    -52,   // wb.bwb
    -51,   // .w.bwb
    -39,   // bw.bwb
    6,     // ww.bwb
    -24,   // ..bbwb
    -113,  // b.bbwb
    -16,   // w.bbwb
    -118,  // .bbbwb
    -42,   // bbbbwb
    -107,  // wbbbwb
    0,     // .wbbwb
    -6,    // bwbbwb
    66,    // wwbbwb
    85,    // ..wbwb
    57,    // b.wbwb
    78,    // w.wbwb
    35,    // .bwbwb
    -41,   // bbwbwb
    0,     // wbwbwb
    21,    // .wwbwb
    1,     // bwwbwb
    104,   // wwwbwb
    -6,    // ...wwb
    -102,  // b..wwb
    -34,   // w..wwb
    19,    // .b.wwb
    12,    // bb.wwb
    -55,   // wb.wwb
    -32,   // .w.wwb
    -101,  // bw.wwb
    -25,   // ww.wwb
    -58,   // ..bwwb
    -57,   // b.bwwb
    -35,   // w.bwwb
    11,    // .bbwwb
    0,     // bbbwwb
    0,     // wbbwwb
    58,    // .wbwwb
    1,     // bwbwwb
    0,     // wwbwwb
    25,    // ..wwwb
    48,    // b.wwwb
    -29,   // w.wwwb
    50,    // .bwwwb
    90,    // bbwwwb
    107,   // wbwwwb
    -80,   // .wwwwb
    -48,   // bwwwwb
    53,    // wwwwwb
    4,     // .....w
    0,     // b....w
    32,    // w....w
    61,    // .b...w
    17,    // bb...w
    -58,   // wb...w
    -51,   // .w...w
    -67,   // bw...w
    49,    // ww...w
    -97,   // ..b..w
    -32,   // b.b..w
    -13,   // w.b..w
    -7,    // .bb..w
    0,     // bbb..w
    102,   // wbb..w
    21,    // .wb..w
    10,    // bwb..w
    33,    // wwb..w
    -8,    // ..w..w
    -49,   // b.w..w
    63,    // w.w..w
    6,     // .bw..w
    -15,   // bbw..w
    6,     // wbw..w
    -181,  // .ww..w
    -34,   // bww..w
    -68,   // www..w
    73,    // ...b.w
    49,    // b..b.w
    -13,   // w..b.w
    -9,    // .b.b.w
    21,    // bb.b.w
    3,     // wb.b.w
    42,    // .w.b.w
    34,    // bw.b.w
    -29,   // ww.b.w
    65,    // ..bb.w
    0,     // b.bb.w
    -20,   // w.bb.w
    31,    // .bbb.w
    -22,   // bbbb.w
    -48,   // wbbb.w
    -77,   // .wbb.w
    -16,   // bwbb.w
    56,    // wwbb.w
    30,    // ..wb.w
    0,     // b.wb.w
    -61,   // w.wb.w
    47,    // .bwb.w
    50,    // bbwb.w
    -57,   // wbwb.w
    0,     // .wwb.w
    -35,   // bwwb.w
    24,    // wwwb.w
    0,     // ...w.w
    32,    // b..w.w
    63,    // w..w.w
    0,     // .b.w.w
    -8,    // bb.w.w
    82,    // wb.w.w
    0,     // .w.w.w
    -43,   // bw.w.w
    6,     // ww.w.w
    -48,   // ..bw.w
    0,     // b.bw.w
    -61,   // w.bw.w
    0,     // .bbw.w
    26,    // bbbw.w
    57,    // wbbw.w
    12,    // .wbw.w
    78,    // bwbw.w
    32,    // wwbw.w
    -66,   // ..ww.w
    0,     // b.ww.w
    -20,   // w.ww.w
    114,   // .bww.w
    -39,   // bbww.w
    113,   // wbww.w
    -22,   // .www.w
    -29,   // bwww.w
    37,    // wwww.w
    0,     // ....bw
    67,    // b...bw
    -58,   // w...bw
    45,    // .b..bw
    27,    // bb..bw
    44,    // wb..bw
    -2,    // .w..bw
    0,     // bw..bw
    -92,   // ww..bw
    0,     // ..b.bw
    43,    // b.b.bw
    3,     // w.b.bw
    -57,   // .bb.bw
    -25,   // bbb.bw
    101,   // wbb.bw
    -11,   // .wb.bw
    -52,   // bwb.bw
    51,    // wwb.bw
    -9,    // ..w.bw
    -34,   // b.w.bw
    82,    // w.w.bw
    -25,   // .bw.bw
    -43,   // bbw.bw
    39,    // wbw.bw
    3,     // .ww.bw
    -55,   // bww.bw
    28,    // www.bw
    6,     // ...bbw
    34,    // b..bbw
    102,   // w..bbw
    32,    // .b.bbw
    25,    // bb.bbw
    101,   // wb.bbw
    -19,   // .w.bbw
    55,    // bw.bbw
    -12,   // ww.bbw
    -25,   // ..bbbw
    29,    // b.bbbw
    -48,   // w.bbbw
    80,    // .bbbbw
    -53,   // bbbbbw
    48,    // wbbbbw
    -50,   // .wbbbw
    -107,  // bwbbbw
    -90,   // wwbbbw
    58,    // ..wbbw
    35,    // b.wbbw
    57,    // w.wbbw
    -58,   // .bwbbw
    0,     // bbwbbw
    -1,    // wbwbbw
    -11,   // .wwbbw
    0,     // bwwbbw
    0,     // wwwbbw
    67,    // ...wbw
    -10,   // b..wbw
    6,     // w..wbw
    51,    // .b.wbw
    -6,    // bb.wbw
    39,    // wb.wbw
    17,    // .w.wbw
    52,    // bw.wbw
    16,    // ww.wbw
    -85,   // ..bwbw
    -78,   // b.bwbw
    -57,   // w.bwbw
    -21,   // .bbwbw
    -104,  // bbbwbw
    -1,    // wbbwbw
    -35,   // .wbwbw
    0,     // bwbwbw
    41,    // wwbwbw
    24,    // ..wwbw
    16,    // b.wwbw
    113,   // w.wwbw
    0,     // .bwwbw
    -66,   // bbwwbw
    6,     // wbwwbw
    118,   // .wwwbw
    107,   // bwwwbw
    42,    // wwwwbw
    -50,   // ....ww
    -17,   // b...ww
    49,    // w...ww
    -70,   // .b..ww
    0,     // bb..ww
    -92,   // wb..ww
    -8,    // .w..ww
    -27,   // bw..ww
    -11,   // ww..ww
    -13,   // ..b.ww
    8,     // b.b.ww
    -29,   // w.b.ww
    38,    // .bb.ww
    0,     // bbb.ww
    -12,   // wbb.ww
    -42,   // .wb.ww
    6,     // bwb.ww
    59,    // wwb.ww
    0,     // ..w.ww
    -21,   // b.w.ww
    6,     // w.w.ww
    -43,   // .bw.ww
    23,    // bbw.ww
    16,    // wbw.ww
    41,    // .ww.ww
    -25,   // bww.ww
    7,     // www.ww
    14,    // ...bww
    15,    // b..bww
    33,    // w..bww
    -35,   // .b.bww
    -23,   // bb.bww
    51,    // wb.bww
    -19,   // .w.bww
    43,    // bw.bww
    59,    // ww.bww
    34,    // ..bbww
    39,    // b.bbww
    56,    // w.bbww
    -47,   // .bbbww
    -42,   // bbbbww
    -90,   // wbbbww
    17,    // .wbbww
    66,    // bwbbww
    62,    // wwbbww
    -43,   // ..wbww
    -50,   // b.wbww
    32,    // w.wbww
    20,    // .bwbww
    0,     // bbwbww
    41,    // wbwbww
    0,     // .wwbww
    0,     // bwwbww
    50,    // wwwbww
    -79,   // ...www
    0,     // b..www
    -68,   // w..www
    -20,   // .b.www
    0,     // bb.www
    28,    // wb.www
    -112,  // .w.www
    25,    // bw.www
    7,     // ww.www
    -4,    // ..bwww
    -26,   // b.bwww
    24,    // w.bwww
    0,     // .bbwww
    0,     // bbbwww
    0,     // wbbwww
    -19,   // .wbwww
    104,   // bwbwww
    50,    // wwbwww
    -79,   // ..wwww
    22,    // b.wwww
    37,    // w.wwww
    42,    // .bwwww
    42,    // bbwwww
    42,    // wbwwww
    46,    // .wwwww
    53,    // bwwwww
    -36,   // wwwwww
    116,   // ccc
    67,    // cc
    79,    // c
    9,     // ttt
    0,     // tt
    246,   // t
    38,    // ct
    0,     // cct
    41,    // ctt
]
